### ISSUE TITLE
生成错误?

### ISSUE THREAD

**Issue by blankhang** [baomidou/mybatis-plus#10]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.blank.mapper.UserMapper">

	
	<sql id="Base_Column_List">
		user_id AS userId, user_name AS userName, user_password AS userPassword, create_time AS createTime, update_time AS updateTime, `status`
	</sql>

</mapper>

生成出来的就这????
另外 为什么不能指定 WINDOWS上的 生成文件位置啊 我指定 D:\JAVA 结果 controller跑到D了....

**Comment by qmdx** [comment]
mp 基础方法都注入了，所有生成的文件都是基础文件只有少量可能用到的内容。 D:\\ 试试

**Comment by blankhang** [comment]
不是啊...少量可用 你也得有 基本的 增删改查吧....这个生成出来 不能 只有一句 base_column_list 吧...

**Comment by yangyang0507** [comment]
看来你还没有明白MP的真谛，xml就是这样，因为基本的CRUD在MP启动的时候注入了，如果你不需要复杂业务，你甚至可以不要xml。

**Comment by yangyang0507** [comment]
生成的东西中CRUD的方法都有的，如果不懂，看看文档 http://mp.baomidou.com/

**Comment by blankhang** [comment]
哦..谢谢 我是先看了文档 然后再操作的.....

D.Yang <notifications@github.com>于2016年11月11日周五 上午11:19写道：
