### ISSUE TITLE
updateFill不能被调用

### ISSUE THREAD

**Issue by carrot1991** [baomidou/mybatis-plus#100]
自定义MetaObjectHandler，updateFill不能被调用，insertFill调用正常，版本号：2.1-gamma

**Comment by carrot1991** [comment]
目前项目有个需求，需要在更新数据时，自动更新时间戳，但是数据库的列类型还不是timestamp，可否依赖当前框架完成？

**Comment by carrot1991** [comment]
查看源码后，原因是我在调用updateById时，更新参数识别为HashMap，取不到tableInfo，我使用update更新则updateFill生效，望尽快解决updateById时updateFill无法调用的问题。

**Comment by yuxiaobin** [comment]
最新代码已修复此问题。

**Comment by qmdx** [comment]
请使用 dev 分支试试如果不能满足，打开该 issue
