### ISSUE TITLE
PerformanceInterceptor 导致无法insert

### ISSUE THREAD

**Issue by xiaozhaoosc** [baomidou/mybatis-plus#1000]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.4

### 该问题是怎么引起的？
启用性能分析插件

### 重现步骤
 /**
     * 启用性能分析插件
     * @return
     */
    @Bean
    public PerformanceInterceptor performanceInterceptor(){
        //启用性能分析插件
        return new PerformanceInterceptor();
    }

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'delegate' in 'class com.sun.proxy.$Proxy145'

**Comment by miemieYaho** [comment]
用最新版,还有错自己排查,这是反射异常
