### ISSUE TITLE
mybatis plus 对于多对多的第三张表的插入有何解决方法

### ISSUE THREAD

**Issue by jwf1173** [baomidou/mybatis-plus#1005]
多对多的情况下，mybatis plus 是如何实现更方便往第三张表插入值呢
例如 有用户表，权限表，用户权限表，当新增用户时，有两个权限，怎么同时往用户权限表插入用户和权限的关系呢？

**Comment by qmdx** [comment]
调用对应表的插入方法插入，没有hibernate那种关联自动插入功能
