### ISSUE TITLE
逻辑删除时，是否支持set 另外的字段？

### ISSUE THREAD

**Issue by InspireYi** [baomidou/mybatis-plus#1006]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
表字段 isdelete ， deleteUserId
如果我在软删除数据时，mybatis plus现有控件，是否支持以下语句？
update table set isdelete = 1 ， deleteUserId = '' where id = xxx and isdelete =0
### 重现步骤
使用deleteByIdWithFill方法不支持
请问要如何实现？

### 报错信息
无报错信息
实际语句为
update table set isdelete = 1  where id = xxx and isdelete =0

**Comment by miemieYaho** [comment]
不支持,使用 update 自己在 updatewrapper.set 里设置

**Comment by InspireYi** [comment]
如果使用update方法，由于逻辑删除字段使用了注解@TableLogic
那么生成的sql语句是不带isdelete字段的。。。

**Comment by miemieYaho** [comment]
updatewrapper.set("isdelete",1).set("deleteUserId",xxx).eq(id,xxx)

**Comment by InspireYi** [comment]
好的，想了解一下逻辑删除不支持set其他字段是出于什么原因，感觉这种情况很常见吧？
