### ISSUE TITLE
EntityWrapper这个类为什么没有了？

### ISSUE THREAD

**Issue by jwf1173** [baomidou/mybatis-plus#1007]
EntityWrapper这个类为什么没有了？

**Comment by qmdx** [comment]
3.X 重构拆分为 queryWrapper updateWrapper

**Comment by jwf1173** [comment]
> 3.X 重构拆分为 queryWrapper updateWrapper

那 ew.sqlSegment还能用吗

**Comment by qmdx** [comment]
> > 3.X 重构拆分为 queryWrapper updateWrapper
> 
> 那 ew.sqlSegment还能用吗

look docs or resource
