### ISSUE TITLE
关于queryWrapper 的 sqlSegment

### ISSUE THREAD

**Issue by jwf1173** [baomidou/mybatis-plus#1008]
Page<User> queryTest(Page<User> page, @Param("ew") QueryWrapper queryWrapper);
```
<select id="queryTest" resultType="com.loksail.modules.system.entity.User">
        select *
        from user
      <where>
          #{ew.sqlSegment}
      </where>
</select>
```

sql 输出
select * from user WHERE 'id = #{ew.paramNameValuePairs.MPGENVAL1}' 

请问现在3.1.0版本的sqlSegment怎么用的呢

**Comment by luluAndXiaofei** [comment]
请问楼主知道解决方法了吗
