### ISSUE TITLE
用传统的maven打包，定义的通用枚举就会失效。

### ISSUE THREAD

**Issue by cptjackwu** [baomidou/mybatis-plus#1009]
### 当前使用版本(必须填写清楚，否则不予处理)
  <mybatis.plus.boot.starter.version>3.1.0</mybatis.plus.boot.starter.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

就是我没有采用如下的打包导入的问题
 <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
而是采用了传统的maven打包，
  <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
 <artifactId>maven-assembly-plugin</artifactId>
                <version>2.6</version>
等，将项目依赖的包单独打出来，以及一些需要的文件。
就是由于这种打包方式，我定义的通用枚举
public enum  UserTypeEnum implements IEnum<Integer> {

    COMMONMEN(0,"普通用户"),

    SUPERMEN(1,"管理员");

    public int value;

    public String desc;

    UserTypeEnum(int value, String desc) {
        this.value = value;
        this.desc = desc;
    }

    @Override
    public Integer getValue() {
        return value;
    }

    @JsonValue
    public String getDesc() {
        return desc;
    }

}

配置文件：
type-enums-package: com.crown.enums
default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

以及实体类中：
    @TableField("UserType")
    private UserTypeEnum userType;

失效了打包运行就失效了，而不打包运行就没有问题
### 报错信息
没有报错信息，就是赋值失效了，返回到前端的时候这个userType就是空的，不打包运行是没有问题，正常显示，maven插件（是将依赖包单独打出来的方式maven-jar-plugin）打包运行就有问题，而如果使用springboot提供的spring-boot-maven-plugin插件打包也没有问题。

**Comment by cptjackwu** [comment]
希望你们强大的团队帮我解决这个问题

**Comment by cptjackwu** [comment]
希望你们能帮我看一下

**Comment by qmdx** [comment]
查看下是否失败的打包方式文件正确存放，枚举扫描正确， 也不必纠结 spring-boot-maven-plugin 这个好使就用这个了

**Comment by cptjackwu** [comment]
我打包没有失败，项目还是正常跑，暂时我就先不用那个通用枚举的功能。不是纠结spring-boot-maven-plugin这个好使，只是打包的文件有点大，所以就想依赖的包单独打出来，每次上传的时候就传项目的包也就很小了。然后就是这样的想法。刚好在进行项目测试一个模块的时候突然才发现通用枚举失效了。

**Comment by cptjackwu** [comment]
> 查看下是否失败的打包方式文件正确存放，枚举扫描正确， 也不必纠结 spring-boot-maven-plugin 这个好使就用这个了

我打包没有失败，项目还是正常跑，暂时我就先不用那个通用枚举的功能。不是纠结spring-boot-maven-plugin这个好使，只是打包的文件有点大，所以就想依赖的包单独打出来，每次上传的时候就传项目的包也就很小了。然后就是这样的想法。刚好在进行项目测试一个模块的时候突然才发现通用枚举失效了。
