### ISSUE TITLE
主键策略采用 ID_WORKER 时可不可以自动设置入 String 类型的 id 中呢？

### ISSUE THREAD

**Issue by lg-Cat73** [baomidou/mybatis-plus#101]
目前的项目希望主键为一串唯一的数字，但不能用 long 类型，因为把 long 传给前段会因为浮点数不精准的问题导致在前段没法用这个 id。
于是解决方案是转为字符串后给前段。
那么有两个方案可以解决这个问题：
1. 在数据给前端接口之前先转为 String，接收时再转换回 Long
2. 数据库里存 char，然后采用自己设置 ID 的方式，自己用 String.valueOf(IdWorker.getId()) 来设置主键的值。

感觉这两个方案都挺麻烦的，能否让 ID_WORKER 在往 id 中注入值之前检查一下数据类型来支持 String 呢？

**Comment by Caratacus** [comment]
查看 [mp.baomidou.com](mp.baomidou.com) 有答案
