### ISSUE TITLE
多表关联删除sql解析错误

### ISSUE THREAD

**Issue by dinghuang** [baomidou/mybatis-plus#1010]
### 当前使用版本(必须填写清楚，否则不予处理)

<mybatis-plus-boot-starter>3.1.0</mybatis-plus-boot-starter>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

想要写一个多表关联删除的xml定义的sql，发现sql没问题，但是解析出来的sql有问题，解析的sql把2个表直接的逗号拼接起来了，导致表找不到。

### 重现步骤
mapper.xml定义的sql：
`<delete id="deleteByBlockNumAndPreselection">
        DELETE
            hou_house_park_con,
            hou_house_park
        FROM
            hou_house_park_con,
            hou_house_park
        WHERE
            hou_house_park_con.id = hou_house_park.park_con_id
        AND hou_house_park_con.block_num = #{blockNum}
        AND hou_house_park_con.is_preselection =
        <choose>
            <when test="preselection">
                "1"
            </when>
            <otherwise>
                "0"
            </otherwise>
        </choose>
    </delete>`

### 报错信息

`Creating a new SqlSession
Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@18de5d07]
JDBC Connection [ProxyConnection[PooledConnection[com.mysql.cj.jdbc.ConnectionImpl@4ae4996c]]] will be managed by Spring
Original SQL: DELETE
            hou_house_park_con,
            hou_house_park
        FROM
            hou_house_park_con,
            hou_house_park
        WHERE
            hou_house_park_con.id = hou_house_park.park_con_id
        AND hou_house_park_con.block_num = ?
        AND hou_house_park_con.is_preselection =
         
                "0"
parser sql: DELETE hou_house_park_conhou_house_park FROM hou_house_park_con, hou_house_park WHERE hou_house_park_con.id = hou_house_park.park_con_id AND hou_house_park_con.block_num = ? AND hou_house_park_con.is_preselection = "0"
==>  Preparing: DELETE hou_house_park_conhou_house_park FROM hou_house_park_con, hou_house_park WHERE hou_house_park_con.id = hou_house_park.park_con_id AND hou_house_park_con.block_num = ? AND hou_house_park_con.is_preselection = "0" 
==> Parameters: ECD02030601(String)
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@18de5d07]
2019-04-10 15:23:13.148  INFO 24631 --- [nio-8072-exec-1] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2019-04-10 15:23:13.176  INFO 24631 --- [nio-8072-exec-1] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@18de5d07]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@18de5d07]
2019-04-10 15:23:13.331 ERROR 24631 --- [nio-8072-exec-1] .c.s.f.c.ExceptionInterceptConfiguration : execute database exception{}

org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Unknown table 'hou_house_park_conhou_house_park' in MULTI DELETE
`

**Comment by miemieYaho** [comment]
有用什么插件吗?

**Comment by dinghuang** [comment]
数据库这块没有用别的插件

**Comment by dinghuang** [comment]
![image](https://user-images.githubusercontent.com/20722776/55876466-4d4e2880-5bca-11e9-9c2e-bce2091df1c8.png)

**Comment by miemieYaho** [comment]
我指的mp提供的插件,你这是jsqlparser解析错误,说明它不支持你这种sql,非必要的插件能不用就不用,要么你就写标准的sql

**Comment by dinghuang** [comment]
嗯，好的，那就是jsqlparser解析错误，那我以后注意下sql的标准，谢啦，你可以把问题关闭了
