### ISSUE TITLE
updateBatchById 批量更新报错

### ISSUE THREAD

**Issue by yuxishua** [baomidou/mybatis-plus#1012]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
以常见的商品功能为例：
ProductService 继承  ServiceImpl<ProductMapper, Product>
ProductMapper 继承BaseMapper<Product>
Product 就是商品实体类

### 重现步骤
ProductServiceImpl productService = new ProductServiceImpl ();
productService.updateBatchById(productList),就会报错，
 `Parameter Param1 key not found. Available parameters are [et]`

### 报错信息
![image](https://user-images.githubusercontent.com/7563822/55950855-72a16c00-5c88-11e9-96d5-618410e4246c.png)

**Comment by miemieYaho** [comment]
自行检查,entity是否把主键进行了注解,service组件是用来注入到spring容器里的

**Comment by czjiang007** [comment]
请问这个问题是如何解决的

**Comment by zhaowenzhe** [comment]
请问如何解决，我也遇到同样问题

**Comment by nadirvishun** [comment]
同遇到过此问题，后来是发现自定义的自动更新创建人和时间的一个拦截器中，更新判定有问题，修改后就好了。

**Comment by huhan-123** [comment]
请问是如何解决该问题的呢

**Comment by bieshuohua** [comment]
v3.0.6小版本更新至v3.0.7.1可解决

**Comment by bieshuohua** [comment]
https://github.com/zhangdaiscott/jeecg-boot/blob/master/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/config/mybatis/MybatisInterceptor.java
116-128行
