### ISSUE TITLE
OptimisticLockerInterceptor 乐观锁插件优化建议

### ISSUE THREAD

**Issue by jinliang123** [baomidou/mybatis-plus#1013]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.0</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
乐观锁更新失败，没有任何提示信息，打印sql才发现是因为版本号不对。
==>  Preparing: UPDATE user SET name=?, version=? WHERE id=? AND version=? 
==> Parameters: kitty123(String), 3(Integer), 6(Long), 2(Integer)
<==    Updates: 0

###建议
建议拦截器里面加个异常信息吧，这样更通用，不然每次更新还需要自己去校验是否更新成功。望采纳

**Comment by miemieYaho** [comment]
这种你应该自己判断,再自己抛出自己的异常

**Comment by NameNull** [comment]
对呀 你们应该做个更新失败抛出乐观锁异常的东西，免得我代码里边都是手动throw RuntimeException... 只要配置了乐观锁，就应该开启这么个东西。

**Comment by NameNull** [comment]
类似于hibrenate的
