### ISSUE TITLE
IDEA 启动项目 Mapper 注入失败，不正确的 baseMapper 依赖

### ISSUE THREAD

**Issue by lemoncy** [baomidou/mybatis-plus#1015]
### 当前使用版本(必须填写清楚，否则不予处理)
Spring Boot v2.1.3.RELEASE, Spring v5.1.5.RELEASE, JAVA 1.8
Mybatis-Plus  3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
搭建SSM工程，所有包依赖包已导入，正常启动。
加入Controller、Service、Mapper（名称改为Dao）
找到一个解决办法：dao增加@Mapper 。可是我本身就已经添加了，
一直提示 **baseMapper** 的问题，麻烦哪位大佬能改释一下
`Unsatisfied dependency expressed through field 'baseMapper'` 
https://blog.csdn.net/weixin_43171019/article/details/88074536

### 1、Controller
`@RestController
@RequestMapping("/sys/user")
public class SysUserInfoController {
    @Autowired
    private SysUserInfoService sysUserInfoService;
    。。。`

**2、Service**
`
@Service("sysUserInfoService")
public class SysUserInfoServiceImpl extends ServiceImpl<SysUserInfoDao, SysUserInfo> implements SysUserInfoService {
    @Autowired
    private SysUserInfoDao sysUserInfoDao;
    。。。`

**3、Mapper**

`@Mapper 
public interface SysUserInfoDao extends BaseMapper<SysUserInfo>{ 
   。。。`

### 重现步骤
IDEA 运行项目一直报错，信息如下

### 报错信息
`org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'sysUserInfoController': 
Unsatisfied dependency expressed through field 'sysUserInfoService'; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'sysUserInfoService': Unsatisfied dependency expressed through field 'baseMapper'; 
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type 'com.mgit.hms.modules.sys.dao.SysUserInfoDao' available: 
expected at least 1 bean which qualifies as autowire candidate. Dependency annotations:
{@org.springframework.beans.factory.annotation.Autowired(required=true)}`

**Comment by miemieYaho** [comment]
去看samples

**Comment by lemoncy** [comment]
@miemieYaho 大佬，是可以不继承么BaseMapper    samples描述的是/可以继承或者不继承BaseMapper。
那如果我继承了BaseMapper报错。是包的问题吗？

**Comment by miemieYaho** [comment]
不继承就没有basemapper的方法,就不能用mp提供的service,自己对照samples检查你的项目

**Comment by lemoncy** [comment]
@miemieYaho 好的，多谢。我再检查下。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
