### ISSUE TITLE
update和insert时忽略updateTime和createTime字段

### ISSUE THREAD

**Issue by liunewshine** [baomidou/mybatis-plus#1017]
### 当前使用版本
3.1.0

### update和insert时强制忽略字段
我们系统要求createTime和updateTime都是数据库自己处理，代码里面不能显式的插入或者更新这个两个字段，怎么拦截这两个字段并且删除。
以下两个方法都尝试了，都不行
![image](https://user-images.githubusercontent.com/7698511/56077544-2c771480-5e10-11e9-8654-c0b2083a4665.png)
![image](https://user-images.githubusercontent.com/7698511/56077563-503a5a80-5e10-11e9-93ee-5fefc61bfc27.png)

**Comment by miemieYaho** [comment]
查看 setFieldValByName 源码自己复制一份去除非null判断
