### ISSUE TITLE
如何关闭generator mapper文件生成

### ISSUE THREAD

**Issue by ESHidden** [baomidou/mybatis-plus#1018]
版本：3.1

我自定义输出位置可以实现，但是原来位置的xml 文件还是生成了，自定义配置并没有覆盖原有配置，结果就在全局配置和自定义配置中各生成了一份mapper.xml文件，
问题1：如何关闭mapper.xml输出或者完全覆盖全局配置？

### 重现步骤
如下配置
![image](https://user-images.githubusercontent.com/28656389/56093069-b7323f00-5ef6-11e9-9add-e80d0d1b66b2.png)

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html
