### ISSUE TITLE
LambdaQueryWrapper报错 MybatisPlusException: cannot find column's cache 

### ISSUE THREAD

**Issue by winneryong** [baomidou/mybatis-plus#1019]
### 当前使用版本(必须填写清楚，否则不予处理)
MP版本：3.1.0
IDE：IDEA 2018.3
JDK：OracleJDK 1.8.0_201-b09

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在Service中引入两个mapper, 第2个mapper执行list时报“cannot find column's cache”

### 重现步骤
![Snipaste_2019-04-15_15-27-20](https://user-images.githubusercontent.com/665637/56115081-28283400-5f95-11e9-80ce-d656033bfe0e.png)
[ProvinceDataIssueServiceImpl.txt](https://github.com/baomidou/mybatis-plus/files/3078914/ProvinceDataIssueServiceImpl.txt)

### 报错信息
MybatisPlusException: cannot find column's cache for "com.xxxx.data.sync.service.communication.impl.ProvinceDataIssueServiceImpl", so you cannot used "class com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper"!

**Comment by winneryong** [comment]
IDEA 编译级别 
Language level: 8 - Lambdas, type annotations etc.

**Comment by miemieYaho** [comment]
使用不当,自己排查

**Comment by winneryong** [comment]
把jdk降级到 1.8.0_112 没有出现此异常。
@miemieYaho

**Comment by winneryong** [comment]
哪里使用不当了？还请指教

**Comment by winneryong** [comment]
在1.8.0_201-b09版本的jdk中，使用以下语法创建QueryWrapper，一样的错误。
new QueryWrapper().lambda()

**Comment by winneryong** [comment]
刚才我代码没有改，将 112版本jdk切换成201版本，又不出现此异常了，这么奇怪。。。

**Comment by winneryong** [comment]
我这里再也无法复现此问题，多谢。
