### ISSUE TITLE
user.insert() 不正确， userService.insert(user) 正确；

### ISSUE THREAD

**Issue by eastxiang** [baomidou/mybatis-plus#102]
版本：2.1-gamma
问题：
    1. 单元测试时，表先初始化3条记录；
    2. 如果在setUp中 使用 initCount = 3; testInsert 使用 user.insert() 测试通过；使用 userService.insert(user); 测试通过；
   3.如果在setUp中 使用  initCount = userService.selectCount(null); testInsert 使用 user.insert() 测试不同通过；使用 userService.insert(user); 测试通过；
   不通过原因 int count = userService.selectCount(null); 返回 3，应该返回23；
 

`@Before
public void setUp() {

    //initCount = 3;
    initCount = userService.selectCount(null);
}
@Test
public void testInsert() {

    int total = 20;
    for (int i = 0; i < total; i++) {
        User user = enhancedRandom.nextObject(User.class);
        //user.insert();
        userService.insert(user);
    }
    int count = userService.selectCount(null);
    // 加初始化插入3条
    total = total + initCount;
    assertThat(count).isEqualTo(total);
}`

**Comment by Caratacus** [comment]
查询事务操作是否正确

**Comment by eastxiang** [comment]
Spring 事务

**Comment by eastxiang** [comment]
可能是mybatis 一级缓冲影响。
