### ISSUE TITLE
同一事务中批量插入后读未提交数据问题

### ISSUE THREAD

**Issue by junit** [baomidou/mybatis-plus#1021]
### 问题描述
在同一事务中作批量插入，事务未提交前无法查询刚刚批量的插入数据。
注：通过单条循环插入的方式可以查询到。

### 日志信息
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e59efcd]
**Fetched SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e59efcd] from current transaction**
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e59efcd]
Transaction synchronization committing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e59efcd]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e59efcd]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2e59efcd]

日志中可以看到Fetched SqlSession之后并没有执行任何SQL。

**Comment by miemieYaho** [comment]
批量插入用的 sqlsession 不是同一个,是单独开出来的,不然无法进行批量插入
