### ISSUE TITLE
自定义的TypeHandle无效

### ISSUE THREAD

**Issue by lyingfromyou** [baomidou/mybatis-plus#1022]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

实体中有个字段类型是 List<String>，保存在数据库是varchar，用逗号分隔，所以我自定义了一个typeHandle，我的Service 继承了IService ，在调用IService中的save方法时，可以执行自定义的typeHandle, 但是在 updateById 或者 saveOrUpdate方法时无效

### 报错信息

![image](https://user-images.githubusercontent.com/24619864/56181866-fb7e2600-6041-11e9-803e-4b1eeaa4af69.png)
![image](https://user-images.githubusercontent.com/24619864/56181881-105ab980-6042-11e9-80e5-a2ae8fb59425.png)

**Comment by miemieYaho** [comment]
#794
