### ISSUE TITLE
condition 只有第一个有效

### ISSUE THREAD

**Issue by jiushizyj** [baomidou/mybatis-plus#1025]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？
QueryWrapper boolean condition 参数 多个参数时只有第一参数的有效并且后面的参数会跟随第一个的设置，例如
QueryWrapper<SystemInfo> queryWrapper=new QueryWrapper<>();
queryWrapper.like(true,"xxx", "xxx");
这一个参数也会被加上，如果前面的为false 后面的为true 后面的 也不会加上执行
queryWrapper.like(false,"xxx", "xxx");

### 报错信息
无报错信息

**Comment by miemieYaho** [comment]
就是这样的,类比 xml 里的 if 标签
