### ISSUE TITLE
关于使用IPage接收Mapper接口返回值的疑问

### ISSUE THREAD

**Issue by qiweibo** [baomidou/mybatis-plus#1028]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0版本。
在使用IPage接收dao层中的Mapper接口方法返回值时，如果mapper映射文件里写的resultType类型与IPage<>接收时的泛型类型不一致，后台为啥不会报错呢，IPage里是否进行了类型的转换？

**Comment by miemieYaho** [comment]
没有也不会去判断是否泛型一致
