### ISSUE TITLE
使用2.1-gamma代码生成器 逻辑删除字段 问题

### ISSUE THREAD

**Issue by wuym2008** [baomidou/mybatis-plus#103]
使用2.1-gamma代码生成器，设置了逻辑删除字段：
        strategy.setLogicDeleteFieldName("deleted");

生成后，Entity的逻辑删除字段没有@TableLogic 注解。

public class StrategyConfig {
    ....
    public StrategyConfig setLogicDeleteFieldName(String logicDeletePropertyName) {
        this.logicDeleteFieldName = **this.logicDeleteFieldName**;
        return this;
    }
    ....
}

**Comment by Caratacus** [comment]
已修复
