### ISSUE TITLE
拆分TableField中el属性.

### ISSUE THREAD

**Issue by nieqiurong** [baomidou/mybatis-plus#1034]
/**
     * 当该Field为类对象时, 可使用#{对象.属性}来映射到数据表.
     * <p>支持：@TableField(el = "role, jdbcType=BIGINT)</p>
     * <p>支持：@TableField(el = "role, typeHandler=com.baomidou.springcloud.typehandler.PhoneTypeHandler")</p>
     */
    String el() default "";

**Comment by dw3799** [comment]
role,   表示什么，我想用一个model里的字段映射到另外一个字段里怎么处理

**Comment by dw3799** [comment]
role,   表示什么，我想用一个model里的字段映射到另外一个字段里怎么处理

**Comment by quavario** [comment]
@dw3799 目前好像还不行, 虽然能查到值,但是映射不到对应的实体上, 而且实体为null

**Comment by qmdx** [comment]
不是已经变成 jdbcType typeHandler 了
