### ISSUE TITLE
DB2使用3.10版本生成代码为空文件夹

### ISSUE THREAD

**Issue by hs598375774** [baomidou/mybatis-plus#1035]
### 当前使用版本(必须填写清楚，否则不予处理)

当前版本3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

下载mybatis-plus-sample-generator，修改数据库配置为DB2
// 数据源配置
            MyDataSourceConfig dsc = new MyDataSourceConfig();
            dsc.setDbType(DbType.DB2);
            dsc.setUrl("jdbc:db2://192.168.1.7:50000/test");
            dsc.setSchemaName("SMY");
            dsc.setDriverName("com.ibm.db2.jcc.DB2Driver");
            dsc.setUsername("db2admin");
            dsc.setPassword("db123456");
            mpg.setDataSource(dsc);

表名、前缀设置
strategy.setInclude("T_STORAGE_BATCH_REPORT");
strategy.setTablePrefix("T_");

### 重现步骤

代码修改完毕之后，运行main方法，发现生成的都是空文件
数据库表都是存储在SMY这个scheme中
发现执行两个SQL的时候，第一个SQL查询不到表名，第二个相同
SELECT * FROM SYSCAT.TABLES where tabschema=current schema
SELECT *  FROM syscat.columns WHERE tabschema=current schema AND tabname='%s'

数据库中存在多个schema，当前的schema并不是SMY
需要这样查询才行
SELECT * FROM SYSCAT.TABLES where tabschema='SMY'
SELECT *  FROM syscat.columns WHERE tabschema='SMY' AND tabname='%s'

看看能不能这个schema动态传入，和其他数据库一样
### 报错信息

无报错信息

**Comment by qmdx** [comment]
修复，关注下一个版本的发布
