### ISSUE TITLE
请求为代码生成器TableField类加入更多信息

### ISSUE THREAD

**Issue by chenbo443756309** [baomidou/mybatis-plus#1036]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0-RELEASE

### 该问题是怎么引起的？
能不能为代码生成器的TableField类加入更多的数据库字段信息呢，比如长度，是否为空，默认值等

**Comment by miemieYaho** [comment]
mp 不是 jpa,不需要

**Comment by chenbo443756309** [comment]
你们有想过做成JPA那样可以反向正向生成表和实体类并在启动的时候验证生成更改表和类的想法吗

**Comment by miemieYaho** [comment]
有hibernate为什么要重复造轮子?

**Comment by TSiven** [comment]
同求,  想通过是否允许为空, 以及长度字段生成对应的validate注解扩展代码

**Comment by 852675742** [comment]
强烈希望为代码生成器的TableField类加入更多的数据库字段信息呢，比如长度，是否为空，默认值等

**Comment by qmdx** [comment]
@miemieYaho  这里说的是生成器中数据库信息，reopen 后面考虑

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html#%E6%B3%A8%E5%85%A5%E6%9F%A5%E8%AF%A2%E5%AD%97%E6%AE%B5%E5%85%B6%E4%BB%96%E4%BF%A1%E6%81%AF
