### ISSUE TITLE
支持自定义的非sql ID生成器？

### ISSUE THREAD

**Issue by dilboy** [baomidou/mybatis-plus#1037]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
需要自定义ID生成器

**Comment by miemieYaho** [comment]
1. 自己 set,2. 使用自动填充功能

**Comment by dilboy** [comment]
有考虑通过IdType枚举来选择自定义的非sql的ID生成器嘛?

**Comment by miemieYaho** [comment]
没有
