### ISSUE TITLE
是否支持多个表前缀

### ISSUE THREAD

**Issue by xhlim** [baomidou/mybatis-plus#1039]
### 当前使用版本(必须填写清楚，否则不予处理)
版本 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在重构老的项目时，发现表设计存在多个前缀
t_user
tab_order
如何进行配置多个表名前缀？
是否可以支持读取实体类的 注解 @Table(name = "t_user")（javax.persistence.Table）

**Comment by miemieYaho** [comment]
不支持,看文档
