### ISSUE TITLE
生成的Entity字段类型错误

### ISSUE THREAD

**Issue by eidolonse** [baomidou/mybatis-plus#104]
如果数据库字段是类似enum('DATE','UPDATE')类型，默认的MySqlTypeConvert转换的时候生成的Entity字段类型会是Date而不是String，同样enum中不能有INT，BIT等出现，否则类型是错的。

**Comment by qmdx** [comment]
> 如果觉得生成器类型不能匹配可以`
```
        dsc.setTypeConvert(new MySqlTypeConvert() {
            // 字段转换
            @Override
            public DbColumnType processTypeConvert(String fieldType) {
                if ("bit(1)".equals(fieldType)) {
                    return DbColumnType.BOOLEAN;
                }
                return super.processTypeConvert(fieldType);
            }
        });
```

**Comment by eidolonse** [comment]
/**
 * <p>
 * MYSQL 数据库字段类型转换
 * </p>
 *
 * @author hubin
 * @date 2017-01-20
 */
public class MySqlTypeConvert implements ITypeConvert {

    public DbColumnType processTypeConvert(String fieldType) {
        String t = fieldType.toLowerCase();
        if (t.contains("char") || t.contains("text")) {
            return DbColumnType.STRING;
        } else if (t.contains("bigint")) {
            return DbColumnType.LONG;
        } else if (t.contains("int")) {
            return DbColumnType.INTEGER;
        } else if (t.contains("date") || t.contains("time") || t.contains("year")) {
            return DbColumnType.DATE;
        } else if (t.contains("text")) {
            return DbColumnType.STRING;
        } else if (t.contains("bit")) {
            return DbColumnType.BOOLEAN;
        } else if (t.contains("decimal")) {
            return DbColumnType.BIG_DECIMAL;
        } else if (t.contains("clob")) {
            return DbColumnType.CLOB;
        } else if (t.contains("blog")) {
            return DbColumnType.BLOB;
        } else if (t.contains("binary")) {
            return DbColumnType.BYTE_ARRAY;
        } else if (t.contains("float")) {
            return DbColumnType.FLOAT;
        } else if (t.contains("double")) {
            return DbColumnType.DOUBLE;
        } else if (t.contains("json") || t.contains("enum")) {
            return DbColumnType.STRING;
        }
        return DbColumnType.STRING;
    }

}

我的意思是这里用contains()有问题，最好先判断enum，另外数据库中set('DATE','UPDATE')这种类型转出来的也是错误的。

**Comment by qmdx** [comment]
@eidolonse  这块我们感觉会有判断 不合理，所以预留了口子你自己判断，如上回复.
