### ISSUE TITLE
缺少日志jar

### ISSUE THREAD

**Issue by xhlim** [baomidou/mybatis-plus#1040]
### 当前使用版本(必须填写清楚，否则不予处理)
版本： 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无法启动，MybatisSqlSessionFactoryBean 类中找不到  org.mybatis.logging.LoggerFactory
参考 https://github.com/baomidou/mybatis-plus/issues/947 修改后无效

https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/spring/MybatisSqlSessionFactoryBean.java#L53

### 重现步骤

使用3.1.0 版本

### 报错信息

 Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory

**Comment by miemieYaho** [comment]
检查依赖冲突
