### ISSUE TITLE
fill = FieldFill.UPDATE 被包装了param1?

### ISSUE THREAD

**Issue by yjloser** [baomidou/mybatis-plus#1043]
### 当前使用版本(必须填写清楚，否则不予处理)

spring boot 2.1.4及mybatis-plus 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在字段上加入fill = FieldFill.UPDATE，然后到自定义实现的MetaObjectHandler，突然发现最外层被包装了

### 报错信息

![image](https://user-images.githubusercontent.com/30133351/56457704-f5c17100-63b0-11e9-9068-7175decfd5ee.png)

**Comment by miemieYaho** [comment]
这是mybatis做的

**Comment by yuxiaobin** [comment]
mp的updateById()方法，仔细看BaseMapper，是使用了@Param注解
