### ISSUE TITLE
3.1版本的枚举问题

### ISSUE THREAD

**Issue by userkdg** [baomidou/mybatis-plus#1044]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
按官方文档定义的枚举类，在实体类中使用，
项目在mysql5.7版本中可以Java中枚举类型，与mysql数据库表字段类型为int/tinyint的对应，可以写入数据成功
但是，在使用m'ysql8.0中，无法写入成功，

### 重现步骤
1.使用mysql5.7，插入一个实体含有官方推荐的extend IEumn接口的
2.使用mysql8.0，插入一个实体含有官方推荐的extend IEumn接口的

### 报错信息
SqlException:报incorrect integer value "中文" for column 'status' at row

**Comment by miemieYaho** [comment]
自行排查
