### ISSUE TITLE
在dynamic数据源中无法配置spring.datasource.druid.connection-init-sqls这个参数

### ISSUE THREAD

**Issue by yousiqi** [baomidou/mybatis-plus#1045]
### 当前使用版本(必须填写清楚，否则不予处理)
2.2.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
没有提供该配置项

### 重现步骤
如果我使用了dynamic，但又需要配置connection-init-sqls，如何处理，麻烦帮忙看看

### 报错信息
无

**Comment by miemieYaho** [comment]
这和我们无关

**Comment by yousiqi** [comment]
那如果我用了dynamic，如何让连接一开始就初始化一句sql呢，在单独使用druid是可以配置的

**Comment by yousiqi** [comment]
![image](https://user-images.githubusercontent.com/28135975/56478448-11786480-64e2-11e9-9ce4-0ffbd832b5b0.png)
在DataSourceFactory中，DruidDataSource是有dynamic生成，但其中druid的配置项不足，由以上截图可知，只是配置了其中的一部分
