### ISSUE TITLE
是否可以与tk.mybatis一起使用

### ISSUE THREAD

**Issue by xhlim** [baomidou/mybatis-plus#1047]
### 当前使用版本(必须填写清楚，否则不予处理)

版本 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

与tk一起使用，出现异常org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)
是否表示不支持与tk.mybatis一起使用

### 重现步骤

引入
       <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper</artifactId>
        </dependency>

### 报错信息

org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)

**Comment by miemieYaho** [comment]
支不支持自己尝试

**Comment by cq-zhaoqf** [comment]
刚刚我试了一下, 可以的, 我的项目是以前用 tk mapper 为主的, 然后我重写一个 mybatis plus config, 如下图
![image](https://user-images.githubusercontent.com/27794583/89777550-855ad800-db3e-11ea-8421-79e537e53419.png)
然后添加 mybatis puls 依赖, 我用的 3.3.2, 然后 tk mapper 排除了 mybatis 的依赖, 就正常使用了... 不过2个的 Dao 都是分开的, 不能只写一个 Dao 同时使用2个mybatis 增强
![image](https://user-images.githubusercontent.com/27794583/89777851-1336c300-db3f-11ea-8bf5-d18d3c1446b3.png)

**Comment by qmdx** [comment]
不建议一起用存在冲突可能
