### ISSUE TITLE
bug tmp文件格式错乱

### ISSUE THREAD

**Issue by fanlushuai** [baomidou/mybatis-plus#1048]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/21078607/56495139-5672ba00-6527-11e9-84a8-ea1a2db8f52c.png)

**Comment by qmdx** [comment]
这是哪个文件

**Comment by fanlushuai** [comment]
> 这是哪个文件

https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/resources/templates/entity.java.vm

**Comment by qmdx** [comment]
修复，请关注下一个版本发布
