### ISSUE TITLE
分页没有指定数据库时，获取的总数total为0

### ISSUE THREAD

**Issue by longzhaobi** [baomidou/mybatis-plus#105]
把下面加上 就正常了。请问知道原因吗？
```
<plugin interceptor="com.baomidou.mybatisplus.plugins.PaginationInterceptor">
  <property name="dialectType" value="mysql" />
</plugin>
```

**Comment by qmdx** [comment]
升级到 最新版本，目前是 2.1-gamma 不在需要加上 dialectType 会自动识别

**Comment by longzhaobi** [comment]
@qmdx 
我用的是2.02，不配置dialectType 插件能查处数据，但就是total是0，导致前端无法分页，昨天升级了下2.1-gamma，也是能查询到数据，就是获取的总数total和pages是0 ，.是我这边配置的问题吗？

**Comment by longzhaobi** [comment]
```
<plugins>
		<!-- 分页查询插件-->
		<plugin interceptor="com.baomidou.mybatisplus.plugins.PaginationInterceptor">
			<!--<property name="dialectType" value="mysql" />-->
		</plugin>
	</plugins>
```
可以了，原来我是把plugins都给注释掉了，原来是要删调里面的property...

**Comment by javastar920905** [comment]
请问你们是把邮件发错了吗 ?请确认邮箱



在 2017-07-20 11:44:09，"龙小川" <notifications@github.com> 写道：

<plugins>
		
		<plugin interceptor="com.baomidou.mybatisplus.plugins.PaginationInterceptor">
			
		</plugin>
	</plugins>


可以了，原来我是把plugins都给注释掉了，原来是要删调里面的property...

**Comment by longzhaobi** [comment]
@javastar920905  你是不是把那个watch给给点上了？你把watch去掉应该是不会收到！
