### ISSUE TITLE
配置了id生产策略 IdType.ID_WORKER，当自定义给id赋值的时候，插入数据库的是自己赋的值，而不是自动生成的

### ISSUE THREAD

**Issue by lix1898** [baomidou/mybatis-plus#1052]
### 配置了id生产策略，当自定义给id赋值的时候，插入数据库的是自己赋的值，而不是自动生成的
@TableId(type = IdType.ID_WORKER)
private Long id;

### 重现步骤

如setId(0L),重复执行两遍，数据库报主键冲突

### 报错信息
Duplicate entry '0' for key 'PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '0' for key 'PRIMARY'

**Comment by miemieYaho** [comment]
自己赋值以你自己赋的值为准
