### ISSUE TITLE
 IdType.ID_WORKER 主键重复错误

### ISSUE THREAD

**Issue by wanghws** [baomidou/mybatis-plus#1053]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

@TableId(type = IdType.ID_WORKER) 主键重复错误

### 重现步骤

并发500个保存请求，2个容器节点接口负载均衡

### 报错信息

 Duplicate entry '1120596181019111426' for key 'PRIMARY'

**Comment by miemieYaho** [comment]
docker容器内获取不到ip和mac地址,这两个是id算法不重复的保证

**Comment by qmdx** [comment]
看文档，可以指定下机器 id 相关参数

**Comment by wanghws** [comment]
> 看文档，可以指定下机器 id 相关参数

看到了，主要容器部署的时候，构建阶段这个workId用maven参数去设置，不知道怎么来保证不重复。

我改了一下Sequence.java

`mpid.append(name.split("@")[1]);`

因为Pod内的地址是1@api-c89884688-r9cdx，后缀是pod名字，每个pod都不同
