### ISSUE TITLE
insertBatch方法报错

### ISSUE THREAD

**Issue by juzhenxing** [baomidou/mybatis-plus#1054]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
insertBatch方法报错
数据源是sqlserver

### 重现步骤
insertBatch方法报错
数据源是sqlserver

**Comment by lcb1208** [comment]
哥们怎么处理的
