### ISSUE TITLE
一对多如何正确使用分页(一对多关联对象分页查询，total字段不准确)

### ISSUE THREAD

**Issue by txr177** [baomidou/mybatis-plus#1056]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
多表联查时其中一张表为多条数据时，分页的total是不正确的，total和数据库返回的行数是相关的，请问是否只有自己些查询总条数的sql这个方案.。还望回复谢谢!!!

**Comment by miemieYaho** [comment]
自己写 count 查
