### ISSUE TITLE
IPage 中convert的使用方式

### ISSUE THREAD

**Issue by wangtaicheng** [baomidou/mybatis-plus#1059]
### 当前使用版本(必须填写清楚，否则不予处理)
3.10

### 报错信息

看到IPage 接口中有个convert 方法，不知道这个是怎么使用的。

**Comment by miemieYaho** [comment]
看源码

**Comment by wjjzl519** [comment]
IPage<CmsCardVO> voiPage = iPage.convert(x -> new CmsCardVO());

**Comment by wjjzl519** [comment]
> ### 当前使用版本(必须填写清楚，否则不予处理)
> 3.10
> 
> ### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
> ### 重现步骤
> ### 报错信息
> 看到IPage 接口中有个convert 方法，不知道这个是怎么使用的。

IPage<CmsCardVO> voiPage = iPage.convert(x -> new CmsCardVO());
对象转化而已
