### ISSUE TITLE
Mybatis-Plus 代码生成器 自定义实体父类有问题

### ISSUE THREAD

**Issue by fanlinhu** [baomidou/mybatis-plus#106]
![image](https://user-images.githubusercontent.com/16377552/28402052-4a44dc66-6d50-11e7-8df3-e48673d301e7.png)
![image](https://user-images.githubusercontent.com/16377552/28402087-83023080-6d50-11e7-9ff1-889116d5fe19.png)

**Comment by qmdx** [comment]
如果使用 AR模式需要自定义实体继承 Model 否则 gc.setActiveRecord(false);
