### ISSUE TITLE
采用mybatis-plus 3.1.0版本后，druid没法打印日志

### ISSUE THREAD

**Issue by shmily2038** [baomidou/mybatis-plus#1060]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
引入mybatis-plus无法打印原来mybatis的SQL，原来的打印配置logging.level.druid.sql.Statement=DEBUG

### 重现步骤
配置好，controller调用mapper，执行方法

### 报错信息
无报错信息，如果将日志的打印定位到mapper，会打印，但是打印日志，不支持正则过滤，所以不可能将所有的mapper一一配置，故需要改进。

**Comment by miemieYaho** [comment]
底层是 mybatis,有问题去找 mybatis

**Comment by shmily2038** [comment]
主要是之前用mybatis没问题的，现在改为mybatis-plus才出现的
![图片](https://user-images.githubusercontent.com/16485682/56717496-56fd9180-676f-11e9-931e-f37dc8aa160c.png)

**Comment by qmdx** [comment]
查看 https://mybatis.plus 文档有日志相关文档

**Comment by shmily2038** [comment]
> 
> 
> 查看 https://mybatis.plus 文档有日志相关文档

能指出具体哪里？

**Comment by shmily2038** [comment]
请具体指出下在哪里可以找到？

**Comment by qmdx** [comment]
无法自己解决，那你就不要使用 durid
