### ISSUE TITLE
指定生成路径只指定了一个全部覆盖了。

### ISSUE THREAD

**Issue by lyricsqq** [baomidou/mybatis-plus#1063]
### 当前使用版本(必须填写清楚，否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.1.0</version>
        </dependency>
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
无法将生成的xml 放在统一的目录下。如果我直接通过 pathInfo 指定会覆盖 java代码的生成路径。我想应该是先有一个默认配置，我配置一个路径覆盖一个，而不是一起覆盖掉。

### 重现步骤
我看了源码，发现是直接覆盖了。我想应该先默认 有一个覆盖一个。
或者将这个私有方法。放开能重写

    /**
     * 处理包配置
     *
     * @param template  TemplateConfig
     * @param outputDir
     * @param config    PackageConfig
     */
    private void handlerPackage(TemplateConfig template, String outputDir, PackageConfig config) {
        // 包信息
        packageInfo = new HashMap<>(8);
        packageInfo.put(ConstVal.MODULE_NAME, config.getModuleName());
        packageInfo.put(ConstVal.ENTITY, joinPackage(config.getParent(), config.getEntity()));
        packageInfo.put(ConstVal.MAPPER, joinPackage(config.getParent(), config.getMapper()));
        packageInfo.put(ConstVal.XML, joinPackage(config.getParent(), config.getXml()));
        packageInfo.put(ConstVal.SERVICE, joinPackage(config.getParent(), config.getService()));
        packageInfo.put(ConstVal.SERVICE_IMPL, joinPackage(config.getParent(), config.getServiceImpl()));
        packageInfo.put(ConstVal.CONTROLLER, joinPackage(config.getParent(), config.getController()));

        // 自定义路径
        Map<String, String> configPathInfo = config.getPathInfo();
        if (null != configPathInfo) {
            pathInfo = configPathInfo;
        } else {
            // 生成路径信息
            pathInfo = new HashMap<>(6);
            setPathInfo(pathInfo, template.getEntity(getGlobalConfig().isKotlin()), outputDir, ConstVal.ENTITY_PATH, ConstVal.ENTITY);
            setPathInfo(pathInfo, template.getMapper(), outputDir, ConstVal.MAPPER_PATH, ConstVal.MAPPER);
            setPathInfo(pathInfo, template.getXml(), outputDir, ConstVal.XML_PATH, ConstVal.XML);
            setPathInfo(pathInfo, template.getService(), outputDir, ConstVal.SERVICE_PATH, ConstVal.SERVICE);
            setPathInfo(pathInfo, template.getServiceImpl(), outputDir, ConstVal.SERVICE_IMPL_PATH, ConstVal.SERVICE_IMPL);
            setPathInfo(pathInfo, template.getController(), outputDir, ConstVal.CONTROLLER_PATH, ConstVal.CONTROLLER);
        }
    }

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html

cfg.setFileCreate(new IFileCreate() ...   部分

**Comment by lyricsqq** [comment]
我仅仅修改了一个参数 。我不想去实现这些方法。例如我修改了  PackageConfig 中的 pathInfo 中的 
xml_path 的默认值。项目中我们常常将它放在 资源路径下。而不是每个java业务包下。我认为应是覆盖指定的路径xml_path 。而不是将 java代码的路径全部覆盖。然后需要全部重新指定。那么这个pathInfo 参数我认为就没有存在的必要了。

**Comment by qmdx** [comment]
每一个人的需求都不一样，框架能做到的就是统一个性化自己 diy 接口

**Comment by lyricsqq** [comment]
是的。我已经diy 完成。 我给了优先给了 pathInfo 默认值。 然后特殊路径 自己配置 覆盖默认的。 问题已经解决。
