### ISSUE TITLE
代码生成器DB2主键

### ISSUE THREAD

**Issue by BINGW2019** [baomidou/mybatis-plus#1064]
**当前使用版本(必须填写清楚，否则不予处理)**
**3.1.0**

**该问题是怎么引起的？(最新版上已修复的会直接close掉)**

db2 中的表生成了主键，代码生成器判断错误将keyFlag设置为false。db2的文档说明了IDENTITY列的值应该为Y/N。

![image](https://user-images.githubusercontent.com/11324138/56785851-6e995080-6829-11e9-968f-1a4bf08cf005.png)

![image](https://user-images.githubusercontent.com/11324138/56785871-84a71100-6829-11e9-81ff-efb7b553713b.png)

https://www.ibm.com/support/knowledgecenter/en/SSEPGG_9.8.0/com.ibm.db2.luw.sql.ref.doc/doc/r0001038.html

**Comment by qmdx** [comment]
无可用测试环境，请 pr 可用代码谢谢

**Comment by BINGW2019** [comment]
@qmdx 好的，有空我提一个pr。
