### ISSUE TITLE
希望尽快发布3.1.1

### ISSUE THREAD

**Issue by yancoo** [baomidou/mybatis-plus#1066]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
@Tablename 不支持 schema，使用postgresql非常不方便，看起来3.1.1将支持，求快～～

### 重现步骤
同上。

### 报错信息
同上。

**Comment by miemieYaho** [comment]
发了
