### ISSUE TITLE
多租户模式下，如何做到指定id的sql不追加多租户过滤

### ISSUE THREAD

**Issue by qiankunpingtai** [baomidou/mybatis-plus#1067]
### 该问题是怎么引起的？
多租户模式下，对表的过滤作如下设置
            @Override
            public String getTenantIdColumn() {
                return "tenant_id";
            }
            @Override
            public boolean doTableFilter(String tableName) {
                // 这里可以判断是否过滤表,不过滤任何表
                return false;
            }
如何实现某些指定id的查询语句，不追加多租户tenant_id过滤标识？

我设置了
mybatis-plus.global-config.sql-parser-cache=true
    /**
     * 这个查询不添加租户id，保证登录名全局唯一
     * */
    @SqlParser(filter = true)
    List<User> getUserListByLoginName(@Param("loginame") String loginame);

但是没有达到这个查询不追加多租户tenant_id标识的效果！

**Comment by miemieYaho** [comment]
文档很清楚
