### ISSUE TITLE
生成器字段信息中，是否能加入是否可为空的信息

### ISSUE THREAD

**Issue by michaelzx** [baomidou/mybatis-plus#1069]
### 当前使用版本
3.0.7.1

### 场景
数据库为MYSQL
项目全局策略，定义的是`NOT_NULL`
数据库中字段，绝大部分设置了不能为空
生成器使用了自定义模板

### 问题
碰到datatime的字段的时候，需要有时候能设置为允许为空
需要在entity中，将这些字段策略单独设为`IGNORED`
但是字段信息中，没有对是否为可为空的描述
无法在自定义模板中进行判断

### 需求
希望能在字段信息中，是可为空的信息，来满足自定义模板的定制需求

**Comment by miemieYaho** [comment]
不支持,你数据库字段是否可以 null 与验证策略没有任何关系
