### ISSUE TITLE
多租户模式设置全局字段拼接为is null而不是=null

### ISSUE THREAD

**Issue by qiankunpingtai** [baomidou/mybatis-plus#1071]
### 该问题是怎么引起的？**([最新版]
多租户模式下我想全局设置租户id为null时，sql拼接为is null而不是=null该如何设置呢？
if(tenantId!=null){
                    //多租户模式，租户id从当前用户获取
                    return new LongValue(Long.parseLong(tenantId.toString()));
                } else {
                    //多租户模式，租户id为null
                    *return null*;
               }

**Comment by miemieYaho** [comment]
不支持,多租户就是完全隔离,不要把这个功能当成一个筛选字段用

**Comment by qiankunpingtai** [comment]
那怎么全局设定一个字段为null时拼接为is null而不是=null呢

**Comment by miemieYaho** [comment]
不支持
