### ISSUE TITLE
3.1.0到3.1.1升级后，报错

### ISSUE THREAD

**Issue by xem1987** [baomidou/mybatis-plus#1072]
### 该问题是怎么引起的？
Maven依赖从3.1.0到3.1.1升级后，系统启动报错，还原回3.1.0，系统正常启动

### 重现步骤
从3.1.0到3.1.1升级后，系统启动报错
```java
new QueryWrapper<ApplicationConfigInfo>().lambda()
                .eq(ApplicationConfigInfo::getConfigGroupId, groupId)
```
貌似是驼峰转化的问题，但是设置后依然报错

### 报错信息
```
mybatis-plus.configuration.map-underscore-to-camel-case=true

Invocation of init method failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Your property named "configGroupId" cannot find the corresponding database column name!
```

**Comment by miemieYaho** [comment]
configGroupId 这个字段是 ApplicationConfigInfo 的父类里面的字段?

**Comment by xem1987** [comment]
不是，configGroupId就是ApplicationConfigInfo里的字段，这个问题和实体继承有关系？

**Comment by miemieYaho** [comment]
你这个方法是什么时候调用的?可能是调用太早,缓存还没好

**Comment by xem1987** [comment]
那是有可能 ，我这个调用时系统启动时调用的，那有什么接口可以让我判断缓存是否ready呢？

**Comment by miemieYaho** [comment]
这没法给你判断,你最好改成普通 wrapper

**Comment by miemieYaho** [comment]
你debug断点看一下是不是这个原因

**Comment by QiulinZhan** [comment]
3.1.0 升3.1.1
Teacher teacher = teacherService.getOne(Wrappers.<Teacher>lambdaQuery().eq(Teacher::getUsername, username));
执行后和楼主错误类似

**Comment by miemieYaho** [comment]
如果有使用 spring-boot-devtools ,请移除

**Comment by Parker-Xiang** [comment]
3.1.0 升3.1.1 之后旧代码都出现和楼主相同的错误，已回归3.1.0
spring-boot-devtools移除问题也没得到解决

**Comment by kr1s-gzq** [comment]
同样遇到类似问题，3.1.0没有问题，3.1.1就这样
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Your property named "channelType" cannot find the corresponding database column name!
退回3.1.0就可以,移除devtools也可以,二选一

**Comment by jia-zhen** [comment]
感谢楼主，遇到同样问题，选择3.1.0就没问题了

**Comment by alterhu2020** [comment]
问题是移除了dev-tools之后，在idea中更改了class的相关代码，不能热更新了啊！

@miemieYaho

**Comment by winnershili** [comment]
已验证是BUG 已退回3.1.0

**Comment by WindStill** [comment]
遇到同样问题，选择3.1.0就没问题了

**Comment by lehug** [comment]
为什么弄不兼容性升级？？？！！！
