### ISSUE TITLE
Failed to configure a DataSource

### ISSUE THREAD

**Issue by VoidStarSp** [baomidou/mybatis-plus#1073]
### 当前使用版本(必须填写清楚，否则不予处理)

'com.baomidou:mybatis-plus-boot-starter:3.1.0',
'com.baomidou:dynamic-datasource-spring-boot-starter:2.5.3',
'com.alibaba:druid-spring-boot-starter:1.1.16',

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

配置多数据源切换,起初用的是com.baomidou:dynamic-datasource-spring-boot-starter:1.0.0,但是在每隔查询之后会显示Creating a new SqlSession,于是准备升级一下,yml配置大概是这个结构
spring:
    datasource:
        dynamic:
            datasource:
                master:
                    name: msyql
                    url: jdbc:mysql://localhost:3307
                slave:
                    sqlServer:
                        name: sqlServer
                        url: jdbc:sqlserver://localhost:1433
然后启动不成功，识别不了yml的url
### 报错信息
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

**Comment by miemieYaho** [comment]
去 dynamic-datasource-spring-boot-starter 提
