### ISSUE TITLE
请问这样配置多数据源是否有误

### ISSUE THREAD

**Issue by a364176773** [baomidou/mybatis-plus#1076]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

> spring:
>   datasource:
>     dynamic:
>       primary: master #设置默认的数据源或者数据源组,默认值即为master
>       datasource:
>         master:
>           username: root
>           password: 17xs2015
>           driver-class-name: com.mysql.jdbc.Driver
>           url: jdbc:mysql://192.168.14.67:33306/17bbt
>         slave_1:
>           username: root
>           password: 17xs2015
>           driver-class-name: com.mysql.jdbc.Driver
>           url: jdbc:mysql://192.168.14.67:33307/17bbt
>     dbcp2:
>       initial-size: 6
>       min-idle: 3
>       max-wait-millis: 60000
>       validation-query: select 'x'
>       time-between-eviction-runs-millis: 60000
>       soft-min-evictable-idle-time-millis: 30000
>       test-on-borrow: false
>       test-on-return: false
>       test-while-idle: true
>     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

service:
`@Service(version = "1.0.0", interfaceClass = IFrontUserSelectService.class)
@Transactional
@DS("slave")
public class FrontUserSerlectServiceImpl extends ServiceImpl<FrontUserMapper, FrontUser>
		implements IFrontUserSelectService {`

请问这样是不是使用mp自带的通用方法就直接是从库里查询的?
还有能否在logger输出的sql的时候顺带也输出对应的数据源名称?

**Comment by miemieYaho** [comment]
去那边提

**Comment by a364176773** [comment]
@miemieYaho  用的就是mp官网介绍的,你让我去哪边提?

**Comment by miemieYaho** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter
