### ISSUE TITLE
oracle

### ISSUE THREAD

**Issue by superpipo** [baomidou/mybatis-plus#1078]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
mysql数据库切换到oracle，查询枚举解析失效

### 重现步骤
枚举存入oracle数据库column为INTEGER类型，但转换失败

### 报错信息
oracle数据库查出来是bigdecimal与integer原类型equals()不匹配，枚举匹配失败(oracle版本11g)

**Comment by a513684882** [comment]
我怎么设置能不接收你们的邮件?谢谢

**Comment by superpipo** [comment]
在 2019-04-29 16:34:47，"a513684882" <notifications@github.com> 写道：
我怎么设置能不接收你们的邮件?谢谢

**Comment by miemieYaho** [comment]
升级版本试试

**Comment by superpipo** [comment]
升级版本问题解决
