### ISSUE TITLE
实体类为内部类时，select会将内部类中隐藏的成员变量（this$0）也当成查询字段

### ISSUE THREAD

**Issue by snippet0809** [baomidou/mybatis-plus#1079]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
成员内部类会隐藏一个指针，指向他所在的外部类，这个隐藏的成员变量和自己声明的成员变量一起被当成了数据库字段

### 重现步骤
1、@TableName标识的类为public的成员内部类
2、按mybatis plus规则正常写MVC
3、得到异常：java.sql.SQLSyntaxErrorException: Unknown column 'this$0' in 'field list'

### 报错信息
exception example：
SQL:SELECT  id, name, age, this$0  FROM user  WHERE id = ?
Cause: java.sql.SQLSyntaxErrorException: Unknown column 'this$0' in 'field list'

配套实体类举例：
public class A{
         @TableName(value="user")
         @Data
         public class B{
                private String id;
                private String name;
                private String name;
         }
}

**Comment by miemieYaho** [comment]
把你这内部类变成静态的

**Comment by snippet0809** [comment]
> 把你这内部类变成静态的

昨天发现这个问题后我就立马改成静态的了，业务需求已经解决了。今天就是突然想到了来反馈了一下，另外感谢你的回复和你们的框架，mybatis plus真的很好用。
