### ISSUE TITLE
selectPage方法对于类似User保留字的表生成的SQL无法运行，建议在表两边加上[]中括号。

### ISSUE THREAD

**Issue by sss768** [baomidou/mybatis-plus#108]
由于维护的是老项目，数据库中有一张表叫User，属于sql的保留字，因为不能修改表名，所以无法直接用mp里的方法

查询方法是：
        List<User> userList5 = userDao.selectPage(new Page<User>(1,10),
                new EntityWrapper<User>().eq("SID","5")); 

报错内容是：
SELECT  ID,UserName,Psw,NickName,Email,SID,CanDownload,CanMgrData,CanPrice,ParentUserID,IsAdmin,IsActivateFROM user   WHERE  (SID = ?)
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'user' 附近有语法错误。

建议在表两边增加[User]，SQL即可正常运行。
如下所示：
SELECT  ID,UserName,Psw,NickName,Email,SID,CanDownload,CanMgrData,CanPrice,ParentUserID,IsAdmin,IsActivate FROM [user]   WHERE  (SID = 1)

**Comment by qmdx** [comment]
@TableName("[user]")  注解到你的类上
