### ISSUE TITLE
IdWorker自定义主键入库后，查询该数据信息时对应主键值跟数据库存储值不一致

### ISSUE THREAD

**Issue by ranxiong** [baomidou/mybatis-plus#1082]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
采用ServiceImpl的save和saveBatch自定义IdWorker主键入库(主键类型为bigint)后，查询该entity数据对应主键值跟数据库不一致，貌似做了某种映射处理
PS:使用IdWorker.get32UUID()存储主键值，正常

### 重现步骤
保存：long id = IdWorker.getId(); entity.setId(id);service.save(entity);
查询：service.list()

**Comment by miemieYaho** [comment]
看文档常见问题,js

**Comment by ranxiong** [comment]
恩，是JS Long型精度问题导致的
