### ISSUE TITLE
逻辑删除的删除时间如何更新

### ISSUE THREAD

**Issue by zzdehao** [baomidou/mybatis-plus#1083]
版本 3.1.0

我想做逻辑删除, 但是有个问题需要咨询一下, 因为删除的时候往往都会记录谁删的在什么时候删除的, 但现在如果调用remove的话那就只能更新到逻辑删的字段了, 而谁删的和什么时候删的就没法记录了啊, 问这个问题一般如何处理比较好?

重现步骤
不涉及

报错信息
不涉及

**Comment by miemieYaho** [comment]
看文档常见问题
