### ISSUE TITLE
升级到3.1.1版本oracle通过mapper自定义sql查询到的字段为什么都变小写了,怎么设置为默认大写

### ISSUE THREAD

**Issue by x55admin** [baomidou/mybatis-plus#1085]
### 当前使用版本(必须填写清楚，否则不予处理)
mp:3.1.1,数据库oracle

### 该问题是怎么引起的？
3.1.0升级到3.1.1之前查询到的字段都是默认大写的,现在debug看查询到的字段都变为小写了.看文档分析capital-mode 参数是管这个功能的 可是我设置为true查询到的字段还是小写,这是为什么,怎么解决?

**Comment by miemieYaho** [comment]
从来不会默认大写

**Comment by miemieYaho** [comment]
你是怎么查询?查询的 map?

**Comment by x55admin** [comment]
> 你是怎么查询?查询的 map?

是的查询的map 3.1.0 key就是大写的,毋庸置疑,3.1.1就变为小写了 为什么呢?

**Comment by miemieYaho** [comment]
最新版如果开启了下划线转换(默认开启),就会自动注入了返回值的 map 的 key 值转驼峰,如果你不需要目前你只能先用 3.1.0,后面版本会考虑给个开关是否自动注入

**Comment by miemieYaho** [comment]
[CHANGELOG](https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md)
`MybatisMapWrapperFactory 自动注入`

**Comment by x55admin** [comment]
> [CHANGELOG](https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md)
> `MybatisMapWrapperFactory 自动注入`

配置了下划线转驼峰,但是不带下划线的字段3.1.0以前key默认都是大写,3.1.1查询出来key都变小写了

**Comment by miemieYaho** [comment]
都跟你说了,`MybatisMapWrapperFactory`这个类,自己点进去看源码

**Comment by x55admin** [comment]
> 都跟你说了,`MybatisMapWrapperFactory`这个类,自己点进去看源码

好的 谢谢

**Comment by miemieYaho** [comment]
可以使用 3.1.2.2-SNAPSHOT,已去除`MybatisMapWrapperFactory`的自动注入

**Comment by x55admin** [comment]
> 可以使用 3.1.2.2-SNAPSHOT,已去除`MybatisMapWrapperFactory`的自动注入

谢谢,正式版再试

**Comment by qmdx** [comment]
u'p
