### ISSUE TITLE
3.1.0为什么取消updateSelectiveById方法

### ISSUE THREAD

**Issue by tangzp** [baomidou/mybatis-plus#1088]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
3.1.0为什么取消updateSelectiveById方法

**Comment by miemieYaho** [comment]
从来没这个方法

**Comment by qmdx** [comment]
默认 update 就是选择性更新的

**Comment by Linhai-Tan** [comment]
> 默认更新就是选择性更新的

请问怎么使用全字段的新增和修改方法，我试了好多个都是选择性的插入和更新
