### ISSUE TITLE
2.1-gamma版本乐观锁插件不能自定义乐观锁字段类型

### ISSUE THREAD

**Issue by wangyt** [baomidou/mybatis-plus#109]
之前使用的2.0.8版本中可以自定义VersionHandler，插件中可根据用户自定义的方式来处理乐观锁字段值的更新。我现在遇到的问题描述如下：
根据实际业务场景，我的乐观锁字段只能是时间戳类型的，但是由于我们现在线上环境使用的数据库版本（MySQL-5.6.2）问题，导致使用时间戳类型会丢失精度，所以我之前的处理方式是数据库字段设置为Long类型，使用MP 2.0.8版本自定义一个Long类型的处理器，这个处理器中对Original值的处理方式不是加1，而是赋值为时间戳的毫秒数，这样就变相实现了时间戳类型的乐观锁，但是最新的MP版本不支持自定义了，能否在后续的版本中考虑加回来自定义的功能？

**Comment by yuxiaobin** [comment]
所以，你的对象的version属性是Timestamp，但是数据库里是Long?

还是：
对象version属性是Long，数据库也是Long？

如果都是Long，配了你的处理器，会导致所有Long的version都会执行这个逻辑哦！

**Comment by yuxiaobin** [comment]
另外告诉你一个小秘密，乐观锁获取更新version的值，是一个protected 方法，也就是说，你可以继承OptimisticLockerInterceptor，然后复写getUpdatedVersionVal()这个方法，来定义你的Long的更新值

**Comment by wangyt** [comment]
对象version属性和数据库字段都是Long，我要的就是都按我自定义的逻辑来处理Long类型

**Comment by yuxiaobin** [comment]
@wangyt 方法我已经告诉你了，自定义一个类：
`MyOptLockerInterceptor` extends OptimisticLockerInterceptor{
@Override  
getUpdatedVersionVal(){
//implement your version control logic
}
}

`
