### ISSUE TITLE
建议：关于mapper @param注解的建议

### ISSUE THREAD

**Issue by 1397649957** [baomidou/mybatis-plus#1090]
我看框架的代码相比于mybatis做了这么大的调整，干脆把org.apache.ibatis.reflection.ParamNameResolver这个类也重写下吧，现在mybatis多参数一般必须写org.apache.ibatis.annotations.Param注解,不然就是#{0},#{1}这种不带业务含义的，像spring框架，实现的org.springframework.core.LocalVariableTableParameterNameDiscoverer挺好用的，每次写@param其实有时候挺多余的，希望这个框架做一些实现

**Comment by miemieYaho** [comment]
没必要
