### ISSUE TITLE
配置objectfactory类地址报错

### ISSUE THREAD

**Issue by yakax** [baomidou/mybatis-plus#1093]
### 当前使用版本(必须填写清楚，否则不予处理)
version:3.1.0
springboot2.1.4

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在application.properties配置了mybatis-plus.configuration.object-factory=com.example.demo.factory.MyObjectFactory 

### 重现步骤
启动报错 
MyObjectFactory这个类是存在的，并且已经继承DefaultObjectFactory并重写了creat方法

### 报错信息

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'mybatis-plus.configuration.object-factory' to org.apache.ibatis.reflection.factory.ObjectFactory:

    Property: mybatis-plus.configuration.object-factory
    Value: com.example.demo.factory.MyObjectFactory
    Origin: class path resource [application.properties]:7:43
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.apache.ibatis.reflection.factory.ObjectFactory]

Action:

Update your application's configuration

**Comment by miemieYaho** [comment]
mybatis自己的statrter也这样,尝试使用 mybatis-plus.configuration-properties 指定

**Comment by yakax** [comment]
格式能否说一下呢.需要的是key value的map格式

**Comment by yakax** [comment]
> mybatis自己的statrter也这样，尝试使用mybatis-plus.configuration-properties指定

能否说一下mybatis-plus.configuration-properties这个配置的格式，谢谢
