### ISSUE TITLE
尝试使用mybatis-plus.configuration-properties

### ISSUE THREAD

**Issue by yakax** [baomidou/mybatis-plus#1094]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无任何报错

### 重现步骤
尝试使用
mybatis-plus.configuration-properties.=classpath:mybatis-config.xml来读取mybatis配置文件
设置objectfactory。
我看了一下你们mybatis-plus.configuration-properties需要的是一个Properties，提示我放keyvalue进去，
不知道是不是我的写法错误，如果错误，能否给个正确的格式来加载配置文件

### 报错信息

并没生效

**Comment by miemieYaho** [comment]
这个属性去看官方文档
