### ISSUE TITLE
BaseMapper是否可以提供一种更简洁的crud操作

### ISSUE THREAD

**Issue by tfwx** [baomidou/mybatis-plus#1095]
### 该问题是怎么引起的？
MybatisPlus在BaseMapper里已经提供了很完善的CRUD接口，但是，对于每一张表都需要生成一个接口并继承BaseMapper，才能使用BaseMapper提供的CURD接口，可我不想为每一张表，都建立一个Mapper接口。

比如：有一张表user,  不用建立一个继承自BaseMapper的UserMapper接口，而是像下面这样可以直接完成查询

User user = baseMapper.get(User.class, new QueryMapper<User>().lambda().eq(User::getName, "selina"));

List&lt;User&gt; userList = baseMapper.list(User.class, new QueryMapper<User>().lambda().gt(User::getAge, 20));

其中，User实体类上已经通过@TableName指定了表名

不知道对于BaseMapper或其它类来讲，能否提供这些更加方便的通用crud操作接口，支持上面的类似写法，不用为每一张表建立一个继承自BaseMapper的接口

**Comment by miemieYaho** [comment]
不能
