### ISSUE TITLE
MyBatisPlus的读写分离插件使用疑问

### ISSUE THREAD

**Issue by tfwx** [baomidou/mybatis-plus#1096]
### 当前使用版本(必须填写清楚，否则不予处理)
&lt;dependency&gt;
&emsp; &lt;groupId&gt;com.baomidou&lt;/groupId&gt;
&emsp;&lt;artifactId&gt;dynamic-datasource-spring-boot-starter&lt;/artifactId&gt;
&emsp;&lt;version&gt;2.5.3&lt;/version&gt;
&lt;/dependency&gt;

### 该问题是怎么引起的？
在学习MybatisPlus的读写分离插件：MasterSlaveAutoRoutingPlugin 时，看到这样一段源码：

```
    @Override
    public Object intercept(Invocation invocation) throws Throwable {
        Object[] args = invocation.getArgs();
        MappedStatement ms = (MappedStatement) args[0];
        try {
            DynamicDataSourceContextHolder.push(SqlCommandType.SELECT == ms.getSqlCommandType() ? MASTER : SLAVE);
            return invocation.proceed();
        } finally {
            DynamicDataSourceContextHolder.clear();
        }
    }
```
也就是说，所有的select操作将会由master节点执行，其他操作全由slave节点执行，但是这与dynamic-datasource-spring-boot-starter提供的使用说明刚好相反：

https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter
**建议
强烈建议在 主从模式 下遵循普遍的规则，以便他人能更轻易理解你的代码。
主数据库 建议 只执行 INSERT UPDATE DELETE 操作。
从数据库 建议 只执行 SELECT 操作。**

**Comment by miemieYaho** [comment]
到 dynamic-datasource-spring-boot-starter 那边去提
