### ISSUE TITLE
mybatisplus generator 生成实体类，可否去掉“@Accessors(chain = true)”？

### ISSUE THREAD

**Issue by guan25** [baomidou/mybatis-plus#1099]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

生成实体类代码包含：@Accessors(chain = true)，
致使set* 带有this返回值；
javabean规范为void类型。所以jdk8之后的 PropertyDescriptor找不到set方法，导致很多潜在组件问题

### 重现步骤

![image](https://user-images.githubusercontent.com/5926540/57189850-160f3500-6f46-11e9-8fb0-11bbf70fe315.png)

**Comment by qmdx** [comment]
请自定义模板，查阅文档

**Comment by guan25** [comment]
Ok，谢谢
