### ISSUE TITLE
2.1-gamma 中事务问题

### ISSUE THREAD

**Issue by ww1516123** [baomidou/mybatis-plus#110]
1.当在一个service 中同时操作2个以上的service (在同一个事物中),则会报错,我跟踪到的原因是乐观锁在查找class的时候是eq,而这个时候这个类是spring的代理类 多了一串spring的标注字符。

2.在一个事物中 for循环调用updateById  我需要更新的是1，2，3，4，5 结果成了 1,2,2,2,5

**Comment by Caratacus** [comment]
请贴出详细信息

**Comment by ww1516123** [comment]
问题1
![image](https://user-images.githubusercontent.com/9375531/28454986-d3ad9ae4-6e2f-11e7-8ce4-0ff892a81161.png)

问题2:
![image](https://user-images.githubusercontent.com/9375531/28455019-000e1d5c-6e30-11e7-9638-3e4c5129a923.png)

**Comment by Caratacus** [comment]
这2个问题 你可以打包最新的master代码 已处理

**Comment by qmdx** [comment]
未解决请加入我们群探讨
