### ISSUE TITLE
oracle字段使用""区分大小写,此时mybatisplus当如何处理

### ISSUE THREAD

**Issue by 1432362460** [baomidou/mybatis-plus#1100]
### 当前使用版本(必须填写清楚，否则不予处理)
当前使用版本2.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

oracle表名和字段名未全部大写，查询时需要对字段加""处理，表示区分字段大小写，否则查询不到值。但mybatisplus自动封装的sql语句不会在字段名上添加""，此时该如何处理

**Comment by yuxiaobin** [comment]
oracle什么版本？建表语句，实体什么的贴一点方便排查

**Comment by 1432362460** [comment]
------------------ 原始邮件 ------------------
发件人: "yuxiaobin"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 上午10:54
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com>;
抄送: "衡荣吉"<1432362460@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [baomidou/mybatis-plus] oracle字段使用""区分大小写,此时mybatisplus当如何处理 (#1100)



感谢回复github上的提问。因问题详情中包含截图，所以添加在附件word文档中，详见word文档。

**Comment by qmdx** [comment]
@1432362460  哪有什么附件，不要邮箱回复来 github 补上你的附件

**Comment by 1432362460** [comment]
不好意思。方便留个邮箱吗？我发邮件给你，这里不好贴图和传附件

**Comment by yuxiaobin** [comment]
@1432362460 发 179634696(AT)qq.com

**Comment by 1432362460** [comment]
已发送邮件

**Comment by yuxiaobin** [comment]
如果就一个表，你可以手动把注解加上
比如 @TableName("\"Tbl_user\""), @TableField("\"Username\"")

如果你所有的表都这样，那建议你自定义代码生成的模板，所有字段/表名加转义
