### ISSUE TITLE
分页插件文档写错了吧

### ISSUE THREAD

**Issue by java-aodeng** [baomidou/mybatis-plus#1101]
文档mapper这里传入page 是Pagination
 List<User> selectUserList(Pagination page, Integer state);
实现类使用的时候却是：Page<User> page 的page

**Comment by java-aodeng** [comment]
https://baomidou.gitee.io/mybatis-plus-doc/#/page-plugin  文档地址

**Comment by miemieYaho** [comment]
你看的是 2.0 的文档

**Comment by java-aodeng** [comment]
@miemieYaho 嗯，看到了，3q
