### ISSUE TITLE
没有全部字段的更新和新增方法

### ISSUE THREAD

**Issue by Linhai-Tan** [baomidou/mybatis-plus#1102]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter  3.1.0

请问现在更新和新增的通用crud都是选择性的么，我没有找到全字段更新或新增的方法

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/injector/methods/additional/AlwaysUpdateSomeColumnById.java
