### ISSUE TITLE
 Maven 插件代码生成怎么使用

### ISSUE THREAD

**Issue by qshun** [baomidou/mybatis-plus#1103]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本：3.1.0
内置代码生成器：采用代码或者 Maven 插件可快速生成 Mapper 、 Model 、 Service 、 Controller 层代码，支持模板引擎，更有超多自定义配置等您来使用
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
请问maven插件怎么使用，有使用文档吗？

**Comment by ShammgodYoung** [comment]
这里https://mp.baomidou.com/guide/generator.html

**Comment by miemieYaho** [comment]
插件不再维护,使用 java 代码
