### ISSUE TITLE
调用更新update(Wrapper<T> updateWrapper)不会触发填充

### ISSUE THREAD

**Issue by Linhai-Tan** [baomidou/mybatis-plus#1104]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

调用IService的update(Wrapper<T> updateWrapper)方法不会触发更新填充，是怎么回事啊

**Comment by miemieYaho** [comment]
填充只能填充实体
