### ISSUE TITLE
IdWorker.getId是否分布式中自增

### ISSUE THREAD

**Issue by luguohong** [baomidou/mybatis-plus#1106]
### 当前使用版本
V2.1.9

### 该问题是怎么引起的？
使用时，应用部署在两台服务器，新增时记录了create_time，然后使用IdWorker.getId作为主键值，
但是发现不同服务器生成的Id并不是按照时间有序的，按照雪花算法，long靠前位的应该是时间戳，然后才是机器码，那么应该是按照时间有序的，
但是实践中发现并不是，所以实现不了按照创建时间排序时，优先使用Id排序的方法

我提到问题是否正确？可否优化？

**Comment by miemieYaho** [comment]
无法优化
