### ISSUE TITLE
BaseMapper中如何指定sql的id

### ISSUE THREAD

**Issue by edwards19900128** [baomidou/mybatis-plus#1107]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
希望两个方法指向同一个sql文，请教下如何在BaseMapper中设置注解来绑定xml中的sql

**Comment by miemieYaho** [comment]
xml里写这个method对应的 {selelct,update....}标签以及里面的sql
