### ISSUE TITLE
mybatis-plus配合shardingjdbc使用时的问题

### ISSUE THREAD

**Issue by herryliq** [baomidou/mybatis-plus#1109]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

确切的说，这不是一个bug，但是确实比较坑人，所以提出来，希望能做一下改善。

项目中使用了mybatis-plus作为ORM的框架，在使用shardingjdbc做数据库主从读写分离时，
发现所有的分页查询，都使用了master进行查询，经过debug发现，是PaginationInterceptor类在注册时，没有为dialectType进行赋值，在进行分页处理时，connection.getMetaData()会导致shardingjdbc中取得的DataSource始终为master，没有使shardingjdbc按照正常的时序，通过sql类型的判断来获取正确的DataSource。

`        Connection connection = (Connection) invocation.getArgs()[0];
        DbType dbType = StringUtils.isNotEmpty(dialectType) ? DbType.getDbType(dialectType)
            : JdbcUtils.getDbType(connection.getMetaData().getURL());`

### 对策：
`    	PaginationInterceptor pageInterceptar = new PaginationInterceptor();
    	pageInterceptar.setDialectType("mysql");`

### 改善建议
PaginationInterceptor类构造时，能不能提前为dialectType进行赋值。

**Comment by miemieYaho** [comment]
不能
