### ISSUE TITLE
怎样实现类似于jpa的   @Column(updatable = false, insertable = false)

### ISSUE THREAD

**Issue by liunewshine** [baomidou/mybatis-plus#1110]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 重现步骤
有些字段只在查询时有效，更新或者插入时忽略此字段，无论字段是否赋值。
jap可以注解@Column(updatable = false, insertable = false)实现，mybatis plus有办法实现吗？

**Comment by miemieYaho** [comment]
目前暂时没这么支持

**Comment by yuxiaobin** [comment]
该功能意见添加，暂时还未发版，下一个版本就会有

参考提交：
https://github.com/baomidou/mybatis-plus/commit/e6eccae82814e68284872d69b410fde3da900899
https://github.com/baomidou/mybatis-plus/commit/3d7f80ad44a98a96b9f9896cf35bd0aed51638c2

**Comment by qmdx** [comment]
up

**Comment by xlb** [comment]
所以现在这个版本还没支持吗

**Comment by liunewshine** [comment]
@xlb 3.1.2已经可以了
