### ISSUE TITLE
3.1.1版本 为什么分页强制限制500条？建议提供配置自行设置不要写死！

### ISSUE THREAD

**Issue by wwjjkk** [baomidou/mybatis-plus#1113]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？
PaginationInterceptor中写死了limit=500，强制最多显示500条
        if (limit > 0 && limit <= page.getSize()) {
            page.setSize(limit);
        }

补充： 在一些跑批程序中，希望一次查询的数据量远大于500，建议不要写死改为可配置参数

**Comment by qmdx** [comment]
paginationInterceptor.setLimit(-1） 取消单页限制，这里是为了防止恶意全表搜索，如果你有这种需求全局设置下

**Comment by iiiron** [comment]
这个点为什么不写在文档里面，我要是不来issue里面查，我都不知道原来setLimit就可以了

**Comment by Lzw2016** [comment]
你可以看源码啊，。。。

**Comment by qmdx** [comment]
https://mybatis.plus/guide/page.html
睁大眼仔细看看文档有说明

**Comment by yuxiaobin** [comment]
![image](https://user-images.githubusercontent.com/12861772/62274581-beb03080-b472-11e9-9c60-3398242cd3a7.png)

paginationInterceptor.setLimit(你的最大单页限制数量，默认 500 条，小于 0 如 -1 不受限制);

**Comment by huanghaoming** [comment]
这个我也踩坑了。。。找来找去才发现限制了500.。。应该默认不限制嘛

**Comment by qmdx** [comment]
> 这个我也踩坑了。。。找来找去才发现限制了500.。。应该默认不限制嘛

不限制容易爆掉你的库

**Comment by zhengganglee** [comment]
有没有局部限制方法啊，全局限制可以理解，怎么局部某个查询可以不限制500？

**Comment by 8debug** [comment]
> https://mybatis.plus/guide/page.html 注释部分仔细看看文档有说明

页面挂了
