### ISSUE TITLE
通过主键更新多个字段的时候出现CommunicationsException

### ISSUE THREAD

**Issue by zhuzb1** [baomidou/mybatis-plus#1117]
### 当前使用版本(必须填写清楚，否则不予处理)

spring boot 2.1.4
mybatis plus 3.1.1
mysql 5.7
连接池 hikari

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

1 通过主键更新数据 typeId 是主键
 例如  
![image](https://user-images.githubusercontent.com/8434914/57377615-75cf3f80-71d5-11e9-8cc5-e29b8c12e255.png)
是正常更新的

**2 通过主键更新多个字段的时候**
![image](https://user-images.githubusercontent.com/8434914/57377676-9c8d7600-71d5-11e9-96e1-bdf81a64e3ba.png)
则会出现错误

3 尝试使用 在xml文件之中写sql更新多个字段
是正常更新

4 尝试使用@Select() 
是正常更新

### 重现步骤

当有一个数据库之中出现多个字符串，需要同时被更新会出现以上问题

### 报错信息

![image](https://user-images.githubusercontent.com/8434914/57377843-0148d080-71d6-11e9-9865-75408d7da6ca.png)
![image](https://user-images.githubusercontent.com/8434914/57378033-71575680-71d6-11e9-99eb-779a56a3866d.png)

**Comment by zhuzb1** [comment]
![image](https://user-images.githubusercontent.com/8434914/57428973-35b39f80-725d-11e9-95ce-e9a5224dc154.png)
通过抓包发现出现了 \n\n 如果去掉就可以执行。不知道这个是什么机制。

**Comment by miemieYaho** [comment]
你有复现 demo 吗?

**Comment by zhuzb1** [comment]
应该是网络问题  我们在公网上面安装一个mysql  就没有问题 我在服务器抓包测试一下 打扰了

**Comment by zhuzb1** [comment]
问题找到了 被waf防火墙拦截了 ：
![image](https://user-images.githubusercontent.com/8434914/57432865-934de900-7269-11e9-8c1f-ef2180092da1.png)
拦截理由是：
_黑客在SQL注入中可能会使用/**/作为空格或者使用/*作为注释
当脚本程序使用输入内容来构造动态SQL语句以访问数据库时，会发生SQL注入攻击。_

**Comment by qmdx** [comment]
@zhuzb1  你是不是起初以为是 BUG 后发现是被注入攻击？？  事事是？？
