### ISSUE TITLE
Api文档有误

### ISSUE THREAD

**Issue by yimi88** [baomidou/mybatis-plus#1118]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybaitsplus.version>3.1.1</mybaitsplus.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
https://mybatis.plus/guide/crud-interface.html#savebatch
![image](https://user-images.githubusercontent.com/14154759/57424564-a8674f80-724a-11e9-8f2d-769ced6a40f6.png)

**Comment by miemieYaho** [comment]
ok
