### ISSUE TITLE
[疑惑] 关于queryWrapper 的条件构造器boolean condition设计思想求解惑

### ISSUE THREAD

**Issue by yimi88** [baomidou/mybatis-plus#1119]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybaitsplus.version>3.1.1</mybaitsplus.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
`ge(R column, Object val)`
`ge(boolean condition, R column, Object val)`
在eclipse中为啥没有ge(R column, Object val)方法
![image](https://user-images.githubusercontent.com/14154759/57437994-86cf8d80-7275-11e9-8a59-d26966ca3a7c.png)
`ge(boolean condition, R column, Object val)`
参数：condition 执行条件，的含义我能明白，为啥要有这么一个字段，不理解

**Comment by miemieYaho** [comment]
看文档

**Comment by yimi88** [comment]
结论Mybatis-plus是否要声明一下jdk的使用版本。
ge(R column, Object val)
ge(boolean condition, R column, Object val)
在eclipse中为啥没有ge(R column, Object val)方法
经验证，这种写法只有1.8的jdk才支持，更换jdk1.8后能正常提示了。
`/**
     * ignore
     */
    default Children ge(R column, Object val) {
        return ge(true, column, val);
    }`

![image](https://user-images.githubusercontent.com/14154759/57499294-cea3f280-7311-11e9-9205-14f2f75f5290.png)
![image](https://user-images.githubusercontent.com/14154759/57499495-7a4d4280-7312-11e9-9504-54fd11f7e958.png)

**Comment by qmdx** [comment]
文档仔细看说明了 jdk 1.8+
