### ISSUE TITLE
2.1-gamma代码生成器问题

### ISSUE THREAD

**Issue by yhan219** [baomidou/mybatis-plus#112]
数据库为MySQL。

- 配置逻辑删除，没添加@TableLogic，并且数据库中是tinyint，生成的是Integer。

- 配置表填充字段，不管配置的是什么，生成的都是Insert。且生成的实体类FieldFill类没有自动导入。

配置如下：
`
       strategy.setLogicDeleteFieldName("deleted");
        strategy.setEntityBooleanColumnRemoveIsPrefix(true);
        List<TableFill> tableFillList = new ArrayList<>();
        tableFillList.add(new TableFill("create_time", FieldFill.INSERT));
        tableFillList.add(new TableFill("update_time", FieldFill.UPDATE));
        tableFillList.add(new TableFill("update_user_id", FieldFill.INSERT_UPDATE));
        strategy.setTableFillList(tableFillList);

`

生成如下：
![image](https://user-images.githubusercontent.com/12593660/28497409-f92f417a-6fb8-11e7-9ff6-02ffca599618.png)

**Comment by qmdx** [comment]
该问题已经修复 ， 这周日发布新版 下周一你试试
