### ISSUE TITLE
关于 com.baomidou.mybatisplus.core.toolkit.support.SerializedLambda

### ISSUE THREAD

**Issue by 1397649957** [baomidou/mybatis-plus#1121]
### 版本

3.1.1

你好，请问下，lambda表达式反序列化的时候，为什么要自己实现一个com.baomidou.mybatisplus.core.toolkit.support.SerializedLambda，我尝试使用java的java.lang.invoke.SerializedLambda会报错
![image](https://user-images.githubusercontent.com/35563513/57499320-e8ddd080-7311-11e9-9201-fbef2573637d.png)
请问这里面有什么学问吗？

**Comment by hcl04** [comment]
这个问题相当的复杂，跟 java 中 lambda 的实现方式相关，涉及到的知识点蛮多的。

**Comment by siyuqxxx** [comment]
同问...各种好奇

**Comment by boying** [comment]
同问。我也看到getClass().getDeclaredMethod("writeReplace") https://blog.csdn.net/tengdazhang770960436/article/details/99960693 这篇文章，用这篇文章的方法实现有啥问题吗？
