### ISSUE TITLE
关于与easyexcel集成时的冲突

### ISSUE THREAD

**Issue by qing-yan** [baomidou/mybatis-plus#1122]
### 当前使用版本(必须填写清楚，否则不予处理)

2.1.9
因为是旧项目，所以版本比较老旧

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

由于使用easyexcel时需要实体类继承BaseRowModel类，而该类包含一个私有字段cellStyleMap，使得在执行sql时，会在查询字段中增加一个字段cell_style_map，使数据库报错找不到该字段

### 重现步骤

实体类继承BaseRowModel类，再用mybatisplus进行数据查询

### 报错信息

Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'cell_style_map' in 'field list'

### 可行的解决方案

在数据库中增加字段cell_style_map

**Comment by miemieYaho** [comment]
这属于你的使用问题,自己解决

**Comment by yijiemanong** [comment]
@TableField(exist = false)
    private Map<Integer,CellStyle> cellStyleMap = new HashMap<Integer,CellStyle>();
把他拿到子类中就行了
