### ISSUE TITLE
设置orderByField的aes/desc出错

### ISSUE THREAD

**Issue by Odinysus** [baomidou/mybatis-plus#1123]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.4

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

传orderByField参数, 例如 id aes
最终结果生成 id aes AES 两个aes

**Comment by miemieYaho** [comment]
自己看 page 源码
