### ISSUE TITLE
文档仔细看说明了 jdk 1.8+

### ISSUE THREAD

**Issue by yimi88** [baomidou/mybatis-plus#1124]
文档仔细看说明了 jdk 1.8+

_Originally posted by @qmdx in https://github.com/baomidou/mybatis-plus/issues/1119#issuecomment-491142087_

能贴一下地址吗，我是从https://mybatis.plus/地址看的，您说的文档是哪个

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/install.html#release
