### ISSUE TITLE
基于注解 mapper 接口

### ISSUE THREAD

**Issue by authub** [baomidou/mybatis-plus#1125]
### 当前使用版本(必须填写清楚，否则不予处理)
 <mybatis-plus.version>3.0.6</mybatis-plus.version>
### 重现步骤
 1、 mapper 接口
    @SelectProvider(type = MapperSQL.class, method = "getSql")
    @ResultType(value= com.vo.Entity.class)
    Page<Entity> getEntityPage(Page page, @Param("cond") Map<String, Object> cond);
2、
   class Mapper{
      public String getExamAreaStat(Map<String, Object> cond) {
           ......
           returun sql;
      }
   }
3、
  调用此方法会拦截分页 但是不会讲查出的数据 set 至 records 总数也不会set进去
4、 
  但是
    @SelectProvider(type = MapperSQL.class, method = "getSql")
    @ResultMap("entityMap")//在XML 文件 编写 resultMap 标签 
    Page<Entity> getEntityPage(Page page, @Param("cond") Map<String, Object> cond);
是可以的
5、
@SelectProvider(type = MapperSQL.class, method = "getSql")
    @ResultType(value= com.vo.Entity.class)
    List<Entity> getEntityPage(Page page, @Param("cond") Map<String, Object> cond);
   也是有List 数据返回
### 报错信息
无报错
但是不会返回数据

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-pagination
