### ISSUE TITLE
关于resultType="java.util.LinkedHashMap"

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [baomidou/mybatis-plus#1126]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.8

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

sql查询结果和代码拿到的查询结果顺序不一致

### 重现步骤
<select id="selectBysql"  resultType="java.util.LinkedHashMap">
    ${value}
	</select>
resultType 并没有按LinkedHashMap排序返回。还是按map排序返回。
### 报错信息

没有报错信息

**Comment by miemieYaho** [comment]
去找mybatis
