### ISSUE TITLE
mybatis-plus建议新增数据库关键字段加密插件支持

### ISSUE THREAD

**Issue by jueding920** [baomidou/mybatis-plus#1127]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
建议新增对数据库关键性敏感数据字段提供加密支持（插件形式提供）。
因目前目前网警对企业这块有要求，尤其是用户个人信息，虽然自己实现typeHandler能达到目的，但是CURD的处理方式就比较蛋疼了，需要手动写insert，Update语句，失去了plus原有的初衷。
希望意见给以采纳，谢谢！

### 重现步骤
无

### 报错信息
无

**Comment by miemieYaho** [comment]
拒绝

**Comment by qmdx** [comment]
请使用 TableField  el 属性，具体加密方式啃不会有，后期会对 el 拆解更便捷的使用 typeHandler

**Comment by wzw921001** [comment]
@jueding920  请问一下你是最后采取的是什么方案实现的呢

**Comment by wzw921001** [comment]
@jueding920 请问一下你，你最终是采取什么方案实现的呢
