### ISSUE TITLE
修改表字段后，再次生成问题

### ISSUE THREAD

**Issue by xiangshiming1992** [baomidou/mybatis-plus#1128]
### 当前使用版本(必须填写清楚，否则不予处理)
版本3.1.1
### 该问题是怎么引起的？**
比如用户表之前含有字段 user_id , user_name , sex 三个字段
生成实体 userId  userName sex三个属性，由于业务需要，在模型上加了一个属性lastLoginTime【上次登录时间，并非用户表字段，是登录日志表关联查询set在用户模型，接口返回app用】。
再后来业务需要，数据库加一个字段 email ，重新使用CodeGenerator--> main 方法生成用户表相关东西，
发现，user实体里面的 自己手动加入的 lastLoginTime不见了。

能否像原生的generator那样，在生成的上面有个标识@mbg.generated，自己手动加的不会加上这个，在再次生成的时候可以通过这个判断，是否替换覆盖。

**Comment by yuxiaobin** [comment]
暂不支持

建议生成的代码和真正开发的代码分开，防止出现以上提到的问题
