### ISSUE TITLE
生成实体意见和遇到的小问题

### ISSUE THREAD

**Issue by xiangshiming1992** [baomidou/mybatis-plus#1129]
### 当前使用版本
3.1.1
### 该问题是怎么引起的？
1、希望新增生成实体 对 @Data【lombok】 的支持，少些代码。好看些
2、 gc.setSwagger2(true); //实体属性 Swagger2 注解，，，但是生成的实体中没有import io.swagger.annotations.ApiModelProperty; 需要手动来导一下注解包

**Comment by ShammgodYoung** [comment]
lombok已经有支持了啊
设置下
StrategyConfig strategy = new StrategyConfig();
strategy.setEntityLombokModel(true);

**Comment by qmdx** [comment]
up
