### ISSUE TITLE
springboot 引用mybatis-config.xml 报错 空指针

### ISSUE THREAD

**Issue by lesons** [baomidou/mybatis-plus#113]
![qq 20170724110914](https://user-images.githubusercontent.com/5379514/28506906-46aaf018-7061-11e7-9d56-34db0d97bcc8.png)
![qq 20170724110917](https://user-images.githubusercontent.com/5379514/28506907-46ce07a6-7061-11e7-9ab4-57be7a1352d4.png)
报错代码和配置见图 因为引用mybatis-config.xml 文件之后 没有使用plus的configuration所以这里为空
而如果我2种方式都配置了：
    /**
     * {@inheritDoc}
     */
    @Override
    public void afterPropertiesSet() throws Exception {
        notNull(dataSource, "Property 'dataSource' is required");
        notNull(sqlSessionFactoryBuilder, "Property 'sqlSessionFactoryBuilder' is required");
        state((configuration == null && configLocation == null) || !(configuration != null && configLocation != null),
                "Property 'configuration' and 'configLocation' can not specified with together");

        this.sqlSessionFactory = buildSqlSessionFactory();
    }

此处断言也会过不去，MybatisSqlSessionFactoryBean.java:386行

另外还个问题：还有直接使用Model操作数据乐观锁不生效，iTestTableService操作才会生效

**Comment by lesons** [comment]
另外还个问题：还有直接使用Model操作数据乐观锁不生效，iTestTableService操作才会生效

**Comment by qmdx** [comment]
参考 demo https://git.oschina.net/baomidou/mybatisplus-spring-boot

**Comment by robinwen** [comment]
仍有相同問題. 
當僅配置ybatis-plus.config-location=classpath:mybatis-config.xml
啟動Spring時, 出現null Exception. MybatisPlusAutoConfiguration, line 120, configuration is null.

**Comment by robinwen** [comment]
@qmdx 
仍有相同問題.
當僅配置ybatis-plus.config-location=classpath:mybatis-config.xml
啟動Spring時, 出現null Exception. MybatisPlusAutoConfiguration, line 120, configuration is null.
