### ISSUE TITLE
分页查询 多添加了一个order by语句

### ISSUE THREAD

**Issue by Ahaolin** [baomidou/mybatis-plus#1131]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatis.spring.boot.version>1.3.0</mybatis.spring.boot.version>
 <mybatis.plus.version>2.1.9</mybatis.plus.version>
 <mybatis.mapper.stater>1.1.1</mybatis.mapper.stater>

### 重现步骤
![image](https://user-images.githubusercontent.com/37574890/57612753-fa400a80-75a7-11e9-9745-58a45bcef2ed.png)

执行page.setRecords(baseMapper.selectPage(page, wrapper)); 

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY createDate DESC LIMIT 0,20' at line 6
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY createDate DESC LIMIT 0,20' at line 6

**Comment by atomiCat** [comment]
与#1160相同

**Comment by yuxiaobin** [comment]
2.x版本也已修复。

参考[码云提交](https://gitee.com/baomidou/mybatis-plus/commit/f98e1484ab6f7787bde5925871a4fad8495edd84)

该修复将包含在v2.3.4里面，目前没有正式发2.3.4版
