### ISSUE TITLE
使用动态数据源@DS时，如何通过databaseid调用对应ds的select SQL

### ISSUE THREAD

**Issue by birdle-joe** [baomidou/mybatis-plus#1132]

**Comment by miemieYaho** [comment]
去那边提

**Comment by birdle-joe** [comment]
不好意思，刚刚问题还没写完，应该去哪提呢？ @miemieYaho

**Comment by miemieYaho** [comment]
这还要我来给你? https://github.com/baomidou/dynamic-datasource-spring-boot-starter

**Comment by birdle-joe** [comment]
收到，感谢回复。本人小白，请谅解~




------------------ 原始邮件 ------------------
发件人: "miemieYaho"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 晚上9:02
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com>;
抄送: "～"<164558184@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [baomidou/mybatis-plus] 使用动态数据源@DS时，如何通过databaseid调用对应ds的select SQL (#1132)




这还要我来给你? https://github.com/baomidou/dynamic-datasource-spring-boot-starter
