### ISSUE TITLE
关于自动填充字段报错

### ISSUE THREAD

**Issue by liyang1987jay** [baomidou/mybatis-plus#1133]
### 增加、修改都有问题

![image](https://user-images.githubusercontent.com/4651483/57622802-f8367580-75c0-11e9-8577-9c99219f96e9.png)
![image](https://user-images.githubusercontent.com/4651483/57622823-fff61a00-75c0-11e9-8613-f16449c36447.png)
![image](https://user-images.githubusercontent.com/4651483/57622839-071d2800-75c1-11e9-8bd7-faadfe3f2179.png)

### 重现步骤
1.有一个基础的entity，子类继承父类

### 报错信息
![image](https://user-images.githubusercontent.com/4651483/57622862-12705380-75c1-11e9-8e15-71f574dfc761.png)

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-auto-fill-metainfo
