### ISSUE TITLE
3.1.1版本库找不到com.baomidou.mybatisplus.extension.kotlin 包

### ISSUE THREAD

**Issue by fengshch** [baomidou/mybatis-plus#1136]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/6309911/57668882-84857e80-763b-11e9-9b22-3e4ac24ec38f.png)

### 报错信息
Unresoleved reference: KtQueryWrapper

**Comment by jaysonjh** [comment]
遇到一样的问题

**Comment by hcl04** [comment]
kotlin 上的支持被移除了

**Comment by pop0505** [comment]
> kotlin 上的支持被移除了

为什么会移除kotlin支持呢？如果要在kotlin中使用，请问应该使用哪个版本?

**Comment by qmdx** [comment]
cv 可用版本代码到你的项目， kotlin 无人维护移除
