### ISSUE TITLE
List 无数据

### ISSUE THREAD

**Issue by authub** [baomidou/mybatis-plus#1138]
<mybatis-plus.version>3.0.6</mybatis-plus.version>
 <mybatisplus-spring-boot-starter.version>1.0.5</mybatisplus-spring-boot-starter.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

[第一张](https://github.com/authub/com-cloud/blob/master/txt/1.png)

[第二张](https://github.com/authub/com-cloud/blob/master/txt/2.png)

[第三张](https://github.com/authub/com-cloud/blob/master/txt/2.png)

mapper  接口 
List<ExamWorkerVO> getPageExamWorkerByPlanIdAndPostId(@Param("cond") Map<String, Object> cond);
xml文件
<select id="getPageExamWorkerByPlanIdAndPostId" resultMap="WorkerVOMap">
        SELECT
        w.PROVINCE_ID AS PROVINCE_ID  ,w.NODE_ID AS NODE_ID  , p.POST_NAME AS  POST_NAME ,w.NAME AS `NAME` , w.PHONE_NUMBER AS PHONE_NUMBER
        FROM
        BD_EXAM_WORKER w
        INNER JOIN bd_exam_position p ON p.id = w.POST_ID
        WHERE
        w.POST_ID = #{cond.postId}
        AND w.PLAN_ID = #{cond.planId}
        and w.NODE_ID IN ( #{cond.nodeIds} )
        <if test="cond.nodeId != null and cond.nodeId.trim() != ''">
            AND w.NODE_ID = #{cond.nodeId}
        </if>
        <if test="cond.provinceId != null and cond.provinceId.trim() != ''">
            AND w.PROVINCE_ID = #{cond.provinceId}
        </if>
        order by
        p.sort,
        w.serial_no
    </select>
<resultMap id="WorkerVOMap" type="com.vo.ExamWorkerVO">
        <id property="id" column="ID"/>
        <result property="planId" column="PLAN_ID"/>
        <result property="postId" column="POST_ID"/>
        <result property="nodeName" column="NODE_NAME"/>
        <result property="nodeId" column="NODE_ID"/>
        <result property="provinceId" column="PROVINCE_ID"/>
        <result property="cityName" column="CITY_NAME"/>
        <result property="cityId" column="CITY_ID"/>
        <result property="name" column="NAME"/>
        <result property="phoneNumber" column="PHONE_NUMBER"/>
        <result property="provinceName" column="PROVINCE_NAME"/>
        <result property="postName" column="POST_NAME"/>
    </resultMap>

看图

**Comment by authub** [comment]
https://github.com/authub/com-cloud/blob/master/txt/3.png  第三张图

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples
https://mybatis.plus/config/#mapunderscoretocamelcase

**Comment by authub** [comment]
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    table-underline: true
    db-config:
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

不知道问题在哪里
