### ISSUE TITLE
sharding-jdbc 如何为 mybatis -plus 配置不同的源

### ISSUE THREAD

**Issue by bigkun** [baomidou/mybatis-plus#1139]
### 当前使用版本 mybatis-plus 3.1.0， sharding-jdbc 4.0.0 RC1
如何为mybatis-plus 针对单库配置一个数据源， 对于分片数据源使用sharding-jdbc 也集成到mybatis-plus，配置另外的数据源。 这样 非分片场景使用原生数据源及连接，分片场景mybatis通过sharding-jdbc进行数据操作。

**Comment by miemieYaho** [comment]
自己研究

**Comment by qmdx** [comment]
try https://mybatis.plus/guide/dynamic-datasource.html
