### ISSUE TITLE
连续执行2次更新操作报错，

### ISSUE THREAD

**Issue by lesons** [baomidou/mybatis-plus#114]
![image](https://user-images.githubusercontent.com/5379514/28523419-e93db28c-70ae-11e7-95e7-7271223b4871.png)

追后的代码行是：SqlExplainInterceptor
![image](https://user-images.githubusercontent.com/5379514/28523511-6aaf3494-70af-11e7-9ed4-c61f1127e08d.png)

环境mysql5.7，用5.1是正常的，不清楚是什么原因

**Comment by qmdx** [comment]
把 sql 拿出去执行看看

**Comment by lesons** [comment]
可以执行的。就放到这里用这个分析器执行就不行 其他的都ok，我把分析器插件关掉就可以用了

**Comment by qmdx** [comment]
请注意说明 http://mp.baomidou.com/#/execution-analysis-plugin  只支持 mysql 5.6.3 以上。
