### ISSUE TITLE
@TableField(condition=SqlCondition.LIKE)不兼容Mysql数据库

### ISSUE THREAD

**Issue by dawn-tangzedong** [baomidou/mybatis-plus#1143]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter-version：3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
@TableField(value = "MC",condition = SqlCondition.LIKE)
SqlCondition.Like是使用"%s LIKE CONCAT('%%',#{%s},'%%')"
MySql中CONCAT函数只支持两位参数，因此为出现参数个数不正确异常

### 重现步骤
@TableField加入condition = SqlCondition.LIKE并使用QueryWapper查询

### 报错信息
Caused by: java.sql.SQLSyntaxErrorException: ORA-00909: 参数个数无效

**Comment by miemieYaho** [comment]
condition 类型是 string,自己看着处理
