### ISSUE TITLE
baseMapper.updateById(entity)源码实现

### ISSUE THREAD

**Issue by lemoncy** [baomidou/mybatis-plus#1144]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
请问下，mybatis plus 这个公共方法实现类是在哪里？
baseMapper.updateById(entity)

**Comment by miemieYaho** [comment]
UpdateById
