### ISSUE TITLE
可以降mybatis的版本吗

### ISSUE THREAD

**Issue by 1397649957** [baomidou/mybatis-plus#1146]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

你好，这个版本的mbp有没有强依赖 mybatis 3.5.1版本，高版本的mybatis的jdbc 4.1语法，druid有些不支持   降到3.4.6可以吗

**Comment by qmdx** [comment]
no 请换掉你的 druid 为 Spring 自带的 HikariCP

**Comment by 1397649957** [comment]
你好，我自行换掉mybatis 的版本对 3.1.1版本的mbp有影响吗，如果换数据库池的话，还需要跟架构沟通一下。

**Comment by hnwkz** [comment]
我也遇到同样问题
