### ISSUE TITLE
FieldStrategy 是否支持insert时使用IGNORED策略，update时使用NOT_NULL策略？

### ISSUE THREAD

**Issue by ltylty** [baomidou/mybatis-plus#1149]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
由于mysql的STRICT_TRANS_TABLES策略，很多字段都要insert为null。但是update时还是希望null的字段不要更新。现在的FieldStrategy 的全局配置能否支持insert时使用IGNORED策略，update时使用NOT_NULL策略？

**Comment by miemieYaho** [comment]
你这种全局默认 NOT_NULL 就行了,insert 时你 set null 和你不 set 结果都是一样的,除非你数据库字段有默认值

**Comment by ltylty** [comment]
SQL语句：show CREATE TABLE olap_chart_dimension;
执行结果如下
CREATE TABLE `olap_chart_dimension` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `group` varchar(50) DEFAULT NULL,
  `chart_id` int(11) NOT NULL,
  `table_id` int(11) NOT NULL,
  `alias_name` varchar(50),
  `order` int(11),
  `number` smallint(6),
  PRIMARY KEY (`id`),
  KEY `olap_chart_dimension_1fc93cbf` (`chart_id`),
  KEY `olap_chart_dimension_a15b1ede` (`table_id`),
  CONSTRAINT `olap_chart_dimension_chart_id_21b0bbbd1ac40b67_fk_olap_chart_id` FOREIGN KEY (`chart_id`) REFERENCES `olap_chart` (`id`),
  CONSTRAINT `olap_chart_dimensi_table_id_5b2bc70c1468c913_fk_olap_ds_table_id` FOREIGN KEY (`table_id`) REFERENCES `olap_ds_table` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7437 DEFAULT CHARSET=utf8

SQL语句：INSERT INTO olap_chart_dimension ( name, chart_id, table_id, number ) VALUES ( 'timeline', 747, 1375, 0 ) ;
执行报错，结果如下
[Err] 1364 - Field 'alias_name' doesn't have a default value

SQL语句：INSERT INTO olap_chart_dimension ( `name`, chart_id, table_id, number , alias_name , `order`) VALUES ( 'timeline', 578, 1375, 0 , null, null) ;
执行成功，插入一条数据。

所以我想要的是即使字段为null也要拼在SQL语句中，不然在STRICT_TRANS_TABLES策略下有时候会报错。

**Comment by ltylty** [comment]
@miemieYaho

**Comment by miemieYaho** [comment]
那就等后面更新的版本,https://github.com/baomidou/mybatis-plus/issues/1110
