### ISSUE TITLE
打算选择PostgreSQL数据库，使用SCHEMA来设计多租户，未能支持

### ISSUE THREAD

**Issue by imyundong** [baomidou/mybatis-plus#115]
不知道能不能支持，或者有其它的方案介绍一下，十分感谢。

**Comment by qmdx** [comment]
SCHEMA 级别不错，想想会不会太大设计上， mp 内部有一个租户插件正在开发中，计划表行级。你可以加入我们群讨论，目前还不能用于生产后面稳定后会推出 https://github.com/baomidou/mybatis-plus/tree/master/src/main/java/com/baomidou/mybatisplus/plugins/tenancy  如果急着使用可以PR贡献

**Comment by qmdx** [comment]
mp 最新版本2.1.1-SNAPSHOT 支持多租户 SQL 自动解析，参考 demo   https://git.oschina.net/baomidou/mybatisplus-spring-boot   对应于  SCHEMA  模式一样的你可以参考目前的 SQL解析器 ，自定义下 解析类既可以支持，  更多疑问加入我们 群交流， 也可以 pr 贡献
