### ISSUE TITLE
cannot access com.baomidou.mybatisplus.core.mapper.BaseMapper

### ISSUE THREAD

**Issue by jiayikoupdz** [baomidou/mybatis-plus#1152]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
自定义了一个BaseMapper继承了mp的BaseMapper. 当自己serviceImpl的时候，出现这个提醒错误。但是代码能跑起来不报错。

### 重现步骤
1.自定了一个通用接口。 没有使用Iservice
public interface IBasevice<T extends BaseEntity>
自定义了一个baseServiceImpl的实现
public class BaseviceImpl<M extends BaseMapper<T>, T extends BaseEntity> implements IBasevice<T>{

    protected Log log = LogFactory.getLog(getClass());

    @Autowired
    protected M baseMapper;

    @Override
    public M getBaseMapper() {
        return baseMapper;
    }
自定义了一个BaseMapper集成了mp的BaseMapper
public interface BaseMapper<T extends BaseEntity> extends com.baomidou.mybatisplus.core.mapper.BaseMapper<T> {
}
 在这里实现的时候就提醒错误
public class RoleServiceImpl extends BaserviceImpl<RoleMapper,Role> implements IRoleService 
![image](https://user-images.githubusercontent.com/50577209/58007810-a0968d80-7b1d-11e9-9522-dabf9ecf8ee2.png)

但是代码打包编译都没问题。只是这个提醒一直在。

### 报错信息
cannot access com.baomidou.mybatisplus.core.mapper.BaseMapper

**Comment by miemieYaho** [comment]
你自己的使用问题,自己找
