### ISSUE TITLE
IN( .......) Sql 语句的问题

### ISSUE THREAD

**Issue by authub** [baomidou/mybatis-plus#1153]
<mybatis-plus.version>3.1.1</mybatis-plus.version>
在使用   IN( .......) Sql 语句的问题
SELECT
	x.ROOM_COUNT AS roomCount,
	y.INSTALL_COUNT AS installCount 
FROM
	( SELECT COUNT( 1 ) ROOM_COUNT FROM pf_plan_room r WHERE r.plan_id = 'ouipoi4qb65ZWB6SXQ4Ax9SCMtZjUudi' ) x,
	( SELECT COUNT( 1 ) INSTALL_COUNT FROM pf_plan_room pr WHERE pr.PLAN_ID = 'ouipoi4qb65ZWB6SXQ4Ax9SCMtZjUudi' AND pr.room_id IN ( ...... ) ) y
已确认这条SQL在数据库执行 两个字段都会 大于 0  而在  mybatis-plus xml文件执行同一样的Sql 第二个参数反射进去为 0  
当我直接在xml 文件写死  用 = 就不会出现上面的问题

**Comment by miemieYaho** [comment]
mp 只负责我们提供的通用 crud 的 sql 生成注入的 mybatis,具体执行 sql 是 mybatis 的事,自己检查
