### ISSUE TITLE
springboot启动缓慢，启动总耗时61s左右其中addMappedStatement耗时35s左右

### ISSUE THREAD

**Issue by alterhu2020** [baomidou/mybatis-plus#1154]
### 当前使用版本(必须填写清楚，否则不予处理)
版本号： 3.1.0

### 重现步骤
添加maven依赖后，启动springboot工程

### 报错信息

**_2019-05-21 10:01:03.796_** [restartedMain] DEBUG org.mybatis.spring.SqlSessionFactoryBean.debug:49 - Parsed mapper file: 'file [D:\GitRepository\yitieyilu.com\ROOT\YanZhiServices\vrpanoapp\target\classes\mapper\generator\WxUserMapper.xml]'
**2019-05-21 10:01:10.424** [restartedMain] DEBUG com.baomidou.mybatisplus.core.MybatisConfiguration.addMappedStatement:85 - addMappedStatement: com.yanzhi.vrpanoapp.mapper.generator.SysUserRegistrationCodeMapper.insert

**2019-05-21 10:01:10.673** [restartedMain] DEBUG com.baomidou.mybatisplus.core.MybatisConfiguration.addMappedStatement:85 - addMappedStatement: com.yanzhi.vrpanoapp.mapper.generator.SysUserRegistrationCodeMapper.selectPage
2019-05-21 10:01:30.362 [restartedMain] WARN  org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter.afterPropertiesSet:302 - Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)
2019-05-21 10:01:31.268 [restartedMain] DEBUG springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping.initHandlerMethods:54 - initialising the handler methods

**2019-05-21 10:01:36.515** [restartedMain] DEBUG com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.afterPropertiesSet:263 - No org.mybatis.spring.mapper.MapperFactoryBean found.
2019-05-21 10:01:42.428 [restartedMain] DEBUG reactor.core.publisher.Hooks.debug:249 - Enabling stacktrace debugging via onOperatorDebug

你会发现在 **2019-05-21 10:01:03.796**耗时7s左右，**2019-05-21 10:01:10.673**时间的时候，addMappedStatement耗时20s左右，在**2019-05-21 10:01:36.515** 总耗时6s左右，这些是最耗时的一些执行锻，还不包含其他的mybatis-plus运行时间, 项目启动总耗时是61s左右，而mybatis总耗时35秒左右。。。。

这个加入mybatis-plus后，项目整体启动拖慢了将近一倍。。。
不知道有没有人有遇到这个问题。

**Comment by miemieYaho** [comment]
你用 mp 和mybatis比?MappedStatement数量都不一样,你该换电脑了

**Comment by yrain** [comment]
确实是很慢.请作者还是重视这个问题
ps:不是电脑配置差.

**Comment by Pengap** [comment]
同样有所感觉，启动慢，目前版本3.3.2

**Comment by R-anybbo** [comment]
是特别的慢, 我启动总共30s+, mp总共用了16s 用的版本也是 3.3.2

**Comment by xbox1994** [comment]
我也碰到了，非常明显的问题，作者就是个废物还死嘴硬

**Comment by easy-wly** [comment]
同问，该如何解决启动慢的问题，用的版本是3.4.3.4

**Comment by w-tomato** [comment]
确实特别慢，还回复个换电脑，我换太湖之光都拯救不了你这玩意，嘴真硬

**Comment by mark4z** [comment]
确实慢，改天我瞅瞅能不能修一下

**Comment by yungsem** [comment]
非常慢，为什么close了，解决了吗

**Comment by qmdx** [comment]
> 非常慢，为什么close了，解决了吗

mp 是启动的时候注入的 SQL 如果表非常多会存在慢的情况

**Comment by isaacwu666** [comment]
启动了一个数据中心 用了249.867秒。谢谢啊

**Comment by ningmengwork** [comment]
3.3.2 是有bug吧？怎么启动这么慢，一直在 addMappedStatement

**Comment by zongrenzhou** [comment]
启动时mybatis-plus很慢，是因为卡在创建
com.baomidou.mybatisplus.core.toolkit.Sequence 这个类的构造方法里面
最终定位在这两个方法上面。
 NetworkInterface network = NetworkInterface.getByInetAddress(ip);
  String name = ManagementFactory.getRuntimeMXBean().getName();
都是获取网络名称，原因是host名字配置不一样，导致没法用缓存。

scutil --set HostName $(scutil --get LocalHostName)
设置成一样就可以了
