### ISSUE TITLE
Sqlserver2008r2 自增主键无法获取

### ISSUE THREAD

**Issue by tmjGitAccount** [baomidou/mybatis-plus#1159]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库：sqlserver 2008 
表主键ID
数据类型：uniqueidentifier
已配置 NEWID() 自动生成
### 重现步骤
实体中字段 String  id 
注解 @TableId(value = "ID",type = IdType.AUTO)
使用MP BaseMapper中的insert方法
### 报错信息
无报错信息，但自增主键无法通过getId()获取。
请问是否是我配置有误？还是不支持？

**Comment by qmdx** [comment]
2008 太老了吧！ 你换成idworker 策略吧
