### ISSUE TITLE
3.x和2.x PaginationInterceptor.java 分页组件，当sql 里 同时存在group by 和order by，且IPage 参数中存在排序属性时，拼接出来的sql会出现两个order by

### ISSUE THREAD

**Issue by atomiCat** [baomidou/mybatis-plus#1160]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1和2.x均存在此问题

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

PaginationInterceptor.java 分页组件，当sql 里 同时存在group by 和order by，且IPage 参数中存在排序属性(page.ascs()有内容)时，拼接出来的sql会出现两个order by，导致语法错误
183行 String buildSql = concatOrderBy(originalSql, page, orderBy);
建议改为 
String buildSql = SqlUtils.concatOrderBy(originalSql, page, !originalSql.toUpperCase().contains(" ORDER BY "));
，当sql中存在order by ，忽略IPage 中的排序属性

**Comment by yuxiaobin** [comment]
“当sql 里 同时存在group by 和order by” -- 这个是自定义SQL？还是MP的wrapper生成的条件？

**Comment by atomiCat** [comment]
mapper.xml里写的自定义sql

**Comment by atomiCat** [comment]
> “当sql 里 同时存在group by 和order by” -- 这个是自定义SQL？还是MP的wrapper生成的条件？

mapper.xml里写的自定义sql

**Comment by yuxiaobin** [comment]
收到，谢谢反馈

**Comment by yuxiaobin** [comment]
已修复。

参考[码云提交](https://gitee.com/baomidou/mybatis-plus/commit/6a7ad176e32f338ab76901f08423e07eabe3b8a2)
