### ISSUE TITLE
3.1.0或者3.1.1乐观锁不生效

### ISSUE THREAD

**Issue by w10511026** [baomidou/mybatis-plus#1161]
3.1.1 & 3.1.0

原代码：

@Bean
public OptimisticLockerInterceptor optimisticLockerInterceptor() {
    return new OptimisticLockerInterceptor();
}

@Version
private Integer version;

int id = 100;
int version = 2;

User u = new User();
u.setId(id);
u.setVersion(version);
u.setXXX(xxx);

if(userService.updateById(u)){
    System.out.println("Update successfully");
}else{
    System.out.println("Update failed due to modified by others");
}

### 报错信息

执行打印的sql： 
UPDATE erp_user SET age=1, version=2 WHERE id=1

**Comment by miemieYaho** [comment]
你用的哪个starter?

**Comment by w10511026** [comment]
mybatis-plus-boot-starter,  springboot版本是 2.1.5.RELEASE

**Comment by w10511026** [comment]
> 你用的哪个starter?
mybatis-plus-boot-starter, springboot版本是 2.1.5.RELEASE

**Comment by w10511026** [comment]
在OptimisticLockerInterceptor类的dealUpdateById打了断点，没有进断点

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-optimistic-locker 你的问题无法复现
