### ISSUE TITLE
select 语句，如果属性带“.” ，结果被拆开

### ISSUE THREAD

**Issue by guan25** [baomidou/mybatis-plus#1163]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

select 语句，如果属性带“.” listMap查询出的结果，就会从“.” 的地方拆开了

### 重现步骤
![image](https://user-images.githubusercontent.com/5926540/58103777-2269e200-7c16-11e9-99a0-682379c9375b.png)

![image](https://user-images.githubusercontent.com/5926540/58103968-8096c500-7c16-11e9-8c27-f9a48c6a7468.png)

**Comment by miemieYaho** [comment]
数据封装是mybatis的事,mp不负责数据封装

**Comment by yuxiaobin** [comment]
sql语句加一个别名 
sum(xxx.xxx) as xxx

**Comment by guan25** [comment]
> sql语句加一个别名
> sum(xxx.xxx) as xxx

感谢：）
