### ISSUE TITLE
无法读取json

### ISSUE THREAD

**Issue by tuzizhanzhu** [baomidou/mybatis-plus#1166]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无法读取json

### 重现步骤
数据库使用json类型
自定义basetypehandler

可以写入。无法读取  
json类型为set《string》
查询结果为null

**Comment by miemieYaho** [comment]
读取需要 typehandler,非类型精准配置要写 resultmap

**Comment by tuzizhanzhu** [comment]
啥意思？ 文档也说不清

**Comment by miemieYaho** [comment]
mybatis 常识

**Comment by tuzizhanzhu** [comment]
你这个不是能不用xml嘛？还是要结合xml使用？

**Comment by yuxiaobin** [comment]
建议你debug一下，json类型的字段被哪个typeHandler处理了

是typeHandler的注册顺序问题导致还是类型判断的问题

**Comment by tuzizhanzhu** [comment]
@tablefield 里面配置了el 但是却只能写不能读。这不算是个bug吗？？ 用xml配置就能读
