### ISSUE TITLE
el属性bug

### ISSUE THREAD

**Issue by tuzizhanzhu** [baomidou/mybatis-plus#1167]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.9

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
@tablefield 里面配置了el 但是却只能写不能读。这不算是个bug吗？？ 用xml配置就能读

### 重现步骤

参考上面步骤 配置type之后 能写数据 不能读取 
### 报错信息

设置了el的属性字段被直接忽略了。 mybatis没有读取对应的 typehandler

**Comment by miemieYaho** [comment]
就是这样的

**Comment by redfish110** [comment]
新版本mybatis-plus的@TableField是不是已经废弃了el属性，官方文档没有对这个属性的更新进行说明，容易造成误解
