### ISSUE TITLE
更新的时候不能自动填充公共字段

### ISSUE THREAD

**Issue by samyanggo** [baomidou/mybatis-plus#117]
tableInfo = TableInfoHelper.getTableInfo(et.getClass());
et是HashMap类型，返回tableInfo是null,进入populateKeys后由于tableInfo是null直接返回了，没有自动填充。

**Comment by samyanggo** [comment]
原因好像是加了乐观锁的关系，用了@Version注解，就出现上面的问题了。

**Comment by yuxiaobin** [comment]
该问题已经修复，今天会发一版，发好有就可以用最新版解决该问题。

Refer to #100
