### ISSUE TITLE
分页查询时，分页超过总记录数。怎么将设置当前页为1.

### ISSUE THREAD

**Issue by luleipo** [baomidou/mybatis-plus#1171]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>2.3</version>
            
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无条件查询时（select * from a）查询结果为12条。size=10；
在页面上点到第2页。然后输入查询条件点查询。select * from a where a.name = 1。结果为5条。
但是前台传到后台的page中current为2。导致mybatis-plus查询时，从第十条数据开始查询。查询十条数据。SQ为：select * from a where a.name = 1 limit 10 offset 10;
故，得到的结果为0条数据。

### 重现步骤
无条件查询时（select * from a）查询结果为12条。size=10；
在页面上点到第2页。然后输入查询条件点查询。select * from a where a.name = 1。结果为5条。
但是前台传到后台的page中current为2。导致mybatis-plus查询时，从第十条数据开始查询。查询十条数据。SQ为：select * from a where a.name = 1 limit 10 offset 10;
故，得到的结果为0条数据。

### 报错信息

得到的结果为0条数据。

**Comment by atomiCat** [comment]
感觉这种问题应该在前端处理，查询条件发生变化应该查询第一页而不是留在当前页

**Comment by qmdx** [comment]
里面有一个开关这是防止异常的，你可以在 PaginationInterceptor 设置 overflow 参数

**Comment by luleipo** [comment]
@Configuration
public class MybatisPlusConfig {
    
    @Bean
    public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor page = new PaginationInterceptor();
        page.setOverflowCurrent(true);
        return page;
    }
}
写了一个配置类解决问题。感谢2楼。
