### ISSUE TITLE
insert报错

### ISSUE THREAD

**Issue by zhidongluo** [baomidou/mybatis-plus#1172]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.9

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

数据表设置了主键，但是没有使用自增模式，在insert实体类的时候，该实体类已经设置了id，但是insert 报错

### 报错信息
Cause: java.sql.SQLException: Field 'f_id' doesn't have a default value

**Comment by qmdx** [comment]
打印你的 sql 排查，注意点： 主键策略如果是自增 数据库需要设置， 其他策略查看以输出 sql 为准，查看升级日志是否该版本有该问题 BUG 如果存在升级为2 x 最新
