### ISSUE TITLE
建议：com.baomidou.mybatisplus.autoconfigure.MybatisPlusProperties#globalConfig.dbconfig.idType中默认值不采用.id_worker

### ISSUE THREAD

**Issue by fanlushuai** [baomidou/mybatis-plus#1174]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用@TableId注解，使用注解默认值idType。即None
然而在insert的时候。竟然采用了DbConfig.idType=id_worker.
之后发现。默认的dbconfig.idType会id_worker。逻辑上又会将None转成id_woker。
这样很容易使得使用者。以为设置idType.None。然而不是。出现问题。
建议：dbConfig.idType不再指定默认值。使用者如果需要，再自己指定。解决这种尴尬易发生的问题。

**Comment by miemieYaho** [comment]
NONE 为跟随全局,后面会更新注释

**Comment by fanlushuai** [comment]
> NONE 为跟随全局,后面会更新注释

感觉，局部优先级>全局肯定优先级。局部不指定，就采用全局。全局不指定。就没有。应该是这种自动的逻辑。而不是说，局部还得指定None，才能跟随全局。
如果说，None为跟随全局。那么我觉得None是没有必要的

**Comment by miemieYaho** [comment]
不需要局部指定,默认跟随全局.注解里给这个一个默认值

**Comment by fanlushuai** [comment]
> 不需要局部指定,默认跟随全局.注解里给这个一个默认值

我的理解是，None是。框架不干预这个字段的id值。只是。在findyId这种场景下。使用某个非数据库id的属性。使其能作为参数。相当于"虚拟的id"。
