### ISSUE TITLE
配置 type-aliases-package 后，与 mbg 中的 *Example$Criterion 类不兼容

### ISSUE THREAD

**Issue by keenorchen** [baomidou/mybatis-plus#1175]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在已有的 mybatis 工程（使用了MBG，并自动生成了*Example类）上新增 mybatis plus 的配置并使用。
在增加 type-aliases-package 的设置后出现问题，原项目未出现此问题。
其中，Criterion 是 *Example 的内部类

### 重现步骤
在原有mybatis的项目上（使用了MBG，并自动生成了各种 *Example类）新增 mybatis plus 配置，并使用了一下配置，
`mybatis-plus:
  type-aliases-package: com.example.mybatis3cp.pojo.po
`
从而导致下面的错误。

### 报错信息

Caused by: org.apache.ibatis.type.TypeException: The alias 'Criterion' is already mapped to the value 'com.example.mybatis3cp.pojo.po.AccountTxPoExample$Criterion'.

**Comment by miemieYaho** [comment]
type-aliases-package 我们没对源码进行改动,就是说你用 mybatis 的 starter 一样会这样,自行解决

**Comment by keenorchen** [comment]
你好，原有项目的配置：
`mybatis:
  typeAliasesPackage: com.example.mybatis3cp.pojo.po
`
这样配置是没有任何问题的，只是我把 原来 mybatis: 的配置项挪到了 mybatis-plus: 下面，
`mybatis-plus:
  typeAliasesPackage: com.example.mybatis3cp.pojo.po
`

才出现的兼容性问题。
虽然mybatis plus 没有改动源码，目前确实是与 *Example 类是有冲突的。
谢谢解答

**Comment by miemieYaho** [comment]
报错类就是mybatis自己的，可能mybatis升级版本后不再你那么支持了

**Comment by keenorchen** [comment]
确实如此，此问题在 最新的 mybatis 3.5.1 下才有，3.5.0 就没有此问题，而 mybatis plus 最新版是 3.1.1，依赖的正是 mybatis 3.5.1，所以才导致 *Example 类报错。
谢谢。我回退到   3.5.0 对应的 mybatis plus 吧

**Comment by keenorchen** [comment]
不好意思，也有可能是 mbg 的 bug，因为 *Example 是 mbg 生成的，或者他们不兼容。我再查查原因看
