### ISSUE TITLE
请教下sql 分页性能

### ISSUE THREAD

**Issue by B0B02333** [baomidou/mybatis-plus#1180]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
下面这个类
com.baomidou.mybatisplus.extension.plugins.pagination.dialects.OracleDialect 

 @Override
    public DialectModel buildPaginationSql(String originalSql, long offset, long limit) {
        limit = (offset >= 1) ? (offset + limit) : limit;
        String sql = "SELECT * FROM ( SELECT TMP.*, ROWNUM ROW_ID FROM ( " +
            originalSql + " ) TMP WHERE ROWNUM <=" + FIRST_MARK + ") WHERE ROW_ID > " + SECOND_MARK;
        return new DialectModel(sql, limit, offset).setConsumerChain();
    }

这个的“SELECT *” 星号会不会影响查询的性能问题，虽然originalSql里面的select使用的是字段，但是这个外面却使用星号，有些不解这个地方的设计想法？

**Comment by miemieYaho** [comment]
这是oracle的分页语句,有异议欢迎pr

**Comment by B0B02333** [comment]
> 这是oracle的分页语句,有异议欢迎pr

抱歉，刚刚继续读了下源码，看到有提供自定义的方法扩展方法getDialect(DbType dbType, String dialectClazz)；
