### ISSUE TITLE
LambdaUtils工具类疑问

### ISSUE THREAD

**Issue by tfwx** [baomidou/mybatis-plus#1183]
### 该问题是怎么引起的？
在看MybatisPlus解析lambda表达式时看到这样一段源码

`
public final class LambdaUtils {

    private static final Map<Class, WeakReference<SerializedLambda>> FUNC_CACHE = new ConcurrentHashMap<>();

    /**
     * <p>
     * 解析 lambda 表达式
     * </p>
     *
     * @param func 需要解析的 lambda 对象
     * @param <T>  类型，被调用的 Function 对象的目标类型
     * @return 返回解析后的结果
     */
    public static <T> SerializedLambda resolve(Property<T, ?> func) {
        Class clazz = func.getClass();
        return Optional.ofNullable(FUNC_CACHE.get(clazz))
            .map(WeakReference::get)
            .orElseGet(() -> {
                SerializedLambda lambda = SerializedLambda.convert(func);
                FUNC_CACHE.put(clazz, new WeakReference<>(lambda));
                return lambda;
            });
    }
}
`

LambdaUtils的resolve方法在解析lambda表达式时，都将结果进行了缓存，存在 FUNC_CACHE 里，但是 func.getClass() 作为key却是不合理的，对于lambda表达式来讲，即使是相同的lambda表达式，获取到的class却是不一样的

下面是我的一段测试代码，清楚的看到相同的 lambda 表达式获取的class根本不一样，而FUNC_CACHE 缓存的意义又在哪里，LambdaUtils每次解析 lambda表达式时， 都无法获取已缓存过的结果 ，而 FUNC_CACHE 却又总是不断缓存？？？
`Function<Person,` Long> func = Person::getId;
 System.out.println(func.getClass());		// 执行结果: class com.demo.Test$$Lambda$1/896681694
 func = Person::getId;
 System.out.println(func.getClass());		// 执行结果: class com.demo.Test$$Lambda$2/706277948`

**Comment by devcolt** [comment]
同问，没有老大解析下

**Comment by hcl04** [comment]
这个解决的主要是并发下的性能问题。

至于为什么用 class 做 key，这里缓存主要是要省去序列化的过程，除了 class 其他信息都是要序列化之后才能拿到。

**Comment by yuxiaobin** [comment]
`@Test`
    `public` void testFunc() {
        `for(int` i=0;i<10;++i){
            `a();`
        `}`
    `}`

    `public void a(){`
        `Function<Person, String> f = Person::getId;`
        `System.out.println(f.getClass());`
   ` }`

从这个测试可以看出，是同一个class
可以理解为：代码编译完，这个class就是确定的

**Comment by tfwx** [comment]
> `@Test`
> `public` void testFunc() {
> `for(int` i=0;i<10;++i){
> `a();`
> `}`
> `}`
> 
> ```
> `public void a(){`
>     `Function<Person, String> f = Person::getId;`
>     `System.out.println(f.getClass());`
> ```
> 
> `}`
> 
> 从这个测试可以看出，是同一个class
> 可以理解为：代码编译完，这个class就是确定的

但是如果在不同的代码位置，多次使用了这个Function，，它们的class是不同的，这样，FUNC_CACHE 缓存里，就会保留Person::getId的多个缓存副本

**Comment by tfwx** [comment]
相同的Function函数如果在不同的代码位置出现，依然会被重复解析，缓存则无效

**Comment by hcl04** [comment]
但是当你第二次调用这个方法，缓存不就有效了？

**Comment by devcolt** [comment]
受教了🙏，还有个疑问，调用地方多了，FUNC_CACHE 会不会好庞大？

**Comment by tfwx** [comment]
> 但是当你第二次调用这个方法，缓存不就有效了？lambda 不是方法引用，只是 Java 让他看起来像方法引用。Lambda 其实就是一种语法糖，你写到不同的地方，就是不同的对象。
> 
> 我们只能尽可能帮你提高性能。

嗯嗯，确实是这样。但是还有另一个问题，LambdaUtils.resolve函数是先get，再put，完成缓存，但是在高并发下，同一个Function是不是会有可能被多次解析，由于get不到，又同时被多个线程同时解析，再多次缓存，那么ConcurrentHashMap的作用体现在何处？

**Comment by tfwx** [comment]
> 受教了🙏，还有个疑问，调用地方多了，FUNC_CACHE 会不会好庞大？

这个确实，虽然在GC发生后，WeakReference包裹的SerializedLambda对象会被回收，但是，WeakReference对象本身，依然没有被清除，还占用着内存

**Comment by hcl04** [comment]
会。目前我们只考虑了 Value 弱引用，既然你们提出了这个问题，我们下一步考虑把这个缓存的键改成弱键（参考 WeakReference、WeakHashMap ），以便在 GC 发生时回收这里的 Entry。目前只回收 Value，但是 key 是在的。HashMap 有扩容机制，但并没有 entry 回收时回收容量的设定，所以当时考虑是认为意义不大，只是回收了较大的那个。再加上我们使用 class 作 key，这意味着这个 key 几乎不可能被回收），这一点我们也希望你们能给点建议。

至于为什么使用 ConcurrentHashMap ，因为这个方法是静态的，静态的就可能被多个线程访问问题，虽然为了避免 map 在多线程操作下数据丢失（java8 以前会死锁）的问题，因此使用了 ConcurrentHashMap 。

重点：为了避免 map 在多线程操作下数据丢失（java8 以前会死锁）的问题

但是这个方法在操作的时候，并不是原子性的，所以你们反映的会有多个线程 put 进一个 key 确实存在，我们前面尝试把这个静态方法改为原子性的（加锁或使用 ConcurrentHashMap  提供的 compute 方法），均发现性能出现大幅度下降，于是就去掉了。这里前后两次的结果并没有依赖关系，所以，即使不是原子性的，这里代码仍然是线程安全的（他在多线程环境与单线程环境下表现一致。）。

**Comment by tfwx** [comment]
> 会。目前我们只考虑了 Value 弱引用，既然你们提出了这个问题，我们下一步考虑把这个缓存的键改成弱键（参考 WeakReference、WeakHashMap ），以便在 GC 发生时回收这里的 Entry。目前只回收 Value，但是 key 是在的。HashMap 有扩容机制，但并没有 entry 回收时回收容量的设定，所以当时考虑是认为意义不大，只是回收了较大的那个。再加上我们使用 class 作 key，这意味着这个 key 几乎不可能被回收），这一点我们也希望你们能给点建议。
> 
> 至于为什么使用 ConcurrentHashMap ，因为这个方法是静态的，静态的就可能被多个线程访问问题，为了避免 map 在多线程操作下数据丢失（java8 以前会死锁）的问题，因此使用了 ConcurrentHashMap 。
> 
> 重点：为了避免 map 在多线程操作下数据丢失（java8 以前会死锁）的问题
> 
> 但是这个方法在操作的时候，并不是原子性的，所以你们反映的会有多个线程 put 进一个 key 确实存在，我们前面尝试把这个静态方法改为原子性的（加锁或使用 ConcurrentHashMap 提供的 compute 方法），均发现性能出现大幅度下降，于是就去掉了。这里前后两次的结果并没有依赖关系，所以，即使不是原子性的，这里代码仍然是线程安全的（他在多线程环境与单线程环境下表现一致。）。

好的。在Lambda解析这一块，缓存我用的是google的MapMarker用来创建弱value引用的concurrentMap,new MapMaker().weakValues().makeMap();

**Comment by tfwx** [comment]
> 会。目前我们只考虑了 Value 弱引用，既然你们提出了这个问题，我们下一步考虑把这个缓存的键改成弱键（参考 WeakReference、WeakHashMap ），以便在 GC 发生时回收这里的 Entry。目前只回收 Value，但是 key 是在的。HashMap 有扩容机制，但并没有 entry 回收时回收容量的设定，所以当时考虑是认为意义不大，只是回收了较大的那个。再加上我们使用 class 作 key，这意味着这个 key 几乎不可能被回收），这一点我们也希望你们能给点建议。
> 
> 至于为什么使用 ConcurrentHashMap ，因为这个方法是静态的，静态的就可能被多个线程访问问题，为了避免 map 在多线程操作下数据丢失（java8 以前会死锁）的问题，因此使用了 ConcurrentHashMap 。
> 
> 重点：为了避免 map 在多线程操作下数据丢失（java8 以前会死锁）的问题
> 
> 但是这个方法在操作的时候，并不是原子性的，所以你们反映的会有多个线程 put 进一个 key 确实存在，我们前面尝试把这个静态方法改为原子性的（加锁或使用 ConcurrentHashMap 提供的 compute 方法），均发现性能出现大幅度下降，于是就去掉了。这里前后两次的结果并没有依赖关系，所以，即使不是原子性的，这里代码仍然是线程安全的（他在多线程环境与单线程环境下表现一致。）。

好的。在Lambda解析这一块，缓存我用的是google的MapMarker，用来创建弱value引用的concurrentMap,
ConcurrentMap<Class<?>, SerializedLambda> FUNC_CACHE = new MapMaker().weakValues().makeMap();
当GC时，key和value都会被回收，在性能方面，我还没测试

**Comment by tfwx** [comment]
然后通过computeIfAbsent的原子性，完成解析和缓存
