### ISSUE TITLE
'doTableFilter(tablename)' bug on use 'tenant_id' column

### ISSUE THREAD

**Issue by funcfoo** [baomidou/mybatis-plus#1186]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
telent_id 

### 重现步骤
如果doTableFilter(tablename)开启a表过滤
demo1: select a.id,b.name from a join b on a.id = b.id
demo2: select a.id,b.name from b join a on a.id = b.id
- demo1会不再给b表添加tenan_id
- demo2会过滤掉a表同时也会给b表添加tenant_id
是过滤的时候break掉了吗?

### 报错信息
无报错

**Comment by yuxiaobin** [comment]
[fixed](https://gitee.com/baomidou/mybatis-plus/commit/c7be69175ba0430ef67f0c02a5fabe2810a5e292)

暂未发版
