### ISSUE TITLE
两个ORDER BY

### ISSUE THREAD

**Issue by eidolonse** [baomidou/mybatis-plus#119]
EntityWrapper<User> ew = new EntityWrapper<>();
ew.eq("state", "VALID");
用Paged对象设置排序字段：page.setOrderByField("name");
调用service的方法：selectPage(page, ew);
分页插件：
`<bean id="paginationInterceptor" class="com.baomidou.mybatisplus.plugins.PaginationInterceptor">`
没有使用二级缓存，排序正常，查询没问题。

如果使用二级缓存，分页插件换成：
`<bean id="paginationInterceptor" class="com.baomidou.mybatisplus.plugins.CachePaginationInterceptor">`
代码不变，发现执行的sql会出现两个ORDER BY，即ORDER BY name ASC ORDER BY name ASC，导致查询报错。

如果ew也加排序：ew.orderBy("name");
sql语句更怪，变成ORDER BY name, name ASC ORDER BY name ASC

**Comment by eidolonse** [comment]
用分页插件
`<bean id="paginationInterceptor" class="com.baomidou.mybatisplus.plugins.PaginationInterceptor">`
开启二级缓存，数据修改后缓存又不刷新，纠结了。

**Comment by qmdx** [comment]
请试试 2.1.2 如果不好使建议不要使用缓存分页
