### ISSUE TITLE
请问如何指定某一个属性的类型转换器？

### ISSUE THREAD

**Issue by zyblove** [baomidou/mybatis-plus#1192]
我需要在某一个字段上面指定具体的类型转换器，我可以在mybatis的xml文件中以
<result column="scene_record" property="sceneRecord"
                typeHandler="com.xxx.xxx.MyBatisTypeHandler.MyBlobTypeHandler"/>
的方式指定，但是这种指定方式在mybatisplus中的通用方法中不起作用，我该怎么做呢？

**Comment by miemieYaho** [comment]
el,select 写 resultmap,后续版本会对 el 进行优化,看文档,`@TableName.resultMap`

**Comment by zyblove** [comment]
> resultMap
好的，明白了，谢谢啊
