### ISSUE TITLE
Oracle数据库使用IEnum枚举插件，当枚举值类型是Integer时查询结果为null

### ISSUE THREAD

**Issue by yuyue888** [baomidou/mybatis-plus#1194]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter 3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

由于oracle数据库中数字类型都是number，而mybatis-plus源码中EnumTypeHandler中调用rs.getObject(columnName)获取的value自动映射的Java类型会是BigDecimal，导致EnumUtils.valueOf方法中Objects.equals(e.getValue(), value)结果都是false，最终返回null
![image](https://user-images.githubusercontent.com/12515243/58545554-15f91100-8236-11e9-82d4-a82d3aba747e.png)

### 重现步骤
1. 使用oracle数据库，枚举对应表字段类型定义为number
2. 定义枚举类继承IEnum，类型是Integer
3. 定义实体对象使用该枚举
4. 查询时会发现该枚举字段值都是null

### 报错信息
无

**Comment by yuxiaobin** [comment]
这个问题在新版上应该早就解决了啊

参考提交：

https://gitee.com/baomidou/mybatis-plus/commit/cc4c74900006291955236bd4e69bf613c204bf23

**Comment by yuxiaobin** [comment]
哦 这个需要3.0.7+

**Comment by yuyue888** [comment]
> 哦 这个需要3.0.7+

嗯，升级3.1.0之后可以了，多谢
