### ISSUE TITLE
3.1.1版本使用自定义xml模板生成代码时候会在resource和mapper类路径下同时生成重复的xml文件

### ISSUE THREAD

**Issue by shijl80** [baomidou/mybatis-plus#1195]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
生成代码时候会在mapper类生成一个同级目录xml，下面有xml文件，在resources/mapper目录下也会有一份xml文件

### 重现步骤
通过idea在线生成spring boot工程（2.1.5.RELEASE），
引入mybatis-plus-boot-starter 3.1.1和mybatis-plus-generator 3.1.1，
引入freemarker 2.3.28、lombok 1.18.8、spring-boot-starter-actuator、spring-boot-starter-aop、spring-boot-starter-web、spring-boot-devtools、mysql-connector-java、spring-boot-starter-test，
参照教程（https://mp.baomidou.com/guide/generator.html）编写CodeGenerator.java类，
修改数据源和包名等，从jar包中copy出entity.java.ftl等ftl模板放到工程templates/demo目录下，
并修改CodeGenerator中的模板配置，注释掉templateConfig.setXml(null);
运行main方法生成代码

**Comment by zbq2019** [comment]
我使用的也是3.1.1 ，springboot 版本也是一样的，生成的时候只要设置了  templateConfig.setXml(null);  就不会出现你说的情况

**Comment by qmdx** [comment]
如上
