### ISSUE TITLE
官网文档配置乐观锁失效

### ISSUE THREAD

**Issue by vulgar-cd** [baomidou/mybatis-plus#1198]
版本：
springboot: 2.1.5.RELEASE
MP: 3.1.1

问题：
根据官方文档配置
```java
@Bean
public OptimisticLockerInterceptor optimisticLockerInterceptor() {
    return new OptimisticLockerInterceptor();
}
```
执行更新代码
```java
Test test = new Test();
test.setId(1L);
test.setOptimistic(0L);
test.setName("vulgar");
testService.updateById(test);
```
发现乐观锁插件并没有执行拦截。

解决：
后看`MybatisSqlSessionFactoryBean.class`源码，发现有个公开方法`setPlugins`，遂将代码调整如下
```java
@Bean
public MybatisSqlSessionFactoryBean sqlSessionFactoryBean(DataSource druidDataSource) {
    MybatisSqlSessionFactoryBean sqlSessionFactoryBean = new MybatisSqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(druidDataSource);
    //乐观锁插件
    sqlSessionFactoryBean.setPlugins(new Interceptor[]{new OptimisticLockerInterceptor()});
    return sqlSessionFactoryBean;
}
```
乐观锁插件生效
```text
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6198e9b5] was not registered for synchronization because synchronization is not active
JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@76ececd] will not be managed by Spring
==>  Preparing: UPDATE test SET name=?, optimistic=? WHERE id=? AND optimistic=? 
==> Parameters: vulgar(String), 2(Long), 1(Long), 1(Long)
<==    Updates: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6198e9b5]
```

具体原因不详，特做个记录，希望大神解答。

**Comment by miemieYaho** [comment]
无法复现,参考 samples

**Comment by yuxiaobin** [comment]
`
@Bean
public MybatisSqlSessionFactoryBean sqlSessionFactoryBean(DataSource druidDataSource) {
    MybatisSqlSessionFactoryBean sqlSessionFactoryBean = new MybatisSqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(druidDataSource);
    //乐观锁插件
    sqlSessionFactoryBean.setPlugins(new Interceptor[]{new OptimisticLockerInterceptor()});
    return sqlSessionFactoryBean;
}
`
兄弟，你这个是自定义SqlSessionFactoryBean，当然不会把你乐观锁插件加载进去
官方给的配置，是使用mp-boot-starter，会自动生成SqlSessionFactoryBean并且把@Bean 这样的插件加载进来

**Comment by vulgar-cd** [comment]
> `@Bean public MybatisSqlSessionFactoryBean sqlSessionFactoryBean(DataSource druidDataSource) { MybatisSqlSessionFactoryBean sqlSessionFactoryBean = new MybatisSqlSessionFactoryBean(); sqlSessionFactoryBean.setDataSource(druidDataSource); //乐观锁插件 sqlSessionFactoryBean.setPlugins(new Interceptor[]{new OptimisticLockerInterceptor()}); return sqlSessionFactoryBean; }`
> 
> 兄弟，你这个是自定义SqlSessionFactoryBean，当然不会把你乐观锁插件加载进去
> 官方给的配置，是使用mp-boot-starter，会自动生成SqlSessionFactoryBean并且把@bean 这样的插件加载进来

正解。谢了哈
