### ISSUE TITLE
queryWrapper like无效

### ISSUE THREAD

**Issue by yuyanan1314** [baomidou/mybatis-plus#1199]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在使用queryWrapper时 加了like 然后sq语句也不打印了 也没报错 直接跳过去了  删除掉like就好了

### 重现步骤

        QueryWrapper<BShop> queryWrapper = new QueryWrapper<BShop>();
        // 条件
        if (StringUtils.isNotBlank(pageBo.getName())) {
            queryWrapper.like(true,"tel", "%" + pageBo.getName() + "%");
        }
      控制台没有执行sql 也没有报错  if语句这三行这块去掉 就会打印出sql 
      queryWrapper.orderBy(true, pageBo.isAsc(), "create_time");
      IPage<BShop> dbResult = ibShopService.page(page, queryWrapper);
     

### 报错信息

无报错信息

**Comment by miemieYaho** [comment]
看文档

**Comment by yuyanan1314** [comment]
请问在文档哪块啊，这是什么问题呢，麻烦了

**Comment by yuyanan1314** [comment]
这是debug时的日志
 c.b.r.s.mapper.BShopMapper.selectPage    : ==>  Preparing: SELECT COUNT(1) FROM b_shop WHERE address LIKE ? AND trial_merchants = ? 
c.b.r.s.mapper.BShopMapper.selectPage    : ==> Parameters: %大王%(String), 1(Integer)
 org.mybatis.spring.SqlSessionUtils       : Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1c2589f8]

**Comment by yuyanan1314** [comment]
是count查不到数据得话，就不打印sql了把

**Comment by miemieYaho** [comment]
en

**Comment by qmdx** [comment]
https://mybatis.plus/guide/wrapper.html#like
