### ISSUE TITLE
二级缓存的问题

### ISSUE THREAD

**Issue by eidolonse** [baomidou/mybatis-plus#120]
在生成的xml中加`<cache/>`，二级缓存不起作用？只能在Mapper接口上用注解添加。
`<mapper namespace="test.GameMapper">
    
    <cache type="org.mybatis.caches.redis.RedisCache"/>
</mapper>`

`@CacheNamespace(implementation = org.mybatis.caches.redis.RedisCache.class)
public interface GameMapper extends BaseMapper<Game> {
｝`

**Comment by qmdx** [comment]
可以的不行应该是没有配置好，不建议缓存放到 mapper 层 ，就算好了你还需要调整分页缓存问题。 建议考虑放到 service 层缓存
