### ISSUE TITLE
多租户不支持子查询的注入

### ISSUE THREAD

**Issue by Debenson** [baomidou/mybatis-plus#1201]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 重现步骤

多租户不支持子查询的注入

示例sql:
select a.id user_id
        from user a
        where a.id in (
          select distinct b.user_id 
          from user_car b      
        )     

实际执行sql: 
`
select a.id user_id
        from user a
        where a.id in (
          select distinct b.user_id 
          from user_car b      
        )  and a.tenant_id = 1
`
实际期望: 
` 
  select a.id user_id
        from user a
        where a.id in (
          select distinct b.user_id 
          from user_car b    
          where b.tenant_id = 1
        )  and a.tenant_id = 1
`
在TenantSqlParser.builderExpression#L264修改一下就可以了
`
 /**
     * 处理条件
     */
    protected Expression builderExpression(Expression expression, Table table) {
        //生成字段名
        EqualsTo equalsTo = new EqualsTo();
        equalsTo.setLeftExpression(this.getAliasColumn(table));
        equalsTo.setRightExpression(tenantHandler.getTenantId());
        //加入判断防止条件为空时生成 "and null" 导致查询结果为空
        if (expression == null) {
            return equalsTo;
        } else {
            if (expression instanceof BinaryExpression) {
                BinaryExpression binaryExpression = (BinaryExpression) expression;
                if (binaryExpression.getLeftExpression() instanceof FromItem) {
                    processFromItem((FromItem) binaryExpression.getLeftExpression());
                }
                if (binaryExpression.getRightExpression() instanceof FromItem) {
                    processFromItem((FromItem) binaryExpression.getRightExpression());
                }
            }
            if (expression instanceof OrExpression) {
                return new AndExpression(equalsTo, new Parenthesis(expression));
            }            
            else {
               if (expression instanceof InExpression) {
                 InExpression inExp = (InExpression) expression;
                 processSelectBody(((SubSelect) inExp.getRightItemsList()).getSelectBody()); 
               } 
               return new AndExpression(equalsTo, expression);
            }
        }
    }

`

修改内容: 
  if (expression instanceof InExpression) {
                 InExpression inExp = (InExpression) expression;
                 processSelectBody(((SubSelect) inExp.getRightItemsList()).getSelectBody()); 
               }

**Comment by qmdx** [comment]
请关注下一个版本发布 https://github.com/baomidou/mybatis-plus/commit/fc55ec21420a7effe96da719584662724cfd0b03

**Comment by Debenson** [comment]
这样直接转有问题， 需要再判断一下
processSelectBody(((SubSelect) inExp.getRightItemsList()).getSelectBody());

if (expression instanceof OrExpression) {
return new AndExpression(equalsTo, new Parenthesis(expression));
} else {
// add by Debenson,支持子查询添加租户id
if (expression instanceof InExpression) {
InExpression inExp = (InExpression) expression;
if (inExp.getRightItemsList() instanceof SubSelect) {
processSelectBody(((SubSelect) inExp.getRightItemsList()).getSelectBody());
}
}
return new AndExpression(equalsTo, expression);
}
