### ISSUE TITLE
 Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'

### ISSUE THREAD

**Issue by pencilso** [baomidou/mybatis-plus#1203]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1
开发环境为 IDEA  JDK1.8

调用getByAppMid 方法会出现异常： Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Your property named "appMid" cannot find the corresponding database column name!]

    @Service
    public class ConfigAlipayServiceImp extends ServiceImpl<ConfigAlipayMapper, ConfigAlipayModel> implements ConfigAlipayService {
    
    
        @Override
        public ConfigAlipayModel getByAppMid(Long appMid) {
            return lambdaQuery().eq(ConfigAlipayModel::getAppMid, appMid).one();
        }
    }

数据库里是有app_mid字段的 并且我直接查询所有是可以查询的 
     List<ConfigAlipayModel> list = configAlipayService.list();

**Comment by miemieYaho** [comment]
去除 dev-tools
