### ISSUE TITLE
代码生成器- AbstractTemplateEngine的getObjectMap方法生成controllerMappingHyphen

### ISSUE THREAD

**Issue by 469753862** [baomidou/mybatis-plus#1204]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator版本 3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
AbstractTemplateEngine类getObjectMap方法
        if (config.getStrategyConfig().isControllerMappingHyphenStyle()) {
            objectMap.put("controllerMappingHyphenStyle", config.getStrategyConfig().isControllerMappingHyphenStyle());
            objectMap.put("controllerMappingHyphen", StringUtils.camelToHyphen(tableInfo.getEntityPath()));
        }
为什么controllerMappingHyphen的value值是使用entityName使用 .
如果我在entityName的join "XXX", (如 "userXXX"="user"+"XXX"), 这样生成的数据岂不是有点尴尬, 毕竟暴露出去的接口和bean是没有关系
建议使用使用 表名去掉表前缀的名称好一点

**Comment by qmdx** [comment]
解决：
1、自定义模板在模板文件中解决前缀问题
2、注入重写传入渲染 map 对象 https://github.com/baomidou/mybatis-plus/commit/686f5b234f775f5f63328d6553a117d0c2def900  下一个版本可用
