### ISSUE TITLE
代码生成器-maven多模块问题

### ISSUE THREAD

**Issue by BinaryHao** [baomidou/mybatis-plus#1205]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/20509387/58693220-df9ccc80-83c2-11e9-9776-542b1f30298e.png)

entity，service，controller在不同的maven模块中，想生成文件到对应的模块中，好像不支持这种配置。

**Comment by miemieYaho** [comment]
不支持

**Comment by BinaryHao** [comment]
这个功能还挺常用的，希望后面版本能支持下。
