### ISSUE TITLE
sql注入问题

### ISSUE THREAD

**Issue by 2720851545** [baomidou/mybatis-plus#1207]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

sql注入问题
new QueryWrapper(null, "* from user; delete from user;select name, age")

**Comment by miemieYaho** [comment]
你懂什么叫 sql 注入吗?了解 #{} 和 %{} 的区别吗?好好去百度去吧
