### ISSUE TITLE
代码生成器-entity继承父类问题

### ISSUE THREAD

**Issue by BinaryHao** [baomidou/mybatis-plus#1208]
### 当前使用版本
3.1.1

### 该问题是怎么引起的？
用setSuperEntityClass设置了entity要继承的父类BaseEntity，生成的类里面为什么还有父类的字段；
比如父类中有字段id，我希望生成的Entity里面没有id这个字段。

用 setSuperEntityColumns 设置了BaseEntity的字段也没有效果。

**Comment by miemieYaho** [comment]
看文档

**Comment by BinaryHao** [comment]
![image](https://user-images.githubusercontent.com/20509387/58698913-d6b1f800-83ce-11e9-9f9c-734e83696d4d.png)
文档就这两句
