### ISSUE TITLE
 org.apache.ibatis.binding.BindingException: Invalid bound statement (not found):

### ISSUE THREAD

**Issue by jsir-1** [baomidou/mybatis-plus#1216]
### 当前使用版本(必须填写清楚，否则不予处理)
springboot 3.1版本

### 重现步骤
mybatis-plus:
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jsrf.demo.entity
这些配置都没问题，自己写的xml是可以正常执行的。但是使用mp的方法就不行。搞了好久了快疯了

### 报错信息

 org.apache.ibatis.binding.BindingException: Invalid bound statement (not found):

**Comment by f00lish** [comment]
mp 没有配置成功

**Comment by miemieYaho** [comment]
看文档
