### ISSUE TITLE
找不到AutoSqlInjector 这个类

### ISSUE THREAD

**Issue by Cearnach** [baomidou/mybatis-plus#1218]
### 版本: 3.1.1
 <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>3.1.1</version>
</dependency>

### 如图,继承AutoSqlInjector接口时提示找不到该类.
![image](https://user-images.githubusercontent.com/24709538/58792754-60f49900-8627-11e9-8ce9-626572da3afd.png)

**Comment by miemieYaho** [comment]
https://mybatis.plus/
