### ISSUE TITLE
版本不支持1.8以下么

### ISSUE THREAD

**Issue by Non-Negative** [baomidou/mybatis-plus#1219]
### 当前使用版本(必须填写清楚，否则不予处理)
项目：mybatis-plus-generator
版本： 3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
运行环境：在jdk1.7版本下

### 重现步骤
调用下列代码异常抛出
AutoGenerator gen = new AutoGenerator(); 

### 报错信息

**java.lang.UnsupportedClassVersionError**

### 疑问
请问是不支持1.7版本么，1.8能在本地可以完美运行

**Comment by miemieYaho** [comment]
1.8 +
