### ISSUE TITLE
bind标签不支持

### ISSUE THREAD

**Issue by scofier** [baomidou/mybatis-plus#122]
代码如下：mapper.java

String bindShardId(String orderNo);

xml 配置：
```
<select id="bindShardId" parameterType="java.lang.String">
    <bind name="orderNo" value="'%' + _parameter" />
    select "#{orderNo}"
</select>
```

报错：

> Caused by: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='orderNo', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
	at com.baomidou.mybatisplus.MybatisDefaultParameterHandler.setParameters(MybatisDefaultParameterHandler.java:264)

**Comment by qmdx** [comment]
look http://blog.csdn.net/lq123456789000/article/details/51859562  未能解决 打开 issue
