### ISSUE TITLE
分页的总行数不会自动查询吗

### ISSUE THREAD

**Issue by ai4581532** [baomidou/mybatis-plus#1222]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 重现步骤
![image](https://user-images.githubusercontent.com/13961477/58848179-30a90b00-86b8-11e9-9bc3-e4cab74fd73b.png)

### 报错信息

分页的总行数不会自动查询吗

**Comment by miemieYaho** [comment]
看文档,看 samples

**Comment by WindBruce** [comment]
遇到同样的问题，看文档来写的，依然无效，service实现类里new Page(1,20)，但查询的结果total为0，当前页和每页条数是默认值，试过各种办法无效
