### ISSUE TITLE
resultType="java.util.Map" 转化驼峰不起效果

### ISSUE THREAD

**Issue by mmdsyl** [baomidou/mybatis-plus#1223]
resultType="java.util.Map" 转化驼峰无效。
### 当前使用版本
3.0.6

### 重现步骤

```
service:
   @Override
    public IPage<Map<String,String>> productListDiy(Page<Map<String,String>> productPage, String categoryId) {
        List<Map<String, String>> maps = productMapper.productList(productPage, categoryId);
        return productPage.setRecords(maps);
    }

mapper:
 <select id="productList" resultType="java.util.Map">
select ...
</>
```

配置使用官网文档中的：
https://mp.baomidou.com/guide/faq.html#%E5%BC%80%E5%90%AF%E6%9F%A5%E8%AF%A2%E7%BB%93%E6%9E%9C%E3%80%90%E4%B8%8B%E5%88%92%E7%BA%BF%E8%BD%AC%E9%A9%BC%E5%B3%B0%E3%80%91

如何使用:【Map下划线自动转驼峰】 指的是：resultType="java.util.Map"  小节

### 报错信息
官方文档的配置没有起效果。

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/config/MybatisPlusConfig.java 
无法复现

**Comment by mmdsyl** [comment]
@miemieYaho 多谢，发现你们的测试用例 比文档还详细。
