### ISSUE TITLE
使用Mybatis-plus策略自动更新数据库时间失败

### ISSUE THREAD

**Issue by ReStartLin** [baomidou/mybatis-plus#1225]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用的mysql数据库8.0.13
数据库中设置的 update_time 字段是有自动更新的  
`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间'

但是使用mybatis-plus封装的mapper进行update时没法进行更新

这是配置
![image](https://user-images.githubusercontent.com/31606497/58863359-497be580-86e5-11e9-8e59-50937dcb8757.png)

### 重现步骤
![image](https://user-images.githubusercontent.com/31606497/58863414-61ec0000-86e5-11e9-8636-5085ba200c9f.png)

![image](https://user-images.githubusercontent.com/31606497/58863431-6b756800-86e5-11e9-8aa6-d3a6d03f57df.png)

两个实体类采用继承方式

使用 mapper.updateById 进行更新 

无法使数据库中的update_time字段自动更新

**Comment by miemieYaho** [comment]
自己看打印的 sql 排查

**Comment by BARERM** [comment]
因为查询出的实体里有update_time了，所以会把实体里的update_time更新到表里，等于是没变。
我是做更新时设置了一下：xxx.setUpdateTime(null);

但感觉有些麻烦。
