### ISSUE TITLE
关于baseMapper自带的selectCount方法的sqlSelect

### ISSUE THREAD

**Issue by zhangzihang** [baomidou/mybatis-plus#1226]
版本2.1.9

我想用baseMapper自带的selectCount统计数量，大概是这么写的

        int currentCount = peopleResidentInfoMapper.selectCount(Condition.create().setSqlSelect("count(DISTINCT rid)")
                .eq("isflag", SysType.ISFLAG_1).like("rid", result.get("sfid").toString(), SqlLike.RIGHT));

我想让count(DISTINCT rid)替换原有的COUNT(1)
不过看起来没有正常工作，输出的sql还是COUNT(1)
请问这个应该怎么解决？

**Comment by miemieYaho** [comment]
2.x版本不支持

**Comment by yuxiaobin** [comment]
2.x 使用 IService.selectObj(wrapper)

参考源码：
`
@Override
    public Object selectObj(Wrapper<T> wrapper) {
        return SqlHelper.getObject(baseMapper.selectObjs(wrapper));
    }
`
