### ISSUE TITLE
一次查询为啥发两次查询sql

### ISSUE THREAD

**Issue by fangjieDevp** [baomidou/mybatis-plus#1229]
### 重现步骤

![image](https://user-images.githubusercontent.com/17747340/58929931-ec873a80-878b-11e9-8d79-ad2a21fb7c10.png)

### 报错信息

![image](https://user-images.githubusercontent.com/17747340/58929919-e2653c00-878b-11e9-941c-9505090f6e42.png)

**Comment by fangjieDevp** [comment]
版本号 3.1.1

**Comment by miemieYaho** [comment]
请用点脑子,可能一样的 sql 给你查两次吗?自己排查

**Comment by fangjieDevp** [comment]
fuck，吊啥啊，一样的sql

**Comment by hcl04** [comment]
![image](https://user-images.githubusercontent.com/39977647/59003733-b7d9b880-8849-11e9-98df-294767d5549c.png)
