### ISSUE TITLE
jdbc-type-for-null 配置无效.采用mybatis xml配置文件可以

### ISSUE THREAD

**Issue by duwei54** [baomidou/mybatis-plus#1231]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？
遇到`JdbcType OTHER`的问题
配置
```
mybatis-plus:
  configuration:
     jdbc-type-for-null: NULL
```
不起作用
配置
```
mybatis-plus:
  configLocation: classpath:/mybatis-config.xml
```
xml文件里面设置
```
<configuration>
    <settings>
        <setting name="jdbcTypeForNull" value="NULL" />
    </settings>
</configuration>
```
可以正常插入`Null`值

mybatis-plus.configuration 支持mybatis所有属性么?

**Comment by miemieYaho** [comment]
你该换idea了,yml配置用小写

**Comment by duwei54** [comment]
@miemieYaho  已逃离Eclipse多年. 这么写是因为刚刚用小写 null 同样不行哦~

**Comment by miemieYaho** [comment]
已确认,那怎么idea不提示你的是小写?

**Comment by miemieYaho** [comment]
spring的问题,原生mybatis-boot-starter同样是这样
`jdbc-type-for-null: 'null'`这么写

**Comment by duwei54** [comment]
@miemieYaho 提示是小写的，小写没用，我拷贝xml的配置变成了"NULL",然后还是不行:joy:。话说，大小写在我映像中貌似没关系:smile:

**Comment by miemieYaho** [comment]
用单引号把 null 包起

**Comment by duwei54** [comment]
@miemieYaho 是的 用单引号包起来就行了.非常感谢
