### ISSUE TITLE
代码生成器TableField类加入更多表属性字段

### ISSUE THREAD

**Issue by TSiven** [baomidou/mybatis-plus#1234]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
希望代码生成器TableField类加入非空字段属性,  便于代码生成器生成hibernate validator的注解信息

**Comment by miemieYaho** [comment]
不支持

**Comment by yuxiaobin** [comment]
不同的数据库，能拿到的字段属性不同，不一定能支持返回字段是否为空的属性。

你可以自己尝试一下，欢迎PR过来
