### ISSUE TITLE
Wrapper 自定义 sql 的问题

### ISSUE THREAD

**Issue by floatime** [baomidou/mybatis-plus#1235]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在测试简单的 Wrapper 自定义条件 sql 时出了问题，首先文档中@Select 注解给的实例必须是这样"<script>sql</script>" 才会解析 ew.customSqlSegment。就这样而言在拼接 sql 时源码内部通过 bean的fieldName 转换 columnName 时，无法获得 TableInfo 继续跟源码发现：
源码中 TableInfoHelper 类中 TABLE_INFO_CACHE 属性 的 key 是 Class 类型。我传入的 clazz 的地址值与 TABLE_INFO_CACHE 相同 class 的地址值不一样，故不能转换 columnName ，所以返回的 customSqlSegment 为 ""

### 重现步骤
1. 方法声明：
 @Select(value = "<script>select * from API_TYPE ${ew.customSqlSegment}</script>")
    List<ApiTypeView> selectAll(@Param(Constants.WRAPPER) Wrapper wrapper);
2. 方法调用：
  ApiTypeView view = new ApiTypeView();
        view.setTypeParentId(10l);
        List<ApiTypeView> as = apiTypeMapper.selectAll(Wrappers.<ApiType>lambdaQuery((ApiType)view));

### 报错信息
 Time：27 ms - ID：com.ymhj.yas.apim.services.mappers.ApiTypeMapper.selectAll
Execute SQL：select * from API_TYPE

**Comment by floatime** [comment]
be flashy without substance.   Have to give up

**Comment by miemieYaho** [comment]
去除 dev-tools

**Comment by miemieYaho** [comment]
只有 basemmaper 的泛型的 class 才会生成 tableinfo

**Comment by floatime** [comment]
@miemieYaho 谢谢，祝好！
