### ISSUE TITLE
interface Mapper 定义重载方法 的问题

### ISSUE THREAD

**Issue by floatime** [baomidou/mybatis-plus#1237]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在 mapper 中定义重载方法时，Wrapper 自定义 sql 失效

### 重现步骤
1. 声明：
   @Select("select * from API_TYPE")
    List<ApiTypeView> selectAll();

    @Select(value = "<script>select * from API_TYPE ${ew.customSqlSegment}</script>")
    List<ApiTypeView> selectAll(@Param(Constants.WRAPPER) Wrapper wrapper);

    @Select(value = "<script>select * from API_TYPE ${ew.customSqlSegment}</script>")
    IPage<ApiTypeView> selectPageByVo(IPage page,@Param(Constants.WRAPPER) Wrapper wrapper);
2. 调用：
    
    List<ApiType> results = apiTypeMapper.selectList(new QueryWrapper<>(view));
     List<ApiTypeView> as = apiTypeMapper.selectAll(Wrappers.<ApiType>lambdaQuery(view).eq(ApiType::getTypeParentId,view.getTypeParentId()));
    IPage<ApiTypeView> pager = apiTypeService.pageViewCondition(view);

### 报错信息
selectAll 方法时没有Wrapper 自定义sql 输出,感觉是调用了无参的 selectAll
 Time：7 ms - ID：com.ymhj.yas.apim.services.mappers.ApiTypeMapper.selectAll
Execute SQL：select * from API_TYPE

**Comment by floatime** [comment]
我试了把重载的方法名字换一下  避免重载 是 OK 的，为了 plus 更好还是来发一下。 是小问题自己可以避免

**Comment by miemieYaho** [comment]
本来就是这么设计的,虽然没什么人用
