### ISSUE TITLE
selectMapsPage如果有字段创建时间，日期如何才能格式化

### ISSUE THREAD

**Issue by wanniwa** [baomidou/mybatis-plus#1238]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在查询分页的时候平常会使用page()方法，我会在字段上加@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 在数据传给前台的时候会自动格式化，但是使用selectMapsPage，map里的时间直接是英文时间没有被格式化，有木有好的办法可以让查询出来的page中的map 时间可以直接格式化好

**Comment by miemieYaho** [comment]
这不关 mp 的事,自己百度解决
