### ISSUE TITLE
getOne查询数据优化建议

### ISSUE THREAD

**Issue by xpeng1215** [baomidou/mybatis-plus#1239]
### 当前使用版本(必须填写清楚，否则不予处理)
使用版本：3.0.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/37093498/59018426-73194600-8878-11e9-97e1-f794f0bfd076.png)
![image](https://user-images.githubusercontent.com/37093498/59018762-3bf76480-8879-11e9-88e6-ab2023fef636.png)

getOne方法是通过查询list获取第一个结果的，如果查询的list过大，会使查询速度变慢，这个能不能通过sql的limit 1来限制结果集呢。

**Comment by miemieYaho** [comment]
最新版,默认 getOne 使用原生的会抛 tooMany 异常,非默认的就自己.last(limit)
