### ISSUE TITLE
mybatis 和 mybatis-plus 混用不行吗

### ISSUE THREAD

**Issue by wdreamsky** [baomidou/mybatis-plus#1240]
### 当前使用版本(必须填写清楚，否则不予处理)
 mybatis-plus 版本为 3.0.3
 mybatis 版本为 1.3.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
引入  mybatis-plus 后，之前的接口无法访问

### 报错信息
绑定不了xml 文件了
"Invalid bound statement (not found)：

**Comment by miemieYaho** [comment]
看文档
