### ISSUE TITLE
新版本 java8的时间 不知各位是否有

### ISSUE THREAD

**Issue by pjworkspace** [baomidou/mybatis-plus#1244]
mysql 数据库 时间类型为时间戳
starter版本 3.1.1 
报错 
Resolved [org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLFeatureNotSupportedException
; null; nested exception is java.sql.SQLFeatureNotSupportedException
starter版本 3.1.0 
不报错

**Comment by miemieYaho** [comment]
换连接池
