### ISSUE TITLE
fill注解无用，没有该注解，一样会执行到handler中

### ISSUE THREAD

**Issue by CrossHub0661** [baomidou/mybatis-plus#1246]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1 
2.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
@TableField(fill = FieldFill.INSERT_UPDATE)注解不论加不加，都会进入MyMetaObjectHandler中

### 重现步骤
使用官方例子
mybatis-plus-sample-auto-fill-metainfo
去掉User.operator的@TableField(fill = FieldFill.INSERT_UPDATE)注解，如下
//    @TableField(fill = FieldFill.INSERT_UPDATE)
    private String operator;
然后执行test
依旧会进入MyMetaObjectHandler中，将operator插入

### 报错信息
未能满足功能要求，即使不使用fill注解，也会进入handler中

**Comment by qmdx** [comment]
该注解是预留 sql 的不是控制是否进入该处理器
