### ISSUE TITLE
当插入的时候如果字段是字符串,切传递的参数前面有空格的话,插入的数据将全部是字符串

### ISSUE THREAD

**Issue by sishuTracy** [baomidou/mybatis-plus#1247]
### 当前使用版本(必须填写清楚，否则不予处理)
  版本:3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

public static String createShareCode() {
    //此处时间戳取负值
    long i = -System.currentTimeMillis();
    int radix = 62;
    byte[] buf = new byte[15];
    int charPos = 14;

    while (i <= -radix) {
      buf[charPos--] = (byte) digits[(int) (-(i % radix))];
      i = i / radix;
    }
    buf[charPos] = (byte) digits[(int) (-i)];
    return new String(buf);
  }

通过此方法生成的字符串进行保存的时候永远保存的是空字符串

**Comment by miemieYaho** [comment]
mp不会加工你的数据,自己解决
