### ISSUE TITLE
pageMaps和list方法返回数据对时间处理不一样，展示差异很大

### ISSUE THREAD

**Issue by xiaoyangren6514** [baomidou/mybatis-plus#1248]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?

通过pageMaps形式， IPage<Map<String, Object>> mapIPage = appInfoService.pageMaps(appInfoPage); 获取到的create_time(mysql为timestamp，java中为LocalDateTime)为 "createTime" -> "2019-06-03 20:56:21.0"。

通过List<AppInfo> list = appInfoService.list(); 获取到的create_time为2019-06-03T07:27:44，该方式通过LocalDateTimeSerializer配置可以在UI页面正常展示：2019-06-03 07:27:44，而第一种方式就无法正常展示了，显示内容为：2019-06-03T12:27:44.000+0000

### 重现步骤
必现，可以采用两种方式分别试一下，个人猜测是没有同步代码，两个获取方式对时间的处理不一致。

### 报错信息

上面已经描述，pageMaps和list方法返回的数据对时间处理不一样，展示差别很大，希望尽快修复。

**Comment by miemieYaho** [comment]
mp不进行数据封装,去找mybatis

**Comment by xiaoyangren6514** [comment]
这个和mybatis无关，你试一下我说的两个方法，这个是mp提供的，获取出来的时间是不一致的，请尝试后再回复。

**Comment by miemieYaho** [comment]
我觉得你才该试一下

**Comment by qmdx** [comment]
底层类似转换问题 mp 并没有处理该处
