### ISSUE TITLE
SQLServer2016版本主键自动生成插入失败

### ISSUE THREAD

**Issue by zchen01** [baomidou/mybatis-plus#125]
实体定义如下：
![1](https://user-images.githubusercontent.com/6150706/28909160-d7eace54-7859-11e7-8bd6-2ce07c1dc605.png)
父类定义：
![2](https://user-images.githubusercontent.com/6150706/28909185-f5b79ee4-7859-11e7-9ea7-107c04e47a8e.png)
spring配置文件如下，采用springboot
![3](https://user-images.githubusercontent.com/6150706/28909293-6ec1073a-785a-11e7-8f25-1bffc990db96.png)
mapper扫描配置类如下：
![4](https://user-images.githubusercontent.com/6150706/28909320-911b03bc-785a-11e7-80a2-97451b808e81.png)
mapper接口具体定义如下：
![5](https://user-images.githubusercontent.com/6150706/28909338-ab42671c-785a-11e7-9f3c-d9d24f159924.png)
数据库定义如下，数据库采用SQL Server 2016，主键自增：
![6](https://user-images.githubusercontent.com/6150706/28909371-cdbff6c4-785a-11e7-9e07-9811d4df5229.png)
具体代码调用如下：
![7](https://user-images.githubusercontent.com/6150706/28909467-2f7e32ae-785b-11e7-9f1f-16046905d283.png)
以上代码执行后，报如下错误：
![8](https://user-images.githubusercontent.com/6150706/28909504-5c4e44a4-785b-11e7-90f2-d232f7e0a651.png)
粗略看下来，应该是没能监测到数据库主键自增设置，但数据库那种截图，已经设置了主键的自增方式，我看了下我们的CHANGELOG，在2.0.9的版本中，已经对SQL Server的该问题做了处理：`修复生成器不能识别sqlServer的自增主键代码生成器不能识别SqlServer自增主键的问题`，为什么我这边本地调试还会出现这个问题？请排查，谢谢。

**Comment by qmdx** [comment]
@zchen01   tableId 指定为 auto 就是自增，否则是 idWorker 策略

**Comment by qmdx** [comment]
未解决请打开
