### ISSUE TITLE
代码生成器中表名没有忽略大小写

### ISSUE THREAD

**Issue by ShammgodYoung** [baomidou/mybatis-plus#1252]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
ConfigBuilder中
if (isInclude) {
   for (String includeTable : config.getInclude()) {
      // 忽略大小写等于 或 正则 true
      if (tableNameMatches(includeTable, tableName)) {
      includeTableList.add(tableInfo);
      } else {
          notExistTables.add(includeTable);
        }
 }

private boolean tableNameMatches(String setTableName, String dbTableName) {
        return setTableName.equalsIgnoreCase(dbTableName)
            || StringUtils.matches(setTableName, dbTableName);
    }
应改为
private boolean tableNameMatches(String setTableName, String dbTableName) {
        return setTableName.equalsIgnoreCase(dbTableName)
            || StringUtils.matches(setTableName, dbTableName);
    }

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/pull/1253
