### ISSUE TITLE
3.1.1版本自动注入MybatisMapWrapperFactory带来的问题

### ISSUE THREAD

**Issue by ottfottf** [baomidou/mybatis-plus#1257]
### 从3.1.0升级到3.1.1
发现3.1.1自动注入了MybatisMapWrapperFactory，即自动处理返回值是Map时的结果集映射，之前都是USER_NAME -> USER_NAME不变，现在变成USER_NAME ->userName。

### 重现步骤
通过SQL直接查询，返回值设置成Map即可

### 报错信息
无错误，但是返回结果Map中的Key全部变成了驼峰。

如何关闭这个自动注入？貌似尝试在配置文件中：
    @Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return i -> i.setObjectWrapperFactory(null);
    }
也没用？

**Comment by miemieYaho** [comment]
用 3.1.0 或者等下一个版本

**Comment by ottfottf** [comment]
> 用 3.1.0 或者等下一个版本

好吧，就是说3.1.1暂时没法关闭这个自动注入的特性了么？

**Comment by sdmq** [comment]
3.1.0 3.1.1 处理map 驼峰不一致, 目前3.1.1 比较合理, 保证map 和 实体 返回前端一致

**Comment by sdmq** [comment]
有时候需要原生的字段, 如果能配置就好了

**Comment by yuxiaobin** [comment]
`<dependency>`
`  <groupId>com.baomidou</groupId>`
`  <artifactId>mybatis-plus</artifactId>`
`  <version>3.1.2</version>`
`</dependency>`
