### ISSUE TITLE
新手求救，插入数据成功，也已经返回主键id，但实际数据库中没有记录

### ISSUE THREAD

**Issue by LetsomeBody** [baomidou/mybatis-plus#1259]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 重现步骤
单元测试，直接注入mapper，使用mapper.insert方法

### 报错信息
无其他报错信息
Creating a new SqlSession
Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1f27f354]
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@5418893c] will be managed by Spring
==>  Preparing: INSERT INTO rel_monitor_broker ( broker_id, cluster_id, alert_type, alert_content, monitor_group_id, ctime, mtime, create_user_id, modify_user_id ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? ) 
==> Parameters: 1(Long), 5884063847232307(Long), 1(Integer), 123(String), 1(Long), 2019-06-13 12:03:50.151(Timestamp), 2019-06-13 12:03:50.151(Timestamp), 1(Long), 1(Long)
<==    Updates: 1
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1f27f354]
3
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1f27f354]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1f27f354]

**Comment by miemieYaho** [comment]
事务
