### ISSUE TITLE
3.1.1 解析异常bug

### ISSUE THREAD

**Issue by Asice** [baomidou/mybatis-plus#1260]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 重现步骤
 update t_user set is_del=(is_del XOR 1) where id=?

原生mybatis 没有这个bug
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: update t_user set is_del=(is_del XOR 1) where id=?;

**Comment by miemieYaho** [comment]
多租户就加注解不走租户

**Comment by Asice** [comment]
本来就是要走租户的，但是遇到XOR就报错
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "XOR" <S_IDENTIFIER>
    at line 1, column 33.

**Comment by miemieYaho** [comment]
jsqlparser 不支持你这种 sql

**Comment by qmdx** [comment]
这个 sql 无法自动解析加租户信息，你需要 sqlParser 注解排除手动处理，要么修改 sql
