### ISSUE TITLE
是否支持对主键的值进行修改

### ISSUE THREAD

**Issue by Cearnach** [baomidou/mybatis-plus#1262]
### 当前使用版本: 3.1.1

使用的是这个方法,
`
int update( @Param(Constants.ENTITY) T entity, @Param(Constants.WRAPPER) Wrapper<T> 
updateWrapper);
`

比如主键是 id=1
想实现 update table set id = 2 where id = 1
我想把主键id改成2 , 但是update方法在更新的时候,就算传入新的主键不能为空,也不会把主键字段放到 update set 要更新的字段里面

**Comment by miemieYaho** [comment]
updateWrapper.set
