### ISSUE TITLE
逻辑删除问题

### ISSUE THREAD

**Issue by CoolLittle** [baomidou/mybatis-plus#1265]
### 当前使用版本(必须填写清楚，否则不予处理)
springboot: 2.1.5
mybatis plus :3.1.0，3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
实体字段已加  @TableLogic 注解

版本 3.1.0逻辑删除必须注入LogicSqlInjector 才可生效
但是版本 3.1.1 不需要注入该Bean即可生效，是这样吗？为什么在3.1.0中LogicSqlInjector 已废弃，有新的替换方式吗

**Comment by miemieYaho** [comment]
没有

**Comment by CoolLittle** [comment]
下一版本3.1.2会解决 dev-tool与MybatisPlusException: Your property named "xxxx" cannot find the corresponding database column name 的问题吗？

**Comment by miemieYaho** [comment]
不一定

**Comment by yuxiaobin** [comment]
逻辑删除，默认DefaultSqlInjector已经包含了逻辑删除的逻辑，所以只要实体带上逻辑删除注解就可以了。

关于dev-tools的问题，暂时没计划解决
