### ISSUE TITLE
idea构建源码不成功

### ISSUE THREAD

**Issue by 852675742** [baomidou/mybatis-plus#1267]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

构建源码不成功

### 报错信息

Could not find method annotationProcessor() for arguments [org.projectlombok:lombok:1.18.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by qmdx** [comment]
lombok 你搜下怎么用
