### ISSUE TITLE
Generate 能否生成基于注解的mapper对象？

### ISSUE THREAD

**Issue by vancezhao** [baomidou/mybatis-plus#127]
mybatis-plus generator能否支持基于注解的mapper对象呢？

**Comment by huayanYu** [comment]
@vancezhao  啥意思? 详细描述下.

**Comment by vancezhao** [comment]
mybatis自身的generator是可以生成基于注解的mapper对象（非xml mapper)

`The generated objects will be Java interfaces for the MyBatis 3.x mapper infrastructure. The interfaces will be based on annotations and MyBatis 3.x SqlProviders. No XML mapper files will be generated.
The ANNOTATEDMAPPER requires MyBatis version 3.0.4 or higher.`

mybatis-plus generator可以实现这个功能么？

**Comment by eidolonse** [comment]
自定义的查询语句可以直接在生成的mapper接口加方法，用注解。这个也可以不生成xml文件。

**Comment by vancezhao** [comment]
@eidolonse mybatis-plus自动生成的方式现在支持吗？比如有几十张表。。

**Comment by qmdx** [comment]
@vancezhao  参考下文档 代码生成器， 你可以自定义下模板即可。这里关掉了，更多疑问加入群讨论
