### ISSUE TITLE
请问下MybatisDefaultParameterHandler可以自定义吗

### ISSUE THREAD

**Issue by gaochuanneu** [baomidou/mybatis-plus#1271]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
MybatisDefaultParameterHandler可以自定义吗?想替换掉默认的IdWorker用自己的id生成服务

### 重现步骤
无

### 报错信息
无

**Comment by miemieYaho** [comment]
不能

**Comment by yuxiaobin** [comment]
可以的，不过你要自定义LanguageDriver并且配置到MybatisSqlSessionFactory里面

你可以参考mp的源码修改

**Comment by gaochuanneu** [comment]
如果通过重写源码只需要将idworker重写就可以达到我的目的,但是还是希望能有个友好点的扩展方式,防止mp升级时出现问题
