### ISSUE TITLE
使用generator 生成数据表时, 注释乱码(mssql数据库)

### ISSUE THREAD

**Issue by devinWan** [baomidou/mybatis-plus#1272]
当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus:2.3

该问题是怎么引起的？(最新版上已修复的会直接close掉)
重现步骤
报错信息

**Comment by qmdx** [comment]
暂无mssql 数据库测试，你可以搞定发现问题 pr 谢谢

**Comment by qmdx** [comment]
pr open
