### ISSUE TITLE
提个bug，使用分页，子表内连接查询count总数的sql，会失去分隔符

### ISSUE THREAD

**Issue by java-aodeng** [baomidou/mybatis-plus#1275]
使用分页，子表内连接查询count总数的sql，会失去分隔符
eg：LEFT JOIN (
	a,
	b,
	c
)
会变成LEFT JOIN (
	a
	b
	c
)

**Comment by qmdx** [comment]
给出具体重新 demo

**Comment by java-aodeng** [comment]
SELECT
            al.id,
            al.ali_logistics_id,
            al.purchase_order_id,
            al.supply_code,
            op.order_increment,
            sii.sku,
            sii.sku_id,
            sii.invoice_id,
            SUM(sii.qty_ordered) AS qty_ordered_total,
            SUM(sii.qc) AS qc_total,
            r.state,
            al.create_at AS create_at_time
            FROM
            ali_logistics al
            LEFT JOIN order_purchase op ON al.purchase_order_id = op.purchase_order_id
            AND op.`supply_code` = al.supply_code
            LEFT JOIN (
            sales_invoice si,
            sales_invoice_item sii,
            supply_attribute sa
            ) ON si.order_increment = op.order_increment
            AND sii.invoice_id = si.invoice_id
            AND sii.sku_id = sa.sku_id
            AND sa.`supply_code` = al.supply_code
            LEFT JOIN replenishment r ON r.order_increment = op.order_increment

这样的sql会变成这样的

            SELECT
            al.id,
            al.ali_logistics_id,
            al.purchase_order_id,
            al.supply_code,
            op.order_increment,
            sii.sku,
            sii.sku_id,
            sii.invoice_id,
            SUM(sii.qty_ordered) AS qty_ordered_total,
            SUM(sii.qc) AS qc_total,
            r.state,
            al.create_at AS create_at_time
            FROM
            ali_logistics al
            LEFT JOIN order_purchase op ON al.purchase_order_id = op.purchase_order_id
            AND op.`supply_code` = al.supply_code
            LEFT JOIN (
            sales_invoice si
            sales_invoice_item sii
            supply_attribute sa
            ) ON si.order_increment = op.order_increment
            AND sii.invoice_id = si.invoice_id
            AND sii.sku_id = sa.sku_id
            AND sa.`supply_code` = al.supply_code
            LEFT JOIN replenishment r ON r.order_increment = op.order_increment

**Comment by qmdx** [comment]
@java-aodeng  如此复杂的 sql 就不要交给 mp 给你自动优化 count sql 手动挡解决 page 里面有参数设置你的 count
