### ISSUE TITLE
使用SQL SERVER 2017代码生成器，生成Entity时候的注解全部为???

### ISSUE THREAD

**Issue by wu275080658** [baomidou/mybatis-plus#1276]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1
使用SQL SERVER 2017代码生成器，生成Entity时候的注解全部。
![image](https://user-images.githubusercontent.com/40565711/59670951-60472f80-91ef-11e9-82b6-0d17528694f7.png)

代码生成器通过这个sql来查询表的信息：
SELECT  cast(a.name AS VARCHAR(500)) AS TABLE_NAME,cast(b.name AS VARCHAR(500)) AS COLUMN_NAME, cast(c.VALUE AS VARCHAR(500)) AS COMMENTS,cast(sys.types.name AS VARCHAR (500)) AS DATA_TYPE,( SELECT CASE count(1) WHEN 1 then 'PRI' ELSE '' END FROM syscolumns,sysobjects,sysindexes,sysindexkeys,systypes  WHERE syscolumns.xusertype = systypes.xusertype AND syscolumns.id = object_id (a.name) AND sysobjects.xtype = 'PK' AND sysobjects.parent_obj = syscolumns.id  AND sysindexes.id = syscolumns.id  AND sysobjects.name = sysindexes.name AND sysindexkeys.id = syscolumns.id  AND sysindexkeys.indid = sysindexes.indid  AND syscolumns.colid = sysindexkeys.colid AND syscolumns.name = b.name) as 'KEY',  b.is_identity isIdentity  FROM ( select name,object_id from sys.tables UNION all select name,object_id from sys.views ) a  INNER JOIN sys.columns b ON b.object_id = a.object_id  LEFT JOIN sys.types ON b.user_type_id = sys.types.user_type_id    LEFT JOIN sys.extended_properties c ON c.major_id = b.object_id AND c.minor_id = b.column_id  WHERE a.name = 'house_detial' and sys.types.name !='sysname' 

sqlserver正确查询中文注释的SQL语句应该是:
SELECT CAST
	(
	a.name AS VARCHAR ( 500 )) AS TABLE_NAME,
	CAST (
	b.name AS VARCHAR ( 500 )) AS COLUMN_NAME,
	c.VALUE  AS COMMENTS,
	CAST (
	sys.types.name AS VARCHAR ( 500 )) AS DATA_TYPE,
	(
SELECT
CASE
COUNT
	( 1 ) 
	WHEN 1 THEN
	'PRI' ELSE '' 
END 
FROM
	syscolumns,
	sysobjects,
	sysindexes,
	sysindexkeys,
	systypes 
WHERE
	syscolumns.xusertype = systypes.xusertype 
	AND syscolumns.id = object_id( a.name ) 
	AND sysobjects.xtype = 'PK' 
	AND sysobjects.parent_obj = syscolumns.id 
	AND sysindexes.id = syscolumns.id 
	AND sysobjects.name = sysindexes.name 
	AND sysindexkeys.id = syscolumns.id 
	AND sysindexkeys.indid = sysindexes.indid 
	AND syscolumns.colid = sysindexkeys.colid 
	AND syscolumns.name = b.name 
	) AS 'KEY',
	b.is_identity isIdentity 
FROM
	( SELECT name, object_id FROM sys.tables UNION ALL SELECT name, object_id FROM sys.views ) a
	INNER JOIN sys.columns b ON b.object_id = a.object_id
	LEFT JOIN sys.types ON b.user_type_id = sys.types.user_type_id
	LEFT JOIN sys.extended_properties c ON c.major_id = b.object_id 
	AND c.minor_id = b.column_id 
WHERE
	a.name = 'house_detial' 
	AND sys.types.name != 'sysname'

**Comment by qmdx** [comment]
暂未做过 2017 sqlServer 的适配，你可以自定义下表信息查询类 参考 com.baomidou.mybatisplus.generator.config.querys.SqlServerQuery 然后注入进去
