### ISSUE TITLE
自定义 service 生成 2个 bean

### ISSUE THREAD

**Issue by kuchaguangjie** [baomidou/mybatis-plus#1277]
## 代码

接口 - UserService.java

```
public interface UserService extends IService<User> {
    User getUser(Serializable id);
}
```

实现 - UserServiceImpl.java

```
@Service
public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements UserService {
    public User getUser(Serializable id) {
        return getById(id);
    }
}
```

## 问题

启动 spring-boot 项目时, 产生了 2个 bean `userService` 和 `userServiceImpl`, 一个使 proxy 对象, 一个是 UserServiceImpl.java 的 对象.

如果 注解 时使用 `UserService` 作为 类型, 会说 有2个 bean, 无法 选择, 而报错.

如果 注解 时使用 `UserServiceImpl` 作为 类型, 倒是可以.

另外 如果 启动 `@EnableTransactionManagement` 注解, 则 第二种 也不行.

请问, 当 需要 扩展 service 层 方法时, 在 mybatis-plus 里 一般 应该怎么来写?

**Comment by kuchaguangjie** [comment]
解决方法是:

- 定义一个 service interface 继承 IService
- 定义一个 service impl 继承 ServiceImpl, 并添加 `@Service` 注解
- 在 controller 里, 用 `@Resource` 注入 service interface.

**Comment by zhanzufen** [comment]
遇到同样的问题，生成UserService 的代理感觉是多余的
