### ISSUE TITLE
代码生成器优化意见

### ISSUE THREAD

**Issue by wanghongshuang** [baomidou/mybatis-plus#1279]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis plus: 3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

目前代码生成器的生成策略只有两种，一种是直接覆盖原文件，一种是什么文件都不生成，建议代码生成器在FileOverride配置为false的情况下，也生成相关的文件，并以特定的后缀结尾，以便在扩展字段时，对源文件进行修改，类似mybatis的代码生成器逻辑。

同时请问一下，在不修改mybatis plus generator源代码的情况下，如何扩展实现上述功能，翻了所有的API没有找到可以扩展的地方。

**Comment by qmdx** [comment]
这个是个性需求无法给予支持，不过你可以利用自定义 FileOutConfig 重写默认模板输出方式 https://mp.baomidou.com/guide/generator.html
