### ISSUE TITLE
怎么把ssm框架里的myabtis替换为mp啊

### ISSUE THREAD

**Issue by FENG1000** [baomidou/mybatis-plus#128]
参照这问题把maven需要引入的jar包，配置文件的内容都改好了，但总是报jar包冲突

**Comment by qmdx** [comment]
好好阅读文档 http://mp.baomidou.com 里面再三强调去掉除了 mp 之外的所有 mybatis 依赖， 还是不会就参考 demo 和 优秀案例。再是搞不定进群

**Comment by FENG1000** [comment]
参照文档通过maven引入需要的jar包，对照文档修改配置文件，service层，dao层继承相关接口就好了

在 2017-08-10 15:08:58，"qmdx" <notifications@github.com> 写道：


Closed #128.
