### ISSUE TITLE
DynamicDataSourceProperties这个bean无法刷新

### ISSUE THREAD

**Issue by itmaaa** [baomidou/mybatis-plus#1280]
### 当前使用版本(必须填写清楚，否则不予处理)
  dynamic-datasource-spring-boot-starter-2.5.3.jar

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用apollo监听配置文件属性更新
this.applicationContext.publishEvent(new EnvironmentChangeEvent(changedKeys));

发现自定义的bean都能刷新，只有这个包DynamicDataSourceProperties属性没有被刷新
导致无法做到不重启重新刷新动态数据源

### 重现步骤
可以调用spring的事件看能否刷新这个bean

### 报错信息
无报错，属性更新监听得到，实际bean里的属性未更新

**Comment by qmdx** [comment]
请提交到 https://github.com/baomidou/dynamic-datasource-spring-boot-starter
