### ISSUE TITLE
自定义sql列名转换问题

### ISSUE THREAD

**Issue by tfwx** [baomidou/mybatis-plus#1281]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.3

### 该问题是怎么引起的？
通过@TableField注解可以进行列名转换，但是，如果是我自定义的sql，好像就失效了，
比如我的XML里有这样一条SQL:
select name, age from user where id = 1
假如我的数据库字段是name和而实体类里对应的属性是username，即使我在username属性上加了@TableField属性重新指定列名，还是无法映射到该属性上，请问，这个有解决办法么，不用在自定义sql里用 as 显示指定实际属性的情况下

**Comment by miemieYaho** [comment]
不支持

**Comment by yuxiaobin** [comment]
可以的，使用mybatis自带的 [resultMap](https://www.cnblogs.com/kenhome/p/7764398.html)

**Comment by tfwx** [comment]
> 可以的，使用mybatis自带的 [resultMap](https://www.cnblogs.com/kenhome/p/7764398.html)

嗯嗯，resultMap 确实可以，但是我不并想这么干，因为要写很多个  resultMap， 而且，我也不想用 AS 指定别名，这样会很麻烦。MybatisPlus既然作为Mybatis的超强辅助，在某些方面，还是没有解决这些麻烦的问题，，无奈。。。。。。
