### ISSUE TITLE
mybatis-plus 同时连接mysql和oracle导致用JPA生成SQL出错

### ISSUE THREAD

**Issue by amoslam1** [baomidou/mybatis-plus#1282]
### **当前使用版本**
`<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
        </dependency>
`
### **该问题是怎么引起的？**
使用：mybatis-plus 同时连接mysql和oracle
数据源：用的阿里的Druid
用法：使用Druid的AbstractRoutingDataSource做动态数据源切换

先调用mysql，可以取回正确结果，然后再调用oracle就生成的mysql的SQL
先调用oracle，也可以取回正确结果，再调用mysql生成的就是oracle的SQL

请问这个问题应该怎么解决？

**Comment by miemieYaho** [comment]
自行解决

**Comment by amoslam1** [comment]
> 自行解决
这个问题应该是执行第一次的时候，比如说先执行mysql，mybatis-plus就把数据库设置成mysql，导致oracle的数据源调用JPA生成了mysql的SQL，发送给oracle执行报错，这个应该是mybatis-plus插件的BUG吧？用原生SQL是没问题的

**Comment by amoslam1** [comment]
@miemieYaho 
这个问题应该是执行第一次的时候，比如说先执行mysql，mybatis-plus就把数据库设置成mysql，导致oracle的数据源调用JPA生成了mysql的SQL，发送给oracle执行报错，这个应该是mybatis-plus插件的BUG吧？用原生SQL是没问题的

**Comment by qmdx** [comment]
怎么还有 jpa 你这个项目如此混乱？你自己解决吧爱莫能助
