### ISSUE TITLE
日期转换出错; 

### ISSUE THREAD

**Issue by cielswift** [baomidou/mybatis-plus#1284]
### 当前使用版本(必须填写清楚，否则不予处理)
version_3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

代码生成器,会把数据库的 date类型生成为 Java 的LocalDate类型,而进行查询会报SQLFeatureNotSupportedException 错误; 但是把转换策略换成DateType.ONLY_DATE,生成 java的 Date类型就没问题;

### 报错信息
SQLFeatureNotSupportedException;

![1](https://user-images.githubusercontent.com/42295829/59818612-2a24bf80-9357-11e9-8bb9-422590cdf723.PNG)
![2](https://user-images.githubusercontent.com/42295829/59818613-2a24bf80-9357-11e9-882e-1ea71967c015.PNG)

**Comment by miemieYaho** [comment]
druid 的问题

**Comment by cielswift** [comment]
连接池的问题还是plus的问题?

**Comment by qmdx** [comment]
连接池的问题这个问题 issue 提了多几个了你搜下
