### ISSUE TITLE
SqlMethod的枚举中UPDATE_ALL_COLUMN_BY_ID中sql 是否多了SET ?

### ISSUE THREAD

**Issue by dingshijie** [baomidou/mybatis-plus#1285]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在扩展 UPDATE_ALL_COLUMN_BY_ID 时发现 com.baomidou.mybatisplus.core.enums.SqlMethod
中 UPDATE_ALL_COLUMN_BY_ID 的枚举中的 sql 多了一个SET

### 重现步骤

可以直接看上面贴出的枚举信息

### 报错信息
提示
UPDATE t_table SET SET c1=?, c2=? WHERE id=?

**Comment by miemieYaho** [comment]
没多

**Comment by dingshijie** [comment]
使用的时候会报错，脚本中会出现两个SET

**Comment by yangyining** [comment]
这个里面确实多了，如果没多了话这个地方要怎么用？？？
![image](https://user-images.githubusercontent.com/3253098/62510260-efacae80-b840-11e9-8d27-e9388d4861aa.png)

**Comment by dingshijie** [comment]
> 
> 
> 这个里面确实多了，如果没多了话这个地方要怎么用？？？
> ![image](https://user-images.githubusercontent.com/3253098/62510260-efacae80-b840-11e9-8d27-e9388d4861aa.png)

我那里也是先自行replace了SET 为空, 不替换就提示多了SET

**Comment by qmdx** [comment]
fixed: issue https://github.com/baomidou/mybatis-plus/issues/1460

**Comment by dingshijie** [comment]
> 
> 
> fixed: issue #1460

好的
