### ISSUE TITLE
多租户两张表查询，其中一张没有拼接租户ID

### ISSUE THREAD

**Issue by sangyuan6122** [baomidou/mybatis-plus#1289]
### 当前使用版本(必须填写清楚，否则不予处理)
版本3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
例如(两张表不需要关联字段):select * from test1 a,test2 b where a.name='xxx'  
parser sql：select * from test1 a,test2 b where a.name='xxx'  and a.tenant_id=1
这里没有拼接test2的tenant_id，是设计本身就是这样还是bug呢?

**Comment by miemieYaho** [comment]
使用标准 inner join 试试

**Comment by sangyuan6122** [comment]
好使，谢谢~
