### ISSUE TITLE
ServiceImpl中多数据源问题

### ISSUE THREAD

**Issue by sunqqqq** [baomidou/mybatis-plus#129]
ServiceImpl中多数据源问题
我想在这个父类中的方法执行前，动态的设置数据源。使用spring aop的方式，不能够在调用ServiceImpl中的方法切入。请问各位大牛，这个问题应该怎么解决？谢谢！

**Comment by eidolonse** [comment]
可以这样：
`@Pointcut("execution(* com.test.*.service..*(..)) || execution(* com.baomidou.mybatisplus.service.impl.ServiceImpl+.*(..))")
public void pointCut() {

}`

**Comment by sunqqqq** [comment]
问题已解决，谢谢！

**Comment by EverSpring** [comment]
这种写法有问题吧，会在所有的数据源中去查询一次，因为point()都会调用com.baomidou.mybatisplus.service.impl.ServiceImpl
