### ISSUE TITLE
@TableLogic update方法deleted的值会被自动过滤掉

### ISSUE THREAD

**Issue by weecoding123** [baomidou/mybatis-plus#1290]
### 当前使用版本
3.1.1

### 该问题是怎么引起的？

当使@TableLogic注解deleted字段的，批量操作一批数据，既有更新，又有插入操作，其中更新需要将deleted从0更新为1。此时发现字段deleted被过滤掉了

### 重现步骤
调用更新语句：
预想输出的SQL为：
UPDATE user SET username=?, age=?, deleted=? WHERE id=? AND deleted=0
实际打印SQL数据：
UPDATE user SET username=?, age=? WHERE id=? AND deleted=0

**Comment by miemieYaho** [comment]
就是这么设计的
