### ISSUE TITLE
mybaits-plus 3.1.1 主键自增不生效

### ISSUE THREAD

**Issue by CoolRabbit593190** [baomidou/mybatis-plus#1291]
### 当前使用版本(必须填写清楚，否则不予处理)

mybaits-plus 3.1.1 版本

### 重现步骤

使用mybatis-plus 3.1.1 版本 表对应entity已设置IdType.AUTO，插入之后的id依然很长，应该还是id_worker形式

**Comment by miemieYaho** [comment]
看文档

**Comment by CoolRabbit593190** [comment]
按照文档做的 其他主键模式都生效 就是自增不生效哦
