### ISSUE TITLE
物理表主键字段名不是id

### ISSUE THREAD

**Issue by keyboardTab** [baomidou/mybatis-plus#1293]
### 当前使用版本(必须填写清楚，否则不予处理)
mybaits-plus 3.1.1 版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库物理表主键字段名不是id导致updateById以及其他与id相关的操作都无法使用
是我的配置有误吗

### 重现步骤
设置物理表中无id字段 然后调用updateById()

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'null' in 'class com.jd.modular.model.jd.TsetNew'

**Comment by dingxudong2017** [comment]
可以设置@TableId(value = "user_id", type = IdType.AUTO) 指定物理数据表value =表字段

**Comment by miemieYaho** [comment]
如上
