### ISSUE TITLE
希望支持"去除某一全局后缀"

### ISSUE THREAD

**Issue by Baby-boy** [baomidou/mybatis-plus#1294]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
优化建议：希望支持"去除某一全局后缀"
例如：
  entity：UserDO
  tableName：t_user
现阶段支持了全局前缀 t_
希望支持去除某一全局后缀 DO 类似功能

### 重现步骤
如上所述

### 报错信息
如上所述

**Comment by miemieYaho** [comment]
不支持

**Comment by qmdx** [comment]
支持全局前缀 GlobalConfig.DbConfig.tablePrefix 全局配置，后缀不支持
