### ISSUE TITLE
3.1.1 entity的delete方法和IService的remove方法的问题

### ISSUE THREAD

**Issue by justlikeliuen** [baomidou/mybatis-plus#1295]
### 3.1.1版本
Model的delete方法和IService的remove方法在底层都是走的update方法，但是使用MetaObjectHandler却无法捕捉到方法执行

### 该问题是怎么引起的？
因为想要在进行逻辑删除的时候通过wapper参数获取到删除时间和操作人，但是调用这两个方法的时候却无法进入到MetaObjectHandler

### 重现步骤
MetaObjectHandler却无法捕捉到Model的delete方法和IService的remove方法

### 报错信息
无报错

**Comment by miemieYaho** [comment]
看文档,deletebyid 不支持填充
