### ISSUE TITLE
saveOrUpdateBatch()方法在测试事务中有问题

### ISSUE THREAD

**Issue by BestRoach** [baomidou/mybatis-plus#1296]
### 当前使用版本(必须填写清楚，否则不予处理)

MyBatisPlus Version:3.1.0
SpringBoot Version:1.5.11.RELEASE
TestNG Version:6.14.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

测试方法继承AbstractTransactionalTestNGSpringContextTests，使用saveOrUpdateBatch()方法后，马上做getById()操作，不会有数据库操作。
也就是说，当执行了saveOrUpdateBatch()后，对插入列表中的id做查询的时候，是无法得到插入值的。

### 重现步骤
1.saveOrUpdateBatch()
![image](https://user-images.githubusercontent.com/24383238/60148014-06072980-9802-11e9-8ba6-25bb523fde8d.png)
2.马上去做查询
![image](https://user-images.githubusercontent.com/24383238/60148223-d0167500-9802-11e9-9c66-04fd53599f7c.png)

### 报错信息

没有报错。

**Comment by miemieYaho** [comment]
不是同一个 sqlsession,
