### ISSUE TITLE
3.1.1 版本代码生成器的 ftl 的 entity 模板 代码缩进有问题

### ISSUE THREAD

**Issue by Leelister** [baomidou/mybatis-plus#1297]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用代码生成器，模板使用 Freemark

### 重现步骤
直接使用代码生成器，我从你们github上master分支看到了entity.java.ftl 中的缩进确实乱了，3.1.0是正常的。

### 报错信息
无

**Comment by Leelister** [comment]
velocity 的 entity 模板也会有问题

**Comment by qmdx** [comment]
已经调整过 3.1.2 已发布你试试
