### ISSUE TITLE
注入分页插件无效

### ISSUE THREAD

**Issue by Baby-boy** [baomidou/mybatis-plus#1299]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
已经将分页插件PaginationInterceptor以Bean的形式注入到SpringBoot中，但实际在使用的过程中未分页
![image](https://user-images.githubusercontent.com/20492148/60166661-26e87280-9834-11e9-8dc9-9236934fd2c3.png)
![image](https://user-images.githubusercontent.com/20492148/60166700-38ca1580-9834-11e9-8aad-1f9e4b9a7f30.png)
![image](https://user-images.githubusercontent.com/20492148/60166742-4bdce580-9834-11e9-9a0c-273a1fb38818.png)

### 报错信息
无报错

**Comment by miemieYaho** [comment]
去看 samples

**Comment by yuxiaobin** [comment]
https://gitee.com/2579/mybatis-plus-samples/tree/master/mybatis-plus-sample-pagination
