### ISSUE TITLE
是否友好支持树形结构查询

### ISSUE THREAD

**Issue by micro-bean** [baomidou/mybatis-plus#1302]
### 当前使用版本(必须填写清楚，否则不予处理)

v3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

相关文档为提及树形查询方法，除了自己xml写查询，是否有更好的树形查询

**Comment by miemieYaho** [comment]
没有
