### ISSUE TITLE
使用gradle不能添加依赖项mybatis-plus-generator

### ISSUE THREAD

**Issue by WeiXiaoxia** [baomidou/mybatis-plus#1303]
项目构建工具用的gradle，但不能添加mybatis-plus-generator依赖，也不能添加mybatis-plus 3.0.3 以前版本。配置如下：
repositories {
	maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }
	maven { url "https://dl.bintray.com/liushuixiaoxia/maven"  }
	maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
	mavenCentral()
	jcenter()

}
dependencies {
	compile group: 'com.baomidou', name: 'mybatis-plus', version: '3.1.1'
	compile group: 'com.baomidou', name: 'mybatis-plus-generator', version: '3.1.2'
}

**Comment by WeiXiaoxia** [comment]
@miemieYaho 为什么关掉我的 issue?

**Comment by WeiXiaoxia** [comment]
@miemieYaho 本地添加jar包也不能用，求解？

**Comment by miemieYaho** [comment]
maven 能用 gradle 不能用?可能吗?

**Comment by WeiXiaoxia** [comment]
丢个例子出来，试过才有发言权。从maven仓库下载的jar包本地引用也不行。这个要求jdk版本吗？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples
