### ISSUE TITLE
查询数据返回结果集为空时PerformanceInterceptor没执行

### ISSUE THREAD

**Issue by abccd33** [baomidou/mybatis-plus#1305]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

当使用自定义SQL查询数据并且返回结果集为空时（没有查询到满足条件的结果）
SQL打印插件不会打印任何语句

### 报错信息
无

**Comment by miemieYaho** [comment]
该插件不再维护
