### ISSUE TITLE
什么会支持简单的多表关联查询呢？

### ISSUE THREAD

**Issue by lynings** [baomidou/mybatis-plus#131]

**Comment by qmdx** [comment]
可以尝试使用 resultMap  可以通过注解 @TableName ( ... resultMap = "xml 中的 map id 关联") ，  mp 不会去支持 复杂的多表操作的， 复杂 sql 要的就是 mybatis xml sql 的灵活性，如果你想要这样的可以使用 hibernate 可能更适合你。
