### ISSUE TITLE
动态表名 SQL 解析器

### ISSUE THREAD

**Issue by climbingDog** [baomidou/mybatis-plus#1312]
### 3.1.1

动态表名 SQL 解析器
https://mybatis.plus/guide/dynamic-table-name-parser.html

这个描述比较简单。
可以给一个使用的demo吗，实在看不懂这个表达的意思。自己写xml传递表名，也就要自己写字段了，真的是很痛苦。

**Comment by sdmq** [comment]
例子程序里边有个例子

**Comment by climbingDog** [comment]
> 例子程序里边有个例子
> https://github.com/baomidou/mybatis-plus-samples

具体使用参考多租户
com.baomidou.mybatisplus.samples.tenant
这个项目吗？
说实话，真的不是太看得懂这个和动态表名 SQL 解析器的关联，也不知道怎么动态切换表名，可以在md里写个简单的使用的demo吗？

**Comment by qmdx** [comment]
1、配置注入动态表名 sql 解析器到解析链
2、需要动态处理表名设置一个复杂一些的名称
3、注入动态处理 handler

**Comment by climbingDog** [comment]
OK

**Comment by ylooq** [comment]
> OK

请问你研究出来了吗？怎么实现的

**Comment by LuSir001** [comment]
动态表名 SQL 解析器  这个真不知道怎么使用，有谁使用过的吗？

**Comment by LuSir001** [comment]
使用过的分享一下啊，qq:471769165

**Comment by ysguo0327** [comment]
貌似参数传不过来啊，你们是怎么解决的？
