### ISSUE TITLE
select-strategy

### ISSUE THREAD

**Issue by scxkd2016** [baomidou/mybatis-plus#1314]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
insertStrategy   updateStrategy  selectStrategy 这三个配置项具体怎么使用？配置了selectStrategy=empty_not 在进行select 的时候还会出现在where条件中。

### 重现步骤
mybatis-plus:
  global-config:
    db-config:
      select-strategy: not_empty
————————————————————————————
QueryWrapper<User> queryWrapper = new QueryWrapper<>();
        String name= "";
        List<User> users = userMapper.selectList(queryWrapper.eq("id", 1).gt("name", name));
        users.forEach(System.out::println);

### 报错信息
SELECT id,name,age,email
 FROM user
 WHERE id = 1 AND name > '';

**Comment by miemieYaho** [comment]
对wrapper无效，只对wrapper内的entity有效
