### ISSUE TITLE
uuid 生成策略

### ISSUE THREAD

**Issue by ylx252** [baomidou/mybatis-plus#1317]
版本 v3.1.2
uuid 默认是使用 IdWorker.get32UUID() 来生成的。
有什么办法可以自定义这个 uuid 生成策略，比如有序uuid。

**Comment by miemieYaho** [comment]
没有

**Comment by qmdx** [comment]
填充看下，利用这个自定义解决

**Comment by ylx252** [comment]
填充太麻烦了，而且重写需要各种 if，开放个重写接口也行啊

**Comment by qmdx** [comment]
@ylx252 mp id 策略就是填充原理， 或者你可以设置手动设置
