### ISSUE TITLE
关于BaseMapper接口建议

### ISSUE THREAD

**Issue by cnshegg** [baomidou/mybatis-plus#1318]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

建议在BaseMapper<T> 之上，再分一层Mapper: ReadMapper<T>,WriteMapper<T> 分别定义对数据库的读和写(增删改)的方法。（BaseMapper再继承ReadMapper,WriteMapper）。这样有利于做读写分离处理：比如用户可以用BaseMapper来处理原始表的读写操作；再用多个ReadMapper定义各种不同返回不同字段（关联字段等）情况下的查询操作，只读不写。同理，可以用多个WriteMapper，进行自定义的写操作（比如同时写多个关联表等）。

**Comment by qmdx** [comment]
你可以自定义 baseMapper 参考 https://mybatis.plus/guide/sql-injector.html 构建你自己的 baseMapper 按需注入

**Comment by cnshegg** [comment]
我看了关于注入SQL的例子，MyBaseMapper接口是继承的BaseMapper。
我自己试了一下，Dao不从BaseMapper继承的话，Dao接口不会被实现，Spring 代理会报找不到实现类。比如我有个IViewDao<T> expends Mapper<T>
如何让 继承了  IViewDao 的接口能够自动映射？（IViewDao 接口里，只包含了BaseMapper里的查询类方法）

**Comment by yuxiaobin** [comment]
来，sample在此，参考自己玩

https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-customize-basemapper
