### ISSUE TITLE
代码生成器对pgsql10.7的数字类型支持不好

### ISSUE THREAD

**Issue by mizhilong** [baomidou/mybatis-plus#1319]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

postgresql，版本10.7，使用代码生成器，对于decimal类型会生成为String。

### 重现步骤
定义一列为decimal（实际数字型的都会有问题），使用代码生成器，会将对应列生成为String，使用mybatis官方生成器，不会出现该问题。

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/converts/PostgreSqlTypeConvert.java
你可以自己重写然后 set 进去
