### ISSUE TITLE
2.1.0 解决布尔类型is开头生成sql错误问题 修复有问题

### ISSUE THREAD

**Issue by markfredchen** [baomidou/mybatis-plus#132]
应该区分Boolean和boolean分别处理。Java针对Boolean和boolean命名规范是不一样的。【v2.1.0 解决布尔类型is开头生成sql错误问题】在Boolean下就有问题了。

@Getter
private boolean good; // => isGood()

@Getter
private Boolean isGood; // => getIsGood()

其实使用MP应该少用boolean，否则使用baseMapper.selectOne, update 等需要根据传入非空字段做处理的方法，boolean如果不设值，默认为false, 这些方法就废了。

**Comment by qmdx** [comment]
抱歉！ mp 中由于判断 null 来处理查询条件的，因此不建议使用 基本类型 boolean 推荐都是包装类修饰

**Comment by youngledo** [comment]
但是阿里巴巴Java规范提到不应该使用is开头来定义布尔类型。因此，如果我写这样的话，应该是可以映射的：
```java
private Boolean good;
```
而数据库的字段是`is_good`。
