### ISSUE TITLE
@TableField typeHandler 不生效,为JSON类型,返回NULL

### ISSUE THREAD

**Issue by vnobo** [baomidou/mybatis-plus#1321]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

 @TableField(jdbcType = JdbcType.VARCHAR,typeHandler=JsonNodeTypeHandler.class)

### 重现步骤
数据库是MY SQL,Demo字段 类型 JSON,

使用@TableField 注解自定义类型

@Data
@Accessors
public class DemoEntry implements Serializable {

    @TableId(value = "id",type = IdType.AUTO)
    private Long id;

    @TableField(jdbcType = JdbcType.VARCHAR,typeHandler=JsonNodeTypeHandler.class)
    private JsonNode extend;
}

类型转换类
public class JsonNodeTypeHandler extends BaseTypeHandler<JsonNode> {

    private ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, JsonNode parameter, JdbcType jdbcType) throws SQLException {
        ps.setString(i, this.toJson(parameter));
    }

    @Override
    public JsonNode getNullableResult(ResultSet rs, String columnName) throws SQLException {
        return this.toObject(rs.getString(columnName), JsonNode.class);
    }

    @Override
    public JsonNode getNullableResult(ResultSet rs, int columnIndex) throws SQLException {
        return this.toObject(rs.getString(columnIndex), JsonNode.class);
    }

    @Override
    public JsonNode getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {
        return this.toObject(cs.getString(columnIndex), JsonNode.class);
    }

    private String toJson(JsonNode object) {
        try {
            return objectMapper.writeValueAsString(object);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private JsonNode toObject(String content, Class<JsonNode> clazz) {
        if (content != null && !content.isEmpty()) {
            try {
                return objectMapper.readValue(content, clazz);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        } else {
            return null;
        }
    }
}

### 报错信息
该字段返回为NULL,无法获取到数据

**Comment by miemieYaho** [comment]
去掉 el,扫描你的 typehandler 包

**Comment by vnobo** [comment]
@miemieYaho 还是不行的!

**Comment by miemieYaho** [comment]
那就 自己写 resultmap应用,或者在 tablename 注解里把自动 resultmap 打开

**Comment by vnobo** [comment]
`@Data
@TableName(resultMap = "",autoResultMap = true)
public class TenantUserTimeEntry implements Serializable {

    @TableId(value = "id",type = IdType.AUTO)
    private Long id;

    @TableField(jdbcType = JdbcType.VARCHAR,typeHandler= JsonNodeTypeHandler.class)
    private JsonNode extend;

}`
刚测试了下 这样 客户端居然请求死机了,

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/base/entity/ResultMapEntity.java

**Comment by VeChar** [comment]
确实存在不自定义handler生效的问题，相同版本 @
