### ISSUE TITLE
建议代码生成器增加对postgresql中numeric类型的支持

### ISSUE THREAD

**Issue by mizhilong** [baomidou/mybatis-plus#1322]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库中存在numeric类型的字段，代码生成工具将该字段生成为string，导致使用出错。

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html#%E6%B3%A8%E5%85%A5%E6%9F%A5%E8%AF%A2%E5%AD%97%E6%AE%B5%E5%85%B6%E4%BB%96%E4%BF%A1%E6%81%AF

**Comment by qmdx** [comment]
如上 地址重写注入部分字段查询，然后重写 PostgreSqlTypeConvert 注入即可
