### ISSUE TITLE
@TableField对虚拟计算字段,sql 支持

### ISSUE THREAD

**Issue by vnobo** [baomidou/mybatis-plus#1329]
功能描述:
  我的实体类有一个时间差的字段totalTime,这个字段是开始时间和结束时间字段计算得来的.
  能否增加一个字段计算SQL属性,或者注解呢

   @TableField(exist = false,for="(IFNULL(TIMESTAMPDIFF(MINUTE,begin_date,IFNULL(end_date,now())),0)-IFNULL(TIMESTAMPDIFF(MINUTE,lunch_date,back_lunch_date),0)) AS totalTime")
    private int totalTime;

**Comment by miemieYaho** [comment]
不支持,自己 java 里算了 set 进去

**Comment by vnobo** [comment]
有没有想法去支持呢
