### ISSUE TITLE
数据库字段是驼峰命名规则，使用查询的时候为什么会把字段改为下划线分割？

### ISSUE THREAD

**Issue by butioy** [baomidou/mybatis-plus#133]
数据库字段是 deviceType 这种形式，  生成的实体类也是一样，但是在查询的时候，会把deviceType自动改为device_type，导致应为没有device_type字段而报错，  我在实体类的属性上加上了@TableField("deviceType")也不行！！

**Comment by qmdx** [comment]
关闭下划线命名配置， 1、 MP 的配置  2、mybatis 原生配置 都检查是否开启了
