### ISSUE TITLE
请问QueryWrapper(entity)封装查询条件遇boolean怎么办

### ISSUE THREAD

**Issue by sks-lwei** [baomidou/mybatis-plus#1330]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用QueryWrapper(T entity)方式封装查询条件，当啊entry中含有boolean属性值字段时，wrapper会自动采用boolean的默认值（即false）封装查询条件，导致查询结果不准确。

### 重现步骤

例如User对象，属性有String name；boolean sex；
新建一个对象 User user = new User("张三");
list(new QueryWrapper(user));查询就会出问题，

此时的SQL显示为 select...where name=‘张三’ and sex=false 

但这不是我想要的，我想要的是select...where name=‘张三’

使用queryWrapper.eq("name", "张三");可以解决，但不现实，太多地方使用上述方式，排查难度太大，且改了之后代码耦合度太高

或者将boolean类型更换，可以解决，但是业务需要，无法更换

请问如何解决这个问题？

**Comment by miemieYaho** [comment]
换 Boolean

**Comment by sks-lwei** [comment]
了解，谢过

**Comment by Abhishek1312** [comment]
Please unsubscribe.

Regards,
Abhishek
9930417142
