### ISSUE TITLE
有表字段y_1、 y_2 、 y_3

### ISSUE THREAD

**Issue by zhangandyhui** [baomidou/mybatis-plus#1331]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
有表字段y_1、 y_2 、 y_3  生成的Bean  y1,y2,y3 生成的sql  y1,y2,y3 所以查询报错

**Comment by miemieYaho** [comment]
看文档,加注解

**Comment by zhangandyhui** [comment]
奇怪的是其他的下划线字段就没问题  当然没有看您的源码  不知道为啥单独针对_数字的进行额外处理，先谢了 已经用了TableField处理了  还是抽空得拜读一下您的源码

**Comment by yuxiaobin** [comment]
下划线，驼峰 
first_name, firstName
可以通过首字母大写来区分下划线

y_1/y1 ->y1
数字就没法区分

**Comment by zhangandyhui** [comment]
好的 谢谢了 麻烦再问一下 3.x版本的   CachePaginationInterceptor为什么去掉了 现在有没有最新版的？
