### ISSUE TITLE
kotlin 的Children orderByAsc(R... columns)  突然不会写了

### ISSUE THREAD

**Issue by TongxiJi** [baomidou/mybatis-plus#1332]
### 当前使用版本
3.1.2

### 报错信息

![TIM截图20190703201728](https://user-images.githubusercontent.com/10556096/60591025-1013c400-9dd0-11e9-94e5-a297d7cf09a8.png)

**Comment by hcl04** [comment]
Kotlin 下 :: 属性返回的是一个 KProperty，而方法本身接受的是 Function，目前 mp 对 kotlin 上下的功夫并不大，所以很多问题处理的并不周全或者尚未考虑。

目前你需要显示的转换方法引用才可以，需要将原有代码改为：
orderByAsc(Function(DkpGuild::gserver), Function(DkpGuild::gname))

**Comment by TongxiJi** [comment]
老哥稳
