### ISSUE TITLE
获取动态表名 ITableNameHandler  不支持saveOrUpdate和saveOrUpdateBatch

### ISSUE THREAD

**Issue by zhangandyhui** [baomidou/mybatis-plus#1333]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
根据指定字段分表  自己实现ITableNameHandler时候 saveOrUpdate和saveOrUpdateBatch方法不支持分表策略

**Comment by LuSir001** [comment]
动态表名 SQL 解析器  这个是怎么试用，请指教 QQ 474769165

**Comment by liu87** [comment]
测试了一下，在进行动态数据表切换的情况下，IService#saveOrUpdate方法可用，测试中分别更新了两张数据表的数据。而IService#saveBatch也无法正常运行，控制台无任何SQL语句输出（事先配置为SQL输出）。
版本3.1.2

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/issues/1395
