### ISSUE TITLE
模糊查询

### ISSUE THREAD

**Issue by zuihou** [baomidou/mybatis-plus#1335]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
1,Bean 配置
```
        GlobalConfig conf = new GlobalConfig();
        GlobalConfig.DbConfig config = new GlobalConfig.DbConfig();
        config.setFieldStrategy(FieldStrategy.NOT_EMPTY);
        config.setColumnLike(true);
```
2，查询代码
```
Application data = new Application();
data.setCode("%");    //  前端只想查询 数据库中包含了   %  的值(由于%是模糊查询关键字)
data.setName("_");      // 前端只想查询 数据库中包含了   _    的值(由于_是模糊查询关键字)
QueryWrapper<Application> query = new QueryWrapper(data);
applicationService.page(page, query);
```

### 报错信息
```
     SELECT *   FROM   application 
    WHERE  code LIKE CONCAT('%', '%', '%')
     &&  name LIKE CONCAT('%', '_', '%')
```

问题描述：
模糊查询时，希望能替换参入参数中的 % 和 _ 这2个关键字

**Comment by zuihou** [comment]
之所以使用 QueryWrapper<Application> query = new QueryWrapper(data); 来配置查询条件，就是为了省事， 虽然 query.like(StringUtils.isEmpty(data.getCode(), "code", data.getCode().replaceAll("\\%" "\\\\%")) ； 是可解决问题。

但想象一下， 假设改表有50个字段， 我想给每个字段都增加 非空 就查询的条件， query.like 方法就要调用50次.....

**Comment by miemieYaho** [comment]
不支持,你只能自己处理
