### ISSUE TITLE
目前TableInfo和TableFields 是否没有表字段的是否为空，字段长度等信息？

### ISSUE THREAD

**Issue by LeeCoder3962** [baomidou/mybatis-plus#1336]
### 当前使用版本
3.0.5

目前TableInfo和TableFields 是否没有表字段的是否为空，字段长度等信息？
Oracle数据库

**Comment by miemieYaho** [comment]
没有

**Comment by yuxiaobin** [comment]
你是指代码生成的时候，获取字段的元数据信息？比如该字段是否nullable, 长度多少，
猜测是想生成hibernate validator字段验证注解之类的用途吧

目前mp是没有这些。而且不同数据库的语句不同。
你可以参考
`com.baomidou.mybatisplus.generator.config.querys.OracleQuery`
应该可以获取到字段元数据

**Comment by LeeCoder3962** [comment]
> 你是指代码生成的时候，获取字段的元数据信息？比如该字段是否nullable, 长度多少，
> 猜测是想生成hibernate validator字段验证注解之类的用途吧
> 
> 目前mp是没有这些。而且不同数据库的语句不同。
> 你可以参考
> `com.baomidou.mybatisplus.generator.config.querys.OracleQuery`
> 应该可以获取到字段元数据

感谢，学习源码搞定了。只要
setDbQuery（new OracleQuery（）{}）
 重写其中的tableFieldsSql()和fieldCustom()
就可以注入TableField的customMap属性自己想要的列信息了

既然有这个便利IDbQuery的接口， 文档有提到吗 我好像没看到
