### ISSUE TITLE
逻辑删除插件与where条件中有or造成的sql拼接错误

### ISSUE THREAD

**Issue by zx472010602** [baomidou/mybatis-plus#1337]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

当开启了逻辑删除后，如果查询条件有or，会造成逻辑删除失效一半

### 重现步骤
这是插件输出的拼接后sql，是一个用用户名或手机号查询用户的功能，逻辑删除字段后没有智能拼接括号，实际使用中其他条件和逻辑删除都应该是并列的，应该动态加上括号
SELECT id,username,password,mobile,nick_name,email,salt,state,user_type,create_time,delete_flag,remark
 FROM user_info
 WHERE delete_flag='N' AND username = 'test21' OR mobile = 'test21';

**Comment by jiangtianyou** [comment]
这个感觉蛮严重的啊，是逻辑删除的表，查询时只要带or的where条件，结果都有可能是错的了。

**Comment by kana112233** [comment]
可以用lambda表达式拼接or
QueryWrapper<User> wrapper = new QueryWrapper<>();
  wrapper.and(i->i.eq("username", "123").or().eq("mobile", "456"));
显示的sql
SELECT *
 FROM
        user 
    WHERE
        deleted=0 
        AND (
            username = '123' 
            OR username = '456' 
        )

**Comment by miemieYaho** [comment]
使用 3.2.0
