### ISSUE TITLE
save/updateBatch

### ISSUE THREAD

**Issue by 0532** [baomidou/mybatis-plus#1338]
### 当前使用版本(必须填写清楚，否则不予处理)

版本  3.1.1

 问一下咱们的批量更新是拆成多个单条循环操作，能一个批量更新的一条sql的吗

**Comment by miemieYaho** [comment]
不能

**Comment by qmdx** [comment]
look https://mybatis.plus/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6
