### ISSUE TITLE
Mapper*.xml文件中编写的SQL包含if函数，sql解析异常

### ISSUE THREAD

**Issue by justyyl** [baomidou/mybatis-plus#1341]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
查看当前依赖 jsqlparserVersion = '1.2'。
手动切换到2.0以上的版本，不再抛异常。

### 重现步骤
Mapper*.xml文件中编写的SQL包含if函数

### 报错信息
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select
      if(t.is_pay > 0, 1, 0)

**Comment by yuxiaobin** [comment]
jsqlparser的问题，目前没法解决

可以去给jsqlparse提issue让他解决
