### ISSUE TITLE
mybatis-plus-generator导致的查询错误

### ISSUE THREAD

**Issue by zx472010602** [baomidou/mybatis-plus#1342]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-generator 3.1.1-3.1.2（3.1.0正常）
mybatis-plus 3.1.2
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

将mybatis-plus-generator从3.1.0升级到3.1.2后发现项目启动报错，查询时原mysql中一个timestamp类型列到java的LocalDateTime字段属性的填充显示错误

### 重现步骤
将mybatis-plus-generator从3.1.0升级到3.1.2，查询一个包含日期类型，javaType为jdk1.8的LocalDateTime的表，SQL执行后填充报错（mysql的timestamp）

### 报错信息

org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLFeatureNotSupportedException

**Comment by yuxiaobin** [comment]
mybatis-plus-generator 默认是optional=true的依赖，
只应该在生成代码（建议放test case里面）才有效

项目启动错误，多给点log，或者提供一个简易的能复现的demo

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/issues/1245

**Comment by zx472010602** [comment]
> mybatis-plus-generator 默认是optional=true的依赖，
> 只应该在生成代码（建议放test case里面）才有效
> 
> 项目启动错误，多给点log，或者提供一个简易的能复现的demo

不是的，项目里是optional=true的，也不是启动错误，而是只要引入了mybatis-plus-generator3.1.1以上版本的依赖（和mybatisplus依赖同时存在），在执行查询时（selectOne等）如果该表有时间类型的列，就会查询失败并报错，该时间列无法映射到Bean

**Comment by yuxiaobin** [comment]
参考 #1245
应该是使用了druid数据源导致的问题

**Comment by zx472010602** [comment]
> 参考 #1245
> 应该是使用了druid数据源导致的问题

这个不清楚，但是将mybatis-plus-generator降级到3.1.0之后，mybatis-plus3.1.2也可以正常查询，所以mybatis-plus-generator3.1.1这个版本一定有问题，应该跟#1326是同一个问题

**Comment by zx472010602** [comment]
> 参考 #1245
> 应该是使用了druid数据源导致的问题

#1326

**Comment by BARERM** [comment]
遇到同样的问题，之前用3.1.0，现在是3.1.2.查询报错了。其它没改过。
