### ISSUE TITLE
3.12版本中selectStrategy（whereStrategy）设置为NOT_EMPTY 使用lamda表达式时依然回座位参数传递

### ISSUE THREAD

**Issue by xlb** [baomidou/mybatis-plus#1343]
![image](https://user-images.githubusercontent.com/7923991/60696660-4dd03400-9f19-11e9-9bbe-ff9c60390414.png)

![image](https://user-images.githubusercontent.com/7923991/60696671-5c1e5000-9f19-11e9-8021-479d22e5f203.png)

![Uploading image.png…]()
 不知道算不算bug

**Comment by miemieYaho** [comment]
selectStrategy 和那个无关

**Comment by xlb** [comment]
可以举一个whereStrategy 的标准用法吗，我认为的是如果 设置了某个字段为NOT_EMPTY（默认参考配置文件，配置文件中我设置了NOT_EMPTY） lamdaquery使用eq或者其他表达式时，就会动态拼接sql

**Comment by miemieYaho** [comment]
只对 wrapper 内的 entity 生效

**Comment by xlb** [comment]
建议以后可以集成到query中，我现在又要把我的狗皮膏药贴回去了. 尴尬.jpg

**Comment by miemieYaho** [comment]
我倒是建议你先去了解完原理了再来提建议

**Comment by yuxiaobin** [comment]
whereStrategy仅在使用wrapper.entity作为条件时才生效：
QueryWrapper.setEntity(new User().setName(""));
当name配置为NOT_NULL, 生成where->
`<if test="wrapper.entity.name!=null">and name=#{name}</if>`
默认是
`<if test="wrapper.entity.name!=null and wrapper.entity.name!=''">and name=#{name}</if>`
