### ISSUE TITLE
取出List<Long> Long类型，跟id进行eq无效

### ISSUE THREAD

**Issue by Hellowutongshu** [baomidou/mybatis-plus#1344]
### 当前使用版本(必须填写清楚，否则不予处理)
<version>3.1.2</version>

### 重现步骤
查询时候传入Long类型数组，查询无法无法查询有效数据
List<Long> collect =packingItemInfos.stream().map(PackingItemInfo::getPackingId).collect(Collectors.toList());
                queryWrapper.in("id",collect);
                IPage<PackingInfo> page1 = packingInfoService.page(infoPage, queryWrapper);
                IPage<PackingInfo> packingInfoIPage = packingInfoMapper.selectPage(infoPage, queryWrapper);

**Comment by miemieYaho** [comment]
自己查看执行sql排查

**Comment by Hellowutongshu** [comment]
Execute SQL：SELECT COUNT(1) FROM packing_info WHERE status = '0' AND id IN (11466601234781)  我打印过，这样明明有数据，但查出来没有
