### ISSUE TITLE
mbg怎样自定义columnNaming策略

### ISSUE THREAD

**Issue by liunewshine** [baomidou/mybatis-plus#1345]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

我们的数据库字段明名方式大驼峰（如CreateTime），实体类中要办成createTime,应该怎么配置呢

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/INameConvert.java

实现并注入
