### ISSUE TITLE
mybatis-plus-boot-starter 3.1.0升级3.1.2启动报错

### ISSUE THREAD

**Issue by lijinghui** [baomidou/mybatis-plus#1347]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
从3.1.0升级到3.1.1启动报错，原因是MybatisMapperAnnotationBuilder.getLanguageDriver 找不到这个方法？

### 重现步骤
直接pom.xml 把版本号从3.1.0替换成3.1.2 启动报错，降回3.1.0则正常启动。

可以引入mybatis3.5.1 解决问题
   <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.5.1</version>
        </dependency>
麻烦整合一下？

### 报错信息
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.getLanguageDriver(MybatisMapperAnnotationBuilder.java:369)

The following method did not exist:

    com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;

The method's class, com.baomidou.mybatisplus.core.MybatisConfiguration, is available from the following locations:

    jar:file:/D:/Maven/3.6.1/repository/com/baomidou/mybatis-plus-core/3.1.2/mybatis-plus-core-3.1.2.jar!/com/baomidou/mybatisplus/core/MybatisConfiguration.class

It was loaded from the following location:

    file:/D:/Maven/3.6.1/repository/com/baomidou/mybatis-plus-core/3.1.2/mybatis-plus-core-3.1.2.jar

**Comment by chenshun00** [comment]
我也出现了这个问题
