### ISSUE TITLE
lambda 查询构造不支持别名

### ISSUE THREAD

**Issue by yeshirow** [baomidou/mybatis-plus#1349]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
lambda 使用别名

### 重现步骤
目前不知道是否支持, 该用法我这边主要防写死字符串字段, 是否可以增加条件方法?
如 queryWrapper.lambda().eq(TestBody::getSzVal, "test")
增加一个参数 aliasName
queryWrapper.lambda().eq(TestBody::getSzVal, "test", "aliasName")
使 从SFunction获取 字段名时带上 aliasName.字段名

**Comment by miemieYaho** [comment]
不支持
