### ISSUE TITLE
3.1.2版本中代码生成器里的 InjectionConfig 现在必须要用到了吗

### ISSUE THREAD

**Issue by all-aroundbadass** [baomidou/mybatis-plus#1350]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我项目中的代码生成功能里没有用到 InjectionConfig，根据文档，这个配置可注入自定义参数等操作以实现个性化操作，但是我并没有这个需求，也就没有用到，在 3.1.1 以及之前的版本是没有问题的，在3.1.2 中没有这个会报空指针异常，我看了一下，在 AbstractTemplateEngine 抽象类中，原先是
return objectMap;
3.1.2 中变更为
return config.getInjectionConfig().prepareObjectMap(objectMap);
这就导致 getInjectionConfig() 获取的是 null，所以现在 InjectionConfig 这个配置在代码生成功能里必须要用到吗？还是说这里应该判断一下 InjectionConfig 是否存在更合理呢？

### 重现步骤
使用代码生成器 new AutoGenerator() 的时候不添加 InjectionConfig

### 报错信息
空指针异常

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/pull/1351
