### ISSUE TITLE
写分页sql时 xml里面 limit start,size 的时候 limit 6,3本来应该是3条 结果查了9条

### ISSUE THREAD

**Issue by Mrchenli** [baomidou/mybatis-plus#1356]
### 当前使用版本(必须填写清楚，否则不予处理)
    compile group: 'com.baomidou', name: 'mybatis-plus-boot-starter', version: '3.0.7.1'

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
写分页sql不对

### 重现步骤
1.mapper
   List<TaskChannel> pageList(@Param("start") Integer start, @Param("size") Integer size);
2.xml
<select id="pageList" resultType="com.mob.microorganism.api.entity.TaskChannel">
        select * from task_channel limit #{start},#{size}
    </select>
3.log
2019-07-09 17:51:53.455 DEBUG pageList ==>  Preparing: select * from task_channel limit ?,? 
2019-07-09 17:51:53.455 DEBUG pageList ==> Parameters: 6(Integer), 3(Integer)
2019-07-09 17:51:53.488 DEBUG pageList <==      Total: 9
### 报错信息
无报错 结果错误

**Comment by miemieYaho** [comment]
执行的sql是什么那就是什么，自行排查

**Comment by Mrchenli** [comment]
sql拿到数据执行的结果 和程序跑出来的不一样。。。。
