### ISSUE TITLE
updateById 更新全部字段

### ISSUE THREAD

**Issue by chencongjin** [baomidou/mybatis-plus#1359]
版本为 3.0.7.1
使用mybatisplus  中baseMapper.updateById 更新数据表中某个字段内容，结果该条记录中其他数据有值的项全部更新为null了，这是版本问题吗？以前用3.0版本的时候没有出席那这个问题。

**Comment by miemieYaho** [comment]
无法复现,自行排查

**Comment by yuxiaobin** [comment]
请检查字段配置strategy：是否配了全局IGNORED？或者局部配置了IGNORED
