### ISSUE TITLE
springboot mybatis plus 使用缓存

### ISSUE THREAD

**Issue by handsomeshengchen** [baomidou/mybatis-plus#136]
在springboot mybatis plus 中怎么使用二级缓存

**Comment by qmdx** [comment]
缓存建议放到 service 层  boot  很容易的，官方例子 https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-cache

**Comment by jinfang134** [comment]
我按照这个配的缓存，不起作用，同一个包下的普通的服务，缓存是生效的。

**Comment by jinfang134** [comment]
debug 了一下，发现服务没有被代理增强，目前没有找到原因，而同一个包下的普通类是有被cglib增加了。所以缓存能够生效。
