### ISSUE TITLE
3.12版本中代码生成器  生成的代码找不到以下两个类

### ISSUE THREAD

**Issue by yongchao9** [baomidou/mybatis-plus#1361]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用官方代码生成示例

### 报错信息
在生成的代码中 找不到以下两个类,import 报错
    com.baomidou.ant.common.BaseController
    com.baomidou.ant.common.BaseEntity

**Comment by qmdx** [comment]
你是照抄文档例子吧？ 这个是演示自定义 父类 的，你可以写上自己的父类，不设置存在父类
