### ISSUE TITLE
逻辑删除不能做自动填充

### ISSUE THREAD

**Issue by kings1990** [baomidou/mybatis-plus#1365]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

MybatisDefaultParameterHandler在处理MetaObjectHandler的时候能不能加入删除操作？
我有一个逻辑删除字段和同步字段
delete_flag:1-未删除 0-已删除
sync_flag   0-已删除 1-默认 2-已更新 3-已同步
就是想在delete的时候全局将有sync_flag字段的表全更新成2

**Comment by miemieYaho** [comment]
看文档常见问题
