### ISSUE TITLE
自定义sql 使用QueryWrapper的问题

### ISSUE THREAD

**Issue by jiangtianyou** [baomidou/mybatis-plus#1366]
**1、当前版本**
3.1.2

**2、问题描述**

自定义sql时，使用了mp提供的QueryWrapper，下面是自定义的xml
![image](https://user-images.githubusercontent.com/5664308/61040069-7fa63680-a402-11e9-9708-85f02e690822.png)
正常运行 

但是我们xml里要求不能使用$符号，所以我使用了下面的方式来替换$的出现。
![image](https://user-images.githubusercontent.com/5664308/61040165-ad8b7b00-a402-11e9-8bde-1f62854c83f5.png)
但是不能正常运行。

请教一下有什么方案，能不用${ew.customSqlSegment}的方式，还能用mp的QueryWrapper吗？

**Comment by miemieYaho** [comment]
不能
