### ISSUE TITLE
如何设置javaTypeResolver节点中的useJSR310Types属性

### ISSUE THREAD

**Issue by Kingmanganese** [baomidou/mybatis-plus#1367]
### 当前使用版本(必须填写清楚，否则不予处理)
![image](https://user-images.githubusercontent.com/33016473/61040023-67ceb280-a402-11e9-8002-788f59ed50a3.png)

我在自动生成代码的时候数据库DataTime类型转换成了LocalDateTime，所以我想强制生成为Date类型。
官方文档:http://www.mybatis.org/generator/configreference/javaTypeResolver.html
在MyBatis-Plus自动生成的文档上没有找到这个选项。

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/GlobalConfig.java 
82行
