### ISSUE TITLE
SpringBoot集成mybatis-plus-boot-starter联合主键的问题

### ISSUE THREAD

**Issue by lsylovelmy** [baomidou/mybatis-plus#1368]
### 当前使用版本(必须填写清楚，否则不予处理)
SpringBoot的版本：2.1.5.RELEASE
mybatis-plus-boot-starter的版本：3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

实体类 联合主键
public class Test {

    @TableId
    private Integer idOne;

    @TableId
    private Integer idTwo;
}

在进行updateById的时候 where 条件只有 idOne = ?

是不是现在MP还不支持联合主键呢？还是我的做法有问题？

**Comment by jiangtianyou** [comment]
是不支持联合主键。因为updateById的参数就一个，都没法传两个id的参数嘛。

**Comment by miemieYaho** [comment]
对
