### ISSUE TITLE
逻辑删除做自动填充

### ISSUE THREAD

**Issue by kings1990** [baomidou/mybatis-plus#1369]
@miemieYaho 

### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

已使用官方常见问题说明中的《逻辑删除下 自动填充 功能没有效果》，使用xxxMapper.deleteByIdWithFill(T t)确实有自动填充功能(FieldFill.UPDATE)，但是如果我要根据这个操作是delete过来的还是update过来的去填充字段为不同的值怎么做，现在的情况是不管是
deleteByIdWithFill 还是update 需要填充的值都是同一个

### 代码

**问题:如何做delete操作syncFlag设置为1 update操作设置为2，因为逻辑删除自动填充走的也是updateFill**
```
public class MyMetaObjectHandler implements MetaObjectHandler {
	
	@Override
	public void insertFill(MetaObject metaObject) {
	
	}
	
	@Override
	public void updateFill(MetaObject metaObject) {
		LocalDateTime now = LocalDateTime.now();
		setUpdateFieldValByName("lastUpdatedTime", now, metaObject);
               //如何做delete操作syncFlag设置为1 update操作设置为2，因为逻辑删除自动填充走的也是updateFill
		setUpdateFieldValByName("syncFlag", 2, metaObject);
	}
}
```

**Comment by kings1990** [comment]
现在的处理方式只能这么做，在删除的时候把syncFlag带上，MetaObjectHandler updateFill()方法中去判断(getFieldValByName)如果syncFlag不是空就不做setUpdateFieldValByName操作，更新的时候不传syncFlag字段，updateFill()方法中获取到syncFlag是空就更新为2

**Comment by miemieYaho** [comment]
那就自己想办法
