### ISSUE TITLE
自定义mapper传入page分页时有问题

### ISSUE THREAD

**Issue by yhan219** [baomidou/mybatis-plus#137]
版本2.1.0，数据库 sqlServer
自定义一个mapper，Java代码：
`List<Product> selectProduct(Page page);`
xml:
`SELECT * FROM productinfo`
这种时候是没问题。可以正常分页。
但是如果xml中的sql是这样：
`select * from (select * from productinfo) a` 或者 `with a as (select * from productinfo) select * from a`
就会报错。
以`select * from (select * from productinfo) a`为例，我看了一下生成的sql，有两条，分别如下：
`SELECT COUNT(1)
 FROM (SELECT *
 FROM productinfo) a;`
`WITH query AS (SELECT TOP 100 PERCENT ROW_NUMBER() OVER (ORDER BY CURRENT_TIMESTAMP) as __row_number__, *
 FROM (SELECT *
 FROM productinfo) a) SELECT *
 FROM query
 WHERE __row_number__ BETWEEN 1 AND 20 ORDER BY __row_number__;`

**Comment by qmdx** [comment]
如果还未解决加入我们群探讨，如果是 bug 解决可用 PR 给我们
