### ISSUE TITLE
3.1.1升级候，自定义ServiceImpl方法错误currentModelClass

### ISSUE THREAD

**Issue by lemoncy** [baomidou/mybatis-plus#1371]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
因业务需求，自定义ServiceImpl，添加方法，3.1.0正常，升级为3.1.1后
currentModelClass方法，报错，信息如下
![image](https://user-images.githubusercontent.com/3096214/61127616-5a88f500-a4e2-11e9-812a-b76a4dc393f5.png)

调用方法如下
![image](https://user-images.githubusercontent.com/3096214/61127567-32999180-a4e2-11e9-9363-666a888c8020.png)

是否传入 this.getClass() 类型错误

### 重现步骤
直接报错

### 报错信息
![image](https://user-images.githubusercontent.com/3096214/61127616-5a88f500-a4e2-11e9-812a-b76a4dc393f5.png)

@miemieYaho

**Comment by miemieYaho** [comment]
自己想办法

**Comment by lemoncy** [comment]
就是copy过来的了，问题已处理，辛苦了。
