### ISSUE TITLE
3.1.0升级3.1.2后，引起的查询排序异常

### ISSUE THREAD

**Issue by junit** [baomidou/mybatis-plus#1373]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
3.1.0升级3.1.2发现问题

### 重现步骤
1.自定义mapper.xml
    <select id="getTreePage" resultType="com.glh.comment.model.Comment">
        SELECT
        ${ew.sqlSelect}
        FROM
        (SELECT * from `comment`)  comment_sorted,(select @pv :=#{parentId,jdbcType=BIGINT}) initialisation
        <where>
            find_in_set(parentId, @pv) AND length(@pv := concat(@pv, ',', id))
        </where>
    </select>
2.执行getTreePage
````
Page page = new Page(1, 10);
page.setOrders(orderlist);
````
### 报错信息
failed to concat orderBy from IPage, exception=null

**Comment by miemieYaho** [comment]
自行排查

**Comment by junit** [comment]
问题找到了，3.1.2版本，PaginationInterceptor的concatOrderBy方法用了CCJSqlParserUtil.parse(originalSql)先校验SQL再拼接orderby，而CCJSqlParser不支持 := 赋值变量的语法所以报错了，3.1.0的版本中，concatOrderBy是直接在SQL后拼接。

**Comment by qmdx** [comment]
@junit  https://github.com/JSQLParser/JSqlParser 这里提一个 issue

**Comment by LW-Francis** [comment]
> 问题找到了，3.1.2版本，PaginationInterceptor的concatOrderBy方法用了CCJSqlParserUtil.parse(originalSql)先校验SQL再拼接orderby，而CCJSqlParser不支持 := 赋值变量的语法所以报错了，3.1.0的版本中，concatOrderBy是直接在SQL后拼接。

您好，这个问题最终是怎么解决的。直接升级版本吗？
