### ISSUE TITLE
queryWrapper.like()，value取值错误

### ISSUE THREAD

**Issue by leemoncn** [baomidou/mybatis-plus#1375]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

queryWrapper.like()，如果value是枚举（已配置好枚举相关配置且实现IEnum），不会调用value.getValue()而是调用的value.toString()

### 重现步骤

任何调用了queryWrapper.like(key,value) api的枚举，可以看到后代打印sql为value.toString的值

**Comment by miemieYaho** [comment]
只支持value.toString
