### ISSUE TITLE
基于父类的模型，在basemapper 转成sql后，sql 可能会带有多余字段

### ISSUE THREAD

**Issue by suanping** [baomidou/mybatis-plus#138]
父类收集了一些表的公共，但不完全确实每个表都完整的一一对应。　

如：　父类中　create_name 在某个表不存在，
	@TableField(value = "create_name", fill = FieldFill.INSERT)
	private String createName;

问题：
　基于生成器生成　mapper.xml 内，ResultMap　及　base_clumn_list  已经过滤了　create_name　字段（是正确的），但基于 子类model 反射　生成sql 时，没与同相应　ResultMap　字段比较，导致生成sql 语句内存在 create_name　字段，　能否改进比对一次，确保sql 是正确的。

**Comment by qmdx** [comment]
公共的才放到父类，程序无法知道某个表不存在该字段，因此无法满足你的需求，如果你有解决方案加入我们 Q 群 576493122 讨论
