### ISSUE TITLE
SAP HANA 数据库支持问题

### ISSUE THREAD

**Issue by brave2chen** [baomidou/mybatis-plus#1381]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

想请教下如何解决 SAP HANA 数据库支持问题，JdbcUtils 看到并没有直接支持的配置

**Comment by qmdx** [comment]
适配新的数据库可能需要了解几个点：
1、你需要了解下注入逻辑
2、了解下分页方言
3、生成器部分你需要了解下 query 类 sql 自定义部分
