### ISSUE TITLE
insertBatch 不能捕获主键唯一

### ISSUE THREAD

**Issue by zcjm60** [baomidou/mybatis-plus#1383]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
insertBatch的时候try catch不能捕获主键重复异常 DuplicateKeyException，但insert是可以的

**Comment by DoyuTu** [comment]
`DuplicateKeyException`是由于数据库的`UNIQUE KEY`策略造成的。 
如果是自行实现的策略需要注意每一个Entity都要设置一个不同的key。
最好是可以贴出代码以便准确定位问题

**Comment by qmdx** [comment]
问题描述不够详细，最好给出复现 demo

**Comment by zcjm60** [comment]
> 问题描述不够详细，最好给出复现演示

例如 实体如下,idcId为唯一主键，用户输入:
![image](https://user-images.githubusercontent.com/22487059/63400091-3a175900-c405-11e9-9287-89178a52cd3a.png)

模拟主键重复的情况：
![image](https://user-images.githubusercontent.com/22487059/63400453-74352a80-c406-11e9-8d1e-b38745bf3f0a.png)

按道理来说通过捕获DuplicateKeyException来处理主键重复的情况，但虽然抛出了异常，却不能通过捕获DuplicateKeyException来处理主键重复的情况

**Comment by qmdx** [comment]
异常为 org.apache.ibatis.exceptions.PersistenceException:  要么你 catch Exception

**Comment by zcjm60** [comment]
> 异常为org.apache.ibatis.exceptions.PersistenceException：要么你捕获异常
> 
> ```
>     @Test
>     @Order(28)
>     void testSaveBatchException() {
>         try {
>             userService.saveBatch(Arrays.asList(
>                 new H2User(1L, "tom"),
>                 new H2User(1L, "andy")
>             ));
>         } catch (Exception e) {
>             Assertions.assertTrue(e instanceof PersistenceException);
>         }
>     }
> ```

![image](https://user-images.githubusercontent.com/22487059/63573606-560f2c00-c5b8-11e9-9a7f-d4c0d1f49e78.png)

使用了和你相同的方式还是不能进入异常处理里，我使用的版本是2.3
