### ISSUE TITLE
提示在xml中找不到BaseMapper中的方法

### ISSUE THREAD

**Issue by xuguangwu** [baomidou/mybatis-plus#1384]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

Mapper类继承了BaseMapper，使用了BaseMapper中的selectList方法，同时该Mapper也有对应的xml文件，调用就会报selectList不存在

**Comment by miemieYaho** [comment]
自行排查

**Comment by yuxiaobin** [comment]
错误信息太少

建议自己去官网FAQ查问题

https://mybatis.plus/guide/faq.html
