### ISSUE TITLE
baseMapper.selectPage的分页大小无法超过500

### ISSUE THREAD

**Issue by youyaerpi** [baomidou/mybatis-plus#1385]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

升级版本之后，分页查询的pageSize无法超过500，超过之后每次分页只查500条，小于500是正常的。

### 重现步骤
降低版本之后没问题

### 报错信息

无报错

**Comment by youyaerpi** [comment]
好吧，翻看源码找到了。
![image](https://user-images.githubusercontent.com/40053200/61350966-e95b9000-a89b-11e9-8180-bce52cb29d4b.png)-------3.1.1版本

**Comment by youyaerpi** [comment]
![image](https://user-images.githubusercontent.com/40053200/61350996-02fcd780-a89c-11e9-94e2-724bb6d783d0.png)
------3.0.5

**Comment by youyaerpi** [comment]
是否出于安全考虑？

**Comment by youyaerpi** [comment]
能否在版本更新里面加上

**Comment by qmdx** [comment]
配置你设置下你的 limit 默认为了保证安全防止全表扫描
