### ISSUE TITLE
关于逻辑删除的 delete_time 问题，不是issue，只是帮助贴，望海涵。

### ISSUE THREAD

**Issue by PedroGao** [baomidou/mybatis-plus#1386]
笔者也是从昨天才入手的mp，今天在解决逻辑删除的问题上绕了好久，由于官方文档上的逻辑删除确实只给出了Integer的实现，而很多orm的框架的软删除支持delete_time等在时间上的赋值，为了跟以前的项目保持统一，却又不想重新实现一遍logic的所有方法，因此提供了下面的方法来实现delete_time的赋值问题，希望帮助更多的开发者，如果已经有人也是这样实现的，纯属雷同。

经过我半天的探索和研究，增加delete_time的方式如下：

1. 添加逻辑删除注解

```java
@Getter
@Setter
@ToString
public class User {

    private Long id;

    private String name;

    private Integer age;

    private String email;

    @TableLogic
    private Date deleteTime;
}
```

2. 修改appplication.properties配置

```properties
# mybatis.mapper-locations=classpath:mapper/*.xml
# mybatis.type-aliases-package=com.pedro.shirodemo.mapper
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 逻辑删除
mybatis-plus.global-config.db-config.logic-delete-value=NOW()
mybatis-plus.global-config.db-config.logic-not-delete-value=NULL
```

此处比较取巧，因为delete-value和not-delete-value均为字符串值，sql在拼接的时候也会拼字符串，因此完全可以借助sql自身的 NOW() 函数来实现delete_time的赋值。

希望可以开此issue，帮助更多的开发者，拜谢了，确实又很多人在这个问题上绕了很久。

**Comment by whh945atsyzx** [comment]
好神奇的方案...这样子逻辑删除不会失效？

**Comment by PedroGao** [comment]
就目前使用的情况是没有失效的

**Comment by qmdx** [comment]
Very well modified to closed state

**Comment by 5468sun** [comment]
在我这不管用
MYSQL 
删除时执行如下sql：
UPDATE wms_mgr_permission SET delete_time=NOW() WHERE guid=1145120443882397698 AND delete_time=NULL

应为 delete_time is NULL

**Comment by PedroGao** [comment]
抱歉，确实是有问题的，我这边也发现了，后续再找找其它方法吧

**Comment by PedroGao** [comment]
还是通过黑魔法解决了一下，毕竟为了兼容，推荐新项目就不要这么做了，通过mybatis的拦截器，修改原始的sql语句，如下：

```java
package com.lin.cms.demo.common.mybatis;

import com.baomidou.mybatisplus.core.toolkit.PluginUtils;
import lombok.extern.slf4j.Slf4j;
import org.apache.ibatis.executor.statement.StatementHandler;
import org.apache.ibatis.mapping.BoundSql;
import org.apache.ibatis.plugin.*;
import org.apache.ibatis.reflection.MetaObject;
import org.apache.ibatis.reflection.SystemMetaObject;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.util.Properties;

@Intercepts({@Signature(type = StatementHandler.class, method = "prepare", args = {Connection.class, Integer.class})})
@Slf4j
public class LogicInterceptor implements Interceptor {
    @Override
    public Object intercept(Invocation invocation) throws Throwable {
        StatementHandler statementHandler = PluginUtils.realTarget(invocation.getTarget());
        MetaObject metaObject = SystemMetaObject.forObject(statementHandler);
        BoundSql boundSql = (BoundSql) metaObject.getValue("delegate.boundSql");
        //获取到原始sql语句
        String sql = boundSql.getSql();
        if (sql.contains("delete_time=NULL")){
            String mSql = sql.replace("delete_time=NULL","delete_time is NULL");
            //通过反射修改sql语句
            Field field = boundSql.getClass().getDeclaredField("sql");
            field.setAccessible(true);
            field.set(boundSql, mSql);
        }
        return invocation.proceed();
    }

    @Override
    public Object plugin(Object target) {
        if (target instanceof StatementHandler) {
            return Plugin.wrap(target, this);
        }
        return target;
    }

    @Override
    public void setProperties(Properties properties) {
    }
}

```

将 `delete_time=NULL`通过拦截器修改为了`delete_time is NULL`，这样的做法比较hack，不知道会不会有后面的bug，笔者也是因为项目的原因才这样做，慎用。

**Comment by yuxiaobin** [comment]
别用黑科技了，这个问题已经修复
参考[提交](https://gitee.com/baomidou/mybatis-plus/commit/246b1ec8611f948224f80e5c0a47957f6174e87a)

稍后发一个快照可以先用着

**Comment by PedroGao** [comment]
喜大普奔，发版了就不用了黑魔法了

**Comment by yuxiaobin** [comment]
快照已发，请配置快照仓库并使用版本3.1.3.1-SNAPSHOT

`<repository>`
            `<id>snapshot</id>`
            `<name>mp-snapshot</name>`
            `<url>https://oss.sonatype.org/content/repositories/snapshots/</url>`
            `<snapshots>`
                `<enabled>true</enabled>`
            `</snapshots>`
        `</repository>`

`<groupId>com.baomidou</groupId>`
`<artifactId>mybatis-plus</artifactId>`
`<version>3.1.3.1-SNAPSHOT</version>`

**Comment by 5468sun** [comment]
坐等发版

**Comment by zonasgao** [comment]
升版了 3.2.0 之后已经可以这样使用了，首先感谢各位大佬们方案和支持。
同时提出自己遇到的一个小坑给各位参考：
       环境：springboot 2.1.0.RELEASE，使用yaml进行配置解析。
       问题：在通过yaml使用配置 mybatis-plus.global-config.db-config.logic-not-delete-value=NULL 的时候SQL附带的添加为查询条件为 deleted=，后面就没有了，所以一直报错。
       原因：因为使用yaml进行配置文件解析的时候会自动转换成空字符串
       解决：将配置更改为 
              mybatis-plus:
                  global-config:
                     db-config:
                         logic-not-delete-value: 'NULL'

**Comment by YiuTerran** [comment]
这里用UNIX_TIMESTAMP()，然后default 0不是更简单么，无须null

**Comment by maybeyj** [comment]
> 这里用UNIX_TIMESTAMP()，然后default 0不是更简单么，无须null

用UNIX_TIMESTAMP()，如果【批量删除】岂不是会有问题？

**Comment by liuanxin** [comment]
默认值设置成 0, 删除的时候设置成当前时间戳
```yml
mybatis-plus.global-config.db-config:
  logic-delete-field: is_deleted
  logic-delete-value: UNIX_TIMESTAMP()
  logic-not-delete-value: 0
```

如果不想用上面的全局配置(比如有些表可能不需要用唯一索引, 字段用 0 1 就够了), 就在具体的注解上处理
```java
/** 非 0 表示已删除 --> is_deleted */
@TableLogic(value = "0", delval = "UNIX_TIMESTAMP()")
private Long isDeleted;

或者

/** 1 表示已删除 --> is_deleted */
@TableLogic
private Boolean isDeleted;
```

上面的两种分别对应有唯一索引和没有的情况
```sql
`is_deleted` BIGINT NOT NULL DEFAULT '0' COMMENT '非 0 表示已删除',
UNIQUE INDEX `uk_xxx` (`xxx`, `is_deleted`),

或者

`is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '1 表示已删除',
```

**Comment by mccray-s** [comment]
> 默认值设置成 0, 删除的时候设置成当前时间戳
> 
> ```yaml
> mybatis-plus.global-config.db-config:
>   logic-delete-field: isDeleted
>   logic-delete-value: UNIX_TIMESTAMP()
>   logic-not-delete-value: 0
> ```
> 
> 如果不想用上面的全局配置(比如有些表可能不需要用唯一索引, 字段用 0 1 就够了), 就在具体的注解上处理
> 
> ```java
> /** 删除标识: 0.未删除, 非 0.删除 --> is_deleted */
> @TableLogic(value = "0", delval = "UNIX_TIMESTAMP()")
> private Integer isDeleted;
> 
> 或者
> 
> /** 删除标识: 0.未删除, 1.已删除 --> is_deleted */
> @TableLogic
> private Boolean isDeleted;
> ```
> 
> 上面的两种分别对应有唯一索引和没有的情况
> 
> ```sql
> `is_deleted` INT NOT NULL DEFAULT '0' COMMENT '删除标识: 0.未删除, 非 0.删除',
> UNIQUE INDEX `uk_xxx` (`xxx`, `is_deleted`),
> 
> 或者
> 
> `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0.未删除, 1.已删除',
> ```

nice 一直没有尝试，然后就在找方法，看到老哥的办法直接尝试了一下OK了

**Comment by KANLON** [comment]
一般 delete_time 设置为 0000-00-00 00:00:00 这个合适些？ 这样在表有唯一索引的时候，不会因为delete_time  为null，而导致唯一索引不生效

**Comment by langlichong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/11713419/8186ada4-3908-4d93-9c5f-e6cf9d13863a)
写了个TableInfo的子类覆盖了formatLogicDeleteSql，程序启动后做业务查询压根不会执行到子类覆盖的代码，要做额外的配置吗（spring boot web环境）

**Comment by Wuaner** [comment]
> ![image](https://private-user-images.githubusercontent.com/11713419/293885429-8186ada4-3908-4d93-9c5f-e6cf9d13863a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDAxNTEsIm5iZiI6MTcwNjc5OTg1MSwicGF0aCI6Ii8xMTcxMzQxOS8yOTM4ODU0MjktODE4NmFkYTQtMzkwOC00ZDkzLTljNWYtZTZjZjlkMTM4NjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE1MDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYjNhYjI3ZTQ2NmNhMzcyNTc0ZjVlY2Y4M2I5MzU5MWU2NzAyZDJkYmY0MWY0NWVjODU0Y2M1ZmRkYjVjMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PiA4Vc16AhIJOuMv8Thj8ski2Iy2q_EhJNC1Cxr4E1I) 写了个TableInfo的子类覆盖了formatLogicDeleteSql，程序启动后做业务查询压根不会执行到子类覆盖的代码，要做额外的配置吗（spring boot web环境）

用不了。注释估计是瞎写的

**Comment by leechor** [comment]
mysql, 列采用tinyint(1),默认为1，
```shell
      logic-delete-field: is_actual
      logic-delete-value: "NULL"
      logic-not-delete-value: 1
```
因为mysql把NULL索引当做唯一值，跟他组成联合索引后这样也可以保证被删除的记录不冲突。同时一般都有update_time，可以表示删除时间。
