### ISSUE TITLE
逻辑删除where拼接排序问题

### ISSUE THREAD

**Issue by chaileilei** [baomidou/mybatis-plus#1387]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
逻辑删除sql拼接的时候，逻辑删除字段放到了where最前面了，怎么做才能放到最后面（条件查询），下面是代码

### 重现步骤
baseMapper.selectList(new QueryWrapper<TvBlockItemEntity>().eq("item_pid", itemId).eq("app_type",param.getAppType()).eq("ctype",param.getCtype()).last("limit " + num).orderByAsc("sort")

打印的sql 只有where部分
WHERE removed=0 AND item_pid = ? AND app_type = ? AND ctype = ? ORDER BY sort ASC limit 5

**Comment by miemieYaho** [comment]
不支持
