### ISSUE TITLE
动态表名 SQL 解析器 这个怎么使用？

### ISSUE THREAD

**Issue by LuSir001** [baomidou/mybatis-plus#1389]
### 当前使用版本(必须填写清楚，否则不予处理)

动态表名 SQL 解析器 这个怎么使用

**Comment by qmdx** [comment]
https://mybatis.plus/guide/dynamic-table-name-parser.html

**Comment by LuSir001** [comment]
看不懂啊？文档是看了，但不知道怎么用，有实际列子吗？
