### ISSUE TITLE
操作数据库为Oracle，Oracle表名大写，字段小写

### ISSUE THREAD

**Issue by zchengfei** [baomidou/mybatis-plus#1390]
### 前提条件      操作Oracle数据库   库名大写，字段小写。。。

代码生成器中 -->策略配置--> new StrategyConfig().setCapitalMode(true)-->如果**有该行配置**，
使用基础CURD时 会报sql语句异常。具体原因是“ABC”列不存在。因为数据库中字段是小写，所以会出现报错。

代码生成器中 -->策略配置--> new StrategyConfig().setCapitalMode(true)-->如果**没有该行配置**，使用基础CURD时 会报sql语句异常。具体原因是表或视图不存在。因为数据库中表名是大写的，而查询的时候用的是小写的表名。

**Comment by qmdx** [comment]
MP 启动参数配置 全局配置  globalConfig.dbConfig.capitalMode 设置大写模式，默认 false 这里指的是 表名 和 字段 ， 暂未支持区分 2 种命名。

你设置默认 false 然后 TableName("大写") 注解大写， 或者修改为统一的命名方案
