### ISSUE TITLE
多租户如何实现tenant_id in (1, 2)

### ISSUE THREAD

**Issue by cleverdb** [baomidou/mybatis-plus#1391]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

多租户
Expression e1 = new LongValue(1);
Expression e2 = new LongValue(2);
ValueListExpression list = new ValueListExpression();
list.setExpressionList(new ExpressionList(e1, e2));
return list;
sql ===  tenant_id = (1, 2)

如何实现tenant_id in (1, 2)

**Comment by miemieYaho** [comment]
不支持

**Comment by qmdx** [comment]
租户插件重写注入条件逻辑

**Comment by cleverdb** [comment]
> 租户插件重写注入条件逻辑
3q ， 那就按照自己的业务重写下TenantSqlParser

**Comment by chengqiGitHub** [comment]
> > 租户插件重写注入条件逻辑
> > 3q，那就按照自己的业务重写下TenantSqlParser

也碰到同样的问题，大概怎么搞？能分享下嘛
