### ISSUE TITLE
@TableFiled注解逻辑问题

### ISSUE THREAD

**Issue by fanlushuai** [baomidou/mybatis-plus#1393]
### 当前使用版本(必须填写清楚，否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.1.2</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

设计的表结构莫名其妙发现。实体生成，有的带了@TableField注解有的没有。

### 重现步骤

com.baomidou.mybatisplus.generator.config.po.TableField#setConvert(com.baomidou.mybatisplus.generator.config.StrategyConfig)

```
    protected TableField setConvert(StrategyConfig strategyConfig) {
        if (strategyConfig.isEntityTableFieldAnnotationEnable()) {
            this.convert = true;
            return this;
        }
        if (strategyConfig.isCapitalModeNaming(name)) {
            this.convert = false;
        } else {
            // 转换字段
            if (NamingStrategy.underline_to_camel == strategyConfig.getColumnNaming()) {
//todo 本issue觉得这里逻辑处理的欠妥当
                // 包含大写处理
                if (StringUtils.containsUpperCase(name)) {
                    this.convert = true;
                }
            } else if (!name.equals(propertyName)) {
                this.convert = true;
            }
        }
        return this;
    }
```

covert=true在模板里面会加上@TableFiled注解。
因为历史原因。我使用的数据库设计比较混乱。字段存在同一张表下划线和驼峰同时存在的情况。
所以我采用underline_to_camel的cover方式。使得java代码全部驼峰。
所以在字段转化的时候，只是通过是否包含大写字母来判断是否经过了转化。就会导致，事实上并没有转化的驼峰字段。带上@TableField属性。

**Comment by fanlushuai** [comment]
刚才又发现。
                if (StringUtils.containsUpperCase(name)) 这个位置。
个人觉得应该使用properyName而不是name。否则在数据库字段全下划线命名，策略选择下划线转驼峰的情况下，用于不会包含大写字母，也就convert永远不会是true。永远没有@TableFiled注解。

**Comment by qmdx** [comment]
mp 默认是提倡无注解，因此尽量不添加注解，最好的办法请规范你的命名
