### ISSUE TITLE
mybatis plus 是否支持联合主键

### ISSUE THREAD

**Issue by B1gB1gRAin** [baomidou/mybatis-plus#1397]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
问题提问，并非功能缺陷。
mybatis plus是否支持联合主键。或者是否有其他解决方案

**Comment by miemieYaho** [comment]
不支持
