### ISSUE TITLE
3.1.2版本的deleteByIdWithFill应该如何使用？

### ISSUE THREAD

**Issue by 5468sun** [baomidou/mybatis-plus#1398]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在常见问题中介绍了 LogicDeleteByIdWithFill 的实现，但是看得不是很明白。

```
public interface MyBaseMapper<T> extends BaseMapper<T> {

    /**
     * 自定义全局方法
     */
    int deleteByIdWithFill(T entity);
}
```

baseMapper 定义的这个方法，入参是个Entity，而不是一个 Id吗？ 那么做删除操作的时候，是需要 new 一个 Entity ，让后再将这个 entity 传入吗？

**Comment by miemieYaho** [comment]
对

**Comment by l7810** [comment]
这种情况，用于哪些场景中？

**Comment by l7810** [comment]
看源码了。功能比较屌，只是这命名有点不符合场景。
