### ISSUE TITLE
苗大侠，bean可否支持动态设置数据库表名称

### ISSUE THREAD

**Issue by lanxingshou** [baomidou/mybatis-plus#14]
如：Bean里面的表名称 @TableName(value="xxxx")这个value能否动态变换？ 数据库的表是动态创建的。谢谢

![image](https://cloud.githubusercontent.com/assets/12092274/21704236/e38183c2-d3f2-11e6-8018-4206cf46101e.png)

**Comment by qmdx** [comment]
非常感谢您的建议！由于这个会影响 mp 结构及安全性暂不考虑支持，希望 xml 自定义处理，这种特殊需求，谢谢支持！
