### ISSUE TITLE
fulltext 查询

### ISSUE THREAD

**Issue by yl1935** [baomidou/mybatis-plus#1400]
### 当前使用版本(必须填写清楚，否则不予处理)
3.12

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
做mysql fulltext全文检索时报错

### 重现步骤
只要sql中出现 match    against语法

### 报错信息
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "AGAINST" <S_IDENTIFIER>

如何绕过jsql parse的解析？

**Comment by qmdx** [comment]
看文档 sqlPaser 过滤它
