### ISSUE TITLE
代码生成器自定义配置问题

### ISSUE THREAD

**Issue by Chengpanfei** [baomidou/mybatis-plus#1401]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

当代码生成器设置自定义配置的时候会产生NPE异常!

### 重现步骤
配置的时候, 不设置自定义配置InjectionConfig

### 报错信息

NullPointerException

### 其它
也不算什么bug吧, 就是可以优化一下, 感觉好一点

**Comment by qmdx** [comment]
已经处理过，待发布 https://github.com/baomidou/mybatis-plus/commit/96bd563a5e8426a619d8f9299c7080e8cad2e80f

**Comment by Chengpanfei** [comment]
谢谢
