### ISSUE TITLE
自定义typeHandler异常问题

### ISSUE THREAD

**Issue by VeChar** [baomidou/mybatis-plus#1402]
### 当前使用版本(必须填写清楚，否则不予处理)
MyBatisPlus： 3.1.2
SpringBoot：2.1.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用自定义TypeHandler，在需要调整的实体类字段上添加：
`@TableField(typeHandler = TestHandler.class)`

如果不在application.yml中配置type-handlers-package属性，那么插入数据可以正常执行自定义typeHandler，其他实体类操作不会出错，而查询时并没有执行typeHandler，返回数据库中的原数据；如果在配置文件中配置了该属性，则项目中所有的插入操作(包括不是该实体类的操作)都会通过自定义的typeHandler进行处理，执行Handler中的setNonNullParameter方法自然就报错了，而查询又是正常执行typeHandler。想知道怎么配置才是只针对这个实体类中的这个字段执行typeHandler的插入更新和查询。还是说是个bug呢？

**Comment by miemieYaho** [comment]
把`@TableName` 的属性 `autoResultMap` 设置为true,去除你配置文件的type-handlers-package,如果你有xml里自定义的sql要返回这个entity,就必须自己写resultmap,这是mybatis的问题`@TableField(typeHandler = TestHandler.class)`只能指定insert和update的时候的typehandler
