### ISSUE TITLE
建议 

### ISSUE THREAD

**Issue by zcjm60** [baomidou/mybatis-plus#1404]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis2.x

例如：现在的查询操作如下:
iSysUserService.selectList(
            new EntityWrapper<SysUser>()
                .eq("name",111)
        );
要是改成这样的模式，字段使用枚举，然后使用泛型来限制：
iSysUserService.selectList(
            new EntityWrapper<SysUser>()
                .eq(SysUserEnum.NAME,111)
        );
这样的代码更优美

**Comment by qmdx** [comment]
如果条件允许请升级到 mp 3.x 可能是你要的写法
```

List<User> userList = userMapper.selectList(
        new QueryWrapper<User>()
                .lambda()
                .ge(User::getAge, 18)
);

```

**Comment by idrools** [comment]
> 如果条件允许请升级到 mp 3.x 可能是你要的写法
> 
> ```
> 
> List<User> userList = userMapper.selectList(
>         new QueryWrapper<User>()
>                 .lambda()
>                 .ge(User::getAge, 18)
> );
> ```
List<User> userList = userMapper.selectList(
        new QueryWrapper<User>()
                .lambda()
                .ge(p->p.getAge(), 18)
);
lambda这么写不可以？
