### ISSUE TITLE
分页size为-1, total返回为0不正确

### ISSUE THREAD

**Issue by 102400** [baomidou/mybatis-plus#1405]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？
传入size为-1突破500的限制来获取所有数据. 但是total返回的不正确, 总是为0, records是有的

### 重现步骤
selectPage(new Page<>()
                        .setCurrent(1)
                        .setSize(-1)

iPage.getTotal() = 0

**Comment by qmdx** [comment]
https://mybatis.plus/guide/page.html

仔细查看文档啊，size 小于 0 是不进行 count 查询当然是 0 ，你的需求是 
`new PaginationInterceptor().setSize(1000);  // 改为最大 1000 条`
