### ISSUE TITLE
postgresql找不到schema

### ISSUE THREAD

**Issue by MapleMart** [baomidou/mybatis-plus#1409]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.1.2</version>
		</dependency>

### 该问题是怎么引起的？
执行CRUD所有操作都不带上schema的值qrtz
"qrtz_exception" does not exist
下正是qrtz.qrtz_exception这样才是对的

### 重现步骤
qrtzExceptionMapper.insert(qe);

### 报错信息

"qrtz_exception" does not exist
正常是qrtz.qrtz_exception这样才是对的

如果在QrtzException类要加上@TableName("qrtz.qrtz_exception")才可以，但是代码生成器不可以自动这样生成

**Comment by miemieYaho** [comment]
全局配置 schema

**Comment by MapleMart** [comment]
spring boot 里怎配置 全局配置 schema 因为有多个schema

**Comment by MapleMart** [comment]
> 全局配置 schema

spring boot 里怎配置 全局配置 schema 因为有多个schema

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/config/GlobalConfig.java
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/TableName.java
