### ISSUE TITLE
希望增加联合主键的支持

### ISSUE THREAD

**Issue by bihell** [baomidou/mybatis-plus#1414]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

数据表为联合组件，虽然已经表实例上标名 TableId ，但实际操作的时候还是只用了一个主键

### 重现步骤

实例：

    /**
     * 主键：表ID
     */
    @TableId(type = IdType.INPUT)
    private BigInteger tblId;
    /**
     * 主键：表参数
     */
    @TableId(type = IdType.INPUT)
    private String paramKey;
    /**
     * 表参数的值
     */
    private String paramValue;

调用方法

insertOrUpdate();

### 报错信息

DEBUG==>  Preparing: SELECT tbl_id,param_key,param_value FROM TABLE_PARAMS WHERE tbl_id=? 
DEBUG==> Parameters: 484764(BigDecimal)

条件里面没有 paramKey

**Comment by miemieYaho** [comment]
不支持

**Comment by qmdx** [comment]
请添加物理主键，联合主键意义不大

**Comment by bihell** [comment]
> 请添加物理主键，联合主键意义不大

就是物理主键。现实情况下还是有很多数据库采用联合组件的。比如大数据体系里面的 Hive 数据库的 Meta 数据库。其中一个表COLUMNS_V2就采用这种方式。 如果能支持联合主键的话会更方便点。

```
-- auto-generated definition
create table COLUMNS_V2
(
    CD_ID       bigint                           not null,
    COMMENT     varchar(256) charset utf8        null,
    COLUMN_NAME varchar(128) collate latin1_bin  not null,
    TYPE_NAME   varchar(4000) collate latin1_bin not null,
    INTEGER_IDX int                              not null,
    primary key (CD_ID, COLUMN_NAME),
    constraint COLUMNS_V2_FK1
        foreign key (CD_ID) references CDS (cd_id)
)
    charset = latin1;

create index COLUMNS_V2_N49
    on COLUMNS_V2 (CD_ID);
```
