### ISSUE TITLE
希望可以支持位运算

### ISSUE THREAD

**Issue by liushangch** [baomidou/mybatis-plus#1416]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
最近业务需要多选，使用逗号分割并不灵活，改用int方式存储，2进制转换10进制，查询时需要使用到位运算 & | 。@TableField 注解 condition 可否配置为 %s&#{%s}
数据库MySql

**Comment by miemieYaho** [comment]
内部用 string.format 做的,要保持2个 %s 就行,第一个是column第二个是property

**Comment by Attect** [comment]
看上面的说法琢磨半天，才发现是这样写
```Kotlin
//Kotlin 继承SqlCondition然后在伴生类里写
const val AND = "%s &amp; #{%s} > 0"

//注解
@TableField(condition = SqlCondition.AND)
```

**Comment by liushangch** [comment]
3个好像就不支持了  %s = %s &amp; #{%s}
