### ISSUE TITLE
希望可以把OrderItem实现Serializable接口

### ISSUE THREAD

**Issue by javacodeofmy** [baomidou/mybatis-plus#1417]
### 当前使用版本(必须填写清楚，否则不予处理)
版本：3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

希望可以把OrderItem实现Serializable接口，目前由于该类没有实现Serializable接口，在dubbo调用的时候调用失败。

**Comment by yuxiaobin** [comment]
已添加

下个版本就支持

**Comment by miemieYaho** [comment]
你可以试试 3.2.0.1-SNAPSHOT,刚刚才发的

**Comment by qmdx** [comment]
使用 up 快照 or  关注正式版本发布
