### ISSUE TITLE
3.1.0升级3.1.2之后，代码生成工具文件时报错。

### ISSUE THREAD

**Issue by han130634** [baomidou/mybatis-plus#1418]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

3.1.0升级3.1.2之后，代码生成工具无法生成文件，并且报错。

### 重现步骤

工具类如下：

package com.biz.one;

import com.baomidou.mybatisplus.annotation.DbType;
import com.baomidou.mybatisplus.generator.AutoGenerator;
import com.baomidou.mybatisplus.generator.config.DataSourceConfig;
import com.baomidou.mybatisplus.generator.config.GlobalConfig;
import com.baomidou.mybatisplus.generator.config.PackageConfig;
import com.baomidou.mybatisplus.generator.config.StrategyConfig;
import com.baomidou.mybatisplus.generator.config.rules.NamingStrategy;

public class GeneratorCode {

    private static final boolean SERVICE_NAME_START_WITH_I = false; //user -> UserService, 设置成true: user -> IUserService
    private static final String PACKAGE_NAME = "com.biz.one"; //包名
    private static final String JDBC_URL = "jdbc:mysql://localhost:3306/ucenter?useSSL=true";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "123456";

    public static void main(String[] args) {
        generateByTables(
                "tb_user"
        );
    }

    /**
     * @param tableNames 表名数组
     */
    private static void generateByTables(String... tableNames) {
        GlobalConfig config = new GlobalConfig();
        DataSourceConfig dataSourceConfig = new DataSourceConfig();
        dataSourceConfig.setDbType(DbType.MYSQL)
                .setUrl(JDBC_URL)
                .setUsername(USERNAME)
                .setPassword(PASSWORD)
                .setDriverName("com.mysql.cj.jdbc.Driver");

        StrategyConfig strategyConfig = new StrategyConfig();
        strategyConfig
                .setCapitalMode(true)
                .setEntityLombokModel(true)
                .setRestControllerStyle(true)
                .setTablePrefix("tb_")
                .setNaming(NamingStrategy.underline_to_camel)
                .setInclude(tableNames);//修改替换成你需要的表名，多个表名传数组

        config.setActiveRecord(false)
                .setEnableCache(false)
                .setAuthor("zhangsan")
                .setOutputDir("generated1")
                .setSwagger2(true)
                .setFileOverride(true);

        if (!SERVICE_NAME_START_WITH_I) {
            config.setServiceName("%sService");
        }
        new AutoGenerator().setGlobalConfig(config)
                .setDataSource(dataSourceConfig)
                .setStrategy(strategyConfig)
                .setPackageInfo(
                        new PackageConfig()
                                .setParent("")
                                .setEntity(PACKAGE_NAME + ".domain")
                                .setMapper(PACKAGE_NAME + ".repository")
                                .setXml("mapper")
                                .setService(PACKAGE_NAME + ".service")
                                .setServiceImpl(PACKAGE_NAME + ".service.impl")
                                .setController(PACKAGE_NAME + ".controller")
                                .setService(PACKAGE_NAME + ".service")
                ).execute();
    }
}

### 报错信息

Connected to the target VM, address: '127.0.0.1:54717', transport: 'socket'
16:34:00.251 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
16:34:01.392 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [generated1/com/biz/one/domain]
16:34:01.392 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [generated1/com/biz/one/controller]
16:34:01.392 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [generated1/mapper]
16:34:01.392 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [generated1/com/biz/one/service]
16:34:01.392 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [generated1/com/biz/one/repository]
16:34:01.392 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [generated1/com/biz/one/service/impl]
16:34:01.397 [main] ERROR com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 无法创建文件，请检查配置信息！
java.lang.NullPointerException: null
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.getObjectMap(AbstractTemplateEngine.java:237)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:74)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:102)
	at com.biz.one.GeneratorCode.generateByTables(GeneratorCode.java:93)
	at com.biz.one.GeneratorCode.main(GeneratorCode.java:29)
16:34:01.409 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================
Disconnected from the target VM, address: '127.0.0.1:54717', transport: 'socket'

Process finished with exit code 0

经查看：

https://github.com/baomidou/mybatis-plus/blob/v3.1.2/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/engine/AbstractTemplateEngine.java

237行出现空指针,应该是配置信息没有注入进去；
return config.getInjectionConfig().prepareObjectMap(objectMap);
由于新接触不久，敢问是不是需要做一些特殊处理？

谢谢~

**Comment by yub1ng** [comment]
我也是这个问题，3.0.x低版本没有出现问题，InjectionConfig就没有配置，按理说不应该出现config.getInjectionConfig()这个语句

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/issues/1401
