### ISSUE TITLE
加入拦截器后@Autowired注入拦截器中报错

### ISSUE THREAD

**Issue by GitH-Hao** [baomidou/mybatis-plus#1419]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

spirng bean发现多个mapper

### 报错信息
把service注入拦截器会生成多个mapper bean

**Comment by qmdx** [comment]
无法理解你的描述，你可以给出 demo
