### ISSUE TITLE
模糊查询怎么区分大小写

### ISSUE THREAD

**Issue by Nero-Li** [baomidou/mybatis-plus#1421]
### 当前使用版本(必须填写清楚，否则不予处理)
版本为3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
传统的sql在模糊查询前加入BINARY就可以对字母区分大小写的查询,想问一下mp怎么实现,谢谢

**Comment by miemieYaho** [comment]
自己看文档 wrapper api找,不行就自己写xml
