### ISSUE TITLE
请问官网是用什么框架搭建的呢

### ISSUE THREAD

**Issue by sangyuan6122** [baomidou/mybatis-plus#1423]
### 当前使用版本(必须填写清楚，否则不予处理)
2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

请问官网是用什么框架搭建的呢

### 重现步骤

请问官网是用什么框架搭建的呢

**Comment by qmdx** [comment]
v'uepress
