### ISSUE TITLE
仅有自增主键一个字段的表（如id）；save时生成错误语法的sql，报错

### ISSUE THREAD

**Issue by tick5** [baomidou/mybatis-plus#1424]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

利用mysql主键自增特性做分布式id生成时

### 重现步骤

新建仅有自增主键一个字段的表（假设表名t_user，主键id，实体User）。
因为主键是自增的，所以可以这样插入一条纪录User user = new User()；service.save(user);
这时生成的sql是 "INSERT INTO t_user VALUES" 于是报语法错误。
正确的语句应该是”INSERT INTO t_user() VALUES ()“

### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1] with root cause

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	... ...

**Comment by miemieYaho** [comment]
不支持只有一个 id 还是自增的表
