### ISSUE TITLE
springboot使用代码自动生成，提示DbType不存在

### ISSUE THREAD

**Issue by qgtkobe** [baomidou/mybatis-plus#1425]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus 3.1.2

### 重现步骤
我引入的maven
		<dependency>
		    <groupId>com.baomidou</groupId>
		    <artifactId>mybatis-plus-boot-starter</artifactId>
		    <version>3.1.2</version>
		</dependency>
		
		<dependency>
		    <groupId>com.baomidou</groupId>
		    <artifactId>mybatis-plus</artifactId>
		    <version>3.1.2</version>
		</dependency>
		
		<dependency>
		    <groupId>com.baomidou</groupId>
		    <artifactId>mybatis-plus-generator</artifactId>
		    <version>3.1.2</version>
		</dependency>
		
		<dependency>
		    <groupId>org.apache.velocity</groupId>
		    <artifactId>velocity-engine-core</artifactId>
		    <version>2.1</version>
		</dependency>

### 报错信息

DbType 不存在

**Comment by qmdx** [comment]
包 mybatis-plus-annotation 中 类  com.baomidou.mybatisplus.annotation.DbType 你看看
