### ISSUE TITLE
分页报错

### ISSUE THREAD

**Issue by chuxiangfeng** [baomidou/mybatis-plus#1427]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter 3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

连接的dataSource为
jdbc:pivotal:greenplum://IP:端口;databaseName=databaseName

### 重现步骤
使用Page分页

### 报错信息

The Database's IDialect Not Supported!

**Comment by miemieYaho** [comment]
看不懂英文总会翻译吧?
