### ISSUE TITLE
日期插入和查询跟实际日期不一致

### ISSUE THREAD

**Issue by kingwrcy** [baomidou/mybatis-plus#1431]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>

`2019-07-30 18:04:41.236 [http-nio-8080-exec-2] DEBUG c.v.v.channel.core.mapper.BaasOnChainMapper.insert - ==> Parameters: 2534400df1341a3bfcfba4638886782f4540f9d086115ca0fec50962dc9bdcec(String), abcd123(String), 1(Integer), C384986752948899840(String), {"artifacts":[{"dataHash":"0x346124690e8e1cd8eff69084b537b701497c412f7442bc65da0f05f055185b7e","vid":"0XE8F41458FD4DAB5362C429AE47EE4423478664D61718D857544CD8B711BCBA33"}],"requestNo":"C384986752948899840","secretKey":"8233d2cdce38dcb645168fec4afee9387d1c8e0cf227fb357201ce642c6757f4","uid":"0x3e2ce97f060c3535b522829215e4d84f244a0d69ca3ddc6ef7b2df1e8a869010"}(String), 1(Integer), PRE_INIT(String), 0(Integer), 2019-07-30T18:04:41.232(LocalDateTime), 2019-07-30T18:04:41.232(LocalDateTime)`

查看数据库 createtime和updatetime变为 2019-07-30 05:04:41 .
打印出来的sql语句都是正确的,但是进入数据库的时间少了11小时为什么呢?
数据库:mysql 5.7

insert写法:
`request.setCreateTime(LocalDateTime.now());
        request.setUpdateTime(LocalDateTime.now());

baseMapper.insert(request)`

直接去mysql里执行也是对的,是什么问题呢?换过datetime和timestamp都一样,数据库也换过3个,也一样,连接串:
`spring.datasource.url=jdbc:mysql://localhost:3306/dev?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf-8`

**Comment by miemieYaho** [comment]
自己去百度

**Comment by kingwrcy** [comment]
Fixed,5.x的mysql用了8.x的驱动导致的，换回来就好了。

**Comment by BeastSen** [comment]
使用原生的insert方法插入时间不管啥时候，最终入库的时间都是插入时间日期的0点0分0秒；最后直接用xmll的方式没有问题；DTO里面设置的时间格式也没有问题
