### ISSUE TITLE
自动填充功能增加数据库关键字。 例如插入时间时 oracle使用sysdate 

### ISSUE THREAD

**Issue by neiyou** [baomidou/mybatis-plus#1432]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

目前只能用对应类型，如何使用sysdate 插入数据库时间？

**Comment by qmdx** [comment]
插入数据库默认 now() 即可

更新注解 @TableField(.. , update="now()")

**Comment by neiyou** [comment]
我测试了 h2、mysql、oracle 都无效（oracle 也使用了 sysdate） ，  只有update=“%s+1” 才有效
