### ISSUE TITLE
@TableField(.. , update="now()") 使用数据库时间 无效

### ISSUE THREAD

**Issue by neiyou** [baomidou/mybatis-plus#1433]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

   /**
     * 字段 update set 部分注入, 该注解优于 el 注解使用
     * <p>
     * 例1：@TableField(.. , update="%s+1") 其中 %s 会填充为字段
     * 输出 SQL 为：update 表 set 字段=字段+1 where ...
     * <p>
     * 例2：@TableField(.. , update="now()") 使用数据库时间
     * 输出 SQL 为：update 表 set 字段=now() where ...
     */
    String update() default "";

其中 @TableField(.. , update="now()") 使用数据库时间 无法使用。 测试了H2,MYSQL,ORACEL都无效

### 重现步骤
切换数据源

### 报错信息

只有%s+1 有效， now()无效

**Comment by neiyou** [comment]
更新方法中：
int update(@Param(Constants.ENTITY) T entity, @Param(Constants.WRAPPER) Wrapper<T> updateWrapper);  这个方法可以。
int updateById(@Param(Constants.ENTITY) T entity); 这个方法不可以。
问题暂时解决。 
提个小建议 如果增加一个insert关键字，能够在插入时保存数据库时间就好了，这样和update 平行。 否则我这边需要在数据库创建时间做默认值

**Comment by neiyou** [comment]
我试了下 
Service.update
Mapper.update

仅作用在mapper上的更新才生效

**Comment by miemieYaho** [comment]
插入数据库设置默认值
