### ISSUE TITLE
动态数据源不能切换问题

### ISSUE THREAD

**Issue by yanzhuan051** [baomidou/mybatis-plus#1438]
### 该问题是怎么引起的？
我配置了多数据源 分别是mysql 和 postgresql 是两个普通的多库，我分别设置primary 为mysql
和postgresql 都能正常查询 ，但是我不如说我设置为primary 为mysql 在 service 中 加@DS("postgresql") 会 发现 本次请求的session 还会是 mysql,最终会报表不存在的问题

**Comment by miemieYaho** [comment]
去那边提,这边是mp
