### ISSUE TITLE
使用map 传递分页Page 报多条错误

### ISSUE THREAD

**Issue by cuihj** [baomidou/mybatis-plus#1440]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用分页插件，使用mapper 参数 为一个Map

### 重现步骤
Map<String, Object> paraMap =new HashMap<>():
paraMap.put('page,new Page());
@Mapper
public interface KsxxMapper {

	IPage<Map<String, Object>> list(Map<String, Object> paraMap);

}

### 报错信息

问题出现在下面的处理逻辑
paraMap
![image](https://user-images.githubusercontent.com/6811333/62208699-2e1e1580-b3ca-11e9-97c7-fc8fda16c0b3.png)

**Comment by miemieYaho** [comment]
去看 samples
