### ISSUE TITLE
LambdaQueryWrapper().last()方法无法实现添加sql的功能

### ISSUE THREAD

**Issue by xiaochonzi** [baomidou/mybatis-plus#1441]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
无法通过调用 LambdaQueryWrapper().last()方法实现添加sql的功能

### 重现步骤
1. QueryWrapper<Entity> query = new QueryWrapper<>(entity);
2.//query.last("limit 1");
3. query.lambda().last("limit 1");

目的是想通过query在最终的sql上增加limit 1 
使用 第2段代码可以实现，但是在改成第3段后，无法实现

**Comment by miemieYaho** [comment]
wrappers.lambdaquery.last

**Comment by xiaochonzi** [comment]
@miemieYaho 谢谢你。
但是我还是有疑惑。
通常的写法可能是这样：
QueryWrapper<OrderInfo> query = new QueryWrapper<>(entity);
 query.lambda().orderByDesc(OrderInfo::getCtime)；
 getOne(query);
这种情况下orderBy是生效的，那么可以理解为lambada的表达式确实在query上发生了作用。
于是我又接着改成query.lambda().orderByDesc(OrderInfo::getCtime).last("limit 1")，目的是想在
sql最后实现limit 1。因为考虑到lambda的形式能够生效，所以直接后面跟着last也会生效，但是没有效果。请问这是什么原因？

**Comment by xiaochonzi** [comment]
@miemieYaho 我调试了一下lastSql在QueryWrapper中并没有与LambdaQueryWrapper进行同步，所以导致了最后我使用query查询的时候丢失了last里的sql
