### ISSUE TITLE
关于批量操作的问题，以及建议

### ISSUE THREAD

**Issue by Lzw2016** [baomidou/mybatis-plus#1442]
### 当前使用版本(必须填写清楚，否则不予处理)

`3.1.2`

### 该问题是怎么引起的？

目前`mybatis-plus`的批量操作会执行多个`sql`，并不是真正的批量执行1条`sql`，我在本机测试这两种的性能有`10--20`倍的差距，特别是当批量数据量超过`1000`以后执行时间的差距尤其严重(`1`条`sq`l的批量`0.1秒`左右，`1000`条`sql`的循环执行`1.2秒`左右)，目前我们ERP系统的数据操作业务场景也很多(相信其他系统也比较常见)，故建议作者实现真正的批量操作接口(最好在`BaseMapper`上实现)

目前我们的批量操作使用如下方法实现的

```xml
<update id="batchUpdate">
    <foreach collection="list" item="item" index="index" open="" close="" separator=";">
    update id_value
    <set>
        current_value = current_value+1
    </set>
    where id_code=#{item.idCode}
    </foreach>
</update>

<insert id="batchInsert">
    insert into id_value (id_code, current_value, create_at, update_at)
    VALUES
    <foreach collection="list" item="item" index="index" separator=",">
    (
        #{item.idCode},
        #{item.currentValue},
        #{item.createAt},
        #{item.updateAt}
    )
    </foreach>
</insert>
```
> 缺点就是不灵活(不好根据字段的“更新、插入”策略实现动态`insert `、`update `)，而且很机械化

##### 2.我查看官方文档有如下说明

> ### 通用 insertBatch 为什么放在 service 层处理
>
>    SQL 长度有限制海量数据量单条 SQL 无法执行，就算可执行也容易引起内存泄露 JDBC 连接超时等
>    不同数据库对于单条 SQL 批量语法不一样不利于通用
>    目前的解决方案：循环预处理批量提交，虽然性能比单 SQL 慢但是可以解决以上问题。

**我觉得上面两个问题都有办法解决：**
1. `SQL 长度` 问题： 可以在生成 批量sql语句时做批量控制，比如10000数据量，生成10个或者20个批量sql，这个数量(10个或者20个)可以根据当前数据库客户端链接的配置(SQL长度数据量大小配置)做到智能控制
2. `不同数据库`问题：可以根据数据库方言或类型，有选择的对主流数据库做支持，对不支持的数据库可以抛出异常或者使用当前`假`的批量实现

**Comment by miemieYaho** [comment]
看文档,有提供,不在basemapper里,自己选择性注入

**Comment by yuxiaobin** [comment]
自定义全局batchInsert, 参考[demo](https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-deluxe)

**Comment by Lzw2016** [comment]
这`Demo`我看过，那我只好自己实现了

**Comment by Lzw2016** [comment]
![图片](https://user-images.githubusercontent.com/19291563/62279116-08514900-b47c-11e9-9266-c3d5693963f3.png)
