### ISSUE TITLE
QueryWrapper在使用lambda表达式，没有将LambdaQueryWrapper中的lastSql，进行双向同步

### ISSUE THREAD

**Issue by xiaochonzi** [baomidou/mybatis-plus#1443]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

QueryWrapper 生成的对象在使用lambda()表达式实际上新建了LambdaQueryWrapper，
同时会将部分参数携带过去，但是QueryWrapper与LambdaQueryWrapper之间并没有做好真正的sql同步。如下代码中last中的`limit 1`并没有在query对象中体现出来。

### 重现步骤
QueryWrapper<OrderInfo> query = new QueryWrapper<>(entity);
query.lambda().orderByDesc(OrderInfo::getCtime).last("limit 1");
getOne(query);

**Comment by miemieYaho** [comment]
建议直接new lambdaquerywrapper,或者用 wrappers 工具类,下个最新版才会修复这个问题

**Comment by xiaochonzi** [comment]
@miemieYaho  谢谢你的答复。我已经这么做了
