### ISSUE TITLE
mybatis-plus 3.1.2 listMaps返回Map中key变为大写

### ISSUE THREAD

**Issue by MaseratiGTX** [baomidou/mybatis-plus#1444]
### 当前使用版本(必须填写清楚，否则不予处理)

mp3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库oracle
使用listMaps(Wrapper<T> queryWrapper)方法返回的Map中key变为大写，使用mp3.1.1的时候为小写，这是哪里需要配置吗？

**Comment by miemieYaho** [comment]
有人不需要,就取消了默认注入,看文档常见问题里,注入 map key下划线转驼峰
