### ISSUE TITLE
配置逻辑删除，查询有问题

### ISSUE THREAD

**Issue by fengxingaotian** [baomidou/mybatis-plus#1447]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
yml配置逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1

实体类配置
 @TableLogic
    private Integer delFlag;

执行查询时 baseMapper.selectById(id)；
每次查询的都是从已删除的数据中查询
Preparing: SELECT id, name, thumbnail, description, del_flag, create_time, update_time, content FROM template WHERE id = ? AND del_flag = 0

正常情况查询应该为del_flag = 1

### 重现步骤
调用查询接口
 baseMapper.selectById(id)；

### 报错信息
未报错，查询sql拼接的逻辑删除字段值错误

**Comment by miemieYaho** [comment]
没配对,自己检查你的yml

**Comment by fengxingaotian** [comment]
这种问题我也是无语了，配置是正确的，但是可能空格有其他看不到的字符换行吧，弄了好一会才查出是这些问题
