### ISSUE TITLE
代码生成器在自定义模板时未检测文件是否存在

### ISSUE THREAD

**Issue by SoyMeng** [baomidou/mybatis-plus#145]
如标题

**Comment by qmdx** [comment]
自定义比较灵活因此请自己确定好生成目录多谢反馈

**Comment by SoyMeng** [comment]
默认的模板有对isoverride进行判断，我需要进行的操作是在文件存在时不生成。
如果是自定义模板，似乎没找到什么方式可以进行判断？

**Comment by qmdx** [comment]
@SoyMeng  存在不生成是吧，  OK 下一个版本会加上

**Comment by SoyMeng** [comment]
@qmdx 是的，跟原生模板相同的判断就好

**Comment by qmdx** [comment]
ok关注 2.1.1 发布
