### ISSUE TITLE
从3.1.1升级到3.1.2

### ISSUE THREAD

**Issue by wocaishiryr** [baomidou/mybatis-plus#1456]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？
从3.1.1升级到3.1.2后,返回值为Map, Map的key由小写转为大写

### 重现步骤
从3.1.1升级到3.1.2后,正常使用会出现

### 报错信息
由于之前使用3.1.1,取值的key为小写,升级后报错 空指针

**Comment by miemieYaho** [comment]
取消了自动注入,看文档常见问题里返回map的key下划线转换
