### ISSUE TITLE
表中俩字段作为条件怎么直接比较

### ISSUE THREAD

**Issue by wangjianl** [baomidou/mybatis-plus#1458]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

比如 ，table  俩个字段，date1 和date2  用lambda怎么写  select * from table where date1>date2

**Comment by miemieYaho** [comment]
apply

**Comment by wangjianl** [comment]
用lambda的方式怎么写

**Comment by miemieYaho** [comment]
不支持

**Comment by wanglaowu977** [comment]
怎么写？
