### ISSUE TITLE
我想问下使用乐观锁插件的时候版本号不会自动查出来嘛

### ISSUE THREAD

**Issue by owoNA** [baomidou/mybatis-plus#1459]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.1.2</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在使用乐观锁插件的时候，版本号不会自动查出来

**Comment by miemieYaho** [comment]
不会,建议你先去百度什么是乐观锁
