### ISSUE TITLE
com.baomidou.mybatisplus.toolkit.GlobalConfigUtils setMetaData 数据库链接未关闭

### ISSUE THREAD

**Issue by hanyeyue33** [baomidou/mybatis-plus#146]
com.baomidou.mybatisplus.toolkit.GlobalConfigUtils setMetaData

/**
     * <p>
     * 设置元数据相关属性
     * </p>
     *
     * @param dataSource   数据源
     * @param globalConfig 全局配置
     */
    public static void setMetaData(DataSource dataSource, GlobalConfiguration globalConfig) {
        Connection connection = null;
        try  {
            connection = dataSource.getConnection();
            String jdbcUrl = connection.getMetaData().getURL();
            // 设置全局关键字
            globalConfig.setSqlKeywords(connection.getMetaData().getSQLKeywords());
            // 自动设置数据库类型
            if (globalConfig.getDbType() == null) {
                globalConfig.setDbTypeOfJdbcUrl(jdbcUrl);
            }
        } catch (Exception e) {
            throw new MybatisPlusException("Error: GlobalConfigUtils setMetaData Fail !  Cause:" + e);
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException ignore) {
                }
            }
        }
    }

**Comment by qmdx** [comment]
请使用 2.1.0 + 试试有问题反馈，先关闭
