### ISSUE TITLE
SqlMethod的枚举中UPDATE_ALL_COLUMN_BY_ID中sql 多了SET

### ISSUE THREAD

**Issue by yangyining** [baomidou/mybatis-plus#1460]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
SqlMethod.UPDATE_ALL_COLUMN_BY_ID 定义的sql里多了set，导致在扩展使用的时候报sql错误。之前貌似有人提这个问题，关系的理由是没有多。如果官方说没多的话麻烦告知要如何正确使用。

### 重现步骤
![image](https://user-images.githubusercontent.com/3253098/62510346-50d48200-b841-11e9-9873-733722b8b74b.png)

**Comment by miemieYaho** [comment]
自己去研究

**Comment by yangyining** [comment]
`
/**
 * <p>
 * 根据 ID 更新有值字段
 * </p>
 *
 * @author yangyining
 */
@Slf4j
public class UpdateAllColumnById extends AbstractMethod {

    @Override
    public MappedStatement injectMappedStatement(final Class<?> mapperClass, final Class<?> modelClass, final TableInfo tableInfo) {
        final SqlMethod sqlMethod = SqlMethod.UPDATE_ALL_COLUMN_BY_ID;

        // 反射修改fieldFill值为update
        final List<TableFieldInfo> fieldList = tableInfo.getFieldList();
        for (final TableFieldInfo tableFieldInfo : fieldList) {
            final Class<? extends TableFieldInfo> aClass = tableFieldInfo.getClass();
            try {
                final Field fieldFill = aClass.getDeclaredField("fieldFill");
                fieldFill.setAccessible(true);
                fieldFill.set(tableFieldInfo, FieldFill.UPDATE);
            } catch (final NoSuchFieldException e) {
                log.error("获取fieldFill失败", e);
            } catch (final IllegalAccessException e) {
                log.error("设置fieldFill失败", e);
            }
        }

        boolean logicDelete = tableInfo.isLogicDelete();
        final String additional = optlockVersion() + tableInfo.getLogicDeleteSql(true, false);
        // 从定义枚举中取sql模板，因为mp底层的sql里多了set ，这地方需要将set替换为空
        final String methodSql = sqlMethod.getSql().replace("SET", "");
        String sql = String.format(methodSql, tableInfo.getTableName(),
            sqlSet(logicDelete, false, tableInfo, false, ENTITY, ENTITY_DOT),
            tableInfo.getKeyColumn(), ENTITY_DOT + tableInfo.getKeyProperty(), additional);
        SqlSource sqlSource = languageDriver.createSqlSource(configuration, sql, modelClass);
        return addUpdateMappedStatement(mapperClass, modelClass, sqlMethod.getMethod(), sqlSource);
    }
}
`

**Comment by qmdx** [comment]
```java
 final String methodSql = sqlMethod.getSql().replace("SET", "");
```

这一行直接写成：
```java
final String methodSql = "UPDATE %s %s WHERE %s=#{%s} %s";
````

**Comment by yangyining** [comment]
我本来是想尽量少的对mp进行改动，mp里已经提供了我就执行用了。如果你们确认这个地方不改我再改。

**Comment by qmdx** [comment]
这个问题会考虑底层是否有必要修改，暂时先按照上头的方法使用

**Comment by yangyining** [comment]
好的，UpdateAllColumnById方法再2.x升3.x的时候被删除掉了。 我在升级的时候没办法写了这个自定义的。 AlwaysUpdateSomeColumnById是在3.1.1的时候才增加的。后面有时间我参考这个改下。
