### ISSUE TITLE
关于mybatis-plus批量插入saveBatch方法优化建议

### ISSUE THREAD

**Issue by boy9527** [baomidou/mybatis-plus#1466]
### 当前使用版本(必须填写清楚，否则不予处理)
我们用的gradle，没有写具体的版本号，默认下载mybatis-plus最新的版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
其实也不是问题，只是优化的建议。saveBatch目前的源码是这样的：
@Transactional(rollbackFor = Exception.class)
    @Override
    public boolean saveBatch(Collection<T> entityList, int batchSize) {
        String sqlStatement = sqlStatement(SqlMethod.INSERT_ONE);
        try (SqlSession batchSqlSession = sqlSessionBatch()) {
            int i = 0;
            for (T anEntityList : entityList) {
                batchSqlSession.insert(sqlStatement, anEntityList);
                if (i >= 1 && i % batchSize == 0) {
                    batchSqlSession.flushStatements();
                }
                i++;
            }
            batchSqlSession.flushStatements();
        }
        return true;
    }
这种方式效率不是很高，建议优化下，
期待改写成这种方式：insert into table values(?),(?),(?)

**Comment by qmdx** [comment]
LOOK  https://mybatis.plus/guide/faq.html#%E9%80%9A%E7%94%A8-insertbatch-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%BE%E5%9C%A8-service-%E5%B1%82%E5%A4%84%E7%90%86    

如果你有这种需求自定义注入一个实现即可！参考 https://mybatis.plus/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6 的实现
