### ISSUE TITLE
条件构造器是否考虑支持驼峰和下划线映射字段

### ISSUE THREAD

**Issue by a1369521908** [baomidou/mybatis-plus#1469]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本 3.1.2
implementation('com.baomidou:mybatis-plus-boot-starter:3.1.2')

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
无

### 重现步骤
1.比如实体类是这样

public class User {
       private  Long userId;
}

2.使用QueryWrapper时
QueryWrapper queryWrapper = new QueryWrapper();
        queryWrapper.eq("user_id", 1);

3.支持字段映射
QueryWrapper queryWrapper = new QueryWrapper();
        queryWrapper.eq("userId", 1);

4.自己写了下扩展,进行转换,依赖 fastJSON 1.2.58

public class ExQueryWrapper<E> extends QueryWrapper {

    @Override
    public Object eq(Object column, Object val) {
        return super.eq(column, val);
    }

    public Object eq(Object column, Object val, Boolean isUnderToCamel) {
        if (isUnderToCamel) {
            //
            SerializeConfig config = new SerializeConfig();
            config.propertyNamingStrategy = PropertyNamingStrategy.SnakeCase;
            column = config.propertyNamingStrategy.translate((String) column);
            return eq(column, val);
        }
        return eq(column, val);
    }
}

### 报错信息
无

**Comment by miemieYaho** [comment]
不支持
