### ISSUE TITLE
代码生成器无法识别非自增唯一主键

### ISSUE THREAD

**Issue by whahuzhihao** [baomidou/mybatis-plus#1471]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
用代码生成器按照默认模板生成entity，表中主键是`user_id`，唯一，但是不自增的时候，无法自动添加注解`@TableId`

### 重现步骤
`user_id` bigint(20) unsigned NOT NULL DEFAULT '0'
PRIMARY KEY (`user_id`) USING BTREE,
 直接用默认模板生成即可复现。

### 报错信息
找不到主键，所有selectById返回null

**Comment by qmdx** [comment]
主键是从数据库查询条件获取更多查看源码 https://github.com/baomidou/mybatis-plus/tree/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/querys  唯一不等于主键 ok !

**Comment by whahuzhihao** [comment]
> 主键是从数据库查询条件获取更多查看源码 https://github.com/baomidou/mybatis-plus/tree/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/querys 唯一不等于主键 ok !

我当然知道唯一不等于主键。
这么说吧，非自增的主键识别不了。

**Comment by qmdx** [comment]
mysql 测试正常，有更多问题欢迎 PR
