### ISSUE TITLE
代码生成器不指定InjectionConfig会报java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by zouanchao** [baomidou/mybatis-plus#1472]
### 当前使用版本(必须填写清楚，否则不予处理)

当前使用代码生成器版本如下：
  <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.1.2</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>3.1.2</version>
            </dependency>

### 重现步骤
 AutoGenerator autoGenerator = new AutoGenerator();
            InjectionConfig cfg = new InjectionConfig() {
                @Override
                public void initMap() {
                    Map<String, Object> map = new HashMap<String, Object>();
                    map.put("abc", this.getConfig().getGlobalConfig().getAuthor() + "-mp");
                    this.setMap(map);
                }
            };
            autoGenerator.setGlobalConfig(initGlobConfig(outputDir))
                    .setDataSource(initDataSource(driverName, url, userName, password))
                    .setStrategy(initStrategyConfig(tablePre, tableName))
                    .setPackageInfo(initPackage(parentPackageName, moduleName))
                    .setTemplate(new TemplateConfig())
//                    .setCfg(cfg) // 大多数情况下，我默认是不需要给这个的，之前3.1.1及以前的版本不给也可以正常使用，但是3.1.2不给这个会报错，跟源码，发现是下图位置报错，请考虑是否调整
                    .execute();
![image](https://user-images.githubusercontent.com/30254670/62667504-805aca00-b9ba-11e9-98c7-fca57ea3706b.png)

### 报错信息

![image](https://user-images.githubusercontent.com/30254670/62667416-23f7aa80-b9ba-11e9-99c6-efad7d6e6676.png)

**Comment by qmdx** [comment]
已解决 https://github.com/baomidou/mybatis-plus/issues/1401
