### ISSUE TITLE
Springboot mybatis plus IdType.UUID无效

### ISSUE THREAD

**Issue by wjc1243** [baomidou/mybatis-plus#1474]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库：postgresql
实体类：
@TableId(value = "id", type = IdType.UUID)
    private String id;
yml配置文件：
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.xmw.logistics.entities
//此处无论是否配置都无效
  global-config:
    db-config:
      id-type: uuid
报错信息：
### Cause: org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint
  详细：Failing row contains (null, 张三啊, 18, 男).
; ERROR: null value in column "id" violates not-null constraint
  详细：Failing row contains (null, 张三啊, 18, 男).; nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint
  详细：Failing row contains (null, 张三啊, 18, 男).

**Comment by miemieYaho** [comment]
自行排查

**Comment by wjc1243** [comment]
找到原因了，是因为我的dao没有继承BaseMapper，而且继承之后也必须要在泛型注明是你的实体类，不然也是不行的。
我太菜了，文档上没找到相关代码，也不怎么会看源码，没在源码里找到原因，作者大大有空的话希望能帮我解惑万分感谢！
