### ISSUE TITLE
saveBatch执行时间过长

### ISSUE THREAD

**Issue by xiaofanTo** [baomidou/mybatis-plus#1476]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在公司项目中拼接了一个Program表的ArrayList,然后通过saveBatch去提交，在数据量只有170条的时候执行时间达到了3.3s，直接数据库通过事务提交只需要 0.024000s

### 重现步骤

插入几百条数据，通过saveBatch去保存

### 报错信息

无

**Comment by miemieYaho** [comment]
去看文档,有说明
