### ISSUE TITLE
分页查询结果不一致的问题

### ISSUE THREAD

**Issue by chenyixin8854** [baomidou/mybatis-plus#1479]
基本条件
尝试使用3.1.0和3.1.2均出现此问题
mysql数据库5.7
使用租户模式
问题描述：
分页查询后page的records数据量是pagesize的两倍，多次改变size查询均查出结果为size的两倍
查询sql：
![image](https://user-images.githubusercontent.com/26102575/62773108-e424e600-bad3-11e9-9009-3df97a297ab4.png)
查询打印日志
 ==>  Preparing: SELECT COUNT(1) FROM t_comment WHERE t_comment.merchant_id = 1 AND merchant_user_id = ? 
 ==> Parameters: 4(Long)
 ==>  Preparing: SELECT id, merchant_id, shop_id, order_id, goods_id, merchant_user_id, customer_name, avatar, grade, remark, picture_urls, create_time, anonymous_type FROM t_comment WHERE t_comment.merchant_id = 1 AND merchant_user_id = ? LIMIT ?,? 
 ==> Parameters: 4(Long), 4(Long), 4(Long)
 <==      Total: 8
 limit 第二个参数为4结果返回8，不符合预期
返回结果打印：
![image](https://user-images.githubusercontent.com/26102575/62773169-159db180-bad4-11e9-9da7-546516b8bf82.png)
如果pagesize=5   --> total=10
pagesize=6  -->  total=12
sql本地试过了返回四条记录正确
![image](https://user-images.githubusercontent.com/26102575/62773285-5b5a7a00-bad4-11e9-8acc-7097c3deba82.png)
排查后怀疑是在分页查询内部的问题，请提供解决思路，谢谢

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by chenyixin8854** [comment]
@miemieYaho 我又测了几遍，之前的问题描述有点片面，返回数据不是两倍，返回数据是当前页及之前页的合计，当前页换成1的话就返回数量正常，当前也是3的话就返回前三页的数据，项目不好拆，我自己先找找吧，谢谢

**Comment by chenyixin8854** [comment]
确认了，问题是shardingjdbc引起的，和mybatis-plus没有关系

**Comment by chenyixin8854** [comment]
去找shardingjdbc的分页后的问题

**Comment by lbin2012** [comment]
> @miemieYaho 我又测了几遍，之前的问题描述有点片面，返回数据不是两倍，返回数据是当前页及之前页的合计，当前页换成1的话就返回数量正常，当前也是3的话就返回前三页的数据，项目不好拆，我自己先找找吧，谢谢

这个最后是怎么解决的，项目中也遇到了

**Comment by RickZhangYixin** [comment]
还能评论不？sharding3.1有这个问题，4.0.1就修复了
