### ISSUE TITLE
问一下 mybatisplus-spring-boot-starter 最新的版本是多少啊 

### ISSUE THREAD

**Issue by zhouyongtao** [baomidou/mybatis-plus#148]
问一下 mybatisplus-spring-boot-starter  最新的版本是多少啊 ，感觉跟 mybatisplus 不同步嘛？

**Comment by qmdx** [comment]
1.0.4   https://search.maven.org/#search%7Cga%7C1%7Cmybatisplus-spring-boot-starter  注解 xml 都可以， mp 是扩展了 mybatis 而已不换句话说就是继承了 mybatis 的所有

**Comment by zhouyongtao** [comment]
好的，谢谢
