### ISSUE TITLE
 mybatis-plus 是否支持对汉字排序？

### ISSUE THREAD

**Issue by GreatGarlic** [baomidou/mybatis-plus#1480]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter
3.1.0

 mybatis-plus 是否支持对汉字排序？

**Comment by miemieYaho** [comment]
去问数据库厂家

**Comment by GreatGarlic** [comment]
@miemieYaho 麻烦看下排序是否正确，我mysql用的字符集是utf-8对汉字排序的时候,没有API可以增加汉字编码转换函数，导致排序是错误的

**Comment by qmdx** [comment]
汉字字段？ 建议修改为英文单词，就算这个坑过去了后面还会有很多坑

**Comment by GreatGarlic** [comment]
@qmdx 好吧，看来我需要手写SQL

**Comment by GreatGarlic** [comment]
@qmdx 我的意思是字段中的内容是汉字
