### ISSUE TITLE
有没有jpa的MappedSuperclass的实现？

### ISSUE THREAD

**Issue by kiss-yu** [baomidou/mybatis-plus#1481]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter
3.1.0

在C extends B,B extends A时，A作为一个基础类，部分entity都拥有A的全部字段，B作为一个拓展基类，C 数据库不继承B的情况下。在tableInfo的tableFields没有将B的字段过滤掉。导致insert时C继承B的属性要全部手动set(null)，select**的时候需要重写AbstractMethod的sqlSelectColumns方法，目前也只能返回*替换。能不能把数据库基类和entity基类分开？

### 重现步骤
BaseEntity{
     a;
}
// 数据库实体  字段a,b
BaseUser extends BaseEntity{
   b;
}
// 数据库实体 字段a,c
WeixinUser extends BaseUser {
  c;
}
insert(WeixinUser )
sql: insert into weixin_user (a,b,c) 
select: select a,b,c from weixin_user
### 报错信息

b在weixin_user表中不存在

**Comment by miemieYaho** [comment]
不能
