### ISSUE TITLE
关于生成空指针错误

### ISSUE THREAD

**Issue by zhidongluo** [baomidou/mybatis-plus#1482]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator v3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

我看到已经有人修复了此错误，但是，最新版的3.1.2还没有打包进去

### 重现步骤
![image](https://user-images.githubusercontent.com/10561969/62817435-454ac900-bb69-11e9-9ec5-928c9791a4bd.png)

**Comment by qmdx** [comment]
等待发布或者使用 3.1.2 之后的快照版本 https://oss.sonatype.org/content/repositories/snapshots/com/baomidou/mybatis-plus-boot-starter/  快照使用查看文档
