### ISSUE TITLE
3.1.2Page对象的排序无效

### ISSUE THREAD

**Issue by mayee** [baomidou/mybatis-plus#1483]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用Pge对象进行分页查询，同时使用排序功能，asc和desc同时使用

### 重现步骤
```java
//分页查询
roleService.lambdaQuery()
                .likeRight(StringUtils.isNotEmpty(roleName), Role::getRoleName, roleName)
                .page(this.getPage(true))
                .convert(e -> e.convert(RoleDTO.class))

//this.getPage()方法中设置排序的写法
Page<T> page = new Page<>(pageNum, pageSize, openPaging);
page.addOrder(OrderItem.asc("remark"));
page.addOrder(OrderItem.desc("create_time"));

//通过Debug模式查看Page的Order对象中数据是没问题的，一个asc，一个desc

```
通过P6SPY实际打印的sql为
SELECT ..., create_time, remark FROM sys_role WHERE role_name LIKE 'admin%' ORDER BY remark, create_time DESC LIMIT 0,2

是我写的不对？
### 报错信息
无

**Comment by miemieYaho** [comment]
sql是正确的就自己排查

**Comment by mayee** [comment]
sql不正确，我设置的是asc+desc，sql里把两个字段全都变成desc了

**Comment by crazy6995** [comment]
我看逻辑似乎是PaginationInterceptor中使用PlainSelect进行sql构建,内部似乎会将所有OrderItem中的column拼接为string.  所以应该得不出这种sql
SELECT ..., create_time, remark FROM sys_role WHERE role_name LIKE 'admin%' ORDER BY remark ASC, create_time DESC LIMIT 0,2

**Comment by miemieYaho** [comment]
试用 3.2.0
