### ISSUE TITLE
自定义分页查询，QueryWrapper 不查询数据库

### ISSUE THREAD

**Issue by nicqchen** [baomidou/mybatis-plus#1486]
### 当前使用版本(必须填写清楚，否则不予处理)

   <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

自定义查询 QueryWrapper中有日期参数，QueryWrapper不执行SQL 查询数据库， 数据库MYSQL字段类型 Datetime

### 报错信息

没有报错

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by nicqchen** [comment]
AppOrderDeliveryPlan pageQuery = page.getQuery();
        QueryWrapper<AppOrderDeliveryPlan> queryWrapper = new QueryWrapper<>(pageQuery);
        queryWrapper.orderByDesc("create_date");
        IPage<AppOrderDeliveryPlan> pageData = this.page(page.createPage(), queryWrapper);

**Comment by nicqchen** [comment]
delivery plan 里面create_date 已经付值， 2019-09-01 11:22:12

**Comment by miemieYaho** [comment]
?????

**Comment by miemieYaho** [comment]
自行检查 FieldStrategy  相关配置

**Comment by nicqchen** [comment]
selectStrategy(since 3.1.2)
请确认确实在这个版本中有这个设置，我在3.1.2没有看到

**Comment by nicqchen** [comment]
mybatis-plus.global-config.db-config.select-strategy=not_null
mybatis-plus.global-config.db-config.insert-strategy=not_null
mybatis-plus.global-config.db-config.update-strategy=not_null

**Comment by nicqchen** [comment]
找到了，真是费劲啊
