### ISSUE TITLE
对spring batch的支持

### ISSUE THREAD

**Issue by huxipi** [baomidou/mybatis-plus#1487]
### 当前使用版本(必须填写清楚，否则不予处理)
 compile group: 'com.baomidou', name: 'mybatis-plus-boot-starter', version: '3.1.2'

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

最近在用spring batch做跑批的处理，mybatis提供MyBatisPagingItemReader，
看到大部分案例是这样的：
<property name="queryId" value="com.jr.gyl.base.pay.app.dao.erp.OpenLinkDao.queryByMutliParams" />
而我使用的是mp的注解,没找到注解的支持，现在对spring batch能提供一些支持吗？

### 重现步骤
未找到支持spring batch的相关代码
MyBatisPagingItemReader

### 报错信息
不支持spring batch

**Comment by miemieYaho** [comment]
不支持就不支持

**Comment by qmdx** [comment]
欢迎 PR
