### ISSUE TITLE
service层添加二级缓存机制

### ISSUE THREAD

**Issue by futurOR** [baomidou/mybatis-plus#1490]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
试图通过service层添加redis缓存时，尝试使用wrapper.getSqlSegment，发现似乎是用了Spel表达式：
object_code LIKE #{ew.paramNameValuePairs.MPGENVAL1} ORDER BY create_time DESC , object_code ASC
这个like后的值无法作为查询条件判断，无法做redis中的key，请问如何操作更合理？
![image](https://user-images.githubusercontent.com/10953765/62854536-2fcccf00-bd22-11e9-9d08-5bc93c54340c.png)

**Comment by miemieYaho** [comment]
自己想
