### ISSUE TITLE
策略配置not_empty，字符串ID 空值（“”）没过滤

### ISSUE THREAD

**Issue by MHlihao** [baomidou/mybatis-plus#1491]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatis.version>2.1.0</mybatis.version>
<mybatis-plus.version>3.1.0</mybatis-plus.version>
<springboot-mybatis.version>2.0.0</springboot-mybatis.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

ID为字符串，全局策略配置的是not_empty，其他字段都会过滤掉，只有 @TableId 不会过滤空字符串

### 重现步骤

版本3.1.0，全局策略配置的是not_empty，字符串ID空值("")无法过滤

### 报错信息

无

**Comment by MHlihao** [comment]
刚试了 3.1.2 也有这问题哦

**Comment by miemieYaho** [comment]
@TableId 一直都不会,自己去判断

**Comment by MHlihao** [comment]
好的，谢谢
