### ISSUE TITLE
使用isSigned命名属性，插入语句时报错

### ISSUE THREAD

**Issue by javalfLF** [baomidou/mybatis-plus#1492]
### 当前使用版本(必须填写清楚，否则不予处理)

2.3版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

错误信息为：
java.lang.RuntimeException: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'signed' in 'class org.otc.model.InvestorInfo'
其中InvestorInfo类中没有signed属性，只有
![image](https://user-images.githubusercontent.com/16460560/62918749-35362200-bdd3-11e9-8822-d6a1bf93c135.png)，并且有get、set方法
![image](https://user-images.githubusercontent.com/16460560/62918932-bf7e8600-bdd3-11e9-9723-ade51bbca043.png)

### 重现步骤

调用com.baomidou.mybatisplus.mapper.BaseMapper中的insert( )方法，传入InvestorInfo对象，提示上述错误。已配置开启驼峰命名映射。

### 报错信息

java.lang.RuntimeException: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'signed' in 'class org.otc.model.InvestorInfo'

**Comment by miemieYaho** [comment]
自行避开 boolean 类型的属性名不要is 开头,去看阿里java规范
