### ISSUE TITLE
UpdateForSet不会触发MetaObjectHandler.updateFill

### ISSUE THREAD

**Issue by cuirongqing** [baomidou/mybatis-plus#1493]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus 2.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
updateForSet差量更新数字不能够触发UpdateFill，但是改成update方法就可以触发。

### 重现步骤
updateForSet("Num=Num-1", entityWrapper)   // 不触发updateFill
update(entity, entityWrapper) // 触发updateFill

### 报错信息
无

**Comment by miemieYaho** [comment]
填充只能填充entity
