### ISSUE TITLE
OrderItem 未实现序列化

### ISSUE THREAD

**Issue by karanatarm** [baomidou/mybatis-plus#1494]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用dubbo, controller层为dubbo消费端 调用service提供端，
在controller编写如下代码 ：

page.setOrders(Arrays.asList(sortDir.equals("asc")? OrderItem.asc(sortField) : OrderItem.desc(sortField)));
page做为参数，问题可以其他方式解决，但希望能在controller，能按上面代码优雅编写

### 报错信息
 OrderItem must implement java.io.Serializable;

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/issues/1417

**Comment by karanatarm** [comment]
大神，下一版发版排序了吗，预计什么时候发版
