### ISSUE TITLE
建议可以自定义子接口继承IEnum接口

### ISSUE THREAD

**Issue by jianchengwang** [baomidou/mybatis-plus#1500]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.5

### 该问题是怎么引起的
IEnum接口只有一个`getValue()`方法，所以另外写了一个`IBaseEnum`接口继承`IEnum`增加`getDescription`方法我的需要。
然后定义一个枚举实现我自己定义的IBaseEnum
```
public enum UserState implements IBaseEnum<Integer> {
```
发现枚举没生效
于是我`IBaseEnum`移除了继承，然后在枚举类实现两个接口
```
public enum UserState implements IBaseEnum,IEnum<Integer> {
```
发现一样的问题
然后调换一下位置发现可以，如下面这样
```
public enum UserState implements IEnum<Integer>, IBaseEnum {
```

### 想要的实现
个人希望支持这一种
```
public enum UserState implements IBaseEnum<Integer> {
```
自己可以写一个子接口继承`IEnum`，然后枚举类直接继承我的子接口就可以了

### 报错信息
 No enum constant com.gy.pgcm.sys.enums.UserState.0

**Comment by qmdx** [comment]
IBaseEnum extends IEnum 解决 ，或者参考文档使用注解方式

**Comment by jianchengwang** [comment]
> IBaseEnum extends IEnum 解决 ，或者参考文档使用注解方式

额，，我就是IBaseEnum extends IEnum没效果，才发这个issue的，

**Comment by yuxiaobin** [comment]
问题应该是没有配置枚举扫描，或者没扫到你这个UserState

经测试，没有上述问题，参考[测试用例](https://gitee.com/baomidou/mybatis-plus-samples/commit/611e0be6134c0113823f4aa265f3bc7d21af3558)

**Comment by jianchengwang** [comment]
> 问题应该是没有配置枚举扫描，或者没扫到你这个UserState
> 
> 经测试，没有上述问题，参考[测试用例](https://gitee.com/baomidou/mybatis-plus-samples/commit/611e0be6134c0113823f4aa265f3bc7d21af3558)

我的问题，应该是接口继承没写好，这样子可以
```
public interface IBaseEnum<T extends Serializable> extends IEnum {
    T getValue();
    Object getDescription();
}

```
