### ISSUE TITLE
updateById()存在bug

### ISSUE THREAD

**Issue by zhangguangkuan** [baomidou/mybatis-plus#1502]
### 当前使用版本(必须填写清楚，否则不予处理)

使用 springboot mybatis mybatisPlus 连接池使用 德鲁伊 
在执行 updateById() 的操作 通过德鲁伊 后台调试界面发现，连接池连接数没有进行关闭

### 重现步骤

使用上述配置 通过德鲁伊 调试发现 活跃连接数 会跟随 updateById() 的执行一直上涨

**Comment by miemieYaho** [comment]
没debug确认过别瞎提issue

**Comment by qmdx** [comment]
请测试下

1、移除 mybatisPlus 看下是不是一样的效果

2、更换为连接池  HikarCP 试试

**Comment by zhangguangkuan** [comment]
> 请测试下
> 
> 1，移除mybatisPlus看下是不是一样的效果
> 
> 2，更换为连接池HikarCP试试看下是不是一样的效果

连接池替换还没试过，但是尝试了一下其他的内置函数 是不会有这个问题的，比如直接更换成 update（）在格鲁伊 就不会发现该问题了

**Comment by qmdx** [comment]
> > 请测试下
> > 1，移除mybatisPlus看下是不是一样的效果
> > 2，更换为连接池HikarCP试试看下是不是一样的效果
> 
> 连接池替换还没试过，但是尝试了一下其他的内置函数 是不会有这个问题的，比如直接更换成 update（）在格鲁伊 就不会发现该问题了

请给出有理有据的测试过程

**Comment by ppr1011** [comment]
德鲁伊，我是牧师
