### ISSUE TITLE
mysql + mybatis-plus 自定义主键自增id生成器配置。

### ISSUE THREAD

**Issue by fongjinming666** [baomidou/mybatis-plus#1504]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus version: 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
 想搭建一个新工程，以spring-boot(2.0.6)+ mybatis-plus + hikari+mysql(8.0)的结构.
目前已经搭建成功，但希望打造一个主键自增的id生成器。
请问下mysql +mybatis-plus的主键自增的demo存在吗？寻找了下只找到orcale的。

**Comment by miemieYaho** [comment]
看文档

**Comment by fongjinming666** [comment]
> 看文档

你指哪里？
