### ISSUE TITLE
关于自定义mapper接口同时继承MP的BaseMapper和ES的ElasticsearchRepository接口报错问题

### ISSUE THREAD

**Issue by sunjidong** [baomidou/mybatis-plus#1505]
版本包如下
'com.baomidou', name: 'mybatis-plus-boot-starter', version: '3.1.2'
compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-elasticsearch', version: '2.1.6.RELEASE'

同时继承这两个接口，启动项目就报错，我用的springboot。目测是重复注入问题。
创建两个接口分别继承是可以的。

### 报错信息
there is already [ Geneic bean :class [org.mybatis.spring.mapper.MapperFactoryBean];scope-single].........

**Comment by qmdx** [comment]
这个你不是应该提给 spring 么？

**Comment by sunjidong** [comment]
两边都提了，有什么好的建议或者解决方案么？在官方未给出回应之前

**Comment by qmdx** [comment]
分开用啊
