### ISSUE TITLE
建议：分页使用do while，可以简化代码，但是，能不能再简化点？

### ISSUE THREAD

**Issue by fanlushuai** [baomidou/mybatis-plus#1507]
### 当前使用版本(必须填写清楚，否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

如下使用do while查询分页，如注释所示小建议：
        IPage page = new Page();
        page.setPages(pageSize);
        //不能使用new Page(0,pageSize); 内部会忽略小于1的数值。建议增加构造器，或者其他方式
        page.setCurrent(0);
        Page<String> pushTokensPage;
        do {
           //需要自己手动plus 1。建议增加函数。或者其他方式
            page.setCurrent(page.getCurrent() + 1);
            pushTokensPage = deviceMapper.listPushToken(page, platform);
            pushByTokenDTO.setPushTokens(new HashSet<>(pushTokensPage.getRecords()));
            mqService.send(pushByTokenDTO);
            log.info("page current {} suc", page.getCurrent());
        } while (pushTokensPage.hasNext());

**Comment by fanlushuai** [comment]
page.setSize(pageSize);

**Comment by miemieYaho** [comment]
没必要
