### ISSUE TITLE
mysql+mybatis-plus生成自定义主键自增失效

### ISSUE THREAD

**Issue by fongjinming666** [baomidou/mybatis-plus#1508]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus version:3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
注入mysql 自定义主键生成器失败
### 重现步骤

public class SnowFlakeIdGenerator implements IKeyGenerator {

    @Resource
    private SnowFlake snowFlake;

    /**
     * uuid生成器
     *
     * @param incrementerName
     * @return
     */
    @Override
    public String executeSql(String incrementerName) {
        return "select " + snowFlake.nextId() + " from dual";
    }
}

@Data
@Accessors(chain = true)
@TableName(value = "sys_user")
@KeySequence(value = "snowFlakeIdGenerator")
public class SysUser implements Serializable {

    @TableId(type = IdType.NONE)
    private Long id;
}

### 报错信息

失败原因是SnowFlakeIdGenerator的executeSql执行每次id都是一样的，并没有生效。

**Comment by fongjinming666** [comment]
请问下mybatis-plus如何实现类似hibernate的IdentifierGenerator效果?

**Comment by qmdx** [comment]
例如：com.baomidou.mybatisplus.core.incrementer.IKeyGenerator.H2KeyGenerator 其中 executeSql 参数 incrementerName 是接收 `@ KeySequence ` 主键 value 值拼接作为完整 key 查询 sql 如果你不需要可以不注解。

Spring boot 注入：
```
@Bean
public H2KeyGenerator h2KeyGenerator(){
    return new H2KeyGenerator();
}
```
