### ISSUE TITLE
条件构造器like过滤占位符

### ISSUE THREAD

**Issue by wuchuanpeng** [baomidou/mybatis-plus#1509]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
`queryWapper2.like("name","张三");
queryWapper.and(i ->queryWapper2);`
queryWapper生成的sql中不会带上%%;

### 重现步骤

如上
### 报错信息

无报错

**Comment by miemieYaho** [comment]
看文档,自己排查,别瞎用
