### ISSUE TITLE
3.1.2的表名和字段转驼峰有问题

### ISSUE THREAD

**Issue by a5595303** [baomidou/mybatis-plus#1514]
数据库字段和表名都是带下划线的
进行如下设置后
strategy.setNaming(NamingStrategy.underline_to_camel);
strategy.setColumnNaming(NamingStrategy.no_change);
设置后,字段变成了驼峰,而不是表里带下划线的那种..

**Comment by a5595303** [comment]
现在用3.1.0版本,就可以正常的生成  驼峰的实体名称,下划线的成员属性

**Comment by qmdx** [comment]
设置后,字段变成了驼峰,而不是表里带下划线的那种..

描述清楚你期望的和实际不一样的点，然后打开 issue
