### ISSUE TITLE
3.1.1QueryWrapper<T>.select(String... columns) 查询指定列(id,user_name,card_number), 只有id映射到实体类上.

### ISSUE THREAD

**Issue by Luokexi** [baomidou/mybatis-plus#1516]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatisplus.version 3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用 userInfoDmoQueryWrapper.select("id","user_name","gender","card_number")

### 重现步骤

1. 配置实体类 实体类与数据表列名不一致的用的@TableField
2. dao接口继承 BaseMapper<T>
3. 构造QueryWrapper对象
QueryWrapper<UserInfoDmo> userInfoDmoQueryWrapper = new QueryWrapper<>();
4. 设置条件 
userInfoDmoQueryWrapper.select("id","user_name","gender","card_number");
5. 返回数据
return userInfoDmos;

### 报错信息

没有报错信息 
SQL日志打印的是
Preparing: SELECT id,user_name,gender,card_number FROM t_user_info
Parameters: Columns: id, user_name, gender, card_number 
Row: 1, test, 0, 7758521
Row: 2, test2, 1, 775852
Row: 1164419024302030850, 张三, 1, 1505310225
Row: 1164421403969724417, 李四, 1, 1505310225
Total: 4

**Comment by Luokexi** [comment]
注解和获取返回值无关, 数据封装走的mybatis? 能解释一下么?

**Comment by Luokexi** [comment]
配置了mybatis自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性. 还是不行.

**Comment by miemieYaho** [comment]
数据封装走的mybatis
