### ISSUE TITLE
返回值为map时，得到的数据不正确

### ISSUE THREAD

**Issue by liufeng82012016** [baomidou/mybatis-plus#1517]
版本：springboot启动器 2.3

问题描述：
select a.*,(select **)as f,(select **)as s from **;
值返回到一个map中
复制sql到mysql，f 和 s都等于1
打印得到
f = false；
s = 0X****
没有报错，只是返回数据和预期不符合

**Comment by qmdx** [comment]
xml 中写的？具体代码贴出
