### ISSUE TITLE
关于

### ISSUE THREAD

**Issue by qierkang** [baomidou/mybatis-plus#1518]
## 在mapper.xml做日期 test="createTime != null and createTime !='' " 的时候
在做日期空判断的时候，经过后来查询：
mybatis 3.3.0中对于时间参数进行比较时的一个bug. 如果拿传入的时间类型参数与空字符串''进行对比判断则会引发异常

**Comment by qmdx** [comment]
mp 代码 date 类型处理了不会判断空

**Comment by miemieYaho** [comment]
mp不会做这种事
