### ISSUE TITLE
自定义sql执行查询结果不正确

### ISSUE THREAD

**Issue by wang229819838** [baomidou/mybatis-plus#1523]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

自定义sql查询，出现的结果和拿sql去数据库中执行结果不一样。而且还会把上一个查询中记录字段值赋予本次sql执行的结果中。
![image](https://user-images.githubusercontent.com/9146527/63631950-bbb6f300-c660-11e9-9c02-f1bddc79c255.png)
![image](https://user-images.githubusercontent.com/9146527/63631964-e4d78380-c660-11e9-9da4-79799ebd163d.png)
![image](https://user-images.githubusercontent.com/9146527/63631999-57486380-c661-11e9-82d3-493a31c84031.png)
![image](https://user-images.githubusercontent.com/9146527/63632043-fe2cff80-c661-11e9-92ad-1b5bd1436236.png)

**Comment by drinkagain** [comment]
...擦，这个问题一直可以复现吗？

**Comment by wang229819838** [comment]
对的，一直这样

**Comment by wang229819838** [comment]
> 个问题一直可以复现

对，一直可以复现的。

**Comment by drinkagain** [comment]
不对啊，你代码里执行的是workorderid=8,你 sql 写的是workorderId =9

**Comment by wang229819838** [comment]
yi

> 不对啊，你代码里执行的是workorderid=8,你 sql 写的是workorderId =9

一样的，我查id为8，也是一样的。
![image](https://user-images.githubusercontent.com/9146527/63632645-2ec66680-c66d-11e9-818f-8cf0327dad61.png)

**Comment by drinkagain** [comment]
怎么感觉你代码中的数据源和你执行Sql的数据源不是同一个，我这没有出现这个问题

**Comment by wang229819838** [comment]
> 怎么感觉你代码中的数据源和你执行Sql的数据源不是同一个，我这没有出现这个问题

我检查了，我项目中用到两个数据源，一个mysql，一个是pgsql，他们是不同的库。执行上面几条SQL就是同一个库，而且navicat，和代码用的确实是同一个数据库的（pgsql）。pgsql 数据库连的是外网的，只有一个。我再找找是不是mp哪里没有配置好。之前问题是找不到xml文件中sql，之后就把扫描xml写到代码中，现在就是这个问题了。

**Comment by wang229819838** [comment]
好像找到问题了，是数据库原因。我把外网数据库迁移到本地，所有地方用本地库执行了下，发现数据是正确的。
