### ISSUE TITLE
InsertBatchSomeColumn

### ISSUE THREAD

**Issue by slyang520** [baomidou/mybatis-plus#1527]
### 当前使用版本(必须填写清楚，否则不予处理)
start 3.1.2
com.baomidou.mybatisplus.extension.injector.methods.additional.InsertBatchSomeColumn

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

InsertBatchAllColumn
InsertBatchSomeColumn
InsertBatch
这3个扩展方法， 有什么区别没，怎么变来变去的 ？问下这个方法的真实含义是什么，我反正是看懵了。

**Comment by miemieYaho** [comment]
看源码注释
