### ISSUE TITLE
公共字段自动注入， 无注解的确不生效，但是此时再给公共字段注入自定义值， 自动注入生效了

### ISSUE THREAD

**Issue by LeeCoder3962** [baomidou/mybatis-plus#1528]
### 当前使用版本(必须填写清楚，否则不予处理)
3.05

调用baseMapper.insert(entity), 
使用公共字段自动注入功能， 删掉实体属性的fill=FieldFill.INSERT的确不再自动注入，
但是此时再在controller里面给entity的公共自动属性注入自定义值， 自动注入又生效了
导致最终无法对此属性注入自定义值

我以为没有注解就算此属性不参与公共字段注入功能？
所以在MetaObjectHandler里面需要我自己对注解做一次判断？

**Comment by miemieYaho** [comment]
mp生成if标签,对于注入模式下没有if标签,mybatis的ognl走完之后,进去注入流程

**Comment by miemieYaho** [comment]
你要不覆盖之前set的值,就自己判定一下是不是有值,null再set
