### ISSUE TITLE
建议自动生成的Mapper.xml增加一些东西

### ISSUE THREAD

**Issue by hhzh** [baomidou/mybatis-plus#153]
比如：生成的resultMap的column属性加表名前缀，防止关联查询的时候字段冲突。
还可以生成需要查询的字段，在<sql></sql>标签里。

**Comment by asd8510678** [comment]
自己改下呗

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="${package.Mapper}.${table.mapperName}">

#if(${enableCache})
	
	<cache type="org.mybatis.caches.ehcache.LoggingEhcache"/>

#end
#if(${baseResultMap})
	
	<resultMap id="BaseResultMap" type="${package.Entity}.${entity}">
#foreach($field in ${table.fields})
#if(${field.keyFlag})##生成主键排在第一位
		<id column="${field.name}" property="${field.propertyName}" />
#end
#end
#foreach($field in ${table.commonFields})##生成公共字段
	<result column="${field.name}" property="${field.propertyName}" /> 
#end
#foreach($field in ${table.fields})
#if(!${field.keyFlag})##生成普通字段
	<result column="${field.name}" property="${field.propertyName}" /> 
#end
#end
	</resultMap>
#end
#if(${baseColumnList})
    
    <sql id="Base_Column_List">
        ${table.fieldNames}
    </sql>
    
    <sql id="Find_List_Where">
		<where>
#foreach($field in ${table.commonFields})##生成字段
#if(${field.propertyType.equals("String")})
		<if test="m.${field.propertyName} != null and m.${field.propertyName} != ''">
#else
		<if test="m.${field.propertyName} != null">
#end
			AND ${field.name} = #{m.${field.propertyName}}  
		</if>
#end
#foreach($field in ${table.fields})##生成字段
#if(${field.propertyType.equals("String")})
		<if test="m.${field.propertyName} != null and m.${field.propertyName} != ''">
#else
		<if test="m.${field.propertyName} != null">
#end
			AND ${field.name} = #{m.${field.propertyName}}  
		</if>
#end
    	</where>
    	ORDER BY id ASC
    </sql>

    
	

#end
</mapper>

**Comment by qmdx** [comment]
如楼上自定义下 vm 模板就可以了
