### ISSUE TITLE
下载3.0源码导入idea 编译不通过？

### ISSUE THREAD

**Issue by 969703029** [baomidou/mybatis-plus#1531]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0

### 重现步骤
下载源码导入idea，编译

### 报错信息
Could not set unknown property 'archiveClassifier' for task ':mybatis-plus:sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
Open File

**Comment by miemieYaho** [comment]
编译不了我们怎么发的版?

**Comment by 969703029** [comment]
那idea和gradle用的什么版本呢？我这边用的4.9的gradle确实报错。

**Comment by 969703029** [comment]
@miemieYaho

**Comment by miemieYaho** [comment]
最新
