### ISSUE TITLE
单个参数无法使用@Param

### ISSUE THREAD

**Issue by GoldSubmarine** [baomidou/mybatis-plus#1532]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

# mapper
List<Permission> findList(@Param("permission") Permission permission);

# xml
    <select id="findList" parameterType="org.javahub.submarine.modules.system.entity.Permission" resultType="org.javahub.submarine.modules.system.entity.Permission">
        SELECT  a.*  FROM permission a WHERE a.del_flag = #{permission.delFlag}
    </select>

虽然只有一个对象参数，但因为一些原因，我想使用#{permission.delFlag}，而不是#{delFlag}，测试后在纯springboot mybatis情况下，上述代码正常运行，引入plus后，报错：

org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'permission' in 'class org.javahub.submarine.modules.system.entity.Permission'

他认为#{permission.delFlag}中的permission是一个属性

**Comment by yuxiaobin** [comment]
经测试，并没有上述问题

参考[提交](https://gitee.com/baomidou/mybatis-plus-samples/commit/6a1e2c82e0a66bcc57ec656b48a3c25b4f8ca748)

**Comment by GoldSubmarine** [comment]
抱歉，不是plus的问题，我用的spring的Param注解，使用apache的就没有问题

import org.apache.ibatis.annotations.Param;

vs

import org.springframework.data.repository.query.Param;
