### ISSUE TITLE
代码生成器忽略某个字段

### ISSUE THREAD

**Issue by pizhihui** [baomidou/mybatis-plus#1533]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

我想忽略某个字段，翻了下源码好像不能，希望可以提供下这个功能。
类似于 mbg 的 ignoreColumn 功能。感谢

**Comment by qmdx** [comment]
设置为公共字段即不在生成

**Comment by pizhihui** [comment]
嗯嗯，已经可以了。谢谢
