### ISSUE TITLE
Mybatis-Plus支持什么版本的 Mybatis？

### ISSUE THREAD

**Issue by okLuo** [baomidou/mybatis-plus#1534]
最新的版本3.2.0，使用3.4.4的MyBatis的导致冲突，不知道什么版本的MyBatis的适用于最新版本的MyBatis的加

**Comment by okLuo** [comment]
最新的版本3.2.0，使用3.4.4的mybatis导致冲突，不知道什么版本的mybatis适用于最新版本的Mybatis-Plus

**Comment by okLuo** [comment]
> 最新的版本3.2.0，使用3.4.4的MyBatis的的导致冲突，不知道什么版本的的MyBatis的适用于最新版本的Mybatis-Plus？

**Comment by miemieYaho** [comment]
自己看依赖.mp维护了mybatis的依赖版本

**Comment by qmdx** [comment]
文档说明了不要自己引入 Mybatis  依赖避免冲突 mp 会自动维护
