### ISSUE TITLE
UpdateWrapper工作不正常

### ISSUE THREAD

**Issue by daanhan** [baomidou/mybatis-plus#1535]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
`
			UpdateWrapper<DltPriceEntity> uw = new UpdateWrapper<>();
			uw.set(DltPriceEntity.DIDA_HOTEL_ID, hotel.HotelID);
			uw.set(DltPriceEntity.DATE, dateIn);

			p = new DltPriceEntity();
			p.setRoomStatus(0);
			update(p, uw);`

![image](https://user-images.githubusercontent.com/2290270/63703506-aeb22380-c85b-11e9-916b-4f2bd2e82eb3.png)

### 重现步骤
执行上述代码

### 报错信息
`### SQL: UPDATE tb_dlt_price  SET room_status=?,   dida_hotel_id=?,date=?`
执行的SQL居然是如下SQL，没有WHERE条件

**Comment by miemieYaho** [comment]
你没给where条件还想哪变出来?

**Comment by FifthSofa** [comment]
遇到类似问题，好不容易找到有人提问的，但是都没给解决方法，这边贴一下DOC地址 https://github.com/baomidou/mybatis-plus-doc/blob/master/guide/wrapper.md
