### ISSUE TITLE
在插件中注入其他的bean,springboot启动报错

### ISSUE THREAD

**Issue by tangjizhou** [baomidou/mybatis-plus#1536]
### 当前使用版本(必须填写清楚，否则不予处理)

 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>

springboot： 2.1.7.RELEASE
java.version:   11

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

<img width="794" alt="image" src="https://user-images.githubusercontent.com/23544926/63702647-eb7d1b00-c859-11e9-8bd5-e532f882ceff.png">

### 重现步骤

在插件中注入其他的bean之后，启动就直接报错了,
Field baseMapper in com.baomidou.mybatisplus.extension.service.impl.ServiceImpl required a single bean, but 2 were found:
	- productMapper: defined in file [/Users/tangjizhou/work/project/tmall/target/classes/net/mshome/twisted/tmall/mapper/ProductMapper.class]
	- sqlLogMapper: defined in file [/Users/tangjizhou/work/project/tmall/target/classes/net/mshome/twisted/tmall/mapper/SqlLogMapper.class]
这两个文件通过mybatisplus代码生成器自动生成，还未添加任何内容。
插件中注入另一个service之后，则报错涉及的mapper随之更改，错误还是一样。

<img width="531" alt="image" src="https://user-images.githubusercontent.com/23544926/63703500-ace86000-c85b-11e9-91b7-f349d0770b8e.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/23544926/63703671-fe90ea80-c85b-11e9-91b5-93d75de90c73.png">

### 报错信息
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/23544926/63702723-149dab80-c85a-11e9-9ce1-bbe29629966a.png">

**Comment by miemieYaho** [comment]
启动顺序问题,自己想办法

**Comment by yuxiaobin** [comment]
MybatisSqlInterceptor 里的ISqlLogService 尝试加 (AT)Lazy 试试看

**Comment by teaRRe** [comment]
> 启动顺序问题,自己想办法

SB
