### ISSUE TITLE
生成器有没有考虑生成枚举呢

### ISSUE THREAD

**Issue by zhidongluo** [baomidou/mybatis-plus#1539]
比如说，在注释上，以 @normal:0:正常 @delete:1:删除 。 然后能够生成枚举类

**Comment by qmdx** [comment]
意义不大，就那么几个枚举类你手动加一下好了

**Comment by LinWanCen** [comment]
因为Java枚举实现的原因，设计成不能继承造成了大量重复代码，我也想写一个生成的工具。
#683 #2319
