### ISSUE TITLE
关于 分页操作

### ISSUE THREAD

**Issue by ShixinPeng** [baomidou/mybatis-plus#154]
场景：
进行分页查询，数据list可以获取，但是page中total为0

发现原因：
查询的sql语句 select字段有重名的，导致执行select count(*) 会抛异常，total为0，
希望改进：
进行查询数据正常，但是分页进行查询总数的查询sql会执行失败，total为0；希望可以查总数异常时抛出异常

**Comment by qmdx** [comment]
分页文档： http://baomidou.oschina.io/mybatis-plus-doc/#/page-plugin

【查询的sql语句 select字段有重名的，导致执行select count(*) 会抛异常，total为0】 给出具体 sql

**Comment by yuxiaobin** [comment]
贴一下查询的代码和sql 不然没法改进

**Comment by qmdx** [comment]
贴出代码跟进后打开 issue 或者加入我们 q 群 576493122

**Comment by liwiseap** [comment]
场景：
进行分页查询，数据list有一条，但是page中total为0
版本：mybatis-plus 2.1.0
查询语句：select * from t_user
