### ISSUE TITLE
字段值与属性名未自动映射

### ISSUE THREAD

**Issue by karanatarm** [baomidou/mybatis-plus#1543]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
1、表里字段名f_option_type,实体类属性名optionType，使用注解@TableField("f_option_type")，在做映射文件中定义查询sql select f_option_type from 表名，并在@TableName(autoResultMap=true)开启了自动映射，执行查询，集合不为空，但元素所为空。
为何不对注解里的字段名与属性名做映射
2、升级3.2.0，在extension扩展包里删除了PerformanceInterceptor，为什么要删除呢。
3、是否有群？
### 重现步骤
希望大牛们解答后再关闭！

**Comment by qmdx** [comment]
1、autoResultMap 这个是给 typeHandler 处理用，默认可用不用加，你移除再试试，另外这个一条你在仔细排查下，然后反馈具体过程
2、查看文档 https://mybatis.plus/ 新的替代方案
3、技术讨论 QQ 群 ： 576493122 🈵 、 648281531 、 643509491

**Comment by miemieYaho** [comment]
自己写的sql就自己写as,不维护就删了,看文档有群

**Comment by karanatarm** [comment]
注解里字段名，为什么不做自动映射呢，需要在sql里写别名

**Comment by karanatarm** [comment]
如果字段没有前缀可以自动映射，那么我理解决，如果有前缀，也可以通过注解里的字段名和属性做自动映射，这样写些sql也很方便

**Comment by qmdx** [comment]
> 如果字段没有前缀可以自动映射，那么我理解决，如果有前缀，也可以通过注解里的字段名和属性做自动映射，这样写些sql也很方便

TableFIeld 属于 mp 注解只对 mp 提供的相关方法有效， xml  sql 写法遵守原生规则，要么 as 要么规范命名。更多你需要去了解原生用法

**Comment by karanatarm** [comment]
好的，感谢大神的回复！




------------------ 原始邮件 ------------------
发件人: "qmdx"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 中午12:18
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com>;
抄送: "杨星"<841866911@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [baomidou/mybatis-plus] 字段值与属性名未自动映射 (#1543)



 
如果字段没有前缀可以自动映射，那么我理解决，如果有前缀，也可以通过注解里的字段名和属性做自动映射，这样写些sql也很方便
  
TableFIeld 属于 mp 注解只对 mp 提供的相关方法有效， xml  sql 写法遵守原生规则，要么 as 要么规范命名。更多你需要去了解原生用法
