### ISSUE TITLE
数据库机子故障转移后还是连的老的机子

### ISSUE THREAD

**Issue by ToryZhou** [baomidou/mybatis-plus#1544]
### 当前使用版本(必须填写清楚，否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.0</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用一个url 的 endpoint, 当endpoint后面的IP地址（机子）变了过后， 链接还是一直连的老的机子。老的机子从可读可写变成了只读。 然而endpoint的实际指向已经是指向可读可写的机子了

### 重现步骤
进行写操作

### 报错信息
```
Cause: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
 3164 ; uncategorized SQLException for SQL []; SQL state [HY000]; error code [1290]; The MySQL server is running with the --read-only option so it cannot execute this statement; nested exception is java.sql.SQLEx      ception: The MySQL server is running with the --read-only option so it cannot execute this statement
```

**Comment by miemieYaho** [comment]
mp不维护DataSource,自己解决
