### ISSUE TITLE
OrderItem#build是private方法，外部没有办法直接调用，Page#addOrder却提示可以直接用

### ISSUE THREAD

**Issue by giszhangke** [baomidou/mybatis-plus#1545]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

增加自定义的分页查询条件时，外部没有办法直接调用OrderItem#build，Page#addOrder却提示可以直接用，

可否考虑把OrderItem#build改成public

**Comment by miemieYaho** [comment]
用其他俩方法
