### ISSUE TITLE
QueryWrapper#select 有别名的字段映射异常

### ISSUE THREAD

**Issue by JanYunkai** [baomidou/mybatis-plus#1546]
### 当前使用版本(必须填写清楚，否则不予处理)
Mybatis-plus 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用了MBG生成代码类似is_xxxx的布尔字段
在select映射有问题

### 重现步骤
mysql表单user 字段  is_enable tinyint(1) 

对象
// 主要是为了使用字段的typeHandler
@TableName(resultMap = "BaseResultMap")
class User {
  @TableField("is_enable")
  private Boolean enable;
}
BaseResultMap
<result column="is_enable" jdbcType="BIT" property="enable" />

LambdaQueryWrapper<User> queryWrapper = new LambdaQueryWrapper<>();
queryWrapper.select(User::getEnable);
List<User> userList = list(queryWrapper);

生成的SQL select is_enable AS enable FROM user;

userList.getEnable()   >> NullPointException

在BaseResultMap中新增
<result column="is_enable" jdbcType="BIT" property="enable" />
<result column="enable" jdbcType="BIT" property="enable" />
就能查到数据。

特别说明：
@TableField("is_enable")是必须的，否则会报
enable 字段不存在

**Comment by qmdx** [comment]
不要使用 is_xxx 命名，这个会和 java get set  isXxx 冲突，所有 
@TableField("is_enable") 这必须申明

**Comment by JanYunkai** [comment]
事实上不会，
is_xxx这种是布尔字段(Boolean)，MBG生成代码的时候会使用columnOverride 映射到xxx（xml文件里的BaseResultMap）
我发现的问题是是
用了注解@TableName(resultMap = "BaseResultMap")
和@TableField("is_enable")你在解析与反解析的时候字段映射不一致。
你生成的SQL其实不用 select is_enable as enable 因为is_enable -> enable的映射存在于BaseResultMap中。而enable -> enable 是没有的。

以上。
关的别那么快。至少看完我的描述，不是.................
