### ISSUE TITLE
当条件参数为null时如何不拼接?

### ISSUE THREAD

**Issue by koy-tome** [baomidou/mybatis-plus#155]
ew.where ("week_ending_day >= {0}",a.getWeekStartDay ())
                .and ("week_ending_day <= {0}",a.getWeekEndingDay ()); 这样写, 当a.getWeekEndingDay ()为null时还是会拼接条件. 查看了api, 没看到有提到这点. 除了if判断, 还有什么别的办法么?

**Comment by yuxiaobin** [comment]
eq.and( a.getWeekEndingDay ()!=null, "week_ending_day <= {0}",a.getWeekEndingDay ())
