### ISSUE TITLE
 mybatis-plus 3.0 代码生成器 字段是否必须，如何获取？

### ISSUE THREAD

**Issue by 18222962201** [baomidou/mybatis-plus#1551]
mybatis-plus 3.0

 自定义模板类

 想知道在模板中是否可以获取每个字段是否为空？因为我们想添加spring校验

**Comment by qmdx** [comment]
参考字段其他信息查询注入

https://mp.baomidou.com/guide/generator.html#%E5%AD%97%E6%AE%B5%E5%85%B6%E4%BB%96%E4%BF%A1%E6%81%AF%E6%9F%A5%E8%AF%A2%E6%B3%A8%E5%85%A5

调整下查询 sql 然后自定义取出你要的内容
