### ISSUE TITLE
不支持phoenix吗？

### ISSUE THREAD

**Issue by huan9dianyu** [baomidou/mybatis-plus#1554]

**Comment by miemieYaho** [comment]
欢迎 pr

**Comment by FlyingGlass** [comment]
最近针对mybatis-plus整合了phoenix，实现链接:https://github.com/FlyingGlass/backend-starter-mybatis，PR有何代码规范要求，有空我可以提交PR，你们看下是否要merge.

**Comment by qmdx** [comment]
> 最近针对mybatis-plus整合了phoenix，实现链接:https://github.com/FlyingGlass/backend-starter-mybatis
> 
> PR有何代码规范要求，有空我可以提交PR，你们看下是否要merge.

你先 PR 有问题我们会调整

**Comment by FlyingGlass** [comment]
已提交PR，https://github.com/baomidou/mybatis-plus/pull/1946

**Comment by FlyingGlass** [comment]
> > 最近针对mybatis-plus整合了phoenix，实现链接:https://github.com/FlyingGlass/backend-starter-mybatis
> > PR有何代码规范要求，有空我可以提交PR，你们看下是否要merge.
> 
> 你先 PR 有问题我们会调整

已提交PR，#1946
