### ISSUE TITLE
多库情况下GlobalConfiguration.dbDype不能按不同库分别设置

### ISSUE THREAD

**Issue by xirui0920** [baomidou/mybatis-plus#1555]
### 当前使用版本(必须填写清楚，否则不予处理)
2.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
springboot配置了多库。一个mysql，一个oracle
主库是mysql，GlobalConfiguration.dbDype配了mysql
查询oracle库某个数据时，有个字段是mysql的关键字，导致生成sql包含``，查询报错。oracle不支持字符``

### 重现步骤
springboot配置了多库。一个mysql，一个oracle
主库是mysql，GlobalConfiguration.dbDype配了mysql
查询oracle库某个数据时，有个字段是mysql的关键字，导致生成sql包含``，查询报错。oracle不支持字符``

**Comment by qmdx** [comment]
不用配置的情况会自动识别，配置就会强制使用你设置的
