### ISSUE TITLE
新版本为什么去掉updateAllColumnById

### ISSUE THREAD

**Issue by fangpy** [baomidou/mybatis-plus#1556]
### 版本：3.1.2

我现在使用的3.X版本去掉了updateAllColumnById方法、只能全局或者在bean上配置updateStrategy，但是我想要动态的调用updateById和updateAllColumnById，这个该怎么处理啊

**Comment by miemieYaho** [comment]
看文档

**Comment by adin283** [comment]
you can use this helper below to avoid write many lines to set property to null.

`
package com.your.package.name;

import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import com.baomidou.mybatisplus.core.metadata.TableFieldInfo;
import com.baomidou.mybatisplus.core.metadata.TableInfo;
import com.baomidou.mybatisplus.core.toolkit.TableInfoHelper;
import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import com.baomidou.mybatisplus.extension.service.IService;
import org.springframework.util.ReflectionUtils;

import java.lang.reflect.Field;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 *
 * @author: zwb
 * @date: 2019-09-05
 * @time: 21:41
 */

public class MyBatisPlusHelper {
    public static <T extends Model> void updateAllColumnById(IService<T> service, Model<T> model) {
        UpdateWrapper updateWrapper = Wrappers.<T>update();
        TableInfo tableInfo = TableInfoHelper.getTableInfo(model.getClass());
        List<TableFieldInfo> fieldList = tableInfo.getFieldList();
        for (TableFieldInfo fieldInfo : fieldList) {
            String column = fieldInfo.getColumn();
            String property = fieldInfo.getProperty();
            Field field = ReflectionUtils.findField(model.getClass(), property);
            field.setAccessible(true);
            Object value = ReflectionUtils.getField(field, model);
            updateWrapper.set(column, value);
        }

        String primaryKeyProperty =  tableInfo.getKeyProperty();
        Field field = ReflectionUtils.findField(model.getClass(), primaryKeyProperty);
        field.setAccessible(true);
        Object primaryKeyValue = ReflectionUtils.getField(field, model);
        updateWrapper.eq(tableInfo.getKeyColumn(), primaryKeyValue);

        service.update((T) model, updateWrapper);
    }
}


// before
yourService.update(
        entity,
        Wrappers.<YourEntity>lambdaUpdate()
                .set(YourEntity::getField1, entity.getField1())// which may be null
                .set(YourEntity::getField2, entity.getField2())
                .set(YourEntity::getField3, entity.getField3())
                .set(YourEntity::getField4, entity.getField4())
                .set(YourEntity::getField5, entity.getField5())
                .set(YourEntity::getField6, entity.getField6())
                ...
);

// after
MyBatisPlusHelper.updateAllColumnById(yourService, yourEntity);

`

**Comment by qmdx** [comment]
文档选装部分
