### ISSUE TITLE
配置逻辑删除无效; 和fill无法自动填充

### ISSUE THREAD

**Issue by cielswift** [baomidou/mybatis-plus#1563]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-boot-starter :3.2.0
spring boot 2.1.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
配置逻辑删除无效; 和fill无法自动填充;
### 重现步骤
![捕获](https://user-images.githubusercontent.com/42295829/64078346-32f92080-cd0c-11e9-84dd-3ae8e9c0dffe.PNG)
![捕获2](https://user-images.githubusercontent.com/42295829/64078347-3391b700-cd0c-11e9-9bd7-d5a088ecba58.PNG)
![捕获3](https://user-images.githubusercontent.com/42295829/64078349-3391b700-cd0c-11e9-8df8-a6f0af500b78.PNG)

**Comment by yuxiaobin** [comment]
描述不明确啊

是insert的时候没自动填充？你的自动填充器呢？

[自动填充+逻辑删除的sample](https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-deluxe)
