### ISSUE TITLE
自动填充插件不起作用了

### ISSUE THREAD

**Issue by sushengbuyu** [baomidou/mybatis-plus#1565]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？
通过AbstractRoutingDataSource配置了多数据源后，自动填充没有用了

### 重现步骤
通过AbstractRoutingDataSource配置多数据源

### 报错信息
无报错

**Comment by miemieYaho** [comment]
自行排查
