### ISSUE TITLE
集成p6spy 日期格式显示问题

### ISSUE THREAD

**Issue by mxpup** [baomidou/mybatis-plus#1568]
### 当前使用版本(必须填写清楚，否则不予处理)

V3.2.0

### 重现步骤

![image](https://user-images.githubusercontent.com/25654465/64102014-a4cf7980-cda1-11e9-8d10-dc10e86138ee.png)

红色为p6sy打印的sql语句，日期字段与黄色不一样，没法直接黏贴到mysql客户端运行
![image](https://user-images.githubusercontent.com/25654465/64102062-bb75d080-cda1-11e9-8520-83139a5a71be.png)

### 报错信息

无

**Comment by miemieYaho** [comment]
去找 p6sy
