### ISSUE TITLE
mybatis plus怎么和generator中updateByPrimaryKey与updateByPrimaryKeySelective

### ISSUE THREAD

**Issue by zhaoyunling** [baomidou/mybatis-plus#1569]
### 当前使用版本(必须填写清楚，否则不予处理)

2.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

更新为空的字段不成功！

### 重现步骤

        ArrayList<String> strings = new ArrayList<>();
        strings.add("3");
        strings.add("4");
        strings.add("6");
        if ("caseAllocation".equals(pageType)) {
            wrapper.eq("id", claimInfo.getId())
                    .in("claim_Status", strings)
                    .eq("delete_flag", 0);
        }
        Integer update = this.baseMapper.updateAllColumnById(claimInfo);

某个字段为“”，不更新为空，保留原来信息

### 报错信息
某个字段为“”，不更新为空，保留原来信息

**Comment by fanlushuai** [comment]
UPDATE_ALL_COLUMN_BY_ID皇城UPDATE_BY_ID 能解决否?

**Comment by qmdx** [comment]
默认策略空null 是被排除的，如果你想更新空null 需要注入mapper 层 选装件  https://mybatis.plus/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6    方法 AlwaysUpdateSomeColumnById
