### ISSUE TITLE
内置的通用mapper和通用service方法执行报错

### ISSUE THREAD

**Issue by giveup** [baomidou/mybatis-plus#1570]
问题有点绕，没办法在标题一句话表达清楚
### 该问题是怎么引起的？
mapper和service继承了通用类，无论是selectById(id)还是getById(id) 运行都会报错。
控制台打印的sql语句
`SQL: SELECT id,birthday,name,bcryptPassword,updateTimestamp,createTimestamp FROM user WHERE id=?`

而我的数据库对应字段为

> 
        <id column="id" jdbcType="INTEGER" javaType="long" property="id"/>
        <result column="name" jdbcType="VARCHAR" javaType="string" property="name"/>
        <result column="bcrypt_password" jdbcType="VARCHAR" javaType="string" property="bcryptPassword"/>
        <result column="birthday" jdbcType="DATE" javaType="date" property="birthday"/>
        <result column="create_timestamp" jdbcType="DATE" javaType="date" property="createTimestamp"/>
        <result column="update_timestamp" jdbcType="TIMESTAMP" javaType="date" property="updateTimestamp"/>

也就是这些通用方法按照实体类去生成了sql语句，而不是按照我配置的映射字段。

已经使用Java config去关闭驼峰命名
`        config.setMapUnderscoreToCamelCase(false);
`
看了看手册文档以及issue，似乎没提到这方面的问题
尝试设置 `        config.setUseActualParamName(true);
        config.setUseColumnLabel(true);`

问题依旧。
### 重现步骤
无

**Comment by miemieYaho** [comment]
描述清楚,或者给出你的复现demo

**Comment by giveup** [comment]
问题是，我用自己的mapper和service去继承通用的mapper和service，然后尝试调用内置的方法时，会报错，错误原因是生成的sql语句是错误的。（实体类和表的列名不一致），但是我已经指定了mapper.xml，并且也配置了列名映射。

**Comment by miemieYaho** [comment]
执行sql和你指定resultmap有什么关系?

**Comment by giveup** [comment]
可能我表达能力是真的不好吧。
我自己写了一个service和mapper，继承了mp内置的IService和和BaseMapper。
然后在控制器调用来自IService的getById方法和BaseMapper的selectById。执行报错，报错原因是sql语句有误，语句有误是因为sql语句的列名是按照实体类生成的。而不是我数据库实际的字段。而我已经配置了resultmap。
我翻了一些官网的手册，似乎没提到需要特别设置（如果要调用IService和BaseMapper的内置方法）

**Comment by miemieYaho** [comment]
你在哪配的resultmap? tablename注解里?如果你告诉mp你赔了resultmap,那select body 是 '*' 而不是具体的各个字段名

**Comment by giveup** [comment]
实体类对应的mapper.xml里面。然后在控制器直接调用来自IService的getById方法和BaseMapper的selectById。
我的本意是，基本CRUD调用通用方法，然后也可以调用自己写的sql语句。
按你的回复是，如果要实现这样的需求，我自己写的sql全部只能select *来查询？

**Comment by miemieYaho** [comment]
你自己写的resultmap要告诉mp用你写的,看注解 `TableName`
