### ISSUE TITLE
主键bug

### ISSUE THREAD

**Issue by diasjda** [baomidou/mybatis-plus#1571]
版本3.1.2
超大bug
用IDWORK自增 发现 数据库1168697202356420610  查出来是1168697202356420600

**Comment by qmdx** [comment]
debug 看看吧，你的问题估计是 js 精度丢失，如否请给出排除过程

**Comment by diasjda** [comment]
是精度丢失问题，昨天发现了，没撤销问题，没想到会回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qmdx"<notifications@github.com&gt;; 
发送时间: 2019年9月3日(星期二) 上午10:30
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "836714531"<836714531@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] 主键bug (#1571)




debug 看看吧，你的问题估计是 js 精度丢失，如否请给出排除过程
