### ISSUE TITLE
分页插件返回值不对

### ISSUE THREAD

**Issue by nzb15555196162** [baomidou/mybatis-plus#1573]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.4

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

分页查询返回信息错误

### 重现步骤
limit 10
start 0
mapper.selectPage(page, warrper)
库里面100条数据
### 报错信息
目前返回100条,total 0

**Comment by yuxiaobin** [comment]
升级到最新版

**Comment by nzb15555196162** [comment]
> 升级到最新版
如果贸然升级会影响其他功能么? 向后兼容性可以保证的么？
