### ISSUE TITLE
批量查询in会在最后的)后自动加上'从而导致sql执行失败

### ISSUE THREAD

**Issue by dwycld** [baomidou/mybatis-plus#1575]
版本3.2.0和3.1.2，其余版本未试验

### 重现步骤
表：
create table test(
  id int(9) not null,
  code varchar(16) not null,
  name varchar(24) null,
 primary key (id)
)

代码：
testMapper.selectList(new QueryWrapper<TestDO>().lambda().in(TestDO::getCode, Arrays.asList("c1")));

### 报错信息
:bad SQL grammar [] .....
WHERE (code IN ('c1'))' at line 1

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by dwycld** [comment]
尴尬了，解决了。自己S&B了
