### ISSUE TITLE
继承了IService接口后，调用IService的方法，导致spring的aop的切面类不执行了。

### ISSUE THREAD

**Issue by 1026170901** [baomidou/mybatis-plus#1576]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用代码生成的service，继承了com.baomidou.mybatisplus.extension.service.IService接口。
然后我的aop切面的切点是 xxx.service.*  。此时调用这个业务service中自定义的方法可以执行到切面类，但是调用com.baomidou.mybatisplus.extension.service.IService中的方法没有执行到aop里面。

### 重现步骤
联系qq:1026170901

### 报错信息
无报错，只是和spring aop 切面冲突了感觉。

**Comment by qmdx** [comment]
1、使用注解方式
2、把 mp 的 service 相关包也切上
