### ISSUE TITLE
关于代码生成器 未找到问题解决办法

### ISSUE THREAD

**Issue by chengx-super** [baomidou/mybatis-plus#1581]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2
` java
StrategyConfig strategyConfig = new StrategyConfig(); 
strategyConfig.setSuperServiceClass(null).setSuperServiceImplClass(null);
`

有没有办法可以实现不继承 extends IService<T>

**Comment by fanlushuai** [comment]
生成器是通过模板文件来生成文件的.所以,你可以通过改变模板的方式.去掉 extends IService的部分.
在实际使用生成器的时候,个人建议.你copy出来内置的模板.进行自定义.使得模板的注释风格还有一些format符合你自己项目的需求

**Comment by chengx-super** [comment]
谢谢
