### ISSUE TITLE
datetime转换为localtime,查询报错

### ISSUE THREAD

**Issue by Clierbin** [baomidou/mybatis-plus#1582]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用generator生成的bean类 ,数据库时间类型为datetime 的被转换为localtime,但是在
查询数据的时候就会报错,无法转换

**Comment by miemieYaho** [comment]
看配置,看文档
