### ISSUE TITLE
用过一次这框架后，决定把这框架列入黑名单，理由如下

### ISSUE THREAD

**Issue by fengyts** [baomidou/mybatis-plus#1583]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1版本

### 重现步骤
你的框架自带的CRUD接口在sql自动填充字段的情况下，在有的场景不需要自动填充的字段，怎么忽略，比如updateById, selectById, updateByOrderNo等等，Id, orderNo字段本来就是在数据库中是唯一的，为什么还要非的加上那些自动填充的字段（完全是多此一举），害得我根据唯一字段去更新的时候还要自己写个sql,然后加上@SqlParser(filter=true)才能行。坑的我怀疑人生。就这框架的灵活性，拉入黑名单妥妥的。
这框架就做些小型简单的项目用用还行，复杂业务场景，完全没法胜任。

**Comment by miemieYaho** [comment]
不用拉倒,还跑来提issue?有病?

**Comment by qmdx** [comment]
Too Young Too Simple

**Comment by VampireAchao** [comment]
推荐使用`nb-orm`

**Comment by miozus** [comment]
"框架自带的CRUD接口在sql自动填充字段的情况下，在有的场景不需要自动填充的字段，怎么忽略"

2019年9月的问题，2023年3月依旧存在，不能绕过自动填充功能，它是全局的。
