### ISSUE TITLE
3.1.2版本UpdateWrapper更新问题

### ISSUE THREAD

**Issue by guangshuowang** [baomidou/mybatis-plus#1585]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
根据id更新指定字段，使用mapper.update(null,updatewraper)方法

null
### 重现步骤
按照官网文档使用这种方法：
mapper.update(
    null,
    Wrappers.<User>lambdaUpdate()
       .set(User::getAge, 3)
       .set(User::getName, "mp")
       .set(User::getEmail, null) //把email设置成null
       .eq(User::getId, 2)
);
第一个参数为null的时候就会报空指针
我的实体对象中大部分属性的更新策略都是IGNORED
空指针问题可以把第一个参数使用new新对象的方式解决，但是会把所有字段都set出来，由于new的对象属性都是空都会set成null，这把原数据都擦除也不对

### 报错信息
![1](https://user-images.githubusercontent.com/17266306/64305882-6c0eea80-cfc3-11e9-9293-7ce01882a83b.jpg)
![0](https://user-images.githubusercontent.com/17266306/64305905-85179b80-cfc3-11e9-9e2c-c90f03c28f71.png)
![2](https://user-images.githubusercontent.com/17266306/64305907-8779f580-cfc3-11e9-8986-a1ba98006624.png)

**Comment by miemieYaho** [comment]
检查你的mp版本是不是 3.1.2 ,如果是就给出你的复现demo

**Comment by guangshuowang** [comment]
我试过了，单独拿出来测试mp版本3.1.2和3.2.0都没有问题，数据库连接也换了druid的ConnectionProxyImpl和HikariProxyConnection，或者JDBC4Connection都没有问题，就是在我项目里有问题，哎时间紧没空找了，只能绕道而行

**Comment by guangshuowang** [comment]
试过了3.1.2和3.2.0都没有问题，单独拿出来测试的，就是在我项目里有问题，我debug进去是这样的
![update](https://user-images.githubusercontent.com/17266306/64399507-46551480-d09b-11e9-84e8-9868c28acbcc.jpg)
这个param1在后面是要用的，但这里解析之后就是空，能看出哪里原因吗

**Comment by miemieYaho** [comment]
param1 就是入参第一个, 等于 et
