### ISSUE TITLE
是否覆盖文件疑问

### ISSUE THREAD

**Issue by pizhihui** [baomidou/mybatis-plus#1587]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
GlobalConfig gc = new GlobalConfig();
gc.setFileOverride(false);   // 是否覆盖文件

这里只能对 dao，domain 和 xml 一项的开关。应该可以分开设置。比如我只想重新生成 domain，因为 dao 和 xml里我可能写了自己代码。

**Comment by qmdx** [comment]
暂不支持挨个配置

**Comment by fanlushuai** [comment]
支持的不是那么明显.但是可以实现.添加InjectionConfig,setIFileCreate,为自己的IFileCreate实现.自己的IFileCreate实现里面就可以完全的把握你说的是否覆盖.

**Comment by qmdx** [comment]
up
