### ISSUE TITLE
希望新增功能：mysql  json字段类型查询映射到实体类

### ISSUE THREAD

**Issue by yuhou615** [baomidou/mybatis-plus#1589]
### 当前使用版本(必须填写清楚，否则不予处理)

最新版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?
 希望加一个功能

### 重现步骤

mysql  json字段类型查询自动映射到实体类或映射成json 对象。

### 报错信息

无

**Comment by qmdx** [comment]
查看文档字段类型部分

**Comment by zuosc** [comment]
https://mybatis.plus/guide/typehandler.html
