### ISSUE TITLE
saveOrUpdate逻辑缺陷

### ISSUE THREAD

**Issue by Euthpic** [baomidou/mybatis-plus#1590]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？

目前你们的saveOrUpdate是根据主键来判断数据是否存在,但是正常情况下这都应该交由mysql判断(通过主键约束或者unique key约束),否则新建一个pojo赋值时一般都不会set主键的(要set的话还得自己额外查一次),这样每次使用你们的saveOrUpdate都是当成新数据去insert,非常不合理.
建议用on duplicate key update完善该逻辑

**Comment by miemieYaho** [comment]
不符合你需求你就自己实现,mp只能满足大部分人

**Comment by yuenke** [comment]
saveOrUpdate这个方法名的确有歧义，叫saveOrUpdateById 或许更合适

**Comment by ninjachen** [comment]
saveOrUpdate名字没啥问题，都是这么用的，update肯定是根据主键
