### ISSUE TITLE
 麻烦看下这个问题

### ISSUE THREAD

**Issue by Euthpic** [baomidou/mybatis-plus#1593]
> ### 当前使用版本(必须填写清楚，否则不予处理)
> com.baomidou mybatis-plus-boot-starter 3.1.1
> 麻烦看下这个问题
> https://gitee.com/baomidou/mybatis-plus/issues/IQ437#note_1740107

这么挫的实现,应该早些看到这条issue,不该入坑

**Comment by miemieYaho** [comment]
挫?你怕是活在梦里哦,希望你就用这一次mp,以后都不要用了.拜拜
