### ISSUE TITLE
mysql数据库自定义枚举对应字段类型是TINYINT时，匹配不上

### ISSUE THREAD

**Issue by haochencheng** [baomidou/mybatis-plus#1595]
使用通用枚举， https://mybatis.plus/guide/enum.html#%E4%B8%80%E3%80%81jackson
数据库mysql ，当枚举对应的字段在数据库中 是 INT时 正常。可以匹配
但是当字段类型是TINYINT时 无法匹配  因为
相关源码
MybatisEnumTypeHandler
![image](https://user-images.githubusercontent.com/20943919/64363694-d9626000-d043-11e9-891a-9314d6e486c4.png)
EnumUtils
![image](https://user-images.githubusercontent.com/20943919/64363809-19c1de00-d044-11e9-8c2b-031b92abfc7c.png)

版本：
```
 <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus</artifactId>
                <version>3.2.0</version>
            </dependency>

```

**Comment by haochencheng** [comment]
![image](https://user-images.githubusercontent.com/20943919/64397207-0a1db600-d093-11e9-88b5-f4171e093e3b.png)
建议使用 BigDecimal.valueOf()方法  有缓存

**Comment by miemieYaho** [comment]
看文档

**Comment by haochencheng** [comment]
文档中并没有相应的说明

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/faq.html#%E5%AD%97%E6%AE%B5%E7%B1%BB%E5%9E%8B%E4%B8%BA-bit-%E3%80%81-tinyint-1-%E6%97%B6%E6%98%A0%E5%B0%84%E4%B8%BA-boolean-%E7%B1%BB%E5%9E%8B
