### ISSUE TITLE
分页查询数据order by 在SELECT TOP 100 PERCENT失效

### ISSUE THREAD

**Issue by weixiao5** [baomidou/mybatis-plus#1596]
### 当前使用版本(必须填写清楚，否则不予处理)

目前使用最新版本 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

数据库使用：sql server 2017版本，使用分页和条件构造器后，order by id desc失效，依旧返回id ase 排序

### 重现步骤

` Page<OrderEntity> page = new Page<OrderEntity>(pageNum, pageSize);
        IPage<OrderEntity> ipages = orderService.page(page, new QueryWrapper<OrderEntity>().eq("user_token", userToken));
        List<OrderEntity> tempListStrDb = ipages.getRecords();
        if (tempListStrDb == null || tempListStrDb.size() == 0) {
            return new CallbackStatusDto<List<OrderEntity>>(1730, "查询信息数据为空！", null);
        }
`

### 报错信息

SELECT TOP 100 PERCENT ROW_NUMBER() OVER (ORDER BY id DESC) as __row_number__, id,transido,apiouttradeno,outtradeno,orderstatus,machine_code AS machineCode,machine_name AS machineName,machine_model_name AS machineModelName,machine_model_code AS machineModelCode,service_name AS serviceName,service_code AS serviceCode,service_money AS serviceMoney,service_cmd AS serviceCmd,service_run_time AS serviceRunTime,service_remark AS serviceRemark,money,pay_group_config_code AS payGroupConfigCode,pay_username AS payUsername,pay_users AS payUsers,pay_type AS payType,pay_mode AS payMode,pay_code AS payCode,pay_quiturl AS payQuiturl,pay_config AS payConfig,pay_res_xml AS payResXml,pay_notify_time AS payNotifyTime,pay_refund_status AS payRefundStatus,pay_refund_transido AS payRefundTransido,pay_refund_remark AS payRefundRemark,gateway_start_time AS gatewayStartTime,gateway_status AS gatewayStatus,gateway_status_remark AS gatewayStatusRemark,gateway_remark AS gatewayRemark,gateway_serial_number AS gatewaySerialNumber,gateway_end_time AS gatewayEndTime,gateway_code AS gatewayCode,user_token AS userToken,feerate_user AS feerateUser,feerate_agent AS feerateAgent,feerate_gateway AS feerateGateway,money_user AS moneyUser,money_agent AS moneyAgent,money_gateway AS moneyGateway,pay_url AS payUrl,create_time AS createTime,update_time AS updateTime,status,remark,agent_uuid AS agentUuid,user_uuid AS userUuid,system_uuid AS systemUuid FROM wash_order WHERE user_token = c5f32067d21db05d806b923bd347099e ORDER BY id DESC) SELECT * FROM selectTemp WHERE __row_number__ BETWEEN 1 AND 10 ORDER BY __row_number__

**Comment by miemieYaho** [comment]
so ? 如何改进?

**Comment by weixiao5** [comment]
SELECT TOP 100 PERCENT 可以建议搞一个配置文件参数，是否添加数据显示（TOP 100 PERCENT）  在分页中其实意义不大

**Comment by weixiao5** [comment]
另外网上说 SELECT TOP 99.9999999 PERCENT 改成这个就可以 我测试 确实生效了

**Comment by miemieYaho** [comment]
来改它  https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/pagination/dialects/SQLServer2005Dialect.java

**Comment by qmdx** [comment]
SQLServer 每一个版本的分页都不一样很无语，你可以 PR 一个 SQLServer2017Dialect
