### ISSUE TITLE
remove and saveBatch 第二个没有提交事务

### ISSUE THREAD

**Issue by xgs0921** [baomidou/mybatis-plus#1597]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/48511813/64399502-4523e780-d09b-11e9-91a5-203e1dce118d.png)
![image](https://user-images.githubusercontent.com/48511813/64399520-4d7c2280-d09b-11e9-88ae-826eb3350509.png)

### 重现步骤
 this.remove(Wrappers.<Setting>query().lambda().eq());
 this.saveBatch(list, list.size());

### 报错信息

Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3472a51e] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@633694213 wrapping com.mysql.cj.jdbc.ConnectionImpl@94a987f] will not be managed by Spring
==>  Preparing: DELETE FROM t_setting WHERE (setting_group = ?) 
==> Parameters: Website(String)
<==    Updates: 0
Committing JDBC Connection [HikariProxyConnection@633694213 wrapping com.mysql.cj.jdbc.ConnectionImpl@94a987f]
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3472a51e]
JDBC Connection [HikariProxyConnection@203426118 wrapping com.mysql.cj.jdbc.ConnectionImpl@94a987f] will not be managed by Spring
==>  Preparing: INSERT INTO t_setting ( id, created_at, setting_group, setting_value, setting_key, version, updated_at ) VALUES ( ?, ?, ?, ?, ?, ?, ? ) 
==> Parameters: 1169814750874923009(Long), 1567740545378(Long), Website(String), https://open.weibo.com/wb(String), xmlns(String), 0(Long), 1567740545378(Long)
Rolling back JDBC Connection [HikariProxyConnection@203426118 wrapping com.mysql.cj.jdbc.ConnectionImpl@94a987f]

**Comment by miemieYaho** [comment]
? 描述清楚, batch操作是一个新的sqlsession

**Comment by xgs0921** [comment]
不好意思 我发现是hikari配置问题导致的。我已经关闭了。不好意思

miemieYaho <notifications@github.com> 于2019年9月6日周五 下午12:12写道：
