### ISSUE TITLE
建议 主键IdType再增加一个 ID_WORKER_STRING的选项，以便支持 String 类型的主键

### ISSUE THREAD

**Issue by songhaoying** [baomidou/mybatis-plus#16]
建议 主键IdType再增加一个 ID_WORKER_STRING的选项，以便支持 String 类型的主键。
经常使用oracle数据库，id_word默认为long型，oracle表的主键只能设为number型。
而在进行查询的时候oracle又默认转成了科学计数法，到view层时看到的值跟实际主键值不一致。

如果oracel主建为String （varchar)型的话，便没有这个问题。

**Comment by songhaoying** [comment]
/* 自定义 ID */
			if (StringUtils.checkValNull(idValue)) {
				if (tableInfo.getIdType() == IdType.ID_WORKER) {
					metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.getId());
				} else if (tableInfo.getIdType() == IdType.UUID) {
					metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.get32UUID());
				} **else if(tableInfo.getIdType()==IdType.ID_WORKER_STRING){
					metaObject.setValue(tableInfo.getKeyProperty(), String.valueOf(IdWorker.getId()));
				}**
			}

**Comment by Caratacus** [comment]
没有这个必要,字符串可以选择使用UUID
