### ISSUE TITLE
mybatis-plus 生成代码插件问题

### ISSUE THREAD

**Issue by Heqi1234** [baomidou/mybatis-plus#1600]
mybatis-plus.version=3.2.0

这个代码生成插件产生的 BaseResultMap 中没有JdbcType，请问那么我要生成的mapper.xml中有JdbcType的话，我要怎么配置呢？
![image](https://user-images.githubusercontent.com/30340479/64412158-60a1e900-d0c1-11e9-9a69-f437ac2326b3.png)

**Comment by qmdx** [comment]
mybatis 底层是自动识别的，绝大多数情况不需要设置，如果你要设置可以手敲 OR 修改生成器模板
