### ISSUE TITLE
saveBatch等批量方法没打印sql日志

### ISSUE THREAD

**Issue by fengbindev** [baomidou/mybatis-plus#1604]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用了p6spy来打印sql日志，但是saveBatch等批量方法没打印sql日志

### 重现步骤

`
    private void syncBaseConfigCache() {
        List<Config> configs = new ArrayList<>();
        QuellaClassContentHandler.baseConfigCache.forEach((code, baseConfig) -> {
            Config config = configService.getOne(Wrappers.<Config>lambdaQuery().eq(Config::getCode,code));
            if (ObjectUtil.isNull(config)){
                config = new Config();
                config.setCode(code);
                config.setName(baseConfig.getName());
                config.setMemo(baseConfig.getMemo());
                configs.add(config);
            }
            cacheManager.getCache(Constant.BASE_CONFIG_CACHE).put(code, JSONUtil.toJsonStr(baseConfig));
        });
        configService.saveBatch(configs);
    }

`

**Comment by fanlushuai** [comment]
decorator.datasource.p6spy.multiline=true  试试

**Comment by nieqiurong** [comment]
excludecategories的配置把batch删掉.

**Comment by qmdx** [comment]
spy.properties 配置：
如果你想看到批量日志， excludecategories 属性去掉 batch 配置，最后一条重复正常操作打印重复因为 flush 导致正常。

**Comment by decadestory** [comment]
解决了没！saveBatch 3条 出现四个单条insert语句，最后两条重复，没有批量insert的语句
