### ISSUE TITLE
关于插入更新时使用主键时遇到的问题

### ISSUE THREAD

**Issue by LacusCon** [baomidou/mybatis-plus#161]
你好，感谢提供了如此方便的插件。
现在我在使用插件的时候遇到了几个问题。
使用场景：
 1.数据库设计了delete_flag
 2.使用了多主键
 3.手动添加TableID给Entity中的多主键
遇到的问题：
  1.生成的时候不支持多主键
  2.使用insertOrUpdate的时候会报错，因为检查不到多主键的重复
  3.插入的内容会出错，因为主键填值不对
  4.想使用手动方法来selectCount后，判断是insert还是update，但是有delete_flag在，所以有内容查不出来，应该update的内容变成了insert

**Comment by huayanYu** [comment]
不支持联合主键

建议：实在有联合主键的需求的表，自行写sql。
