### ISSUE TITLE
mybatis-plus能不能like相关方法能有一个不区分大小写的开关

### ISSUE THREAD

**Issue by mifashion** [baomidou/mybatis-plus#1610]
### 当前使用版本(必须填写清楚，否则不予处理)
3.x

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
现在默认是区分大小写的，想要一个区分大小写的开关，这样我就不用重新去在xml中写了，还有就是能不能尽快实现多表关联查询

### 报错信息
没有报错

**Comment by miemieYaho** [comment]
不支持,永远不会实现连表

**Comment by mifashion** [comment]
为什么

**Comment by mifashion** [comment]
> 不支持,永远不会实现连表

为什么
