### ISSUE TITLE
mysql 字段压缩处理问题

### ISSUE THREAD

**Issue by xlchao** [baomidou/mybatis-plus#1613]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

你好，我这边有一个需求是要对数据库某个很大的字段进行压缩处理，即插入更新的时候使用COMPRESS(content)函数，查询的时候使用UNCOMPRESS（content） as content 处理，有什么比较优雅的方式实现吗？只能自己手写sql?

**Comment by fanlushuai** [comment]
https://mp.baomidou.com/guide/typehandler.html

**Comment by qmdx** [comment]
up 自定义 typehandler
