### ISSUE TITLE
注解MapperScan导致出现多个service层bean

### ISSUE THREAD

**Issue by 1511pzz** [baomidou/mybatis-plus#1614]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
当@MapperScan注解的包范围过大包含service层时, 该注解会给service接口也生成一个spring bean
@MapperScan("com.app.modules")                     // 异常, 一个Iservice, 一个serviceImpl
@MapperScan("com.app.modules.**.mapper")   // 正常, 一个serviceImpl

**Comment by miemieYaho** [comment]
去找mybatis
