### ISSUE TITLE
mybatisplus分页在dubbo中失效

### ISSUE THREAD

**Issue by ciweigg2** [baomidou/mybatis-plus#1615]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用springcloudalibaba集成dubbo和mybatisplus 传入xx页 xx条后显示全部记录

### 重现步骤
请求参数
{
  "object": {
    "userId": null,
    "userName": null,
    "createTime": null
  },
  "size": 1,
  "current": 2
}
返回结果所有记录 已经配置分页插件
@Bean
public PaginationInterceptor paginationInterceptor() {
    return new PaginationInterceptor();
}

### 报错信息
无报错信息

**Comment by miemieYaho** [comment]
自行排查
