### ISSUE TITLE
代码生成实体类，批注换行导致生成的代码报错

### ISSUE THREAD

**Issue by authorZhao** [baomidou/mybatis-plus#1616]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
代码生成时，生成swagger2注解
```java
@ApiModelProperty(value = "博客id

")
    @TableId(value = "blog_id", type = IdType.AUTO)
    private Integer blogId;
```

### 重现步骤
1.数据库字段批注换行
2.生成代码实体类时配置swagger2注解

### 报错信息
无报错，但是生成的实体类会报错

**Comment by qmdx** [comment]
请先查看你的表注解是否存在换行

**Comment by authorZhao** [comment]
我的表是navicat创建的，mysql5.7，里面确实存在换行，我目前解决解决办法是手工替换里面的换行，希望能默认实现
```java
public class MyAutoGenerator extends AutoGenerator {

    @Override
    protected List<TableInfo> getAllTableInfoList(ConfigBuilder config) {
        List<TableInfo> tableInfos =  super.getAllTableInfoList(config);
        tableInfos.forEach(t->{
            t.getFields().forEach(f->{
                if(org.apache.commons.lang3.StringUtils.isNotBlank(f.getComment())) {
                    String comment = f.getComment();
                    comment = comment.replaceAll("\r\n" , "");
                    f.setComment(comment);
                }
            });
        });
        return tableInfos;
    }


}
```

**Comment by authorZhao** [comment]
> 请先查看你的表注解是否存在换行

我的表是navicat创建的，mysql5.7，里面确实存在换行，我目前解决解决办法是手工替换里面的换行，希望能默认实现

public class MyAutoGenerator extends AutoGenerator {

    @Override
    protected List<TableInfo> getAllTableInfoList(ConfigBuilder config) {
        List<TableInfo> tableInfos =  super.getAllTableInfoList(config);
        tableInfos.forEach(t->{
            t.getFields().forEach(f->{
                if(org.apache.commons.lang3.StringUtils.isNotBlank(f.getComment())) {
                    String comment = f.getComment();
                    comment = comment.replaceAll("\r\n" , "");
                    f.setComment(comment);
                }
            });
        });
        return tableInfos;
    }


}

**Comment by qmdx** [comment]
默认不处理这种事情，报错反而有利于发现问题及时纠正
