### ISSUE TITLE
如果不是Spring系列项目 如何集成 mybatis-plus?

### ISSUE THREAD

**Issue by dcwang1989** [baomidou/mybatis-plus#1617]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

非Spring环境下 搭建 mybatis-plus 没有相关文档

**Comment by yansheng836** [comment]
这个问题有解吗？不是Spring系列项目能使用mybatis-plus吗?

**Comment by sunyaf** [comment]
我也想问，不是spring 项目怎么集成

**Comment by qmdx** [comment]
@yansheng836 @sunyaf  查看文档
