### ISSUE TITLE
Mybatis Plus 怎么使用APO的方式在mapper层进行数据源切换？

### ISSUE THREAD

**Issue by 18818542910** [baomidou/mybatis-plus#1618]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis plus 3.2.0 版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无法在mapper 层使用自定义注解进行数据源切换

**Comment by qmdx** [comment]
https://mybatis.plus 多数据源部分查看
