### ISSUE TITLE
mybatis-plus 代码生成器必须指定模板引擎吗，如何禁用模板引擎

### ISSUE THREAD

**Issue by 1than** [baomidou/mybatis-plus#1619]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

**Comment by fanlushuai** [comment]
不使用就禁用了。不然不可能。

**Comment by qmdx** [comment]
必须有不指定默认依赖 velocity

**Comment by 1than** [comment]
> 必须有不指定默认依赖 velocity

就是说不管我有没有用到 都要在模版引擎里加入velocity依赖是吗

**Comment by yuxiaobin** [comment]
> > 必须有不指定默认依赖 velocity
> 
> 就是说不管我有没有用到 都要在模版引擎里加入velocity依赖是吗

没用到可以不用引入依赖。
你可以不依赖，或者依赖的scope=test, 仅在unit test时使用，这样依赖不会进主项目
