### ISSUE TITLE
使用乐观插件和自定义Interceptor中et和param1不一致的问题

### ISSUE THREAD

**Issue by lxy1693** [baomidou/mybatis-plus#1622]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
（这可能算不上bug，希望能在文档上标下免得后面的人再遇到同样的问题）；

1.使用mp的乐观锁插件；
2.自定义mybatis拦截器实现公共字段填充；

3.出现的问题填充的字段不生效，执行的sql没有上图两个字段；
4.最终结果更新操作的公共字段填充没有作用；

和正常填充的过程比较和查阅issue发现：
正常填充的：param1和et一样
不能填充的：param1是自定义的某个对象，et是hashMap,自定义拦截器更新param1时，et不会变

![image](https://user-images.githubusercontent.com/25860264/65111516-ee110180-da0e-11e9-95aa-f872d0d47d1c.png)
### 报错信息
经过调用过程查看，在mp的乐观锁实现的拦截中对et进行了处理并且改变了et的数据结构；
可以针对这个情况在自定义拦截器进行处理来解决填充不成功的问题

![image](https://user-images.githubusercontent.com/25860264/65111482-d0439c80-da0e-11e9-8cd0-a2eed9a15f44.png)

**Comment by miemieYaho** [comment]
就是这样的

**Comment by yuxiaobin** [comment]
暂时的解决方案： 把你的拦截器放在乐观锁后面加载，后加载先执行

等后面把乐观锁的实现改进一下，尽量不改变结构（对象变map）
