### ISSUE TITLE
更新字段的时候不会根据加入的@TableField(update = "now()", fill = FieldFill.INSERT_UPDATE)注解去更新时间

### ISSUE THREAD

**Issue by Linshowtime** [baomidou/mybatis-plus#1623]
### 当前使用版本(必须填写清楚，否则不予处理)
version：3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用 
default boolean update(Wrapper<T> updateWrapper) {
        return update(null, updateWrapper);
    }
该方法的时候，更新字段的时候不会根据加入的@TableField(update = "now()", fill = FieldFill.INSERT_UPDATE)注解去更新时间

**Comment by miemieYaho** [comment]
自动填充是填充到entity,你entity都没有没法填充
