### ISSUE TITLE
在执行条件构造器select方法时会忽略@TableId和@TableField的注解

### ISSUE THREAD

**Issue by Pxxxiang** [baomidou/mybatis-plus#1624]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在执行条件构造器select方法时会忽略@TableId和@TableField的注解

### 重现步骤
@Data
@TableName("px_user")
public class User {

    @TableId("user_id")
    private Long id;

    @TableField("name")
    private String userName;

然后在
@Test
    public void userSelectByWrapper1(){
        QueryWrapper<User> queryWrapper = new QueryWrapper<>();
        QueryWrapper<User> query = Wrappers.query();
        query.like("name","头").lt("age",13).select("user_id ","name ");
        List<User> userList = userMapper.selectList(query);
        userList.forEach(System.out::println);
    }
运行日志：
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5328a9c1] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@1247127272 wrapping com.mysql.jdbc.JDBC4Connection@8c46918] will not be managed by Spring
==>  Preparing: SELECT user_id ,name FROM px_user WHERE (name LIKE ? AND age < ?) 
==> Parameters: %头%(String), 13(Integer)
<==    Columns: user_id, name
<==        Row: 6, 光头强
<==        Row: 1170531422176092161, 光头
<==      Total: 2
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5328a9c1]
null
null
导致实体类无法接收到结果，没有报错却返回空值
然后在把条件移除试一次：
 @Test
    public void userSelectByWrapper1(){
        QueryWrapper<User> queryWrapper = new QueryWrapper<>();
        QueryWrapper<User> query = Wrappers.query();
        query.select("user_id ","name ");
        List<User> userList = userMapper.selectList(query);
        userList.forEach(System.out::println);
    }
运行日志：
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@36bc415e] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@704387627 wrapping com.mysql.jdbc.JDBC4Connection@4d0b0fd4] will not be managed by Spring
==>  Preparing: SELECT user_id ,name FROM px_user 
==> Parameters: 
<==    Columns: user_id, name
<==        Row: 1, Jone
<==        Row: 2, Jack
<==        Row: 3, Tom
<==        Row: 4, Sandy
<==        Row: 5, Billie
<==        Row: 6, 光头强
<==        Row: 12, 苏钊
<==        Row: 123, 123
<==        Row: 1232, 123
<==        Row: 1170531422176092161, 光头
<==        Row: 1170531600786317313, 光头
<==        Row: 1170532611315769345, 光头
<==        Row: 1170534880639778818, 头
<==        Row: 1170535823943004162, 向西
<==        Row: 1170537855122755585, 向北
<==        Row: 1170539156221018114, 向南
<==      Total: 16
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@36bc415e]
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null

还是一样也无法接收。

后面我试了一次在select中添加As id和As userName：
 @Test
    public void userSelectByWrapper1(){
        QueryWrapper<User> queryWrapper = new QueryWrapper<>();
        QueryWrapper<User> query = Wrappers.query();
        query.like("name","头").lt("age",13).select("user_id as id","name as userName");
        List<User> userList = userMapper.selectList(query);
        userList.forEach(System.out::println);
    }
运行日志：
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5328a9c1] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@1247127272 wrapping com.mysql.jdbc.JDBC4Connection@8c46918] will not be managed by Spring
==>  Preparing: SELECT user_id as id,name as userName FROM px_user WHERE (name LIKE ? AND age < ?) 
==> Parameters: %头%(String), 13(Integer)
<==    Columns: id, userName
<==        Row: 6, 光头强
<==        Row: 1170531422176092161, 光头
<==      Total: 2
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5328a9c1]
User(id=6, userName=光头强, age=null, email=null, b=null, c=null)
User(id=1170531422176092161, userName=光头, age=null, email=null, b=null, c=null)

才可以接收到数据

### 报错信息
无

**Comment by miemieYaho** [comment]
入参是 string 的自己处理,和entity注解没任何关系
