### ISSUE TITLE
mybatis plus @select()和baseMapper 中的SQL都可以执行，但是放在XML中则无法找到

### ISSUE THREAD

**Issue by 18818542910** [baomidou/mybatis-plus#1626]
### 当前使用版本(必须填写清楚，否则不予处理)

   <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

**在Mapper.xml中自己定义一个select 调用报找不到映射**
### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.example.demo.mapper.WhOverallrcvandshpMapper.testSelect

**Comment by miemieYaho** [comment]
看文档

**Comment by 18818542910** [comment]
所有的配置都有配置，但是目前就是无法实现，我也觉得很奇怪

**Comment by 18818542910** [comment]
mybatis-plus:
  mapper-locations: classpath*:com/example/demo/mapper/xml/WhOverallrcvandshpMapper.xml
  typeAliasesPackage: com.example.demo.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

**Comment by 18818542910** [comment]
@MapperScan("com.example.demo.mapper")

**Comment by 191824852** [comment]
这个是怎么解决的呢，我也遇见这个问题了

**Comment by wangsenyan** [comment]
我也遇到了，用的3.4.1
