### ISSUE TITLE
update 更新字段为null的时候失败

### ISSUE THREAD

**Issue by fanzunying** [baomidou/mybatis-plus#1627]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
更新的时候，如果字段为null值，sql语句直接就忽略字段的更新，和你们的方法注释不符合。

### 重现步骤
`VillageEntity villageEntity = villageMapper.selectOne(new QueryWrapper<VillageEntity>().last("limit 1"));
        villageEntity.setVillageName(null);
        int id = villageMapper.update(villageEntity, new UpdateWrapper<VillageEntity>().eq("ID", villageEntity.getId()));
        System.out.println("id = " + id);`

### 报错信息
sql语句如下：
第一个查询语句的sql语句为：SELECT ID,VILLAGE_ID,VILLAGE_NAME,IS_DELETED,VERSION,CREATOR,CREATE_TIME,UPDATER,UPDATE_TIME,COMMENTS FROM t_village WHERE IS_DELETED=false limit 1 ；
第二个更新sql的语句为：
UPDATE t_village SET VILLAGE_ID=?, VERSION=?, CREATOR=?, CREATE_TIME=?, UPDATER=?, UPDATE_TIME=? WHERE IS_DELETED=false AND ID = ? AND VERSION = ? 

没有了set VILLAGE_NAME

**Comment by miemieYaho** [comment]
去看文档

**Comment by fanzunying** [comment]
看了文档，你文档上面所描述的，和我得到的sql语句不符合，文档上面写的是可以设置为null，但实际上并没有，

**Comment by miemieYaho** [comment]
```java
/**
     * 根据 whereEntity 条件，更新记录
     *
     * @param entity        实体对象 (set 条件值,可以为 null)
     * @param updateWrapper 实体对象封装操作类（可以为 null,里面的 entity 用于生成 where 语句）
     */
```
可以为 null 指的 entity

**Comment by jijunpeng** [comment]
我也从文档里面没有看明白，想要更新整条记录，单独设置某个字段为null，不知道怎么写代码

**Comment by jijunpeng** [comment]
试了一下，可以这样设置字段为null 值
```java
villageMapper.update(villageEntity, new LambdaUpdateWrapper<VillageEntity>()
    .set(VillageEntity::getVillageName, null)
    .eq("ID", villageEntity.getId()));
```
