### ISSUE TITLE
关于设置排序条件的问题

### ISSUE THREAD

**Issue by wangzhanxu** [baomidou/mybatis-plus#1628]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
最近搭建项目框架技术选型采用了MP，之前只是简单了解过，现在想在使用的层面上稍微深入一些，进行一些项目级别的封装。
在设置排序条件问题上想咨询一下，现在Page类和QueryWrapper/LamdaQueryWrapper都支持设置排序条件，出于什么原因作者在Page类里支持设置排序条件呢？我目前能想到的原因可能是：用户在不使用Wrapper对象进行查询时，可以通过Page设置排序条件，不知道是否正确。
另外，我比较关注的是，在未来的版本迭代中，Page设置排序条件是否一直会支持？因为我前面说了目前在进行项目级别的二次封装，设置排序条件，想采用Page对象。

**Comment by miemieYaho** [comment]
Page 方式适合前端传字段,wrapper适合固定字段
