### ISSUE TITLE
无法打印执行的sql语句

### ISSUE THREAD

**Issue by zzyto88** [baomidou/mybatis-plus#163]
连接池：com.alibaba.druid.pool.DruidDataSource
数据库：oracle
mybatis-plus版本：2.1.2

打印出来是这样：
 Time：16 ms - ID：cn.com.reading.orm.system.DictMapper.findList
 Execute SQL：
    oracle.jdbc.driver.T4CPreparedStatement@65adea6c

**Comment by qmdx** [comment]
数据连接池问题，不知道是否解决

**Comment by cy1ng** [comment]
我也遇到这个问题  是连接池问题吗？请问怎么解决呢？ @zzyto88 @qmdx
