### ISSUE TITLE
${ew.customSqlSegment}可以在一个查询中使用多个吗，自测发现会最后一个wrapper会覆盖掉前面所有的wrapper

### ISSUE THREAD

**Issue by chenm1xuexi** [baomidou/mybatis-plus#1632]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本为3.1.0
希望${ew.customSqlSegment}可以在一个sql中使用多个，类似于
select * from user ${ew.customSqlSegment}
union
select * from user ${ew1.customSqlSegment}

感觉这样的场景会很常见，如果系统稍微复杂一点，希望大佬能够推出这种功能

**Comment by miemieYaho** [comment]
不支持,手撸xml

**Comment by yuxiaobin** [comment]
final String customerSql = ew.getCustomerSqlSegment();
final String customerSql1 = ew1.getCustomerSqlSegment();

select * from user ${customerSql}
union
select * from user ${customerSql1}

**Comment by chenm1xuexi** [comment]
这还是通过自定义sql来编写呀，我的意思是能否使用Java的wrapper包装器来实现

**Comment by shushengming** [comment]
现在能使用多个ew在union的sql语句中么?

**Comment by chenzhenjia** [comment]
这个功能刚需啊，我看了3.1 的版本还有个paramAlias 参数,到了3.2 就没了。但是3.1 的paramAlias值根本没有setter方法

**Comment by yuxiaobin** [comment]
mybatis原生include支持 复用sql
```
<sql id="innerConditionSql">
  and column1=${a}
</sql>

<select id="myselect1">
select * from tbl_a
where column_x=1
<include refid="innerConditionSql">
   <property name="a" value="#{a}"/>
</include>
</select>
```
