### ISSUE TITLE
分页pags为long类型

### ISSUE THREAD

**Issue by zIronX** [baomidou/mybatis-plus#1634]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
    <version>3.2.0</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
因为id是long类型用IDwork生成，long值过大导致json转换数值失真,因此我们统一用拦截器把long类型在json转换时为String,但是因为pages的类型也是long导致pages也会转化为String这样前端在分页时又要把pages转化一下，能否把pages改回int，或者如何解决这个问题

**Comment by qmdx** [comment]
文档问题部分
