### ISSUE TITLE
如何提取获取id

### ISSUE THREAD

**Issue by lwq1003** [baomidou/mybatis-plus#1635]
当前MP的Id是在插入数据时自动生成的，实际应用场景中，有提前获取id的需求，例如一张单据，新增后，打开单据页面，填写几个字段，然后上传附件，这时候，单据id并没有生成，但是附件作为单据的附属物，需要单据id去进行数据库写入。

请问mp是否有方法可以在上面这种场景下，提前获取基于雪片算法生成的id，用于附件数据的写入？另外，如有这样的方法，底层处理时，已经指定了单据id，insert单据时，会直接使用，还是会重新生成？

**Comment by miemieYaho** [comment]
insert之前setid

**Comment by lwq1003** [comment]
大哥，你只回复了后面的一个小问题，前面的关键问题，是否有方法对外的公用方法来生成id？不会是自己再去实现一遍id的生成算法吧，即使这样做，也有很大可能是冲突

**Comment by miemieYaho** [comment]
idwork.getid

**Comment by lwq1003** [comment]
多谢多谢，问题解决
