### ISSUE TITLE
Mybatis saveOrUpdateBatch  批量入库，异常时并未抛出异常

### ISSUE THREAD

**Issue by 303489429** [baomidou/mybatis-plus#1636]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

入口方法：
        log.info(" rs:{}", JSONObject.toJSONString(rs));
        //批量入库
        boolean b = service.saveOrUpdateBatch(rs);  //执行会失败，但是并无异抛出
        log.info("rs b:{}",b);  //异常时代码不执行

现象：
![image](https://user-images.githubusercontent.com/16587700/65407487-497b2f00-de15-11e9-95ab-6a9c61a98039.png)

通过IDEA 手动执行代码结果：
![image](https://user-images.githubusercontent.com/16587700/65407709-f0f86180-de15-11e9-8d9f-cad5b4dc808e.png)

追踪代码：
![image](https://user-images.githubusercontent.com/16587700/65407794-34eb6680-de16-11e9-8182-325d988fa135.png)
此处的异常没有正常抛给调用方

### 重现步骤

批量入库时，实际数据长度超过数据库字段长度导致异常。

### 报错信息
该有报错信息，但无报错信息

**Comment by nieqiurong** [comment]
或许你该检查下自己代码,如果异常没有抛出,为啥你后面消费结束日志没有打印呢?
