### ISSUE TITLE
原生mybatis查询条件不能有中文？

### ISSUE THREAD

**Issue by hhzh** [baomidou/mybatis-plus#164]
在mapper.xml中写查询SQL，用字符串作查询条件，字符串中不能有中文。
如果有中文，就查不出数据。这是个bug吗？

**Comment by huayanYu** [comment]
如果是原生xml写法你应该去mybatis那去提问，或者查看错误自行分析。

**Comment by hhzh** [comment]
我以前用过mybatis，查询条件可以是中文。现在用mp就不行了，会不会是mp的原因？
打印的日志也好好的，没有任何乱码。就是条件用中文，查不出数据

**Comment by qmdx** [comment]
明确的告诉你不是 mp 问题，我们自己使用也没有发现这个问题

**Comment by yuxiaobin** [comment]
看执行的sql，就知道为什么了
