### ISSUE TITLE
3.2.0 自定义生成entity时，能读取到数据表字符字段的长度吗？想在entity里面对字符串自动生成字符串长度的校验

### ISSUE THREAD

**Issue by rbw204** [baomidou/mybatis-plus#1640]

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/generator.html#%E5%AD%97%E6%AE%B5%E5%85%B6%E4%BB%96%E4%BF%A1%E6%81%AF%E6%9F%A5%E8%AF%A2%E6%B3%A8%E5%85%A5

**Comment by rbw204** [comment]
@qmdx  可以增加自定义的字段，但是查询出来的fields只有type，没有专门type长度的field，该怎么读取长度呢？
![image](https://user-images.githubusercontent.com/31235206/65492129-fa9bcb00-dee2-11e9-9eac-42c9c652b5ab.png)
