### ISSUE TITLE
自定义Map类型处理器，引发Service.ListMaps异常。

### ISSUE THREAD

**Issue by sooheng** [baomidou/mybatis-plus#1642]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.1</version>
 </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用自定义TypeHandler：
@MappedJdbcTypes(JdbcType.VARCHAR)
@MappedTypes(value = {Map.class})
public class JsonTypeHandler extends BaseTypeHandler<Object> 
{...
}
不仅是数据库的VARCHAR字段 -> 实体类的Map类型属性的时候会调用自定义处理器，
当调用ListMaps，让实体对象 -> Map类型的时候也会调用自定义处理器。
自然就报异常了，因为我的自定义处理器只针对JsonString -> Map对象，不包括实体对象 -> Map。
是我对自定义处理器的处理范围理解有误，还是说是个bug呢？
（我对自定义处理器的处理范围，是只处理字符串字段到实体对象属性的转化，不包括实体对象对Map对象的转化。）

**Comment by miemieYaho** [comment]
mybatis的问题,去找mybatis
