### ISSUE TITLE
lambda 条件查询时，使用apply方法拼接sql，传入2个参数以上，会抛出Parameter index out of range异常

### ISSUE THREAD

**Issue by amwgwiqpl** [baomidou/mybatis-plus#1643]
### 当前使用版本(必须填写清楚，否则不予处理)
mybaist-plus-core-3.2.0

### 重现步骤

	public List<Zgis> queryAll() {
		Wrapper<Zgis> wrapper = new QueryWrapper<Zgis>().lambda().likeRight(Zgis::getGeohash, "wmg23")
				.apply("FLOOR(ST_DISTANCE_SPHERE(ST_GEOMFROMTEXT('point(105.878169 32.419339)'), gis)) < {0}", 5000);
		return super.list(wrapper);
	}

### 报错信息
 java.sql.SQLException: Parameter index out of range (3 > number of parameters, which is 2).
.

**Comment by amwgwiqpl** [comment]
public List<Zgis> queryAll() {
	Wrapper<Zgis> wrapper = new QueryWrapper<Zgis>().lambda().likeRight(Zgis::getGeohash, "wmg23")
			.apply("FLOOR(ST_DISTANCE_SPHERE(ST_GEOMFROMTEXT('point({0} {1})'), gis)) < {2}", 105.878169, 32.419339, 5000);
	return super.list(wrapper);
}

**Comment by nieqiurong** [comment]
需要拿mybatis生成的sql语句单独在你的数据库里面执行一次看看了

**Comment by gamead** [comment]
我也遇到这个问题啦，有其他条件，也有apply的情况，apply里有参数就报 Parameter index out of range
