### ISSUE TITLE
非spring和spring boot例子

### ISSUE THREAD

**Issue by huigesv123** [baomidou/mybatis-plus#1645]
我发现官方很多例子都是Spring

能否有一些非Spring 只是使用mybatis和MP的例子呢？最基本CRUD和批量添加有吧？

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-quickstart-springmvc

**Comment by cngkqy** [comment]
这个是例子
https://github.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-no-spring
