### ISSUE TITLE
使用saveOrUpdateBatch批量处理数据问题

### ISSUE THREAD

**Issue by robbetliang521** [baomidou/mybatis-plus#1646]
### 当前使用版本(必须填写清楚，否则不予处理)
当前使用版本：3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

我遇到的问题：假如表上的主键是ID，可是有些场景去做saveOrUpdateBatch时并不是按照
主键ID来判断数据是进行save还是update，而是根据其他字段(一个或多个字段组合)进行判断，请问目前是否有方法适配这样的场景，谢谢！

**Comment by miemieYaho** [comment]
没有,自己处理
