### ISSUE TITLE
实体类id不生成

### ISSUE THREAD

**Issue by lchoot** [baomidou/mybatis-plus#1647]
### 当前使用版本(必须填写清楚，否则不予处理)
springboot 2.1.3.RELEASE
mp:3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用代码自动生成的时候，如果数据库的主键名字叫id，生成的实体类中没有出现，数据库中像user_id，role_id就会出现。

**Comment by maple-day** [comment]
springboot 2.3 、 mybatis-plus 3.2.0  数据库 mysql
没有设置setSuperEntityClass（官网上生成的代码），如果表主键是id的生成的Entity就没有id这个字段，如果表主键不是id生成的Entity就会有主键字段但是没有@TableId注解。要怎么解决吗？
