### ISSUE TITLE
IService的listByMap方法

### ISSUE THREAD

**Issue by ShammgodYoung** [baomidou/mybatis-plus#1648]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
请问IService的listByMap(Map<String, Object> map)方法支持自动映射配置吗？比如map传orderNo映射为ORDER_NO

**Comment by miemieYaho** [comment]
不支持
