### ISSUE TITLE
Add support for database provided atomic operation

### ISSUE THREAD

**Issue by FLXT-Qi** [baomidou/mybatis-plus#1653]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

In MySQL and Postgres, we use the syntax like `insert on duplicate key do nothing` or `insert on duplicate key update` to leverage the atomic guarantee that database provided. 
We don't have to create a new standalone transaction and deal with several levels of isolation which is really hard to understand and really vulnerable.

Could you please add support for this kind of statement?

**Comment by yuxiaobin** [comment]
Suggest you to define a custimized base method, see [sample](https://github.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-sql-injector/src/main/java/com/baomidou/samples/injector/MySqlInjector.java)
