### ISSUE TITLE
insert 的时候如何让时间字段=now()

### ISSUE THREAD

**Issue by maruixiang** [baomidou/mybatis-plus#1654]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter :3.2.0
spring boot 1.5.7

通过@TableField(fill = FieldFill.INSERT_UPDATE, update="now()") 可以让update时使用数据库的时间now（），但insert的时候如何解决类似的问题呢？

**Comment by maruixiang** [comment]
为了保证时间一致，不想直接用new Date（）

**Comment by miemieYaho** [comment]
数据库设默认值,或者用自动填充
