### ISSUE TITLE
自动填充更新时间失败

### ISSUE THREAD

**Issue by Mosiki** [baomidou/mybatis-plus#1656]
### 当前使用版本(必须填写清楚，否则不予处理)

V3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用IService 方式直接更新，自动填充更新时间失败（自动填充相关配置是无误的）

### 重现步骤
```java
User entity = new User();
entity.setDeptId(1);
userMapper.update(entity, Wrappers.<User>lambdaUpdate()
        .eq(User::getUsername, "test@163.com"));

userService.lambdaUpdate()
        .eq(User::getUsername, "test@163.com")
        .set(User::getDeptId, 1)
        .update(new User());

userService.lambdaUpdate()
        .eq(User::getUsername, "test@163.com")
        .set(User::getDeptId, 1)
        .update();
```
User 对象的 updateTime 加了注解 @TableField(fill = FieldFill.INSERT_UPDATE)

第三种方式自动填充更新时间失败，原因是该方式没有传递 **Constants.ENTITY** 参数

第三种**update()**无参方式可能会被误用，但第二种方式感觉很奇怪的样子，希望能优化一下，不需要传 Entity也能实现自动填充，或者像 basemapper 一样 update 时必须传 **T entity**参数

**Comment by qmdx** [comment]
必须需要啊否则填充到那个实体？

**Comment by miemieYaho** [comment]
如上,必须要实体
