### ISSUE TITLE
同时使用逻辑删除和自动填充功能，删除（update）操作时，没有更新修改时间

### ISSUE THREAD

**Issue by zhangyu-yxff** [baomidou/mybatis-plus#1657]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
同时配置逻辑删除和自动填功能（修改时间），执行删除操作时，实际是update操作，没有自动填充修改时间

### 重现步骤

UPDATE DK_USER SET del_flag=1 WHERE id=? AND del_flag=0

**Comment by miemieYaho** [comment]
没有entity不能填充,自动填充是填充到entity里

**Comment by zhangyu-yxff** [comment]
entity是有的，使用updateById这个方法，可以正常填充修改时间
`@TableField(fill=FieldFill.UPDATE)`
`private Date updateDate;`

**Comment by zhangyu-yxff** [comment]
> 没有entity不能填充,自动填充是填充到entity里

如上

**Comment by miemieYaho** [comment]
指的入参必要entity

**Comment by zhangyu-yxff** [comment]
> 指的入参必要entity

收到。remove的方法里没有传入实体类的；使用updateById方法，修改时间是自动更新了，但是修改逻辑删除字段不成功（其他字段可正常修改），逻辑删除字段只在insertFill方法里配置了自动填充。
```
DkUser delUser = new DkUser();
delUser.setId(userId);
delUser.setAge(111);
delUser.setDelFlag(1);
boolean success = dkUserService.updateById(delUser);
```
UPDATE DK_USER SET AGE=?, update_date=? WHERE id=? AND del_flag=0

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/faq.html#%E9%80%BB%E8%BE%91%E5%88%A0%E9%99%A4%E4%B8%8B-%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-%E5%8A%9F%E8%83%BD%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C

**Comment by zhangyu-yxff** [comment]
> https://mybatis.plus/guide/faq.html#%E9%80%BB%E8%BE%91%E5%88%A0%E9%99%A4%E4%B8%8B-%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-%E5%8A%9F%E8%83%BD%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C

好的，使用的方法一，手动修改逻辑删除字段和修改时间字段
