### ISSUE TITLE
实体类createTime字段，默认映射到数据库字段为create_tiime ?

### ISSUE THREAD

**Issue by bayberryan** [baomidou/mybatis-plus#1660]
### 当前使用版本(必须填写清楚，否则不予处理)

version: '3.2.0'

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

mp+sqlite 数据实体属性包含createTime字段时默认被映射为create_time。
数据表字段名与实体属性名相同导致查询错误。
只能通过注解指定字段名才执行通过。

### 重现步骤
 使用sqlite数据库，实体类包含createTime字段，调用Mapper的getById方法。

### 报错信息
Error querying database.  Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: create_time)
The error occurred while executing a query\r\n### SQL: SELECT id,bucket,path,create_time,name,updateTime,type,mark FROM File WHERE id=?

**Comment by miemieYaho** [comment]
https://mybatis.plus/config/#mapunderscoretocamelcase

**Comment by bayberryan** [comment]
> https://mybatis.plus/config/#mapunderscoretocamelcase

谢谢，那就是updateTime没有转换成经典数据库列名了
