### ISSUE TITLE
单元测试时,如何比较 QueryWrapper 变量 是否相等

### ISSUE THREAD

**Issue by craone** [baomidou/mybatis-plus#1661]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

mock Mapper 查看 生成的 QueryWrapper 是否是 自己 测试中 想要的的 QueryWrapper ,
不知如何比较.麻烦提示一下.谢谢!

```java
        verify(orderMapper, times(1))?.selectList(
            argThat {
                // this.expression.normal.size == orderQueryWrapper.expression.normal.size
                this.expression == orderQueryWrapper
            }
        )
```

**Comment by miemieYaho** [comment]
自己想
