### ISSUE TITLE
数据库字段与实体绑定错误

### ISSUE THREAD

**Issue by hsulei** [baomidou/mybatis-plus#1663]
springboot: 2.1.8 RELEASE
mybatis-plus: 3.2.0
连接池： Hikari
数据库 postgres11

### 该问题是怎么引起的？
返回的columns与实体中的字段匹配错乱，导致转换错误

### 重现步骤
```java
@TableName(value = "t_account")
public class Account {

  /** id */
  @TableId("id")
  private String id;

  /** 用户名 */
  @TableField("username")
  private String username;

  /** 别名 */
  @TableField("alias")
  private String alias;

  /** 密码 */
  @TableField("password")
  private String password;

  /** 联系方式 */
  @TableField("phone")
  private String phone;

  /** 员工ID */
  @TableField("employee_id")
  private String employeeId;

  /** 状态 */
  @TableField("status")
  private StatusEnum status;

  /** 创建时间 */
  @TableField(value = "create_date", fill = FieldFill.INSERT)
  private OffsetDateTime createDate;

  /** 创建用户ID */
  @TableField("create_user_id")
  private String createUserId;

  /** 创建用户人 */
  @TableField("create_user")
  private String createUser;

  /** 更新时间 */
  @TableField(value = "update_date", fill = FieldFill.UPDATE)
  private OffsetDateTime updateDate;

  /** 更新人 */
  @TableField("update_user_id")
  private String updateUserId;

  /** 更新人 */
  @TableField("update_user")
  private String updateUser;

  /** 组织id */
  @TableField("org_id")
  private String orgId;
}
```
`AccountMapper`继承了`BaseMapper`
测试
```
List<Account> accounts = accountMapper.selectList(null) ;
Assert.assertEquals(2, accounts.size());
accounts.forEach(item -> System.out.println(item));
```

### 报错信息
JDBC Connection [HikariProxyConnection@1227293806 wrapping org.postgresql.jdbc.PgConnection@6c7c71e] will not be managed by Spring
==>  Preparing: SELECT id,update_date,create_user_id,update_user_id,update_user,employee_id,org_id,password,phone,alias,create_user,create_date,status,username FROM t_account 
==> Parameters: 
<==    Columns: id, update_date, create_user_id, update_user_id, update_user, employee_id, org_id, password, phone, alias, create_user, create_date, status, username
<==        Row: 84326034-9692-11e9-bc42-526af7764f64, 2019-09-29 21:30:21, 1, 1, 1, 1, 1, $2a$10$7Rps0HYMvAu0AvIs5gb0MeR2ZjXA/DK.vGRSwwJE77k9.AGPeQaMu, 12345678902, 张三, 1, 2019-09-29 21:30:17, 0, user
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@acb0c44]

Error attempting to get column 'password' from result set.  Cause: org.postgresql.util.PSQLException: conversion to class java.time.OffsetDateTime from varchar not supported

我可以保证 password类型是String，

如果将实体中的时间字段去除
==>  Preparing: SELECT id,create_user_id,password,update_user_id,phone,update_user,alias,create_user,employee_id,org_id,status,username FROM t_account 
==> Parameters: 
<==    Columns: id, create_user_id, password, update_user_id, phone, update_user, alias, create_user, employee_id, org_id, status, username
<==        Row: 84326034-9692-11e9-bc42-526af7764f64, 1, $2a$10$7Rps0HYMvAu0AvIs5gb0MeR2ZjXA/DK.vGRSwwJE77k9.AGPeQaMu, 1, 12345678902, 1, 张三, 1, 1, 1, 0, user
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@32cb47f2]

Error attempting to get column 'alias' from result set.  Cause: org.postgresql.util.PSQLException: 不良的类型值 int : 张三
; 不良的类型值 int : 张三; nested exception is org.postgresql.util.PSQLException: 不良的类型值 int : 张三
org.springframework.dao.DataIntegrityViolationException: Error attempting to get column 'alias' from result set.  Cause: org.postgresql.util.PSQLException: 不良的类型值 int : 张三
; 不良的类型值 int : 张三; nested exception is org.postgresql.util.PSQLException: 不良的类型值 int : 张三

### 其他信息
 测试使用`selectMaps`不报错
 mybatis-plus 版本降级到3.1.2不报错

**Comment by miemieYaho** [comment]
entity给个无参构造
