### ISSUE TITLE
多数据源如何区分生成的mapper xml文件

### ISSUE THREAD

**Issue by hongtu1993** [baomidou/mybatis-plus#1664]
### 当前使用版本
3.1.2

### 该问题是怎么引起的？
使用dynamic-datasource-spring-boot-starter配置多数据源, 怎么区分生成的 mapper xml文件, 如果数据源1中, 没有user表, 则会启动报错

### 报错信息
org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [/target/classes/.../UserMapper.xml]';

**Comment by qmdx** [comment]
该 issue 请提交到 https://github.com/baomidou/dynamic-datasource-spring-boot-starter
