### ISSUE TITLE
分页问题, 版本 2.1.9 ,冲突详情是项目之前引入了 其他 com.github.pagehelper jar 包, 分页插件不执行

### ISSUE THREAD

**Issue by kzcm** [baomidou/mybatis-plus#1665]
## 版本
Mybaits-plus 版本2.1.9,  com.github.pagehelper 版本 1.2.5, 
## 分页插件使用方式
mybatis-plus 分页插件配置方式是 springboot 中配置了得java 配置类,配置 分页插件,然后 类中使用,是集成IService.selectPage 然后调用  BaseMapper.selectPage 方法进行调用,后面用 性能分析插件发现没用执行分页得sql 生成
## 确定冲突得原因
将 com.github.pagehelper 得引入信息,充pom 注释,去掉代码中得 相关引用,然后可以分页了

**Comment by kzcm** [comment]
不执行得时候, Page 类对象返回得total 为0,pages 也为0,  后面注释掉其他分页 jar 后,性能分析插件也没用打印出 查询得sql, 但 Page 类对象返回得分页参数有值

**Comment by qmdx** [comment]
不推荐该模式 https://github.com/baomidou/mybatis-plus/issues/1668 如果你一定要用自行解决

**Comment by kzcm** [comment]
后面去除了 其他 分页插件, 使用 传入 Page 参数的方式修改了对应代码, 就还是很奇怪,这个冲突虽然可以通过这种方式解决,但是冲突发生的时候没有报错,也没有其他的打印什么的,很难排查,
