### ISSUE TITLE
分页插件问题

### ISSUE THREAD

**Issue by dushitaoyuan** [baomidou/mybatis-plus#1668]
### 使用版本
mybatis-plus-boot-starter 3.2
sprinboot 2.1.8

### 重现步骤

1. 实体上无mybatis-plus的各种注解,sql为自定义,返回resultMap或resultType
2. 分页查询,查询参数中包含page,返回IPage<T>,
3. 分页查询,参数@Param("xxx") String xxx,@Param("page")Page page

备注:不带@param注解或无条件查询时查询正常

### 报错信息
类型转换异常:
xxx 
cannot be cast to com.baomidou.mybatisplus.core.metadata.IPage

###问题描述
分页逻辑问题,定位代码如下:
PaginationInterceptor,210-216,
`    Configuration configuration = mappedStatement.getConfiguration();
        List<ParameterMapping> mappings = new ArrayList<>(boundSql.getParameterMappings());
        Map<String, Object> additionalParameters = (Map<String, Object>) metaObject.getValue("delegate.boundSql.additionalParameters");
        model.consumers(mappings, configuration, additionalParameters);
        metaObject.setValue("delegate.boundSql.sql", model.getDialectSql());
        metaObject.setValue("delegate.boundSql.parameterMappings", mappings);
        return invocation.proceed();
`

### 个人建议 
分页插件侵入性太大,提供threadlocal方式分页,返回的page对象,实现list接口

**Comment by qmdx** [comment]
list 就是  list  , page 就是 page 你说的侵入性 threadLocal 存在数据错误可能因此设计之初就不采用该种模式

**Comment by dushitaoyuan** [comment]
这是我的建议,mybatis-plus,可以不采纳,可能我是用pagehelper习惯了,觉得IPage对象实现list接口,可实现对mybatis mapper的零侵入,不会影响mybatis原生使用
但是小弟提出的问题,烦请大佬看下,反馈下

**Comment by qmdx** [comment]
https://mybatis.plus/guide/page.html

**Comment by dushitaoyuan** [comment]
不好意思，这些我还是能看的懂的，好吧issue既然已关闭，就当我没提过吧

**Comment by qmdx** [comment]
使用如 mp 文档 page  放方法第一个参数即可！！

如 pageHelper  方式 ThreadLocal 传递  page 参数貌似更高端实则隐患四伏，下面举个例子：

```
public void test() {
   PageHelper.startPage(1, 10); // 这一行也很突兀遗漏或者无效全表搜是一种灾难
   // 如果这一行为  userMapper.getById(1) 那么下一行无效分页全表搜索
  ArrayList<User> list
  if(条件){
  list  = userMapper.getUsers();
  } else {
   // 如果这一行条件满足，影响下面进跟着的 list 查询
    list = new ArrayList();
 }
```

这种模式还存在一个问题  select * from (sql) limt 1,10 很多真实情况这是低效如果你去优化，那么面对  xml 传参模式，回归到 mp 提倡的模式。

在 mp 2.0 曾经支持过 ThreadLocal 传参衡量再三该模式不适用交给用户去规避可能存在的风险。

如果你觉得你喜欢 mp 分页模式你可以不选择 其他 分页方式，就说这么多了。
