### ISSUE TITLE
mybatis依赖版本管理问题

### ISSUE THREAD

**Issue by zzzvvvxxxd** [baomidou/mybatis-plus#1669]
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
   <version>3.2.0</version>
</dependency>

![image](https://user-images.githubusercontent.com/8758926/66263875-a1aa2c00-e82c-11e9-8ce2-6f6c73907bf0.png)

core和annotation引用的mybatis版本好像不一致，这点是不是不太严谨
关注这个问题主要还是文档中说：

> 引入 MyBatis-Plus 之后请不要再次引入 MyBatis 以及 MyBatis-Spring，以避免因版本差异导致的问题。

感觉所有的module引用的mybatis应该是一致的才对

**Comment by qmdx** [comment]
源码如下，并没有存在多个版本问题，请查看是不是你查看工具问题。

https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/build.gradle
```
apply plugin: 'org.jetbrains.kotlin.jvm'
dependencies {
    api project(":mybatis-plus-annotation")
    api "${lib.'jsqlparser'}"
    api "${lib.mybatis}"

    implementation "${lib.cglib}"
    implementation "${lib.'spring-aop'}"
    

    testCompile "${lib.'mybatis-ehcache'}"
    testCompile "${lib.'logback-classic'}"
    testCompile "${lib.'commons-dbcp2'}"

    testCompile "${lib.aspectjweaver}"
    testCompile "${lib.hikaricp}"
    testCompile "${lib.druid}"
    testCompile "${lib.fastjson}"
    testCompile "${lib.tomcatjdbc}"
}

```

https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-annotation/build.gradle
```
dependencies{
    api "${lib.mybatis}"
}
```
