### ISSUE TITLE
打印出来的SQL可以执行，是不是有什么规则？

### ISSUE THREAD

**Issue by gumulingfeng** [baomidou/mybatis-plus#167]
打印出来的SQL可以执行，是不是有什么规则？
改了好几次都没有成功
@TableField("pay_Service_Charge")
	private BigDecimal payServiceCharge;

xml
<result column="pay_Service_Charge" jdbcType="DECIMAL" property="payServiceCharge" />
使用插件的默认根据ID查询的方法

**Comment by qmdx** [comment]
没看懂，更多问题加我们Q 群576493122
