### ISSUE TITLE
动态数据源启动报错

### ISSUE THREAD

**Issue by zjg2524** [baomidou/mybatis-plus#1671]
mp: 3.1.0,  dynamic-datasource-spring-boot-starter: 2.3.3

按照文档配置动态数据源，master1是oracle，master2是mysql，启动报错java.lang.IllegalArgumentException: Can not set final java.lang.Class field org.apache.ibatis.binding.MapperProxy.mapperInterface to com.baomidou.mybatisplus.core.override.MybatisMapperProxy

**Comment by qmdx** [comment]
该问题请提交到 https://github.com/baomidou/dynamic-datasource-spring-boot-starter
