### ISSUE TITLE
作者有打算支持PrestoDriver没？或如何扩展支持--代码生成时

### ISSUE THREAD

**Issue by hank583746309** [baomidou/mybatis-plus#1672]
### 当前使用版本(必须填写清楚，否则不予处理)

使用版本 3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无针对 com.facebook.presto.jdbc.PrestoDriver 的 DbType 支持。

### 重现步骤

代码生成执行即可见，同时分页插件等相关实现，均不包含此。

### 报错信息
无可支持驱动逻辑实现。

**Comment by qmdx** [comment]
欢迎 pr

**Comment by hank583746309** [comment]
你好，我已经在3.0.5版本基础上做了支持，这边的做法是反编译后再打包，目前在公司内部测试完毕。我可以在3.2.1上 pr 么？

**Comment by zhangzhaohuazai** [comment]
请问这个功能有上线吗？
