### ISSUE TITLE
怎么把IPage里面字段的数字1和0转为文本是和否,只能再下面再循环吗? 还是有效率更高的方法?

### ISSUE THREAD

**Issue by gclsoft** [baomidou/mybatis-plus#1675]
### 当前使用版本(3.2.0)
IPage<List<CustomerQueryVO>> list = dataStateMapper.getCustomerQuery(page,DataStateVO);
这个怎么把里面字段的数字1和0转为文本是和否,只能再下面再循环吗? 还是有效率更高的方法?
因为每个页面都要做查询和导出excel,所以数字转文本等都在后端做了. 每个api请求里都这样循环转一次, 不知有没更高效率的方法?

**Comment by qmdx** [comment]
list 实体新写一个 get 方法转  OR  实体属性映射使用 mybatis typeHandler
