### ISSUE TITLE
3.1.1版本分页测试报错

### ISSUE THREAD

**Issue by huyaoban** [baomidou/mybatis-plus#1676]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-boot-starter</artifactId>
        <version>3.1.1</version>
</dependency>

### 重现步骤
![image](https://user-images.githubusercontent.com/24906133/66532649-a891b100-eb42-11e9-9dcc-f78bae119594.png)
![image](https://user-images.githubusercontent.com/24906133/66532698-d7a82280-eb42-11e9-9c8c-e9a52c4b80f3.png)

如下测试用例报错，没有查出是什么问题，帮忙看下
![image](https://user-images.githubusercontent.com/24906133/66532677-c101cb80-eb42-11e9-81ae-379b2199da96.png)

### 报错信息
![image](https://user-images.githubusercontent.com/24906133/66532736-1342ec80-eb43-11e9-8b88-5e3191d2fbe8.png)

**Comment by miemieYaho** [comment]
看文档
