### ISSUE TITLE
单引号作为值更新到数据库字段的sql格式检测bug

### ISSUE THREAD

**Issue by lesons** [baomidou/mybatis-plus#168]
在做数据insert 或者 update 的时候有个特殊字符无法更新  格式检查错误 ，实际上是ok的

{"shop":{"bgUrl":"/public/assets/static/shop/banner1.png","createTime":"2017-09-22 14:23:14","describe":"emma's shop","fee":0.00,"id":139,"logoUrl":"http://demo1.essintra.ejucloud.cn/yipu/2017-09-26/912704192688246785.jpeg@imageView2/1/w/100/h/100","major":"爱美丽","mbId":182,"name":"赵红艳的店铺emma","state":0,"updateTime":"2017-09-22 14:23:13"},"grades":[{"channelId":10000,"gradeType":1,"id":178,"mbId":182,"shopId":139,"value":4.8},{"channelId":10000,"gradeType":2,"id":179,"mbId":182,"shopId":139,"value":1.0},{"channelId":10000,"gradeType":3,"id":180,"mbId":182,"shopId":139,"value":1.0}]}

上面这段这个作为一个值 插入到一个表字段![sc9u v 2 jmke s8441](https://user-images.githubusercontent.com/5379514/31490155-9ab040f2-af75-11e7-9a5d-b222915235f8.png)  这个位置的这个符号 去掉就可以 ，不然就格式检测不通过。。

**Comment by qmdx** [comment]
1、具体什么数据库

2、调用的什么方法

体代码帖一下。 

如果是 mysql 单引号是转义符号需要注意！ 如果是自定义方法那就是你的方法使用了 $ 符号未预编译自己处理即可。

有疑问回答以上问题打开 issue

**Comment by lesons** [comment]
你好：
是用的mysql5.7  ，mysql-connector-java-5.1.42.jar 
调用的plus的insert 或者update方法都不行，
有的地方直接存入一段包含单引号的值是ok的  像上面这种 一个对象转换出来的json数据里面包含的这种形式就有问题，这值是作为一个string类型的value存入到一个数据库字段

**Comment by qmdx** [comment]
经过测试无反应问题，参考 demo  https://git.oschina.net/baomidou/mybatisplus-spring-boot
访问 http://localhost:8080/user/add 添加特殊符号字符串， 查询 http://localhost:8080/user/page 查看结果

**Comment by lesons** [comment]
@qmdx 不是你这样操作，按照我上面提供的字符串去操作就知道了，往往问题没有这么简单重现你何必还要做这样简单的测试呢？字符串是上面提供的你可以试试
