### ISSUE TITLE
sql解析打印使用控制台输出影响新能

### ISSUE THREAD

**Issue by 136900923** [baomidou/mybatis-plus#1680]
版本为3.2.0，控制台打印输出的sql如下

`16:26:24.912 car-trace-logging [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2b086d92] was not registered for synchronization because synchronization is not active
16:26:25.072 car-trace-logging [http-nio-8080-exec-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
16:26:25.208 car-trace-logging [http-nio-8080-exec-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
JDBC Connection [HikariProxyConnection@312441754 wrapping com.mysql.cj.jdbc.ConnectionImpl@7ab749bd] will not be managed by Spring
==>  Preparing: UPDATE ad_customer_clue SET companyName=?, source=?, companyCode=?, contactMobile=?, updateUserId=?, updateUserName=?, updateTime=?, progress=?, contactUser=?, status=? WHERE isDelete=0 AND (id = ?) 
==> Parameters: companyName(String), 10(Integer), companyCode(String), 137(String), 1(Long), admin(String), 2019-10-10T16:26:25.069(LocalDateTime), 0(Integer), hahaou(String), 0(Integer), 1182191137203163137(Long)
<==    Updates: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2b086d92]
16:26:25.234 car-trace-logging [http-nio-8080-exec-1] INFO  c.h.ad.service.CustomerClueService - update records : 1
`

**Comment by miemieYaho** [comment]
那就关掉
