### ISSUE TITLE
控制台为什么会打印查询的自动填充字段的时间

### ISSUE THREAD

**Issue by cike978** [baomidou/mybatis-plus#1681]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

执行selectlist查询时，控制台会出现 
 2019-09-23 15:40:59.0

 这样的时间，查询的列表数据越多。打印的越多，如何关掉

### 重现步骤

16:49:17 [http-nio-8183-exec-5] INFO  c.p.pay.payment.aspect.WebLogAspect - 请求地址 : http://192.168.0.17:8183/trade/appPay
16:49:17 [http-nio-8183-exec-5] INFO  c.p.pay.payment.aspect.WebLogAspect - 客户端IP : 192.168.0.27
16:49:17 [http-nio-8183-exec-5] INFO  c.p.pay.payment.aspect.WebLogAspect - HTTP METHOD : POST
16:49:17 [http-nio-8183-exec-5] INFO  c.p.pay.payment.aspect.WebLogAspect - CLASS_METHOD : com.pansoft.pay.payment.controller.PayOrderController.tradeCreate
16:49:17 [http-nio-8183-exec-5] INFO  c.p.pay.payment.aspect.WebLogAspect - 参数 : [1020, ali, 1, 15665223354, null, null, org.apache.catalina.connector.RequestFacade@3ebd977c]
**2019-10-10 16:44:33.0
2019-10-10 16:44:33.0**
16:49:17 [http-nio-8183-exec-5] INFO  c.p.pay.payment.aspect.WebLogAspect - 耗时 :78

**Comment by miemieYaho** [comment]
你自己写的你怪谁呢?
