### ISSUE TITLE
Mapper生成问题

### ISSUE THREAD

**Issue by lanseyouling163** [baomidou/mybatis-plus#1685]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在springboot项目中，执行代码生成*Mapper.java

### 重现步骤
在测试中执行查询，报错，见报错信息
临时解决方法是手动给Mapper添加 @Mapper的注释就可以解决
但Mapper过多就比较麻烦了，除非在jar里修改模版文件

### 报错信息

Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'cn.electricity.mapper.task.InspectionTaskViewMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by 846449812** [comment]
怎么解决啊？
