### ISSUE TITLE
greenplum数据库使用3.1.0版本,分页无效

### ISSUE THREAD

**Issue by yijiemanong** [baomidou/mybatis-plus#1686]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
分页插件
@Bean
    public PaginationInterceptor paginationInterceptor() {
        return new PaginationInterceptor();
    }

### 重现步骤
查询不分页,

### 报错信息
sql:
SELECT id,name FROM t_data_customize WHERE datakysj_id = ?

**Comment by miemieYaho** [comment]
不自动支持greenplum该数据库,剩下的看文档看PaginationInterceptor源码

**Comment by yijiemanong** [comment]
谢谢  我设置
```
@Bean
    public PaginationInterceptor paginationInterceptor() {
        return new PaginationInterceptor().setDialectType("postgresql");
    }
```
目前没有发现问题
