### ISSUE TITLE
代码生成器中的BaseEntity找不到

### ISSUE THREAD

**Issue by 449073709** [baomidou/mybatis-plus#1687]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter 3.2.0
mybatis-plus-generator    3.2.0

### 该问题是怎么引起的？**([最新版]
使用代码生成器生成后，引用不到BaseEntity类
这段代码标红 import com.baomidou.ant.common.BaseEntity;

**Comment by miemieYaho** [comment]
BaseEntity是要你自己定义的
