### ISSUE TITLE
Mysql 5.7 Full Text Search 的分页搜索支持

### ISSUE THREAD

**Issue by linyuliang** [baomidou/mybatis-plus#1688]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
报错出现在PaginationInterceptor.java的104行：
                Select selectStatement = (Select) CCJSqlParserUtil.parse(originalSql);
解析SQL，不识别MATCH() AGAINST ()全文搜索语法，抛异常。
JSqlParser里面V3.0版本已经支持，但是还是存在参数传入后异常问题，见：https://github.com/JSQLParser/JSqlParser/pull/824

另外，PaginationInterceptor.java的125行，这个异常没打印异常堆栈，只log，查sql错误要断点很麻烦。

### 重现步骤
mapper.java:
    IPage<AppDO> searchAppPage(Page page, @Param("keyword") String keyword);

执行以下分页sql：
    <select id="searchAppPage" resultType="com.test.AppDO">
        select
        *
        from t_app
        where MATCH(name) AGAINST (CONCAT('*',#{keyword},'*') IN BOOLEAN MODE)
    </select>

### 报错信息
无异常，只打印一条告警信息，failed to concat orderBy from IPage, exception=，但是只分页，不排序

另外，我看com.github.pagehelper    pagehelper 这个插件可以支持，是否mybatis-plus可以不用分页插件，改用这个pagehelper插件来进行分页？

**Comment by linyuliang** [comment]
暂时引入了V3.0版本的 jsqlparser，然后keyword使用${keyword}来替代#{}占位符，外部自己保障搜索词转义，来规避该问题
       
        <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>3.0</version>
        </dependency>

**Comment by miemieYaho** [comment]
要用 pagehelper 就去除mp的分页插件, @bean 注入他的分页插件
