### ISSUE TITLE
能否支持表及字段自动更新到数据库

### ISSUE THREAD

**Issue by zzbinfo** [baomidou/mybatis-plus#169]
在ar模式下构建项目，在项目初期数据库表字段变化比较大，每次改动都需要修改数据库表结构，然后使用代码生成器或者手动同步mode与数据库表代码，当改动越频繁，也感觉繁琐。如果mode的更改能自动更新到数据库就太方便了，就像python中的sqlalchemy。请考虑支持，谢谢~

**Comment by qmdx** [comment]
业界已经有类似的解决方案 http://www.liquibase.org 你可以搜搜相关 demo

**Comment by yuxiaobin** [comment]
spring boot 默认就是用的这个liquibase 来执行ddl语句
