### ISSUE TITLE
如何设置记录的修改人，删除人是谁

### ISSUE THREAD

**Issue by guangshuowang** [baomidou/mybatis-plus#1692]
1、这不是个错误，想问一下不手动书写sql的情况如何实现这样的效果，逻辑删除的时候不知道是谁删的，想记录一下当前账号，我看有一个delete(Wrapper)这么个方法，但好像这个是设置查询条件的，不能设置修改字段
2、还有一个问题调用自带的update的时候是会记录修改人的真实姓名，但是在用户管理那里这个真实姓名是可以被修改的，创建人的那个字段我已经设置用户数据权限了，因为真实姓名能被修改所以我在创建人那里记录的是账号而不是真实姓名，我想让创建人和修改人保持一直，所以想问一下如何让自带的update方法设置修改人是当前账号，而不是真实姓名？

**Comment by miemieYaho** [comment]
逻辑删除那看文档,剩下的自己琢磨
