### ISSUE TITLE
自动生成代码sqlite兼容问题

### ISSUE THREAD

**Issue by chenhengming** [baomidou/mybatis-plus#1693]
当前版本3.2.0

当表主键有PRIMARY KEY关键词，生成实体类bean 自动默认主键为自增
当设置setIdType(IdType.ID_WORKER);无法生成workI_id
去掉主键关键词就无法找到主键字段，TableId注解也不会生成

建议sqllite 生成时候存在setIdType(IdType.ID_WORKER)时候，生成实体类bean按设置的处理。

@akuma @qmdx

**Comment by qmdx** [comment]
生成器和代码是两回事，另外代码里面有全局配置无需生成器单独生成挨个实体 id 配置
