### ISSUE TITLE
数据库字段不是保留字，但是变量是保留字，这种情况怎么处理

### ISSUE THREAD

**Issue by CoxxA** [baomidou/mybatis-plus#1695]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

    @TableField("`R_Group`")
    private String group;

### 重现步骤

    @TableField("`R_Group`")
    private String group;

### 报错信息
变量名要写 group，这种情况应该怎么处理

**Comment by miemieYaho** [comment]
自行规避
