### ISSUE TITLE
 Could not find @TableId in Class这个警告可以关掉吗

### ISSUE THREAD

**Issue by juzi214032** [baomidou/mybatis-plus#1698]
### 当前使用版本(必须填写清楚，否则不予处理)

3.5.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

正常启动就会有

### 重现步骤

正常启动就会有

### 报错信息

 Could not find @TableId in Class

**Comment by miemieYaho** [comment]
不能

**Comment by feiniaoying** [comment]
因为有些表没有主键，怎么能够在实体类中设置@Tableld呢？

**Comment by fzyzcjy** [comment]
同问，对于有复合主键的表，无法设置@TableId，请问如何避免Warning

谢谢

**Comment by fzyzcjy** [comment]
@miemieYaho 

同问，对于有复合主键的表，无法设置@TableId，请问如何避免Warning

谢谢
