### ISSUE TITLE
自动填充，多次继承没发填充

### ISSUE THREAD

**Issue by javanan** [baomidou/mybatis-plus#170]
BaseEntity中  有自动填充的字段，   SysUser继承了BaseEntity   SysUserForm继承了SysUser

操作 SysUserForm 的时候 自动填无效

**Comment by qmdx** [comment]
是否解决？

**Comment by javanan** [comment]
@qmdx 没有， 多级继承不行。

**Comment by qmdx** [comment]
那就不要多次集成了

**Comment by javanan** [comment]
不可能吧，  很多地方是多次继承的，  比如一个基本的 id，和一些自动填充的实体A，  然后业务A1 的 顶级实体继承这个A   业务A2继承这个实体A    然后 A1的具体业务实体A11  继承 A1    这是很常见的。

**Comment by 1065744299** [comment]
@javanan 解决了吗这个问题？

**Comment by javanan** [comment]
@1065744299  没测试，不清楚

**Comment by yuxiaobin** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/e287194507b8016f1ce6983f2f108f15c252b3cb

这里有多重继承后自动填充的testcase，测试没问题。

`
SuSuperEntity{
private Date lastUpdatedDt;
}

SuperEntity extends SuSuperEntity{
private Long id;
}

H2UserMetaObj extends SuperEntity{
}

H2MetaObjectHandlerTest{
//这里的testcase都是测insert/update的自动填充
}
`

**Comment by yuxiaobin** [comment]
公共填充的bug在2.1.5版本就修复了，如果出现问题，请先升级下mp版本
