### ISSUE TITLE
如何使用setInclude的正则表达式

### ISSUE THREAD

**Issue by crtxr1998** [baomidou/mybatis-plus#1700]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus  3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
   使用代码生成器
  //需要包含的表名，允许正则表达式（与exclude二选一配置）
  strategy.setInclude("TB_GG*");
  没有生成以TB_GG开头的实体
  不知道是不是姿势不对

### 重现步骤
      // 策略配置
        StrategyConfig strategy = new StrategyConfig();
        strategy.setNaming(NamingStrategy.underline_to_camel);
        strategy.setColumnNaming(NamingStrategy.underline_to_camel);
        strategy.setEntityLombokModel(true);
        strategy.setSuperControllerClass("com.moe.tool.common.entity.BaseController");
        strategy.setRestControllerStyle(true);
        👉strategy.setInclude("TB_GG*");
        strategy.setControllerMappingHyphenStyle(true);
        strategy.setTablePrefix(pc.getModuleName() + "_");

**Comment by qmdx** [comment]
👉strategy.setInclude("^TB_GG(.*)$");

**Comment by crtxr1998** [comment]
好像依旧无法正确匹配

**Comment by prettydva** [comment]
https://github.com/baomidou/mybatis-plus/issues/2948
