### ISSUE TITLE
多数据源多数据库类型配置问题

### ISSUE THREAD

**Issue by 1805214** [baomidou/mybatis-plus#1703]
### 当前使用版本(必须填写清楚，否则不予处理)
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>3.1.1</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
配置了sqlserver和mysql的数据源.
sqlserver不使用默认dbo模式, 使用新创建的一个模式,这个时候我如果配置了
db-config:
      table-prefix:
      table-underline: true
      schema: xxx
sqlserver的表可以正常操作,但是mysql的表就会找不到.
如果不配置schema
db-config:
      table-prefix:
      table-underline: true
mysql的表可以正常操作,但是sqlserver的表就会找不到.
并且如果我有多个sqlserver的库和模式,怎么配置.同一个项目中.

**Comment by miemieYaho** [comment]
不支持,自己创建俩sqlsessionfactory
