### ISSUE TITLE
乐观锁开启状态下Double类型size字段如果为null也会被更新且无法更改策略

### ISSUE THREAD

**Issue by maybeyj** [baomidou/mybatis-plus#1705]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
前提：开启乐观锁
调用updateById方法更新数据，Double类型的size字段如果是null也会被携带上将结果集更新成null，我的更新策略是默认。

### 重现步骤
开启乐观锁：
![image](https://user-images.githubusercontent.com/34763876/66894823-f23b3980-f023-11e9-955a-f94efe229f35.png)
实体类：
![image](https://user-images.githubusercontent.com/34763876/66894944-4514f100-f024-11e9-9fbc-66d97ab86f2d.png)

测试：
![image](https://user-images.githubusercontent.com/34763876/66894903-29a9e600-f024-11e9-892f-a937f3d37fd8.png)

关闭乐观锁则不存在此问题！

**Comment by maybeyj** [comment]
![image](https://user-images.githubusercontent.com/34763876/66895315-0af81f00-f025-11e9-8371-27a94fd7d925.png)
![image](https://user-images.githubusercontent.com/34763876/66895331-18150e00-f025-11e9-981e-c99623541d49.png)
为什么？？？？

**Comment by maybeyj** [comment]
总结问题：乐观锁开启状态下，实体类字段不能叫size，否则更新的时候，如果size字段为null，结果集也会被更新成null，且无法修改更新策略！！！

**Comment by hcl04** [comment]
![图片](https://user-images.githubusercontent.com/39977647/66901560-7ea02900-f031-11e9-9347-8d3b2aa8aa58.png)

**Comment by nieqiurong** [comment]
生成if需转换size,keys,keySet,values,isEmpty这五个key.

<if test="size !=null ">  <if test="['size'] !=null ">

**Comment by maybeyj** [comment]
@nieqiurong 意思是实体类中属性名 size 是mybatis-plus的特殊关键字吗？实体类中的字段不能叫做size？

**Comment by maybeyj** [comment]
@nieqiurong 奇怪的是只有在开启乐观锁的情况下会出现这个BUG，关闭乐观锁则不影响

**Comment by nieqiurong** [comment]
> @nieqiurong 奇怪的是只有在开启乐观锁的情况下会出现这个BUG，关闭乐观锁则不影响

和乐观锁无关,也不是mybatis-plus的关键字,这与ognl表达式处理有关.
