### ISSUE TITLE
sqlserver代码生产之后没有ID注解@TableId(value = "id", type = IdType.UUID)

### ISSUE THREAD

**Issue by 1805214** [baomidou/mybatis-plus#1707]
### 当前使用版本(必须填写清楚，否则不予处理)

 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.1.1</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
mysql正常  sqlserver 生成没有@TableId注解 导致更新报没有主键
because can not find column for id from entity!

**Comment by qmdx** [comment]
生成器如果属性为 id 是不生成注解的，更新错误请给出示例后打开issue
