### ISSUE TITLE
升级到SB2.2.0后parameteMapping报错导致无法启动应用

### ISSUE THREAD

**Issue by pkaq** [baomidou/mybatis-plus#1710]
升级到SB2.2.0后parameteMapping报错导致无法启动应用

**Comment by pkaq** [comment]
@miemieYaho ?????

**Comment by miemieYaho** [comment]
有疑问就给出你的复现demo,我们无法复现

**Comment by nieqiurong** [comment]
在resources下建立spring.properties,增加配置spring.jndi.ignore=true 试试看看.
