### ISSUE TITLE
与seata结合使用时，model自身调用insert()方法并不能实际保存入数据库

### ISSUE THREAD

**Issue by Rosaling** [baomidou/mybatis-plus#1713]
### 当前使用版本(必须填写清楚，否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

与seata结合使用，大概是seata与代理了dataSource有关？使用在*Mapper.xml里的自定义sql语句，数据能正常insert进数据库，但model.insert()，model能获取到插入id，但并没有实际存入数据库。

是不是我哪里配置有问题？

### 重现步骤

![image](https://user-images.githubusercontent.com/16833254/66989985-ede05080-f0f7-11e9-82f1-50b03578f241.png)
![image](https://user-images.githubusercontent.com/16833254/66990380-aad2ad00-f0f8-11e9-9aac-7ffca75fb28e.png)
![image](https://user-images.githubusercontent.com/16833254/66990358-9f7f8180-f0f8-11e9-8abe-8b3ae7eeafe0.png)

### 报错信息

无报错信息，只有实际结果异常。

**Comment by miemieYaho** [comment]
不要修改默认的 transactionFactory
