### ISSUE TITLE
请问removeById逻辑删除同时，自动填充字段不生效，是bug吗

### ISSUE THREAD

**Issue by lemoncy** [baomidou/mybatis-plus#1715]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/3096214/67010160-b2f21300-f11f-11e9-9089-ad8ac686ace1.png)

removeById逻辑删除同时，自动填充字段不生效。
removeById 最终执行的是update，modifyTime未更新，执行其他：saveOrUpdate、updateById方法modifyTime都更新了。
请问removeById逻辑删除同时，自动填充字段不生效，是bug吗，还是逻辑删除同时就不支持字段自动填充。

### 重现步骤
无

### 报错信息
无

**Comment by miemieYaho** [comment]
看文档常见问题里
