### ISSUE TITLE
代码生成拓展方面设计不合理

### ISSUE THREAD

**Issue by luohongtu** [baomidou/mybatis-plus#1717]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
代码生成器拓展InjectionConfig initMap()方法没有传入TableInfo相关信息，导致我无法给某个表定制的去生成环境变量，比如我现在要拓展前端，所有前端元数据通过前台编辑保存在数据库上面，但是这个时候我点生成代码的时候，需要去数据库拉取，initMap() 没当前执行表的信息，我无法给某个表单独处理，只能做把所有表都处理，这样我必须cfg.表名.字段名.meta 才能拿到相关元数据，而不是cfg.字段名.meta

**Comment by qmdx** [comment]
有人提过 pr 针对该问题调整 https://github.com/baomidou/mybatis-plus/commit/91a922a017046b665d322b71c1bfe513d0a02663 下一个版本可用

**Comment by luohongtu** [comment]
哈哈，那个人就是我，就是我提交的

**Comment by luohongtu** [comment]
最近，再用mybatisplus 搞后台全套代码生成器，在用到这块的是否，发现设计不合理，然后我是通过别的方案实现的，但是感觉还是不是太合理，然后就把自己觉得最合理方案提交上去了

**Comment by luohongtu** [comment]
谢谢，大佬merge我提交，是对我最大的鼓励，我第一次提交pull request，以后一定多贡献自己微薄之力
