### ISSUE TITLE
项目放在中文目录下启动报错

### ISSUE THREAD

**Issue by yuanhca** [baomidou/mybatis-plus#1719]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-boot-starter-3.2.0.jar

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

项目放在一个中文路径下，比如 /中文/projectName
`com.baomidou.mybatisplus.autoconfigure.SpringBootVFS`
这个文件中的方法
```java
    private String preserveSubpackageName(final String baseUrlString, final Resource resource, final String rootPath) {
        try {
            return rootPath + (rootPath.endsWith("/") ? "" : "/")
                + resource.getURL().toString().substring(baseUrlString.length());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
```
resource的地址没有encode ，baseUrlString被encode后比前者长，越界

**Comment by qmdx** [comment]
感谢反馈，这种问题就不要纠结了换一个英文目录

**Comment by nieqiurong** [comment]
![Uploading image.png…]()
