### ISSUE TITLE
分页插件中total无法自动计算？

### ISSUE THREAD

**Issue by edwardlau** [baomidou/mybatis-plus#172]
```
    Page page =new Page<CancerDict>(1,10);
		Map<String,Object> stringObjectMap = Maps.newHashMap();
		stringObjectMap.put("del_flag",0);
		stringObjectMap.put("PARENT_ID",1);
Page<CancerDict> cancerDictPage =cancerDictService.selectPage(page,null);
```
日志打印出来的是这样的:

```
cancerDictPage: Page:{ [Pagination { total=0 ,size=10 ,pages=0 ,current=1 }], records-size:1 }
```

调用getTotal方法为什么是0还需要设置什么么？

**Comment by yhb890430** [comment]
只使用分页插件是这样的，这个问题你解决没有

**Comment by hookszhang** [comment]
可以手动调用一下 selectCount 方法
```
page.setTotal(service.selectCount(null));
```

**Comment by qmdx** [comment]
必须配置分页插件 http://baomidou.oschina.io/mybatis-plus-doc/#/page-plugin

**Comment by Kimmyzhao** [comment]
![tim 20180601155947](https://user-images.githubusercontent.com/11455494/40829184-4d14e874-65b5-11e8-9dc8-93318d1fac28.png)
![tim 20180601160009](https://user-images.githubusercontent.com/11455494/40829185-4d52c18a-65b5-11e8-8dc3-74cd412aa868.png)
![tim 20180601160123](https://user-images.githubusercontent.com/11455494/40829187-4d8a89ee-65b5-11e8-98fd-f1b7755db32d.png)
total为0

**Comment by hookszhang** [comment]
```
@Configuration
public class MybatisPlusConfig
```

**Comment by Kimmyzhao** [comment]
有的，刚截图没有截出来而已 @hookszhang

**Comment by Kimmyzhao** [comment]
![tim 20180601160819](https://user-images.githubusercontent.com/11455494/40829541-58de5a18-65b6-11e8-9ac5-f586a3a5aab2.png)
@hookszhang

**Comment by hookszhang** [comment]
我用的也是 MySQL，没有设置 DialectType，可以正常工作

> http://baomidou.oschina.io/mybatis-plus-doc/#/page-plugin 官方实例

```
//Spring boot方式
@EnableTransactionManagement
@Configuration
@MapperScan("com.baomidou.cloud.service.*.mapper*")
public class MybatisPlusConfig {

    /**
     * 分页插件
     */
    @Bean
    public PaginationInterceptor paginationInterceptor() {
        return new PaginationInterceptor();
    }
}
```
