### ISSUE TITLE
代码生成器连接sqlserver2000生成报错

### ISSUE THREAD

**Issue by JinJieZhiLu6** [baomidou/mybatis-plus#1721]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus：3.2.0  mybatis-plus-generator：3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用jdts驱动连接sqlserver2000生成mapper等文件，然后报错，连接sqlserver2008就没事

### 报错信息
java.sql.SQLException: Invalid object name 'sys.extended_properties'.

**Comment by JinJieZhiLu6** [comment]
用mybatis自己逆向工程也能生成，就是mybatis-plus的代码生成器不行

**Comment by qmdx** [comment]
sqlserver2000  这个老古董暂无可测库，希望解决 pr
