### ISSUE TITLE
可以自己继承AbstractTemplateEngine来生成controller和service中的CRUD方法吗？

### ISSUE THREAD

**Issue by webcat007** [baomidou/mybatis-plus#1722]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.2.0</version>
</dependency>

**Comment by webcat007** [comment]
刚刚研究了一下代码生成器的源码，建议将FileOutConfig配置放出来，这样用户可以在MP的基础上自定义模板内容，这样对于有需求的使用者来说会更加方便，希望作者采纳。

**Comment by qmdx** [comment]
FileOutConfig 是可以注入的

**Comment by 15050050972** [comment]
我正在实现类似的需求，在controller中加上CRUD的模板方法，但是需要用到一些变量. 如`userService`, 这样的小驼峰名字，生成器中只看到了大写相关的ServiceName和ControllerName，请问如何将首字母转小写？在velocity文档中没看到有比较方便的操作方法.
在`InjectionConfig`中的`initMap`方法也无法插入和tableInfo相关的属性
