### ISSUE TITLE
构造查询时候空指针异常

### ISSUE THREAD

**Issue by a123715438** [baomidou/mybatis-plus#1724]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用条件构造器时，使用condition 作为条件判断时，条件不成立时，后面执行内容有空时报空指针异常

**Comment by qmdx** [comment]
升级到 3.2.0 版本低版本不做重复 Bug 修复，3.2.0 如果还存在问题给出给出具体例子，并打开 issue
