### ISSUE TITLE
TableFieldInfo的this.column = column;可以提供接口吗？或配置转换规则

### ISSUE THREAD

**Issue by TanqiZhou** [baomidou/mybatis-plus#1725]
mysql存在关键字，可以提供接口配置字段一个转换规则吗？有点像驼峰命名转换一样
因为我不想出现原因时才一个个设置注解

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/config/GlobalConfig.java 117行,
建议直接规范数据库字段命名
