### ISSUE TITLE
大佬们好,我在整合actable 和mybatis的时候,总是报错

### ISSUE THREAD

**Issue by haohaoxueba** [baomidou/mybatis-plus#1726]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
如果可以,我希望mybatisplus 可以纳入actable 项目的功能,自动创建表,这样可以省去很多的工作,actable目前感觉很差劲,在生成表的时候,是没有先后顺序设置的,往往表生成出来,主键列的顺序不固定,如果可以,希望顺序可以控制,我希望我创建一个entity实体,项目启动时表和mapper就已经自动创建好了,这样也能降低java开发的门槛,希望被采纳

**Comment by hcl04** [comment]
![图片](https://user-images.githubusercontent.com/39977647/67155997-aa7e2000-f34b-11e9-8d99-c99dd7a3cf53.png)
骚年，一般公司的数据库账号都没有进行 DDL 的权限吧？

**Comment by haohaoxueba** [comment]
> ![图片](https://user-images.githubusercontent.com/39977647/67155997-aa7e2000-f34b-11e9-8d99-c99dd7a3cf53.png)
> 骚年，一般公司的数据库账号都没有进行DDL的权限吧？

我们是小公司,没有DBA,基本全是Java写Java需要从web到数据库全做了....很难受啊

**Comment by qmdx** [comment]
你说的这个功能比较鸡肋对 MP 改也会很大，推荐独立组件  flyway 自动维护 sql 非常简单易用
