### ISSUE TITLE
只生成entity

### ISSUE THREAD

**Issue by qiyu23793637** [baomidou/mybatis-plus#1729]
当前使用版本：3.2.0
代码生成希望能有个开关，毕竟大多数只是想要个entity。

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/generator.html#%E6%B7%BB%E5%8A%A0%E4%BE%9D%E8%B5%96

例子中关闭 xml 自定义路径
```
// 关闭对应模块设置 NULL
templateConfig.setXml(null);
```
