### ISSUE TITLE
代码生成问题

### ISSUE THREAD

**Issue by xupengggggg** [baomidou/mybatis-plus#173]
ConfigBuilder - convertTableFields 里，field查询语句里的%s，不用string.format替换掉表名的话，是怎么执行成功的？

**Comment by xupengggggg** [comment]
哦，2.1.1有这问题，2.1.3已经更新这个情况了，增加了
 else {
                tableFieldsSql = String.format(tableFieldsSql, tableInfo.getName());
            }

**Comment by qmdx** [comment]
恩恩 有一个版本确实存在问题，多谢支持
