### ISSUE TITLE
关于实体类 scheme的问题 一些数据库命名为xx-xxx导致生成sql的时候报错

### ISSUE THREAD

**Issue by 5zyd14** [baomidou/mybatis-plus#1730]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
有一些数据库的命名是 xxx-xxx，导致生成SQL的时候报错了
因为select * from xxx-xxx需要修改为select * from `xxx-xxx`

### 报错信息
库名为:
bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-cloud

**Comment by miemieYaho** [comment]
```java
@TableName(`xxx-xxx`)
```

**Comment by 5zyd14** [comment]
谢谢。。忘了这茬了 一开始以为这个字段会有其他作用 仔细想了想 好像确实只有在拼接sql的时候有用。。
