### ISSUE TITLE
2.1.9版本的手写批量更新总是返回1

### ISSUE THREAD

**Issue by zhangzewa** [baomidou/mybatis-plus#1735]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.9

### 重现步骤

```sql
<update id="updateBatch" parameterType="java.util.List">
        <foreach collection="list" item="item" index="index" open="" close="" separator=";">
            UPDATE stock
            <set>
                stock_count = #{item.stockCount},
                version = #{item.version}+1,
            </set>
            <where>
                id = #{item.id} AND version=#{item.version}
            </where>
        </foreach>
    </update>
```
Preparing:UPDATE st_stock SET stock_count = ?, version = ?+1 WHERE id = ? AND version=? ; UPDATE st_stock SET stock_count = ?, version = ?+1 WHERE id = ? AND version=?
Parameters: 111.0(Float), 4(Long), 2(Long), 4(Long), 1113.0(Float),  4(Long), 1(Long), 4(Long)
Updates: 1

### 报错信息
0条成功，返回updates=0
1至n条成功，返回updates=1

需要通过获取updates和list.size对比，判断是否全部更新
****

**Comment by miemieYaho** [comment]
你手写那就和mp没关系了
