### ISSUE TITLE
使用lamdba表达式查询报错，直接写参数名可以正常使用，求解

### ISSUE THREAD

**Issue by houniantang** [baomidou/mybatis-plus#1736]
7a14f2bcf83 | java.lang.IllegalStateException: Failed to execute CommandLineRunner
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.kylin.auth.AuthApplication.main(AuthApplication.java:20)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.lang.reflect.Method.invoke(Method.java:498)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
kylin-auth-server_1_b7a14f2bcf83 | Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [org.apache.ibatis.reflection.ReflectionException: Error parsing property name 'lambda$0'.  Didn't start with 'is', 'get' or 'set'.]
kylin-auth-server_1_b7a14f2bcf83 | 	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.sun.proxy.$Proxy115.selectOne(Unknown Source)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.sun.proxy.$Proxy118.selectOne(Unknown Source)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.kylin.auth.controller.AuthController.getAppPermission(AuthController.java:87)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.kylin.auth.controller.AuthController$$FastClassBySpringCGLIB$$e3129088.invoke(<generated>)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.kylin.auth.controller.AuthController$$EnhancerBySpringCGLIB$$7285297c.getAppPermission(<generated>)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.kylin.auth.client.service.AuthService.initAppPermission(AuthService.java:204)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.kylin.auth.client.runner.AuthRunner.run(AuthRunner.java:31)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
kylin-auth-server_1_b7a14f2bcf83 | 	... 13 common frames omitted
kylin-auth-server_1_b7a14f2bcf83 | Caused by: org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [org.apache.ibatis.reflection.ReflectionException: Error parsing property name 'lambda$0'.  Didn't start with 'is', 'get' or 'set'.]
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:48)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.ExpressionEvaluator.evaluateBoolean(ExpressionEvaluator.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.IfSqlNode.apply(IfSqlNode.java:34)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.TrimSqlNode.apply(TrimSqlNode.java:55)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.IfSqlNode.apply(IfSqlNode.java:35)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.DynamicSqlSource.getBoundSql(DynamicSqlSource.java:39)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:297)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.lang.reflect.Method.invoke(Method.java:498)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
kylin-auth-server_1_b7a14f2bcf83 | 	... 31 common frames omitted
kylin-auth-server_1_b7a14f2bcf83 | Caused by: org.apache.ibatis.ognl.OgnlException: sqlSegment
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.OgnlRuntime.getMethodValue(OgnlRuntime.java:1693)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.ObjectPropertyAccessor.getPossibleProperty(ObjectPropertyAccessor.java:60)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.ObjectPropertyAccessor.getProperty(ObjectPropertyAccessor.java:147)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.OgnlRuntime.getProperty(OgnlRuntime.java:2719)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.ASTProperty.getValueBody(ASTProperty.java:114)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.ASTChain.getValueBody(ASTChain.java:141)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.ASTNotEq.getValueBody(ASTNotEq.java:50)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.ASTAnd.getValueBody(ASTAnd.java:61)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.Ognl.getValue(Ognl.java:493)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.Ognl.getValue(Ognl.java:457)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:46)
kylin-auth-server_1_b7a14f2bcf83 | 	... 55 common frames omitted
kylin-auth-server_1_b7a14f2bcf83 | Caused by: org.apache.ibatis.reflection.ReflectionException: Error parsing property name 'lambda$0'.  Didn't start with 'is', 'get' or 'set'.
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.reflection.property.PropertyNamer.methodToProperty(PropertyNamer.java:37)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.getColumn(AbstractLambdaWrapper.java:88)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:72)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:68)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:39)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.lambda$addCondition$ac69df92$1(AbstractWrapper.java:332)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList.childrenSqlSegment(NormalSegmentList.java:89)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.segments.AbstractISegmentList.getSqlSegment(AbstractISegmentList.java:102)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.getSqlSegment(MergeSegments.java:72)
kylin-auth-server_1_b7a14f2bcf83 | 	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.getSqlSegment(AbstractWrapper.java:432)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
kylin-auth-server_1_b7a14f2bcf83 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kylin-auth-server_1_b7a14f2bcf83 | 	at java.lang.reflect.Method.invoke(Method.java:498)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:881)
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.ognl.OgnlRuntime.getMethodValue(OgnlRuntime.java:1691)
kylin-auth-server_1_b7a14f2bcf83 | 	... 73 common frames omitted
kylin-auth-server_1_b7a14f2bcf83 |

**Comment by houniantang** [comment]
kylin-auth-server_1_b7a14f2bcf83 | Caused by: org.apache.ibatis.reflection.ReflectionException: Error parsing property name 'lambda$0'.  Didn't start with 'is', 'get' or 'set'.
kylin-auth-server_1_b7a14f2bcf83 | 	at org.apache.ibatis.reflection.property.PropertyNamer.methodToProperty(PropertyNamer.java:37)
难道是lambda字符没有被替换掉吗？

**Comment by miemieYaho** [comment]
eclipse?

**Comment by houniantang** [comment]
用maven编译的

**Comment by miemieYaho** [comment]
是不是用eclispe跑的?

**Comment by wcpaxx** [comment]
跟eclispe应该没关系，可能跟jdk版本有关，目前我本机1.8.0.191没问题，测试环境1.8.0.101报错如上，原因是获取的lambda方法名类似“lambda$1”，而不是getXxxx

**Comment by houniantang** [comment]
问题已经解决了，确实是eclipse的问题，我更想到最新版本后问题解决了



houniantang@163.com
 
发件人： wcpaxx
发送时间： 2020-04-13 17:17
收件人： baomidou/mybatis-plus
抄送： houniantang; Author
主题： Re: [baomidou/mybatis-plus] 使用lamdba表达式查询报错，直接写参数名可以正常使用，求解 (#1736)
跟eclispe应该没关系，可能跟jdk版本有关，目前我本机1.8.0.191没问题，测试环境1.8.0.101报错如上，原因是获取的lambda方法名类似“lambda$1”，而不是getXxxx

**Comment by wcpaxx** [comment]
更新最新版本eclipse时，jdk版本有升级吗？

**Comment by wcpaxx** [comment]
本地降到101版本，也能成功，不是jdk问题

**Comment by houniantang** [comment]
JDK没有升级一直都是1.8的，应该是eclipse版本太老，不支持jdk1.8的新增功能



houniantang@163.com
 
发件人： wcpaxx
发送时间： 2020-04-13 18:27
收件人： baomidou/mybatis-plus
抄送： houniantang; Author
主题： Re: [baomidou/mybatis-plus] 使用lamdba表达式查询报错，直接写参数名可以正常使用，求解 (#1736)
更新最新版本eclipse时，jdk版本有升级吗？
―
