### ISSUE TITLE
mybatis-plus.configuration.map-underscore-to-camel-case: true失效

### ISSUE THREAD

**Issue by moxiaobin** [baomidou/mybatis-plus#1738]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2;
3.2.0; 

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

spring boot配置文件bootstrap.yml中配置:
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true

查询自定义的mapper.xml中, 字段返回值类型为:Map;
但map中的字段key并没有驼峰命名, 还是数据库下划线.

### 重现步骤

3.1.1版本升级后, 自定义mapper中的sql都没有写select 字段 as; 报错;

**Comment by miemieYaho** [comment]
返回map看文档常见问题
