### ISSUE TITLE
批处理自动填充失败

### ISSUE THREAD

**Issue by jqncc** [baomidou/mybatis-plus#174]
`
public abstract class BaseEntity implements  Serializable{
 private Date createDate;
    /**
     * 创建人
     */
    private String createBy;
    /**
     * 更新时间
     */
    private Date updateDate;
    /**
     * 更新人
     */
    private String updateBy;
//getter and setter
}
`
其他实体类都继承该类,举例有AdPlan 和AdPlayLists两个实体类
单一save没有问题,批处理填充失败

`
 @Test
    public void testbatchSave() {

        List<AdPlayList> playLists = new ArrayList<>();
        AdPlayList p1 = new AdPlayList();
        p1.setBuyerId("1");
        p1.setMaterialId(1);
        p1.setPlanId(2);
        p1.setPlayOrder(2);
        playLists.add(p1);
        adPlayListServiceImpl.save(p1);//填充成功
        adPlayListServiceImpl.batchSave(playLists);//填充失败,输出sql无要填充的字段,导致数据库报错
    }
`

**Comment by qmdx** [comment]
是否解决？

**Comment by qmdx** [comment]
文档 http://baomidou.oschina.io/mybatis-plus-doc/#/auto-fill 注意注解 fill
