### ISSUE TITLE
请问mybatis-plus新版本里头 有没有简便的方法可以查询出逻辑删除的数据？或者说在某个业务场景下，可以禁用逻辑删除注解生效呢？

### ISSUE THREAD

**Issue by weiailuxueqi** [baomidou/mybatis-plus#1740]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

请问mybatis-plus新版本里头 有没有简便的方法可以查询出逻辑删除的数据？或者说在某个业务场景下，可以禁用逻辑删除注解生效呢？
在公司多个项目中都是使用这个，发现都有这样的场景，逻辑删除注解又不想去掉，因为业务繁多，现在去改又不太方便，所以特来咨询看是否可以加个这样的功能。感激不尽。

**Comment by miemieYaho** [comment]
没有
