### ISSUE TITLE
升级springboot版本2.2.0，启动报错

### ISSUE THREAD

**Issue by yaohuiye** [baomidou/mybatis-plus#1742]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

#### 问题
原先使用的spring boot版本是2.1.6.RELEASE
最近将SpringBoot升级为2.2.0.RELEASE
打成war包，在测试环境上通过tomcat部署，启动不了。
当我将版本还原为原来的，则能正常启动，不报错

#### 报错日志
启动日志的报错如附件图

Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' 

![image](https://user-images.githubusercontent.com/3142520/67449024-617be380-f64b-11e9-8b07-9bc5f638f311.png)

#### 项目中mybatis-plus的配置
![image](https://user-images.githubusercontent.com/3142520/67449121-a99b0600-f64b-11e9-9538-aa99a71c9b11.png)

**Comment by miemieYaho** [comment]
不是mp的问题
