### ISSUE TITLE
springBoot mybatis-plus  启动 IService的 baseMapper 注入错误

### ISSUE THREAD

**Issue by listener-He** [baomidou/mybatis-plus#1743]
### 当前使用版本(必须填写清楚，否则不予处理)

  Mybatis-plus 3.2.0    SpringBoot 1.5.9

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

  IService 中的baseMapper 提示有两个Bean ，经排除发现无两个bean，也没注入两次

### 报错信息

Field baseMapper in com.baomidou.mybatisplus.extension.service.impl.ServiceImpl required a single bean, but 2 were found:

**Comment by miemieYaho** [comment]
给出你的复现demo
