### ISSUE TITLE
lambda last 不起作用

### ISSUE THREAD

**Issue by zxkxhn** [baomidou/mybatis-plus#1744]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis plus 3.1.1 + spring boot 2.0.4 

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用lambda时 加入了 last 
,发现打印出来的语句中并不会加入last中的sql

### 重现步骤
```java
QueryWrapper<entity> queryWrapper = new QueryWrapper<>();
query.lambda
         .eq(xx,xx)
         .last('limit 1');
         
dao.selectOne(queryWrapper ); // 此处会报错,因为返回值是多个
```
### 报错信息
就是返回值多个,接受只有一个,报错了

**Comment by yh2388** [comment]
这个问题有修复吗？没有看到与该issue关联的pr。
