### ISSUE TITLE
获取查询条件动态分表逻辑

### ISSUE THREAD

**Issue by jasonzhouxf** [baomidou/mybatis-plus#1745]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 重现步骤
1. 用QueryWrapper查询
 final QueryWrapper<User> queryWrapper = new QueryWrapper<>();

        queryWrapper.eq("id", 1);
        queryWrapper.eq("name", "mike");
        final List<User> users = userMapper.selectList(queryWrapper);

2. Plugins获取MetaObject
 StatementHandler statementHandler = PluginUtils.realTarget(invocation.getTarget());
MetaObject metaObject = SystemMetaObject.forObject(statementHandler);

3. metaObject 获取查询参数

获取到的参数：
ew.paramNameValuePairs.MPGENVAL5 
ew.paramNameValuePairs.MPGENVAL6

问题：

如何才能从metaObject 获取id，name 两个参数及对应的值，用作动态表

### 报错信息

无报错，无法获取到参数

**Comment by jasonzhouxf** [comment]
用Wrapper的方式，都无法做动态表操作

**Comment by miemieYaho** [comment]
不支持获取,你可以使用sharding-jdbc进行分表

**Comment by jasonzhouxf** [comment]
应该可以吧，不然参数如何塞给ibatis啊
