### ISSUE TITLE
wrapper 如何构造 and 里多个动态的 or 

### ISSUE THREAD

**Issue by FollowTheTrend** [baomidou/mybatis-plus#1747]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
想咨询一下, 目前有这样的需求:  wp.and(i -> i.or().or());  并且每个 or() 其实是根据遍历 list 来动态生成的, 想请问下这种 wrapper 是否支持?
目前写法是新创建一个 wrapper, 然后遍历 list 把这个 wrapper 组装好, 最后 wp.and (i -> wrapper) 
sql 其实能正确输出出来, 但是传进去的参数却不对, 不知道发生了什么, 想咨询一下作者

### 重现步骤
```
LambdaQueryWrapper<PartnerBo> orWrapper = Wrappers.lambdaQuery();

            for (NoticeRegionBo noticeRegionBo : noticeRegionList) {
                orWrapper.or(w -> w.eq(StringUtils.isNotEmpty(noticeRegionBo.getProvinceCode()), PartnerBo::getProvinceCode, noticeRegionBo.getProvinceCode())
                    .eq(StringUtils.isNotEmpty(noticeRegionBo.getCityCode()), PartnerBo::getCityCode, noticeRegionBo.getCityCode())
                    .eq(StringUtils.isNotEmpty(noticeRegionBo.getAreaCode()), PartnerBo::getAreaCode, noticeRegionBo.getAreaCode()));
            }
            wp.and(i -> orWrapper);
```

### 报错信息
无报错信息

**Comment by miemieYaho** [comment]
p.and(i -> {
for (NoticeRegionBo noticeRegionBo : noticeRegionList) {
                i.or(w -> w.eq(StringUtils.isNotEmpty(noticeRegionBo.getProvinceCode()), PartnerBo::getProvinceCode, noticeRegionBo.getProvinceCode())
                    .eq(StringUtils.isNotEmpty(noticeRegionBo.getCityCode()), PartnerBo::getCityCode, noticeRegionBo.getCityCode())
                    .eq(StringUtils.isNotEmpty(noticeRegionBo.getAreaCode()), PartnerBo::getAreaCode, noticeRegionBo.getAreaCode()));
            }
});
