### ISSUE TITLE
saveOrUpdate 时报错

### ISSUE THREAD

**Issue by xutingyin** [baomidou/mybatis-plus#1749]
### 该问题是怎么引起的？
调用saveOrUpdate(...)

### 报错信息
java.lang.RuntimeException: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: error: can not execute. because can not find cache of TableInfo for entity!
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: error: can not execute. because can not find cache of TableInfo for entity!

**Comment by miemieYaho** [comment]
自己检测你的代码,mapper没扫描到
