### ISSUE TITLE
代码生成插件能否支持把Alias_Base_Column_List也生成下

### ISSUE THREAD

**Issue by wangzhanxu** [baomidou/mybatis-plus#1753]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
GlobalConfig#setBaseColumnList设置true后会生成Base_Column_List，但是通常来说，需要自定义sql时，一般都会存在需要连表的情况，此时Base_Column_List并不好用，希望官方能直接支持Alias_Base_Column_List的生成

**Comment by qmdx** [comment]
自定义下吧
