### ISSUE TITLE
怎么通过注入方法实现表名通过参数传入？

### ISSUE THREAD

**Issue by Mairuis** [baomidou/mybatis-plus#1756]
# 版本
3.2.0

# 问题
我怎么能通过自定义注入实现通过参数将表名传入？
比如我有这种表 Login_20191030 Login_20191029
但是所有Login表的结构都一样，可以通过自定义注入实现下面这种操作吗？

```java
Login login_20191030 = LoginMapper.selectByDate("20191030");
```

**Comment by miemieYaho** [comment]
我们提供的不支持,你可以自己注入你自己的,看文档里有
