### ISSUE TITLE
使用注解 @TableId(value = "id", type = IdType.UUID)

### ISSUE THREAD

**Issue by w5185552** [baomidou/mybatis-plus#1757]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用mybatis的
org.apache.ibatis.plugin.Interceptor拦截器获取不到自动生成的主键

**Comment by miemieYaho** [comment]
那拦截的是在填充了id之前

**Comment by w5185552** [comment]
我应该怎么拦截比较合适，求大神指教。

**Comment by miemieYaho** [comment]
debug [MybatisDefaultParameterHandler](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/MybatisDefaultParameterHandler.java) 自己看执行先后顺序

**Comment by miemieYaho** [comment]
这不是你能指定的,自己看先执行 MybatisDefaultParameterHandler 还是先执行插件,再根据结果自己想办法
