### ISSUE TITLE
文档defaultEnumTypeHandler好像有误

### ISSUE THREAD

**Issue by DreamXiao** [baomidou/mybatis-plus#1760]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
发现@EnumValue有误查阅文档，提示需要使用com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler : 枚举类需要实现IEnum接口或字段标记@EnumValue注解.
但是发现这个类不存在，存在的是com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

**Comment by nieqiurong** [comment]
在3.1.1之前是那个类来着，但3.1.1之后改名,文档稍微调整一下.
