### ISSUE TITLE
代码自动生成插件希望支持不同的文件生成到不同的目录

### ISSUE THREAD

**Issue by wujw2017** [baomidou/mybatis-plus#1761]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

这不是一个bug。只是希望能提供新的功能。
现在很多spring-boot项目都是多model的（xxx-api，xxx-service，xxx-persist等等）。
目前导出文件只能用fileOutConfigList和tableInfo 2个类还自定义输出。实现特别繁琐。
希望能重构一下，再tableInfo中加入一个属性：output，可以自定义输出到哪个目录下。
目录支持占位符，这样就能直接用配置来修改输出路径。

**Comment by qmdx** [comment]
tableInfo 改动量较大，目前自定义输出模式虽然配置繁琐但是逻辑更加清晰
