### ISSUE TITLE
mapper接口多表联查分页,参数封装到bean,报错

### ISSUE THREAD

**Issue by Muyuping** [baomidou/mybatis-plus#1765]
### 当前使用版本(必须填写清楚，否则不予处理)

版本3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

IPage<Bill> method1(Page<Bill> pageInfo,@Param("param1") String param1)

这样写是没问题的，但是当我参数过多时，是封装到一个对象中的，写成

IPage<Bill> method2(Page<Bill> pageInfo, BillDto billDto)
这样就会报错，请问是不支持还是有其他写法

### 报错信息

Parameter 'payDateStart' not found. Available parameters are [pageInfo, billDto, param1, param2]

**Comment by miemieYaho** [comment]
IPage method2(Page pageInfo, @param("dto") BillDto billDto)

xml 里 dto. payDateStart 取值
