### ISSUE TITLE
使用LambdaQueryWrapper处理dto时，.select(column) 会导致getColumn报错

### ISSUE THREAD

**Issue by lockielyKIM** [baomidou/mybatis-plus#1767]
### 当前使用版本(必须填写清楚，否则不予处理)

版本： 3.1.2

### 重现步骤
Wrappers.lambdaQuery(new BrandDto()).select(BrandDto::getName).
由于这里的BrandDto 没有在TableInfoHelper中缓存 lambda， 所以导致报错了， 默认只缓存了TableInfo的实体。

### 报错信息

**Assert.notNull(columnCache, "can not find lambda cache for this property [%s] of entity [%s]",
            fieldName, aClass.getName());**

**Comment by miemieYaho** [comment]
就这样的
