### ISSUE TITLE
无法整合shardingJDBC分页一起使用

### ISSUE THREAD

**Issue by xr2117** [baomidou/mybatis-plus#1769]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

与ShardingJDBC 实现分表查询进行分页时候 出现异常。 

### 重现步骤
        Page<Goods1> page = new Page<>(1, 2);
        QueryWrapper<Goods1> query = Wrappers.query();
        IPage<Goods1> iPage = goods1Mapper.selectPage(page, query);

### 报错信息
"nested exception is org.apache.ibatis.exceptions.PersistenceException: \r\n### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : \n SELECT COUNT(1) FROM goods \n\r\n### The error may exist in com/frame/provider/mapper/Goods1Mapper.java (best guess)\r\n### The error may involve defaultParameterMap\r\n### The error occurred while setting parameters\r\n### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : \n SELECT COUNT(1) FROM goods \n"

**Comment by xr2117** [comment]
不知道是不是他们框架问题 分页使用Long类型会报转换异常

**Comment by xr2117** [comment]
org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination包下

    private int getValue(final PaginationValueSegment paginationValueSegment, final List<Object> parameters) {
        return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment
                ? (int) parameters.get(((ParameterMarkerPaginationValueSegment) paginationValueSegment).getParameterIndex())
                : ((NumberLiteralPaginationValueSegment) paginationValueSegment).getValue();
    }

无法把long转为int 所以抛出异常

**Comment by miemieYaho** [comment]
用shardingJDBC最新版
