### ISSUE TITLE
升级2.0版本后发现整合的ehcache不能自动刷新了

### ISSUE THREAD

**Issue by hanyi366** [baomidou/mybatis-plus#177]
升级到2.0后查询分页使用正常，新增或者删除数据后不会自动刷新缓存，会造成脏数据，请问这个如何决解，是不是因为分页引起的？

**Comment by qmdx** [comment]
自动刷新的话会引入二次查询，因此默认是不建议开启/ 推荐 service 层缓存，如果一定要用缓存分页，更好插件为 com.baomidou.mybatisplus.plugins.CachePaginationInterceptor

**Comment by hanzhenchaoGit** [comment]
CachePaginationInterceptor缓存分页不管用  查询时翻页一直返回的是缓存里的第一页数据
