### ISSUE TITLE
整合ShrdingJDBC问题

### ISSUE THREAD

**Issue by xr2117** [baomidou/mybatis-plus#1770]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0
ShrdingJDBC也是最新版

## ShardingJDBC源码

    private int getValue(final PaginationValueSegment paginationValueSegment, final List<Object> parameters) {
        return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment
                ? (int) parameters.get(((ParameterMarkerPaginationValueSegment) paginationValueSegment).getParameterIndex())
                : ((NumberLiteralPaginationValueSegment) paginationValueSegment).getValue();
    }
 Page对象创建分页条件是long类型 shardingJDBC使用的int 造成转换异常

### 重现步骤
整合Sharding 使用分页即可出现

### 报错信息
 Cause: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

**Comment by gm-xiao** [comment]
最终怎样了，我这边也是这个问题

**Comment by gm-xiao** [comment]
换成4.0.0就可以了
