### ISSUE TITLE
关于getObj方法的问题

### ISSUE THREAD

**Issue by XiaoBaiSAMA** [baomidou/mybatis-plus#1772]
当前使用版本：3.2.0
使用service的getObj(Wrapper<T> queryWrapper, Function<? super Object, V> mapper)和listObjs(Wrapper<T> queryWrapper, Function<? super Object, V> mapper)
以及对应的mapper的方法时，返回的都是查询出来的表内的第一个字段的值，但是打印出来的却是全部查询出来的sql语句，这里是不是应该查询整个对象出来？因为我看到它还有一个参数是转换器Function，这方法名和参数列表看起来就像是应该这么用的：
XXXDto dto = this.getObj(wrapper,Converter::convert);
因为在IPage里也有一个类似的转换器的方法，所以getObj这个方法是否是个bug？

**Comment by miemieYaho** [comment]
obj就是一个对象而不是任何entity

**Comment by XiaoBaiSAMA** [comment]
getObj查出来的是表里第一个字段的值的包装类（如果是自增id那就是个Integer），这个方法到底有什么用？

**Comment by miemieYaho** [comment]
有什么用那你去问 mybatis 吧
