### ISSUE TITLE
分页插件中，当请求的页码超过总页数，可否返回最后一页的数据？

### ISSUE THREAD

**Issue by xingkong6648** [baomidou/mybatis-plus#1773]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
目前我们在使用分页插件时，若请求的页码超过总页数，会返回首页或者空数据，但是我们希望返回的是最后一页的数据，这样可以保持用户操作的连续性，不必再从第一页翻到最后一页。可否修改下，以支持这个需求，谢谢！

**Comment by miemieYaho** [comment]
等最新版,自己去重写相关规则
