### ISSUE TITLE
springboot升级到2.2.0,在idea下正常启动,部署到tomcat8或者9报错

### ISSUE THREAD

**Issue by yejianmail** [baomidou/mybatis-plus#1774]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus 3.2.0
springboot 2.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

从springboot 2.1.x升级到springboot 2.2.0

### 重现步骤
在idea下使用springboot内嵌的tomcat能正常启动,
打包成war放到tomcat下就会出现报错,

### 报错信息
以下报错信息截取自csdn一个网友的,我的报错和其一样,解决方式同样是降级到springboot2.1.x

    报错信息1：
    Error creating bean with name 'articleController': Unsatisfied dependency expressed through field 'articleService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'articleService': Unsatisfied dependency expressed through field 'articleDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'articleDao' defined in file [E:\tomcat8\apache-tomcat-8.5.40\webapps\kshonblog\WEB-INF\classes\top\annokshon\kshonblog\dao\ArticleDao.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.
    报错信息2：
    Error creating bean with name 'mybatis-org.mybatis.spring.boot.autoconfigure.MybatisProperties': Could not bind properties to 'MybatisProperties' : prefix=mybatis, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis.configuration.mapped-statements[0].parameter-map.parameter-mappings[0]' to org.apache.ibatis.mapping.ParameterMapping

**Comment by yejianmail** [comment]
@miemieYaho 怎么被close掉了,有解决方案或者别的issue参考么?

**Comment by miemieYaho** [comment]
你不会自己搜一下 issue?

**Comment by yejianmail** [comment]
@miemieYaho 我先是搜索了,然后那个issue#1372里面说的根本不是解决办法,我的项目里面没有依赖jasypt,别的也被你close掉了,难道要使用mp3只能止步于springboot2.2.0

**Comment by dengjin001** [comment]
升级到springboot 2.2.1 或者2.2.0的版本新建spring.properties加上spring.jndi.ignore = true

**Comment by yejianmail** [comment]
@dengjin001 已测试有效,特来感谢大神!
