### ISSUE TITLE
关于QueryWrapper优化建议

### ISSUE THREAD

**Issue by fizzxue** [baomidou/mybatis-plus#1775]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
1.  使用QueryWrapper查询时，如值为null，还会生成对应sql的where条件
如 new QueryWrapper().eq("id", null),还会生成 where id = null这种条件。能否在plus里做非空判断？
2. 使用QueryWrapper<Object> qw = new QueryWrapper<>(new Object());
做过滤时会自动生成对应属性的eq条件，能否增加功能qw.like("字段名")，
这样就不用写qw.like("字段名"，字段值)了。

### 重现步骤
1.            QueryWrapper<SystemInfo> qw = new QueryWrapper<>();
            String systemType = systemInfo.getSystemType();
            Optional.ofNullable(systemType).ifPresent(str -> qw.eq("system_type", str));
目前每个实体属性都要做非空判断，很难受。。
2.  QueryWrapper<SystemInfo> qw = new QueryWrapper<>(systemInfo);
qw.like("system_type", systemInfo.getSystemType());//感觉这样写很麻烦，plus可否做个判断，如构造QueryWrapper时已传入实体，则调用qw.like("system_type"）即可做查询过滤
### 报错信息
无报错，只是为了使用上更方便提的一点建议。如果你们没时间，我可以提pr吗？

**Comment by miemieYaho** [comment]
自己判空

**Comment by fizzxue** [comment]
@miemieYaho 如果热爱，请用心做好！如果不，请。。。（你这样我要去用jpa了，一个我你不怕，那全中国的我你怕了吗？）

**Comment by miemieYaho** [comment]
你以为人人都要判空?,别拿你的需求当大家的需求,想去用jpa就去用,别打嘴炮

**Comment by fizzxue** [comment]
@miemieYaho 厉害厉害了，国产开源软件出了你这号人也是可喜可贺啊，转到知乎给你出个名吧

**Comment by miemieYaho** [comment]
去吧,zz
