### ISSUE TITLE
 from db1.table 怎么做到

### ISSUE THREAD

**Issue by wangriyue001** [baomidou/mybatis-plus#1776]
### 当前使用版本(必须填写清楚，否则不予处理)
任意版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

datasouce : jdbcUrl 不直接指定默认数据库 
`jdbc:mysql://xxx:3306`
用户权限能查db0下的表,有可以查db1下的表。
实体@TableName 目前做不到这种功能

**Comment by miemieYaho** [comment]
做不到
