### ISSUE TITLE
insertBatch时设置useGeneratedKeys取回ID为null，插入失败应该是

### ISSUE THREAD

**Issue by WeiYang1005** [baomidou/mybatis-plus#1777]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

批量insert操作时设置操作为useGeneratedKeys="true" keyProperty="id"情况下，id不做任何注解，取回的id为null

### 重现步骤
随便重现

### 报错信息

Error getting generated key or setting result to parameter object. Cause:java.lang.NullPointerException

报错位置：.../mybatis/3.5.1/mybatis-3.5.1.jar!/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.class
方法：Entry
代码：boolean singleParam = paramMap.values().stream().distinct().count() == 1L;

lamba表达式抛出空指针

**Comment by miemieYaho** [comment]
随便重现是怎么个重现法?

**Comment by WeiYang1005** [comment]
是mybatis更新版本后出现的问题，sorry
