### ISSUE TITLE
updateBatchById  更新后没有将mybatis的二级缓存清除。

### ISSUE THREAD

**Issue by lockielyKIM** [baomidou/mybatis-plus#1781]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

v3.1.2

### 重现步骤

updateBatchById  更新后没有将mybatis的二级缓存清除。

**Comment by nieqiurong** [comment]
最好提供一份代码,方便看.

**Comment by lockielyKIM** [comment]
类ServiceImpl中的代码片段
    @Transactional(rollbackFor = Exception.class)
    @Override
    public boolean saveBatch(Collection<T> entityList, int batchSize) {
        String sqlStatement = sqlStatement(SqlMethod.INSERT_ONE);
        try (SqlSession batchSqlSession = sqlSessionBatch()) {
            int i = 0;
            for (T anEntityList : entityList) {
                batchSqlSession.insert(sqlStatement, anEntityList);
                if (i >= 1 && i % batchSize == 0) {
                    batchSqlSession.flushStatements();
                }
                i++;
            }
            batchSqlSession.flushStatements();
        }
        return true;
    }
这个方法没有将缓存清除， 需要重写覆盖后， 手工调用batchSqlSession.commit(); 来进行清除才可以。
