### ISSUE TITLE
mybatis-plus-boot-starter依赖与nacos的配置动态更新有冲突

### ISSUE THREAD

**Issue by pengliaoye** [baomidou/mybatis-plus#1782]
### 当前使用版本(必须填写清楚，否则不予处理)
starter版本3.2.0，nacos使用的是spring cloud alibaba 2.1.0.RELEASE

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我通过spring cloud方式与nacos集成。在Bean上加了@RefreshScope。然后注入的成员
变量值会动态更新。

但是我一添加mybatis-plus-boot-starter依赖，动态更新就不生效了。去掉就可以。

好像也会导致spring context在重启，看日志一直在什么started

**Comment by miemieYaho** [comment]
那就是不支持

**Comment by pengliaoye** [comment]
dataId=device-management.yaml, group=DEFAULT_GROUP, md5=47ca20e30c14fe06d35eaf7534d73419, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@67d7f4bc tx={}

org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.incomplete-cache-refs[0].assistant.configuration.mapped-statements[0].result-maps[0]' to org.apache.ibatis.mapping.ResultMap

**Comment by pengliaoye** [comment]
<spring-boot.version>2.2.1.RELEASE</spring-boot.version>
    <spring-cloud.version>Hoxton.RC1</spring-cloud.version>
    <spring-cloud-alibaba.version>2.1.0.RELEASE</spring-cloud-alibaba.version>
<artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>

**Comment by pengliaoye** [comment]
第二次更新就生效了

**Comment by Alvinnlee** [comment]
你可以 试下  在Nacos客户端 最后一行结束时候  再加一个换行  会提示语法有问题 但是没有影响 @RefreshScope就有效了   我是这么解决的
