### ISSUE TITLE
mapper内置的查询可否增加支持@ResultMap指定自定义resultMap

### ISSUE THREAD

**Issue by q578135872** [baomidou/mybatis-plus#1783]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
当实体类中存在实体嵌套时，如：
public class A  {
    private String fieldA;
    private int fieldB;
    private B objB;
}
使用mybatisplus内置的查询（如xxMapper.selectPage(page, queryWrapper);），无法查出嵌套的B类实体字段数据。
在xxMapper（自定义的业务Mapper）中override方法selectPage(page, queryWrapper)，并使用@ResultMap注解指定xml里自定义的resultMap无效（该自定义的resultMap使用了collection标签关联实体字段）。mapper代码示例如下：
    @Override
    @ResultMap("skinResult")
    IPage<Skin> selectPage(IPage<Skin> page, @Param("ew") Wrapper<Skin> queryWrapper);

是否是因为mybatisplus的mapper层实现指定了resultType，没有对mapper中重写的方法增加的@ResultMap做判断导致的呢？

可否考虑让BaseMapper<T>子类中的查询方法在解析执行时，如果有@Override（参数签名及返回类型完全一样，仅仅是增加了@ResultMap指定自定义的resultMap结果映射）的情况，并且重写的方法有@ResultMap注解，则将查询结果的resultMap设置为用户指定的值？

### 重现步骤

非报错类问题

### 报错信息
非报错类问题

**Comment by miemieYaho** [comment]
method 改个名,别 override
