### ISSUE TITLE
二级缓存对自定义方法上使用Options注解没有作用

### ISSUE THREAD

**Issue by lockielyKIM** [baomidou/mybatis-plus#1784]
### 重现步骤
调用MybatisMapperAnnotationBuilder类的GlobalConfigUtils.getSqlInjector(configuration).inspectInject(assistant, type);方法后，
会注入自定义的方法， 但是没有将方法上的注解Options进行解析， 导致二级缓存失效。

**Comment by miemieYaho** [comment]
不会解析任何注解

**Comment by miemieYaho** [comment]
你怎么加上注解的?

**Comment by nieqiurong** [comment]
增加自定义方法注入的时候,默认查询select的useCache注入都是为true的.

**Comment by lockielyKIM** [comment]
使用了自定义的BaseMapper , 由super-mapper-class 进行设置的，  导致加上二级缓存失效， 见代码MybatisMapperAnnotationBuilder类的
// TODO 注入 CURD 动态 SQL , 放在在最后, because 可能会有人会用注解重写sql
            if (GlobalConfigUtils.isSupperMapperChildren(configuration, type)) {
                GlobalConfigUtils.getSqlInjector(configuration).inspectInject(assistant, type);
            }
片段。  此片段没有对注解Options进行处理。

**Comment by miemieYaho** [comment]
不支持任何注解
