### ISSUE TITLE
mapper接口 insert方法出现问题

### ISSUE THREAD

**Issue by yuhou615** [baomidou/mybatis-plus#1786]
### mapper接口 insert方法出现问题。用的最新的版本 3.2.0
代码： userMapper.insert(user);

### 该问题是怎么引起的？
有可能并非引起，偶然发生的。

### 重现步骤

线上偶然发生的

### 报错信息
错误：
 INSERT INTO user  ( id,  alliance_platform_info, show_platforml_key,     show_platform_code,   bid, user_code )  VALUES  ( ?,                                                                                                        ?, ?,     ?,   ?, ? )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'oXT8C5XUDyvsuPYj_6TtM9b6q164-2' for key 'show_platform_c                                                                                                      ode'
; Duplicate entry 'oXT8C5XUDyvsuPYj_6TtM9b6q164-2' for key 'show_platform_code'; nested exception is java.sql.SQLIntegrityConstraintVio                                                                                                      lationException: Duplicate entry 'oXT8C5XUDyvsuPYj_6TtM9b6q164-2' for key 'show_platform_code'

oXT8C5XUDyvsuPYj_6TtM9b6q164-2
show_platforml_key 应该是 oXT8C5XUDyvsuPYj_6TtM9b6q164
show_platform_code 应该是 2
oXT8C5XUDyvsuPYj_6TtM9b6q164-2 变成了show_platform_code插入的值了。

**Comment by qmdx** [comment]
正确的执行sql 如果出现你说的问题那么就是你业务赋值不对
