### ISSUE TITLE
不支持create语句

### ISSUE THREAD

**Issue by LesliePie** [baomidou/mybatis-plus#1787]
### 当前使用版本(必须填写清楚，否则不予处理)
# 3.1.2版本不支持建表语句

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

由所引用的jsqlparse1.2抛出的不支持create 关键字

### 报错信息
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "CREATE" "CREATE"
    at line 1, column 1.

Was expecting one of:

    "("
    ";"
    "ALTER"
    "CALL"
    "COMMIT"
    "DELETE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SELECT"
    "SET"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "WITH"

**Comment by miemieYaho** [comment]
给 jsqlparse 提
