### ISSUE TITLE
查询时 实体有继承 结果集与父类属性映射不上

### ISSUE THREAD

**Issue by xiaozhaorong** [baomidou/mybatis-plus#1790]
### 当前使用版本(必须填写清楚，否则不予处理)
<version>3.2.0</version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用查询 实体有继承时 结果集与父类属性映射不上

### 重现步骤
实体A
![image](https://user-images.githubusercontent.com/41188311/68558663-1d734600-0475-11ea-84f3-d9ecc86df283.png)
新建一个实体B 继承A
![image](https://user-images.githubusercontent.com/41188311/68558716-4b588a80-0475-11ea-98d6-2c9dfeaf34ec.png)
创建查询操作
![image](https://user-images.githubusercontent.com/41188311/68558802-9d011500-0475-11ea-9ebf-e6d0c988004a.png)
![image](https://user-images.githubusercontent.com/41188311/68558823-b2763f00-0475-11ea-9c82-4a02a0730f87.png)
执行查询 结果集映射不上
![image](https://user-images.githubusercontent.com/41188311/68558881-e0f41a00-0475-11ea-9f12-390a0f17fd0c.png)
可是直接把实体A的属性写到实体B 又可以正常映射
![image](https://user-images.githubusercontent.com/41188311/68558953-38928580-0476-11ea-86d4-23a1def49d8a.png)

### 报错信息
无报错信息

**Comment by miemieYaho** [comment]
虽然我知道答案,但我不告诉你,你自己去找.友情提示: lombok
