### ISSUE TITLE
字段类型处理器，处理JSON 数组，丢失泛型

### ISSUE THREAD

**Issue by wenrjay** [baomidou/mybatis-plus#1793]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

   @TableField(value = "position", typeHandler = FastjsonTypeHandler.class)
    private List<TenantMemberPositionJsonDTO> positions;

### 报错信息

![image](https://user-images.githubusercontent.com/19367422/68579528-4c0e1280-04af-11ea-8b11-3c1556499f8d.png)

**Comment by miemieYaho** [comment]
自己去百度typehandler

**Comment by wenrjay** [comment]
您好，通过反射方式无法取出 List中的泛型参数，目前使用数组方式可处理JSON数组反序列化带来的问题。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: miemieYaho <notifications@github.com>
发送时间: Monday, November 11, 2019 10:02:52 PM
收件人: baomidou/mybatis-plus <mybatis-plus@noreply.github.com>
抄送: wenrjay <glyl@live.cn>; Author <author@noreply.github.com>
主题: Re: [baomidou/mybatis-plus] 字段类型处理器，处理JSON 数组，丢失泛型 (#1793)


自己去百度typehandler

―
