### ISSUE TITLE
代码生成器可否支持View？

### ISSUE THREAD

**Issue by wwhai** [baomidou/mybatis-plus#1794]
### 当前使用版本(必须填写清楚，否则不予处理)
版本：3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用了Mysql的视图

### 重现步骤
用代码生成器从视图生成代码

### 报错信息

```
22:56:06.904 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
表 [user_role_view] 在数据库中不存在！！！
```

**Comment by nieqiurong** [comment]
估计没时间搞.

**Comment by freshgeek** [comment]
我使用的是
            <version>3.2.0</version>
设置
strategy.setSkipView(false);
        是可以正常生成视图的 不过视图对应的主键配置会丢失,但可以正常生成对应的实体属性id

**Comment by freshgeek** [comment]
> ### 当前使用版本(必须填写清楚，否则不予处理)
> 版本：3.2.0
> 
> ### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
> 使用了Mysql的视图
> 
> ### 重现步骤
> 用代码生成器从视图生成代码
> 
> ### 报错信息
> ```
> 22:56:06.904 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
> 表 [user_role_view] 在数据库中不存在！！！
> ```

我使用的是
3.2.0
设置
strategy.setSkipView(false);
是可以正常生成视图的 不过视图对应的主键配置会丢失,但可以正常生成对应的实体属性id

**Comment by wwhai** [comment]
> > ### 当前使用版本(必须填写清楚，否则不予处理)
> > 版本：3.2.0
> > ### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
> > 使用了Mysql的视图
> > ### 重现步骤
> > 用代码生成器从视图生成代码
> > ### 报错信息
> > ```
> > 22:56:06.904 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
> > 表 [user_role_view] 在数据库中不存在！！！
> > ```
> 
> 我使用的是
> 3.2.0
> 设置
> strategy.setSkipView(false);
> 是可以正常生成视图的 不过视图对应的主键配置会丢失,但可以正常生成对应的实体属性id

3Q,我试试.
