### ISSUE TITLE
自定义分页传参问题

### ISSUE THREAD

**Issue by limengyong** [baomidou/mybatis-plus#1797]
### 当前使用版本(必须填写清楚，否则不予处理)
版本：3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
自定义分页的时候，比如IPage<User> selectPageVo(Page page, @Param("state") Integer state);
这是官网的例子，但是如果我的第二个参数是Map或者对象就不行了，我也没法指定Param，所以就报非法参数异常，我记得2.0的时候还是可以传map的。

### 报错信息
Available parameters are [page, map, param1, param2]

**Comment by miemieYaho** [comment]
@param("xx") Map map

xml: xx.id

**Comment by zhangxiucai12** [comment]
解决方法有效
