### ISSUE TITLE
SqlHelper中tabel()方法 返回的tableInfo为空意味着什么

### ISSUE THREAD

**Issue by Linfini** [baomidou/mybatis-plus#1809]
版本:
3.2.0
问题:
自定义IBaseSerivce和自定义IbaseMapper 

### 报错信息
Error: Cannot execute table Method, ClassGenricType not found .

PS.SqlHelper 中table方法 tableInfo为空,我不太明白这是啥意思.

**Comment by miemieYaho** [comment]
entity没有初始化成功,对应的mapper调用会出现 binding 异常

**Comment by Linfini** [comment]
> entity没有初始化成功,对应的mapper调用会出现 binding 异常

那我需要怎么做.Entity初始化还是手动操作啥吗,不应该自动扫描Mapper的泛型吗

**Comment by miemieYaho** [comment]
是自动扫描，没扫描到就检查你的配置

**Comment by Linfini** [comment]
我大概也许可能知道了 ,我没有使用MybatisSqlSessionFactoryBean.
