### ISSUE TITLE
updateById不能触发typeHandler

### ISSUE THREAD

**Issue by shenbinglife** [baomidou/mybatis-plus#181]
版本：
<mybatisplus-spring-boot-starter.version>1.0.5</mybatisplus-spring-boot-starter.version>
 <mybatisplus.version>2.1.4</mybatisplus.version>
mybatis的版本应该是mybaits plus中带的3.4.5版本

问题：在使用insert方法和selectList方法都能正常触发typeHandler，但是updateById方法不行。

配置：
springboot的application.properties
```
mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml  
mybatis-plus.type-aliases-package=com.XX.domain  
#主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";  
mybatis-plus.global-config.id-type=3  
#字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"  
mybatis-plus.global-config.field-strategy=2  
#驼峰下划线转换  
mybatis-plus.global-config.db-column-underline=true  
#刷新mapper  
mybatis-plus.global-config.refresh-mapper=true  
mybatis-plus.global-config.meta-object-handler=com.XX.MybatisMetaObjectHandler  
mybatis-plus.configuration.map-underscore-to-camel-case=true  
mybatis-plus.configuration.cache-enabled=false  
mybatis-plus.type-handlers-package=com.XX.mybatis  
```

**Comment by qmdx** [comment]
试下 @TableField(el = "role, typeHandler=com.baomidou.xx.typehandler.PhoneTypeHandler")

**Comment by shenbinglife** [comment]
谢谢，这确实解决了这个问题。并且我的写法是`@TableField(el = "extend, javaType=java.util.Map, jdbcType=VARCHAR")`，这样应该可以将typeHandler与字段更好的解耦，注册好的typeHandler可以自动触发。
关于这个问题，网上一直找不到相关的解答，也不知道是不是我的搜索关键字有问题。建议在官网文档上添加这个问题的解决办法。

**Comment by qmdx** [comment]
我们是不推荐 el 的使用方法的，所有文档故意没有说

**Comment by shenbinglife** [comment]
但是mp框架本身对typeHandler支持不好吧，只能通过el才能支持。如题，updateById方法总是无法触发typeHandler。 还是说这算是一个需要你们处理的bug？建议让mp的updateById方法能自动根据参数类型触发typeHandler。
