### ISSUE TITLE
关于com.baomidou.mybatisplus.core.toolkit.SystemClock

### ISSUE THREAD

**Issue by wangzhanxu** [baomidou/mybatis-plus#1810]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
不是BUG，我看到这个类是为了”高并发场景下System.currentTimeMillis()的性能问题的优化“，为了优化System.currentTimeMillis()，而使用了一个线程每隔1ms更新缓存在内存里的时钟，这应该要带来大量的CPU上下文切换。考虑到写数据的场景，真的需要在极短时间内产生大量的id么？
当然，也确实不好判断，维持着这么一个更新时钟的线程会对服务器性能产生多少的影响，但是还是觉得应该要综合判断一下，这样做是否得不偿失。

**Comment by nieqiurong** [comment]
3.2.1支持自定义.
```java
    @Bean
    public IdGenerator idGenerator() {
        return new SnowflakeIdGenerator(new Sequence() {
            @Override
            protected long timeGen() {
                return System.currentTimeMillis();
            }
        });
    }
```
