### ISSUE TITLE
Mybatis3关于order by字段存在SQL注入的问题

### ISSUE THREAD

**Issue by EyoungShieh1992** [baomidou/mybatis-plus#1811]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用page.setAsc或page.setDesc设置要order by的字段

### 重现步骤
后台代码：
Page<TbUser> page = new Page<>(pageRequest.getPageNumber(), pageRequest.getPageSize(), true);
        if ("asc".equals(pageRequest.getSord())) {
            page.setAsc(StringUtils.toUnderlineCase(pageRequest.getSidx()));
        } else {
            page.setDesc(StringUtils.toUnderlineCase(pageRequest.getSidx()));
        }
postman测试：
![image](https://user-images.githubusercontent.com/31103392/68817886-112df980-06be-11ea-9c8f-f59deb5646d5.png)

### 报错信息
无报错，直接成功了
![image](https://user-images.githubusercontent.com/31103392/68817920-315db880-06be-11ea-86bb-7c43b553f0ad.png)

**Comment by qmdx** [comment]
这部分就是 sql 拼接的你需要自己判断
