### ISSUE TITLE
性能插件问题

### ISSUE THREAD

**Issue by kingflyok** [baomidou/mybatis-plus#1812]
1、对于3.2.0中移除的性能插件，是否可以增加上，其实对于我们初学者还是很有用处
2、第二就是达梦数据库我用的3.1.2版本，输出的并不是SQL语句

**Comment by kingflyok** [comment]
第二个问题可以忽略，第一个问题就是可否恢复？

**Comment by miemieYaho** [comment]
不会恢复

**Comment by qmdx** [comment]
请使用https://mp.baomidou.com/guide/p6spy.html 这个插件一样的效果，另外你一定需要 copy 出来放在自己的工程
