### ISSUE TITLE
LambdaUtils.createColumnCacheMap 可能存在实体字段缺失

### ISSUE THREAD

**Issue by chaiyunhao** [baomidou/mybatis-plus#1821]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 重现步骤

com.baomidou.mybatisplus.core.toolkit.LambdaUtils.createColumnCacheMap
缓存实体字段 MAP 信息时,由于 MAP 的 key，默认是对字段名进行 toUpperCase
实体中如果存在大写后字段名相同的情况，MAP 中会缺失字段
eg：testAb testaB

**Comment by miemieYaho** [comment]
mybatis 的 entity 字段取缓存就是这样的,建议你改属性和字段名
