### ISSUE TITLE
多表连接查询不使用xml可以吗？

### ISSUE THREAD

**Issue by zouyaowen** [baomidou/mybatis-plus#1828]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
QueryWrapper<DoctorDO> query = new QueryWrapper<>();

### 报错信息
目前查询操作都是但表操作，多表操作只能写SQL？可以不写吗？？？

**Comment by zouyaowen** [comment]
目前版本是3.2.0版本，版本写错了，抱歉

**Comment by qmdx** [comment]
不行 mp 解决的是单表问题，如果多表你也想非 xml 推荐 hibernate

**Comment by zouyaowen** [comment]
> 不行 mp 解决的是单表问题，如果多表你也想非 xml 推荐 hibernate

谢谢，明白了
