### ISSUE TITLE
sqlserver 2012 插入数据时候IDENTITY_INSERT

### ISSUE THREAD

**Issue by houpe** [baomidou/mybatis-plus#183]
## Cause: java.sql.SQLException: 当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'sys_resource' 中的标识列插入显式值。
; SQL []; 当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'sys_resource' 中的标识列插入显式值。; nested exception is java.sql.SQLException: 当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'sys_resource' 中的标识列插入显式值。

_### #IDENTITY_INSERT sql 解决办法：
### 1.有一项数据(message_id)如是自动添写的。把那列删掉就可以写进去了。 具体为：
原始："insert into user_message(message_id,user_id,message_content) Values(11,333,'hahaha')";  //报错
改成："insert into user_message(user_id,message_content) Values(333,'hahaha')";_

# **但是，用mp自带的方法，插入对象，都会带这个主键啊，咋办啊**

**目前尝试**
主键 @tableid(value = "id", type = IdType.AUTO)
insert可以用
insertBatch好像还是不行

**Comment by houpe** [comment]
主键 @TableId(value = "id", type = IdType.AUTO)
insert可以用
insertBatch好像还是不行

**Comment by qmdx** [comment]
还未解决请入 qq 群
