### ISSUE TITLE
3.2.0 代码构造器别名怎么指定？

### ISSUE THREAD

**Issue by q-corder** [baomidou/mybatis-plus#1830]

**Comment by q-corder** [comment]
Parameter 'ew' not found. Available parameters are [wp, param1]

**Comment by miemieYaho** [comment]
@param

**Comment by q-corder** [comment]
我就是用这个注解指定别名 wp  但是报错了，Parameter 'ew' not found. Available parameters are [wp, param1]

**Comment by miemieYaho** [comment]
只能ew
