### ISSUE TITLE
如何设置参数Page的size默认值

### ISSUE THREAD

**Issue by mengmakies** [baomidou/mybatis-plus#1831]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
`public R<IPage<User>> getUserPage(Page page, @RequestParam("type")Long type) {
        return R.ok(sysPediaService.getSystemUserList(page, type));
    }`
如果不传size，默认为每页显示10条数据，如何单独设置默认size为20？
类似PageableDefault注解：
`getUserPage(@PageableDefault(page=1, size=20) Pageable page)`

**Comment by nieqiurong** [comment]
可以自己实现IPage.
