### ISSUE TITLE
com.baomidou.mybatisplus.mapper.BaseMapper导入该包时为什么调用BaseMapper的方法会报错？

### ISSUE THREAD

**Issue by cloudswzy** [baomidou/mybatis-plus#1833]
### 当前使用版本(必须填写清楚，否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generate</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.29</version>
        </dependency>
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
调用继承自BaseMapper的方法报错

### 重现步骤
1.使用代码生成器生成代码mapper层默认导入包为import com.baomidou.mybatisplus.mapper.BaseMapper;
使用该包调用selectList会报错

2.当将包替换为import com.baomidou.mybatisplus.core.mapper.BaseMapper;
测试运行正常

### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.wzy.test.dao.UserMapper.selectList

刚入门的新人，使用代码生成器后生成代码然后写了个例子直接报错，然后百度各种都没有效果，最后把官网demo下载下来一个个对比，然后发现dao层导入的包少了个core，抱着试一试的心态加了，然后就好了...不知道为什么就好了，所以想来问一下。提前谢谢诸位dalao回复。

**Comment by miemieYaho** [comment]
版本号统一 3.2.0

**Comment by cloudswzy** [comment]
> 版本号统一 3.2.0

老哥，啥意思？我导入的包都是用的都是maven里最新的，版本号统一 3.2.0这个应该怎么做？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples

**Comment by cloudswzy** [comment]
> https://github.com/baomidou/mybatis-plus-samples

我做对比用的包就是找的里面的quick-start工程，里面dao层导入的包是import com.baomidou.mybatisplus.core.mapper.BaseMapper，然而我用2.3.3版本的代码生成器生成的代码在mapper层导入的包是import com.baomidou.mybatisplus.mapper.BaseMapper，包路径中间少了一个core，导致用一般的方式调用BaseMapper里的基础方法会报错。
