### ISSUE TITLE
继承BaseMapper之后，直接调用insert方法，出现Invalid bound statement (not found)

### ISSUE THREAD

**Issue by pobc** [baomidou/mybatis-plus#1835]
### 当前使用版本(必须填写清楚，否则不予处理)
jdk1.8
mybatis-plus 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我自己写的CustomMapper接口继承BaseMapper，然后在其他地方调用 insert方法，就会报Invalid bound statement (not found)，我没有写mapper对应的.xml文件，请问CustomMapper 对应的.xml文件一定要写吗？

### 重现步骤
自定义一个Mapper接口，继承BaseMapper，然后在其他地方调用insert方法

### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.able.tbk.web.history.mapper.PlatformGoodsMapper.insert

**Comment by a401554998** [comment]
继承BaseMapper<model类>  同时model中需要定义好表名称。

**Comment by pobc** [comment]
> 继承BaseMapper<model类> 同时model中需要定义好表名称。

这是我的Mapper类，
```
public interface PlatformGoodsMapper extends BaseMapper<PlatformGoodsPO> {}
```
这是我的实体类，
```
@TableName("platform_goods")
public class PlatformGoodsPO extends Model<PlatformGoodsPO>{....}
```
@TableName 
两种都试过了，但是不行
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotations.TableName;

在调用insert的时候，还是会报如上的错误.
mapper报的扫描配置也加了

**Comment by miemieYaho** [comment]
bound 异常就是没扫描到mapper,自己检测

**Comment by AngelaERP** [comment]
请问您这个问题解决了吗？
