### ISSUE TITLE
关于java实体和数据库字段都是驼峰风格，mp生成的sql语句自动转换为下划线风格

### ISSUE THREAD

**Issue by alexluojian** [baomidou/mybatis-plus#1838]
版本3.2.0，使用mybatis-plus-boot-starter

如User实体有一个字段为createTime，数据库里的字段名也是createTime，但是mp生成的查询语句会自动转换为下划线风格：
Execute SQL：SELECT id,create_time,name,update_time,email,age FROM user
造成数据库报错：
Cause: java.sql.SQLSyntaxErrorException: Unknown column 'create_time' in 'field list'

请问有相关配置，关掉此转换吗？

**Comment by miemieYaho** [comment]
https://mybatis.plus/config/#mapunderscoretocamelcase
