### ISSUE TITLE
没有全量跟新方法

### ISSUE THREAD

**Issue by wuzhaozhongguo** [baomidou/mybatis-plus#1839]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
没有全量更新的方法，我想把某些字段改为null。

### 重现步骤
com.baomidou.mybatisplus.core.mapper.BaseMapper#updateById方法

**Comment by wuzhaozhongguo** [comment]
用UpdateWrapper太麻烦了，希望能增加以前mybatis generate生成的那种有全量更新又有增量更新方法

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6
