### ISSUE TITLE
updateAllColumnById 什么时候补充啊

### ISSUE THREAD

**Issue by 171998110** [baomidou/mybatis-plus#1840]
![754339fdb074a9f689f7b9693d99db5](https://user-images.githubusercontent.com/13607689/69228266-3ccd4a00-0bbe-11ea-9164-14e3e69c2721.png)

![e79d13dd3fe5856e1e423635d134da6](https://user-images.githubusercontent.com/13607689/69228311-4e165680-0bbe-11ea-8132-f1c4126bef6d.png)

清空没有updateAll该怎么写

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6
