### ISSUE TITLE
逻辑删除NULL设置

### ISSUE THREAD

**Issue by 86993225** [baomidou/mybatis-plus#1841]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

logic-delete-value: "null" 时会拼接成 set delete is null,mysql不支持该语法，只能set delete = null

### 重现步骤

logic-delete-value: "null"

**Comment by miemieYaho** [comment]
? 你确定是未删除有值,已删除是null?

**Comment by 86993225** [comment]
是的，UPDATE ec_site SET is_delete is NULL
&nbsp;WHERE id=6 AND is_delete='0';
我现在只能自己写mybatis拦截修改


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miemieYaho"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 下午4:58
收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;"陈利"<86993225@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 逻辑删除NULL设置 (#1841)




? 你确定是未删除有值,已删除是null?

**Comment by miemieYaho** [comment]
你这种逻辑删除字段不是null就是一个固定值的有什么意义吗？

**Comment by 86993225** [comment]
逻辑删除是null，可以增加唯一索引




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miemieYaho"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 下午5:48
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "陈利"<86993225@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] 逻辑删除NULL设置 (#1841)




你这种逻辑删除字段不是null就是一个固定值的有什么意义吗？

**Comment by miemieYaho** [comment]
那同一数据多次创建删除呢？

**Comment by 86993225** [comment]
多次删除也一样，只要删除字段为空就可以，唯一索引支持这种



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miemieYaho"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 晚上6:06
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "陈利"<86993225@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] 逻辑删除NULL设置 (#1841)




那同一数据多次创建删除呢？

**Comment by miemieYaho** [comment]
你说的唯一索引是单一字段值唯一的那个索引?

**Comment by 86993225** [comment]
有逻辑删除的话需要组合建索引，类似：ALTER TABLE ec_site ADD UNIQUE `site_code_is_delete` ( site_code , is_delete ) USING BTREE;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miemieYaho"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 晚上6:16
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "陈利"<86993225@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] 逻辑删除NULL设置 (#1841)




你说的唯一索引是单一字段值唯一的那个索引?

**Comment by miemieYaho** [comment]
使用 3.2.1.2-SNAPSHOT 版本, [测试用例](https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-logic-delete/src/test/java/com/baomidou/mybatisplus/samples/logic/SampleTest.java)
