### ISSUE TITLE
批量插入很慢

### ISSUE THREAD

**Issue by damacheng009** [baomidou/mybatis-plus#1842]
### 当前使用版本(必须填写清楚，否则不予处理)
        <dependency>
		    <groupId>com.baomidou</groupId>
		    <artifactId>mybatis-plus-boot-starter</artifactId>
		    <version>3.2.0</version>
	</dependency>

### 重现步骤
使用代码生成器，用生成的service类调用saveBatch方法，插入几十条数据都需要几秒钟
请问该怎么优化？

**Comment by qmdx** [comment]
service  层的批量支持海量数据跨各种数据库方案，如果数据量小且为 mysql 可以装载 https://mp.baomidou.com/guide/crud-interface.html#insertbatchsomecolumn
