### ISSUE TITLE
新增数据时能否自动塞逻辑默认值，不需要在代码里手动的赋值

### ISSUE THREAD

**Issue by yuhangtdm** [baomidou/mybatis-plus#1843]

**Comment by huayanYu** [comment]
neng

**Comment by yuhangtdm** [comment]
试了用代码配置，类似插入时间那种可以。但是文档里没有其他实现方式------------------ 原始邮件 ------------------
发件人: "小锅盖"<notifications@github.com>
发送时间: 2019年11月21日(星期四) 晚上11:02
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com>;
抄送: "yuhangtdm"<649411629@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [baomidou/mybatis-plus] 新增数据时能否自动塞逻辑默认值，不需要在代码里手动的赋值 (#1843)



neng
 
&mdash;
