### ISSUE TITLE
类上无@TableId时使用updateById会报错no getter for property named 'null'

### ISSUE THREAD

**Issue by JayGuAtGitHub** [baomidou/mybatis-plus#1848]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在使用updateById方法时, 如果类上没有任何字段为@TableId, 会提示报错信息
There is no getter for property named 'null' in 'class com.***.model.data.***'
建议可以改为更友好的提示(比如class *** 需要@TableId)

**Comment by miemieYaho** [comment]
如果 entity 没有指定主键, 启动时就会有 warn 级别信息
