### ISSUE TITLE
批量插入可能会同时写入两条数据,而且这样会导致mybatis拦截器无法拦截。。。

### ISSUE THREAD

**Issue by pog2g** [baomidou/mybatis-plus#1849]
批量插入数据会同时写入两条吗？？？？？

![image](https://user-images.githubusercontent.com/48884933/69417337-72576c00-0d53-11ea-8209-9ed36d282369.png)
需要怎么才能避免，，因为出现这种数据mybatis拦截器无法拦截。。我不知道是mp的错还是mybatis的错

**Comment by miemieYaho** [comment]
执行一个 mapper.method 只会执行一条sql,如果出现两条那就是拦截器没写对

**Comment by pog2g** [comment]
不是拦截器没写对好吧，，，如果没写对其他为什么正常。。只有批量插入batchsize为1时永远正常

发自我的iPhone

在 2019年11月22日，18:15，miemieYaho <notifications@github.com> 写道：

﻿

执行一个 mapper.method 只会执行一条sql,如果出现两条那就是拦截器没写对

**Comment by miemieYaho** [comment]
那你最好给出你的复现demo

**Comment by pog2g** [comment]
已经测试，，去掉拦截器也会出现。。晚点会提交一个最简化案例

发自我的iPhone

在 2019年11月22日，19:27，miemieYaho <notifications@github.com> 写道：

﻿

那你最好给出你的复现demo

**Comment by pog2g** [comment]
# 最小案例地址
```
git@github.com:pog2g/demo.git
```
# 启动后访问地址(swagger ui选择batch size 为默认)
```
http://127.0.0.1:8080/demo/swagger-ui.html
```

# 运行日志截图
<img width="1590" alt="1" src="https://user-images.githubusercontent.com/48884933/69443978-633fe080-0d8a-11ea-9282-332de63457c7.png">

**Comment by miemieYaho** [comment]
因为用的是 batch sqlsession, 就算你裸用 mybatis 指定默认 sqlsession 类型是 batch 结果也是一样的
