### ISSUE TITLE
实体关键字

### ISSUE THREAD

**Issue by liyuan0420** [baomidou/mybatis-plus#1850]
### 当前使用版本(必须填写清楚，否则不予处理)
最新版本3.x

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据实体反射成SQL的别名为关键字，像一些常用的字段，password，create等等。官方文档建议自己解决我觉得不合理，起码主流的关系型数据库，Oracle，MySql，SqlServer这些可以加上吧。况且本身是个好东西为啥你要去掉呢。

**Comment by miemieYaho** [comment]
使用关键字并不是什么好事情,你非要用就自己多加点配置: 比如全局 columnFormat,字段注解里自己用转义符包裹之类

**Comment by liyuan0420** [comment]
我数据库没有使用关键字，我实体关键字是常用的吧？像一些 create，passowrd这些字段名不常用？你说出来我都不行，使用率高达85%吧

**Comment by miemieYaho** [comment]
下个版本有全局配置 propertyFormat
