### ISSUE TITLE
mybatisplus service批量时会同时入两条数据。。

### ISSUE THREAD

**Issue by pog2g** [baomidou/mybatis-plus#1851]
service的批量方法会同时入两条数据(两条不同的数据同时入库)：

调用方法:  boolean result = personService.saveBatch(list);某条插入会两条数据同时入库，，
调用方法: boolean result = personService.saveBatch(list,1);一切正常

![image](https://user-images.githubusercontent.com/48884933/69423073-337be300-0d60-11ea-81f6-4c1ccca3848d.png)

这个批量不是单条处理一起提交吗？？为啥会出现两条同时插入。。
怎么会出现类似于:insert(id,name)values()()拼接sql的情况。

**Comment by pog2g** [comment]
# 最小案例地址。
```
git@github.com:pog2g/demo.git
```

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/1849
