### ISSUE TITLE
高版本中没有CachePaginationInterceptor类如何实现分页缓存？

### ISSUE THREAD

**Issue by Zbuter** [baomidou/mybatis-plus#1853]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

包中没有CachePaginationInterceptor类，请问如何实现分页缓存。

**Comment by nieqiurong** [comment]
用3.2.1.1-SNAPSHOT试试,按正常的分页处理即可.
