### ISSUE TITLE
mybatis-plus.global-config.db-config.select-strategy = NOT_EMPTY不生效

### ISSUE THREAD

**Issue by yuhangtdm** [baomidou/mybatis-plus#1856]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
配置文件配了
mybatis-plus.global-config.db-config.select-strategy = NOT_EMPTY
代码里
 LambdaQueryWrapper<BrandDO> queryWrapper = Wrappers.lambdaQuery(brandDO)
                .like(BrandDO::getName, requestDTO.getName())
                .like(BrandDO::getEnglishName, requestDTO.getEnglishName())
                .eq(BrandDO::getFirstLetter, requestDTO.getFirstLetter());
传参：
requestDTO的name为null时
null依然拼接在sql中
请问：select-strategy = NOT_EMPTY该配置不是全局的？？？？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/1779
