### ISSUE TITLE
请问MybatisPLus支持连接MongoDB4.x吗？尤其是分页

### ISSUE THREAD

**Issue by arraycto** [baomidou/mybatis-plus#1857]
### 当前使用版本(必须填写清楚，否则不予处理)
1.mybatis Plus v3.2.0

### 该问题是怎么引起的？** 
请问MybatisPLus支持连接MongoDB4.x吗？
例如使用MybatisPlus进行MongoDB的分页和crud操作。

**Comment by miemieYaho** [comment]
你能用mybatis就能用 mp, 分页不支持
