### ISSUE TITLE
IService的saveOrUpdate（）方法NUll和0的问题

### ISSUE THREAD

**Issue by arraycto** [baomidou/mybatis-plus#1858]
### 当前使用版本(必须填写清楚，否则不予处理)

1.MybatisPlus3.2.0

### 该问题是怎么引起的？ 

进行saveOrUpdate操作引起的。

### 重现步骤

1.mysql数据库，数据库表User的status的字段是tinyint类型。默认值是null
2.继承mybatisPlus封装的Iservice接口，使用saveOrUpdate（inserOrUpdate）方式，JavaBean 的set属性，setStatus=0.。若数据库无记录的时候saveOrUpdate插入数据正常，但是status值是null，已不是0.不符合要求。update的时候正常、
### 报错信息
数据库的status值应该为0却为null

**Comment by miemieYaho** [comment]
本质就是调用mapper层的接口,自己排查
