### ISSUE TITLE
mybatis-plus-generator，不支持生成的jdbcType

### ISSUE THREAD

**Issue by zhangfang1993** [baomidou/mybatis-plus#1859]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
反向生成工具中，开启 BaseResultMap后，mapper.xml.vm模版中没有jdbcType这个属性，为什么不支持，自定义的话，加上jdbcType="${field.columnType}"，不会是正确的jdbcType，比如字段是bigint，应该是jdbcType=“BIGINT”，但是生成后是jdbcType="LONG"

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/generator.html#%E5%AD%97%E6%AE%B5%E5%85%B6%E4%BB%96%E4%BF%A1%E6%81%AF%E6%9F%A5%E8%AF%A2%E6%B3%A8%E5%85%A5
