### ISSUE TITLE
mybatisplus 生成的id 是19位的有可能超出mysqlbigint的长度，数据库用什么类型呢，或者这个id生成的位数可以变么

### ISSUE THREAD

**Issue by yj348382870** [baomidou/mybatis-plus#1860]

**Comment by miemieYaho** [comment]
bigint 范围 = java long 的范围,不存在超长,默认不支持自定义长度,
下个版本新增 com.baomidou.mybatisplus.core.incrementer.IdGenerator 接口,你可以自己注入(@Bean方式) 改变默认生成id的方法
