### ISSUE TITLE
BaseEntity  Id 策略如何设置？

### ISSUE THREAD

**Issue by hyzhan43** [baomidou/mybatis-plus#1865]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

你好，我想问下 如果自定义一个 BaseEntity 基类，存储着  id、create_time等等字段，id 的策略该如何配置呢？  尝试在 基类  id 字段 加上 @TableId(type = IdType.AUTO) 配置无效，全局配置也无效，还是会采用 默认 id 策略

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by hyzhan43** [comment]
刚刚新建了测试项目测试了一下，发现没有问题，然后对比检查原项目，不管怎么测试一直都是 11位数左右的 id，不是我定义的 IdType.AUTO策略，然后我把表删了，重新创建就正常了。具体原因不太清楚。。

**Comment by miemieYaho** [comment]
雪花ID可不是止11位，现在是20位
