### ISSUE TITLE
xml sql 利用 collection 实现一对多查询出现错误

### ISSUE THREAD

**Issue by LLH2019** [baomidou/mybatis-plus#1866]
### 当前使用版本(必须填写清楚，否则不予处理)
版本：3.2.0
 当使用xml 自写SQL 利用collection 实现一对多查询出现错误，错误如下
![image](https://user-images.githubusercontent.com/46324430/69552579-a348d280-0fd9-11ea-87c5-8e5156a61547.png)

我的实现步骤如下
1、首先有一实体类 MaintenanceType， 如下
![image](https://user-images.githubusercontent.com/46324430/69552733-f0c53f80-0fd9-11ea-9f2f-0d9d697b5c19.png)

2、然后另外一实体类 RelativeStandardItemFlowVO， 如下，包含MaintenanceType组成的List数组

![image](https://user-images.githubusercontent.com/46324430/69552838-1baf9380-0fda-11ea-8941-644dbb1c2ee3.png)

3、一实体类 StandardItemFlowAndType， 如下， 包含maintenanceTypeId 以及
![image](https://user-images.githubusercontent.com/46324430/69553104-895bbf80-0fda-11ea-9723-8f91eac90d0c.png)

3、在XML中 首先根据一id  查询 standard_item_flow_and_type表， 然后 将得到的是由多个 maintenance_type_id_ 字段
![image](https://user-images.githubusercontent.com/46324430/69554027-1bb09300-0fdc-11ea-9202-c5dfca88d504.png)

4、根据得到的maintenance_type_id_ 字段进行查询，将得到的数据保存到RelativeStandardItemFlowVO里面的List<MaintenanceType>中
![image](https://user-images.githubusercontent.com/46324430/69554013-14898500-0fdc-11ea-8995-76d067703515.png)

5、 collection 中select操作
![image](https://user-images.githubusercontent.com/46324430/69554045-2408ce00-0fdc-11ea-915b-39b7ff4476cc.png)

debug 信息如下
1、 根据 id=1198902560660942850 进行查询， 得到三个值
![image](https://user-images.githubusercontent.com/46324430/69554283-8661ce80-0fdc-11ea-967b-41b9e2a725ad.png)

2、第一个值 1198892983529893890 进行查询
![image](https://user-images.githubusercontent.com/46324430/69554399-b4471300-0fdc-11ea-9177-00ef5b34b443.png)

3、第二个值1198893039276388353 进行查询
![image](https://user-images.githubusercontent.com/46324430/69554476-cde85a80-0fdc-11ea-9415-c88f45ae999d.png)

4、第三个值 1198893054933725186 进行查询
![image](https://user-images.githubusercontent.com/46324430/69554524-e22c5780-0fdc-11ea-9946-e45becb50e97.png)

得到报错信息如下：
![image](https://user-images.githubusercontent.com/46324430/69554593-fb350880-0fdc-11ea-8e7d-a876390809ea.png)

打开DefaultSqlSession.java:80 可以看到 
![image](https://user-images.githubusercontent.com/46324430/69554684-1a339a80-0fdd-11ea-80eb-772a9a034e3e.png)

因此可以看到是由于调用selectOne 函数原因，但是我尝试了很多方法，不知道为什么都一直调用这个函数，而不是selectList

谢谢，由于该错误是在实际开发中遇到的，所以有些地方可能不太简洁明了，望见谅！

**Comment by LLH2019** [comment]
各位道兄，这个问题有遇到过吗？

**Comment by miemieYaho** [comment]
你把 collection 标签里ofType属性填上试试

**Comment by LLH2019** [comment]
ofType 改为与依然出现相同的错误
![image](https://user-images.githubusercontent.com/46324430/69698059-37708200-111f-11ea-8b2a-34610211c433.png)

**Comment by miemieYaho** [comment]
ofType 是你 list 装的那个类

**Comment by miemieYaho** [comment]
https://mybatis.org/mybatis-3/zh/sqlmap-xml.html#Result_Maps

**Comment by LLH2019** [comment]
还是不行
![image](https://user-images.githubusercontent.com/46324430/69701257-7efb0c00-1127-11ea-883d-41189b4feb4e.png)

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-resultmap
新鲜的示范,自己对照着看吧
