### ISSUE TITLE
3.1.2批量更新仅更新一条问题

### ISSUE THREAD

**Issue by if2018** [baomidou/mybatis-plus#1867]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

updateBatchById批量更新无法实现批量更新

### 重现步骤

使用updateBatchById进行批量更新操作

### 报错信息

无报错信息
![image](https://user-images.githubusercontent.com/35320255/69605876-4b06e480-105c-11ea-8ce1-44a90e65e359.png)
![image](https://user-images.githubusercontent.com/35320255/69605906-5ce88780-105c-11ea-8b3f-86ba79fe6f97.png)

**Comment by miemieYaho** [comment]
用了最新版再说

**Comment by if2018** [comment]
> 用了最新版再说

好的谢谢，我升级试试

**Comment by if2018** [comment]
> 用了最新版再说

升级新版本后还是无法批量更新，saveOrUpdateBatch也是同样的问题，仅更新了第一条，查询全部都有查询
![image](https://user-images.githubusercontent.com/35320255/69607503-565c0f00-1060-11ea-85b4-d4a2341177fc.png)

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/69609414-6544c080-1064-11ea-8c51-9ccf4091e209.png)
你这个不是显示了更新5条?
