### ISSUE TITLE
3.2.0 selectList数据数量对,但是数据都为空;sql查询返回数据也正常

### ISSUE THREAD

**Issue by yfdxzy2010** [baomidou/mybatis-plus#1869]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？
2.3版本正常.但是使用3.2.0版本时,selectList数据数量对,但是数据都为空;sql查询返回数据也正常;从控制台日志,sql查询也正常
 typeAliasesPackage;extends BaseMapper<>;都已经配置

### 报错信息
没有报错信息

**Comment by huayanYu** [comment]
建议自行断点调试。 一般sql正常就没问题。 自己检查业务代码+断点调试。

**Comment by yfdxzy2010** [comment]
断点调试了,list就是数量对,对象都是null;2.3就正常
