### ISSUE TITLE
如何同时使用自定义全局操作Injector和逻辑删除Injector

### ISSUE THREAD

**Issue by Humphrey0822** [baomidou/mybatis-plus#187]
`public class GlobalConfiguration implements Serializable {

    // 逻辑删除全局值
    private String logicDeleteValue = null;
    // 逻辑未删除全局值
    private String logicNotDeleteValue = null;
    // 数据库类型
    private DBType dbType;
    // 主键类型（默认 ID_WORKER）
    private IdType idType = IdType.ID_WORKER;
    // 表名、字段名、是否使用下划线命名（默认 false）
    private boolean dbColumnUnderline = false;
    // SQL注入器
    private ISqlInjector sqlInjector;
    // 表关键词 key 生成器
    private IKeyGenerator keyGenerator;`
GlobalConfiguration 中属性只含有一个ISqlInjector对象，如何同时使用自定义全局操作Injector和逻辑删除Injector两个ISqlInjector呢？

**Comment by qmdx** [comment]
继承逻辑删除注入器
