### ISSUE TITLE
能否提供多查一条,从而知道是否有下一页的功能

### ISSUE THREAD

**Issue by sinc3721** [baomidou/mybatis-plus#1871]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
没有在不取总数的情况下,判断是否存在下一页的功能

**Comment by huayanYu** [comment]
没有，这个功能如果后台做必定要查count，或者另外的sql语句。
数据量变动不大，建议前端首页查count, 后面的都不查。 前端自己判断是否有下一页。
