### ISSUE TITLE
3.2.0 版本 selectList 报错， Parameter 'status' not found. Available parameters are [ew, param1]

### ISSUE THREAD

**Issue by yunlonggong** [baomidou/mybatis-plus#1872]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0 （有问题）
3.0.1 （正常）

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
正常访问 selectList 方法就会报错

### 重现步骤
QueryWrapper<T> queryWrapper = new QueryWrapper<>();
queryWrapper.eq("column_name", column_value);
mapper.selectList(queryWrapper);

### 报错信息
org.apache.ibatis.binding.BindingException: Parameter 'status' not found. Available parameters are [ew, param1]

**Comment by yunlonggong** [comment]
selectList 方法在 3.2.0 版本中会报该错误，但是在 3.0.1 版本是正常的，所以简单的临时解决办法是降低版本，使用低版本的 3.0.1 是正常的

**Comment by miemieYaho** [comment]
自行排查
