### ISSUE TITLE
3.2.0 集成的mybatis有问题     3.2.0 selectList数据数量对,但是数据都为空;sql查询返回数据也正常

### ISSUE THREAD

**Issue by yfdxzy2010** [baomidou/mybatis-plus#1873]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0 

### 该问题是怎么引起的？
3.2.0 sql查询结果和实体类映射问题

### 重现步骤

Caused by: org.apache.ibatis.session.SqlSessionException: 
Unknown column is detected on 'Dao.selectList' auto-mapping. 
Mapping parameters are [columnName=p_id,propertyName=p_id,propertyType=null]

### 报错信息
at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)

如果时xml,可在xml中配置,没有xml怎么办?

**Comment by miemieYaho** [comment]
你要配啥?能把话说清楚?

**Comment by yfdxzy2010** [comment]
/**
     * 是否自动构建 resultMap 并使用
     * 如果设置 resultMap 则不会进行 resultMap 的自动构建并注入
     * 只适合个别字段 设置了 typeHandler 或 jdbcType 的情况
     *
     * @since 3.1.2
     */
    boolean autoResultMap() default false;      真坑

**Comment by miemieYaho** [comment]
所以呢?
