### ISSUE TITLE
mybatis plus 3.2.0 ，id_work_str ，在docker容器下，一个应用开启多个副本，同一个表生成的主键ID重复

### ISSUE THREAD

**Issue by keason10** [baomidou/mybatis-plus#1877]

**Comment by keason10** [comment]
已经解决相关问题，单元测试，同一个应用3个容器，对同一个表生成的ID不再重复。
1. plus 3.2.0 使用mac 地址和 进程pid作为雪花算法参数，3个容器，1000并发的时候，有7条主键冲突。
2.目前我单元测试，使用mac地址和ip地址作为雪花算法参数，3个容器5000并发，没有主键冲突。

**Comment by miemieYaho** [comment]
docker 下 无法获取真实的 mac
