### ISSUE TITLE
复杂查询例如is_del = 0 and disabled = 0 and (title like '%s%' or title like '%t%') 在3.x如何实现

### ISSUE THREAD

**Issue by flaw0r** [baomidou/mybatis-plus#1878]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
复杂查询例如is_del = 0 and disabled = 0 and (title like '%s%' or title like '%t%');
titile是动态的，一个不固定长度的list中取得
在3.0以上如何实现？2.x版本有andNew

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/wrapper.html#and
