### ISSUE TITLE
希望能增加一个数据库关键字处理功能.

### ISSUE THREAD

**Issue by Swain9** [baomidou/mybatis-plus#188]
如下代码所示:
使用1处代码会报错
必须的用2处的代码

    public ResultBean list(@RequestParam Map<String, Object> params) {

        PageInfo<SystemConfig> pageInfo = new PageInfo<>(params);
        EntityWrapper<SystemConfig> wrapper = new EntityWrapper<>();
        if (params.get("key") != null) {
            String key = (String) params.get("key");
            1.wrapper.like("key", key);
            2.wrapper.like("`key`", key);
        }
        //查询列表数据
        Page<SystemConfig> page = systemConfigService.selectPage(pageInfo, wrapper);
        //return new ResultBean(new EasyUIPageBean(list.getTotal(), list.getRecords()));
        BootstrapPageBean pageBean = new BootstrapPageBean(page.getRecords(), page.getTotal(), page.getSize(), page.getCurrent());

        return new ResultBean(pageBean);

    }

**Comment by qmdx** [comment]
wrapper 灵活性太大，底层不好彻底处理 这种情况希望自己处理，或者避免出现 关键词
