### ISSUE TITLE
请问一下在切换数据源的情况下，第一次分页还是会连接的默认启动的数据库，会报错

### ISSUE THREAD

**Issue by locedubo** [baomidou/mybatis-plus#1881]
### 当前使用版本(必须填写清楚，否则不予处理)
我的是2.1.8版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我的多数据源切换时。通过MethodInterceptor获取路劲从而setDataSourceKey数据源切换，在有分页的情况下，下面这个调用的时候回连接默认数据源，虽然数据源显示切换了，但是在第一次的时候还是报错了。
PageHelper.startPage(pageNum, pageSize);
是开始默认连接默认数据源的。造成报错

### 重现步骤
在切换数据源的情况下
 PageHelper.startPage(pageNum, pageSize);
会第一次默认连接默认数据库，第二次才转换过来，如何在第一次改变数据源的时候，分页也默认切换过去。

### 报错信息
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'tadopmodel.data_test' doesn't exist

**Comment by qmdx** [comment]
2.x 不在维护请自行解决
