### ISSUE TITLE
新功能 ：支持replace方式插入数据库

### ISSUE THREAD

**Issue by Liesport758** [baomidou/mybatis-plus#1883]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

如题。以replace into方式 插入数据库

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/guide/sql-injector.html 自己注入
