### ISSUE TITLE
LambdaCache 找不到泛型中的属性

### ISSUE THREAD

**Issue by czyhome** [baomidou/mybatis-plus#1884]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0 或者 3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

我有复现的工程项目
3.1.0 不会出现此类情况

### 重现步骤
启动工程
请求 localhost:8075/user/load

### 报错信息
"nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not find lambda cache for this property [createdDate] of entity [com.team.domain.infrastructure.base.MybatisBaseEntity]]

**Comment by miemieYaho** [comment]
LambdaCache 只支持basemapper 泛型的entity,如果你要玩花的不支持

**Comment by czyhome** [comment]
> LambdaCache 只支持basemapper 泛型的entity,如果你要玩花的不支持

好吧

**Comment by czyhome** [comment]
兄弟 ,lambdaCache 的逻辑在什么位置

> LambdaCache 只支持basemapper 泛型的entity,如果你要玩花的不支持

兄弟 ,lambdaCache 的逻辑在什么位置

**Comment by miemieYaho** [comment]
tqbleinfohelper。 abstractlambawrapper
