### ISSUE TITLE
不能区分mysql的describe关键字？

### ISSUE THREAD

**Issue by Tansky0** [baomidou/mybatis-plus#1885]
### 当前使用版本(必须填写清楚，否则不予处理)
使用版本：3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
字段名字describe，执行save()方法时会认为describe是普通字段，一直报错

**Comment by miemieYaho** [comment]
看文档
