### ISSUE TITLE
配置动态数据源，无法自动填充

### ISSUE THREAD

**Issue by xiaosTyy** [baomidou/mybatis-plus#1886]
### 当前使用版本(必须填写清楚，否则不予处理)
版本3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
配置了动态数据源，无法自动填充。

### 重现步骤
![image](https://user-images.githubusercontent.com/39477475/69799528-674a8300-120e-11ea-9ee4-f4b008697c20.png)

**Comment by miemieYaho** [comment]
哪个培训班出来的? [MybatisPlusConfig](https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/config/MybatisPlusConfig.java)
