### ISSUE TITLE
自动生成`CRUD`代码 并在关键字上自动添加@TableField注解

### ISSUE THREAD

**Issue by 1314cc** [baomidou/mybatis-plus#1887]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter:3.2.0
hikaricp:3.2.0

### 该问题是怎么引起的？
mysql 关键字问题

### 背景
我在使用自动生成CRUD的功能时候, 自定义了模板. 生成代码后发现`mysql`关键字会引起`sql`解析异常. 查看了下相关`issue`,  发现可以使用`@TableField` 解决. 

### 问题
**如何在自动生成`CRUD`代码的时候,进行自动判断是否为关键字. 然后自动添加`@TableField`注解**

**Comment by miemieYaho** [comment]
不支持,自行规范数据库字段命名或者自己手动加
