### ISSUE TITLE
updateBatchById()批量更新LocalDatetTime时间多了8个小时

### ISSUE THREAD

**Issue by love-jay** [baomidou/mybatis-plus#1888]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus版本是3.1.2版本.

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
当批量更新时间的时候，实体时间是LocalDateTime ,更新后会导致时间更新多8个小时.
mysql 连接配置添加了&serverTimezone=Asia/Shanghai指定了上海时区.
其中mysql中数据类型是datetime类型.

### 重现步骤
从数据库中查询出数据后，给LocalDateTime字段赋值后,进行updateBatchById()操作。更新的结果发现时间多了8小时

**Comment by miemieYaho** [comment]
自己排查,mp不会对数据做处理
