### ISSUE TITLE
提个优化page的使用方式

### ISSUE THREAD

**Issue by a364176773** [baomidou/mybatis-plus#1889]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

比如在使用xxxService.page,通常我们需要new一个page,或者接收一个page,但是我们有一个接口需要返回2张表以上的分页信息的时候,又不是联查的情况下,代码就比较麻烦了,得new超过2个page对象.
提个建议,是否可以直接改为:
xxxxService.page(qw,1,10)类似这样的形式,或者直接xxxxService.list(qw).page(1,10),之类的,这样使用上,代码更加的简洁.

**Comment by miemieYaho** [comment]
无意义，page并不大
