### ISSUE TITLE
可以为ServiceImpl中的XXXByIds的方法中加上空白集合的判断吗？

### ISSUE THREAD

**Issue by immimij** [baomidou/mybatis-plus#1890]
### 当前使用版本(必须填写清楚，否则不予处理)

version: 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

因为执行sql如 select * from a where id in () 这样的语句会报错，
每次调用XXXByIds方法前都要判断一下集合是否为空，
可以为ServiceImpl中的XXXByIds的方法中加上空白集合的判断吗？

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/91db7070d9c7439812c192fecb8088a1a28283cb

**Comment by tangjizhou** [comment]
@qmdx  你好 请问一下  查询的时候 没有做空集合判断 这个是有什么出于什么考虑呢 ?
