### ISSUE TITLE
queryWrapper采用实体注解方式,自定义mapper方法不起作用

### ISSUE THREAD

**Issue by bestitxq** [baomidou/mybatis-plus#1893]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我们想使用注解方式 @TableField(condition = SqlCondition.LIKE), 进行数据的赋值,但是在自己写的mapper里并没有插入条件

### 重现步骤
我们使用注解方式 @TableField(condition = SqlCondition.LIKE), 对请求参数做查询操作,queryWrapper使用的是实体构造器赋值的, mapper.xml中已经加入了${ew.customSqlSegment}, 但是在自己写的mapper里并没有插入实体的查询条件,用自带的查询方式可以实现,但是我们是多表查询,必须自己写mapper中的sql,请问有什么解决方式吗?

**Comment by miemieYaho** [comment]
可以说有,也可以说没有,自己debug断点看各种注入的sql,例如: SelectList.java

**Comment by bestitxq** [comment]
嗯,我看到了,只不过重写的话多个类都需要重写,包括service层继承的ServiceImpl也需要进行封装过后才可以正常使用,这样就得不偿失了,有大神可以封装一个自定义的就好了
