### ISSUE TITLE
能否提供 json字符串存取功能

### ISSUE THREAD

**Issue by xiaozxiaozz** [baomidou/mybatis-plus#1894]
需求:
### 当前使用版本
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
        </dependency>

### 是怎么引起的？
      能否,实现 json字符串存取功能.
      如果可以将提供很大的方便.很多扩展属性很方便存取计算和扩展.
      比如user.address信息  (也许可以参考枚举typeHander的实现)
      class User{
          @TableId
          Long id;
          Address address;
      }

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-typehandler
