### ISSUE TITLE
官网文档代码排版问题

### ISSUE THREAD

**Issue by yaoyuanbj** [baomidou/mybatis-plus#1898]
### 当前使用版本(必须填写清楚，否则不予处理)
最新文档

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

这个地方没有空格，代码排版看着难受

### 重现步骤
官网浏览

### 报错信息

![image](https://user-images.githubusercontent.com/3211909/69912383-9574d080-1463-11ea-8b18-50d4ae98664c.png)

**Comment by nieqiurong** [comment]
移步  https://github.com/baomidou/mybatis-plus-doc
