### ISSUE TITLE
Entity 能否添加重写toString的strategy

### ISSUE THREAD

**Issue by mpthink** [baomidou/mybatis-plus#19]
最近使用中发现entity template中没有tostring的重写，对于POJO来说，tostring可以使调试更加方便，希望下一版本中能添加这一配置

**Comment by Caratacus** [comment]
感谢支持,不过没打算去支持toString方法,个人需要可以自行拓展

**Comment by qmdx** [comment]
@mpthink   自定义下模板接口实现

**Comment by mpthink** [comment]
非常谢谢，我已经按照文档在摸版里面添加了
