### ISSUE TITLE
集成quartz 2.2.1

### ISSUE THREAD

**Issue by w5185552** [baomidou/mybatis-plus#1900]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter  3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
集成quartz 2.2.1

### 重现步骤
![图片](https://user-images.githubusercontent.com/24616689/69927900-c51fe900-14f4-11ea-93d3-6192193fb3af.png)

### 报错信息
![图片](https://user-images.githubusercontent.com/24616689/69927919-d8cb4f80-14f4-11ea-9636-510ba2bbc73f.png)

**Comment by miemieYaho** [comment]
自己排查

**Comment by w5185552** [comment]
![图片](https://user-images.githubusercontent.com/24616689/69936903-14c1dd00-1514-11ea-9a93-5d1852a0b39d.png)
就是这里出现了警告，请问有什么办法解决吗？

**Comment by w5185552** [comment]
![图片](https://user-images.githubusercontent.com/24616689/69937486-e6dd9800-1515-11ea-886b-132c183b19ab.png)
