### ISSUE TITLE
数据库数据插入成功，但是返回主键id为null

### ISSUE THREAD

**Issue by Misaniy** [baomidou/mybatis-plus#1902]
### 当前使用版本(必须填写清楚，否则不予处理)
spring boot 2.1.6 RELEASE
mysql-connector-java 8.0.18
mybatis-plus 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库

### 重现步骤
@Data
entity{
    @TableId( type = IdType.INPUT)
    private Integer id;
    private String name;
}

public interface entityMapper extends BaseMapper<entity>
Entity params = new entity();
params.setName("name");
entityMapper.insert(params);
System.out.println(params.getId());

### 报错信息
控制台打印
null

**Comment by Misaniy** [comment]
driver-class-name: com.mysql.cj.jdbc.Driver
type: com.zaxxer.hikari.HikariDataSource

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/guide/annotation.html#tableid
