### ISSUE TITLE
注解冲突@Column&@TableField

### ISSUE THREAD

**Issue by xi63** [baomidou/mybatis-plus#1904]
### 当前使用版本(必须填写清楚，否则不予处理)
使用版本:3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
![image](https://user-images.githubusercontent.com/18697011/69955147-f2da5180-1537-11ea-95b4-b40883a1a699.png)
这种数据库为id,实体类中为java实体对象的情况, 我必须用 实体类中city属性去映射 数据库中的 city 字段, 原本我想用city 通过 @Column 去映射到 数据库中的 city_id 但是 不起作用, 必须改为 city 对应city 
奇怪的是: 
![image](https://user-images.githubusercontent.com/18697011/69955370-73994d80-1538-11ea-8b89-8fdd5b4b9023.png)
创建人这种 createBy 映射 create_by 的这种情况 可以正常映射！
这种现象,麻烦大佬给指点下迷津！感谢

**Comment by xi63** [comment]
理想效果如下：但是暂时无法实现
![image](https://user-images.githubusercontent.com/18697011/69955669-2b2e5f80-1539-11ea-89c1-692f2800cfbc.png)

**Comment by miemieYaho** [comment]
不支持
