### ISSUE TITLE
主键生成策略全部配置报红

### ISSUE THREAD

**Issue by Mrhy1996** [baomidou/mybatis-plus#1908]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
代码生成器中的
  gc.setDbConfig(new GlobalConfig.DbConfig().setKeyGenerator(new OracleKeyGenerator()));
setDbconfig 和  Dbconfig() 报红，不能引入依赖

### 重现步骤
配置全局主键生成策略的时候，在代码生成器中声明全局配置
        GlobalConfig gc = new GlobalConfig();
        gc.setDbConfig(new GlobalConfig.DbConfig().setKeyGenerator(new OracleKeyGenerator()));
下方的setDbconfig报红

### 报错信息
can not resolve method setDbconfig

**Comment by nieqiurong** [comment]
注意导的包.
