### ISSUE TITLE
Page对象, 当size小于0，orders有排序字段时，分页拦截器不处理排序

### ISSUE THREAD

**Issue by VanHelxing** [baomidou/mybatis-plus#1911]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor

 ...
public Object intercept(Invocation invocation) throws Throwable {
 ...

       /*
         * 不需要分页的场合，如果 size 小于 0 返回结果集
         */
        if (null == page || page.getSize() < 0) {
            return invocation.proceed();
        } 

       ...
      // 后面才会解析排序sql
      String buildSql = concatOrderBy(originalSql, page);
       ...
}
 
### 重现步骤

 当size小于0，orders有排序字段。
 查询的结果不会排序。

**Comment by miemieYaho** [comment]
不分页不排序
