### ISSUE TITLE
代码生成器控制Controller是否生成

### ISSUE THREAD

**Issue by Georgeqhh** [baomidou/mybatis-plus#1913]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用代码生成器的时候，输入表名生成mapper,service,controller等类或者接口，但是很多时候并不想生成controller,controller能否提供要不要生成的配置

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/generator.html

例如关闭 xml 生成

templateConfig.setXml(null);

**Comment by Georgeqhh** [comment]
我想关闭controller，就是templateConfig.setController(null)?设置了好像全部没生成了，包括service,entity

**Comment by Georgeqhh** [comment]
> https://mp.baomidou.com/guide/generator.html
> 
> 例如关闭 xml 生成
> 
> templateConfig.setXml(null);

我想关闭controller，就是templateConfig.setController(null)?设置了好像全部没生成了，包括service,entity
