### ISSUE TITLE
EnumUtils valueOf 判断错误

### ISSUE THREAD

**Issue by smartpoko** [baomidou/mybatis-plus#192]
com.baomidou.mybatisplus.toolkit.**EnumUtils**

if ((value instanceof String && e.getValue().equals(value))  || **_e.getValue() == value_**)

e.getValue() == value 如果 value为大于127的Integer的时候不匹配。

**Comment by qmdx** [comment]
改为 https://gitee.com/baomidou/mybatis-plus/blob/dev/mybatis-plus-support/src/main/java/com/baomidou/mybatisplus/toolkit/EnumUtils.java  欢迎给出更好的方法
