### ISSUE TITLE
对象嵌套，查询，保存

### ISSUE THREAD

**Issue by ztg-zlu** [baomidou/mybatis-plus#1921]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

`public class TeacherInfo {
      private User user;
}`
如果对象中，还有对象，这个怎么查？怎么保存？
如果在xml文件中用resultMap，这样的话，plus内置的方法，还是查不出来。

用字段类型处理器，可是我保存对象的时候，就报错了

`Field error in object 'teacherInfo' on field 'createBy': rejected value []; codes [typeMismatch.teacherInfo.createBy,typeMismatch.createBy,typeMismatch.com.tszj.entity.User,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [teacherInfo.createBy,createBy]; arguments []; default message [createBy]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'com.tszj.entity.User' for property 'createBy'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.tszj.entity.User' for property 'createBy': no matching editors or conversion strategy found]`

有什么办法，可以实现吗？？？

**Comment by miemieYaho** [comment]
多表写xml

**Comment by ztg-zlu** [comment]
@miemieYaho  可以写xml,可这样的话，保存就有问题，保存不了，报错`Resolved exception caused by handler execution: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: Could not set property 'createBy' of 'class com.tszj.academy.entity.TeacherInfo' with value 'D410832BF8894F8FA61C6F9F3D45F7AB' Cause: java.lang.IllegalArgumentException: argument type mismatch`

**Comment by ztg-zlu** [comment]
@miemieYaho 而且 内置的方法的方法，，怎么resultMap？？？

**Comment by miemieYaho** [comment]
看文档,mp只支持单表 crud

**Comment by ztg-zlu** [comment]
@miemieYaho  谢谢了，搞定了，我在自动填充的时候，用了，getUser.getId(),这时，用getUser，就好了
![image](https://user-images.githubusercontent.com/26703048/70408479-40e4dd00-1a83-11ea-8b3d-a588e34eb170.png)
