### ISSUE TITLE
3.2.0中 @TableField(value="update_time",update="now()") update不生效

### ISSUE THREAD

**Issue by Kunxian615** [baomidou/mybatis-plus#1922]
### 重现步骤
![image](https://user-images.githubusercontent.com/33412590/70389408-d6d42580-19f9-11ea-970c-2089927ddd58.png)
![image](https://user-images.githubusercontent.com/33412590/70389410-e05d8d80-19f9-11ea-9f69-bb8b7a281e5f.png)
使用IService自带的save()方法，注解中的update="now()" 不生效
![image](https://user-images.githubusercontent.com/33412590/70389445-53670400-19fa-11ea-933f-2055d1cec896.png)
 

### 报错信息

![image](https://user-images.githubusercontent.com/33412590/70389459-81e4df00-19fa-11ea-8775-8877b10d4a5d.png)

**Comment by Zbuter** [comment]
大哥 自动填充是fill属性。

**Comment by Kunxian615** [comment]
> 大哥 自动填充是fill属性。

大哥，您看，update="now()"  ，不是在sql会自动追加，当前 update_time=now() 吗
![image](https://user-images.githubusercontent.com/33412590/70390140-5fa38f00-1a03-11ea-8c01-e86f0e95654a.png)

![image](https://user-images.githubusercontent.com/33412590/70390134-54e8fa00-1a03-11ea-8efb-c9b1691c0394.png)

**Comment by miemieYaho** [comment]
修改验证策略,默认字段值不为null

**Comment by Kunxian615** [comment]
> 修改验证策略,默认字段值不为null
ok,谢谢
![image](https://user-images.githubusercontent.com/33412590/70390991-16573d80-1a0b-11ea-8080-34c8c87b954a.png)
