### ISSUE TITLE
怎么使用代码生成器生成的date字段自动进行fastjson格式化

### ISSUE THREAD

**Issue by lyq027** [baomidou/mybatis-plus#1924]
### 当前使用版本(必须填写清楚，否则不予处理)

版本3.3.0

怎么使用代码生成器生成的date字段自动进行fastjson格式化？目前每个entity都要手动在日期上加上    @JSONField(format = "yyyy-MM-dd hh:mm:ss")

**Comment by qmdx** [comment]
fastjson 应该有全局的解析器百度谷歌去吧，或者去 fastJson issue 不属于 MP 的范畴
