### ISSUE TITLE
使用@Select自定义sql语句，其中需要转化为对象的字段不走typehandler进行转换，使用BaseMapper自带的方法则没有任何问题。

### ISSUE THREAD

**Issue by zhuchengxing** [baomidou/mybatis-plus#1925]
### 当前使用版本(必须填写清楚，否则不予处理)

[3.2](url)
### 重现步骤
_1.我先定义了一个user类
![1](https://user-images.githubusercontent.com/29362652/70402856-cb234600-1a6f-11ea-9865-accac680bce1.png)
2.里面包含一个Test对象
![2](https://user-images.githubusercontent.com/29362652/70402878-e2faca00-1a6f-11ea-8690-af8170a44888.png)
![3](https://user-images.githubusercontent.com/29362652/70402880-e42bf700-1a6f-11ea-87a9-538183fa9eea.png)
3.然后在自定义了一个sql语句
![4](https://user-images.githubusercontent.com/29362652/70402891-ec843200-1a6f-11ea-832a-1aa5d6340699.png)
4.这是我测试的代码
![5](https://user-images.githubusercontent.com/29362652/70403043-7207e200-1a70-11ea-8668-ed46e8de38e5.png)
5.然后查询的结果对比如下
![6](https://user-images.githubusercontent.com/29362652/70403048-7af8b380-1a70-11ea-804c-ed9f18526310.png)
![7](https://user-images.githubusercontent.com/29362652/70403051-7d5b0d80-1a70-11ea-8259-54d270abb5f5.png)

**Comment by miemieYaho** [comment]
你自己写的sql是脱离了mp的范围

**Comment by zhuchengxing** [comment]
也就是说 自己写sql  是无法使用typehandler的？

**Comment by miemieYaho** [comment]
恩
