### ISSUE TITLE
数据库postgre操作数组使用函数&&自动转义成And

### ISSUE THREAD

**Issue by cj92825** [baomidou/mybatis-plus#1926]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
数据库使用postgre,其中有数组操作函数&&

&& | 重叠(有共同元素) | ARRAY[1,4,3] && ARRAY[2,1] | t
-- | -- | -- | --

在xml中配置string_to_array(fieldA,',') &amp;&amp; string_to_array(#{do.queryParam, jdbcType=VARCHAR},',')
最后输出查询的语句是 string_to_array(fieldA, ',') AND string_to_array(?, ',') ,&&自动转义成了AND

请问有方法解决或规避吗

**Comment by miemieYaho** [comment]
这得看你是不是用了什么mp提供的基于jsqlparser进行sql解析的插件(例如多租户),如果没有那很可能就是mybatis的问题
