### ISSUE TITLE
多租户-连接查询issue

### ISSUE THREAD

**Issue by Wadeqin** [baomidou/mybatis-plus#1932]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
select a.* ,b.* from a,b where a.id=b.id    b不会加上tenant_id

select a.* ,b.* from a inner join b on a.id=b.id 这样是ok的。

**Comment by skyzhangyf** [comment]
这个问题可以解决吗？

**Comment by Wadeqin** [comment]
暂时只能自己写完整,用inner join什么join这种就可以 373899542 邮箱373899542@qq.com 签名由 网易邮箱大师 定制 在2019年12月13日 10:07，skyzhangyf 写道： 这个问题可以解决吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yinzihe** [comment]
遇到一样的问题 通过 join方式连表会出现自动在on后面增加加粗部分，就会有问题，如果附表没有租户字段呢？不就是会报错了吗
```sql
SELECT a.key_id FROM fi JOIN ii ON ii.key_id = fi.key_id **AND ii.tenant_id = '4e0f45c8-2446-4a17-98a6-d172524ab054'** WHERE fi.tenant_id = '4e0f45c8-2446-4a17-98a6-d172524ab054' 
```

**Comment by miemieYaho** [comment]
连表就写标准带 join 的sql,否则无法识别
