### ISSUE TITLE
子类调用父类字段进行构造查询

### ISSUE THREAD

**Issue by zacat** [baomidou/mybatis-plus#1935]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 重现步骤
举例如下
调用BaseMapper中updateById语句，更新SaleOrder实体
 

abstract class BaseEntity {
  Long id;
  public Long getId(){};
}

class SaleOrder extends BaseEntity{
  String name;
  public String getName(){}
}

SaleOrder order = new SaleOrder():
order.setName("mybatis");

update(order,Wrappers.<SaleOrder>lambdaQuery().eq(SaleOrder::getId,3323432432423L);

### 报错信息

can not find lambda cache for this property [id] of entity

**Comment by zacat** [comment]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not find lambda cache for this property [id] of entity [com.zoe.framework.commons.entity.bus.BusEntity]]

**Comment by zacat** [comment]
Mybatis plus 3.1.0 获取的类的方法在Mybatis plus 3.3.0 是正确的
![11111](https://user-images.githubusercontent.com/20654293/70516429-f8f0b380-1b71-11ea-85a3-c726279a8eb6.png)

Mybatis plus 3.2.0 以后获取的值就对了。
![22222222222222](https://user-images.githubusercontent.com/20654293/70516489-0e65dd80-1b72-11ea-89c6-c4fd6a3225a7.png)

**Comment by miemieYaho** [comment]
有复现demo?

**Comment by zacat** [comment]
取类名错误。导致的问题。

**Comment by miemieYaho** [comment]
demo呢?

**Comment by zacat** [comment]
稍等一下，我给你写一个。

**Comment by zacat** [comment]
![QQ图片20200116113218](https://user-images.githubusercontent.com/20654293/72491080-ee51ca00-3853-11ea-905e-f92df3782a18.png)
示例代码已发送

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/2086

**Comment by qmdx** [comment]
问题点
```
public class BusSecApiController<
        T extends BusSecEntity<SecEntity>,
        Srv extends BusSecService<T, SecEntity>,
        SecEntity extends BusDetailEntity,
        SecSrv extends CrudService<SecEntity>> {
    @Autowired
    SecSrv secSrv;
    @Autowired
    Srv srv;
    @GetMapping
    public T get(String id) {
        LambdaQueryWrapper<SecEntity> lw = Wrappers
                .<SecEntity>lambdaQuery()
                .eq(SecEntity::getInterId, id);
```
