### ISSUE TITLE
sql server 批量插入异常

### ISSUE THREAD

**Issue by fastj2ee** [baomidou/mybatis-plus#1937]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatisplus.version>3.2.0</mybatisplus.version>

### 该问题是怎么引起的？
批量插入数据库
业务层调用方法  this.saveBatch(Collection<T> entityList)

### 重现步骤
批量插入数据库
业务层调用方法  this.saveBatch(Collection<T> entityList)

### 报错信息
Error flushing statements.  Cause: org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。\r\n### Cause: org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。

**Comment by miemieYaho** [comment]
sqlserver驱动不支持
