### ISSUE TITLE
3.3.0版本代码生成器setExclude报空指针

### ISSUE THREAD

**Issue by yinzihe** [baomidou/mybatis-plus#1942]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-generator</artifactId>
    <version>3.3.0</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

生成代码

### 重现步骤

在StrategyConfig中设置排除表名：
strategy.setExclude("flyway_version");

### 报错信息

报空指针

### 源码分析
`if (isInclude) {
                    sql.append(" AND ").append(this.dbQuery.tableName()).append(" IN (").append((String)Arrays.stream(config.getInclude()).map((tb) -> {
                        return "'" + tb + "'";
                    }).collect(Collectors.joining(","))).append(")");
                } else if (isExclude) {
                    sql.append(" AND ").append(this.dbQuery.tableName()).append(" NOT IN (").append((String)Arrays.stream(config.getInclude()).map((tb) -> {
                        return "'" + tb + "'";
                    }).collect(Collectors.joining(","))).append(")");
                }`
> 在exclude的判断中，config.getInclude()报空指针，是个比较明显的错误，应该为config.getExclude()。

**Comment by nieqiurong** [comment]
尝试使用3.3.1.8-SNAPSHOT,快照使用方式参考:https://mp.baomidou.com/guide/install.html

**Comment by fanqisoft** [comment]
我碰到了相同的问题
