### ISSUE TITLE
能否支持联合主键的getOne,saveOrUpdate

### ISSUE THREAD

**Issue by sywh1234-git** [baomidou/mybatis-plus#1943]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

我使用oracle创建了一个表，表中有两个字段作为主键，但使用到saveOrUpdate时发现keyProperty是字符串类型，只支持单个主键，能否考虑一下联合主键的情况？

**Comment by miemieYaho** [comment]
不支持
