### ISSUE TITLE
官方文档地址打不开！！！！

### ISSUE THREAD

**Issue by DevilMafia** [baomidou/mybatis-plus#1951]
![image](https://user-images.githubusercontent.com/41660452/70765940-3eda9100-1d97-11ea-8aa7-2edf3886436c.png)

**Comment by miemieYaho** [comment]
投诉你的带宽运营商

**Comment by DevilMafia** [comment]
不只是我这里打不开啊，我朋友和我在同一所城市，也打不开！！1

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/70776344-be785800-1db7-11ea-892b-94cdbaf5b92f.png)

**Comment by miemieYaho** [comment]
https://mybatis.plus   这个地址也可以

**Comment by DevilMafia** [comment]
是的，这个链接可以进来，谢谢！
