### ISSUE TITLE
mybatis-plus 的一些问题和建议

### ISSUE THREAD

**Issue by ztg-zlu** [baomidou/mybatis-plus#1952]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

1. `@TableName(value = "academy_course", autoResultMap = true)`
我想直接 `@TableName(value = "academy_course as a", autoResultMap = true)` 给他设置个别名。
这样的话插入更新，都不行了，逻辑删除字段也没有带上别名。
2.啥时候，可以多表联查呀，现在多表联查写，xml，那和mybatis就没有区别了。
现在单表，很少了，我的表，都有创建人字段，查找的时候，要把创建人的名称，也查出来 。
现在，我只能是先查数据，然后在字段类型处理器里，再去查创建人的数据。这样很麻烦。

**Comment by miemieYaho** [comment]
mp不会去做多表,喜欢多表去用jpa
