### ISSUE TITLE
连续调用二次getOne方法，第二次异常

### ISSUE THREAD

**Issue by Angelpierce0619** [baomidou/mybatis-plus#1953]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
连续调用二次getOne方法，第二次没有去数据库查询，用的第一次的返回结果

### 重现步骤
第一次查询结果后，进行处理，然后第二次查询，获取原数据，跟踪发现控制台没有打印sql语句，返回结果为第一次修改后的对象（地址相同）

**Comment by miemieYaho** [comment]
这是一缓,关了就行了

**Comment by Angelpierce0619** [comment]
怎么关闭呢，哪里有步骤？

**Comment by miemieYaho** [comment]
百度上

**Comment by nearzk** [comment]
@Angelpierce0619 两次查询不要在一个事务里
