### ISSUE TITLE
使用jsonb的运算符报错 

### ISSUE THREAD

**Issue by wjc1243** [baomidou/mybatis-plus#1955]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用jsonb的运算符报错

### 重现步骤

select uc."id", u.nickname, u.avatar, b.title, uc.images, uc.created_at as createdAt
		from library.ugc_comment uc
		INNER JOIN library.book b on (uc.books_id ->> 0)::INTEGER = b."id"
		INNER JOIN library.users u ON uc.user_id = u.user_id
		where uc.id = 1

### 报错信息
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:128)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
	... 156 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "->>" "->>"
    at line 3, column 45.

Was expecting one of:

    "&"
    "&&"

**Comment by wjc1243** [comment]
&gt；跟 cdata都试过了 不行

**Comment by miemieYaho** [comment]
JSqlParser不支持解析

**Comment by miemieYaho** [comment]
一般只有多租户那里会报错，建议把该method用注解过滤不走租户然后你自己设置租户条件

**Comment by wjc1243** [comment]
@miemieYaho 我看之前的issue里你也提到了这个，我们好像也没用多租户，而且我也没找到用啥注解，能直接告我下用哪个注解嘛，谢谢了。

**Comment by wjc1243** [comment]
找到方法了，在mapper方法上使用 @SqlParser(filter=true) 排除 SQL 解析
注意！！全局配置 sqlParserCache 设置为 true 才生效。(MP 3.1.1开始不再需要这一步，这句话是官方文档上的我没试过)
感谢@miemieYaho

**Comment by xhu928181** [comment]
3.5以上版本 可以使用 @InterceptorIgnore(tenantLine = "true")
