### ISSUE TITLE
3.3.0版本 缓存分页会出现查询不到数据问题

### ISSUE THREAD

**Issue by samuel072** [baomidou/mybatis-plus#1956]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用redis做二级缓存，分页会出现total为0

**Comment by nieqiurong** [comment]
#1919 
请详细描述一下,或者提供你具体的使用方式.

**Comment by samuel072** [comment]
使用3.3.0做二级缓存时， 获取数据时会出现这个错误：Error querying database. Cause: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long。大佬求方案，我不知道改怎么修改！

**Comment by nieqiurong** [comment]
按道理来说,这个是属于你json反序化的问题,你可以尝试一下使用jdk序列化方式试试,但我可以做个五毛钱的优化,来兼容一下这些问题.

**Comment by samuel072** [comment]
其实咱们可以出一个序列化的代码文本。嗯，是的，使用fastJSON可以解决这个问题。但是只能暂时只能使用1.2.60以及以下。不然会出现问题。如果有谁需要可以@我。我可以发出来这个序列化的相关代码。

**Comment by nieqiurong** [comment]
尝试使用3.3.1.8-SNAPSHOT,快照使用方式参考:https://mp.baomidou.com/guide/install.html
