### ISSUE TITLE
Why isn't the usage statistics displayed?

### ISSUE THREAD

**Issue by diguage** [baomidou/mybatis-plus#1958]
Why isn't the usage statistics displayed?

![image](https://user-images.githubusercontent.com/2121467/70886591-c3871280-2016-11ea-916f-04e0b98caaee.png)

**Comment by nieqiurong** [comment]
因为不是maven工程,虽然可以放个pom上来进行分析。

**Comment by qmdx** [comment]
也许是 github 不支持 gradle 项目的统计
