### ISSUE TITLE
3.3.0使用乐观锁version时，自动填充出现null值

### ISSUE THREAD

**Issue by wggd** [baomidou/mybatis-plus#1964]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

实现MetaObjectHandler - updateFill - setFieldValByName
setFieldValByName("updateTime", LocalDateTime.now(), metaObject);

当使用乐观锁version时，中间的fieldVal，传值了，但是会被置null，不使用乐观锁，一切正常。
3.1.2、3.2.0版本都没这个问题。

### 重现步骤
<img width="858" alt="WX20191217-193133@2x" src="https://user-images.githubusercontent.com/13821124/70992812-85b4e780-2105-11ea-8526-2af511b0029d.png">

**Comment by miemieYaho** [comment]
使用 `3.3.1.5-SNAPSHOT`
