### ISSUE TITLE
basemapper 自动生成的sql中列名有mysql内置函数未转义

### ISSUE THREAD

**Issue by jinspire** [baomidou/mybatis-plus#1966]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
mybatis plus 生成的sql 没有对列名和内置函数名相同的进行转义，返回的值不是存储预期值，而是函数调用值。
期望的sql:
<img width="638" alt="9855EB77-7CD3-4FF9-AE1A-EEA4AA5723E2" src="https://user-images.githubusercontent.com/5680904/71073243-ef42fd80-21ba-11ea-9a37-e955a6d3e045.png">

实际的sql
<img width="957" alt="生成的sql" src="https://user-images.githubusercontent.com/5680904/71073164-ccb0e480-21ba-11ea-8911-56aeb2e7c21f.png">

### 重现步骤

1.在mysql建一张表
`CREATE TABLE `dmcs_sequence` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `current_val` int(11) NOT NULL DEFAULT '0',
  `min` int(11) NOT NULL DEFAULT '0',
  `max` int(11) NOT NULL DEFAULT '0',
  `current_date` date NOT NULL DEFAULT '1970-01-01' COMMENT '当前日期',
  `gmt_create` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `gmt_modify` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='序列';`

2.利用mysql-generator建立对象
`public class DmcsSequence implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    private Integer currentVal;

    private Integer min;

    private Integer max;

    @ApiModelProperty(value = "当前日期")
    private Date currentDate;

    @ApiModelProperty(value = "创建时间")
    private Date gmtCreate;

    @ApiModelProperty(value = "修改时间")
    private Date gmtModify;

}`
以及mapper
`
public interface DmcsSequenceMapper extends BaseMapper<DmcsSequence> {
}
`

3.调用DmcsSequenceMapper selectById方法 返回的DmcsSequence检查字端currentDate 

### 报错信息
期望返回值
<img width="836" alt="D8CFA541-565C-49B1-B2EB-0A9F0B9D0E86" src="https://user-images.githubusercontent.com/5680904/71073293-0e418f80-21bb-11ea-8959-4edeb1cdf856.png">
实际返回值

> 当天日期

期望和实际返回值不相等。

**Comment by miemieYaho** [comment]
自行注解,看文档

**Comment by jinspire** [comment]
可以使用  @TableField(value="`current_date`")
    private Date currentDate 解决，下次请对解决方案回答的透彻一些，不要有所保留。
