### ISSUE TITLE
不支持mysql全文检索，MATCH  （‘filedname’） AGAINST（‘1111’）

### ISSUE THREAD

**Issue by LiuBaiBing** [baomidou/mybatis-plus#1967]
### 重现步骤
xml中编写全文检索语句即可

### 报错信息
 Encountered unexpected token: "AGAINST" <S_IDENTIFIER>
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.

**Comment by chenyulzhh** [comment]
我还在 3.1.0，直接 xml里面写 全文检索 是可以的啊。。
现在 看到都3.3.0了。。但是不敢升级啊。。怕不兼容啊

**Comment by miemieYaho** [comment]
用什么插件了?
