### ISSUE TITLE
字段配置了FieldStrategy.IGNORED之后, updateById方法仍然没有加入该字段

### ISSUE THREAD

**Issue by shenshb808** [baomidou/mybatis-plus#1968]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
@ApiModelProperty(value = "跳转地址")
@TableField(updateStrategy = FieldStrategy.IGNORED)
private String jumpAddress;

### 重现步骤
@ApiModelProperty(value = "跳转地址")
@TableField(updateStrategy = FieldStrategy.IGNORED)
private String jumpAddress;

### 报错信息
UPDATE qbx_banner 
SET picture = ?,
background_color = ?,
sort = ?,
visit_number = ?,
visit_user_number = ?,
city_code = ? 
WHERE
	id = ? 
	AND state = 0

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by shenshb808** [comment]
> 
> 
> 给出你的复现demo

``
