### ISSUE TITLE
updateBatchById 卡住直至事务超时

### ISSUE THREAD

**Issue by SunJiFengPlus** [baomidou/mybatis-plus#1969]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
用 Junit 跑测试类时没有问题, 但是用 mvn test 跑测试类时, 跑到updateBatchById 就会卡住, 直到事务超时. 

### 重现步骤
测试类简写
``` java
@SpringBootTest
@RunWith(SpringRunner.class)
@Transactional
public class GoodsInfoServiceTest {
    @Test
    public void testShelveGoodsBatch1() {
        // IService::save 插入了两条数据
        // 使用 updateBatchById 更新那2条数据
        // 断言
    }
}
```

### 报错信息
Maven 的报错信息
``` java
org.springframework.dao.CannotAcquireLockException: 
com.xxx.service.goodscenter.mapper.GoodsInfoMapper.updateById (batch index #1) failed. 
Cause: java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction; Lock wait timeout exceeded; try restarting transaction; 
nested exception is java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction
```

卡住时的日志, 根据日志时间卡了快2分钟左右
``` java
2019-12-19 10:05:47.758 [main] DEBUG Logger.java::debug:49 - JDBC Connection [com.mysql.jdbc.JDBC4Connection@3e8eea59] will be managed by Spring
2019-12-19 10:05:47.760 [main] DEBUG BaseJdbcLogger.java::debug:143 - ==>  Preparing: UPDATE goods_info SET show_status=?, audit_uid=?, audit_time=?, undercarriage_type=?, undercarriage_time=? WHERE id=? 
2019-12-19 10:05:47.761 [main] DEBUG BaseJdbcLogger.java::debug:143 - ==> Parameters: 0(Integer), 0(Integer), 2019-12-19T10:05:47.755(LocalDateTime), 1(Integer), 2019-12-19T10:05:47.755(LocalDateTime), 767685(Integer)
2019-12-19 10:05:47.762 [main] DEBUG BaseJdbcLogger.java::debug:143 - ==> Parameters: 0(Integer), 0(Integer), 2019-12-19T10:05:47.755(LocalDateTime), 1(Integer), 2019-12-19T10:05:47.755(LocalDateTime), 767684(Integer)
2019-12-19 10:07:30.014 [main] DEBUG Logger.java::debug:49 - Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@19070326]
2019-12-19 10:07:30.014 [main] DEBUG Logger.java::debug:49 - Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@19070326]
```
卡住时的 `mysql > SHOW FULL PROCESSLIST;` 信息

| Command | Time | State | Info |
| --- | --- | --- | --- |
| Query | 29 | updating | UPDATE goods_info  SET show_status=0, refused_reason='testReason',undercarriage_type=0, undercarriage_time='2019-12-19 10:04:04.483'  WHERE id=767338 |

卡住时的 `mysql > SELECT * FROM INFORMATION_SCHEMA.INNODB_LOCKS; ` 信息

|lock_id	|lock_trx_id	|lock_mode	|lock_type	|lock_table	|lock_index	|lock_space	|lock_page	|lock_rec |lock_data|
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|391193218:1446:87822:21	|391193218	|X	|RECORD	|goods_info	|PRIMARY	|1446	|87822	|21	|767338|
|391193172:1446:87822:21	|391193172	|X	|RECORD	|goods_info	|PRIMARY	|1446	|87822	|21	|767338|

**Comment by nieqiurong** [comment]
是否存在多个测试用例操作767338这条记录？

**Comment by SunJiFengPlus** [comment]
> 是否存在多个测试用例操作767338这条记录？

每个测试类跑的都是不同的记录, 验证了一下: 我把其他测试类 @Test 都注释掉了, 还是会卡在 updateBatchById.

**Comment by helloqhx** [comment]
这个问题我也碰到过，根这个框架没有关系，应该是你批量插入的时候，多条数据竞争同一个锁了。

**Comment by SunJiFengPlus** [comment]
我是臭傻*, 我自裁 (￣ε(#￣)☆╰╮

**Comment by MaxHang** [comment]
请问是怎么解决的，用 Junit 跑测试只有一个事务，但是 mvn test跑多mockMvc.perform的请求测试也会卡在updateBatchById（两个事务死锁），但我取消测试类的@Transactional注解时，就可以正常运行测试。但是我通过日志打印，发现mockMvc.perform进入到service的@Transactional方法时，是正常的加入了事务测试的活动事务的。

+--------+---------------------------------------------+-----------------------+-----------+----------+---------------+-----------------+----------------+-------------------+------------+-----------------------+-----------+---------------+-------------+---------------------+
| ENGINE | ENGINE_LOCK_ID                              | ENGINE_TRANSACTION_ID | THREAD_ID | EVENT_ID | OBJECT_SCHEMA | OBJECT_NAME     | PARTITION_NAME | SUBPARTITION_NAME | INDEX_NAME | OBJECT_INSTANCE_BEGIN | LOCK_TYPE | LOCK_MODE     | LOCK_STATUS | LOCK_DATA           |
+--------+---------------------------------------------+-----------------------+-----------+----------+---------------+-----------------+----------------+-------------------+------------+-----------------------+-----------+---------------+-------------+---------------------+
| INNODB | 140356647523920:308:1086:140356578515648    |                421232 |       175 |      355 | r_pan         | r_pan_file      | NULL           | NULL              | NULL       |       140356578515648 | TABLE     | IX            | GRANTED     | NULL                |
| INNODB | 140356647523920:308:1089:140356578515472    |                421232 |       175 |      337 | r_pan         | r_pan_user      | NULL           | NULL              | NULL       |       140356578515472 | TABLE     | IX            | GRANTED     | NULL                |
| INNODB | 140356647523920:308:1090:140356578515560    |                421232 |       175 |      340 | r_pan         | r_pan_user_file | NULL           | NULL              | NULL       |       140356578515560 | TABLE     | IX            | GRANTED     | NULL                |
| INNODB | 140356647524728:680:1090:140356578521744    |                421233 |       185 |       44 | r_pan         | r_pan_user_file | NULL           | NULL              | NULL       |       140356578521744 | TABLE     | IX            | GRANTED     | NULL                |
| INNODB | 140356647523920:308:24:8:83:140356578512560 |                421232 |       185 |       44 | r_pan         | r_pan_user_file | NULL           | NULL              | PRIMARY    |       140356578512560 | RECORD    | X,REC_NOT_GAP | GRANTED     | 1949032920459919360 |
| INNODB | 140356647524728:680:24:8:83:140356578518832 |                421233 |       185 |       44 | r_pan         | r_pan_user_file | NULL           | NULL              | PRIMARY    |       140356578518832 | RECORD    | X,REC_NOT_GAP | WAITING     | 1949032920459919360 |
+--------+---------------------------------------------+-----------------------+-----------+----------+---------------+-----------------+----------------+-------------------+------------+-----------------------+-----------+---------------+-------------+---------------------+
