### ISSUE TITLE
Id生成器 时间生成

### ISSUE THREAD

**Issue by iPhotoner** [baomidou/mybatis-plus#197]
com.baomidou.mybatisplus.toolkit.Sequence.timeGen():
use(such as) Instant.now().toEpochMilli() replace System.currentTimeMillis()

**Comment by qmdx** [comment]
why ?

**Comment by yuxiaobin** [comment]
Instant.toEpochMilli() 
return the number of milliseconds since the epoch of 1970-01-01T00:00:00Z

该方法只能在 **JDK8** 下使用.

System.currentTimeMillis()
return  the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC.

没看出有什么特别的地方

**Comment by qmdx** [comment]
System.currentTimeMillis() 当前 UTC 的瞬时时间，  Instant.now().toEpochMilli() 精确到毫秒
