### ISSUE TITLE
查询时候出现异常,但是直接sql语句,可以执行通过

### ISSUE THREAD

**Issue by newbirdking** [baomidou/mybatis-plus#1973]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

![image](https://user-images.githubusercontent.com/5317586/71161594-963f9c00-2284-11ea-8506-0c6d54a1c2c7.png)

### 重现步骤
点击查询接口直接后端异常报错
数据库查询语句:
![image](https://user-images.githubusercontent.com/5317586/71162324-f71ba400-2285-11ea-88c2-81c35cd74681.png)

### 报错信息
![image](https://user-images.githubusercontent.com/5317586/71161594-963f9c00-2284-11ea-8506-0c6d54a1c2c7.png)

![image](https://user-images.githubusercontent.com/5317586/71162191-bde33400-2285-11ea-9f65-e5a33e16cbd7.png)
![image](https://user-images.githubusercontent.com/5317586/71162263-dce1c600-2285-11ea-8664-df41778f5d69.png)

**Comment by miemieYaho** [comment]
sqlparser不支持解析

**Comment by newbirdking** [comment]
那我如果需要这样做,需要改动sqlparse的源码,来支持?

**Comment by miemieYaho** [comment]
用 `3.3.1.5-SNAPSHOT`,还不行就用注解指定该method不走解析器链.其他依托解析器链的功能(例如多租户)就自行处理

**Comment by newbirdking** [comment]
感谢回复.明白了.我尝试下看看
