### ISSUE TITLE
条件ne  查询问题

### ISSUE THREAD

**Issue by purgeyao** [baomidou/mybatis-plus#1974]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

条件ne  查询问题

ne()  如果传入null的话 查询结果不对  

原因 数据库 <> null 的话是有问题的   必须用 is null

希望改善下这个条件   上游传入了null   查询结果就会差强人意了

### 报错信息

无

**Comment by purgeyao** [comment]
@miemieYaho 大老看下啦

**Comment by miemieYaho** [comment]
自己判断处理

**Comment by purgeyao** [comment]
哈哈哈  那有空pr下

**Comment by miemieYaho** [comment]
pr也不会接的
