### ISSUE TITLE
QueryWrapper条件查询list,无法自动转换为小写

### ISSUE THREAD

**Issue by jojoalwayswin** [baomidou/mybatis-plus#1980]
### 当前使用版本(必须填写清楚，否则不予处理)
版本  3.1

### 重现步骤
public List  queryAllitem( String orderId) {
        QueryWrapper<OrderItemEntity> wrapper =new QueryWrapper<>();
        wrapper.eq("order_id",orderId);
        List<Map<String,Object>> list = baseMapper.selectMaps(wrapper);
        return list;
    }
实体类为小写驼峰，数据库里字段为小写加下划线

### 报错信息
postman请求为orderId = 2
相应为：
{
    "msg": "success",
    "code": 0,
    "data": {},
    "itemList": [
        {
            "PRODUCT_PRICE": 2.00,
            "SUBTOTAL": 4.00,
            "ORDER_ID": "2",
            "ORDER_SN": "2",
            "QUANTITY": 2,
            "ID": "3",
            "PRODUCT_NAME": "2"
        },
        {
            "PRODUCT_PRICE": 2.00,
            "SUBTOTAL": 4.00,
            "ORDER_ID": "2",
            "ORDER_SN": "2",
            "QUANTITY": 2,
            "ID": "4",
            "PRODUCT_NAME": "2"
        }
    ]
}

**Comment by miemieYaho** [comment]
自己转
