### ISSUE TITLE
BUG-ITableNameHandler

### ISSUE THREAD

**Issue by SmythAsen** [baomidou/mybatis-plus#1981]
### 当前使用版本
3.3.0

### 该问题是怎么引起的？
ITableNameHandler返回的TableName会替换调字段名，如果字段名中包含了表名
例如：返回的表名为tb_a（替换tb为tb_a) ，但是表中有一个字段为tb_id
正常的update 语句应该是
UPDATE tb_a SET some_field=? WHERE tb_id=? 
但实际上执行时，字段中的表名也会被替换
UPDATE tb_a SET some_field=? WHERE **tb_a_id**=?

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/dynamic-table-name-parser.html 注意事项部分看下，该解析器默认采用的是替换方式存在误替换问题，你需要设置复杂一些的命名规则避免错误替换，另外你可以重写父类的方法自己编写替换规则
