### ISSUE TITLE
代码生成器生成不了父类，按源码要求setSuperEntityClass放在setSuperEntityColumns后依旧不好使

### ISSUE THREAD

**Issue by zhaomingcheng01** [baomidou/mybatis-plus#1982]
@Test
    public void testGenerator() {
        // 当前工程路径
        String path = System.getProperty("user.dir");
        // 全局配置
        GlobalConfig config = new GlobalConfig();
        config.setActiveRecord(false) // 是否支持AR模式
                .setAuthor("zmc") // 作者
                .setOutputDir(path + "\\src\\main\\java") // 生成路径
                .setFileOverride(true)  // 文件覆盖
                .setIdType(IdType.AUTO) // 主键策略
                .setServiceName("%sService")  // 设置生成的service接口的名字的首字母是否为I
                .setBaseResultMap(true)
                .setBaseColumnList(true)
                .setSwagger2(true)//开启 swagger2 模式
                .setOpen(false);//是否打开输出目录

        //数据源配置
        DataSourceConfig dsConfig = new DataSourceConfig();
        dsConfig.setDbType(DbType.MYSQL)  // 设置数据库类型
                .setDriverName("com.mysql.cj.jdbc.Driver")
                .setUrl("jdbc:mysql://localhost:3306/mybatis_plus_test?serverTimezone=UTC")
                .setUsername("root")
                .setPassword("1234");

        TableFill createTime = new TableFill("createTime", FieldFill.INSERT);
        TableFill updateTime = new TableFill("updateTime", FieldFill.INSERT_UPDATE);
        //策略配置
        StrategyConfig stConfig = new StrategyConfig();
        stConfig.setCapitalMode(true) //全局大写命名
                .setSkipView(true)//是否跳过视图
                .setColumnNaming(NamingStrategy.underline_to_camel) // 驼峰命名
                .setNaming(NamingStrategy.underline_to_camel) // 数据库表映射到实体的命名策略
                .setEntityLombokModel(true)//使用Lombok
                .setRestControllerStyle(true) //Rest风格
                // .setTablePrefix("tbl_") 设置数据库中表前缀
                //.setFieldPrefix("")//字段前缀
                .setVersionFieldName("version")
                .setLogicDeleteFieldName("deleted")
                .setSuperEntityColumns("id","createTime","updateTime","globalId","version","deleted")
                .setSuperEntityClass("com.test.generator.domain.BaseEntry")
                // 以上的四个方法不好使,需要注意
                .setTableFillList(Arrays.asList(createTime, updateTime))
                .setEntityBooleanColumnRemoveIsPrefix(true)// 移除is前缀
                .setInclude("employee");// 包含表,不定长参数列表

        //包名策略配置
        PackageConfig pkConfig = new PackageConfig();
        String javaPath = "com.test.generator";
        pkConfig.setParent(javaPath)
                .setMapper("mapper")
                .setService("service")
                .setServiceImpl("service.impl")
                .setController("controller")
                .setEntity("domain")
                .setXml("resources.mapper");

        //配置自定义模板
//        TemplateConfig templateConfig = new TemplateConfig();
//        templateConfig.setEntity(javaResources + "templates.entity2.java");

        // 整合配置
        AutoGenerator ag = new AutoGenerator();
        ag.setGlobalConfig(config)
                .setDataSource(dsConfig)
                .setStrategy(stConfig)
                .setPackageInfo(pkConfig);
        // 配置模板引擎
//        ag.setTemplateEngine(new FreemarkerTemplateEngine());
        //执行
        ag.execute();
    }

 
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.0</version>
        </dependency>

**Comment by nieqiurong** [comment]
不会给你生成com.test.generator.domain.BaseEntry，需要你自己写。
