### ISSUE TITLE
下边那段注释不是很明确

### ISSUE THREAD

**Issue by zhaomingcheng01** [baomidou/mybatis-plus#1983]
/**
 * 自定义Sql注入
 */
public class MySqlInjector extends DefaultSqlInjector {

	@Override
	public List<AbstractMethod> getMethodList(Class<?> mapperClass) {
		List<AbstractMethod> methodList = super.getMethodList(mapperClass);
		//增加自定义方法
		methodList.add(new DeleteAll());

// 这里不是很懂
		/**
		 * 以下 3 个为内置选装件
		 * 头 2 个支持字段筛选函数
		 */
		// 例: 不要指定了 update 填充的字段
		methodList.add(new InsertBatchSomeColumn(i -> i.getFieldFill() != FieldFill.UPDATE));
		methodList.add(new AlwaysUpdateSomeColumnById());
		methodList.add(new LogicDeleteByIdWithFill());
		return methodList;
	}
}
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.0</version>
        </dependency>

**Comment by miemieYaho** [comment]
不懂就点进去看源码
