### ISSUE TITLE
可以实现querywrapper.select(。。。很多字段,sum（某个字段）)这种效果吗

### ISSUE THREAD

**Issue by 15206125206** [baomidou/mybatis-plus#1984]
### 当前使用版本(必须填写清楚，否则不予处理)
最新

### 报错信息

可以实现querywrapper.select(。。。很多字段,sum（某个字段）)这种效果吗，为了一个字段把几十个字段都写一遍感觉很麻烦

**Comment by miemieYaho** [comment]
不支持
