### ISSUE TITLE
3.2.0 kotlin 使用报错

### ISSUE THREAD

**Issue by kewei24** [baomidou/mybatis-plus#1986]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用kotlin时，用KtQueryWrapper
需要进行模糊查询
wrapper.and {itemWrapper->
                itemWrapper.like(CustomerEntity::name, query.searchKey)
                        .or()
                        .like(CustomerEntity::phone, query.searchKey)
            }
报错
### 报错信息
Parameter specified as non-null is null: method com.baomidou.mybatisplus.extension.kotlin.KtQueryWrapper.<init>, parameter entity

**Comment by miemieYaho** [comment]
怎么用的列完整

**Comment by kewei24** [comment]
`private fun fillQueryWrapper(query: OpportunityWebPageQuery): KtQueryWrapper<CustomerEntity> {
        val wrapper = KtQueryWrapper(CustomerEntity::class.java)
        wrapper.eq(CustomerEntity::valid, query.valid)
        if (!query.districtId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::districtId, query.districtId)
        } else if (!query.cityId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::cityId, query.cityId)
        } else if (!query.provinceId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::provinceId, query.provinceId)
        } else if (!query.region.isNullOrEmpty() && RegionType.of(query.region!!.toInt())?.areaCodes?.toList().isNotNullOrEmpty()) {
            wrapper.`in`(CustomerEntity::provinceId, RegionType.of(query.region!!.toInt())?.areaCodes?.toList())
        }
        wrapper.entity = CustomerEntity()
        if (!query.searchKey.isNullOrEmpty()) {
            wrapper.and { itemWrapper ->
                itemWrapper.like(CustomerEntity::name, query.searchKey)
                        .or()
                        .like(CustomerEntity::phone, query.searchKey)
            }
        }
        if (query.opportunityType != 0) {
            wrapper.eq(CustomerEntity::type, query.opportunityType)
        }
        return wrapper
    }`

**Comment by kewei24** [comment]
```
private fun fillQueryWrapper(query: OpportunityWebPageQuery): KtQueryWrapper<CustomerEntity> {
        val wrapper = KtQueryWrapper(CustomerEntity::class.java)
        wrapper.eq(CustomerEntity::valid, query.valid)
        if (!query.districtId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::districtId, query.districtId)
        } else if (!query.cityId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::cityId, query.cityId)
        } else if (!query.provinceId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::provinceId, query.provinceId)
        } else if (!query.region.isNullOrEmpty() && RegionType.of(query.region!!.toInt())?.areaCodes?.toList().isNotNullOrEmpty()) {
            wrapper.`in`(CustomerEntity::provinceId, RegionType.of(query.region!!.toInt())?.areaCodes?.toList())
        }
        wrapper.entity = CustomerEntity()
        if (!query.searchKey.isNullOrEmpty()) {
            wrapper.and { itemWrapper ->
                itemWrapper.like(CustomerEntity::name, query.searchKey)
                        .or()
                        .like(CustomerEntity::phone, query.searchKey)
            }
        }
        if (query.opportunityType != 0) {
            wrapper.eq(CustomerEntity::type, query.opportunityType)
        }
        return wrapper
    }
```

**Comment by kewei24** [comment]
> 怎么用的列完整

```
private fun fillQueryWrapper(query: OpportunityWebPageQuery): KtQueryWrapper<CustomerEntity> {
        val wrapper = KtQueryWrapper(CustomerEntity::class.java)
        wrapper.eq(CustomerEntity::valid, query.valid)
        if (!query.districtId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::districtId, query.districtId)
        } else if (!query.cityId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::cityId, query.cityId)
        } else if (!query.provinceId.isNullOrEmpty()) {
            wrapper.eq(CustomerEntity::provinceId, query.provinceId)
        } else if (!query.region.isNullOrEmpty() && RegionType.of(query.region!!.toInt())?.areaCodes?.toList().isNotNullOrEmpty()) {
            wrapper.`in`(CustomerEntity::provinceId, RegionType.of(query.region!!.toInt())?.areaCodes?.toList())
        }
        wrapper.entity = CustomerEntity()
        if (!query.searchKey.isNullOrEmpty()) {
            wrapper.and { itemWrapper ->
                itemWrapper.like(CustomerEntity::name, query.searchKey)
                        .or()
                        .like(CustomerEntity::phone, query.searchKey)
            }
        }
        if (query.opportunityType != 0) {
            wrapper.eq(CustomerEntity::type, query.opportunityType)
        }
        return wrapper
    }
```

**Comment by craone** [comment]
查看文档 [插入或更新的字段有 空字符串 或者](https://mp.baomidou.com/guide/faq.html#%E6%8F%92%E5%85%A5%E6%88%96%E6%9B%B4%E6%96%B0%E7%9A%84%E5%AD%97%E6%AE%B5%E6%9C%89-%E7%A9%BA%E5%AD%97%E7%AC%A6%E4%B8%B2-%E6%88%96%E8%80%85-null)
```kotlin
KtUpdateWrapper(Member::class.java)
                .set(Member::unionId, null)
                .eq(Member::id, memberId)
```
是可以的,但是提示错误
```log
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.baomidou.mybatisplus.extension.kotlin.KtUpdateWrapper.set, parameter value
	at com.baomidou.mybatisplus.extension.kotlin.KtUpdateWrapper.set(KtUpdateWrapper.kt)
	at com.baomidou.mybatisplus.extension.kotlin.KtUpdateWrapper.set(KtUpdateWrapper.kt:34)
	at com.baomidou.mybatisplus.core.conditions.update.Update.set(Update.java:30)
```

**Comment by miemieYaho** [comment]
使用 `3.3.1.10-SNAPSHOT`

**Comment by miemieYaho** [comment]
使用 3.3.1
