### ISSUE TITLE
文档不全

### ISSUE THREAD

**Issue by lizhuangs** [baomidou/mybatis-plus#1987]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 问题
比如IdType，找遍文档并没有相关说明，文档只写了默认值是ID_WROKER，但实际上这个已经被弃用了。其它几个值分别是什么也没有说明，测试发现默认IdType.ASSIGN_ID是19位数字。可是代码里面ASSIGN_ID的注释却写着：默认 ID_WORKER？？？：
```java
/**
* 主键类型（默认 ID_WORKER）
*/
private IdType idType = IdType.ASSIGN_ID;
```
建议说明一下IdType默认值，以及其它几个值的说明和使用场景。

**Comment by flyingglass** [comment]
1. 查看com.baomidou.mybatisplus.annotation.IdType枚举，已有添加注释了。
2. DefaultIdentifierGenerator主键生成策略，
 - 自增的话采用Snowflake生成自增id
 - uuid的话，默认是jdk的uuid生成
在DBConfig自定义后可直接覆盖

**Comment by flyingglass** [comment]
> ### 当前使用版本(必须填写清楚，否则不予处理)
> 3.3.0
> 
> ### 问题
> 比如IdType，找遍文档并没有相关说明，文档只写了默认值是ID_WROKER，但实际上这个已经被弃用了。其它几个值分别是什么也没有说明，测试发现默认IdType.ASSIGN_ID是19位数字。可是代码里面ASSIGN_ID的注释却写着：默认 ID_WORKER？？？：
> 
> ```java
> /**
> * 主键类型（默认 ID_WORKER）
> */
> private IdType idType = IdType.ASSIGN_ID;
> ```
> 
> 建议说明一下IdType默认值，以及其它几个值的说明和使用场景。

查看com.baomidou.mybatisplus.annotation.IdType枚举，已有添加注释了。
DefaultIdentifierGenerator主键生成策略，
自增的话采用Snowflake生成自增id
uuid的话，默认是jdk的uuid生成
在DBConfig自定义后可直接覆盖

**Comment by lizhuangs** [comment]
这个不是应该写在官方文档里面么，看源码这个。。。建议更新一下文档吧。我都看看文档写测试用例的。当测试结果和文档描写不符，我才不得不看源码是不是改了。

**Comment by Skqing** [comment]
有些文档逻辑写的确实有问题啊，有点乱。还是要看示例。

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/IdType.java
