### ISSUE TITLE
SpringBoot Maven 热部署 不重启服务器 编译项目提示xml找不到

### ISSUE THREAD

**Issue by Terrency** [baomidou/mybatis-plus#199]
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.xx.xx.mapper.BannerMapper.selectList
Banner是首页的接口， 正常重启服务器是可以加载到的， 但是使用maven的启动方式， 带上热部署的功能以后， 执行mybatis plus 的selectList方法就提示找不到这个方法， 其他所有不在单独写的mapper里面的方法都找不到
应该是xml文件没有绑定到， 导致热部署无法生效， 有什么好的解决办法吗， 不然这个插件基本是不支持springboot的。

**Comment by Terrency** [comment]
当然不止maven的启动方式， 通过springboot的Application直接启动，也是一样的问题，不支持热部署

**Comment by qmdx** [comment]
xml 扫描不对，我自己也使用的 devtools 无任何问题，请注意你的 xml 扫描
