### ISSUE TITLE
MySQL 多主键的支持

### ISSUE THREAD

**Issue by zhangbaiquan** [baomidou/mybatis-plus#1992]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus 3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

可以支持多主键吗？目前好像只能支持单主键。

**Comment by miemieYaho** [comment]
不支持
