### ISSUE TITLE
通用枚举使用，填充值还是Enum.name()

### ISSUE THREAD

**Issue by TanLinRu** [baomidou/mybatis-plus#1993]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 重现步骤
=====SexEnum=====
package com.tlq.boss.common.enums;
@Getter
public enum SexEnum {
    MAN(1,"男"),
    WOWEN(0,"女");

    SexEnum(int sex, String desc){
        this.sex = sex;
        this.desc = desc;
    }

    @EnumValue
    private int sex;

    private String desc;

}

====application.yml=====

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  type-enums-package: com.tlq.boss.common.enums

### 报错信息
[department=技术后台, position=Java后台开发, sex=MAN（这里的sex值还是默认Enum.name()）]

**Comment by miemieYaho** [comment]
使用不当,自己排查 https://github.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-enum
