### ISSUE TITLE
LambdaQueryWrapper 如何移除一个查询条件

### ISSUE THREAD

**Issue by w5185552** [baomidou/mybatis-plus#1994]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
多处使用一个查询条件但是查询条件有区别如何覆盖前一个的相同条件

**Comment by w5185552** [comment]
已找到解决方案

**Comment by quavario** [comment]
你怎么解决的啊
