### ISSUE TITLE
3.3.0 如何使用数据库自增id

### ISSUE THREAD

**Issue by LiZhenNet** [baomidou/mybatis-plus#1995]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0 

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

自3.3.0开始,默认使用雪花算法+UUID ，如何使用数据库自增id呢 ？

**Comment by miemieYaho** [comment]
idtype=AUTH
