### ISSUE TITLE
自定义Sql配合Wrapper、Page分页时多执行了一条并没定义的Sql

### ISSUE THREAD

**Issue by ggitta** [baomidou/mybatis-plus#1996]
### 当前使用版本(必须填写清楚，否则不予处理)

版本3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

执行之后，多执行了一条Sql，导致报错，以下是多执行的Sql：
==> Preparing: SELECT COUNT(1) FROM User WHERE (org = ? AND role = ?)

### 重现步骤

我的Mapper方法：
@select("select * from User ${ew.customSqlSegment}")
IPage getAllUserPageWrapper(@param(Constants.WRAPPER) Wrapper ew, Page page);
我的Wrapper：
userWrapper.eq("org",org.getId()).eq("role",role.getId());

### 报错信息

Expected one result (or null) to be returned by selectOne(), but found: 3

**Comment by miemieYaho** [comment]
这是count sql
