### ISSUE TITLE
实体DemoDO如何解析出表名为demo?

### ISSUE THREAD

**Issue by kopstill** [baomidou/mybatis-plus#1997]
### 当前使用版本(必须填写清楚，否则不予处理)

最新版

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

用户需求

### 重现步骤

不用重现

### 报错信息

无报错信息

**Comment by miemieYaho** [comment]
tablleinfohelper 看源码

**Comment by kopstill** [comment]
> tablleinfohelper 看源码

不方便扩展自定义解析规则
