### ISSUE TITLE
Issue about code generator for Oralce

### ISSUE THREAD

**Issue by mpthink** [baomidou/mybatis-plus#20]
在使用oracle数据库的时候遇到一个问题，提示：表 [XXX] 在数据库中不存在！！！
但是表是存在的，只是不在对应用户的schema下，但是该用户可以访问到该表。
代码如下：
dsc.setDriverName("oracle.jdbc.driver.OracleDriver");
dsc.setUsername("aaaa");
dsc.setPassword("aaaa");
dsc.setUrl("jdbc:oracle:thin:@10.11.22.33:1521:xe");
String sql = "select * from alarm";
PreparedStatement pre = dsc.getConn().prepareStatement(sql);// 实例化预编译语句
ResultSet rs = pre.executeQuery();
System.out.println("test:  " + rs.getFetchSize());

rs可以获取结果，但是提示alarm表找不到。  aaaa这个schema下面没有alarm表，但是给予了它访问其他schema的权限。

**Comment by mpthink** [comment]
看了下mybatis-plus的QuerySQL代码，目前只能获取当前用户的表，其他的获取不了
这个问题我可以修改user table to all table来解决

多问个问题：　是不是所有用户都可以查询all_col_comments？　　如果是，是不是应该用all_col_comments而不是user_tab_comments  来获取表

**Comment by mpthink** [comment]
换成all之后效率太低了，我决定还是在当前用户下重新创建需要的表

**Comment by qmdx** [comment]
@mpthink   多谢反馈 oracle 支持如果不完善可以参与 mp 的支持开发，随时欢迎加入。

**Comment by yuxiaobin** [comment]
Oracle下代码生成，2.1.7应该优化了（但是2.1.7分页插件有问题, see [changelog](http://baomidou.oschina.io/mybatis-plus-doc/#/changelog?id=v217-20171211-%e4%bb%a3%e5%8f%b7%ef%bc%9a%e6%b8%85%e9%a3%8e%e5%be%90%e6%9d%a5-%ef%bc%8c-%e8%af%a5%e7%89%88%e6%9c%ac%e5%8f%b7%e5%ad%98%e5%9c%a8%e5%88%86%e9%a1%b5-asc-bug-%e8%af%b7%e6%94%b9%e4%b8%ba-217-snapshot)）

之前是拿该用户下所有表，优化为 ：
配置了include的，就只会拿include的表
配置exclude的，会排除这些表
