### ISSUE TITLE
自定义主键生成策略仅执行一次

### ISSUE THREAD

**Issue by zhouhan91** [baomidou/mybatis-plus#2000]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

自定义主键生成，继承IkeyGenerator，但每次执行insert时，主键都是一样，导致第一条可以插入成功，之后的都报主键冲突

### 重现步骤
重启项目，第二次执行insert操作时报错

### 报错信息
主键冲突

**Comment by miemieYaho** [comment]
用最新版试了再说

**Comment by zhouhan91** [comment]
> 用最新版试了再说

换成3.2.0也一样

**Comment by miemieYaho** [comment]
那把你的代码列出来

**Comment by zhouhan91** [comment]
MybatisKeyGenerator ：

`@Slf4j
@Component
public class MybatisKeyGenerator implements IKeyGenerator {
	@Override
	public String executeSql(String incrementerName) {
		long uid = new SnowflakeIdWorker().nextId();
		return "select " + uid + " from dual";
	}
}`

实体类：

‘@Data
@KeySequence("mybatisKeyGenerator")
public class Test {
	@TableId(type = IdType.INPUT)
	private Long id;
	private String name;
}’

**Comment by miemieYaho** [comment]
你还是先去看看其他的 `IKeyGenerator` 子类是怎么实现的吧

**Comment by zhouhan91** [comment]
> 你还是先去看看其他的 `IKeyGenerator` 子类是怎么实现的吧

嗯，看了，请问mysql数据，主键通过雪花算法生成，应该怎么实现呢

**Comment by miemieYaho** [comment]
不需要你实现,看文档,看 samples
