### ISSUE TITLE
字段是否可以选择插入或更新？

### ISSUE THREAD

**Issue by liangzhi2019** [baomidou/mybatis-plus#2002]
### 当前使用版本
3.2.0

当前版本是否支持配置某个字段（属性）只在INSERT时插入，而在UPDATE时不处理呢？或者反过来只在UPDATE时更新，而INSERT时不处理？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/TableField.java  insertStrategy  updateStrategy
