### ISSUE TITLE
你好，IService中的saveOrUpdateBatch(Collection)，打印的为什么只有一条更新日志？

### ISSUE THREAD

**Issue by yangshuangjun** [baomidou/mybatis-plus#2003]

**Comment by miemieYaho** [comment]
你是怎么看到只有一条的?

**Comment by yangshuangjun** [comment]
![图片](https://user-images.githubusercontent.com/11353608/71465903-d5c43600-27f8-11ea-907c-00e6aca9f445.png)

**Comment by yangshuangjun** [comment]
我打上日志后，调了这个方式~~~日志只看到一次update以及多次select by id~~~求老哥解决下

**Comment by miemieYaho** [comment]
你的日志是什么日志?

**Comment by yangshuangjun** [comment]
简单配了~~mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

**Comment by miemieYaho** [comment]
去掉这个,用logback看

**Comment by yangshuangjun** [comment]
多谢老哥~~~看到多次更新了。~~~不懂就问，为什么更新之前都查询一次

**Comment by miemieYaho** [comment]
不查怎么知道是insert还是update呢
