### ISSUE TITLE
返回为Map时没有转成驼峰命名

### ISSUE THREAD

**Issue by zhanjunfeng** [baomidou/mybatis-plus#2004]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2，3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
用3.1.1的时候，返回类型为Map会自动转成驼峰命名，怎么从3.1.2开始就不能转了？还要是配置什么东西？

**Comment by miemieYaho** [comment]
有的人不想要,文档上有

**Comment by ikutarian** [comment]
那要怎么开启？

**Comment by ikutarian** [comment]
文档在这里，后来的朋友可以看这里

https://mp.baomidou.com/guide/faq.html#%E9%80%BB%E8%BE%91%E5%88%A0%E9%99%A4%E4%B8%8B-%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-
%E5%8A%9F%E8%83%BD%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C
