### ISSUE TITLE
oracle 想要获取查询数据的前10行应该怎么做。

### ISSUE THREAD

**Issue by 1357214904** [baomidou/mybatis-plus#2006]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
想使用 .last("limit0,1")来查询，报错。这种写法好像是mysql的

**Comment by qmdx** [comment]
last 是 放到最后，根据的数据库字符串指定你的写法

**Comment by wu9007** [comment]
@1357214904 这种写法还是得你自己做数据库兼容，要么就用分页插件。

**Comment by wu9007** [comment]
@qmdx 建议BaseMapper中加一个selectTop的方法

目前我们只能是通过默认方法实现：
![image](https://user-images.githubusercontent.com/35946000/209049869-2e31562f-c5b4-4baf-8811-035ffd8a14ad.png)
