### ISSUE TITLE
LocalDateTime的问题。。

### ISSUE THREAD

**Issue by huanghaoming** [baomidou/mybatis-plus#2013]
### 报错信息

本人菜鸟。。。一直用datetime，后来发现映射生成的是一个LocalDateTime的玩意。。。这个东西好陌生。。而且很难操作。。。例如addDay啥的方法都没有。。不像datetime有很多工具类。。。请问大伙是怎么解决这个问题的。。难道是已经有很成熟的工具类我不知道吗。。求解惑

**Comment by JieJo** [comment]
druid 1.1.20, Oracle 驱动 升级到jdbc8,mybatis-plus.version:3.3.0，查询没什么问题
