### ISSUE TITLE
wrapper搜索的条件字段能不能加上表名

### ISSUE THREAD

**Issue by thinsstar** [baomidou/mybatis-plus#2014]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用xml关联查询,使用Wrapper, xml中是${ew.customSqlSegment},但是因为两个关联表有字段名相同,wrapper直接使用实体类的属性设值时会报错.
故而想找能不能设值搜索时的条件加上实体类的表名变成 where table.column=xxx这样的格式

**Comment by miemieYaho** [comment]
用querywrapper自己定义string类型的column名
