### ISSUE TITLE
关于ServiceImpl的事务问题讨论

### ISSUE THREAD

**Issue by jnan88** [baomidou/mybatis-plus#2015]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus</artifactId>
      <version>3.0.7.1</version>
    </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

com.baomidou.mybatisplus.extension.service.impl.ServiceImpl

在saveBatch上加入 @Transactional(rollbackFor = Exception.class)
但是save、removeById、updateById、update等未加事务控制，但直接使用这些方法时就会出现事务不回滚了

**Comment by miemieYaho** [comment]
又没对数据产生影响，回滚个什么东西？
