### ISSUE TITLE
生成代码建议

### ISSUE THREAD

**Issue by gaodonghua** [baomidou/mybatis-plus#2019]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

建议在实体类中添加 Column enums 方便在 Wrapper中使用 这样就不必知道数据库字段是怎么写的了，不然还要关心数据库字段的写法

**Comment by nieqiurong** [comment]
new StrategyConfig().setEntityColumnConstant(true);
不知道这种常量是不是你想要的那种。

**Comment by gaodonghua** [comment]
> new StrategyConfig().setEntityColumnConstant(true);
> 不知道这种常量是不是你想要的那种。

是的 没找到这个配置，，，哈哈哈
