### ISSUE TITLE
使用分页插件的同时，功能查询问题

### ISSUE THREAD

**Issue by Android-Adam** [baomidou/mybatis-plus#2020]
### 当前使用版本(必须填写清楚，否则不予处理)

版本号 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

请问在使用分页插件的同时，能否指定从某条数据开始分页查询，而不是目前永远从第一条开始。

举个栗子：查询文章列表，当用户点击查看第n条时，仍然会查询一个列表数据，这个列表数据也是带分页的，不同的是，从用户点击的那条数据开始为第一条，查询在它之后且满足条件的列表

### 重现步骤

无

### 报错信息

无

**Comment by miemieYaho** [comment]
不支持

**Comment by Android-Adam** [comment]
能否支持呢？或者说，开发者自己能通过其他什么方式间接实现？
