### ISSUE TITLE
当自定义分页SQL语句中的查询字段出现传参数的值做比较时，分页传入的排序参数无效

### ISSUE THREAD

**Issue by fengyoushuang** [baomidou/mybatis-plus#2022]
### 当前使用版本(必须填写清楚，否则不予处理)
**3.3.0**

### 该问题是怎么引起的？

当自定义分页SQL语句中的查询字段出现传参数的值做比较时，分页传入的排序参数无效

### 重现步骤
_自定义sql语句：_

        SELECT  uc.*, (uc.cuid=#{request.cuid}) as hasUse
        FROM comments uc,user u
        where uc.eid=u.eid and uc.cuid=u.id and uc.mid=#{request.mid}

> (uc.cuid=#{request.cuid})  常量值和字段值比较，返回的是0或者1

传入的Page中自定义排序字段：page.addOrder(OrderItem.desc(“uc.date_time”))

### 报错信息
WARN 16173 --- [nio-3001-exec-7] c.b.m.e.plugins.PaginationInterceptor    : failed to concat orderBy from IPage, exception=null

**Comment by nieqiurong** [comment]
看样子是jsqlparser出毛病了

**Comment by miemieYaho** [comment]
jsqlparser 的异常
