### ISSUE TITLE
Postgresql 数据库字段是Jsonb 时候，使用BaseMapper的方法查询报错operator does not exist: jsonb = character varying

### ISSUE THREAD

**Issue by kong6001** [baomidou/mybatis-plus#2023]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
Postgresql 数据库字段是Jsonb 时候，使用BaseMapper的方法查询报错
但如果是在mapper 定义查询是不会报错的
	@Select("select * from xcx_mini    WHERE app_id @> '[\"3\"]'")
	Mini getOneByJSONB();

### 重现步骤
mapper文件
 
    <resultMap id="mini" type="com.zhiyi.miniapp.entity.Mini" autoMapping="true">
    …..
         <result column="app_id" property="appId"  javaType="Object"  jdbcType="OTHER" typeHandler="com.zhiyi.miniapp.general.nosql.handler.JSONTypeHandler"/>
    </resultMap>

### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: operator does not exist: jsonb = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 176
### Cause: org.postgresql.util.PSQLException: ERROR: operator does not exist: jsonb = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 176
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: jsonb = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 176

**Comment by kong6001** [comment]
已解决
属性添加注解
	@TableField(typeHandler = JSONBTypeHandler.class)

**Comment by GongZhengMe** [comment]
> 已解决
> 属性添加注解
> @TableField(typeHandler = JSONBTypeHandler.class)

请问JSONBTypeHandler.class是自己写的还是Mybatis Plus自带的，我的是3.3.0，没有这个类
