### ISSUE TITLE
Enum 类型在query时出错

### ISSUE THREAD

**Issue by helloqhx** [baomidou/mybatis-plus#2024]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**

QueryWrapper 使用enum类型的参数时，不能正确地根据MybatisEnumHandler转换。

### 重现步骤
```
public class TestModel {

    private Long companyId;

    private String companyName;

    private Boolean success;

    @TableField(typeHandler = MybatisEnumTypeHandler.class)
    private Status status;

    @AllArgsConstructor
    @Getter
    public enum Status {
        UNKNOWN(0, "未知"),
        SUCCESS(1, "成功"),
        FAILED(2, "失败");

        @EnumValue
        private final int value;

        private final String name;
    }

}
```
第一种使用方式：
```
TestModel testModel = new TestModel();
testModel.setStatus(TestModel.Status.SUCCESS);
LambdaQueryWrapper<TestModel> queryWrapper = new LambdaQueryWrapper<>(testModel);
int count = testMapper.selectCount(queryWrapper);
```
报错信息：
```
Caused by: java.lang.IllegalArgumentException: Could not find @EnumValue in Class: java.lang.Object.
	at com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler.lambda$null$0(MybatisEnumTypeHandler.java:65)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler.lambda$new$1(MybatisEnumTypeHandler.java:65)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler.<init>(MybatisEnumTypeHandler.java:64)
	... 84 more
```

第二种使用方式：
```
LambdaQueryWrapper<TestModel> queryWrapper = new LambdaQueryWrapper<>();
queryWrapper.eq(TestModel::getStatus, TestModel.Status.FAILED);
int countFailed = testModelRepo.getBaseMapper().selectCount(queryWrapper);
assertEquals(2, countFailed);
```
不能正确执行：
debug信息：
```
2019-12-31 09:22:46,792 [Test worker] DEBUG c.i.s.v.t.m.T.selectCount - ==>  Preparing: SELECT COUNT( 1 ) FROM test_model WHERE (status = ?) 
2019-12-31 09:22:46,794 [Test worker] DEBUG c.i.s.v.t.m.T.selectCount - ==> Parameters: FAILED(String)
2019-12-31 09:22:46,823 [Test worker] DEBUG c.i.s.v.t.m.T.selectCount - <==      Total: 1
```
```
expected:<2> but was:<1>
Expected :2
Actual   :1
```

**Comment by miemieYaho** [comment]
去看文档

**Comment by helloqhx** [comment]
请问一下哪里配错了吗？除了需要配置@EnumValue外，还需要什么配置吗？

**Comment by bits-bean** [comment]
> 

这态度。。。好歹你也贴一下文档链接呀

**Comment by lihuagang03** [comment]
建议提供完整的解决方法，说明问题根因，避免重复踩坑。

自动映射枚举
https://baomidou.com/guides/auto-convert-enum/

#1755 
#2141

```
Could not find @EnumValue in Class: java.lang.Object.
```

**Comment by lihuagang03** [comment]
按照官方文档，确实解决了

自动映射枚举
https://baomidou.com/guides/auto-convert-enum/

声明通用枚举属性
方式一：使用 @EnumValue 注解枚举属性

配置 MyBatis-Plus 自动映射枚举
方式二：全局修改 DefaultEnumTypeHandler

<img width="995" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/1811851/0b1a2ca7-f964-4b2f-8d33-b5733948ecbf">

<img width="979" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/1811851/18dcb259-9495-4410-97b9-c25984813694">

InterfaceCacheConfigDo
```
import java.time.LocalDateTime;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.lefit.gateway.admin.client.model.EnableStateEnum;
import com.lefit.gateway.admin.client.model.EnvironmentTagEnum;
import lombok.Data;

/**
 * 接口缓存配置【数据对象】
 *
 * @since 2024/5/17
 */
@Data
@TableName(value = "t_api_interface_cache_config", autoResultMap = true)
public class InterfaceCacheConfigDo {
    /**
     * 主键
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    // ...

    /**
     * 环境标签，1-开发环境，2-测试环境，3-预发环境，4-生产环境
     */
    @TableField(value = "environment_tag")
    private EnvironmentTagEnum environmentTag;

    /**
     * 启用状态，0-未启用，1-启用
     */
    @TableField(value = "enable_status")
    private EnableStateEnum enableStatus;

    // ...

    /**
     * 创建时间
     */
    @TableField(value = "create_time", fill = FieldFill.INSERT)
    private LocalDateTime createTime;

    /**
     * 更新时间
     */
    @TableField(value = "update_time", fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;
}
```

EnvironmentTagEnum
```
import com.baomidou.mybatisplus.annotation.EnumValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 环境标签
 *
 * @since 2024/5/17
 */
@Getter
@AllArgsConstructor
public enum EnvironmentTagEnum {
    /**
     * 开发环境
     */
    DEVELOP_ENV(0),
    /**
     * 测试环境
     */
    TEST_ENV(1),
    /**
     * 预发环境
     */
    STAGING_ENV(2),
    /**
     * 生产环境
     */
    PRODUCTION_ENV(3),
    ;

    /**
     * 标记数据库存的值是code
     */
    @EnumValue
    private final int code;
}
```

EnableStateEnum
```
import com.baomidou.mybatisplus.annotation.EnumValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 启用状态
 *
 * @since 2024/5/17
 */
@Getter
@AllArgsConstructor
public enum EnableStateEnum {
    /**
     * 未启用
     */
    NOT_ENABLE(0),
    /**
     * 启用
     */
    ENABLE(1),
    ;

    /**
     * 标记数据库存的值是code
     */
    @EnumValue
    private final int code;
}
```

application.properties
```properties
mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
```

**Comment by fengjian1993** [comment]
> 按照官方文档，确实解决了
> 
> 自动映射枚举 https://baomidou.com/guides/auto-convert-enum/
> 
> 声明通用枚举属性 方式一：使用 @EnumValue 注解枚举属性
> 
> 配置 MyBatis-Plus 自动映射枚举 方式二：全局修改 DefaultEnumTypeHandler
> 
> <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/1811851/335035974-0b1a2ca7-f964-4b2f-8d33-b5733948ecbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDI3OTksIm5iZiI6MTcyMTgwMjQ5OSwicGF0aCI6Ii8xODExODUxLzMzNTAzNTk3NC0wYjFhMmNhNy1mOTY0LTRiMmYtOGQzMy1iNTczMzk0OGVjYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMDYyODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWExMjk1Y2FkZGMzNWM2MWRiODZhN2EwZWE3YzRkZTAwOWZhOTI3NDE1MDE4MjI1MmU3YTQ0YjkzYjkzZjg3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J7smnNccNyCIpm28JMVu8D2C-7b9qCPcPLU60h-mMV0"> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/1811851/335036210-18dcb259-9495-4410-97b9-c25984813694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDI3OTksIm5iZiI6MTcyMTgwMjQ5OSwicGF0aCI6Ii8xODExODUxLzMzNTAzNjIxMC0xOGRjYjI1OS05NDk1LTQ0MTAtOTdiOS1jMjU5ODQ4MTM2OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMDYyODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVmYmExZTJmNGQ3YzEyOThlZjNiY2RhZTMzYTJmMzA5ZjE4ZmMxYTQxMTg0OTFmMTc0ZDU0MDViYWFlMjA2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WPdw_3fVrgaQp_YkBLlVn7GCWQ_Ea4iZwBzyIl7Dx1k">
> InterfaceCacheConfigDo
> 
> ```
> import java.time.LocalDateTime;
> 
> import com.baomidou.mybatisplus.annotation.FieldFill;
> import com.baomidou.mybatisplus.annotation.IdType;
> import com.baomidou.mybatisplus.annotation.TableField;
> import com.baomidou.mybatisplus.annotation.TableId;
> import com.baomidou.mybatisplus.annotation.TableName;
> import com.lefit.gateway.admin.client.model.EnableStateEnum;
> import com.lefit.gateway.admin.client.model.EnvironmentTagEnum;
> import lombok.Data;
> 
> /**
>  * 接口缓存配置【数据对象】
>  *
>  * @since 2024/5/17
>  */
> @Data
> @TableName(value = "t_api_interface_cache_config", autoResultMap = true)
> public class InterfaceCacheConfigDo {
>     /**
>      * 主键
>      */
>     @TableId(value = "id", type = IdType.AUTO)
>     private Long id;
> 
>     // ...
> 
>     /**
>      * 环境标签，1-开发环境，2-测试环境，3-预发环境，4-生产环境
>      */
>     @TableField(value = "environment_tag")
>     private EnvironmentTagEnum environmentTag;
> 
>     /**
>      * 启用状态，0-未启用，1-启用
>      */
>     @TableField(value = "enable_status")
>     private EnableStateEnum enableStatus;
> 
>     // ...
> 
>     /**
>      * 创建时间
>      */
>     @TableField(value = "create_time", fill = FieldFill.INSERT)
>     private LocalDateTime createTime;
> 
>     /**
>      * 更新时间
>      */
>     @TableField(value = "update_time", fill = FieldFill.INSERT_UPDATE)
>     private LocalDateTime updateTime;
> }
> ```
> 
> EnvironmentTagEnum
> 
> ```
> import com.baomidou.mybatisplus.annotation.EnumValue;
> import lombok.AllArgsConstructor;
> import lombok.Getter;
> 
> /**
>  * 环境标签
>  *
>  * @since 2024/5/17
>  */
> @Getter
> @AllArgsConstructor
> public enum EnvironmentTagEnum {
>     /**
>      * 开发环境
>      */
>     DEVELOP_ENV(0),
>     /**
>      * 测试环境
>      */
>     TEST_ENV(1),
>     /**
>      * 预发环境
>      */
>     STAGING_ENV(2),
>     /**
>      * 生产环境
>      */
>     PRODUCTION_ENV(3),
>     ;
> 
>     /**
>      * 标记数据库存的值是code
>      */
>     @EnumValue
>     private final int code;
> }
> ```
> 
> EnableStateEnum
> 
> ```
> import com.baomidou.mybatisplus.annotation.EnumValue;
> import lombok.AllArgsConstructor;
> import lombok.Getter;
> 
> /**
>  * 启用状态
>  *
>  * @since 2024/5/17
>  */
> @Getter
> @AllArgsConstructor
> public enum EnableStateEnum {
>     /**
>      * 未启用
>      */
>     NOT_ENABLE(0),
>     /**
>      * 启用
>      */
>     ENABLE(1),
>     ;
> 
>     /**
>      * 标记数据库存的值是code
>      */
>     @EnumValue
>     private final int code;
> }
> ```
> 
> application.properties
> 
> ```ini
> mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
> ```

你好这个参数mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler我没办法加，这个影响了所有的枚举类的TypeHander,不同的类存数据库的字段是不一样的，有写是code有些是value有些是name。
目前我在自己的枚举属性上加了@EnumValue, 实体类上加了TypeHandler,我的typeHandler构造方法报错Caused by: java.lang.IllegalArgumentException: Object does not represent an enum type. 还请赐教

**Comment by lihuagang03** [comment]
> 你好这个参数mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler我没办法加，这个影响了所有的枚举类的TypeHander,不同的类存数据库的字段是不一样的，有写是code有些是value有些是name。 目前我在自己的枚举属性上加了@EnumValue, 实体类上加了TypeHandler,我的typeHandler构造方法报错Caused by: java.lang.IllegalArgumentException: Object does not represent an enum type. 还请赐教

- 可以把你相关的完整代码，贴出来。
- `mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler`，是Spring Boot自动化配置。可以通过`MybatisConfiguration#setDefaultEnumTypeHandler`手动设置喔
- “不同的类存数据库的字段是不一样的，有写是code有些是value有些是name。” 属性字段的命名，没关系，可以任意取名。

**Comment by lihuagang03** [comment]
> 你好这个参数mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler我没办法加，这个影响了所有的枚举类的TypeHander,不同的类存数据库的字段是不一样的，有写是code有些是value有些是name。 目前我在自己的枚举属性上加了@EnumValue, 实体类上加了TypeHandler,我的typeHandler构造方法报错Caused by: java.lang.IllegalArgumentException: Object does not represent an enum type. 还请赐教

- "IllegalArgumentException: Object does not represent an enum type."，异常提示信息很明显了，字段定义的类型是枚举类型吗？ 建议把相关代码贴出来，不然在抓瞎喔。提供的信息不够看清楚问题根因

**Comment by jcatom** [comment]
> 按照官方文档，确实解决了
> 
> 自动映射枚举 https://baomidou.com/guides/auto-convert-enum/
> 
> 声明通用枚举属性 方式一：使用 @EnumValue 注解枚举属性
> 
> 配置 MyBatis-Plus 自动映射枚举 方式二：全局修改 DefaultEnumTypeHandler
> 
> <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/1811851/335035974-0b1a2ca7-f964-4b2f-8d33-b5733948ecbf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyNzYwODYsIm5iZiI6MTc1ODI3NTc4NiwicGF0aCI6Ii8xODExODUxLzMzNTAzNTk3NC0wYjFhMmNhNy1mOTY0LTRiMmYtOGQzMy1iNTczMzk0OGVjYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MTlUMDk1NjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjc5NzM1NDRiZGRiZDZjNjUyMzk4M2MzZjNiOGYxMjVmYjY2YWFmNDZiYTkzMzA1NTJjODVhNTgwYTk1YzhmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WP0nZoPLV9H-eZr86GuS2iwWzRFDoldJMeG5mLF2JYg"> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/1811851/335036210-18dcb259-9495-4410-97b9-c25984813694.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyNzYwODYsIm5iZiI6MTc1ODI3NTc4NiwicGF0aCI6Ii8xODExODUxLzMzNTAzNjIxMC0xOGRjYjI1OS05NDk1LTQ0MTAtOTdiOS1jMjU5ODQ4MTM2OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MTlUMDk1NjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2FjNDllMTU3NmRhOGI2MTFmM2M2ZTQyZmVhMjExNjFlZjEwZWRjODcxODEzNWIxNTFlNjQzNzAwMmZhZTQ2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6hfT3WrXaQVgS9z6Uh1nUGriJ7T0IaYdDJJPORmSSzY">
> InterfaceCacheConfigDo
> 
> ```
> import java.time.LocalDateTime;
> 
> import com.baomidou.mybatisplus.annotation.FieldFill;
> import com.baomidou.mybatisplus.annotation.IdType;
> import com.baomidou.mybatisplus.annotation.TableField;
> import com.baomidou.mybatisplus.annotation.TableId;
> import com.baomidou.mybatisplus.annotation.TableName;
> import com.lefit.gateway.admin.client.model.EnableStateEnum;
> import com.lefit.gateway.admin.client.model.EnvironmentTagEnum;
> import lombok.Data;
> 
> /**
>  * 接口缓存配置【数据对象】
>  *
>  * @since 2024/5/17
>  */
> @Data
> @TableName(value = "t_api_interface_cache_config", autoResultMap = true)
> public class InterfaceCacheConfigDo {
>     /**
>      * 主键
>      */
>     @TableId(value = "id", type = IdType.AUTO)
>     private Long id;
> 
>     // ...
> 
>     /**
>      * 环境标签，1-开发环境，2-测试环境，3-预发环境，4-生产环境
>      */
>     @TableField(value = "environment_tag")
>     private EnvironmentTagEnum environmentTag;
> 
>     /**
>      * 启用状态，0-未启用，1-启用
>      */
>     @TableField(value = "enable_status")
>     private EnableStateEnum enableStatus;
> 
>     // ...
> 
>     /**
>      * 创建时间
>      */
>     @TableField(value = "create_time", fill = FieldFill.INSERT)
>     private LocalDateTime createTime;
> 
>     /**
>      * 更新时间
>      */
>     @TableField(value = "update_time", fill = FieldFill.INSERT_UPDATE)
>     private LocalDateTime updateTime;
> }
> ```
> 
> EnvironmentTagEnum
> 
> ```
> import com.baomidou.mybatisplus.annotation.EnumValue;
> import lombok.AllArgsConstructor;
> import lombok.Getter;
> 
> /**
>  * 环境标签
>  *
>  * @since 2024/5/17
>  */
> @Getter
> @AllArgsConstructor
> public enum EnvironmentTagEnum {
>     /**
>      * 开发环境
>      */
>     DEVELOP_ENV(0),
>     /**
>      * 测试环境
>      */
>     TEST_ENV(1),
>     /**
>      * 预发环境
>      */
>     STAGING_ENV(2),
>     /**
>      * 生产环境
>      */
>     PRODUCTION_ENV(3),
>     ;
> 
>     /**
>      * 标记数据库存的值是code
>      */
>     @EnumValue
>     private final int code;
> }
> ```
> 
> EnableStateEnum
> 
> ```
> import com.baomidou.mybatisplus.annotation.EnumValue;
> import lombok.AllArgsConstructor;
> import lombok.Getter;
> 
> /**
>  * 启用状态
>  *
>  * @since 2024/5/17
>  */
> @Getter
> @AllArgsConstructor
> public enum EnableStateEnum {
>     /**
>      * 未启用
>      */
>     NOT_ENABLE(0),
>     /**
>      * 启用
>      */
>     ENABLE(1),
>     ;
> 
>     /**
>      * 标记数据库存的值是code
>      */
>     @EnumValue
>     private final int code;
> }
> ```
> 
> application.properties
> 
> mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler这个配置是必要条件，实现IEnum接口或使用@EnumValue才是两种方式，当不配置全局default-enum-type-handler时，只在字段上添加typeHander=MybatisEnumTypeHandler.class就会出现楼主说的这种情况。

**Comment by lihuagang03** [comment]
> mybatis-plus.configuration.default-enum-type-handler=com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler这个配置是必要条件，实现IEnum接口或使用@EnumValue才是两种方式，当不配置全局default-enum-type-handler时，只在字段上添加typeHander=MybatisEnumTypeHandler.class就会出现楼主说的这种情况。

意思明白了，没有设置全局配置，只在字段上设置了，这样就出现这个异常。
看了mybatis-plus和mybatis的源代码，`mybatis-plus.configuration.default-enum-type-handler`是org.apache.ibatis.session.Configuration#setDefaultEnumTypeHandler()里的配置，默认值是`EnumTypeHandler`。

<img width="1738" height="780" alt="Image" src="https://github.com/user-attachments/assets/d2edee41-1510-48e5-86aa-be0a6199c964" />

`MybatisEnumTypeHandler`和`EnumTypeHandler`的实现方式，是不一样的。可以在这两个类中，debug调试看看差异，或许有惊喜。
