### ISSUE TITLE
Generator代码生成器  连接mycat。生成不了模板！

### ISSUE THREAD

**Issue by 623990721** [baomidou/mybatis-plus#2025]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

连接mycat出现的。直接连接mysql数据库没有问题。

### 重现步骤
请输入表名，多个英文逗号分割： sys_users_roles
然后就报错了。
好像是数据库运行
show table status WHERE 1=1  AND NAME IN ('sys_users_roles')
这个语句是报错了。 把IN 改成 = 或者LIKE 都没问题

### 报错信息
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM ('sys_users_roles')' at line 1

**Comment by nieqiurong** [comment]
没用过mycat，暂时用3.3.1.7-SNAPSHOT，new StrategyConfig().setEnableSqlFilter(false);

**Comment by 623990721** [comment]
3.3.1.7-SNAPSHOT 什么时候发布？

**Comment by nieqiurong** [comment]
> 3.3.1.7-SNAPSHOT 什么时候发布？

都发了好久了，现在可以用3.3.1.8-SNAPSHOT使用参考。https://mp.baomidou.com/guide/install.html#release
