### ISSUE TITLE
java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.mybatis.spring.annotation.MapperScan.factoryBean()

### ISSUE THREAD

**Issue by javaforrest** [baomidou/mybatis-plus#203]
这是启动类
`
@EnableAsync
@EnableAutoConfiguration
@SpringBootApplication
@MapperScan(basePackages={"com.dooper.winshop.mapper"})
public class Application extends SpringBootServletInitializer {
	
	@Override  
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {  
        return application.sources(Application.class);  
    }  
	
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
	
}
`
下面是maven引用jar包版本
`<properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <java.version>1.8</java.version>
           	<maven.compiler.source>1.8</maven.compiler.source>
			<maven.compiler.target>1.8</maven.compiler.target>
			<mybatisplus-spring-boot-starter.version>1.0.5</mybatisplus-spring-boot-starter.version>
			<mybatisplus.version>2.1.7</mybatisplus.version>
			<HikariCP.version>2.7.2</HikariCP.version>
			<fastjson.version>1.2.39</fastjson.version>
     </properties>
	`

**Comment by javaforrest** [comment]
springboot版本问题，使用1.5.7版本解决

**Comment by qmdx** [comment]
解决就好 closed
