### ISSUE TITLE
1、selectPage 方法 in查询 不能查出数据；2、in中参数是字符类型，数据库字段是数字类型，会报错：无效数字。

### ISSUE THREAD

**Issue by fore2016** [baomidou/mybatis-plus#2032]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

1、selectPage 方法 in查询 不能查出数据，但是把sql语句在Oracle 是可以查询出来的。
2、把sql语句在Oracle 是可以查询出来的

### 报错信息
无报错。
: ==>  Preparing: SELECT COUNT(1) FROM VIEW_RTP_RETAIL01 WHERE (retailid IN (?, ?, ?, ?, ?, ?) AND comid = ? AND shopid = ?) 
: {conn-10001, pstmt-20049} created. SELECT COUNT(1) FROM VIEW_RTP_RETAIL01 WHERE (retailid IN (?, ?, ?, ?, ?, ?) AND comid = ? AND shopid = ?)
: ==> Parameters: '64167208146219008'(String), '64167064176734208'(String), '63446729715548160'(String), '63446664573812736'(String), '59718590542192640'(String), '59456827698520064'(String), 320401000004(Long), 1009001(Long)
: {conn-10001, pstmt-20049} Parameters : ['64167208146219008', '64167064176734208', '63446729715548160', '63446664573812736', '59718590542192640', '59456827698520064', 320401000004, 1009001]
: {conn-10001, pstmt-20049} Types : [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, BIGINT]
: {conn-10001, pstmt-20049, rs-50045} query executed. 2.889954 millis. SELECT COUNT(1) FROM VIEW_RTP_RETAIL01 WHERE (retailid IN (?, ?, ?, ?, ?, ?) AND comid = ? AND shopid = ?)
: {conn-10001, pstmt-20049, rs-50045} open
: {conn-10001, pstmt-20049, rs-50045} Header: [COUNT(1)]
: {conn-10001, pstmt-20049, rs-50045} Result: [0]
: {conn-10001, pstmt-20049, rs-50045} closed
: {conn-10001, pstmt-20049} closed
: {conn-10001} pool-recycle

**Comment by miemieYaho** [comment]
自行排查,注意 https://mp.baomidou.com/config/#mapunderscoretocamelcase
