### ISSUE TITLE
count()方法加上条件后返回0

### ISSUE THREAD

**Issue by a413528002** [baomidou/mybatis-plus#2033]
### 当前使用版本(必须填写清楚，否则不予处理)
3.30

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用lambdaquery().eq().count()返回值一直是0，把打印出来的sql拿到数据库执行是能得到结果的
如果没有任何条件则能得到正确的值

### 报错信息

没有

**Comment by miemieYaho** [comment]
无法复现，自行排查

**Comment by kevin0307** [comment]
我也遇到了这个问题，数据有数据，查询就是 返回0
