### ISSUE TITLE
设置排除表，ConfigBuilder在拼接show table sql时，获取include，但include必为空

### ISSUE THREAD

**Issue by wjse** [baomidou/mybatis-plus#2034]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

 sql.append(" AND ").append(dbQuery.tableName()).append(" NOT IN (")
                    .append(Arrays.stream(config.getInclude()).map(tb -> "'" + tb + "'").collect(Collectors.joining(","))).append(")");

**Comment by nieqiurong** [comment]
#1942

**Comment by nieqiurong** [comment]
使用3.3.1.8-SNAPSHOT试试
