### ISSUE TITLE
active record模式出错 

### ISSUE THREAD

**Issue by happyblizzard** [baomidou/mybatis-plus#2038]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0版本自动生成代码，以activerecord模式，调用时异常：
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: xuefeng.springlearn.repository.model.Student Not Found TableInfoCache.

**Comment by miemieYaho** [comment]
需要有对应的mapper

**Comment by happyblizzard** [comment]
代码时自动生成的，有mapper，还是不行，我再琢磨琢磨吧

**Comment by Gang-bb** [comment]
> 代码时自动生成的，有mapper，还是不行，我再琢磨琢磨吧

请问解决了吗？
