### ISSUE TITLE
打扰一下，3.0+版本是否支持自定义sql条件查询?

### ISSUE THREAD

**Issue by zhuyouzhufu** [baomidou/mybatis-plus#2039]
我现在需要执行一下sql：
select * from table_name where TO_DAYS(字段名) = TO_DAYS(NOW())
可否支持这样写：
queryWrapper.lambda().where(sql语句字符串) 或 queryWrapper.where(sql语句字符串) 
queryWrapper.lambda().and(sql字符串)  或 queryWrapper.and(sql字符串) 
我看2.0版本是有一个EntityWrapper支持这种操作，
![image](https://user-images.githubusercontent.com/34908518/71673870-d5a5d680-2db4-11ea-8a4b-89e797fea8c2.png)

遗憾的是3.x以上的版本我在文档没有查询到对应的方法，如果有大佬看到了可否请教一下这个如何处理，我不想写SQL

**Comment by miemieYaho** [comment]
apply

**Comment by zhuyouzhufu** [comment]
谢谢大哥，刚刚在群里找到3.0以上的文档
