### ISSUE TITLE
sqlite3库级锁问题和自动化创建表

### ISSUE THREAD

**Issue by zhbitzwz** [baomidou/mybatis-plus#2040]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
1.使用sqlite3在多线程写的情况下出现库级锁问题，mybatis-plus可以在业务无侵入下在底层解决这个问题吗？如果想做到业务最小化改造，有没有建议性的方案，谢谢！
2.什么时候支持springboot对sqlite自动化创建表，谢谢！

### 重现步骤
使用sqlite3,多线程写出现库级锁，抛出异常

### 报错信息
sqlite exception:The database file is locked (database is locked)

**Comment by miemieYaho** [comment]
锁住了那是你的问题，mp不支持根据entity建表
