### ISSUE TITLE
mybatis plus 的 lambda 方式是否支持根据请求参数, 使用动态排序功能

### ISSUE THREAD

**Issue by FollowTheTrend** [baomidou/mybatis-plus#2043]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
需求是想通过页面传过来的参数, 利用 lambda 以实现动态排序功能

### 重现步骤
需求是想通过页面传过来的参数, 利用 lambda 以实现动态排序功能
```java
 List<TestPo> testPoList = testService.lambdaQuery()
                // .orderBy(testParam.getOrderBy())
                .list();
```

### 报错信息
无

**Comment by miemieYaho** [comment]
不能

**Comment by Blusez** [comment]
为啥不能加这种能力？第一次用mybatis-plus，发现很多功能都没有，我觉得这是个很正常的功能啊
