### ISSUE TITLE
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.getObj,参数function到底有什么用

### ISSUE THREAD

**Issue by yanluhua** [baomidou/mybatis-plus#2044]
### 当前使用版本3.5.3
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl#getObj(Wrapper<T> queryWrapper, Function<? super Object, V> mapper)，我理解代码的意思是是要获取某个对象的某个字段的集合，

### 
Function<? super Object, V> mapper这个参数，下限约定的条件只能是Object对象，那么就只能使用Object的方法，并不能使用自己的实体Entity。
例如：
Function<? super Object, V> mapper=Object::hashCode。
例如我想获取苹果，重量的集合
Function<? super Object, V> mapper=Apple::getColor,这种是无法使用的

我觉得这个方法，第二个参数是否改成Function<? super T， V>这种方式会好点

**Comment by miemieYaho** [comment]
不是

**Comment by yanluhua** [comment]
那这个方法的使用场景是在哪里，该如何使用

**Comment by miemieYaho** [comment]
object转其他

**Comment by chace0120** [comment]
getObj查出来的是符合查询条件的数据中的首个字段数据，比如主键id。然后可以通过Function参数将主键id进行处理转换等操作。
