### ISSUE TITLE
mybatis-plus 的 IService 接口和dubbo的大部分Serialization不能兼容

### ISSUE THREAD

**Issue by 643562798** [baomidou/mybatis-plus#2045]
我用mybatis-plus3.2和dubbo2.7整合时，如果使用实现IService接口的class作为服务提供者，希望用到IService中便利的方法，dubbo的Serialization对参数和返回值都有约束，基本都不兼容。目前dubbo有下列Serialization：
`fastjson=org.apache.dubbo.common.serialize.fastjson.FastJsonSerialization
fst=org.apache.dubbo.common.serialize.fst.FstSerialization
hessian2=org.apache.dubbo.common.serialize.hessian2.Hessian2Serialization
native-hessian=org.apache.dubbo.serialize.hessian.Hessian2Serialization
java=org.apache.dubbo.common.serialize.java.JavaSerialization
compactedjava=org.apache.dubbo.common.serialize.java.CompactedJavaSerialization
nativejava=org.apache.dubbo.common.serialize.nativejava.NativeJavaSerialization
kryo=org.apache.dubbo.common.serialize.kryo.KryoSerialization
kryo2=org.apache.dubbo.common.serialize.kryo.optimized.KryoSerialization2
avro=org.apache.dubbo.common.serialize.avro.AvroSerialization
protostuff=org.apache.dubbo.common.serialize.protostuff.ProtostuffSerialization

gson=org.apache.dubbo.common.serialize.gson.GsonSerialization

protobuf-json=org.apache.dubbo.common.serialize.protobuf.support.GenericProtobufJsonSerialization
protobuf=org.apache.dubbo.common.serialize.protobuf.support.GenericProtobufSerialization
`

**Comment by miemieYaho** [comment]
不支持传递wrapper
