### ISSUE TITLE
3.1.2 升级到 3.3.0出现错误

### ISSUE THREAD

**Issue by bushadie** [baomidou/mybatis-plus#2046]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2 升级到 3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
升级到3.3.0版本出现问题

### 重现步骤
springboot maven,  原来的3.1.2 的 pom配置可以运行,升级到3.3.0后无法开启.
maven重下也无法解决

### 报错信息
`***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:196)

The following method did not exist:

    'void com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.setDefaultScriptingLanguageDriver(java.lang.Class)'

The method's class, com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean, is available from the following locations:

    jar:file:/C:/Users/15755/.m2/repository/com/baomidou/mybatis-plus-extension/3.1.1/mybatis-plus-extension-3.1.1.jar!/com/baomidou/mybatisplus/extension/spring/MybatisSqlSessionFactoryBean.class

It was loaded from the following location:

    file:/C:/Users/15755/.m2/repository/com/baomidou/mybatis-plus-extension/3.1.1/mybatis-plus-extension-3.1.1.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean

Process finished with exit code 1
`

**Comment by miemieYaho** [comment]
jar冲突
