### ISSUE TITLE
关于sql语句的构建

### ISSUE THREAD

**Issue by Gauss-s** [baomidou/mybatis-plus#2047]
简单看了一下源码，querywrapper中没有直接返回sql的方法，只能通过配置文件的设置来在控制台进行打印，如果可以增加一个方法将sql打印出来可以更加方便使用，因为目前我准备使用Phoenix，所以准备借鉴这个项目来给出wrapper统一构建sql语句。还有一个问题，如果使用此项目进行相应修改，能否发送到个人github上，是否存在版权问题，希望得到回答谢谢😜

**Comment by miemieYaho** [comment]
wrapper 只能构建 sql 的一部分,遵守 Apache License 2.0 随便你怎么玩
