### ISSUE TITLE
枚举报错

### ISSUE THREAD

**Issue by jf-xiao** [baomidou/mybatis-plus#205]
如果我配置了 
mybatis-plus.typeEnumsPackage=cn.xiaojf.springboot.mybatisplus.entity.enums
但是Java package下没有任何类，如
![image](https://user-images.githubusercontent.com/6881671/34336082-1595c9b0-e98f-11e7-9e0a-829567f0688d.png)
就会报错
![image](https://user-images.githubusercontent.com/6881671/34336087-2dbe5aa2-e98f-11e7-8415-557ba1811c66.png)
请假一个非空判断，谢谢

**Comment by qmdx** [comment]
这是源码内部故意抛出的异常，不适用请不要配置
