### ISSUE TITLE
建议增加SuperBuilder 选项，勾选SuperBuilder 增加 @SuperBuilder() 或 @SuperBuilder(toBuilder = true),

### ISSUE THREAD

**Issue by moyutech** [baomidou/mybatis-plus#2053]
### 当前使用版本(必须填写清楚，否则不予处理)
2.7.8-191-193

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

目前勾选Builder选项，生成的实体使用@Builder注解，如果实体继承BaseEntity，会出现错误，
建议增加SuperBuilder 选项，勾选SuperBuilder 增加 @SuperBuilder() 或 @SuperBuilder(toBuilder = true)

**Comment by qmdx** [comment]
说的是生成器？

**Comment by moyutech** [comment]
发错了

**Comment by HengCC** [comment]
我猜是继承了Model , 我遇到的应该也是类似这样的问题.
```
public class BaseEntity<T extends Model<?>> extends Model<T> {...}
```
然后实体类继承BaseEntity的时候. 无法使用lombok的SuperBuilder注解.  因为model上没有. 
@qmdx
