### ISSUE TITLE
关于Service save后不返回id的问题

### ISSUE THREAD

**Issue by haoyousb** [baomidou/mybatis-plus#2054]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
前提： 实体类已经配置过 @TableId 注解，主键类型自增
测试： 用Mapper insert实体类    和  Service save实体类做测试
结果： Service save后id未赋值

![1578452210900](https://user-images.githubusercontent.com/5801082/71946791-c6d08100-3205-11ea-9d30-f28fa4d35d14.jpg)
![1578452351962](https://user-images.githubusercontent.com/5801082/71946860-f4b5c580-3205-11ea-9530-0023cdc43a4e.jpg)

如果确实是bug的话，希望官方能尽快解决谢谢~

**Comment by qmdx** [comment]
auto 数据库需要设置自增，会自动获取自增结果

**Comment by haoyousb** [comment]
您是指表里的id要设置为自增么？   已经是自增了   要不控制台也不会打印出来18
