### ISSUE TITLE
我拉下代码改成了maven管理依赖，发现部分依赖可能可以优化，希望对你们有用

### ISSUE THREAD

**Issue by siblesos** [baomidou/mybatis-plus#2056]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.1.8-snapshot
我拉下代码改成了maven管理依赖，发现部分依赖可能可以优化，希望对你们有用。另外建议咱们的mybatis-plus 大版本跟依赖的 springboot-startar  一致，避免某些未知冲突。
下面提交的依赖基于springboot 2.0.9.RELEASE .
mybatis-spring-boot-starter 2.0.1 是基于该版本
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <kotlin-reflect.version>1.3.61</kotlin-reflect.version>
        <kotlin-stdlib-jdk8.version>1.3.61</kotlin-stdlib-jdk8.version>
        <jsqlparser.version>3.1</jsqlparser.version>
        
        
        
        <mybatis-thymeleaf.version>1.0.1</mybatis-thymeleaf.version>
        <mybatis-freemarker.version>1.2.0</mybatis-freemarker.version>
        <mybatis-velocity.version>2.1.0</mybatis-velocity.version>
        

        <aspectjrt.version>1.0.1</aspectjrt.version>
        <cglib.version>3.3.0</cglib.version>
        <lombok.version>1.18.4</lombok.version>
        
        <aspectjweaver.version>1.9.5</aspectjweaver.version>
        
        
        
        <mybatis-spring-boot-starter.version>2.0.1</mybatis-spring-boot-starter.version>
        
        <junit-jupiter.version>5.4.2</junit-jupiter.version>
        <mockito-junit-jupiter.version>3.2.4</mockito-junit-jupiter.version>

        <fastjson.version>1.2.62</fastjson.version>
        <gson.version>2.8.5</gson.version>
        <jodd-lagarto.version>5.1.0-20190624</jodd-lagarto.version>
        
        <p6spy.version>3.8.7</p6spy.version>

        <sqlserver.version>4.0</sqlserver.version>
        <postgresql.version>42.2.9</postgresql.version>
        <oracle.version>12.1.0.1</oracle.version>
        
        <h2.version>1.4.200</h2.version>
        <mysql.version>8.0.18</mysql.version>
        <sqlite.version>3.30.1</sqlite.version>
        
        <velocity-engine-core.version>2.1</velocity-engine-core.version>
        <beetl.version>3.0.16.RELEASE</beetl.version>

        <swagger-annotations.version>1.5.3</swagger-annotations.version>

        <spring-boot-starter.version>2.0.9.RELEASE</spring-boot-starter.version>
        
        

    </properties>

### 重现步骤
放大

### 报错信息

[整理后的依赖关系.txt](https://github.com/baomidou/mybatis-plus/files/4033435/default.txt)

**Comment by qmdx** [comment]
源码的依赖是为了兼容各种情况的不是没啥用
