### ISSUE TITLE
auto 数据库需要设置自增，会自动获取自增结果

### ISSUE THREAD

**Issue by haoyousb** [baomidou/mybatis-plus#2057]
auto 数据库需要设置自增，会自动获取自增结果

_Originally posted by @qmdx in https://github.com/baomidou/mybatis-plus/issues/2054#issuecomment-571870493_

id列已经配置成自增了
id    bigint auto_increment primary key,

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by haoyousb** [comment]
建表语句：
create table test
     (
       id          bigint auto_increment
         primary key,
       nick_name   varchar(255)                        not null
       comment '用户昵称'
     )
       comment '测试表'



测试代码:

        Test t1 = new Test();
        t1.setNickName("111");
        testService.save(t1);
        System.out.println("-用Service插入数据-->" + t1.getId());

        Test t2 = new Test();
        t2.setNickName("2222");
        testMapper.insert(t2);
        System.out.println("-用Mapper插入数据-->" + t2.getId());

实体类(不让传java文件  我改成txt了)

[Test.txt](https://github.com/baomidou/mybatis-plus/files/4033510/Test.txt)

**Comment by haoyousb** [comment]
这个是我这边的运行结果

![1578454839282](https://user-images.githubusercontent.com/5801082/71948686-c804ac80-320b-11ea-9b03-3d2d757a5152.jpg)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/MysqlTestDataMapperTest.java 无法复现
1. 注释掉 build.gradle 180行 
2. 修改 (DBConfig 44-46行数据库连接信息)[https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/config/DBConfig.java]
3. 直接运行 (Test 94行的method)[https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/MysqlTestDataMapperTest.java]

**Comment by haoyousb** [comment]
关于第三部 ：直接运行 Test 94行的method

第103行不要用 mysqlMapper.insert
改用mysqlDataService.save

成功之后  id是空的

**Comment by haoyousb** [comment]
mapper的insert方法是有效的  

service的save方法有问题

**Comment by miemieYaho** [comment]
service就是调用的mapper的insert

**Comment by haoyousb** [comment]
您这边方便用MysqlDataService试一下么

**Comment by miemieYaho** [comment]
要试你自己试,试出来了你就写个demo传git上发出来看看
