### ISSUE TITLE
debug发现BaseMapper.selectById,其sql select字段,表名都是小写,导致不能操作大小写敏感的数据库

### ISSUE THREAD

**Issue by wangddddd** [baomidou/mybatis-plus#2058]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0
debug发现BaseMapper.selectById的sql select字段,表名都是小写,导致不能操作大小写敏感的数据库。
如何让BaseMapper以大写的SQL访问数据库

**Comment by miemieYaho** [comment]
看文档
