### ISSUE TITLE
多表连接时为where条件列指定所属表名

### ISSUE THREAD

**Issue by MQTimor** [baomidou/mybatis-plus#2059]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis plus boot 3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

join查询时 where 条件的列 如 create_by 多个表同时拥有该字段 能否手动指定所属a表或b表

**Comment by miemieYaho** [comment]
不能

**Comment by MQTimor** [comment]
干脆利落 我敬你是条汉子

**Comment by zaiao** [comment]
试了一下，直接写成 u.create_by= 就可以
