### ISSUE TITLE
有排序字段 查询list异常

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#206]
int total = this.selectCount(wrapper);
		wrapper.orderBy("create_time", false);
		List<BusSoftOrder> records = busSoftOrderDao.selectPage(page, wrapper);
数据库是sqlserver2005

**Comment by qmdx** [comment]
无力吐槽 sqlserver  1、要么升级到 2012 以后  2、换数据库吧  3、自己修改 MP 源码
