### ISSUE TITLE
代码生成器3.3.0 sqlserver下出错

### ISSUE THREAD

**Issue by Wayne-ll** [baomidou/mybatis-plus#2060]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator 3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
当数据库为mssqlserver的时候代码生成器就会出现问题

### 重现步骤
3.3.0版本下 DbType.SQL_SERVER 生成代码时
观察到ConfigBuilder类 476行执行的sql如下
select cast(so.name as varchar(500)) as TABLE_NAME, cast(sep.value as varchar(500)) as COMMENTS from sysobjects so left JOIN sys.extended_properties sep on sep.major_id=so.id and sep.minor_id=0 where (xtype='U' or xtype='v') AND TABLE_NAME IN ('表名称')
因而出错提示 列名 'TABLE_NAME' 无效。
现在使用3.1.0的代码生成器正常
### 报错信息
com.microsoft.sqlserver.jdbc.SQLServerException: 列名 'TABLE_NAME' 无效。

**Comment by nieqiurong** [comment]
#1917
