### ISSUE TITLE
oracle 使用instr 查询不出来 在Navicat能查询出来

### ISSUE THREAD

**Issue by liyang1987jay** [baomidou/mybatis-plus#2062]
### 当前使用版本(必须填写清楚，否则不予处理)
版本为3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用sql语句为
SELECT
	R.ID,
	R.CH_NAME,
	R.EN_NAME,
	R.PT_NAME,
	R.TYPE,
	R.MEMO,
	R.CH_MEMO,
	R.PT_MEMO,
	R.SEQ,
	R.ROLE_NAME 
FROM
	SYS_ROLE R 
WHERE
	R.DELETE_STATE = 1
	and instr (LOWER(R.ROLE_NAME)||LOWER(R.CH_NAME)||LOWER(R.PT_NAME),LOWER('办事员'))>0
ORDER BY
	R.UPDATE_TIME DESC,
	R.CREATE_TIME DESC,
	R.ID
### 重现步骤
mapper文件为
![image](https://user-images.githubusercontent.com/4651483/72015552-3ffdc180-3262-11ea-9d20-2d86e94fdbb5.png)

### 报错信息
代码层面查询不出数据
![image](https://user-images.githubusercontent.com/4651483/72015709-910db580-3262-11ea-8b38-9f26dba08de6.png)

Navicat可以查询出来
![image](https://user-images.githubusercontent.com/4651483/72015681-84895d00-3262-11ea-9bb0-d5394126fc33.png)

**Comment by miemieYaho** [comment]
自行排查,sql执行是mybatis的事
