### ISSUE TITLE
长得一样就等于同一个?

### ISSUE THREAD

**Issue by ubuntu-m** [baomidou/mybatis-plus#2066]
长得一样就等于同一个?

_Originally posted by @miemieYaho in https://github.com/baomidou/mybatis-plus/issues/2065#issuecomment-572524537_

我是说他两长得一样，但是对应的class对象不一样

**Comment by ubuntu-m** [comment]
你们这么明目张胆的写BUG难道不虚心接受意见？有点开源精神 好吗？

**Comment by miemieYaho** [comment]
不一样很正常

**Comment by ubuntu-m** [comment]
你说的是对的，肯定不一样，我的问题是正因为class不一样，所以LambdaUtil中的缓存永远命不中

**Comment by monightsky** [comment]
这个如果不一样作为缓存的key要如何使用呢，因为永远无法命中了！

**Comment by ubuntu-m** [comment]
问题听明白了吗？这种命不中的缓存加上是显得mybatis plus有多快吗？

**Comment by miemieYaho** [comment]
命中命不中就靠你口嗨了?热门接口还会命不中?还oom?你们跑java项目就配128mb内存?

**Comment by ubuntu-m** [comment]
到现在还没明白bug所在 ...... 提示你一下。这个缓存中的每一条数据是永远无法命中。而且数据一直倍增。即使不OOM，你这么明目张胆写bug。谁教你的？




| |
马雪峰
|
|
邮箱：17793873123@163.com
|

签名由 网易邮箱大师 定制

在2020年01月09日 21:44，miemieYaho 写道：

命中命不中就靠你口嗨了?热门接口还会命不中?还oom?你们跑java项目就配128mb内存?

**Comment by miemieYaho** [comment]
你才没明白,命中是肯定会命中的,参考 https://github.com/baomidou/mybatis-plus/issues/1183 以及 [H2UserTest 503行的test](https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/h2/H2UserTest.java)

**Comment by hcl04** [comment]
怎么命不中，第二次调这个方法不就命中了？

内存可能大一点点点，溢出那肯定不至于。最多一个 key 多个地址引用（4 byte 左右）
