### ISSUE TITLE
使用lambdaUpdate时, updateFill失效

### ISSUE THREAD

**Issue by scolia** [baomidou/mybatis-plus#2068]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

当使用LambdaUpdateWrapper进行更新时, 发现updateFill并不会生效. 是否updateFill就是不支持LambdaUpdateWrapper的, 如果是, 请在文档中注明. 我并没有在文档中找到有相关的限制条件.

### 重现步骤

```
LambdaUpdateWrapper<TestEntity> update = Wrappers.lambdaUpdate();
update.set(TestEntity::getName, "bca");
update.eq(TestEntity::getName, "abc");
testMapper.update(null, update);
```

顺带一提, 当update的时候使用

```
testMapper.update(new TestEntity(), update);
```

又可以重新生效, 这个新new的Entity会对update语句造成什么影响

**Comment by miemieYaho** [comment]
有entity才能填充，entity也是set的一部分

**Comment by scolia** [comment]
如果我使用new的新entity, 不设置任何属性, 就不会影响生成的sql中set的自动吧

**Comment by miemieYaho** [comment]
那得看你字段的更新策略了 updateStrategy
