### ISSUE TITLE
支持javax.persistence

### ISSUE THREAD

**Issue by mrtylerzhou** [baomidou/mybatis-plus#2070]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0

### 报错信息

无

**Comment by mrtylerzhou** [comment]
支持javax.persistence下的注解,虽然自带注解问题也不大,但是支持java规范的注解能显著减少初学者负担,快速上手,并且增加亲切感.

**Comment by miemieYaho** [comment]
不支持,没有共通性
