### ISSUE TITLE
集成SpringBoot配置logging后，无法在日志文件输出mybatis-plus banner

### ISSUE THREAD

**Issue by maonings** [baomidou/mybatis-plus#2071]
### 配置文件截图

![2](http://images.maonings.com/issue/2020-01-10_15-21.png)
![1](http://images.maonings.com/issue/2020-01-10_15-21_1.png)
![2](http://images.maonings.com/issue/2020-01-10_15-22.png)

**Comment by miemieYaho** [comment]
那个是直接控制台打印的

**Comment by maonings** [comment]
> 那个是直接控制台打印的

了解，谢谢回复
