### ISSUE TITLE
资源未关闭

### ISSUE THREAD

**Issue by monightsky** [baomidou/mybatis-plus#2072]
### 当前使用版本(必须填写清楚，否则不予处理)
3.10

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
看代码看到的，com.baomidou.mybatisplus.core.toolkit.SerializationUtils
![image](https://user-images.githubusercontent.com/30967098/72149360-ed491480-33dd-11ea-9be7-cefe2c7c3a6c.png)

**Comment by miemieYaho** [comment]
从之前的spring 里 copy 出来的 https://github.com/spring-projects/spring-framework/commit/5b1b1bae37318a917c7a27a88ab5870393ded1d2#diff-737f52119bf2a11d8b79193f784ab3b4

**Comment by miemieYaho** [comment]
已从spring copy了最新代码
