### ISSUE TITLE
ORACLE 使用序列自增生成器，是不是应该默认使用表名+特定前后缀

### ISSUE THREAD

**Issue by fanyijie** [baomidou/mybatis-plus#2073]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
优化使用建议，感觉oracle场景应该是批量需求ID自增

**Comment by qmdx** [comment]
https://mybatis.plus/guide/sequence.html
