### ISSUE TITLE
Unpermitted character

### ISSUE THREAD

**Issue by z125499702** [baomidou/mybatis-plus#2074]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

UNION ALL 排序部分结果时出错。

### 重现步骤
mapper.xml:
(
        select * from xxxxxxx
)
UNION ALL
(
        select * from xxxxx rs
        order by rs.lease_start_time
)
service.java:
 List<xxxxxVO> useablePutDotList = xxxxxxMapper.searchxxxxList(page,xxxxDTO);

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IllegalArgumentException: Unpermitted character 
)
### Cause: java.lang.IllegalArgumentException: Unpermitted character 
)

**Comment by nieqiurong** [comment]
版本太久远了，你还是上传一份栗子上来把，或者把完整的日志传上来。
