### ISSUE TITLE
在entity中配置了IdType.AUTO，是否还能在插入时保留entity中id字段的值？v3.1.2

### ISSUE THREAD

**Issue by agostop** [baomidou/mybatis-plus#2075]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

如果在entity上配置了IdType.AUTO，那么插入数据库时，即使entity中有id的值，也会重新生成一个新的主键，能否使用什么方法，能在id字段有值的时候，保留改主键的值，直接使用该主键值来进行插入?

**Comment by miemieYaho** [comment]
没有

**Comment by agostop** [comment]
那问下是否可以使用mybatis源生的KeyGenerator接口，而非项目中的IKeyGenerator来定义key生成器呢？

**Comment by miemieYaho** [comment]
IKeyGenerator 约等于 SelectKeyGenerator
