### ISSUE TITLE
MybatisSimpleExecutor.doQuery

### ISSUE THREAD

**Issue by chenhuaiao** [baomidou/mybatis-plus#2076]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
</dependency>

### 重现步骤
项目首次启动，调用db业务查询或者新增，耗时比较旧，发现是MybatisSimpleExecutor.doQuery占用的时间比较长，请问如何优化

**Comment by miemieYaho** [comment]
这是cv并重写 mybatis 的 SimpleExecutor 了部分逻辑(缓存相关),你应该自己排查一下
