### ISSUE TITLE
id没有设置，但是自动生成且类型不匹配

### ISSUE THREAD

**Issue by aohanhongzhi** [baomidou/mybatis-plus#2080]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 重现步骤

请查看腾讯文档详细记录
https://docs.qq.com/doc/DSFZmWExva0xwUW52

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/guide/annotation.html#tablename
https://mp.baomidou.com/config/#idtype
