### ISSUE TITLE
MybatisMapperRefresh 使用问题，先别关啊，我知道删除了

### ISSUE THREAD

**Issue by jht385** [baomidou/mybatis-plus#2082]
### 当前使用版本(必须填写清楚，否则不予处理)
没有引用mp，只是最新版的sb+mybatis

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
eclipse开发，只是不想在开发时xml修改要重启，也不喜欢还要安装插件这种需要依赖外部资源的方式，直接拿了mp的MybatisMapperRefresh类使用，在使用的时候出现问题

### 重现步骤
我写了一个案例
https://github.com/jht385/sb-dynamic-xml
使用MybatisMapperRefresh在清除缓存重新构建时，会提示已经绑定了对应的namespace.id
或者 是删除后绑定不上，再次调用查询会找不到对应的语句
目前使用我从网上找的MybatisMapperRefreshAllKill全清再构建不会出现上面问题，但是太不优雅了，大佬棒棒看看什么问题

**Comment by nieqiurong** [comment]
自行研究把，全清改一个加载所有，得不偿失，不全清还存在sql节点应用问题。
