### ISSUE TITLE
3.3.0 cannot find lambda cache for this property of entity

### ISSUE THREAD

**Issue by kanghouchao** [baomidou/mybatis-plus#2086]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

版本从3.1.0升级到3.2.0后，原来使用lambda表达式执行修改操作报错

### 重现步骤
使用3.2.0
类似问题是 #1428

### 报错信息

![image](https://user-images.githubusercontent.com/14899450/72321558-24ba0880-36df-11ea-93f5-fdd03974d2c6.png)

**Comment by kanghouchao** [comment]
![{1248E68E-D9CE-4D22-8E1A-4799D01066EB}](https://user-images.githubusercontent.com/14899450/72325779-d1e54e80-36e8-11ea-8a7a-6112da694213.jpg)

**Comment by kanghouchao** [comment]
写问题描述之前我用的是3.2.0，但是写的过程中用3.3.0测试了一下，也是一样的问题，改了标题，忘记改问题描述里面的版本号了

**Comment by kanghouchao** [comment]
试了3.1.0，3.1.2  3.2.0和3.3.0

只有3.1.0支持类似写法

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by kanghouchao** [comment]
完整代码弄不出来
先给一个示例代码，完整的demo我稍后写一个

`@Validated
public class BaseServiceImpl<M extends BaseMapper<T>, T extends BaseEntity> extends ServiceImpl<M, T> implements BaseService<T> {

       private Class<T> entityClass;

       ......

	@Override
	public boolean deleteLogic(@NotEmpty List<Integer> ids) {
                T entity = BeanUtil.netInstance(entityClass);
                entity.setUpdateUser(....);
                .....
		return super.update(entity, new UpdateWrapper<T>().lambda().in(T::getId, ids);
	}

}`

**Comment by miemieYaho** [comment]
T::getId ,现在不支持这种

**Comment by kanghouchao** [comment]
那这个方法不可用了？还是有 其他的传参方式

**Comment by miemieYaho** [comment]
不支持泛型,你非要这么用就用 `3.3.1.10-SNAPSHOT` ,该版本下直接new LambdaWrapper 使用 entityclass 入参的构造函数

**Comment by kanghouchao** [comment]
好吧

**Comment by kanghouchao** [comment]
如果实例里面设置了逻辑删除字段，就在调用remove方法的时候触发自动填充的update也能实现这个效果

**Comment by miemieYaho** [comment]
只能用 LambdaWrapper 的 entityclass 入参的构造器 new

**Comment by ye17186** [comment]
T::getId 这种用法，后续还考虑支持吗？
