### ISSUE TITLE
like 引起得排序问题

### ISSUE THREAD

**Issue by lhf-programer** [baomidou/mybatis-plus#2087]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用like 时, page.setOrders 设置排序无效生效
错误: failed to concat orderBy from IPage, exception=null

### 重现步骤
使用like 时, page.setOrders 设置排序无效生效

### 报错信息
错误: failed to concat orderBy from IPage, exception=null

**Comment by miemieYaho** [comment]
用最新版给出你的复现demo

**Comment by lhf-programer** [comment]
用3.3.0 版本试过了，还是有，dome要什么样得？一个项目么？

**Comment by lhf-programer** [comment]
正常: ![normal](https://user-images.githubusercontent.com/32329839/72336726-4c6b9980-36fc-11ea-9598-0110c205ecc8.png)
错误: ![error](https://user-images.githubusercontent.com/32329839/72336891-9785ac80-36fc-11ea-9df6-3b0708e5e7ad.png)

**Comment by miemieYaho** [comment]
git项目

**Comment by lhf-programer** [comment]
https://github.com/lhf-programer/mybatis-demo 测试项目

**Comment by miemieYaho** [comment]
jsqparser不支持这种xml写like的方式,请用 concat
