### ISSUE TITLE
关于用达梦数据库无法解析转义字符\n的问题

### ISSUE THREAD

**Issue by xuzining** [baomidou/mybatis-plus#2088]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在使用达梦数据库DM8的时候，使用mybatis PLUS的save方法，他会自动在字段后面加入转义字符\n，导致达梦的jdbc无法解析转系字符\n

### 重现步骤
save方法的sql语句
insert into (username,password,gender,age......) value (?,?,?........)
经过plus组装后的数据是这样的
insert INTO (username,\npassword,\n....) values (?,\n?,\n.....)

### 报错信息
dm.jdbc.driver.DMException:\n语法分析出错

**Comment by miemieYaho** [comment]
你应该找dm

**Comment by xuzining** [comment]
我已经给达蒙数据库反馈了，我想知道，咱的mybatis plus在哪里添加的换行符，哪个类，我明天仔细看看，学习学习，望回复，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miemieYaho"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 晚上7:19
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "小提摩太"<1379540723@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] 关于用达梦数据库无法解析转义字符\n的问题 (#2088)




你应该找dm

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/tree/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/injector/methods
