### ISSUE TITLE
 请教SqlParser的自定义时，如何拿到Mapper对应的Method

### ISSUE THREAD

**Issue by xugege** [baomidou/mybatis-plus#209]
**问题场景：** 
我想做一个类似租户的SqlParser，但是只是针对Mapper中部分方法进行过滤

**我的方案1** 
想通过在Mapper方法上标上一个注解，在类似TenantHandler中的doTableFilter中获取到Mapper目标方法，然后判断是否存在注解达到过滤的效果

**方案1问题** 
但是我发现TenantHandler中的doTableFilter只存在一个tableName参数，无法获取当前sql语句对应Mapper的Method的对象

**我的方案2** 
给PaginationInterceptor设置一个SqlParserFilter，通过doFilter方法中的MetaObject参数获取到对应的Mapper的method对象，达到过滤的效果

**方案2问题** 
通过MetaObject也是获取不到Mapper的method方法对象

**求教**
 是否有一些API可以通过tableName获取到对应的Mapper，或者通过MetaObject获取到对应的Mapper上的Method

代码片段
![image](https://user-images.githubusercontent.com/10491416/34547166-3982d78a-f134-11e7-807e-3212b7d64f54.png)

**Comment by qmdx** [comment]
先这样解决，注解方式后期考虑下！！
`
        tenantSqlParser.setTenantHandler(new TenantHandler() {
            @Override
            public Expression getTenantId() {
                return new LongValue(currentTenantId());
            }

            @Override
            public String getTenantIdColumn() {
                return "tenant_id";
            }

            @Override
            public boolean doTableFilter(String tableName) {
                // 过滤不存在企业 ID 的表
                if ("表名1".equals(tableName)
                        || "表名2".equals(tableName)) {
                    return true;
                }
                return false;
            }
        });`
