### ISSUE TITLE
能否在使用条件构造器的时候，手动选择忽略逻辑删除字段

### ISSUE THREAD

**Issue by RudeCrab** [baomidou/mybatis-plus#2091]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

因为设置了逻辑删除字段嘛，有部分情况下进行一些操作的时候又不想要自带的语句 带上逻辑删除判断，在这种情况下目前就只能手写sql了。能否在条件构造器的时候加一个设置呢，可以手动忽略逻辑删除判断，这样更方便一些

**Comment by miemieYaho** [comment]
不能

**Comment by RudeCrab** [comment]
好的，多谢
