### ISSUE TITLE
strictUpdateFill 设置updateTime 没有更新时间

### ISSUE THREAD

**Issue by Libin6666** [baomidou/mybatis-plus#2096]
### 当前使用版本(必须填写清楚，否则不予处理)
```
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.0</version>
        </dependency>

```

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

设置updateTime为插入和更新都填充，插入时没问题，更新时updateTime字段没有变化

### 重现步骤
entity信息：
![image](https://user-images.githubusercontent.com/38720407/72497423-6ecdf600-3867-11ea-9c4e-86c8b7b5fbdf.png)
![image](https://user-images.githubusercontent.com/38720407/72497437-768d9a80-3867-11ea-93b0-89f732f17c02.png)
![image](https://user-images.githubusercontent.com/38720407/72497441-7ab9b800-3867-11ea-90cf-0923844e3f25.png)
![image](https://user-images.githubusercontent.com/38720407/72497472-91600f00-3867-11ea-9feb-3b74c4cfcb83.png)

### 报错信息

无明显报错信息。debug日志如下：
`DEBUG==>  Preparing: UPDATE t_user SET user_name=?, user_age=?, email=?, manager_id=?, create_time=?, update_time=?, version=? WHERE id=? AND version=? AND deleted=0 
DEBUG==> Parameters: 李斌2(String), 99(Integer), 123@163.com(String), 1234(Long), 2020-01-16T13:29:39(LocalDateTime), **2020-01-16T13:29:39(LocalDateTime),** 5(Integer), 1217680288713396225(Long), 4(Integer)
DEBUG<==    Updates: 1`

**Comment by miemieYaho** [comment]
默认规则有值不进行覆盖,看源码调用

**Comment by SQNDNT** [comment]
> 默认规则有值不进行覆盖,看源码调用

这个默认规则能改吗，好不方便
