### ISSUE TITLE
单表crud不支持带for update的select？

### ISSUE THREAD

**Issue by ganhang** [baomidou/mybatis-plus#2100]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 重现步骤

无

### 报错信息

无

**Comment by qmdx** [comment]
默认不支持 解决方法 1、重写注入器实现你的要的对象注入  2、xml 里面写

**Comment by ganhang** [comment]
感觉这个应该符合常用需求，实现也容易，想问下默认不支持这个是有啥考虑吗？

**Comment by qmdx** [comment]
> 感觉这个应该符合常用需求，实现也容易，想问下默认不支持这个是有啥考虑吗？

不是所有人所有数据库都可以这样，你的个性需求自定义就好了
