### ISSUE TITLE
【建议】支持replace into

### ISSUE THREAD

**Issue by Hfate** [baomidou/mybatis-plus#2101]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

目前应该是只支持 insert  into    语句
期待  replace into 语句

**Comment by miemieYaho** [comment]
选装件pr

**Comment by fanglijun** [comment]
> 选装件pr

啥意思啊
