### ISSUE TITLE
代码生成器无法连接远程数据库 显示本地ip navicat远程连接正常

### ISSUE THREAD

**Issue by ProgrammingDream** [baomidou/mybatis-plus#2103]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-boot-starter 3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

错误信息：显示连接地址为本地ip地址
java.sql.SQLException: Access denied for user 'db_guli'@'124.166.153.12' (using password: YES)

### 重现步骤

![TIM截图20200117144546](https://user-images.githubusercontent.com/32506044/72590187-1fa3c600-3938-11ea-9ecb-a72d2e4ea2b2.png)
![TIM截图20200117144546](https://user-images.githubusercontent.com/32506044/72590208-2e8a7880-3938-11ea-9070-2753d0e26192.png)
![TIM截图20200117144718](https://user-images.githubusercontent.com/32506044/72590258-495ced00-3938-11ea-9bbc-0d61916a7e99.png)

### 报错信息

java.sql.SQLException: Access denied for user 'db_guli'@'124.166.153.12' (using password: YES)

**Comment by nieqiurong** [comment]
属于你数据库远程访问权限分配问题，自行处理。
