### ISSUE TITLE
MyBatis Plus支持空where拦截嘛？

### ISSUE THREAD

**Issue by SoftwareKing** [baomidou/mybatis-plus#2105]
MyBatis Plus支持空where拦截嘛？

**Comment by nieqiurong** [comment]
解析链里面有一个阻断update，delete的。
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/parsers/BlockAttackSqlParser.java
