### ISSUE TITLE
IllegalSQLInterceptor 里 索引检查时候出现大小写不匹配导致检测出错

### ISSUE THREAD

**Issue by windidea** [baomidou/mybatis-plus#2107]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatis-plus-boot-starter.version>3.2.0</mybatis-plus-boot-starter.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
IllegalSQLInterceptor 177行对比数据库字段时候，用了Objects.equals，建议使用StringUtils.equalsIgnoreCase

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/ffd809e9e923e1d9c9ca04ff32ffcc3ce0017820
