### ISSUE TITLE
LambdaQueryWrapper无参构造的实体无法获取到泛型的实体对象的真实类型

### ISSUE THREAD

**Issue by sdsEnjoyLife** [baomidou/mybatis-plus#2109]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在代码层面做敏感词加解密的拦截时，拦截到LambdaQueryWrapper对象但是无法获取到实体的类型，导致这个敏感词加解密的工具jar 有缺陷。

### 重现步骤
LambdaQueryWrapper lambdaQueryWrapper = new LambdaQueryWrapper<User>().eq(User::getPhone, phone);
根据lambdaQueryWrapper 获取不到User的类型。
是否可以源码里支持一下？

### 报错信息
无

**Comment by lll1412** [comment]
这个怎么解决的
