### ISSUE TITLE
整合 spring-cache 的问题

### ISSUE THREAD

**Issue by qiujy** [baomidou/mybatis-plus#211]
怎么在 service 层 添加 spring-cache 呢？

**Comment by huayanYu** [comment]
一般包一次。Baseservice是改不了， 只有注解在自己的service。

**Comment by qmdx** [comment]
重写父类方法，或者自定义方法

**Comment by jinfang134** [comment]
我整合了以后，缓存未生效，而同一个包下的其它服务缓存是生效的，
我使用的版本是
···
 <mybatis-plus-boot-starter.version>2.1.9</mybatis-plus-boot-starter.version>
···

**Comment by qmdx** [comment]
@jinfang134  我们内部使用正常，请仔细排查

**Comment by jinfang134** [comment]
@qmdx 问题已经解决了，是因为循环依赖引起的问题，谢谢您的帮助
