### ISSUE TITLE
@TableField typeHandler的问题

### ISSUE THREAD

**Issue by sdsEnjoyLife** [baomidou/mybatis-plus#2110]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
字段上增加如下注解：
@TableField(typeHandler = AESEncryptHandler.class)
    private String phone;
用LambdaQueryWrapper查询不会进入自定义的AESEncryptHandler里。
用new QueryWrapper<>(query)这种方式可以。
是否LambdaQueryWrapper现有实现的方式就支持不了？

### 重现步骤
必现哦

### 报错信息
无

**Comment by miemieYaho** [comment]
只有wrapper内部entity支持

**Comment by miracle-bean** [comment]
> 只有wrapper内部entity支持
可以具体说明一下吗

**Comment by miemieYaho** [comment]
debug看`SelectList` 这个类

**Comment by miracle-bean** [comment]
多谢🙏

**Comment by HaowenChen27** [comment]
LambdaQueryWrapper怎么拦截器怎么获取入参呢
