### ISSUE TITLE
查询SQL出现实体类不存在的字段

### ISSUE THREAD

**Issue by hjljy** [baomidou/mybatis-plus#2114]
### 当前使用版本(必须填写清楚，否则不予处理)
使用的是3.2.0版本
    
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.2.0</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在forEach 方法当中调用list(queryWrapper)方法时
### 重现步骤
1 先查询出所有数据去重后的数据
2 然后遍历所有数据，满足某个条件的话，查询满足条件的所有数据。

PS：操作的是同一张表。同一个实体

### 报错信息
错误发出的sql:   
Preparing:
 SELECT id,category2,category3,category4,period,category5,subject,category1,grade,version,parent_id FROM jyo_category WHERE (grade = ? AND subject = ? AND version = ?) 

Unknown column 'category2' in 'field list'

**Comment by miemieYaho** [comment]
自行排查
