### ISSUE TITLE
配置扫描通用枚举 + fastjson 小问题

### ISSUE THREAD

**Issue by zhfish** [baomidou/mybatis-plus#213]
```
public enum Status implements IEnum{
    DISABLE(0, "未启用"),
    ENABLE(1, "启用");

    private int value;
    private String desc;

    Status(final int value, final String desc) {
        this.value = value;
        this.desc = desc;
    }

    @Override
    public Serializable getValue() {
        return this.value;
    }

    public String getDesc(){
        return this.desc;
    }

    @Override
    public String toString(){
        return String.valueOf(this.value);
    }
}
```
按照文档配置,写入没问题了
传入ENABLE和DISABLE都能写入1和0

但是取出的时候却是空值
`expressService.selectList(null);`
status这项是null

打印的log
```
       List<Express> expresses = expressService.selectList(null);
       Status status = expresses.get(0).getStatus();
```
ststus 是 null

**Comment by qmdx** [comment]
参考例子 https://git.oschina.net/baomidou/mybatisplus-spring-boot

**Comment by zhfish** [comment]
@qmdx 
首先例子是jackson的..
我和例子差别是在getDesc上加 `@JsonValue`
结果是一样的

能否给一个fastjson的例子?

**Comment by zhfish** [comment]
@qmdx 
[按照文档](http://baomidou.oschina.io/mybatis-plus-doc/#/enum)
fastjson不加`@JsonValue`
第一步 如上我发的enum
第二步 也没问题
第三步 fastjson我用的全局`SerializerFeature.WriteEnumUsingToString`

结果是form表单提交字符串DISABLE,
controller拿到model是正确的enum
提交也是正确的int值

只是查询时,值出不来

**Comment by qmdx** [comment]
@zhfish  入群说话，这里太慢了
