### ISSUE TITLE
MetaObjectHandler字段填充器无效

### ISSUE THREAD

**Issue by shanzhaozhen** [baomidou/mybatis-plus#2135]
### 重现步骤
 `
（继承MetaObjectHandler）
@Override
    public void insertFill(MetaObject metaObject) {
        Long userId = UserDetailsUtils.getUserId();
        this.strictInsertFill(metaObject, "createdDate", BaseEntity.class, new Date());
        this.strictInsertFill(metaObject, "createBy", BaseEntity.class, userId);
        this.strictInsertFill(metaObject, "lastModifiedDate", BaseEntity.class, new Date());
        this.strictInsertFill(metaObject, "lastModifiedBy", BaseEntity.class, userId);
    }

    @Override
    public void updateFill(MetaObject metaObject) {
        Long userId = UserDetailsUtils.getUserId();
        this.strictUpdateFill(metaObject, "lastModifiedDate", BaseEntity.class, new Date());
        this.strictUpdateFill(metaObject, "lastModifiedBy", BaseEntity.class, userId);
    }
`
`
（公共实体）
@Getter
@Setter
@ApiModel(description = "实体基础信息")
public class BaseEntity implements Serializable {

    private static final long serialVersionUID = -4890503939284694535L;

    @TableField(fill = FieldFill.INSERT)
    @ApiModelProperty(value = "创建人")
    private Long createBy;

    @JsonFormat(pattern="yyyy-MM-dd hh:mm:ss",timezone = "GMT+8")
    @TableField(fill = FieldFill.INSERT)
    @ApiModelProperty(value = "创建时间")
    private Date createdDate;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    @ApiModelProperty(value = "修改人")
    private Long lastModifiedBy;

    @JsonFormat(pattern="yyyy-MM-dd hh:mm:ss",timezone = "GMT+8")
    @TableField(fill = FieldFill.INSERT_UPDATE)
    @ApiModelProperty(value = "修改时间")
    private Date lastModifiedDate;

}

`

### 报错信息
没有进行自动填充字段，该功能更新有点太频繁了，三次看文档都用不同的方法对字段自动填充。反而最老的方法好用，新方法不好使了

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/guide/auto-fill-metainfo.html

**Comment by shanzhaozhen** [comment]
> https://mp.baomidou.com/guide/auto-fill-metainfo.html

有看文档，建议还是写个demo测试一下吧，我这边试过不能正常执行

**Comment by lewisjing** [comment]
我也遇到这个问题了，请问解决了嘛？

**Comment by wcpaxx** [comment]
me too

**Comment by wcpaxx** [comment]
我也有这个问题
3.3.1.tmp

**Comment by xgj1988** [comment]
@shanzhaozhen  问题解决了吗？

**Comment by xgj1988** [comment]
一直不敢升级到3.2.0。就是因为这个问题
