### ISSUE TITLE
生成的实体导入Serializable重复

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#214]
package cn.wj.order.entity;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotations.TableField;
import java.util.Date;
import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;
import java.io.Serializable;

**Comment by qmdx** [comment]
多谢反馈已解决
