### ISSUE TITLE
实体类日期类型映射报错

### ISSUE THREAD

**Issue by g1335333249** [baomidou/mybatis-plus#2145]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用page分页查询，只有一个过滤条件
IPage<User> page = iUserService.page(new Page<>(1, 500),
					Wrappers.<User> lambdaQuery().isNull(User::getUserName))
实体类日期类型为java.util.Date
使用list或page其他条件未发现错误，猜测是isNull导致的
### 报错信息
Error attempting to get column 'create_time' from result set.  Cause:.sql.SQLException: YEAR
; YEAR; nested exception is java.sql.SQLException: YEAR

**Comment by miemieYaho** [comment]
类型映射是mybatis的事
