### ISSUE TITLE
是否有计划根据idea的database表设计一键生成代码？参考easyCode插件

### ISSUE THREAD

**Issue by joey-happy** [baomidou/mybatis-plus#2149]
是否有计划根据idea的database表设计一键生成代码？参考easyCode插件

**Comment by h2so** [comment]
此类插件很多吧？mp没必要在做一个了

**Comment by lunxian8** [comment]
直接用easycode不就完了，此类东西异曲同工有一个东西用用的了

**Comment by nieqiurong** [comment]
没有人员,没有精力.

**Comment by cnscoo** [comment]
@joey-happy 春节期间闲起来做了一个类似的插件 [Batiso](https://gitee.com/cnscoo/batiso/tree/idea-plugin)，基本功能已经可以用了，不过还有些问题和数据库适配需要处理。
