### ISSUE TITLE
是否支持根据多字段排序，如：A字段升序，B字段降序，C字段升序

### ISSUE THREAD

**Issue by Aouty** [baomidou/mybatis-plus#2153]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus -> 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
查询数据集合后排序时，未找到满足以上条件的排序方式

### 重现步骤
无

### 报错信息
无

**Comment by miemieYaho** [comment]
去看文档
