### ISSUE TITLE
com.baomidou.mybatisplus.extension.service.IService#listObjs的用法问题

### ISSUE THREAD

**Issue by q20096** [baomidou/mybatis-plus#2154]
当前版本：3.5.3（估计全版本都是这样）

使用方式
![image](https://user-images.githubusercontent.com/29053247/75036639-4af87280-54ed-11ea-8887-8763040ee043.png)
如上图，个人理解listObjs是查询User实体后，通过mapper，将实体转化为其他对象。

期望：
“user”为User的实体对象

实际：
查询出来的却是一个字段，上图中的“user”的类型实际上是Integer，其表示user的Id（经过测试，user为查询的第一个字段，比如 select name，id from t_user，则user就等于name的值）

原因
![image](https://user-images.githubusercontent.com/29053247/75036415-c1e13b80-54ec-11ea-9a81-fbe91ac0376a.png)
对生成selectObjs方法的MappedStatement时，这里传入了Object.class

我认为这里应该传入"tableInfo.getEntityType()", 
改造后如下：
![image](https://user-images.githubusercontent.com/29053247/75036716-809d5b80-54ed-11ea-8063-26492e982a37.png)

改造后最终效果：
![image](https://user-images.githubusercontent.com/29053247/75036769-93179500-54ed-11ea-855a-2a313d00d764.png)

**Comment by miemieYaho** [comment]
想放回entity用另一个方法

**Comment by yiyuan0109** [comment]
那个方法呢？

**Comment by anic** [comment]
> 那个方法呢？

selectList
