### ISSUE TITLE
能否添加返回值为主键集合的api

### ISSUE THREAD

**Issue by suzhengit** [baomidou/mybatis-plus#2155]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我们经常需要通过条件查询出主键或者主键列表进行后续操作，目前Mybatis-Plus查询结果都是为对象或者对象列表，还需要通过流map出主键集合，比较麻烦。能否提供listIds和oneId这样的api，方便查询。

### 重现步骤

无

### 报错信息

无

**Comment by miemieYaho** [comment]
用 selectObjs , wrapper设置只select id
