### ISSUE TITLE
代码生成器是否能够支持添加其他模板

### ISSUE THREAD

**Issue by f4112cd** [baomidou/mybatis-plus#2157]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.3.1

### 该问题是怎么引起的？
目前代码生成器好像就只可以添加entity、service、serviceImpl、mapper、xml、controller这几个部分的模板，也就是说只能生成这几部分的代码。如果我想添加其他模板生成其他部分的代码，好像不支持。

例如：
在entity包下面有po和vo两个包，这两个包下面存放着实体类，其中po下的类对应着数据库的表，而vo下的类继承自po类用于添加其他额外的属性。在这种情况下我只能设置po的模板从而生成po的代码，但是没有地方设置vo的模板来生成vo，当然其实不用vo也可以因为也提供了@TableField(exist = false)。

不过这里也是举一个例子，如果我要添加一些其他的模板来生成其他的文件目前好像就只能添加上面提到的那几个。所以能不能提供一种方案来让我们自己扩展，还是说本来就提供了只是我没有找到？

**Comment by 15050050972** [comment]
官网里有
https://mybatis.plus/guide/generator.html#%E4%BB%A3%E7%A0%81%E7%94%9F%E6%88%90%E5%99%A8

看下代码
```
// 自定义输出配置
        List<FileOutConfig> focList = new ArrayList<>();
        // 自定义配置会被优先输出
        focList.add(new FileOutConfig(templatePath) {
            @Override
            public String outputFile(TableInfo tableInfo) {
                // 自定义输出文件名 ， 如果你 Entity 设置了前后缀、此处注意 xml 的名称会跟着发生变化！！
                return projectPath + "/src/main/resources/mapper/" + pc.getModuleName()
                        + "/" + tableInfo.getEntityName() + "Mapper" + StringPool.DOT_XML;
            }
        });
```

**Comment by qmdx** [comment]
up

**Comment by f4112cd** [comment]
thank
