### ISSUE TITLE
使用 Enum 插件后， setValue 很不方便， 望有方便的方法改进

### ISSUE THREAD

**Issue by yuchenzhen** [baomidou/mybatis-plus#2165]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter  3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

```java
@Getter
public enum GradeEnum {

    PRIMARY(1, "小学"),
    SECONDORY(2, "中学"),
    HIGH(3, "高中");

    GradeEnum(int code, String descp) {
        this.code = code;
        this.descp = descp;
    }

    @EnumValue
    private final int code;
    private final String descp;

}
```

```java
public class User {
    
    private String name;
    /**
     * 使用枚举类型来限制输入值
     */
    private GenderEnum gender;
    
}
```

使用以上代码后， setGender方法不能直接 输入参数 int 类型，
如果重载 setGender 方法， 使用 int 做入参， 则要通过  GradeEnum(int , string) 的形式获取 GradeEnum 类型， 通常 getGender  就只能拿到 int 类型参数， 再去获取 string 的类型的参数比较不方便，很累赘  

希望有方便的 setGender(int gender) 的方法

**Comment by miemieYaho** [comment]
自行处理
