### ISSUE TITLE
Oracle 11g分页问题

### ISSUE THREAD

**Issue by ifaron** [baomidou/mybatis-plus#2169]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatis-plus-boot-starter.version>3.1.0</mybatis-plus-boot-starter.version>
<mybatis-plus-generator.version>3.1.0</mybatis-plus-generator.version>
<mybatis-plus-extension.version>3.1.0</mybatis-plus-extension.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

`QueryWrapper<SysUser> wrapper = new QueryWrapper();
wrapper.eq("SEX", 1);
Page<SysUser> page = new Page<>(1,2);
IPage<SysUser> mapIPage = userDao.selectPage(page, wrapper);`

### 报错信息

22:15:21.636 [http-nio-8080-exec-2] DEBUG c.l.m.s.S.selectPage - [debug,159] - ==>  Preparing: SELECT * FROM ( SELECT TMP.*, ROWNUM ROW_ID FROM ( SELECT * FROM ( SELECT TMP_PAGE.*, ROWNUM ROW_ID FROM ( SELECT USER_ID,NAME,USER_TYPE,EMAIL,PHONENUMBER,SEX,AVATAR,PASSWORD,SALT,STATUS,DEL_FLAG,LOGIN_IP,LOGIN_DATE,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME,REMARK,USER_NAME,ORGANIZATION_CODE,ORGANIZATION_NAME,CAMPUS_CODE,CAMPUS_NAME,TEL,ID_NUMBER,SCHEDULING,EXTERNAL_USER_ID,INPUT_CODE1,INPUT_CODE2,INPUT_CODE3,BIRTHDAY,SIGNATURE,ADMIN_FLAG FROM SYS_USER WHERE DEL_FLAG=0 AND SEX = ? ) TMP_PAGE WHERE ROWNUM <= ? ) WHERE ROW_ID > ? ) TMP WHERE ROWNUM <=?) WHERE ROW_ID > ? 
22:15:21.640 [http-nio-8080-exec-2] DEBUG c.l.m.s.S.selectPage - [debug,159] - ==> Parameters: 1(Integer), 10(Integer), 0(Integer), 2(Long), 0(Long)
22:15:33.621 [http-nio-8080-exec-2] ERROR c.l.f.w.e.GlobalExceptionHandler - [handleException,77] -

**Comment by ifaron** [comment]
是我自己造成的。
在使用mybatis plus分页查询前，误执行了PageHelper.startPage导致的

**Comment by ZhaoyuanDu** [comment]
这个问题怎么决绝呢？我同事的代码也是用这个进行分页的，但是却没有报这个错误。我按照这样写就出现这个错误，看了下打印的sql，发现第一次打印的正确，第二次出现外层添加select * from (select TMP.* ROWNUM ROW_ID FROM (select * from (select TMP.* ROWNUM ROW_ID FROM (内查询)))这样的sql，请问如果不升级包如何解决？

**Comment by ZhaoyuanDu** [comment]
当我不配置PaginationInterceptor分页插件bean的注入时，该功能能正常使用，我同事的项目也是这样写的，不过这样有没有影响呢？

**Comment by liukecheng46** [comment]
> 是我自己造成的。
> 在使用mybatis plus分页查询前，误执行了PageHelper.startPage导致的

我没有使用pagehelper，只使用了paginationinterceptor，dbtype使用oracle时也报这个错。dbtype使用oracle_12c时没有这个错，但是会有其他问题。
