### ISSUE TITLE
建议使用编译插件进行代码生成

### ISSUE THREAD

**Issue by tntsl** [baomidou/mybatis-plus#2171]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
编译插件进行代码生成

### 重现步骤
无

### 报错信息
使用代码方式生成代码，不太合适，尤其是在同一个项目中进行新的代码生成用于覆盖旧的的时候，覆盖不掉，手动删除后编译报错，导致生成代码用的工具也没法用。应该能跳过代码编译校验，最好是使用编译插件，在编译器就生成代码。所以，建议完善一下代码生成器的插件，用于代码生成

**Comment by nieqiurong** [comment]
要不来波PR看看.

**Comment by qmdx** [comment]
欢迎 pr
