### ISSUE TITLE
getone查询因sql字段和model字段位置不一致导致报错

### ISSUE THREAD

**Issue by zdpbj2014** [baomidou/mybatis-plus#2177]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.2.0</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

继承的ServiceImpl类中直接
QueryWrapper<ABC> queryWrapper = new QueryWrapper<>();
queryWrapper.eq("s_id", storeId);
return getOne(queryWrapper);查询，

ABC类的结构
@Data
@AllArgsConstructor
@TableName("abc")
public class ABC implements Serializable {
	@TableId(value = "id", type = IdType.AUTO)
	private Long id;
	@TableField(value = "s_id", jdbcType = JdbcType.VARCHAR)
	private String sId;
	@TableField(value = "s_name", jdbcType = JdbcType.VARCHAR)
	private String sName;
	@TableField(value = "f_condition", jdbcType = JdbcType.VARCHAR)
	private String fCondition;
	@TableField(value = "t_id", jdbcType = JdbcType.BIGINT)
	private Long tId;
	@TableField(value = "update_time", jdbcType = JdbcType.DATE)
	private Date updateTime;
}

查询语句是
SELECT id,t_id,f_condition,update_time,s_name,_id FROM ABC WHERE (s_id = 'A007') 

数据库结构
CREATE TABLE `abc` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `s_id` varchar(50) DEFAULT NULL ,
  `s_name` varchar(200) DEFAULT NULL ,
  `f_condition` varchar(500) DEFAULT NULL ,
  `t_id` bigint(20) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL ,
  PRIMARY KEY (`id`),
)

### 重现步骤
getone查询必现,其他查询没试，保存是没问题的

### 报错信息
Caused by: java.sql.SQLDataException: Cannot convert string 'AAA' to java.sql.Timestamp value

**Comment by miemieYaho** [comment]
升级或者给无参构造

**Comment by zdpbj2014** [comment]
> 升级或者给无参构造

确实是少了一个无参构造的注解。已解决
