### ISSUE TITLE
分页插件获取数据库类型的问题，

### ISSUE THREAD

**Issue by springpro** [baomidou/mybatis-plus#2178]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

com.baomidou.mybatisplus.extension.toolkit.JdbcUtils#getDbType
的42行使用jdbcUrl.contains(":mysql:")判断数据库类型，如果数据库连接字符串里使用大写字符就会出错。不知道这算不算bug，如果开发者认为这不是问题的话，请在文档里说明一下，让使用者强制用小写字母。也请在com.baomidou.mybatisplus.extension.plugins.pagination.dialects.UnknownDialect的抛异常【throw new MybatisPlusException(" not support.");】时候，把“UnknownDialect”写到消息字符串，方便开发者知道错误原因。

### 重现步骤
jdbc:MYSQL://localhost:3306

### 报错信息
Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException:  not support.

**Comment by nieqiurong** [comment]
用3.3.2.1-SNAPSHOT试试，使用方式参考https://mp.baomidou.com/guide/install.html#snapshot
