### ISSUE TITLE
代码生成器设置实体名时，controller的path跟着变化

### ISSUE THREAD

**Issue by jiafuzhang** [baomidou/mybatis-plus#2182]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
设置自定义实体名
GlobalConfig的setEntityName方法

### 重现步骤
// 代码生成器
AutoGenerator mpg = new AutoGenerator();
// 全局配置
GlobalConfig gc = new GlobalConfig();
**gc.setEntityName("%sEntity");**//Entity命名方式，实体名AcInfoEntity，开发人员看起来直观
//因为设置了实体名，同时导致controller中的路径也跟着变化了，生成的controller如下：
**@RequestMapping("/business/acInfoEntity")**
public class AcInfoController extends BaseController {

}

### 报错信息
无报错信息，建议可以配置或者设置controller的path。成如下效果
**@RequestMapping("/business/acInfo")**
public class AcInfoController extends BaseController {

}
希望用户看到的路径是/business/acInfo，而不是/business/acInfoEntity
以上，祝愿mybatis plus越来越好！

**Comment by nieqiurong** [comment]
这个要想下实现方式,不过目前还是自定义一下模板把,可以考虑加下原名称放入作用域范围.

**Comment by qmdx** [comment]
up
