### ISSUE TITLE
数据库表中存在名为id的字段时，代码生成器生成实体时缺失字段

### ISSUE THREAD

**Issue by dogelee0701** [baomidou/mybatis-plus#2185]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用代码生成器生成实体时，若字段有名为id的，会缺少此字段。经测试发现是因为这个字段没有被放进TableInfo的fields中，放到了commonfields中。版本3.3.1。

**Comment by qmdx** [comment]
你的代码生成器是否配置了公共字段

**Comment by dogelee0701** [comment]
> 你的代码生成器是否配置了公共字段

刚刚整理配置文件的时候发现了，针丢人
