### ISSUE TITLE
GlobalConfig

### ISSUE THREAD

**Issue by lovlyhao** [baomidou/mybatis-plus#2188]
### 当前使用版本(必须填写清楚，否则不予处理)

在springboot中mybatisplus.3.1.0版本中怎么获取GlobalConfig. @Autowired注入无效，我需要使用logic-delete-value配置的值做判断使用

**Comment by miemieYaho** [comment]
3.1.2 及之后试试注入 MybatisPlusPropertiesCustomizer 从里面取GlobalConfig set到你的类里面去
