### ISSUE TITLE
查询入参为Dto，返回值为entity场景

### ISSUE THREAD

**Issue by summer9989** [baomidou/mybatis-plus#2189]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

查询场景是DTO作为参数（UserDto，里面有额外field，比如birthdayStart,birthdayEnd这样的范围查询），返回entity（User），这样的查询如何用selectList支持

只能这样吗？
UserDto userDto = new UserDto();
userDto.setAgeStart(24);
userDto.setAgeEnd(34);
userDto.setName("Tom");
User user = new User();
BeanUtils.copyProperties(userDto, user);
List userList = userMapper.selectList(Wrappers.lambdaQuery(user).gt(User::getAge, userDto.getAgeStart()).lt(User::getAge, userDto.getAgeEnd()));

请作者给个思路

**Comment by miemieYaho** [comment]
试试Wrappers.lambdaQuery(userDto),不行就没办法

**Comment by summer9989** [comment]
当然是不行啊，直接报错的，原因是你们订的selectList泛型，入参和返回值都是T一样的!
另外你是作者吗？怎么一言不合就关issue @ @akuma @qmdx @nieqiurong
