### ISSUE TITLE
PackageConfig 不指定moduleName的时候，生成的目录里面有null

### ISSUE THREAD

**Issue by clevertension** [baomidou/mybatis-plus#2192]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator-3.3.1.jar

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

com.baomidou.mybatisplus.generator.config.PackageConfig, 不指定moduleName

### 重现步骤
mybatis-plus-generator生成代码

### 报错信息
没有报错

**Comment by clevertension** [comment]
![image](https://user-images.githubusercontent.com/346723/75851418-93d0f500-5e24-11ea-81e7-9054dbdaad9f.png)

**Comment by nieqiurong** [comment]
附加一下测试代码.

**Comment by clevertension** [comment]
![image](https://user-images.githubusercontent.com/346723/76477312-e66f6a00-643f-11ea-8ceb-1a8e8dab44cf.png)

这个是generator的代码修改，build.gradle 针对该模块的test已经exclude掉了

**Comment by clevertension** [comment]
@nieqiurong 不过这个模块的test，我可以把我的改动加上

**Comment by nieqiurong** [comment]
问题出现在明知道moduleName为null值还拼接输出路径导致生成null目录.
```java
List<FileOutConfig> focList = new ArrayList<>();
focList.add(new FileOutConfig(templatePath) {
    @Override
    public String outputFile(TableInfo tableInfo) {
        // 自定义输出文件名 ， 如果你 Entity 设置了前后缀、此处注意 xml 的名称会跟着发生变化！！
        return sqliteGenertorPath + "/src/main/resources/mapper/" + pc.getModuleName()
            + "/" + tableInfo.getEntityName() + "Mapper" + StringPool.DOT_XML;
    }
});
```
