### ISSUE TITLE
分页时，foreach标签的collection不支持单个对象中含有集合的操作

### ISSUE THREAD

**Issue by Liesport758** [baomidou/mybatis-plus#2205]
版本：3.3.0

### 重现步骤
  <foreach collection='roleIds' item='item' index='index' SEPARATOR=',' OPEN='(' CLOSE=')'>" +
                    "        #{item}  " +
                    "      </foreach>" +
                    "</where>" +
            )
    IPage<RolePermitVO> selectRolePermitList(Page<?> page,@Param("ew") RolePermitQuery query);
![image](https://user-images.githubusercontent.com/10843358/76134141-340e6000-6057-11ea-9657-f475abd4777c.png)

其中：
@Data
public class RolePermitQuery extends Page {
    List<Long> roleIds;
}

### 报错信息
nested exception is org.apache.ibatis.binding.BindingException: Parameter 'roleIds' not found. Available parameters are [ew, arg0, param1, param2]
。
foreach标签的collection不支持单个对象中含有集合的操作

**Comment by miemieYaho** [comment]
ew.

**Comment by Liesport758** [comment]
> ew.

去掉@param也一样出错的

**Comment by Liesport758** [comment]
问题怎么直接关了？

> ew.

问题怎么直接关了？

**Comment by CroceIt** [comment]
Ta估计是说要将#{item}这个改为#{ew.item}

**Comment by Liesport758** [comment]
这样更不行的。我看mybaits-plus有改mybaits源码这块，


| |
李仕波
kihcrjwq@163.com
|
签名由网易邮箱大师定制
在2020年3月9日 11:33，CroceIt<notifications@github.com> 写道：

Ta估计是说要将#{item}这个改为#{ew.item}
