### ISSUE TITLE
JsqlParserCountOptimize中order by优化疑问

### ISSUE THREAD

**Issue by summer9989** [baomidou/mybatis-plus#2207]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

请问如下语句中，为什么出现group by就不去除orderBy？
```
// 添加包含groupBy 不去除orderBy
            if (null == groupBy && CollectionUtils.isNotEmpty(orderBy)) {
                plainSelect.setOrderByElements(null);
                sqlInfo.setOrderBy(false);
            }
```

能否举例什么情况下去除orderBy会出错？比如下列的语句优化好像没啥问题？
`select count(1) from (select name,count(1) from user GROUP BY name order by age desc, update_time desc)a` 优化后为
`select count(1) from (select name,count(1) from user GROUP BY name )a`

**Comment by nieqiurong** [comment]
看到你在码云上提过了. https://gitee.com/baomidou/mybatis-plus/issues/I1B7RJ

**Comment by summer9989** [comment]
@nieqiurong  目前码云上还没答案哦，麻烦安排看下
