### ISSUE TITLE
insert生成sql后列缺失

### ISSUE THREAD

**Issue by xingya771** [baomidou/mybatis-plus#221]
# Test

    `    <dependency>
    			<groupId>org.mybatis.spring.boot</groupId>  
    			<artifactId>mybatis-spring-boot-starter</artifactId>  
    			<version>1.3.1</version>  
    		</dependency>  
            <dependency>  
                <groupId>com.baomidou</groupId>  
                <artifactId>mybatisplus-spring-boot-starter</artifactId>  
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus</artifactId>
                <version>2.1.8</version>
            </dependency>`    
            
        
    `CREATE TABLE time_info
        (
          id         INT AUTO_INCREMENT
            PRIMARY KEY,
          user_id    INT NOT NULL,
          time_used  INT NULL,
          time_total INT NULL
        )
          ENGINE = InnoDB
          CHARSET = utf8;`

    `@Data
    @TableName("time_info")
    @AllArgsConstructor
    @NoArgsConstructor
    public class TimeInfo extends BaseEntity<TimeInfo> {
    	private static final long serialVersionUID = -8699150088739427859L;
    	@TableId("user_id")
    	private Integer userId;  
    	@TableField("time_used")
    	private Integer timeUsed;   
    	@TableField("time_total")
    	private Integer timeTotal;
    }`
    `public class BaseEntity<T extends Model> extends Model<T> {
    
        /**
         * 主键ID
         */
        @TableId
        public Integer id;
    
        public Integer getId() {
            return this.id;
        }
    
        public void setId(Integer id) {
            this.id = id;
        }
    
        @Override
        protected Serializable pkVal() {
            return this.id;
        }
    }
`

    `@Test
    	public void timeInfoInsert() {
    		TimeInfo timeinfo=new TimeInfo();
    		timeinfo.setUserId(1);
    		timeinfo.setTimeTotal(1);
    		timeinfo.insert();
    	}`
运行后生成的SQL为` INSERT INTO time_info ( time_total ) VALUES ( ? )  `
因user_id字段为非空字段，导致插入失败。 希望得到您的帮助，谢谢！

**Comment by xingya771** [comment]
![1](https://user-images.githubusercontent.com/17630155/35011682-fe8aa942-fb41-11e7-8b28-a20cb0cccd67.png)
![2](https://user-images.githubusercontent.com/17630155/35011683-fec217b0-fb41-11e7-87a9-eeade8e42ae6.png)

**Comment by qmdx** [comment]
1、 你的命名策略可以无注解化，详情看下配置开启全局下划线命名

2、请注意你的 ID 策略是不是开启自增了这样不会有 id 字段出现，这时候你的数据库要开启自增

以上 2 点还是未解决 入Q群  , 群号:576493122
