### ISSUE TITLE
数据库字段类型判断过于简单，会造成类型错误的bug

### ISSUE THREAD

**Issue by wjse** [baomidou/mybatis-plus#2213]
### 重现步骤
数据库字段为枚举类型，枚举类型中包含bit字符，比如enum('ETH','BITCOIN')
代码上简单粗暴的用contains验证字段类型，此时该类型就会被判断为Boolean类型

**Comment by qmdx** [comment]
异常信息？ 什么功能？ 怎么引起？ 写清楚

**Comment by gwsh** [comment]
没法重现 请附上环境和重现代码

**Comment by qmdx** [comment]
请给出 demo
