### ISSUE TITLE
和数据库查询不一致

### ISSUE THREAD

**Issue by lishangpeng** [baomidou/mybatis-plus#2216]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-boot-starter
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

分页查询

`    @Select({
            "<script>" +
                "select  ",
                "mall.default_pic as productImg ,mall.product_name as productName,mall.size_show as showSize,mall.advise_price as oriPrice, " +
                        "mall.size_list as sizeList,weidian.weidian_price as price,weidian.profit as profit,weidian.prod_code as prodCode ",
                "from t_weidian_prod weidian" ,
                "left join mall_product_list mall ",
                "on weidian.prod_code = mall.product_code ",
                "where weidian_id = #{weidianId} and weidian.on_shelves = 1 and mall.delete_flag = 0 and mall.on_shelves = 1  ",
                "<choose>",
                    "<when test='orderByType != null and orderByType == 1'> and weidian.recommend =1  order by weidian.recommend_date desc  </when>"+
                    "<otherwise> and weidian.recommend = 0 order by weidian.recommend_date desc  </otherwise>"+
                "</choose>"+
            "</script>"
    })
    IPage<AppProductModel> pageIndexProd(IPage<?> page,
                                         @Param(value = "weidianId") Integer weidianId,
                                         @Param(value = "orderByType") Integer orderByType);`

Preparing:select mall.default_pic as productImg ,mall.product_name as productName,mall.size_show as showSize,mall.advise_price as oriPrice, mall.size_list as sizeList,weidian.weidian_price as price,weidian.profit as profit,weidian.prod_code as prodCode from t_weidian_prod weidian left join mall_product_list mall on weidian.prod_code = mall.product_code where weidian_id = ? and weidian.on_shelves = 1 and mall.delete_flag = 0 and mall.on_shelves = 1 and weidian.recommend = 0 order by weidian.recommend_date desc LIMIT ?,? 

我按照上面的sql语句在数据库中查询 结果数据和Columns返回的参数不一致

### 报错信息

无报错信息

**Comment by litice-wen** [comment]
大佬，你这个后面是怎么解决的
