### ISSUE TITLE
分页查询对溢出总页数的优化建议

### ISSUE THREAD

**Issue by lizhian** [baomidou/mybatis-plus#2217]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus 3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
现实中遇到的业务需求
有时候希望溢出总页数后显示第一页
有时候想显示最后一页
(就是这么操蛋)

### 我的初步解决方案
先创建创建处理类型枚举类
```java
@AllArgsConstructor
public enum OverflowType {
    NONE("不做任何处理"),
    FIRST("查询第一页"),
    LAST("查询最后一页"),
    EXCEPTION("抛出异常");
    private String desc;
}
```
然后把对应的处理类型把`OverflowType`存入到`ThreadLocal`
最后我重写`PaginationInterceptor.handlerOverflow(IPage<?> page)`方法,从`ThreadLocal`取出`OverflowType`值,再做对应处理

### 存在的问题
因为是使用了`ThreadLocal`做值传递,不能保证百分百的可用性和安全性;

### 优化建议,实现起来十分简单有效
1. 将溢出处理方式改成`pega`的属性传入
2. `PaginationInterceptor`中的`overflow`变成`defaultOverflowType`,即全局默认处理方式
3. 修改`PaginationInterceptor`的处理逻辑

相关代码
`page`
```java
public class Page<T> implements IPage<T> {
    ......
    //溢出处理方式
    private OverflowType overflowType;
    ......
```
`PaginationInterceptor`
```java
            page.setTotal(total);
            if (page.getCurrent() > page.getPages()) {
                OverflowType overflowType = Optional.ofNullable(page.getOverflowType)
                               .orElse(this.defaultOverflowType);
                  switch (overflowType ) {
			case ...:
				....;
                                break;
			case ...:
				....;
                                break;
                        case ...:
				....;
                                break;
                         case ...:
				....;
                                break;
			default:
				....;
			}
            }
```

**Comment by nieqiurong** [comment]
自行实现IPage接口和覆写分页插件方法实现.
