### ISSUE TITLE
spring 设置 GlobalConfiguration 的dbColumnUnderline 字段不生效

### ISSUE THREAD

**Issue by xaiowei** [baomidou/mybatis-plus#2220]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus</artifactId>
			<version>2.3</version>
</dependency>

### 重现步骤
数据库字段本身就是驼峰,到java实体仍然是驼峰 ,查询会转换成下划线

### 报错信息
字段映射问题

**Comment by yuxiaobin** [comment]
经测试，2.x最新的 v_2.3.3没有这个问题

**Comment by yuxiaobin** [comment]
<property name="dbColumnUnderline" value="false"/>
