### ISSUE TITLE
可以在非spring环境中使用吗？比如guice

### ISSUE THREAD

**Issue by Fengxq2014** [baomidou/mybatis-plus#2222]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp

**Comment by miemieYaho** [comment]
可以

**Comment by Fengxq2014** [comment]
@miemieYaho 有例子可以参考吗

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-no-spring
非框架下使用参考
