### ISSUE TITLE
怎么给 Wrapper 定义别名, 替换掉默认的 "ew"

### ISSUE THREAD

**Issue by Nisus-Liu** [baomidou/mybatis-plus#2223]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？
`com.baomidou.mybatisplus.core.conditions.Wrapper#getCustomSqlSegment`注释第4条说: "4.ew是wrapper定义别名,可自行替换" . 可是不知道哪里有修改的入口?

有时候sql中多出需要用到独立的sql片段, 比如一个 where 条件片段, 一个 having 片段, 这时候, 设置别名, 替换掉默认的 "ew" 就非常有用了. 定义一个 "whereEw" 和 一个 "havingEw" , 分别生成各自的sql片段.

**Comment by miemieYaho** [comment]
不支持

**Comment by Nisus-Liu** [comment]
哦, 好的吧, 可惜了, 要是能支持就更加灵活了.
我现在只能写个 MyQueryWrapper 继承 QueryWrapper 后, 重写 getCustomSqlSegment()
