### ISSUE TITLE
对于FastJson 枚举类型转换

### ISSUE THREAD

**Issue by lemonade-water** [baomidou/mybatis-plus#2224]
### 当前使用版本(必须填写清楚，否则不予处理)
<version>3.3.1.tmp</version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
FastJSON 枚举类型转换时候  转换字典值的时候，是枚举的名称，SpringBoot内置的FastJSON转换器在前台展示也是不行的，必须要把对象通过JSON.toJSON(JSON.toJSONString(object))转一下才行。

### 重现步骤
通过JSON.toJSON(JSON.toJSONString(object))转一下，

### 报错信息
不报错

**Comment by miemieYaho** [comment]
json化去找百度
