### ISSUE TITLE
使用ConfigurationCustomizer配置GlobalConfig的相关属性不起作用

### ISSUE THREAD

**Issue by jameslu77** [baomidou/mybatis-plus#2225]
原因：
通过ConfigurationCustomizer设置的GlobalConfig对象，与MybatisPlus配置文件使用的GlobalConfig不是同一个

### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
正常初始化

### 重现步骤
任何情况下都能重现

### 报错信息
没有报错

**Comment by miemieYaho** [comment]
用 MybatisPlusPropertiesCustomizer
