### ISSUE TITLE
使用求助，baseMapper怎么最终获取到表名

### ISSUE THREAD

**Issue by lehug** [baomidou/mybatis-plus#2226]
我期望在service层，对原始的updateById，save等方法进行封装，用于记录操作日志。日志中有一个字段是表名，想着从baseMapper等获取到当前entity的表名，请问如何获取？

我debug看这个是一个proxy，不知道怎么拿到他的泛型，然后最后从entity拿到@TableName的值，求助大神帮忙提供解决方案～

**Comment by miemieYaho** [comment]
参考 https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/injector/AbstractSqlInjector.java

**Comment by lehug** [comment]
抱歉，我思路错了，应该直接通过entity，不用绕道用mapper。
并且TableInfoHelper.getTableInfo(entity.getClass())可以获取到所有的tableInfo
