### ISSUE TITLE
3.3.1版本中联合主键的表 使用saveOrUpdateBatch时 查询时仅使用了其中一个字段

### ISSUE THREAD

**Issue by ersutUp** [baomidou/mybatis-plus#2227]
版本：3.3.1

问题：批量更新或者保存方法联合主键使用了其中一个字段

日志：

	Caused by: java.lang.NullPointerException
java.util.Objects.requireNonNull(Objects.java:203)
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.executeBatch(ServiceImpl.java:232)
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.executeBatch(ServiceImpl.java:252)
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveOrUpdateBatch(ServiceImpl.java:158)
com.baomidou.mybatisplus.extension.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$76535273.invoke(<generated>)
org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
xxx.xxxx.service.wx.friend.impl.FriendServiceImpl$$EnhancerBySpringCGLIB$$514edec5.saveOrUpdateBatch(<generated>)
xxx.xxxx.service.wehub.impl.WehubServiceImpl.savaFriend(WehubServiceImpl.java:264)
xxx.xxxx.service.wehub.impl.WehubServiceImpl.report_contact(WehubServiceImpl.java:216)
xxx.xxxx.service.wehub.impl.WehubServiceImpl$$FastClassBySpringCGLIB$$35e93373.invoke(<generated>)
org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)

Friend类：

public class Friend implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId
    private String wxId;
    @TableId
    private String toWxId;
}

**Comment by miemieYaho** [comment]
不支持联合主键
