### ISSUE TITLE
全局使用驼峰命名的bug

### ISSUE THREAD

**Issue by wanderhero** [baomidou/mybatis-plus#223]
mp 的 dbColumnUnderline 表示 是否使用下划线命名，如需驼峰命名，则 false
mybatis 的 mapUnderscoreToCamelCase 表示 是否开启自动驼峰命名规则，如需驼峰命名，则 true

以下代码在想全局驼峰，即dbColumnUnderline设置为 false，mapUnderscoreToCamelCase设置为 true 的时候，dbColumnUnderline又会是 true，等于又变成全局下划线了
```
         /*
         * 驼峰设置 PLUS 配置 > 原始配置
		 */
        GlobalConfiguration globalCache = this.getGlobalConfig();
        if (!globalCache.isDbColumnUnderline()) {
            globalCache.setDbColumnUnderline(configuration.isMapUnderscoreToCamelCase());
        }
```

**Comment by qmdx** [comment]
mp 受 mapUnderscoreToCamelCase 控制，如果你是驼峰请都不需要配置 或者 false

**Comment by wanderhero** [comment]
我调试过了，有问题的，问题就出在
mp 的 dbColumnUnderline false = mybatis 的 mapUnderscoreToCamelCase true
应该改成 globalCache.setDbColumnUnderline(!configuration.isMapUnderscoreToCamelCase());
```
         /*
         * 驼峰设置 PLUS 配置 > 原始配置
		 */
        GlobalConfiguration globalCache = this.getGlobalConfig();
        if (!globalCache.isDbColumnUnderline()) {
            globalCache.setDbColumnUnderline(!configuration.isMapUnderscoreToCamelCase());
        }
```
