### ISSUE TITLE
代码生成StrategyConfig中include字段并不支持正则表达式

### ISSUE THREAD

**Issue by IridescentL** [baomidou/mybatis-plus#2231]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.1.tmp

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

大神你好，我提一个小问题：
直接查看了代码生成部分源码，发现实际代码实现中include字段并不支持正则表达式，但文档中写的是支持正则表达式

### 报错信息

不报错，但功能失效。

**Comment by nieqiurong** [comment]
要不举起个栗子

**Comment by IridescentL** [comment]
代码位于类package com.baomidou.mybatisplus.generator.config.builder中的类ConfigBuilder的方法private List<TableInfo> getTablesInfo(StrategyConfig config)中

**Comment by nieqiurong** [comment]
我的意思是要你补充下你的正则表达式.

**Comment by IridescentL** [comment]
比如^\\w+$

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/blob/v3.3.1/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/builder/ConfigBuilder.java#L560
