### ISSUE TITLE
数据库字段包含blob类型时生成的代码无法编译

### ISSUE THREAD

**Issue by csxcsx00** [baomidou/mybatis-plus#2234]
### 当前使用版本(必须填写清楚，否则不予处理)
com.baomidou:mybatis-plus-generate:2.3.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用mybatis-plus-generate工具生成代码时必然会出现
经过跟踪源码发现com.baomidou.mybatisplus.generator.config.rules.DbColumnType中对BLOB类型的包定义貌似有问题，不仅是BLOB，TIME、CLOB和TIMESTAMP也存在这样的问题。
以下是com.baomidou.mybatisplus.generator.config.rules.DbColumnType中有问题的代码片段：
    TIME("Time", "java.querys.Time"),
    BLOB("Blob", "java.querys.Blob"),
    CLOB("Clob", "java.querys.Clob"),
    TIMESTAMP("Timestamp", "java.querys.Timestamp"),

### 重现步骤
1.准备数据源并创建表，表中包含类型为blob或longblob的字段，表中插入测试数据
2.引用mybatis-plus-generate工具生成代码
3.编译生成后的代码

### 报错信息
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[3,19] 程序包java.querys不存在
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[23,13] 找不到符号
[ERROR]   符号:   类 Blob
[ERROR]   位置: 类 com.caoshx.demo.freemarker.entity.HeadPortrait
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[42,12] 找不到符号
[ERROR]   符号:   类 Blob
[ERROR]   位置: 类 com.caoshx.demo.freemarker.entity.HeadPortrait
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[46,29] 找不到符号
[ERROR]   符号:   类 Blob
[ERROR]   位置: 类 com.caoshx.demo.freemarker.entity.HeadPortrait
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[3,19] 程序包java.querys不存在
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[23,13] 找不到符号
[ERROR]   符号:   类 Blob
[ERROR]   位置: 类 com.caoshx.demo.freemarker.entity.HeadPortrait
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[42,12] 找不到符号
[ERROR]   符号:   类 Blob
[ERROR]   位置: 类 com.caoshx.demo.freemarker.entity.HeadPortrait
[ERROR] /C:/my_project/freemarker_demo/src/main/java/com/caoshx/demo/freemarker/entity/HeadPortrait.java:[46,29] 找不到符号
[ERROR]   符号:   类 Blob
[ERROR]   位置: 类 com.caoshx.demo.freemarker.entity.HeadPortrait
[ERROR] -> [Help 1]

**Comment by nieqiurong** [comment]
2.x的版本应该不会再发正式版(可能会发快照版本),需要你自己拉源码代码打包.

**Comment by csxcsx00** [comment]
OK 感谢@nieqiurong
