### ISSUE TITLE
FactoryBean被提前初始化的bug

### ISSUE THREAD

**Issue by huangxfchn** [baomidou/mybatis-plus#2235]
# 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

# 该问题是怎么引起的？(最新版上已修复的会直接close掉)
3.2+版本使用了 spring-mybatis 提供的 `MapperScannerConfigurer`，但是这个会导致 FactoryBean 提前被初始化，具体见我提交的 [issue#454](https://github.com/mybatis/spring/issues/452)

# 重现步骤
参考 [issue#454](https://github.com/mybatis/spring/issues/452)

# 报错信息

**Comment by miemieYaho** [comment]
只需要升级 mybatis-spring 就可以了吧?

**Comment by huangxfchn** [comment]
> 只需要升级 mybatis-spring 就可以了吧?

是的，mybatis-spring 在 2.0.5 这个版本解决这个bug，但是现在还没有 RELEASE

**Comment by miemieYaho** [comment]
快照可以用撒

**Comment by huangxfchn** [comment]
可以用，这个bug已经提交commit了
