### ISSUE TITLE
@TableId(type = IdType.AUTO) 不生效

### ISSUE THREAD

**Issue by ltjackll** [baomidou/mybatis-plus#2239]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在全局以及pojo类下都声明了,但是依然会自动生成id而不是由数据库自增

### 重现步骤
代码如下:
- pojo:
    @TableId(type = IdType.AUTO)
    private Long id;
- properties:
mybatis-plus.global-config.db-config.id-type=auto

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by ltjackll** [comment]
Demo如下,麻烦了!
https://github.com/ltjackll/myBatisDemo

**Comment by miemieYaho** [comment]
版本 `3.1.1` ???

**Comment by miemieYaho** [comment]
建表sql呢?

**Comment by ltjackll** [comment]
我尝试降版本看行不行而已,忘改回来了,sql已上传.

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/76845638-27b9ac80-687a-11ea-8e7d-4d5a919d1735.png)
没毛病啊

**Comment by ltjackll** [comment]
惊了...见你这么一说,我回去把mybaits版本改到3.3.1(之前用的3.3.0),然后就好了,唉...又是一喊人查代码就没事了...好吧好吧,麻烦你了,谢谢谢谢~
