### ISSUE TITLE
[Bug]Enum @JSONField无法解析。

### ISSUE THREAD

**Issue by ukhack** [baomidou/mybatis-plus#224]
根据官方文档：http://baomidou.oschina.io/mybatis-plus-doc/#/enum
试着做了一个枚举类，使用的是fastJson的第二种形式，
文档表意不明，不确定究竟注释写在哪里。
```
@JSONField(serialzeFeatures= SerializerFeature.WriteEnumUsingToString)
    public String getKey() {
        return this.key;
    }
```
以及
```
@JSONField(serialzeFeatures= SerializerFeature.WriteEnumUsingToString)
private CashdiaryEnum type;
```

我在这两处都尝试了一下，调试时发现不能正确的替换值，而改成@JsonValue就可以使用了。

**Comment by qmdx** [comment]
http://baomidou.oschina.io/mybatis-plus-doc/#/enum?id=_3json%e5%ba%8f%e5%88%97%e5%8c%96%e5%a4%84%e7%90%86 这都是亲测好使的，如果不行你检查下你的配置是否正确
