### ISSUE TITLE
连接池问题请教

### ISSUE THREAD

**Issue by lehug** [baomidou/mybatis-plus#2243]
比如我在一个方法内，不加事物，我连续执行多个service方法，伪代码如下
```
public void methodA() {
    getById(1L);
    getById(2L);
    updateById(1L);
}
```
我从日志上看到`o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource` 多次的获取了jdbc连接。

请问我怎么设置，可以让这3个sql查询，共用一个jdbc连接？另外共用一个jdbc有意义吗？是否减少连接使用，可以优化代码？

**Comment by miemieYaho** [comment]
那就得加事务
