### ISSUE TITLE
kotlin+oracle序列生成问题

### ISSUE THREAD

**Issue by ljl5229662** [baomidou/mybatis-plus#2244]
### 
@Data
@TableName("BLOCK_CUSTOMER")
@KeySequence(value = "SEQ_customer", clazz = Long::class)
class BlockCustomerInfo : Serializable {

        @TableId(value = "ID",type = IdType.INPUT)
        val id: Long?= null

        val name: String?= null
        val tax_code: String?= null
        val work_address: String?= null
        val register_address: String?= null
        val contact: String?= null
        val mobile: String?= null
        val phone: String?= null
}

**Comment by nieqiurong** [comment]
检查一下是否配置了IKeyGenerator.

**Comment by ljl5229662** [comment]
> 检查一下是否配置了IKeyGenerator.

我理解IKeyGenerator只是针对不支持的数据库才自定义，而数据库一直使用的oracle，以前用java开发都可以自动生成，换成kotlin就不行，不是很清楚该如何配置，还请说明一下

**Comment by ljl5229662** [comment]
> 检查一下是否配置了IKeyGenerator.

确实是配置问题，感谢
