### ISSUE TITLE
多租户环境下使用mybatis <foreach>方式批量插入异常

### ISSUE THREAD

**Issue by snailst** [baomidou/mybatis-plus#225]
经测试发现在多租户环境下，使用xml方式的<foreach>批量插入时异常，其中collection集合size() > 1, 如果size() == 1时，则不会出现异常，mybatis-plus版本：2.1.8，报错位置：TenantSqlParser.processInsert(Insert insert)：
((ExpressionList) insert.getItemsList()).getExpressions().add(tenantHandler.getTenantId());
在collection集合size() >1 时，insert.getItemsList()的类型为MultiExpressionList，此时强制类型转换异常

**Comment by qmdx** [comment]
请关注 `2.1.9` 发布 ， 支持  `@SqlParser(filter=true)` 注解排除 mapp.java 批量操作建议使用 MP 的 service 层批量模式。
