### ISSUE TITLE
select行为不一致

### ISSUE THREAD

**Issue by YiuTerran** [baomidou/mybatis-plus#2250]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在QueryWrapper里select单列，如果该列为null，则返回实例也是null。此时有歧义：无法判断是对应的行根本不存在，还是对应的行存在，但是对应的列为null。

期望行为：返回一个实例，对应的列为null。

目前的解决方案：如果单列可能为null，就在select的时候加上id列。

**Comment by miemieYaho** [comment]
返回数据封装问题去找mybatis
