### ISSUE TITLE
租户隔离和默认内置字段的问题

### ISSUE THREAD

**Issue by dtless** [baomidou/mybatis-plus#2252]
### 当前使用版本(必须填写清楚，否则不予处理)

是这样的，一个多租户的管控后台，做内置字段和租户隔离是没有问题的，但如果我这个东西要提供给第三方接口，那这几个字段就不一定有，要怎么做到某几张表，在必要的时候进行租户隔离查询，不必要的时候跳过这个限制

哈哈，怎么联系作者？微信？

**Comment by miemieYaho** [comment]
不需要租户过滤的method加上注解,看文档
