### ISSUE TITLE
typehandler 配置相关

### ISSUE THREAD

**Issue by wunian7yulian** [baomidou/mybatis-plus#2253]
https://mybatis.plus/guide/typehandler.html
文档中 是注解和xml配置二选一   
我在项目实践中(非官方demo给出的无xml方式)
不在xml中写入配置 会导致项目启动直接报错
不在entity中写入 autoResultMap=true 会导致 无法走handler中的转换方法
在entity中写入 autoResultMap=true  则必须写入需要转换字段的*handler.class
综上 文档所说的二选一配置方法  在有xml方式的项目中不适应  应该为都要配置

**Comment by miemieYaho** [comment]
哪里写二选一了? 注解只生效于mp注入的通用select,之外你自己写的select用不了mp构造的resultMap只能你自己在xml里resultMap使用

**Comment by wunian7yulian** [comment]
该注解对应了 XML 中写法为

这句话的意思引起误解了 '

**Comment by miemieYaho** [comment]
后面会考虑改改
