### ISSUE TITLE
用到两个 where 查询 给两个Wrapper设置@Para 无效3.1.1

### ISSUE THREAD

**Issue by Chaoscz** [baomidou/mybatis-plus#2254]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1

### 该问题是怎么引起的？
 List<Tree> getParentRoleMenu(@Param("wrapper1") Wrapper<RoleMenu> wrapper1,@Param(Constants.WRAPPER) Wrapper<Menu> wrapper);

**Comment by miemieYaho** [comment]
不支持2个wrapper
