### ISSUE TITLE
多数据源，用mp自带的查询方法报错

### ISSUE THREAD

**Issue by hhzh** [baomidou/mybatis-plus#226]
Caused by: org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.demo.dao.UserMapper.selectById

但是我写的原生的SQL查询，切换主从都没问题。我猜测可能是没扫描到mapper.xml文件。
这是application.yaml
`master:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.100.1.1:3306/union
    username: root
    password: 123456
  mybatis:
    typeAliasesPackage: com.union.entity
    mapper-locations: classpath:/mapper/*Mapper.xml

slave:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.100.1.1:3306/scmd
      username: root
      password: 123456
  mybatis:
      typeAliasesPackage: com.union.entity
      mapper-locations: classpath:/mapper/*Mapper.xml`

加载动态数据源的类：
`@Configuration
@MapperScan(basePackages = {"com.union.dao"}, sqlSessionFactoryRef = "sqlSessionFactoryBean")
public class DataSourceConfig {

    @Bean
    @ConfigurationProperties(prefix = "master.datasource")
    public DataSource dataSource1() {
        return DataSourceBuilder.create().build();
    }

    @Bean
    @ConfigurationProperties(prefix = "slave.datasource") 
    public DataSource dataSource2() {
        return DataSourceBuilder.create().build();
    }

    /**
     * 动态数据源: 通过AOP在不同数据源之间动态切换
     *
     * @return
     */
    @Bean
    @Primary
    public DataSource dataSource() {
        DynamicDataSource dynamicDataSource = new DynamicDataSource();
        // 默认数据源
        dynamicDataSource.setDefaultTargetDataSource(dataSource1());

        // 配置多数据源
        Map<Object, Object> dsMap = new HashMap<>(5);
        dsMap.put(DBTypeEnum.UNION_DB, dataSource1());
        dsMap.put(DBTypeEnum.SCMD_DB, dataSource2());

        dynamicDataSource.setTargetDataSources(dsMap);

        return dynamicDataSource;
    }

    @Bean
    @ConfigurationProperties(prefix = "master.mybatis")
    public SqlSessionFactoryBean sqlSessionFactoryBean() {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSource());
        return sqlSessionFactoryBean;
    }

    @Bean
    public PlatformTransactionManager transactionManager() {
        return new DataSourceTransactionManager(dataSource());
    }
}`

诸位帮我看看是啥问题，折腾好几天了。

**Comment by xuqinjie** [comment]
```
@Bean
@ConfigurationProperties(prefix = "master.mybatis")
public SqlSessionFactoryBean sqlSessionFactoryBean() {
    SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(dataSource());
    return sqlSessionFactoryBean;
}
```
应该是这块不对，你只简单创建了个SqlSessionFactoryBean，没有任何初始化。
具体参考MybatisPlusAutoConfiguration

**Comment by qmdx** [comment]
http://baomidou.oschina.io/mybatis-plus-doc/#/multi-datasource
