### ISSUE TITLE
springboot整合mybasit-plus3.3.1.temp启动项目扫描不了mapper接口

### ISSUE THREAD

**Issue by xhlc02** [baomidou/mybatis-plus#2268]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用springboot2.2.5.RELEASE 整合mybatis-plus，配置了扫描包，

### 重现步骤
springboot2.2.5.RELEASE整合mybatis-plus3.3.1.tmp，配置userServiceImpl继承ServiceImpl 以及UserMapper继承BaseMapper<>，运行项目报错
然后引入
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>3.3.1.tmp</version>
        </dependency>
项目可以正常运行

### 报错信息
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysUserMapper' defined in file [E:\xuexi\xmall\mall2\target\classes\com\mall\project\system\user\mapper\SysUserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory

**Comment by nieqiurong** [comment]
自行检查依赖mybatis-spring冲突问题.
