### ISSUE TITLE
TableField 的value和entity字段名（驼峰命名）不一致时不会自动映射

### ISSUE THREAD

**Issue by zhangdc007** [baomidou/mybatis-plus#2277]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
有个表，字段叫class,自动生成的时候，class是java关键字，于是改名为className 
 @TableField("class")
    private Date class;
改为
 @TableField("class")
    private Date className;
但是查询无法查到该字段，并没有想象中进行映射
修复：查询的时候，主动as 为class_name解决
   QueryWrapper<entity> query = new QueryWrapper<>();
        query.select("class as class_name");

期望，不用手工as ，在 TableField里的数据库字段自动映射

**Comment by miemieYaho** [comment]
给出你的复现demo
