### ISSUE TITLE
代码生成器strategy.setColumnNaming设置无效

### ISSUE THREAD

**Issue by springpro** [baomidou/mybatis-plus#2278]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
strategy.setColumnNaming(NamingStrategy.underline_to_camel);

com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder
第653行：
field.setPropertyName(strategyConfig, processName(field.getName(), config.getNaming()));
应该为：config.getColumnNaming()

### 重现步骤
StrategyConfig strategy = new StrategyConfig();
//strategy.setNaming()  不设置
strategy.setColumnNaming(NamingStrategy.underline_to_camel);

**Comment by nieqiurong** [comment]
最新源码改过一次了.

**Comment by nieqiurong** [comment]
#2203

**Comment by nieqiurong** [comment]
用3.3.2.1-SNAPSHOT试试，使用方式参考https://mp.baomidou.com/guide/install.html#snapshot
