### ISSUE TITLE
能否给mapper或server加个回调处理结果的功能

### ISSUE THREAD

**Issue by luyanfeng** [baomidou/mybatis-plus#2282]
### 当前使用版本(必须填写清楚，否则不予处理)

所有

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
能否给mapper或server加个回调处理结果的功能。比如我只想查询10个用户的id，但应为用的是实体，返回的是实体list，我还只能遍历这个集合再重组件list<Long>之类的东西。

**Comment by miemieYaho** [comment]
用listobj或者自己写工具类处理

**Comment by luyanfeng** [comment]
@miemieYaho 就是说目前只能『我还只能遍历这个对像集合list<ObjectEntity>再重组成id集合list<long>之类的东西。』

**Comment by miemieYaho** [comment]
listObj指定只查id不需要遍历,list返回entity需要遍历

**Comment by luyanfeng** [comment]
谢谢，看过，但文档描述的看不出是什么操作就没偿试


有事请联系QQ:506915189


在2020年03月25日 16:52，miemieYaho<notifications@github.com> 写道：

listObj指定只查id不需要遍历,list返回entity需要遍历
