### ISSUE TITLE
lambdaQuery().in语句，当列表长度为0时，sql报错

### ISSUE THREAD

**Issue by hiro0729** [baomidou/mybatis-plus#2283]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

```java
Set<Integer> groupIds = platformGroupUserMappingService.lambdaQuery().eq(PlatformGroupUserMapping::getUserID, userID).list().stream().map(PlatformGroupUserMapping::getGroupID).collect(Collectors.toSet());
platformRoleGroupMappingService.lambdaQuery().in(PlatformRoleGroupMapping::getGroupID, groupIds).list();
```

### 重现步骤
当groupIds 获取数据为空时，SQL语句报错

### 报错信息
![image](https://user-images.githubusercontent.com/7811341/77522952-02ebb780-6ec0-11ea-938d-017a1af26916.png)

**Comment by miemieYaho** [comment]
自己判空处理
