### ISSUE TITLE
TypeHandler 如果使用了@Component注解则对所有泛型类型都生效

### ISSUE THREAD

**Issue by FJiayang** [baomidou/mybatis-plus#2284]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用了@Component注解后，不管字段上是否指定了@TableField，或者使用自定义ResultMap都会对所有String类型生效

### 重现步骤
1. 实体类对指定的一个String类型字段配置了TypeHandler
2. 在自定义实现的针对String类型的TypeHandler，若不使用@Component注解得到的结果符合预期
3. 加上@Component注解后，不管字段上是否指定了@TableField，或者使用自定义ResultMap都会对所有String类型生效

### 报错信息
无报错信息

处理器定义
```java
@Component
public class StringTypeHandler extends BaseTypeHandler<String> {}
```

**Comment by miemieYaho** [comment]
就这样的，你用mybatis也一样
