### ISSUE TITLE
全局逻辑删除，自动填充日期无效

### ISSUE THREAD

**Issue by funtask** [baomidou/mybatis-plus#2285]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 重现步骤
实体类：
    @TableField(fill= FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;

执行逻辑删除，更新deleted字段为逻辑删除时，updateTime没有更新
==>  Preparing: UPDATE cms_storage SET deleted=1 WHERE deleted=0 AND (`key` = ?) 

### 报错信息
更新时间不会自动填充

**Comment by miemieYaho** [comment]
去看文档常见问题
