### ISSUE TITLE
代码生成器主键策略无法修改

### ISSUE THREAD

**Issue by funtask** [baomidou/mybatis-plus#2288]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

设置为ASSIGN_UUID
gc.setIdType(IdType.ASSIGN_UUID);

生成实体为AUTO
@TableId(value = "id", type = IdType.AUTO)
private Long id;

### 重现步骤
    <#if field.keyFlag>
        <#-- 主键 -->
        <#if field.keyIdentityFlag>
    @TableId(value = "${field.name}", type = IdType.AUTO)
        <#elseif idType??>
    @TableId(value = "${field.name}", type = IdType.${idType})
        <#elseif field.convert>
    @TableId("${field.name}")
        </#if>

**Comment by nieqiurong** [comment]
这个好像还和数据库表是否设置了是否自增长有关.

**Comment by funtask** [comment]
> 这个好像还和数据库表是否设置了是否自增长有关.

数据库主键是自增的，从模板文件上看keyIdentityFlag true都是IdType.AUTO
但是自增主键不能设置雪花主键？

**Comment by miemieYaho** [comment]
自增不行
