### ISSUE TITLE
主键兼容策略

### ISSUE THREAD

**Issue by lclmichael** [baomidou/mybatis-plus#2291]
当前使用版本
<dependency>
  <groupId>com.baomidou</groupId>
  <artifactId>mybatis-plus-boot-starter</artifactId>
  <version>3.3.0</version>
</dependency>

在使用@TableId(type = IdType.AUTO)
调用BaseMapper.insert(entity)时，entity指定id会被忽略而生成mysql的自增id。

能否有个一个兼容模式，指定主键不为null时候使用input模式，指定主键为null时使用auto模式或者用mysql自己的生成策略。

**Comment by miemieYaho** [comment]
不能

**Comment by dunkboy** [comment]
为什么不能 这个策略有些场景还是需要吧
