### ISSUE TITLE
复合主键的updateById，deleteById，是否支持？

### ISSUE THREAD

**Issue by xinsibo** [baomidou/mybatis-plus#2292]
### 该问题是怎么引起的？**(

使用@TableId注解标记双主键，调用baseMapper 的 updateById(Entity entity)无效，会执行update table_name set 主键1=？ where 主键2=？，导致唯一性约束错误。

)**

### 重现步骤

使用@TableId注解标记双主键，调用baseMapper 的 updateById(Entity entity)无效，会执行update table_name set 主键1=？ where 主键2=？，导致唯一性约束错误。

### Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: 违反唯一约束条件 (POSP.SYS_C009385)

; ORA-00001: 违反唯一约束条件 (POSP.SYS_C009385)
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-00001: 违反唯一约束条件 (POSP.SYS_C009385)

**Comment by miemieYaho** [comment]
不支持,下版本多个注解将直接启动报错
