### ISSUE TITLE
v3.3.1 新增批量执行用法提供

### ISSUE THREAD

**Issue by fullSecKil** [baomidou/mybatis-plus#2297]
### 当前使用版本(必须填写清楚，否则不予处理)

v3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我看你们更新日志里有提到自定义批量执行操作请问有使用的例子提供吗

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/blob/v3.3.1/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/h2/cache/service/impl/CacheServiceImpl.java#L17

**Comment by yuxiaobin** [comment]
参考 [示例项目](https://github.com/baomidou/mybatis-plus-samples)
其中就有：
* mybatis-plus-sample-sql-injector: 自定义全局操作示例
* mybatis-plus-sample-deluxe: 完整示例（包含 分页、逻辑删除、自定义全局操作 等绝大部分常用功能的使用示例，相当于大整合的完整示例）
