### ISSUE TITLE
IMetaObjectHandler 公共字段填充只有在tableInfo.getIdType().getKey() >= 2才可用

### ISSUE THREAD

**Issue by enzocq** [baomidou/mybatis-plus#23]
MybatisDefaultParameterHandler.java
protected static Object populateKeys(TableInfo tableInfo, MappedStatement ms, Object parameterObject) {
if (null != tableInfo && StringUtils.isNotEmpty(tableInfo.getKeyProperty()) && null != tableInfo.getIdType()
				&& **tableInfo.getIdType().getKey() >= 2**) {
}
这里的判断只是给主键设置用的吧，公共字段的填充如CreateDate, 不应该放在这个if块里面。
请苗大侠解答。

**Comment by qmdx** [comment]
已经修复，下一个版本会支持
