### ISSUE TITLE
请问大神 mp最新版本支持optional吗？

### ISSUE THREAD

**Issue by fengsuiyuan** [baomidou/mybatis-plus#2305]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

请问大神 mp最新版本支持optional吗？自动生成哪里该怎么设置才能让像byId这项的查询返回的对象是Optional<Object>

### 重现步骤

3333

### 报错信息

33333

**Comment by nieqiurong** [comment]
升级版本后,原生的支持了,mp暂时没的,得自己弄.

**Comment by fengsuiyuan** [comment]
好的 知道了 十分谢谢 希望能早日支持optional 写非空判断之类的实在太难受了
