### ISSUE TITLE
Lambda条件生成器怎么使用sql函数？

### ISSUE THREAD

**Issue by funtask** [baomidou/mybatis-plus#2306]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

QueryWrapper没问题，我可以直接写字符串
QueryWrapper<Order> qw = new QueryWrapper<Order>();
qw.select("count(*) count", "order_status status")

LambdaQueryWrapper该怎么用？
        LambdaQueryWrapper<Order> lqw = new LambdaQueryWrapper<Order>(Order.class);
        lqw..select(Order::getOrderStatus,"count(*) count")
                .groupBy(Order::getOrderStatus);

**Comment by miemieYaho** [comment]
不支持,你只能QueryWrapper.select之后再.lambda使用
