### ISSUE TITLE
全局逻辑删除的问题

### ISSUE THREAD

**Issue by hepengju** [baomidou/mybatis-plus#231]
baseMapper中deleteBatchIds参数名称为: coll
AutoSqlInjector中injectDeleteByIdSql方法batch时参数也是coll, 没有问题
LogicSqlInjector中重写的injectDeleteByIdSql方法batch时参数为list, 实测运行报错.

LogicSqlInjector的injectSelectByIdSql方法也有此BUG
还请大侠修改.

**Comment by chwoyaofei** [comment]
今天使用批量逻辑删除是也遇到了相同的问题，已经确认是这个问题
在自己的的Mapper中增加方法覆盖deleteBatchIds，只是将@Param中的coll改成list即可
@Override
Integer deleteBatchIds(@Param("list") Collection<? extends Serializable> idList);

**Comment by qmdx** [comment]
@hepengju @chwoyaofei  解决 https://gitee.com/baomidou/mybatis-plus/commit/3bb5e041cd324ec9d80d7aed1c68fb63803fd715 请关注下一个版本。
