### ISSUE TITLE
多数据源切换问题

### ISSUE THREAD

**Issue by TongKevin** [baomidou/mybatis-plus#2312]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用多数据源时，在同一个mapper中切换数据源时，数据源名称包含下划线时切换失败，但官网的例子却是包含下划线的

**Comment by miemieYaho** [comment]
去那边提

**Comment by TongKevin** [comment]
> 去那边提
什么意思？哪边？

**Comment by TongKevin** [comment]
> 去那边提

什么意思？哪边？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter
