### ISSUE TITLE
请问一下使用in条件查询，使用哪个order by 可以保证查出来的跟in里面的顺序一致？

### ISSUE THREAD

**Issue by yangbo-true1** [baomidou/mybatis-plus#2313]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

无
### 重现步骤

无

### 报错信息
无

**Comment by yangbo-true1** [comment]
也就是使用自定义的排序，field函数

**Comment by miemieYaho** [comment]
不知道,我们也不负责教写sql
