### ISSUE TITLE
MySQL JSON语法查询无报错无结果，望大佬教育

### ISSUE THREAD

**Issue by zhaoxiufei** [baomidou/mybatis-plus#2315]
demo 里面是 varchar 类型的 而我的是JSON类型 加了Hanler 并没有什么用

_Originally posted by @miemieYaho in https://github.com/baomidou/mybatis-plus/issues/2314#issuecomment-607837919_

**Comment by qmdx** [comment]
你 debug 下 typeHandler 看看原因，需要注意的是反序列化是否生效了
