### ISSUE TITLE
可不可以增加 比如 userService.setTableName("user_1") 动态设置表名的功能

### ISSUE THREAD

**Issue by CrazyLionL** [baomidou/mybatis-plus#2317]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
有需求  需要根据参数动态生成表  与  根据参数动态查询表

**Comment by miemieYaho** [comment]
用sharding-jdbc
