### ISSUE TITLE
no duplicate key update 是否支持

### ISSUE THREAD

**Issue by yxsongy** [baomidou/mybatis-plus#2318]
### 当前使用版本(必须填写清楚，否则不予处理)
请问是否支持no duplicate key update ？现在从xml中写sql的方式转换成plus写法，因特殊原因需要原xml写法中设置了no duplicate key update， 转成plus写法因没有找到相关设置，多线程并发报错

**Comment by miemieYaho** [comment]
不支持,都是通用sql
