### ISSUE TITLE
枚举支持从数据库字典表里动态生成吗

### ISSUE THREAD

**Issue by muziling** [baomidou/mybatis-plus#2319]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp

枚举文档里的：
PRIMARY(1, "小学"),  SECONDORY(2, "中学"),  HIGH(3, "高中");

这种1，2，3及对应的中文，可以配置为数据库里的字典表数据吗，即不在JAVA里写死枚举1，2，3的值。

**Comment by miemieYaho** [comment]
不能
