### ISSUE TITLE
使用mybatis-plus 插件进行查询无法获取total 和 pages,

### ISSUE THREAD

**Issue by fanyaoxuan** [baomidou/mybatis-plus#232]
1、分页插件配置
`@Bean
    public PaginationInterceptor paginationInterceptor() {
        return new PaginationInterceptor();
    }`
2、查询条件
`public Page<SysUserEntity> queryUserListByMap(Page<SysUserEntity> page,SysUserEntity sysUserEntity) throws Exception{
		try {
			Page<SysUserEntity> sysUserEntities = selectPage(page,new EntityWrapper<>(sysUserEntity));
			logger.debug("分页查询公司的用户,查询条件:{},查询结果:{}", sysUserEntity,JSONObject.toJSONString(sysUserEntities));
			return sysUserEntities;
		} catch (Exception e) {
			logger.error("分页查询公司的用户失败,查询条件:{},异常信息:{}",JSONObject.toJSONString(sysUserEntity),e.getStackTrace());
			throw e;
		}
	}`
3、查询结果
` Page:{ [Pagination { total=0 ,size=10 ,pages=0 ,current=1 }], records-size:1 }`

**Comment by qmdx** [comment]
这里是否配置 http://baomidou.oschina.io/mybatis-plus-doc/#/page-plugin

**Comment by fanyaoxuan** [comment]
@qmdx  `
![image](https://user-images.githubusercontent.com/22194156/35395769-4240b506-0226-11e8-9fde-2325998dd532.png)
`
这里理解有误，只配置了spring boot的配置，而没有加入mybais-config 中的插件配置，谢谢
