### ISSUE TITLE
@DS不生效

### ISSUE THREAD

**Issue by BazookaW** [baomidou/mybatis-plus#2321]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

比如如下代码，我在Repository中加了@DS("ods")注解，但是不能生效

```
@Component
@DS("ods")
public interface UcUserRepository extends BaseMapper<UcUser> {

    Page<UcUser> ucUserList(Page<?> page, @Param("userIds") List<Long> userIds, @Param("nickname") String nickname,
                             @Param("literaturePhaseId") String literaturePhaseId, @Param("mathPhaseId") String mathPhaseId,
                             @Param("courseId") String courseId, @Param("classId") String classId,
                             @Param("teacherId") String teacherId, @Param("tags") List<Integer> tags);
}
```

### 重现步骤
我的table -> uc_user在ods库里的，但是却会去crm_service这个库里找，所以每次请求都会报找不到table的错误。

### 报错信息
Table 'crm_service.uc_user' doesn't exist

![image](https://user-images.githubusercontent.com/17539174/78498795-f8aea080-777e-11ea-8191-293696a6ce34.png)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter
