### ISSUE TITLE
in查询,内存无法回收,最终导致内存溢出

### ISSUE THREAD

**Issue by PerryZhu** [baomidou/mybatis-plus#2324]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用in查询进行批量查询时,JVM无法回收内存,经过几次查询后jvm的char数组实例数会迅速飙升,最后导致OOM

### 重现步骤
使用in查询多次进行批量查询

### 报错信息
OOM

**Comment by l617388617** [comment]
我这边也遇到了同样的情况， 3.2.1 版本， 大量使用 in 查询导致内存飙升。无法回收内存，请问下是不是mybatis plus 有缓存查询语句导致的？

**Comment by miemieYaho** [comment]
in的数据量特别多,建议自己写xml
