### ISSUE TITLE
集成mp后不支持mybatis-velocity的sql的脚本解析

### ISSUE THREAD

**Issue by TenShenSun** [baomidou/mybatis-plus#2325]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp
是不是mp目前不支持，还是可以通过其他方法配置使其支持，如果不支持后期能不能考虑下升级，感觉mybatis的脚本解析能力还是挺弱的，不过现在官方也开始支持了。http://mybatis.org/velocity-scripting/index.html

**Comment by miemieYaho** [comment]
default scripting language 不支持,其他支持,该怎么用怎么用
