### ISSUE TITLE
重写BaseMapper导致的报错

### ISSUE THREAD

**Issue by ljp190** [baomidou/mybatis-plus#2328]
### 当前使用版本 3.3.0

公司新人，就想重写BaseMapper中的方法（我也是服气，文档都看了，就是想起一模一样的方法名），导致大量报错
之前也没遇到过相关问题，排查了一下午才发现是由于mapper的方法名和BaseMapper里面方法名一样，重写了BaseMapper里的方法

能不能让BaseMapper和IService中内置的方法不可被重写呢

**Comment by miemieYaho** [comment]
你得问oracle答不答应
