### ISSUE TITLE
Mybatis-plus 2.1.8 SqlExplainInterceptor 与 Driud 配合使用时异常 ast.statement.MySqlExplainStatement not allow :

### ISSUE THREAD

**Issue by jackphang** [baomidou/mybatis-plus#233]
`Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: com.baomidou.mybatisplus.exceptions.MybatisPlusException: java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlExplainStatement not allow : EXPLAIN UPDATE tm_plan SET valid_flag='0' WHERE plan_id=?`

` /**
     * SQL 执行分析拦截器 stopProceed 发现全表执行 delete update 是否停止运行
     * 作用是分析 处理 DELETE UPDATE 语句， 防止小白或者恶意 delete update 全表操作！
     * 该插件只用于开发环境，不建议生产环境使用。。
     * * 会抛错，暂时屏蔽
     * com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlExplainStatement not allow :
     * @author: jackphang
     * @date: 18-1-23 上午9:30
     */
    @Bean
    public SqlExplainInterceptor sqlExplainInterceptor() {
        SqlExplainInterceptor sqlExplainInterceptor = new SqlExplainInterceptor();

        sqlExplainInterceptor.setStopProceed(true);
        return sqlExplainInterceptor;
    }`

解决方法，去掉SqlExplainInterceptor即可

**Comment by qmdx** [comment]
这个插件使用者比较少，如果你可以解决 欢迎 PR
