### ISSUE TITLE
kotlin 中 lambda表达式不能使用

### ISSUE THREAD

**Issue by Ambitie** [baomidou/mybatis-plus#2330]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.1

### 具体情况以及分析：
 
https://cloud.tencent.com/developer/article/1563019

**Comment by miemieYaho** [comment]
自己new https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/kotlin/com/baomidou/mybatisplus/extension/kotlin/KtQueryWrapper.kt
