### ISSUE TITLE
使用Service CRUD 接口无法被Spring Boot 扫描注册成bean

### ISSUE THREAD

**Issue by liuxinhh** [baomidou/mybatis-plus#2331]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter  ->   3.3.1
spring-boot-starter-parent  ->  2.2.6.RELEASE

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用 `IService<T>` 接口和实现类无法被Spring Boot扫描到 

### 重现步骤
```
public interface IDictDataService extends IService<DictData> {
}
```
```
public interface IDictDataService extends IService<DictData> {
}
```
```
public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(LayuiAdminApplication.class, args);
        DictDataServiceImpl bean = context.getBean(DictDataServiceImpl.class);
        System.out.println(bean);
    }
```

```

### 报错信息

```
Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.layui.admin.web.system.service.impl.DictDataServiceImpl' available

```

**Comment by qmdx** [comment]
配置使用问题，更多参考 https://github.com/baomidou/mybatis-plus-samples
