### ISSUE TITLE
mybatis-plus注解处理代码

### ISSUE THREAD

**Issue by yueyuebixa** [baomidou/mybatis-plus#2337]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.1

### 重现步骤

mybatis-plus新增了一些注解，翻阅jar包的时候，没看到对于注解处理的相关代码，能否告知具体位置学习一下。感谢

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/metadata/TableInfoHelper.java
