### ISSUE TITLE
AOP动态代理 抛异常

### ISSUE THREAD

**Issue by chengjianhit** [baomidou/mybatis-plus#2339]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
当用户自定义AOP切面时，执行完切点的方法后，异步线程执行自定义业务逻辑（自定义业务逻辑使用mybatis-plus新增数据），会抛异常。但不影响整个业务流程。

### 重现步骤
1、自定义AOP
2、在AOP逻辑里，使用异步线程、通过mybatis-plus操作数据
3、抛异常

### 报错信息
org.springframework.aop.AopInvocationException：Null return value from advice does not match primitive return typr for : public abstract boolean ***.***.***.method(***.***.***.JavaPOJO)
考虑隐私需要，包名使用“***”替代

如果不使用异步线程执行数据库操作，则没有异常信息

**Comment by miemieYaho** [comment]
用最新版给出你的复现demo
