### ISSUE TITLE
查询结果 Page 放入 redis, 取出来的时候报错

### ISSUE THREAD

**Issue by simplelist** [baomidou/mybatis-plus#234]
直接将查询分页结果Page<Entity>放入 redis,第二次取出该对象强转成 PageM<Entity>报错.
offsetCurrent 不是一个字段. redis 里存了该字段. Page 对象没有 offsetCurrent 这个字段导致的
` at [Source: [B@b3af211; line: 1, column: 481] (through reference chain: com.baomidou.mybatisplus.plugins.Page["offsetCurrent"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "offsetCurrent" (class com.baomidou.mybatisplus.plugins.Page), not marked as ignorable (13 known properties: "size", "records", "total", "searchCount", "openSort", "asc", "offset", "orderByField", "current", "limit", "pages", "isAsc", "condition"])
 at [Source: [B@b3af211; line: 1, column: 481] (through reference chain: com.baomidou.mybatisplus.plugins.Page["offsetCurrent"])] with root cause`

**Comment by qmdx** [comment]
已解决！ 请关注 `2.1.9` 的发布 https://gitee.com/baomidou/mybatis-plus/commit/d952e189d3f97a831d9d59041225dd06b37e5403
