### ISSUE TITLE
nextId分布式主键重复，是否可以加一个端口号的后缀？

### ISSUE THREAD

**Issue by DkAlsace** [baomidou/mybatis-plus#2340]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在一个服务器起多个主键服务。

### 重现步骤
在一个服务器起多个主键服务。

### 报错信息
主键重复。

**Comment by qmdx** [comment]
重复可能是因为你一台机器部署 多个节点等因素，你可以试着设置里面的一些参数，IdWorker.getId() 就是主键 ID 你可以自己加上后缀什么的 setId(新的 id)
