### ISSUE TITLE
mybatis-plus 总是报空指针异常

### ISSUE THREAD

**Issue by sun-chao** [baomidou/mybatis-plus#2343]
### 当前使用版本(必须填写清楚，否则不予处理)
使用版本3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
查询语句写了对应的xml文件，其中一个字段名写错了；调用的时候报的错误不是sql异常，而是一个空指针异常。
打断点发现DefaultSqlSession中的selectOne中返回的list集合为空，然后判断list.size()的时候报了空指针；可是这明明是sql异常的问题，这样报错以后都不好定位问题？

**Comment by miemieYaho** [comment]
mp不进行sql执行及数据封装,自己排查

**Comment by sun-chao** [comment]
大哥，我想说的是mp把一些sql异常报错返回为空指针异常，这样真的好吗？？？

**Comment by miemieYaho** [comment]
那你告诉我是mp哪行代码拦截了sql异常?
