### ISSUE TITLE
Page类同时实现了Map接口，查询无法返回结果

### ISSUE THREAD

**Issue by wxjwzx** [baomidou/mybatis-plus#2346]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

自定义了一个MyPage类，继承了Page类,同时又实现了Map接口。使用 @SelectProvider 方式进行进行分页查询后，无法返回查询结果。

### 重现步骤

自定义了一个MyPage类，继承了Page类,同时又实现了Map接口。使用 @SelectProvider 方式进行进行分页查询后，无法返回查询结果。

### 报错信息
无报错信息，没有返回查询数据

**Comment by miemieYaho** [comment]
不支持map
