### ISSUE TITLE
询问一下配置问题

### ISSUE THREAD

**Issue by FromNowSHC** [baomidou/mybatis-plus#2348]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
我使用的是springboot + mybatis plus + oracle
看网上说

#如果插件版本是3.0-gamma这个选项必须配置,否则会nullPoint
mybatis-plus.global-config.db-config.db-type=oracle

想问一下是不是必须配置？

**Comment by miemieYaho** [comment]
现在没db-type了
