### ISSUE TITLE
用LambdaQueryChainWrapper构建的条件执行mapper.delete(wrapper)会报异常

### ISSUE THREAD

**Issue by ifaron** [baomidou/mybatis-plus#2349]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

用LambdaQueryChainWrapper构建的条件执行mapper.delete(wrapper)会报异常
而用LambdaQueryWrapper构建的条件同样执行mapper.delete(wrapper)是正常的

### 报错信息
BuilderException: Error evaluating expression 'ew.entity != null'
MybatisPlusException: can not use this method for "getEntity"

**Comment by miemieYaho** [comment]
LambdaQueryChainWrapper.delete

**Comment by Suomm** [comment]
> LambdaQueryChainWrapper.delete

哪个版本？

**Comment by qmdx** [comment]
因为 LambdaQueryChainWrapper 禁用了  getEntity() 方法，链式调用不能放到方法参数中

```
public T getEntity() {
   throw ExceptionUtils.mpe("can not use this method for \"%s\"", "getEntity");
}
```
