### ISSUE TITLE
二级缓存和多表查询分页

### ISSUE THREAD

**Issue by hepengju** [baomidou/mybatis-plus#235]
1. Mybatis开启二级缓存, 在Mapper文件中自定义SQL的方法有缓存, Mybatis-Plus本身注入的方法没有使用缓存,而是新发送SQL语句, 查找许久,没有找到原因, 不知是何缘故?

2. Mybatis-Plus本身的通用Service的selectPage, 其中Page<T>需要指定泛型, 报表查询需要关联多个表, 此时需要在xml中自定义SQL语句, 此时如何分页呢? 
 只能开始PageHelper, 然后调用PageHelper.startPage吗?

**Comment by qmdx** [comment]
1、缓存问题 http://baomidou.oschina.io/mybatis-plus-doc/#/question?id=mapper-%e5%b1%82%e4%ba%8c%e7%ba%a7%e7%bc%93%e5%ad%98%e9%97%ae%e9%a2%98


2、分页问题 http://baomidou.oschina.io/mybatis-plus-doc/#/page-plugin?id=%e6%96%b9%e5%bc%8f%e4%b8%80-%e3%80%81%e4%bc%a0%e5%8f%82%e5%8c%ba%e5%88%86%e6%a8%a1%e5%bc%8f%e3%80%90%e6%8e%a8%e8%8d%90%e3%80%91


问？？？？为什么不看文档？？？？？？？？

**Comment by hepengju** [comment]
不好意思, 之前文档我也是真的读了好几遍了, 但是关于缓存问题,文档中就如下一句话:
**<我们建议缓存放到 service 层，你可以自定义自己的 BaseServiceImpl 重写注解父类方法，继承自己的实现。>**
没有看懂, Mybatis的缓存不是全局配置开启, xml追加<cache>就可以了吗? 实测自己在xml中配置的SELECT语句可以击中缓存的, 但是自动注入的没有击中.

分页的我看文档中也只有一个简单单表示例, 那我再研究研究吧.
