### ISSUE TITLE
多租户模式下能否配置自定义sql均不开启

### ISSUE THREAD

**Issue by chaitou** [baomidou/mybatis-plus#2352]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
多租户模式下经常使用关键字报错，加@sqlFilter在方法上可以解决
可不可以开启配置，让所有自定义的sql都不开启多租户模式

**Comment by miemieYaho** [comment]
不能
