### ISSUE TITLE
是不是不支持mapper和XML放不同文件夹

### ISSUE THREAD

**Issue by A3liu** [baomidou/mybatis-plus#2353]
### 该问题是怎么引起的？**([最新版]
mapper和XML不在同一文件夹下，mybatis无法识别

### 重现步骤
如上，
切换回mybatis-spring-boot-starter之后问题解决

**Comment by A3liu** [comment]
猜测是不是mapperLocation配置没有识别

**Comment by miemieYaho** [comment]
xml默认放resource下,放java下看文档常见问题
