### ISSUE TITLE
Mapper xml 文件在Idea中显示“Cannot resolve symbo”

### ISSUE THREAD

**Issue by pengyusong** [baomidou/mybatis-plus#2357]
版本：3.3.1.tmp

代码生成脚本生成的XML Mapper文件在Idea中提示不能解析符号，由于生成的Model中带有“@Accessors(chain = true)” 注解导致Idea无法正常解析

**Comment by nieqiurong** [comment]
用3.3.2.1-SNAPSHOT试试，使用方式参考https://mp.baomidou.com/guide/install.html#snapshot

**Comment by pengyusong** [comment]
strategyConfig.setChainModel(false);
设置了还是没效果呢
