### ISSUE TITLE
maven下载jar不对

### ISSUE THREAD

**Issue by zhao-staff-officer** [baomidou/mybatis-plus#2358]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.3.0

### 重现步骤
![图片](https://user-images.githubusercontent.com/39394934/79351922-d3cee000-7f6b-11ea-9271-35d70a50f428.png)

### 报错信息

![图片](https://user-images.githubusercontent.com/39394934/79351922-d3cee000-7f6b-11ea-9271-35d70a50f428.png)

**Comment by zhao-staff-officer** [comment]
![图片](https://user-images.githubusercontent.com/39394934/79351991-e2b59280-7f6b-11ea-8c79-48c85a7af7fa.png)

**Comment by zhao-staff-officer** [comment]
为什么只有3K?是我打开姿势不对吗

**Comment by miemieYaho** [comment]
https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-generator/3.3.0
