### ISSUE TITLE
自动生成代码时,如果库中有视图(名字为中文),乱码?

### ISSUE THREAD

**Issue by liuchangng** [baomidou/mybatis-plus#236]
###### SQL 语句 show table status; 结果会查出视图,如果视图是中文就会乱码?
解决方法: 
1. strategy.setExclude(new String[]{"视图名字"}); // 排除生成的表,还包括视图
2. /src/main/java/com/baomidou/mybatisplus/generator/config/builder/ConfigBuilder.java 第 462行加上判断  String tableComment = results.getString(querySQL.getTableComment()); 如果 tableComment  == "VIEW" 就跳过.

**Comment by qmdx** [comment]
视图不能跳过，后面考虑设置一个开关，你最好还是用英文

**Comment by qmdx** [comment]
LOOK https://gitee.com/baomidou/mybatis-plus/commit/366567ea134293669d3aa340341ce5fec2f37928
