### ISSUE TITLE
@Select foreach时 @Result 部分property没有反填回实体

### ISSUE THREAD

**Issue by nanfangstation** [baomidou/mybatis-plus#2366]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
@Select 和 @Results 注解同时使用时，部分字段没有反填到指定实体，需要重新指定 @Result 才能返回该字段

### 重现步骤
@Select("<script>select * from kaido_case where case_id in  " +
        "<foreach item='item' index='index' collection='caseIdList' open='(' separator=',' close=')'>" +
        "#{item}" +
        "</foreach> </script>")
@Results({
        // @Result(property = "caseId",column = "case_id"),  没有此行那么只有caseId这个字段无法反填回实体
        @Result(property = "generateAlarmCount", column = "case_id", javaType = Long.class,
                one = @One(select = "com.mapper.KaidoAlarmMapper.getGenerateAlarmCountByCaseId"))
})
public List<KaidoCase> getCaseWithAlarmCount(@Param("caseIdList") List<Long> caseIdList);

### 报错信息
没有此行那么只有caseId这个字段无法反填回实体
@Result(property = "caseId",column = "case_id")

**Comment by miemieYaho** [comment]
注解规则是mybatis规定的,去找mybatis
