### ISSUE TITLE
多租户ID-WHERE参数异常

### ISSUE THREAD

**Issue by TeaR7** [baomidou/mybatis-plus#2370]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1.tmp

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

开启租户，重写此方法，
public Expression getTenantId(boolean where) {
此处获取的WHERE不正确

查阅了gitee上类似issue，但是发现解决部分不全面
https://gitee.com/baomidou/mybatis-plus/issues/I1DTCL，
但是这样在没有查询条件的select语句，依然获取到错误的where值（false）

### 重现步骤
多租户的情况下，使用.list()方法，不携带任何查询参数，获取到的where为false

sql：SELECT * FROM banner
拼接租户后的sql（确实是出现在where里）
sql：SELECT * FROM banner WHERE banner.tenant_id = 'xx'

### 报错信息

无报错信息，结果和预期的不一致

**Comment by miemieYaho** [comment]
看 gitee
