### ISSUE TITLE
多租户 UPDATE 拼接异常

### ISSUE THREAD

**Issue by TeaR7** [baomidou/mybatis-plus#2371]
### 当前使用版本
3.3.1.tmp

### 该问题是怎么引起的？

多个租户ID的情况下，UPDATE语句如下
UPDATE banner SET status = ? WHERE id = ?

获得到的拼接结果为

UPDATE app_banner SET status = ?
WHERE app_banner.tenant_id = tenant_id IN ('xx', 'xx') AND id = ?

### 重现步骤

多租户，存在多个租户ID的情况下，使用baseMapper.updateById方法

### 报错信息

com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DOUBLE value:

**Comment by TeaR7** [comment]
额，是我的提交方式不对吗……

还是新版本已经考虑修正了这个问题= =

**Comment by miemieYaho** [comment]
看 gitee

**Comment by softboy99** [comment]
gitee的哪里？找不到啊
遇到同样的问题，在@async方法中updateById拼接的tenantId =0，造成更新数据失败
