### ISSUE TITLE
IPage 是否能够放到其他扩展包中

### ISSUE THREAD

**Issue by 1120076969** [baomidou/mybatis-plus#2372]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
IPage 在mybatis-plus-core中，所以使用该对象需要引入mybatis-plus-core jar，但是我不需要mybatis-plus-core jar在 api，和 client 项目中。IPage 是否能够放到其他扩展包中？

### 重现步骤
api 和 client 项目使用IPage 接口

### 报错信息
无

**Comment by miemieYaho** [comment]
换包改动较大,可能mp4才会这么做
