### ISSUE TITLE
columnNaming设置无效

### ISSUE THREAD

**Issue by hubbbbbb** [baomidou/mybatis-plus#2376]
### 当前使用版本(必须填写清楚，否则不予处理)
	<dependency>
		<groupId>com.baomidou</groupId>
		<artifactId>mybatis-plus-boot-starter</artifactId>
		<version>3.1.0</version>
	</dependency>
	<dependency>
		<groupId>com.baomidou</groupId>
		<artifactId>mybatis-plus-generator</artifactId>
		<version>3.2.0</version>
	</dependency>

### 该问题是怎么引起的？
代码生成器StrategyConfig设置strategy.setColumnNaming(NamingStrategy.underline_to_camel);无效，只能跟随setNaming。

    /**
     * 数据库表字段映射到实体的命名策略
     * <p>未指定按照 naming 执行</p>
     */
    private NamingStrategy columnNaming = null;

**Comment by nieqiurong** [comment]
#2279

**Comment by nieqiurong** [comment]
用3.3.2.1-SNAPSHOT试试，使用方式参考https://mp.baomidou.com/guide/install.html#snapshot
