### ISSUE TITLE
动态数据源配置是否能硬编码配置

### ISSUE THREAD

**Issue by wk199251248** [baomidou/mybatis-plus#2377]
spring-boot:2.2.4.RELEASE
dynamic-datasource-spring-boot-starter:3.0.0
示例给出的动态数据源配置是基于配置文件的，是否有方法能使用@Configuration硬编码方式实现，目的能通过Apollo动态修改数据源密码

**Comment by miemieYaho** [comment]
去 dynamic-datasource-spring-boot-starter 提
