### ISSUE TITLE
3.2.0及以上版本selectMapsPage等方法(返回类型是Map)驼峰转换不生效

### ISSUE THREAD

**Issue by warApePoint** [baomidou/mybatis-plus#2380]
### 3.2.0及以上版本  eg:3.2.0/ 3.3.0
涉及的接口com.baomidou.mybatisplus.core.mapper.BaseMapper
方法: selectMaps/selectMapsPage等返回类型是Map的方法
### 引起原因
IPage<Map<String, Object>> mapIPage = userService.pageMaps(new Page<>());
* 3.1.1 返回正确结果
![image](https://user-images.githubusercontent.com/32215349/79738522-7225c180-832f-11ea-8fd9-9abef3eecf09.png)

* 3.2.0 返回错误结果
![image](https://user-images.githubusercontent.com/32215349/79738314-2bd06280-832f-11ea-81cf-8da63eae5283.png)

## 其他
以上错误结果只针对返回Map形式的接口。如果返回的是对应的实体类则不会出现以上错误的问题。

**Comment by miemieYaho** [comment]
文档上有

**Comment by warApePoint** [comment]
> 文档上有

mapUnderscoreToCamelCase  是这个配置么?  不生效呀  而且默认就是true

**Comment by warApePoint** [comment]
找到了 
@Bean
public ConfigurationCustomizer configurationCustomizer() {
    return i -> i.setObjectWrapperFactory(new MybatisMapWrapperFactory());
}
