### ISSUE TITLE
v3.3.0缺少PerformanceInterceptor类

### ISSUE THREAD

**Issue by coonle** [baomidou/mybatis-plus#2381]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus-extension-3.3.1.jar
缺少以下类
import com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor;

### 报错信息
Cannot resolve symbol 'PerformanceInterceptor'

**Comment by miemieYaho** [comment]
移除了
