### ISSUE TITLE
oracle环境下，查询异常

### ISSUE THREAD

**Issue by liweiboy** [baomidou/mybatis-plus#2382]
### 当前使用版本
mybatis-plus:3.3.1，oracle版本11g；
### 重现步骤
调用api报错：sysDeptService.list(Wrappers.<SysDept>lambdaQuery().orderByAsc(SysDept::getParentIds,SysDept::getSort));
### 报错信息
java.lang.AbstractMethodError: Method oracle/jdbc/driver/OracleResultSetImpl.getObject(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; is abstract
	at oracle.jdbc.driver.OracleResultSetImpl.getObject(OracleResultSetImpl.java)
![123](https://user-images.githubusercontent.com/37232258/79849442-0d349f00-83f5-11ea-9dd1-19ee98297e16.png)

**Comment by miemieYaho** [comment]
mp不负责sql执行和数据封装,自己排查

**Comment by bandiandian** [comment]
> ### 当前使用版本
> mybatis-plus:3.3.1，oracle版本11g；
> 
> ### 重现步骤
> 调用api报错：sysDeptService.list(Wrappers.lambdaQuery().orderByAsc(SysDept::getParentIds,SysDept::getSort));
> 
> ### 报错信息
> java.lang.AbstractMethodError: Method oracle/jdbc/driver/OracleResultSetImpl.getObject(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; is abstract
> at oracle.jdbc.driver.OracleResultSetImpl.getObject(OracleResultSetImpl.java)
> ![123](https://user-images.githubusercontent.com/37232258/79849442-0d349f00-83f5-11ea-9dd1-19ee98297e16.png)

我也遇到了 解决了码

**Comment by lunxian8** [comment]
同样的问题
https://blog.csdn.net/weixin_42213903/article/details/103188639
mybatis 3.5 版本高了 这咋整
