### ISSUE TITLE
gc.setOutputDir 没有此方法了？

### ISSUE THREAD

**Issue by rbw204** [baomidou/mybatis-plus#2383]
### 当前使用版本(必填,否则不予处理)
<groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.1.tmp</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自动生成代码，文档中的全局配置的几个方法都取消了？如果取消了，用什么代替呢，文档能跟上是最好了，要不一脸懵逼。

**Comment by nieqiurong** [comment]
请注意包导入的是com.baomidou.mybatisplus.generator.config而不是com.baomidou.mybatisplus.core.config
