### ISSUE TITLE
指定数据库类型为oracle 12c时，分页报错

### ISSUE THREAD

**Issue by sangenmutou** [baomidou/mybatis-plus#2385]
### 当前使用版本(必填,否则不予处理)

3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

指定数据库类型为oracle 12c时
paginationInterceptor.setDbType(DbType.ORACLE_12C); 
调用分页出现错误
Page<Idcsysdatalog> p = new Page<>(page, limit);
IPage<Idcsysdatalog> ip = idcsysdatalogService.page(p, wrapper);

直接指定oracle，可正常使用
 paginationInterceptor.setDbType(DbType.ORACLE); 

### 报错信息

org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect FIRST, actual NEXT, pos 192, line 7, column 64, token NEXT : SELECT  
send_code,biztype,specode,operate,send_time,versions,create_time,status,send_userid
  FROM IDC_SYS_DATA_LOG 
 
  
 
  ORDER BY send_time DESC , send_code DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY 
### Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect FIRST, actual NEXT, pos 192, line 7, column 64, token NEXT : SELECT  
send_code,biztype,specode,operate,send_time,versions,create_time,status,send_userid
  FROM IDC_SYS_DATA_LOG 
 
  
 
  ORDER BY send_time DESC , send_code DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY 
; uncategorized SQLException; SQL state [null]; error code [0]; sql injection violation, syntax error: syntax error, expect FIRST, actual NEXT, pos 192, line 7, column 64, token NEXT : SELECT  
send_code,biztype,specode,operate,send_time,versions,create_time,status,send_userid
  FROM IDC_SYS_DATA_LOG 
 
  
 
  ORDER BY send_time DESC , send_code DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY ; nested exception is java.sql.SQLException: sql injection violation, syntax error: syntax error, expect FIRST, actual NEXT, pos 192, line 7, column 64, token NEXT : SELECT  
send_code,biztype,specode,operate,send_time,versions,create_time,status,send_userid
  FROM IDC_SYS_DATA_LOG 
 
  
 
  ORDER BY send_time DESC , send_code DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY

**Comment by miemieYaho** [comment]
针对不同数据库指定,如果你用的就是12c的觉得分页语句不正确可以pr

**Comment by sangenmutou** [comment]
我用的数据库是Oracle12c，不是分页语句不正确，而是我调用底层的page方法，直接就报错了，打印出来的语句：SELECT * FROM IDC_SYS_DATA_LOG
ORDER BY send_time DESC , send_code DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY,是没问题的，不知道是什么原因，
现在切换成DbType.ORACLE，可以正常使用，没有任何问题

**Comment by sangenmutou** [comment]
> 针对不同数据库指定,如果你用的就是12c的觉得分页语句不正确可以pr
我用的数据库是Oracle12c，不是分页语句不正确，而是我调用底层的page方法，直接就报错了，打印出来的语句：SELECT * FROM IDC_SYS_DATA_LOG
ORDER BY send_time DESC , send_code DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY,是没问题的，不知道是什么原因，
现在切换成DbType.ORACLE，可以正常使用，没有任何问题
