### ISSUE TITLE
TableInfo的fieldList不包含主键字段

### ISSUE THREAD

**Issue by chengjf0526** [baomidou/mybatis-plus#2386]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
因为QueryWrapper不支持RPC，所以自定义了对象，进行转换时，判断是否为表字段使用了
```
TableInfoHelper.getTableInfo(表实体类).getFieldList()
```
发现ID不在该列表中

### 重现步骤(如果有就写完整)
直接调用就可以了

### 报错信息
认定主键ID不是表字段

**Comment by miemieYaho** [comment]
不在,在tableInfo里
