### ISSUE TITLE
怎么实现表名和类名一样，不进行任何转换

### ISSUE THREAD

**Issue by wxq1990** [baomidou/mybatis-plus#2388]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我数据库是区分大小写的，表名设计是驼峰设计（比如Dict），mp生成的sql表名是小写的（dict），
查询报表找不到，我也没找到配置来实现表名和类名一样，
请问该怎么做实现

**Comment by nieqiurong** [comment]
```java
new StrategyConfig().setNaming(NamingStrategy.no_change); 
```

**Comment by wxq1990** [comment]
这个是在用代码生成器的配置 ，我说的是调用查询接口时 根据实体类生成的sql  中from 的表名不进行转换

**Comment by miemieYaho** [comment]
不支持,@tableName注解指定

**Comment by kangjianwei** [comment]
我也正在烦恼这个问题，作者好像一直没解决
