### ISSUE TITLE
查询语句不对

### ISSUE THREAD

**Issue by newbirdking** [baomidou/mybatis-plus#2390]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查询语句不对

### 重现步骤(如果有就写完整)

QueryWrapper<Student> queryWrapper = new QueryWrapper<>(student);
		queryWrapper.lambda().or().like(Student::getParentId, "111");
		list(queryWrapper);

SELECT id, parent_id
 FROM student
 WHERE id = '111' AND del_flag = '0' AND parent_id LIKE '%111%';

明明用的lambda().or()可是语句出来的确是and而非指定的or??
### 报错信息
没有报错信息,只是查询语句不是想要的数据

**Comment by miemieYaho** [comment]
wrapper里的entity和外部的没有关联关系

**Comment by newbirdking** [comment]
其实也是一个entity,只是有得情况下需要or (entity中的某个值)来,这种形式不支持?

**Comment by miemieYaho** [comment]
不支持
