### ISSUE TITLE
用mybatis plus中关于update的方法里面使用redis缓存操作失效（set delete失效）

### ISSUE THREAD

**Issue by allhuo** [baomidou/mybatis-plus#2391]
### 具体代码
        if (cpwAuctioneerService.updateById(cpwAuctioneer)){
            //删除用户令牌缓存
            redisTemplate.delete(RedisKeyConstant.CPW_JWT_TOKEN + RoleConstant.ROLE_AUCTIONEER + ":" + cpwAuctioneer.getUsername());
            return Result.ok("密码修改成功 请重新登录");
        }
其中delete 缓存不执行，但是拿出来放到updateById外面可以执行成功

**Comment by miemieYaho** [comment]
你这代码不就是update没成功嘛

**Comment by allhuo** [comment]
我打断点update成功了，数据库信息也修改了，代码也执行到了删除缓存那一行，但是发现缓存里面依然没删，我已经试过多次了，都是这样。

**Comment by miemieYaho** [comment]
那就是你代码问题了,自己排查
