### ISSUE TITLE
QueryWrapper是否会引入运行期额外性能损耗？

### ISSUE THREAD

**Issue by fzyzcjy** [baomidou/mybatis-plus#2392]
### 当前使用版本(必填,否则不予处理)
latest

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
你好，`QueryWrapper`是否会引入额外性能损耗？（官网好像有说BaseMapper.selectById这一类是启动时注入，所以不会有运行期间的损耗，但不太确定QueryWrapper是否会有）

谢谢！

### 重现步骤(如果有就写完整)
N/A

### 报错信息
N/A

**Comment by miemieYaho** [comment]
有的，追求性能的地方应该使用自己写xml

**Comment by fzyzcjy** [comment]
@miemieYaho 谢谢！
