### ISSUE TITLE
数据源采用ShardingJDBC管理之后，MetaObjectHandler.updateFill和MetaObjectHandler.insertFill都不在起作用

### ISSUE THREAD

**Issue by yc825106632** [baomidou/mybatis-plus#2398]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据源采用ShardingJDBC管理之后，MetaObjectHandler.updateFill和MetaObjectHandler.insertFill都不在起作用

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/21304095/80187073-9b04ca00-8641-11ea-9634-8925f73d53ca.png)

![image](https://user-images.githubusercontent.com/21304095/80187086-a0621480-8641-11ea-9d0d-6889e3cbf3ad.png)

### 报错信息
没有任何报错信息，生气了语句正常执行，只是需要填充的字段还是空
Execute SQL：INSERT INTO hos_basic ( name, code, remark, create_user, create_time, update_user, update_time ) VALUES ('基础字段', '', '基础字段', NULL, NULL, NULL, NULL)

**Comment by miemieYaho** [comment]
自己排查

**Comment by yc825106632** [comment]
我应该从哪开始排查，找了半天也没有找到入口，根本就不进入这个字段填充的类

**Comment by miemieYaho** [comment]
你自己构建sqlsessionfactory了?

**Comment by yc825106632** [comment]
没有啊
![image](https://user-images.githubusercontent.com/21304095/80188184-6265f000-8643-11ea-9a4e-a75e5f277861.png)

**Comment by miemieYaho** [comment]
`MybatisPlusAutoConfiguration`点开启动debug看
```java
// TODO 注入填充器
this.getBeanThen(MetaObjectHandler.class, globalConfig::setMetaObjectHandler);
```
有没有注入

**Comment by yc825106632** [comment]
![image](https://user-images.githubusercontent.com/21304095/80192853-65b0aa00-864a-11ea-93ae-071265ad5fc5.png)
找到问题了，在这个地方ShardingJDBC构建sqlsessionfactory了，只是我应该怎么重新注入MetaObjectHandler

**Comment by miemieYaho** [comment]
这是你们自己写的吧,自己写的就参考 MybatisPlusAutoConfiguration 改

**Comment by yc825106632** [comment]
明白了，谢谢
