### ISSUE TITLE
请问新版本热加载功能什么会加回

### ISSUE THREAD

**Issue by 2720851545** [baomidou/mybatis-plus#2400]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
贵框架官网显示热加载功能3.0.6移除了热加载, 在google中查找了一圈没有发现能用的动态加载maper实现方法, 请问您们有什么方式能短暂的实现动态加载功能, 或在什么版本中会加回该功能, 
没有该功能我们感觉开发效率大打折扣

谢谢贵框架开发者开发的该框架

**Comment by miemieYaho** [comment]
不会加回，重启大法
