### ISSUE TITLE
mybtis plus非标准insert 如何提前获取雪花算法值？

### ISSUE THREAD

**Issue by liquanjin** [baomidou/mybatis-plus#2401]
### 当前使用版本(必填,否则不予处理)
3.2.0 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
不能算是问题，只是咨询下。非标准的insert 语句，是否可以通过某种方式获取到mybatis plus 生成的雪花算法值？
比如：insert table_a(name,sex) select name_b, sex_b from  table_b;

既然已经使用了mybatis plus 的雪花算法值，当然所有的id 都要使用同一个算法才是最合适的。

特此咨询，感谢

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
```java
Idworker.getId
```

**Comment by liquanjin** [comment]
十分感谢：）
