### ISSUE TITLE
字段自动填充功能的疑惑

### ISSUE THREAD

**Issue by MSObito** [baomidou/mybatis-plus#2402]
### 当前使用版本(必填,否则不予处理)

3.0.7.1

### 该问题是如何引起的？
想要咨询一下，如果配置了字段自动填充功能，那么无论是调用mybatis-plus提供的mapper更新接口，还是自己手写的sql，代码都会经过字段自动填充，是吗？如果是的话，该怎样使手写的sql绕过字段自动填充功能。

**Comment by miemieYaho** [comment]
绕不过去

**Comment by miozus** [comment]
绕过mybaitsplus的逻辑删除

https://blog.csdn.net/qq_37990736/article/details/118030617

还有一种绕过方法是 XML 手写SQL
