### ISSUE TITLE
关于bean中@TableField注解的疑问

### ISSUE THREAD

**Issue by yc825106632** [baomidou/mybatis-plus#2407]
### 当前使用版本(必填,否则不予处理)
3.3.1

没有遇到报错和问题，来问下bean中@TableField注解添加和不添加有没有性能上的影响，官方推荐加上注解还是不推荐加上注解？
![image](https://user-images.githubusercontent.com/21304095/80327011-3c239880-886d-11ea-89df-c420384e1c73.png)

**Comment by yc825106632** [comment]
![image](https://user-images.githubusercontent.com/21304095/80327099-8442bb00-886d-11ea-9b7a-08f0f6ef0410.png)

**Comment by miemieYaho** [comment]
没影响，你喜欢满屏注解就加不喜欢满屏注解就不加
