### ISSUE TITLE
条件构造抽象类Wrapper能否实现克隆接口

### ISSUE THREAD

**Issue by hepengju** [baomidou/mybatis-plus#241]
项目中多个校验条件共享一些SQL片段, 仅仅有一个字段的不同. 如果Wrapper可以克隆, 可以很大的简化代码.

目前使用Apache common langs的方法:
```
Wrapper<Z010User> wrapper = new EntityWrapper<Z010User>().ne(Objects.nonNull(id), "id", id).eq("del_flag", "1");
Wrapper clone01 = SerializationUtils.clone(wrapper);
```

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/ee3e1ae0973e354711350d84f62004f1be834055
