### ISSUE TITLE
service的listByIds传数字字符串报错

### ISSUE THREAD

**Issue by ShallowBreeze** [baomidou/mybatis-plus#2415]
### 当前使用版本(必填,否则不予处理)
3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用service.listByIds(ids)方法查询，id字段为String类型，ids里面包含000这种纯数字字符串，执行查询报错。

### 报错信息
无效的列类型

**Comment by miemieYaho** [comment]
你mapper自己写个 listByIds 看看报不报错

**Comment by qmdx** [comment]
请给出错误
