### ISSUE TITLE
模糊查询 特殊字符

### ISSUE THREAD

**Issue by aslimao** [baomidou/mybatis-plus#2416]
### 当前使用版本(必填,否则不予处理)

v3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

like() 查询   _ % ' \ 等特殊字符 查询出全部数据 而不是包含这些字符的数据

### 重现步骤(如果有就写完整)
wapper.like("字段", "_");
list(wapper);

### 报错信息

无

**Comment by miemieYaho** [comment]
自己做处理

**Comment by Long-Liu** [comment]
这个应该要转义下

**Comment by aslimao** [comment]
我知道要转义，但既然有模糊查询是不是底层处理一下比较好，提个意见而已
