### ISSUE TITLE
无法打印sql日志(不使用p6spy,输出mybatis自身日志)

### ISSUE THREAD

**Issue by ilyq013** [baomidou/mybatis-plus#2420]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
配置文件加了mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

是否是引入plus问题

**Comment by nieqiurong** [comment]
```
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
```

**Comment by qmdx** [comment]
up

**Comment by hh1202** [comment]
配置：
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

打印日志：
Creating a new SqlSession
Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5308958a]
JDBC Connection [HikariProxyConnection@35668170 wrapping org.postgresql.jdbc.PgConnection@f090767] will be managed by Spring
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5308958a]
Transaction synchronization committing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5308958a]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5308958a]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5308958a]

**Comment by wi1wei** [comment]
> ```
> mybatis-plus:
>   configuration:
>     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
> ```

请问如何在日志文件里面也有sql，这个配置只在控制台有sql
