### ISSUE TITLE
插入多张表时，发生异常，之前数据未回滚

### ISSUE THREAD

**Issue by just1cm** [baomidou/mybatis-plus#2421]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在service层使用事务时，在一个方法中对多个表进行插入，其中最后一个表插入失败，但是之前插入的数据未回滚

### 重现步骤(如果有就写完整)
service中对多个表进行插入，最后一个插入失败，数据库未回滚，数据库使用的mysql

### 报错信息
目前分析下来，原生mybatis在进行数据库操作时会先set autoCommit=0 而mybatis-plus使用的是自动提交事务。

**Comment by miemieYaho** [comment]
事务和mp没关系,自己排查
