### ISSUE TITLE
多数据源的情况分页插件加入官方不支持的数据库类型

### ISSUE THREAD

**Issue by hyanqing1** [baomidou/mybatis-plus#2422]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter：3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
现在我们公司引入神通数据库，在多数据源的情况下，比如一部分数据在mysql、一部分表在神通数据库，分页插件会抛出不支持异常。查看源代码分页插件中是从JdbcUtils和DbType中动态获取的，没发现自定义DBType加入到官方的枚举当中。

### 报错信息
数据源不支持

**Comment by miemieYaho** [comment]
不支持的只能pr
