### ISSUE TITLE
新旧版本兼容问题

### ISSUE THREAD

**Issue by fatpander** [baomidou/mybatis-plus#2424]
### 当前使用版本(必填,否则不予处理)

mybatis plus 3.3.1， 旧版 mybatis 2.1.gmma

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

旧版本的addFilter 和 selectList等api在新版中直接被废弃了，导致旧的项目想要升级mybatisplus都非常麻烦，改动很大，这样对我们企业级用户非常的不友好，企业要的是稳定，不能升级以后新功能又使用不了，非常纠结，希望这一块能引起作者的重视。众多语音的orm都有非常简洁的方案，mybatis插件中，mybatis plus是非常不错的。望作者继续努力

### 重现步骤(如果有就写完整)

service.selectList(new EntityWrapper<User>().addFilter("stat= 1") ) 旧版api，在新版无法使用，望作者打个补丁，让兼容旧版api

### 报错信息

方法不存在

**Comment by miemieYaho** [comment]
新旧版改动较大,无法兼容
