### ISSUE TITLE
CachePaginationInterceptor 无法引入

### ISSUE THREAD

**Issue by 1263080327** [baomidou/mybatis-plus#2431]
### 当前使用版本(必填,否则不予处理)
3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
整合redis作为二级缓存时，分页查询缓存异常，查看官方文档说明：建议缓存放到 service 层，当然如果你是一个极端分子，请使用 CachePaginationInterceptor 替换默认分页，这样支持分页缓存，坚持将二级缓存放在mapper的情况下，实际未发现CachePaginationInterceptor 这个类，无法引入

**Comment by qmdx** [comment]
这是 MP  2.X 的解决方案（不太理想） 3X 不再提供，建议自己在 service 缓存方法注解去解决

**Comment by jiangxingyou** [comment]
怎么解决呀, 老哥

**Comment by Andionion** [comment]
建议自己在 service 缓存方法注解去解决
这是什么意思啊，能再清楚点吗？不好查呀
