### ISSUE TITLE
多租户自定义sql分页查询及Count问题

### ISSUE THREAD

**Issue by linkangsheng** [baomidou/mybatis-plus#2432]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 重现步骤(如果有就写完整)
1.自定义SQL如下
![图片](https://user-images.githubusercontent.com/18477709/81142390-29fad600-8fa2-11ea-9d5c-dd73005e14d2.png)
多租户条件是手动传递进去的，但MybatsiPlus进行count的时候自动的把多租户条件加上去了，而且 boolean where 是false。
![图片](https://user-images.githubusercontent.com/18477709/81142557-8cec6d00-8fa2-11ea-9d01-ef3e2a8b1a57.png)

所以想问下这种情况是自己手动分页，然后自己手动写查询汇总sql么？

**Comment by miemieYaho** [comment]
不走租户插件就method上加注解过滤掉

**Comment by linkangsheng** [comment]
> 
> 
> 不走租户插件就method上加注解过滤掉



> 
> 
> 不走租户插件就method上加注解过滤掉



> 
> 
> 不走租户插件就method上加注解过滤掉
@miemieYaho 好的，知道了，一开始我以为自定义sql不会自动加上租户条件，刚刚研究了下发现会，谢谢
