### ISSUE TITLE
希望json相关的TypeHandler可以支持对PostgreSQL中jsonb字段类型的支持

### ISSUE THREAD

**Issue by linghuanxu** [baomidou/mybatis-plus#2436]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我使用的数据库是PostgreSQL 10.5，其支持jsonb类型的字段。这个类型是可以进行关联查询和设立索引的。
我尝试使用JacksonTypeHandler之后，提示我插入的类型是varchar。后来我查看了其中的代码，其中假设了总是使用String类型来处理。这样的话就，使用json的意义就只变成了方便序列化和反序列化对象和字段之间的映射。
事实上Mysql在5.7开始也增加了对json的支持。还是希望可以以一种优雅的方式来解决这种问题。

### 报错信息

2020-05-06 18:37:25.368 [http-nio-9998-exec-1] ERROR c.y.f.m.s.s.service.GlobalDefaultExceptionHandler - org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: 错误: 字段 "config" 的类型为 jsonb, 但表达式的类型为 character varying
  建议：你需要重写或转换表达式
  位置：96
### Cause: org.postgresql.util.PSQLException: 错误: 字段 "config" 的类型为 jsonb, 但表达式的类型为 character varying
  建议：你需要重写或转换表达式
  位置：96
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: 错误: 字段 "config" 的类型为 jsonb, 但表达式的类型为 character varying
  建议：你需要重写或转换表达式
  位置：96
2020-05-06 18:37:25.369 [http-nio-9998-exec-1] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Resolved exception caused by Handler execution: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: 错误: 字段 "config" 的类型为 jsonb, 但表达式的类型为 character varying
  建议：你需要重写或转换表达式
  位置：96
### Cause: org.postgresql.util.PSQLException: 错误: 字段 "config" 的类型为 jsonb, 但表达式的类型为 character varying
  建议：你需要重写或转换表达式
  位置：96
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: 错误: 字段 "config" 的类型为 jsonb, 但表达式的类型为 character varying
  建议：你需要重写或转换表达式
  位置：96

**Comment by miemieYaho** [comment]
不支持定制，这是全数据库通用的

**Comment by linghuanxu** [comment]
我并不是说要对PostgreSQL进行定制，而是让json这种数据结构的支持更加准确一些，这样人们在关系型数据库中对json这种数据结构的看法就会产生变化。事实上，从各大数据库的新版本来看，json成为关系型数据库的标准数据类型已经很近了。

**Comment by linghuanxu** [comment]
事实上这个TypeHandler我已经实现了，只是class实例引入的方向很恶心，让总线看看有没有更优雅的实现方式罢了。

**Comment by linghuanxu** [comment]
顺便说，autoResultMap很好用

**Comment by miemieYaho** [comment]
通用的需要jdbc进行支持

**Comment by linghuanxu** [comment]
我明白数据库适配是个不符合Mybatis plus定位的工作。而我的实现也用到了PG自己的库，mybatis的jdbc枚举里没有json。但，我想，如果只实现一两个有兴趣实现的数据库适配，更多的是把适配的接口流出来让使用者自己实现就可以了。
我刚才有细看了下AbstractJsonTypeHandler和它的子类，明天我试试自己写AbstractJsonTypeHandler的子类能不能跑通吧，能正常工作的话。我的问题就很好的解决了。

**Comment by hong4cong** [comment]
> 我明白数据库适配是个不符合Mybatis plus定位的工作。而我的实现也用到了PG自己的库，mybatis的jdbc枚举里没有json。但，我想，如果只实现一两个有兴趣实现的数据库适配，更多的是把适配的接口流出来让使用者自己实现就可以了。 我刚才有细看了下AbstractJsonTypeHandler和它的子类，明天我试试自己写AbstractJsonTypeHandler的子类能不能跑通吧，能正常工作的话。我的问题就很好的解决了。

@linghuanxu 解决了吗？

**Comment by aboutZZ** [comment]
[可在SQL语句中强转类型为`json`或`jsonb`](https://stackoverflow.com/a/62774773/5357696), 我想这个应该是能实现的，看作者愿不愿意改了
例如：
```SQL
INSERT INTO room_categories (name, code, metadata) VALUES (?, ?, ? ::jsonb )
```

**Comment by baklpc** [comment]
public class JsonbTypeHandler extends Jackson3TypeHandler {

    public JsonbTypeHandler(Class<?> type) {
        super(type);
    }

    // 自3.5.6版本开始支持泛型,需要加上此构造.
    public JsonbTypeHandler(Class<?> type, Field field) {
        super(type, field);
    }

    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, Object parameter, JdbcType jdbcType)
            throws SQLException {
        var jsonbObject = new PGobject();
        jsonbObject.setType("jsonb");
        jsonbObject.setValue(toJson(parameter));
        ps.setObject(i, jsonbObject);
    }

}

**Comment by sophiebob** [comment]
jdbcurl添加stringtype=unspecified

**Comment by sophiebob** [comment]
自定义PostgresJsonbTypeHandler比jdbcurl添加stringtype=unspecified好些
