### ISSUE TITLE
受影响行数的问题

### ISSUE THREAD

**Issue by ladixiu** [baomidou/mybatis-plus#2437]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
根据id更新一条数据，当数据没有更改时，更新语句返回的是0

### 报错信息
无

我之前的项目使用的是2.1.9，是能正常返回的，不管数据有没有改动，执行成功都会返回1

**Comment by miemieYaho** [comment]
返回1还是0那是mybatis的事

**Comment by ladixiu** [comment]
找到原因了，mybatis做了处理，正常情况下返回的是两者的综合，如果jdbc连接字符串，添加了useAffectedRows=true，表示采用数据库返回的值，mysql数据库对应未做更改的update语句，做了优化，不去更新数据，所以返回的是0，如果要使用mybatis的更新值，连接字符串去掉useAffectedRows=true，就可以了
