### ISSUE TITLE
3.3.1生成代码后，在controller注入service失败

### ISSUE THREAD

**Issue by wsxGit** [baomidou/mybatis-plus#2441]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.3.1
mybatis-plus-generator 3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
生成代码之后，在controller注入service失败

### 重现步骤(如果有就写完整)
引入依赖
```
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>2.0</version>
        </dependency>
```

生成代码
service代码

```
public interface IUserService extends IService<User> {

}
```

serviceImpl代码

```
@Service
public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements IUserService {

}
```

controller代码

```
@RestController
@RequestMapping("/sys/user")
@RequiredArgsConstructor
public class UserController {

    private final IUserService service;
}
```

启动时报错
### 报错信息
Parameter 0 of constructor in com.jnh.web.bussiness.sys.controller.UserController required a single bean, but 2 were found:
	- UserServiceImpl: defined in file [D:\Project\yzgt\web\target\classes\com\jnh\web\bussiness\sys\service\impl\UserServiceImpl.class]
	- IUserService: defined in file [D:\Project\yzgt\web\target\classes\com\jnh\web\bussiness\sys\service\IUserService.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Comment by miemieYaho** [comment]
升级spring boot 版本

**Comment by qmdx** [comment]
u'pup

**Comment by iLinuxs** [comment]
> 升级spring boot 版本

为什么我更新到2.3.0.RELEASE 还是不行
`<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.1</version>
        </dependency>`
