### ISSUE TITLE
3.3.0  ASSIGN_ID模式无法生成ID

### ISSUE THREAD

**Issue by FORyc** [baomidou/mybatis-plus#2442]
### 当前使用版本(必填,否则不予处理)
mp的版本为3.3.0
java version 为 openjdk version "1.8.0_232"

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类
![image](https://user-images.githubusercontent.com/36726775/81304158-42a4e200-90af-11ea-9037-c95aaef4ccc5.png)
使用接口工具模拟用户注册
![image](https://user-images.githubusercontent.com/36726775/81304698-f8703080-90af-11ea-8346-42c6075f17aa.png)
可以看到这里id并没有根据生成策略生成，不知道是什么原因

数据库为MySQL 8.0.19     
相应表的字段类型为bigint， 非空，非自增

### 报错信息
数据能成功入库，除ID为0之外，没有其他异常信息

**Comment by miemieYaho** [comment]
0是你自己set的吧

**Comment by FORyc** [comment]
谢谢，问题找到了，经过你的提醒我检查了一下请求体，确实是swagger的默认请求体内给ID赋了初始值，删除初始值后ID成功生成
