### ISSUE TITLE
分页条件查询wrapper设置string类型的查询条件时无效

### ISSUE THREAD

**Issue by youngerboye** [baomidou/mybatis-plus#2446]
### 当前使用版本(必填,否则不予处理)
3.0.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在3.05版本中用分页条件查询时传入string查询条件，查询无结果

### 重现步骤(如果有就写完整)
   /**
     * 条件查询带参数
     */
    @PostMapping("page/{current}/{size}")
    public ResponseResult pageCondition(@PathVariable Long current, @PathVariable Long size, @RequestBody(required = false) TeachQuery teachQuery) {

        LambdaQueryWrapper<EduTeacher> wrapper = new LambdaQueryWrapper<EduTeacher>()
                .like(StringUtils.isNotBlank(teachQuery.getName()), EduTeacher::getName, teachQuery.getName())
                .eq(teachQuery.getLevel() != null, EduTeacher::getLevel, teachQuery.getLevel());
        Page<EduTeacher> page  = new Page<>(current, size);
        IPage<EduTeacher> iPage = eduTeacherService.page(page, wrapper);
        return ResponseResult.success().data(iPage);
    }

这是TeachQuery的VO对象
@Data
public class TeachQuery {

    private String name;

    private Integer level;

    private String begin;

    private String end;
}

这是数据表（edu_teacher）数据
id                                     name
1	                                张三
1189389726308478977	晴天
1189390295668469762	李刚
1189426437876985857	王二
1189426464967995393	王五
1192249914833055746	李四
554446655	杨某某
### 报错信息
用swagger测试，
当输入
current:1,
 size:10 ,
teachQuery:{
  "name": "张"
}
点击tryout发现结果集为空。
但是输入
current:1,
 size:10 ,
teachQuery:{
   "level": 1
}
结果集正确，可以帮忙解决吗？

**Comment by youngerboye** [comment]
当前使用springboot版本为2.2.1

**Comment by miemieYaho** [comment]
自己排查

**Comment by tuwenjiex** [comment]
可以把条件写在外面
Example:
        if (null != id && !id.equals("")) {
            wrapper.eq("id", id );
        }

**Comment by xuxingman** [comment]
你好，这个问题解决了吗
