### ISSUE TITLE
逻辑删除无法满足更新`updateBy修改人`，`updateTime修改时间` 字段

### ISSUE THREAD

**Issue by purgeyao** [baomidou/mybatis-plus#2447]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用下面配置：
```
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
```
开启逻辑删除。

一般情况数据库都是有 `updateBy修改人`，`updateTime修改时间` 字段。
使用 `ServiceImpl#remove` 方法只具备 把 `deleted` 更新为已删除。

那么一个删除方法需要执行两条sql 先更新id为1的`updateBy修改人`，`updateTime修改时间` 字段。
在调用`ServiceImpl#remove`  把 `deleted` 更新为已删除。

在不使用逻辑删除  我们只需要使用一个update方法 把`updateBy修改人`，`updateTime修改时间``deleted` 字段更新下。

是否考虑下`updateBy修改人`，`updateTime修改时间`两个字段   让remove执行一条sql即可。

市面上在设计表基本都有修改人和更新时间字段。

**Comment by miemieYaho** [comment]
文档上有
