### ISSUE TITLE
Service层调用BaseMapper的insert方法和mybatis自定义插件执行顺序问题

### ISSUE THREAD

**Issue by 472405746** [baomidou/mybatis-plus#2448]
**### 当前使用版本(必填,否则不予处理)**
    
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>3.0.7.1</version>
            <scope>compile</scope>
        </dependency>
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
**场景**：自己写了一个对象公共字段赋值的mybatis插件：拦截prepare方法，入口：StatementHandler.class，
将拦截到的对象动态字段createTime,updateTime赋值，

**问题**：在service层调用调用BaseMapper的insert方法后，数据对应createTime,updateTime还是null，也就是说mybatis插件里给实体赋值没有生效。

**可能的原因**：在service层调用BaseMapper的insert在插件拦截之前已经执行了，请问这个如何处理尼？感谢！

**Comment by 472405746** [comment]
看错了

**Comment by 472405746** [comment]
![QQ截图20200509221311](https://user-images.githubusercontent.com/3732883/81476105-85e38a00-9242-11ea-931c-00ff209a5220.png)

**Comment by miemieYaho** [comment]
自己排查吧,ognl走完了才会走插件
