### ISSUE TITLE
程序包com.baomidou.dynamic.datasource.annotation不存在

### ISSUE THREAD

**Issue by githubzsy** [baomidou/mybatis-plus#2449]
### 当前使用版本(必填,否则不予处理)
spring boot 2.2.6
mybatis-plus 3.3.1
dynamic-datasource-spring-boot-starter 3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
就是编译不过，但是代码没有红线提示，不知道是不是版本兼容问题

### 报错信息
Error:(3, 50) java: 程序包com.baomidou.dynamic.datasource.annotation不存在
Error:(19, 2) java: 找不到符号
  符号: 类 DS

**Comment by miemieYaho** [comment]
去 dynamic-datasource-spring-boot-starter 提
