### ISSUE TITLE
逻辑删除 在插入的时候该字段没有默认值

### ISSUE THREAD

**Issue by damozhiying** [baomidou/mybatis-plus#245]
逻辑删除字段在插入的时候该字段没有默认值，已经配置了
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

**Comment by qmdx** [comment]
数据库默认值需要你在数据库上自己设置，更多了解下逻辑删除原理。
