### ISSUE TITLE
MP 3.3.0版本如何使用数据库时间

### ISSUE THREAD

**Issue by literatureandyou** [baomidou/mybatis-plus#2450]
### 当前使用版本(必填,否则不予处理)
3.3.0
MP在插入和更新操作室如何使用数据库时间，望回复，谢谢。

**Comment by miemieYaho** [comment]
insert不行但你可以数据库设置字段默认值,update可以字段上注解.update使用函数前提是字段符合校验规则能ognl后放行(默认需要字段有值)或者updatewrapper.setsql设置

**Comment by literatureandyou** [comment]
收到，谢谢您的回复，顺便请问下个版本这点功能会加入么？

**Comment by miemieYaho** [comment]
不会
