### ISSUE TITLE
更新时自动填充,自动填充的字段设置了值,自动填充的sql却设置了null

### ISSUE THREAD

**Issue by thinsstar** [baomidou/mybatis-plus#2452]
### 当前使用版本(必填,否则不予处理)

3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

设置自动填充属性,但在update时设置了setSql,最后的sql却还是有设置该属性为null的片段
按理说应该只有setSql的片段

### 重现步骤(如果有就写完整)

对象中设置了自动填充字段
@TableField(value = "last_operator_name", fill = FieldFill.INSERT_UPDATE)
    @ApiModelProperty(value = "最后操作人名称")
    private String lastOperatorName;

更新时使用setSql进行设置,原意是保持原纪录的lastOperatorName字段
couponInfoMapper.update(update, new UpdateWrapper<CouponInfo>()
                    .setSql("last_operator_name = last_operator_name")
                    .lambda()
                    .eq(CouponInfo::getId, param.getId())
            );

sql确实如下
UPDATE coupon_info SET receive_count = 2, last_update_time = '2020-05-11T12:00:00.095+0800', last_operator_name = NULL, last_operator_name = last_operator_name WHERE  is_delete = 0 AND (id = xx)

设置了两次last_operator_name

### 报错信息

无

**Comment by miemieYaho** [comment]
entity和UpdateWrapper里的条件不互联,用了填充就按要求用填充来set值
