### ISSUE TITLE
嵌套循环与数据量大在写数据过程中速度慢，请问有没有好的意见和建议

### ISSUE THREAD

**Issue by wxyyfcto** [baomidou/mybatis-plus#2455]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我现在从外部mdb数据库导入数据，A表和B表关联，先查询并写入A表的一条数据，然后B表里面会有60条数据和A表关联，每一次都是用A表的主键去B表里面查询到数据，然后写入mysql。目前速度用户接受不了，，请问一下有没有好的建议或意见

### 重现步骤(如果有就写完整)
我现在从外部mdb数据库导入数据，A表和B表关联，先查询并写入A表的一条数据，然后B表里面会有60条数据和A表关联，每一次都是用A表的主键去B表里面查询到数据，然后写入mysql。目前速度用户接受不了，，请问一下有没有好的建议或意见

### 报错信息
无报错，性能提升

**Comment by qmdx** [comment]
可以考虑用数据库的一些特性去解决， 存储过程，触发器 等。
