### ISSUE TITLE
批量插入方法的建议

### ISSUE THREAD

**Issue by Andy-Wang0301** [baomidou/mybatis-plus#2456]
### 当前使用版本
3.1.2

### 使用建议
是否可以把批量插入的方法改成insert into values 的方式， for循环一次次单独insert的方式有效率上的缺陷

**Comment by miemieYaho** [comment]
看文档

**Comment by greydesolate** [comment]
> ### 当前使用版本
> 3.1.2
> 
> ### 使用建议
> 是否可以把批量插入的方法改成insert into values 的方式， for循环一次次单独insert的方式有效率上的缺陷

https://mp.baomidou.com/guide/faq.html#%E5%9C%A8-wrapper-%E4%B8%AD%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-limit-%E9%99%90%E5%88%B6-sql

**Comment by greydesolate** [comment]
怕内存泄露连接超时理由明白了.个人感觉还是需要insert values方法,因为提出这个需求的,都是关心性能问题了才提出的.

但是感觉还是提供values方式比较好.毕竟性能还是比单条性能更好.
如果担心内存溢出导出JDBC超时,那是程序员自己需要解决的问题了.到时候开发人员自己可以调整批次数量大小来降低jdbc超时.

提供高性能但有风险的方法,有何不可.用不用,用的好不好在于开发人员的责任了.
毕竟简单一个String无限++也会溢出.
