### ISSUE TITLE
关于mybatisplus多数据源问题

### ISSUE THREAD

**Issue by iPopular89** [baomidou/mybatis-plus#2459]
### 当前使用版本(必填,否则不予处理)
3.0.5版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
https://mp.baomidou.com/guide/dynamic-datasource.html
配置了注解方式的多数据源，然后在service中我需要查询多个数据源的数据，查询方法不加事务注解，会出现will not be managed by Spring。加了事务注解的话，会出现数据源无法切换，会统一以默认的primary的数据源去查询所有的库，多数据源切换不生效.....

### 重现步骤(如果有就写完整)
service(){
   aMapper.aa();
   bMapper.bb();
}

@DS("A")
AMapper

@DS("B")
BMapper

### 报错信息
不加事务注解报的是
was not registered for synchronization because synchronization is not active
will not be managed by Spring

加事务注解的是
org.springframework.jdbc.BadSqlGrammarException:

**Comment by miemieYaho** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter

**Comment by iPopular89** [comment]
> https://github.com/baomidou/dynamic-datasource-spring-boot-starter

是要用这种方式来操作多数据源吗，之前官网的注解方式不推荐是吗
https://mp.baomidou.com/guide/dynamic-datasource.html

**Comment by iPopular89** [comment]
> https://github.com/baomidou/dynamic-datasource-spring-boot-starter

你发这个是做什么....好像没有解决我的问题...
