### ISSUE TITLE
使用非常规数据库引起的分页排序问题

### ISSUE THREAD

**Issue by dimples822** [baomidou/mybatis-plus#2460]
### 当前使用版本
        
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>
        

### 问题

我在使用一款非常规数据库，在使用mybatis-plus的分页插件时，我重写了IDialect如下图：

![image](https://user-images.githubusercontent.com/34737419/81702112-74e28500-949d-11ea-97f5-521a21d389e8.png)
      
但是在我分页时，使用page..addOrder()方法后，该分页会报错,是由于Page添加的 ORDER BY 语句是在上图中的 originalSql 变量末尾引起的，请问如何能使 该ORDER BY 语句在上图的 String sql 变量末尾，或者我该如何去自定义扩展它。

**Comment by miemieYaho** [comment]
目前无解,规避使用page.addOrder()吧

**Comment by dimples822** [comment]
那我是否能够扩展某个类，或者自定义切入点去生成相关的分页sql，如果可以，望能告知相关的类，谢谢！



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miemieYaho"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 中午11:53
收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;"仲永键"<1126834403@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 使用非常规数据库引起的分页排序问题 (#2460)





 
目前无解,规避使用page.addOrder()吧

**Comment by miemieYaho** [comment]
没有,建议你自己写个分页插件

**Comment by dimples822** [comment]
好的，谢谢了






仲永健
开发工程师
东华软件股份公司


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miemieYaho"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 中午12:44
收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;"仲永键"<1126834403@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 使用非常规数据库引起的分页排序问题 (#2460)





 
没有,建议你自己写个分页插件
