### ISSUE TITLE
为什么新版本去掉了XML热加载功能

### ISSUE THREAD

**Issue by kangyz** [baomidou/mybatis-plus#2461]
### 当前使用版本(必填,否则不予处理)

为什么新版本去掉了XML热加载功能

**Comment by miemieYaho** [comment]
不为什么

**Comment by kangyz** [comment]
> 不为什么

好牛逼的样子，不想答还做什么社区分享

**Comment by qmdx** [comment]
> > 不为什么
> 
> 好牛逼的样子，不想答还做什么社区分享

因为不太稳定建议用 JRebel
