### ISSUE TITLE
v2.3 BuilderException

### ISSUE THREAD

**Issue by yanxp1227** [baomidou/mybatis-plus#2463]
BuilderException: Error evaluating expression 'et.type_!=null'
实体类：
@TableField(value = "type_")
private String type_;//字典详情类型
省略getter/setter方法

只有这个字段映射不上

**Comment by yanxp1227** [comment]
v2.0.3正常使用，升级到v2.3报BuilderException

**Comment by qmdx** [comment]
2x 已经不在维护了，请修改表字段命名方式解决
