### ISSUE TITLE
[优化建议]   @tableLogic 使用问题

### ISSUE THREAD

**Issue by Higanbana0729** [baomidou/mybatis-plus#2465]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
配置了@tableLogic之后
我大致瞄了源码  查询语句都会拼上逻辑未删除值  
即使我在queryWapper里拼接上相关的逻辑字段值 还是如此

是否考虑先对eq里的查询属性进行判断 如果 包含逻辑属性  则以使用者写的为准

### 重现步骤(如果有就写完整)
例如：
    // 配置是 0为逻辑未删除值  2为逻辑删除值
   @TableLogic
    private Integer status;
    
    queryWrapper.eq("status", 2);
    
    查询的sql会变成 where status =2 and status = 0;

**Comment by miemieYaho** [comment]
不支持
