### ISSUE TITLE
请问如何获取所有的SQL语句

### ISSUE THREAD

**Issue by airclear** [baomidou/mybatis-plus#2466]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 问题描述

mybatis能通过sqlsessionFactory获取，使用mp，如果集成了basemapper，发现在sqlsessionfactory里获取不到了

请问mp如何获取所有的SQL语句？

**Comment by qmdx** [comment]
mp 注入点 https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/MybatisSqlSessionFactoryBuilder.java
