### ISSUE TITLE
mybatis-plus文档用到什么框架技术

### ISSUE THREAD

**Issue by rainLeelzr** [baomidou/mybatis-plus#2468]
请问https://mybatis.plus/  这个文档是用什么框架技术写的，有没有连接教程。怎么用gitee pages部署，我也想写一个文档。我 clone 你的 https://github.com/baomidou/mybatis-plus-doc  然后开启gitee pages报错。
```
部署失败
错误信息: Liquid syntax error (line 48): Tag '{%' was not properly terminated with regexp: /\%\}/
```

**Comment by nieqiurong** [comment]
vuepress
