### ISSUE TITLE
关于复合主键

### ISSUE THREAD

**Issue by llwmeme** [baomidou/mybatis-plus#2469]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当数据库中使用复合主键的时候 使用saveOrUpdate() 前会调用selectOne()确认是新增还是修改，但是仅使用了一个id 作为条件，请问这个是否有解决方案？

**Comment by miemieYaho** [comment]
没有,不支持多主键,下一版本多个主键注解将会启动报错
