### ISSUE TITLE
自定义全局操作,做了一个查询但是封装不上数据一直Null

### ISSUE THREAD

**Issue by thinking-in-java** [baomidou/mybatis-plus#2477]
### 当前使用版本(必填,否则不予处理)

2.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

写了个自定义全局操作 查询oracle中某列数据封装不进实体类 显示null

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/61909256/82150865-15fd8100-988c-11ea-90fc-866286f5084f.png)

### 报错信息
就打印结果为null,无报错

**Comment by miemieYaho** [comment]
参考其他的自动注入sql的类
