### ISSUE TITLE
:sparkles: 希望添加一个功能

### ISSUE THREAD

**Issue by lingting-gzm** [baomidou/mybatis-plus#2480]
我看到有个方法 com.baomidou.mybatisplus.core.enums.SqlMethod 里面有些已经配置好的脚本，它们应该都是按照规则解析，能否开发一个接口让我们能够自定义一些这种脚本呢？

只要确定解析规则，那么这里的脚本我们自定义应该也可以把？

**Comment by miemieYaho** [comment]
这不是脚本,这东西相当于内部常量
