### ISSUE TITLE
BigDecimal类型无法被更新为null，大家怎么处理？

### ISSUE THREAD

**Issue by wangtiegang** [baomidou/mybatis-plus#2481]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当字段类型为 BigDecimal 时，如果将字段的值 set 为 null，然后调用框架的更新方法，数据库的值不会被更新，查了下好像是因为 mybatis 的策略导致的，不知道大家会怎么处理？不太想使用 xml 自己定义更新语句

**Comment by miemieYaho** [comment]
updatewrapper.set(clomun,null)
