### ISSUE TITLE
wrapper.in查询时传入列表为空的情况下自动去除in条件？

### ISSUE THREAD

**Issue by dwkfxj** [baomidou/mybatis-plus#2484]
### 当前使用版本(必填,否则不予处理)
2.1.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请问3.x版本是否解决了这个问题？

### 重现步骤(如果有就写完整)
wrapper.in(column,List)  当传入的List.isEmpty时，生成的sql没有in条件，会直接查出全量数据。

**Comment by miemieYaho** [comment]
3.x版会生成 in () ,然后执行sql报错

**Comment by qaz4042** [comment]
> 3.x版会生成 in () ,然后执行sql报错

我觉得最常的需求是,单表 wrapper.in(column,List)  为空 替换为 1!=0

**Comment by qaz4042** [comment]
> 3.x版会生成 in () ,然后执行sql报错


我觉得最常的需求是,单表 wrapper.in(column,List)  为空 替换为 1=0
