### ISSUE TITLE
代码生成器无法忽略表中的字段不映射到实体

### ISSUE THREAD

**Issue by davelet** [baomidou/mybatis-plus#2486]
### 当前使用版本(必填,否则不予处理)
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-generator</artifactId>
			<version>3.2.0</version>
		</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

表中的字段
```sql
    `last_updated_at` datetime(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
```
不想映射到实体中，在mybatis原始配置中可以使用
```xml
<ignoreColumn column="last_updated_at"/>
```

**Comment by qmdx** [comment]
设置为父类公共字段即可字段
