### ISSUE TITLE
生成自定义模板建议

### ISSUE THREAD

**Issue by z-hanwen** [baomidou/mybatis-plus#2487]
### 当前使用版本(必填,否则不予处理)
starter 3.2.0 
generator 3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
关于生成器的自定义模板部分，文档可否给出较为直观的例子，
什么引擎都无所谓，这个可以自己看相关文档学习
另外，提供了哪些变量可以在引擎里使用，能否列出来
例如自定义模板时想引用表名的变量，不知道变量名，无法引用

**Comment by qmdx** [comment]
配置说明 https://mybatis.plus/config/generator-config.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

使用说明 https://mybatis.plus/guide/generator.html
