### ISSUE TITLE
使用Sql注入器实现自定义接口，在多数据源的情况下如何使用

### ISSUE THREAD

**Issue by skksksksks** [baomidou/mybatis-plus#2489]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
单数据源项目中，使用@Bean注册LogicSqlInjector可以使用自定义接口，多数据源项目中使用@Bean注册分页插件与Sql注入器并没有效果。已知分页插件可以通过sqlSessionFactoryBean.setPlugins(paginationInterceptor)实现，请问Sql注入器应该怎么注册？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java
