### ISSUE TITLE
插入时返回主键失效

### ISSUE THREAD

**Issue by hhxx1994** [baomidou/mybatis-plus#249]
insert id="insertAndGetId" useGeneratedKeys="true" keyProperty="id" keyColumn="id" parameterType="com.hhx.house.entity.User" 
    insert into user(name,password,register_date)
    values(#{user.name},#{user.password},now())
 insert

不能返回主键

**Comment by qmdx** [comment]
这是自定义插入吧， 不属于 mp 的范畴了。请使用 MP 提供的插入方法
