### ISSUE TITLE
为什么service里有批量增加,修改 , 而mapper没有

### ISSUE THREAD

**Issue by sin97** [baomidou/mybatis-plus#2495]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如果表有关联关系,需要批量保存的话,
在service里写逻辑, 难道还要调用其他service 保存吗....
在mapper里写的话,又不想写foreach...

**Comment by miemieYaho** [comment]
看文档
