### ISSUE TITLE
代码生成开启实体类swagger注解，当数据库comment存在换行时，存在问题

### ISSUE THREAD

**Issue by jerrywoooooooo** [baomidou/mybatis-plus#2498]
### 当前使用版本
3.3.1.tmp

### 报错信息
代码生成的时候如果开启实体类swagger注解，当数据库注解存在换行时（虽然不会这么用）：
![image](https://user-images.githubusercontent.com/33852129/82643052-7bad8c80-9c41-11ea-8ec8-e1794eed27a7.png)

**Comment by yuxiaobin** [comment]
是时候展现你实力了，PR推起来

**Comment by nieqiurong** [comment]
升级至快照版本3.3.3.7-SNAPSHOT，使用教程仓库-> https://mp.baomidou.com/guide/install.html#snapshot。
