### ISSUE TITLE
逻辑bug

### ISSUE THREAD

**Issue by Giler** [baomidou/mybatis-plus#2500]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
断言判空 逻辑取反 

### 重现步骤(如果有就写完整)
逻辑问题，

### 报错信息
package com.baomidou.mybatisplus.extension.api
public class Assert
public static void notEmpty(Collection<?> collection, IErrorCode errorCode) {
        if (CollectionUtils.isNotEmpty(collection)) {
            fail(errorCode);
        }
    }
逻辑取反 对比其上下两个函数。
如果就是 取反 请忽略。

**Comment by yuxiaobin** [comment]
应该是苗老板写的隐藏bug

**Comment by Giler** [comment]
收到

**Comment by qmdx** [comment]
fixed https://github.com/baomidou/mybatis-plus/commit/68d7dbc242888a49a3509688c57810509b6baf28
