### ISSUE TITLE
特殊字符分页查询，count不为0但数据查不出的问题

### ISSUE THREAD

**Issue by GreatlyJellyfish** [baomidou/mybatis-plus#2501]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用反斜杠\做模糊查询时，打印sql语句查询count时不为0，在mysql中也能查询的到值为1，但没有数据返回
反斜杠\已转义

### 报错信息
无

**Comment by qmdx** [comment]
请给出具体使用代码部分

**Comment by xiaop1ng** [comment]
入参存在 \\\\ 时，分页器会响应 total =  0
