### ISSUE TITLE
update和insert方法都需要返回实体给前端,

### ISSUE THREAD

**Issue by zhyusgethup** [baomidou/mybatis-plus#2502]
v3.3.1.tmp

你好! 非常感谢关注我的麻烦.
update和insert方法都需要返回实体给前端, 但是像created, updated这些字段, 他是由数据库自动加入的, 请问有没办法获取数据库自动加入的值, 实在没办法也可以手动注入一个, 目前我用aop 切update, insert等方法. 有没有更合适的方案呢

**Comment by miemieYaho** [comment]
没有,只能select
