### ISSUE TITLE
updateFill如果不是null，就不会自动填入

### ISSUE THREAD

**Issue by SingerDracula** [baomidou/mybatis-plus#2503]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类设置fill = FieldFill.INSERT_UPDATE，自动填入配置类重写updateFill方法，需要自动填入的字段如果不是null，就不会自动填入

### 报错信息

逻辑错误

**Comment by miemieYaho** [comment]
填充类点开源码看调用链，不满意就自己重写
