### ISSUE TITLE
【代码生成器】开启setEntityBooleanColumnRemoveIsPrefix, 生成的实体类import缺少TableField

### ISSUE THREAD

**Issue by xuguoqin** [baomidou/mybatis-plus#2504]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
StrategyConfig类开启setEntityBooleanColumnRemoveIsPrefix(true)

### 重现步骤(如果有就写完整)
setEntityBooleanColumnRemoveIsPrefix(true)
如果数据库中有is_delete这种字段
生成的实体类中delete字段上有@TableField("is_delete")注解，但是没有导入包

### 报错信息
未导入com.baomidou.mybatisplus.annotation.TableField;
Error:(37, 6) java: 找不到符号
  符号:   类 TableField
  位置: 类 com.demo.user.entity.User

**Comment by xuguoqin** [comment]
排查是AutoGenerator类pretreatmentConfigBuilder方法中只设置了需要转换去掉开头的字段，没有添加@TableField注解到importPackages中

**Comment by qmdx** [comment]
mp 3.3.2 试试
