### ISSUE TITLE
代码生成器生成entity时，如果表名未启用underline_to_camel，而字段启用underline_to_camel，则生成的entity只有第一个非key字段有@TableField注解，其它字段没有，并且其它字段下划线不会转换为驼峰

### ISSUE THREAD

**Issue by gmshiot** [baomidou/mybatis-plus#2506]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
代码生成器生成entity时，如果表名未启用underline_to_camel，而字段启用underline_to_camel，则生成的entity只有第一个非key字段有@TableField注解，其它字段没有，并且其它字段下划线不会转换为驼峰

**Comment by nieqiurong** [comment]
#2278

**Comment by qmdx** [comment]
请使用 3.3.2 版本测试，不行再打开讨论
