### ISSUE TITLE
IEnum在查询结果有空格时转换失败

### ISSUE THREAD

**Issue by yuyue888** [baomidou/mybatis-plus#2507]
### 当前使用版本(必填,否则不予处理)
版本3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
db2数据库中，对应枚举字段类型设成了char(2)，实际值长度为1，导致查询结果中该字段右侧自动补了空格，比如'A'查询结果是 'A   ' ，此时无法成功转成对应枚举类型。
希望在MybatisEnumTypeHandler的equalsValue方法中，进行比较前对sourceValue做一下trim处理

### 重现步骤(如果有就写完整)
orcale或者db2数据库，（mysql8.0似乎char类型的查询结果会自动去右侧空格）
1.定义枚举类，值长度为1的字符串
2.数据库对应字段类型设置为char(2)
3.定义对象，进行查询

### 报错信息
对应枚举字段转换结果为null

**Comment by yuxiaobin** [comment]
为啥不是varchar2..
[已修复](https://gitee.com/baomidou/mybatis-plus/commit/3e240ac8844ab6d761b07417fb5c3f32e6e26c8f)
