### ISSUE TITLE
启动的时候Mapper文件上加了@Mapper注解，识别不到Mapper

### ISSUE THREAD

**Issue by yanganxing** [baomidou/mybatis-plus#2509]
### 当前使用版本(必填,否则不予处理)
V3.3.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
添加如下依赖，除了这个以外没有添加Mybatis相关的依赖，然后启动的时候报错，大概意思Mapper找不到

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
        </dependency>
        

### 重现步骤(如果有就写完整)
项目地址如下，小白求翻牌
https://github.com/yanganxing/infosystem.git

### 报错信息
![image](https://user-images.githubusercontent.com/20694615/82853948-a9dce600-9f39-11ea-9c90-747e70c25d26.png)

**Comment by miemieYaho** [comment]
项目 404

**Comment by yanganxing** [comment]
https://github.com/yanganxing/infosystem

**Comment by yanganxing** [comment]
感谢大佬翻牌

**Comment by miemieYaho** [comment]
启用需要 DataSource ,你把 DataSource 的自动注入排除了当然就不生效了
