### ISSUE TITLE
XML文件热加载BUG

### ISSUE THREAD

**Issue by zhangguojun** [baomidou/mybatis-plus#251]
xml文件中覆盖某一方法，例如：
实体类A（TableName 指向 A）
当xml中重写 selectList SQL语句 （**SELECT * FROM B，此时指向B表**）, 然后将重写的selectList SQl语句标签清除掉，结果还是执行 **SELECT * FROM B**

**Comment by qmdx** [comment]
idea 重新编译一下 eclipse 也许重启
