### ISSUE TITLE
加密的处理建议

### ISSUE THREAD

**Issue by zxiaozhou** [baomidou/mybatis-plus#2512]
##  看了加密处理感觉意义不大(当然这个世界上没有什么是绝对安全的只是相对安全)
* 提供一个url获取密钥：
*  整个系统对数据库、配置文件共用一个对称密钥
* 当然也可以选择本地获取

## 整个项目其实已经是实现了的，虽然完全由自己写，但公司项目不敢开源，在这里只是提个建议

**Comment by qmdx** [comment]
这里只是简单需求如果要按照你的思路实现就需要独立开一个项目来做了，这里暂不支持
