### ISSUE TITLE
调用批量更新updateBatchById方法报错

### ISSUE THREAD

**Issue by lijiawengo** [baomidou/mybatis-plus#2513]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用updateBatchById方法报错

### 重现步骤(如果有就写完整)
        List<SysUser> sysUsers = new ArrayList<>(1);
        sysUsers.add(
                SysUser.builder()
                        .id(1L)
                        .username("admin")
                        .secretCode(encoder.encode("admin"))
                        .build());
        sysUserService.updateBatchById(sysUsers);

org.apache.ibatis.session.defaults.DefaultSqlSession类中执行到public int update(String statement, Object parameter)方法的return executor.update(ms, wrapCollection(parameter));语句时报错

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]

**Comment by miemieYaho** [comment]
无法复现,你先检查jar版本依赖是否有冲突吧

**Comment by lijiawengo** [comment]
谢谢，确实是和自定义的mybatis plugin冲突了

**Comment by win434545299** [comment]
> 谢谢，确实是和自定义的mybatis plugin冲突了

请问这个问题是怎么解决的啊，我也遇到这个问题了...= =
