### ISSUE TITLE
新版本包引用问题

### ISSUE THREAD

**Issue by timandy** [baomidou/mybatis-plus#2514]
### 当前使用版本(必填,否则不予处理)
从 MP 3.3.1 升级到 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1. 多了很多 kotlin 开头的包, 这些包是否必要? 
2. 多了几个不必要的包(这两个包只在编译期有作用,现在却被打到构建物里)
spring-boot-autoconfigure-processor-2.3.0.RELEASE.jar
spring-boot-configuration-processor-2.3.0.RELEASE.jar

版本信息
java8
spring boot 2.3.0

**Comment by qmdx** [comment]
![1164006](https://user-images.githubusercontent.com/1481125/82879482-977d9f00-9f6f-11ea-88e4-da76c6cef0a6.png)
如图并没有你说的情况，这里是 gradle 构建，你刷新下依赖看看 ？

**Comment by timandy** [comment]
@qmdx 看这个地方看不出来, 要打成 spring boot 的 fat-jar 然后解压看一下.我一会截一个对比图. 已经确认是 3.3.2 引入的

**Comment by timandy** [comment]
![Uploading image.png…]()

**Comment by qmdx** [comment]
感谢反馈，抽空解决

**Comment by qmdx** [comment]
@timandy 如上

**Comment by timandy** [comment]
相同的 spring boot 版本, 只升级 mybatis-plus 的版本就会多出很多无关的包. 例如 fastjson, mybatis-plus-generator,processor  等等. 我上传了一个 demo 请看一下.
[demo.zip](https://github.com/baomidou/mybatis-plus/files/4693914/demo.zip)

**Comment by timandy** [comment]
@qmdx

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/83126486-718d0180-a10b-11ea-9e76-2a2b64decbc2.png)
并没有你说的问题

**Comment by nieqiurong** [comment]
gradle构建的话，先把gradle版本改成5.x版本，例如5.6.4。

**Comment by timandy** [comment]
用 gradlew clean build 打的包

**Comment by nieqiurong** [comment]
使用快照版本试试 3.3.3.2-SNAPSHOT，快照使用方式 https://mp.baomidou.com/guide/install.html#snapshot
