### ISSUE TITLE
分页查询，返回的结果是全部，日志打印显示没有limit

### ISSUE THREAD

**Issue by MsencSir** [baomidou/mybatis-plus#2516]
使用版本：
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>
</dependency>

查询代码：
![image](https://user-images.githubusercontent.com/46589466/82895788-5a250b80-9f87-11ea-8cf9-f1a72f2a545d.png)

page使用来源：
![image](https://user-images.githubusercontent.com/46589466/82896019-cdc71880-9f87-11ea-8d12-c42fce155409.png)

日志打印：
![image](https://user-images.githubusercontent.com/46589466/82895860-83de3280-9f87-11ea-9e54-c4b54ccb38c3.png)

发现执行sql并没有limit; 查询的是全部结果；

请问是我用法有误吗？

**Comment by miemieYaho** [comment]
插件没注入进去,自己排查,要是自己构建sqlsessionfactory就照着mp的autoConfiguretion抄
