### ISSUE TITLE
mysql使用Merge分表,不能使用事务？

### ISSUE THREAD

**Issue by MsencSir** [baomidou/mybatis-plus#2517]
使用版本：
![image](https://user-images.githubusercontent.com/46589466/82896313-55148c00-9f88-11ea-9d3c-71b9bd8c09d3.png)

![image](https://user-images.githubusercontent.com/46589466/82896614-d704b500-9f88-11ea-9dad-c7672dd43290.png)

总表：
![image](https://user-images.githubusercontent.com/46589466/82896693-fc91be80-9f88-11ea-9aa6-70ff2fdda936.png)

分表1：
![image](https://user-images.githubusercontent.com/46589466/82896726-087d8080-9f89-11ea-8591-aebc672a1e71.png)

问题描述：
经测试正常表的操作事务是没有问题的；但是操作分表的总表时，事务没有起作用；

请问是不支持分表事务吗？还是我用法有问题呢？

**Comment by miemieYaho** [comment]
这和mp没关系,自己排查吧
