### ISSUE TITLE
2.1.7版本下的BaseMapper#selectById查不到数据

### ISSUE THREAD

**Issue by JulianHang** [baomidou/mybatis-plus#2518]
### 当前使用版本(必填,否则不予处理)
<dependency>
           <groupId>com.baomidou</groupId>
           <artifactId>mybatis-plus</artifactId>
            <version>2.1.7</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用通用的BaseMapper中的selectById(Serializable id)方法为null，而实际上直接把SQL拿到数据库管理工具上执行却是有的

### 重现步骤(如果有就写完整)
调用BaseMapper中的selectById(Serializable id)查不到数据，而实际上却有

### 报错信息
查不到数据

**Comment by miemieYaho** [comment]
model代码?mapUnderscoreToCamelCase?yml配置?

**Comment by JulianHang** [comment]
// Model
@TableName("sys_org")
public class SysOrg {
	@TableId("org_id")
	private BigInteger orgId;
}

// yml配置
mybatis.configuration.map-underscore-to-camel-case = true

通过以下方式复写BaseMapper#selectById可以查出数据
public interface Test extends BaseMapper<SysOrg> {
     
}

@miemieYaho

**Comment by miemieYaho** [comment]
mybatis-plus.configuration

**Comment by JulianHang** [comment]
> mybatis-plus.configuration

使用springboot配置文件的提示功能，只有mybatis.configuration，加上网上查阅资料发现也是这么写的...

**Comment by JulianHang** [comment]
额外补充一点，这种现象是偶尔出现...

@miemieYaho

**Comment by miemieYaho** [comment]
什么叫偶尔出现?

**Comment by JulianHang** [comment]
> 什么叫偶尔出现?

没做任何操作，通过重启系统的方式进行多次测试，有时候会出现可以查询出数据，有时候又不行

**Comment by miemieYaho** [comment]
搞迷信?

**Comment by stjava** [comment]
我也出现这个问题了

**Comment by alun135998** [comment]
我也遇到这个问题了，请问如何解决？

**Comment by VamerTyv** [comment]
我也遇到了,saveOrUpdateBatch this.getById((Serializable)idVal) 返回的结果是0,打印的SQL在mysql数据库有值

**Comment by ahaha-vip** [comment]
遇到了同样的问题

**Comment by blackdobb** [comment]
我3.0.5版本也遇到了。。。。

**Comment by ahaha-vip** [comment]
我们当时的情况是新增后，马上有线程去查询，概率性查不到。后面定位到是数据库主从复制的问题，数据同步可能会有一定延迟。
