### ISSUE TITLE
事务内分页无法取到下一页数据

### ISSUE THREAD

**Issue by ksh033** [baomidou/mybatis-plus#252]
我在事务方法内循环分页无法取到下一页数据

**Comment by qmdx** [comment]
测试无该问题

**Comment by yuercl** [comment]
我也遇到了一样的问题了。 @ksh033 k

**Comment by shihua-guo** [comment]
我尝试在循环里面获取下一页，但是一直是死循环。无法获取到下一页数据。
`do{
            page.setCurrent(page.getCurrent()+1);
            apiConfigIPage = baseMapper.selectPage(page, criteria);
            records = apiConfigIPage.getRecords();
            for(ApiConfig apiConfig:records){
                try{
                    JSONObject params = JSONObject.parseObject(apiConfig.getParams());
                }catch (Exception e){
                    failMerchantIds.add(apiConfig.getMerchantId());
                }
            }
        }while (!records.isEmpty());`
