### ISSUE TITLE
initResultMap后未设置initResultMap属性为true

### ISSUE THREAD

**Issue by lsdwangkang** [baomidou/mybatis-plus#2520]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在使用autoResultMap=true后会使用select * 而不是各个具体的字段

原因可能是
com.baomidou.mybatisplus.core.metadata.TableInfo.initResultMapIfNeed
该方法最后没有设置initResultMap这个字段为true

**Comment by miemieYaho** [comment]
可能？

**Comment by lsdwangkang** [comment]
使用autoResultMap=true的时候selectById方法使用的sql实际是select * 而非各个具体的字段，我不太确定这是mybatis-plus有意为之还是一个bug，如果不是有意为之，那原因就是我上面指出的方法有问题，麻烦解答一下，谢谢。

**Comment by miemieYaho** [comment]
确实没设置 initResultMap 为 true

**Comment by miemieYaho** [comment]
这块的逻辑已经改了,不需要这个属性了,想体验可以使用 `3.3.3.1-SNAPSHOT`

**Comment by miemieYaho** [comment]
该版本在设置了 autoResultMap 为 true 下,select的body都不会进行as,如果手动设置了 resultMap 则 selectBody 为 '*'
