### ISSUE TITLE
使用update（UpdateWrapper）方法

### ISSUE THREAD

**Issue by Sunyb01** [baomidou/mybatis-plus#2523]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用update（UpdateWrapper<>().lamda().eq().setEntity()）
时，提示sql语法错误

### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=10
 AND ops_dc_user_id=1241
 AND name='44444'
 AND phone='string'
 AND ' at line 2
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=10
 AND ops_dc_user_id=1241
 AND name='44444'
 AND phone='string'
 AND ' at line 2

### 报错信息
提示sql语法错误， sql为 Update table where clomn = ....

**Comment by miemieYaho** [comment]
你咋不给set值呢? set的Entity是用来生成where的

**Comment by Sunyb01** [comment]
感谢

**Comment by xun404** [comment]
> 你咋不给set值呢? set的Entity是用来生成where的

我觉的这地方要不要改一下，setEntity我也踩坑了，直觉setEntity是set 对象的，而不是where条件。

**Comment by xun404** [comment]
> > 你咋不给set值呢? set的Entity是用来生成where的
> 
> 我觉的这地方要不要改一下，setEntity我也踩坑了，直觉setEntity是set 对象的，而不是where条件。

allEq(entity)
