### ISSUE TITLE
分页查询current大于当前最大页号时的查询

### ISSUE THREAD

**Issue by ilaotan** [baomidou/mybatis-plus#2529]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
selectPage分页，假设数据是145条，当 size=10, current大于15时，sql会执行count查询总数,然后执行具体sql， 请问有没有开关能根据总count数做判断，如果count的值大于当前页号*size，就不再具体查询sql了？

**Comment by nieqiurong** [comment]
count的值大于当前页号*size ???????

**Comment by ilaotan** [comment]
> count的值大于当前页号*size ???????

看不懂咩？比如  count总数145条 我传入的current=17 ,size=10 .很明显查不出来数据。 但是还是会执行具体的sql查询。

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/PaginationInterceptor.java 

你看下代码啊，默认如果溢出分页数会设置到第一页 overflow 参数设置 true 即可。

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/3056073f527c83af024de90fa89b69ee2898e7bd
