### ISSUE TITLE
Hikari连接池针对DB2数据库无法打印sql语句

### ISSUE THREAD

**Issue by sxrstrive** [baomidou/mybatis-plus#253]
底层数据库：DB2
连接池版本：HikariCP-java7--2.4.13
在判断HikariPreparedStatementWrapper.equals(stmtClassName)时，通过getValue("delegate.sqlStatement")获取不到sql语句，返回的为类对象字符形式

**Comment by qmdx** [comment]
抱歉，我们团队无 db2 环境，希望可以提供 PR
