### ISSUE TITLE
多数据源切换情况下 xml文件中的 databaseId无效

### ISSUE THREAD

**Issue by zhuqinyangdev** [baomidou/mybatis-plus#2530]
### 当前使用版本(必填,否则不予处理)

3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在xml文件中配置了databaseId，同时系统集成了多数据源切换会导致databaseId无效

### 重现步骤(如果有就写完整)

主数据库mysql,切换到oracle时在执行mapper中的语句还会执行mysql的语句

**Comment by miemieYaho** [comment]
自行排查
