### ISSUE TITLE
 插入 bean的属性无法转下划线

### ISSUE THREAD

**Issue by wzl1990** [baomidou/mybatis-plus#254]
如数据user(id,create_time) 对应 User(id,createTime)  调用insert  执行sql 是 (id,createTime) values(1,'2017-09-19'); 这样就报错了，请问除了加  @TableField(value = "create_time") 注解外，有全局配置吗

**Comment by qmdx** [comment]
看文档 mp.baomidou.com 全局配置改为下划线命名
