### ISSUE TITLE
MybatisPlusAutoConfiguration, Null Exception

### ISSUE THREAD

**Issue by robinwen** [baomidou/mybatis-plus#255]
in MybatisPlusAutoConfiguration

當this.properties.getConfigLocation()有值時, 
line 120: configuration.setDefaultScriptingLanguage(MybatisXMLLanguageDriver.class);
將發生configuration的Null Exception

**Comment by robinwen** [comment]
是否将纳入patch?

**Comment by qmdx** [comment]
`當this.properties.getConfigLocation()有值時` 什么场景要这么做？

**Comment by robinwen** [comment]
[in application.properties], 只定义config-location, 无定义其他mybatis-plus参数
mybatis-plus.config-location=classpath:mybatis.xml

[in MybatisPlusAutoConfiguration]
if (configuration == null && !StringUtils.hasText(this.properties.getConfigLocation())) {
            configuration = new MybatisConfiguration();
}
判断式为false, 不建立configuration 

如此, line 120将发生Null Exception

**Comment by robinwen** [comment]
我只需要定义config-location, 因为要设定很多Alias与自定plugins还是有其他方法?
[myabtis-config.xml]
	<typeAliases>
		<typeAlias alias="LinkedHashMap" type="java.util.LinkedHashMap" />
 		<package name="core.persistence.entity" />
	</typeAliases>
	<plugins>
		<plugin interceptor="admin.helper.MyInter">
		<property name="val" value="100"/>
	</plugin>

**Comment by qmdx** [comment]
已加上非空判断
