### ISSUE TITLE
@TableId 设置Auto不起作用

### ISSUE THREAD

**Issue by Leomii** [baomidou/mybatis-plus#2551]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 报错信息

没有报错信息，就是自动生成一个Long型的主键，非自增
已经设置了 类型为 AUTO

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by redfish110** [comment]
IdType：
AUTO：自增。前提，数据库表主键设置了自增约束。
数据库主键设置了自增，使用mybatis-plus自己自增生成的id值。
数据库主键没有设置自增，使用数据库默认值，不会有自增效果。

个人认为mybatis-plus的@TableId的auto逻辑应该修改为：
不论数据库表有没有设置自增，都应该使用mybatis-plus自己生成的自增id

**Comment by yancong303** [comment]
我也遇到了这个问题，解决办法就是把原来包装类型的Long 改为long就行了，这可能是代码的bug
private long id;
