### ISSUE TITLE
为啥3.0.5以上移除excludeColumns 方法，挺好用的呀

### ISSUE THREAD

**Issue by CaoShenZhou** [baomidou/mybatis-plus#2552]
### 当前使用版本 3.3.1
为啥3.0.5以上移除excludeColumns方法
新版的这样排除字段不是很好用
info -> !info.getColumn().equals("update_time")
 && !info.getColumn().equals("create_time")

希望出一个类似excludeColumns(Entity::updateTime,Entity::createTime)的方法排除字段

**Comment by miemieYaho** [comment]
该方法不合理

**Comment by CaoShenZhou** [comment]
> 该方法不合理

请问以后会有简单一些的排除字段方法吗，Lambda表达式这种

**Comment by miemieYaho** [comment]
没有
