### ISSUE TITLE
使用 Wrapper 自定义SQL 有 sql 注入风险

### ISSUE THREAD

**Issue by kendog2** [baomidou/mybatis-plus#2556]
### 当前使用版本(必填,否则不予处理)

3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用${ew.customSqlSegment} ，前端传%能查出数据

**Comment by miemieYaho** [comment]
自己做过滤处理

**Comment by good2luck** [comment]
不使用${ew.customSqlSegment} ，也是一样的情况
