### ISSUE TITLE
条件构造器是否可以加入 Class.filed 这样来代替写字符串字段

### ISSUE THREAD

**Issue by guoqianyou** [baomidou/mybatis-plus#256]
通过lambda 来实现 获取 class中的filed和注解，这样让开发不用操心数据库里的字段名字。 

![1520479121](https://user-images.githubusercontent.com/13718642/37131244-7b4b0a24-22c2-11e8-9c16-5279a4ab0666.png)

通过反射机制获取到字段名字和注解

![1520479121](https://user-images.githubusercontent.com/13718642/37131490-9356d6a6-22c3-11e8-94c1-2778837bb459.png)
![1520479121](https://user-images.githubusercontent.com/13718642/37131522-aad14d02-22c3-11e8-9b3b-fed7e8312218.png)

![1520479121](https://user-images.githubusercontent.com/13718642/37131569-e3ddd3f4-22c3-11e8-9445-1d38c68e6c6d.png)

这样 model 修改后，代码也可以报错，利于修改。写的时候也挺方便的

**Comment by huayanYu** [comment]
能否提交一个demo在test下。

**Comment by qmdx** [comment]
TO https://gitee.com/baomidou/mybatis-plus/issues/IIB86

MP `3.0`  解决该问题。
