### ISSUE TITLE
集成选装件InsertBatchSomeColumn批量插入默认会插入null值

### ISSUE THREAD

**Issue by heyaping388** [baomidou/mybatis-plus#2560]
### 当前使用版本(必填,否则不予处理)
3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
集成选装件InsertBatchSomeColumn做批量插入，实体类为null的字段，在生成批量插入SQL语句中会产生null值

### 重现步骤(如果有就写完整)
产生的sql语句如： insert into(id,name,age) values(1,null,2)  而不是insert into(id,age) values(1,2)

**Comment by miemieYaho** [comment]
肯定会有null

**Comment by heyaping388** [comment]
有办法不插入null吗？不然表字段的默认值就无效了 都是插入了null

**Comment by miemieYaho** [comment]
看里面属性进行字段筛选

**Comment by heyaping388** [comment]
哪里的属性   需要改com.baomidou.mybatisplus.extension.injector.methods.InsertBatchSomeColumn.java吗

**Comment by heyaping388** [comment]
![image](https://user-images.githubusercontent.com/25815555/84119980-c0219080-aa67-11ea-9645-677f1002b23d.png)
是不是要模仿
![image](https://user-images.githubusercontent.com/25815555/84120077-e5160380-aa67-11ea-82a0-8427a8ffe30f.png)
生成if 脚本

**Comment by miemieYaho** [comment]
InsertBatchSomeColumn.predicate

**Comment by heyaping388** [comment]
我是这样写的
![image](https://user-images.githubusercontent.com/25815555/84124944-74beb080-aa6e-11ea-8c1a-91f8d2e9d60b.png)
  但是没有效果 求指点 万分感谢

**Comment by heyaping388** [comment]
研究了下 貌似mybatis批量insert操作  没法动态生成非null的column

**Comment by miemieYaho** [comment]
那是筛选字段的函数
batch= 
```sql
insert into table (column1,column2) values(list[0].value1,list[0].value2),(list[1].value1,list[1].value2)......
```
字段固定那值必须也固定,有几个字段就必须有几个值,否则会报错

**Comment by heyaping388** [comment]
> 那是筛选字段的函数
> batch=
> 
> ```sql
> insert into table (column1,column2) values(list[0].value1,list[0].value2),(list[1].value1,list[1].value2)......
> ```
> 
> 字段固定那值必须也固定,有几个字段就必须有几个值,否则会报错

意思是只能指定固定字段名作为筛选条件，而不能适应所有场景？

**Comment by xbox1994** [comment]
@heyaping388 我暂时在entity里把字段的默认值直接加上了，可以解决

**Comment by heyaping388** [comment]
> @heyaping388 我暂时在entity里把字段的默认值直接加上了，可以解决

阿里巴巴java开发手册不推荐entity加默认值

**Comment by ldf-hub** [comment]
所以有解决方案吗？

**Comment by wangjintaod** [comment]
可以投机取巧，我的场景是，数据库中有个create_time字段，设置的是在数据新增时默认赋值为当前时间戳，然后我使用InsertBatchSomeColumn插入时createTime没有赋值，导致插入了好多null的值，数据库的默认值也失效了。于是乎我直接这么写
` methodList.add(new InsertBatchSomeColumn(tableFieldInfo -> !"createTime".equals(tableFieldInfo.getField().getName())));`
这样做直接createTime就不参与sql的拼接，进而解决了这个问题。

**Comment by wangjintaod** [comment]
可以自己写一个方法，在拼sql的时候判断一下 null的时候 colum不拼，value也不拼，我目前是想要让updateTime赋值为now()的，所以我这么写了。同样的道理，拼出来的sql自己调整一下就可以了.
![代码图片](https://github.com/user-attachments/assets/2d7ed51c-9a24-4d51-ad0c-768c0687cc4c)
