### ISSUE TITLE
LambdaUtils.getColumnMap(aClass)获取映射之后未修改是否初始化映射标识符

### ISSUE THREAD

**Issue by idealiezed** [baomidou/mybatis-plus#2565]
### 当前使用版本(必填,否则不予处理)

3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

代码改进建议

### 重现步骤(如果有就写完整)

com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper[91]
if (!initColumnMap) {
            columnMap = LambdaUtils.getColumnMap(aClass);
        }

### 报错信息

改进为
if (!initColumnMap) {
            columnMap = LambdaUtils.getColumnMap(aClass);
initColumnMap = Boolean.TRUE;
        }

**Comment by miemieYaho** [comment]
早改了
