### ISSUE TITLE
枚举注入可否指定注入字段 。而不是注入下标

### ISSUE THREAD

**Issue by 54skyray** [baomidou/mybatis-plus#2568]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
  FALSE(10, "否"){
        @Override
        public boolean isFalse(){
            return true;
        }
    },
    TRUE(11, "是"){
        @Override
        public boolean isTrue(){
            return true;
        }
    };
有一个po使用以上枚举，插入后发现枚举字段是0 和1 。最后发现是注入的下标

**Comment by miemieYaho** [comment]
不支持
