### ISSUE TITLE
sqlite数据库中时间类型错误

### ISSUE THREAD

**Issue by sglmsn** [baomidou/mybatis-plus#2572]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用sqlite，数据库字段类型为datetime ，java类型为LocalDateTime，插入的时候数据库值为时间字符串，取出的时候报错

### 重现步骤(如果有就写完整)
用com.baomidou.mybatisplus.core.mapper.BaseMapper#selectList查询sqlite

### 报错信息
org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLFeatureNotSupportedException
; null; nested exception is java.sql.SQLFeatureNotSupportedException

**Comment by nieqiurong** [comment]
https://mp.baomidou.com/guide/faq.html#error-attempting-to-get-column-create-time-from-result-set-cause-java-sql-sqlfeaturenotsupportedexception

https://mp.baomidou.com/guide/faq.html#mp版本从3-1-0及以下版本升级到高版本，jdk8日期新类型localdatetime等无法映射（报错）
