### ISSUE TITLE
如何加入mybatisplus开源团队

### ISSUE THREAD

**Issue by FlashMickeyMouse** [baomidou/mybatis-plus#2573]
### 当前使用版本(必填,否则不予处理)
3.x

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

希望整合shardingjdbc分库分表

**Comment by miemieYaho** [comment]
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example
