### ISSUE TITLE
为什么新版把updateForSet方法给去掉了

### ISSUE THREAD

**Issue by 15927131968** [baomidou/mybatis-plus#2574]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
感觉去掉updateForSe方法后不方便了，比如想实现类似效果，来更新账户余额，该如何实现？
update 账户表 set 账户表的余额=账户表的余额-输入的金额

**Comment by miemieYaho** [comment]
updateWrapper
