### ISSUE TITLE
mybatis plus整合sharding

### ISSUE THREAD

**Issue by CrazyZhou0708** [baomidou/mybatis-plus#2577]
当前使用版本(必填,否则不予处理)
mybatis plus版本:3.2.0
sharding-jdbc:4.0.0-RC1

该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis plus主键策略设置如下:
global-config:
#主键类型 1:"数据库ID自增", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID";
id-type: 2
sharding-jdbc主键策略:
bean的id属性:
type=IdType.input
SNOWFLAKE
使用mybatis plus连接sharding-jdbc,插入数据时会报如下错误:
java.lang.StringIndexOutOfBoundsException: String index out of range: -8
但如果不使用mybatis plus的save方法,手写sql,就不会有问题

重现步骤(如果有就写完整)
//orderService.save(order);---mybatis plus的save方法(会报错)
orderMapper.addTOrder(order);---手写sql,没问题

报错信息
Error updating database. Cause: java.lang.StringIndexOutOfBoundsException: String index out of range: -8
The error may exist in com/crazyzhou/shardingjdbc/dao/OrderMapper.java (best guess)
The error may involve com.crazyzhou.shardingjdbc.dao.OrderMapper.insert-Inline
The error occurred while setting parameters
SQL: INSERT INTO public.t_order ( order_id, order_content ) VALUES ( ?, ? )
Cause: java.lang.StringIndexOutOfBoundsException: String index out of range: -8] with root cause

**Comment by miemieYaho** [comment]
你写一个复现demo吧

**Comment by CrazyZhou0708** [comment]
好的,我以附件的形式发你,谢谢了

**Comment by xiaoyangzhang** [comment]
什么原因

**Comment by miemieYaho** [comment]
发在哪的?

**Comment by CrazyZhou0708** [comment]
我发在你github绑定的邮箱了,或者你提供一个具体的邮箱地址给我,我重新发送一遍

**Comment by miemieYaho** [comment]
wonderming@vip.qq.com

**Comment by miemieYaho** [comment]
你给的demo不管怎么跑都是报错,不管你写的insert还是内置的insert入参都是entity,后面走mp的流程都是一样的

**Comment by Wangshuhong123** [comment]
请问下你这个问题解决了吗？我也遇到了，向你请教下怎么解决的
