### ISSUE TITLE
对于insert语句能够支持自定义方法扩充

### ISSUE THREAD

**Issue by idealiezed** [baomidou/mybatis-plus#2578]
### 当前使用版本(必填,否则不予处理)

3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

需要自定义一个 mysql的 ON DUPLICATE KEY UPDATE 通用方法，目前的TableInfo,TableFieldInfo对插入语句不支持拼接入参前缀，导致无法实现
[https://github.com/baomidou/mybatis-plus/issues/2575](url)

### 报错信息
1.TableInfo#convertIf 字段名需要考虑入参前缀
2.MybatisDefaultParameterHandler[177]
Object idValue = metaObject.getValue(tableInfo.getKeyProperty()); 
应考虑字段有入参前缀的情况

**Comment by miemieYaho** [comment]
使用 `3.3.3.2-SNAPSHOT` ,想要融入mp,前缀就只支持: "et."

**Comment by idealiezed** [comment]
只支持et.是没问题的，那这个会考虑发布到release吗

**Comment by miemieYaho** [comment]
会,不过release不会那么快发

**Comment by idealiezed** [comment]
MybatisDefaultParameterHandler[166]
Object idValue = metaObject.getValue(tableInfo.getKeyProperty());

3.3.3.2-SNAPSHOT 这个版本这个问题我看好像并没有对这个做什么处理。
因为给过出去的参数是et实体，keyProperty仍然是不带参数前缀，取值会报错。

**Comment by miemieYaho** [comment]
前面取过et了

**Comment by idealiezed** [comment]
嗯，抱歉没注意看，没问题了，再次感谢
