### ISSUE TITLE
能否做到一个实体对应多张表，动态切换表名？

### ISSUE THREAD

**Issue by zhengwen6300** [baomidou/mybatis-plus#258]
能否做到一个实体对应多张表，动态切换表名？

**Comment by qmdx** [comment]
理论上是可以的，但是暂不支持

**Comment by suan2046** [comment]
基于 @zhengwen6300 的提问，延伸一下。比如 user表做分表处理，比如 user_01,user_02,user_03.....，这样的情况 mp支持么？mapper接口、pojo 设置一个么？

**Comment by qmdx** [comment]
暂无，如果你好的办法欢迎 pr
