### ISSUE TITLE
Xml中Select语句查询Oracle带Schema时，分隔符(点)被忽略

### ISSUE THREAD

**Issue by leighyu1983** [baomidou/mybatis-plus#2580]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter   版本3.3.2
spring-boot-starter-web  版本2.3.0.RELEASE

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
from语句中的schema和table 分隔符(点)，在运行时没有了，导致schema和table 被拼接为一个字符串，被当做了新表名。

### 重现步骤(如果有就写完整)
1. xml文件如下
```xml
    <select id="findByMyId" resultType="mydomain.user.entity.UserEntity">
        select *
        from MY_SCHEMA_A.T_USER
        where id = #{id}
    </select>
```
2. 运行时打印出的SQL语句为
```sql
sql select *  from MY_SCHEMA_AT_USER  where id = ?
```
注意上面的sql语句中schema和table中间的点没有了，MY_SCHEMA_AT_USER整个被当作了表名。

### 报错信息
找不到该表或者视图。

**Comment by miemieYaho** [comment]
你检查一下你都用什么插件了,mp不会没事干改你sql的,实在不知道你就写个复现demo吧
