### ISSUE TITLE
统一代码生成器生成的 interface 命名规则

### ISSUE THREAD

**Issue by siyu77** [baomidou/mybatis-plus#2581]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
接口命名规则不一致，例如有的接口以字母I作前缀，有的没有：
```
public interface BaseMapper<T> extends Mapper<T> {...}
```
```
public interface IService<T> {...}
```
建议去掉 I 前缀，或允许自定义。

**Comment by qmdx** [comment]
这已经是历史命名问题，暂不做调整
