### ISSUE TITLE
dynamicTableName  使用metaObject传参数

### ISSUE THREAD

**Issue by William-ZXS** [baomidou/mybatis-plus#2582]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

samples中提示  “// metaObject 可以获取传入参数，这里实现你自己的动态规则”
比较困惑，应该怎么使用？比如我需要根据某个字段的前两位来匹配一个规则，我如何传递这个参数（可能是表中的字段，也可能不是）？

**Comment by zWeng33** [comment]
ThreadLocal you can try it
