### ISSUE TITLE
该方法存在的意义

### ISSUE THREAD

**Issue by zzz583974851** [baomidou/mybatis-plus#2584]
### 当前使用版本(必填,否则不予处理)
3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.1.1

### 重现步骤(如果有就写完整)

@Test
public void getOneTest04() {
    queryWrapper.ge("emp_age", 18);
    boolean b = employeeService.getObj(queryWrapper, (m) -> {
        Employee employee = employeeService.getById((Long)m);
        employee.setEmpPhone("-----");
        boolean flag = employeeService.updateById(employee);
        return flag;
    });
    System.out.println(b);
}

### 报错信息

不明白，返回主键是什么，如果想要对应实体的其他属性，难道真的要在里边再查询一遍数据库，然后取相应的值吗，那我还不如自己写sql去实现，还减少查询。

**Comment by miemieYaho** [comment]
第二个入参只是单纯的obj转换函数

**Comment by zzz583974851** [comment]
只返回id转换obj没意义呀
