### ISSUE TITLE
自动填充 id字段不生效，其它字段有效

### ISSUE THREAD

**Issue by onvertex** [baomidou/mybatis-plus#2586]
### 当前使用版本(必填,否则不予处理)

3.3.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

实体字段 主键 id 自动填充这个字段不生效 createTime updateTime 生效了

### 报错信息

![WX20200609-160346](https://user-images.githubusercontent.com/31512349/84122320-d9780c00-aa6a-11ea-9f60-f3176fdc8187.png)

![image](https://user-images.githubusercontent.com/31512349/84122365-e8f75500-aa6a-11ea-8b50-aaf8605e4eed.png)

![image](https://user-images.githubusercontent.com/31512349/84122384-f1e82680-aa6a-11ea-9d99-ded6911e494a.png)

**Comment by miemieYaho** [comment]
对id不会生效,默认填充规则是有值不填充,走填充之前就有值了

**Comment by onvertex** [comment]
但是我这字段 ID 除了自动填充这 没其他赋值的地方啊？

**Comment by onvertex** [comment]
> 对id不会强制，替换填充规则是有值不填充，走填充之前就有值了

但是我这一级ID除了自动填充这没其他赋值的地方啊？

**Comment by onvertex** [comment]
> 对id不会强制，替换填充规则是有值不填充，走填充之前就有值了

现在的情况，字段id填充之前是没值的 ，求教 怎么才能填充这个id  因为以前用的老版本 现在一升级新的版本就填充不了，  如果填充不了 代码改动就太大了。跪求指教~~

**Comment by miemieYaho** [comment]
id不需要你填充

**Comment by onvertex** [comment]
> 对id不会生效,默认填充规则是有值不填充,走填充之前就有值了

是不是3.3之后 集成自定义ID  生成器就行了？

**Comment by miemieYaho** [comment]
en

**Comment by onvertex** [comment]
> en

好的。 万分感谢！
