### ISSUE TITLE
泛型ResultType无法正确映射

### ISSUE THREAD

**Issue by YiuTerran** [baomidou/mybatis-plus#2593]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

3.3.0 无此问题，升级到3.3.2后报错。推测是将ResultType中的Object直接当Json处理了，这显然是不对的。

### 重现步骤(如果有就写完整)
`ResultType`设置为`NamedId<String>`

```java
@Data
@NoArgsConstructor
public class NamedId<T> {
    T id;
    String name;

    public NamedId(T id, String name) {
        this.id = id;
        this.name = name;
    }
}
```

sql语句为：

```xml
        select project_code as id,
               project_name as name
        from oa_project where id="p1101012005260430"
```

### 报错信息
 Error attempting to get column 'id' from result set.  Cause: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'p1101012005260430': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"p1101012005260430"; line: 1, column: 18]

**Comment by miemieYaho** [comment]
有复现demo?

**Comment by YiuTerran** [comment]
我发现问题了，应该是我自己以前写了一个Json的TypeHandler指定了MappedTypes为Object.class

不知道为啥3.3.0没有正确使用这个类，我删掉这个类就行了。。
