### ISSUE TITLE
mysql json数组字段类型查询映射到实体类集合

### ISSUE THREAD

**Issue by lxyer** [baomidou/mybatis-plus#2594]
### 当前使用版本(必填,否则不予处理)

3.3.1.tmp

### 重现步骤(如果有就写完整)
使用@TableField(typeHandler = FastjsonTypeHandler.class)保存是没有问题的,但是在查询的时候,不能把数据库中的json数组映射成Java对象数组.
![image](https://user-images.githubusercontent.com/17336748/84340826-2a574400-abd4-11ea-8b81-d52f0905a596.png)
![image](https://user-images.githubusercontent.com/17336748/84340836-2e836180-abd4-11ea-9dae-ea5867334a00.png)

**Comment by miemieYaho** [comment]
mp的typehandler不认泛型
