### ISSUE TITLE
大数据例如spark job 等一般为啥不用这块呢

### ISSUE THREAD

**Issue by CSuperC** [baomidou/mybatis-plus#2597]
### 当前使用版本(必填,否则不予处理)
3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
一般看来大数据，都是搞个jdbc，不是很明白，为啥不用这么强大的mybatisplus，是因为性能不够么，网上很少有这块的样例

### 重现步骤(如果有就写完整)
略

### 报错信息

略

**Comment by miemieYaho** [comment]
连mybatis都不用为什么要用mp?

**Comment by CSuperC** [comment]
@miemieYaho 为什么他们不用mybatis呢，是因为性能不够么，要是能用的化，结合mybatisplus，感觉会很快就开发啊

**Comment by miemieYaho** [comment]
那你应该去问他们啊

**Comment by CSuperC** [comment]
@miemieYaho 我觉得，可以用的，这就是探讨一下，这issue 不用关闭吧，我感觉没有解决我的问题呢

**Comment by miemieYaho** [comment]
别人用不用是别人的自由,你问我们有啥用?

**Comment by CSuperC** [comment]
@miemieYaho 别人不用，就想问问，你们知道原因不，或者看看有没有人知道，别人不用，我可以写一个spark 调用这块的demo，现在是没搞清楚，为啥，都用jdbc，不用这块，或者，你们这边，还有其他人知道这个问题，我建议open 这块吧，你难道不觉得，要是mp 切进 hive ，和spark，是一个更好的事情么？

**Comment by miemieYaho** [comment]
不觉得
