### ISSUE TITLE
生成器生成无字段表异常

### ISSUE THREAD

**Issue by DR-YangLong** [baomidou/mybatis-plus#2598]
### 当前使用版本(必填,否则不予处理)
com.baomidou:mybatis-plus-generator:3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
由于表中无列导致NPE。
报错类：
com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder
行：401
修改前：
```
if (null != globalConfig.getIdType() && tableInfo.getFields().stream().anyMatch(TableField::isKeyFlag)) {
....
        }
```
修改后：
```
if (null != globalConfig.getIdType() && CollectionUtils.isNotEmpty(tableInfo.getFields()) && tableInfo.getFields().stream().anyMatch(TableField::isKeyFlag)) {
...
        }
```
### 重现步骤(如果有就写完整)
新建一个表，不加列，生成报错。预计与列有关的都会报错。建议加个首选项，能够忽略无列的空表。

### 报错信息
NPE

**Comment by nieqiurong** [comment]
升级至快照版本3.3.3.7-SNAPSHOT，使用教程仓库-> https://mp.baomidou.com/guide/install.html#snapshot。
