### ISSUE TITLE
建议建立交流群

### ISSUE THREAD

**Issue by Q-Qplus1s** [baomidou/mybatis-plus#2599]
建议建立交流群，方便开发者实时交流，提高效率和社区活跃度

**Comment by qmdx** [comment]
Q 群 183066216

**Comment by Q-Qplus1s** [comment]
@qmdx 建议添加到 README 文件上，第一时间能够看到

**Comment by qmdx** [comment]
一直就有 https://github.com/baomidou/mybatis-plus/blob/3.0/README-zh.md
