### ISSUE TITLE
设置mybatis-plus.global-config.banner=false后banner无法关掉

### ISSUE THREAD

**Issue by xiedaijin1018** [baomidou/mybatis-plus#2600]
### 当前使用版本(必填,否则不予处理)
3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
MybatisConfiguration中的GlobalConfig用的是default的，导致application.properties(spring boots项目)设置的mybatis-plus.global-config.banner=false无效。既然这是全局配置为什么在MybatisConfiguration里面又是单独生成一个新的GlobalConfig？

**Comment by miemieYaho** [comment]
用外面那个,MybatisConfiguration里的只是缓存

**Comment by ysymi** [comment]
确实设置了没有效果，依然存在

**Comment by ysymi** [comment]
```
 _ _   |_  _ _|_. ___ _ |    _
| | |\/|_)(_| | |_\  |_)||_|_\
     /               |
                        3.5.2
```
