### ISSUE TITLE
mp为什么支持AND和OR，但不支持not操作？

### ISSUE THREAD

**Issue by chariothy** [baomidou/mybatis-plus#2604]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
没有相关SQL操作

### 重现步骤(如果有就写完整)
没有相关SQL操作

### 报错信息
没有相关SQL操作

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/guide/wrapper.html
