### ISSUE TITLE
mapper文件中重载方法调用错误

### ISSUE THREAD

**Issue by xingya771** [baomidou/mybatis-plus#261]
版本：2.1.8。mapper文件有两个同名的方法，方法A有分页，方法签名为：
`	List<XXX> getXXX(@Param("xxx") String xxx, Pagination page, Integer cpage);
`
方法B无分页：
` List<XXX> getXXX(@Param("xxx") String xxx);
`
两个方法对应的sql不同，无分页的字段多点。
项目中有使用分页插件
`   @Bean
 public PaginationInterceptor paginationInterceptor() {
        return new PaginationInterceptor();
    }
`
经测试发现调用getXXX()实际调用的方法为方法A。改变方法A对应的sql后（增加某列），调用的又变成了方法B。去掉方法A中列后，该现象可重现，且在多个环境中出现同样情况。
初步猜测是分页插件导致的，希望能得到您的帮助，谢谢

**Comment by yuxiaobin** [comment]
mybatis默认是用mapper类名+方法名=statementID（就是sql的id），所以同一个mapper类不能方法名重名。

**Comment by xingya771** [comment]
好的，谢谢
