### ISSUE TITLE
自设主键不识别

### ISSUE THREAD

**Issue by SunGod0508** [baomidou/mybatis-plus#2610]

**Comment by miemieYaho** [comment]
你怎么用的?
新版推荐这么用 https://mp.baomidou.com/guide/id-generator.html#spring-boot

**Comment by nieqiurong** [comment]
填充处理器复写compatibleFillId方法。
```java
@Override
public boolean compatibleFillId() {
    return true;
}
```

**Comment by SunGod0508** [comment]
dto.setId(IdWorker.getNextIdStr());
...
baseMapper.insert(categoryConfig);
以这种形式设置主键的，不是其他方式

**Comment by SunGod0508** [comment]
> 填充处理器复写compatibleFillId方法。
> 
> ```java
> @Override
> public boolean compatibleFillId() {
>     return true;
> }
> ```

没用，不起作用，而且这个方法在我这个版本不推荐的

**Comment by SunGod0508** [comment]
> 你怎么用的?
> 新版推荐这么用 https://mp.baomidou.com/guide/id-generator.html#spring-boot

不是以这种方式的
