### ISSUE TITLE
为什么支持AND和OR，但不支持not操作？

### ISSUE THREAD

**Issue by chariothy** [baomidou/mybatis-plus#2613]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
and / or都是public的，但not是protected的，没法直接用。
尽管not逻辑可以进行逻辑转换到不用not，但有些复杂的条件不用not也很麻烦。
希望能够将not开放出来。

### 重现步骤(如果有就写完整)
and / or都是public的，但not是protected的，没法直接用。

### 报错信息
and / or都是public的，但not是protected的，没法直接用。

**Comment by miemieYaho** [comment]
内部自用,不会开出来
