### ISSUE TITLE
多租户根据id进行逻辑删除的时候更新无效

### ISSUE THREAD

**Issue by linkangsheng** [baomidou/mybatis-plus#2615]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
根据id进行删除，删除失败，影响条数为0

### 重现步骤(如果有就写完整)
这是sql
![图片](https://user-images.githubusercontent.com/18477709/84753963-43a42a00-aff2-11ea-9d69-e3f13bb47040.png)

**Comment by miemieYaho** [comment]
除了select都只支持单参，不要把租户和权限混淆
