### ISSUE TITLE
请问如何获取生成的sql及参数，并断开默认对数据库的连接操作

### ISSUE THREAD

**Issue by iquanzhan** [baomidou/mybatis-plus#2617]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
系统需要对接集成其他框架，只需要获取sql及参数。然后通过http接口的形式操作数据库。
mp中应该如何获取完整的sql，并不进行操作数据库。也就是如何让只mp作为一个sql拼接工具来用

**Comment by miemieYaho** [comment]
mp注入的sql是和mybatis强关联的,你拿到了也没用,你只要拼sql的工具可以看看mybatis的 org.apache.ibatis.jdbc.SQL 类

**Comment by iquanzhan** [comment]
> mp注入的sql是和mybatis强关联的,你拿到了也没用,你只要拼sql的工具可以看看mybatis的 org.apache.ibatis.jdbc.SQL 类

那是不是意味着，mp在项目中将无法使用。麻烦问下在系统已经使用mp的基础上，如何更快的切换为http  传递请求的形式
