### ISSUE TITLE
出现调用了抽象方法的问题和

### ISSUE THREAD

**Issue by poisonduyao** [baomidou/mybatis-plus#2618]
### 当前使用版本(必填,否则不予处理)
最新版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用jdbc4的包出现的

### 重现步骤(如果有就写完整)
   <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>sqljdbc4</artifactId>
            <version>4.0</version>

### 报错信息

java.lang.AbstractMethodError: Method com/microsoft/sqlserver/jdbc/SQLServerResultSet.getObject(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; is abstract

**Comment by miemieYaho** [comment]
这事你应该找mybatis
