### ISSUE TITLE
IService类事务注解value值问题 

### ISSUE THREAD

**Issue by caogy1987** [baomidou/mybatis-plus#2619]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
IService类一些方法加了@Transactional注解，但是如果多个事务管理器，@Transactional注解必须指定value，有什么解决方案？

### 报错信息
![image](https://user-images.githubusercontent.com/13953879/84924680-784fd880-b0fb-11ea-80d1-9262605caa51.png)

**Comment by miemieYaho** [comment]
没有,要么你就自己写个自己的IService
