### ISSUE TITLE
代码生成controller模版错误

### ISSUE THREAD

**Issue by wangpengxiang1996** [baomidou/mybatis-plus#2621]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
逆向生成的时候，使用freemarker模版的时候，生成的controller的requestMapper有两个斜杠

### 重现步骤(如果有就写完整)
同上

### 报错信息
无报错

通过修改模版可以解决

**Comment by nieqiurong** [comment]
升级至快照版本 3.3.3.7-SNAPSHOT，使用教程仓库-> https://mp.baomidou.com/guide/install.html#snapshot。
