### ISSUE TITLE
TypeHandler在collection下无效

### ISSUE THREAD

**Issue by wu-gang** [baomidou/mybatis-plus#2622]
### 当前使用版本(必填,否则不予处理)
最新版：mp: 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

@TableName(value = "xxx_t", autoResultMap = true)
public class XXX   {
        @TableField(typeHandler = XXXXTypeHandler.class)
	private List<ResourceSpecModel> spec;

在单独查询这个数据的时候，typeHandler是生效的，
但是通过自定义SQL查询，有一对多collection时，typeHandler不生效。

### 报错信息

使用了默认的TypeHandler

**Comment by miemieYaho** [comment]
自定义的你怎么用原始的mybatis写就怎么写
