### ISSUE TITLE
findById出现两个结果

### ISSUE THREAD

**Issue by wcgh** [baomidou/mybatis-plus#2624]
### 当前使用版本(必填,否则不予处理)

3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/12288209/84983609-b1c02c80-b16b-11ea-91da-be290ac92154.png)
并发的时候产生了两个不一样的ID,1273423277535051778，1273423277535051779
然后查询的时候根据1273423277535051778去查询，结果出现两个记录。1273423277535051778，1273423277535051779

### 重现步骤(如果有就写完整)
并发产生连续的Long类型的ID,用getById方法去拿数据，拿到两个连续ID的记录。

### 报错信息
![image](https://user-images.githubusercontent.com/12288209/84983726-f21faa80-b16b-11ea-8dba-bab9d746d9ad.png)

**Comment by wcgh** [comment]
通过mysql去查询，也是两个记录。通过getById去查询也是两个记录。
mysql加单引号去查，只有一条记录。getById id+""去查，也只有一条记录。

**Comment by miemieYaho** [comment]
所以这和mp有什么关系?

**Comment by wcgh** [comment]
覆盖了你们的源码就好了，getById(id){id=id+"";...}

**Comment by miemieYaho** [comment]
没用过纯jdbc吗?mp=mybatis底层就是jdbc
