### ISSUE TITLE
setSuperEntityClass 报错 找不到指定的class！请仅在明确确定会有 class 的时候，调用该方法

### ISSUE THREAD

**Issue by takyzheng** [baomidou/mybatis-plus#2625]
### 当前使用版本(必填,否则不予处理)
代码生成器  3.3.2 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
setSuperEntityClass 直接设置字符串全类名报错
之前版本不会出现这种问题，最新版本，此方法过时，新方法要指定 class ？
使用的模板生成的entity对象 ，并没有创建java对象，没有class 怎么指定？

### 重现步骤(如果有就写完整)
strategyConfig.setSuperEntityClass("cn.net.taky.common.BaseEntity");

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: 找不到指定的class！请仅在明确确定会有 class 的时候，调用该方法

**Comment by nieqiurong** [comment]
尽量在有class存在的环境下生成，因为在生成子类的时候，需要排除掉父类字段信息，后面3,3.3版本继续支持你们这种不存在实体类的，需要自行手动设置superEntityColumns来避免子类重复生成父类字段信息。

**Comment by takyzheng** [comment]
好的谢谢，我主要是做了一个通用的 独立的生成器 ，临时我用自定义参数的方式来判断了添加了。。

**Comment by nieqiurong** [comment]
升级至快照版本3.3.3.7-SNAPSHOT，使用教程仓库-> https://mp.baomidou.com/guide/install.html#snapshot。
