### ISSUE TITLE
在3.x版本上,用@EnableConfigurationProperties和@ConfigurationProperties注解读取yml中的配置映射到实体上失败

### ISSUE THREAD

**Issue by jamkpt** [baomidou/mybatis-plus#2626]
### 当前使用版本(必填,否则不予处理)

3.2.0 , 3.3.0, 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
   在3.x版本上,用@EnableConfigurationProperties和@ConfigurationProperties注解读取yml中的配置映射到实体上失败,排除所有依赖包后发现是mybatis_plus引起的

### 重现步骤(如果有就写完整)
在environment看到yml中的配置已经被读取到了,但是映射实体失败
![image](https://user-images.githubusercontent.com/32906114/84989333-17b1b180-b176-11ea-94de-8dda0f2341dd.png)

![image](https://user-images.githubusercontent.com/32906114/84989368-25673700-b176-11ea-8ee2-a660456eea1c.png)
### 报错信息
没有报错

**Comment by miemieYaho** [comment]
什么叫映射到实体?

**Comment by jamkpt** [comment]
使用了fegin的配置情况下,就是读取yml配置信息到配置对象  ,配置对象获取到的参数为null
使用了以下注解
@Configuration(proxyBeanMethods = false)
@EnableFeignClients
@EnableConfigurationProperties(GumingUucProperties.class)
@Data
@ConfigurationProperties

![image](https://user-images.githubusercontent.com/32906114/84996284-a0811b00-b17f-11ea-9f32-f4efbcafe638.png)

![image](https://user-images.githubusercontent.com/32906114/84996345-b5f64500-b17f-11ea-8a3d-1dddae2635f4.png)

**Comment by miemieYaho** [comment]
你这赖mp头上有点牵强啊
