### ISSUE TITLE
为什么我用了querywraper的select 出来的结果还会有其他字段，不过都变成null了是不是哪里配置不对

### ISSUE THREAD

**Issue by sohenk** [baomidou/mybatis-plus#2629]
### 当前使用版本(必填,否则不予处理)
mybatisplus 3.3.2
spring boot 2.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`
 QueryWrapper queryWrapper=new QueryWrapper();
 queryWrapper.select("name");
iAdminUsersService.list(queryWrapper).forEach(System.out::println);
`

出来的结果
`
AdminUsers(username=null, password=null, name=admin, avatar=null, rememberToken=null, createdAt=null, updatedAt=null, status=null, perms=null, nickname=null, gender=null, language=null, city=null, province=null, country=null, openid=null)
AdminUsers(username=null, password=null, name=dsgds, avatar=null, rememberToken=null, createdAt=null, updatedAt=null, status=null, perms=null, nickname=null, gender=null, language=null, city=null, province=null, country=null, openid=null)
`
里面有一堆null，只有select的字段有内容，但是我不想显示其他字段啊。是不是哪里不对

**Comment by miemieYaho** [comment]
请回炉重学编程基础
