### ISSUE TITLE
能不能增加设置字段为空的方法

### ISSUE THREAD

**Issue by wanttoget** [baomidou/mybatis-plus#2632]
其他框架 提供两个方法，一个可以设置字段为空 一个不可以
/**
     * 根据主键更新对象，所以属性都参与更新。也可以使用主键ColumnIgnore来控制更新的时候忽略此字段
     * @param entity
     * @return
     */
    int updateById(T entity);
    /**
     * 根据主键更新对象，只有不为null的属性参与更新
     * @param entity
     * @return
     */
    int updateTemplateById(T entity);

### 当前使用版本(必填,否则不予处理)
3.0

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6

**Comment by JellyBo** [comment]
可以参考这个updateStrategy配置注解 https://mp.baomidou.com/config/#updatestrategy
