### ISSUE TITLE
配置数据安全保护 claims to not accept jdbcUrl

### ISSUE THREAD

**Issue by YellowKang** [baomidou/mybatis-plus#2633]
### 当前使用版本(必填,否则不予处理)

<version>3.3.2</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

配置数据安全保护

### 重现步骤(如果有就写完整)

添加数据安全保护不支持的jdbcUrl,
Url:	mpw:ghF0E/FzfK8KqppYCD+6SLcHfoOgargtmWqVcOq9eAsAiXZmcc0H/Kqci+bBmYH+
username:	mpw:lq5H1ggYHJAo1tXQWnGDEA==
password:	mpw:DcFjr9RzDzfERA9B/9fMMA==

正确相同的Key
IDEA Program arguments = --mpw.key=**********

### 报错信息
java.lang.RuntimeException: Driver com.mysql.jdbc.Driver claims to not accept jdbcUrl, mpw:ghF0E/FzfK8KqppYCD+6SLcHfoOgargtmWqVcOq9eAsAiXZmcc0H/Kqci+bBmYH+

**Comment by qmdx** [comment]
请 debug 下这个类 com.baomidou.mybatisplus.autoconfigure.SafetyEncryptProcessor 看下是否正常解密

**Comment by YellowKang** [comment]
能够正常访问





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qmdx"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 下午3:55
收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;"诗人诉梦"<1360154205@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 配置数据安全保护 claims to not accept jdbcUrl (#2633)





 
请 debug 下这个类 com.baomidou.mybatisplus.autoconfigure.SafetyEncryptProcessor 看下是否正常解密

**Comment by qmdx** [comment]
> 能够正常访问
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"qmdx"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月22日(星期一) 下午3:55 收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 抄送:&nbsp;"诗人诉梦"<1360154205@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [baomidou/mybatis-plus] 配置数据安全保护 claims to not accept jdbcUrl (#2633) 请 debug 下这个类 com.baomidou.mybatisplus.autoconfigure.SafetyEncryptProcessor 看下是否正常解密 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那是搞定了？？

**Comment by YellowKang** [comment]
启动还是报错，但是秘钥配置能读取到------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;qmdx&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月22日(星期一) 晚上10:52
收件人:&nbsp;&quot;baomidou/mybatis-plus&quot;<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;&quot;黄康&quot;<1360154205@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 配置数据安全保护 claims to not accept jdbcUrl (#2633)

**Comment by qmdx** [comment]
未得到反馈，后续反馈打开
