### ISSUE TITLE
代码生成处理boolean类型的is有问题

### ISSUE THREAD

**Issue by wangpengxiang1996** [baomidou/mybatis-plus#2638]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用freemarker模版使用generator功能时，StrategyConfig提供的entityBooleanColumnRemoveIsPrefix属性不生效

### 重现步骤(如果有就写完整)
mysql创建一张表，创建一个字段为bit名字为isAaa的字段，使用代码生成，生成的实体get方法报错

### 报错信息
生成过程不报错，生成实体内容报错

通过在TableField类的getCapitalName方法增加判断即可解决

**Comment by huayanYu** [comment]
解决方法都有了何不提交一个PR参与进来。

**Comment by wangpengxiang1996** [comment]
> 解决方法都有了何不提交一个PR参与进来。

电脑不联网，拿手机提的issues
