### ISSUE TITLE
ID_WORKER_STR 可否增加个 带前缀？

### ISSUE THREAD

**Issue by zhangmz0223** [baomidou/mybatis-plus#264]
想采取加入前缀+ID_WORKER_STR 来搭配使用。
例如：
UserID = U973913147540852737
Mall = M973913147540852720

大部分使用的是业务做标识。
@TableId(value = "user_id", type = IdType.ID_WORKER_STR ,prefix="U")

**Comment by qmdx** [comment]
经过 组织内部 讨论 觉得这个需求无意义，个性化的需求不适合加入在框架层面。多谢建议

**Comment by zhangmz0223** [comment]
@qmdx 好的。
