### ISSUE TITLE
代码生成器功能

### ISSUE THREAD

**Issue by hjljy** [baomidou/mybatis-plus#2640]
### 当前使用版本(必填,否则不予处理)

最新

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当前代码生成器无法直接生成开发当中常用的Entity对应的VO或者说DTO，希望能够默认提供一个简单的DTO生成。

当前我个人的做法是通过自定义属性以及修改模板实现的。

**Comment by qmdx** [comment]
请自定义生成模板注入参考文档 https://mybatis.plus/guide/generator.html
