### ISSUE TITLE
配置配置动态数据源时，整合druid，查询sql时提示was not registered for synchronization because synchronization is not active

### ISSUE THREAD

**Issue by mythology2xk** [baomidou/mybatis-plus#2643]
### 当前使用版本(必填,否则不予处理)
mybatis-plus使用3.3.2版本dynamic-datasource-spring-boot-starter使用3.1.1版本
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
测试service和mapper的crud功能时，控制台提示信息：
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@520f630b] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@45d5ba1f] will not be managed by Spring
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@520f630b]
### 报错信息
不算报错。sql还是会正常执行， 我想知道导致这个问题的原因是什么，会有什么影响？

**Comment by miemieYaho** [comment]
用shiro了?

**Comment by mythology2xk** [comment]
> 用shiro了?

没有，就只是 用了 dynamic-datasource-spring-boot-starter， 我设置了两个数据源，执行查询的时候，就提示这个问题。必须要加注解@Transactional 才会提示 
Creating a new SqlSession
Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0]
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@3738934] will be managed by Spring
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0]

**Comment by miemieYaho** [comment]
这是没代理到事务的问题,百度搜使用shiro事务失效,然后自己排查

**Comment by xiehuanx** [comment]
> ### 当前使用版本(必填,否则不予处理)
> mybatis-plus使用3.3.2版本dynamic-datasource-spring-boot-starter使用3.1.1版本
> 
> ### 该问题是如何引起的？(确定最新版也有问题再提!!!)
> 测试service和mapper的crud功能时，控制台提示信息： Creating a new SqlSession SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@520f630b] was not registered for synchronization because synchronization is not active JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@45d5ba1f] will not be managed by Spring Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@520f630b]
> 
> ### 重现步骤(如果有就写完整)
> ### 报错信息
> 不算报错。sql还是会正常执行， 我想知道导致这个问题的原因是什么，会有什么影响？



> > 用shiro了?
> 
> 没有，就只是 用了 dynamic-datasource-spring-boot-starter， 我设置了两个数据源，执行查询的时候，就提示这个问题。必须要加注解@transactional 才会提示 Creating a new SqlSession Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0] JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@3738934] will be managed by Spring Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0] Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0] Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0]

老哥你是怎么解决的

**Comment by xiehuanx** [comment]
@

> > 用shiro了?
> 
> 没有，就只是 用了 dynamic-datasource-spring-boot-starter， 我设置了两个数据源，执行查询的时候，就提示这个问题。必须要加注解@transactional 才会提示 Creating a new SqlSession Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0] JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@3738934] will be managed by Spring Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0] Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0] Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@2f8528a0]

@mythology2xk 老哥你是怎么解决的
