### ISSUE TITLE
多数据源情况下的关键词自动转义问题

### ISSUE THREAD

**Issue by hepengju** [baomidou/mybatis-plus#265]
主数据源: MySQL, 第二数据源: Oracle. (采用Spring的AbstractRoutingDataSource)

表中有字段名称为name和type, 导致关键词自动转义为`name`,`type`, 切换到Oracle数据源后查询发送的SQL语句仍然为`name`,`type`, 导致报错ORA-00911: invalid character.

问题1: 如何关闭关键词自动转义?
通过分析DBType类, 发现有些数据库比如oracle,db2的转义设置为null, 因此我处在spring配置文件中将dbType修改为oracle后, 虽然mysql也没有了转义,但两个倒是都可以运行了.

问题2: 数据源切换后, 关键词转义怎么可以设置为随之改变?

**Comment by yuxiaobin** [comment]
不能，你还是分开定义2个SessionFactory吧
不然sql只生成一次，切换不同数据库会有问题

**Comment by qmdx** [comment]
2个SessionFactory  不同数据库会自动转义
