### ISSUE TITLE
分页接口IPage的分页条件condition可以进行SQL注入

### ISSUE THREAD

**Issue by BrokenAnkh** [baomidou/mybatis-plus#2650]
### 当前使用版本(必填,否则不予处理)
3.0.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
将sql语句当做com.baomidou.mybatisplus.core.metadata.IPage的condition Map的key值传入,可直接拼入SQL,然后SQL会被直接执行

**Comment by miemieYaho** [comment]
实际上condition目前并没有什么用,就算有什么用默认的page也并没有实现该方法,就算最后都有用了,也不应该是mp来验证参数的合法性

**Comment by neozo** [comment]
> 实际上condition目前并没有什么用,就算有什么用默认的page也并没有实现该方法,就算最后都有用了,也不应该是mp来验证参数的合法性

这个condition在实际项目中还是有很多场景会用到，为什么取消了？能分享下思路吗
