### ISSUE TITLE
mappedStatement占用内存较多

### ISSUE THREAD

**Issue by anic** [baomidou/mybatis-plus#2651]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用mybatisplus后，初始没什么问题，随着表的增多，达到300多个表，在做jvm内存调优时发现最大的Object为MybatisConfiguration中的mappedStatement，占了近50M内存。

![image](https://user-images.githubusercontent.com/916562/85935307-d2ce0d80-b921-11ea-8473-615f9acea27f.png)

![image](https://user-images.githubusercontent.com/916562/85935326-fe50f800-b921-11ea-9150-c7dc5d24bfdc.png)

分析原因，是因为默认会对每个表/mapper绑定一系列的默认方法，在表数目较多时，一些不常用的方法如selectObjs就会显得多余。虽然可以使用SqlInjector减少默认提供的方法数目，但是依旧占用内存较为明显。请问是否有较好的方法和机制进行优化？

**Comment by miemieYaho** [comment]
没有,这是mybatis的东西

**Comment by flyfeifei66** [comment]
> ### 当前使用版本(必填,否则不予处理)
> mybatis-plus 3.1.1
> 
> ### 该问题是如何引起的？(确定最新版也有问题再提!!!)
> 使用mybatisplus后，初始没什么问题，随着表的增多，达到300多个表，在做jvm内存调优时发现最大的Object为MybatisConfiguration中的mappedStatement，占了近50M内存。
> 
> ![image](https://user-images.githubusercontent.com/916562/85935307-d2ce0d80-b921-11ea-8473-615f9acea27f.png)
> 
> ![image](https://user-images.githubusercontent.com/916562/85935326-fe50f800-b921-11ea-9150-c7dc5d24bfdc.png)
> 
> 分析原因，是因为默认会对每个表/mapper绑定一系列的默认方法，在表数目较多时，一些不常用的方法如selectObjs就会显得多余。虽然可以使用SqlInjector减少默认提供的方法数目，但是依旧占用内存较为明显。请问是否有较好的方法和机制进行优化？
> 
> ### 重现步骤(如果有就写完整)
> ### 报错信息

用的什么工具分析的？

**Comment by Royal520** [comment]
jprofile
