### ISSUE TITLE
新版mybatis-plus 为什么会出现部分表的schame无效，这个bug隐藏的很深啊，试了多种方法都没办法，也没相关说明

### ISSUE THREAD

**Issue by airesgit** [baomidou/mybatis-plus#2653]
### 当前使用版本(必填,否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/49652424/85936428-5a6d4980-b92d-11ea-9c44-28346d9eccc8.png)
jiu's就是很简单的表插入做的测试，表结构都类似，但是部分表就会出现schame无法使用，而且sql不会动态的去除null值

![image](https://user-images.githubusercontent.com/49652424/85936439-7f61bc80-b92d-11ea-93a3-04d164114fc5.png)
![image](https://user-images.githubusercontent.com/49652424/85936442-88eb2480-b92d-11ea-97ce-fb7253f3e51f.png)
同样配置，同样的库，另外的表是有的而且也会去动态去除null，也是单单入库操作
![image](https://user-images.githubusercontent.com/49652424/85936461-b6d06900-b92d-11ea-89cc-2965790335d4.png)

![image](https://user-images.githubusercontent.com/49652424/85936484-df586300-b92d-11ea-8a60-f7ef199a8a7c.png)

Mapper 也没什么不同
![image](https://user-images.githubusercontent.com/49652424/85936491-f4cd8d00-b92d-11ea-9f35-2edf490ad8a7.png)
![image](https://user-images.githubusercontent.com/49652424/85936495-feef8b80-b92d-11ea-8fa8-1e1bd38372be.png)
![image](https://user-images.githubusercontent.com/49652424/85936513-19296980-b92e-11ea-848d-35c285710439.png)

### 报错信息
不是报错，是schame 无法使用的问题

**Comment by airesgit** [comment]
图片是裂了？还是我这边网速问题

**Comment by miemieYaho** [comment]
看看你的entity

**Comment by airesgit** [comment]
> 看看你的entity

我所有的entity没有用任何注解的，因为是从mybatis切换过来的，另外那张正常的unit表没有注解也是会加上的，是必须要加上吗？我在调试源码的时候，前面进行拼接sqlHelp 类的 tableName是有加schame的，但是后面获取的sql的就没有这个东西
![image](https://user-images.githubusercontent.com/49652424/85937129-37de2f00-b933-11ea-90a1-9c8c17c91e74.png)

**Comment by airesgit** [comment]
![image](https://user-images.githubusercontent.com/49652424/85937146-622fec80-b933-11ea-802f-811848ca3657.png)

**Comment by miemieYaho** [comment]
启动时debug`Insert`这个类看看注入的sql呢

**Comment by airesgit** [comment]
> 启动时debug`Insert`这个类看看注入的sql呢

![image](https://user-images.githubusercontent.com/49652424/85937215-0ca80f80-b934-11ea-9f6c-8dfa6aa01f08.png)
ji就是那个，而且我看sqlHelp里面解析的时候，没有注解tableName，也是会从xml里面拼接的
![image](https://user-images.githubusercontent.com/49652424/85937234-3fea9e80-b934-11ea-9489-803ab2238cbb.png)，后面的sql 提取出来之后就不见了，没有找到是在哪儿进行的拼接处理，但是获取出来之后就没了。在此时配置都是有的
![image](https://user-images.githubusercontent.com/49652424/85937289-bdaeaa00-b934-11ea-8c6f-c929ba116aa0.png)，走到这儿发现sql就是没有schame的了，sql拼接太多实现没找着是哪个
![image](https://user-images.githubusercontent.com/49652424/85937300-d8811e80-b934-11ea-8c45-1ed7e75985ab.png)

**Comment by miemieYaho** [comment]
你用的什么插件?

**Comment by airesgit** [comment]
> 你用的什么插件?

是指哪个，所有mybatis相关插件都是不存在的，springboot2.0.3+druid，具体的其它很多，因为在项目里边
![image](https://user-images.githubusercontent.com/49652424/85937374-64934600-b935-11ea-9dab-f7734fd55b53.png)zhe'ge这个是另外一张表的，sql完全正常

**Comment by miemieYaho** [comment]
你都debug到了表名初始化那里了,你倒是看看为什么你那个表表名不正确啊

**Comment by airesgit** [comment]
> 你都debug到了表名初始化那里了,你倒是看看为什么你那个表表名不正确啊

![image](https://user-images.githubusercontent.com/49652424/85937816-95757a00-b939-11ea-8be2-66920c9fc518.png)
找了，没找到boundSql是在什么时候赋值进去的

**Comment by miemieYaho** [comment]
https://user-images.githubusercontent.com/49652424/85937234-3fea9e80-b934-11ea-9489-803ab2238cbb.png这里!

**Comment by airesgit** [comment]
> ![image](https://user-images.githubusercontent.com/49652424/85937234-3fea9e80-b934-11ea-9489-803ab2238cbb.png)
> 这里!

![image](https://user-images.githubusercontent.com/49652424/85938255-3108e980-b93e-11ea-801c-5a70b5a573ba.png)

<script>
INSERT INTO ELE_ARCHIVES.t_photo_collect_record_relation <trim prefix="(" suffix=")" suffixOverrides=",">
id,
<if test="collectGroupId != null">collect_group_id,</if>
<if test="recordGroupId != null">record_group_id,</if>
<if test="relationState != null">relation_state,</if>
<if test="userName != null">user_name,</if>
<if test="userId != null">user_id,</if>
<if test="unitId != null">unit_id,</if>
<if test="unitName != null">unit_name,</if>
<if test="departId != null">depart_id,</if>
<if test="departName != null">depart_name,</if>
<if test="processTime != null">process_time,</if>
</trim> VALUES <trim prefix="(" suffix=")" suffixOverrides=",">
#{id},
<if test="collectGroupId != null">#{collectGroupId},</if>
<if test="recordGroupId != null">#{recordGroupId},</if>
<if test="relationState != null">#{relationState},</if>
<if test="userName != null">#{userName},</if>
<if test="userId != null">#{userId},</if>
<if test="unitId != null">#{unitId},</if>
<if test="unitName != null">#{unitName},</if>
<if test="departId != null">#{departId},</if>
<if test="departName != null">#{departName},</if>
<if test="processTime != null">#{processTime},</if>
</trim>
</script>
那里都是正常的，到后面拼接sql的script的时候也是正常的，但是最终的sql是不正常的，这个最终赋参的地方我没找着在哪块

**Comment by miemieYaho** [comment]
初始化正常那就要看你用了什么插件把sql改了

**Comment by airesgit** [comment]
> 初始化正常那就要看你用了什么插件把sql改了

解析脚本参数赋值是在哪块做的，数据源操作都用的plus，没有其它的插件，而且有部分表又是正常的，都是简单的 mapper调用insert 方法，解析脚本参数赋值是在哪个类做的，没找着这个类，是不是这里有问题

**Comment by miemieYaho** [comment]
mp只是注入sql,剩下的都是原生mybatis的事

**Comment by airesgit** [comment]
> mp只是注入sql,剩下的都是原生mybatis的事

解决了，因为是从原本的mybatis切换过来的，mybatis处理的时候是以xml为准的，会将mp生成的script替换掉

**Comment by airesgit** [comment]
> mp只是注入sql,剩下的都是原生mybatis的事

![image](https://user-images.githubusercontent.com/49652424/85939632-ba71e900-b949-11ea-9c43-a4011417923f.png)

**Comment by airesgit** [comment]
有一个配置哪怕mapper里面没有和xml的映射，这个类在判断有这个文件的时候就会加载里面的sql进来，所以并没有用开始解析的sql，以前单纯使用mybatis的时候如果没有mapper接口对应的映射这个xml定义的好像是没用的（哪怕不删），建议这个可以做下优化处理

**Comment by miemieYaho** [comment]
就这样的,xml写了以xml为准
