### ISSUE TITLE
统一数据返回格式设计是否合理？

### ISSUE THREAD

**Issue by sunshixiong789** [baomidou/mybatis-plus#2654]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

http://www.ruanyifeng.com/blog/2018/10/restful-api-best-practices.html

![image](https://user-images.githubusercontent.com/31101988/85937340-1b42f680-b935-11ea-8636-0188f3a4afb0.png)

restful规则中别把错误封装到200状态码中，mybatis-plus封装的R.class感觉不符合restful。想知道一种微服务api设计中的一种最佳设计方案，应该怎么弄。确实这样qianduan前端需要每次都判断还是很烦人的。

### 重现步骤(如果有就写完整)

是否

**Comment by yuxiaobin** [comment]
个人喜好，这个200对前端友好
你也可以自己封装
