### ISSUE TITLE
saveOrUpdateBatch(T t)不能用自定义的唯一索引，只能使用id主键索引，引发重复插入唯一索引

### ISSUE THREAD

**Issue by ItYunTeng** [baomidou/mybatis-plus#2657]
### 当前使用版本(必填,否则不予处理)
version 3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
list中存在既要更新的又要插入的时，就会出现
列（伪代码）
list.add(a) // a在数据库中已存在
list.add(b) // b在数据中不存在
a和b不同
执行
saveOrUpdateBatch(Collection t) 唯一键异常

### 报错信息
唯一索引重复

**Comment by miemieYaho** [comment]
不用id主键索引就自己重写

**Comment by ItYunTeng** [comment]
我想问的是框架的后续版本中能不通过entity的注解机制自行实现唯一索引字段

**Comment by miemieYaho** [comment]
不会
