### ISSUE TITLE
SpringMVC如何启用逻辑删除

### ISSUE THREAD

**Issue by liushangch** [baomidou/mybatis-plus#2658]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目架构使用的SpringMVC，找不到相关demo资料

**Comment by miemieYaho** [comment]
字段加上注解,xml配置[参考](https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-quickstart-springmvc/src/main/resources/spring.xml)

**Comment by liushangch** [comment]
谢谢，找到了
