### ISSUE TITLE
Page中的condition为什么要设置为transient呢？

### ISSUE THREAD

**Issue by qinaichen** [baomidou/mybatis-plus#266]
在分页查询的时候，我时常会传输一些筛选条件，这时用condition字段会非常方便，新版本设置为transient，请问为什么要这样设置？

**Comment by qmdx** [comment]
这个不会对你传入产生影响吧？ 这是控制 json 对外序列化输出忽略

**Comment by qinaichen** [comment]
前端的参数是这样的

```
param:{  
     total:0,
     current:1,
     size:20,
    condition:{
          name:''
    }
}
```
这样在spring的controller中，我直接使用一个Page对象，就能接收到前端的数据了，最新的版本中condition字段被设置为transient,所以我不太明白为什么要这样设置，您是有什么特殊的考虑吗？
```
@ResponseBody
@RequestMapping("/listData")
public Result<Object> listUserData(@RequestBody Map<String,Object> param, @RequestBody Page<Users> page){
	
}
```

**Comment by qmdx** [comment]
@qinaichen 你取消 transient 序列化忽略的配置，更多 疑问 你可以 加入我们 QQ 群号:576493122  讨论
