### ISSUE TITLE
整合mybatis3.5.0报错

### ISSUE THREAD

**Issue by elylon1101** [baomidou/mybatis-plus#2660]
### 当前使用版本
mybatis-plus:3.3.2
mybatis: 3.5.0

### 该问题是如何引起的？
启动项目时报错

### 重现步骤
配置好启动就报错

### 报错信息
An attempt was made to call a method that does not exist. The attempt was made from the following location:
com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.getLanguageDriver(MybatisMapperAnnotationBuilder.java:371)
The following method did not exist:
com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;
The method's class, com.baomidou.mybatisplus.core.MybatisConfiguration, is available from the following locations:
    jar:file:/D:/Program%20Files/maven-3.6.3/repository/com/baomidou/mybatis-plus-core/3.3.2/mybatis-plus-core-3.3.2.jar!/com/baomidou/mybatisplus/core/MybatisConfiguration.class
The class hierarchy was loaded from the following locations:
    com.baomidou.mybatisplus.core.MybatisConfiguration: file:/D:/Program%20Files/maven-3.6.3/repository/com/baomidou/mybatis-plus-core/3.3.2/mybatis-plus-core-3.3.2.jar
    org.apache.ibatis.session.Configuration: file:/D:/Program%20Files/maven-3.6.3/repository/org/mybatis/mybatis/3.5.0/mybatis-3.5.0.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of com.baomidou.mybatisplus.core.MybatisConfiguration
Disconnected from the target VM, address: '127.0.0.1:6981', transport: 'socket'
Process finished with exit code 1

**Comment by miemieYaho** [comment]
不要自己定义mybatis相关版本，jar版本冲突
