### ISSUE TITLE
支持not and ，not or的查询

### ISSUE THREAD

**Issue by acyutao** [baomidou/mybatis-plus#2663]
### 当前使用版本(必填,否则不予处理)
<mybatis-plus.version>3.3.0</mybatis-plus.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
queryWrapper如何构建类似下面的查询：
select * from table where not (field_eng_name like 'E%' or field_ch_name like '%主%')

**Comment by zcboy1** [comment]
没有直接的。但是你可以改成下面这样的形式
