### ISSUE TITLE
order by  field

### ISSUE THREAD

**Issue by hjljy** [baomidou/mybatis-plus#2668]
### 当前使用版本(必填,否则不予处理)

最新版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
希望在order by 支持 field函数

主要原因是在使用listbyIds这个方法进行查询的时候，发现返回的数据不是按照传入的ID顺序进行的返回，需要通过field函数进行设置

**Comment by miemieYaho** [comment]
比如?

**Comment by hjljy** [comment]
> 比如?

select  * from table where id in(1,2,5,4) order by field(id,1,2,5,4);   类似这样的order by

**Comment by hcl04** [comment]
![图片](https://user-images.githubusercontent.com/39977647/86085941-04d2a180-bad3-11ea-80d6-f6811ef3543a.png)

**Comment by gaodonghua** [comment]
> > 比如?
> 
> select * from table where id in(1,2,5,4) order by field(id,1,2,5,4); 类似这样的order by

@hjljy   这个问题解决了么 我现在也遇到相应的问题了，如已解决是使用什么方式解决的？希望题主能回答一下

**Comment by miemieYaho** [comment]
你这种属于方言,自己写xml吧
