### ISSUE TITLE
用xml写sql需要重新写resultMap

### ISSUE THREAD

**Issue by bigbugbean** [baomidou/mybatis-plus#2672]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
用xml写sql需要重新写resultMap
什么时候支持引用自动生成的resultMap

**Comment by miemieYaho** [comment]
用不了,mybatis加载顺序决定的

**Comment by bigbugbean** [comment]
用了一个土方法可以实现...把mbp自动生成的resultMap id填上去

**Comment by miemieYaho** [comment]
什么土方法?

**Comment by bigbugbean** [comment]
在自定义的<select resultMap="">中填上把mbp自动生成的resultMap id

**Comment by bigbugbean** [comment]
在自定义的<select resultMap="">中填上把mbp自动生成的resultMap id

**Comment by bigbugbean** [comment]
在自定义的&lt;select resultMap=""&gt;中填上把mbp自动生成的resultMap id

**Comment by miemieYaho** [comment]
仔细看了一下,还真是顺便发现一个史诗级bug

**Comment by miemieYaho** [comment]
又看了一下并没有bug,虽然可以用不过还是不太建议这么用

**Comment by vipcxj** [comment]
@miemieYaho 这个问题还没解决吗？这个plus不就是省事嘛，如果resultMap稍有改动都要自己重新写，还省事个p啊~
