### ISSUE TITLE
关于使用sql拦截器后mybatisplusSelectBatchIds报错 有人遇到过吗？

### ISSUE THREAD

**Issue by xiang-admin** [baomidou/mybatis-plus#2674]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用自定义Interceptor拦截器拦截sql，并向sql中注入条件

### 重现步骤(如果有就写完整)
当拦截器拦截到SelectBatchIds查询时，解析出coll和param1参数之后再放回原sql运行是报错

### 报错信息
by: org.apache.ibatis.binding.BindingException: Parameter '__frch_item_0' not found. Available parameters are [coll, param1]

**Comment by miemieYaho** [comment]
自己写的插件自己负责

**Comment by chuansang12138** [comment]
我也遇到这个问题，入参是collection就会报错  其他情况没问题

**Comment by chuansang12138** [comment]
排到原因了，boundsql的additionalParameters属性没有复制过来
