### ISSUE TITLE
使用typehandler映射json类型的列在mvn test时报错，提示resultMap找不到

### ISSUE THREAD

**Issue by zshnb** [baomidou/mybatis-plus#2675]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如题

### 重现步骤(如果有就写完整)
按照文档字段类型处理器的说明一模一样配置了typeHandler，然后执行mvn test单元测试时调用service.save(T)会报错

### 报错信息
 java.lang.IllegalArgumentException: Result Maps collection does not contain value for com.qiangdong.reader.dao.UserActivityMapper.mybatis-plus_UserActivity
感觉是@tableName(autoResult=true)在mvn test时无法注入，但在idea运行单个测试是可以的

**Comment by nieqiurong** [comment]
是否有多个@SpringBootTest测试用例。

**Comment by zshnb** [comment]
> 是否有多个@ SpringBootTest测试用例。

是的，有多个@Test的测试用例，使用idea运行单个测试用例没问题，但是使用mvn test集成跑所有测试就会报错

**Comment by nieqiurong** [comment]
#2550

**Comment by zshnb** [comment]
> #2550

请问什么时候会合并master呢

**Comment by zshnb** [comment]
3.3.3.2-snapshot没有依赖，请问这是怎么回事呢

**Comment by nieqiurong** [comment]
> 3.3.3.2-snapshot没有依赖，请问这是怎么回事呢

https://mp.baomidou.com/guide/install.html#snapshot

**Comment by zshnb** [comment]
3.4.0版本好像还是有这个问题，是我使用方式不对吗
