### ISSUE TITLE
代码生成器能否分别指定 entity mapper xml controller service 的路径?

### ISSUE THREAD

**Issue by blankhang** [baomidou/mybatis-plus#2677]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
现在的生成器
只支持  XML  和 代码 2个路径配置
希望能支持多module 这种多路径的配置就完美了 谢谢
因为我很多项目都是多module 拆分的结构 
目录不同
entity /mapper /xml 与 controller/service 在不同目录中

### 重现步骤(如果有就写完整)
```java
//代码目录
gc.setOutputDir(projectPath + "/api/web/src/main/java");
// 这里能不能增加成多个目录配置


// xml目录
 // 自定义配置会被优先输出
        focList.add(new FileOutConfig(templatePath) {
            @Override
            public String outputFile(TableInfo tableInfo) {

                    // 自定义输出文件名 ， 如果你 Entity 设置了前后缀、此处注意 xml 的名称会跟着发生变化！！
                    return projectPath + "/api/common/src/main/resources/mapper/oa/" + tableInfo.getEntityName() + "Mapper" + StringPool.DOT_XML;
              }
        });
```

**Comment by superLovezhang** [comment]
// 包配置
        PackageConfig pc = new PackageConfig();
        pc.setModuleName("companyManagement");
        pc.setParent("com.superflower");
        pc.setController("controller");
        pc.setEntity("entity");
        pc.setService("service");
        pc.setMapper("mapper");
        mpg.setPackageInfo(pc);

**Comment by blankhang** [comment]
> // 包配置
> PackageConfig pc = new PackageConfig();
> pc.setModuleName("companyManagement");
> pc.setParent("com.superflower");
> pc.setController("controller");
> pc.setEntity("entity");
> pc.setService("service");
> pc.setMapper("mapper");
> mpg.setPackageInfo(pc);

你这个配置生成后的代码仍然都在  gc.setOutputDir 中
我要的是不同的路径。。。。
我顶级pom 下 多module 每个module 代码路径不一样 你这个不行

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html

- 指定默认模板路径切换如下

```xml
        // 自定义配置会被优先输出
        focList.add(new FileOutConfig(templatePath) {
            @Override
            public String outputFile(TableInfo tableInfo) {
                // 自定义输出文件名 ， 如果你 Entity 设置了前后缀、此处注意 xml 的名称会跟着发生变化！！
                return projectPath + "/src/main/resources/mapper/" + pc.getModuleName()
                        + "/" + tableInfo.getEntityName() + "Mapper" + StringPool.DOT_XML;
            }
        });
```
