### ISSUE TITLE
map-underscore-to-camel-case选项命名是否有误？

### ISSUE THREAD

**Issue by feidegenggao** [baomidou/mybatis-plus#2679]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

通过查询源码，发现开启此选项后，在初始化tableinfo的时候，会把列名做一个：驼峰转下划线的操作
（com.baomidou.mybatisplus.core.toolkit.StringUtils#camelToUnderline）
**### 问题：为什么选项叫做：下划线转驼峰呢？**

### 重现步骤(如果有就写完整)
helloworld工程即可复现。

**Comment by miemieYaho** [comment]
mybatis就是这么映射的
