### ISSUE TITLE
在删除的过程中没有数据也会返回成功！ 建议把等于0去掉！

### ISSUE THREAD

**Issue by js86531255** [baomidou/mybatis-plus#268]
/**
     * <p>
     * 删除不存在的逻辑上属于成功
     * </p>
     *
     * @param result 数据库操作返回影响条数
     * @return boolean
     */
```
    public static boolean delBool(Integer result) {
        return null != result && result >= 0;
    }
```
```
   public static boolean delBool(Integer result) {
        return null != result && result > 0;
    }

```
修改为这样！

**Comment by qmdx** [comment]
看注释啊，删除不存在的逻辑上属于执行成功

**Comment by js86531255** [comment]
恩看到注释了！ 但是建议去掉等于！ 因为在数据库没有数据 或者同时多用户点击删除场景  前台没法判断的时候返回true 根本没法细化的去判断是否删除成功！我重新构建你们源码！

**Comment by qmdx** [comment]
建议写自己的 serviceImpl 基类，重写我们的 delete 返回
