### ISSUE TITLE
mybatis-plus能支持类似updateByPrimaryKeySelective的功能吗

### ISSUE THREAD

**Issue by HenryFlying** [baomidou/mybatis-plus#2683]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
前端查询的时候传了一个UserDo，希望mybatis-plus支持根据Entity实体类直接构建出Wrapper对象，
Entity字段值为null就跳过，值不为null就加入到Wrapper对象中
有点类似mybatis的updateByPrimaryKeySelective功能

**Comment by miemieYaho** [comment]
没有
