### ISSUE TITLE
类中的嵌套对象属性如何用来查询

### ISSUE THREAD

**Issue by nyanpasus** [baomidou/mybatis-plus#2688]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

类似于 mybatis-plus-samples 中的嵌套类
public class Child {

    private Long id;

    private String name;

    private Long laoHanId;

    private Long laoMaId;

    private Man laoHan;

    private Woman laoMa;
}

希望查询时能够使用 laoMa.name这种的属性，在官网查看文档时显示@TableField中有el属性，相当于#{...}，所以写按照Mybatis中的写法@TableField(el="laoMa.name")，
但是在使用时提示
Error:(31, 17) java: cannot find symbol
  symbol:   method el()
  location: @interface com.baomidou.mybatisplus.annotation.TableField

请问这个方法是被废弃了嘛，不知道有没有其他替代方案呢。

**Comment by miemieYaho** [comment]
不支持
