### ISSUE TITLE
类中的字段不加TableField注释也在update中默认拼装了

### ISSUE THREAD

**Issue by zhou470259742** [baomidou/mybatis-plus#269]
实体类中的字段不加@TableField注解反而被通用crud拼装到update语句中了，只有加@TableField(exist = false)才不会拼装进去，我看了下源码mybatis-plus-support-2.1.9中的TableInfoHelper中的172行做了判断，不存在这个注解的时候返回false,不过返回false的时候又在下方进行了拼装，这就导致了不加注解的属性被拼到update得column中，这种设计可能是考虑到类中不是表里的字段比是表里的字段少的多，不过这种设计有点违反习惯，对于正常的逻辑来说应该是加了@TableField注解才会标记为表字段，不加应该就是不标记，只是用来接收查询结果。如果为了保持这个风格，建议可以在全局系统参数中增加一个配置项，类似于field-strategy

**Comment by qmdx** [comment]
设计的初衷 entity 实体 与表 字段 一一对应，非表字段 entityVO 继承 entity 利于维护。不建议实体被污染
