### ISSUE TITLE
column-format: 前缀_%s,全局配置无效，sql打印属性都是null AS 定义属性

### ISSUE THREAD

**Issue by Jorkins** [baomidou/mybatis-plus#2697]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
表列的别名带前缀，如pi_sys_log,全局配置 column-format: pi_%s,实体对象定义sysLog,但是数据库查询属性列全部都是null。

 SELECT pi_id AS id,null AS errorMsg等

![image](https://user-images.githubusercontent.com/6858010/86743507-809c9300-c06b-11ea-8d23-8d4095096689.png)

### 重现步骤(如果有就写完整)

参考链接：https://my.oschina.net/u/4195213/blog/3097208

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by Jorkins** [comment]
没有demo，就是在不加@TableFild前提下，通过全局配置能否正常处理数据库属性映射到实体属性，数据库属性有自己的前缀，视图属性去掉前缀，网上讲全局配置前缀_%s匹配下即可。但是不生效，能否优化下全局配置，要不代码属性加@TableFiled数据库属性，代码就不简洁了。希望能处理个问题！

**Comment by miemieYaho** [comment]
你说不生效那你倒是写个demo给我看看你是怎么不生效的

**Comment by qmdx** [comment]
up给出demo 打开issue
