### ISSUE TITLE
plus可以解决mysql5.7存入时间四舍五入多1秒的情况吗？

### ISSUE THREAD

**Issue by gyjx** [baomidou/mybatis-plus#2704]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mysql5.7 存入时间，默认毫秒会四舍五入导致存入数据库多了1秒，plus有解决方案不让四舍五入吗？

**Comment by miemieYaho** [comment]
没有
