### ISSUE TITLE
继承IService的自定义service接口被mybatis生成代理类，导致通过接口类型依赖注入时报bean实例不唯一

### ISSUE THREAD

**Issue by mxlfyy** [baomidou/mybatis-plus#2708]
不是插件问题

**Comment by zonkidd** [comment]
同遇到这个问题。
debug调试一下，发现自定义的Service实际上为com.baomidou.mybatisplus.core.override.MybatisMapperProxy@65c66fc4
myBatis-Plus版本为3.2.0
我是通过@Resource(name = 'xxServiceImpl')勉强解决的。期待有更好的答案

**Comment by originDoris** [comment]
我也遇到了这个问题，当@MapperScan范围较大时，即使没有实现IService接口，还是会被mybatisplus生成代理类
