### ISSUE TITLE
dubbo跨服务调用，使用QueryWrapper批量删除where条件不生效

### ISSUE THREAD

**Issue by naokeziteng** [baomidou/mybatis-plus#2727]
### 当前使用版本(必填,否则不予处理)

3.3.1(mybatis-plus-boot-starter)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
尝试了最新的3.3.2版本，问题同样出现；
调用BaseMapper的 delete(@Param(Constants.WRAPPER) Wrapper<T> wrapper)方法时，封装的QueryWrapper条件没用生效

### 重现步骤(如果有就写完整)
使用dubbo作为RPC框架,
A服务提供delete(QueryWrapper wrapper)批量删除方法，B服务内封装QueryWrapper，调用A服务的delete方法where条件不生效，生成的sql没有把where条件拼接上(DELETE FROM demo_table);
如果把QueryWrapper的封装放到A服务内部封装，where条件会生效.

**Comment by miemieYaho** [comment]
wrapper不支持进行传输

**Comment by naokeziteng** [comment]
后面会考虑实现这个功能吗?

**Comment by miemieYaho** [comment]
不会
