### ISSUE TITLE
Error: Cannot execute table Method, ClassGenricType not found .

### ISSUE THREAD

**Issue by andychen1555** [baomidou/mybatis-plus#2730]
### 当前使用版本(必填,否则不予处理)

3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用 saveBatch接口报错,serviceImpl中对应mapper和实体类都指定了

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/36066557/87747572-4e86f000-c826-11ea-8fff-1482023f9090.png)
![image](https://user-images.githubusercontent.com/36066557/87747595-5ba3df00-c826-11ea-8e8a-0c761d475a5b.png)
![image](https://user-images.githubusercontent.com/36066557/87747605-63fc1a00-c826-11ea-88b3-fb0ae56b505f.png)

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Cannot execute table Method, ClassGenricType not found .

**Comment by miemieYaho** [comment]
确定最新版也有问题再提!!!

**Comment by andychen1555** [comment]
确定最新版也有问题!!!

**Comment by andychen1555** [comment]
3.3.2

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by andychen1555** [comment]
上面给了啊  类对照关系都有啊

**Comment by miemieYaho** [comment]
你给的无法复现

**Comment by andychen1555** [comment]
启动后 TableInfoHelper, TABLE_INFO_CACHE 没有缓存下来对应的表?

**Comment by andychen1555** [comment]
public static TableInfo getTableInfo(Class<?> clazz) {
        if (clazz == null) {
            return null;
        } else {
            TableInfo tableInfo = (TableInfo)TABLE_INFO_CACHE.get(ClassUtils.getUserClass(clazz));
            if (null != tableInfo) {
                return tableInfo;
            } else {
                **for(Class currentClass = clazz; null == tableInfo && Object.class != currentClass; tableInfo = (TableInfo)TABLE_INFO_CACHE.get(ClassUtils.getUserClass(currentClass))) {**
                    currentClass = currentClass.getSuperclass();
                }

                if (tableInfo != null) {
                    TABLE_INFO_CACHE.put(ClassUtils.getUserClass(clazz), tableInfo);
                }

                return tableInfo;
            }
        }
    }
这一段没获取到表

**Comment by miemieYaho** [comment]
那你就扫描mapper让他初始化啊

**Comment by andychen1555** [comment]
扫了啊  项目里用了多个数据源  没用mp的多数据源配置  会导致这个问题?

**Comment by miemieYaho** [comment]
你自己启动debug看 TableInfoHelper#initTableInfo
