### ISSUE TITLE
【优化建议】逻辑删除

### ISSUE THREAD

**Issue by rcfeng** [baomidou/mybatis-plus#2737]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
建议在QueryWrapper允许方法控制逻辑删除的启用/禁用
比如我现在全局都是逻辑删除，但是部分场景需要物理删除，就需要自己写sql了，如果有这个开关就省心了
相关场景：数据归档

**Comment by miemieYaho** [comment]
没有开关也不会有开关

**Comment by hokaso** [comment]
> 没有开关也不会有开关

真牛逼啊，写代码写魔怔了吗？真是厉害了，我的哥！你们这框架是打算一锤子买卖啊？逻辑删除全局开关，部分场景需要物理删除，这么常见的需求，你们一句‘没有开关也不会有开关’就给打发了？是不是觉得我们这些用框架的人都得按照你们设定的方式来，不能有半点自己的想法？数据归档这种场景不是很常见吗？难道每个用mybatis-plus的人遇到这种需求都得自己写SQL？那要你们这框架干嘛？装饰吗？真是服了，开源项目这么傲慢，迟早药丸！
