### ISSUE TITLE
在插入或者更新一条数据的时候，两个相邻的空格，第一个空格会变成问号

### ISSUE THREAD

**Issue by FeiQiangSheng** [baomidou/mybatis-plus#2738]
### 当前使用版本(必填,否则不予处理)
2.1.9

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版不清楚呢！

### 重现步骤(如果有就写完整)
后台使用insert，或者updatebyId方法插入一个对象。对象的其中一个字段为两个连续的空格，保存后，数据库变化。
![MJS(}~C5T CA~_PL_)QWR6L](https://user-images.githubusercontent.com/49670800/87906296-f9044a80-ca94-11ea-84d3-e5a0d3a28b46.png)
![5Y T%2586LCJ586RJYZWLDH](https://user-images.githubusercontent.com/49670800/87906304-fbff3b00-ca94-11ea-9cf3-6a385d4001e7.png)

### 报错信息
没有报错。

**Comment by FeiQiangSheng** [comment]
![MJS(}~C5T CA~_PL_)QWR6L](https://user-images.githubusercontent.com/49670800/87906503-500a1f80-ca95-11ea-926d-8928a1f8ac0a.png)
![5Y T%2586LCJ586RJYZWLDH](https://user-images.githubusercontent.com/49670800/87906507-513b4c80-ca95-11ea-82fa-e5985875c324.png)

**Comment by miemieYaho** [comment]
具体执行sql的是mybatis

**Comment by FeiQiangSheng** [comment]
> 具体执行sql的是mybatis

谢谢哥，大哥洪福齐天，法力无边
