### ISSUE TITLE
SpringMVC listMaps无法将下划线转驼峰，文档中只有SpringBoot版本的解决方案

### ISSUE THREAD

**Issue by github-chr** [baomidou/mybatis-plus#2742]
### 当前使用版本(必填,否则不予处理)
当前使用版本：3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
QueryWrapper queryWrapper = new QueryWrapper();
queryWrapper.select("user_id,inviter_user_id");
userBcoinService.listMaps(queryWrapper);

### 重现步骤(如果有就写完整)
无法将下划线转为驼峰

**Comment by miemieYaho** [comment]
把 放进 `Configuration`里面去

**Comment by github-chr** [comment]
这种方法需要自定义转换器，有更为Caused by: java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.apache.ibatis.reflection.wrapper.ObjectWrapperFactory' for property 'objectWrapperFactory': no matching editors or conversion strategy found<bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean"&gt;
   <property name="dataSource" ref="dataSource" /&gt;
   <property name="configuration" ref="configuration" /&gt;
   <property name="mapperLocations" value="classpath*:mybatis/*.xml" /&gt;
</bean&gt;
<bean id="globalConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig"&gt;
</bean&gt;
<bean id="configuration" class="com.baomidou.mybatisplus.core.MybatisConfiguration"&gt;
   <property name="objectWrapperFactory" value="com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory"/&gt;
</bean&gt;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miemieYaho"<notifications@github.com&gt;; 
发送时间: 2020年7月20日(星期一) 晚上9:54
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "子木倾然"<513572443@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] SpringMVC listMaps无法将下划线转驼峰，文档中只有SpringBoot版本的解决方案 (#2742)





 
把 放进 Configuration里面去
 
&mdash;

**Comment by github-chr** [comment]
这种方法需要自定义转换器，有更为简易的方式吗？Caused by: java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.apache.ibatis.reflection.wrapper.ObjectWrapperFactory' for property 'objectWrapperFactory': no matching editors or conversion strategy found<bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean"&gt;
   <property name="dataSource" ref="dataSource" /&gt;
   <property name="configuration" ref="configuration" /&gt;
   <property name="mapperLocations" value="classpath*:mybatis/*.xml" /&gt;
</bean&gt;
<bean id="globalConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig"&gt;
</bean&gt;
<bean id="configuration" class="com.baomidou.mybatisplus.core.MybatisConfiguration"&gt;
   <property name="objectWrapperFactory" value="com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory"/&gt;
</bean&gt;



------------------ 原始邮件 ------------------
发件人: "miemieYaho"<notifications@github.com&gt;; 
发送时间: 2020年7月20日(星期一) 晚上9:54
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;; 
抄送: "子木倾然"<513572443@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [baomidou/mybatis-plus] SpringMVC listMaps无法将下划线转驼峰，文档中只有SpringBoot版本的解决方案 (#2742)





 
把 放进 Configuration里面去
