### ISSUE TITLE
自动填充功能-更新指定填充字段，无法实际更新字段

### ISSUE THREAD

**Issue by huangfei1101** [baomidou/mybatis-plus#2743]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用自动填充功能，字段上加上注解@TableField(fill=FieldFill.INSERT_UPDATE)，同时实现com.baomidou.mybatisplus.core.handlers.MetaObjectHandler接口，在重写的方法public void updateFill(MetaObject metaObject) {} ，根据官方文档的用法来调用com.baomidou.mybatisplus.core.handlers.MetaObjectHandler#strictUpdateFill(org.apache.ibatis.reflection.MetaObject, java.lang.String, java.lang.Class<T>, java.lang.Object)去更新相应的字段，实际上改函数最后会走到com.baomidou.mybatisplus.core.handlers.MetaObjectHandler#strictFillStrategy，该函数默认有值不覆盖，导致更新无效

### 重现步骤(如果有就写完整)
按照官方文档，自动填充字段那一节的用法即可重现

**Comment by miemieYaho** [comment]
你想覆盖就自己重写那个方法
