### ISSUE TITLE
mybatis二级缓存和多租户

### ISSUE THREAD

**Issue by happyycm** [baomidou/mybatis-plus#2745]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用mybatis 二级缓存(Redis)的同时有多租户配置

### 重现步骤(如果有就写完整)

1，配置mybatis二级缓存
2，配置多租户

### 报错信息

mybatis 二级缓存生成的cache key不包含多租户筛选信息
比如 日志输出的sql为：
select * from table_name where deleted = 0 and tenant_id=xxx;
二级缓存生成的cache key为：
select * from table_name where deleted = 0 ;

导致租户信息错乱。

**Comment by miemieYaho** [comment]
你可以试用 `3.3.3.6-SNAPSHOT`,
[配置方式参考](https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-tenant/src/main/java/com/baomidou/mybatisplus/samples/tenant/config/MybatisPlusConfig.java)

**Comment by happyycm** [comment]
> 你可以试用 `3.3.3.6-SNAPSHOT`,
> [配置方式参考](https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-tenant/src/main/java/com/baomidou/mybatisplus/samples/tenant/config/MybatisPlusConfig.java)

好的，谢谢

**Comment by happyycm** [comment]
> 你可以试用 `3.3.3.6-SNAPSHOT`,
> [配置方式参考](https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-tenant/src/main/java/com/baomidou/mybatisplus/samples/tenant/config/MybatisPlusConfig.java)

暂时没有发现问题，但是请问为什么 setUseDeprecatedExecutor 被标记为 Deprecated，如果必须使用的话。

**Comment by miemieYaho** [comment]
旧的分页和多租户完全移除之后就没这个属性了

**Comment by happyycm** [comment]
> 旧的分页和多租户完全移除之后就没这个属性了

我现在更新到3.3.4了，还需要保留这个设置吗？

`@Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseDeprecatedExecutor(false);
    }`

**Comment by miemieYaho** [comment]
要,以后移除了旧分页这个配置才会移除
