### ISSUE TITLE
配置全局雪花主键，不生效

### ISSUE THREAD

**Issue by cacosen** [baomidou/mybatis-plus#2748]
### 当前使用版本(必填,否则不予处理)
当前使用3.3.2版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
系统老版本是3.1.1，今天改成了3.3.2版本，然后在springboot的yml文件中，配置全局主键策略，不生效。

yml的配置如下：
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

总是提示id为空，没有默认值

**Comment by cacosen** [comment]
补充操作步骤：
从3.1.1升级到3.3.2：
一、修改了maven的依赖版本号
二、yml的配置如下：
mybatis-plus:
global-config:
db-config:
id-type: assign_id
三、把数据库的id从integer改成long，并取消数据库里的id自增

**Comment by cacosen** [comment]
就这么简单的改动，然后雪花算法的id没有出现，
是不是哪里漏了配置？

**Comment by cacosen** [comment]
报错信息如下：

Caused by: java.sql.SQLException: Field 'id' doesn't have a default value
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461)
        at com.alibaba.druid.wall.WallFilter.preparedStatement_execute(WallFilter.java:627)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
        at com.sun.proxy.$Proxy84.update(Unknown Source)
        at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
        at com.sun.proxy.$Proxy160.update(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)

**Comment by miemieYaho** [comment]
你先看看你项目里mp的jar版本是不是有冲突

**Comment by cacosen** [comment]
![image](https://user-images.githubusercontent.com/10444403/88070996-e4fc3e00-cba5-11ea-9aa5-c7c0626c94c0.png)
![image](https://user-images.githubusercontent.com/10444403/88071204-212f9e80-cba6-11ea-96e2-6b2cfbee0c08.png)
![Uploading image.png…]()
没有发现冲突啊，我是多模块的项目

**Comment by cacosen** [comment]
真是太奇怪了，我刚才直接在entity类里记上
@TableId(type = IdType.ASSIGN_ID)
    private Long id;

然后也没有出现效果，一样的报错信息

**Comment by miemieYaho** [comment]
那你看看执行的sql

**Comment by cacosen** [comment]
以下是sql，可以看出plus的多租户功能是生效的，
但是id没有自动注入，帮忙看看哈

### The error occurred while setting parameters
### SQL: INSERT INTO litemall_ext_room (`name`, `count`, topic, tips, add_time, update_time, tenantid) VALUES (?, ?, ?, ?, ?, ?, 'tenantidfromtest')
### Cause: java.sql.SQLException: Field 'id' doesn't have a default value
; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value
org.springframework.dao.DataIntegrityViolationException:
### Error updating database.  Cause: java.sql.SQLException: Field 'id' doesn't have a default value

**Comment by cacosen** [comment]
以下是sql，可以看出plus的多租户功能是生效的，
但是id没有自动注入，帮忙看看哈

The error occurred while setting parameters
SQL: INSERT INTO ext_room (name, count, topic, tips, add_time, update_time, tenantid) VALUES (?, ?, ?, ?, ?, ?, 'tenantidfromtest')
Cause: java.sql.SQLException: Field 'id' doesn't have a default value
; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value
org.springframework.dao.DataIntegrityViolationException:

Error updating database. Cause: java.sql.SQLException: Field 'id' doesn't have a default value

**Comment by miemieYaho** [comment]
你这不是自增嘛,检查你的entity,实在不行那你写个demo出来

**Comment by cacosen** [comment]
是啊，好奇怪，为啥全局配置成assign_id不生效呢？
我的entity是用generator生成的，没有做局部配置啊

public class ExtRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.count
     *
     * @mbg.generated
     */
    private String count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.topic
     *
     * @mbg.generated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.tips
     *
     * @mbg.generated
     */
    private String tips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_room.tenantid
     *
     * @mbg.generated
     */
    private String tenantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.id
     *
     * @return the value of ext_room.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.id
     *
     * @param id the value for ext_room.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.name
     *
     * @return the value of ext_room.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.name
     *
     * @param name the value for ext_room.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.count
     *
     * @return the value of ext_room.count
     *
     * @mbg.generated
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.count
     *
     * @param count the value for ext_room.count
     *
     * @mbg.generated
     */
    public void setCount(String count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.topic
     *
     * @return the value of ext_room.topic
     *
     * @mbg.generated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.topic
     *
     * @param topic the value for ext_room.topic
     *
     * @mbg.generated
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.tips
     *
     * @return the value of ext_room.tips
     *
     * @mbg.generated
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.tips
     *
     * @param tips the value for ext_room.tips
     *
     * @mbg.generated
     */
    public void setTips(String tips) {
        this.tips = tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.add_time
     *
     * @return the value of ext_room.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.add_time
     *
     * @param addTime the value for ext_room.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.update_time
     *
     * @return the value of ext_room.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.update_time
     *
     * @param updateTime the value for ext_room.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.deleted
     *
     * @return the value of ext_room.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.deleted
     *
     * @param deleted the value for ext_room.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_room.tenantid
     *
     * @return the value of ext_room.tenantid
     *
     * @mbg.generated
     */
    public String getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_room.tenantid
     *
     * @param tenantid the value for ext_room.tenantid
     *
     * @mbg.generated
     */
    public void setTenantid(String tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", count=").append(count);
        sb.append(", topic=").append(topic);
        sb.append(", tips=").append(tips);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", tenantid=").append(tenantid);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExtRoom other = (ExtRoom) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getTopic() == null ? other.getTopic() == null : this.getTopic().equals(other.getTopic()))
            && (this.getTips() == null ? other.getTips() == null : this.getTips().equals(other.getTips()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getTenantid() == null ? other.getTenantid() == null : this.getTenantid().equals(other.getTenantid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getTopic() == null) ? 0 : getTopic().hashCode());
        result = prime * result + ((getTips() == null) ? 0 : getTips().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getTenantid() == null) ? 0 : getTenantid().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ext_room
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        name("name", "name", "VARCHAR", true),
        count("count", "count", "VARCHAR", true),
        topic("topic", "topic", "VARCHAR", false),
        tips("tips", "tips", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        tenantid("tenantid", "tenantid", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ext_room
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}

**Comment by cacosen** [comment]
我把配置内容，打印出来了，帮忙看看哪里有问题啊？
sqlSessionFactory和identifierGenerator，是否有问题呢？

MybatisPlusProperties(configLocation=null, mapperLocations=[classpath:/*Mapperokokouter.xml], typeAliasesPackage=null, typeAliasesSuperType=null, typeHandlersPackage=null, checkConfigLocation=false, executorType=null, defaultScriptingLanguageDriver=null, configurationProperties=null, configuration=null, typeEnumsPackage=null, globalConfig=GlobalConfig(banner=true, workerId=null, datacenterId=null, enableSqlRunner=false, dbConfig=GlobalConfig.DbConfig(idType=ASSIGN_ID, tablePrefix=null, schema=null, columnFormat=null, propertyFormat=null, tableUnderline=true, capitalMode=false, keyGenerator=null, logicDeleteField=null, logicDeleteValue=1, logicNotDeleteValue=0, insertStrategy=NOT_NULL, updateStrategy=NOT_NULL, selectStrategy=NOT_NULL), sqlInjector=com.baomidou.mybatisplus.core.injector.DefaultSqlInjector@3e32f37f, superMapperClass=interface com.baomidou.mybatisplus.core.mapper.Mapper, sqlSessionFactory=org.apache.ibatis.session.defaults.DefaultSqlSessionFactory@545b995e, mapperRegistryCache=[], metaObjectHandler=null, identifierGenerator=com.baomidou.mybatisplus.core.incrementer.DefaultIdentifierGenerator@2d5e2da5))

**Comment by cacosen** [comment]
看内容而言，idType=ASSIGN_ID是被正确读取且正确取值了的啊
为啥还是不会自动生成雪花ID呢

**Comment by cacosen** [comment]
entity的内容，也打印出来了，id=null的啊
为啥就是不触发自动注入雪花id呢？？？

ExtRoom [Hash = -1558130689, IS_DELETED=false, NOT_DELETED=false, id=null, name=7, count=7, topic=, tips=, addTime=null, updateTime=null, deleted=null

**Comment by miemieYaho** [comment]
你写个demo出来吧

**Comment by cacosen** [comment]
知道原因了，mp和mbg有冲突不兼容，希望mp可以改进一下，
也谢谢您的解答，谢谢。
