### ISSUE TITLE
没有联合主键的配置

### ISSUE THREAD

**Issue by blueLi0428** [baomidou/mybatis-plus#2749]
### 当前使用版本(必填,否则不予处理)

3.0.7.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我有a,b两张表，b表没有主键，只有a表的id以及项次做联合主键，如果对b两个主键都加上@TableId注解调用提供的insert方法会失败。

**Comment by miemieYaho** [comment]
不支持联合主键,只能有一个属性注解 @TableId

**Comment by blueLi0428** [comment]
> 不支持联合主键，最多只能有一个属性注释解@TableId

好的，非常感谢

**Comment by BlackTeaChan** [comment]
> 不支持联合主键，最多只能有一个属性注解@TableId

但是项目启动的时候会很慢啊，一堆警告
