### ISSUE TITLE
lambdaQuery 中怎么使用的函数

### ISSUE THREAD

**Issue by frowhy** [baomidou/mybatis-plus#2755]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

lambdaQuery 查询时想使用一些函数，比如内置的`sum`、`max`等和自己自定义的函数，但是不知道该怎么使用，如果用 query 是可以的，我想知道 lambdaQuery 是否支持使用函数或者别名，如果支持该如何使用？Thanks♪(･ω･)ﾉ

**Comment by miemieYaho** [comment]
不支持

**Comment by frowhy** [comment]
> 不支持

这就很蛋疼了，使用起来其实不方便。。。
