### ISSUE TITLE
数据库postgresql操作数组使用函数&&时被自动转义成AND

### ISSUE THREAD

**Issue by willwayzz** [baomidou/mybatis-plus#2756]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用Postgresql数组操作符&&的查询语句，在自动构建count语句时会被mybatis-plus自动转义成AND

### 重现步骤(如果有就写完整)
操作符配置如下
![image](https://user-images.githubusercontent.com/25221000/88173052-893cbe00-cc54-11ea-8de2-232fa43d9806.png)

![image](https://user-images.githubusercontent.com/25221000/88172531-b9379180-cc53-11ea-82e1-ef3b943867ad.png)

### 报错信息

如上图，自定义count语句可以解决该问题，应该不是mybatis的问题，这应该属于一个bug吧，我看到有之前有[帖子](https://github.com/baomidou/mybatis-plus/issues/1926)描述过该问题，但未解决就被关闭了，辛苦大佬们看一下！！！

**Comment by miemieYaho** [comment]
jsqlparser的问题

**Comment by miemieYaho** [comment]
https://github.com/JSQLParser/JSqlParser/releases

**Comment by willwayzz** [comment]
> jsqlparser的问题

多谢，修改jsqlparser的版本到3.2解决了该问题，mybatis-plus是不是可以升级下pom依赖呢？

**Comment by qmdx** [comment]
> > jsqlparser的问题
> 
> 多谢，修改jsqlparser的版本到3.2解决了该问题，mybatis-plus是不是可以升级下pom依赖呢？

会的请关注 mp 发版
