### ISSUE TITLE
UpdateWrapper的where条件部分转换为QueryWrapper

### ISSUE THREAD

**Issue by idlesysman** [baomidou/mybatis-plus#2757]
```java
int update(@Param("et") T entity, @Param("ew") Wrapper<T> updateWrapper)
```
有什么办法能把这个方法生成的where条件转化为QueryWrapper.

##### 需求场景
当调用这个方法时利用其条件查询出相关字段更新缓存

**Comment by miemieYaho** [comment]
updayewrapper本身就是querywrapper只是没有其独有的方法，如果你用了乐观锁并且entity内带上了乐观锁值会在updatewrapper内追加乐观锁条件

**Comment by idlesysman** [comment]
好的，谢谢

**Comment by idlesysman** [comment]
@miemieYaho 没对啊。
我是想把UpdateWrapper转换为QueryWrapper，直接强制转换报错的。(QueryWrapper<XX>)updateWrapper;

**Comment by idlesysman** [comment]
`java
QueryWrapper<XXXX> queryWrapper=new QueryWrapper<XXXX>;
UpdateWrapper<XXXX> updateWrapper=new UpdateWrapper<XXXX>;
//希望把queryWrapper和updateWrapper合并为一个QueryWrapper
QueryWrapper<XXXX> finalQueryWrapper=queryWrapper ∪ updateWrapper
`

**Comment by miemieYaho** [comment]
不能
