### ISSUE TITLE
mybatis引入plus

### ISSUE THREAD

**Issue by yocaning** [baomidou/mybatis-plus#2758]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

原mybatis升级，引入plus导致

### 重现步骤(如果有就写完整)
原mybatis项目
引入mybatis-plus 3.3.2
初步判断是版本问题，排序依赖还是没用，有没有友好升级的解决方案提供

### 报错信息
Error creating bean with name 'sqlSessionFactory' defined in class path resource

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples
