### ISSUE TITLE
从3.1.1升级到3.3.2后，logback异常

### ISSUE THREAD

**Issue by cacosen** [baomidou/mybatis-plus#2759]
### 当前使用版本(必填,否则不予处理)
当前使用3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
只是从3.1.1升级到3.3.2，然后重新部署项目，
项目启动时可以正常走logback输入日志，
但是启动后所有操作，都没法输出日志了。

没有改过系统的其他配置，升级plus前是正常的。

**Comment by cacosen** [comment]
下面是我的logback配置：

<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">
    <contextName>logback</contextName>
    <property name="log.path" value="logs" />

    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>debug</level>
        </filter>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${log.path}/log.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${log.path}/log-%d{yyyy-MM-dd}.log</fileNamePattern>
        </rollingPolicy>

        <encoder>
            <pattern>%date %level [%thread] %logger{36} [%file : %line] %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="error" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${log.path}/error.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${log.path}/error-%d{yyyy-MM-dd}.log</fileNamePattern>
        </rollingPolicy>

        <encoder>
            <pattern>%date %level [%thread] %logger{36} [%file : %line] %msg%n
            </pattern>
        </encoder>
        
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>ERROR</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
    </appender>

    <root level="ERROR">
        <appender-ref ref="console" />
        <appender-ref ref="file" />
        <appender-ref ref="error" />
    </root>
    <logger name="org.mybatis" level="INFO" />
    <logger name="org.springframework" level="INFO" />
    <logger name="org.testplus.core" level="INFO" />
   <logger name="org.testplus.db" level="INFO" />
    <logger name="org.testplus.admin" level="INFO" />
    <logger name="org.testplus.wx" level="INFO" />
    <logger name="org.testplus" level="INFO" />
</configuration>

**Comment by cacosen** [comment]
现象二：
如果我在yml中新添加如下配置，就可以输出日志，但是只有sql，没有任何其他执行的日志输出：

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

**Comment by cacosen** [comment]
我的3.1.1版本是不需要添加yml的log配置的，是可以正常输出的。

**Comment by cacosen** [comment]
我的logback版本是1.2.3

**Comment by miemieYaho** [comment]
你写个demo出来看看吧

**Comment by cacosen** [comment]
哈哈，又是遇到你来解答，稍等哈我弄一个新项目出来给你

**Comment by cacosen** [comment]
已解决。谢谢。
