### ISSUE TITLE
逻辑删除存在事务问题

### ISSUE THREAD

**Issue by github24518** [baomidou/mybatis-plus#2762]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
（1）新建一个聚合service方法。
（2）开启required级别事务
 （3）调用mybaits plus官方形式的 Iservice接口的新增接口（自动返回主键ID），
    立刻使用IService接口的getById()方法。entity对象未使用逻辑删除字段是ok的。使用逻辑删除字段就不行了
  （4）显然，这是一个事务问题！

**Comment by miemieYaho** [comment]
逻辑删除是已经预先注入进sql里的，等于你自己写的XML里的sql

**Comment by github24518** [comment]
> 逻辑删除是已经预先注入进sql里的，等于你自己写的XML里的sql

![Uploading image.png…]()

**Comment by miemieYaho** [comment]
?
