### ISSUE TITLE
使用lambdaQueryWrapper多条件判断查询时，可能会导致空指针

### ISSUE THREAD

**Issue by liaozan** [baomidou/mybatis-plus#2763]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用lambdaQueryWrapper多条件判断查询时，可能会导致空指针

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/26990889/88284285-bdc97c00-cd1f-11ea-9df8-baf7e145bf1a.png)
在传入到`public Children eq(boolean condition, R column, Object val) `方法之前,val需要被先计算，如果值为空，可能会导致空指针

**Comment by miemieYaho** [comment]
你自己处理

**Comment by minglea** [comment]
如果要自己处理方法第一个参数还加什么布尔判断呢？希望可以改正
