### ISSUE TITLE
SpringBoot整合MyBasit-Plus3.3.2启动项目扫描不了mapper接口

### ISSUE THREAD

**Issue by hjp123-h** [baomidou/mybatis-plus#2765]
### 当前使用版本(必填,否则不予处理)

MyBasit-Plus 3.3.2 velocity 2.2 SpringBoot 2.2.1.RELEASE

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用springboot2.2.1.RELEASE整合MyBasit-Plus，配置了扫描包，使用了代码生成器，启动报错

### 重现步骤(如果有就写完整)

springboot2.2.1.RELEASE整合mybatis-plus3.3.2，使用代码生成器生成eduTeacherServiceImpl继承ServiceImpl以及eduTeacherMapper继承BaseMapper <>，运行项目报错

### 报错信息

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eduTeacherServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eduTeacherMapper' defined in file [E:\Online school\service\service_edu\target\classes\com\hjp123\eduservice\mapper\EduTeacherMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

**Comment by qmdx** [comment]
应该是你配置问题 ，参考 https://github.com/baomidou/mybatis-plus-samples
