### ISSUE TITLE
有提供动态的批量写入与修改吗

### ISSUE THREAD

**Issue by LczFrist** [baomidou/mybatis-plus#2766]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库字段有默认值，但是在使用saveBatch方法时报字段不能为null

**Comment by qmdx** [comment]
在 serviceImpl 层继承即可使用

**Comment by LczFrist** [comment]
继承什么？不是太明白。能否详细说一下？继承什么，调用哪个方法，是可以动态的写入

**Comment by LczFrist** [comment]
> 在 serviceImpl 层继承即可使用

继承什么？不是太明白。能否详细说一下？继承什么，调用哪个方法，是可以动态的写入

**Comment by qmdx** [comment]
> > 在 serviceImpl 层继承即可使用
> 
> 继承什么？不是太明白。能否详细说一下？继承什么，调用哪个方法，是可以动态的写入

https://mybatis.plus/guide/crud-interface.html#service-crud-%E6%8E%A5%E5%8F%A3
