### ISSUE TITLE
mybatis-plus typehandler映射为list<T>时在IPage分页查询时无效(T is not String)

### ISSUE THREAD

**Issue by Smaillife** [baomidou/mybatis-plus#2768]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

pre: 确定order表的trip字段有正确的json值

`IPage<Order> findOrders(Page page, @Param("order") Order order);`

`<select id="findOrders" resultType="order" parameterType="order">
        SELECT
            前其他代码省略.......
            trip,
            后其他代码省略.......
        from
        t_order
    </select>`

`@Data
@Accessors(chain = true)
@TableName(value = "t_order", autoResultMap = true)
public class Order implements Serializable {

前其他代码省略.......
    @TableField(value = "TRIP", typeHandler = JacksonTypeHandler.class)
    private List<Trip> trip;
后其他代码省略.......

}`

page result：
{
"code": 200,
"data": {
"rows": [
{
......
"trip": null,
.......
}
],
"total": 1
}
}

getbyid查询、更新时均正常，在ipage查询中trip is null ?!!!!

### 重现步骤(如果有就写完整)

Talk is cheep，show with code！

**Comment by miemieYaho** [comment]
你自己写的sql需要你自己写resultmap用
