### ISSUE TITLE
3.2版本升级嵌套查询实现不了

### ISSUE THREAD

**Issue by Jorkins** [baomidou/mybatis-plus#2769]
### 重现步骤(如果有就写完整)
3.1.2版本如下语法可以使用，升级最新版本嵌套API更新导致嵌套多条件查询无法使用
             queryWrapper.and(j -> {
                            j = j.like(field, vals[0]);
                            for (int k = 1; k < vals.length; k++) {
                                j = j.or().like(field, vals[k]);
                            }
                            return j;
                        });

**Comment by miemieYaho** [comment]
消费函数
