### ISSUE TITLE
分页插件的count优化问题

### ISSUE THREAD

**Issue by dpp66** [baomidou/mybatis-plus#2777]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库类型为PG，前端传入如下sql:
select count(id) as num from info_table where time_stamp>now()- INTERVAL '15 S'
在使用mybatis plus分页插件自带的count优化时，会自动将count(id) as num 替换成count(1),
此时会出现一种问题，当count(1)为0时，下一步真正的sql直接就不执行了，以为没有数据，
其实我这个sql的结果永远会有一个结果 num和 num的值。
我目前的解决办法就是把mybait plus的count()优化关闭page.setOptimizeCountSql(false);或者自己写一个针对这种类型sql的单独count()语句。
不清楚，有没有更好的方式？

**Comment by qmdx** [comment]
这就是最简单的解决办法，有些 sql 确实无法自动处理解决
