### ISSUE TITLE
达梦数据库代码自动生成实体字段重复

### ISSUE THREAD

**Issue by pengxingwang** [baomidou/mybatis-plus#2778]
### 当前使用版本(必填,否则不予处理)
3.3.2.1-SNAPSHOT

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
达梦数据库代码自动生成实体字段重复

比如会生成多个ID字段

![image](https://user-images.githubusercontent.com/26086540/88612767-857ac280-d0be-11ea-9557-85316235278c.png)

### 重现步骤(如果有就写完整)
maven引入如下:
```
<mybatis-plus-boot-starter.version>3.3.2.1-SNAPSHOT</mybatis-plus-boot-starter.version>
<repository>
    <id>snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```

**Comment by qmdx** [comment]
希望你能够帮助完善 达梦数据库的生成器部分 sql 然后 PR  苞米豆团队暂无该数据库无法测试支持
