### ISSUE TITLE
saveBranch或者其他批量操作事务超时

### ISSUE THREAD

**Issue by huanghuanghui** [baomidou/mybatis-plus#2780]
### 当前使用版本(必填,否则不予处理)

3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当saveBranch或者其他批量操作的，数据量较大的时候，会事务超时，当前使用mybatis-plus做数据同步，branch任务超过2W就会导致事务超时退出，如何去除jar包中的@Transactional事务
![image](https://user-images.githubusercontent.com/32832946/88616621-32593d80-d0c7-11ea-8e96-f432be656aa6.png)

### 报错信息
Lock wait timeout exceeded; try restarting transaction

**Comment by miemieYaho** [comment]
去除不了

**Comment by huanghuanghui** [comment]
谢谢，刚刚看了下，可以调用设置batchSize的重载方法，分片提交就好了
