### ISSUE TITLE
3.3.2 版本在 Gradle 构建环境下存在依赖 spring-boot-dependencies 行为

### ISSUE THREAD

**Issue by Devifish** [baomidou/mybatis-plus#2782]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 使用 Gradle 构建环境下 最新版的mybatis-plus存在依赖 spring-boot-dependencies 行为
导致见解依赖了所有spring-boot-dependencies 指定版本的依赖包  如kotlin标准库、 freemarke等

### 重现步骤(如果有就写完整)
使用 Gradle 构建环境  导入最新版的mybatis-plus

**Comment by Devifish** [comment]
依赖结构如图
![image](https://user-images.githubusercontent.com/26357254/88634510-09e23b00-d0e9-11ea-86b3-2815a4880dc5.png)

**Comment by nieqiurong** [comment]
#2514
