### ISSUE TITLE
同样的一份无重复的数据，saveBatch批量插入的时候，报自定义唯一索引冲突，后面就会一直随机报其中一个索引冲突，但是重启服务后问题就不会出现

### ISSUE THREAD

**Issue by mana392** [baomidou/mybatis-plus#2784]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
线上批量插入的时候，某次出现后就一直报唯一索引冲突，重启后就没事

### 报错信息
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '001910-2020-07-28' for key 'XXXXXXXX'

**Comment by miemieYaho** [comment]
无法复现

**Comment by mana392** [comment]
@miemieYaho 表里两个字段自定义唯一索引，准备大概两百条数据，没有重复的，saveBatch批量插入后，不删除表数据，再次批量插入一次，这时候肯定报唯一索引冲突，然后再把表数据清掉，再次同样的数据插入一次，就会出现唯一索引冲突的异常，一直插入的话，每次报错的索引key还不一样，我目前是100%必现，但是只要重启下服务，就不会报错。

**Comment by yanzhaoyl** [comment]
主键是string类型执行saveorupdate的时候 提示 违反唯一约束,  正常应当是 执行 更新操作才是  ,我使用的版本是 3.3.2,  和 这个 问题 类似

**Comment by yanzhaoyl** [comment]
> @miemieYaho 表里两个字段自定义唯一索引，准备大概两百条数据，没有重复的，saveBatch批量插入后，不删除表数据，再次批量插入一次，这时候肯定报唯一索引冲突，然后再把表数据清掉，再次同样的数据插入一次，就会出现唯一索引冲突的异常，一直插入的话，每次报错的索引key还不一样，我目前是100%必现，但是只要重启下服务，就不会报错。

你可以试着看下这个, 提交的问题与你的问题可能类似, 可以更新下版本 尝试下 是否解决你的问题
https://github.com/baomidou/mybatis-plus/issues/2788

**Comment by yanzhaoyl** [comment]
> ### 当前使用版本(必填,否则不予处理)
> 3.3.1
> 
> ### 该问题是如何引起的？(确定最新版也有问题再提!!!)
> 线上批量插入的时候，某次出现后就一直报唯一索引冲突，重启后就没事
> 
> ### 重现步骤(如果有就写完整)
> ### 报错信息
> 由以下原因引起：java.sql.SQLIntegrityConstraintViolationException：键“ XXXXXXXX”的条目“ 001910-2020-07-28”重复

你可以试着看下这个, 提交的问题与你的问题可能类似, 可以更新下版本 尝试下 是否解决你的问题
https://github.com/baomidou/mybatis-plus/issues/2788

**Comment by Kevin-pop** [comment]
我也遇到了类似情况，设置唯一键，删除部分行后，用saveBatch插入唯一键相同的数据会报唯一键冲突。仅在重启springboot服务才能插入，且进行删除后又会出现该情况。
未在数据库链接url加上rewriteBatchedStatements=true&时上述操作中saveBatch会报DuplicateKeyException但数据可以插入；添加rewriteBatchedStatements=true&后报错同时数据并不会插入

**Comment by qmdx** [comment]
> 我也遇到了类似情况，设置唯一键，删除部分行后，用saveBatch插入唯一键相同的数据会报唯一键冲突。仅在重启springboot服务才能插入，且进行删除后又会出现该情况。
> 未在数据库链接url加上rewriteBatchedStatements=true&时上述操作中saveBatch会报DuplicateKeyException但数据可以插入；添加rewriteBatchedStatements=true&后报错同时数据并不会插入

这个和 mp 没有关系吧很明显是数据库自增出现了问题，建议用分布式 id

**Comment by Kevin-pop** [comment]
> > 我也遇到了类似情况，设置唯一键，删除部分行后，用saveBatch插入唯一键相同的数据会报唯一键冲突。仅在重启springboot服务才能插入，且进行删除后又会出现该情况。
> > 未在数据库链接url加上rewriteBatchedStatements=true&时上述操作中saveBatch会报DuplicateKeyException但数据可以插入；添加rewriteBatchedStatements=true&后报错同时数据并不会插入
> 
> 这个和 mp 没有关系吧很明显是数据库自增出现了问题，建议用分布式 id

并没有使用自增，主键使用mp提供的雪花算法id和自己写的雪花算法，DuplicateKeyException出现在另外的一个复合唯一键，我尝试过将已删除的数据作为list，用saveBatch会报错，最后使用list.foreach save（T entity）逐个保存，能保存但也会报错，现在打算写insert ignore语句

**Comment by Carol0** [comment]
目前遇到类似问题，请问后面怎么解决的啊？

**Comment by Kevin-pop** [comment]
你好，这是来自QQ邮箱的自动回复邮件。我将在看到邮件后尽快给你回复。---------江俊杰中山大学资讯管理学院The School Of Information Management,Sun Yat-sen UniversityMobile：13431790563
