### ISSUE TITLE
使用自定义ID生成器，批量保存saveBatch时，主键是同一个插入提示违反唯一约束

### ISSUE THREAD

**Issue by Libin6666** [baomidou/mybatis-plus#2785]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库对应实体类的id设置为的雪花算法自动生成，批量提交时发现id是同一个，这样插入数据库肯定报违反唯一约束

### 报错信息
![image](https://user-images.githubusercontent.com/38720407/88773474-bb01d780-d1b4-11ea-81b7-aeab3d64d95b.png)

**Comment by miemieYaho** [comment]
这是你自己set的

**Comment by Libin6666** [comment]
找到问题了，是实体类用的单例，造成属性覆盖，会认为是同一个对象实体。改为普通的new 就好了
