### ISSUE TITLE
代码生成器可否关闭默认实现

### ISSUE THREAD

**Issue by Sheer-Cold** [baomidou/mybatis-plus#2789]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 重现步骤(如果有就写完整)
使用文档中Demo的代码生成器

现在业务中，Mapper,Service,Controller 三层，无需接口在Impl，是否有选项可以关闭先接口再实现的功能？

**Comment by qmdx** [comment]
可以选择关闭你不需要生成的类及文件，如果模板不是你要的可以自定义

https://mybatis.plus/guide/generator.html
