### ISSUE TITLE
最新版支持数据库情况咨询

### ISSUE THREAD

**Issue by liangzhi2019** [baomidou/mybatis-plus#2791]
想咨询下，目前最新版本支持polardb、oceanbase吗？

**Comment by miemieYaho** [comment]
支持不支持的仅体现在分页以及代码生成上,分页的话就算不能自动识别数据库也可以指定`dbType`来使用对应数据库的分页方言

**Comment by liangzhi2019** [comment]
> 支持不支持的仅体现在分页以及代码生成上,分页的话就算不能自动识别数据库也可以指定`dbType`来使用对应数据库的分页方言

了解。谢谢

**Comment by qmdx** [comment]
目前 oceanbase 已经是支持的，至于 polardb 查询资料 https://www.aliyun.com/product/polardb 可知  polardb 完全兼容 mysql / oracle 语法，根据你的驱动 mp 会选择对应的 dbType 为 mysql  或者 oracle
