### ISSUE TITLE
[3.3.2]使用代码生成器 生成的 实体类, 缺少 id 字段

### ISSUE THREAD

**Issue by yanzhaoyl** [baomidou/mybatis-plus#2792]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://user-images.githubusercontent.com/59864824/89151835-6aafbe80-d594-11ea-98c9-6ef80f49959e.png)

### 重现步骤(如果有就写完整)

使用代码生成器 生成的 实体类, 缺少 id 字段,  不知道是不是我 哪里操作错了,没生成  还是 其他原因呢

### 报错信息

无

**Comment by miemieYaho** [comment]
你好好看看配置,别看都不看具体配置都什么意思就cv

**Comment by yanzhaoyl** [comment]
> 你好好看看配置，别看都不看具体配置都什么意思就cv
好的, 不好意思哈 我去好好看看
