### ISSUE TITLE
多表连接分页查询速度非常慢

### ISSUE THREAD

**Issue by blueLi0428** [baomidou/mybatis-plus#2796]
### 当前使用版本(必填,否则不予处理)

2.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

分页查询时，映射速度非常慢，在SSMS中直接用SQL查询速度两秒左右，但是通过程序查询会花一分钟以上的时间
数据库为SqlServer2019。

其他单表分页查询返回结果的没有问题

### 报错信息
时间过长会自动关闭链接

**Comment by miemieYaho** [comment]
你自己写的sql = 你用mybatis写的sql,mp不会去执行sql的

**Comment by blueLi0428** [comment]
在SSMS中执行的控制台打印出来的SQL，两者没有任何区别，个人觉得是因为映射的时候出了问题，因为超时自动关闭连接的时候，控制台会打印出来查询的结果，然后再关闭连接，具体的表结构以及SQL我可以发您邮箱吗？因为公司项目，不方便贴上来。

**Comment by miemieYaho** [comment]
你发我也没用啊，具体sql执行以及结果集封装都是mybatis执行的

**Comment by blueLi0428** [comment]
好吧，那我再试试其他办法😭😭😭
