### ISSUE TITLE
MP多租户问题

### ISSUE THREAD

**Issue by gengxiangyu** [baomidou/mybatis-plus#2797]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用MP的多租户功能，自己写的xml也会在后面拼接上租户条件，导致自己写的sql有别名，mp识别不到别名的问题，除非用相关注解或者配置该mapper的全限定类名才能去掉多租户条件，所以就想这个问题能不能改下，跟逻辑删除一样，逻辑删除就没这个问题，根据实体类有多租户字段来进行拦截拼接该多租户条件，谢谢

**Comment by gengxiangyu** [comment]
应该是自己写的xml不需要拦截拼接租户条件，使用MP单表操作时需要

**Comment by miemieYaho** [comment]
这俩功能实现方式不一样，不可能做到你说的那样

**Comment by gengxiangyu** [comment]
> 这俩功能实现方式不一样，不可能做到你说的那样

那自己写的SQL只能通过注解或配置全类名Mapper的方式去掉多租户了吗

**Comment by miemieYaho** [comment]
嗯
