### ISSUE TITLE
mp导出500条限制修改后自动填充失效的问题

### ISSUE THREAD

**Issue by jiushijiang** [baomidou/mybatis-plus#2798]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在导出数据的时候，我发现有最多500条的限制，所以配置了一下SqlSession，但是配置完成后发现原来自动填充功能失效了，查阅官网发现问题是出在sqlSession上

- **SqlSessionFactory不要使用原生的，请使用MybatisSqlSessionFactory**

### 重现步骤(如果有就写完整)
	@Bean(name = "sqlSession")
	public SqlSessionTemplate sqlSession(@Autowired DataSource dataSource) throws Exception {
		MybatisSqlSessionFactoryBean factoryBean = new MybatisSqlSessionFactoryBean();
		factoryBean.setDataSource(dataSource);
		MybatisConfiguration mybatisConfiguration = new MybatisConfiguration();

		mybatisConfiguration.setDefaultScriptingLanguage(MybatisXMLLanguageDriver.class);
		mybatisConfiguration.setJdbcTypeForNull(JdbcType.NULL);
		mybatisConfiguration.setMapUnderscoreToCamelCase(true);//开启下划线转驼峰

		/*不限制最大导出量*/
		paginationInterceptor.setLimit(-1);
		paginationInterceptor.setCountSqlParser(new JsqlParserCountOptimize(true));
		mybatisConfiguration.addInterceptor(paginationInterceptor);
		factoryBean.setConfiguration(mybatisConfiguration);
		return new SqlSessionTemplate(factoryBean.getObject());

	}

### 报错信息
现在系统已经重置回去了，我想问一下能不能在不改变原有代码的基础上解决mp导出最大限制的问题

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-pagination/src/main/java/com/baomidou/mybatisplus/samples/pagination/config/MybatisPlusConfig.java
用 3.3.3.7-SNAPSHOT, 新分页默认没有限制
