### ISSUE TITLE
3.3.2版本mybatis-plus-generator和mybatis-plus-boot-starter不兼容

### ISSUE THREAD

**Issue by kingwsi** [baomidou/mybatis-plus#2799]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

同时引入mybatis-plus-generator和mybatis-plus-boot-starter依赖后启动报错

### 重现步骤(如果有就写完整)

MybatisMapperAnnotationBuilder第288行，configuration.getDefaultResultSetType();
没有getDefaultResultSetType()这个方法

### 报错信息

The following method did not exist:

com.baomidou.mybatisplus.core.MybatisConfiguration.getDefaultResultSetType()Lorg/apache/ibatis/mapping/ResultSetType;

**Comment by miemieYaho** [comment]
自己检查你项目mybatis的依赖版本冲突

**Comment by chencong-plan** [comment]
同样遇到这个问题 3.1.0里面288行是没有这句话的

**Comment by chencong-plan** [comment]
@kingwsi 降版本到 3.3.0 应该就可以了

**Comment by kingwsi** [comment]
> @kingwsi降版本到3.3.0应该就可以了

嗯 我也是降级解决的，但是模板文件也略有不同，要修改一下

**Comment by qmdx** [comment]
打开抽时间验证

**Comment by qmdx** [comment]
经过测试无法重现，请给出你的 demo

**Comment by kingwsi** [comment]
我又去测试了一下，定位到问题了，复现方式如下
同时使用3.3.2版本的依赖

**Comment by kingwsi** [comment]
我又去测试了一下，定位到问题了，复现方式如下：
### 1.新建springBoot项目，同时使用3.3.2版本的依赖
```xml
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>
        </dependency>
        <!--代码生成器-->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.2</version>
        </dependency>
```
#### 2.写一个mapper，并使用注解方式写个查询
```java
@Mapper
public interface UserMapper extends BaseMapper<User> {
    @Select("SELECT * FROM user WHERE id = #{id}")
    User selectUserById(@Param("id") String id);
}
```
### 3.启动项目
nested exception is java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.MybatisConfiguration.getDefaultResultSetType()Lorg/apache/ibatis/mapping/ResultSetType;

**Comment by chencong-plan** [comment]
@qmdx  你可以看看上面那个版本里面 MybatisMapperAnnotationBuilder第288行，configuration.getDefaultResultSetType();
没有getDefaultResultSetType()这个方法 问题就出现在这里
