### ISSUE TITLE
关于逻辑删除sql拼接不同版本结果不一致的问题

### ISSUE THREAD

**Issue by Linda-pan** [baomidou/mybatis-plus#2800]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在使用3.1.1版本正常后，切换至最新版出的问题。

### 重现步骤(如果有就写完整)

对象entity里面有字段如下。

`  @TableLogic(value = "N", delval = "Y")
    private String isDeleted;`

在3.1.1版本中调用TableInfo的getLogicDeleteSql方法
`   if (tableInfo.isLogicDelete()) {
            sb.append(tableInfo.getLogicDeleteSql(true, false));
 }`
得到结果 ` AND is_deleted='N'`
而在3.3.2版本调用后得到的是 ` AND is_deleted='Y'`。

看新版getLogicDeleteSql方法的注释
   * @param isWhere      是否需要的是逻辑删除值
formatLogicDeleteSql
  * @param isWhere true: logicDeleteValue, false: logicNotDeleteValue
貌似也没有说明，如果isWhere传值false则只查询逻辑删除的数据

### 报错信息

无

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/89628737-5428a080-d8cf-11ea-824f-44d58616f4e6.png)
只有逻辑删除的时候才会传false
