### ISSUE TITLE
maven 中央仓库 mybatis-plus 3.3.1和3.3.2  jar  错误

### ISSUE THREAD

**Issue by yunzaiqintian** [baomidou/mybatis-plus#2801]
### pom文件中引入
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus</artifactId>
			<version>3.3.2</version>
		</dependency>

### 重现步骤(如果有就写完整)
下载下来的包不足1KB,本以为是阿里云代理仓库的错误，后面直接去[中央仓库](https://repo1.maven.org/maven2/com/baomidou/mybatis-plus/3.3.2/)下载，发现这两个版本的jar  上传确实有问题

### 报错信息
中央仓库下载的mybatis-plus-3.3.2.jar  中不包含任何class,导致程序运行出现classnotfount  异常

**Comment by qmdx** [comment]
请先看下文档 http://mybatis.plus

**Comment by yunzaiqintian** [comment]
> 请先看下文档 http://mybatis.plus 快速开始部分

快速开始部分的依赖好像都是springboot  的，如果不是springboot 的项目，只能使用2.X的版本吗？我之前的项目引用2.X  是正常的，升级下载的jar 在中央仓库只有1KB  不到是以后不支持非springboot 的方式构建吗？

**Comment by qmdx** [comment]
> > 请先看下文档 http://mybatis.plus 快速开始部分
> 
> 快速开始部分的依赖好像都是springboot 的，如果不是springboot 的项目，只能使用2.X的版本吗？我之前的项目引用2.X 是正常的，升级下载的jar 在中央仓库只有1KB 3.X是不支持非springboot 的方式构建吗？

支持请仔细看文档
