### ISSUE TITLE
执行逻辑删除方法，MP内部将delete语句转update语句，但是MetaObjectHandler公共字段填充拦截未进入

### ISSUE THREAD

**Issue by hong1989** [baomidou/mybatis-plus#2802]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在执行逻辑删除的时候，由于MP内部会将delete语句转update来进行软删除执行，原本想法是通过MetaObjectHandler拦截处理，在软件删除的时候，同步更新下表中的update_time字段，但是实际运行发现，如果是软删除操作，MetaObjectHandler拦截方法根本不会进来，而如果是其他正常的更新操作，都是能正常进来的。想确认下，目前这种情况，是否是mybatis-plus内部特意处理的，将软删除的操作与普通的update操作区分开来了。如果想要软删除的update语句也进入MetaObjectHandler拦截器，需要如何配置修改?

**Comment by miemieYaho** [comment]
填充是填充到entity的.
https://mp.baomidou.com/guide/logic-delete.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
