### ISSUE TITLE
代码生成器，当PackageConfig不设置moduleName时，生成的Controller请求路径出现@RequestMapping("//user")

### ISSUE THREAD

**Issue by zuobian502** [baomidou/mybatis-plus#2804]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator 版本使用 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当PackageConfig不设置moduleName时

### 重现步骤(如果有就写完整)
自动生成代码，当PackageConfig不设置moduleName时，生成的Controller请求路径出现@RequestMapping("//user")

### 报错信息
生成的Controller请求路径出现两条斜线，效果：@RequestMapping("//user")

**Comment by nieqiurong** [comment]
#2621
