### ISSUE TITLE
使用updateById方法更新逻辑删除字段更新不了

### ISSUE THREAD

**Issue by angiely1115** [baomidou/mybatis-plus#2805]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

如果使用remove方法，公共填充字段不起作用，于是使用使用updateById方法更新逻辑删除字段却发现更新不了

**Comment by miemieYaho** [comment]
就是这么设计的，看文档里逻辑删除里的问题

**Comment by angiely1115** [comment]
谢谢，希望在使用lambda的时候也可以自动更新填充字段
