### ISSUE TITLE
查询列表时，如何限制只查询n条数据，不想通过分页实现，分页会多查询一次数据库

### ISSUE THREAD

**Issue by rewind-weijx** [baomidou/mybatis-plus#2812]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

查询列表时，想通过limit的方式去对数据进行查询，不想用page处理，page在查询时会先查询一次total count，t会造成一部分时间损耗

### 重现步骤(如果有就写完整)

不是bug，是一个新的需求

### 报错信息

没有报错

**Comment by miemieYaho** [comment]
page里有属性配置不查count

**Comment by huayanYu** [comment]
.last("limit 20")
