### ISSUE TITLE
IPage接口里的List<OrderItem> orders();能改成泛型List<? extends OrderItem> orders();吗

### ISSUE THREAD

**Issue by ancienter** [baomidou/mybatis-plus#2815]
IPage接口里的List<OrderItem> orders();能改成泛型List<? extends OrderItem> orders();吗

**Comment by miemieYaho** [comment]
为什么?

**Comment by ancienter** [comment]
不方便继承后自定义，既然IPage设计的目的是被继承，那IPage里面的东西也应该是，比如OrderItem应该设计为IOrderItem，并且列表应该使用List<? extends IOrderItem> orders();


leesam@leesam.cn
 
发件人： miemieYaho
发送时间： 2020-08-21 15:17
收件人： baomidou/mybatis-plus
抄送： ancienter; Author
主题： Re: [baomidou/mybatis-plus] IPage接口里的List<OrderItem> orders();能改成泛型List<? extends OrderItem> orders();吗 (#2815)
为什么?

**Comment by miemieYaho** [comment]
ipage是可以xml取值所以实现才有意义

**Comment by ancienter** [comment]
增加继承的友好性设计，对原本的功能并没有影响，而且可以更灵活地通过继承来自定义自己的分页对象，希望可以考虑增加
