### ISSUE TITLE
如果实现and ( a=b or a1=c or a2=d ...)

### ISSUE THREAD

**Issue by nxycdl** [baomidou/mybatis-plus#2817]
### 当前使用版本(必填,否则不予处理)

3.1.2

### 重现步骤(如果有就写完整)

for (Register r : rlist){
                        wrapper.apply(" jzdate between {0} and {1}" , DateUtil.beginOfDay(r.getHosdate()),DateUtil.endOfDay(r.getHosdate())).or();
                    }

想实现 where name ='x' and ( jzdate between date and date or jzdate between date and date1 or ....) 
实际的效果where name ='x' and jzdate between date and date or jzdate between date and date1 or ....
如果把or 里面的内容使用括号扩起来.

**Comment by miemieYaho** [comment]
文档里面有

**Comment by nxycdl** [comment]
只找到where 条件固定的写法. 这种带有for 循环递归的怎么处理?
