### ISSUE TITLE
建议 能添加强制索引拼接功能吗?

### ISSUE THREAD

**Issue by yang3350380** [baomidou/mybatis-plus#2820]
能添加强制索引拼接功能吗?
你们好
mybatis-plus非常好用
点赞
在实际使用中发现没有支持强制索引的功能
能建议添加这个功能吗?
或者现在是否能够实现?

**Comment by miemieYaho** [comment]
啥东西?

**Comment by yang3350380** [comment]
> > 啥东西?
> 
> 他的意思应该是 强制sql走索引吧,类似于这种
> select customer,count(1) c from upv_1 force index(idx_created)

没错 强制索引啊 还是比较常用的

**Comment by miemieYaho** [comment]
IllegalSQLInnerInterceptor ? 这个不止是强制索引了,如果你只想要强制索引你可以参考这个自己写来用或者pr上来

**Comment by qmdx** [comment]
up

**Comment by xy83918** [comment]
请问关闭是放弃修改还是有新的feature支持这个功能呢

**Comment by BobCN2017** [comment]
自定义Sql可以实现。但每一次都需要自定义不方便
