### ISSUE TITLE
通用枚举的问题

### ISSUE THREAD

**Issue by 178180793** [baomidou/mybatis-plus#2821]
### 当前使用版本(必填,否则不予处理)

mybatis-plus:3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

框架使用的是spring cloud ，订单服务调用商品服务。

### 重现步骤(如果有就写完整)

问题1
使用的是sping cldoud fegin 作为服务之间的调用。
然后使用的通用枚举在商品服务的时候枚举是生效的。
然后数据到了订单服务，枚举值就变成了空。

问题2
如果一个实体类里面有两个通用枚举，第二个不生效。

### 报错信息

没有报错信息，就是通用枚举值是空的了。

**Comment by miemieYaho** [comment]
?你这不是序列化的事吗?

**Comment by 178180793** [comment]
实体类，和枚举都序列化了啊。还是空的啊。你说的序列化是啥序列化啊？
![image](https://user-images.githubusercontent.com/46117717/90704706-cdf35d80-e2c3-11ea-9d48-ee299544711c.png)
通过fegin调用商品服务回来就变成了空
![image](https://user-images.githubusercontent.com/46117717/90704940-6558b080-e2c4-11ea-99a3-e824ce184de1.png)

就是说，在服务内部是没问题的，然后通过fegin 转换就有了问题。都是同一个实体类接收的返回值。

**Comment by 178180793** [comment]
如果我用implements IEnum<Integer>  这个，fegin传递是没问题的。
但是我用的注解的形式， @EnumValue @JsonValue	//标记响应json值
通过fegin 传递是空值。

**Comment by 178180793** [comment]
@EnumValue @JsonValue 同时运用到code字段上，是可以的。但是分开，@EnumValue在code  @JsonValue  在desc 上是不行的。

**Comment by 178180793** [comment]
![image](https://user-images.githubusercontent.com/46117717/90710848-d2267780-e2d1-11ea-80c5-dda26fc43ff3.png)
@EnumValue @JsonValue同时运用到代码一个字段上，但是为啥过来的值不一样了呢。？2是正确的。3是不正确的啊。

**Comment by miemieYaho** [comment]
http传递正反序列化

**Comment by 178180793** [comment]
http正反序列化没问题的啊

**Comment by 178180793** [comment]
我使用了实现ienum接口了。
