### ISSUE TITLE
for 循环递归嵌套

### ISSUE THREAD

**Issue by nxycdl** [baomidou/mybatis-plus#2824]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查询条件的where 是一个for 循环生产的or语句,如下,查询条件的个数由 list的大小决定.
for (Register r : rlist){
    wrapper.apply(" jzdate between {0} and {1}" , DateUtil.beginOfDay(r.getHosdate()),DateUtil.endOfDay(r.getHosdate())).or();
}

按照上面的写法变成where 1=1 and jzdate betwen :1 and :2 or jzdate between :3 and :4 or jzdate between .....

实际想实现啊是for循环后变成 where 1=1 and(  jzdate betwen :1 and :2 or jzdate between :3 and :4 or jzdate between .....) 这种的. 不知道怎么在 lambdaQuery 中使用for循环. 官方例子 userWrapper.and(wrapper -> wrapper.like("login_name", keys) 这种都是已经能确定有几个where 条件的,使用链式调用的.怎么结合for循环调用.

**Comment by miemieYaho** [comment]
自己去想
