### ISSUE TITLE
分页条件构建有问题，我已经设置了字段查询判断策略为not_empty，为啥分页还是会构建进去(默认分页方法)

### ISSUE THREAD

**Issue by zxiaozhou** [baomidou/mybatis-plus#2826]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1. 我配置文件设置了字段查询判断策略为not_empty，但调用IService中分页却没有效果，我时间的确是null,但查询sql居然是构建出来的

### 重现步骤(如果有就写完整)
1. queryWrapper构建截图
![image](https://user-images.githubusercontent.com/62740686/90784503-ebf8a680-e333-11ea-878e-40965133bdaf.png)
2. 构建出来sqlri日志
![image](https://user-images.githubusercontent.com/62740686/90784529-f31fb480-e333-11ea-82b3-b6534b46da4e.png)
3. 配置文件查询策略
![image](https://user-images.githubusercontent.com/62740686/90784584-03379400-e334-11ea-80ec-dba1f6343eb3.png)

**Comment by miemieYaho** [comment]
那个策略只对wrapper内的entity有效
