### ISSUE TITLE
更新3.4.0版本 @PostConstruct注解初始化数据的方法全报错了

### ISSUE THREAD

**Issue by CrazyLionL** [baomidou/mybatis-plus#2832]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 重现步骤(如果有就写完整)
所有使用@PostConstruct注解 初始化数据的操作 全都报 org.apache.ibatis.binding.BindingException: Invalid bound statement (not found) 异常了

### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)

**Comment by CrazyLionL** [comment]
切换回3.3.0版本是没问题的

**Comment by miemieYaho** [comment]
那你就换成 CommandLineRunner 吧

**Comment by CrazyLionL** [comment]
能换早就换了

**Comment by CrazyLionL** [comment]
连jdk的注解都不支持  我真是服了你们了
