### ISSUE TITLE
使用mybatis-plus查询时，拼接wrapper条件时，需要使用到exists，但目前exists可以支持where条件吗？

### ISSUE THREAD

**Issue by wanganlee** [baomidou/mybatis-plus#2838]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当前使用的是最新版，正常开发的需求

### 重现步骤(如果有就写完整)
就是需要使用exists的场景

### 报错信息
不是报错，是感觉目前好像缺少这块的功能。场景如下：
有两张表A表table_a、B表table_b。A表和B表通过订单号order_no字段进行关联。
现在需要查询A表中的数据，且以B表中的状态字段status进行过滤，伪sql如下：
select * from table_a a  where exists (select b.id from table_b b where a.order_no = b.order_no and b.status = '1' );

现在使用mybatis-plus时，首先需要构造查询条件wrapper：
QueryWrapper<TableA> wrapper = Wrappers.<TableA>query();
wrapper.exists("SELECT id FROM table_b b where **a.order_no** = b.order_no and b.status = '1' "); // 问题来了，这块的exists里面的语句如何拼接？？？这里的 "a.order_no" 如何识别？？？

麻烦帮忙解答一下，十分感谢！

**Comment by miemieYaho** [comment]
那不行,自己写xml 吧
