### ISSUE TITLE
分页插件的count未添加多租户的过滤条件

### ISSUE THREAD

**Issue by kcly3027** [baomidou/mybatis-plus#2840]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

开启多租户插件后，执行page，mp生成的动态count方法未加入租户的过滤条件

**Comment by miemieYaho** [comment]
你怎么用的?

**Comment by kcly3027** [comment]
> 你怎么用的?

感谢，已经解决了addInnerInterceptor的顺序调整后就可以了，把多租户插件调整到最前面
