### ISSUE TITLE
sql查询生成错误

### ISSUE THREAD

**Issue by peter17ji** [baomidou/mybatis-plus#2842]
### 当前使用版本(必填,否则不予处理)
3.3.2 maven版boot starter
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

正常使用发现查不到数据，结果查mysql的查询记录发现语句生成错误

### 重现步骤(如果有就写完整)
pojo片段
    private Date businessDt;//没注解
    private Integer fileType;//没注解
    @TableField(value = "is_analysed",updateStrategy = FieldStrategy.IGNORED)//不加value也错
    private Integer isAnalysed;
使用
 NewestLog = rawDataLogDao.selectOne(
                    Wrappers.lambdaQuery(RawDataLog.class)
                            .eq(RawDataLog::getIsAnalysed, 1)
                            .eq(RawDataLog::getFileType, 1)
                            .orderByDesc(RawDataLog::getBusinessDt)
                            .last("limit 1"));

### 报错信息
生成的错误sql语句
-- 无关字段用*代替
SELECT  *  FROM raw_data_log  WHERE (business_dt = 1 AND file_type = 1) ORDER BY business_dt DESC limit 1

**Comment by miemieYaho** [comment]
哪错了?

**Comment by qmdx** [comment]
该语句是正确的，请确认是不是你表字段什么的不匹配
