### ISSUE TITLE
PostgreSqlTypeConvert类 char类型转换策略有误

### ISSUE THREAD

**Issue by DIYpeter** [baomidou/mybatis-plus#2843]
### 当前使用版本(必填,否则不予处理)
mybatis plus 3.3.2

postgreSQL 9.5.4
PostgreSQL JDBC Driver 42.2.14

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在包
`com.baomidou.mybatisplus.generator.config.converts`
的
`PostgreSqlTypeConvert`
类
第35行
34     if (t.contains("char")) {
35           return DbColumnType.STRING;

为什么数据库中是char类型生成的策略是STRING类型？
是未更新？还是需要我们自己实现接口自定义策略？

**Comment by DIYpeter** [comment]
更新版本到
mybatis plus 3.4.0

第42行
42    .test(containsAny("char", "text", "json", "enum").then(STRING))

**Comment by qmdx** [comment]
如果默认转换器无法满足，继承重新注入
