### ISSUE TITLE
请问，mybatis plus可以和TIDB一起使用吗，

### ISSUE THREAD

**Issue by gitfortune** [baomidou/mybatis-plus#2848]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis本身和TIDB兼容性还可以，很少出现问题，不知道mybatis plus能不能很好的支持TIDB

**Comment by miemieYaho** [comment]
只要支持标准sql就行，除了分页需要确定分页方言之外

**Comment by qmdx** [comment]
可以的

**Comment by gitfortune** [comment]
> 只要支持标准sql就行，除了分页需要确定分页方言之外

TIDB对MySQL 协议 兼容的很好，那分页插件的DbType应该选 DbType.MYSQL 还是DbType.OTHER

**Comment by miemieYaho** [comment]
mysql
