### ISSUE TITLE
https://mybatis.plus/访问不了

### ISSUE THREAD

**Issue by jvhuaxia** [baomidou/mybatis-plus#2851]
### 当前使用版本(必填,否则不予处理)

3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
https://mybatis.plus/
访问不了

### 重现步骤(如果有就写完整)
https://mybatis.plus/
访问不了

### 报错信息
403

**Comment by qmdx** [comment]
你网络的问题，无法使用你就试试  mp.baomidou.com

**Comment by 8debug** [comment]
我也访问不了
