### ISSUE TITLE
JSON.toJSONString(pojoList); 为什么会执行Preparing sql

### ISSUE THREAD

**Issue by tzhanhe** [baomidou/mybatis-plus#2852]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 重现步骤(如果有就写完整)

List<Pojo> pojoList=this.list(new QueryWrapper<>());

JSON.toJSONString(pojoList);

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

Preparing: SELECT id,name FROM pojo WHERE id = ? AND is_deleted = 0

### 报错信息

Preparing: 

无报错信息

**Comment by miemieYaho** [comment]
？？？尼哪个培训机构学的Java？
