### ISSUE TITLE
请教一下想要合并数据应该怎么处理

### ISSUE THREAD

**Issue by InVinCiblezz** [baomidou/mybatis-plus#2853]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
新手的restful api业务需求

### 重现步骤(如果有就写完整)

我用sql join 两个表，user 和 items, 取出来的数据是
user_id username item_id item_name
1           x                1           xxx
1           x                2          zzz
我想合并输出成 {user_id:1, username:'x', items:[...]} 

想构造这样的形式，是不是只能用xml的方式比较好？
在哪一层执行合并数据比较合理呢？
直接给我样例code的链接也可以 十分感谢！

**Comment by miemieYaho** [comment]
这里不处理业务问题
