### ISSUE TITLE
pgsql 分页筛选日期（Date类型），该怎么格式化成年月日

### ISSUE THREAD

**Issue by 564142183** [baomidou/mybatis-plus#2859]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
pgsql `分页筛选日期问题`

### 重现步骤(如果有就写完整)
实体
@ApiModelProperty("发布时间")
    @TableField(value = "date")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date date;

分页方法
public R list(PageParam pageParam, Article entity) {
   IPage<Article> pageInfo = articleService.page(getPageParam(pageParam), Wrappers.query(entity));
   return R.success(pageInfo);
}

日志打印
 Consume Time：16 ms 2020-09-01 09:57:44
 Execute SQL：SELECT COUNT(1) FROM cms_article WHERE date = '2020-09-15T00:00:00.000+0800' AND del_flag = '0'
传进去的日期没有格式化

### 报错信息
无报错

**Comment by miemieYaho** [comment]
底层是mybatis，自己格式化了再传参

**Comment by fullee** [comment]
遇到了相同的问题，同样的写法在另一个项目中没有问题
