### ISSUE TITLE
使用@Insert 注解sql，自动填充的createTime和updateTime都直接null插入数据库

### ISSUE THREAD

**Issue by linchuqun8384** [baomidou/mybatis-plus#2864]
请问如果是用@Insert注解语句，要怎么配置，才能使用自动填充创建时间到数据库呢？

**Comment by miemieYaho** [comment]
debug 看 `Insert` 这个类

**Comment by linchuqun8384** [comment]
你好，请问我是用@Insert的，如何去debug这个类？

**Comment by linchuqun8384** [comment]
我debug了传进@Insert接口的参数，并没有看到createTime和updateTime呢

**Comment by miemieYaho** [comment]
搜索这个类，启动时debug看注入的sql
