### ISSUE TITLE
@TableField(exist = false) 导致LambdaQueryWrapper报错

### ISSUE THREAD

**Issue by ancienter** [baomidou/mybatis-plus#2865]
### 当前使用版本(必填,否则不予处理)

mybatis-plus-boot-starter 3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

can not find lambda cache for this property [code] of entity

### 重现步骤(如果有就写完整)

设置
@TableField(exist = false, value="code")
然后
queryWrapper.lambda().like(xxxxEntity::getCode, xxxx.getCode());

**Comment by miemieYaho** [comment]
设置这个等于数据库没这字段,自然不会进行缓存

**Comment by ancienter** [comment]
但是视图和子查询里面有
