### ISSUE TITLE
使用Mybatis-plus进行搜索返回结果和在数据库直接执行不一致的问题。

### ISSUE THREAD

**Issue by oxcz** [baomidou/mybatis-plus#2867]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用mybatis plus接口调用返回的顺序。
![image](https://user-images.githubusercontent.com/16790410/91964751-2275ee80-ed42-11ea-822f-fc66a405f06a.png)
直接在数据库进行搜索返回的顺序。
![image](https://user-images.githubusercontent.com/16790410/91964838-3cafcc80-ed42-11ea-8d76-8cc958d496d6.png)
确认过执行SQL和参数都是一致的，在数据库执行的SQL是从控制台直接复制过来的，如果有需要可以提供更多信息。
SQL如下。

> 
SELECT question.*, category.category_name
FROM exam_question question
         LEFT JOIN anyu_category category ON question.category_id = category.id
         LEFT JOIN exam_paper_middle_question middle
                   ON middle.is_deleted = 0 AND middle.question_id = question.id AND middle.paper_id = 1300338716673359874 AND
                      middle.paper_middle_id = 1301082146277961729
WHERE question.question_type = 1
  AND question.is_deleted = 0
  AND middle.id IS NULL
ORDER BY question.create_time DESC
LIMIT 0,10

### 报错信息
无

**Comment by miemieYaho** [comment]
去找mybatis
