### ISSUE TITLE
使用sql注入器：MyLogicSqlInjector之后，字段类型处理器一直报错

### ISSUE THREAD

**Issue by linchuqun8384** [baomidou/mybatis-plus#2868]
> 我在MybatisPlusConfig加入了SqlInjector的bean

`@Configuration
@MapperScan("com.hboxs.mapper")
public class MybatisPlusConfig {

    /**
     * 新的分页插件,一缓和二缓遵循mybatis的规则,需要设置 MybatisConfiguration#useDeprecatedExecutor = false 避免缓存出现问题
     */
    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.H2));
        return interceptor;
    }

    @Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseDeprecatedExecutor(false);
    }

    /**
     * 自定义 SqlInjector
     * 里面包含自定义的全局方法
     */
    @Bean
    public MyLogicSqlInjector myLogicSqlInjector() {
        return new MyLogicSqlInjector();
    }

}
`

> 启动项目一直报下面这个错：

Caused by: java.lang.IllegalStateException: Type handler was null on parameter mapping for property 'authorities'. It was either not specified and/or could not be found for the javaType (java.util.List) : jdbcType (null) combination.
	at org.apache.ibatis.mapping.ParameterMapping$Builder.validate(ParameterMapping.java:119) ~[mybatis-3.5.5.jar:3.5.5]

“authorities” 是我项目model层一个字段：
    @TableField(typeHandler = JacksonTypeHandler.class)
    private List<String> authorities;

**Comment by miemieYaho** [comment]
那得看你加了些什么自定义的全局方法,注入的sql是怎样的,要么你自己参考mp提供的改,要么收费帮解决

**Comment by qmdx** [comment]
无法重现
