### ISSUE TITLE
StringUtils的split方法报空指针异常

### ISSUE THREAD

**Issue by shizhishayaoyao** [baomidou/mybatis-plus#2869]
### 当前使用版本(必填,否则不予处理)

mybatis-plus-core-3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用split方法,str传null,会出现控制针异常,  注释样例中写了 StringUtils.split(null, *)= null
,是否优化下?

### 报错信息
空指针异常

**Comment by GeorgeAnson** [comment]
新版本已经移除该方法，建议更新至3.x版本

**Comment by qmdx** [comment]
up
