### ISSUE TITLE
版本3.4.0使用多条件排序会警告Unchecked generics array creation for varargs parameter

### ISSUE THREAD

**Issue by madongbao** [baomidou/mybatis-plus#2870]
![image](https://user-images.githubusercontent.com/33247803/92082158-c620d680-edf6-11ea-8119-fcd10d73b2b9.png)

Unchecked generics array creation for varargs parameter

**Comment by miemieYaho** [comment]
就这样的,自己unchecked抑制

**Comment by freshgeek** [comment]
..... 为啥这边会出 筛选不会
