### ISSUE TITLE
查询数据时传入非数据库字段

### ISSUE THREAD

**Issue by fangqj** [baomidou/mybatis-plus#2873]
### 当前使用版本(必填,否则不予处理)
3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
存在两个一样的表，结构相同， 想通过新增@TableField(exist = false)属性 结合DynamicTableNameParser，根据属性不同查询不同的表
 查询时设置这个非数据库属性，报错Your property named "XXX" cannot find the corresponding database column name!
### 重现步骤(如果有就写完整)
1.新增@TableField(exist = false)属性
2.LambdaQueryWrapper 设置这个属性
3.查询

### 报错信息
XXX 非数据库属性
Your property named "XXX" cannot find the corresponding database column name!

**Comment by miemieYaho** [comment]
LambdaQueryWrapper 怎么用的?

**Comment by fangqj** [comment]
> LambdaQueryWrapper 怎么用的?
  .eq(MonitorRule::getXXX,XXX); XXX为非数据库属性

**Comment by fangqj** [comment]
> LambdaQueryWrapper 怎么用的?
  .eq(实体类::getXXX,XXX);

**Comment by miemieYaho** [comment]
你注解标记了xxx不属于数据库字段，自然不会进行缓存

**Comment by fangqj** [comment]
还要别的方法吗？根据参数不同 查询不同的表

**Comment by miemieYaho** [comment]
分表建议使用shardingjdbc
