### ISSUE TITLE
动态表名根据非数据库参数，查询不同的表

### ISSUE THREAD

**Issue by fangqj** [baomidou/mybatis-plus#2874]
### 当前使用版本(必填,否则不予处理)

3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
动态表名 如何根据参数不同 查询不同的表，参数为非数据库字段。

### 重现步骤(如果有就写完整)

动态表名 如何根据参数不同 查询不同的表，参数为非数据库字段。

**Comment by miemieYaho** [comment]
用treadlocal
