### ISSUE TITLE
去除多租户多余的表名引发的bug

### ISSUE THREAD

**Issue by yushxzh** [baomidou/mybatis-plus#2875]
# 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
移除表名之后，表名未使用Alias的多表联查语句，租户字段不明确
 [相关commit](https://github.com/baomidou/mybatis-plus/commit/3e46b54dcf62df28c4b25d26402223558e32b558)

### 重现步骤(如果有就写完整)
原始sql：`select a.* from a left join b on a.id=b.a_id where a.id=1 `
去除多余的表名之前的sql: `select a.* from a left join b on a.id=b.a_id and b.tenant_id=1 where a.id=1 and a.tenant_id=1`
去除多余的表名之后的sql: `select a.* from a left join b on a.id=b.a_id and tenant_id=1 where a.id=1 and tenant_id=1`

### 报错信息
java.sql.SQLIntegrityConstraintViolationException: Column 'tenant_id' in where clause is ambiguous

**Comment by miemieYaho** [comment]
那你就加上表别名
