### ISSUE TITLE
自定义Sql注入器报Invalid bound statement (not found): 

### ISSUE THREAD

**Issue by nolynn** [baomidou/mybatis-plus#2876]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

自定义 MyLogicSqlInjector 定义 findAll 方法 报   Invalid bound statement (not found):

### 重现步骤(如果有就写完整)

org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.jswPlatform.system.provider.mapper.user.SysUserMapper.findAll

 Invalid bound statement (not found):

**Comment by nolynn** [comment]
@qmdx 求助

**Comment by qmdx** [comment]
https://baomidou.com/guide/faq.html#%E5%87%BA%E7%8E%B0-invalid-bound-statement-not-found-%E5%BC%82%E5%B8%B8
