### ISSUE TITLE
我在本地新增了对gbase8s数据库分页支持，如何提交

### ISSUE THREAD

**Issue by weiwenman** [baomidou/mybatis-plus#2877]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
新功能

**Comment by miemieYaho** [comment]
最新版已经支持自动识别gbase并自动使用mysql的分页方言

**Comment by weiwenman** [comment]
首先gbase和gbase8s的驱动不一样，其次分页语句也不一样

utils类：com.baomidou.mybatisplus.extension.toolkit.JdbcUtils

gbase驱动入口:
else if (jdbcUrl.contains(":gbase:")) {
            return DbType.GBASE;
        }
gbase8s驱动入口:
if (jdbcUrl.contains(":gbasedbt-sqli:")){
            return DbType.GBASE8S;
        }

Dialect类：com.baomidou.mybatisplus.extension.plugins.pagination.dialects.IDialect

gbase直接继承mysql:GBaseDialect extends MySqlDialect 
分页语法 SELECT * FROM TABLE LIMIT offset,limit

而gbase8s 分页的语法  SELECT SKIP offset FIRST limit * FROM TABLE

**Comment by weiwenman** [comment]
> 
> 
> 最新版已经支持自动识别gbase并自动使用mysql的分页方言

首先gbase和gbase8s的驱动不一样，其次分页语句也不一样

utils类：com.baomidou.mybatisplus.extension.toolkit.JdbcUtils

gbase驱动入口:
else if (jdbcUrl.contains(":gbase:")) {
return DbType.GBASE;
}
gbase8s驱动入口:
if (jdbcUrl.contains(":gbasedbt-sqli:")){
return DbType.GBASE8S;
}

Dialect类：com.baomidou.mybatisplus.extension.plugins.pagination.dialects.IDialect

gbase直接继承mysql:GBaseDialect extends MySqlDialect
分页语法 SELECT * FROM TABLE LIMIT offset,limit

而gbase8s 分页的语法 SELECT SKIP offset FIRST limit * FROM TABLE

**Comment by qmdx** [comment]
请 pr  https://git-scm.com/docs/git-request-pull

**Comment by lixhbs** [comment]
> > 最新版已经支持自动识别gbase并自动使用mysql的分页方言
> 
> 首先gbase和gbase8s的驱动不一样，其次分页语句也不一样
> 
> utils类：com.baomidou.mybatisplus.extension.toolkit.JdbcUtils
> 
> gbase驱动入口:
> else if (jdbcUrl.contains(":gbase:")) {
> return DbType.GBASE;
> }
> gbase8s驱动入口:
> if (jdbcUrl.contains(":gbasedbt-sqli:")){
> return DbType.GBASE8S;
> }
> 
> Dialect类：com.baomidou.mybatisplus.extension.plugins.pagination.dialects.IDialect
> 
> gbase直接继承mysql:GBaseDialect extends MySqlDialect
> 分页语法 SELECT * FROM TABLE LIMIT offset,limit
> 
> 而gbase8s 分页的语法 SELECT SKIP offset FIRST limit * FROM TABLE

请问这个pr 处理了么，我这也需要gbase8s
