### ISSUE TITLE
Generator后续更新有可能携带数据库字段能否为空的信息吗？

### ISSUE THREAD

**Issue by FindingArrow** [baomidou/mybatis-plus#2878]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
希望结合swagger，通过自动生成的方式，直接在Api文档里表明参数是否必填

### 重现步骤(如果有就写完整)
DEBUG进了generator内部，发现执行过程中 'show full fields from `xxx`' 函数是携带了字段是否为空的信息的，但是TableField对象内没有这个字段，也没有做处理

### 报错信息
希望可以增加这个参数。

**Comment by qmdx** [comment]
暂时没有处理这么复杂的逻辑，你可以自定义注入你的需要然后修改模板来实现你的需求
