### ISSUE TITLE
请问mybatis-plus 能和 tkmapper一起使用吗?

### ISSUE THREAD

**Issue by wajncn** [baomidou/mybatis-plus#2880]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
tkmapper版本:1.1.5

### 重现步骤(如果有就写完整)
之前项目封装的框架是用的tkmapper   我想在新的功能上使用mybatis-plus. 请问可以一起使用吗?

### 报错信息

org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'mapper' for bean class [com.thoughtworks.xstream.mapper.Mapper] conflicts with existing, non-compatible bean definition of same name and class [com.baomidou.mybatisplus.core.mapper.Mapper]

**Comment by nieqiurong** [comment]
没试过，也不建议，省的后面接盘的人骂。
