### ISSUE TITLE
sqlserver 

### ISSUE THREAD

**Issue by wdx13666** [baomidou/mybatis-plus#2883]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

请教下 sqlserver  newid   怎么插入完id回显

**Comment by qmdx** [comment]
sqlserver 某些版本驱动好像自增无法回写到实体，建议用分布式唯一 id

**Comment by qmdx** [comment]
up 其它问题请打开具体反馈
