### ISSUE TITLE
mybatisPlus 跟sqlserver整合时，遇到sqlserver 关键字status 会加`status` ，导致sql语法错误

### ISSUE THREAD

**Issue by zrd1314** [baomidou/mybatis-plus#2887]
### 当前使用版本(必填,否则不予处理)

2.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用springboot 并且使用多数据源情况下，导致的， 单数据源的话 这个 status字段，就不加 ` ` ,是对的

**Comment by zrd1314** [comment]
很急，你好，有好的办法解决现在 有遇到一个 state 关键字 sql 语句加了 反引号

**Comment by qmdx** [comment]
多数据源 是怎么处理的

**Comment by zrd1314** [comment]
我看源码 启动时候 这个关键字 是定义在 SqlReservedWords 类里面的 ，但是 启动时候无法手动指定DBType 数据库类型 ，导致我的多数据 默认使用 mysql的，然后给 关键字加了 反引号

**Comment by qmdx** [comment]
> 我看源码 启动时候 这个关键字 是定义在 SqlReservedWords 类里面的 ，但是 启动时候无法手动指定DBType 数据库类型 ，导致我的多数据 默认使用 mysql的，然后给 关键字加了 反引号

全局配置 identifierQuote  为 `%s` 不做任何处理， 需要处理的特殊字段你通过注解解决

**Comment by zrd1314** [comment]
我就是 设置了 identifierQuote  这个 配置为 "%s" ,但是自动装配时候为什么GlobalConfiguration 的类的 dbType  不让 通过外部属性进行配置呢， 导致我本来想用的是 sqlserver的 但是 用到是 mysql的
