### ISSUE TITLE
sql性能规范插件 多数据源 oracle coon.getSchema() 空值报错问题

### ISSUE THREAD

**Issue by 5918l** [baomidou/mybatis-plus#2890]
### 当前使用版本(必填,否则不予处理)

mybatis-plus 3.4.0
springboot 2.3.1
dynamic-datasource 3.2.0
druid-springboot 1.1.9

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus 引入插件 配置多数据源 阿里连接池  在IllegalSQLInnerInterceptor.getIndexInfos()                 String schema = StringUtils.isBlank(dbName) ? conn.getSchema() : dbName;

### 重现步骤(如果有就写完整)
配置好直接定时器执行sql

### 报错信息
报错  java.sql.SQLFeatureNotSupportedException

**Comment by qmdx** [comment]
该问题请提交至 https://github.com/baomidou/dynamic-datasource-spring-boot-starter
