### ISSUE TITLE
mybatis-plus 中QueryWrapper 支持mysql 的全文索引吗

### ISSUE THREAD

**Issue by 17090000987** [baomidou/mybatis-plus#2892]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用mysql 全文索引

select 
    code, name
from 
    branch_bank 
where 
    code = #{code, jdbcType=VARCHAR} 
    and match(name) against(#{name, jdbcType=VARCHAR})

可以通 Wrapper 实现吗

**Comment by miemieYaho** [comment]
用 apply
