### ISSUE TITLE
Mybatis Plus多租户拦截器getTenantId缺少select传参

### ISSUE THREAD

**Issue by VioletCzy** [baomidou/mybatis-plus#2893]
### 当前使用版本(必填,否则不予处理)
mybatis plus version：3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.3.x中TenantHandler的getTenantId(boolean select)能根据参数判断select/其他(insert、delete、update),进行不同的处理,
3.4.0中的TenantLineHandler.getTenantId()没有参数传递,无法判断。

### 重现步骤(如果有就写完整)
3.4.0中TenantLineHandler.getTenantId()方法参数缺失

### 报错信息
无

**Comment by qmdx** [comment]
该问题内部讨论比较激烈，结果不会做调整现有隔离方式，建议 CV 租户插件部分从新注入到解析链，后续版本会提供更好的解决方案

**Comment by literatureandyou** [comment]
VioletCzy 你好，3.3.2中，TenantHandler的getTenantId(boolean select)，select参数无论是select还是其他(insert、delete、update)我这里总是false，请问你使用3.3.x时是怎么解决的？谢谢
