### ISSUE TITLE
PaginationInterceptor 为什么被标记为Deprecated？有什么替代方式吗？

### ISSUE THREAD

**Issue by SHIELD7** [baomidou/mybatis-plus#2895]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
升级3.4.0后，PaginationInterceptor 为什么被标记为Deprecated？有什么替代方式吗？

### 重现步骤(如果有就写完整)
null

### 报错信息
null

**Comment by kxys422834** [comment]
```java
MybatisPlusInterceptor pagination = new MybatisPlusInterceptor();
pagination.addInnerInterceptor(new PaginationInnerInterceptor());
```

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html
