### ISSUE TITLE
使用条件构造器QueryWrapper，SQL语句不会拼接条件构造器里面的语句。

### ISSUE THREAD

**Issue by erdongxin** [baomidou/mybatis-plus#2896]
### 当前使用版本(必填,否则不予处理)
3.1.2，3.3.2，3.4.0同样效果

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
关键代码贴在重现步骤里。

情况描述：查询时条件构造器未把条件拼接到sql中，把product_id为其他值的列的也查询出来了，乍一看代码。

以为是Service层出了问题，检查之后发现，项目中其他地方的getById，page分页方法均有效，只有使用的条件构造器的地方条件构造器里的调用全部无效。

查看源码发现eq第一个参数要传true，但是默认是true，不抱希望的去测试，果然不是这里的问题。

猜测可能和MP版本有关，原MP版本为3.1.2，升到3.3.2，3.4.0结果相同。

打断点进入QueryWrapper里面，发现entity实体是空的，因为不怎么懂原理，现在不知道问题出现在哪。

### 重现步骤(如果有就写完整)
@Reference(version = "1.0.0")
StoreContactService storeContactService;

QueryWrapper<StoreContactEntity> storeContactEntityQueryWrapper = new QueryWrapper<>();
storeContactEntityQueryWrapper.eq("store_id", storeUserEntity.getId());
List<StoreContactEntity> storeContactEntityList = storeContactService.list(storeContactEntityQueryWrapper);
打印的sql语句为：

SELECT id,product_id,specs_name,specs_content,product_price,original_price,status,sort_order,create_time,update_time FROM specs_type

==> Parameters: 

<==    Columns: id, product_id, specs_name, specs_content, product_price, original_price, status, sort_order, create_time, update_time

<==        Row: 1, 1, 规格1, 精品套餐1, 10.00, 10.00, 1, 1, 2020-09-05 22:22:38.0, null

<==        Row: 2, 1, 规格2, 精品套餐2, 12.00, 12.00, 1, 1, 2020-09-05 22:23:11.0, null

<==        Row: 3, 2, 规格1, 2套餐, 10.00, 10.00, 1, 1, 2020-09-10 17:27:56.0, null

<==      Total: 3

dubbo 2.5.3版本，springboot 1.5.6.RELEASE。

### 报错信息

未报错，条件构造器未拼接进sql中，没有出现预期的结果。

**Comment by kxys422834** [comment]
这点信息量没法判断问题的。自己写个demo，或者自己 打断点追踪 Wrapper.eq( 这个方法里面，看最后AbstractWrapper中 expression 里面有没有你加的这个条件啊！

**Comment by miemieYaho** [comment]
又用dubbo传wrapper了？

**Comment by erdongxin** [comment]
是的是的，用dubbo传wrapper了。0.0

**Comment by snow950** [comment]
entity空的是不是因为你用的.eq方法
