### ISSUE TITLE
二级缓存，使用BaseMapper的方法，@Option 不生效

### ISSUE THREAD

**Issue by lxc-123** [baomidou/mybatis-plus#2897]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
接口和xml同时存在，在接口中重写使用继承BaseMapper的方法selectList。  添加注解@Option(useCache=false) 不管用。
@Option与@Select 同时使用才可生效useCache=false。

### 报错信息
开启二级缓存后，接口继承BaseMapp<xxxx>,使用注解@CacheNamespaceRef(xxxxxMapper.class)
------------------------------------------------------------------
    @Override
    @Options(useCache = false)
    List<DtConfig> selectList(@Param("ew") Wrapper<DtConfig> queryWrapper);
-------------------------------------------------------------------
中@Options(useCache = false) 不生效。 必须添加@Select。但该方法BaseMapper以有默认实现，不需添加@Select.

**Comment by miemieYaho** [comment]
就这样的

**Comment by lxc-123** [comment]
就这样的？@Option必须与@Select,@Update,@Insert,@Delete同时存在？。单独@Option（useCache="false"）不生效？

**Comment by lxc-123** [comment]
> 就这样的
就这样的？@option必须与@select，@Update，@insert，@delete同时存在？单独@option（useCache将= “假”）不生效？

**Comment by miemieYaho** [comment]
对
