### ISSUE TITLE
PaginationInterceptor已过时！！

### ISSUE THREAD

**Issue by loks666** [baomidou/mybatis-plus#2898]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
oracle使用分页插件

### 重现步骤(如果有就写完整)
@Bean
    public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
        // 设置请求的页面大于最大页后操作， true调回到首页，false 继续请求  默认false
        // paginationInterceptor.setOverflow(false);
        // 设置最大单页限制数量，默认 500 条，-1 不受限制
        // paginationInterceptor.setLimit(500);
        // 开启 count 的 join 优化,只针对部分 left join
        paginationInterceptor.setCountSqlParser(new JsqlParserCountOptimize(true));
        Properties properties = new Properties();
        properties.setProperty("dialect","oracle");
        paginationInterceptor.setProperties(properties);
        return paginationInterceptor;
    }
配置类如下，显示PaginationInterceptor已过时！可替换的类只有github的分页插件类

### 报错信息
我就想问此类过时了的话，替换的类是什么？而且官方的文档上没有更新

**Comment by miemieYaho** [comment]
samples里有，文档里看内置插件
