### ISSUE TITLE
kotlin的支持问题

### ISSUE THREAD

**Issue by kay365** [baomidou/mybatis-plus#2900]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

kotlin调用mybatis-plus无法正确使用lambda查询

### 重现步骤(如果有就写完整)

调用Lambda查询，这是kotlin的写法
Wrappers.query<YbUsrRole>().lambda().eq(YbUsrRole::userId,t.id)
代码执行到这句就会报下面的异常:"该方法仅能传入 lambda 表达式产生的合成类"
解决方式不用lambda查询，使用普通的字符串查询，如果将来字段发生改动，这个维护成本比较大，希望能在后面的版本支持kotlin使用lambda查询，这里这个问题原因的详细分析https://cloud.tencent.com/developer/article/1563019
### 报错信息

该方法仅能传入 lambda 表达式产生的合成类

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/tree/3.0/mybatis-plus-extension/src/main/kotlin/com/baomidou/mybatisplus/extension/kotlin
