### ISSUE TITLE
使用mybatis-plus 3.4.0 报错  java.lang.NoSuchMethodError: org.apache.ibatis.annotations.Select.databaseId()Ljava/lang/String;

### ISSUE THREAD

**Issue by mujinjia** [baomidou/mybatis-plus#2904]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用3.4.0会报错 改用3.3.1正常

### 报错信息
Error creating bean with name 'areaDictMapperExt' defined in file [E:\test\......\quote\biz\mapper\AreaDictMapperExt.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.apache.ibatis.annotations.Select.databaseId()Ljava/lang/String;

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder$AnnotationWrapper.<init>(MybatisMapperAnnotationBuilder.java:677)

The following method did not exist:

    org.apache.ibatis.annotations.Select.databaseId()Ljava/lang/String;

The method's class, org.apache.ibatis.annotations.Select, is available from the following locations:

    jar:file:/D:/Development/apache-maven/mavenRepository/org/mybatis/mybatis/3.5.4/mybatis-3.5.4.jar!/org/apache/ibatis/annotations/Select.class

It was loaded from the following location:

    file:/D:/Development/apache-maven/mavenRepository/org/mybatis/mybatis/3.5.4/mybatis-3.5.4.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.ibatis.annotations.Select

与目标VM断开连接, 地址为: ''127.0.0.1:50224'，传输: '套接字'', 传输: '{1}'

Process finished with exit code 1

**Comment by qmdx** [comment]
无法定位，请给出详细可重现 demo 然后打开

**Comment by shuoyan-tx** [comment]
相同的问题，3.4.0在mybatis-plus中使用@Select注解报错，请问下解决了吗？

**Comment by lightningl** [comment]
相同的问题，3.4.0在mybatis-plus中使用@select注解报错，请问下解决了吗？

**Comment by mujinjia** [comment]
解决了，Mybatis-Plus3.4.0 对应mybatis3.5.5，之前是因为mybatis版本太低

**Comment by lightningl** [comment]
收到，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午4:48
收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;"cop"<247745366@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 使用mybatis-plus 3.4.0 报错  java.lang.NoSuchMethodError: org.apache.ibatis.annotations.Select.databaseId()Ljava/lang/String; (#2904)





 
解决了，Mybatis-Plus3.4.0 对应mybatis3.5.5，之前是因为mybatis版本太低

**Comment by onlyGuo** [comment]
同样的问题，用的是mybatis-plus-boot-starter 3.4.2
mybatis-spring-boot-starter是2.1.0（对应mybatis3.5.2）

**Comment by yhliyr** [comment]
可以对照下时间，找个差不多的，3.4.3.1 对应 2.1.3(mybatis-spring-boot-starter) 实测可以
