### ISSUE TITLE
多租户插件无法拦截<resultMap>中的<collection>对应select

### ISSUE THREAD

**Issue by liuzhaohua** [baomidou/mybatis-plus#2906]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当resultMap中包含collection标签时，collection对应的select查询无法拦截

### 重现步骤(如果有就写完整)
当resultMap中包含collection标签时，collection对应的select查询无法拦截

**Comment by miemieYaho** [comment]
mybatis 不走插件有啥法呢?
