### ISSUE TITLE
请问现在MP支持mysql57版本的josn格式查询吗？

### ISSUE THREAD

**Issue by Sunyb01** [baomidou/mybatis-plus#2908]
### 当前使用版本(必填,否则不予处理)

3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请问MP的现有版本或之后版本会支持mysql5.7版本的josn列查询吗

### 重现步骤(如果有就写完整)

无

### 报错信息

无

**Comment by miemieYaho** [comment]
mp = mybatis
