### ISSUE TITLE
类注解TableName和TableField扫描不到

### ISSUE THREAD

**Issue by xingxianping** [baomidou/mybatis-plus#2911]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

springcloud架构，我把实体类抽离到了common，然后依赖到其他模块使用，因为其他模块需要该对象，但由此引发其他模块扫描不到注解
### 报错信息

会自动根据类名和表名解析成sql，不根据注解解析成sql

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by xingxianping** [comment]
这个给不了，牵扯很多，包括nacos等，是个分布式项目

**Comment by miemieYaho** [comment]
那你自己排查吧, TableInfoHelper

**Comment by xingxianping** [comment]
没进入这个类

**Comment by miemieYaho** [comment]
这是启动构建表信息的,自己去排查吧

**Comment by xingxianping** [comment]
找到了，是导包到错了，所以没扫描到注解

**Comment by xingxianping** [comment]
谢谢
