### ISSUE TITLE
saveBatch、saveOrUpdateBatch方法效率比较低，压测情况下很容易耗时超过1s

### ISSUE THREAD

**Issue by wxy2015** [baomidou/mybatis-plus#2912]
### 当前使用版本(必填,否则不予处理)

使用版本3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

底层代码还是使用批处理的方式，比insert tb values (val1),(val2),(val3)...的方式性能低很多

### 重现步骤(如果有就写完整)

表字段有20多个，10条数据执行saveOrUpdateBatch方法，耗时100多ms到1000多ms不等，压测工具jmeter，每秒生成50个请求，使用数据库连接池，连接池大小100。
单条数据执行插入耗时平均小于40ms，希望大大们可以优化下性能问题，建议增加一个参数，可以选择批量插入的方式是批处理还是insert tb values (val1),(val2),(val3)...的方式。毕竟很多使用该功能可能都是小白，想要自己封装公共方法的难度比较大。

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/faq.html#%E9%80%9A%E7%94%A8-insertbatch-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%BE%E5%9C%A8-service-%E5%B1%82%E5%A4%84%E7%90%86
https://mybatis.plus/guide/crud-interface.html#mapper-%E5%B1%82-%E9%80%89%E8%A3%85%E4%BB%B6
