### ISSUE TITLE
select查询时会自动带上逻辑未删除的状态

### ISSUE THREAD

**Issue by legend-c** [baomidou/mybatis-plus#2916]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter -3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当配置了逻辑删除之后，使用select查询时，会自动带上逻辑未删除的查询条件

### 重现步骤(如果有就写完整)
>**逻辑删除的配置：**
![image](https://user-images.githubusercontent.com/49267985/93580063-da0d3080-f9d1-11ea-88d9-799276618485.png)
![image](https://user-images.githubusercontent.com/49267985/93580126-f27d4b00-f9d1-11ea-9b15-8e4ba07cb72b.png)

>**select查询的方法**：
![image](https://user-images.githubusercontent.com/49267985/93580277-28223400-f9d2-11ea-9119-852f59b43218.png)

>**sql打印信息：**
![image](https://user-images.githubusercontent.com/49267985/93580323-3c663100-f9d2-11ea-9e1c-8ce6bf00d904.png)

### 建议！！
能够提供一个配置设置不自动带上吗？要不然又要自己写mapper SQL实现，很不方便

**Comment by qmdx** [comment]
既然你打开了逻辑删除那就相当于删除，你要查询已经删除的数据当然需要自定义 sql

按照你的要求你的需求应该是一个状态非逻辑删除业务，请不要设置为逻辑删除，查询的时候加上状态条件即可
