### ISSUE TITLE
达梦数据库中LocalDateTime类型不支持，但是生成实体类的日期类型都为LocalDateTime

### ISSUE THREAD

**Issue by ybreathing** [baomidou/mybatis-plus#2917]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 重现步骤(如果有就写完整)

获取数据时候报错

### 报错信息

 Error attempting to get column 'CREATE_DATE' from result set.  Cause: dm.jdbc.driver.DMException: 不支持的接口或功能

**Comment by miemieYaho** [comment]
看文档，可配置不用localfatetime

**Comment by gyf6067** [comment]
找这个配置找了半天：
GlobalConfig gc = new GlobalConfig();
...
gc.setDateType(DateType.ONLY_DATE);

**Comment by imic07** [comment]
@gyf6067 
是mybatis的问题, 需要重新定义一个LocalDateTimeTypeHandler implements TypeHandler<LocalDateTime>， 然后再全局注册下typeHandlerRegistry.register(LocalDateTime.class, LocalDateTimeTypeHandler.class);     就可以了
