### ISSUE TITLE
QueryWrapper同时设置entity和条件，执行sql出现问题

### ISSUE THREAD

**Issue by holenzh** [baomidou/mybatis-plus#2918]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

QueryWrapper同时设置setEntity和ne时，ne的条件不会加上and条件，导致执行报错。

### 重现步骤(如果有就写完整)
```
    @Override
    protected QueryWrapper<DO> buildWrapper(PageRequest<DO> request) {
        QueryWrapper<DO> wrapper = new QueryWrapper<>();
        Optional.ofNullable(request.getCondition()).ifPresent(wrapper::setEntity);
        wrapper.ne(Constant.STATUS, StatusEnum.DELETED.name());
        return wrapper;
    }
```

### 报错信息

The error may involve defaultParameterMap\n### The error occurred while setting parameters\n### SQL: SELECT id,value,description,status,type  FROM data_conf  WHERE  type=?    (status <> ?) \n### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax;

**Comment by miemieYaho** [comment]
无法复现,给出你的复现demo以git形式
