### ISSUE TITLE
@TableId(type = IdType.ID_WORKER)  有没有java的方法实现方式？

### ISSUE THREAD

**Issue by 8debug** [baomidou/mybatis-plus#2919]
### 当前使用版本(必填,否则不予处理)
3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
表主键字段使用 `@TableId(type = IdType.ID_WORKER)`注解可生成全局唯一，如果想将表中某一个字段（非主键）也想采用` IdType.ID_WORKER`方式赋值，请问提供相应的java方法吗？

**Comment by zhang0001** [comment]
IdWorker.getId()

**Comment by miemieYaho** [comment]
如上
