### ISSUE TITLE
关于 insert 插入，数据库的默认字段的回写

### ISSUE THREAD

**Issue by zhangmz0223** [baomidou/mybatis-plus#292]
例如：User 表字段 创建时间 createTime + 更新时间 updateTime 使用数据库函数 **自动创建 和 自动更新** 
```
User user = new User();
user.setName("haha");
user.setAge(18);
```

使用 `userMapper.insert(user);`  成功后。
此时，`user.getCreateTime()` 仍然为null 即无数据。

以上只是列举一个使用场景，可能会有别的业务字段需要使用到createTime。

目前解决方式是，需再次查询 即可获取到createTime数据。

不算Bug的话，希望能作为功能增强方式提供。

**Comment by qmdx** [comment]
直接使用 new  date 就可以，服务器时间和数据库时间差距不大，没有必要计较那一点点时间差

**Comment by zhangmz0223** [comment]
@qmdx  我使用的是数据库在创建数据的时候自动创建，没必要自己重新再创建一遍吧？
