### ISSUE TITLE
扩展使用【${ew.customSqlSegment}】时的两个小问题

### ISSUE THREAD

**Issue by gyf6067** [baomidou/mybatis-plus#2921]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 详细描述
1. ${ew.customSqlSegment} 没有别名 t，多表关联时，如果字段重名，就会报错；

2. 我想在自定义SQL中，即使用【${ew.customSqlSegment}】，又使用 map 扩展的字段，缺少可扩展的SQL，参照这段扩展代码：
 
>
    
    <sql id="sqlWhere">
        <where>
            <include refid="sqlWhereExtendable"/>

            <if test="id !=null ">
            	 and t.id = #{id}
            </if>
            <if test="creatorId !=null ">
            	 and t.creator_id = #{creatorId}
            </if>
        </where>
    </sql>

    
    <sql id="sqlWhereExtendable">
    </sql>

**Comment by miemieYaho** [comment]
不支持

**Comment by gyf6067** [comment]
😭😭😭

**Comment by gyf6067** [comment]
😭😭😭

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。

**Comment by gyf6067** [comment]
与领导讨论一下，是否可以添加这个特性吧，个人觉得是很有用的。。。
