### ISSUE TITLE
清除历史数据时，遇到的限制 #enhancement #helpwanted

### ISSUE THREAD

**Issue by fwonce** [baomidou/mybatis-plus#2927]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 报错信息
非报错，疑问，文档未及相关内容

场景：清除历史数据，需要把A表中一定条件的数据select出来，经过一定业务处理后，从A表delete，并insert入一个同构的历史表B。遇到3个问题。

1. select from A 强制加上了[`@TableLogic`](https://baomidou.com/guide/annotation.html#tablelogic) deleted字段的where条件。
    - 希望在不影响其他大部分场景下的业务代码情况下，有办法能在特殊语句中不限定deleted字段，把逻辑删除的也select出来，比如在queryWrapper里主动设置一个选项。
2. delete from A 强制变成了update逻辑删除语句。
    - 希望在不影响其他大部分场景下的业务代码情况下，有能够真正物理删除的方法。
3. 生成的 insert 语句去掉了[`@TableId`](https://baomidou.com/guide/annotation.html#tableid) id字段，尽管在entity上显式设置了id值。
    - 希望TableId模式为AUTO时，依然有办法能显式指定，就好比数据库字段为自增时，你不传值是自增，传值则用你传的。

**Comment by fwonce** [comment]
通过变相手段实现。问题关闭吧…

**Comment by qmdx** [comment]
1，2，逻辑删除等同于物理删除你的需求请使用 state 状态解决而不是逻辑删除

3，已设置为自增就不能自定义，有冲突隐患，如果你硬是要这么多自己 xml 实现
