### ISSUE TITLE
使用分页插件optimize this sql to a count sql has exception

### ISSUE THREAD

**Issue by wangweiye01** [baomidou/mybatis-plus#2928]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

`select * from card_card order by convert (name using gbk) asc`

### 报错信息

optimize this sql to a count sql has exception

![1](https://pcoss.guan2018.com/WX20200922-084328.png)

**Comment by miemieYaho** [comment]
jsqlparser不支持解析
