### ISSUE TITLE
selectCount NumberFormatException 异常

### ISSUE THREAD

**Issue by outdoxl** [baomidou/mybatis-plus#2931]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`selectCount` 返回类型为 Integer
实际查询返回结果如果大于 2147483647 (`Integer.MAX_VALUE`) 
会报异常：NumberFormatException

### 重现步骤(如果有就写完整)
无

### 报错信息
java.lang.NumberFormatException: For input string: "4178000785"

---

建议将 `selectCount` 返回值改为 Long 类型，或者新增一个接口 `selectCountLong` 返回 Long 类型

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/b988866c3df89e8ebf89daacb371fb1b4998ac38
