### ISSUE TITLE
转换函数怎么使用？

### ISSUE THREAD

**Issue by ymgjava** [baomidou/mybatis-plus#2934]
listObjs方法：
  <V> List<V> listObjs(Wrapper<T> queryWrapper, Function<? super Object, V> mapper); 
可以传入转换函数，但怎么使用的？

下面是两个例子：
LambdaQueryWrapper<BotSeat> query1 = Wrappers.lambdaQuery(BotSeat.class);
query1.select(BotSeat::getExtPhone).eq(BotSeat::getCompanyId, companyId);
// 此处IDE报错
List<String> phones = this.listObjs(query1, BotSeat::getExtPhone); 

LambdaQueryChainWrapper<BotSeat> query = this.lambdaQuery();
List<BotSeat> list = query.select(BotSeat::getExtPhone).eq(BotSeat::getCompanyId, companyId).list();
List<String> pones = list.stream().map(BotSeat::getExtPhone).collect(Collectors.toList());

通过查看listObjs源码，getBaseMapper().selectObjs(queryWrapper).stream().filter(Objects::nonNull).map(mapper).collect(Collectors.toList());
与下面的代码实现方式一样

**Comment by miemieYaho** [comment]
那个问号指代和数据库字段类型对应的某个类型而不是entity
