### ISSUE TITLE
如何实现联合分页查询？

### ISSUE THREAD

**Issue by 77321660** [baomidou/mybatis-plus#294]
用户表t_user(user_id,username,pwd,dept_id)
部门表t_dept(dept_id,dept_name)
用户查询列表希望显示部门名称，请问如何定义分页查询的Mapper接口和Mapper.xml

**Comment by yuxiaobin** [comment]
http://mp.baomidou.com/#/page-plugin?id=%E6%96%B9%E5%BC%8F%E4%B8%80-%E3%80%81%E4%BC%A0%E5%8F%82%E5%8C%BA%E5%88%86%E6%A8%A1%E5%BC%8F%E3%80%90%E6%8E%A8%E8%8D%90%E3%80%91
