### ISSUE TITLE
Mapper接口方法参数是否允许传入多个条件构造器

### ISSUE THREAD

**Issue by Ronaltn** [baomidou/mybatis-plus#2943]
### 当前使用版本(必填,否则不予处理)
3.4.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
能否支持Mapper接口方法，允许传递多个多个条件构造器。
### 重现步骤(如果有就写完整)
```java
public interface ReportMapper{
    @Select("with query1 as (select XXX from table1 ${ew1.customSqlSegment}),query2 as (select xxx from table2 ${ew2.customSqlSegment}) select XXX from table1 join table2 on XXX ")
    List<ReportEntity> getReport(@Param("ew1") wapper1,@Param("ew2") wrapper2);
}
```
### 报错信息
提示找不到ew参数

**Comment by qmdx** [comment]
你给出的 @Param 也没有 ew

**Comment by Ronaltn** [comment]
> 你给出的 @param 也没有 ew

目前应该只认一个条件构造器并且固定是ew，我想提的是后续能否支持多个。

**Comment by qmdx** [comment]
> > 你给出的 @param 也没有 ew
> 
> 目前应该只认一个条件构造器并且固定是ew，我想提的是后续能否支持多个。

太复杂的建议 xml 写可能更好维护，感谢支持
