### ISSUE TITLE
多组户问题？

### ISSUE THREAD

**Issue by literatureandyou** [baomidou/mybatis-plus#2944]
### 当前使用版本(必填,否则不予处理)
3.0.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
// select since: 3.3.2，参数 true 表示为 select 下的 where 条件,false 表示 insert/update/delete 下的条件
                // 只有 select 下才允许多参(ValueListExpression),否则只支持单参
                if (!select) {
                    ValueListExpression expression = new ValueListExpression();
                    ExpressionList list = new ExpressionList(new StringValue("0"), new StringValue("10"));
                    expression.setExpressionList(list);
                    return expression;
                }
多组户传入2个租户id，拼接的SQL是：WHERE (parent_id = ?) AND region.tenant_id = ('0', '10')
为啥不是 in ('0', '10')

### 报错信息
Cause: org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = record

**Comment by miemieYaho** [comment]
3.3.2

**Comment by literatureandyou** [comment]
你好，换成3.3.2版本后多租户（传入2个租户id），拼接出来的sql还是  WHERE (parent_id = ?) AND region.tenant_id = ('0', '10')，这里应该是 in  ('0', '10')才对

**Comment by miemieYaho** [comment]
查看入参boolean描述

**Comment by VioletCzy** [comment]
嗨喽,这个最终处理了吗
