### ISSUE TITLE
多租户多租户id查询不对的问题！

### ISSUE THREAD

**Issue by literatureandyou** [baomidou/mybatis-plus#2946]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
// select since: 3.3.2，参数 true 表示为 select 下的 where 条件,false 表示 insert/update/delete 下的条件
// 只有 select 下才允许多参(ValueListExpression),否则只支持单参

ValueListExpression expression = new ValueListExpression();
ExpressionList list = new ExpressionList(new StringValue("0"), new StringValue("10"));
expression.setExpressionList(list);
return expression;
多组户传入2个租户id，拼接的SQL是：WHERE (parent_id = ?) AND region.tenant_id = ('0', '10')
为啥不是 in ('0', '10')，应该 使用 in 查询才是对的

### 报错信息
Cause: org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = record

**Comment by literatureandyou** [comment]
![image](https://user-images.githubusercontent.com/39126967/94275857-10225580-ff7a-11ea-92ef-120e43b0f378.png)

麻烦看下

**Comment by sawakonotsadako** [comment]
怎么你的3.3.2和我的3.3.2版本不一样，并且我的3.3.2的代码是判断了如果是instanceOf ValueListExpression就会用in连接表达式，没问题的
