### ISSUE TITLE
在3.4.0版本中分页插件过时提示

### ISSUE THREAD

**Issue by kenx-max** [baomidou/mybatis-plus#2947]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在3.4.0版本中分页插件过时提示

### 重现步骤(如果有就写完整)
    public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
        List<ISqlParser> sqlParserList = new ArrayList<>();
        // 攻击 SQL 阻断解析器、加入解析链
        sqlParserList.add(new BlockAttackSqlParser());
        paginationInterceptor.setSqlParserList(sqlParserList);
        return paginationInterceptor;
    }

### 报错信息
过时了，请问新的api分页怎么配置
![image](https://user-images.githubusercontent.com/45358764/94357258-deb89f80-00c9-11eb-8f3b-3e1de378af94.png)

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html
