### ISSUE TITLE
使用Myabisplus继承的service下的list方法, 执行很慢 

### ISSUE THREAD

**Issue by lingyangcj** [baomidou/mybatis-plus#2949]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 重现步骤(如果有就写完整)

情况1: 使用Service下继承plus自带的list方法,请求超时很慢.
情况2: 把对应的SQL写入xml文件,不使用plus自带的方法, 执行时间为0.023秒, 数据库执行sql也是如此.

SQL 如下(表数据量为50W)
select * from td_ssgl_people where rklx = 1 and orgCode like '430%' limt 0,10

### 报错信息
无

**Comment by qmdx** [comment]
没有给出默认打印的sql 无法分析， 默认 list 使用 wrapper 查询是否加上条件  wrapper.last("limit 10")
