### ISSUE TITLE
BaseMapper为什么不提供批量插入的接口,必须要ServiceImpl才可以吗?

### ISSUE THREAD

**Issue by patience00** [baomidou/mybatis-plus#2950]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
一般我们都是项目中有BaseService需要继承

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/faq.html#%E9%80%9A%E7%94%A8-insertbatch-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%BE%E5%9C%A8-service-%E5%B1%82%E5%A4%84%E7%90%86
