### ISSUE TITLE
 Mapper如何实现  update set count=count+1 的sql

### ISSUE THREAD

**Issue by dabaisk** [baomidou/mybatis-plus#2953]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
传统xml实现方法
<update id="addCount">
		update album set count=count+1 where id=#{id}
</update>

### 重现步骤(如果有就写完整)

Mapper中没找到类似方法

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/faq.html#%E5%A6%82%E4%BD%95-update-%E6%97%B6-column-column-1
