### ISSUE TITLE
@TableField注解中的typeHandler，在使用lambdaQuery和update的情况下不生效

### ISSUE THREAD

**Issue by wuhuagang** [baomidou/mybatis-plus#2956]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

设置typeHandle，比如将Object序列化为byte[]，使用lambdaQuery和update，typeHandle不生效

### 重现步骤(如果有就写完整)

步骤同上

### 报错信息
没有报错，只有存储的数据和查询的数据不正确

**Comment by miemieYaho** [comment]
用3.4.0,update只对入参的entity有效
