### ISSUE TITLE
 MybatisConfiguration#useDeprecatedExecutor 方法过时

### ISSUE THREAD

**Issue by LiuShuKu** [baomidou/mybatis-plus#2957]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版本

### 重现步骤(如果有就写完整)
设置分页插件时 配置 useDeprecatedExecutor=false 时 提示过时

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/2955
