### ISSUE TITLE
不为空判断问题

### ISSUE THREAD

**Issue by HaoliHope** [baomidou/mybatis-plus#2960]
### 当前使用版本(必填,否则不予处理)

`        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2</version>
        </dependency>`

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用QueryWrapper查询发生

### 重现步骤(如果有就写完整)

1.  yml配置
` mybatis-plus:
      global-config:
    db-config:
      select-strategy: not_empty`
2. 执行查询方法，值为参数为 null
3.  执行SQL
`==>  Preparing: SELECT id,menu_status,icon,pid,menu_name,remark,update_time,url,menu_order,create_by,create_time,update_by,perms,menu_type FROM sys_menu WHERE (perms LIKE ? AND menu_name LIKE ?) 
==> Parameters: %null%(String), %null%(String)
<==      Total: 0`
### 报错信息
返回零条数据

**Comment by HaoliHope** [comment]
抱歉忘记加上使用QueryWrapper的代码了，我在补上
`        QueryWrapper<SysMenu> sysMenuQueryWrapper = new QueryWrapper<>();
        sysMenuQueryWrapper.lambda()
                .like(SysMenu::getPerms, menuQuery.getPerms())
                .like(SysMenu::getMenuName, menuQuery.getMenuName());
        List<SysMenu> sysMenuList = sysMenuMapper.selectList(sysMenuQueryWrapper);`

**Comment by miemieYaho** [comment]
该规则只对wrapper内的的entity有效
