### ISSUE TITLE
配置包扫描

### ISSUE THREAD

**Issue by kenx-max** [baomidou/mybatis-plus#2966]
我看到现在mybatis-plus 有的配置
 type-aliases-package 是strign类型，但是如果我想扫描多组包怎么实现，比如：
type-aliases-package: cn.soboys.admin.web.*.dto,cn.soboys.admin.web.*.vo  但是不行

请问怎么样可以实现我这样，扫描

**Comment by miemieYaho** [comment]
mybatis怎么配就怎么配

**Comment by kenx-max** [comment]
什么意思，我是要配置原生，的myatis的配置吗基于springboot的配置，他不会影响吗mybatis-plus配置吗

**Comment by miemieYaho** [comment]
你用mybatis的时候那里填什么现在就在这里填什么
