### ISSUE TITLE
mybatis-plus分页报错

### ISSUE THREAD

**Issue by dpjs** [baomidou/mybatis-plus#2967]
[###](url) 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus分页

### 重现步骤(如果有就写完整)
mybatis简单的分页操作

### 报错信息
WARN  [hjxz-client,,,] XNIO-1 task-1 com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor optimize this sql to a count sql has exception, sql:"select
            upw.id as wikiId,upw.wiki_title as wikiTitle,upw.wiki_type as wikitype,upw.content as content,upw.read_amount as readAmount
        from
            ums_psychology_wiki upw
        where
            upw.wiki_type = ? and upw.is_deleted = 0 and upw.publish_status = 0", exception:
null

**Comment by miemieYaho** [comment]
检查你的 jsqlparser 有没有版本冲突
