### ISSUE TITLE
如何整合Guice？并且可以使用ServiceImp里面提供的方法

### ISSUE THREAD

**Issue by KylinShinlyLin** [baomidou/mybatis-plus#2974]
请问如何整合Guice并能使用里面提供的ServiceImp方法

**Comment by huayanYu** [comment]
@KylinShinlyLin 建议自己参考重写。 如有成果，欢迎PR。~

**Comment by Fengxq2014** [comment]
@KylinShinlyLin 需要覆盖重新ServiceImpl里面的方法，里面部分方法依赖了spring，我这边已经整合过一次，有需要可以联系我
