### ISSUE TITLE
3.4版本 逻辑删除不生效

### ISSUE THREAD

**Issue by wangjia2016** [baomidou/mybatis-plus#2975]
### 当前使用版本(必填,否则不予处理)
3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.3.1 也有问题

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/16084076/95936191-9c040080-0e07-11eb-8f2b-07015d09e9d8.png)
![image](https://user-images.githubusercontent.com/16084076/95936198-9f978780-0e07-11eb-924f-28b47d4c0313.png)

按文档https://baomidou.com/guide/logic-delete.html 配置

### 报错信息
插入 is_delete字段没有值，依然是null

**Comment by miemieYaho** [comment]
自己赋值或数据库给默认值

**Comment by wangjia2016** [comment]
@miemieYaho 既然数据库要弄默认值，那这个逻辑删除插件是不是不起作用了？
