### ISSUE TITLE
如何处like字段被包含的情况

### ISSUE THREAD

**Issue by q8888tttt** [baomidou/mybatis-plus#2983]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如何处理like被包含的情况，如 ‘字符串’ like concat('%',ziduanming,'%')

**Comment by qmdx** [comment]
wrapper.like(xx, xx)
