### ISSUE TITLE
请问mybatis plus有没有单独的查询Mapper用来继承

### ISSUE THREAD

**Issue by jvhuaxia** [baomidou/mybatis-plus#2987]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请问mybatis plus有没有单独的查询Mapper用来继承
因为 我有一个业务 查询一个视图 只有查询需求 感觉继承BaseMapper不是很好

**Comment by miemieYaho** [comment]
暂无
