### ISSUE TITLE
您好，使用 mybatis-plus-boot-starter 3.4.0 遇到问题

### ISSUE THREAD

**Issue by niuniu-blog** [baomidou/mybatis-plus#2988]
#### 引起原因详述

> 这里使用的是@Mapper

> 项目启动类中 增加 @ComponentScan() 只要指定扫描位置（包括了mapper.java文件位置）
> 项目启动类中 增加 @ComponentScans() 只要指定扫描位置（包括了mapper.java文件位置）,无论指定一种或多种扫描位置
mybatis 不加载，请求接口报错

### 重现步骤(如果有就写完整)

手动增加 @ComponentScan

### 报错信息
Invalid bound statement (not found): com.apsp.demo.aaa.sys.mapper.UserMapper.selectList

**Comment by wangyunpeng0319** [comment]
使用这个注解@MapperScan

**Comment by miemieYaho** [comment]
你自己注入了 MapperFactoryBean 或 MapperScannerConfigurer ?

**Comment by niuniu-blog** [comment]
并没有，只是引入进去，没有进行其他配置


在 2020年11月3日 22:59，miemieYaho<notifications@github.com> 写道：


你自己注入了 MapperFactoryBean 或 MapperScannerConfigurer ?

**Comment by miemieYaho** [comment]
这是mybatis的东西,你自己多谷歌看看吧

**Comment by niuniu-blog** [comment]
使用@MapperScan 这个注解 指定路径就可以了


在 2020年11月4日 13:40，miemieYaho<notifications@github.com> 写道：


这是mybatis的东西,你自己多谷歌看看吧
