### ISSUE TITLE
MP3.4.0 异常不会自动throw

### ISSUE THREAD

**Issue by github-chr** [baomidou/mybatis-plus#2992]
### 当前使用版本(必填,否则不予处理)

MP3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
插入一张不存在的表（或任意SQL异常），无Exception信息

### 重现步骤(如果有就写完整)

不进行catch，无报错信息。catch以后可以捕获到

### 报错信息

无任何信息

**Comment by miemieYaho** [comment]
请回炉java基础

**Comment by github-chr** [comment]
不好意思，注释代码不小心把最外层的catch里面异常打印注释了。
