### ISSUE TITLE
能够在mybatisPlus中加入动态判定条件，类似于eq后面的条件是否成立的判断，可以让查询时可以获取到已经被逻辑删除的数据

### ISSUE THREAD

**Issue by hbzengcan** [baomidou/mybatis-plus#2995]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用MP查询时，希望可以获取到所有的数据，包含被逻辑删除的数据

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
不支持
