### ISSUE TITLE
大佬，请问一下后续版本是否会支持查询所有的数据，包含逻辑删除的？

### ISSUE THREAD

**Issue by hbzengcan** [baomidou/mybatis-plus#2996]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
个人希望大佬们可以在wrapper中加入类似于一个withDetele这样的方法，可以控制where语句中是否添加逻辑删除字段，因为有时候需要查询全部的数据，包含逻辑删除的数据，这就让人很困扰

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
也不会支持,删除就是删除
