### ISSUE TITLE
springboot2.3.4 连接两个数据库使用mybatis-plus3.4.0自动填充没有起效。

### ISSUE THREAD

**Issue by zhengjf1988** [baomidou/mybatis-plus#2999]
### 当前使用版本(必填,否则不予处理)
mybatis-plus3.4.0

### 重现步骤(如果有就写完整)
使用springboot2.3.4 连接两个数据库，添加MetaObjectHandler的实现类MyMetaObjectHandler，并添加@Component注解

类MyMetaObjectHandler在项目启动的时候可以确定已加载，但是在添加和修改数据时，没有自动填充对应的字段
`/**
 * 通用字段设置值（创建与更新人、时间等一些通用默认信息）
 *
 * @author admin
 */
@Component
public class MyMetaObjectHandler implements MetaObjectHandler {
    MyMetaObjectHandler(){
        System.out.println("88888888888888888888");
    }
    @Override
    public void insertFill(MetaObject metaObject) {

        System.out.println("***************");
        this.strictInsertFill(metaObject, "createDate", LocalDateTime.class, LocalDateTime.now());
        this.setFieldValByName("updateDate", LocalDateTime.now(), metaObject);
    }

    @Override
    public void updateFill(MetaObject metaObject) {
        this.setFieldValByName("updateDate", LocalDateTime.now(), metaObject);
    }
}`
多数据库连接设置

**Comment by zhengjf1988** [comment]
![image](https://user-images.githubusercontent.com/16054422/96947066-acf1f780-1514-11eb-80ab-42ea70ebb474.png)

**Comment by miemieYaho** [comment]
你自己构造了 SqlSessionFactory 就去抄starter的代码
