### ISSUE TITLE
如何实现1对多的主从表查询？

### ISSUE THREAD

**Issue by aoyunfeng** [baomidou/mybatis-plus#3]
如何实现1对多的主从表查询？如一个班有多个学生，有好的解决方法吗？

**Comment by qmdx** [comment]
太复杂了建议采用原生 xml 去写

**Comment by yangyang0507** [comment]
Mybatis-Plus 专注单表业务，如果业务太复杂，建议像原生Mybatis一样操作，没有任何影响。
