### ISSUE TITLE
字符串类型为神马默认 FieldStrategy.NOT_EMPTY ？？

### ISSUE THREAD

**Issue by wnli350** [baomidou/mybatis-plus#30]
TableInfoHelper 292-295行是作何考虑的？
/* 字符串类型默认 FieldStrategy.NOT_EMPTY */
if (String.class.isAssignableFrom(fieldType) && FieldStrategy.NOT_NULL.equals(validate)) {
                validate = FieldStrategy.NOT_EMPTY;
}

**Comment by qmdx** [comment]
已经修复
