### ISSUE TITLE
apply 中使用 like

### ISSUE THREAD

**Issue by Dongzhichao12** [baomidou/mybatis-plus#3004]
### 当前使用版本(必填,否则不予处理)
最新版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
apply 拼接 sql中使用like

**Comment by Dongzhichao12** [comment]
apply 中使用 like 解决办法

.apply( "name like '%'||{0}||'%'", name)

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/97999702-a02fa680-1e26-11eb-9a8a-a783cabe06a9.png)
