### ISSUE TITLE
@TableName（“db.user”）

### ISSUE THREAD

**Issue by zhangjinmei** [baomidou/mybatis-plus#3011]
### 当前使用版本(必填,否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.4.0</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我使用同一个数据源但是有不同的库名。所以需要指定表的库名加表明 例如@TableName(db1.user)  @TableName(db2.user)
但是目前未在配置的代码中发现配置项感觉不是很方便
### 重现步骤(如果有就写完整)
优化项非bug

### 报错信息
优化项非bug

**Comment by miemieYaho** [comment]
schema
