### ISSUE TITLE
mybatis plus 3.4.0 自定义拦截器执行顺序问题

### ISSUE THREAD

**Issue by ldw4033** [baomidou/mybatis-plus#3018]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis plus 3.4.0 自定义拦截器执行顺序问题
继承mybatis自身 Interceptor 和使用新版的 分页插件PaginationInnerInterceptor 如何配置执行顺序，
我想将原生拦截器先执行

**Comment by miemieYaho** [comment]
先执行的放前面
