### ISSUE TITLE
请问下oracle数据库下，能同时使用多种自定义keygenerate吗？一个项目包含自定义INPUT主键策略（截取当前8位时间字符+序列seq值）和现有的INPUT策略（oracle seq）

### ISSUE THREAD

**Issue by zhoutao1** [baomidou/mybatis-plus#3020]

**Comment by zhoutao1** [comment]
应该是能同时使用多种自定义keygenerate吗

**Comment by qmdx** [comment]
idType  策略是支持的，多数据 keyGenerate 3.4.3 将支持 https://github.com/baomidou/mybatis-plus/commit/1983193cc6d9fb38bc60125de2c0d7072652f256
