### ISSUE TITLE
急急急，QueryWrapper 与 @Select 结合使用时，如何添加一表中列和列相等的条件？？？

### ISSUE THREAD

**Issue by zhuwenquan2019** [baomidou/mybatis-plus#3021]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

QueryWrapper 与 @Select 结合使用时，如何添加一表中列和列相等的条件？？？
QueryWrapper有eq(R column, Object val) 只能判断列的值是否=一个对象Object的值，
需求：我要判断列的值与同表中另外一个列的值相等？不想写xml配置方式，我该怎么办？
请各位大佬帮忙。我看官方没有 eq(R column, R column)难道要自己重新加入重载方法吗？如果是怎么加？
求最快的方式，希望有小案例代码，万分感谢！
希望打印的sql语句是：a表.列1=a表.列2，但是sql语句打印的是：a表.列1="a表.列2" 错把 “a表.列2”当成对象的值了

### 重现步骤(如果有就写完整)
QueryWrapper有eq(R column, Object val) 只能判断列的值=一个对象Object的值，
需求：我要判断列的值与同表中另外一个列的值相等？不想写xml配置方式，我该怎么办？
请各位大佬帮忙。我看官方没有 eq(R column, R column)难道要自己重新加入重载方法吗？如果是怎么加？
求最快的方式，希望有小案例代码，万分感谢！
希望打印的sql语句是：a表.列1=a表.列2，但是sql语句打印的是：a表.列1="a表.列2" 错把 “a表.列2”当成对象的值了

### 报错信息
希望打印的sql语句是：a表.列1=a表.列2，但是sql语句打印的是：a表.列1="a表.列2" 错把 “a表.列2”当成对象的值了

**Comment by miemieYaho** [comment]
apply

**Comment by zhuwenquan2019** [comment]
@miemieYaho  有没有办法解决？

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/wrapper.html#apply
