### ISSUE TITLE
3.4版本 分页插件失效 数据库是MSSQL 退回3.3版本正常

### ISSUE THREAD

**Issue by 2524685265** [baomidou/mybatis-plus#3023]

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/97999504-5cd53800-1e26-11eb-9d59-0d63aaceec42.png)

**Comment by yanxinren** [comment]
这个问题我也碰到过 你需要自行配置分页插件的配置 
比如
package com.miaozhen.crutch.config;

import com.baomidou.mybatisplus.annotation.DbType;
import com.baomidou.mybatisplus.autoconfigure.ConfigurationCustomizer;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;

/**
 * @author 
 */
@Order(1)
@Configuration
public class MybatisPlusConfig {

    /**
     * 新的分页插件,一缓和二缓遵循mybatis的规则,需要设置 MybatisConfiguration#useDeprecatedExecutor = false 避免缓存出现问题(该属性会在旧插件移除后一同移除)
     * 需要在sqlsessionFactory指定 sqlSessionFactoryBean.setPlugins(xxxxxxxx);
     */
    @Bean("mybatisPlusInterceptor")
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }

    //TODO 使用高版本配置
    @Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseDeprecatedExecutor(false);
    }
}
