### ISSUE TITLE
3.4.0版本: MybatisConfiguration.setGlobalConfig在自动装配过程中被提前调用，导致后续设置globalConfig会失效

### ISSUE THREAD

**Issue by heylear** [baomidou/mybatis-plus#3024]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
    当MybatisConfiguration在globalconfig没有
    public void setGlobalConfig(GlobalConfig globalConfig) {
        GlobalConfigUtils.setGlobalConfig(this, globalConfig);
    }

**Comment by miemieYaho** [comment]
不支持你这么搞

**Comment by heylear** [comment]
> 不支持你这么搞

最简复现:
MainApplication.java

@SpringBootApplication
public class MainApplication {
    public static void main(String[] args) {
        SpringApplication.run(MainApplication.class, args);
    }
}

application.properties

spring.datasource.url=jdbc:mysql://192.168.33.90:3306/ronganai_middle?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
spring.datasource.username=root
spring.datasource.password=shyunzj@sd_dev
# 注意这里，加上后insertFill就不再起作用！！！
mybatis-plus.configuration.global-config.banner=false

DemoEntity.java

@Getter
@Setter
@TableName("t_demo")
public class DemoEntity implements Serializable {

    private static final long serialVersionUID = 1L;
    @TableId(type = IdType.AUTO)
    private Long id;

    @TableField(fill = FieldFill.INSERT)
    private Date createTime;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    private Date updateTime;

    @TableField(select = false)
    private Integer isDeleted;
}

DemoMapper.java

@Mapper
public interface DemoMapper extends BaseMapper<DemoEntity> {
}

DemoTest.java

@Component
@RequiredArgsConstructor
public class DemoTest implements ApplicationListener<ApplicationReadyEvent> {
    private final DemoMapper demoMapper;

    @Override
    public void onApplicationEvent(ApplicationReadyEvent event) {
        demoMapper.insert(new DemoEntity());
    }
}

这个例子中，只要配置文件中配置了mybatis-plus.configuration.global-config前缀的任何属性，insertFill就会失效，因为只要配置了，MybatisConfigruation.setGlobalConfig就会被调用，之后再去调用GlobalConfigUtils.setGlobalConfig就无法覆盖了；

@miemieYaho 你看下
