### ISSUE TITLE
Querylambda  in 数组

### ISSUE THREAD

**Issue by FreeOfYou** [baomidou/mybatis-plus#3025]
### 当前使用版本(必填,否则不予处理)

![image](https://user-images.githubusercontent.com/21058936/97987464-50e17a00-1e16-11eb-997b-36a3a7121946.png)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.0</version>
 </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用Querylambda的时候用in 条件直接接数组参数无法传入进去，传入的为引用地址。

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/21058936/97987889-feed2400-1e16-11eb-9703-e7b211dc9a89.png)

 int[] a={1,3,4};
List<area> areas = areaService.list(Wrappers.<area>query().lambda().in(area::getId, a));

### 报错信息

![image](https://user-images.githubusercontent.com/21058936/97987944-17f5d500-1e17-11eb-8390-51512dd55e47.png)

==>  Preparing: SELECT areaname,id,geoareaid FROM area WHERE (id IN (?))
==> Parameters: [I@3729c084(int[])

**Comment by miemieYaho** [comment]
数组只支持Object[]
