### ISSUE TITLE
多数据源控制台输出bannner多次 

### ISSUE THREAD

**Issue by yanxinren** [baomidou/mybatis-plus#3027]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

配置多个数据源 非主从   控制台输出mybatis plus banner  3次  

### 重现步骤(如果有就写完整)

只是想下一个版本可以关闭这个输出 

### 报错信息
无报错

**Comment by miemieYaho** [comment]
配置里面自己关，看文档

**Comment by yanxinren** [comment]
多数据源 无效！
