### ISSUE TITLE
mybatis和Mybatis Plus如何支持任意类型的JSON字符串的字段转换为对象

### ISSUE THREAD

**Issue by shenbinglife** [baomidou/mybatis-plus#303]
通常情况下，我可以自定义TypeHandler处理一个json字符串的字段，但是这个TypeHandler只会支持一个Java类型。如果我有很多的json字符串字段，并且java类型不同，那么我貌似只能定义很多的TypeHandler。

请问，Mybatis 或者Mybatis Plus 如何支持任意的Java类型，将数据库的json字符串字段通过Json框架转换为实体类的Object类型字段。

另外，对Hibernate ORM有了解的话，请说下Hibernat对该情况是否支持。

**Comment by qmdx** [comment]
多个 TypeHandler 其他解决办法 baidu or google

**Comment by shenbinglife** [comment]
百度和谷歌没有找到我需要的
