### ISSUE TITLE
QueryWrapper#like 字符串参数生成多了引号 导致查询失败

### ISSUE THREAD

**Issue by TanLiangZhong** [baomidou/mybatis-plus#3034]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.4.0

### 重现步骤(如果有就写完整)
`new QueryWrapper<Branch>().like("name", bo.getKeyword())`
Preparing: `SELECT branch_id,
       code,
       name
FROM sys_branch
WHERE del_flag = 0 and (name LIKE ?)`
Parameters： `%'上海'%(String)`

**Comment by miemieYaho** [comment]
mp不会无中生有给你加东西,自己排查
