### ISSUE TITLE
来提需求~~

### ISSUE THREAD

**Issue by chn8lij** [baomidou/mybatis-plus#3035]
使用github不是很熟练,只能找到这个地方跟官方沟通,
想请问mp官方有计划开发多表关联查询这种功能么?类似于hibernate的@OneToMany之类的注解,如果没有的话,我写了个几个注解功能,主要针对于1对1,一对多的场景的,不侵入框架,写在框架之外的,能帮助使用者快速的进行面向对象的关联查询,如果官方大佬们有空看看我的垃圾代码,我就提一个PR,大佬们有空可以自己写一个这样的扩展,增加要求不高的多表关联查询的使用体验
ps: 我自己使用过程中觉得还比较舒适,只考虑开发效率的情况下,确实能节省时间
基本逻辑: 

1. 将mp 初始化 注入的 数据库实体类,数据库,mp的Mapper的映射信息塞到 springboot 启动后的缓存里

2.调用BaseMapper里的单表方法,作为关联查询的基础

3.通过注解标记,将单表查询出来的塞入到 注解标记的字段里, 可以是单个Object,也可以是List

**Comment by miemieYaho** [comment]
无计划,也不会吸收这种东西

**Comment by chn8lij** [comment]
> 无计划,也不会吸收这种东西

为啥呢??

**Comment by miemieYaho** [comment]
我们只做单表的

**Comment by wu9007** [comment]
@chn8lij 666
