### ISSUE TITLE
3.4.0版本的多租户处理，TenantLineHandler接口的getTenantId()方法，什么原因改为只支持单个 ID 值

### ISSUE THREAD

**Issue by 495640129** [baomidou/mybatis-plus#3036]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
TenantLineHandler接口的getTenantId方法改为只支持单个 ID 值，是什么原因？
这个改动源码看到的，未在更新说明里面。

### 重现步骤(如果有就写完整)
3.3.2升级到3.4.0

### 报错信息
之前配置的多租户ID形式，不能升级到3.4.0版本

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/issues/I1ESYP
