### ISSUE TITLE
sososo奇葩的问题，查询字段BigDecimal值时而有时而没有

### ISSUE THREAD

**Issue by lambertlei** [baomidou/mybatis-plus#3037]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

单表查询，查询字段中“actual_payment”之类带下划线，数据类型是BigDecimal，经常出现该列为0.00，但是其他该类型字段有正常值，经过调试，发现jdbc中的“rowBytes”中该“actual_payment”属性值就是0.00.

**Comment by miemieYaho** [comment]
so?
