### ISSUE TITLE
update语句 提示 java.sql.SQLIntegrityConstraintViolationException: Column 'xx' cannot be null

### ISSUE THREAD

**Issue by wangjia2016** [baomidou/mybatis-plus#3039]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
执行update语句

### 重现步骤(如果有就写完整)
<update id="updateGoodStock" parameterType="java.lang.Long" >

    update mall_goods mg inner join (
    select moi.goods_id ,moi.number
    from mall_order_item  moi
    where moi.order_no = #{orderNo,jdbcType=BIGINT}
    ) b on mg.id =b.goods_id
    set mg.stock= mg.stock-b.number

  </update>

### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'stock' cannot be null
; Column 'stock' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'stock' cannot be null

SQL 到navicat 里面执行是正常的  不报错的

**Comment by miemieYaho** [comment]
jql异常你找我们干啥？
