### ISSUE TITLE
OracleTypeConvert类型映射问题

### ISSUE THREAD

**Issue by xingguang2013** [baomidou/mybatis-plus#304]
OracleTypeConvert#processTypeConvert方法中对NUMBER类型的处理，这个正则表达是`NUMBER\(+\d\)`和`NUMBER\(+\d{2}+\)`中的`+`号是否是错误的，这里的意图是否是根据NUMBER的位数，设置Java中不同的类型INTEGER和LONG，不过这个正则表达式感觉没有表达清楚。请予以说明

**Comment by qmdx** [comment]
你可以继承 OracleTypeConvert 修改你要转换的类型，如果 sql 不满足判断，可以查看 https://github.com/baomidou/mybatis-plus/tree/master/mybatis-plus-generate/src/main/java/com/baomidou/mybatisplus/generator/config/querys 注入 自定义 Query 来处理
