### ISSUE TITLE
用@TableLogic逻辑删除时，自动填充列怎么更新时间？

### ISSUE THREAD

**Issue by yxx515** [baomidou/mybatis-plus#3041]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
用@TableLogic逻辑删除时，用@TableField(value = "update_stime", fill = FieldFill.INSERT_UPDATE)注解标识的列没有更新

### 重现步骤(如果有就写完整)

用@TableLogic逻辑删除，会把delete语句变成update语句，理论上用FieldFill.INSERT_UPDATE自动填充的日期列会在update时更新时间，但是实际并没有。

### 报错信息

无

**Comment by miemieYaho** [comment]
自动填充只能填充到entity里

**Comment by lunfangyu** [comment]
遇到同样问题了； 搜索已关闭的 issues ; 说有解决办法：[https://mybatis.plus/guide/faq.html#%E9%80%BB%E8%BE%91%E5%88%A0%E9%99%A4%E4%B8%8B-%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-%E5%8A%9F%E8%83%BD%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C](url) 
点开链接，常见问题里已经没有这个了

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/logic-delete.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
