### ISSUE TITLE
联合组建怎么弄呢？

### ISSUE THREAD

**Issue by Silentdoer** [baomidou/mybatis-plus#3048]
比如表里是pro1和pro2共同组成组建，但是看了下@TableId只能唯一，而没有TableId又提示warn（上级会说），是否增加一个TableCoId来设置联合组建？

**Comment by miemieYaho** [comment]
不支持，注入的byid方法只支持一个id

**Comment by Silentdoer** [comment]
那是否考虑一下@TableCoId？或者没有ID的情况下不需要warn提示？

**Comment by miemieYaho** [comment]
不考虑

**Comment by Silentdoer** [comment]
那这种情况怎么解决呢？这张表不是我们创建的，所以没法弄个单个主键。

**Comment by miemieYaho** [comment]
那你要么随便指定一个或者不指定id,别用byid的方法就行

**Comment by guohongtao0214** [comment]
> 那你要么随便指定一个或者不指定id,别用byid的方法就行

未来还会有联合主键的功能吗
