### ISSUE TITLE
重复主键注解(@TableId )检测

### ISSUE THREAD

**Issue by shguilin** [baomidou/mybatis-plus#3050]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://user-images.githubusercontent.com/55934709/98795629-5f96e500-2445-11eb-856e-d10898d998a1.png)

### 重现步骤(如果有就写完整)
Circle circle = new Circle();
updateById(cirle)

### 报错信息
重复的主键,期望启动时有检测机制，能够告知用户

**Comment by miemieYaho** [comment]
新版有

**Comment by shguilin** [comment]
thanks 张桂林 邮箱：shguilin@gmail.com 签名由 网易邮箱大师 定制 在2020年11月11日 18:04，miemieYaho 写道： 新版有 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
