### ISSUE TITLE
xml 里面的sql写了函数 就会报错

### ISSUE THREAD

**Issue by feipengcheng** [baomidou/mybatis-plus#3052]
### 当前使用版本(必填,否则不予处理)

最新版

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

xml 里面的sql写了函数

### 重现步骤(如果有就写完整)
select
lvg.out_time,
            exists(select 1 from location_warn lw where lw.card_no = lvg.card_no and hand_time is null) ifWarn
        FROM
            location_visitor_log lvg

### 报错信息

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "exists" "EXISTS"

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException

**Comment by lemos1235** [comment]
升级到最新的 jsqlparser 4.0 可以了。
