### ISSUE TITLE
最新版本3.4.1 中使用到了非自包含的组件

### ISSUE THREAD

**Issue by Stefankeep** [baomidou/mybatis-plus#3053]
### 当前使用版本
3.4.1

### 该问题是如何引起的？
Mapper.updateById(model)

### 重现步骤
com.baomidou.mybatisplus.extension.plugins.inner.BlockAttackInnerInterceptor  
中引用了
org.apache.commons.lang3.StringUtils

使用 
spring-boot-starter - 2.3.4.RELEASE
spring-boot-starter-undertow
出现错误

### 报错信息
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

**Comment by miemieYaho** [comment]
可以用 `3.4.1.1-SNAPSHOT`
