### ISSUE TITLE
与flyway启动顺序的问题

### ISSUE THREAD

**Issue by yidasanqian** [baomidou/mybatis-plus#3054]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

最新spring boot项目引入flyway和mybatis-plus-boot-starter，怎么让mybatis-plus-boot-starter在FlywayAutoConfiguration
之后执行？

### 报错信息
提示表不存在，因为sql脚本未被flyway初始化

**Comment by miemieYaho** [comment]
你是在用generator吧
