### ISSUE TITLE
如何针对postgresql数据库构造Page类的order信息？

### ISSUE THREAD

**Issue by 0xkevin** [baomidou/mybatis-plus#3056]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

原因：
postgresql的排序order by有一个坑，和mysql不一样，如果列存在NULL值，默认排序规则是NULL在前，如果想要非NULL的值排在前面，必须使用它独有的SQL语法：order by age desc NULLS LAST。

请问：如何针对分页Page类，构造出这样的order by语句？希望能支持这种动态sql语法

目前的版本只支持以下这种分页查询：
IPage<User> userIPage = userMapper.selectPage(
                  new Page<User>()
                        .setCurrent(1) //设置当前查询页
                        .setSize(3) // 设置每页条数
                        .addOrder(OrderItem.desc("age")),//使用page 进行排序
                new QueryWrapper<User>()
                        .lambda()
                        .likeRight(User::getEmail, "test")
                        .select(User::getId, User::getName, User::getAge)

**Comment by miemieYaho** [comment]
不支持方言,你可以使用最新版并重写分页插件的concatOrderBy方法来用
文档: https://mybatis.plus/guide/interceptor.html
