### ISSUE TITLE
建议获取 @TableName 等注解时，使用 getAnnotation 方法

### ISSUE THREAD

**Issue by lbhfuture** [baomidou/mybatis-plus#3058]
### 当前使用版本(必填,否则不予处理)
v3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
建议获取 @TableName 等注解时，使用 getAnnotation 方法，现在使用的 getDeclaredAnnotation 方法会导致在自定义注解继承 
@TableName 时获取不到该注解。

**Comment by miemieYaho** [comment]
哪里?
