### ISSUE TITLE
配置相关

### ISSUE THREAD

**Issue by liubin95** [baomidou/mybatis-plus#3059]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

能否使用配置类的形式进行所有配置；
像这样的
```
public class SpringWebConfig implements WebMvcConfigurer{

}
```
通过继承，或者实现接口的方式，配置 
`com.baomidou.mybatisplus.core.config.GlobalConfig$DbConfig`
这样的属性

**Comment by miemieYaho** [comment]
starter包里自己去看
