### ISSUE TITLE
单元测试@MockBean时，mybatis plus加载这个Entity的mapper时会出错

### ISSUE THREAD

**Issue by shijieahi** [baomidou/mybatis-plus#3064]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
复用JVM时，发现启动mybatis plus时会报错。情况是，如果有Entity使用了@TableName(autoResultMap = true)，单元测试中使用了@MockBean时，mybatis plus加载这个Entity的mapper时会出错

**Comment by miemieYaho** [comment]
3.4.1
