### ISSUE TITLE
使用官网推荐的IService及ServiceImpl时，报错找不到getBaseMapper()

### ISSUE THREAD

**Issue by ye17186** [baomidou/mybatis-plus#3065]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.4.0

### 重现步骤(如果有就写完整)
接口：
 public interface UserService extends IService<User> {}
实现类：
@Service
public class UserServiceImpl extends ServiceImpl<UserMapper, User> implements UserService {
}

使用：
@Autowired
UserService  userService;
@Autowired
UserMapper usreMapper

userMapper.selectOne() => 这样用没有问题
userService.getOne()  => 这样用报错，getBaseMapper()找不到

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-assembly/src/main/java/com/baomidou/mybatisplus/samples/assembly/AssemblyApplication.java

**Comment by ye17186** [comment]
补充，我的mapper.java 放在com.a.b.c.mapper包中，如果我MapperScan指定com.a.b.c，则会出现上述问题。如果我MapperScan指定com.a.b.c.mapper，则不会出现该问题

**Comment by miemieYaho** [comment]
扫包不要范围大了,mybatis会把你指定包下的所有interface都认成mapper

**Comment by HitSoul** [comment]
> 扫包不要范围大了,mybatis会把你指定包下的所有interface都认成mapper

good idea
