### ISSUE TITLE
使用LocalDate还是无法使用

### ISSUE THREAD

**Issue by haopangang** [baomidou/mybatis-plus#3066]
### 当前使用版本(必填,否则不予处理)
3.4.1 版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`final LocalDate localDate = LocalDate.now().plusDays(queryConds.getSigningDays());
   queryWrapper.ge(EmployeeContract.COL_SIGNING_OPERATE_DATE, localDate);
`
查询代码这样查询不出任何结果，按照下面写，则没问题，能查询出结果
![image](https://user-images.githubusercontent.com/24272650/99356086-81c8b100-28e4-11eb-85cd-4289a684fc2c.png)

**Comment by yangyonglin** [comment]
这个问题真的是继续解决一下

**Comment by miemieYaho** [comment]
自己去排查咯,执行sql又不是mp在做

**Comment by haopangang** [comment]
> ,

执行sql不是在mp做的。这个mp支持一下那不就完美了
