### ISSUE TITLE
JacksonTypeHandler 作用在List<IEnum>上，入库的时候会存枚举名，不会@EnumValue 标示的值

### ISSUE THREAD

**Issue by 294100330** [baomidou/mybatis-plus#3067]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.1依然

### 重现步骤(如果有就写完整)
数据库
版本:mysql8，使用json类型

Java 
将 @TableField(typeHandler = JacksonTypeHandler.class) 打在List<TestEnum>上，TestEnum实现了IEnum，并在TestEnum指定属性上配置了 @EnumValue，入库之后，数据库会存["Test1"]，不会存被@EnumValue指定的属性值

**Comment by miemieYaho** [comment]
不支持 list和map
