### ISSUE TITLE
请教贴：hibernate迁移mybaits plus主键自增长相关问题

### ISSUE THREAD

**Issue by minmy** [baomidou/mybatis-plus#3070]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

mybatis plus自身功能无法实现

###问题描述
已知oracle主键自增长可以通过@KeySequence指定序列，但旧的hibernate项目是通过一张单独的表要存储id，而非序列，请问mybatis plus自身功能该如何实现？
例如hibernate中：
@Id
@GeneratedValue(strategy = GenerationType.TABLE, generator = "xxx")
@TableGenerator(table = Serial.SEQUENCE_TABLE_NAME, name = "xxx"", allocationSize = 1, pkColumnValue = "列值")
protected Integer id;

上诉这种id生成策略该如何实现？自定义主键生成器又怕影响性能！
感谢回答

**Comment by huayanYu** [comment]
@minmy 就用自定义主键生成器啊， 你都存在表里的。 再怎么都要查表插表，无法避免的问题。

性能差不了啥。
