### ISSUE TITLE
wrapper.in(column,list) list为空时 ,最常的需求是,把 " in( ) "替换为 "1=0"

### ISSUE THREAD

**Issue by qaz4042** [baomidou/mybatis-plus#3071]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

wrapper.in(column,list) list为空时 
我觉得最常的需求是,把 " in( ) "替换为 "1=0"
不需要在业务冗余其他代码

**Comment by miemieYaho** [comment]
自己去处理
