### ISSUE TITLE
自动填充功能：逻辑删除removeById();不自动更新FieldFill.INSERT_UPDATE字段

### ISSUE THREAD

**Issue by zdwsheng** [baomidou/mybatis-plus#3072]
### 当前使用版本(必填,否则不予处理)
<version>3.4.1</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
@TableField(fill = FieldFill.INSERT_UPDATE)
    @JsonIgnore
    private LocalDateTime updateTime;
配置了自动填充字段和逻辑删除，但是调用removeById();不会去自动更新，调用updateById()是可以的。

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/logic-delete.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by coding-weilong** [comment]
> https://mybatis.plus/guide/logic-delete.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

打不开了...
