### ISSUE TITLE
BlockAttackInnerInterceptor报错

### ISSUE THREAD

**Issue by brucewuu520** [baomidou/mybatis-plus#3073]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
BlockAttackInnerInterceptor类使用了org.apache.commons.lang3.StringUtils;导致报NoClassDefFoundError错误

### 报错信息
nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

**Comment by miemieYaho** [comment]
可以用 `3.4.1.1-SNAPSHOT`

**Comment by LjyDeerWhale** [comment]
需要加入         <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.11</version>
        </dependency>
依赖

**Comment by huayanYu** [comment]
3.4.2
