### ISSUE TITLE
Page 分页，是否可以像PageHelper需要分页时传入对应的pagenum和pagesize，不需要分页时设置pagesize=0

### ISSUE THREAD

**Issue by xiaofeng010766** [baomidou/mybatis-plus#3075]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 版本 3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Page<Map<String, Object>> page = new Page<>(pageNum, pageSize);
想根据实际场景判断是否需要分页，查看源码发现设置pageSize<0时，不会分页，但是不分页，total能否查询一并给出呢？
难道还需要自行判断分页时获取page.getTotal();不分页时获取page.getRecords().size()?这有点不智能了吧

![image](https://user-images.githubusercontent.com/7794555/99626527-57eec600-2a6d-11eb-8e7e-561a581103a5.png)

**Comment by GeorgeAnson** [comment]
page.size<0

**Comment by xiaofeng010766** [comment]
问题时不分页，我看到了pagesize<0可以实现，那么我想在不分页的同时，能否返回查询到的数据量总条数？意思就是能否帮我执行select count(1) from xxxx。然后再Page对象中将records和total一并返回呢？

**Comment by miemieYaho** [comment]
不分页还count个什么,你自己的业务自己去处理
