### ISSUE TITLE
非主键字段如何实现像主键自增的方案

### ISSUE THREAD

**Issue by Bertluo** [baomidou/mybatis-plus#3076]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

主键已经被使用，需要维护一个序列号（唯一自增）

**Comment by huayanYu** [comment]
无法，只能参照自动填充，自己来维护。

**Comment by Antenbabby** [comment]
这样就可以了  @TableField(value = "auto_id", insertStrategy = FieldStrategy.NEVER)
