### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zhengwen6300** [baomidou/mybatis-plus#308]
建议加上selectCountById方法，这样就不用每次写wrapper了。
在查询的时候增加对返回类型的设置，这样查询单个字段就不用每次都是查询对象或对象集合之后再获取或循环获取。

**Comment by qmdx** [comment]
selectCountById 根据主键这么查表不是永远只是 1 ？

**Comment by zhengwen6300** [comment]
不一定哦，可能为0哦，用来判断资源ID是否合法

**Comment by qmdx** [comment]
@zhengwen6300  我的建议是在通用  service 层处理这个问题
