### ISSUE TITLE
如何设置MybatisSqlSessionFactoryBean.setTypeHandlers这个属性?

### ISSUE THREAD

**Issue by zhady009** [baomidou/mybatis-plus#3081]
使用版本3.1.2

因为使用的typeHanlder有个构造方法是依赖Bean的
不能用getTypeHandlerRegistry.register()方法来注册, mybatis依旧会自己反射创建该typeHandler

所以想要使用MybatisSqlSessionFactoryBean内的setTypeHandlers方法来把实例对象设置进去
找了相关资料都没有类似的设置, 目前的解决方法是直接把自动配置类里面的复制过来了..不优雅

**Comment by miemieYaho** [comment]
看源码就应该知道MybatisSqlSessionFactoryBean的typeHanlders最终还是会getTypeHandlerRegistry.register()方法来注册

**Comment by zhady009** [comment]
> 看源码就应该知道MybatisSqlSessionFactoryBean的typeHanlders最终还是会getTypeHandlerRegistry.register()方法来注册

今天上班看了一下,是因为type handler package的原因,那几个handler都在同一个包里面(有些handler不依赖bean),所以就用反射去创建实例了.

感觉stream.filter那个过滤也要加上typeHandlers属性对应的class

**Comment by miemieYaho** [comment]
不会有
