### ISSUE TITLE
升级到3.4.1后  PageHelper.startPage(1,0) 没生效 

### ISSUE THREAD

**Issue by dengjin001** [baomidou/mybatis-plus#3082]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!
从3.3.1升级到3.4.1后 修改MybatisPlusConfig 配置
3.3.1：
`@Bean
    public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
        List<ISqlParser> sqlParserList = new ArrayList<>();
        sqlParserList.add(new BlockAttackSqlParser());
        paginationInterceptor.setSqlParserList(sqlParserList);
        return paginationInterceptor;
    }`

3.4.1:
`    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new BlockAttackInnerInterceptor());
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor());
        return interceptor;
    }`

### 重现步骤(如果有就写完整)
PageHelper.startPage(1,0) ;
List<user> result=selectListxxx;
new PageInfo<result>;
查出了所有的数据Total有数据 但是返回的pageInfo中list数据为空

### 报错信息

![image](https://user-images.githubusercontent.com/29300542/99784862-5dc0d600-2b57-11eb-833e-71b5ae48e0c7.png)

**Comment by miemieYaho** [comment]
早就不支持 PageHelper.startPage,你直接用 PageHelper 吧
