### ISSUE TITLE
baseMapper.selectById(Id)查不到数据，但数据库中的确有数据

### ISSUE THREAD

**Issue by alun135998** [baomidou/mybatis-plus#3083]
### 当前使用版本(必填,否则不予处理)

<mybatis-plus.version>3.0.5</mybatis-plus.version>

### 重现步骤(如果有就写完整)
使用MP的BaseMapper.selectById(Id)查询结果为null，但是数据库中有相关记录

**Comment by zhouyongshen** [comment]
您好，能说一下产生这个问题的原因吗？

**Comment by alun135998** [comment]
![Uploading image.png…]()

**Comment by alun135998** [comment]
由于周末有事在忙，所以现在才把代码片段发送过来，不好意思。代码片段请查看附件，谢谢。













在 2020-11-20 18:32:49，"叶枫" <notifications@github.com> 写道：

您好，能说一下产生这个问题的原因吗？
