### ISSUE TITLE
想要加入 优秀案例 列表 奈何找不到联系组织的方式 只能提交 issues了

### ISSUE THREAD

**Issue by hiparker** [baomidou/mybatis-plus#3086]
目前个人出于学习的目的做了一套开源框架,  内数据处理 采用 mybatis-plus

完全免费开源

官网地址: https://opsli.com
Logo: https://www.opsli.com/logo.png
github: https://github.com/hiparker/opsli-boot

**Comment by hiparker** [comment]
OPSLI 快速开发平台基于springboot、vue、element-ui ，项目采用前后端分离架构，热插拔式业务模块与插件扩展性高 ,代码简洁，功能丰富，开箱即用，帮助Java项目解决70%的重复工作，让开发更关注业务逻辑，既能快速提高效率，节省研发成本，同时又不失灵活性！

**Comment by qmdx** [comment]
已收录
