### ISSUE TITLE
新版3.4.1 生成的count sql不正确

### ISSUE THREAD

**Issue by lsw1990** [baomidou/mybatis-plus#3089]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
链表查询测试遇到的，分页count不正确，被优化的感觉，但是这种优化感觉不正确

### 重现步骤(如果有就写完整)
`@Select("""
            select t1.name,t2.account_name from user_info t1
                left join user_account t2 on t1.id = t2.user_id
                where t1.id = 1
            """)
    Page<UserInfo> getUserInfoPage(Page<UserInfo> page);`
`打印出来的count sql为
SELECT COUNT(*) FROM user_info t1 WHERE t1.id = 1`
实际正常运行count应该是3，但是count不知道为什么优化成这样子，需求期望是和原sql保持一致

### 报错信息

count sql不正确

**Comment by miemieYaho** [comment]
默认对 left join 进行优化,虽然能优化count,但是加上分页的话如果1对多本身结果条数就是不正确的,
不想要就自己重写里面的autoCountSql方法
