### ISSUE TITLE
Pagination 对象 bug 及修复建议

### ISSUE THREAD

**Issue by WangLejiang** [baomidou/mybatis-plus#309]
由于一些原因，分页查询的对象并不是传给前端的对象，需要把 Page<A> 转成 Page<B>
于是我进行了参数转换：
`BeanUtils.copyProperties(pageA, pageB);`
按常理 Page 对象的基本参数都能转过来，但在调用 pageB.hasNext() 的时候始终为 false。

原因：
Page 对象继承了 Pagination，
Pagination 里 hasNext() 函数调用了成员变量 this.pages，但 this.pages 没有 set方法，所以 copyProperties 的时候没有初始化，在 getPages() 才能通过计算来初始化。
导致进行过 copyProperties 操作的 Page 对象在调用 hasNext() 之前必须调用 getPages()，否则会得到错误结果。

源代码：
```
public int getPages() {
        if(this.size == 0) {
            return 0;
        } else {
            this.pages = this.total / this.size;
            if(this.total % this.size != 0) {
                ++this.pages;
            }
            return this.pages;
        }
    }
```

建议：
既然 Pagination 中的 this.pages 为计算属性，则可以将 pages 这个成员变量改为局部变量，在其他用到成员变量的地方直接调用函数 getPages() 即可，这样就避免了 getPages() 来初始化的尴尬。

**Comment by qmdx** [comment]
感谢反馈 https://github.com/baomidou/mybatis-plus/commit/00e1f0057889c1f0d08ad8558fbd08fe4f627502  请关注 下一个版本的发布
