### ISSUE TITLE
可否让通用BaseMapper 中的通用方法在XML中有对应语句的时候执行自己写的SQL语句

### ISSUE THREAD

**Issue by atliwen** [baomidou/mybatis-plus#3094]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

可否让通用BaseMapper 中的通用方法在XML中有对应语句的时候执行自己写的SQL语句

### 重现步骤(如果有就写完整)
可否让通用BaseMapper 中的通用方法在XML中有对应语句的时候执行自己写的SQL语句

**Comment by miemieYaho** [comment]
本身就可以

**Comment by atliwen** [comment]
能说一下怎么设置吗，我测试就不行啊？

![image](https://user-images.githubusercontent.com/10055836/100063317-029b2600-2e6c-11eb-8c1b-9b578468a5b6.png)

XML 设置同样的接口方法名称， 实际执行还是  BaseMapper 原本的语句

**Comment by atliwen** [comment]
> 本身就可以

能说一下 如何设置吗，我直接在XML 中写与 BaseMapper  接口的 selectList 方法 语句，执行的还是  BaseMapper   生成出来的语句。

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/rewrite/RewriteTest.java

**Comment by miemieYaho** [comment]
那你是没加载到mapper.xml

**Comment by atliwen** [comment]
> 那你是没加载到mapper.xml

！！！！ 谢谢了！还真是！！ 自己写的代码生成的模板，XML文件路径设置没有读取到文件！
