### ISSUE TITLE
多数据源分页sqlserver有问题

### ISSUE THREAD

**Issue by pozxnm123** [baomidou/mybatis-plus#3096]
### 当前使用版本(必填,否则不予处理)
mybatis-plus version: 3.4.0
dynamic-datasource-spring-boot-starter  version: '3.2.1'

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

目前使用多数据源 Postgresql (主要) 和 Sqlserver
如果 Service 是使用 SqlServer 分页这里后段会是以
LIMIT ? 呈现

### 报错信息

```


org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.


```

**Comment by miemieYaho** [comment]
你数据源没切换成功吧,你给个复现demo出来

**Comment by pozxnm123** [comment]
@miemieYaho 

目前配置是这样
![1606202269774](https://user-images.githubusercontent.com/18299406/100108383-ae149c80-2ea5-11eb-9656-6e140465dc98.jpg)
![1606228444994](https://user-images.githubusercontent.com/18299406/100108386-afde6000-2ea5-11eb-85a0-fa77e4be1d3e.jpg)


数据源切换应该是有成功的

若使用 IPage 则会出现错误

```

 @Service("ABC")
 @DS("sqlserver")
public class ABCImpl extends ServiceImpl<ABCDAO, ABC> implements IABCService {

    @Override
    public IPage<ABC> selectList() {
        LambdaQueryWrapper<ABC> queryWrapper = new LambdaQueryWrapper<>();
        queryWrapper.orderByDesc(ABC::getDataKey);
        return this.page(PageFactory.defaultPage(), queryWrapper);
    }
}

```

若使用 list 可以正常输出

```

@Service("ABC")
@DS("sqlserver")
public class HealthCarrOrderMainServiceImpl extends ServiceImpl<HealthCarrOrderMainDAO, HealthCarrOrderMain> implements IHealthCarrOrderMainService {

    @Override
    public List<HealthCarrOrderMain> selectList() {
        LambdaQueryWrapper<HealthCarrOrderMain> queryWrapper = new LambdaQueryWrapper<>();
        queryWrapper.orderByDesc(HealthCarrOrderMain::getDataKey);

        return this.list(queryWrapper);
    }
}


```

**Comment by miemieYaho** [comment]
分页插件构造函数把你指定的dbtype删了

**Comment by pozxnm123** [comment]
@miemieYaho 
抱歉小弟太浅, 这部分想请教一下能怎么做呢~?

**Comment by miemieYaho** [comment]
分页插件不指定dbtype，而且你那dbtype是h2，真就cv代码不需要动脑吗？

**Comment by pozxnm123** [comment]
@miemieYaho 
理解了, 抱歉没注意到这块 , 感谢!!

**Comment by t0rjan** [comment]
在自定义声明DataSourceConfig那里，SqlSessionFactory bean的部分，加上这个，不同的数据源，自己选择不同的DbType
    MybatisSqlSessionFactoryBean bean = new MybatisSqlSessionFactoryBean();
    //分页
    MybatisPlusInterceptor mybatisPlusInterceptor = new MybatisPlusInterceptor();
    mybatisPlusInterceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.SQL_SERVER));
    bean.setPlugins(mybatisPlusInterceptor)
