### ISSUE TITLE
关于QueryWrapper(T entity)的说明文档上哪看？

### ISSUE THREAD

**Issue by 157677678** [baomidou/mybatis-plus#3098]
在官网当前文档，及大多数搜索结果中，查询都没有提到Wrapper可以根据entity实例化。
多亏慕课网 3-8 那个视频 提到才看到。 
请在文档着重强调一下这个方法吧，个人认为比lamdawrapper那个更容易。

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/wrapper.html#abstractwrapper

**Comment by liubinylx** [comment]
> https://mybatis.plus/guide/wrapper.html#abstractwrapper

这文档正常人是看不懂的，只有脑子有问题的人才看的懂
