### ISSUE TITLE
能否支持json查询？

### ISSUE THREAD

**Issue by tianxin8206** [baomidou/mybatis-plus#3099]
### 当前使用版本(必填,否则不予处理)
3.4.0

目前各数据库对json存储、查询等已经支持的比较好了，能否考虑支持json的相关查询？

**Comment by miemieYaho** [comment]
没有

**Comment by aozhilin1** [comment]
早就可以查询了吧？我的都可以拿来查询

**Comment by wangjia2016** [comment]
> 早就可以查询了吧？我的都可以拿来查询

mybatiplus 都不支持，怎么查json字段？

**Comment by aozhilin1** [comment]
mybatiplus 支持json增删改查，只是修改会有点问题！

**Comment by wangjia2016** [comment]
> mybatiplus 支持json增删改查，只是修改会有点问题！

queryWrapper.apply("JSON_CONTAINS(

这样查询？

**Comment by aozhilin1** [comment]
> > mybatiplus 支持json增删改查，只是修改会有点问题！
> 
> queryWrapper.apply("JSON_CONTAINS(
> 
> 这样查询？

可以百度搜索下，就是加点注解配置一下

**Comment by aozhilin1** [comment]
> > mybatiplus 支持json增删改查，只是修改会有点问题！
> 
> queryWrapper.apply("JSON_CONTAINS(
> 
> 这样查询？

https://www.cnblogs.com/changchangchang/p/13121407.html 可以参考一下这个， 自己再百度百度！
