### ISSUE TITLE
分页参数传{     "page":0,     "size":1000 }最多取出来500条记录

### ISSUE THREAD

**Issue by Jackson-zhanganbing** [baomidou/mybatis-plus#3102]
### 当前使用版本(必填,否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

基础分页查询，入参
{     "page":0,     "size":1000 }

### 报错信息
未报错，只是结果不对，本意取1000条，但是只有500条。发现自行添加了limit 0,500，与传入size参数不符！

**Comment by miemieYaho** [comment]
新版分页插件没默认限制最大limit数
