### ISSUE TITLE
先slectById或者selectOne再执行updateById更新不成功

### ISSUE THREAD

**Issue by Rovebiy** [baomidou/mybatis-plus#3103]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
先查出bus，再用这个bus更新其中的某个值，更新不成功
Bus bus = busMapper.selectById(student.getCarNo());
bus.set();
busMapper.updateById(bus);

### 报错信息
没报错

**Comment by Rovebiy** [comment]
发现问题了，用了某个属性做乐观锁，必须把这个属性重新设值改变才行

**Comment by Rovebiy** [comment]
能不能处理一下这个问题

**Comment by miemieYaho** [comment]
处理啥？你不会看执行的sql排查问题吗？我们可没什么好处理的

**Comment by Rovebiy** [comment]
问题不是已经说了吗?你们updateById的时候能不能判断一下除了乐观锁的其他属性如果有改变的话，就改变一下乐观锁的值,这不算问题吗?我现在是自己查出来的时候再更新需要自己手动修改乐观锁的值，我是用更新时间作为乐观锁。

**Comment by miemieYaho** [comment]
本身你参数带上乐观锁的旧值就会给个新值,你说没给那你就写个复现demo出来

**Comment by huayanYu** [comment]
无回复，关闭。
