### ISSUE TITLE
 如何取消这些提示This primary key of "id" is primitive !不建议如此请使用包装类 

### ISSUE THREAD

**Issue by wuxingdefeng** [baomidou/mybatis-plus#3106]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动提示，如何取消这个提示

### 报错信息

 This primary key of "id" is primitive !不建议如此请使用包装类

**Comment by miemieYaho** [comment]
取消不了,你改成包装类就没这提示了

**Comment by Muyangmin** [comment]
我使用的是 Kotlin 的数字类（如 `Long`, `Int` 之类），它们与Java 的基本类型并不一样，而且使用 Kotlin 的时候并不鼓励使用Java原生的包装类。能否增加判断，对于 kotlin 的数字类不做告警呢？
