### ISSUE TITLE
这个Model这里面这个日志的依赖能不能换成注解的方式,我看这里好只有查询操作才有用,我如果基础baseEntiy继承,这个log这个字段也会继承过去,我生成Mongo的Doc对象就会报错

### ISSUE THREAD

**Issue by zenas001** [baomidou/mybatis-plus#3108]
https://github.com/baomidou/mybatis-plus/blob/917d68854275ac9c854d24a18ffbd93652f4b0aa/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/activerecord/Model.java#L50

https://github.com/baomidou/mybatis-plus/blob/917d68854275ac9c854d24a18ffbd93652f4b0aa/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/activerecord/Model.java#L199

**Comment by miemieYaho** [comment]
不能,mp内部日志都得用 mybatis的
