### ISSUE TITLE
麻烦更新下官方文档，自定义SQL还得需要自己inject()实现方法

### ISSUE THREAD

**Issue by qq29oo** [baomidou/mybatis-plus#311]
自定义SQL还得需要自己inject()实现方法，麻烦把这个点写在官方文档上啊，文档里压根都没提到，Debug找了半天才看到代码注释里写了需要自己实现inject，坑

**Comment by pyzheng** [comment]
我参考了 https://www.cnblogs.com/liuyangfirst/p/9744011.html  终于把自己自定义的deleteAll()注入了，可是，默认的方法却找不到了？  
官方的文档 https://mp.baomidou.com/guide/sql-injector.html 很抽象，实在太抽象了，几乎看不懂的。
不知道该说什么好
