### ISSUE TITLE
IPage返回的getTotal getPages都是0

### ISSUE THREAD

**Issue by kiritokun07** [baomidou/mybatis-plus#3110]
### 当前使用版本
`<mybatis-plus.version>3.4.1</mybatis-plus.version>`

### 该问题是如何引起的？
按[官方文档-插件主体(since 3.4.0)](https://baomidou.com/guide/interceptor.html)
MP从**3.4.0**以后分页拦截器由`PaginationInterceptor`变成了`inner.PaginationInnerInterceptor`
导致使用IPage分页获取的`getTotal`和`getPages`的值都是0。当我把版本改回**3.1.1**后，分页功能正常

### 重现步骤(如果有就写完整)
```
@Configuration
@MapperScan("com.demo.service.mapper")
public class MybatisPlusConfig {
    @Bean //配置分页插件
    public PaginationInterceptor paginationInterceptor(){
        return new PaginationInterceptor();
    }
}
```
```
    @Test
    public void testSelectPage(){
        Page<Student> page=new Page<>(1,1); //查询第一页，查询1条数据

        QueryWrapper<Student> wrapper=new QueryWrapper<>();
        wrapper.like("Name","xxx");
        IPage<Student> iPage = studentMapper.selectPage(page, wrapper);
        System.out.println("数据总条数："+iPage.getTotal());
        System.out.println("数据总页数："+iPage.getPages());
        System.out.println("当前页数："+iPage.getCurrent());

        iPage.getRecords().forEach(System.out::println);
    }
```
output:
数据总条数：0
数据总页数：0
当前页数：1
.....（getRecords正常）

### 报错信息
暂无

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-pagination/src/main/java/com/baomidou/mybatisplus/samples/pagination/config/MybatisPlusConfig.java

**Comment by bain2018** [comment]
解决了吗，我也是这样，但么有解决啊

**Comment by itming001** [comment]
问题咋解决的？
