### ISSUE TITLE
select列不支持like concat?

### ISSUE THREAD

**Issue by oopsRookie** [baomidou/mybatis-plus#3113]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
select查询时，在查询结果上使用了like, concat

### 重现步骤(如果有就写完整)
select usename, **username like concat('%',#{username},'%') AS similar**

### 报错信息
sqlParser里like不是如下所预期的字符中的一个。

### 补充
concat也会报这个错，是由于mybatis不支持LIKE concat作为查询列的条件吗？
数据库中这句sql是可以正常执行的，原因在通不过sqlParser的sql解析。

**Comment by lunxian8** [comment]
@SqlParsel 过滤掉？

**Comment by ye17186** [comment]
这个歌jsqlParser的问题，可以通过@InterceptorIgnore过滤掉。或者升级jsqlParser 3.2 -> 4.0

**Comment by oopsRookie** [comment]
> 
> 
> 这个歌jsqlParser的问题，可以通过@InterceptorIgnore过滤掉。或者升级jsqlParser 3.2 -> 4.0

感谢！
