### ISSUE TITLE
@Table失效

### ISSUE THREAD

**Issue by xcmonline** [baomidou/mybatis-plus#3114]
3.4.1

因原来使用 mybaits升级到 mybaits-plus 原数据库实体类中使用了 @Table表明与数据库关系。但在升级后执行SQL使用了类名加下划线，因原来的实体类名加了Entity，目前 mybaits-plus 每张表都加了_entity，@Table中指定的name="表名"无效。

执行SQL时表名不存在。

**Comment by miemieYaho** [comment]
1. mybatis 没有叫 Table 的注解
2. mybaits-plus 该怎么用去看文档
