### ISSUE TITLE
希望无缝兼容dynamic-datasource

### ISSUE THREAD

**Issue by lizhuangs** [baomidou/mybatis-plus#3115]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
[https://baomidou.gitee.io/dynamic-datasource-doc/guide/integration/MybatisPlus.html#%E5%9F%BA%E7%A1%80%E4%BB%8B%E7%BB%8D](url)
mp内置的ServiceImpl在新增,更改,删除等一些方法上自带事物导致不能切换数据源。

这2个的核心作者好像都是青苗吧，不过其它框架没有这个问题，我现在想集成这2个，看到这个问题就不敢用了。
项目中使用自带的save,delete,update基本上全是。
所以上面说的，mp内置的方法事务是否是可选开关更灵活一点？

**Comment by miemieYaho** [comment]
没有开关
