### ISSUE TITLE
请问如果只是想删除一个Wrapper里面的东西，该怎么删除呢？

### ISSUE THREAD

**Issue by oxcz** [baomidou/mybatis-plus#3116]
### 当前使用版本(必填,否则不予处理)
最新
在之前的Wrapper里面eq了一个东西
后面根据条件判断不要eq了
请问怎么在Wrapper里面把这个删除了，找了一下好像没有这个方法。
谢谢～～～

**Comment by miemieYaho** [comment]
删除不了

**Comment by oxcz** [comment]
> 删除不了

不考虑增加这个特性吗？感觉有些场景还是有需求的。

**Comment by miemieYaho** [comment]
加不了也没必要
