### ISSUE TITLE
对于mybatis-plus框架要生成的SQL语句，如果已经在 mapper.xml 文件中定义了，用的还是框架生成的，期望是用 自己写的

### ISSUE THREAD

**Issue by fangjinuo** [baomidou/mybatis-plus#3123]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
从mybatis迁移到mybatis-plus后
原来的 mapper.xml 文件中是写了 selectById 语句的，
迁移后，执行的不是 自定义的SQL语句，而是 mybatis-plus生成的。

由此情况，存在这样的情况：
     对于mybatis-plus 要自动生成的语句，默认采用了框架生成的，而没有采用 自定义的sql语句，
一旦自定义的SQL语句里，有特殊的逻辑，可能会因为迁移到Mybatis-plus后，导致原有的业务失败。

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/3094
