### ISSUE TITLE
mybatis-plus使用数据安全保护功能 问题

### ISSUE THREAD

**Issue by xuguangyao** [baomidou/mybatis-plus#3126]
### 当前使用版本(必填,否则不予处理)
版本：3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

结合Druid数据连接池连接数据库报错。

![image](https://user-images.githubusercontent.com/32193099/100961063-9059ce00-355c-11eb-80b2-938f4f810023.png)

![image](https://user-images.githubusercontent.com/32193099/100960823-06116a00-355c-11eb-9d56-1ce40727b46e.png)

### 重现步骤(如果有就写完整)

希望帮忙看下，如何解决

**Comment by huayanYu** [comment]
@xuguangyao  动态数据源有自带的参数加密方法，建议使用其自带的。
