### ISSUE TITLE
集成启动报错-org.mybatis.logging.LoggerFactory

### ISSUE THREAD

**Issue by romantictravel01** [baomidou/mybatis-plus#3130]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

启动

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/59325449/101114867-51d81800-361d-11eb-8cd8-4ef699e5d32c.png)
![image](https://user-images.githubusercontent.com/59325449/101114878-569ccc00-361d-11eb-8d1e-36f3eb9c947b.png)

### 报错信息
![image](https://user-images.githubusercontent.com/59325449/101114954-76cc8b00-361d-11eb-85bb-3d2196e51c6a.png)

**Comment by miemieYaho** [comment]
mybatis-spring 版本冲突
