### ISSUE TITLE
ServiceImpl类的批量插入方法，当i=0时就调用了一次flushStatements()方法

### ISSUE THREAD

**Issue by zycmws** [baomidou/mybatis-plus#314]
/**
	 * 批量插入
	 *
	 * @param entityList
	 * @param batchSize
	 * @return
	 */
	public boolean insertBatch(List<T> entityList, int batchSize) {
		if (CollectionUtils.isEmpty(entityList)) {
			throw new IllegalArgumentException("Error: entityList must not be empty");
		}
		SqlSession batchSqlSession = sqlSessionBatch();
		try {
			int size = entityList.size();
			for (int i = 0; i < size; i++) {
				batchSqlSession.insert(sqlStatement(SqlMethod.INSERT_ONE), entityList.get(i));
				if (i % batchSize == 0) {
					batchSqlSession.flushStatements();
				}
			}
			batchSqlSession.flushStatements();
		} catch (Exception e) {
			logger.warn("Error: Cannot execute insertBatch Method. Cause:" + e);
			return false;
		}
		return true;

	}

**Comment by qmdx** [comment]
怎么会等于 0 呢？

**Comment by zycmws** [comment]
for (int i = 0; i < size; i++) {}
这里从0开始遍历的呀，i++是在循环体执行完再执行的

**Comment by qmdx** [comment]
感谢反馈已经修复
