### ISSUE TITLE
queryWrapper.eq(column, val)条件构造器里的val值为null时的处理

### ISSUE THREAD

**Issue by BiYanzhao** [baomidou/mybatis-plus#3140]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

queryWrapper.eq(column, val)，当条件构造器里的val值为null时，是不是可以自动处理为column is null，目前结果是 = null

### 重现步骤(如果有就写完整)

==>  Preparing: SELECT *  FROM table WHERE (column1= ? AND column2= ? AND column3= ? AND column4= ?) 
==> Parameters: 1(String), 2(String), 3(String), null
<==      Total: 0

**Comment by huayanYu** [comment]
不行,mp提供了先判断是否拼接的方法， 建议程序员开发自行判断。

**Comment by BiYanzhao** [comment]
> 不行,mp提供了先判断是否拼接的方法， 建议程序员开发自行判断。

找到allEq方法了，感谢
