### ISSUE TITLE
请教一下关于分页方言扩展的问题

### ISSUE THREAD

**Issue by aiolosgs** [baomidou/mybatis-plus#3145]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我们的产品中需要适配Gbase8s，目前我们的解决方案是覆盖了mp中的DbType、DialectRegistry、JdbcUtils这几个类，并且添加了Gbase8s的IDialect的实现类，可是这样的话在升级mybatis-plus的时候就很麻烦，需要对覆盖的类进行差异对比，想请教下有没有其他的方法对方言进行扩展？

**Comment by miemieYaho** [comment]
重写新分页插件的 findIDialect 方法

**Comment by aiolosgs** [comment]
懂了，我试下，多谢
