### ISSUE TITLE
selectPage PaginationInnerInterceptor分页插件 不返回 total 始终是0

### ISSUE THREAD

**Issue by MOEKIRITO** [baomidou/mybatis-plus#3147]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
从3.3.2版本更新为3.4.1后 selectPage 不返回 total，分页插件为 PaginationInnerInterceptor，并且 new Page 的 isSearchCount 为 true

### 重现步骤(如果有就写完整)
用PaginationInnerInterceptor 插件不返回total，继续使用3.4.1，但分页插件换回 PaginationInterceptor 可正常返回total

### 报错信息
无

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html
