### ISSUE TITLE
是否支持自定义排序

### ISSUE THREAD

**Issue by lsiuf** [baomidou/mybatis-plus#3148]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 代码片段
`order by FIELD(status, 1, 0, 2, 3) ASC, start_time desc`

**Comment by miemieYaho** [comment]
用普通 queryWrapper.orderByAsc("FIELD(status, 1, 0, 2, 3)")

**Comment by lsiuf** [comment]
谢谢
