### ISSUE TITLE
Failed to process, please exclude the tableName or statementId.

### ISSUE THREAD

**Issue by latmns** [baomidou/mybatis-plus#3149]
version: 3.4.1

SQL:
<select id="testFun1" resultType="java.util.HashMap">
        SELECT
        ticket.EINVOICECODE as ticketCode,
        ticket.EINVOICENUMBER as ticketNumber,
        ticket.SERIANUMBER as bizCode,
        ticket.MAINTYPE as mainType,
        ticket.PATIENTNUMBER visitNumber,
        ticket.STATUS as ticketStatus,
        ticket.KPDATE as kpDate,
        CASE WHEN ticket.REDCODE is Null THEN 0 ELSE 1 END AS isRed,
        ticket.REDCODE as redCode,
        ticket.REDNUMBER as redNumber,
        CASE WHEN ticket.MAINTYPE = 1 then
        (select CONCAT(@pName:=mz.PAYERPARTYNAME, @pIdCard:=mz.PAYERPARTYCODE, @pMoney:=mz.TOTALAMOUNT)
        from cz_fet_main_mz mz where mz.ORGID = ticket.ORGCODE and mz.EINVOICECODE = ticket.EINVOICECODE
        and mz.EINVOICENUMBER = ticket.EINVOICENUMBER limit 1)
        ELSE
        (select CONCAT(@pName:=zy.PAYERPARTYNAME, @pIdCard:=zy.PAYERPARTYCODE, @pMoney:=zy.TOTALAMOUNT)
        from cz_fet_main_zy zy where zy.ORGID = ticket.ORGCODE and zy.EINVOICECODE = ticket.EINVOICECODE
        and zy.EINVOICENUMBER = ticket.EINVOICENUMBER limit 1)
        END AS temp4,
        @pName as patientName ,
        @pIdCard as idCard ,
        @pMoney as invoiceAmount,
        ticket.ORGCODE
        FROM cz_fet_pjkj ticket
        where 1
        and date_format(ticket.KPDATE,'%Y-%m-%d') >='2010-09-10'
        and date_format(ticket.KPDATE,'%Y-%m-%d') &lt;= '2020-09-30'
        and ticket.MAINTYPE = 1
        and ticket.STATUS = 1
        and ticket.EINVOICECODE = '41060120'
        and ticket.ORGCODE = '416046926'
    </select>

@Mapper
public interface TestMapper {
    List<HashMap<String, Object>> testFun1();
}

  @Bean
    CommandLineRunner runner(TestMapper mapper) {

        return args -> {
            System.out.println(mapper.testFun1());
        };
    }

Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: SELECT
        ticket.EINVOICECODE as ticketCode,
        ticket.EINVOICENUMBER as ticketNumber,
        ticket.SERIANUMBER as bizCode,
        ticket.MAINTYPE as mainType,
        ticket.PATIENTNUMBER visitNumber,
        ticket.STATUS as ticketStatus,
        ticket.KPDATE as kpDate,
        CASE WHEN ticket.REDCODE is Null THEN 0 ELSE 1 END AS isRed,
        ticket.REDCODE as redCode,
        ticket.REDNUMBER as redNumber,
        CASE WHEN ticket.MAINTYPE = 1 then
        (select CONCAT(@pName:=mz.PAYERPARTYNAME, @pIdCard:=mz.PAYERPARTYCODE, @pMoney:=mz.TOTALAMOUNT)
        from cz_fet_main_mz mz where mz.ORGID = ticket.ORGCODE and mz.EINVOICECODE = ticket.EINVOICECODE
        and mz.EINVOICENUMBER = ticket.EINVOICENUMBER limit 1)
        ELSE
        (select CONCAT(@pName:=zy.PAYERPARTYNAME, @pIdCard:=zy.PAYERPARTYCODE, @pMoney:=zy.TOTALAMOUNT)
        from cz_fet_main_zy zy where zy.ORGID = ticket.ORGCODE and zy.EINVOICECODE = ticket.EINVOICECODE
        and zy.EINVOICENUMBER = ticket.EINVOICENUMBER limit 1)
        END AS temp4,
        @pName as patientName ,
        @pIdCard as idCard ,
        @pMoney as invoiceAmount,
        ticket.ORGCODE
        FROM cz_fet_pjkj ticket
        where 1
        and date_format(ticket.KPDATE,'%Y-%m-%d') >='2010-09-10'
        and date_format(ticket.KPDATE,'%Y-%m-%d') <= '2020-09-30'
        and ticket.MAINTYPE = 1
        and ticket.STATUS = 1
        and ticket.EINVOICECODE = '41060120'
        and ticket.ORGCODE = '416046926'
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.

![image](https://user-images.githubusercontent.com/19808319/101346031-ef07aa80-38c2-11eb-944f-d4e9dcd57b83.png)

**Comment by latmns** [comment]
How can I solve this problem ？

**Comment by miemieYaho** [comment]
jsqlparser not support your sql

**Comment by huayanYu** [comment]
sql 太复杂了，会遇到jsqlparser无法解析的问题。 建议太复杂的sql自己写xml，或者提PR来处理极其复杂下jsqlparser无法解析的问题，或者给jsqlparser提ISSUE
