### ISSUE TITLE
oracle date 类型数据，查询返回不待时分秒

### ISSUE THREAD

**Issue by rockjava** [baomidou/mybatis-plus#315]
在使用mybatisplus的情况下，不在xml中显示映射字段类型，这时候在查询oracle date 类型数据时，查询返回不待时分秒，这个问题改怎么解决？

**Comment by qmdx** [comment]
timestamp 类型试试

**Comment by rockjava** [comment]
不想用timestamp类型，现在表里有数据，而且很多字段已经时data类型的了。存储在数据库中的data类型数据已经是有时分秒的了。这种情况，改怎么办？必须在xml中映射字段类型吗？如果这样就失去了mybatisplus的灵活方便性了。

**Comment by rockjava** [comment]
该问题与Oracle驱动有关系，问题已经解决，多谢。
在Oracle11g之前DATE被映射为java.sql.Date,TIMESTAMP被映射为java.sql.Timestamp，从Oracle11开始，其JDBC驱动程序又重新开始回归为将内置类型DATE映射为java.sql.Timestamp
升级驱动，问题解决。

**Comment by yongming9011** [comment]
你好，我也遇到了同样的问题，请问你的Oracle版本跟Oracle驱动版本分别是多少？

**Comment by yuxiaobin** [comment]
11.2.0.3
