### ISSUE TITLE
IService无mapper泛型

### ISSUE THREAD

**Issue by gitzhangliang** [baomidou/mybatis-plus#3152]
public interface IService<T> {
BaseMapper<T> getBaseMapper();
}
改后：
public interface IService<M,T>{
M getBaseMapper();
}
改后的在调用getBaseMapper后可以调用自定义mapper中自定义的方法，这样的改动是好是坏，有何问题？

**Comment by miemieYaho** [comment]
自己去思考

**Comment by gitzhangliang** [comment]
给自己提问题
