### ISSUE TITLE
就不能兼容JPA规范的注解么

### ISSUE THREAD

**Issue by jiangjialiang918** [baomidou/mybatis-plus#3154]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 重现步骤(如果有就写完整)
 
 <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.3.2</version>
                <exclusions>
                    <exclusion>
                        <artifactId>mybatis-plus-annotation</artifactId>
                        <groupId>com.baomidou</groupId>
                    </exclusion>
                </exclusions>
            </dependency>

### 报错信息

Caused by: java.lang.ClassNotFoundException: com.baomidou.mybatisplus.annotation.IdType

**Comment by miemieYaho** [comment]
功能都不一样,兼容个寂寞?

**Comment by jiangjialiang918** [comment]
> 功能都不一样,兼容个寂寞?

tk.mybatis 不都用的jpa的注解？你是搞错我的意思了吧，我说的是javax.persistence下的注解
