### ISSUE TITLE
mybatis-plus 不支持kylin分页

### ISSUE THREAD

**Issue by pzjjjj** [baomidou/mybatis-plus#3155]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
手写mybatis-kylin分页插件 PaginationInterceptor 209行
    DialectModel model = DialectFactory.buildPaginationSql(page, buildSql, dbType, dialectClazz);
IDialect 方言 DbType枚举有11种实现类另外一种other 不支持kylin 
报错 DialectFactory getDialectByDbType方法 126行报错 The Database's IDialect Not Supported!
无法重写mybatis-plus的方言 IDialect不支持kylin

### 重现步骤(如果有就写完整)
如上 新建mybatis 拦截器

### 报错信息
The Database's IDialect Not Supported!

**Comment by miemieYaho** [comment]
用新分页插件,并设置dbtype为postgresql,https://mybatis.plus/guide/interceptor.html

**Comment by pzjjjj** [comment]
感谢
