### ISSUE TITLE
查询里面使用了Mysql MATCH AGAINST全文搜索，日志里面报错

### ISSUE THREAD

**Issue by willzhujian** [baomidou/mybatis-plus#3156]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
        if (userQuery.getClazzId() != null) {
            wrapper.eq(User::getClazzId, userQuery.getClazzId());
        }
        if (StringUtils.isNotEmpty(userQuery.getKeyword())) {
            wrapper.apply("MATCH (name, login_name, email, mobile_phone, company_name) AGAINST ({0})", userQuery.getKeyword());
        }
        Page<User> page = new Page<User>(userQuery.getPageStart(), userQuery.getPageSize(), userQuery.getIsCount());
        page.addOrder(userQuery.getOrders());

### 报错信息
2020-12-09 14:27:49.191 WARN  [http-nio-8069-exec-1]c.b.m.extension.plugins.inner.PaginationInnerInterceptor.autoCountSql():329 - optimize this sql to a count sql has exception, sql:"SELECT  id,name,...  FROM user 
 
 WHERE (is_deleted = ? AND type = ? AND MATCH (name, login_name, email, mobile_phone, company_name) AGAINST (?))", exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "MATCH" "MATCH"
    at line 3, column 41.

Was expecting one of:

    "!"
    "("
    "NOT"

**Comment by miemieYaho** [comment]
jsqlparser 不能解析,去找他

**Comment by willzhujian** [comment]
> jsqlparser 不能解析,去找他

找谁，这个也影响，order by生成不了


2020-12-09 14:39:34.554 WARN  [http-nio-8069-exec-2]c.b.m.extension.plugins.inner.PaginationInnerInterceptor.concatOrderBy():375 - failed to concat orderBy from IPage, exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "MATCH" "MATCH"
    at line 3, column 41.

Was expecting one of:

    "!"
    "("
    "NOT"

**Comment by Hyang-918** [comment]
请问怎么解决的，没办法再使用全文索引了吗

**Comment by Hyang-918** [comment]
请问怎么解决的，没办法再使用全文索引了吗
