### ISSUE TITLE
wrappers的count()方法返回Integer建议修改成Long

### ISSUE THREAD

**Issue by daselang** [baomidou/mybatis-plus#3158]
### 当前使用版本(必填,否则不予处理)
3.4.0 以及其他版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
作者在设计queryWrapper的时候对 count方法的返回值定义为Integer，但是int类型本身的极限过小，最大值仅21亿多，
虽然很少见int放不下的情况，但是此数仍旧过小，总有count查询总数溢出的情况。
另外JPA对count的标准也是Long类型，且hibernate为了适配JPA标准在一次版本（3.2）更新中做过兼容性破坏更新，从 aggregation (count) function的返回值Integer直接修改成Long.也是出于数据溢出情况的考虑。

### 重现步骤(如果有就写完整)

源码有

### 报错信息
无

**Comment by miemieYaho** [comment]
等 mp4

**Comment by huayanYu** [comment]
因对用户破坏性较大，后期大版本升级应该会改为 long
