### ISSUE TITLE
删除操作出现错误

### ISSUE THREAD

**Issue by TourDJ** [baomidou/mybatis-plus#316]
做删除操作时，出现如下操作：
`### Error updating database.  Cause: com.baomidou.mybatisplus.exceptions.MybatisPlusException: org.postgresql.util.PSQLException: ResultSet 中找不到栏位名称 Extra。
### Cause: com.baomidou.mybatisplus.exceptions.MybatisPlusException: org.postgresql.util.PSQLException: ResultSet 中找不到栏位名称 Extra。`
不知 Extra 字段是干嘛用的？

**Comment by qmdx** [comment]
给出你的操作 sql 注意 extra 是否属于你的表字段

**Comment by TourDJ** [comment]
extra 不是我的表字段
