### ISSUE TITLE
自动填充字段功能，希望提供逻辑删除时自动填充自定义字段

### ISSUE THREAD

**Issue by wgbvirtualS** [baomidou/mybatis-plus#3160]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
逻辑删除时，调用deleteById时，只更新了逻辑删除字段，我定义的updateTime和updateBy并没有更新

### 重现步骤(如果有就写完整)
在新增和更新时，createBy，createTime，updateBy，updateTime都有更新，逻辑删除时也应该属于更新功能

### 报错信息
无

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/logic-delete.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
