### ISSUE TITLE
MetaObjectHandler 自动填充 update（params1,params2）,不生效

### ISSUE THREAD

**Issue by zhouyufei8** [baomidou/mybatis-plus#3162]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用自带的方法,
`bizOrderMapper.update(null, updateWrapper)`

自定义填充不生效
`   public void updateFill(MetaObject metaObject) {
        String id = getId();
        setFieldValByName(updateBy, id, metaObject);
        setFieldValByName(updateTime, new Date(), metaObject);
    }`

只有将null改为实体对象才生效
`bizOrderMapper.update(new BizOrder(), updateWrapper)`

使用场景是 由于需要修改的参数比较少，只有一个两个，就没有用 updateById 的方法。

**Comment by miemieYaho** [comment]
填充只能填充到入参的entity里
