### ISSUE TITLE
对社区的一些建议

### ISSUE THREAD

**Issue by SunJiFengPlus** [baomidou/mybatis-plus#3164]
通过平时的 issue 处理似乎能看出一些问题, 几个核心 committer 不像是社区维护者, 更像是 issue closer, 这种现象不是一个健康开源社区该有的现象. 我也知道大家都是搞技术的, 可能也不知道该怎么去运营开源社区.

#2834  在这个 issue 中能看到社区维护者的一些痛点: **issue 太多处理不过来**, 我以我个人的角度去分析了一下, 如果不对的话还请指正, 或者自己做一遍"5 Whys".

Q: 为什么 issue 太多处理不过来?
A: 因为社区维护者少, 就那么几个人, 处理不过来.
Q: 为什么社区维护者少?
A: 社区转化率低, 被"使用者到贡献者再到核心维护者"这个过程劝退.
Q: 为什么转化率低?
A: "使用者到贡献者再到核心维护者" 这个过程的本身就很有挑战, 加上维护者的态度不好, 那就难上加难了.
Q: 为什么维护者态度不好?
A: "这帮傻*, 这个不懂, 那个也不明白, 就天天问, 我都不耐烦了"
核心问题: **包容度**

Mybatis-plus 的用户很多, 这个从这几年的年度开源软件的TOP榜单就能看出来, 但是社区的转化率太低了.

我个人的建议: 
- 把贡献指南建起来, 小到文档加个空格, 大到下个release做什么. 提升社区参与感
- Issue & PR 处理重在态度和质量. 提升社区包容度

**Comment by miemieYaho** [comment]
如果 Issue & PR 质量高那当然好,问题是质量大部分真的不咋地
- 源码不看,源码注释也不看
- 文档不看,samples也不看
- debug都不会的一抓一大把
![OJV%E3)1NPV C0VEHQGO7L1](https://user-images.githubusercontent.com/28334419/101638706-58292280-3a69-11eb-8f9a-acc16798a295.jpg)

**Comment by lzb6666** [comment]
1、个人觉得可以社区维护者确实有些少，可以考虑吸纳更多的社区贡献者，面对各种各样的ISSUE，少数的几个核心commiter，应对一个连续top的热门开源库，确实会精力不足。
2、关于ISSUE可以参考google的Issue Tracker，把重现步骤改为复现demo。既能够帮助社区快速定位问题，也能过滤掉一些低质量无意义的issue。每个使用者的业务逻辑都不相同也可能比较复杂，很多情况没有复现demo仅靠几句复现步骤，很难定位是mbp的问题还是使用者本身业务逻辑的问题；

**Comment by SunJiFengPlus** [comment]
要不先提升一下**包容度**和**参与感**试一段时间? 设置几个维度观察指标, 比如非核心committer解决的 issue 增率、PR增率等.

维护者资源的话是否可以向公司申请一些? 我猜既然公司支持开源了, 那再申请几个人应该没什么问题吧.

**Comment by miemieYaho** [comment]
哪来的公司?苞米豆技术有限公司?

**Comment by lzb6666** [comment]
> 哪来的公司?苞米豆技术有限公司?

我看到楼上说，我还专门百度了一圈是哪个公司

**Comment by SunJiFengPlus** [comment]
> 哪来的公司?苞米豆技术有限公司?

我不太了解 MPG 的历史哈, 我猜它起初只是在公司内部应用, 然后来被开源出来了, 上级应该知道这件事吧. 可以寻求他们的一些帮助. 或者寻求一些有开源文化的公司的朋友帮忙.

**Comment by SunJiFengPlus** [comment]
公司在享受开源的福利, 为开源做一点事也不过分吧.

**Comment by miemieYaho** [comment]
确实都是个人开发者

**Comment by SunJiFengPlus** [comment]
那这条路不通就再找一条呗, 方法总比困难多, 关键就在于社区有多想解决这个问题.

像上面的几条建议可以试一下, 行不通的话也算是得到了反馈, 为什么行不通, 开始下一轮试错.

**Comment by qmdx** [comment]
最近太忙没时间来处理 issue 多谢包容，当前 mp 都是个人开发者维护，后续会想办法规范化

**Comment by ChoviWu** [comment]
挺好的，可以多找点人参与开源

**Comment by cweijan** [comment]
想多了, 还社区, 大多人都是伸手党.

**Comment by plusmancn** [comment]
建议可以先从规范提交记录开始，
比如常见的：
```shell
feat: 新增特性描述等
fix: bug 修复提交
test: 测试用例描述
```

**Comment by wosuxiongmao** [comment]
呃。。。。我这不就40个issues嘛。。有什么多的。。？

**Comment by hcl04** [comment]
![I0_PZ(NT0B@3UQ7K}D0RI}G](https://user-images.githubusercontent.com/39977647/112107634-2c7e1280-8bea-11eb-8bef-b16e150e279c.jpg)

**Comment by SunJiFengPlus** [comment]
工信部的开源社区治理标准: https://gitee.com/TieDan01/Open-Source-Community-Governance

工信部的开源项目评估模型: https://gitee.com/TieDan01/OpenBz

可以参考下

**Comment by SunJiFengPlus** [comment]
工信部开源项目评估模型征求意见: https://gitee.com/TieDan01/OpenBz
工信部开源项目评估模型草案: https://gitee.com/fisheryy/oss_contr_eva_model
这个可以参考下

草案形成没拍全, 尝试在 gitee 中查找也查不到
![图片](https://user-images.githubusercontent.com/39667700/112435851-3c2f5f80-8d80-11eb-9d54-921cb7e93a2d.png)
