### ISSUE TITLE
项目启动报错，是否和版本兼容有关

### ISSUE THREAD

**Issue by lujinyongwh** [baomidou/mybatis-plus#3167]
### 当前使用版本(必填,否则不予处理)
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.8.RELEASE</version>
        <relativePath/> 
    </parent>
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
不确定如何引起，还有以下配置
mybatis-plus:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mapper/*.xml
    - classpath:mapper/**/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath*:com/**/mapper/xml/*.xml

@MapperScan({"com.macro.mall.mapper","com.macro.mall.dao","com.mall.distribution.core.mapper"})
### 重现步骤(如果有就写完整)
项目启动时报的错

### 报错信息
An attempt was made to call a method that does not exist. The attempt was made from the following location:   com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.getLanguageDriver(MybatisMapperAnnotationBuilder.java:369)
The following method did not exist:  com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;
The method's class, com.baomidou.mybatisplus.core.MybatisConfiguration, is available from the following locations:
    jar:file:/C:/anzhuang/repository/com/baomidou/mybatis-plus-core/3.3.1/mybatis-plus-core-3.3.1.jar!/com/baomidou/mybatisplus/core/MybatisConfiguration.class
It was loaded from the following location:
    file:/C:/anzhuang/repository/com/baomidou/mybatis-plus-core/3.3.1/mybatis-plus-core-3.3.1.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of com.baomidou.mybatisplus.core.MybatisConfiguration

**Comment by miemieYaho** [comment]
依赖冲突,自己排查
