### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] - "Showcase"

### ISSUE THREAD

**Issue by MrCull** [baomidou/mybatis-plus#3169]
### 当前使用版本(必填,否则不予处理)
N/A

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
N/A

### 重现步骤(如果有就写完整)

The markup version of the readme that is displayed for the main page in this repo contains the following link:

"Showcase"
Status code [404:NotFound] - Link: https://github.com/baomidou/awosome-mybaits-plus

(The link in the readme’s raw markdown may appear in a different relative format to the link above)

I cannot see any file or folder in this repo with a similar name to "Showcase" so cannot suggest what the fix is.

### 报错信息

![image](https://user-images.githubusercontent.com/16634034/101926662-63945f00-3bcb-11eb-82db-3d85b033d9b9.png)

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fbaomidou%2fmybatis-plus
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=baomidou

**Comment by yangyang0507** [comment]
fixed

**Comment by yangyang0507** [comment]
your project is very cool~ already use your project to check our readme file，awesome
