### ISSUE TITLE
官网英语语言下目录重复

### ISSUE THREAD

**Issue by pengdezhi** [baomidou/mybatis-plus#3179]
找不到直接联系方式只能在这里进行提交
![image](https://user-images.githubusercontent.com/26673095/102341449-d427eb00-3fd2-11eb-973e-4ed88773fb2f.png)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-doc
欢迎 pr

**Comment by huayanYu** [comment]
英文文档暂无人维护。。~
