### ISSUE TITLE
两个小bug

### ISSUE THREAD

**Issue by zhfish** [baomidou/mybatis-plus#318]
## 1. 生成器  
在`setEntityLombokModel(true)`并且没设置`setSuperEntityClass`的时候
lambok会报警告
```
Warning:(26, 1) java: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type
```
应该在这种情况下，增加注解
`@EqualsAndHashCode(callSuper=false)`

## 2. Wrapper的使用  
`Condition.wrapper()`是带泛型的，为啥再`.eq("","")`泛型就没了呢?
变成了`wrapper<Object>`
泛型没了就只能忍着警告

**Comment by qmdx** [comment]
1、消灭了请关注 `mp 2.3 +` 发布

2、这个只能忍着暂时
