### ISSUE TITLE
Mock测试单元用例,mock无法模拟mybatis plus service层的数据

### ISSUE THREAD

**Issue by JavaGreenHands** [baomidou/mybatis-plus#3181]
### 当前使用版本(必填,否则不予处理)

Springboot 2.13.RELEASE
mybatisplus  3.3.0
mockito-core 2.23.4
![select-agent-session](https://user-images.githubusercontent.com/38916042/102347712-be6af380-3fdb-11eb-89ec-29d33cc898ca.png)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

编写应用测试用例时,使用Mock 模拟了service层的对象,调用.list(),参数使用了new QueryWrapper<User>()
                .lambda()
                .eq(User::getId, 1)
在使用Mock模拟其返回值时,发现mock的返回值并不正确,测试过Mock是没有问题的,参数对象是String 类型时,Mock可以模拟调用成功,参数类型是对象是,Mock模拟不成功,第一次使用Mock,不知道算是mybatis plus的问题还是mock的问题,如果跟mybatis plus 无关,请忽略回答,本人小白一枚,敬请谅解.

### 重现步骤(如果有就写完整)

其他对象示例
![image](https://user-images.githubusercontent.com/38916042/102346513-ec4f3880-3fd9-11eb-8051-101c8856d434.png)
打印：
![image](https://user-images.githubusercontent.com/38916042/102347007-beb6bf00-3fda-11eb-8c99-a460521874a1.png)

mybatisplus 对象示例
![image](https://user-images.githubusercontent.com/38916042/102346891-929b3e00-3fda-11eb-8df1-dab471c8ac0c.png)
打印:
![image](https://user-images.githubusercontent.com/38916042/102346913-9af37900-3fda-11eb-9747-998a6ff2aa74.png)

### 报错信息
 暂无

**Comment by miemieYaho** [comment]
any(PPOta.class) ?

**Comment by JavaGreenHands** [comment]
@miemieYaho 收到,今天试了一下,可以了,使用any(xx.class)是可以的,谢谢
