### ISSUE TITLE
动态序列@KeySequence是否支持（添加/移除）？

### ISSUE THREAD

**Issue by oopsRookie** [baomidou/mybatis-plus#3184]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
算作疑问或建议吧。我想在运行时添加或者移除@KeySequence，不知是否可行？

### 重现步骤(如果有就写完整)
无

### 报错信息
无

补充：
此前以完成了runtime时动态表名、修改注解中的值（jdk代理和反射实现的）。
现在我想一个动态表名对应一个动态序列，以及有可能插入不去采用序列。
于是尝试了runtime时把@KeySequence中的value置成""，但测试后mybatis plus还是会去找序列的NEXTVAL，
即 `SELECT  .NEXTVAL FROM DUAL`。自然抛出了找不到序列的异常，索引想知道能不能动态启用/关闭序列。

**Comment by huayanYu** [comment]
感觉不可行，除非改很底层的源码，然后暴露给外面接口。
改动太大， 你也可以尝试解决然后提交PR。
不过你这需求太小众，建议你还是尝试其他方法解决
