### ISSUE TITLE
使用 Wrapper 自定义SQLThere is no getter for property named 'ew' in 'class com.baomidou.mybatisplus.core.conditions.query.QueryWrapper

### ISSUE THREAD

**Issue by max-end** [baomidou/mybatis-plus#3189]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
加分页可以查询
按照官方文档使用 Wrapper 自定义SQL

### 重现步骤(如果有就写完整)
mapper

@Select("select sum(user_value) from order_detail ${ew.customSqlSegment}")
Double sumUserValue(Wrapper<OrderDetail> ew);

### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'ew' in 'class com.baomidou.mybatisplus.core.conditions.query.QueryWrapper'

**Comment by miemieYaho** [comment]
检查你mybatis版本冲突

**Comment by lychs1998** [comment]
试试：`Double sumUserValue(@Param("ew") Wrapper ew);`
