### ISSUE TITLE
PaginationInterceptor已经被标记为deprecated，分页的替代方案是什么？

### ISSUE THREAD

**Issue by iengchen** [baomidou/mybatis-plus#3190]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
PaginationInterceptor已经被标记为deprecated，但是官网教程还是用com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor类，那么分页的替代方案是什么？

**Comment by codeStarry** [comment]
https://baomidou.com/guide/interceptor.html#mybatisplusinterceptor
