### ISSUE TITLE
能出一个mybaits-plus+spring boot+shardingsphere-jdbc5+seata 的例子吗

### ISSUE THREAD

**Issue by romantictravel01** [baomidou/mybatis-plus#3192]
### 当前使用版本(必填,否则不予处理)

最新

能出一个mybaits-plus+spring boot+shardingsphere-jdbc5+seata 的例子吗

**Comment by miemieYaho** [comment]
shardingsphere 和 seata 都是代理DataSource的,和mp没关系,自行研究
