### ISSUE TITLE
MybatisPlusInterceptor和DynamicTableNameInnerInterceptor查询结果与预期不符

### ISSUE THREAD

**Issue by billow36** [baomidou/mybatis-plus#3194]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

MybatisPlusInterceptor和DynamicTableNameInnerInterceptor结合使用时，分页查询的条目查询未切换动态表名

### 重现步骤(如果有就写完整)
如动态表名为 fitem_{xxx},通过p6spy打印条目查询脚本为fitem_00(实体默认),select  count(*) from fitem_00
期望为select  count(*) from fitem_xxx

### 报错信息
无报错，但是结果不正确

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html#mybatisplusinterceptor
