### ISSUE TITLE
LambdaQueryWrapper为什么不加一个limit方法?

### ISSUE THREAD

**Issue by onforyou** [baomidou/mybatis-plus#3198]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

想要效果：select * from test where status = 1 and name like '%name%' order by id asc limit 100;

代码：
LambdaQueryWrapper<Test> lambdaQueryWrapper = new LambdaQueryWrapper();
lambdaQueryWrapper.like(Test::getStatus, searchParam.getStatus());
lambdaQueryWrapper.like(Test::getName, searchParam.getName());
lambdaQueryWrapper.orderByAsc(Test::getId);
lambdaQueryWrapper.last(" limit " + pageSize);

有代码洁癖，lambdaQueryWrapper.last(" limit " + pageSize)，希望可以写成 lambdaQueryWrapper.limit(pageSize);

**Comment by miemieYaho** [comment]
不支持方言
