### ISSUE TITLE
升级到2.2.0版本后分页不能用了

### ISSUE THREAD

**Issue by lazyducker** [baomidou/mybatis-plus#320]
升级到2.2.0后，原来的分页不可用，
经调试发现 分页的sql语句后面出现
select ....   from tablename **limit ? LIMIT 0,2147483647**

**Comment by sc0574** [comment]
同样

**Comment by hongliangpan** [comment]
2.3 版本正常

**Comment by Kimmyzhao** [comment]
2.3版本也不正常吧，total一直为0

**Comment by qmdx** [comment]
分页插件配置基本上就没有问题，注意观察下 count sql 是否打印， 更多查看文档 mp.baomidou.com
