### ISSUE TITLE
多数据源配置schema，启动时初始化表结构，无效

### ISSUE THREAD

**Issue by wu-xin** [baomidou/mybatis-plus#3203]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动初始化脚本，H2数据库，无效

### 重现步骤(如果有就写完整)
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: db2 
      datasource:
        db2:
          url: 
          driver-class-name: com.ibm.db2.jcc.DB2Driver
          username: 
          password: 
        h2:
          url: jdbc:h2:file:xxx
          driver-class-name: org.h2.Driver
          schema: db/schema.sql

### 报错信息
无，没有动静, sql没有问题，没有执行，路径也没问题

**Comment by miemieYaho** [comment]
去找spring
