### ISSUE TITLE
库表中本为NULL的字段，MP查询竟然会有值

### ISSUE THREAD

**Issue by wssy001** [baomidou/mybatis-plus#3204]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
正常的select操作

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/22979223/103070130-d229e180-45fb-11eb-86db-028fb7b920ba.png)
如图所示 我再执行插入操作时 故意将一个字段设置为null，然后我确保并没有其他字段，Navicat查询库表，该字段也为null，但是

### 报错信息
库表中本为null的字段，通过mybatis-plus自带的mapper查询后 竟然有了值，且该值为其前一个字段的值

**Comment by miemieYaho** [comment]
自己去排查
