### ISSUE TITLE
来提需求

### ISSUE THREAD

**Issue by q8888tttt** [baomidou/mybatis-plus#3206]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
假如A是B,C的基类，当对B,C构建lambdaWrappers时 
那么A中的字段作为条件需要在Wrappers.<B>lambdaQuery(),和Wrappers.<C>lambdaQuery()中重复编写
造成不能重复利用的问题

**Comment by ppx-build-code** [comment]
在最后一步设置entity
