### ISSUE TITLE
逻辑删除功能调整建议

### ISSUE THREAD

**Issue by nirry** [baomidou/mybatis-plus#321]
建议参考thinkphp5中的软删除功能，仅增加delete_time字段，软删除时把该字段更新为当前时间，查询时where条件后加  delete_time is null

参考文档
https://www.kancloud.cn/manual/thinkphp5/189658

另：thinkphp5中有三个字段是系统控制的,分别为create_time、update_time和delete_time，只要表中有该三个字段，对表进行增删改时就会对这些字段进行相应操作

个人建议,仅供参考

**Comment by qmdx** [comment]
http://mp.baomidou.com/#/logic-delete 看看是不是你要的
