### ISSUE TITLE
Mybatis Plus Cannot Read Database type or The Database's Not Supported!

### ISSUE THREAD

**Issue by lieyanhaipo** [baomidou/mybatis-plus#3212]
### 当前使用版本(必填,否则不予处理)

3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库驱动通过网络隔离装置非标准驱动

### 报错信息

The jdbcUrl is jdbc:nds://xxxx:xxxx,xxxx:xxxx/xxxx?xxxx, Mybatis Plus Cannot Read Database type or The Database's Not Supported!

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html
