### ISSUE TITLE
好像typeHandlersPackage不支持通配符

### ISSUE THREAD

**Issue by nowui** [baomidou/mybatis-plus#322]
我用的是spring boot, 在application.yml里面配置了typeHandlersPackage: com.xx.cloud.oauth.app.entity.typehandler就可以读取数据, 如果配置了typeHandlersPackage: com.xx.cloud.oauth.**.entity.typehandler就只能写入数据，读取不了数据。

**Comment by mocking3** [comment]
咋解决的
