### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by zhaoyang0415** [baomidou/mybatis-plus#3222]
### 进行分页查询时启用二级缓存，PaginationInnerInterceptor中134行

 Object result = executor.query(countMs, parameter, rowBounds, resultHandler, cacheKey, countSql).get(0);

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/commit/40f8791d770766483c70563f7882b6ce62f8f7d6
