### ISSUE TITLE
3.3.1 版本分页插件

### ISSUE THREAD

**Issue by chen1220502052** [baomidou/mybatis-plus#3226]
### 当前使用版本(必填,否则不予处理)
3.3.1 版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
           PaginationInterceptor.queryTotal 方法中下面两句话，导致ParameterHandler的拦截器在分页情况失效，应该使用ParameterHandler代理 来处理参数设置：
            DefaultParameterHandler parameterHandler = new MybatisDefaultParameterHandler(mappedStatement, boundSql.getParameterObject(), boundSql);
            parameterHandler.setParameters(statement);
          

### 重现步骤(如果有就写完整)
拦截器定义：
@Slf4j
@Component
@Intercepts({
        @Signature(type = ParameterHandler.class, method = "setParameters", args = {PreparedStatement.class})
})
public class ParameterHandlerInterceptor implements Interceptor {'
}

分页查询方法
List<ObjectListVo> getObejctList(IPage<ObjectListVo> page, @Param("query") Query query)

### 报错信息
PaginationInterceptor.queryTotal 方法中参数设置时候，没用ParameterHandler代理类，导致ParameterHandler的拦截器在分页情况失效

**Comment by chen1220502052** [comment]
试了一下 3.4.1 一样的问题

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html

**Comment by chen1220502052** [comment]
@Bean
    public PaginationInnerInterceptor paginationInterceptor() {
        PaginationInnerInterceptor paginationInterceptor = new PaginationInnerInterceptor();
        //设置默认最大分页数量
        paginationInterceptor.setMaxLimit(2000L);
        return paginationInterceptor;
    }
新的分页插件是可以的，谢谢啦
