### ISSUE TITLE
3.3.1和3.4.1分页count查询问题

### ISSUE THREAD

**Issue by wxb2468235** [baomidou/mybatis-plus#3227]
### 当前使用版本(必填,否则不予处理)
3.3.1  3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
select  t1.b,(select count(t2.d) * from t2 where t2.c=t1.c) as cc
from  t where t1.a='111' 
having cc = 0
分页count优化结果
select  count(1)
from  t where t1.a='111' 
having cc = 0  这是一条错误的sql，select 字段在having完全抛弃了

**Comment by miemieYaho** [comment]
自己写count吧
