### ISSUE TITLE
[请教]可不可以一次性执行多条不同的SQL语句

### ISSUE THREAD

**Issue by CodeLunatic** [baomidou/mybatis-plus#3229]
### 当前使用版本(必填,否则不予处理)

v3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

请教类问题，因为逻辑极为复杂，并且要保证执行效率，所以要减少与数据库的网络请求次数，需要一次性执行多条不同操作的SQL语句。如果不使用xml的情况下，有没有办法实现该功能。

### 重现步骤(如果有就写完整)

无

### 报错信息

无

**Comment by ppx-build-code** [comment]
多线程、java8并行流

**Comment by miemieYaho** [comment]
不能
