### ISSUE TITLE
如果使逻辑删除触发自定义公共字段自动填充

### ISSUE THREAD

**Issue by lzp4ever** [baomidou/mybatis-plus#323]
- 在`MetaObjectHandler`内定义了**插入时间戳**和**更新时间戳**的自动填充
- 配置了逻辑删除
- 逻辑删除不会触发`MetaObjectHandler`内的`updateFill`

**Comment by qmdx** [comment]
http://mp.baomidou.com/#/auto-fill 挨个看下注意注解
