### ISSUE TITLE
plus是否已经保存了当前数据库表格与实体映射信息

### ISSUE THREAD

**Issue by tuxin95** [baomidou/mybatis-plus#3231]
### 当前使用版本(必填,否则不予处理)
3.0.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我想在项目启动得时候获取一部分表的信息 比如字段 实体属性 备注 等信息进行保存,请问作者plus是否已经有这部分信息保存了,或者提供了相关api

**Comment by qmdx** [comment]
表相关信息存放在类 com.baomidou.mybatisplus.core.metadata.TableInfoHelper 中自己处理

**Comment by tuxin95** [comment]
> 表相关信息存放在类 com.baomidou.mybatisplus.core.metadata.TableInfoHelper 中自己处理

谢谢回答.好像这部分信息中没有注释

**Comment by qmdx** [comment]
> > 表相关信息存放在类 com.baomidou.mybatisplus.core.metadata.TableInfoHelper 中自己处理
> 
> 谢谢回答.好像这部分信息中没有注释

注释你可以考虑自定义注解获取，如果用了swagger 可以取 swagger 注解内容
