### ISSUE TITLE
QueryWrapper 是否可以支持嵌套，或者获取完整的sql语句

### ISSUE THREAD

**Issue by chaoweiyi** [baomidou/mybatis-plus#3233]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用场景，我需要构造一条sql语句，如下
select a.* from a where a.id in (select id from b where b.name like '%测试%')

### 重现步骤(如果有就写完整)

QueryWrapper<UserEntity> queryWrapper = new QueryWrapper<>();
queryWrapper.apply("a.id in (select id from b where b.name like {0})", String.format("%%%s%%", name));

### 报错信息

存在sql注入风险

### 请求帮助
（1）QueryWrapper 是否支持嵌套，例如
QueryWrapper<UserEntity> queryWrapper = new QueryWrapper<>();
queryWrapper.in(UserEntity.Id, new QueryWrapper<DeviceEntity>().like(DeviceEntity.Name, name));

（1）QueryWrapper  是否可以公布一个方法，获取将要执行的完整sql语句，即不使用占位符的sql，例如
String sql = new QueryWrapper<DeviceEntity>().like(DeviceEntity.Name, name).toSql();
QueryWrapper<UserEntity> queryWrapper = new QueryWrapper<>();
queryWrapper.apply(String.format("a.id in (%s)", sql));

**Comment by miemieYaho** [comment]
不支持
