### ISSUE TITLE
updateById方法无法自动填充，但是自动填充方法已经被执行（需要填充的字段在数据库中有数据）

### ISSUE THREAD

**Issue by 316374157** [baomidou/mybatis-plus#3234]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
更新时，自动填充的时间无法填充进去（更新时间在插入时也填进去了）

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/46001074/104003911-0d243b80-51de-11eb-8e67-6b9946822f70.png)
![image](https://user-images.githubusercontent.com/46001074/104003993-2a590a00-51de-11eb-8a6b-87d15cd29593.png)
![image](https://user-images.githubusercontent.com/46001074/104004127-55dbf480-51de-11eb-92b8-131a57b66fe4.png)
![image](https://user-images.githubusercontent.com/46001074/104004153-612f2000-51de-11eb-8e38-225eb3f9f070.png)
![image](https://user-images.githubusercontent.com/46001074/104004602-e1558580-51de-11eb-92e0-4d71bd0ee06c.png)
图片无法显示
就是在插入的时候顺便自动填充了更新时间，然后通过updateById方法更新的时候无法填充更新时间字段，但是更新时自动填充的方法被执行了，看了源码发现是原来数据库不为空的字段无法自动填充，这个能解决吗

### 报错信息
无

**Comment by miemieYaho** [comment]
你重写对应的method不就解决了
