### ISSUE TITLE
不支持Postgrepsql ON CONFLICT ON CONSTRAINT finance_house_charge_key DO NOTHING 语法

### ISSUE THREAD

**Issue by junwangit** [baomidou/mybatis-plus#3235]
### 当前使用版本(必填,否则不予处理)
V3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

插入数据使用ON CONFLICT ON CONSTRAINT finance_house_charge_key DO NOTHING语法执行报错。

同样语法在客户端直接执行就正常

### 重现步骤(如果有就写完整)

 <insert id="batchInsertHouseChargeStandard">
        INSERT INTO finance_house_charge (
            id,
            community_id,
            house_id,
            charge_standard_id,
            begin_date,
            end_date,
            no_end_time,
            price,
            remark,
            revision,
            created_by,
            created_name,
            created_time,
            updated_by,
            updated_name,
            updated_time,
            del_flag
        )
        VALUES
        <foreach collection="list" item="item" index="index" separator=",">
            (
            #{item.id},
            #{item.communityId},
            #{item.houseId},
            #{item.chargeStandardId},
            #{item.beginDate},
            #{item.endDate},
            #{item.noEndTime},
            #{item.price},
            #{item.remark},
            #{item.revision},
            #{item.createdBy},
            #{item.createdName},
            #{item.createdTime},
            #{item.updatedBy},
            #{item.updatedName},
            #{item.updatedTime},
            #{item.delFlag}
            )
        </foreach>
        ON CONFLICT ON CONSTRAINT finance_house_charge_key DO NOTHING
    </insert>

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: INSERT INTO finance_house_charge (
            id,
            community_id,
            house_id,
            charge_standard_id,
            begin_date,
            end_date,
            no_end_time,
            price,
            remark,
            revision,
            created_by,
            created_name,
            created_time,
            updated_by,
            updated_name,
            updated_time,
            del_flag
        )
        VALUES
          
            (
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            ?
            )
         
        ON CONFLICT ON CONSTRAINT finance_house_charge_key DO NOTHING

**Comment by miemieYaho** [comment]
jslparser无法解析
