### ISSUE TITLE
版本小于3.4想阻止全表更新与删除

### ISSUE THREAD

**Issue by yangzcp** [baomidou/mybatis-plus#3236]
### 当前使用版本(必填,否则不予处理)
3.0.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目是老项目在运行,不敢升级近期出现了全表更新事故想寻求大佬给个解决方案不升级版本前提下,跪拜

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/interceptor-block-attack.html

**Comment by yangzcp** [comment]
3.0.6这个版本 没有BlockAttackInnerInterceptor,怎样能做到阻止全表更新或删除

**Comment by qmdx** [comment]
> 3.0.6这个版本 没有BlockAttackInnerInterceptor,怎样能做到阻止全表更新或删除

复制下新版东西过去用，或者升级
