### ISSUE TITLE
JacksonTypeHandler不起作用

### ISSUE THREAD

**Issue by benxiaohai529** [baomidou/mybatis-plus#3238]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

调用系统方法时不起作用,例如getById，获取到的对象里面加@TableField(value="person",typeHandler = JacksonTypeHandler.class)的属性为nulll;

**Comment by miemieYaho** [comment]
看源码注解注释
