### ISSUE TITLE
QueryWrapper 条件分页查询异常

### ISSUE THREAD

**Issue by yqwoe** [baomidou/mybatis-plus#3242]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用QueryWrapper 

### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) TOTAL' at line 3
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) TOTAL' at line 3]

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式
