### ISSUE TITLE
LambdQueryWrapper是否可以支持忽略大小写的查询

### ISSUE THREAD

**Issue by zongxingy** [baomidou/mybatis-plus#3243]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
文档找未找到忽略大小写的方法支持

### 重现步骤(如果有就写完整)
无

### 报错信息
无

--- 类似sql中的
and upper(字段xxx) like upper('%xxx%')
![image](https://user-images.githubusercontent.com/12457426/104162039-d5f89900-542e-11eb-93aa-3b1b271ff420.png)
'

**Comment by huayanYu** [comment]
不会做类似支持，建议写sql。
