### ISSUE TITLE
baseMapper.insert 后是如何实现给entity.setId的？

### ISSUE THREAD

**Issue by andrewperry01** [baomidou/mybatis-plus#3247]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1.Entity 已经设置 @TableId(value = "record_id", type = IdType.AUTO)
2.调用baseMapper.insert(Entity);
Long id = entity.getId(); 结果id 为null;
3.特殊声明：生产环境用的阿里mysql，自动走中间件实现主从分离，但是主从同步有延迟。

### 报错信息
日志获取不到id

**Comment by huayanYu** [comment]
没有环境来复现，不过按理来说，带插入都应该加了事务，强制走主库。

如果可以，可以写一个基础demo，提供一个可测试环境。
@andrewperry01

**Comment by miemieYaho** [comment]
原理: https://blog.csdn.net/lkforce/article/details/77744050
