### ISSUE TITLE
使用mybatis-plus根据id查询数据，如果该行数据的时间（localDateTime）有值那么可以查出，如果该行数据的时间为空，报错   Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLException: Error

### ISSUE THREAD

**Issue by js110** [baomidou/mybatis-plus#3250]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用mybatis-plus根据id查询数据，如果该行数据的时间（localDateTime）有值那么可以查出，如果该行数据的时间为空，报错 

### 报错信息
Error attempting to get column 'create_time' from result set.  Cause: java.sql.SQLException: Error\n; uncategorized SQLException; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error"},"data":null}

**Comment by js110** [comment]
durid已经使用1.2.4，spring boot2.2.2，mp3.4.0

**Comment by js110** [comment]
> `# mybatis-plus配置
mybatis-plus:
  #  mapper-locations: classpath:/service/bo/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-underline: true          # 驼峰下划线转换`
这是mp的配置

**Comment by js110** [comment]
# mybatis-plus配置
mybatis-plus:
  #  mapper-locations: classpath:/service/bo/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-underline: true          # 驼峰下划线转换

**Comment by js110** [comment]
3.4.1也同样报错，mp配置如下
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-underline: true          # 驼峰下划线转换

**Comment by miemieYaho** [comment]
mp不参与数据封装,自己排查

**Comment by KaminanGTO** [comment]
检查druid版本，用新一点的，比如1.1.20

**Comment by zhangjiayu139** [comment]
检查一下mysql驱动是否是5.1.47以下版本，升级到5.1.47问题解决

**Comment by zhangjiayu139** [comment]
检查一下mysql驱动是否是5.1.47以下版本，升级到5.1.47问题解决
