### ISSUE TITLE
建议查询QueryWrapper添加order by field排序的方法

### ISSUE THREAD

**Issue by featnet** [baomidou/mybatis-plus#3252]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
需求：QueryWrapper、QueryChainWrapper、LambdaQueryChainWrapper等，建议在查询时添加可以根据字段值排序的方法

**Comment by miemieYaho** [comment]
不支持
