### ISSUE TITLE
Mapper传值到xml中，若实体类有属性是Vo结尾，xml中无法找到属性

### ISSUE THREAD

**Issue by lujibao** [baomidou/mybatis-plus#3253]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
例如：实体类中entryinfoVo属性，使用mysql 插入操作的时候
报错There is no getter for property named 'entryinfoVo' 

### 重现步骤(如果有就写完整)
实体类的值：[{"id":"1","name":"xiaoming","xxVo":null,"yyVo":null},{"id":"2","name":"liming","xxVo":null,"yyVo":null}]
mysql批量插入

1、同时插入xxVo,yyVo
insert into (id,name,xx_vo,yy_vo)
 VALUES
        <foreach collection="list" item="item" separator=",">
           (#{item.id},#{item.name},#{item.xxVo},#{item.yyVo})
         </foreach>
2、去掉xxVo插入
insert into (id,name,xx_vo,yy_vo)
 VALUES
        <foreach collection="list" item="item" separator=",">
           (#{item.id},#{item.name}#{item.yyVo})
         </foreach>
3、同时去掉xxVo,yyVo插入，插入成功
### 报错信息
1、同时插入xxVo,yyVo：There is no getter for property named 'xxVo'
2、去掉xxVo插入：There is no getter for property named 'yyVo'
3、同时去掉xxVo,yyVo,插入成功。

**Comment by miemieYaho** [comment]
去找mybatis
