### ISSUE TITLE
懒加载MappedStatement

### ISSUE THREAD

**Issue by huayanYu** [baomidou/mybatis-plus#3256]
随着表的增多，BaseMapper自动注入的也随着增多，有没有方法减少MappedStatement的数量。

方案一：拆分BaseMapper。

方案二： 动态代理，具体用到的时候再注入。

方案三： 给mybatis官方提ISSUE或贡献。

**Comment by plusmancn** [comment]
可否有更多细节描述

**Comment by hcl04** [comment]
经实际测试，懒加载没有意义，需要考虑拆分 BaseMapper
