### ISSUE TITLE
QueryWrapper方法里的in查询时与数据库数据不一致

### ISSUE THREAD

**Issue by jition1987** [baomidou/mybatis-plus#3259]
### 版本信息（旧版本与新版本问题一样）
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.2</version>
</dependency>

### 使用in查询数据不正确（数据库执行sql与mybatis-plus查询数据不一致）
参数类型为String：List<String> ids=Arrays.asList("test,"test001","test002") ;
在使用mybatis plus提供的QueryWrapper方法里的in查询时 

### 重现步骤(如果有就写完整)
LamdaQueryWarpper<MerchantInfo> in=new QueryWrapper<MerchantInfo>().lamda().in(MerchantInfo::getMerchantId,merchantids);
List<MerchantInfo> merchantInfos=merchantInfoMapper.select(in)

### 报错信息
select merchant_id,merchant_name merchant_info where IN("test","test001","test002")
数据库执行有3条件数据
而使用QueryWrapper方法里的in只有一条数据

**Comment by miemieYaho** [comment]
mp不负责执行sql
