### ISSUE TITLE
mybatis-plus 必须依赖spring吗？

### ISSUE THREAD

**Issue by 912349441** [baomidou/mybatis-plus#3260]
项目中不需要使用spring。只想用mybatis plus做数据操作。但是官网上的例子都是集成spring的，必须依赖吗？

**Comment by wajncn** [comment]
你用jdbc吧. 用啥mybatis

**Comment by BingChunMoLi** [comment]
myabtis 只是数据库的查询，主流是SSM框架，既然myabtis-plus是配合mybatis的，当然就会大篇幅的与spring系列整合，如果不需要spring，就需要手动进行配置。会很繁琐

**Comment by BingChunMoLi** [comment]
Mybatis-plus默认是不支持的，需要排除mybatis-spring的依赖，所以不如直接使用mybatis吧

**Comment by 912349441** [comment]
十分感谢！


 
---原始邮件---
发件人: "冰彦糖"<notifications@github.com&gt;
发送时间: 2021年1月17日 23:23:57
收件人: "baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送: "Team丶ty"<912349441@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [baomidou/mybatis-plus] mybatis-plus 必须依赖spring吗？ (#3260)




 
Mybatis-plus默认是不支持的，需要排除mybatis-spring的依赖，所以不如直接使用mybatis吧

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/MybatisTest.java
