### ISSUE TITLE
无xml的情况下，执行BaseMapper的方法如何设置flushCache

### ISSUE THREAD

**Issue by 1146604040** [baomidou/mybatis-plus#3261]
### 当前使用版本(必填,否则不予处理)
当前使用版本：3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用xml的情况下设置flushCache=true，可以实现在同个查询在同个事务中传入的参数不变每次调用都会执行sql
但是mp在无xml的情况下使用BaseMapper.selectById(id)如何做到在同个事务中传入的参数不变，让其每次调用都执行sql呢？

**Comment by huayanYu** [comment]
没有办法，个性化的需求建议还是用原生xml
