### ISSUE TITLE
新版本是否更改了数据库字段和实体类属性映射之间的规则?

### ISSUE THREAD

**Issue by LiJunXiao** [baomidou/mybatis-plus#3265]
### 当前使用版本(必填,否则不予处理)
3.4.0
请问为什么数据库字段有下划线的情况下,实体类属性和数据库字段一致的时候也可以映射上，小驼峰命名法也可以映射上，这是新版本更改了映射规则么？

**Comment by miemieYaho** [comment]
https://mybatis.plus/config/#mapunderscoretocamelcase
