### ISSUE TITLE
官网代码生成器链接404

### ISSUE THREAD

**Issue by wlsDDD** [baomidou/mybatis-plus#3266]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.1
![image](https://user-images.githubusercontent.com/51633561/104867941-fb305e80-597c-11eb-8c4e-db37fb2cdd1f.png)

**Comment by huayanYu** [comment]
感谢已修复
