### ISSUE TITLE
集成clickhouse数据库做批量插入时报错

### ISSUE THREAD

**Issue by zddcw** [baomidou/mybatis-plus#3270]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
集成clickhouse数据库做批量插入时报错

### 重现步骤(如果有就写完整)
InterverUploadService extends ServiceImpl<InterverUploadMapper , InterverUploadDistributed>{
this.saveBatch(list , list.size());

}

### 报错信息
 DB::Exception: Cannot parse input: expected '\t' before: '.0\t0.0\t0.0\t0.0\

**Comment by qmdx** [comment]
暂无数据库测试，欢迎解决 PR
