### ISSUE TITLE
sqlserver 构造器为什么必须要加oder by 不想排序也不行吗

### ISSUE THREAD

**Issue by lutu2** [baomidou/mybatis-plus#3276]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
构造器不想加排序 

### 重现步骤(如果有就写完整)

“OFFSET”附近有语法错误。

**Comment by huayanYu** [comment]
??? 看不懂，描述需要更细致， 什么版本，什么sql。 怎么使用的，

**Comment by lutu2** [comment]
按文档写的，没升级前不加order by 没问题，升级到3.4.2时，就必须加order by  不加就报错 “OFFSET”附近有语法错误。
，
  //lqw.orderByDesc("xsr.create_time");
        IPage<XgSampleRecord> page = new Page<>(pageNum, pageSize);
        List<Map<String, Object>> list = iXgSampleRecordService.selectXgSampleRecordList(page,lqw);
xml和server等都是按文档写的
