### ISSUE TITLE
字段使用FastJSON的TypeHandler的时候, baseMapper的insert, update没问题, 但是selectById结果为null

### ISSUE THREAD

**Issue by zhyusgethup** [baomidou/mybatis-plus#3278]
版本3.3.2

最新版本3.42一样复现

字段使用FastJSON的TypeHandler的时候, baseMapper的insert, update没问题, 但是selectById结果为null, 目前自己用的解决办法是在xml里重写方法selectById

**Comment by miemieYaho** [comment]
看注解源码注释
