### ISSUE TITLE
3.4.2逻辑删除字段配置无效

### ISSUE THREAD

**Issue by modefang** [baomidou/mybatis-plus#3282]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
只添加以下配置无效
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted

还需要添加`@TableLogic`注解，才能生效。

但是文档里面说明不需要添加
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)

**Comment by miemieYaho** [comment]
那是entity的属性名不是数据库的字段名

**Comment by kiwi-field** [comment]
logic-delete-field: deleted我配置了这个，还是需要添加@TableLogic注解

**Comment by kiwi-field** [comment]
我的字段名和数据库列名都是deleted

**Comment by kiwi-field** [comment]
@miemieYaho
