### ISSUE TITLE
是否支持关于全表查询及全表删除的拦截

### ISSUE THREAD

**Issue by yujuanIt** [baomidou/mybatis-plus#3285]
### 当前使用版本(必填,否则不予处理)

3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis 条件未传，导致查询全表数据

### 重现步骤(如果有就写完整)
无

### 报错信息

无

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor-block-attack.html
