### ISSUE TITLE
多个service进行pageMaps查询返回的是同一对象

### ISSUE THREAD

**Issue by MrYangXxx** [baomidou/mybatis-plus#3287]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Page<Map<String, Object>> orderPage = orderService.pageMaps(page);
Page<Map<String, Object>> productPage = productService.pageMaps(page);
 

### 重现步骤(如果有就写完整)
经测试随便两个service调用pageMaps返回的结果集都会被第二个覆盖
即使先定义：
Page<Map<String, Object>> orderPage = new Page();
Page<Map<String, Object>> productPage = new Page();
orderPage = orderService.pageMaps(page);
productPage = productService.pageMaps(page);
仍然会是同一个page对象

### 报错信息
无，按正常逻辑应该是两个互不干扰的结果集，还是我少做了什么？

**Comment by miemieYaho** [comment]
入参的page就是返回的page
