### ISSUE TITLE
updateById的bug

### ISSUE THREAD

**Issue by HouserWang** [baomidou/mybatis-plus#329]
现在updateById的实现逻辑应该是近似于xml里的<字段!=null and 字段 != ‘’>,  这样的实现导致了，不能更新对应字段为‘’空字符串，假如用updateAllConlumnById的话，每个数据库有默认值的都需要设置值，不然对应sql更新那个为null报错，所以希望把updateById改为<字段!=null>，这样就可以更新对应字段为空字符串了！

**Comment by qmdx** [comment]
可以指定字段的验证策略你可以看下文档 mp.baomidou.com 另外 2.3 支持 updateForSet 指定更新字段为任意值
