### ISSUE TITLE
继承对象后修改时间问题

### ISSUE THREAD

**Issue by caorongzhe** [baomidou/mybatis-plus#3292]
### 当前使用版本(必填,否则不予处理)
版本：3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
线上问题

### 重现步骤(如果有就写完整)
dto继承生成的对象文件，然后使用生成的修改方法，传入dto修改成功，修改时间第一次成功，但是往后即使在修改数据也不会再做时间修改了。

### 报错信息
无

**Comment by miemieYaho** [comment]
mp不做sql执行
