### ISSUE TITLE
3.4.1，3.4.2 mysql5.7全文索引，分页PaginationInnerInterceptor方式sql查询报错，而旧的PaginationInterceptor配置没问题

### ISSUE THREAD

**Issue by xiesangzi** [baomidou/mybatis-plus#3294]
### 当前使用版本(必填,否则不予处理)
3.4.1，3.4.2也一样有问题

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 mysql5.7全文索引，使用以下分页方式报错
  @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        PaginationInnerInterceptor paginationInnerInterceptor = new PaginationInnerInterceptor(DbType.MYSQL);
        interceptor.addInnerInterceptor(paginationInnerInterceptor);
        return interceptor;
    }

如果换成下下面方式就没问题
@Bean
public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
        // 设置请求的页面大于最大页后操作， true调回到首页，false 继续请求  默认false
         paginationInterceptor.setOverflow(false);
        // 设置最大单页限制数量，默认 500 条，-1 不受限制
          paginationInterceptor.setLimit(500);
        // 开启 count 的 join 优化,只针对部分 left join
        paginationInterceptor.setCountSqlParser(new JsqlParserCountOptimize(true));
        return paginationInterceptor;
    }
### 报错信息
17:44:04.694 logback [XNIO-1 task-1] WARN  c.b.m.e.p.i.PaginationInnerInterceptor - optimize this sql to a count sql has exception, sql:"select a.id as tchId,b.role_id,c.title as roleName, a.name, a.sex, a.birthday, a.wk_num, a.phone,
        a.status,a.type, a.remark,b.avatar, a.create_user, a.create_time
        from t_bs_teacher a
        inner join sys_user b on b.id = a.id
        left join sys_role c on c.id = b.role_id
         WHERE a.deleted = 0 and MATCH(a.name,a.wk_num,a.phone) AGAINST(? IN BOOLEAN MODE) 
        order by a.id desc", exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "MATCH" "MATCH"
    at line 8, column 21.

Was expecting one of:

    "!"
    "("
    "NOT"

**Comment by miemieYaho** [comment]
这只是警告，老插件没打印而已

**Comment by zerodayZHOUXUTIAN** [comment]
这个警告日志、下个版本能去掉吗。吓死人。
