### ISSUE TITLE
MybatisSqlSessionFactoryBean报错java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory

### ISSUE THREAD

**Issue by Chenyt24** [baomidou/mybatis-plus#3295]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
代码配置MybatisSqlSessionFactoryBean出错，看源码发现
import org.mybatis.logging.Logger;
import org.mybatis.logging.LoggerFactory;
这两个类应该路径不对，mybatis3.4.6中路径应该是org.apache.ibatis.logging.LogFactory

### 重现步骤(如果有就写完整)

只要启动就会报错

### 报错信息

Caused by: java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory

**Comment by miemieYaho** [comment]
mybatis- spring依赖版本冲突

**Comment by Chenyt24** [comment]
我只导入了一个mybatis-plus-boot-starter，怎么导致版本冲突呢
