### ISSUE TITLE
自动填充功能

### ISSUE THREAD

**Issue by kliein** [baomidou/mybatis-plus#3296]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter  3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
有一个类没有配置@TableField注解，但是里面的更新时间被自动填充了。

### 重现步骤(如果有就写完整)

这是配置的自动填充代码
@Component
public class MetaHandler implements MetaObjectHandler {

    @Override
    public void insertFill(MetaObject metaObject) {
        this.setFieldValByName("createTime", new Date(), metaObject);
        this.setFieldValByName("updateTime", new Date(), metaObject);
    }

    @Override
    public void updateFill(MetaObject metaObject) {
        this.setFieldValByName("updateTime", new Date(), metaObject);
    }
}

### 报错信息
所有的插入和更新都会自动填充，但是并没有添加@TableField注解

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/auto-fill-metainfo.html
