### ISSUE TITLE
Pagination SearchCount 默认为true导致查询慢

### ISSUE THREAD

**Issue by abocode** [baomidou/mybatis-plus#330]
if (rowBounds instanceof Pagination) {
                Pagination page = (Pagination)rowBounds;
                boolean orderBy = true;
                if (page.isSearchCount()) {
                    SqlInfo sqlInfo = SqlUtils.getOptimizeCountSql(page.isOptimizeCountSql(), this.sqlParser, originalSql);
                    orderBy = sqlInfo.isOrderBy();
                    this.queryTotal(this.overflowCurrent, sqlInfo.getSql(), mappedStatement, boundSql, page, connection);
                    if (page.getTotal() <= 0L) {
                        return invocation.proceed();
                    }
                }

**Comment by qmdx** [comment]
默认会优化你的 sql 变成 count sql ，如果无法优化你可以设置 false 自定义 count 设置到 page
