### ISSUE TITLE
xml映射文件找不到

### ISSUE THREAD

**Issue by Chenyt24** [baomidou/mybatis-plus#3302]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

检查配置没有问题，BaseMapper可以使用，但是xml文件绑定找不到

### 报错信息

Invalid bound statement (not found)

**Comment by miemieYaho** [comment]
看文档常见问题

**Comment by Chenyt24** [comment]
检查了，但是都对
