### ISSUE TITLE
出现"Invalid bound statement (not found)"问题，根据官网的解决办法没能解决

### ISSUE THREAD

**Issue by JaneRoad** [baomidou/mybatis-plus#3303]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自建一个新的类文件，service接口，serviceImpl实现类，类的mepper，引入了mybatisplus后，使用save方法报这个错

### 重现步骤(如果有就写完整)
大概意思同上

### 报错信息
{
    "msg": "Invalid bound statement (not found): com.xxx.framework.mapper.xxxMapper.insert",
    "code": 500
}

**Comment by liqiang1216** [comment]
这个问题怎么解决的
