### ISSUE TITLE
自动填充功能更新字段，“【如果有值则不覆盖】”这种设计理念会使更新字段的意义丧失

### ISSUE THREAD

**Issue by iamdzk** [baomidou/mybatis-plus#3307]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在自动填充功能中，【MetaObjectHandler提供的默认方法的策略均为:如果属性有值则不覆盖,如果填充值为null则不填充。】这个设计理念会使更新字段的意义丧失。

### 重现步骤(如果有就写完整)

例如：updateTime这样的时间字段，我在插入时要更新，在修改时也要更新，但是我在使用时，先插入或查询出来，更新后再修改回数据库，该字段会因为【如果有值则不覆盖】使得updateTime字段还保持着原来的值，并没有更新。

### 报错信息

无

**Comment by huayanYu** [comment]
支持自定义的啊。~   setFieldValByName(fieldName, fieldVal, metaObject);

**Comment by miemieYaho** [comment]
重写调用链最后的method去

**Comment by iamdzk** [comment]
非常感谢您的回复。但是这个问题大多数人在使用时并没有注意到这个问题，如果可以，希望能在【[自动填充功能](https://baomidou.com/guide/auto-fill-metainfo.html)】页面添加一些提示，提示用户关于updatetime的问题和如何自定义修改这样的功能。毕竟不点进去看源码的实现方式，是不知道怎么去自定义的。
