### ISSUE TITLE
spring-boot-devtools热重启不加载MetaObjectHandler

### ISSUE THREAD

**Issue by JeremyZheng** [baomidou/mybatis-plus#331]
# 需求简述
使用spring boot并使用spring-boot-devtools自动进行热加载，公共字段字段填充类无法被spring-devtools类加载器加载.

# 背景简述
spring boot, mybatis plus

# 产生问题
insertFill中或者updateFill方法在强行转换对象类型时发生ClassCastException。
比如获取shiro中的user对象：User user = (User)SecurityUtils.getSubject().getPrincipal();就会抛出ClassCastException，由于类加载器不同不能把User转成User。

# workaround
禁用spring-boot-devtools

**Comment by JeremyZheng** [comment]
@qmdx 修改好格式了，请看一下吧

**Comment by qmdx** [comment]
这个问题暂时无时间去重现，如果解决欢迎 pr
