### ISSUE TITLE
为什么 selectBatchIds 返回结果是按ID 排序的？

### ISSUE THREAD

**Issue by Q-Qplus1s** [baomidou/mybatis-plus#3311]
为什么 selectBatchIds 返回结果是按ID 排序的？

### 当前使用版本(必填,否则不予处理)
3.3.2

### 重现步骤(如果有就写完整)

idList = [2,3,1,5];
var res = selectBatchIds(idList);
返回 res 的id 排序：[1,2,3,5];

**Comment by miemieYaho** [comment]
你得去问数据库
