### ISSUE TITLE
@DS注解value是否支持bean name

### ISSUE THREAD

**Issue by iHarry007** [baomidou/mybatis-plus#3313]
目前datasource都是通过bean封装的，DS注解支持bean name 吗？有没有讨论群？快速联系技术支持

**Comment by miemieYaho** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter

**Comment by iHarry007** [comment]
项目文档看过了，就是说不支持?

**Comment by iHarry007** [comment]
> https://github.com/baomidou/dynamic-datasource-spring-boot-starter

项目文档看过了，就是说不支持?
