### ISSUE TITLE
QueryWrapper如何支持两个条件组的and/or合并？

### ISSUE THREAD

**Issue by xiaoshengaimm** [baomidou/mybatis-plus#3319]
### 当前使用版本(必填,否则不予处理)
        <mybatis-plus.version>3.4.1</mybatis-plus.version>      
      
       <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

如何缔造条件组合 
`select * from table where (a = 0 and b = 0) and (c LIKE '%str%' or d LIKE '%str%');`

```
我目前有条件组1 QueryWraper1 对应条件 a = 0 and b = 0
条件组2 QueryWrapper2 对应条件  c LIKE '%str%' or d LIKE '%str%'
目前没有找到办法 queryWraper1.and(queryWrapper2)
```

**Comment by miemieYaho** [comment]
文档用法里有,自己去研究

**Comment by liubinylx** [comment]
> 文档用法里有,自己去研究

文档写的乱七八糟，只能高手用，普通人不适合
