### ISSUE TITLE
DB2中insertBatch方法引发的NPE异常

### ISSUE THREAD

**Issue by hepengju** [baomidou/mybatis-plus#332]
## 需求简述
在数据库表主键设置为自增, 执行通用的insertBatch方法时, 如果数据库驱动支持获得产生的主键则自动设置主键, 如果数据库驱动不支持, 方法也应该执行成功. (比如excel批量导入的时候)

## 背景简述
1. BO类的主键数据库自增.
2. 通用insert(T entity)插入后, BO可以获得数据库的自增主键.
3. 通用insertBatch(List<T> entityList)插入后, 在MySQL数据库中也可以正常获得主键, 但是在DB2数据库中无法获得, 抛出NPE异常. 
  * 测试代码[Db2GenKeys](https://gist.github.com/harawata/f1d75e8cb7af919bf63d3a7623f805a2)

## 产生问题
DB2数据库批量插入的时候无法获得自增主键, 导致这个通用方法发生异常

## 解决分析
1. DB2的JDBC驱动解决
  * 但如果也有其他数据库在批量插入时无法获得自增主键呢?
2. MyBatis解决.
  * 参看[Mybatis Issue 1288](https://github.com/mybatis/mybatis-3/issues/1288)
  * Mybatis建议不需要主键自增的时候, 设置```useGeneratedKeys``` is ```false```. 
3. MybatisPlus解决
  * ServiceImpl.insertBatch(List<T>, int)中的batchSqlSession.flushStatements(); 用try-catch包裹起来, 打印警告信息. 但不知道批量刷入时,是否会有其他的异常产生, 也许需要Mybatis在这种情况下抛出指定异常, 比如```GeneratedKeysException```

**Comment by qmdx** [comment]
你这个 issue 可以评为 最佳 issue 非常感谢

**Comment by yuxiaobin** [comment]
最佳 issue 非常感谢
