### ISSUE TITLE
请问如何在非spring项目里使用？

### ISSUE THREAD

**Issue by kran** [baomidou/mybatis-plus#3320]
查了很多文档，没有相关说明。不知是否支持呢？

**Comment by miemieYaho** [comment]
目前暂时不太支持

**Comment by miemieYaho** [comment]
你可以看看 https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/BaseDbTest.java,获取mapper只能通过`sqlSession.getMapper`

**Comment by kran** [comment]
多谢多谢。不知道是否有相应的开发计划，mp真的太好用了。感谢您的产品。
