### ISSUE TITLE
QueryWrapper的select查询的字段无法通过TableField映射到实体

### ISSUE THREAD

**Issue by q8888tttt** [baomidou/mybatis-plus#3322]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

QueryWrapper的select查询的字段无法通过TableField映射到实体
只有实体属性和select后的字段名一样才能成功映射，其他的的无法映射
而使用lambdaQuery().select才能映射成功

### 重现步骤(如果有就写完整)

list(new QueryWrapper<>(entity).select("x1","x2")

**Comment by miemieYaho** [comment]
自己加上 as
