### ISSUE TITLE
left join 查询时，返回的分页条数不对

### ISSUE THREAD

**Issue by huan3360166** [baomidou/mybatis-plus#3327]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页查询

### 重现步骤(如果有就写完整)
实际查询sql语句：select su.id,sur.id name from sys_user su left join sys_user_role sur ON su.id = sur.user_id
log打印的分页条数查询sql语句 SELECT COUNT(1) FROM sys_user su
left join 语句后面丢失

**Comment by miemieYaho** [comment]
插件.optimizeJoin = false
