### ISSUE TITLE
mapper xml较多时，扫描较耗时

### ISSUE THREAD

**Issue by HiJackXD** [baomidou/mybatis-plus#3329]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目存在较多xml时，启动扫描xml较耗时

**Comment by miemieYaho** [comment]
你需要给它 提 https://github.com/mybatis/spring/blob/master/src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
