### ISSUE TITLE
Mybatis-Plus Comment

### ISSUE THREAD

**Issue by qmdx** [baomidou/mybatis-plus#333]
提问方式参考： https://github.com/baomidou/mybatis-plus/issues/332 

不符合一律不予回复！！

**Comment by tcdwlid** [comment]
postgesql 的数组怎么转？

**Comment by yaohu0044** [comment]
请问下 MySQL在插入成功以后 怎么返回主键   或者是需要配置个什么才能返回?

**Comment by lovesea6688** [comment]
用mycat中间件的话，表名为关键字的话，我建了一张表名为position的表，插入报错，表名没有带``,不让插入，直接连库貌似可以，所有我想这个是不是可以给关键保留字为表名的上面加个`，引起来

**Comment by arraykyky** [comment]
按照api怎么抛出异常，是哪里配置的问题嘛
There is no getter for property named 'ew' in 'class com.baomidou.mybatisplus.mapper.EntityWrapper'

**Comment by DarkLove** [comment]
@Autowired
    private DataSource dataSource;

    @Bean
    public MybatisSqlSessionFactoryBean sqlSessionFactory(){
        MybatisSqlSessionFactoryBean mybatisPlus = new MybatisSqlSessionFactoryBean();
        mybatisPlus.setDataSource(dataSource);
        GlobalConfiguration globalConfiguration = new GlobalConfiguration();
        globalConfiguration.setMetaObjectHandler( new MyMetaObjectHandler());
        mybatisPlus.setGlobalConfig(globalConfiguration);
        return mybatisPlus ;
    }
请问不用xml文件怎么配置，以上是我的，报错了

**Comment by DarkLove** [comment]
> @arraykyky
> 按照api怎么抛出异常，是哪里配置的问题嘛
> There is no getter for property named 'ew' in 'class com.baomidou.mybatisplus.mapper.EntityWrapper'
哥们，你的搞好了没

**Comment by arraykyky** [comment]
> @DarkLove
> 我自己把EntityWrapper封装了一下，调用变成了下面的形式
List<?> listEW = abstractService.selectMyPage(page, ew);
 PageData pageData = new PageData();//一个map结构的对象
 pageData.put("ew",entityWrapper);//添加key=ew,对应xml中取值
 return baseMapper.selectMyPage(page,pageData);
xml中的sql是这样写的，pd就是pagedata的简称，可以通过@Alias("pd")配置
<select id="selectMyPage" parameterType="pd" resultMap="BaseResultMap">
        SELECT * FROM fd_abstract
        <where>
            ${ew.sqlSegment}//ew对应pd中的ew对象
        </where>
</select>

**Comment by arraykyky** [comment]
> @DarkLove
>xml
    <select id="selectMyPage" parameterType="pd" resultMap="BaseResultMap">
        SELECT * FROM fd_abstract
        <where>
            ${ew.sqlSegment}
        </where>
    </select>

**Comment by arraykyky** [comment]
@DarkLove 
    <select id="selectMyPage" parameterType="pd" resultMap="BaseResultMap">
        SELECT * FROM fd_abstract
        <where>
            ${ew.sqlSegment}
        </where>
    </select>

**Comment by arraykyky** [comment]
@DarkLove 
详细的xml贴不上去，页面过滤掉了

**Comment by miraclehjt** [comment]
使用EntityWrapper在本地环境正常，在centos下出现字段找不到的奇怪问题，本身没有这个字段，求解。 org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.entity.authId!=null'. Cause: org.apache.ibatis.ognl.NoSuchPropertyException: com.ytkj.web.user.entity.UserSampleInfo.authId

**Comment by wangchunting666** [comment]
如果数据库表字段首字母小写，生成的实体类，不能使用insertOrUpdate方法？

**Comment by miraclehjt** [comment]
调用删除方法报错，ew传参数进去提示一个字段不存在，而这个字段这个实体没有，莫名其妙出来的，最奇怪的是本地环境没问题，阿里云上报错。

**Comment by suollk** [comment]
请问有人使用多租户这个测试成功的么?研究了一天demo都没通

**Comment by suollk** [comment]
想请教一下关于多租户的实现问题: 我下载了springboot版本的demo

修改数据库为:mysql  建立user表   

但是多租户的问题一直没有成功  我把内部的字段从 tenantId改为了 tenant_id 也不行

想请教一下有成功处理了的兄弟么?

**Comment by ouyangbob** [comment]
请问什么时候支持springboot2.0 啊？

**Comment by lovesea6688** [comment]
> @ouyangbob
> 请问什么时候支持springboot2.0 啊？
> 
这个是支持的啊，我前几天就用这个做了个小项目，用的就是springboot2.0

**Comment by abciop** [comment]
有没有考虑实体生成JSR验证

**Comment by ouyangbob** [comment]
@lovesea6688 
不行，我这边springboot2.0 + oracle 不支持。

**Comment by ouyangbob** [comment]
@miraclehjt  请问你解决了没？我现在也报这个错误。

**Comment by Lu1ffy** [comment]
请问我看有的案例项目里面只有mybatisplus-spring-boot-starter一个依赖,而有的项目里有两个依赖,一个是mybatisplus-spring-boot-starter,另外一个是mybatis-plus,只用其中的一个会有什么问题吗? 还是说两个都必须要,项目是spingboot项目

**Comment by lovesea6688** [comment]
@ouyangbob 我用的是mysql

**Comment by chenyi2333** [comment]
使用通用 单表新增时，支持自定义主键生成规则吗

**Comment by njxujunjie** [comment]
为啥集成到自己的工程里 一直启动不起来  有大神指导一下么：
Caused by: java.lang.NoSuchMethodError: org.apache.ibatis.session.Configuration.getDefaultScriptingLanguageInstance()Lorg/apache/ibatis/scripting/LanguageDriver;
	at com.baomidou.mybatisplus.mapper.AutoSqlInjector.injectSqlRunner(AutoSqlInjector.java:906)
	at com.baomidou.mybatisplus.MybatisMapperRegistry.<init>(MybatisMapperRegistry.java:48)
	at com.baomidou.mybatisplus.MybatisConfiguration.<init>(MybatisConfiguration.java:45)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:419)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 53 common frames omitted

**Comment by jackenwjk** [comment]
mybatis- plus中使用BaseMapper基类的方法不会走二级缓存，请问有什么方法可以解决吗？

**Comment by lidk** [comment]
oracle不支持么？

**Comment by y5284037** [comment]
初来学习, 点赞一波.

**Comment by honglang1992** [comment]
请问下 MySQL在插入成功以后 怎么返回主键 或者是需要配置个什么才能返回?

**Comment by yaohu0044** [comment]
> @honglang1992
> 请问下 MySQL在插入成功以后 怎么返回主键 或者是需要配置个什么才能返回?

  	<property name="idType" value="0" />

**Comment by jamespangm** [comment]
数据库 主键id字段类型为 varchar mp配置的为主键全局增长. 但是在插入数据的时候无论设置不设置id值,执行时候都报错:Caused by: java.sql.SQLException: Field 'id' doesn't have a default value;  执行插入语句的时候没有插入id值得语句 .哪位大神有办法解决? 谢谢

**Comment by honglang1992** [comment]
楼上的问题：
 没遇到 主键id 用varchar的情况，都是用的 数字类型
解决方法： 你试着在数据库里把id 换成int类型，并设为自增长。

**Comment by VincentHQL** [comment]
你好，能否把TableField注解中 el 的用法描述的详细点？ “当该Field为类对象时, 可使用#{对象.属性}来映射到数据表.”意思是不是可以映射对象或者集合？

**Comment by MartinYiWu** [comment]
启动报错  哪位大神知道什么原因吗？
15:53:40.644 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/velocity/context/Context
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)
	at com.pdcourse.generator.MyBatisPlusGenerator.main(MyBatisPlusGenerator.java:81)
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.context.Context
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by xzsanmm** [comment]
类User对象属性office指向类Office.
以前用mybatis，写sql:select a.id,a.office_id as office.id ,o.name as office.name from user a left join office o on a.office_id=o.id
通过该sql，可以在返回的user对象中获取office对象（id和name属性有值），一个查询就可以。
在plus中，好像就直接用officeId的属性来指明外部对象关联情况（查看了很多例子，sql查询只返回user对象，然后遍历user对象，通过officeId获取office对象再赋值）
在sql中，basemapper默认实现的select*函数中，该如何配置相关信息，以到达类似上面sql语句效果（不用另外编写xml文件中的sql语句，而是通过annonation的配置，获取在xml中额外配置部分语句）。

**Comment by telltao** [comment]
> @yaohu0044
> 请问下 MySQL在插入成功以后 怎么返回主键   或者是需要配置个什么才能返回?

不需要配置 直接实体类.getId() 就是你入库的id啦~

**Comment by honglang1992** [comment]
> @telltao
> > @yaohu0044
> > 请问下 MySQL在插入成功以后 怎么返回主键   或者是需要配置个什么才能返回?
> 
> 不需要配置 直接实体类.getId() 就是你入库的id啦~

 BaseMapper<T>.insert(T entity)方法，但是插入成功之后，entity里的id 依然是null

**Comment by honglang1992** [comment]
> @yaohu0044
> > @honglang1992
> > 请问下 MySQL在插入成功以后 怎么返回主键 或者是需要配置个什么才能返回?
> 
>   	<property name="idType" value="0" />

我就是这样配置的，生成的entity如下所示：
	@TableId(value="id", type= IdType.AUTO)
	private Integer id;

我用的是sql server

**Comment by dlovetco** [comment]
GlobalConfig和GlobalConfiguration 有啥区别
yml里面配置的是GlobalConfig
而在sqlsession中注入的却是GlobalConfiguration 完全把配置文件中的GlobalConfig屏蔽掉了

**Comment by TomyJx** [comment]
在我们自己进行查找的时候，因为代码中大量用到了列名，作为查找条件。那么当某个列名修改的时候，就需要进行编码的修改了。这里提议，能不能再生成实体类的时候，也顺便生成一个表对应的静态变量类。这个类中的字段就是列名呢。。。

**Comment by mhs1314** [comment]
实体不支持生成swagger注解啊

**Comment by lidk** [comment]
请问怎么使id字段自动递增的

**Comment by telltao** [comment]
> @lidk
> 请问怎么使id字段自动递增的

在id字段上添加  @TableId(value = "id",type = IdType.AUTO) type注解就是自增,如果是springboot 在application.yml 中填入 mybatis-plus: global-config:id-type: 0    就可以了 有问题发我邮箱 tellstao@163.com

**Comment by kallima55206086** [comment]
在3.x 版本中，这个自定义sql注入怎么配置啊

**Comment by honglang1992** [comment]
背景：
1.数据库 sqlsever  字段类型：decimal(18,8) 用途：余额
2.生成的entity 里的字段，用的Bigdecimal ，官方默认用的double，这里我为了避免精度丢失的后续使用问题，直接在AutoGenerator的时候换成了Bigdecimal

问题：
在调用insert（entity）时，发现，无论BigDecimal值是多少，插入数据库中都会变成0，请问有目前有什么解决办法吗

debug日志：
14:13:23,719 DEBUG insert:159 - ==>  Preparing: INSERT INTO coin_line_history ( currency_id, period, count_time, open_price, high_price, low_price, close_price, deal_amount ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? ) 
14:13:23,720 DEBUG insert:159 - ==> Parameters: 1(Integer), 604800000(Integer), 1530720000000(Long), 0E-8(BigDecimal), 0E-7(BigDecimal), 0E-8(BigDecimal), 0E-7(BigDecimal), 0.0000(BigDecimal)

**Comment by chexiazi** [comment]
> @yaohu0044
> 请问下 MySQL在插入成功以后 怎么返回主键   或者是需要配置个什么才能返回?

不是说了 会返回主键到实体类吗？你没有看 简单示例的文档？

**Comment by chexiazi** [comment]
> @honglang1992
> > @telltao
> > > @yaohu0044
> > > 请问下 MySQL在插入成功以后 怎么返回主键   或者是需要配置个什么才能返回?
> > 
> > 不需要配置 直接实体类.getId() 就是你入库的id啦~
> 
>  BaseMapper<T>.insert(T entity)方法，但是插入成功之后，entity里的id 依然是null

你需要这样去接收 才会有  user = user.insert(xxx);

**Comment by a931083335** [comment]
字段isDeleted  解析set get方法时 ，get方法 解析成了 isDeleted（） 这个问题怎么解决

**Comment by a931083335** [comment]
/** 前缀处理 */
        String property = fieldInfo.getProperty();
        Class propertyType = fieldInfo.getPropertyType();
        property = StringUtils.removeIsPrefixIfBoolean(property, propertyType);


 * <p>
     * 去除boolean类型is开头的字符串
     * </p>
     *
     * @param propertyName 字段名
     * @param propertyType 字段类型
     * @return
     */
    public static String removeIsPrefixIfBoolean(String propertyName, Class<?> propertyType)这个能不能配置啊别强制转

**Comment by telltao** [comment]
@chexiazichexiazi  不要误人子弟 user.insert(userEntity); 返回的是boolean类型

**Comment by limingbonc** [comment]
如何调整xml生成位置， 我想在resources/mapper下

**Comment by chenyurong** [comment]
按照配置启动报错。。。

**Comment by darren-wang** [comment]
使用Spring boot 2.0.3, FreeMarker, Mysql, Druid, MP测试自动代码生成过程中，`com.baomidou.mybatisplus.annotation.TableId`和`com.baomidou.mybatisplus.annotation.TableField`注解被错误的生成为`com.baomidou.mybatisplus.annotations.TableId`和`com.baomidou.mybatisplus.annotations.TableField`，希望修复！

**Comment by qmdx** [comment]
@darren-wang  你用的是 MP3 吧？ 这个问题已经解决，最新快照  3.0-beta-SNAPSHOT

**Comment by zhaojiacan** [comment]
条件构建器，or或者orNew         user = this.selectOne(new EntityWrapper<User>()
                    .or("user_account="+username)
                    .or("user_mobile="+username)
                    .or("user_email="+username)
不加单引号报错，sql中不会自己加单引号
SELECT  user_id AS userId,user_key AS userKey,user_name AS userName,user_pet_name AS userPetName,user_birthday AS userBirthday,user_sex AS userSex,user_photo_url AS userPhotoUrl,user_mobile AS userMobile,user_email AS userEmail,user_account AS userAccount,user_password AS userPassword,user_reg_time AS userRegTime,user_login_time AS userLoginTime,user_active AS userActive,user_signature AS userSignature,user_remark AS userRemark  FROM user   WHERE  (user_account=admin OR user_mobile=admin OR user_email=admin

**Comment by qmdx** [comment]
@zhaojiacan   wrapper 部分需要手动添加转义符

**Comment by darren-wang** [comment]
逻辑删除的视频能不能换个清楚一点的，上面的字什么都看不到。

**Comment by MissJin** [comment]
> @xzsanmm
> 类User对象属性office指向类Office.
> 以前用mybatis，写sql:select a.id,a.office_id as office.id ,o.name as office.name from user a left join office o on a.office_id=o.id
> 通过该sql，可以在返回的user对象中获取office对象（id和name属性有值），一个查询就可以。
> 在plus中，好像就直接用officeId的属性来指明外部对象关联情况（查看了很多例子，sql查询只返回user对象，然后遍历user对象，通过officeId获取office对象再赋值）
> 在sql中，basemapper默认实现的select*函数中，该如何配置相关信息，以到达类似上面sql语句效果（不用另外编写xml文件中的sql语句，而是通过annonation的配置，获取在xml中额外配置部分语句）。
-----------------------------------------------
可以使用 在mapper中的定义一个 resultMap , 级联的表 可以用 collection 关键字

**Comment by wangyijue** [comment]
List<String> list = new ArrayList<String>(){{
           add("015bce6e7d084693beb58c6a8ea39ea0");
           add("01ba84356bb049e190d9ac77791c14b1");
           add("01df182396d3473fae79ce52af078b34");
           add("0246cae1e472429c857b33c5ff5f2cd3");
           add("073bca8a41db4c429cd49d8eb4620079");
           add("0753dcdc6f844dbc94f919abc1cfcc9c");
           add("079e7fd492bb4d44abd662380c36b738");
        }};
        return smsSourcePoolMapper.selectList(new EntityWrapper<SmsSourcePool>().in("id",list));
整合的spring boot2.0 每次这么写都会报错
类似这种
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'type' not found. Available parameters are [ew, param1]
请问怎么解决

**Comment by qmdx** [comment]
@wangyijue  这个才是重点 Parameter 'type' not found.

**Comment by miYox-z** [comment]
yml文件有误吧   为什么db-config节点没了

**Comment by kallima55206086** [comment]
这个以后还要维护吗

**Comment by kallima55206086** [comment]
还是3.0 就是终结版了

**Comment by kallima55206086** [comment]
sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector 3.0 这个在spring boot 中直接配置就报错啊，该怎么配置啊

**Comment by suollk** [comment]
@darren-wang   你这个问题  其实可以直接重写他的生成代码

**Comment by Z-Beatles** [comment]
> /** 前缀处理 */
> String property = fieldInfo.getProperty();
> Class propertyType = fieldInfo.getPropertyType();
> property = StringUtils.removeIsPrefixIfBoolean(property, propertyType);
> 
> * * 去除boolean类型is开头的字符串
>     * 
>     *
>     * @param propertyName 字段名
>     * @param propertyType 字段类型
>     * @return
>     */
>    public static String removeIsPrefixIfBoolean(String propertyName, Class propertyType)这个能不能配置啊别强制转
这个强制去除很头疼啊，新版本解决了吗。或者老铁们有什么优雅的方法吗？
