### ISSUE TITLE
多线程,for循环查询,数据重复

### ISSUE THREAD

**Issue by VitZhou** [baomidou/mybatis-plus#3331]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
多线程,for循环查询,数据重复

代码如下
list.parallelStream().peek(e->{
 E e = dao.select(e.id, randId); 
 if (e == null){
dao.insert(e)
}else{
  dao.update(e)
}
})

### 重现步骤(如果有就写完整)

麻烦看下图片把 代码不好贴
https://tva1.sinaimg.cn/large/008eGmZEgy1gne06a9g2cj31bt0jljw4.jpg

https://tva1.sinaimg.cn/large/008eGmZEgy1gne05vybz1j30ka045gly.jpg

**Comment by miemieYaho** [comment]
自行排查，mp不负责sql执行
