### ISSUE TITLE
MybatisPlusInterceptor支持对执行结果处理

### ISSUE THREAD

**Issue by duanqinglei** [baomidou/mybatis-plus#3332]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-extension 3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当我想对update操作结果做统一处理的时候，试图实现InnerInterceptor接口，InnerInterceptor接口是个很优秀的接口，能够处理beforeQuery，beforeUpdate等，但是没发现afterQuery，afterUpdate，是否会考虑对执行结果处理的支持？

**Comment by miemieYaho** [comment]
该接口本质就是对mybatis的插件进行扩展而已，不会支持
