### ISSUE TITLE
QueryWrapper的lambda表达式condition遇到null对象出现npe异常

### ISSUE THREAD

**Issue by lovejavaallmylife** [baomidou/mybatis-plus#3334]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
ConditonDTO conditionDTO = null;
queryWrapper.lambda().eq(conditionDTO != null, DBEntity::getAppCode, conditionDTO .getAppCode());
按照理解，如果condition如果判定为false，condition后面的条件就不应该在执行。如：
if(conditionDTO != null && conditionDTO.getAppCode() != null)

### 报错信息
NullPointerException

**Comment by miemieYaho** [comment]
回去重修java

**Comment by qrqhuang** [comment]
@miemieYaho 

这块使用`eq(condition, xx)`方法时， 可否提供一个 `Supplier val` 的重载呢
楼上的诉求其实很常见
