### ISSUE TITLE
IdType.ASSIGN_UUID自动生成的UUID没有中杠

### ISSUE THREAD

**Issue by CodingSoldier** [baomidou/mybatis-plus#3335]
### 当前使用版本(必填,否则不予处理)
<mybatis.plus.version>3.3.2</mybatis.plus.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
postgresql的UUID类型的字段必须带有中杠，不然无法插入数据。
mybatis plus不支持自动生成带中杠的UUID，导致我不能在数据库中把ID字段定义为UUID类型

### 重现步骤(如果有就写完整)
1、postgresql数据库表id定义为UUID类型
2、自动生成代码，java bean的id是@TableId(value = "id",type = IdType.ASSIGN_UUID)
3、插入数据

### 报错信息
能插入成功，但是postgresql会自动加中杠，导致很困惑

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/incrementer/IdentifierGenerator.java
