### ISSUE TITLE
This primary key of "id" is primitive !不建议如此请使用包装类 in Class: "com.job.entity.User"

### ISSUE THREAD

**Issue by Bleachtred** [baomidou/mybatis-plus#3337]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
定义实体类使用时产生问题

### 重现步骤(如果有就写完整)
实体类定义如下：
@Data@ToString
public class User implements Serializable {
    private int id;
    private String name;//用户名
    private String account;//账号
    private String password;//密码
    private String avatar;//头像
    private String sex;//性别
    private int age;//年龄
    private int category;//类别 1管理员  2用户
    private int flag;//是否有效
    private Date insertTimestamp;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }
    public User(){
        this.insertTimestamp = new Date(System.currentTimeMillis());
    }
}

可进行增删改查，无问题。就是运行时产生警告。但是不影响使用。就是想问一下，如何清除该警告。

### 报错信息
This primary key of "id" is primitive !不建议如此请使用包装类 in Class: "com.job.entity.User"

**Comment by Edwin-Xu** [comment]
what?

**Comment by elinxer** [comment]
Entity => change id column as long  using  Long
Mark！
