### ISSUE TITLE
希望在未来版本提供的基类中，增改操作可以直接返回增改成功后的对象

### ISSUE THREAD

**Issue by YoungTakhin** [baomidou/mybatis-plus#3338]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
默认的基类增改操作返回的boolean类型，但由于业务原因，在实际使用中需要返回增改后的对象，为了避免重复造轮子，希望可以在通过配置的方式来控制整改操作的返回值（整改成功后的对象或boolean值）

**Comment by miemieYaho** [comment]
没有
