### ISSUE TITLE
自定义一个服务类扩张ServiceImpl，执行保存实体的时候获取的实体对象不对

### ISSUE THREAD

**Issue by lisonglin** [baomidou/mybatis-plus#3340]
### 当前使用版本(必填,否则不予处理)
V3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
public class CommonServiceImpl<T, E extends Model<E>, M extends BaseMapper<E>> extends ServiceImpl<M, E> 

### 重现步骤(如果有就写完整)
我服务端使用微服务，自定义了一个CommonServiceImpl<DTO, Model, Mapper>
执行保存操作的时候在旧版本的3.1.0中可以拿到正确的entityClass，
在3.4.1会DTO.insert 方法不存在（获取entityClass为DTO这个class），

### 报错信息

在3.4.1会DTO.insert 方法不存在（获取entityClass为DTO这个class）

**Comment by qmdx** [comment]
请给出复现 demo 根据描述无法定位
