### ISSUE TITLE
分页 模型 isSearchCount  不填写默认false 不分页

### ISSUE THREAD

**Issue by gaoquanqiang** [baomidou/mybatis-plus#3341]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

接口入参为page对象

### 重现步骤(如果有就写完整)

接口入参为page对象
 @GetMapping("list")
    public ResponseData list(Pages pages) {}

### 报错信息
total=0
pages=0

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/pagination/Page.java
