### ISSUE TITLE
能否在逻辑删除时也执行 updateFill策略，不然无法记录删除人删除时间

### ISSUE THREAD

**Issue by Skight** [baomidou/mybatis-plus#3344]
### 当前使用版本(必填,否则不予处理)
3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

能否在逻辑删除时也执行 updateFill策略，不然无法记录删除人删除时间

### 重现步骤(如果有就写完整)
逻辑删除, updateTime updateBy等公共表字段想要能够自动更新

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/logic-delete.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by zhen-e-liu** [comment]
感谢回复，这个我了解的，但是需要项目整体扩展Mapper，实现起来比较麻烦而且也不太通用。
能否增加logicByFill注解，类似于InsertFill和updateFill一样的策略注解，有BaseMapper内置支持。

**Comment by miemieYaho** [comment]
没有
