### ISSUE TITLE
国产瀚高数据库支持

### ISSUE THREAD

**Issue by yfdxzy2010** [baomidou/mybatis-plus#3353]
### 3.4.2
您好，
我是国产瀚高数据库的开发者，随着国产化的快速进行，瀚高数据库的用户量也在快速增加，需要在mybatis-plus中增加对瀚高数据库配置的支持，希望可以得到大佬的支持。下边是瀚高数据库jdbc的配置方式：
driver: com.highgo.jdbc.Driver
url: jdbc:highgo://hostname:port/dbname
分页语法：
    SELECT select_list
    FROM table_expression
    [ ORDER BY ... ]
    [ LIMIT { number | ALL } ] [ OFFSET number ]
If a limit count is given, no more than that many rows will be returned (but possibly fewer, if the query itself yields fewer rows). LIMIT ALL is the same as omitting the LIMIT clause, as is LIMIT with a NULL argument.

OFFSET says to skip that many rows before beginning to return rows. OFFSET 0 is the same as omitting the OFFSET clause, as is OFFSET with a NULL argument.

If both OFFSET and LIMIT appear, then OFFSET rows are skipped before starting to count the LIMIT rows that are returned.

When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows. You might be asking for the tenth through twentieth rows, but tenth through twentieth in what ordering? The ordering is unknown, unless you specified ORDER BY.

The query optimizer takes LIMIT into account when generating query plans, so you are very likely to get different plans (yielding different row orders) depending on what you give for LIMIT and OFFSET. Thus, using different LIMIT/OFFSET values to select different subsets of a query result will give inconsistent results unless you enforce a predictable result ordering with ORDER BY. This is not a bug; it is an inherent consequence of the fact that SQL does not promise to deliver the results of a query in any particular order unless ORDER BY is used to constrain the order.

The rows skipped by an OFFSET clause still have to be computed inside the server; therefore a large OFFSET might be inefficient.

**Comment by qmdx** [comment]
希望 pull request 这边会审核合并 ，参考 https://github.com/baomidou/mybatis-plus/pull/1550/files

**Comment by yfdxzy2010** [comment]
我本地建了分支，怎么提交到远程分支

**Comment by qmdx** [comment]
> 我本地建了分支，怎么提交到远程分支

https://www.jianshu.com/p/a31a888ac46b

**Comment by yfdxzy2010** [comment]
已pull request，谢谢

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/pull/3423
