### ISSUE TITLE
分页查询从第2页开始就存在查询的数据被累加

### ISSUE THREAD

**Issue by htring1314** [baomidou/mybatis-plus#3355]
### 当前使用版本(必填,否则不予处理)
* 3.3.2

### 重现步骤(如果有就写完整)
==>  Preparing: SELECT DISTINCT dd.*, dpd.COMPANY_ID, (SELECT COUNT( ddl.ID ) FROM dev_device_link ddl LEFT JOIN dev_device ddd ON ddd.ID = ddl.LINK_ID WHERE ddd.DELETED = '0' AND ddl.DEVICE_ID = dd.ID) AS LINK_NUM FROM dev_device dd LEFT JOIN dev_project_device dpd ON dpd.DEVICE_ID = dd.ID WHERE dd.DELETED = '0' AND dpd.PROJECT_NO = ? AND dpd.COMPANY_ID IN ('09ac59ad05dee775ec3b7353635d51bc','a4018cb5695d475c71c42d53c34a2585','a390ae0480d89c9c9a1151b53e037360','e853d36e96feafb47e6d5edc88d300f6','245301651e6a39f5434ccdbbac1f6570','ef35251870f293cd57441f4ed9f87951','d828247b7eba0153aa50c6ebdfb7a6bd','10e9207a39011e6369cbfe903a60d2a6','25313b1a70b780d2342ea7083dddf831','56bf8cebe18c16c0cc1d33466fad538b','9469f14dba887fc66ea25e51ce59392d','ba4afc3eae9f5e0de810d9777eefd985','c86f4ee61de30bddcfabef79aea87898','ff912e5391d702d331afc08e050a63e4','5b10b3a0c5b709d5fff5e53c78c9cc2e','b011979e4bd8391ed838d5fdca1890df','51908259797113e361c44419faa362e4','80cf7c7433b3dd5dc357a5ff98128ff6','d3e18794a654e4ca0138e164adc39172','f3e83dedf11537a4f35e1cbc4fffbb82','c76826df2a0222d658ecded06a16467a','5098ea2a3535939eeeac669d1621f003','961545ff25d907989461c23925aa7f94','5cfba001852244dba9c34b5a1d91db16') AND dd.type = 'video' ORDER BY dd.CREATE_TIME DESC LIMIT ?,? 
==> Parameters: BJSX001(String), 16(Long), 8(Long)

却返回了23条数据：

……
5e35dc02e22448dca9c3436326956d41, 项目管理员, 1, null, null, null, , 1, null, , , <<BLOB>>, null, , , 961545ff25d907989461c23925aa7f94, 0
<==        Row: 5bf754fc7e9b301a936f29fb8c08c2ee, 曾经大消防的抖肩, 11111111111111111111, 软件园三期B区14栋5楼展厅, null, null, video, 1, , , http://192.168.25.237:7370/ff_user/AlarmVideo/2020/02/13/dj03_03.mp4, null, 1, 0, 2020-01-15 17:25:57, 5e35dc02e22448dca9c3436326956d41, 项目管理员, 2021-02-23 18:28:45, 5e35dc02e22448dca9c3436326956d41, 项目管理员, 1, null, null, null, null, 1, null, , , <<BLOB>>, null, , , ba4afc3eae9f5e0de810d9777eefd985, 0
<==      Total: 23

按照语句应该是只有最多8条记录。

但是数据库里直接执行该sql则是正常的7条数据：
![2021-02-26_114450](https://user-images.githubusercontent.com/48041177/109252357-4b29fd00-7828-11eb-8c22-3e119702edfc.gif)

**Comment by miemieYaho** [comment]
自行排查
