### ISSUE TITLE
saveOrUpdateBatch的里面的更新只能更新非null的字段，为null的更新不了

### ISSUE THREAD

**Issue by ylh23y** [baomidou/mybatis-plus#3361]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

saveOrUpdateBatch的里面的更新只能更新非null的字段，为null的更新不了，有些情况需要覆盖更新，希望可以进行配置，支持覆盖更新，为null的字段也可以更新

**Comment by qmdx** [comment]
自定义 sql 或者自定义注入 https://baomidou.com/guide/crud-interface.html#alwaysupdatesomecolumnbyid 更新部分字段功能

**Comment by ylh23y** [comment]
int alwaysUpdateSomeColumnById(T entity);这个方法批量更新也可以自定义吗
