### ISSUE TITLE
Quarkus 支持

### ISSUE THREAD

**Issue by JimmyLvZP** [baomidou/mybatis-plus#3369]
大佬 将来是否会添加 Quarkus 支持

**Comment by miemieYaho** [comment]
非主流数据库就提pr

**Comment by JimmyLvZP** [comment]
> 非主流数据库就提pr

呃 大佬 或许过几个月 你就会了解 Quarkus

**Comment by mjiuming** [comment]
> 非主流数据库就提pr

额，大佬大佬，Quarkus是非主流数据库，学废了

**Comment by zohar-soul** [comment]
> 非主流数据库就提pr

quarkus 不是数据库, 是java云原生的一种
