### ISSUE TITLE
希望在queryWrapper里面提供unSelect字段支持（不查指定字段 ，剩下都要）

### ISSUE THREAD

**Issue by daselang** [baomidou/mybatis-plus#3376]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

不只是3.4.2，在现有的所有版本，在queryWrapper或者lambda queryWrapper里面，提供了select具体字段的支持，不写则是select * 所有字段 ，但是没有叫unSelect支持，即指定排除查询某一个或多个字段，剩下的我都要的功能。有时候为了排除不查询某一个大内容字段但是得把其他字段写一遍，太多也不方便，字段增减了sql也不自动变化。希望早日上线，与现有queryWrapper功能也不冲突。

### 重现步骤(如果有就写完整)

无

### 报错信息

无

**Comment by miemieYaho** [comment]
用 select(Class<T> entityClass, Predicate<TableFieldInfo> predicate)

**Comment by zheng2k16** [comment]
还是希望在querywrapper的接口上加入
excludeColumns（string ...col）
