### ISSUE TITLE
globalConfig.setXmlName()不生效

### ISSUE THREAD

**Issue by htwdjqr** [baomidou/mybatis-plus#3379]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator 3.4.1版本

### 重现步骤(如果有就写完整)

全局配置设值了Mapper.xml的命名方式，但是缺没有生效。
GlobalConfig gc = new GlobalConfig();
gc.setXmlName("%sDao"); 
期待生成的效果：UserDao.xml，实际生成的效果：UserEntityMapper.xml

### 报错信息
无

**Comment by huayanYu** [comment]
你的表是不是就是UserEntity
