### ISSUE TITLE
想做关联查询

### ISSUE THREAD

**Issue by qinxiang01** [baomidou/mybatis-plus#338]
# 需求简述
想要在查询时做关联查询，但是动态条件过多，想就在代码里面做关联查询，不知道是否能支持？
# 解决分析
我有在andNew方法中强行写入sql语句做子查询，功能可以实现，但是有没有更好的方法呢？

**Comment by qmdx** [comment]
推荐使用  xml 方式处理关联逻辑， vo  or resultMap 方式解决
