### ISSUE TITLE
Teradata 数据库，无法使用API生成的SQL查询映射到实体类

### ISSUE THREAD

**Issue by liwei125** [baomidou/mybatis-plus#3383]
### 当前使用版本(必填,否则不予处理)
compile("com.baomidou:mybatis-plus-boot-starter:3.4.2")

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
连接使用的是Teradata数据库
当数据库表中的字段设置了TITLE，且TITLE不等于字段名，如：
CREATE SET TABLE DB_AA.TEST_TABLE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      ID BIGINT NOT NULL,
      CNAME VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC TITLE '中文名'
     )
UNIQUE PRIMARY INDEX ( ID );

此时JDBC（mybatis-plus）查询出的列名分别为： ID， 中文名。 
实体类中， ID字段可以映射到值，CNAME则因为是“中文名”而无法映射到值。

因为业务上要求所有字段名都需要设置TITLE，所以我不得不重构所有的查询代码；
需要在XML上写SQL语句，并且即使原本这样写：SELECT　ID，CANME　FROM TEST_TABLE 
也必须要重构成： SELECT　ID AS ID，CANME AS CNAME  FROM TEST_TABLE 

### 重现步骤(如果有就写完整)
1. 整合连接TERADATA
2. 建表，并给字段名设置TITLE，有的字段不设置作为对比
3. 使用QueryWrapper查询，查看实体类取值

### 报错信息
无

**Comment by miemieYaho** [comment]
不支持
