### ISSUE TITLE
mapper与原有的mybatis多数据源冲突， required a single bean, but 23 were found，defined by method 'sqlSessionFactoryBean'   

### ISSUE THREAD

**Issue by ZY1014** [baomidou/mybatis-plus#3387]
### 当前使用版本(必填,否则不予处理)
springBoot v2.7.3  mp: v3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目之前使用的mybaitis，并且按包名的方式配置多数据源，按照流程引入plus后启动报错DataSource与之前的多数据源冲突

其中一个数据源：
![image](https://user-images.githubusercontent.com/34773548/111246675-abe77100-8641-11eb-91ac-9c8f1f53d1a3.png)
mpjavaConfig:
![image](https://user-images.githubusercontent.com/34773548/111246722-c0c40480-8641-11eb-9b4f-a9b22da42296.png)
mapper:
![image](https://user-images.githubusercontent.com/34773548/111246945-26b08c00-8642-11eb-9f4c-40f87a2a6b91.png)

### 报错信息

![image](https://user-images.githubusercontent.com/34773548/111246783-da654c00-8641-11eb-8e8e-4a4bde6a5c62.png)

**Comment by miemieYaho** [comment]
给出你的复现demo,以git形式

**Comment by huayanYu** [comment]
告诉你了指定一个primary或者 每个用@Qualifier指定好具体名称
