### ISSUE TITLE
SqlRunner selectPage 方法未释放连接

### ISSUE THREAD

**Issue by rollstones** [baomidou/mybatis-plus#3390]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
SqlRunner selectPage 方法未释放连接

    @Override
    public <E extends IPage<Map<String, Object>>> E selectPage(E page, String sql, Object... args) {
        if (null == page) {
            return null;
        }
        page.setRecords(sqlSession().selectList(SELECT_LIST, sqlMap(sql, page, args)));
        return page;
    }

### 重现步骤(如果有就写完整)
调用此方法达到连接池配置数量后，报错获取不到连接

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/6b893455eef5e89c935f3d8a82fe2f87bea1164e
