### ISSUE TITLE
having方法不支持or条件

### ISSUE THREAD

**Issue by totoro52** [baomidou/mybatis-plus#3393]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用了QueryWrapper中的having方法拼接了条件，但是我的条件是多条or条件，我在其having() 跟随一个or方法后不起效，一样变成了and

**Comment by miemieYaho** [comment]
不支持

**Comment by totoro52** [comment]
以后版本会支持吗，我这边追踪了代码 or只会追加到where中 确实是不支持

**Comment by miemieYaho** [comment]
也不会
