### ISSUE TITLE
ServiceImpl中mapperClass类型问题

### ISSUE THREAD

**Issue by olditer** [baomidou/mybatis-plus#3397]
### 当前使用版本(必填,否则不予处理)
3.4.1、3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

com.baomidou.mybatisplus.extension.service.impl.ServiceImpl中的currentMapperClass方法，返回的应该是
Class<BaseMapper< T >>类型吧，请确认一下

```
    protected Class<T> currentMapperClass() {
        return (Class<T>) ReflectionKit.getSuperClassGenericType(getClass(), 0);
    }
```

**Comment by beichenhpy** [comment]
我感觉也有点怪，调用的方法，最后返回的泛型是第一个的，也就是BaseMapper的协变泛型。。这里应该用 `Class<M>`我感觉。。但是返回的结果又是对的。。

**Comment by kkzxm** [comment]
ServiceImpl在源码中用的是set注入，如果把它改成构造函数注入：就像：[这样](https://github.com/kkzxm/LingDreamRoot/blob/master/src/main/java/com/lingDream/root/service/MyService.java)，而实际的子类，就是：[这样](https://github.com/kkzxm/llfEnglish/blob/master/type/src/main/java/com/lingDream/llfEnglish/service/WordTypeService.java)
需要多写

一个构造函数。

**Comment by qmdx** [comment]
不明所以，请给出问题详细描述，错误，期望
