### ISSUE TITLE
TableNameParser解析表名有误

### ISSUE THREAD

**Issue by fangqj** [baomidou/mybatis-plus#3398]
### 当前使用版本(必填,否则不予处理)
3.2.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用表名替换
mysql：delete rslt from montrulerslt rslt, montrulerslt_task_temp
DynamicTableNameParser.parser
(new TableNameParser(sql)).tables()
解析出的table 为  rslt

**Comment by qmdx** [comment]
问题描述不够准确，无法处理
