### ISSUE TITLE
如果表中存在名为sequence的字段，使用page进行分页查询会提示异常

### ISSUE THREAD

**Issue by Kuidaxia** [baomidou/mybatis-plus#3399]
### 当前使用版本(必填,否则不予处理)

mybatis_plus version 3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用IService.java中的page方法进行分页查询
![image](https://user-images.githubusercontent.com/39208351/111963597-aa7ce380-8b2e-11eb-934b-efe35c20cd41.png)
调用示例
![image](https://user-images.githubusercontent.com/39208351/111963823-edd75200-8b2e-11eb-98d8-1fa41b7f7efe.png)
如果在mysql的表中存在名为sequence的字段则会有如下异常信息提示
![image](https://user-images.githubusercontent.com/39208351/111964268-63dbb900-8b2f-11eb-9228-e21255ec7cb5.png)
如果我将表对应实体（entity）中的sequence字段注释掉则不会在报上述异常信息

**Comment by miemieYaho** [comment]
去找 jsqlparser

**Comment by Kuidaxia** [comment]
说实话，不是很明白，这个我也没有自己写sql，按理说这个sql的解析应该是mybatis plus完成的啊，这个jsqlparser应该也是通过mp引入的，这个我有办法进行更改吗，找了很久，我也没找到，也确实不知道该怎么找，望解惑
