### ISSUE TITLE
根据经纬度计算距离，如何结合使用Wrapper

### ISSUE THREAD

**Issue by ohmygodlin** [baomidou/mybatis-plus#340]
需求：有一个商家表：
{
  int id
  double lng
  double lat
  int name
  date create_time
}
现在希望通过传入当前经纬度，与表中已有的经纬度计算距离：
SELECT    
id, name,lng,lat, create_time
(st_distance (point (lng, lat),point(input_lng,input_lat) ) / 0.0111) AS distance    
FROM    
shop
where name like %input_name%, create_time between input_start and input_end (可以通过Wrapper实现)
ORDER BY distance  
问题的根源似乎是：有一个自定义的字段distance需要通过mysql特定的函数（st_distance和point）计算得到，并且需要结合Wrapper的like和between，然后对这个自定义字段排序，再分页。
请问通过Mybatis-plus应该如何实现？谢谢。

**Comment by qmdx** [comment]
请 xml 中写
