### ISSUE TITLE
Question: How to mock (simulate) data access layer for unit testing for Model<> Active Record ?

### ISSUE THREAD

**Issue by paulvi** [baomidou/mybatis-plus#3400]
In codebase where model classes use

> public class SomeDomainClass extends Model<SomeDomainClass> {

How to mock (simulate) data access layer for unit testing?

### 当前使用版本(必填,否则不予处理)

`com.baomidou:mybatis-plus-extension:3.4.1`

### 报错信息

---
Asked on https://stackoverflow.com/questions/66756355/question-how-to-mock-simulate-data-access-layer-for-unit-testing-for-model

**Comment by qmdx** [comment]
Junit 吧 mock 没空去研究了

**Comment by paulvi** [comment]
Please keep this issue open until answered/solved.
