### ISSUE TITLE
3.4.1版本分页count时自动优化会截断sql

### ISSUE THREAD

**Issue by zsh19950418** [baomidou/mybatis-plus#3401]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页查询时，count会自动截取sql，3.4.0版本不会

### 重现步骤(如果有就写完整)
分页查询，有left join的时候会把left join后的语句截取掉

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/3363
