### ISSUE TITLE
association关联实体 分页数量对不上

### ISSUE THREAD

**Issue by wsdl-king** [baomidou/mybatis-plus#3402]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当我进行分页查询的时候 使用 <resultMap> ，并且其中有association关联一个实体，自定一个一个sql进行查询的时候，进行分页查询出来的count  total 都是对的 但是分页的list是对不上的。

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/37235056/112248750-6d7d3200-8c91-11eb-80c0-5b6f38c26fdb.png)

![image](https://user-images.githubusercontent.com/37235056/112248722-60f8d980-8c91-11eb-86ad-6385016fcf90.png)

![image](https://user-images.githubusercontent.com/37235056/112248801-871e7980-8c91-11eb-8807-e21d1966f160.png)

### 报错信息

。

**Comment by miemieYaho** [comment]
mybatis给你去重了
