### ISSUE TITLE
JsqlParserCountOptimize 开启 count 的 join 优化的疑问

### ISSUE THREAD

**Issue by summer9989** [baomidou/mybatis-plus#3404]
当前使用版本(必须填写清楚，否则不予处理)
3.3.1

该问题是怎么引起的？(最新版上已修复的会直接close掉)
请问如下语句中，为什么出现group by就不去除orderBy？

// 添加包含groupBy 不去除orderBy
            if (null == groupBy && CollectionUtils.isNotEmpty(orderBy)) {
                plainSelect.setOrderByElements(null);
                sqlInfo.setOrderBy(false);
            }
能否举例什么情况下去除orderBy会出错？比如下列的语句优化好像没啥问题？
select count(1) from (select name,count(1) from user GROUP BY name order by age desc, update_time desc)a 优化后为
select count(1) from (select name,count(1) from user GROUP BY name )a

重现步骤
报错信息

**Comment by qmdx** [comment]
自动优化不是所有 sql 都能自动处理，所有有开启这个开关，目前自动优化只局限于简单 sql 复杂 的暂未支持而已不是有问题

**Comment by summer9989** [comment]
我详细读过源码，清楚该类里面的逻辑。

主要是想问下这一个if是当初遇到什么案例，特地加上的？谢谢

**Comment by qmdx** [comment]
group by 对应复杂统计 sql 情况
