### ISSUE TITLE
从3.3.2升级到3.4.1,发现ReflectionKit删除了很多方法

### ISSUE THREAD

**Issue by xswby** [baomidou/mybatis-plus#3405]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
版本升级的问题

### 报错信息

找不到getMethodValue方法

**Comment by huayanYu** [comment]
确实删除了，如有需要可以本地拷贝一下老版本的
