### ISSUE TITLE
关于数据库主键设计的问题，使用雪花算法作为id，返回前端会出现丢失精度的问题

### ISSUE THREAD

**Issue by shanzhaozhen** [baomidou/mybatis-plus#3408]
### 当前使用版本
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用雪花算法作为表的主键ID的时候，保存方式为bigint，java类型为Long，返回到前端是会出现丢失精度的问题，请问这个问题各位是怎么处理的。
如果ID使用varchar方式保存则会降低性能；如果在返回到前端的时候将主键Long类型转换成字符串类型，感觉也行，不过对于前端使用了typescript也是很大的工作量，同时也不严谨。
希望大佬可以分享一下主键的设计方案。

**Comment by miemieYaho** [comment]
看文档

**Comment by chn-yang** [comment]
所以这位兄弟你后来是怎么处理的? 我刚学java, 我怎么看Long类型json返回都会丢精度? 必须转字符串吧

**Comment by kaixinbaba** [comment]
同问。。这个问题怎么处理。。

**Comment by chn-yang** [comment]
这个其实是js的问题，不是mp也不是Java的问题，long类型数据太大js解析不了，你去搜一下js的数字类型只有2的48还是53次方，我忘了，有个最大值，你用jackson的话就写个自定义序列器把超过最大数值的转为字符串返回。完美解决











yang

---原始邮件---
发件人: "Jeff ***@***.***&gt;
发送时间: 2022年1月26日(周三) 中午11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baomidou/mybatis-plus] 关于数据库主键设计的问题，使用雪花算法作为id，返回前端会出现丢失精度的问题 (#3408)




 
同问。。这个问题怎么处理。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
