### ISSUE TITLE
PaginationInterceptor分页查询性能优化，使用伪列查询行数，最好提供异步方法

### ISSUE THREAD

**Issue by TanqiZhou** [baomidou/mybatis-plus#3410]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页查询行总数性能太差，使用了 原SQL 子查询
建议mysql调整为查询 SELECT  '1' as id,以提高性能；增加异步调用方法

**Comment by miemieYaho** [comment]
调整自行重写,异步不会有

**Comment by TanqiZhou** [comment]
好的
