### ISSUE TITLE
saveOrUpdateBatch能不能加一个像开关一样的字段如果为true就可以更新所有字段包括null的

### ISSUE THREAD

**Issue by ylh23y** [baomidou/mybatis-plus#3413]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
saveOrUpdateBatch能不能加一个像开关一样的字段如果为true就可以更新所有字段包括null的，现在为null的字段没有更新，导致数据库里面的对应字段需要被更新为null,但是却没有被更新，还要之前的值，方便使用者调用

**Comment by miemieYaho** [comment]
没有
