### ISSUE TITLE
insert时是否可以支持使用数据库的时间,设置添加时间create_date?

### ISSUE THREAD

**Issue by wangchen223** [baomidou/mybatis-plus#3414]
### 当前使用版本(必填,否则不予处理)
3.3.2

**Comment by wangchen223** [comment]
/**
     * 修改时间
     */
    @TableField(update = "now()")
    private LocalDateTime updateDate;

update可以通过注解的方式支持,insert是否也可以考虑支持?

**Comment by miemieYaho** [comment]
数据库字段给默认值,insert的entity的字段不赋值
