### ISSUE TITLE
springboot和整合3.4.2版本的mybatis-plus-boot-starter启动报错

### ISSUE THREAD

**Issue by wuyongda** [baomidou/mybatis-plus#3415]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.2</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.2版本的mybatis-plus-boot-starter依赖mybatis-3.5.1.jar，该jar包下的org/apache/ibatis/annotations/Select.class类缺少databaseId()函数，该函数到mybatis-3.5.5.jar版本才引入

### 重现步骤(如果有就写完整)
springboot和整合3.4.2版本的mybatis-plus-boot-starter启动报错

### 报错信息
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder$AnnotationWrapper.<init>(MybatisMapperAnnotationBuilder.java:686)

The following method did not exist:

    org.apache.ibatis.annotations.Select.databaseId()Ljava/lang/String;

The method's class, org.apache.ibatis.annotations.Select, is available from the following locations:

    jar:file:/D:/server/maven/repository/org/mybatis/mybatis/3.5.1/mybatis-3.5.1.jar!/org/apache/ibatis/annotations/Select.class

The class hierarchy was loaded from the following locations:

    org.apache.ibatis.annotations.Select: file:/D:/server/maven/repository/org/mybatis/mybatis/3.5.1/mybatis-3.5.1.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.ibatis.annotations.Select

**Comment by wzj2014** [comment]
试过最新的3.4.2、3.4.3、3.4.3.1，都会有这个问题，3.3.0没有问题

**Comment by wzj2014** [comment]
@miemieYaho 我看issue关闭了，请问是如何解决呢？

**Comment by wuyongda** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] springboot和整合3.4.2版本的mybatis-plus-boot-starter启动报错 (#3415)





 
@miemieYaho 我看issue关闭了，请问是如何解决呢？
