### ISSUE TITLE
was not registered for synchronization because synchronization is not active

### ISSUE THREAD

**Issue by TianM** [baomidou/mybatis-plus#3416]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
普通的查询

### 报错信息

Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@23ee2ccf] was not registered for synchronization because synchronization is not active
16:41:56.251 INFO  com.zaxxer.hikari.HikariDataSource 110 getConnection - voicechat - Starting...
16:41:56.793 INFO  com.zaxxer.hikari.HikariDataSource 123 getConnection - voicechat - Start completed.
JDBC Connection [HikariProxyConnection@1716368074 wrapping com.mysql.jdbc.JDBC4Connection@1491cd6c] will not be managed by Spring
==>  Preparing: SELECT room_id,member_uid,title,notice,online_count,room_type,gmt_create,gmt_modify,deleted FROM room
==> Parameters: 
<==    Columns: room_id, member_uid, title, notice, online_count, room_type, gmt_create, gmt_modify, deleted
<==        Row: 17, b1d79057dbeb47d3a4c823eb904e0d53, 老田的房间1, null, 1, 0, 2021-03-06 23:22:17.0, 2021-03-16 21:07:13.0, 1
<==        Row: 18, b1d79057dbeb47d3a4c823eb904e0d53, 老田的房间2, null, 1, 0, 2021-03-06 23:25:36.0, 2021-03-08 10:54:39.0, 1

Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@23ee2ccf]
是必须要加事务吗？

**Comment by huayanYu** [comment]
没加事务mybatis原生底层就是会打印日志啊。 不喜欢日志配置关掉就好了

**Comment by mosicong** [comment]
@huayanYu Mybatis-plus有没有像Mybatis那样可以配置交由容器管理事务？这个和日志打印不是直接关系吧？事务管理问题

> 没加事务mybatis原生底层就是会打印日志啊。 不喜欢日志配置关掉就好了
