### ISSUE TITLE
selectList方法,在使用实体查询和wrapper拼接同时有查询条件时，看源码是用 and 连接起这两部分的

### ISSUE THREAD

**Issue by feihua666** [baomidou/mybatis-plus#3418]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用实体查询和wrapper拼接同时有查询条件时，看源码是用 and 连接起这两部分的

可否将这个 and 让用户去设定

### 重现步骤(如果有就写完整)
源码位置：com.baomidou.mybatisplus.core.injector.AbstractMethod 225行 ，
SqlScriptUtils.convertIf(" AND", String.format("%s and %s", WRAPPER_NONEMPTYOFENTITY, WRAPPER_NONEMPTYOFNORMAL)
                               .....上面的AND..... 

以下是selectList方法的模板，通过debug获得

<script><choose>
<when test="ew != null and ew.sqlFirst != null">
${ew.sqlFirst}
</when>
<otherwise></otherwise>
</choose> SELECT <choose>
<when test="ew != null and ew.sqlSelect != null">
${ew.sqlSelect}
</when>
<otherwise>id,name,use_bool,create_at,create_by,update_at,update_by,version</otherwise>
</choose> FROM common_test 
<if test="ew != null">
<where>
<if test="ew.entity != null">
<if test="ew.entity.id != null">id=#{ew.entity.id}</if>
<if test="ew.entity['name'] != null"> AND name=#{ew.entity.name}</if>
<if test="ew.entity['useBool'] != null"> AND use_bool=#{ew.entity.useBool}</if>
<if test="ew.entity['createAt'] != null"> AND create_at=#{ew.entity.createAt}</if>
<if test="ew.entity['createBy'] != null"> AND create_by=#{ew.entity.createBy}</if>
<if test="ew.entity['updateAt'] != null"> AND update_at=#{ew.entity.updateAt}</if>
<if test="ew.entity['updateBy'] != null"> AND update_by=#{ew.entity.updateBy}</if>
<if test="ew.entity['version'] != null"> AND version=#{ew.entity.version}</if>
</if>
<if test="ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere">
<if test="ew.nonEmptyOfEntity and ew.nonEmptyOfNormal"> AND</if> ${ew.sqlSegment}
</if>
</where>
<if test="ew.sqlSegment != null and ew.sqlSegment != '' and ew.emptyOfWhere">
 ${ew.sqlSegment}
</if>
</if> <choose>
<when test="ew != null and ew.sqlComment != null">
${ew.sqlComment}
</when>
<otherwise></otherwise>
</choose>
</script>

### 报错信息

尚无报错信息，因为自己的使用中可以这两部分需要用OR连接

**Comment by miemieYaho** [comment]
不能
