### ISSUE TITLE
 PostgreSql jsonb类型适配 ::jsonb

### ISSUE THREAD

**Issue by yexuejc** [baomidou/mybatis-plus#342]
问题描述
#{roles, typeHandler=com.yexuejc.guansc.core.mybatis.handler.JsonTypeHandler}::jsonb, 这种带::jsonb的怎么组装

重现步骤
@TableField(el = "roles, typeHandler=com.yexuejc.guansc.core.mybatis.handler.JsonTypeHandler") private List roles;

报错信息
SQL: INSERT INTO consumer ( consumer_id, "mobile", "is_enable", "is_non_expire", "is_non_lock", "nickname", "is_layer", "head", "roles", "pay_pwd" ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
Cause: org.postgresql.util.PSQLException: ERROR: column "roles" is of type jsonb but expression is of type character varying
建议：You will need to rewrite or cast the expression. 位置：232 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "roles" is of type jsonb but expression is of type character varying 建议：You will need to rewrite or cast the expression.

**Comment by qmdx** [comment]
如果解决确定问题欢迎反馈 or pr

**Comment by vlijiantao** [comment]
how to solve it?

**Comment by MohnSnow** [comment]
how to solve it?

**Comment by xhc-code** [comment]
how to solve it?
