### ISSUE TITLE
3.4.2版本全局配置mybatis-plus.global-config.db-config.id-type=auto 依旧使用雪花算法生成主键id，只能使用@TableId(type = IdType.AUTO)才能生效

### ISSUE THREAD

**Issue by syherry** [baomidou/mybatis-plus#3421]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
雪花算法自动生成的id是19位的数字，19位数字数据传到前端之后精度会丢失，造成前端获取的id并不是实际的数据库存的id。

### 重现步骤(如果有就写完整)
springboot项目中配置：
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

原本意思是不想使用默认的雪花算法了，但是这么配置还是没用，依旧是生成了19位数字。
******************现在唯一解决办法就是用注解了，不知道官方大大怎么设计主键生成这块的配置呢？

### 报错信息
逻辑错误，没有报错。

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式

**Comment by syherry** [comment]
> 给出你的复现demo以git形式

这个地方我刚刚又试了一下，项目默认的是NONE,使用雪花算法插入了id，这个时候mysql自增长的id也变成了刚刚插入的那个19位的数字id，修改id-type是auto之后还是从刚才的19位数字+1,truncate表以后从1开始成功了。
这个地方会给人一个假象就是设置auto之后还是生成的19位，以为是没有生效，后面有可能的话在官方文档里加个注意说明吧。
我看到网上不少人有跟我同样的疑问呢。

**Comment by miemieYaho** [comment]
这不属于我们需要进行提醒的东西
