### ISSUE TITLE
加入逻辑删除后，想要获取已经被逻辑删除的数据，只能自定义sql，无法使用基础方法

### ISSUE THREAD

**Issue by itz-Q** [baomidou/mybatis-plus#3422]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.2</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

加入逻辑删除后，使用基础方法无法获取已经被逻辑删除的数据，必须重新定义sql

### 重现步骤(如果有就写完整)
这是以selectList为例，com.baomidou.mybatisplus.core.injector.methods.selectList#injectMappedStatement生成的的动态sql原始模板是
![image](https://user-images.githubusercontent.com/81466348/113482727-7a6b0400-948f-11eb-8f5f-83b409b2a757.png)

我想是不是可以加个开关：ew.ignoreTableLogic（忽视逻辑删除字段）
`
<if test="ew.ignoreTableLogic != true">
    AND deleted='0'
</if>
`
默认关闭，但是允许开发人员手动开启
### 报错信息

加入逻辑删除后，想要获取已经被逻辑删除的数据，只能自定义sql，无法使用基础方法

**Comment by miemieYaho** [comment]
就这样的
