### ISSUE TITLE
分页插件写的分页接口没有过滤逻辑删除字段，需要手动自己添加where条件

### ISSUE THREAD

**Issue by kim709394** [baomidou/mybatis-plus#3426]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

分页插件写的分页接口没有过滤逻辑删除字段，查出来的数据带有逻辑已删除的数据。

**Comment by miemieYaho** [comment]
自己写的sql自己加逻辑删除条件
