### ISSUE TITLE
3.2.0升级到3.4.0

### ISSUE THREAD

**Issue by flyMyDreams** [baomidou/mybatis-plus#3427]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

2个分页方法如何进行升级，意味着我的所有分页方法都要升级，不会还有升级吧

**Comment by huayanYu** [comment]
查看文档分页部分，只是改变下分页的配置方法， 底层不用改
