### ISSUE TITLE
service 直接 调用 removeById 方法时 不会更新 update time 字段

### ISSUE THREAD

**Issue by changdaye** [baomidou/mybatis-plus#3428]
### 当前使用版本(必填,否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.0</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

service 直接 调用 removeById 方法时 不会更新 update time 字段  代码 如下 

---------------------------------------
   boolean updateResult = logProjectApplicationAdvertisingSpaceService.removeById(logProjectApplicationAdvertisingSpaceId);

---------------------------------------
        public class BaseEntity {
        
            @TableField(fill = FieldFill.INSERT_UPDATE)
            private Date updateTime;
        
            @TableField(fill = FieldFill.INSERT)
            private Date createTime;
        
            @TableLogic
            private Integer deleted;
        }

### 报错信息

 无报错

**Comment by miemieYaho** [comment]
看文档
