### ISSUE TITLE
动态列名

### ISSUE THREAD

**Issue by naolz** [baomidou/mybatis-plus#3429]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
该项目没看到如何使用动态列名的介绍

### 重现步骤(如果有就写完整)
我目前的需求是，动态的表名，但是有规则，可以找到，动态的列名，有些基础的列名，例如创建时间，创建人，有些是动态的列名，当然这个需要一个实体类，实体中不能描述列名的情况下，该如何使用CRUD的快捷操作。

### 报错信息
无

**Comment by miemieYaho** [comment]
没有
