### ISSUE TITLE
自定义sql在order by中无法使用convert函数

### ISSUE THREAD

**Issue by Achrou** [baomidou/mybatis-plus#3431]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

当需要在mysql中对中文排序时，order by条件中使用convert函数就会报错。[JSqlParser那边说暂不支持](https://github.com/JSQLParser/JSqlParser/issues/688)，作者这边有没有什么解决方案？

### 重现步骤(如果有就写完整)

SELECT * FROM test ORDER BY CONVERT(user_name USING GBK ) DESC

**Comment by huayanYu** [comment]
暂时没有，底层依赖jsqlParser， 个别的遇到了只有自己写分页了。 有其他办法可以提交PR

**Comment by zhangconan** [comment]
这个问题后面有修复吗？

**Comment by sage417** [comment]
> 这个问题后面有修复吗？

cast(xxx as char character set gbk)

**Comment by kongfanyu06** [comment]
> > 这个问题后面有修复吗？
> 
> cast(xxx as char character set gbk)

实测有效

**Comment by HomeLives** [comment]
> > 这个问题后面有修复吗？
> 
> cast(xxx as char character set gbk)

非常棒

**Comment by chaggle** [comment]
好啊，刚好也遇到了这个问题，感谢大佬
