### ISSUE TITLE
动态表名

### ISSUE THREAD

**Issue by chaoweiyi** [baomidou/mybatis-plus#3432]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

是否可以提供更优雅的动态表名实现，项目里使用ThreadLocal，这种方式不方便维护，今天看到了[Mybatis-Link](https://www.oschina.net/news/137040/mybatis-link-1-0-0-released)，这里实现了动态表名，我想这个需求有很多人遇到，希望能添加，谢谢！

**Comment by huayanYu** [comment]
可以参考贡献PR给我们，非常期待你的参与
