### ISSUE TITLE
表字段交大，查询报错

### ISSUE THREAD

**Issue by zhaojingchun** [baomidou/mybatis-plus#3449]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
表字段内容比较大

### 重现步骤(如果有就写完整)

表字段内容比较大

### 报错信息
Error querying database. Cause: java.sql.SQLSyntaxErrorException: vtgate: http://vtgate-ht63b-produce-g1rsf:15001/: target: sn_platform.0.master, used tablet: ht63b-1600287934 (11.21.238.173): vttablet: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (46666500 vs. 33554432) ### The error may exist in com/jd/solution/dao/mapper/RContainerComponentMapper.java (best guess) ### The error may involve defaultParameterMap ### The error occurred wh

**Comment by huayanYu** [comment]
sql底层报错，上层无法处理。
