### ISSUE TITLE
使用@Select的select * 部分字段映射到数据

### ISSUE THREAD

**Issue by xcmonline** [baomidou/mybatis-plus#3453]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用 Select * 字段只有部分数据能映射。

### 重现步骤(如果有就写完整)
使用
@Select("select a.* from t_docx a where docxCode=#{docxCode} ") 
List<DocxEntity> getList(@Param("docxCode") String docxCode)

### 报错信息

DocxEntity 实体的 主键未映射到数据。其他的字段可以映射到数据。

DocxEntity定义为
    @TableId("docxId")
    private String docxId;
    @TableField("docxCode")
    private String docxCode;

**Comment by aboutZZ** [comment]
数据库请使用标准字段命名规范

**Comment by huayanYu** [comment]
无法复现， 稳定复现可以给一个github的简单demo。
