### ISSUE TITLE
使用@TableField标注的属性名称与数据库字段名不一致时查询返回属性值为null

### ISSUE THREAD

**Issue by Umizhang0910** [baomidou/mybatis-plus#3458]
### 当前使用版本(必填,否则不予处理)

2.1.9

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自己写的SQL查询方法中使用@TableField标注的属性名称与数据库字段列明不一致时查询返回属性值为null
`	@TableField("master_type")
	private Short dealerMaster;`
修改为
`	@TableField("master_type")
	private Short masterType;`
后属性值正常查询返回

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by totoro52** [comment]
2.1.9版本太老了吧，我在新版本没遇到上述问题，建议升级

**Comment by Umizhang0910** [comment]
> 2.1.9版本太老了吧，我在新版本没遇到上述问题，建议升级

也就是说我当前使用的版本是存在这样的问题对吧？什么原因导致的方便描述一下吗

**Comment by huayanYu** [comment]
太老了，无法维护。 @TableField("master_type") 中的应和数据库的名称对应，应该没问题。  检查名称

**Comment by zkh123** [comment]
我使用的3.4.0版本。也是出现这个问题。 很奇怪啊。  到底是什么原因导致的？
