### ISSUE TITLE
wrapper.like()里带%问题

### ISSUE THREAD

**Issue by ansel-peng** [baomidou/mybatis-plus#3459]
### 使用版本

3.4.2

### 问题
使用like()方法里面String 带 % 导致生成语句如下:

![image](https://user-images.githubusercontent.com/78771329/115694080-1d2de880-a393-11eb-813b-a67c2b0f49e1.png)

### 临时解决
![image](https://user-images.githubusercontent.com/78771329/115694384-641bde00-a393-11eb-8435-278d63634fa3.png)

**Comment by huayanYu** [comment]
嗯，自己处理下特殊的吧。
