### ISSUE TITLE
使用mybatis-plus 的generator连接mycat执行模板生成后报mysql语法错误

### ISSUE THREAD

**Issue by pettyAlways** [baomidou/mybatis-plus#3463]
### 当前使用版本(必填,否则不予处理)

当前的mybatis-plus版本为3.4.2，mybatis-plus generator 版本为v3.4.0。mycat使用mysql-connector-java的驱动版本为5.1.47

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

mysql集群中使用mycat代理，并使用mybatis-plus generator生成controller等一些列模板代码，连接数据源为mycat的ip和8066端口，在执行过程中框架抛出sql语法错误，具体引发的sql语句为show table status  WHERE 1=1  AND NAME IN ('account')。如果加上from cluster则可以执行，完整命令为：show table status from cluster WHERE 1=1  AND NAME IN ('account')

如果我想使用mycat作为数据源进行代码生成，我还需要做什么才能顺利完成

**Comment by huayanYu** [comment]
有点复杂，生成器独立维护了。 你这种只能自己扩展了
