### ISSUE TITLE
spring-boot 1.3.3版本集成mybaits-plus 3.1.0错误

### ISSUE THREAD

**Issue by aladingDenson** [baomidou/mybatis-plus#3465]
### 当前使用版本(必填,否则不予处理)
3.1.0版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
spring-boot 1.3.3版本集成mybaits-plus 3.1.0错误

**Comment by huayanYu** [comment]
spirngboot版本过于老了，无法维护。
