### ISSUE TITLE
Lambda系列Wrapper的疑问

### ISSUE THREAD

**Issue by zezuu** [baomidou/mybatis-plus#3467]
### 当前使用版本(必填,否则不予处理)
v3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
业务原因， 需要对已经生成的Wrapper二次加工处理，统一在某一个地方添加排序、筛选条件字段等
现业务已经传递过来了排序规则、筛选条件字段及表达式、值等， 需要把这些信息加到现有的wapper中

问题：Lambda系列Wrapper 的条件构造器的 R 表示的是SFunction， 而当下我的筛选字段为字符串， 不能直接把字符串类型的字段加到Lambda系列wapper中去，请问有何办法处理这个问题， 手动创建 SFunction 在 MP里面重写的SerializedLambda类中不能通过（不是合成类）

可否能在 Lambda系列的Wrapper中 添加返回一个 非Lambda的wapper的方法？

望指教~

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by huayanYu** [comment]
暂时没有， 可以不使用Lambda的Wrapper   ，用普通的QueryWrapper

**Comment by zezuu** [comment]
这？QueryWrapper当然可以， 就是因为是底层逻辑， 需要兼容Lambda的Wrapper 才提出的

**Comment by huayanYu** [comment]
@zezuu 兼容不了，LambdaWrapper就是设计以字段Lambda，不使用字符串设计的

**Comment by zezuu** [comment]
好的  thx~
