### ISSUE TITLE
自定义sql文件里 mysql里面的字段是JSON格式，读取为null

### ISSUE THREAD

**Issue by shijieahi** [baomidou/mybatis-plus#3471]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 重现步骤(如果有就写完整)
自定义sql文件里 mysql里面的字段是JSON格式，xml里面resultType 是java对象，对象里面的字段是JSONObject 格式，读取的时候这个字段为null。

**Comment by liubinylx** [comment]
反正作者默认使用者都是大神，这么垃圾的项目也不知道是怎么被吹起来的
