### ISSUE TITLE
SQL内部一对多使用 <collection> 导致分页出现错误

### ISSUE THREAD

**Issue by yanzhisishui** [baomidou/mybatis-plus#3474]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
SQL内部一对多使用 <collection> 导致分页出现错误

### 报错信息
无报错，只是它把collection集合里面的数据也算作分页数据，比如1个订单50个订单商品，当查询前10页时，都是这一个订单的数据，但是理想结果应该是当前这个订单只算作一条数据。

**Comment by yanzhisishui** [comment]
1个订单50个订单商品，1对50，以一页10条数据，查第二页应该是第6个订单，但是现在第二页还是第一个订单，

**Comment by yanzhisishui** [comment]
请帮忙指点一下

**Comment by huayanYu** [comment]
- -，你返回的是订单商品啊， 当然了。   想不通就用自己原生手写分页试一试。

**Comment by yanzhisishui** [comment]
不是啊，我返回的是订单啊，订单里面有个orderProductList属性啊，




按道理说，分页应该以订单为准，而不是应该以订单商品的数据条目为准啊






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 下午3:21
***@***.***&gt;;
抄送:&nbsp;"Never Part ***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] SQL内部一对多使用 <collection&gt; 导致分页出现错误 (#3474)





  
-，你返回的是订单商品啊， 当然了。   想不通就用自己原生手写分页试一试。

**Comment by huayanYu** [comment]
来给个复现的最小化demo吧。~

**Comment by yanzhisishui** [comment]
不用复现，任何业务，你只要用 collection标签就有问题，这应该是 MyBatis 的问题，只要你用 collection标签去映射，就会出现问题，不知道为什么官方一直不修复，mybatis官方找不到反馈的地方，所以来plus试试，它其他没问题，数据也能映射进去，唯一的问题就是分页的时候把子集合数目算在了分页数据总数。
这样就会导致分页出问题，网上给出一个办法就是用 group_concat 去连接，，，然后拼接JSON 去在实体类映射成对象集合




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 下午3:26
***@***.***&gt;;
抄送:&nbsp;"Never Part ***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] SQL内部一对多使用 <collection&gt; 导致分页出现错误 (#3474)





 
来给个复现的最小化demo吧。~
