### ISSUE TITLE
文档自定义SQL里面有一句 不支持 Wrapper 内的entity生成where语句 这个是什么意思呢？

### ISSUE THREAD

**Issue by oxcz** [baomidou/mybatis-plus#3477]

**Comment by qmdx** [comment]
自定义sql使用 wrapper 时候，实体不参与 sql 生成，mp 内置的 sql 除外

**Comment by oxcz** [comment]
> 自定义sql使用 wrapper 时候，实体不参与 sql 生成，mp 内置的 sql 除外

是直接set一个实体这种用法的情况下吗？

**Comment by vichen2021** [comment]
@Override
    public IPage<DishVO> dishPage(DishPageQueryDTO dishPageQueryDTO)
    {
        return dishMapper.selectPageVo(
                new Page<>(dishPageQueryDTO.getPage(), dishPageQueryDTO.getPageSize()),
                            new LambdaQueryWrapper<DishVO>()
                                .like(StringUtils.isNotEmpty(dishPageQueryDTO.getName()),DishVO::getName,dishPageQueryDTO.getName())
                                .eq(dishPageQueryDTO.getStatus()!= null,DishVO::getStatus,dishPageQueryDTO.getStatus())
                                .eq(dishPageQueryDTO.getCategoryId()!= null,DishVO::getCategoryId,dishPageQueryDTO.getCategoryId())
                                    .orderByDesc(DishVO::getUpdateTime) //  更新时间降序排列
                            );
    }

``` 
这样是否可行
