### ISSUE TITLE
通过反射在运行时动态修改Field上的TableId的type没有效果

### ISSUE THREAD

**Issue by sss768** [baomidou/mybatis-plus#348]
我在分布式环境中，主服务器A的一个表想自增插入，其他分布式服务器B想插入的时候指定主键ID的值。又想所有的项目都用一套公用的实体。于是在注解上写的是IdType.Input。
	@TableId(value="ID", type= IdType.INPUT)
	private Integer ID;

想通过如下代码在运行时进行TableId的IdType修改，下面的代码已经起作用了，但是MyBatisPlus在生成sql的时候依然按照之前的注解来做的，并没有生效。请问有什么办法可以实现我的需求
 CooperateIns cooper = new CooperateIns();
        Field field = cooper.getClass().getDeclaredField("ID");
        TableId tableId = field.getAnnotation(TableId.class);
        //获取 foo 这个代理实例所持有的 InvocationHandler
        InvocationHandler h = Proxy.getInvocationHandler(tableId);
        // 获取 AnnotationInvocationHandler 的 memberValues 字段
        Field hField = h.getClass().getDeclaredField("memberValues");
        // 因为这个字段事 private final 修饰，所以要打开权限
        hField.setAccessible(true);
        // 获取 memberValues
        Map memberValues = (Map) hField.get(h);
        // 修改 value 属性值
        memberValues.put("type", "AUTO");
        // 获取 foo 的 value 属性值
        String value = tableId.value();
        System.out.println(value); // ddd

        cooper.setName("haha");

        cooper.insert();

**Comment by qmdx** [comment]
子类可以重写父类的 id 属性 即 注解可以被子类覆盖重写
