### ISSUE TITLE
使用DataPermissionInterceptor 时候 union all会导致报错

### ISSUE THREAD

**Issue by larry-ct** [baomidou/mybatis-plus#3482]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用DataPermissionInterceptor 时候 union all会导致报错

### 重现步骤(如果有就写完整)

使用union all 两个都有where 条件导致 使用InterceptorIgnore也忽略不了

### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

**Comment by larry-ct** [comment]
![image](https://user-images.githubusercontent.com/40970099/116663801-2db11500-a9ca-11eb-95ce-9a7903dd8372.png)
这里强转报错的

**Comment by larry-ct** [comment]
查看plainselect  需要使用
![image](https://user-images.githubusercontent.com/40970099/116665092-e6c41f00-a9cb-11eb-8b31-e0066c179fca.png)
来做list 并添加

**Comment by qmdx** [comment]
ok https://github.com/baomidou/mybatis-plus/commit/3bf38132b4a46f9e8386fe45eace0b054b5fb4c9
