### ISSUE TITLE
分页查询pages属性为null，在freemarker中接收不到

### ISSUE THREAD

**Issue by foxfire881** [baomidou/mybatis-plus#3484]
### 当前使用版本(必填,否则不予处理)
3.4.1、3.4.2都试了，全部报错。
之前在gitee上看到有人说是jdk 1.8的问题，但是我升级了jdk11仍然报错。

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
MybatisPlus在返回IPage对象给freemark时，pages属性为空异常报错。（其他属性都正常）

### 重现步骤(如果有就写完整)
Controller中：

Page<Item> page= new Page<>(pagenum, pageSize,true);
IPage<Item> ipage = mapperItem.search(page,condition);
long x = ipage.getPages();   //这里getPages()函数可以正常获取到页面总数；
map.addAttribute("ipage",ipage); 压入map返回给freemarker模板

Freemark模板：
${ipage.total}   //正常获取
${ipage.current} //正常获取
${ipage.size} //正常获取
${ipage.pages}  //异常，报空值
${ipage.getPages()} //异常，报没有这个方法
 

### 报错信息
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> ipage.pages

### 诉求
大佬~~赶紧升级发布一个新版修复bug吧，急啊

**Comment by qmdx** [comment]
不应该出现 null 啊，请检查后重新提交 issue 近期会发版更新
```
    /**
     * 当前分页总页数
     */
    default long getPages() {
        if (getSize() == 0) {
            return 0L;
        }
        long pages = getTotal() / getSize();
        if (getTotal() % getSize() != 0) {
            pages++;
        }
        return pages;
    }
```
