### ISSUE TITLE
使用 mybatis-plus 和 shardingjdbc5.0.0 或 4.1.1 会出现问题。使用 mybatis 没有问题

### ISSUE THREAD

**Issue by wangkang09** [baomidou/mybatis-plus#3486]
### 当前使用版本(必填,否则不予处理)
mybatis-plus: 3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用 mybatis-plus 和 shardingjdbc  生成 sql 时，字段顺序会乱。

这是我的测试项目：https://github.com/wangkang09/sharding-test.git
这是我的问题链接：https://github.com/apache/shardingsphere/issues/10105

**Comment by wangkang09** [comment]
https://github.com/wangkang09/sharding-test.git  的 mybatis-test 分支使用的 mybatis，没有问题

**Comment by qmdx** [comment]
如果是为了解决多数据源问题，推荐  https://github.com/baomidou/dynamic-datasource-spring-boot-starter 暂无支持 shardingjdbc 打算

**Comment by wangkang09** [comment]
dynamic-datasource-spring-boot-starter 不支持分库分表后的数据聚合功能，，
