### ISSUE TITLE
updateStrategy属性的缺陷

### ISSUE THREAD

**Issue by xuluoluo** [baomidou/mybatis-plus#3487]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
@TableField(updateStrategy = FieldStrategy.IGNORED)
该注解是注解为PO的属性上的特性
无法指定某个方法不执行置空操作，某个方法执行置空操作

**Comment by qmdx** [comment]
请使用 updateWrapper 注解是放方向控制，不支持方法级别粒度控制

**Comment by xuluoluo** [comment]
有类似通用update的支持方法级别粒度控制的功能吗？

**Comment by qmdx** [comment]
> 有类似通用update的支持方法级别粒度控制的功能吗？

https://baomidou.com/guide/crud-interface.html#alwaysupdatesomecolumnbyid

这个方法解决更新空问题的你看看

**Comment by xuluoluo** [comment]
这个方法是使用TableFieldInfo中的某些属性进行判定该字段是否要update，但是这个也是启动时解析存入getMethodList中的List，无法做到删除该【@TableField(updateStrategy = FieldStrategy.IGNORED)】的效果。
