### ISSUE TITLE
【功能建议】是否可以增加动态更新mybatis-plus配置的功能？

### ISSUE THREAD

**Issue by Costriod** [baomidou/mybatis-plus#3493]
配合spring cloud + apollo配置中心一起使用，程序启动之后，本来想动态更新mybatis-plus的配置，但是发现apollo的配置更新了之后，mybatis-plus里面的配置没有自动更新

**Comment by qmdx** [comment]
mp 原理启动加载配置无运行时损耗，不支持动态需求
