### ISSUE TITLE
MetaObjectHandler 不生效

### ISSUE THREAD

**Issue by wangjia2016** [baomidou/mybatis-plus#3494]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
insertFill updateFill 方法不执行

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/16084076/117395735-183c6d80-af2b-11eb-96b2-2b10a569021a.png)

### 报错信息
1、无报错信息，类可以加载，log.info("MyBatisHandler starter"); 可以打印出来
insertFill updateFill 方法不执行

2、MyBatisHandler 是在web工程里面

dao mapper 是在 service里面 
service通过 dubbo暴露接口给web层调用，web层才能获取登录的用户

**Comment by zhu1147212910** [comment]
我是直接不进入这个handler里面，3.4.1 版本，根本就没有进行字段填充

**Comment by zhu1147212910** [comment]
我的问题，是我的 idea编译器 不自动编译程序，导致加了填充注解不生效

**Comment by qmdx** [comment]
up

**Comment by wangjia2016** [comment]
> 你的 Web 层依赖在上，而 MP 是作用在 DAO 层的，无法取到你 Web 层的 Handler，建议你将 MyBatisHandler 抽离到 common 包或者 infrastructure 包，由 dao 层引入。 至于你说的 web 层才能获取登录用户，建议自己维护一个上下文，用 ThreadLocal 存储一份用户信息。

最终自己写了个切面，调用接口的时候 手动给字段赋值了
