### ISSUE TITLE
使用JacksonTypeHandler序列化可以保存为json字符串，但是回显数据则是LinkedHashMap数据结构

### ISSUE THREAD

**Issue by veione** [baomidou/mybatis-plus#3500]
### 当前使用版本(必填,否则不予处理)
mybatis-plus v3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
定义了一个Domain类，里面有一个List<XXX>属性，标记了JsonTypeHandler，保存数据可以正常保存json字符串，但是回显数据结构则是LinkedHashMap结构，正常应该返回的是List<XXXX>结构类型。

**Comment by qmdx** [comment]
请自定义实现 AbstractJsonTypeHandler 类处理
