### ISSUE TITLE
jdk 1.7是否使用mybatisplus

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [baomidou/mybatis-plus#3501]
### 该问题是如何引起的？  QueryWrapper 工具没有了？？还是 当前版本不支持jdk1.7

 jdk1.7 支持mybatisplus哪个版本？？？

**Comment by qmdx** [comment]
3.0 一下版本支持  1.7

**Comment by Tuzhiqiang1996** [comment]
好的，谢谢！
