### ISSUE TITLE
分页泛型指定问题

### ISSUE THREAD

**Issue by a852203465** [baomidou/mybatis-plus#3502]
### 当前使用版本(必填,否则不予处理)
版本：mybatis-plus-boot-starter，version: 3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1. 问题：由于分页Page 对象使用时需要指定泛型并且每次使用都需要new，因此对Page对象做工具类封装，出现泛型指定问题
2. 建议：能否将泛型修改为 在new时传入具体对象的Class对象

### 重现步骤(如果有就写完整)
封装实例：
（该方法就无法指定T 的具体对象了）
public static <T> Page<T> basicPage(Long page, Long size, SortDTO dto) {
        page = (page == null || page < 0) ? 1 : page;
        size = (size == null || size <= 0) ? 20 : size;
        Page<T> pageHelper = new Page<T>(page, size, Boolean.TRUE);
        if (DEFAULT_ORDER_TYPE.equals(dto.getOrderType())) {
            pageHelper.addOrder(OrderItem.desc(dto.getOrderField()));
        }else {
            pageHelper.addOrder(OrderItem.asc(dto.getOrderField()));
        }
        return pageHelper;
    }

**Comment by nishimoguima** [comment]
public static <T> Page<T> basicPage(Long page, Long size,Class<T> clazz) {
        page = (page == null || page < 0) ? 1 : page;
        size = (size == null || size <= 0) ? 20 : size;
        Page<T> pageHelper = new Page<T>(page, size, Boolean.TRUE);
        return pageHelper;
    }
你好，可以尝试这样写哦

**Comment by a852203465** [comment]
我知道可以这么写， 但是“clazz”是没法传给Page 对象的，因为你们的设计是Page<T>传入，而不是参数传入



***@***.***
 
发件人： 唐绎
发送时间： 2021-05-15 20:14
收件人： baomidou/mybatis-plus
抄送： a852203465; Author
主题： Re: [baomidou/mybatis-plus] 分页泛型指定问题 (#3502)
public static Page basicPage(Long page, Long size,Class clazz) {
page = (page == null || page < 0) ? 1 : page;
size = (size == null || size <= 0) ? 20 : size;
Page pageHelper = new Page(page, size, Boolean.TRUE);
return pageHelper;
}
你好，可以尝试这样写哦

**Comment by nishimoguima** [comment]
抱歉 代码没有贴全,可以这样传递泛型
public static <T> Page<T> basicPage(Long page, Long size,Class<T> clazz) {
        page = (page == null || page < 0) ? 1 : page;
        size = (size == null || size <= 0) ? 20 : size;
        Page<T> pageHelper = new Page<T>(page, size, Boolean.TRUE);
        return pageHelper;
    }

**Comment by nishimoguima** [comment]
![image](https://user-images.githubusercontent.com/38577454/118361307-6998cc80-b5bd-11eb-8c56-f91630f78afd.png)
