### ISSUE TITLE
MP怎么兼容多数据库？

### ISSUE THREAD

**Issue by lingfenghu** [baomidou/mybatis-plus#3511]
### 当前使用版本(必填,否则不予处理)
3.4.2

###
比如我要同时兼容MYsql和Oracle，Oracle则需要在实体类写@KeySequence 并且使用@TableId(type = IdType.INPUT)，mysql 则直接使用 @TableId(type = IdType.AUTO)这样就好了，当我从mysql切换到oracle，我需要修改实体类这方面的注解，才能保证我使用baseMapper的insert方法才是正确的，有什么技巧可以不用修改实体类吗？

**Comment by qmdx** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter

**Comment by lingfenghu** [comment]
这个有使用示例吗？给个链接也太模糊了吧？
