### ISSUE TITLE
试图通过 注册自动填充插件进行填充主键，但是无法进入   metaObjectHandler的insertFill方法

### ISSUE THREAD

**Issue by touwaeriol** [baomidou/mybatis-plus#3512]
### 当前使用版本(必填,否则不予处理)

3.0.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我将主键注解 设置为type= IdType.INPUT，然后注入自定义的MetaObjectHandler，但是由于所有字段注解的fill属性 都为FieldFill.DEFAULT，在MybatisParameterHandler的insertFill(MetaObject metaObject, TableInfo tableInfo）方法中tableInfo.isWithInsertFill()为false 导致无法进入metaObjectHandler.insertFill(metaObject)

### 重现步骤(如果有就写完整)
将主键注解 设置为type= IdType.INPUT，其他字段注解的fil属性均为默认值，自己注册MetaObjectHandler，在insertFill中填充id，插入数据 id为null。

### 报错信息
无法进入MetaObjectHandler 的insertFill方法

**Comment by qmdx** [comment]
请使用 3.4.1 版本，更多查看 https://gitee.com/baomidou/mybatis-plus-samples
