### ISSUE TITLE
mp-generator 不支持虚谷数据库

### ISSUE THREAD

**Issue by Roger0917** [baomidou/mybatis-plus#3513]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator-3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用Guns后台管理框架，数据库使用xugu，代码生成
![微信图片_20210513143146](https://user-images.githubusercontent.com/21167121/118087344-fdb93700-b3f7-11eb-9a43-2b52e740fa2f.png)
![微信图片_20210513143154](https://user-images.githubusercontent.com/21167121/118087346-ff82fa80-b3f7-11eb-878f-fcb598ec71d9.png)

### 重现步骤(如果有就写完整)
使用Guns作为后台管理系统脚手架，驱动换成xugu jdbc driver，guns使用的是mybatis-plus的代码生成，生成代码时new 一个datasouceConfig设置dbtype为xugu，但dbquery属性仍为MysqlQuery，没有XuguQuery

### 报错信息

下图为虚谷数据库的日志记录
![微信图片_20210513143721](https://user-images.githubusercontent.com/21167121/118088244-56d59a80-b3f9-11eb-8ba2-8bf6f1b15a68.png)
![微信图片_20210513144046](https://user-images.githubusercontent.com/21167121/118088251-589f5e00-b3f9-11eb-860d-ec3826f43ab8.png)

**Comment by qmdx** [comment]
请 PR https://github.com/baomidou/generator
