### ISSUE TITLE
Page对象中数据反序列化问题

### ISSUE THREAD

**Issue by luzhichao** [baomidou/mybatis-plus#3518]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？
Page对象中数据反序列化问题

### 重现步骤(如果有就写完整)
微服务之间调用，服务端返回Page<实体对象>，在客户端中实际接受的的是Page<实体对象>但接收变成了Page<Map>，
类型发生了变化；两个服务中实体对象都实现了Serializable进行了序列化

### 报错信息
java.lang.ClassCastException

**Comment by qmdx** [comment]
请使用版本 `3.4.3.1` 试试
