### ISSUE TITLE
关于填充策略疑问

### ISSUE THREAD

**Issue by tdwu** [baomidou/mybatis-plus#3521]
3.4.2版本中
关于填充策略

查看代码发现，填充策略是table统一，并不是每个字段独立的
 if (metaObjectHandler.openInsertFill() && tableInfo.isWithInsertFill()) {

为什么不把他填充策略配置到table注解中，而是配置在@TableField中？
并且tableInfo的也是根据字段来的

  void setFieldList(List<TableFieldInfo> fieldList) {
        this.fieldList = fieldList;
        AtomicInteger logicDeleted = new AtomicInteger();
        AtomicInteger version = new AtomicInteger();
        fieldList.forEach(i -> {
            if (i.isLogicDelete()) {
                this.withLogicDelete = true;
                this.logicDeleteFieldInfo = i;
                logicDeleted.getAndAdd(1);
            }
            if (i.isWithInsertFill()) {
                this.withInsertFill = true;
            }
            if (i.isWithUpdateFill()) {
                this.withUpdateFill = true;
            }
            if (i.isVersion()) {
                this.withVersion = true;
                this.versionFieldInfo = i;
                version.getAndAdd(1);
            }
        });

**Comment by qmdx** [comment]
table 注解可能存在太臃肿，分开字段更易理解维护
