### ISSUE TITLE
为什么Id不能为基础类型比如long

### ISSUE THREAD

**Issue by tdwu** [baomidou/mybatis-plus#3522]
### 当前使用版本(必填,否则不予处理)
3.4.2

1 为什么Id不能为基础类型比如long。是处于某种考虑吗。

2 另外能否开放Id也可以出发填充策略，当发现没设置时，自动设置。
  如果手工设置过则以手工为准？

**Comment by nishimoguima** [comment]
1、因为包装类型可以为null
2、一般数据库id都只有一种策略
