### ISSUE TITLE
mybatisplis和nacos config整合启动抛出空指针

### ISSUE THREAD

**Issue by ShenJia123** [baomidou/mybatis-plus#3525]
### 当前使用版本(必填,否则不予处理)
mybatis plus 版本是 3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版是有同样的问题

### 重现步骤(如果有就写完整)
启动抛出空指针异常，无法初始化basrMapper

### 报错信息
Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tbGuaranteeDemandMapper' defined in file [D:\Sj\huixin\hbjrpt-golden\hbjrpt-service-mgt\hbhrpt-service\target\classes\com\sgcc\hbjrpt\mapper\TbGuaranteeDemandMapper.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException

**Comment by ShenJia123** [comment]
db配置放到nacos config中就会有这个问题

**Comment by qmdx** [comment]
请给出重现 demo 或者详细错误日志，目前提供信息无法重现

**Comment by ShenJia123** [comment]
> 请给出重现 demo 或者详细错误日志，目前提供信息无法重现

不好意思，问题解决了  是我的问题  配置搞错了
