### ISSUE TITLE
Mybatis-plus能否支持Oracle的模式访问

### ISSUE THREAD

**Issue by abcbuzhiming** [baomidou/mybatis-plus#353]
Oracle下经常会有这种情况，有用户AAA和BBB，BBB下有一堆表，AAA对BBB下的这堆表有访问权限。但是你只有AAA的账号，没有BBB的账号，也就是说你必须在登录AAA账号的情况下去访问BBB模式，在Oracle里select语句必须这么写
select * from BBB.表名;
直接写
select * from 表名;
会告诉你没有这个表，而且这种时候mybatis-plus的代码生成器也是没法用的，因为此时代码生成器能取到的是AAA账号下的表，而不是BBB账号下的表。我找了没有找到mybatis-plus能设定用户模式的地方

**Comment by yuxiaobin** [comment]
可以直接TableName("BBB.tbl_abc")

试一下

**Comment by qmdx** [comment]
如上
