### ISSUE TITLE
开启了逻辑删除后，是否可以动态查询已删除的记录

### ISSUE THREAD

**Issue by Suny95** [baomidou/mybatis-plus#3538]
目前我所知道的好像只有通过写xml的sql才可以查已删除的记录，这块是否可以优化？可以动态的决定某个查询可以查询已删除的记录

**Comment by 986510453** [comment]
你这个应该用一个状态来标识

而不是逻辑删除

删除那么就不应该再看，逻辑删除只是为了恢复和记录。

**Comment by qmdx** [comment]
up
