### ISSUE TITLE
EntityWrapper 支持 多表join

### ISSUE THREAD

**Issue by hongliangpan** [baomidou/mybatis-plus#354]
EntityWrapper 支持 多表join，如：
wrapper .setJoinColumns("a.c_name activeName");
wrapper .setJoinTable("INNER JOIN act_activity a ON t.c_activity_id=a.c_id");
join可以作为过滤条件，或关联查询出字段

**Comment by qmdx** [comment]
多表还是希望在 xml 中搞定，多谢建议

**Comment by GuoDapeng** [comment]
之前用 thinkphp6 写东西，现在用这个，自己拼装 sql 各种不适用，总感觉自己在跑偏
