### ISSUE TITLE
com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler 去哪了？

### ISSUE THREAD

**Issue by workhelper** [baomidou/mybatis-plus#3545]
### 当前使用版本：3.4.3
com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler 这个类还在用吗？
有些第三方代码用到了这个类，但在下载的extension包中未找到这个类。

**Comment by workhelper** [comment]
查了下，这个类在3.3.2版本中还存在，后续版本移除了，更新日志中没看到对移除这个类的说明

**Comment by qmdx** [comment]
插件做了重构，更多查看 com.baomidou.mybatisplus.extension.plugins 包，3.4... 做了过期标记，目前 3.4.3 移除了

**Comment by pkaq** [comment]
> 插件做了重构，更多查看 com.baomidou.mybatisplus.extension.plugins 包，3.4... 做了过期标记，目前 3.4.3 移除了

所以重构哪里去了？

**Comment by icoco** [comment]
居然删除了。。。

有什么简单方法可以获得 完整的sql语句 ？ 

比如 .list(QueryWrapper)   ,   有个场景，需要用 jdbc方式 直接call，复用 mybatis 生成的 sql语句
