### ISSUE TITLE
mybatis plus 多种类型数据源分页不写Dialect查询结果是全量，写死Dialect无法转换数据源

### ISSUE THREAD

**Issue by daofuzhang** [baomidou/mybatis-plus#3546]
### 当前使用版本(必填,否则不予处理)

mybatis-plus 3.4.0
dynamic-datasource:3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
同一个项目使用两种数据源（oracle 和mysql）查询分页，MybatisPlusConfig配置类中mybatisPlusInterceptor不设置数据源类型，会查询全量结果，写死一种数据源类型，另外一种查询生成的sql是前一种的。

### 重现步骤(如果有就写完整)
mybatisPlusInterceptor中：
interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
查询oracle时分页sql会使用limit ；
如果不添加InnerInterceptor，会查询出全量数据.

### 报错信息
使用DbType.MYSQL查询oracle报错,limit 异常; 如果不写DbType ，查询出全量数据.

**Comment by huayanYu** [comment]
gitee已回答
