### ISSUE TITLE
3.4.3版本调用排序方法会出现警告？

### ISSUE THREAD

**Issue by willing555** [baomidou/mybatis-plus#3552]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
升级3.4.3后通过lambda查询调用orderBy、orderByDesc、orderByAsc排序方法会出现警告 Type safety: A generic array of SFunction<CommissionOrder,?> is created for a varargs parameter

### 报错信息
警告信息 Type safety: A generic array of SFunction<CommissionOrder,?> is created for a varargs parameter

**Comment by lzb6666** [comment]
相关排序方法中使用了变长参数到数组的装换，但是使用过程是安全的，不会造成堆污染。并且这个警告似乎并不是在所有java版本都会出现，我这边没有出现。

**Comment by qmdx** [comment]
后续不再提供多个泛型输入的方法，消除该警告
