### ISSUE TITLE
分页查询时当current大于total时查询结果为空

### ISSUE THREAD

**Issue by WeLinkOn** [baomidou/mybatis-plus#3559]
### 当前使用版本
3.4.2

### 该问题是如何引起的？
分页查询时结果有数据但如果current大于total，查询无结果，预期是返回 total 页的数据。

### 重现步骤(如果有就写完整)
假如满足条件的数据共有5条，且page.getSize() 大于5，则 total 为 1，此时如果 page.getCurrent() 大于1，例如为 2，则查询结果为空。是否可以设置成当 current > total 时 current = total，这样就不会出现查询结果中 total 大于 0 而实际的records 却为空的情况。

### 报错信息
无报错信息，查询结果与预期不符。

**Comment by 986510453** [comment]
设置参数overflow=true即可
![image](https://user-images.githubusercontent.com/33100175/119810724-df375d80-bf18-11eb-8e1a-6de66bb15bab.png)
![image](https://user-images.githubusercontent.com/33100175/119810798-f70ee180-bf18-11eb-95f1-85c299100ac3.png)

**Comment by 986510453** [comment]
或者在MybatisPlusInterceptor中设置参数也可
![image](https://user-images.githubusercontent.com/33100175/119811251-7ac8ce00-bf19-11eb-881b-a8a2db36c4ad.png)

**Comment by WeLinkOn** [comment]
第一种方式经测试是可以的：
![image](https://user-images.githubusercontent.com/26466555/119813413-d2683900-bf1b-11eb-981e-ce83cdc319f5.png)

但是第二种貌似没起作用，是不是我用的姿势不对：
![image](https://user-images.githubusercontent.com/26466555/119813234-9c2ab980-bf1b-11eb-8372-4dcffe66efaa.png)

**Comment by 986510453** [comment]
注意看这上面的规则
![image](https://user-images.githubusercontent.com/33100175/119813623-18bd9800-bf1c-11eb-8abc-6efd648a43af.png)
