### ISSUE TITLE
api 内部实现风格不统一

### ISSUE THREAD

**Issue by EzrealOf** [baomidou/mybatis-plus#3562]
### 当前使用版本(必填,否则不予处理)
3.x
master

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
api 内部实现风格不统一

### 重现步骤(如果有就写完整)

UpdateWrapper.set 方法没有调用  columnToString
但是 父类都有调用 columnToString 将列名转一下

![image](https://user-images.githubusercontent.com/16066266/119774655-1136c880-bef5-11eb-8ec9-db55b792fc18.png)

### 报错信息
无

**Comment by nancheung97** [comment]
这个没问题吧，别的地方调用columnToString，是因为column不是String，这个地方column就是String，不需要转
