### ISSUE TITLE
3.4.3版本，list查询方法，参数字段为空字符串，会带到where条件中

### ISSUE THREAD

**Issue by fzon0902** [baomidou/mybatis-plus#3563]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
list查询方法，参数字段为空字符串，会带到where条件中

### 重现步骤(如果有就写完整)
前端传的某个查询条件为''，mybatis-plus的查询语句的where条件中会带上xx=''这个条件，select-strategy: not_empty配置不生效，相关字段加上注解@TableField(whereStrategy = FieldStrategy.NOT_EMPTY)才生效

### 报错信息
未报错

**Comment by nancheung97** [comment]
看了下，这个提交应该已经解决了你这个问题
https://github.com/baomidou/mybatis-plus/commit/35a38fa00795397209ac014931fe9c82254e3094
