### ISSUE TITLE
v3.3.0版本 select的同时count(id)或 group by导致分页失效

### ISSUE THREAD

**Issue by city2012** [baomidou/mybatis-plus#3564]
### 当前使用版本(必填,否则不予处理)
V3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 select的同时count(id)或 group by导致分页失效

### 重现步骤(如果有就写完整)
select
         
            pi.serials_no,
            count(pi.serials_no) quantity,
         
         
        ni.product_title,
        ni.product_type,
        ni.zipped_url
        from product_info pi
        left join product_asset pa on pi.id = pa.product_info_id
        where pa.user_id = ?
        and pi.product_type = ?
        and pa.status = 1
        and pi.is_deleted = 0
        and pa.is_deleted = 0
         
            group by pi.serials_no
            order by pi.serials_no desc LIMIT ?,? ::: [[350957715, 2, 0, 2147483647]]

### 报错信息
我传入的page是1，pagesize是3
给我填充的是0, 2147483647
一般分页可以执行，但凡加入count或group by就填充分页信息错误。

查询结果里面的分页统计信息是正确的但是，结果集是该条件的所有结果集实体，没有做分页

**Comment by 986510453** [comment]
@city2012  最新版是否存在该问题？

**Comment by qmdx** [comment]
3.4.3 测试后有问题再打开
