### ISSUE TITLE
saveOrupdate 保存 主键空 报错

### ISSUE THREAD

**Issue by biubiubiu3971** [baomidou/mybatis-plus#3566]
### 当前使用版本(必填,否则不予处理)
3.3.1
到最新版本也是这个

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
saveorupdate 问题
查询之后，再insert没有把原先的主键带过去。。。导致主键空报错，update没试过。我的主键没有设置填充类型

**Comment by touwaeriol** [comment]
主键没有设置填充类型就不会自动填充，没有主键就插入很明显会报错。

**Comment by biubiubiu3971** [comment]
> 主键没有设置填充类型就不会自动填充，没有主键就插入很明显会报错。

嗯嗯，这个逻辑理解，这个是最简单的保存时候的逻辑，但是saveOrUpdate就不一样了。

我觉得可以优化一下，既然查询那一步的是有主键的，那我填充进去的也就是要保存进去的主键。可以在save和update的时候填充自查询那边的主键

**Comment by biubiubiu3971** [comment]
我这边的修改方案是在id上面设置 input。但是如果本来id需要数据库自增的时候就崩了。还是建议作者可以优化一下
