### ISSUE TITLE
希望提供根据实体类查询获取List或者是Page的API

### ISSUE THREAD

**Issue by moil-xm** [baomidou/mybatis-plus#3567]
### 当前使用版本(必填,否则不予处理)

```
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.4.2</version>
            </dependency>
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

如果需要根据对象查询 以现有的api就得封装Wrapper或者转化为Map,否则就必须自定义这个方法,希望提供一个根据实体类查询，
并且提供null属性处理的boolean的判断

**Comment by 986510453** [comment]
@moil-xm  QueryWrapper提供 setEntity()方法，对于个别字段的where条件策略可以结合@TableField的whereStrategy属性配置

**Comment by 986510453** [comment]
@moil-xm  麻烦测试下是否满足需求，并提供反馈，谢谢

**Comment by moil-xm** [comment]
嗯 ，感谢，可行
