### ISSUE TITLE
使用国产优炫数据库，什么时候支持国产优炫数据库

### ISSUE THREAD

**Issue by iliangdong** [baomidou/mybatis-plus#3570]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用国产优炫数据库，什么时候支持国产优炫数据库

### 重现步骤(如果有就写完整)
使用国产优炫数据库，什么时候支持国产优炫数据库

### 报错信息
使用国产优炫数据库，什么时候支持国产优炫数据库

**Comment by qmdx** [comment]
请参考 https://github.com/baomidou/mybatis-plus/pull/3423/files  然后 PR

**Comment by huayanYu** [comment]
无回复，关闭。
