### ISSUE TITLE
建议，希望官方出一个join的插件

### ISSUE THREAD

**Issue by parkerisme** [baomidou/mybatis-plus#3572]
希望官方出一个join的插件。目前市场看到的，非常实用。
git地址：https://github.com/yulichang/mybatis-plus-join

**Comment by qmdx** [comment]
有此类似计划，欢迎关注 https://gitee.com/baomidou/mybatis-plus-enterprise 版本的发布

**Comment by qmdx** [comment]
第三方扩展  https://gitee.com/tangzc/mybatis-plus-ext

**Comment by 565785929** [comment]
期待已久。

**Comment by kamjin1996** [comment]
怎么样了 好用吗 后台管理系统 大量需要join 哈哈

**Comment by seabean1999** [comment]
> 怎么样了 好用吗 后台管理系统 大量需要join 哈哈

利用mybatis-plus现有的功能其实也能够做到无SQL多表联合查询——若干次单表查询，然后在Service层进行数据的整合，效果等同于多表联合查询，在高并发且数据量大的场景下还有不少优点，这种做法怎么样？我看网上有人在实际项目中这样做了，参考链接：[MySQL多表关联查询效率高点还是多次单表查询效率高，为什么？ - 小知的回答 - 知乎](https://www.zhihu.com/question/68258877/answer/2071090987)

**Comment by tinytik** [comment]
@lin-xibin 多表关联往往可能既要根据左表条件过滤又要根据右表条件，写伪代码不考虑查询条件和分页的问题我也会写[MySQL多表关联查询效率高点还是多次单表查询效率高，为什么？ - 小知的回答 - 知乎](https://www.zhihu.com/question/68258877/answer/2071090987)

**Comment by qmdx** [comment]
下一个版本 https://gitee.com/baomidou/mybatis-plus4 会支持
