### ISSUE TITLE
如何配置全局的typehandler

### ISSUE THREAD

**Issue by xiaonatuo** [baomidou/mybatis-plus#3574]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
开发需求中需要动态查询数据库表数据，字段内容及类型无法确定，想通过配置全局的typehandler来处理CLOB等数据类型，但是在官方文档中没有找到相关文档

**Comment by xiaonatuo** [comment]
动态查询数据库表数据，是通过动态配置多数据源，需求中需要查询数据库表的前10条数据作为示例数据展示，所以数据库表字段及内容无法确定

**Comment by touwaeriol** [comment]
typeHandler 是mybatis的东西，你可以继承TypeHadnler 并通过@Comment 注册到容器里
![image](https://user-images.githubusercontent.com/52620633/120258026-e61cf200-c2c3-11eb-9e6d-ea515764cb9f.png)

**Comment by touwaeriol** [comment]
请注意类上的这几个注解，用于标注 数据库数据 到java的映射关系
![image](https://user-images.githubusercontent.com/52620633/120258071-f6cd6800-c2c3-11eb-9994-abf8f7948593.png)

**Comment by touwaeriol** [comment]
配置全局TypeHandler只需要通过注入实现了TypeHandler接口的类即可

**Comment by touwaeriol** [comment]
在类上标注 JAVA到jdbc的映射关系，但是不知道这样能否应用于你用map接收参数的场景
![image](https://user-images.githubusercontent.com/52620633/120258481-b6221e80-c2c4-11eb-9319-67df7d4045e0.png)

**Comment by xiaonatuo** [comment]
@touwaeriol 感谢回复，经过我的试验，该方式并不能对Map类型的结果集起作用，已经通过其他方式处理了

**Comment by youxiaxiaomage** [comment]
什么方式Map 配置了typeHandler也不行
