### ISSUE TITLE
文档的条件构造器的作用是什么

### ISSUE THREAD

**Issue by liubinylx** [baomidou/mybatis-plus#3575]
### 报错信息

文档的条件构造器有什么作用？指导开发？莫名其妙的一堆方法，这软件是给高手用的啊，那还开源干啥

**Comment by nishimoguima** [comment]
条件构造器是用来构建条件的，比如1 = 1 等等..中文文档已经说的很清楚了，至于开源不开源不需要你批准，我们有的是人pr。

**Comment by liubinylx** [comment]
> 条件构造器是用来构建条件的，比如1 = 1 等等..中文文档已经说的很清楚了，至于开源不开源不需要你批准，我们有的是人pr。
很清楚，你中文是体育老师教的啊，建议重修小学语文
