### ISSUE TITLE
@Results 注解无效， 版本3.3.2

### ISSUE THREAD

**Issue by zhujiancom** [baomidou/mybatis-plus#3576]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在Mapper上使用@Results 无效

### 重现步骤(如果有就写完整)

在MybatisMapperAnnotationBuilder::parseResultMap 方法中没有获取Results.class而获取的是Result.class

Result[] results = method.getAnnotationsByType(Result.class);

### 报错信息
没有报错信息

**Comment by miemieYaho** [comment]
去找mybatis

**Comment by zhujiancom** [comment]
> 去找mybatis

额。。。 我看这个类源代码是在mybatis-plus-core里的啊？

**Comment by miemieYaho** [comment]
`MybatisMapperAnnotationBuilder extends MapperAnnotationBuilder` ,基本上是对 `MapperAnnotationBuilder` 全量 copy

**Comment by zhujiancom** [comment]
![image](https://user-images.githubusercontent.com/4801004/120286609-0616da80-c2f1-11eb-836c-354be0c926f4.png)

大哥， 这个方法被你们覆写掉了， mybatis是对的

**Comment by miemieYaho** [comment]
那你可能对mybatis 的依赖有冲突导致版本不一致.3.3.2的mp依赖的3.5.4的mybatis

**Comment by zhujiancom** [comment]
不是啊， 大哥， 跟依赖有什么关系， 现在看源代码你们的逻辑就是错的啊， @Result是@Results的子属性，当然从方法上要拿@Results啊， 怎么可能拿到Result.class呢？ 我看你们现在3.0分支最新的代码也是拿的Result.class， 我觉得应该也是错的

**Comment by zhujiancom** [comment]
不是啊， 大哥， 跟依赖有什么关系， 现在看源代码你们的逻辑就是错的啊， @Result是@Results的子属性，当然从方法上要拿@Results啊， 怎么可能拿到Result.class呢？ 我看你们现在3.0分支最新的代码也是拿的Result.class， 我觉得应该也是错的

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/120291179-9d7e2c80-c2f5-11eb-8b22-c2f5561df201.png)

**Comment by miemieYaho** [comment]
你想说我们 cv 都能 cv 错吗?

**Comment by zhujiancom** [comment]
我刚看了， mybatis的master分支用的Result.class， 你们cv的没错， 是mybatis错了， 但是我也看了mybatis的3.3.x分支，写的是Results.class, 这是没错的！你们是不是可以帮他们把这个问题改了？

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/120293112-8a6c5c00-c2f7-11eb-962f-2018073fa9d9.png)

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/120293263-a839c100-c2f7-11eb-9708-0ba2de96513f.png)

**Comment by zhujiancom** [comment]
这个方法没什么用， 只不过就是去生成一个requestMapId, 最主要的还是Result[]这句有用
