### ISSUE TITLE
多租户只能过滤表，不灵活，且注入是明文的

### ISSUE THREAD

**Issue by little3201** [baomidou/mybatis-plus#3577]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
多租户只能过滤表，不灵活，且注入是明文的

希望能够更加灵活，例如：只有使用mytabis-plus提供的mapper接口才注入，且非明文

### 重现步骤(如果有就写完整)
配置多租户，设置隔离字段，那当前表所有操作都会被明文注入；

### 报错信息
无

**Comment by qmdx** [comment]
你需要强制关联用户登录信息对于企业租户ID 不允许认为改变即可
