### ISSUE TITLE
请问mybatis是否可以支持一下Sap hana数据库

### ISSUE THREAD

**Issue by liuzhanhua810** [baomidou/mybatis-plus#3578]
### 当前使用版本(必填,否则不予处理)
3.3.1

**Comment by miemieYaho** [comment]
除了分页方言,只要你这个数据库支持通用sql

**Comment by qmdx** [comment]
请参考 https://github.com/baomidou/mybatis-plus/pull/3423/files 然后 PR

**Comment by liuzhanhua810** [comment]
> 请参考 https://github.com/baomidou/mybatis-plus/pull/3423/files 然后 PR

是自己提，不是他们给做事吧？

**Comment by qmdx** [comment]
> > 请参考 https://github.com/baomidou/mybatis-plus/pull/3423/files 然后 PR
> 
> 是自己提，不是他们给做事吧？

你支持上然后 pr 过来
