### ISSUE TITLE
设置dbConfig.setLogicNotDeleteValue("")，查询时SQL是 =NULL

### ISSUE THREAD

**Issue by sgzman** [baomidou/mybatis-plus#3582]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
设置dbConfig.setLogicNotDeleteValue("")，
再取getById（id），打印的SQL的条件是  逻辑删除字段 =NULL

### 重现步骤(如果有就写完整)
Oracle数据库，逻辑删除字段是VARCHAR2(10)

**Comment by sgzman** [comment]
![image](https://user-images.githubusercontent.com/31655098/120451767-48f5b280-c3c4-11eb-93d3-5dc7172005ff.png)

**Comment by sgzman** [comment]
不知道是不是和这个相关

![image](https://user-images.githubusercontent.com/31655098/120583711-557c1880-c461-11eb-98a2-4dad6abbd678.png)

**Comment by miemieYaho** [comment]
dbConfig.setLogicNotDeleteValue("null")

**Comment by sgzman** [comment]
> dbConfig.setLogicNotDeleteValue("null")

谢谢，果然是这样，我之前只试了 dbConfig.setLogicNotDeleteValue(null)和dbConfig.setLogicNotDeleteValue("")。原来是没试全
