### ISSUE TITLE
Property 'mapperLocations' was specified but matching resources are not found.

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [baomidou/mybatis-plus#3584]
### 当前使用版本(必填,否则不予处理)

3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动程序

 
配置文件
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
xml 文件放在 resources目录下 
### 报错信息

Property 'mapperLocations' was specified but matching resources are not found.

**Comment by qmdx** [comment]
http://baomidou.com/ 查看问题部分
