### ISSUE TITLE
有没有办法将一个实体类转换为LambdaQueryWrapper

### ISSUE THREAD

**Issue by DawnSouther** [baomidou/mybatis-plus#3588]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter@3.4.2

### 想要进行的操作
我想写一个工具方法，这个工具方法可以将一个实体过滤掉null属性后将其他属性转换为一个wrapper。

我先尝试将实体转换为QueryWrapper，
这种方式需要手动进行一次驼峰转下划线，但是无法处理其他格式的转换，如 deleteStatus-> isDelete

我又尝试转换为LambdaQueryWrapper，但是由于eq()方法接收参数的限制，
它是通过反射获取lambda表达式的implName来进行字段映射，这样的话受限于元数据，无法动态传入指定字段。

局面因此陷入了僵局，有没有其他方法可以绕过这个限制？

### 其他思路
或者说，可否写一个接收驼峰式字段（实体字段名）的方法，在QueryWrapper中自动转换为数据库字段，
解决这种QueryWrapper必须传入数据库字段的模式

**Comment by nishimoguima** [comment]
你好，可以使用TableInfoHelper.getTableInfo(class)的方法获取字段和数据库字段名称映射来完成.

**Comment by DawnSouther** [comment]
ok可以，非常感谢
