### ISSUE TITLE
请问 mybaits plus 对于oracle数据库的支持如何

### ISSUE THREAD

**Issue by MinstrelOrMisa** [baomidou/mybatis-plus#359]
如题，最近公司项目要重写，因为之前是jdbc+mybaits的架构（好吧，历史原因。。）
但是不知道 mybaits plus对于oralce的支持如何。。因为demo和文档好像都是针对mysql的。比如分页那些。
也去搜索过相关的信息，但是并没有得到有用的信息。所以还望解答。。

**Comment by qmdx** [comment]
完全支持
