### ISSUE TITLE
@DS注解失效

### ISSUE THREAD

**Issue by hhhanshuo** [baomidou/mybatis-plus#3590]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.4.1
dynamic-datasource 3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
策略模式+工厂模式初始化Bean发生@DS失效

### 重现步骤(如果有就写完整)
创建了一个策略继承InitializingBean
public interface IDownloadBaseService extends InitializingBean {

    void op(HttpServletResponse response, String auditScenario, Boolean isChecked);
}

创建了一个工厂类：
private static final Map<String, IDownloadBaseService> map = new HashMap<>();

    public static IDownloadBaseService getInvokeStrategy(String type){
        return map.get(type);
    }

    public static void register(String name, IDownloadBaseService iDownloadBaseService){
        map.put(name,iDownloadBaseService);
    }

每个业务接口实现类实现IDownloadBaseService接口
DownloadFileSelectedFactory.register("",this);
然后在controller中获取
DownloadFileSelectedFactory.getInvokeStrategy().op()
### 报错信息
数据库没有对应表，实际上数据源没切换

**Comment by huayanYu** [comment]
理解AOP， 基于AOP的切换。
