### ISSUE TITLE
com.baomidou.mybatisplus.core.metadata.IPage是否可以单独开一个工程

### ISSUE THREAD

**Issue by galaxy-sea** [baomidou/mybatis-plus#3593]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.core.metadata.IPage是否可以单独开一个工程

如在rpc的客户端中使用IPage就需要引入整个core工程，

**Comment by galaxy-sea** [comment]
com.baomidou.mybatisplus.extension.plugins.inner.InnerInterceptor的6个实现类是否可以从extension工程中独立出来呐，

自动分页: PaginationInnerInterceptor
多租户: TenantLineInnerInterceptor
动态表名: DynamicTableNameInnerInterceptor
乐观锁: OptimisticLockerInnerInterceptor
sql性能规范: IllegalSQLInnerInterceptor
防止全表更新与删除: BlockAttackInnerInterceptor

**Comment by GoForItChen** [comment]
业务横向切割的时候，controller业务引用page对象也遇到了同样的问题。使用page对象就需要core依赖和extension依赖。这样相当于引入了controller业务也引入了plus的全部包。能否像annotation依赖一样把Ipage和page这两个类独立出来。

**Comment by nancheung97** [comment]
或许可以抽一个mybatisplus-model模块

**Comment by qmdx** [comment]
引用 mybatis-plus-extension 排除 其它模块依赖
