### ISSUE TITLE
LambdaUpdateWrapper  set 报错can not find lambda cache for this entity 

### ISSUE THREAD

**Issue by PingYufeng** [baomidou/mybatis-plus#3594]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1、对BaseMapper、ServiceImpl、IService做了一层继承
public interface SuperMapper<T> extends BaseMapper<T> {

}

public abstract class BaseServiceImpl<M extends SuperMapper<T>, T> extends ServiceImpl<M, T> {

}

public interface IBaseService<T> extends IService<T> {

}
2、本案例是springcloud下对服务层和接口层进行分离为独立模块，在接口工程模块的Controller层面，在3.4.2版本上使用lambda更新构造器set出现报错。
public class ProcessController {
        LambdaUpdateWrapper<HyperspectralItem> updateWrapper = new LambdaUpdateWrapper<>();
        updateWrapper.eq(HyperspectralItem::getId, hyperspectralItem.getId())
                .set(HyperspectralItem::getBeginTakeTime, beginTakeTime)
                .set(HyperspectralItem::getEndTakeTime, endTakeTime);

}

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not find lambda cache for this entity

**Comment by miemieYaho** [comment]
只有含有mapper层的模块才能使用Lambda模式

**Comment by PingYufeng** [comment]
谢谢
