### ISSUE TITLE
请问Service层的泛型对象与Mappper层泛型对象要求不一致如何解决？

### ISSUE THREAD

**Issue by a1782680475** [baomidou/mybatis-plus#3596]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我现在有一种需求，在Controller层与Service层传输对象新增了DTO层，而Mapper层与Service层传输数据仍然使用DO层，这样就导致Service层继承的IService接口传入的泛型为DTO层的对象，而Mapper层的BaseMapper接口传入的泛型为DO层的对象。这种需求我该如何操作呢？

**Comment by nancheung97** [comment]
将DTO转为DO
