### ISSUE TITLE
分页插件bug

### ISSUE THREAD

**Issue by Huzhengtao** [baomidou/mybatis-plus#3599]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
PaginationInnerInterceptor.setMaxLimit();
当pageSize小于0时，单页分页条数限制失效，会取全部数据

**Comment by nancheung97** [comment]
https://github.com/baomidou/mybatis-plus/pull/3600
这个pr可以解决

**Comment by qmdx** [comment]
> #3600
> 这个pr可以解决

但是通过改变 size 方式不可取

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/f39cea0d5d53c7319b1a0df54696e7990f24465a
