### ISSUE TITLE
Sequence的ID_WORKER生成策略存在问题，机器Id有可能重复

### ISSUE THREAD

**Issue by cyejing** [baomidou/mybatis-plus#360]
Sequence的datacenterId和workerId是通过求余产生的，当机器数量多的情况下有可能出现重复。有出现重复Id的隐患。
https://github.com/baomidou/mybatis-plus/blob/8807ea62c78d69708b8d461268f4fa8a81bfe1e8/mybatis-plus-support/src/main/java/com/baomidou/mybatisplus/toolkit/Sequence.java#L61
希望能够开放Id生成策略的拓展接口

**Comment by qmdx** [comment]
`
        this.datacenterId = getDatacenterId(maxDatacenterId);
        this.workerId = getMaxWorkerId(datacenterId, maxWorkerId);
`

取得   byte[] mac = network.getHardwareAddress();
进程 ID 理论上除非单机部署多节否则不应该重复

**Comment by cyejing** [comment]
不是，因为实现是取mac地址做求余得到DatacenterId，理论上mac地址求余之后就会出现重复。即使单机单节点，多台机器的mac求余得到同一个id的几率还是有的。有出现重复Id的隐患。

**Comment by cyejing** [comment]
应该开发Sequence的DatacenterId和WorkerId给使用者自由设置

**Comment by xsomnus** [comment]
```
@EqualsAndHashCode(callSuper = true)
@Data
@Builder
@KeySequence("withdrawalsParticipantId")
@TableName("tb_withdrawals_order_participant")
public class WithdrawalsOrderParticipant extends BasicField<WithdrawalsOrderParticipant> {

    @TableId
    private Long id;

    private OffsetDateTime deleteTime;

    private OffsetDateTime expireTime;

    private String uri;

    private Long withdrawalsOrderId;

    @Override
    protected Serializable pkVal() {
        return id;
    }
}
```
@KeySequence("withdrawalsParticipantId") 可以使用自定义的策略，保证不会重复

**Comment by qmdx** [comment]
关注下一个版本 3.0.3 发布, 支持自定义参数了 https://github.com/baomidou/mybatis-plus/commit/9adbcf34433e0cd4a5cbc4ce2686f3ff64efaaf7
