### ISSUE TITLE
lambdaQuery表达式查询错误，不知道是什么，换成QueryWrapper就可以，其他的场景都是这么用的也没出问题

### ISSUE THREAD

**Issue by gcwu** [baomidou/mybatis-plus#3601]
### 当前使用版本(必填,否则不予处理)
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用lambdaQuery查询
peopleHurtCaseInfoService.lambdaQuery().eq(PeopleHurtCaseInfo::getAppointmentInfoId,"123").one()

使用以下就没问题

QueryWrapper<PeopleHurtCaseInfo> queryWrapper = new QueryWrapper();
PeopleHurtCaseInfo p = new PeopleHurtCaseInfo();
p.setAppointmentInfoId("123");
queryWrapper.setEntity(p);
peopleHurtCaseInfoService.getOne(queryWrapper)

### 报错信息
org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: 该方法仅能传入 lambda 表达式产生的合成类]

**Comment by nancheung97** [comment]
是kotlin代码吗？如果是，请看 #716 。 如果不是kotlin，请补充更多信息或复现demo

**Comment by qmdx** [comment]
up

**Comment by hipilee** [comment]
我也遇见了同样的问题，但是感觉并不意向输出结果。

**Comment by wangJiaLun-china** [comment]
如果是使用的idea开发工具，在debugger窗口会产生这个问题。直接运行代码是可以的，debugger小窗口反复执行模式会复现这个问题。
