### ISSUE TITLE
jsqlparser 版本问题

### ISSUE THREAD

**Issue by wu-xin** [baomidou/mybatis-plus#3609]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
更新依赖jsqlparser 4.0 后，jsqlparser有个union的解析问题，官方的issues https://github.com/JSQLParser/JSqlParser/issues/1094
说要到4.1版本修复，如果手动降到3.2的版本是否可行？是否有对4.0做一些特殊处理？

**Comment by 986510453** [comment]
@wu-xin 
maven依赖里面exclude JSQLParser依赖，然后在单独引入4.1版本的

**Comment by qmdx** [comment]
官方发布新版 mp 会第一时间引入

**Comment by wu-xin** [comment]
> @wu-xin
> maven依赖里面exclude JSQLParser依赖，然后在单独引入4.1版本的

4.1版本还不知道什么时候发

**Comment by wu-xin** [comment]
> 官方发布新版 mp 会第一时间引入

可能要等很久

**Comment by qmdx** [comment]
版本 `3.4.3.2` 已发布，请升级验证修复该问题，有任何问题 issue 该问题关闭！
