### ISSUE TITLE
能否不在Entity上生成Swagger注解？

### ISSUE THREAD

**Issue by yxlaisj** [baomidou/mybatis-plus#3612]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 重现步骤(如果有就写完整)
GlobalConfig gc = new GlobalConfig();
gc.setSwagger2(false);

直接结果依然生成swagger注解

**Comment by nancheung97** [comment]
使用3.5.0-SNAPSHOT版本测试正常

**Comment by qmdx** [comment]
请关注 https://github.com/baomidou/generator
