### ISSUE TITLE
BaseMapper增加selectByEntity诉求

### ISSUE THREAD

**Issue by 1252999** [baomidou/mybatis-plus#3619]
### 当前使用版本(必填,否则不予处理)
selectByMap 需要map 而 selectList 需要 queryWrapper，都需要进行转换，建议直接增加根据实体查询

**Comment by huayanYu** [comment]
核心是基于Wrapper设计，里面可以设置实体。
你也可以根据文档自己扩展基础方法。

**Comment by miemieYaho** [comment]
new queryWrapper(entity)
