### ISSUE TITLE
同一个事务 baseMapper.selectById 每次执行返回的实体是同一个引用

### ISSUE THREAD

**Issue by fusi0011** [baomidou/mybatis-plus#362]
T model1 = this.baseMapper.selectById(3);
T model2 = this.baseMapper.selectById(3);
System.out.println(model1 == model2);  //等于true

在项目中发现这个问题，  如果出于缓存的考虑， SQL只执行一次，结果进行缓存， 返回时将结果封装到实体中进行返回， 每次返回应该会new 一次， 但是目前引用是一样的， 这是出于什么考虑呢？

**Comment by qmdx** [comment]
如上
