### ISSUE TITLE
添加字段唯一注解

### ISSUE THREAD

**Issue by anganing** [baomidou/mybatis-plus#3621]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
系统有大量检验某个字段唯一的需求，自己写了一个注解@Unique(tableName="tableName", cloumn="clomun",message="字段值已经存在！")
tableName是数据库表名，cloumn是表字段名。已经能够成功校验，希望官方也加一个这样的注解吧。

**Comment by nancheung97** [comment]
这应该由数据库的唯一索引约束

**Comment by huayanYu** [comment]
不会支持
