### ISSUE TITLE
每个sql执行的时候都需要对包含对某个字段的where判断，有点儿类似于逻辑删的策略，请问如何实现

### ISSUE THREAD

**Issue by YAGAMIL** [baomidou/mybatis-plus#3626]
每个sql执行的时候都需要对包含对某个字段的where判断，有点儿类似于逻辑删的策略，请问如何实现
自带的insert中需要包含这个字段，insertOrUpdate中的查询需要包含where字段条件，delete以及其它磨人的查询方法也要带，可否提供一类似于@TableLogic(delval = "0", value = "1")这样的注解，逻辑可以开放自己实现，配置sql调用枚举，什么时候必要where该字段等

**Comment by 986510453** [comment]
@YAGAMIL  可以参考租户插件代码：TenantLineInnerInterceptor

**Comment by YAGAMIL** [comment]
> @YAGAMIL 可以参考租户插件代码：TenantLineInnerInterceptor

好的，感谢

**Comment by YAGAMIL** [comment]
你们可不可以加一个这样的注解来实现，将或者将逻辑删除的注解能力开放出来，允许多个这样的注解，每个表可以子定义每个字段是否强制拼接特定语句，然后照常扫描所有的注解，同时可以交由自己来配置特定字段的处理策略和方案，我觉得这样会更优雅一些

**Comment by YAGAMIL** [comment]
> @YAGAMIL 可以参考租户插件代码：TenantLineInnerInterceptor

你们可不可以加一个这样的注解来实现，将或者将逻辑删除的注解能力开放出来，允许多个这样的注解，每个表可以子定义每个字段是否强制拼接特定语句，然后照常扫描所有的注解，同时可以交由自己来配置特定字段的处理策略和方案，我觉得这样会更优雅一些

**Comment by qmdx** [comment]
无通用性请自行处理
