### ISSUE TITLE
3.4.3 版本排序条件为什么取消了字段数组方法增加了一个需要固定字段的

### ISSUE THREAD

**Issue by lwQin** [baomidou/mybatis-plus#3629]
### 当前使用版本
3.4.3

**Comment by 986510453** [comment]
@lwQin 现在是细化了，有什么问题吗？
![image](https://user-images.githubusercontent.com/33100175/122318339-778d9480-cf51-11eb-8384-dfe5b0f0d84c.png)

**Comment by angcyo** [comment]
可以自己传入  `a,b,c` 这样的字符串.

**Comment by lwQin** [comment]
@986510453 原本使用 `queryWrapper.orderByAsc(fields);` 的，现在得`queryWrapper.orderByAsc(fields[0], fields);`了，觉得别扭。。

**Comment by 986510453** [comment]
@lwQin 

#5e7d88d 优化 JDK 默认不推荐泛型数组，会引起 Java堆污染(Heap Pollution) 拆分为单个泛型、集合泛型两个方法

https://github.com/baomidou/mybatis-plus/commit/c1f5aa5

可以转成集合，使用orderByAsc(List<R> columns)方法哈

**Comment by lwQin** [comment]
@986510453 这个修改还没 release :(

**Comment by 986510453** [comment]
@lwQin  那就先用低版本吧😂
