### ISSUE TITLE
之前版本用AbstractSqlParserHandler做了数据权限控制 现在去哪了？

### ISSUE THREAD

**Issue by pkaq** [baomidou/mybatis-plus#3632]
### 当前使用版本(必填,否则不予处理)
3.4.3
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
类丢失
### 报错信息
not found

**Comment by 986510453** [comment]
@pkaq  参考多租户代码：TenantLineInnerInterceptor

**Comment by pkaq** [comment]
> @pkaq 参考多租户代码：TenantLineInnerInterceptor

发现源码中有DataPermissionInterceptor ，但是文档没有任何提及？

**Comment by 986510453** [comment]
@pkaq  那算是试验功能，功能是没问题的，可以尝试使用，欢迎反馈哈
