### ISSUE TITLE
当父类和子类中有相同成员变量 类型不同时   查询结果做映射时 set失败  自动映射获取的是父类的变量

### ISSUE THREAD

**Issue by Curtaingit** [baomidou/mybatis-plus#3633]
### 当前使用版本(必填,否则不予处理)
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1.tmp</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

> 父类中定义
@TableField(exist = false)
 private String endTime;

> 子类中定义
 private Date endtime;

> 数据表定义
字段名:endtime 类型:Date

### 重现步骤(如果有就写完整)
自动映射处理时
![image](https://user-images.githubusercontent.com/31627168/122143414-0338ef80-ce84-11eb-8ba9-69a084e7bee6.png)

### 报错信息
导致子类中的endtime 无法映射      （数据库中字段实际类型为 endtime）

**Comment by Curtaingit** [comment]
现在我通过mapper.xml中指定resultMap  可以避免这个问题              但是直接使用baseMapper中的selectList就会有这个问题

**Comment by miemieYaho** [comment]
`@TableName(resultMap='xxxxxx')`

**Comment by Curtaingit** [comment]
> `@TableName(resultMap='xxxxxx')`

谢谢！  本来我还在想  有怎么办法可以指定某个字段  不去执行大小写转化。
