### ISSUE TITLE
项目无法使用p6spy，如何打印完整的sql日志，想3.1

### ISSUE THREAD

**Issue by YAGAMIL** [baomidou/mybatis-plus#3638]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
无法使用p6spy打印完整sql，内部分库分表数据库不暴露jdbcurl，无法配置dataSource为p6spy的驱动，按照原本3.1版本的
模仿了一份儿PerformanceInterceptor配置也不起作用

希望能把PerformanceInterceptor提供回来，不然实在不知道执行sql为啥出错，配置了逻辑删除，太难定位了

**Comment by qmdx** [comment]
你找到旧版复制 PerformanceInterceptor 到你本地项目即可
