### ISSUE TITLE
多租户过滤

### ISSUE THREAD

**Issue by lijiangbo114** [baomidou/mybatis-plus#3645]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
QueryWrapper查询和baseMapper 自带的mapper方法，租户过滤。

### 重现步骤(如果有就写完整)

Mybatis-Plus 如果配置了多租户功能，QueryWrapper查询和baseMapper 自带的mapper方法，就会被强制拦截添加租户字段，这种插件自带的便捷查询等功能，就不适用了。QueryWrapper查询和baseMapper能不能加上租户的过滤开关条件了。这样㘝使用QueryWrapper查询和baseMapper查询也能忽略租户拦截。

### 报错信息
无

**Comment by miemieYaho** [comment]
不能

**Comment by liu-xinhui** [comment]
有同样的需求，目前只能自写sql，通过注解进行某个方法的排除，就不能用自带的QueryWrapper了。要是QueryWrapper中增加一个ignoreTenantLine = true参数就好了
