### ISSUE TITLE
考虑@TableId支持mysql8的 uuid_to_bin(uuid()) 方法么

### ISSUE THREAD

**Issue by 827551331** [baomidou/mybatis-plus#3646]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

考虑@TableId支持，mysql8的 uuid_to_bin(uuid()) 方法么

**Comment by qmdx** [comment]
查看文档 https://baomidou.com/guide/sequence.html  自定义处理
