### ISSUE TITLE
逻辑删除希望也可以带入通用字段更新

### ISSUE THREAD

**Issue by leixinwei12** [baomidou/mybatis-plus#3647]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

这个更新是有注入通用字段的
UPDATE usr_user SET telephone = ?, update_date = now(), update_user_id = ?, update_user_name = ? WHERE  id = ? AND delete_flag = 0

逻辑删除没有注入通用字段的
UPDATE usr_user SET delete_flag = id WHERE  id IN (?, ?) AND delete_flag = 0

逻辑删除应该也可以注入通用的字段信息才合理

**Comment by qmdx** [comment]
你如果有这种需求可以注入 https://baomidou.com/guide/crud-interface.html#logicdeletebyidwithfill 这个方法调用
