### ISSUE TITLE
请问要如何在使用group by的情况下获得记录的总条数

### ISSUE THREAD

**Issue by abcbuzhiming** [baomidou/mybatis-plus#365]
在Mysql5.7以上版本，使用group by后，希望获得得到的记录表的总条数，使用selectCount(entity)的方式会失败，失败提示是：
Expected one result (or null) to be returned by selectOne(), but found: xxx
,我通过解析sql语句发现内部调用的SELECT COUNT(1)。这种在group by使用时无法得到全部条数。那么使用group by时想得到整体条数该如何办？

**Comment by qmdx** [comment]
复杂 sql 建议 xml 解决
