### ISSUE TITLE
默认事务隔离级别下的selectList取值问题

### ISSUE THREAD

**Issue by avanda945** [baomidou/mybatis-plus#3650]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在同一个方法中先执行save然后再执行selectList，会把当前save的这条也查出来，查出来的这条数据的id是null

### 重现步骤(如果有就写完整)
public void method(xxxDTO) {
xxxDTO.setScore(xxx);
super.save(xxxDTO);
List<xxxDTO> list = super.list(params);
}

### 报错信息

list中会带有save操作的这一条数据，但是数据对象是method方法入参中的dto而不是save之后的dto(id是null，score值也是null)

**Comment by qmdx** [comment]
事务设置 READ_COMMITTED

**Comment by avanda945** [comment]
我试过了还是一样的


来自 魅族 16th Plus

-------- 原始邮件 --------
发件人：qmdx ***@***.***>
时间：2021年6月26日 18:29
收件人：baomidou/mybatis-plus ***@***.***>
抄送：avanda945 ***@***.***>,Author ***@***.***>
主题：Re: [baomidou/mybatis-plus] 默认事务隔离级别下的selectList取值问题 (#3650)
