### ISSUE TITLE
考虑参考typeorm的关联关系解决方案吗？

### ISSUE THREAD

**Issue by Formerscholar** [baomidou/mybatis-plus#3653]
实体类定义关键关系
API直接调用

或者参考laravel框架的orm实现

**Comment by huayanYu** [comment]
暂无此计划。

**Comment by ZhaoJin-Big** [comment]
> 实体类定义关键关系
> API直接调用
> 
> 或者参考laravel框架的orm实现

可以参考这个 https://gitee.com/mr_zhaojin/mybatis-plus-join.git
