### ISSUE TITLE
vararg 参数的未检查的泛型数组创建 ,官方文档需要更新

### ISSUE THREAD

**Issue by whiteS18** [baomidou/mybatis-plus#3656]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
原来使用的是方法是QueryWrapper.lambda().条件判断(类::getxx,参数).orderByDesc(类::getxx)；可以正常使用，现在使用会提示
vararg 参数的未检查的泛型数组创建，查看源码发现方法参数变成了
default Children orderByDesc(R column, R... columns) 
而官方文档还是旧的orderByDesc(R... columns)
请问现在新版本该如何使用？

**Comment by 986510453** [comment]
暂时先使用低版本吧，后续会发布集合参数 单个参数等三个重载方法。
