### ISSUE TITLE
我使用中遇到了一个问题，急

### ISSUE THREAD

**Issue by yingjie-ye** [baomidou/mybatis-plus#366]
`我自定义了一个mybatis-plus配置文件在MAPPER-location配置遇到了问题，我的代码如下`
`log.info("初始化SqlSessionFactory");
		MybatisSqlSessionFactoryBean sqlSessionFactory = new MybatisSqlSessionFactoryBean();
		sqlSessionFactory.setDataSource(dataSource); // 数据源
		sqlSessionFactory.setGlobalConfig(globalConfig); // 全局配置
		sqlSessionFactory.setConfiguration(mybatisConfig);// mybatis配置
		// 分页插件，乐观锁插件
		Interceptor[] interceptor = { paginationInterceptor, new OptimisticLockerInterceptor() };
		sqlSessionFactory.setPlugins(interceptor);
		ResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
		try {
			// 自动扫描Mapping.xml文件
			if (!"none".equals(mapperLocations)){
				Resource[] resources= resolver.getResources(mapperLocations);
				log.debug("MAPPER-XMP扫描结果:----------------");
				for (Resource r : resources) {
					log.debug(r.getFilename());
				}
				log.debug("----------------------------------");
				sqlSessionFactory.setMapperLocations(resources);
			}
			// 实体
			sqlSessionFactory.setTypeAliasesPackage(typeAliasesPackage);
			// 枚举
			if (!"none".equals(typeEnumsPackage))
				sqlSessionFactory.setTypeEnumsPackage(typeEnumsPackage);
			return sqlSessionFactory.getObject();
		} catch (Exception e) {
			e.printStackTrace();
			throw e;
		}`
我配置的MapperLocations加载路径：classpath*:/mapper/**/*.xml，
当我mapper/xx/xx.xml只有一个文件的时候，可以正常调用，但有多个XML文件的时候，调用任务SQL都会报错，错误如下：
`Caused by: java.lang.IllegalArgumentException: Result Maps collection does not contain value for java.lang.String
	at org.apache.ibatis.session.Configuration$StrictMap.get(Configuration.java:888)
	at org.apache.ibatis.session.Configuration.getResultMap(Configuration.java:640)
	at org.apache.ibatis.builder.MapperBuilderAssistant.getStatementResultMaps(MapperBuilderAssistant.java:344)
	... 48 more`

我查看过加载过程，我的MAPPER.XML文件都能够正常加载，但就是用不了，急急急！

**Comment by qmdx** [comment]
这是配置问题， http://mp.baomidou.com/#/install?id=%E4%BC%98%E7%A7%80%E6%A1%88%E4%BE%8B 随便好一个案例好好看看
