### ISSUE TITLE
xml 里 resultMap 中加 Collection，报 java.lang.ClassCastException

### ISSUE THREAD

**Issue by FarewellXzz** [baomidou/mybatis-plus#3660]
### 当前使用版本(必填,否则不予处理)

3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

xml 里 resultMap 中加 Collection，报 java.lang.ClassCastException
： class com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap$Ambiguity cannot be cast to class org.apache.ibatis.mapping.ResultMap
### 报错信息

org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'com/csii/dgm/metadata/mapper/MetadataDbViewMapper.xml'. Cause: java.lang.ClassCastException: class com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap$Ambiguity cannot be cast to class org.apache.ibatis.mapping.ResultMap (com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap$Ambiguity and org.apache.ibatis.mapping.ResultMap are in unnamed module of loader 'app')

**Comment by bolinnn** [comment]
我也遇过这个问题，触发条件是，所有xml有如果有同相同id的resultMap，其中一个resultMap如果有association或者collection属性就会触发。

**Comment by qmdx** [comment]
版本 `3.4.3.2` 已发布，请升级验证修复该问题，有任何问题 issue 该问题关闭！
