### ISSUE TITLE
使用select控制查询字段的时候，有没有办法动态的使用外部参数

### ISSUE THREAD

**Issue by ideaviewes** [baomidou/mybatis-plus#3662]
### 当前使用版本(必填,否则不予处理)

使用版本3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/5431843/122860062-9a53ea80-d34f-11eb-9b89-68e56649b0d2.png)

怎么才能把fields传递到select方法中，通过fields变量动态的控制查询哪个字段

**Comment by nancheung97** [comment]
直接写字符串？

**Comment by ideaviewes** [comment]
@nancheung97 ，lambda表达式这种，没办法这样传参吗？

**Comment by ideaviewes** [comment]
我找到了办法，
把fields转成数组就行了
