### ISSUE TITLE
使用 DataPermissionInterceptor 数据权限插件在分页场景统计总数量错误（数据不正确）

### ISSUE THREAD

**Issue by houkunlin** [baomidou/mybatis-plus#3668]
### 当前使用版本(必填,否则不予处理)
`com.baomidou:mybatis-plus-boot-starter:3.4.3.1`

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用 DataPermissionInterceptor 插件设置数据查询条件（数据范围），在分页的场景分页插件 PaginationInnerInterceptor 有一个查询统计数量的语句，这个语句得到的结果不正确（没有使用到DataPermissionInterceptor插件设置的条件），但是实际的查询数据中有DataPermissionInterceptor插件设置的查询条件

### 重现步骤(如果有就写完整)
用了DataPermissionInterceptor插件后，在定义的DataPermissionHandler中返回一个新的（涵盖以前的条件）条件信息。

业务Service继承IService，业务Mapper继承BaseMapper，直接使用 Service..lambdaQuery().page(page); 获取分页数据，在控制台中，第一条统计数量的SQL无任何DataPermissionHandler定义的查询条件，在第二条查询数据的SQL有DataPermissionHandler定义的查询条件

### 报错信息
无任何报错，就是得到的分页数量信息不正确

**Comment by miemieYaho** [comment]
放分页前面

**Comment by houkunlin** [comment]
> 放分页前面

非常感谢，问题已解决
