### ISSUE TITLE
queryWrapper使用.select时，id字段为null

### ISSUE THREAD

**Issue by YuRenGe** [baomidou/mybatis-plus#3673]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用queryWrapper.select("*")时，返回的结果中id为null

### 重现步骤(如果有就写完整)
1. 随便定义个实体：
public class test{
    @TableId(value = "test_id", type = IdType.AUTO)
    private Long id;
    @TableField(value = "nename")
    private String neName;
    @TableField(value = "soname")
    private String soName;
}
2. 按上面字段写个数据库数据
3. 做个查询
queryWrapper.select("*").eq("ne_name",nename);

其他字段数据都可以查出来，但是所有数据的id为null

**Comment by Inighty** [comment]
参考#3342
因为主键字段与数据库实际字段对应不上的原因 
mybatis 转换实体对象的时候 只会通过反射获取字段去设置

**Comment by qmdx** [comment]
全局配置  https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/config/GlobalConfig.java

```
        /**
         * db字段 format
         * <p>
         * 例: `%s`
         * <p>
         * 对主键无效
         *
         * @since 3.1.1
         */
        private String columnFormat;
```
