### ISSUE TITLE
带有子查询的分页查询中，针对某字段去重无效

### ISSUE THREAD

**Issue by Jugol7** [baomidou/mybatis-plus#3674]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

自定义sql语句，其中带有子查询，针对某一个字段进行去重，分页插件执行的sql语句，没有指定字段去重，生成的ROW_NUMBER会不一致，导致去重失败

**Comment by qmdx** [comment]
描述与 mp 无关
