### ISSUE TITLE
自定义mapper修改方法导致MetaObjectHandler失效

### ISSUE THREAD

**Issue by Curtaingit** [baomidou/mybatis-plus#3676]
### 当前使用版本(必填,否则不予处理)
  <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.1.tmp</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自定义mapper 的 insert or update导致 MetaObjectHandler 失效

### 报错信息
通过  baseMapper 调用  save or  update  自动注入可以实现

通过断点发现  使用自定义mapper完成insert or update的时候   strictInsertFill() strictUpdateFill()依然会触发   对象的值也会被填充 ,但是最后生成的sql  没有包含填充字段

**Comment by miemieYaho** [comment]
ognl之后才会进行填充,需要填充的字段是不能用 if 的
