### ISSUE TITLE
pg库 批量插入 jsonb字段最终是同一个数值

### ISSUE THREAD

**Issue by jeremeyjiang** [baomidou/mybatis-plus#3677]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.4.2
mybatis 3.5.3

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/6545089/123404280-8b816800-d5db-11eb-8024-d1bb86fd3fdc.png)

![image](https://user-images.githubusercontent.com/6545089/123404189-84f2f080-d5db-11eb-936e-cdaf87d8d3a2.png)

![image](https://user-images.githubusercontent.com/6545089/123404652-a48a1900-d5db-11eb-85a5-4ae978d1d034.png)

JsonbTypeHandler 类中 列表是可以确认分别赋值  且数值符合预期。但最终落库数据jsonb字段是相通的

**Comment by jeremeyjiang** [comment]
将mp版本更新至 3.4.3.1 结果一致

**Comment by jeremeyjiang** [comment]
![image](https://user-images.githubusercontent.com/6545089/123739833-e2d45080-d8d9-11eb-9a3d-7ed685482559.png)
已解决

**Comment by ilwyiworld** [comment]
> ![image](https://user-images.githubusercontent.com/6545089/123739833-e2d45080-d8d9-11eb-9a3d-7ed685482559.png) 已解决

是把这个 PGobject 设置为局部变量吗
