### ISSUE TITLE
（分页）插件不起作用

### ISSUE THREAD

**Issue by YAGAMIL** [baomidou/mybatis-plus#3679]
### 当前使用版本(必填,否则不予处理)

3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
内部数据库兼容mysql使用，其它都支持，现在发现分页插件不起作用，配置也都是正常，debug分页插件发现根本就没进去过，最终执行sql也没有拼接limit分页条件，想问问您这边如何排查

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/16757285/123430362-aadbbd80-d5fa-11eb-9abe-620d47ff8a02.png)
似乎所有插件都不起作用，自己添加了旧版的log插件也不生效

另外官网写的这个配置是什么意思，应该是你们写错了吧
![image](https://user-images.githubusercontent.com/16757285/123430517-db235c00-d5fa-11eb-9b92-f5ab6b0264c8.png)

### 报错信息

插件不起作用（分页）

**Comment by YAGAMIL** [comment]
debug发现注入插件成功
![image](https://user-images.githubusercontent.com/16757285/123439155-05c5e280-d604-11eb-9756-70ec97421b72.png)
但是sql执行依然没有拼接limit分页及相关条件
debug最终没有走到
buildPaginationSql(String originalSql, long offset, long limit)方法中，也没有走到com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor#beforeQuery中

**Comment by YAGAMIL** [comment]
![image](https://user-images.githubusercontent.com/16757285/123443330-635c2e00-d608-11eb-87d3-69480dfde781.png)
先是走到了
com/baomidou/mybatis-plus-extension/3.4.3/mybatis-plus-extension-3.4.3-sources.jar!/com/baomidou/mybatisplus/extension/plugins/MybatisPlusInterceptor.java:74这一行内部调用

![image](https://user-images.githubusercontent.com/16757285/123443837-d6fe3b00-d608-11eb-8dc2-b49e54221a52.png)
List<Object> result = executor.query(countMs, parameter, rowBounds, resultHandler, cacheKey, countSql);

**Comment by yihuiaa** [comment]
**当前使用版本(必填,否则不予处理)**
3.0.5

**该问题是如何引起的？(确定最新版也有问题再提!!!)**
mybatis映射文件添加缓存后分页不在生效

**Comment by YAGAMIL** [comment]
> **当前使用版本(必填,否则不予处理)**
> 3.0.5
> 
> **该问题是如何引起的？(确定最新版也有问题再提!!!)**
> mybatis映射文件添加缓存后分页不在生效
找到问题了，非常感谢，项目中有人加了空的mybatis-conf.xml并指定该配置为默认配置导致的，非常感谢您的回复，打扰了，不过借此机会看了挺多mybatisplus的源码
