### ISSUE TITLE
mybatis使用insert自建语句插入时报jdbcType没有制定

### ISSUE THREAD

**Issue by ghj1040110333** [baomidou/mybatis-plus#3681]
### 当前使用版本(必填,否则不予处理)

3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

 Mysql切换到ORACLE出现的，主键递增策略也不能用

### 重现步骤(如果有就写完整)

java.sql.SQLException: Invalid column type: 1111

### 报错信息

java.sql.SQLException: Invalid column type: 1111

**Comment by qmdx** [comment]
oracle 请使用 https://baomidou.com/guide/sequence.html
