### ISSUE TITLE
字段通过xml定义resultMap做了映射，插入跟查询字段不一致！！！

### ISSUE THREAD

**Issue by huanglongyue** [baomidou/mybatis-plus#3684]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
字段做了映射，插入跟查询字段不一致！！！

### 重现步骤(如果有就写完整)
1：在mapper.xml 定义了一个resultMap
 ```
 <resultMap id="BaseResultMap" type="com.xxx.BeanDO">
    <id column="id" jdbcType="BIGINT" property="id" />
    <result column="name" jdbcType="VARCHAR" property="address" />
    <result column="address" jdbcType="INTEGER" property="name" />
  </resultMap>
```
2: 定义beanDO
```
@TableName(value = "db_test",resultMap = "BaseResultMap")
@Data
public class BeanDO {
    private String name;
    private String address;
    private Long id;
}
```

3：通过mapper.insert(beanDO),然后 mapper.selectById（id），查询出来的结果跟插入的结果字段映射不上，也就是说插入的时候没有使用到resultMap映射，查询的时候使用到了resultMap映射

### 报错信息

未报错，但结果不是预期想要的

**Comment by miemieYaho** [comment]
去百度  mybatis的resultMap是什么

**Comment by heihei180** [comment]
> 去百度 mybatis的resultMap是什么

我在想：是否可以支持这个功能？ 我现在也遇到这个问题就是：数据库换了：字段名可能有区别，我的意思是否可以通过 直接再实体类上 标记 rsult map 就可以无缝切换： 如果需要  我 可以提供 pr、
