### ISSUE TITLE
MyBatisPlus升级3.4.3.1版本报错：MybatisConfiguration$StrictMap$Ambiguity cannot be cast to ResultMap

### ISSUE THREAD

**Issue by herenpeng** [baomidou/mybatis-plus#3685]
### 报错相关可以参考本人博客：https://blog.csdn.net/qq_45193304/article/details/118346115
报错方法：com.baomidou.mybatisplus.core.MybatisConfiguration#checkGloballyForDiscriminatedNestedResultMaps

绕过泛型检查的原因：com.baomidou.mybatisplus.core.MybatisConfiguration.StrictMap#put
重写的 put 方法进行了类型强转。

**Comment by zengzhuo** [comment]
这个问题还没有修复吗？也遇到同样的问题

**Comment by Inighty** [comment]
> 这个问题还没有修复吗？也遇到同样的问题

已经修复了 不过还没发布  可以先使用3.4.4.3-SNAPSHOT或者回退版本

**Comment by liu-xinhui** [comment]
> > 这个问题还没有修复吗？也遇到同样的问题
> 
> 已经修复了 不过还没发布 可以先使用3.4.4.3-SNAPSHOT或者回退版本

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.4.3-SNAPSHOT</version>
        </dependency>

找不到这个包呀

**Comment by Inighty** [comment]
> > > 这个问题还没有修复吗？也遇到同样的问题
> > 
> > 
> > 已经修复了 不过还没发布 可以先使用3.4.4.3-SNAPSHOT或者回退版本
> 
> ```
>     <dependency>
>         <groupId>com.baomidou</groupId>
>         <artifactId>mybatis-plus-boot-starter</artifactId>
>         <version>3.4.4.3-SNAPSHOT</version>
>     </dependency>
> ```
> 
> 找不到这个包呀

https://baomidou.com/guide/install.html#snapshot

**Comment by liu-xinhui** [comment]
> > > > 这个问题还没有修复吗？也遇到同样的问题
> > > 
> > > 
> > > 已经修复了 不过还没发布 可以先使用3.4.4.3-SNAPSHOT或者回退版本
> > 
> > 
> > ```
> >     <dependency>
> >         <groupId>com.baomidou</groupId>
> >         <artifactId>mybatis-plus-boot-starter</artifactId>
> >         <version>3.4.4.3-SNAPSHOT</version>
> >     </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 找不到这个包呀
> 
> https://baomidou.com/guide/install.html#snapshot

非常感谢

**Comment by qmdx** [comment]
版本 `3.4.3.2` 已发布，请升级验证修复该问题，有任何问题 issue 该问题关闭！

**Comment by qmdx** [comment]
版本 `3.4.3.2` 已发布，请升级验证修复该问题，有任何问题 issue 该问题关闭！
