### ISSUE TITLE
拦截器获取lamada表达式真实列名

### ISSUE THREAD

**Issue by maitong** [baomidou/mybatis-plus#3694]
### 当前使用版本(必填,否则不予处理)

3.4.4.3-SNAPSHOT

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
想通过拦截器获取lamada表达式eq(OrderEntity:getOrderNo)里面的参数名，但是通过boundSql.getParameterMappings
获取到的参数名parameterMapping.getProperty都是被格式化成ew.paramNameValuePairs.MPGENVAL1这种参数，我想获取真实的列名orderNo，这种应该如何获取，
目前我是通过正则获取传参名称，再和值一一对应，不知道官方有没有更好的办法，获取到真实的列名与参数值

**Comment by nancheung97** [comment]
见：com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper#columnToString(com.baomidou.mybatisplus.core.toolkit.support.SFunction<T,?>)

**Comment by maitong** [comment]
> 见：com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper#columnToString(com.baomidou.mybatisplus.core.toolkit.support.SFunction<T,?>)

感谢您的回复，可能我没说清楚，这个是把列名转换成动态参数的，我是希望获取转换成动态参数之前的，
详见：[https://www.cnblogs.com/qubing/p/14384525.html](https://www.cnblogs.com/qubing/p/14384525.html)最后一张图
propertyName，我想拿到yysj yysj xzz_jd这些值，而不是ew.paramNameValuePairs.MPGENVAL1, ew.paramNameValuePairs.MPGENVAL2,  ew.paramNameValuePairs.MPGENVAL3

**Comment by nancheung97** [comment]
> > 见：com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper#columnToString(com.baomidou.mybatisplus.core.toolkit.support.SFunction<T,?>)
> 
> 感谢您的回复，可能我没说清楚，这个是把列名转换成动态参数的，我是希望获取转换成动态参数之前的，
> 详见：https://www.cnblogs.com/qubing/p/14384525.html最后一张图
> propertyName，我想拿到yysj yysj xzz_jd这些值，而不是ew.paramNameValuePairs.MPGENVAL1, ew.paramNameValuePairs.MPGENVAL2, ew.paramNameValuePairs.MPGENVAL3

此方法返回的确实是字段名，具体实现方法可以跟踪源码

**Comment by qmdx** [comment]
mp 内部不维护映射关系
