### ISSUE TITLE
MyBatis-Plus 官网 (苞米豆网址) 网站中的某个连接，点开后会弹出黄色网站

### ISSUE THREAD

**Issue by ddxl123** [baomidou/mybatis-plus#3695]
简介中的 

MyBatis-Plus (opens new window)（简称 MP）是一个 [MyBatis](http://www.mybatis.org/mybatis-3/) (opens new window)的增强工具，在 MyBatis 的基础上只做增强不做改变，为简化开发、提高效率而生。

**Comment by sustly** [comment]
好想知道你经历了什么，上班的时候打开的吗，，，

**Comment by ddxl123** [comment]
> 好想知道你经历了什么，上班的时候打开的吗，，，

**Comment by ddxl123** [comment]
> 好想知道你经历了什么，上班的时候打开的吗，，，

简介中的 
```
MyBatis-Plus (opens new window)（简称 MP）是一个 MyBatis (opens new window)的增强工具，在 MyBatis 的基础上只做增强不做改变，为简化开发、提高效率而生。
```
http://www.mybatis.org/mybatis-3/ 这个连接

**Comment by Surrin1999** [comment]
自己浏览器有问题吧。。我点开就是mybatis官网

**Comment by ddxl123** [comment]
> 自己浏览器有问题吧。。我点开就是mybatis官网

microsoft edge 浏览器就会跳转黄色，其他浏览器就没跳转。

**Comment by nancheung97** [comment]
这是mybatis官网，和mybatis-plus没关系，怀疑是你dns被劫持了

**Comment by qmdx** [comment]
baomidou.com
