### ISSUE TITLE
您好按照快速启动整理的配置 不使用xml文件mapper 使用注解出现了Invalid bound statement (not found)

### ISSUE THREAD

**Issue by LandscapeOde** [baomidou/mybatis-plus#3696]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 重现步骤(如果有就写完整)
Service 实现了IService  实现类继承了ServiceImpl 实现了接口Service

### 报错信息

Invalid bound statement (not found)

**Comment by LandscapeOde** [comment]
Mapper 文件也继承了BaseMapper 并且 也大了注解 @Mapper  和 @Repository

**Comment by LandscapeOde** [comment]
报错提示 mapper不存在insert  后来将注入的service 换成 mapper 使用insert 不爆红 但运行时就提示taskTimerMapper

**Comment by LandscapeOde** [comment]
Invalid bound statement (not found)

**Comment by nishimoguima** [comment]
这个问题原因有点多，自己百度搜索一下，排查原因。
附上我们的实例：https://github.com/baomidou/mybatis-plus-samples

**Comment by qmdx** [comment]
参考示例工程 https://gitee.com/baomidou/mybatis-plus-samples
