### ISSUE TITLE
updateAllColumnById方法

### ISSUE THREAD

**Issue by chenchi2038** [baomidou/mybatis-plus#37]
所有的update方法都是更新非null字段，更新全部字段只能再自己写sql了么？
我看到SqlMethod里是定义了updateAllColumnById方法的，为什么BaseMapper最终没有这个方法？

**Comment by Caratacus** [comment]
see https://github.com/baomidou/mybatis-plus/blob/master/mybatis-plus/src/main/java/com/baomidou/mybatisplus/mapper/BaseMapper.java
