### ISSUE TITLE
Quarkus 后面会支持吗?

### ISSUE THREAD

**Issue by zohar-soul** [baomidou/mybatis-plus#3713]
myBatis已经支持了.
https://github.com/quarkiverse/quarkus-mybatis

**Comment by qmdx** [comment]
精力有限欢迎你支持好 pr

**Comment by zhfeng** [comment]
@qmdx we will consider to support mybatis-plus in https://github.com/quarkiverse/quarkus-mybatis/issues/100 and feel free to add any feedback and comment.
