### ISSUE TITLE
querywrapper中能否增加自定义sql

### ISSUE THREAD

**Issue by yhl452493373** [baomidou/mybatis-plus#3715]
我某个字段是逗号分隔的id字符串，类似 id1,id2,id3

在mysql中有 find_in_set(#{userId}, user_id) > 0 这种写法，在mybatis-plus中由于不能自行增加拼接的sql到wrapper中，因此要么用like，要么就在mapper.xml中重写方法。

我的想法是，能否增加一个sql(boolean condition,String sqlString)方法，由开发人员自行拼接一个sql片段进去。如有此方法，我上面描述就能写成：queryWrapper.sql(true,"find_in_set('"+用户id+"', user_ids) > 0")，等效于select * from xxx where find_in_set(#{userId}, user_id) > 0，如此可以少写xml

**Comment by miemieYaho** [comment]
apply

**Comment by yhl452493373** [comment]
原来如此，多谢
