### ISSUE TITLE
使用QueryWrapper.gt()传入时间DateTime查询结果总是0条

### ISSUE THREAD

**Issue by wangx33** [baomidou/mybatis-plus#3719]
### 当前使用版本(必填,否则不予处理)
mybatisplus-spring-boot-starter.version：1.0.5
mybatisplus.version：3.0.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用QueryWrapper.gt()传入时间DateTime 被自动转换成 2021-01-08 16:27:28.0(Timestamp)，最后多了 .0 和数据库Date类型匹配不上，每次查询结果都是0条，复制SQL到PL/SQL中，把参数中的.0删除后可以查询到数据

### 报错信息
没有报错，查询结果总是0，实际Oracle数据库有数据

**Comment by miemieYaho** [comment]
这是mybatis的对应数据类型的typehandler处理的
