### ISSUE TITLE
使用了orderByDesc()或者orderByAsc()，ide会提示：Unchecked generics array creation for varargs parameter

### ISSUE THREAD

**Issue by ice-fun** [baomidou/mybatis-plus#3720]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用条件构造器查询的时候，使用了orderByDesc或者orderByAsc，ide会提示：Unchecked generics array creation for varargs parameter

### 重现步骤(如果有就写完整)
构造查询条件的时候加上orderByDesc就出现，不管参数传了几个都是

### 报错信息
Unchecked generics array creation for varargs parameter

**Comment by qmdx** [comment]
后续版本会删除泛型多参方法，就不在有警告
