### ISSUE TITLE
mbp3.0.5版本saveBatch为什么不传batchSize会出现插入不成功问题。

### ISSUE THREAD

**Issue by heqiang2580** [baomidou/mybatis-plus#3722]
### 当前使用版本(必填,否则不予处理)
mbp3.0.5   springboot2.2.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

现阶段无法进行升级

### 重现步骤(如果有就写完整)

上面一条不传list.size（）则无法插入到数据库信息。
但是传了长度之后就能插入了，想知道为什么会造成这个原因。数据库中没有插入但是id已经被使用过了。

### 报错信息

插入不成功并没有报错信息，也没有执行成功条数，控制台只会输出语句和值

**Comment by qmdx** [comment]
不成功可能是sql没有提交，旧版本不再维护，请自行解决
