### ISSUE TITLE
map类型传值 执行方法没有驼峰转换

### ISSUE THREAD

**Issue by peterzcl** [baomidou/mybatis-plus#3723]
### 当前使用版本 3.4.0
3.4.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://user-images.githubusercontent.com/28745693/124909038-93e69380-e01c-11eb-8b37-f5c861b07ddf.png)

![image](https://user-images.githubusercontent.com/28745693/124909181-bc6e8d80-e01c-11eb-91f1-d0fefa49e7ad.png)

### 重现步骤(如果有就写完整)
yml已经配置 map-underscore-to-camel-case: true
@Bean
public ConfigurationCustomizer configurationCustomizer() {
  return i -> i.setObjectWrapperFactory(new MybatisMapWrapperFactory());
}

**我从方法里传入examId 该方法不可以直接转成exam_id吗  还要 param.put('','')操作吗  就像注释的那样**

### 报错信息

无报错

**Comment by qmdx** [comment]
map-underscore-to-camel-case: true  这个指的的是 map 返回的 key 转驼峰，并不会转为你需要的 question 对象 ，你请需要一个工具类由 驼峰 map 转为 对象
