### ISSUE TITLE
3.4.3.1版本为何page中的排序字段setAscs，setDesc被删除了

### ISSUE THREAD

**Issue by shanzhaozhen** [baomidou/mybatis-plus#3728]
### 当前使用版本(必填,否则不予处理)
3.4.3.1版本为何page中的排序字段setAscs，setDesc被删除了

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.3.1中page代码减少了setAscs，setDesc的方法，导致前端传排序参数排序无效，请问是出于什么考虑删除了的，也没有看到备注说以后会删除的提示

**Comment by shanzhaozhen** [comment]
啊，刚刚回退到3.4.1才发现原来确实说了会删掉，但是如果小项目的话感觉删掉之后影响有点大，因为想前端传参到后台可以直接不转换数据直接搜索，可能对大神们觉得会不太安全吧，删掉了这两个方法的话前端传参只能使用post请求才可以把排序对象传输到后台，get请求构造不了太复杂的参数（orders这个参数包了两层）

**Comment by huayanYu** [comment]
恩，不安全删掉了。自己处理下吧。
