### ISSUE TITLE
3.4.1版本使用h2数据库，删除操作使用LambdaQueryWrapper报错

### ISSUE THREAD

**Issue by yuhouliming** [baomidou/mybatis-plus#3734]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用h2数据库，然后删除代码使用LambdaQueryWrapper 报错

### 报错信息
ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause

**Comment by qmdx** [comment]
请给出具体可重现操作 demo 然后打开
