### ISSUE TITLE
MP 3.0版本 全局字段填充项目启动时报错

### ISSUE THREAD

**Issue by zhongtaogit** [baomidou/mybatis-plus#374]
开发环境 SpringBoot 2.0.3
----------------------------------------------------------------------------
配置文件 ↓ ↓ ↓ ↓
mybatis-plus:
  type-aliases-package: com.edu.domain #domian 对象位置
  mapper-locations: com.edu.dao #dao 接口位置
  global-config:
    db-config:
      column-underline: true #驼峰命名
      field-strategy: not-empty #字段筛选策略不为空
    #自定义填充策略接口实现
    meta-object-handler: com.edu.config.MetaObjectHandlerConfig
----------------------------------------------------------------------------
注入的类↓ ↓ ↓ ↓ ↓

@Component  （通过@Component注解装载Bean）
public class MetaObjectHandlerConfig extends  com.baomidou.mybatisplus.core.handlers.MetaObjectHandler{

	@Override
	public void insertFill(MetaObject metaObject) {
		setFieldValByName("createTime", DateUtil.getDate(), metaObject);
	}

	@Override
	public void updateFill(MetaObject metaObject) {
		setFieldValByName("modifyTime", DateUtil.getDate(), metaObject);
	}

----------------------------------------------------------------------------
控制台报错描述如下↓↓↓
Description:

Failed to bind properties under 'mybatis-plus.global-config.meta-object-handler' to com.baomidou.mybatisplus.core.handlers.MetaObjectHandler:

    Property: mybatis-plus.global-config.meta-object-handler
    Value: com.edu.config.MetaObjectHandlerConfig
    Origin: class path resource [application.yml]:17:26
    Reason: No converter found capable of converting from type [java.lang.String] to type [com.baomidou.mybatisplus.core.handlers.MetaObjectHandler]

Action:

Update your application's configuration
----------------------------------------------------------------------------
另外 MP 3.0 中无法引入 Mybatis中的 MetaObject 对象，该对象不存在

**Comment by qmdx** [comment]
经过测试正常可用，参考 https://gitee.com/baomidou/mybatisplus-spring-boot/commit/096e4e42fbea3a37ce52b66dd8f2b1b5dc64334e
