### ISSUE TITLE
生成的sql语句

### ISSUE THREAD

**Issue by Liang-Dongxing** [baomidou/mybatis-plus#3742]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查询的时候

### 报错信息
不是报错
生成的sql语句
SELECT id,version,sql_type FROM trsom_db_version WHERE (sql_type = 'om')
我想要这样的sql语句 需要``包裹
SELECT `id`,`version`,`sql_type` FROM trsom_db_version WHERE (`sql_type` = 'om')

**Comment by Liang-Dongxing** [comment]
有没有全局开关可以开启这一项

**Comment by c4you** [comment]
《mysql/mybatis解决查询字段为关键字的问题condition》https://blog.csdn.net/luo_yu_1106/article/details/88745054
试下这个

**Comment by qmdx** [comment]
全局配置  https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/config/GlobalConfig.java

```
        /**
         * db字段 format
         * <p>
         * 例: `%s`
         * <p>
         * 对主键无效
         *
         * @since 3.1.1
         */
        private String columnFormat;
```
