### ISSUE TITLE
调用saveBatch方法后，返回的自增逐渐id和实际在表里插入的id不一致

### ISSUE THREAD

**Issue by nikexu** [baomidou/mybatis-plus#3743]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-extension-3.2.0.jar

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
还不考虑升级mybatis-plus的版本

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/52957111/125744451-160a904a-bdb0-4b2c-953c-69b30d6bda28.png)

![image](https://user-images.githubusercontent.com/52957111/125744470-b2ae8c4b-31fc-40c2-a1fa-e894f143a8b3.png)

返回的id值和实际插入数据库的值不一致（没有使用事务之类的影响返回id的操作，就是单纯的批量插入，偶发性问题）

**Comment by qmdx** [comment]
无法重现，请给居于最新版重现 demo 旧版本不在维护
