### ISSUE TITLE
3.x的selecctPage没有执行分页

### ISSUE THREAD

**Issue by xiaonanfeng** [baomidou/mybatis-plus#375]
3.x的selecctPage没有执行分页
参数1
new com.baomidou.mybatisplus.extension.plugins.pagination.Page<>(0, 10)；
参数2
QueryWrapper<Entity> queryWrapper = new QueryWrapper();
queryWrapper.like("col1", "测试").eq("title", "标题");
--执行查询
baseMapper.selectPage(iPage, qw);

**Comment by qmdx** [comment]
你需要配置分配插件，参考 https://gitee.com/baomidou/mybatisplus-spring-boot
