### ISSUE TITLE
@TableLogic  全局逻辑删除是否不够灵活，有方法能够让逻辑删除配置失效吗

### ISSUE THREAD

**Issue by wyf2215087636** [baomidou/mybatis-plus#3751]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter
<mybatis-plus.version>3.4.2</mybatis-plus.version>

### 该问题是如何引起的？

没有发现bug，@TableLogic 注解 采用逻辑删除之后自动全局加上了sql拦截拼上逻辑删除，不知道是否拥有突然配置了逻辑删除
是否拥有忽略的方法？让该注解在执行时失效？可以更加灵活

**Comment by huayanYu** [comment]
无

**Comment by qmdx** [comment]
突然失效那不就是 bug  逻辑删除本质是 update 你想突破逻辑删除限制，可以自定义 sql 即可，mp 逻辑删除目前只对默认自带方法有效
