### ISSUE TITLE
逻辑删除时，updateTimeDb 更新时间自动填充不起作用，逻辑删除操作时间没有自动记录、version也不好用

### ISSUE THREAD

**Issue by tntfyf** [baomidou/mybatis-plus#3754]
### 当前使用版本(必填,否则不予处理)

3.4.3.1
![图片](https://user-images.githubusercontent.com/45613518/126109439-6ae1a86f-d5c3-44eb-b872-48dc271fa175.png)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

给deletedDb字段配置了逻辑删除
![图片](https://user-images.githubusercontent.com/45613518/126108318-4378c7bb-fb5c-4f6a-8430-a6370f8c231d.png)
给updateTimeDb 字段配置了自动填充更新时间
![图片](https://user-images.githubusercontent.com/45613518/126108729-16d23ae9-f918-470d-98e2-45cc566acbbe.png)

配置了自动填充配置
![图片](https://user-images.githubusercontent.com/45613518/126108960-58aad473-7a0e-4895-9b91-b94c16034fec.png)

使用更新方法，ServiceImpl.updateById(entity) ，updateTimeDb 可以自动填充。
使用ServiceImpl.removeById(id)方法，deletedDb 可以自动修改

问题1：但是 deletedDb 自动修改的同时，updateTimeDb 没有更新还是上次的时间。逻辑删除的操作时间没有被记录下来。
问题2：配置了version乐观锁插件、ServiceImpl.updateById(entity) 方法可以使version自动加1但是ServiceImpl.removeById(id)方法不行。

**Comment by taoanqi** [comment]
请问下，有解决办法了吗，遇到了同样的问题

**Comment by qmdx** [comment]
方法一、调用包含实体的删除方法
```
    /**
     * 根据实体(ID)删除
     *
     * @param entity 实体对象
     * @since 3.4.4
     */
    int deleteById(T entity);
```

方法二、https://baomidou.com/guide/crud-interface.html#insertbatchsomecolumn
`int logicDeleteByIdWithFill(T entity);`
