### ISSUE TITLE
mybatis-plus-core的package-info中写的是不添加spring, 实际却添加了

### ISSUE THREAD

**Issue by zohar-soul** [baomidou/mybatis-plus#3755]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

https://github.com/baomidou/mybatis-plus/blob/master/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/package-info.java
仅仅在ReflectionKit中有用到, 感觉不是很有必要, 也和package-info的说明相违背.

是否可以考虑移除掉呢? 单纯因为这个而引入spring不是很有必要( 尤其在本身没有用到spring的项目中而言.

**Comment by huayanYu** [comment]
不是写的不用spring吗

**Comment by zohar-soul** [comment]
> 不是写的不用spring吗

写的是不引入

> 只放mybatis-plus核心代码，不涉及数据库，**不添加spring等**

**Comment by huayanYu** [comment]
> > 不是写的不用spring吗
> 
> 写的是不引入
> 
> > 只放mybatis-plus核心代码，不涉及数据库，**不添加spring等**

    api project(":mybatis-plus-annotation")
    api "${lib.'jsqlparser'}"
    api "${lib.mybatis}"

    implementation "${lib.cglib}"
    implementation "${lib.'spring-aop'}"
    implementation "${lib.'imadcn'}"
    implementation "${lib.'mybatis-ehcache'}"
    implementation "${lib.'mybatis-redis'}"

是implementation ，感觉没啥毛病啊。  或者你觉得怎么改提PR~

**Comment by zohar-soul** [comment]
我的意思不是改gradle, 而是修改ReflectionKit这个类, spring有且仅有这一个类用到了, 而且是3.4.3.1新引入的, 3.4.3.0 还没有

**Comment by zohar-soul** [comment]
@huayanYu 
具体修改的话, 我觉得把这个回滚掉就ok了

https://github.com/baomidou/mybatis-plus/commit/7210b461b23211e6b95ca6de2d846aa392bdc28c#diff-0cdb8c06efd0bf309b228e2287ccd86e622fc307e56fe5635c1ca3ebfbbb58e7R20

**Comment by huayanYu** [comment]
> @huayanYu
> 具体修改的话, 我觉得把这个回滚掉就ok了
> 
> [7210b46#diff-0cdb8c06efd0bf309b228e2287ccd86e622fc307e56fe5635c1ca3ebfbbb58e7R20](https://github.com/baomidou/mybatis-plus/commit/7210b461b23211e6b95ca6de2d846aa392bdc28c#diff-0cdb8c06efd0bf309b228e2287ccd86e622fc307e56fe5635c1ca3ebfbbb58e7R20)

这修复了其他BUG。。。

**Comment by zohar-soul** [comment]
@huayanYu 
因为修复一个bug而引入了整个spring...
这个操作有点不太合适吧? 😂

**Comment by huayanYu** [comment]
@qmdx

**Comment by zohar-soul** [comment]
@qmdx @huayanYu 
这个最后有啥结论了嘛?

**Comment by qmdx** [comment]
> @qmdx @huayanYu
> 这个最后有啥结论了嘛?

关于泛型的处理这块新版未来解决一些递归集成确实用到 spring-core 一个核心工具

你是非 spring 项目使用 mp 吗？？

**Comment by zohar-soul** [comment]
> 关于泛型的处理这块新版未来解决一些递归集成确实用到 spring-core 一个核心工具
> 
> 你是非 spring 项目使用 mp 吗？？

是的, 红帽的quarkus里面要用,  见这个issue ,https://github.com/baomidou/mybatis-plus/issues/3713#issuecomment-877940441
@qmdx

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/6c3bf64518dae727b1809d320373a70c21a973c9

使用注入您使用框架的反射泛型处理方式

`GenericTypeUtils.setGenericTypeResolver(IGenericTypeResolver genericTypeResolver)`

**Comment by zohar-soul** [comment]
> [6c3bf64](https://github.com/baomidou/mybatis-plus/commit/6c3bf64518dae727b1809d320373a70c21a973c9)
> 
> 使用注入您使用框架的反射泛型处理方式
> 
> `GenericTypeUtils.setGenericTypeResolver(IGenericTypeResolver genericTypeResolver)`

非常感谢

**Comment by qmdx** [comment]
> > [6c3bf64](https://github.com/baomidou/mybatis-plus/commit/6c3bf64518dae727b1809d320373a70c21a973c9)
> > 使用注入您使用框架的反射泛型处理方式
> > `GenericTypeUtils.setGenericTypeResolver(IGenericTypeResolver genericTypeResolver)`
> 
> 非常感谢

关注 3.4.3.3 版本今天会发布

**Comment by jxl0506** [comment]
这个问题解决了吗
