### ISSUE TITLE
是否支持对查询结果重新筛选

### ISSUE THREAD

**Issue by rigelzhang** [baomidou/mybatis-plus#3756]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
想问下大佬是否支持类似 select distinct column  from (select * from a where a ) where rownum<100类似这样的查询，因为我想查询去重后的数据，发现没找到类似的用法，求解答

**Comment by huayanYu** [comment]
不支持，复杂sql请手写xml
