### ISSUE TITLE
租户在某些SQL的join部分没有注入租户字段

### ISSUE THREAD

**Issue by qq592304796** [baomidou/mybatis-plus#3757]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
join on没有注入租户字段
只有部分会有这种情况

### 重现步骤(如果有就写完整)
`select d.sku_no as skuNo, d.spu_name as spuName, sum(d.plan_qty) as plan_qty, d.*, ifnull((select sum(stock.`shelf_qty`) from `wms_stock` stock where stock.`stock_qty` > 0 and stock.`area_id` = d.`area_id` and stock.`sku_id` = d.`sku_id` and stock.`stock_status` = d.`stock_status`),0) `shelf_qty`, woro.order_no as orderNo, woro.order_type as orderType, ( select count(1) FROM wms_outbound_rec_amendment wora where wora.warehouse_id = d.warehouse_id and wora.rec_order_id = woro.id ) as amendmentCount, ( select radl.rec_qty FROM wms_outbound_rec_amendment_detail radl WHERE radl.warehouse_id = d.warehouse_id and radl.rec_detail_id = d.id ORDER BY radl.c_t DESC LIMIT 1 ) as amendmentQty, ( select rad.unit_price FROM wms_outbound_rec_amendment_detail rad WHERE rad.warehouse_id = d.warehouse_id and rad.rec_detail_id = d.id ORDER BY rad.c_t DESC LIMIT 1 ) as amendmentUnitPrice from wms_outbound_rec_detail d left join wms_outbound_rec_order woro on d.order_id = woro.id where d.warehouse_id = 1740 and `order_id` in ( 54201 ) and d.`state` = 1 GROUP BY woro.order_no,d.id order by d.id ASC`

**Comment by qmdx** [comment]
你这个 sql 太复杂了，可能是解析器无法识别部分 sql 建议排查自动注入租户条件，手动传入，更多解析支持可以提交 https://github.com/JSQLParser/JSqlParser
