### ISSUE TITLE
selectById异常--严重

### ISSUE THREAD

**Issue by wltsysterm** [baomidou/mybatis-plus#376]
错误信息：
Cause: java.sql.SQLException: sql injection violation, syntax error: ERROR. pos 15, line 1, column 11, token FROM : SELECT id, FROM knowl_search_previewfail_file WHERE id=?
解释：
这张表只有一个id字段，然后通过selectByID就报错了，我理解了是多了个逗号导致了。

**Comment by qmdx** [comment]
单个 Id 字段表无意义啊，不过鉴于为 bug 已修复
