### ISSUE TITLE
@KeySequence 与 业务主键的 setId(XXX) 互斥的问题

### ISSUE THREAD

**Issue by 1252999** [baomidou/mybatis-plus#3761]
### 当前使用版本(必填,否则不予处理)
@KeySequence 与 业务主键的 setId(XXX) 互斥，若要使用业务主键，就删除@KeySequence，若使用数据自生成的主键就仅仅使用@KeySequence。这个限制比较死，能有setId时，@KeySequence就不起作用的方法吗？

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Long  id =  getSequence("SEQ_TMP_ID");
						
...逻辑
save(A表); --虽然setId了值，但是因为A表有@KeySequence，setid就失效而是另外生成了一个值。

...逻辑
save(A的子表，用到了id); --子表和主表无法勾稽。

**Comment by qmdx** [comment]
默认的  id_worker  uuid 就是你要的效果，自定义主键就是限制的
