### ISSUE TITLE
建议去掉JsqlParser的依赖，改用其他的

### ISSUE THREAD

**Issue by WenSteven** [baomidou/mybatis-plus#3764]
### 当前使用版本(必填,否则不予处理)

不管哪个版本，依赖的JsqlParser总会出现各种bug

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

依赖的JsqlParser 出bug，导致无法使用一些sql,间接影响到mybatis-plus的使用

**Comment by miemieYaho** [comment]
那你来写一个好了

**Comment by WenSteven** [comment]
> 那你来写一个好了

听同事说你跟狗一样，还真是。。

**Comment by miemieYaho** [comment]
我看你俩真的适合一直呆在狗窝里相亲相爱
