### ISSUE TITLE
自定义ID主键新增时没有调用

### ISSUE THREAD

**Issue by guchengod** [baomidou/mybatis-plus#3765]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自定义ID主键新增时没有调用

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/21252591/126425326-cac932af-aeb2-48f5-8392-a4ec7293c6b1.png)

![image](https://user-images.githubusercontent.com/21252591/126425310-1ebac60a-52b0-4d93-9191-1a42ff26a801.png)

### 报错信息
因为没有调用主键自定义主键,每次默认为0,导致主键冲突

**Comment by huayanYu** [comment]
怎么自定义的啊，相关配置啊

**Comment by guchengod** [comment]
> 怎么自定义的啊，相关配置啊

实现IdentifierGenerator 接口, 调用的分布式主键生成器

**Comment by qmdx** [comment]
参考使用文档 https://baomidou.com/guide/sequence.html
