### ISSUE TITLE
jsqlParser解析sql异常导致分页排序问题

### ISSUE THREAD

**Issue by zero-wsh** [baomidou/mybatis-plus#3767]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库：sqlservre2012
SQL: select id,name,[order] from t_table

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/44697042/126611714-c4131a99-9eb3-44a7-b8ff-e64aed35866d.png)
在这个位置执行sql就能重现；官方回复地址：https://github.com/JSQLParser/JSqlParser/issues/1281

### 报错信息
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "[" "["

**Comment by huayanYu** [comment]
mp无法修复
