### ISSUE TITLE
entity的文件名能自定义吗?

### ISSUE THREAD

**Issue by 675760585** [baomidou/mybatis-plus#377]
### 需求简述
entity的文件名能自定义吗

### 背景简述
比如生成的User.java  我的需求是UserEntity.java，希望也能支持自定义

### 解决分析
ConfigBuilder.processTable() 这个方法是否添加条件支持就可以了？

**Comment by qmdx** [comment]
3.0 支持 https://github.com/baomidou/mybatis-plus/commit/a4b1111517617044b38f08e3445abe8360eae560
