### ISSUE TITLE
自定义接口没有继承IService，但创建了MybatisMapperProxy代理类

### ISSUE THREAD

**Issue by cdhcrs** [baomidou/mybatis-plus#3770]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
UsersCloudService没有继承IService，但却生成了一个名为usersCloudService的MybatisMapperProxy代理类。请问这是bug吗，这导致我用beanName注入usersCloudService时异常。
```java
public interface UsersService extends IService<UsersEntity> {
}
```
```java
@FeignClient(name = "${spring.application.name}")
public interface UsersCloudService {
}
```
```java
public class UsersServiceImpl extends ServiceImpl<UsersMapper, UsersEntity> implements UsersService, UsersCloudService{
}
```

### 重现步骤(如果有就写完整)
![微信截图_20210723111139](https://user-images.githubusercontent.com/42325042/126733514-d07c3b77-aff2-4be7-ace8-59e42eba7dbd.png)

**Comment by cdhcrs** [comment]
刚刚创建了一个新的接口，没有在任何地方被使用，但是还是被创建了代理类。后来经过排查，是这个类被@MapperScan扫描到了。。。mp的mapper接口不是会继承BaseMapper吗，应该做一个判断吧，现在是只要扫描到了就代理

**Comment by miemieYaho** [comment]
你用mybatis也一样的,只会判断被扫到的是不是interface
