### ISSUE TITLE
countSql再where中没有用到left join表时，会把left join优化掉，但是left join表会在order by中使用，这样就会报错了

### ISSUE THREAD

**Issue by keliubo** [baomidou/mybatis-plus#3775]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
countSql再where中没有用到left join表时，会把left join优化掉，但是left join表会在order by中使用，这样就会报错了
### 重现步骤(如果有就写完整)
<select>
select cr.id ,
               cr.setting_room_id ,
               cr.monitor_student_id ,
        wcd.num         ,
               wcd.semester_id
        from xs_duty.week_civilized_dorm wcd
inner join xs_duty.civilized_room cr on wcd.id = cr.civilized_dorm_id and wcd.deleted = 0
         where cr.deleted = 0
        <if test="civilizedRoomIds != null and civilizedRoomIds.size() != 0">
and cr.id in
            <foreach collection="civilizedRoomIds" item="civilizedRoomId" close=")" open="(" separator=",">
                #{civilizedRoomId,jdbcType=BIGINT}
            </foreach>
</if>
        order by wcd.semester_id desc, wcd.num desc
<if test="settingRoomIdSort != null and settingRoomIdSort.size() != 0">
            <foreach collection="settingRoomIdSort" item="c" open=",Field(cr.setting_room_id," close=")"
                     separator=",">
                #{c,jdbcType=BIGINT}
            </foreach>
</if>
    </select>

**Comment by totoro52** [comment]
https://github.com/baomidou/mybatis-plus/issues/3737

我已经提过这个问题，但是没有得到回复，可能作者认为这不是一个BUG吧，可以关闭掉分页的优化，或者带上连表的那个表的条件 具体看我的issues

**Comment by qmdx** [comment]
up
