### ISSUE TITLE
异常没有抛出导致查询结果有误

### ISSUE THREAD

**Issue by xingfenhao** [baomidou/mybatis-plus#378]
PaginationInterceptor.queryTotal
异常场景还原：
 try (PreparedStatement statement = connection.prepareStatement(sql)) {
            DefaultParameterHandler parameterHandler = new MybatisDefaultParameterHandler(mappedStatement, boundSql.getParameterObject(), boundSql);
            parameterHandler.setParameters(statement);
            int total = 0;
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    total = resultSet.getInt(1);
                }
            }
            page.setTotal(total);
            /*
             * 溢出总页数，设置第一页
			 */
            int pages = page.getPages();
            if (overflowCurrent && (page.getCurrent() > pages)) {
                page = new Pagination(1, page.getSize());
                page.setTotal(total);
            }
        } catch (Exception e) {
            logger.error("Error: Method queryTotal execution error !", e);
        }
如上代码， statement.executeQuery()执行sql的列有重复,则会有异常：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'status'，
但是catch后没有抛出，导致 page.total默认0

**Comment by qmdx** [comment]
感谢反馈已修复 https://github.com/baomidou/mybatis-plus/commit/1bf620fcb43dc86b7414ed4161c2340820b2c0cf
