### ISSUE TITLE
细分mapper或者service

### ISSUE THREAD

**Issue by AnLiBoBo** [baomidou/mybatis-plus#3780]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
有部分业务,数据库是不允许被更新或者插入,但是继承了IService之后,是会有这种功能
所以能不能把service更加细致的分开一下, 比如分成 IQueryService IUpdateService ISaveService 这样的

**Comment by huayanYu** [comment]
可以自己拆分啊

**Comment by AnLiBoBo** [comment]
> 可以自己拆分啊

是的,现在就是自己拆分了,只是觉得mp是个很好的项目,多一些issue能让mp更完善

**Comment by qmdx** [comment]
mapper 层才分注入参考 https://baomidou.com/guide/sql-injector.html 

service 自行处理
