### ISSUE TITLE
strategyConfig.setEntityBooleanColumnRemoveIsPrefix(true)未生效，is_deleted字段还是映射成了isDeleted实体类字段

### ISSUE THREAD

**Issue by DamonEvil** [baomidou/mybatis-plus#3781]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter：3.4.3
mybatis-plus-generator：3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
strategyConfig.setEntityBooleanColumnRemoveIsPrefix(true)
未生效，is_deleted字段还是映射成了isDeleted实体类字段

### 重现步骤(如果有就写完整)
如上

### 报错信息
无

**Comment by qmdx** [comment]
请使用 https://gitee.com/baomidou/generator 旧版本不再维护，另外有问题在这个仓库下 issue
