### ISSUE TITLE
对数据进行分页排序时出现数据错乱！

### ISSUE THREAD

**Issue by daquanzheng** [baomidou/mybatis-plus#3783]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
对数据进行分页 并按时间排序  当数据库中两个数据的时间（精确到秒）相同时，最后返回结果会出现2个相同的数据（不同的页码当中，如第1页有这个数据 第二页也有可能有这个数据）

### 重现步骤(如果有就写完整)
数据库中第6条数据与第7条数据的时间相同，分页并按时间排序时（pageSize=6时），第一页的最后一个数据与第二页的数据是同一个数据（id相同）

### 报错信息

没有报错信息，只是返回的数据错乱了！

**Comment by miemieYaho** [comment]
这你得报给数据库

**Comment by daquanzheng** [comment]
> 这你得报给数据库

数据库是mysql

**Comment by yuxiaobin** [comment]
排序字段,最后需要加一个唯一值,比如ID

**Comment by yuxiaobin** [comment]
很多数据库都会有这个问题(比如ORACLE等),排序的时候需要注意

**Comment by daquanzheng** [comment]
多谢大神！

**Comment by harrychan19** [comment]
mysql本身执行sql是不会出错的
