### ISSUE TITLE
Mybatis-plus+ShardingSphere枚举类型处理器失效

### ISSUE THREAD

**Issue by ezio7584** [baomidou/mybatis-plus#3786]
### 当前使用版本(必填,否则不予处理)
Mybatis-plus 3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目添加ShardingSphere5.0.0-bate进行分表功能后,@EnumValue与IEnum接口均不会处理查询结果,使用mybatis-plus 3.3.1tmp则正常

**Comment by qmdx** [comment]
非 mp 问题
