### ISSUE TITLE
mybatis-plus-generator项目TableField包名错误

### ISSUE THREAD

**Issue by 675760585** [baomidou/mybatis-plus#379]
### 产生问题
com.baomidou.mybatisplus.annotations.TableField 找不到，包名错误希望更正！
com.baomidou.mybatisplus.annotation.TableField

**Comment by qmdx** [comment]
感觉反馈已修复 https://github.com/baomidou/mybatis-plus/commit/091fb1e30768f3791fe1987f21fe541f8ffb91de
