### ISSUE TITLE
能否支持ClickHouse的9000端口的驱动

### ISSUE THREAD

**Issue by xuhongapple** [baomidou/mybatis-plus#3791]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.0</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
不支持的类型
https://housepower.github.io/ClickHouse-Native-JDBC/zh/guide/jdbc_driver.html

### 重现步骤(如果有就写完整)
适用阿里druid数据源用ClickHouse-Native-JDBC驱动，执行sql报错

### 报错信息
SQLFeatureNotSupportedException

**Comment by miemieYaho** [comment]
java8新时间类型?

**Comment by xuhongapple** [comment]
> java8新时间类型?

不是哦，是jar包驱动的问题

**Comment by miemieYaho** [comment]
那你找我们没用,执行sql以及返回值封装都是mybatis的事
