### ISSUE TITLE
分页参数中的private List<OrderItem> orders = new ArrayList<>()如何使用

### ISSUE THREAD

**Issue by qq984876303** [baomidou/mybatis-plus#3792]
### 当前使用版本(必填,否则不予处理)
这个传参应当如何传？如何才能实现前端控制排序呢

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

这个传参应当如何传？如何才能实现前端控制排序呢

### 重现步骤(如果有就写完整)
这个传参应当如何传？如何才能实现前端控制排序呢

### 报错信息
这个传参应当如何传？如何才能实现前端控制排序呢

**Comment by lizeze** [comment]
https://github.com/lizeze/mp-search 

 希望对你有用吧

**Comment by Inighty** [comment]
这个应该是后端接收前端参数后自己组装吧
page.setOrders(Arrays.asList(OrderItem.asc("id"), OrderItem.asc("name")));

**Comment by bunsl** [comment]
用page直接接收存在漏洞
接收方式 ?orders[0].asc=true&orders[0].column=id

https://www.freebuf.com/articles/web/278585.html

**Comment by qmdx** [comment]
自己做一个类型转换后台组装 OrderItem 对象，最好不要前台直接传入有注入风险
