### ISSUE TITLE
自定义ID生成器 required a single bean, but 2 were found

### ISSUE THREAD

**Issue by onvertex** [baomidou/mybatis-plus#3793]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

原来版本是3.4.2，升级3.4.3后自定义生成器异常
![image](https://user-images.githubusercontent.com/31512349/128022123-79d7ba53-359a-4dcb-a0fb-e91d86e0035a.png)
看了源码发现多了IdentifierGeneratorAutoConfiguration配置类里面也注入了同样的IdentifierGenerator从而导致下面错误信息
![image](https://user-images.githubusercontent.com/31512349/128022349-538ec477-bec2-4601-a84a-8218e69acd90.png)

### 报错信息
<img width="1337" alt="WX20210803-211655@2x" src="https://user-images.githubusercontent.com/31512349/128022020-ba527364-6625-4abc-86b3-8e0b844e10a9.png">

**Comment by miemieYaho** [comment]
把你自己的类的 order 注解去掉呢

**Comment by onvertex** [comment]
> 把你自己的类的顺序注释掉呢

去掉了 不行

**Comment by nancheung97** [comment]
@AutoConfigureBefore(IdentifierGeneratorAutoConfiguration.class)

方法1：Configuration类不能使用@order
方法2：将CustomIdGenerator显示定义bean，使用@Primary

**Comment by qmdx** [comment]
upp
