### ISSUE TITLE
postgresql数据库，mybatisplus使用save方法插入数据，表里数据新增成功了，但是返回结果是false

### ISSUE THREAD

**Issue by qpkscf** [baomidou/mybatis-plus#3799]
### 当前使用版本(必填,否则不予处理)
mybatis plus版本3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

mybatisplus使用save方法插入数据，库里数据新增成功，但是返回结果是失败

### 报错信息

无报错信息，返回false

**Comment by miemieYaho** [comment]
有复现demo吗?

**Comment by huayanYu** [comment]
无回复关闭

**Comment by dulm** [comment]
https://www.cnblogs.com/wyq178/p/8652443.html

insert 返回false, 查到最后是这个. 请问是正常现象么? 是否最佳实践是编码时不用管返回值.

> 无回复关闭
