### ISSUE TITLE
PerformanceInterceptorxin性能分析插件，使用Druid数据源配置了filters后，输出的sql是对象地址

### ISSUE THREAD

**Issue by alexluojian** [baomidou/mybatis-plus#38]
![qq 20170423083056](https://cloud.githubusercontent.com/assets/7976180/25309398/44acccbe-27ff-11e7-9a83-3fdfc9d967e6.png)
![qq 20170423083126](https://cloud.githubusercontent.com/assets/7976180/25309397/44ac7962-27ff-11e7-851f-6648bf200e42.png)
![qq 20170423082902](https://cloud.githubusercontent.com/assets/7976180/25309399/44b2fc88-27ff-11e7-9fe5-ae90b999c064.png)

**Comment by Caratacus** [comment]
升级版本或降低版本,该问题是某版本改动导致

**Comment by xusheng1987** [comment]
我升级到2.1.4，这个问题依旧存在啊
