### ISSUE TITLE
再次生成，不覆盖

### ISSUE THREAD

**Issue by a893359278** [baomidou/mybatis-plus#380]
需求是这样的：
通常，在dao层，我们会实现一些另外的方法。
然后，突然表结构需要改动。 这个时候，需要重新生成 dao层代码。
不知道。 mybatis-plus 能不能做个。 不要去覆盖我原先已经写好的代码。
只要把原先通用的代码，再次覆盖就行。这个可以做到吗？
service层、controller 层的代码也是类似
感谢，开发者， 开发下这个新功能呗！！！！

**Comment by qmdx** [comment]
mp 的通用类方法只是继承即可无方法，因此不存再次生成的必要
