### ISSUE TITLE
国产化适配问题

### ISSUE THREAD

**Issue by hatakes** [baomidou/mybatis-plus#3803]
### 当前使用版本(必填,否则不予处理)
mybatisplus.version 2.1.9
mybatisplus.spring.boot.version 1.0.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

公司项目做国产化适配,想问一下,mp是否支持国产的神通数据库

### 报错信息
![1628155927(1)](https://user-images.githubusercontent.com/26193001/128327831-f281755b-69ad-4409-b626-ae94641462da.png)

**Comment by huayanYu** [comment]
支持的吧，主要是分页功能

**Comment by hatakes** [comment]
![image](https://user-images.githubusercontent.com/26193001/128484336-c020eae1-526a-4e43-b11b-1174c13f1d22.png)
看着好像是不支持的啊,不知道是不是版本问题,还是说最新版也是这样的

**Comment by hatakes** [comment]
![image](https://user-images.githubusercontent.com/26193001/128484799-14452c45-1b7a-4ead-8be2-77f26ef61733.png)
我找个版本看着是不支持的,最新版的也是没有支持吗

**Comment by miemieYaho** [comment]
3.x 只有分页插件区分数据库
