### ISSUE TITLE
无法获取通用字段的列名映射

### ISSUE THREAD

**Issue by LeonardoEzio** [baomidou/mybatis-plus#3808]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
public static TableInfo getTableInfo(Class<?> clazz) {
        if (clazz != null && !ReflectionKit.isPrimitiveOrWrapper(clazz) && clazz != String.class) {
            TableInfo tableInfo = (TableInfo)TABLE_INFO_CACHE.get(ClassUtils.getUserClass(clazz));
            if (null != tableInfo) {
                return tableInfo;
            } else {
                for(Class currentClass = clazz; null == tableInfo && Object.class != currentClass; tableInfo = (TableInfo)TABLE_INFO_CACHE.get(ClassUtils.getUserClass(currentClass))) {
                    currentClass = currentClass.getSuperclass();
                }

                if (tableInfo != null) {
                    TABLE_INFO_CACHE.put(ClassUtils.getUserClass(clazz), tableInfo);
                }

                return tableInfo;
            }
        } else {
            return null;
        }
    }

### 重现步骤(如果有就写完整)
无法通过lambda表达式获取通用字段的列名映射

**Comment by qmdx** [comment]
描述不清楚，请重新详细阐述需求或者bug  然后打开
