### ISSUE TITLE
逻辑删除的问题

### ISSUE THREAD

**Issue by oz-wdai** [baomidou/mybatis-plus#381]
在使用逻辑删除的时候，在bean中配置了LogicSqlInjector，然而开启了逻辑删除之后，一旦使用QueryMapper对数据进行查询的时候，就会出现问题
mapper.selectPage(new Page<>(1L, 2L),
        new QueryWrapper<StrategyBPMNDefinition>().like("name", name).like("portfolioType", portfolioType))
      .getRecords()

生成的SQL有错误
...  FROM strategyBPMNDefinition WHERE deleted='N'name LIKE ? AND portfolioType LIKE ?

这里的deleted为逻辑删除字段，并没有如文档所说，放到最后，而是直接放到了所有查询条件之前。

不知道是否是我的用法不正确，希望指正

**Comment by qmdx** [comment]
什么版本？

**Comment by qmdx** [comment]
请试试快照 3.0-beta-SNAPSHOT 该问题已修复
