### ISSUE TITLE
MybatisPlusInterceptor一直报红，引入不了相关类

### ISSUE THREAD

**Issue by lvgitt** [baomidou/mybatis-plus#3810]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
新项目，第一次使用，在同事电脑上打开一样引入不进来

### 重现步骤(如果有就写完整)
引入
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3.1</version>
        </dependency>
引入官方相关分页插件配置类
@Configuration
public class MybatisPlusConfig {
    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }
}
发现报红线，然后检查maven依赖冲突项，没有任何冲突，如图1；
然后清理依赖包，重新引入，依然报红；
然后清理idea缓存，重新打开，依然报红
### 报错信息

Cannot resolve symbol 'MybatisPlusInterceptor'

**Comment by lvgitt** [comment]
![Uploading image.png…]()

**Comment by lvgitt** [comment]
![image](https://user-images.githubusercontent.com/44693144/128672767-145bd711-5036-4a07-b293-f61309488350.png)

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/128672976-dbf095b5-05b4-44bb-8f57-5417a11fc87d.png)
那这叫什么?

**Comment by lvgitt** [comment]
3.4.3版本下mybatis-plus-boot-starter依赖所包含的mybatis-plus版本怎么会是3.3.1呢？
目前我的解决方法是先把3.3.1的mybatis-plus的依赖排除，再重新引入3.4.3版本的mybatis-plus
![image](https://user-images.githubusercontent.com/44693144/128677859-2b319fb0-cf0c-4185-a418-bce3441297d5.png)

**Comment by miemieYaho** [comment]
怎么会是3.3.1?这你应该问你自己哦
