### ISSUE TITLE
jdk16使用QueryWrapper<>()的lambda表达式条件查询报错

### ISSUE THREAD

**Issue by zhezhic** [baomidou/mybatis-plus#3811]
### 当前使用版本(必填,否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3.1</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
jdk16使用QueryWrapper<>()的lambda表达式条件查询报错

### 重现步骤(如果有就写完整)
        User user = new User();
        user.setEmail("2555538809@qq.com");
        QueryWrapper<User> wrapper = new QueryWrapper<>();
        wrapper.lambda().eq(User::getEmail, user.getEmail());
        User user1 = userMapper.selectOne(wrapper);

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.ExceptionInInitializerError]

**Comment by YunlongChen** [comment]
有没有使用lombok呢，我使用了lombok，也出现了这个问题，我看了看可能跟lombok有关系

**Comment by zhezhic** [comment]
不使用lombok后还是同样的问题，jdk退用11后没问题

**Comment by WangZuQi** [comment]
3.4.2 版本的 lombok可以

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/issues/3558
