### ISSUE TITLE
字段是否允许支持注解方式进行模糊查询

### ISSUE THREAD

**Issue by LLLLLLong** [baomidou/mybatis-plus#3813]
### 当前使用版本(必填,否则不予处理)

3.3.1或者更高版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

如果前端需要进行模糊查询，后端查询条件还要重写.like(column, val)
若能提供注解支持实体模版like查询，则代码会优雅很多

### 重现步骤(如果有就写完整)

无

### 报错信息

无

**Comment by nancheung97** [comment]
那如果这个字段同时有模糊和精确查询的需求怎么做呢

**Comment by qmdx** [comment]
`@TableField(condition = SqlCondition.LIKE)`
