### ISSUE TITLE
springmvc集成，idea的debug模式下无法启动报错循环依赖illegal cyclic inheritance dependencies

### ISSUE THREAD

**Issue by zhangzihang** [baomidou/mybatis-plus#3815]
### 当前使用版本(必填,否则不予处理)

版本3.4.1，用法为springmvc集成，spring 版本5.2.11.RELEASE，tomcat版本9.0.26,idea版本2021.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在idea上，普通启动不会报错，debug或者jrebel的debug启动会报如下错误

### 重现步骤(如果有就写完整)
debug或者jrebel deubg
![QQ截图20210812152454](https://user-images.githubusercontent.com/34065852/129155348-0d819682-36f1-4c97-b5c7-7b77fce79fb2.png)

### 报错信息

`Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/CM_prevalence_distribute_war_exploded] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [com.baomidou.mybatisplus.extension.injector.methods.additional.LogicDeleteByIdWithFill->com.baomidou.mybatisplus.extension.injector.methods.LogicDeleteByIdWithFill->com.baomidou.mybatisplus.extension.injector.methods.additional.LogicDeleteByIdWithFill]`

**Comment by zhangzihang** [comment]
这个所谓的循环依赖，我看是两个不同的类，不明白怎么就循环依赖了

**Comment by huayanYu** [comment]
建议给个能复现的完整demo

**Comment by zhangzihang** [comment]
> 建议给个能复现的完整demo

没事了。。中途换plus但不重新构建工件，导致lib下出现了两个版本的包造成的包冲突，不好意思智障了
