### ISSUE TITLE
支持MySQL原生JSON字段

### ISSUE THREAD

**Issue by zxcvbnm3057** [baomidou/mybatis-plus#3818]
请问最新版mybatisplus是否支持操作MySQL原生JSON字段？哪里有demo或文档呢，我尝试使用String、JSONObject、JSONArray类型均无法直接入库，且没有找到直接查询JSON文档内容的方法，是否有计划支持呢？

我使用的版本：com.baomidou:mybatis-plus-boot-starter:3.4.3.1

**Comment by huayanYu** [comment]
需要和原生mybatis一样自定义typeHandler啊

**Comment by wangjia2016** [comment]
查询支持吗？
