### ISSUE TITLE
通用Mapper封装的通用IServiceImpl查询数据与Xml配置的查询不同

### ISSUE THREAD

**Issue by hanzhenchaoGit** [baomidou/mybatis-plus#382]
问题场景：为了实现数据插入之后对插入数据以及数据库已有数据进行汇总，将汇总结果写入专门的汇总表

就是在同一个事物中，批量插入了一堆数据，然后用通用service查询selectByMap 查出来的数据包含事物未提交的数据以及数据库里面已经持久化的数据，然后下面又自己写了一个Xml的查询，发现xml的语句是查不到未提交的数据的，未出现脏读，这是什么原因呢

**Comment by qmdx** [comment]
事务未提交数据库无法查询是正常的，否则事务有啥意义

**Comment by hanzhenchaoGit** [comment]
但是baseMapper的查询逻辑跟mapper.xml的逻辑不一致吗  前者可以查出带脏读的数据 也就是事物中的数据 而后者是查询已经持久化的数据

**Comment by qmdx** [comment]
请确定你表数据真实开启了事务
