### ISSUE TITLE
集成测试失败

### ISSUE THREAD

**Issue by primejava** [baomidou/mybatis-plus#3822]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

@SpringBootTest可以测试通过
希望只加载必要的类来提高测试速度，但是
@SpringBootTest(classes={UserServiceImpl.class})测试失败

### 报错信息
Unsatisfied dependency expressed through field 'baseMapper'

**Comment by miemieYaho** [comment]
不支持

**Comment by primejava** [comment]
不明白为什么不支持，只是个注入问题

**Comment by lehug** [comment]
挖坟，为啥不支持呢
