### ISSUE TITLE
CURD 的返回值类型都代表着什么？

### ISSUE THREAD

**Issue by ddxl123** [baomidou/mybatis-plus#3823]
### 当前使用版本(必填,否则不予处理)
com.baomidou:mybatis-plus-boot-starter:3.4.3.1

官方文档和源码里的注释都没有关于返回值的说明。

关于 IService:
save: 
![image](https://user-images.githubusercontent.com/33950845/129635114-db5363bc-34fd-413c-a085-fb8f06c4fb0b.png)
remove:
![image](https://user-images.githubusercontent.com/33950845/129635163-9de0dadb-52c0-40ac-a60b-748e1bc3c452.png)
update;
![image](https://user-images.githubusercontent.com/33950845/129635287-3fceaa36-2b5a-42ef-ae0d-4838cc3335fc.png)

关于 Mapper:
insert:
![image](https://user-images.githubusercontent.com/33950845/129635389-d26ea7be-d27f-44ce-a375-c18962d2364e.png)
delete:
![image](https://user-images.githubusercontent.com/33950845/129635419-619f9adb-68ef-4e3f-b6a0-2847cc676031.png)
update:
![image](https://user-images.githubusercontent.com/33950845/129635443-3e6929a9-6ccf-4395-85b9-8c0d4d4da5db.png)

返回值为 Boolean 类型的都分别代表什么？返回 true 是存在 error 还是处理的条数不为0？

返回值为 Int 类型的都分别代表什么？是数量还是 id？

java 里没有 kotlin 的可空类型，因此源码都写着 Boolean/Int，那么使用 kotlin 需不需要判断为 null 的情况吗？

虽然我可以自己测试吧，但是还是建议官方能在文档或注释里说明一下。

**Comment by huayanYu** [comment]
是否成功
