### ISSUE TITLE
逻辑删除字段如果是字符串，不支持逻辑删除值为now函数

### ISSUE THREAD

**Issue by lockelee1015** [baomidou/mybatis-plus#3824]
### 当前使用版本(必填,否则不予处理)

v3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

目前如果配置中的逻辑删除值配置的是now()，只对datetime类型生效，但是datetime做唯一索引的话又有问题。
所以期望使用字符串类型作为逻辑删除值，并且配置 logic_deleted_value为now()或者unix_timestamp().

### 重现步骤(如果有就写完整)
Data Object 和数据库表结构 设置 is_deleted 为字符串类型
mybatis-plus 配置 logic-deleted-value 为now()
执行逻辑删除后，发现值确实为now()，而不是当时的时间

### 报错信息
无

**Comment by miemieYaho** [comment]
太混乱不支持

**Comment by mccray-s** [comment]
目前有什么解决办法吧，我现在想把逻辑删除的值设置为 unix_timestamp()
