### ISSUE TITLE
针对动态表名插件优化

### ISSUE THREAD

**Issue by qmdx** [baomidou/mybatis-plus#3826]
针对动态表名插件优化 https://github.com/baomidou/mybatis-plus/pull/3800

**Comment by liming0** [comment]
刚好看到了，希望在生成动态表名那里可以获取到参数，因为很多情况下动态表名需要根据参数取模

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/115780793cdb6cf287e58651ea8a0fda4a5a14e9
