### ISSUE TITLE
自动建表

### ISSUE THREAD

**Issue by asm2356** [baomidou/mybatis-plus#3827]
mybatis plus 不支持 类似于hibernate 自动建表功能使用actable jar冲突，索引注解

**Comment by qmdx** [comment]
利用注解方式建表尝试处理过，问题比较多而且需要兼容各种数据库，放弃该方案。

推荐使用 flyway 或者 mp 企业版 https://baomidou.com/guide/mybatis-mate.html#%E8%A1%A8%E7%BB%93%E6%9E%84%E8%87%AA%E5%8A%A8%E7%BB%B4%E6%8A%A4
