### ISSUE TITLE
Formated deleted sql 注释里写了可以override by subclass,但是方法是private的

### ISSUE THREAD

**Issue by lockelee1015** [baomidou/mybatis-plus#3828]
https://github.com/baomidou/mybatis-plus/blob/2cbef3e0104801e50afec832b6668c46286831cb/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/metadata/TableInfo.java#L423

这个地方怎么override呢，求一个case

**Comment by lockelee1015** [comment]
/**
     * format logic delete SQL, can be overrided by subclass
     * github #1386
     *
     * @param isWhere true: logicDeleteValue, false: logicNotDeleteValue
     * @return sql
     */
    private String formatLogicDeleteSql(boolean isWhere) {
        final String value = isWhere ? logicDeleteFieldInfo.getLogicNotDeleteValue() : logicDeleteFieldInfo.getLogicDeleteValue();
        if (isWhere) {
            if (NULL.equalsIgnoreCase(value)) {
                return logicDeleteFieldInfo.getColumn() + " IS NULL";
            } else {
                return logicDeleteFieldInfo.getColumn() + EQUALS + String.format(logicDeleteFieldInfo.isCharSequence() ? "'%s'" : "%s", value);
            }
        }
        final String targetStr = logicDeleteFieldInfo.getColumn() + EQUALS;
        if (NULL.equalsIgnoreCase(value)) {
            return targetStr + NULL;
        } else {
            return targetStr + String.format(logicDeleteFieldInfo.isCharSequence() ? "'%s'" : "%s", value);
        }
    }

**Comment by qmdx** [comment]
处理这个 public String getLogicDeleteSql(boolean startWithAnd, boolean isWhere)   后续开放
