### ISSUE TITLE
希望支持select添加class参数，转化为对应java类型

### ISSUE THREAD

**Issue by moil-xm** [baomidou/mybatis-plus#3829]
### 当前使用版本(必填,否则不予处理)

3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

希望支持select添加class参数，转化为对应java类型

### 重现步骤(如果有就写完整)

希望支持select添加class参数，转化为对应java类型

### 报错信息

希望支持select添加class参数，转化为对应java类型

**Comment by miemieYaho** [comment]
mybatis不支持
