### ISSUE TITLE
插入数据的时候用什么方法可以返回主键啊

### ISSUE THREAD

**Issue by shenshihala** [baomidou/mybatis-plus#383]
![image](https://user-images.githubusercontent.com/25096686/42364131-b5342680-812c-11e8-8293-da27313ca75d.png)

**Comment by Bo9013** [comment]
entity.getId()

**Comment by qmdx** [comment]
如上

**Comment by cztchoice** [comment]
注意配置，@TableId(type = IdType.AUTO)

默认这个type为IdType.NONE，无法起效

**Comment by GuoDapeng** [comment]
兄弟，你明白了吗？我看文档，谷歌百度各种查，实在是太难了……

**Comment by GuoDapeng** [comment]
insert 后如何返回主键
insert 后主键会自动 set 到实体的 ID 字段，所以你只需要 getId() 就好

但是 getId() 这个方法我找不到……

**Comment by shenshihala** [comment]
> insert 后如何返回主键
> insert 后主键会自动 set 到实体的 ID 字段，所以你只需要 getId() 就好
> 
> 但是 getId() 这个方法我找不到……

你插入的对象应该对应的是数据库的某张表吧，这个表应该有个字段被设置为主键，这个主键字段不一定是叫id，也有可能是别的名字，看你的表字段如何命名的，例如 user_id等等

**Comment by GuoDapeng** [comment]
谢谢你这么快的回复我，我也是实在是没办法了……试验了6个多小时都没得到返回的主键，不过倒是正常的写库了……

user_up_id 这个是我的主键，我知道不应该拿自己的代码问别人的，但是我身边确实没有懂这个的……

![截屏2020-05-22 下午4 27 08](https://user-images.githubusercontent.com/7477750/82647757-3c833980-9c49-11ea-82d0-22c057dd2181.png)

**Comment by GuoDapeng** [comment]
> 注意配置，@TableId(type = IdType.AUTO)
> 
> 默认这个type为IdType.NONE，无法起效

这个人是正确的，下面这个警告提示了，这个警告没了，id也知道更新了……

```
2020-05-22 22:51:49.181  WARN 6677 --- [  restartedMain] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: xxx.xxx.xxx.
```
