### ISSUE TITLE
在使用分页插件时，发现如果未查到数据时，直接返回

### ISSUE THREAD

**Issue by ZhangQuankang** [baomidou/mybatis-plus#3833]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
配置多个插件，发现后续插件不执行

### 重现步骤(如果有就写完整)
if (page.isSearchCount()) {
            SqlInfo sqlInfo = SqlParserUtils.getOptimizeCountSql(page.optimizeCountSql(), countSqlParser, originalSql);
            this.queryTotal(sqlInfo.getSql(), mappedStatement, boundSql, page, connection);
            if (page.getTotal() <= 0) {
                return null;
            }
   }
 查询时，未查询到数据，直接return null，导致后续插件不会执行

**Comment by miemieYaho** [comment]
就这样的,不然你就放分页前面
