### ISSUE TITLE
数据库取值转换成枚举属性报错

### ISSUE THREAD

**Issue by loren-codes** [baomidou/mybatis-plus#3834]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库取值转换成枚举属性报错。

### 报错信息
Error attempting to get column 'tm_status' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: 不支持此操作。

**Comment by qmdx** [comment]
无法重现，更多查看

https://github.com/baomidou/mybatis-plus-samples
