### ISSUE TITLE
查询指定几个字段的建议

### ISSUE THREAD

**Issue by Bo9013** [baomidou/mybatis-plus#384]
### 需求简述
表中字段很多,查询的时候只有几个字段不需要查询,使用QueryWrapper.select()方法需要设置很长的字段名,可不可以添加一个notSelect()方法来指定不需要查询的字段名

### 背景简述
1.分页查询数据.
2.通过QueryWrapper.select()方法设置需要查询的字段名称,表中字段很多时,需要设置很长的字段名称.

### 解决分析
添加一个notSelect()方法来指定不需要查询的字段名

**Comment by fuyong859050943** [comment]
你要查很多字段, 那多一两个字段有多大影响呢?我个人感觉这个需求意义不大. 如果你说不要查的字段刚好是大字段.那我觉得是你的表设计有问题嘞

**Comment by Bo9013** [comment]
如果有100个字段,有20个字段是不需要查询出来的,且不说多查询出来的字段会占用带宽,你是愿意写80个字段名称,还是愿意写20个字段名称?你没有这样的需求,并不代表别人没有这样的需求.

**Comment by qmdx** [comment]
追踪 https://gitee.com/baomidou/mybatis-plus/issues/ILDNC

**Comment by ZaneRicky** [comment]
removeWordWithComma("test_id as orderid2, test_id as id, name, age", "id")
打印结果: test_as order2, test_as name, age

无法适配字段名包含的情况

**Comment by jamebon** [comment]
3.0.7.1为什么又去掉了exclude方法~~~

**Comment by qmdx** [comment]
> 3.0.7.1为什么又去掉了exclude方法~~~

https://mp.baomidou.com/guide/wrapper.html#excludecolumns

**Comment by huanghaoming** [comment]
exclude字段这个方法挺好的啊。。为什么去掉了。。。有没有其他办法？
