### ISSUE TITLE
lambdaUpdate批量更新数据，版本号不会改变

### ISSUE THREAD

**Issue by wangzp200** [baomidou/mybatis-plus#3845]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

批量更新数据，版本号不会改变。

### 重现步骤(如果有就写完整)

          PurchaseQcResult updateQcResult = new PurchaseQcResult();
                updateQcResult.setReturnStateEnum(ReturnStateEnum.AWAIT);
                List<Integer> updateQcResultIds = details.stream().map(x -> x.getQcResultId()).distinct().collect(Collectors.toList());
                LambdaUpdateChainWrapper<PurchaseQcResult> updateChainWrapper = qcResultService.lambdaUpdate().in(PurchaseQcResult::getId, updateQcResultIds);
                updateChainWrapper.update(updateQcResult);
此写法批量更新PurchaseQcResult ，但是版本信息不会改变

**Comment by nancheung97** [comment]
使用最新版也出现此问题吗

**Comment by qmdx** [comment]
应该是这样写的吧

   updateChainWrapper.update(updateQcResult,   updateChainWrapper ); 

还未解决重新 issue
