### ISSUE TITLE
逻辑删除问题

### ISSUE THREAD

**Issue by piglz** [baomidou/mybatis-plus#3849]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

1,2表中的逻辑删除字段名a一样，但是我只想1表中的a字段是逻辑删除，2表的是正常字段，这个怎么设置

**Comment by John-Chan** [comment]
试试按需配置逻辑删，也就是
- 全局配置里面不要写逻辑删除字段的名称
- 需要逻辑删除的实体类加上`@TableLogic`注解


see [逻辑删除](https://baomidou.com/guide/logic-delete.html)
