### ISSUE TITLE
oracle代码生成时, 因为表都在其他schema下,导致一个表都查不出来

### ISSUE THREAD

**Issue by fuyong859050943** [baomidou/mybatis-plus#385]
### #20 这里曾经反馈说改成使用下面语句
```sql
SELECT * FROM ALL_TAB_COMMENTS
```
但是我看现在源代码里还依然是下面语句
```sql
SELECT * FROM USER_TAB_COMMENTS
```
后面反馈说太慢, 那可能是因为, 他没有带条件导致表太多.
### 提下面两个小建议
1. 一般企业使用都会用到schema, 生成表时能够根据设置schema来生成指定schema下的表
2. 指定表前缀(或后缀); 一般像企业里一个schema下可能有上千张表, 但是我们不同的业务系统有自己对应的模块前缀名, 我一般使用表前缀来区分业务. 如果可以的话使用排除指定几个表前缀或表后缀的方式来生成自己要的表; 之前使用Include, Exclude这种方式在动辄成百上千的erp系统oracle下就显得相当鸡肋了

**Comment by yuxiaobin** [comment]
已在3.0分支修复：支持oracle下使用schema来生成代码

**Comment by yuxiaobin** [comment]
2.x分支也提交 具体参考gitee.com
