### ISSUE TITLE
插入数据的时候报错

### ISSUE THREAD

**Issue by XuBoZhangQvQ** [baomidou/mybatis-plus#3852]
### 当前使用版本(必填,否则不予处理)

使用的mybatis-plus-boot-starter版本为3.4.3.2 
使用的mybatis-plus-generator版本为3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库是Oracle
主键是用的Number(20)

使用generator生成的实体类主键对应的是BigDecimal，  生成策略是IdType.ASSIGN_ID
在insert的时候，报错

### 报错信息

Could not set property 'id' of 'entity.test' with value '1430465992084963329' Cause: java.lang.IllegalArgumentException: argument type mismatch

**Comment by XuBoZhangQvQ** [comment]
![image](https://user-images.githubusercontent.com/35949334/130772604-3781d483-74de-4cef-99f2-63f11cb457e6.png)
在代码生成器这里如果number长度超过18的话就生成Bigdecimal
![image](https://user-images.githubusercontent.com/35949334/130773229-dada5cdd-89df-440e-aebf-a95616deb771.png)
而ASSIGN_ID这个策略对应的ID生成只有Long,Integer,String

**Comment by XuBoZhangQvQ** [comment]
我就寻思着，自己跟自己卡BUG呢？🤣

**Comment by qmdx** [comment]
已支持， 已发布 `3.4.3.3` 欢迎尝鲜
