### ISSUE TITLE
调用原生SQL如何指定某些sql不打印其日志

### ISSUE THREAD

**Issue by keweiLv** [baomidou/mybatis-plus#3858]
### 当前使用版本(必填,否则不予处理)

V3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

目前系统设定日志级别为info，对于某些原生SQL，如getone等，在某些场景长有循环查询，导致大量sql打印，如果指定某些特定sql不打印日志

**Comment by qmdx** [comment]
修改日志级别
