### ISSUE TITLE
insert 获取自增主键报错 

### ISSUE THREAD

**Issue by phpdxj** [baomidou/mybatis-plus#3859]
### 当前使用版本(必填,否则不予处理)
mybatis-plus: 3.4.3
mybatis: 3.5.5
mybatis-spring: 2.0.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

集成BaseMapper接口并使用 insert 方法报错，错误内容如下：
![image](https://user-images.githubusercontent.com/20316941/130963707-2c32acfd-5cfd-437d-b20e-d03e74309844.png)

配置如下：
![image](https://user-images.githubusercontent.com/20316941/130963835-d39fca75-2a75-4226-a434-22395365bf7a.png)

数据库中间件使用了阿里的tddl，版本 5.2.3

目前通过xml覆盖insert方法可以解决该问题，但还是希望能得到解决，感谢

**Comment by qmdx** [comment]
希望解决 pr   无 tddl 环境可用于调试
