### ISSUE TITLE
分页 Page 能否增加map转换方法

### ISSUE THREAD

**Issue by hexw** [baomidou/mybatis-plus#3860]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
能否像 Spring data jpa Page 一样增加map 方法
<U> Page<U> map(Function<? super T, ? extends U> converter);

**Comment by huayanYu** [comment]
可以参与PR

**Comment by hexw** [comment]
不好意思,已有类似convert方法
