### ISSUE TITLE
Page extends IPage  构造函数能否加个List<?>record参数~ 

### ISSUE THREAD

**Issue by jiahuayu** [baomidou/mybatis-plus#3861]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-extension-3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.extension.plugins.pagination    Page.class
 Page<long currentPage,long total>   构造函数为啥不加个 Page<long currentPage,long total, List<?>record>
涉及类型转换时好用啊

**Comment by qmdx** [comment]
record 是返回结果，难道你预先就有结果？？
