### ISSUE TITLE
建议底层接口不要随意更改，selectCount返回类型由Integer修改为Long！！！

### ISSUE THREAD

**Issue by ccor** [baomidou/mybatis-plus#3862]
### 当前使用版本(必填,否则不予处理)
更新到3.4.3.2，发现底层接口破坏性变动！！！
基础组件不带这样玩的，小版本接口变化，引起已有代码大量保错！！！

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
BaseMapper
Integer selectCount(@Param("ew") Wrapper<T> queryWrapper);
Long selectCount(@Param("ew") Wrapper<T> queryWrapper);

**Comment by qmdx** [comment]
抱歉！ 这个地方涉及超 int 情况，当初设计上的缺陷，未来版本会以 long 为准

**Comment by qmdx** [comment]
> @qmdx 建议以后做类似更改的时候，在 changelog 和 release 页里，都列出 BREAKING CHANGES，把不兼容的项都列进去，字体加粗。如果涉及使用方法或配置项的修改，可以编写 Upgrading from Previous Version，列出代码或配置项如何改造， 这样让看 changelog 的人一目了然，能够提前知道自己的项目升级MP版本时改造的工作量。这是一个负责任的开源库的表现。

感谢建议

**Comment by weishd** [comment]
确实是，这次的改为long型，还有removeByIds的问题，搞死了。

**Comment by qmdx** [comment]
> 确实是，这次的改为long型，还有removeByIds的问题，搞死了。

3.4.3.3 已经发布修复了 id 问题

**Comment by chenjinhao** [comment]
有个疑问，既然selectCount改成long了，insert/update这些不同步一下吗，理论上返回的都是count嘛

**Comment by qmdx** [comment]
> 有个疑问，既然selectCount改成long了，insert/update这些不同步一下吗，理论上返回的都是count嘛

你插入会超过 int 数量？

**Comment by someok** [comment]
想这种常用方法应该尽量不要动，可以增加个方法，然后把原来的方法置为过期状态，否则升级相当麻烦

**Comment by liudonghua123** [comment]
最后支持 selectCount 返回 Integer 的版本是哪个？ 
https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md 里面也找不到呀
