### ISSUE TITLE
建议添加 lambdaQuery添加limit关键字以及查询参数类型映射

### ISSUE THREAD

**Issue by moil-xm** [baomidou/mybatis-plus#3877]
### 当前使用版本(必填,否则不予处理)

3.4.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

查询时候可以添加limit关键字类似lambdaQuery().limit(long x) lambdaQuery().limit(long x,long y)
类型映射 类似 X x = lambdaQuery().select(x.class) 类似于mybatis xml 中的 resultType

### 重现步骤(如果有就写完整)

查询时候可以添加limit关键字类似lambdaQuery().limit(long x) lambdaQuery().limit(long x,long y)
类型映射 类似 X x = lambdaQuery().select(x.class) 类似于mybatis xml 中的 resultType

**Comment by miemieYaho** [comment]
limit 属于方言,不会支持. resultType 不可变
