### ISSUE TITLE
saveBatch 不支持事务回滚

### ISSUE THREAD

**Issue by ZhuanShuAngel** [baomidou/mybatis-plus#3879]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

批量保存，前面几条可以进去，后面报错进不去数据库

### 重现步骤(如果有就写完整)

批量保存，前面几条可以进去，后面报错进不去数据库

**Comment by qmdx** [comment]
是否添加注解事务？ 如何使用的给出可重现 demo

**Comment by sawsaw12138** [comment]
> 是否添加注解事务？ 如何使用的给出可重现 demo

同样的问题，生产环境出现多次，测试环境无法复现。当系统操作用户多时就会出现这种问题，目前碰到的都是只插入一条数据，其余数据没有插入到数据库中，与插入数据的数量多少无关，

**Comment by qmdx** [comment]
> > 是否添加注解事务？ 如何使用的给出可重现 demo
> 
> 同样的问题，生产环境出现多次，测试环境无法复现。当系统操作用户多时就会出现这种问题，目前碰到的都是只插入一条数据，其余数据没有插入到数据库中，与插入数据的数量多少无关，

请给出重复 demo
