### ISSUE TITLE
 Mybatis-Plus3.0入门手册(非官方)

### ISSUE THREAD

**Issue by moshowgame** [baomidou/mybatis-plus#388]
我自己写了一份 Mybatis-Plus3.0入门手册，简单上手，3.0走起，STS可以直接导入，大神们求指导一下。

https://blog.csdn.net/moshowgame/article/details/81008485

**Comment by moshowgame** [comment]
开源项目再此，虽然微不足道，但是还是可以一起学习一起讨论的。mybatis-plus很棒，等3.0等了好久，终于来了，期待，也感谢plus释放了我们的双手，简约开发，简单粗暴。
https://github.com/moshowgame/spring-cloud-study

**Comment by Bo9013** [comment]
谢兄台分享

**Comment by darren-wang** [comment]
写的很好，建议贡献到官方文档，官方文档已经过时，里面很多类都已经找不到了。

**Comment by gatspy** [comment]
现在还在用2.3.

**Comment by weixiaohu** [comment]
3.0-bate自动填充，设置为更新填充，怎么都不生效，有遇到这个问题吗

**Comment by leikegeek** [comment]
我也碰到了相同的问题 @weixiaohu  你解决了吗

**Comment by qmdx** [comment]
@weibaohui  @leikegeek  更新到 3.0-RC 试试

**Comment by leikegeek** [comment]
@qmdx  更新到新版本后正常了 谢谢
