### ISSUE TITLE
分页器size为null或者负数时直接跳过了排序

### ISSUE THREAD

**Issue by Assassink126** [baomidou/mybatis-plus#3884]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页器size为null或者负数时直接跳过了排序处理等后续操作
  /*
         * 不需要分页的场合，如果 size 小于 0 返回结果集
         */
        if (null == page || page.getSize() < 0) {
            return invocation.proceed();
        }
使用场景：实现导出全部记录时在部分页面未获取总数，所以使用size=-1实现全部导出 但是排序失效了

**Comment by 986510453** [comment]
既然都要查询所有数据了，为什么还要掉分页接口呢？为什么不新增一个list接口呢

**Comment by Assassink126** [comment]
> 既然都要查询所有数据了，为什么还要掉分页接口呢？为什么不新增一个list接口呢
一个接口能实现的事情，为什么要多加一个接口呢
解决办法当然有很多，但是解决办法和这样设计的原因没啥关系吧，分页设置不应该影响排序逻辑吧？
至于为什么要查询所有数据，因为导出功能和分页查看数据在一个页面，所以共用一个接口

**Comment by 986510453** [comment]
这里的逻辑是如果条件不满足就不会做任何操作，自然就不会修改排序。
要实现你的需求，可以自定义分页拦截器
