### ISSUE TITLE
BaseMapper.insert/update/updateById自动设置一些字段值

### ISSUE THREAD

**Issue by ooizj** [baomidou/mybatis-plus#3885]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
能否在BaseMapper.insert/update/updateById的时候自动更新一些字段（如，createdby/updatedby）

### 重现步骤(如果有就写完整)
User u = new User();
u.setName("小明");
baseMaper.insert(u); // 能否自动设置u.createdby和u.updatedby（值可以在ThreadLocal中获取）

**Comment by qmdx** [comment]
https://baomidou.com/guide/auto-fill-metainfo.html
