### ISSUE TITLE
关于填充器的问题

### ISSUE THREAD

**Issue by xianzhikeji** [baomidou/mybatis-plus#3889]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用填充器获取当前用户信息时，添加数据时会查询数据库，如果是通过excel导入批量写入数据库，保存一条就会查询一次，比较消耗资源，mp能否提供一个方法，在这种情况下只查询一次数据库

**Comment by huayanYu** [comment]
你有很多种方法来解决这个问题，不一定非要mp来解决。
1. 不管是session还是token，都可以把当前用户存起来，从session或者token去查不经过数据库。
2. 非要经过数据库，在事务模式下，mybatis本身有缓存不会重查。
3. 没有事务，建议自己查出来，list巡查自己插入当前用户，当前对象有值就不会再填充。
