### ISSUE TITLE
MyBatis Page 添加 排序BUG。

### ISSUE THREAD

**Issue by xgj1988** [baomidou/mybatis-plus#389]
正常情况下是不会出现的，但是如果这样写就有问题了。
List<String> orders = new ArrayList<>();
orders.add("convert(usernameusing gbk)");
page.setAscs(orders);

那么，就会出现 两次ORDER BY的情况，看了一下源代码。。原因是这样。
JsqlParserCountOptimize这个类的 optimizeSql方法  执行的时候 Select selectStatement = (Select) CCJSqlParserUtil.parse(sql);这里转换失败，抛出异常。catch 代码如下
 SqlInfo sqlInfo = SqlInfo.newInstance();
        try {
            Select selectStatement = (Select) CCJSqlParserUtil.parse(sql);
          ....
            // 添加包含groupBy 不去除orderBy
            if (CollectionUtils.isEmpty(groupBy) && CollectionUtils.isNotEmpty(orderBy)) {
                plainSelect.setOrderByElements(null);
                sqlInfo.setOrderBy(false);
            }
         ....
        } catch (Throwable e) {
            // 无法优化使用原 SQL
            sqlInfo.setSql(SqlUtils.getOriginalCountSql(sql));
            return sqlInfo;
        }
但是这个try里面有个这句 sqlInfo.setOrderBy(false);不会执行，导致PaginationInterceptor这个类，这段代码

     // 针对定义了rowBounds，做为mapper接口方法的参数
        BoundSql boundSql = (BoundSql) metaObject.getValue("delegate.boundSql");
        String originalSql = boundSql.getSql();
        Connection connection = (Connection) invocation.getArgs()[0];
        DBType dbType = StringUtils.isNotEmpty(dialectType) ? DBType.getDBType(dialectType) : JdbcUtils.getDbType(connection.getMetaData().getURL());
        if (rowBounds instanceof Pagination) {
            Pagination page = (Pagination) rowBounds;
            boolean orderBy = true;
            if (page.isSearchCount()) {
                SqlInfo sqlInfo = SqlUtils.getOptimizeCountSql(page.isOptimizeCountSql(), sqlParser, originalSql);
                orderBy = sqlInfo.isOrderBy();
                this.queryTotal(overflowCurrent, sqlInfo.getSql(), mappedStatement, boundSql, page, connection);
                if (page.getTotal() <= 0) {
                    return invocation.proceed();
                }
            }
            String buildSql = SqlUtils.concatOrderBy(originalSql, page, orderBy);
            originalSql = DialectFactory.buildPaginationSql(page, buildSql, dbType, dialectClazz);
        } else {
            // support physical Pagination for RowBounds
            originalSql = DialectFactory.buildPaginationSql(rowBounds, originalSql, dbType, dialectClazz);
        }

    orderBy = sqlInfo.isOrderBy();这里的代码不会执行，也就是orderBy还是为true，所以在执行 String buildSql = SqlUtils.concatOrderBy(originalSql, page, orderBy);这里的时候，又会拼接 orderBy。我现在是重写了分页插件，但是我感觉我的方法不优雅，我是直接判断 page 里面是否有排序集合，有的话，直接赋值为false。

**Comment by qmdx** [comment]
建议复杂情况关闭 SQL 解析，page.setOptimizeSql(false)
