### ISSUE TITLE
JacksonTypeHandler 如何处理 LocalDate类型的数据？

### ISSUE THREAD

**Issue by wangjia2016** [baomidou/mybatis-plus#3891]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

```
 @TableField(typeHandler = JacksonTypeHandler.class)
    private List<LocalDate> startDate;
```

### 重现步骤(如果有就写完整)
发现转换的时候，默认是转成ArrayList<String>了
![image](https://user-images.githubusercontent.com/16084076/132433692-9de4fdb2-0ba1-401a-87e9-be1ab00d679a.png)

### 报错信息
类型转换异常
`org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: java.lang.String cannot be cast to java.time.LocalDate; nested exception is com.fasterxml.jackson.databind.JsonMappingException: java.lang.String cannot be cast to java.time.LocalDate

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: java.lang.String cannot be cast to java.time.LocalDate 
`

保存进数据库的json 也是没有格式化之后的日期格式

`[{"era": "CE", "year": 2021, "month": "SEPTEMBER", "leapYear": false, "dayOfWeek": "FRIDAY", "dayOfYear": 253, "chronology": {"id": "ISO", "calendarType": "iso8601"}, "dayOfMonth": 10, "monthValue": 9}, {"era": "CE", "year": 2021, "month": "SEPTEMBER", "leapYear": false, "dayOfWeek": "MONDAY", "dayOfYear": 263, "chronology": {"id": "ISO", "calendarType": "iso8601"}, "dayOfMonth": 20, "monthValue": 9}]`

[{"era": "CE", "year": 2021, "month": "SEPTEMBER", "leapYear": false, "dayOfWeek": "FRIDAY", "dayOfYear": 253, "chronology": {"id": "ISO", "calendarType": "iso8601"}, "dayOfMonth": 10, "monthValue": 9}, {"era": "CE", "year": 2021, "month": "SEPTEMBER", "leapYear": false, "dayOfWeek": "MONDAY", "dayOfYear": 263, "chronology": {"id": "ISO", "calendarType": "iso8601"}, "dayOfMonth": 20, "monthValue": 9}]

**Comment by nancheung97** [comment]
`com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler#setObjectMapper`

手动配置jackson的序列化，设置自定义的ObjectMapper
