### ISSUE TITLE
MyBatis Page可以实现动态分页吗？

### ISSUE THREAD

**Issue by chenxukf103** [baomidou/mybatis-plus#390]
目前有个需求是希望通过一个参数去控制是否执行分页，比如前端传参数的时候doPage是false，那么就不执行分页操作，true则执行正常的分页操作，这个MyBatis-plus支持吗

**Comment by qmdx** [comment]
3.0-gamma  新增 IPage  listModel 集合模式，如果 http://localhost:8080/user/page?listModel=true  返回所有结果集，参考 https://gitee.com/baomidou/mybatisplus-spring-boot
