### ISSUE TITLE
实体类List泛型，配置typeHandler=FastjsonTypeHandler，查询遍历失败

### ISSUE THREAD

**Issue by viskeee** [baomidou/mybatis-plus#3908]
### 当前使用版本(必填,否则不予处理)
3.4.3~3.4.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
将List泛型对象 转为json字符串 存储到数据库，再次读取时获取对象类型正常，为ArrayList，但遍历失败。

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/49233036/132807973-33b2775a-1ee7-4603-bcf2-b9dd5956bf51.png)

![image](https://user-images.githubusercontent.com/49233036/132808327-d3f5cd72-cd7f-4cc2-b236-97cdb862b36e.png)

### 报错信息

![image](https://user-images.githubusercontent.com/49233036/132808347-6bd7cc73-068e-41b7-a6a4-af0e58110d67.png)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/3897
