### ISSUE TITLE
MP可以查询JSON了吗？

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [baomidou/mybatis-plus#3912]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用了JSON

**Comment by VampireAchao** [comment]
@see[字段类型处理器](https://mp.baomidou.com/guide/typehandler.html)

**Comment by miemieYaho** [comment]
up

**Comment by Conmi-WhiteJoker** [comment]
> @see[字段类型处理器](https://mp.baomidou.com/guide/typehandler.html)

好像找了一圈也没找到这个标签以及用法~
