### ISSUE TITLE
多数据源使用乐观锁不生效

### ISSUE THREAD

**Issue by wangqiuping1** [baomidou/mybatis-plus#3915]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
配置了hibernate为主数据源，mybatis-plus为副数据源
在mybatis-plus config 中配置了最新版的乐观锁
，在单数据源的情况下是没有问题的

### 重现步骤(如果有就写完整)
再执行更新的操作的时候就直接报错了

### 报错信息

nested exception is org.apache.ibatis.binding.BindingException: Parameter 'MP_OPTLOCK_VERSION_ORIGINAL' not found. Available parameters are [param1, et]

**Comment by miemieYaho** [comment]
代码,demo

**Comment by wangqiuping1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 多数据源使用乐观锁不生效 (#3915)





 
代码,demo
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangqiuping1** [comment]
> 代码,demo

代码demo已发送至您邮箱
