### ISSUE TITLE
多数据源模式，mpw方式加密密码字段不起作用

### ISSUE THREAD

**Issue by yuanqixun** [baomidou/mybatis-plus#3918]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
对password字段进行mpw方式的加密，但是启动时，仍然报密码错。

**Comment by huayanYu** [comment]
如果用的苞米豆的多数据源方案，就用多数据源的加密。
