### ISSUE TITLE
批量提交不生效

### ISSUE THREAD

**Issue by hbzengcan** [baomidou/mybatis-plus#3925]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
执行批量插入操作的saveBatch，但是不生效，控制台打印结果是逐条插入，操作数据：20000条

### 重现步骤(如果有就写完整)
执行批量插入操作的saveBatch，但是不生效，控制台打印结果是逐条插入，操作数据：20000条

### 报错信息
无

**Comment by huayanYu** [comment]
就是如此的

**Comment by rockit-ba** [comment]
> 就是如此的
那批量的意义在哪里，只是简化代码操作而没有考虑性能问题吗

**Comment by huayanYu** [comment]
@rockit-ba mybatis底层就是batchExecter， 可以找mybatis优化
