### ISSUE TITLE
查询已经删除的数据

### ISSUE THREAD

**Issue by chency-jn** [baomidou/mybatis-plus#3926]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1.del字段添加了@TableLogic 使用更新语句时 加入我的更新字段有del这个字段 他生成的update语句不会设置我自己设置的条件。
2.假如我要查询已经删除的数据呢？只能自己写sql？
我觉得应该是这样 假如用户没有设置值可以自己填充上，如果设置了是不是就应该按照用户的意图来查询呢？就像我要查询已经删除的数据一样

### 重现步骤(如果有就写完整)

2个问题
1. 一个是我使用update方法更新对象时，设置了删除状态为删除，结果没有删
2. 我想要查询已经删除的数据 再wrap里设置的del为true 结果不好使依然自动添加了del = 0

**Comment by huayanYu** [comment]
做不到， 有查询需求的，建议你这个字段就不要用逻辑删除，用一个状态去维护、
