### ISSUE TITLE
mp聚合查询组装失败

### ISSUE THREAD

**Issue by zzqfighting** [baomidou/mybatis-plus#3929]
### 当前使用版本(必填,否则不予处理)
3.3.2

所有版本都存在这个问题

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
配置文件自定义查询中，如果类属性配置中包含typeHandler=“”，那么在一对多、多对多聚合查询之后，不会进行组装

### 重现步骤(如果有就写完整)
<resultMap id="BaseResultMap" type="xxx“>
       <result column="id" property="id"/>
       <result column="json" property="json" typeHandler="com.baomidou.mybatisplus.extension.handlers.FastjsonTypeHandler"/>
     
    <collection property="list”  ofType="xxxx">
          <result column="name" property="name"/>
   </collection>
</resultMap>
 
这种配置查询之后完全没有进行组装返回

### 报错信息
没有报错

**Comment by miemieYaho** [comment]
不支持,自己xml写的自己用resultmap
