### ISSUE TITLE
增加对Clickhouse数据库更新和删除的支持

### ISSUE THREAD

**Issue by urzeye** [baomidou/mybatis-plus#3930]
### 当前使用版本(必填,否则不予处理)

v3.4.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

MP生成的更新语句统一为：`update table_name set column = new_value where condition`，
而Clickhouse更新的语法为：`alter table table_name update column = new_value where condition`，
Clickhouse删除的语法为：`alter table table_name delete where condition`.

能否对Clickhouse的更新和删除进行一下单独的处理？

**Comment by miemieYaho** [comment]
https://baomidou.com/guide/sql-injector.html
