### ISSUE TITLE
为什么要把javassist包放入到mybatis-3.5.7基础包里，修改了JavassistProxyFactory 但是并没有使用新增的javassist包下的类

### ISSUE THREAD

**Issue by izerui** [baomidou/mybatis-plus#3931]
### 当前使用版本(必填,否则不予处理)

最新版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

可能导致的类引入混淆

### 报错信息

暂时没有报错，因为想扩展一套属于自己的page对象映射和封装，感觉这块有点迷惑。

**Comment by miemieYaho** [comment]
黑人问号
