### ISSUE TITLE
多数据源分页问题，神通数据库的方言

### ISSUE THREAD

**Issue by geng4j** [baomidou/mybatis-plus#3936]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
现在的分页插件虽然支持多数据源分页，但是只支持多数据源为同一类型的的数据源。例如两个数据源都是mysql，连接的mysql库不一致，这种情况下是可以分页的，但是对于两个不用的数据源，例如一个是mysql，一个是神通数据库，这种情况下无法实现同时分页。
另外神通数据库的方言和oracle一直，并非为mysql

**Comment by huayanYu** [comment]
你是用的啥多数据源方案， 然后分页又是怎么配置的？

是支持的啊，提问要记得带配置啊
