### ISSUE TITLE
神通数据库分页方言错误

### ISSUE THREAD

**Issue by geng4j** [baomidou/mybatis-plus#3937]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

<img width="746" alt="截屏2021-09-20 08 58 39" src="https://user-images.githubusercontent.com/76054806/133950150-b1ba5342-c044-4ec4-a201-bff4488238b4.png">

mybatis-plus支持的神通数据库分页方言为mysql，而实际神通数据库分页类似于oracle，应采用oracle方言。
另外，建议官方将DialectRegistry.dialect_enum_map权限放开，支持用户自定义数据库类型和其对应的方言。

**Comment by huayanYu** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/inner/PaginationInnerInterceptor.java 可以直接设置dialect

**Comment by geng4j** [comment]
<img width="746" alt="截屏2021-09-20 08 56 23" src="https://user-images.githubusercontent.com/76054806/134027798-f4fdf29a-c87b-4eb8-8fd3-c7686ce31027.png">

直接设置dialect的话，则每个分页都执行的是设置dialect，对于神通数和mysql多数据源情况下，需要不同的分页dialect，这种情况无法适用。

**Comment by miemieYaho** [comment]
神通 分页用 mysql 那是别人指定的,别人的神通 用mysql的方言你的就不行
