### ISSUE TITLE
注入自定义事务工厂

### ISSUE THREAD

**Issue by liaozan** [baomidou/mybatis-plus#3942]
[这个 commit 是认真的吗？](https://github.com/baomidou/mybatis-plus/commit/7b114469ae9eed0d0f00017bb26df8079d2ea7cc)，
那 com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java:198 还有啥用呢

**Comment by liaozan** [comment]
就这么简单 close 掉？140 行注入 TransactionFactory，201 又注入 TransactionFactory，能不能统一一下行为？

**Comment by miemieYaho** [comment]
ok

**Comment by miemieYaho** [comment]
已更正
