### ISSUE TITLE
自定义全局操作如何添加多个呢，例子中添加了一个

### ISSUE THREAD

**Issue by B1gB1gRAin** [baomidou/mybatis-plus#395]
自定义全局操作如何添加多个呢，例子中添加了一个，比如我要添加deleteAll,findAll两个方法，该如何添加呢。小白 求赐教

**Comment by B1gB1gRAin** [comment]
public class MySqlInjector extends AutoSqlInjector {

    @Override
    public void inject(Configuration configuration, MapperBuilderAssistant builderAssistant, Class<?> mapperClass,
            Class<?> modelClass, TableInfo table) {
       deleteAllUser1(mapperClass, modelClass, table);
        deleteAllUser2(mapperClass, modelClass, table);
    }

考虑了下 这样就可以了对不

**Comment by qmdx** [comment]
多个就注入多个方法
