### ISSUE TITLE
为什么看不到3.5.1的版本

### ISSUE THREAD

**Issue by aSingleDragon** [baomidou/mybatis-plus#3966]
我在你们的官网看到代码生成器提示了最新的版本3.5.1
为什么github上看不到呢？
https://mp.baomidou.com/guide/generator-new.html#%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8

**Comment by miemieYaho** [comment]
https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-generator
