### ISSUE TITLE
MybatisPlusGenerator3.5.1如何配置不生成controller和service

### ISSUE THREAD

**Issue by FreedomFoolt** [baomidou/mybatis-plus#3968]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

3.5.1版本中的injectionConfig 配置没有fileCreate，如何配置不生成controller和service代码？

**Comment by miRUAcleInjoker** [comment]
`.templateConfig(builder -> builder.disable(TemplateType.CONTROLLER, TemplateType.SERVICE, TemplateType.SERVICEIMPL))`
