### ISSUE TITLE
refresh代码问题，可能导致应用假死，慎用isRefresh

### ISSUE THREAD

**Issue by dchack** [baomidou/mybatis-plus#398]
https://github.com/baomidou/mybatis-plus/blob/585cc09dc0075b4d53099611b103a57bdaa9b443/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/spring/MybatisMapperRefresh.java#L140

MybatisMapperRefresh类中，判断`if (file.isFile() && file.lastModified() > beforeTime)` 如果在这个if里的代码出现异常，而没有执行到后续的` beforeTime = SystemClock.now();`，我们看到异常catch里没有中断流程没有抛出异常，所以for循环继续，那么此时判断依然为true，继续报错，从而死循环，可能导致应用假死。
这里推荐不设置isRefresh为true，如果你不小心把true的设置弄到里线上，而刚好线上的服务器时间的差异，可能导致应用假死的情况。

**Comment by xiangyichang** [comment]
就是这个原因，我这里也经常异常，怎么设置它关闭呢？
