### ISSUE TITLE
type-enums-package扫描使用了switch的枚举类报错

### ISSUE THREAD

**Issue by goolnen** [baomidou/mybatis-plus#3982]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1、项目通过type-enums-package扫描枚举包
2、在新增的某个枚举中使用了switch，该枚举类有派生类
3、项目启动报错：java.lang.NoClassDefFoundError

### 重现步骤(如果有就写完整)
1、mybatis-plus加载包下的所有类时先加载了派生类再加载枚举类导致报错
2、把加载顺序调整为先加载枚举类再加载派生类就没问题

### 报错信息
java.lang.NoClassDefFoundError

**Comment by qmdx** [comment]
移除 派生类
