### ISSUE TITLE
lambdaQueryWrapper的ge和le方法操作日期条件时报错空指针异常

### ISSUE THREAD

**Issue by 635399797** [baomidou/mybatis-plus#3985]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
lambdaQueryWrapper.ge(false, RecordVO::getCreateTime, recordDTO.getStartDate().plusDays(1));

lambdaQueryWrapper.le(BeanUtil.isNotEmpty(recordDTO.getEndDate()), RecordVO::getCreateTime, recordDTO.getEndDate().plusDays(1));
构造日期条件大于或小于时，即使第一个参数结果为false，第三个参数recordDTO.getEndDate()为null时调用LocalDate的.plusDays(1)方法也会报空指针异常.NullPointerException

### 报错信息
NullPointerException

**Comment by miemieYaho** [comment]
java基础
