### ISSUE TITLE
关于逻辑删除

### ISSUE THREAD

**Issue by tjpulwy** [baomidou/mybatis-plus#3990]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1. 逻辑删除值如果是时间戳怎么做？
2. 如果我设置了删除时间和删除人，如何在MetaObjectHandler里判断是逻辑删除？
通过读代码，感觉上面两项目前都实现不了

**Comment by miemieYaho** [comment]
1. 文档里有
2.  MetaObjectHandler 只能set值
