### ISSUE TITLE
typeHandler指定类型的条件查询

### ISSUE THREAD

**Issue by huangjianfeng1** [baomidou/mybatis-plus#3992]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
假设某个字段指定了类型处理器：typeHandler=JsonUserTypeHandler.class，指定字段为User类型时，假设要查询User.type=1的列表，请问这个如何实现？
即我存储该字段的内容为User的Json字符串，要用其部分内容作为查询条件，目前我使用的是用like，type:1

**Comment by yisirman** [comment]
同问 是否支持这样的写法
JSON_CONTAINS(field, JSON_OBJECT('key', #{value}))

**Comment by VampireAchao** [comment]
目前暂无此方面计划支持，因为要考虑到数据库兼容性
