### ISSUE TITLE
@TableId(value = "ID", type = IdType.ASSIGN_UUID), 如果数据库为oracle, 且设置ID为主键, 则实体类插入会报错

### ISSUE THREAD

**Issue by Evil-GK** [baomidou/mybatis-plus#3997]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

@TableId(value = "ID", type = IdType.ASSIGN_UUID), 如果数据库为oracle, 且设置ID为主键, 则实体类插入会报错;

### 重现步骤(如果有就写完整)

@TableId(value = "ID", type = IdType.ASSIGN_UUID), 如果数据库为oracle, 且设置ID为主键, 则实体类插入会报错;
此时在数据库如果取消ID字段的主键设置(oracle可不设置主键), 插入成功;
不取消ID字段为主键的情况下, 如果将实体类id注解换为@TableField(value = "ID"), 使用UUID.randomUUID().toString()手动创建uuid, 插入也能成功;

### 报错信息

java.sql.SQLIntegrityConstraintViolationException: ORA-00001: 违反唯一约束条件

**Comment by qmdx** [comment]
https://baomidou.com/pages/e131bd/#spring-boot
