### ISSUE TITLE
Method queryTotal execution error of sql 

### ISSUE THREAD

**Issue by CrookedSmile** [baomidou/mybatis-plus#3999]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

SELECT COUNT(1) FROM x WHERE (a IN (?, ?, ?) AND b IN (?) AND c IN (?))
参数均有值，尝试过升级 mp 到 3.4.2 仍有问题

### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql :
SELECT COUNT(1) FROM x WHERE (a IN (?, ?, ?) AND b IN (?) AND c IN (?))
The error may involve defaultParameterMap
The error occurred while setting parameters
Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql :
SELECT COUNT(1) FROM x WHERE (a IN (?, ?, ?) AND b IN (?) AND c IN (?))

**Comment by TaotieLin** [comment]
我在mybatis puls 2.3，数据库sqlServer 中也遇到相同问题， 奇怪的是我在某些表分页中使用order  by 是正常的。我查看生成的sql为 	:
SELECT COUNT(1) FROM rule_trigger_log
而某些表中生成的sql为 :
SELECT COUNT(1) FROM ( SELECT  id AS id,name FROM zy_ad_position  ORDER BY id DESC ) TOTAL
我仔细观察他们的使用并没有发现差异。我不清楚mybtais plus 是根据什么生成不同的count 语句的。

**Comment by jie6mm** [comment]
> 

兄弟解决了嘛，我也遇到了这个问题

**Comment by jie6mm** [comment]
> 我在mybatis puls 2.3，数据库sqlServer 中也遇到相同问题， 奇怪的是我在某些表分页中使用order by 是正常的。我查看生成的sql为 : SELECT COUNT(1) FROM rule_trigger_log 而某些表中生成的sql为 : SELECT COUNT(1) FROM ( SELECT id AS id,name FROM zy_ad_position ORDER BY id DESC ) TOTAL 我仔细观察他们的使用并没有发现差异。我不清楚mybtais plus 是根据什么生成不同的count 语句的。

兄弟解决了嘛，我也遇到了这个问题
