### ISSUE TITLE
int selectCount(Wrapper<T> wrapper)接口可否增加一种处理带有group by语句的情况

### ISSUE THREAD

**Issue by abcbuzhiming** [baomidou/mybatis-plus#400]
如果wrapper生成的语言的最外层带有group by。比如 wrapper.setSqlSelect('name').groupBy("name") 如果此时是selectList，最后生成的语句是：

`select name from user_info group by name`

这是可以通过的，但是，如果用的是selectCount，最后生成的语句是

`select count(1) from user_info group by name`
这样的语句是会失败的，实际应该生成

select count(1) from (select name from user_info group by name)
我注意到了这个issue：https://gitee.com/baomidou/mybatis-plus/issues/IBDT9 里面提到用分页插件时只要设置page.setOptimizeCount(false)就能解决，跟踪源码也发现 Pagination类里有这样的注释

` /**
     * 优化 Count Sql 设置 false 执行 select count(1) from (listSql)
     */
    private boolean optimizeCountSql = true;`
既然如此，能否增加一个int selectCount(Wrapper wrapper，boolen optimizeCountSql)；当第二个参数为false时采用和Pagination类同样的策略呢

**Comment by qmdx** [comment]
page.setOptimizeCount(false) 这怎么写
