### ISSUE TITLE
3.3.1版本，MAT分析mybatisConfiguration积累内存

### ISSUE THREAD

**Issue by lipenglina** [baomidou/mybatis-plus#4006]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

dump下内存堆，mat进行分析

### 重现步骤(如果有就写完整)

项目是采用springboot 2.1.6 release+mybtispuls 3.3.1

### 报错信息
![image](https://user-images.githubusercontent.com/40021766/139046118-978ceca1-a9b7-4dfa-83eb-6bf00253c917.png)

**Comment by komorebi64** [comment]
我也遇到了这个问题，几乎占据了堆空间的30%

dump分析的结果来看，我们都遇到的是 #2651 同一个问题

**Comment by lipenglina** [comment]
所以，现在没有解决办法是吧？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 晚上11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 3.3.1版本，MAT分析mybatisConfiguration积累内存 (Issue #4006)





 
我也遇到了这个问题，几乎占据了堆空间的30%
 
dump分析的结果来看，我们都遇到的是 #2651 同一个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
