### ISSUE TITLE
IdType.INPUT 是否不会被自动填充功能填充ID

### ISSUE THREAD

**Issue by wilder-ness** [baomidou/mybatis-plus#4008]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在主键上注解    @TableId(value = "ID", type = IdType.INPUT)
在save 的时候不会进入自动填充的方法

### 重现步骤(如果有就写完整)
直接加上这个注解 没有其他的自动填充的字段

**Comment by qmdx** [comment]
INPUT 是不处理的
