### ISSUE TITLE
使用自动填充字段时，如果日期用LocalDateTime.now()函数，获取到的是空

### ISSUE THREAD

**Issue by kawaiim** [baomidou/mybatis-plus#4019]
### 当前使用版本(必填,否则不予处理)

3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版本的问题

### 重现步骤(如果有就写完整)

this.strictUpdateFill(metaObject, "createTime", LocalDateTime.class, LocalDateTime::now);

### 报错信息

没报错，值是空的

**Comment by miemieYaho** [comment]
自己看入参类型
