### ISSUE TITLE
同时连接oracle和MySQL两个数据源时分页失败

### ISSUE THREAD

**Issue by tomkrus007** [baomidou/mybatis-plus#4021]
### 当前使用版本
v3.4.3.2

### 该问题是如何引起的？
由于注册分页插件时必须指定数据库类型，所以当系统同时连接oracle和MySQL的数据源时，必有一个数据源的分页语句报错。

比如，DbType设置为DbType.ORACLE：
    @Bean
    public MybatisPlusInterceptor oracleInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.ORACLE));
        return interceptor;
    }
则MySQL的数据源分页会报错。
反之亦然。

**Comment by miemieYaho** [comment]
你也是不看文档不看代码的cv工程师是吧

**Comment by tomkrus007** [comment]
用户有问题就不能问了吗？就你这态度是做开源的态度吗？

**Comment by miemieYaho** [comment]
说得还欠你似的了?没点脑子你还是回家搬砖种地去吧,那个适合你

**Comment by tomkrus007** [comment]
别素质太低，动不动就人身攻击。就你这种脑子也就只能在这里怼怼用户了。

**Comment by miemieYaho** [comment]
怼的就是你这种二逼

**Comment by tomkrus007** [comment]
你妈b给你操烂了才能生出你这种傻逼。

**Comment by miemieYaho** [comment]
没把你射墙上是你爸这辈子做过最错误的选择

**Comment by linvaux** [comment]
6啊

**Comment by XUEfei150129** [comment]
不堪入目

**Comment by thinker-gao** [comment]
> 你也是不看文档不看源码的cv工程师是吧
Your documentation is written like shit, you can only know it after reading the source code
