### ISSUE TITLE
 "Base_Column_List"的报红"<statement> or DELIMITER expected, got 'id'"的解决方案

### ISSUE THREAD

**Issue by APIInvoker** [baomidou/mybatis-plus#4023]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自动生成的"Base_Column_List"都有这个问题

### 重现步骤(如果有就写完整)
只要自动生成mapper就有

### 报错信息
\<statement\> or DELIMITER expected, got 'id'

**Comment by APIInvoker** [comment]
在里面加上<if test="true"></if>标签

**Comment by qmdx** [comment]
描述不清楚
