### ISSUE TITLE
关于Date类型插入数据库问题

### ISSUE THREAD

**Issue by zuosenyu** [baomidou/mybatis-plus#4026]
### 当前使用版本(必填,否则不予处理)
mybatisplus3.4.0版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
插入带毫秒的时间类型，毫秒数大于500的，数据库会加一秒，导致时间字段不匹配，不知官方可有在mybatis框架中有什么处理方式

**Comment by miemieYaho** [comment]
没有方法

**Comment by zuosenyu** [comment]
好吧，那我就从其他方式解决吧
