### ISSUE TITLE
Mybatis-plus 分页查询tdengine, 是否支持用户动态添加数据库DbType?

### ISSUE THREAD

**Issue by liangbinc** [baomidou/mybatis-plus#4027]
### 当前使用版本(必填,否则不予处理)

3.3.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

分页查询涛思数据库

### 重现步骤(如果有就写完整)

分页查询涛思数据库

### 报错信息

other database not supported

**Comment by miemieYaho** [comment]
只有一个数据库种类的就配置dbtype,对应分页类型

**Comment by liangbinc** [comment]
> 只有一个数据库种类的就配置dbtype,对应分页类型

没有对应的dbType

**Comment by miemieYaho** [comment]
那你只能重写分页插件里findIDialect方法,或者你pr该数据库的dbtype参考 findIDialect方法里面的内容

**Comment by liangbinc** [comment]
> 那你只能重写分页插件里findIDialect方法,或者你pr该数据库的dbtype参考 findIDialect方
