### ISSUE TITLE
设置逻辑删除后，删除记录update_person,update_time未更新

### ISSUE THREAD

**Issue by luo1993hao** [baomidou/mybatis-plus#403]
所有表都有live_flag逻辑删除位置，并设置为逻辑删除位，有create_time,create_person,update_person,update_time4个公共字段并成功设置。正常的修改与新增，4个字段都有对应记录。但是delete操作update_person,update_time这2个字段没有未更新。SQL打印出来为update XXX set live_flag=0.

**Comment by qmdx** [comment]
逻辑删除的时候不会填充公共字段因为这条记录删除了，如果有这个需求你需要执行 update 操作手动更新逻辑删除字段。

**Comment by justlikeliuen** [comment]
> 逻辑删除的时候不会填充公共字段因为这条记录删除了，如果有这个需求你需要执行 update 操作手动更新逻辑删除字段。

使用IService或者Mapper提供的updateById等方法依然会屏蔽手动更新的delete字段,是否只能自己来写sql来操作呢请问?

**Comment by miemieYaho** [comment]
看文档,有说明
