### ISSUE TITLE
sqlserver 分页,利用page插件报错

### ISSUE THREAD

**Issue by newbirdking** [baomidou/mybatis-plus#4030]
### 当前使用版本(必填,否则不予处理)

version 3.4.1

### 重现步骤(如果有就写完整)
具体操作如下:
https://github.com/JSQLParser/JSqlParser/issues/1404

jsqlparse 建议封装 
Select selectStatement = (Select) CCJSqlParserUtil.parse(originalSql, parser -> parser.withSquareBracketQuotation(true));
![image](https://user-images.githubusercontent.com/5317586/140467640-8b59754a-45c1-466f-bcf9-4f10a8924416.png)
如果要解决,是不是需要重写分页;为啥官网的方法不用withSquareBracketQuotation?
重写确实可以解决

**Comment by qmdx** [comment]
排除 sql 解析
