### ISSUE TITLE
诉求：怎么对BaseMapper的某个方法进行增强处理，如对批量更新方法增加更新条数验证

### ISSUE THREAD

**Issue by muyu-group** [baomidou/mybatis-plus#4033]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

诉求：怎么对BaseMapper的某个方法进行增强处理，如对批量更新方法增加更新条数验证

**Comment by qmdx** [comment]
mapper 层方法返回的是行数，自行解决
