### ISSUE TITLE
Phoenix批量插入的问题

### ISSUE THREAD

**Issue by zhaoqiuyang1023** [baomidou/mybatis-plus#4036]
### 当前使用版本(必填,否则不予处理)

  <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3.4</version>
  </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Phoenix 插入是 unset 但是当我用mybatisplus 的插入时出现以下错误
ERROR 601 (42P00): Syntax error. Encountered "INSERT" at line 1, column 1.
官网说的是支持Phoenix

### 重现步骤(如果有就写完整)
  List<TruckTrack> phoenixDbDataList = new ArrayList<>();
        for (Map dto : result.getMappedResults()) {
            System.out.println(JSON.toJSONString(dto));
            TruckTrack phoenixDbData = JSON.parseObject(JSON.toJSONString(dto), TruckTrack.class);
            phoenixDbDataList.add(phoenixDbData);
        }
        truckTrackService.saveOrUpdateBatch(phoenixDbDataList);

### Cause: org.apache.phoenix.exception.PhoenixParserException: ERROR 601 (42P00): Syntax error. Encountered "INSERT" at line 1, column 1.
; bad SQL grammar []; nested exception is org.apache.phoenix.exception.PhoenixParserException: ERROR 601 (42P00): Syntax error. Encountered "INSERT" at line 1, column 1.

**Comment by miemieYaho** [comment]
默认注入的sql只支持标准语法,各种数据库的支持只是在`分页`上
