### ISSUE TITLE
IdType.ASSIGN_ID不生效

### ISSUE THREAD

**Issue by hongshunanhai** [baomidou/mybatis-plus#4037]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
主键的类型使用@TableId(type = IdType.ASSIGN_ID)雪花算法，自己在xml写了Mapper的insertBatch方法，执行的时候提示java.sql.SQLException: Field 'id' doesn't have a default value

### 重现步骤(如果有就写完整)
```
nsert into agenda(name, user_id, project_id, agenda_type, status, started_at)         values                        (?, ?, ?, ?, ?, ?)          ,              (?, ?, ?, ?, ?, ?)          ,              (?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLException: Field 'id' doesn't have a default value
; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value] with root cause
```

### 报错信息
java.sql.SQLException: Field 'id' doesn't have a default value

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/injector/methods/InsertBatchSomeColumn.java
