### ISSUE TITLE
@TableField(typeHandler = MybatisEnumTypeHandler.class)在update操作时报错

### ISSUE THREAD

**Issue by GSTC** [baomidou/mybatis-plus#4038]
### 当前使用版本(必填,否则不予处理)
springboot 2.2.1
mybatis-plus 3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在官方的demo里，指定@TableField(typeHandler = MybatisEnumTypeHandler.class)，在updateById也会报错

### 重现步骤(如果有就写完整)
1. 定义枚举
![image](https://user-images.githubusercontent.com/2264251/140930060-55b428ec-fd2b-4927-914b-9901526527d9.png)

2.定义实体类
![image](https://user-images.githubusercontent.com/2264251/140930124-b594f0fc-8b01-40f5-a228-8ceb89dd56e9.png)

3.mybatis-plus配置
![image](https://user-images.githubusercontent.com/2264251/140930202-24e547e8-2cdd-47ad-9958-3fab187b061a.png)

4. DAO
![image](https://user-images.githubusercontent.com/2264251/140930585-120172ec-c8ed-481d-bb60-ebbed6be5b12.png)
![image](https://user-images.githubusercontent.com/2264251/140930618-5b64e415-edc5-4bca-9b27-c0255520d377.png)

5. service调用DAO
![image](https://user-images.githubusercontent.com/2264251/140930488-e07dd8b6-c869-4e16-b400-b82312e44e5e.png)

### 报错信息
![image](https://user-images.githubusercontent.com/2264251/140929952-4f3a4916-5a3d-49c2-b770-c1abeac07b17.png)

###辅助定位问题的信息
1. 必须得给枚举值指明@TableField(typehandler)，直接改springboot配置mybatis-plus.configuration.default-enum-type-handler为MybatisEnumTypeHandler不生效
2. @TableField(typeHandler = MybatisEnumTypeHandler.class, javaType = true)，加上这个javaType=true，MybatisEnumTypeHandler就能正确拿到枚举类型了，否则updateById的时候，拿到的是java.lang.Object类型

**Comment by lj870704** [comment]
有大哥可以解释下为什么呢？看了下底层，javaType的作用就是和jdbcType配合进行判断使用什么handler，但是赋值一个true是什么意思

**Comment by miemieYaho** [comment]
看文档,最新版不需要指定枚举包了
