### ISSUE TITLE
reactive和quarkus支持

### ISSUE THREAD

**Issue by jiafuzhang** [baomidou/mybatis-plus#4039]
### 当前使用版本(必填,否则不予处理)
3.4.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用https://code.quarkus.io/ 创建项目时，找不到mybatis，只有hibernate。

### 重现步骤(如果有就写完整)
idea2021->新建项目->quarkus->找不到mybatis扩展

### 报错信息
not find

**Comment by huayanYu** [comment]
找IDEA比较合适

**Comment by dongxicc** [comment]
不支持吧，quarkus-mybatis 是有的https://github.com/quarkiverse/quarkus-mybatis
