### ISSUE TITLE
Full table operation is prohibited

### ISSUE THREAD

**Issue by vipdon** [baomidou/mybatis-plus#404]
update 操作时提示  Full table operation is prohibited

`if (!"Using where".equals(rs.getString("Extra"))) {
                        if (this.isStopProceed()) {
                            throw new MybatisPlusException("Error: Full table operation is prohibited. SQL: " + boundSql.getSql());
                        }
                        break;
                    }`

实祭 rs.getString("Extra")  的值 为     Usingwhere;Using  temporary ，因此经常会报错，是bug吗

**Comment by qmdx** [comment]
你这是开启了 SQL 执行分析拦截器执行了全表操作被阻止了，详情看  SqlExplainInterceptor 源码

**Comment by fmeirlyn** [comment]
how to generate view in postgre with mybatisplus?
