### ISSUE TITLE
在使用BaseMapper提供的selectByMap方法，默认会执行自定义的类型转换器，但目的是不让默认执行

### ISSUE THREAD

**Issue by shanyaodexingxing** [baomidou/mybatis-plus#4049]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类型：
![image](https://user-images.githubusercontent.com/42084832/141715905-54c9ba00-bd7f-4355-8de9-ec77eb503218.png)
自定义类型转换器：
![image](https://user-images.githubusercontent.com/42084832/141715927-4a06ee76-287c-43fc-9643-1e1a5b62adf2.png)

### 重现步骤(如果有就写完整)
使用BaseMapper提供的selectByMap方法进行查询，实体类型已截图，其余都使用默认配置，在调用中发现实体类中String类型的字段会执行自定义的类型转换器，但是我没有指定。

**Comment by miemieYaho** [comment]
封装逻辑是mybatis的
