### ISSUE TITLE
多表查询，相同字段重复

### ISSUE THREAD

**Issue by huangjian888** [baomidou/mybatis-plus#405]
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'create_date' in where clause is ambiguous
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

LogServiceImpl：
public class LogServiceImpl extends CommonServiceImpl<LogMapper,Log> implements ILogService {
	@Override
	public Page<Log> selectPage(Page<Log> page, Wrapper<Log> wrapper) {
		wrapper.eq("1", "1");
		page.setRecords(baseMapper.selectLogPage(page, wrapper));
		return page;
	}
}
Mapper:
public interface LogMapper extends BaseMapper<Log> {
	
	List<Log> selectLogPage(Page<Log> page, @Param("ew") Wrapper<Log> wrapper);
}
Mapper.xml:
<sql id="Base_Column_List" >
    t.id, 
    t.type, 
    t.title, 
    t.content, 
    t.logtype, 
    t.create_by as "createBy.id", 
    t.create_date ,
    t.remote_addr, 
    t.user_agent, 
    t.request_uri, 
    t.method,
    t.params, 
    t.exception,
    u.realname as "createBy.realname",
    u.username as "createBy.username",
    u.create_date as "createBy.create_date"
  </sql>
  
  <select id="selectLogPage" resultType="Log">
	  select  
	  <include refid="Base_Column_List" />
	  from sys_log t 
	  LEFT JOIN sys_user u on t.create_by=u.id 
	  <where>
	   ${ew.sqlSegment} 
	  </where>
  </select>
用户表里面存在create_date 字段，并且日志表也有create_date 字段，出现字段重复，应该怎么处理呢

**Comment by qmdx** [comment]
可以考虑改一个属性名称

**Comment by huangjian888** [comment]
是否有多表相同字段分页查的文档么，或者该写法是不支持的？怎么能传别名进去呢

**Comment by qmdx** [comment]
多表 xml mp 不去修改 mybatis 原生 xml 多表逻辑，这块建议维护到 xml 比较好

**Comment by huangjian888** [comment]
好的，感谢回复
