### ISSUE TITLE
对于mybatis-plus自带的 savebatch 出现的主键自增问题

### ISSUE THREAD

**Issue by LjyDeerWhale** [baomidou/mybatis-plus#4050]
### 当前使用版本(必填,否则不予处理)

 <dependency>
     <groupId>com.baomidou</groupId>
     <artifactId>mybatis-plus-boot-starter</artifactId>
     <version>3.4.3.4</version>
 </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在测试一批数据时候使用了自带的saveBatch 进行批量增加(每次测试都会进行truncate),主键不会从第一个开始

### 报错信息
![微信截图_20211115131239](https://user-images.githubusercontent.com/41040767/141726101-9f0c8404-dc37-4b78-8a73-1bece3591402.png)

**Comment by qmdx** [comment]
雪花算法存在时间增长不是按顺序自增
