### ISSUE TITLE
关于Mybatis-Plus执行sql时创建Sqlsession的问题

### ISSUE THREAD

**Issue by lsay-git** [baomidou/mybatis-plus#4051]
### 当前使用版本(必填,否则不予处理)

Mybatis-Plus: 3.4.1
SpringBoot: 2.3.7.RELEASE

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

项目运行后，有时调接口执行sql时，会卡在 Create a new Sqlsession 这个步骤无法继续执行下去。

### 重现步骤(如果有就写完整)

请求接口到执行sql时 会出现如下情况

![image](https://user-images.githubusercontent.com/59008730/141734081-060c350a-c09b-4352-955b-282d5a5e76bc.png)

程序会卡在 create a new sqlsession ，很长一段时间后输出下一句。

### 报错信息

信息如下
![image](https://user-images.githubusercontent.com/59008730/141734081-060c350a-c09b-4352-955b-282d5a5e76bc.png)

**Comment by huayanYu** [comment]
这是正常的日志。
