### ISSUE TITLE
分页统计的sql没有加入租户id问题

### ISSUE THREAD

**Issue by iteaj** [baomidou/mybatis-plus#4060]
### 当前使用版本(必填,否则不予处理)
v3.4.2, 新版也有这个问题

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在MybatisPlusInterceptor里面新增了两个拦截器包括(TenantLineInnerInterceptor和PaginationInnerInterceptor)，如果分页拦截器配置在租户拦截器之前，那么会出现在做分页统计的时候租户id不生效的问题

### 重现步骤(如果有就写完整)
PaginationInnerInterceptor和PaginationInnerInterceptor拦截器再放入到MybatisPlusInterceptor的拦截器列表的时候有顺序问题，如果先加入分页拦截器而后加入租户拦截器会导致分页统计的sql不加入租户id

### 报错信息
不属于报错，分页统计的sql不加入租户id

**Comment by miemieYaho** [comment]
文档里都写了不去看
