### ISSUE TITLE
IPage查询结果有数据，接口返回数据变为了null

### ISSUE THREAD

**Issue by sayhei** [baomidou/mybatis-plus#4061]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 报错信息

IPage查询结果有数据，接口返回数据变为了null

接口返回直接返回ipage或者将ipage包到result实体里，都会出现这种现象

目前我这做法是重新定义一个自己的MyPage
```
@Data
@Builder
@Accessors(chain = true)
class MyPage{
    private  long total;

    private  List<T> data;
 
}
```
然后将Ipage里的数据 重新赋值到MyPage里就可以正常拿到数据：
```
MyPage.<E>builder().total(iPage.getTotal()).data(iPage.getRecords()).build()
```

![2111637378701_ pic_hd](https://user-images.githubusercontent.com/8320880/142713062-ec562481-cb14-4840-bfeb-91f66a61b8b5.jpg)
![2121637378715_ pic](https://user-images.githubusercontent.com/8320880/142713071-d1eaf649-8036-451d-b8fa-9861ad71e08d.jpg)

**Comment by miemieYaho** [comment]
给出你的git形式的demo

**Comment by kamjin1996** [comment]
ipage不是接口吗 返回com.baomidou.mybatisplus.extension.plugins.pagination.Page对象就好了
