### ISSUE TITLE
@TableField 注解的 target 属性问题

### ISSUE THREAD

**Issue by liaozan** [baomidou/mybatis-plus#4063]
### 当前使用版本(必填,否则不予处理)

 3.4.3.4

#### 源码显示`TableFiled` 可以打在注解上，但是实际打在注解上的时候，获取不到自定义注解上的`@TableField`，返回 `null`
<img width="514" alt="image" src="https://user-images.githubusercontent.com/26990889/142759416-a0581fbc-2452-4703-b759-6efd6e272f21.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/26990889/142759587-edb17ad9-0522-4254-81cc-5268f0bbf436.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/26990889/142759600-46326d74-f845-4df3-91f8-53644bf885ab.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/26990889/142759605-918458f9-c40c-40ab-98f0-f26988855ddf.png">

**Comment by Bjergsenj** [comment]
源码里面读的是TableField,并不是bizId这个注解,获取不到个人理解是正常的，
你可以通过 field.getAnnotations(); 看下你这个字段上都有哪些注解可以获取

**Comment by liaozan** [comment]
这个和bizId没有关系吧，我想说，TableField是支持打在注解上的，所以我理解，是可以作为元注解来使用的类似spring的Component(TableField)，RestController(BizId)，但是最终没有达到想要的效果

**Comment by Bjergsenj** [comment]
> 这个和bizId没有关系吧，我想说，TableField是支持打在注解上的，所以我理解，是可以作为元注解来使用的类似spring的Component(TableField)，RestController(BizId)，但是最终没有达到想要的效果

嗯嗯 明白你的意思,但是还是不太一样的
spring的@service,@controller等注解,有@AliasFor(annotation = Component.class)的支持
