### ISSUE TITLE
数据权限

### ISSUE THREAD

**Issue by lwl888** [baomidou/mybatis-plus#4070]
### 当前使用版本(必填,否则不予处理)
mate版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据权限SQL语句in括号内太多数据就会报错

### 重现步骤(如果有就写完整)
IN很多数据

### 报错信息
直接报错

**Comment by qmdx** [comment]
你可以试用 jsqlparser 表达式组合 sql 语句解决
