### ISSUE TITLE
sql in拼接问题

### ISSUE THREAD

**Issue by ansel-peng** [baomidou/mybatis-plus#4075]
### 当前使用版本(必填,否则不予处理)
3.4.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

 QueryWrappe in方法ArrayList为空 最后sql语句报错 WHERE (state = ? AND server_group_id IN ()) 
 in拼接为()应为in(null)

**Comment by miemieYaho** [comment]
不支持
