### ISSUE TITLE
AbstractWrapper orderB() 方法缺少，column 列名传入字符串的功能，手动转SFunction无效

### ISSUE THREAD

**Issue by bigintpro** [baomidou/mybatis-plus#4076]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
大量的排序字段和排序方式需要由前端控制，如果代码中都是if-else，不优雅，同时为了防止sql注入，应该model类做一次校验

**Comment by miemieYaho** [comment]
不支持

**Comment by bigintpro** [comment]
我已经代码实现了，要怎么样才能合并到仓库主分支

**Comment by miemieYaho** [comment]
不接受
