### ISSUE TITLE
tinyint(1) 无法通过@EnumValue解析

### ISSUE THREAD

**Issue by haut-zm** [baomidou/mybatis-plus#4077]
### 当前使用版本(必填,否则不予处理)
3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
MySQL数据库设置属性类型为tinyint(1)，实体类枚举属性添加注解@EnumValue，但是查询时，无法解析成枚举类型

### 重现步骤(如果有就写完整)
1、设置数据库类型为tinyint(1)
2、添加对应实体类的属性@EnumValue
3、查询单条记录、分页、列表
4、具体枚举属性无数据，显示为null

### 报错信息
无报错信息，但是查询结果为null

**Comment by miemieYaho** [comment]
文档-常见问题
