### ISSUE TITLE
EXPLAIN之后跟UPDATE报错

### ISSUE THREAD

**Issue by KevinPan1992** [baomidou/mybatis-plus#4078]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
通过EXPLAIN 之后跟sql语句,校验sql是否正确;EXPLAIN SELECT可以正常执行,EXPLAIN UPDATE报错,直接报sql复制到Navicat中是可以正常执行的

### 报错信息
Error updating database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: EXPLAIN UPDATE ***

**Comment by miemieYaho** [comment]
jsqlparser 解析报错

**Comment by KevinPan1992** [comment]
> jsqlparser 解析报错

关键是怎么 解决呢,我也找到是 jsqlparser 解析报错

**Comment by miemieYaho** [comment]
文档里:注解排除该method走插件

**Comment by KevinPan1992** [comment]
> 文档里:注解排除该method走插件

具体怎么操作,能来点代码吗?网上也找不到类似的解决方案

**Comment by KevinPan1992** [comment]
方法上面使用注解
@InterceptorIgnore(tenantLine = "1")
