### ISSUE TITLE
IPage 侵入性太强了

### ISSUE THREAD

**Issue by galaxy-sea** [baomidou/mybatis-plus#4080]
### 当前使用版本(必填,否则不予处理)

3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在feign 接口中使用了 IPage之后导致 第三方包需要引入 mybatis-plus-core 

个人觉得 IPage完全可以放到独立到  mybatis-plus-metadata 中

**Comment by qmdx** [comment]
可以自定义其他对象传输
