### ISSUE TITLE
MetaObjectHandler能不能把 SqlCommandType 传进来

### ISSUE THREAD

**Issue by liaozan** [baomidou/mybatis-plus#4081]
处理 updateFill 的时候想根据 SqlCommandType 进行不同的处理，如果是删除，给某个字段赋值，比如逻辑删除时同时给逻辑删除版本字段赋值

**Comment by miemieYaho** [comment]
逻辑删除下SqlCommandType是UPDATE

**Comment by yan624** [comment]
那咋区分是逻辑删除还是更新啊？
