### ISSUE TITLE
updateBatchById应该判断每条sql是否更新成功

### ISSUE THREAD

**Issue by zhouquan2016** [baomidou/mybatis-plus#4085]
### 当前使用版本(必填,否则不予处理)

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.0</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

com.baomidou.mybatisplus.extension.service.IService#updateBatchById(java.util.Collection<T>)，调用这个方法每个实体都有两个版本号，实体类数据完全一直，并发情况下实际多个事务只有一个事务数据库更新成功，但是调用这个方法都是返回true，应该是一个事务返回true，其他事务都返回false

### 重现步骤(如果有就写完整)

同一个业务接口，idea debug 断点打在updateBatchById，请求两次

### 报错信息
无报错，两次请求都返回true，具体原因是com.baomidou.mybatisplus.extension.service.impl.ServiceImpl#updateBatchById，
![image](https://user-images.githubusercontent.com/18661266/143804887-03207e93-f59f-410a-b2bc-4ea3939b8067.png)
这里没有判断受影响的行

**Comment by miemieYaho** [comment]
mybatis的batch方法只会返回固定值

**Comment by zhouquan2016** [comment]
其中一条没更新成功不应该返回false吗？我们业务出现幂等性问题了！

**Comment by zhouquan2016** [comment]
> 其中一条没更新成功不应该返回false吗？我们业务出现幂等性问题了！



> mybatis的batch方法只会返回固定值
其中一条没更新成功不应该返回false吗？我们业务出现幂等性问题了！
