### ISSUE TITLE
LambdaUpdateChainWrapper.update()

### ISSUE THREAD

**Issue by liaozan** [baomidou/mybatis-plus#4090]
### 当前使用版本(必填,否则不予处理)

3.4.3.4

LambdaUpdateChainWrapper.update()是继承自 ChainUpdate，ChainUpdate的默认实现是调用了重载的 update(null)
由于这里传入的是 null，导致在 MybatisParameterHandler#process 方法的时候获取不到 entity，最终导致 MetaObjectHandler 无法支持 lambda 写法的 update 进行自动填充。
能不能调用空参 update 的时候，传入一个默认的空 bean，让 MybatisParameterHandler#process 处理的时候可以拿到 entity，最终体现在 MetaObjectHandler 可以处理 lambda 写法的 fill

**Comment by miemieYaho** [comment]
不能,按需使用,你想要那样就new个出来放进去
