### ISSUE TITLE
逻辑删除问题

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4091]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

### 重现步骤(如果有就写完整)

把 @TableLogic注解全部删除了,逻辑删除出现问题
因为看官方文档说
全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
所以我专门删除了

**Comment by miemieYaho** [comment]
什么问题说清楚,该截图截图

**Comment by 274574162** [comment]
![image](https://user-images.githubusercontent.com/39609367/143974581-b3fada5b-142b-430a-a98f-08ed0f6ff660.png)
是不是第一步做完逻辑删除就可以用了,但是不加注解是不生效的,我使用的最高版本

**Comment by miemieYaho** [comment]
你的配置截图呢?你的entity截图呢?你的程序代码截图呢?你的sql执行打印截图呢?

**Comment by 274574162** [comment]
手动封装了自定义数据源导致失败
