### ISSUE TITLE
使用lambdaUpdate更新增量值，如何可以写的更优雅？

### ISSUE THREAD

**Issue by beamofsoul** [baomidou/mybatis-plus#4092]
现在这样写：
基本上update table set a = a + x
`preSecondDao.update(newPre, Wrappers.<PreSecond>lambdaUpdate()
                    .eq(PreSecond::getId, preSecond.getId())
                    .setSql(" a = a + " + preSecond.getGuarantee()));`

如何可以使用API写的更优雅，更符合类型安全呢？

**Comment by miemieYaho** [comment]
就这样的
