### ISSUE TITLE
多租户分页查询

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4093]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
多租户分页查询问题

### 重现步骤(如果有就写完整)
查询总条数不是0,结果是0,总数好像没没添加租户条件

**Comment by miemieYaho** [comment]
看文档

**Comment by qingbinyang** [comment]
大凶死，这个问题怎么处理的？

**Comment by qingbinyang** [comment]
> 看文档

请问文档的链接是多少？
