### ISSUE TITLE
@SqlParser(filter = true) 失效

### ISSUE THREAD

**Issue by Wsinry** [baomidou/mybatis-plus#4094]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
SQL中含有:= 符号，无法解析，需要过滤租户验证

### 重现步骤(如果有就写完整)
mapper代码：
    @SqlParser(filter = true)
    List<DepartmentDO> queryAllSubDeptsById(Long deptId);
添加@SqlParser(filter = true) ，SQL还是添加了tenant_id字段

### 报错信息
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ":" ":"

望解答，感谢

**Comment by miemieYaho** [comment]
过时api不处理

**Comment by Wsinry** [comment]
> 过时api不处理
@sqlparser(filter = true) 这个注解不是3.4.x开始才失效吗，那现在是不是需要把mybatis-plus 升级到 3.4.x，然后使用
@InterceptorIgnore(tenantLine = "true") 代替？

**Comment by Wsinry** [comment]
升级到3.4.1，采用@InterceptorIgnore(tenantLine = "true") 注释还是不行，SQL依然会带上tenant_id，是不是还需要什么配置？
