### ISSUE TITLE
给数据库字段设置默认值的时候是直接在数据库中设置default还是在程序中定义比较好

### ISSUE THREAD

**Issue by quezhihui** [baomidou/mybatis-plus#4095]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

这些有规范吗，比如像创建时间，更新时间，是否删除这样的字段，考虑到要用到索引不能为null
所以必须设置默认值。但好像没有很明确的说法这些设置在数据库中还是写在程序里。但是唯一知道的是写在程序中的话要考虑分布式时间同步问题，数据库一般读写分离1主多从的话就没这个情况。

### 重现步骤(如果有就写完整)
![5 2OXS3 }D 5HHIH$_45N(O](https://user-images.githubusercontent.com/13636503/143977774-3bb2e9b1-e9f9-4869-ade5-01894acdedef.png)

![U0R PMUJESH5 14{E9F(`T7](https://user-images.githubusercontent.com/13636503/143977811-4d8a210b-2f52-4fac-9d02-14b9e59925a0.png)

**Comment by quezhihui** [comment]
这两种方案哪种更好一些，考虑到兼容多类型数据库和应用分布式部署

**Comment by 274574162** [comment]
我们都是时间自动更新,比如你执行脚本或者手动改库的时候时间会自动更新,如果代码维护时间就不会变,看公司了,一般很少直接修改数据库,哪一种都行,一个公司用一种就行了

**Comment by huayanYu** [comment]
规范看公司。
