### ISSUE TITLE
typeHandler不支持泛型，是否可以参考@RequestBody解决？

### ISSUE THREAD

**Issue by liu-xinhui** [baomidou/mybatis-plus#4096]
@TableField(typeHandler = JacksonTypeHandler.class)
不支持泛型，因为java编译后泛型就丢失了。导致List类型的数据处理比较麻烦

但是spring mvn实现post接口时@RequestBody却支持泛型，是否可以参考？

**Comment by miemieYaho** [comment]
参考不了,mybatis不支持
