### ISSUE TITLE
自动填充建议,非问题

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4098]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
建议:自动填充问题
![image](https://user-images.githubusercontent.com/39609367/144164331-5750c51b-4bd7-43e3-ad8d-39ae1ede8a62.png)
既然实现已经指定了字段名,注解就没必要加了吧,添加字段对应不上他也填充不进去的
能否优化,忽略填充注解,应为大部分用户字段都是需要填充的

### 报错信息
嘿嘿

**Comment by whcrow** [comment]
注解 `com.baomidou.mybatisplus.annotation.TableField#fill` 决定生成的sql脚本，

```
com.baomidou.mybatisplus.core.handlers.MetaObjectHandler#insertFill
com.baomidou.mybatisplus.core.handlers.MetaObjectHandler#updateFill
```
是赋值，

不是一回事。

**Comment by miemieYaho** [comment]
如上,不加注解本身字段为null后赋值并不会在sql里出现该字段
