### ISSUE TITLE
LambdaQueryWrapper.orderBy 可变参数列表泛型警告

### ISSUE THREAD

**Issue by ningyudie** [baomidou/mybatis-plus#4099]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.core.conditions.interfaces.Func#orderByDesc(R, R...) 的泛型可变参数警告
![image](https://user-images.githubusercontent.com/40515646/144174807-76582fe3-a517-4af5-9db8-687200142486.png)

如果可以, 建议和 `java.util.Arrays#asList` 一样, 加上 `@SafeVarargs` 和 `@SuppressWarnings("varargs")`

![image](https://user-images.githubusercontent.com/40515646/144175025-7141445a-6b2a-4c58-b6a2-65d6072a8b21.png)

**Comment by huayanYu** [comment]
新版的应该没有了吧。

**Comment by ningyudie** [comment]
> 新版的应该没有了吧。

我现在用的 3.4.3  还是有这个警告. 除非在每个用到 orderBy 的地方手动 `@suppressWarnings`  或者关闭IDEA的检查
但是不合理

**Comment by qmdx** [comment]
使用 list 传参方法避免警告

**Comment by vxinv** [comment]
确实3.4.3 依然有问题 提示创建可变参数泛型数组

**Comment by vxinv** [comment]
而且我找不到 idea怎么关

**Comment by vxinv** [comment]
> `suppressWarnings`



> > 新版的应该没有了吧。
> 
> 我现在用的 3.4.3 还是有这个警告. 除非在每个用到 orderBy 的地方手动 `@suppressWarnings` 或者关闭IDEA的检查 但是不合理

3.4.3.4 已经把这个方法不推荐使用了

**Comment by vxinv** [comment]
> 
也可以这样使用

		LambdaQueryWrapper<YsCategory> lqw = new LambdaQueryWrapper<YsCategory>()
			.eq(YsCategory::getShopId,shopId)
			.eq(YsCategory::getIsVisible, YsCategory.defalutVid)
			.orderByAsc(YsCategory::getSort)
			.orderByAsc(YsCategory::getCategoryPic);

**Comment by ningyudie** [comment]
> > 
> 
> 也可以这样使用
> 
> ```
> 	LambdaQueryWrapper<YsCategory> lqw = new LambdaQueryWrapper<YsCategory>()
> 		.eq(YsCategory::getShopId,shopId)
> 		.eq(YsCategory::getIsVisible, YsCategory.defalutVid)
> 		.orderByAsc(YsCategory::getSort)
> 		.orderByAsc(YsCategory::getCategoryPic);
> ```

有什么区别? 没看出来

**Comment by vxinv** [comment]
我已经不用plus了 没什么优势
