### ISSUE TITLE
自动生成的serviceimpl怎么集成spring-cache注解

### ISSUE THREAD

**Issue by fatg1988** [baomidou/mybatis-plus#41]
如题，请问框架集成cache的扩展点在哪里

**Comment by yuxiaobin** [comment]
spring cache是针对interface 的public方法的实现，目前生成的serviceImpl里面没有其他方法，都是父类的方法。
如果要加缓存，你得定义一个方法，根据参数来做缓存。

**Comment by qmdx** [comment]
1、复制我们提供的 service 去处理
2、重写父类方法
