### ISSUE TITLE
insert数据updateTime时间填充无效

### ISSUE THREAD

**Issue by aptexd** [baomidou/mybatis-plus#4105]
### 当前使用版本(必填,否则不予处理)

3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

updateTime 字段用这个注解 `@TableField(fill = FieldFill.INSERT_UPDATE)` 在insert的时候更新“更新时间”无效

### 重现步骤(如果有就写完整)

本场景实用的是PostgreSQL，createTime没有问题

**Comment by huayanYu** [comment]
无法复现，建议提供基础demo，重新补充详细复现步骤，重新提交
