### ISSUE TITLE
ServiceImpl 获取entity和mapper 存在问题

### ISSUE THREAD

**Issue by yangs-dever** [baomidou/mybatis-plus#4108]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自己定义了一个抽象类 去集成 hibernate 的 dao,mybatis-plus的Mapper,Entity 和 Mybatisplus的ServiceImpl
在实现类里面使用 saveOrUpdate
提示 can not execute ...... not find cache of TableInfo for entity

### 重现步骤(如果有就写完整)
编写一个抽象类
abstract class AbstractBaseService<D extends BaseDao<T>,M extends BaseMapper<T> ,T extends BaseEntity<t>> extends ServiceImpl<M,T> implements BaseService<D,M,T>

然后在 serviceImpl extends AbstractBaseService implements service{

方法（）{
saveorUpdate(xxxxxx);
}

}

### 报错信息
提示 can not execute ...... not find cache of TableInfo for entity

问题主要出现在 ServiceImpl类里面
protected Class<T> entityClass = this.currentModelClass(); //获取第0个
protected Class<T> mapperClass = this.currentMapperClass(); //获取第1个

**Comment by qmdx** [comment]
高版本该问题已经解决升级到 `3.4.3.4 +`
