### ISSUE TITLE
条件构造器不支持自定义参数别名

### ISSUE THREAD

**Issue by zhangshiyao0114** [baomidou/mybatis-plus#4110]
### 当前使用版本(必填,否则不予处理)
3..4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用自定义参数别名的时候报错

@Select("select * from table ${query.customSqlSegment}")
Page<VO> getWorkPage(Page<Entity> page, @Param("query") Wrapper wrapper);

### 报错信息

nested exception is org.apache.ibatis.binding.BindingException: Parameter 'ew' not found. Available parameters are [arg0, query, param1, param2]

**Comment by miemieYaho** [comment]
不支持
