### ISSUE TITLE
is_Del 配置之后，直接是全局的，能不能在查询的时候根据需要进行关闭呢？

### ISSUE THREAD

**Issue by seart** [baomidou/mybatis-plus#4112]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

想问一下，如果在字段里进行了配置，但是在查询语句的时候默认会把 is_del = false 条件带上，但是还是想把删除的数据进行关联查询出来，除了手动写sql， 是否有优先级配置呢？
例如在 LambdaQueryWrapper 查询中，即使设置了 is_del  in( true, false) 还是不能查询出被删除的数据，能否以查询语句的为主，如果查询语句中没有设置 is_del 就采用默认的查询

**Comment by miemieYaho** [comment]
不能
