### ISSUE TITLE
 wrapper.lambda().select(Message::getUserId); 只查这一个字段,如何返回List<Long> 泛型的集合?

### ISSUE THREAD

**Issue by patience00** [baomidou/mybatis-plus#4116]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如果我调用的iserviceImpl实现类的listObj(),返回的是List<Object>,请问支持泛型吗?

**Comment by miemieYaho** [comment]
不能,底层是mybatis
