### ISSUE TITLE
mybatis-plus-extension中InsertBatchSomeColumn(List<T> entityList) 

### ISSUE THREAD

**Issue by cchil** [baomidou/mybatis-plus#4121]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus-extension 的3.4.3.4版本中InsertBatchSomeColumn(List<T> entityList) 
entityList中必须有值？如果传了一个空的entityList，会报错

### 报错信息
syntax error, expect ')', pos 229, line 1, column 230, token EOF

**Comment by miemieYaho** [comment]
不支持空

**Comment by cchil** [comment]
嗯嗯。好的。
