### ISSUE TITLE
Wrappers.query().后面条件被括号括起来了，某些条件结果不同

### ISSUE THREAD

**Issue by qq294145849** [baomidou/mybatis-plus#4122]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

正常查询列表

### 重现步骤(如果有就写完整)

1、user实体类
User user = User();
user.setDeleted(0);
String name="李";
String phone="133";
int sex=0;
2、Service.page(page,Wrappers.query(user).eq("sex",sex).like("name",name).or().like("phone",phone);

真实sql：select * from user where  delete=0  and（sex=0 and name like '%李%' or phone like '%133%'）

想要达目的：去掉括号，多了一个括号，很多时候想查询的结果会不一样
select * from user where  delete=0 and sex=0 and name like '%李%' or phone like '%133%'

### 报错信息
无报错

**Comment by miemieYaho** [comment]
不支持

**Comment by qq294145849** [comment]
上次举例不当
2、Service.page(page,Wrappers.query(user).or().like("phone",phone);

真实sql：select * from user where delete=0 and（phone like '%133%'）

想要达目的：去掉括号，多了一个括号，很多时候想查询的结果会不一样
select * from user where delete=0 or phone like '%133%'

**Comment by gudu-zhe** [comment]
为什么我现在查询还是有这个括号存在？

**Comment by gudu-zhe** [comment]
还是说就是这样设计的？
