### ISSUE TITLE
mybatis-plus-boot-starter: Remote code injection in Log4j

### ISSUE THREAD

**Issue by hycao** [baomidou/mybatis-plus#4128]
### 当前使用版本(必填,否则不予处理)

``` 
compile group: 'com.baomidou', name: 'mybatis-plus-boot-starter', version: '3.3.1'
```
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

log4j 出现远程执行漏掉，经排查，我们项目中  引入log4j 的地方来自于 `mybatis-plus-boot-starter`

![image](https://user-images.githubusercontent.com/51392146/145530281-e17f03e3-a26d-43cc-b3c2-5cd7ba7988d0.png)

![image](https://user-images.githubusercontent.com/51392146/145530110-dd4b478d-bb84-42b1-a6ae-7e2bd4208e1f.png)

**Comment by miemieYaho** [comment]
你这要我们说啥好,看图也知道这是spring-boot-satrter-logging依赖下的包嘛
