### ISSUE TITLE
同一个字段名有两种Class类型怎样全局填充

### ISSUE THREAD

**Issue by yanzhisishui** [baomidou/mybatis-plus#4129]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
全局填充时候不能兼容两种类型
![image](https://user-images.githubusercontent.com/44022031/145545036-3fc53b36-dfd2-4cd8-b74a-68034948186e.png)

### 重现步骤(如果有就写完整)
更新Date类型可以填充，更新OffsetDateTime 类型不能填充
![image](https://user-images.githubusercontent.com/44022031/145545098-3b71f008-cf23-4988-9ad9-3069b19da493.png)

是否现在的版本不支持？后续有没有可能支持？

### 报错信息
无

**Comment by miemieYaho** [comment]
给出git形式的复现demo

**Comment by yanzhisishui** [comment]
> 给出git形式的复现demo
额。。不是太懂，是要代码吗？git 形式是啥？
