### ISSUE TITLE
update(entity, wrapper) 支持自动注入乐观锁吗？

### ISSUE THREAD

**Issue by liuzhaowei55** [baomidou/mybatis-plus#4132]
### 当前使用版本(必填,否则不予处理)

3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

乐观锁文档中提到的 `update(entity, wrapper)` 使用是指查询条件，更新字段都自己手动添加 version 字段吗？
目前是只有 updateById 这个方法可以自动添加查询与更新 version

**Comment by qmdx** [comment]
你可以试试新版本 `3.5.1`
