### ISSUE TITLE
3.4.3的bug: mybatis-plus-3.4.3不支持BaseServiceImpl<M extends BaseMapper<T>,T>的superService类

### ISSUE THREAD

**Issue by 564155611** [baomidou/mybatis-plus#4134]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
从mybatis-plus-3.2.0升级到mybatis-plus-3.4.3

### 重现步骤(如果有就写完整)
mybatis-plus-3.4.3不支持BaseServiceImpl<M extends BaseMapper<T>,T>的superServiceImpl类,一旦引入就会报错
可以从本人[oversell](https://github.com/564155611/elastic-lock/tree/master/03_oversell  "oversell项目")项目中执行测试:
com.imooc.elasticlock.oversell.OversellApplicationTests#concurrentOrder就会出现附件中的错误:**sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class**

另外希望扩充一下updateWrapper的功能:我继承了UpdateWrapper类添加的两个方法我觉得还是很有意义的.因为当前的UpdateWrapper无法实现 SET COUNT=COUNT-?的SET SQL

### 报错信息

![image](https://user-images.githubusercontent.com/73692902/145680527-398572c3-530d-4c7f-996c-c20fbe05ac12.png)

**Comment by jptx1234** [comment]
应该是这个问题：https://github.com/baomidou/mybatis-plus/issues/3540
升级即可：https://search.maven.org/artifact/com.baomidou/mybatis-plus
https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md#v3431-20210615
