### ISSUE TITLE
为什么不建议使用int类型作为自增主键, 而且还打成了warn级别的日志

### ISSUE THREAD

**Issue by bthulu** [baomidou/mybatis-plus#4135]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类主键如下
`
    @TableId(type = IdType.AUTO)
    private int id;
`
spring boot启动时, 日志中会打印
`This primary key of "id" is primitive !不建议如此请使用包装类 in Class`
为什么使用warn级别呢? 会造成mybatis-plus的某些功能用不了吗?
我的实体类一般是能用primitive类型就用primitive类型, 避免NPE.
之前一直用的spring data jdbc, 当使用primitive类型时, 它是按 id = 0来区分是不是已经save过一次了.
按说java的NPE这么多, 不是应该提倡使用原始类型吗? 如果对mybatis-plus没有功能上的影响, 建议这条日志去掉

### 重现步骤(如果有就写完整)
实体类自增主键如下设置, 然后启动spring boot
`
    @TableId(type = IdType.AUTO)
    private int id;
`

**Comment by liuzhaowei55** [comment]
[关于 Long 型主键填充不生效的问题](https://baomidou.com/guide/faq.html#%E5%85%B3%E4%BA%8E-long-%E5%9E%8B%E4%B8%BB%E9%94%AE%E5%A1%AB%E5%85%85%E4%B8%8D%E7%94%9F%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by bthulu** [comment]
> [关于 Long 型主键填充不生效的问题](https://baomidou.com/guide/faq.html#%E5%85%B3%E4%BA%8E-long-%E5%9E%8B%E4%B8%BB%E9%94%AE%E5%A1%AB%E5%85%85%E4%B8%8D%E7%94%9F%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98)
我试过了, 3.4.3.4版本里long主键填充是正常的, 这个问题应该早就解决掉了.
所以我提的这个issue依然有效, 不应该关闭, 请重新打开
