### ISSUE TITLE
$开头的字段无法识别，查询结果中没有包含$开头的字段

### ISSUE THREAD

**Issue by lvgitt** [baomidou/mybatis-plus#4136]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 
-- auto-generated definition
create table home
(
    id                         bigint auto_increment primary key,
    $home               varchar(10)  null
)
   charset = utf8mb4;

### 重现步骤(如果有就写完整)

通过mybatis-plus查询API-selectMaps,无法正常返回有值的 $home 字段

### 报错信息

无

**Comment by miemieYaho** [comment]
不支持
