### ISSUE TITLE
能不能大致讲讲Wrapper构建完成之后 mapper是如何处理的

### ISSUE THREAD

**Issue by 550932785** [baomidou/mybatis-plus#4138]
### 当前使用版本(必填,否则不予处理) 3.4.1

自己查了源码 发现BaseMapper在这里面传入之后 没找到后续代码 麻烦给点思路

**Comment by mabyoung** [comment]
后续的CRUD动态sql注入代码，是在mybatis-plus-core包下，你可以研究下mybatis-plus-core下的代码

**Comment by mabyoung** [comment]
具体的：对于Wrapper，会参与动态sql的select和where条件拼接，select条件拼接对应com.baomidou.mybatisplus.core.injector.AbstractMethod.sqlSelectColumns()方法，where条件拼接对应com.baomidou.mybatisplus.core.injector.AbstractMethod.sqlWhereEntityWrapper()方法

**Comment by qmdx** [comment]
更多细节自行查看源码

**Comment by 550932785** [comment]
@mabyoung  @qmdx 感谢解惑 谢谢了

**Comment by mabyoung** [comment]
> @mabyoung @qmdx 感谢解惑 谢谢了

客气了大佬，有问题多交流
