### ISSUE TITLE
3.0-RC分页有问题

### ISSUE THREAD

**Issue by Kimmyzhao** [baomidou/mybatis-plus#414]
调试截图如下
![87bfdbf99b545c31d1b79a40756fc998](https://user-images.githubusercontent.com/11455494/43438338-5b6d5e94-94c0-11e8-94c0-ed9861ba9308.jpg)
控制台打印SQL如下:
![qq20180731-125142](https://user-images.githubusercontent.com/11455494/43438371-833f4806-94c0-11e8-92f4-eac6868dde41.png)
已经配置了分页插件
![qq20180731-125314](https://user-images.githubusercontent.com/11455494/43438421-bfc91e46-94c0-11e8-8424-e224c2813456.png)

**Comment by Kimmyzhao** [comment]
同样的配置,不同的版本,2.3版本分页就是好的

**Comment by qmdx** [comment]
3.0 将不在支持 localpage 模式，更多你可以参考

**Comment by qmdx** [comment]
https://github.com/baomidou/dynamic-datasource-spring-boot-starter
