### ISSUE TITLE
分页插件分页查询只返回了总数

### ISSUE THREAD

**Issue by guilter** [baomidou/mybatis-plus#4140]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用的h2数据库，使用分页插件分页，已配置好了PaginationInnerInterceptor，未写sql语句而使用的selectPage方法，
发现此方法只返回了总数，其他查询都正常。

### 重现步骤(如果有就写完整)
1.使用h2数据库(最新)
2.使用分页插件，已配置好了MybatisPlusInterceptor、PaginationInnerInterceptor，且DbType选择了H2数据库
3.未实现Mapper的selectPage接口(即没有写sql)，使用默认实现。service那些都使用默认实现
4.在controller中调用service.page(page,wrapper)方法，发现返回了记录总数未返回数据(records为空)
5.查看sql打印，发现只有一条查询总数的语句

### 报错信息
无

**Comment by miemieYaho** [comment]
total不是0吗?

**Comment by guilter** [comment]
> total不是0吗?

total显示的是正确的总数，records是空的。

**Comment by miemieYaho** [comment]
那你给出一个git形式的demo看看

**Comment by guilter** [comment]
找到原因了，size参数传了null之后，size默认变为0了。不好意思叨扰了。。。
