### ISSUE TITLE
Mapper自动生成的部分方法不支持sqlFirst

### ISSUE THREAD

**Issue by liverliu** [baomidou/mybatis-plus#4143]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.core.injector.methods.* 下只有部分方法支持sqlFirst(如SelectList)，Delete，Update等方法不支持
，希望都能够加上对sqlFirst的支持。

**Comment by miemieYaho** [comment]
说说你想干什么

**Comment by huayanYu** [comment]
无回复关闭， 如有需要请详细描述重新提
