### ISSUE TITLE
mybatis-plus 在SQL server下 sql 重复执行

### ISSUE THREAD

**Issue by youngerier** [baomidou/mybatis-plus#415]
mbp 配置
![image](https://user-images.githubusercontent.com/10486543/43466640-8e8f6432-9512-11e8-8754-9978d15e6873.png)

druid 配置
![image](https://user-images.githubusercontent.com/10486543/43466717-bda0a678-9512-11e8-9452-cd71b28d5953.png)

控制台输入
![image](https://user-images.githubusercontent.com/10486543/43466495-3be4a51c-9512-11e8-8909-2519c7d64750.png)

druid 监控

![image](https://user-images.githubusercontent.com/10486543/43466533-513a2c70-9512-11e8-8b93-3ac602b8532a.png)

请问有没有配置错误的地方会 让sql 多次执行?

**Comment by qmdx** [comment]
无 sqlServer 测试环境，欢迎解决 PR

**Comment by shanty-per** [comment]
请问你这个问题解决了吗，我也是出现这种情况

**Comment by shanty-per** [comment]
求助求助
![Uploading image.png…]()

**Comment by shanty-per** [comment]
<img width="1112" alt="Snipaste_2024-12-26_18-04-41" src="https://github.com/user-attachments/assets/d3ca15cb-b430-436e-afe0-554d84140930" />
