### ISSUE TITLE
使用insql如何避免sql注入

### ISSUE THREAD

**Issue by lyyu1988** [baomidou/mybatis-plus#4162]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

**Comment by mabyoung** [comment]
insql是指什么呀，是指在wrapper中使用条件构造器in吗

**Comment by qmdx** [comment]
底层有处理，如果不放心可用调用  com.baomidou.mybatisplus.core.toolkit.sql.SqlInjectionUtils  自行验证一遍

**Comment by lyyu1988** [comment]
> insql是指什么呀，是指在wrapper中使用条件构造器in吗

wrapper条件构造器中的insql，文档里面有写

**Comment by Ahaochan** [comment]
用前端传入的查询条件，在数据库里预先查询一遍，再用查出来的数据传入inSql中进行查询，确保前端入参的合法性。
以下是伪代码
```
List<String> list = mapper.select("select name from user where name in (?,?,?)", usernameList);

wrapper.inSql("name", "select name from user where name in ('" + list.join("','") + "')");
```
