### ISSUE TITLE
建议将Bean到表的映射关系定义放到Mapper中

### ISSUE THREAD

**Issue by ccor** [baomidou/mybatis-plus#4169]
### 当前使用版本(必填,否则不予处理)
v3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
目前的使用@TableName等注解用于实体Bean上，会造成实体bean对mybatis-plus的强依赖；
也就是实体bean如果出dao层会把mybatis-plus带着；
其实mybaits对实体bean到标的映射是定义在mapper.xml中的，可以考虑在Mapper中定义个关系，这样可以解除bean对组件的依赖；
可以考虑
1、通过注解定义映射关系；
2、在BaseMapper定义映射关系获取接口，在子类中实现具体映射关系；

**Comment by qmdx** [comment]
实体 bean 与 mapper 解耦吗？ mp 是初始化注入的绑定不可避免

**Comment by qmdx** [comment]
实体 bean 与 mapper 解耦吗？ mp 是初始化注入的绑定不可避免
