### ISSUE TITLE
kotlin使用MetaObjectHandler 字段填充注入问题

### ISSUE THREAD

**Issue by doctorzgh** [baomidou/mybatis-plus#4192]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类文件也是.kt 基本类型字段填充比如 int 和boolean
StrictFill Class<T> fieldType 与tableInfo获取的fieldList 的TableFieldInfo 的PropertyType对应的类型不匹配
前者是kotlin stdlib,后者是java.lang包下的
希望提供string类型的propertyType匹配解决

### 重现步骤(如果有就写完整)
save

### 报错信息
没有报错

**Comment by qmdx** [comment]
欢迎 pr
