### ISSUE TITLE
springboot + mybatis-plus 3.4 use H2 database query error!

### ISSUE THREAD

**Issue by phial3** [baomidou/mybatis-plus#4193]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.4.3.4  

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
use H2 driver

### 报错信息
![image](https://user-images.githubusercontent.com/27754514/147559269-da344a20-d6a6-44a5-87f5-72336a194afc.png)

**Comment by qmdx** [comment]
sql 的写法错了
