### ISSUE TITLE
重写默认的mapper方法失败

### ISSUE THREAD

**Issue by ludonghai715** [baomidou/mybatis-plus#4196]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

重写默认的mapper方法（selectList, selectById。。。），
如果是引用的ResultMap，则重写失败，调用的还是默认的方法
如果是重写方法上定义的Results，则是重写成功

![bug](https://user-images.githubusercontent.com/740845/147796718-af283373-5814-4783-9181-4fb3da0b2654.png)

**Comment by Bjergsenj** [comment]
你这个什么场景需要重写方法呢？ 
是否可以参考自定义baseMapper的方式解决问题
参考链接如下:
https://baomidou.com/pages/42ea4a/
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-deluxe

**Comment by ludonghai715** [comment]
有时候需要返回的结果里有one2one， one2many，但还是希望mapper接口的命名采用默认的命名， 例如selectList
![bug](https://user-images.githubusercontent.com/740845/147796682-73d114f5-250c-4c36-963e-bc063b933d15.png)

**Comment by miemieYaho** [comment]
mybatis加载顺序问题,首次加载失败(比如你指定的resultmap没提前于这个方法被加载)会进入重试,重试期间mp自带的方法先加载了,所以你就无法重写了
