### ISSUE TITLE
添加@Param导致自动填充失效

### ISSUE THREAD

**Issue by lingfenghu** [baomidou/mybatis-plus#4199]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Mappper层使用@Param 导致自动填充失效
 void addButtons(@Param("buttons") Set<Button> buttons);

**Comment by lingfenghu** [comment]
这个有什么好的解决办法吗？

**Comment by nieqiurong** [comment]
用@Param(“collection”)

**Comment by lingfenghu** [comment]
谢谢
