### ISSUE TITLE
3.5.0 存在一个 System.out.println

### ISSUE THREAD

**Issue by liaozan** [baomidou/mybatis-plus#4211]
### 当前使用版本(必填,否则不予处理)
3.5.0

[com/baomidou/mybatisplus/extension/spring/MybatisSqlSessionFactoryBean.java:609](https://github.com/baomidou/mybatis-plus/blob/03efa77cfd0aeb274c686ba4143ee3cd129ca228/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/spring/MybatisSqlSessionFactoryBean.java#L609)

https://github.com/baomidou/mybatis-plus/blob/03efa77cfd0aeb274c686ba4143ee3cd129ca228/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/spring/MybatisSqlSessionFactoryBean.java#L609

![image](https://user-images.githubusercontent.com/26990889/147826423-1a665570-391e-4b88-8818-174e6a2fdf05.png)

**Comment by VampireAchao** [comment]
已提交[PR](https://gitee.com/baomidou/mybatis-plus/pulls/203)
