### ISSUE TITLE
orderByDesc函数里面能使用sql的cast函数么？

### ISSUE THREAD

**Issue by yipanbo** [baomidou/mybatis-plus#4215]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

想请教下orderByDesc函数里面能使用sql的cast函数么？
数据库中的code字段时字符串类型的，但是里面的数据其实是数字类型，我现在查询的时候，想再orderByDesc函数里面对code这一列加一个cast函数，把这一列从字符串类型转成整数类型，请问mybatis_plus支持么？

**Comment by uncarbon97** [comment]
试试康?

this.list(
                new QueryWrapper<实体类>()
                        .select(" CAST( field AS SIGNED ) AS castedValue ")
                        .groupBy(" castedValue ")
                        .lambda()
                        .其他条件
        )

**Comment by yipanbo** [comment]
> 试试康?
> 
> this.list( new QueryWrapper<实体类>() .select(" CAST( field AS SIGNED ) AS castedValue ") .groupBy(" castedValue ") .lambda() .其他条件 )

首先感谢回复！
这个写法不能满足需求。
期望的是：select ... from ... order by cast(field as signed) desc；
但是这个写法最终形成的sql是：select cast(field as signed) from ... order by field desc;

**Comment by uncarbon97** [comment]
那就是
this.list(
new QueryWrapper<实体类>()
.groupBy(" CAST( field AS SIGNED ) ")
.lambda()
.其他条件
)

我只是按自己习惯，GROUP BY的列也会返回
mp支持你在代码里硬编码SQL

**Comment by qmdx** [comment]
不支持该函数，只能如上
