### ISSUE TITLE
添加对impala的支持

### ISSUE THREAD

**Issue by qinjun5230** [baomidou/mybatis-plus#4216]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
目前版本不支持对impala的查询

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/0e3c3fbd9fd82d8de768e641849638c97753ad3d
