### ISSUE TITLE
V3.5.0内连接多租户忽略表明无效

### ISSUE THREAD

**Issue by 112921482** [baomidou/mybatis-plus#4218]
V3.5.0
版本更换引起，V3.4.3.4正常
使用多租户插件，已经忽略INNER JOIN中的表，但是组装的sql中还是添加了tenant_id = ?的查询条件

**Comment by huayanYu** [comment]
需要提供更详细的信息

**Comment by 112921482** [comment]
原sql：select * from a inner join b on b.b_id = a.id
使用租户插件，忽略表b
生成的sql：select * from a inner join b on b.b_id = a.id and b.tenant_id = ***

**Comment by qmdx** [comment]
升级 3.5.1
