### ISSUE TITLE
可以生成36位长度的UUID吗

### ISSUE THREAD

**Issue by KevinCGH** [baomidou/mybatis-plus#422]
如题，目前配置`id-type: uuid`，自动生成的是32位的uuid
比如
```
fee8a9e8aba4443a9940c3aae9051b2f
```
有配置或者扩展可以生成36位带`-`的UUID吗？
```
ff1d1b27-15aa-48c5-be1c-31251ede32a4
```

**Comment by miemieYaho** [comment]
36位的对比32位没有任何意义,还会增加数据库索引的负担

**Comment by zxlaole** [comment]
我认为不是没有意义：
1.在肉眼对比的时候分段有用；
2.有些客户以前已经习惯了，有这个要求；
能否考虑配置，我已经查过源码了，是强制的。

**Comment by miemieYaho** [comment]
数据库id不是给人肉眼看的,喜欢看着方便就用数据库自增
