### ISSUE TITLE
mybatis-plus-generator 3.5.1 PostgreSqlQuery查询主键BUG

### ISSUE THREAD

**Issue by renlm** [baomidou/mybatis-plus#4220]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator 3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
SQL语句关联错误

### 重现步骤(如果有就写完整)
PostgreSqlQuery类，查询字段列表信息时，获取主键未在pg_constraint关联条件中指定属于那张表，导致数据错误，一个表查出多个主键
![image](https://user-images.githubusercontent.com/38641421/148002080-1347f7f8-29d8-4ecb-82ec-552c6f8b2fba.png)

当前版本如下图
![image](https://user-images.githubusercontent.com/38641421/148002019-40888653-0982-412e-ab9b-4bae106454f5.png)

修正后如下图
![image](https://user-images.githubusercontent.com/38641421/148001931-49d15d4d-433f-4bbe-9093-f76af2d55330.png)

### 报错信息

PostgreSQL数据库生成实体中出现多个主键字段

**Comment by renlm** [comment]
BUG提错地方了，这是mybatis-plus-generator 3.5.1 的BUG，问题怎么没有删除按钮，忽略此问题

**Comment by mabyoung** [comment]
可以直接提交pr

**Comment by qmdx** [comment]
使用最新  `3.5.3`  版本 ，采用默认 JDBC 读取方式不要使用 DBQuery
