### ISSUE TITLE
字段名为"advance" 引起 net.sf.jsqlparser.parser.ParseException

### ISSUE THREAD

**Issue by chuangyi110** [baomidou/mybatis-plus#4226]
### 当前使用版本(必填,否则不予处理)
3.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
只要查询字段包含 ggbi.advance
就会报
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 5, column 13.
这个5行13列是指 ggbi.advance 这个字段中间的‘.’

### 重现步骤(如果有就写完整)

只要查询字段包含 ggbi.advance
就会报
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 5, column 13.
这个5行13列是指 ggbi.advance 这个字段中间的‘.’

### 报错信息
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@34e5b341] was not registered for synchronization because synchronization is not active optimize this sql to a count sql has exception, sql:"select
        ggbi.goods_id as goodsId,
        ggbi.on_sale as onSale,
        ggbi.activity as activity,
        ggbi.advance,
        ggbi.gst,
        ggbi.default_goods as defaultGoods,
        ......
", exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."
    at line 5, column 13.

**Comment by miemieYaho** [comment]
你应该给 jsqlparser 提

**Comment by chuangyi110** [comment]
> 你应该给 jsqlparser 提

关键字？

**Comment by qmdx** [comment]
提问题到 https://github.com/JSQLParser/JSqlParser
