### ISSUE TITLE
mysql的datetime怎么按格式映射到java.util.date

### ISSUE THREAD

**Issue by JsonBeyond** [baomidou/mybatis-plus#423]
mysql的datetime怎么按格式映射到java.util.date
场景是使用selectpage时，records中的date字段对应数据库中的datetime，结果是取到的秒

**Comment by JsonBeyond** [comment]
补充：mp版本：2.1.9

**Comment by qmdx** [comment]
数据库设置 date 类型，这是 mybatis 的范畴
