### ISSUE TITLE
model属性类型自定义映射

### ISSUE THREAD

**Issue by AnLiBoBo** [baomidou/mybatis-plus#4232]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`service.list()`
抛出异常
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of 'com.mp.app.model.setting.AbstractSettingVO'`

原因就是在TableFieldInfo里的propertyType根据get方法返回值获取的属性类型
所以mp能不能在TableField注解里提供强制设置javaType的属性

### 重现步骤(如果有就写完整)
实体类
```java
public class TestModel extends Convert {
    private String  code;
   
    @TableField(typeHandler = JacksonTypeHandler.class)
    private Map<String, Object> setting;

    public AbstractSettingVO getSetting() {
        return new SettingVO();
    }

    public void setSetting(AbstractSettingVO setting) {
        this.setting = setting.convert(Map.class);
    }
}
```

**Comment by VampireAchao** [comment]
3.4.0 @2020-07-23新增了
`com.baomidou.mybatisplus.annotation.TableField#javaType`

https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/TableField.java#L170

**Comment by qmdx** [comment]
up
