### ISSUE TITLE
微服务场景将实体类抽成公共的

### ISSUE THREAD

**Issue by AccountGc** [baomidou/mybatis-plus#4233]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter-3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

微服务场景将实体类抽成公共的，供其他服务引用：
`<dependency>
	<groupId>com.test</groupId>
	<artifactId>api-system</artifactId>
</dependency>`

公共api不引入mybatis-plus，公共实体中实体类属性需要@TableName等注解，请问是否有解决办法？

**Comment by miemieYaho** [comment]
最少依赖 `mybatis-plus-annotation`

**Comment by AccountGc** [comment]
@miemieYaho 多谢！
