### ISSUE TITLE
忽略租户注解导致逻辑删除失效

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4237]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
需要忽略租户查询

@InterceptorIgnore(tenantLine = "true")
Page<TableInfo> selectPageIgnoreTenant(Page<?> page);

### 重现步骤(如果有就写完整)
其他的接口都没问题,都能过滤删除的数据
加上忽略租户的注解就会导致逻辑删除失效,感觉逻辑删除和忽略租户注解没关系啊

**Comment by miemieYaho** [comment]
逻辑删除只存在于内置的method.其他你自己写的sql要自己加过滤
