### ISSUE TITLE
批量插入insertBatch报错，bug已找到，请修复。

### ISSUE THREAD

**Issue by ybp825** [baomidou/mybatis-plus#424]
调用service.insertBatch,抛出异常“6a3c10759a034fffb738f10c4bc5e3bc-com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Cannot execute insertBatch Method. Cause”
通过调试发现问题，com.baomidou.mybatisplus.extension.service.impl.currentModelClass(),获取index=1的泛型类型是mapperClass，应该改成index=2才是modelClass，请尽快修改这个问题。

**Comment by qmdx** [comment]
什么版本 mp  ???

**Comment by ybp825** [comment]
3.0的都有

**Comment by qmdx** [comment]
测试无该问题，你给出你的实体类，看看你泛型位置

**Comment by ybp825** [comment]
`public abstract class AbstractService<ID extends Serializable, DAO extends BaseMapper<ENTITY>, ENTITY extends AbstractEntity<ID, ENTITY>>
        extends ServiceImpl<DAO, ENTITY> `

**Comment by ybp825** [comment]
感谢提醒，问题已找到，是我们自己封装的AbstractService类的泛型顺序写错了，如下
`public abstract class AbstractService<ID extends Serializable, DAO extends BaseMapper<ENTITY>, ENTITY extends AbstractEntity<ID, ENTITY>>
        extends ServiceImpl<DAO, ENTITY> `
应该为：
`public abstract class AbstractService<ID extends Serializable, ENTITY extends AbstractEntity<ID, ENTITY>, DAO extends BaseMapper<ENTITY>,>
        extends ServiceImpl<DAO, ENTITY>`
