### ISSUE TITLE
LambdaUpdateWrapper 更新Date类型入库时间会多一秒

### ISSUE THREAD

**Issue by super-lzb** [baomidou/mybatis-plus#4240]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

尝试过3.5.0但问题依旧存在

### 重现步骤(如果有就写完整)

问题：使用LambdaUpdateWrapper更新Date类型字段时，入库时间比程序打印时间多1秒
过程：
1、声明一个Date对象并格式化为yyyy-MM-dd HH:mm:ss 且打印，例如：2022-01-12 15:47:08
2、将此对象通过 LambdaUpdateWrapper 赋值给Date类型的字段并更新入库，发现时间是 2022-01-12 15:47:09

### 报错信息

无报错信息

**Comment by miemieYaho** [comment]
mp不会去动你的入参

**Comment by lancemoll** [comment]
应该是数据库使用的date类型,没有设置小数位数,会进行四舍五入
