### ISSUE TITLE
select 返回 一整行 null 

### ISSUE THREAD

**Issue by codegrady** [baomidou/mybatis-plus#4243]
### 当前使用版本(必填,否则不予处理)

3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查寻返回一行  null 

### 重现步骤(如果有就写完整)

==>  Preparing: select z.* from promotion_ref ref left join promotion_zone z on ref.promotion_zone_id = z.id where ref.status = 1 and ref.promotion_id = ? order by z.id
==> Parameters: 2(Integer)
<==    Columns: id, zone_id, company_id, company_building_id, title, name, kind, type, brand_id, area, site_num, idle_site_num, price, unit_type, images, video, video_cover, source_id, label, floor, renovation_status, registrable, divisible, has_window, direction, view_time, starting_time, devices, least_months, free_months, deposit_months, pay_months, description, biz_status, status, create_time, create_user, update_time, update_user
<==        Row: null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, <<BLOB>>, null, null, null, null, null, null
<==        Row: 22, 2126, 1, 4, 北京海场-办公室25人间, 8层南区801/802封闭工位, 2, 1, 1, 240.74, 25, 25, 2000.00, 1, 340,341,342,343, null, null, 3207, 近地铁,, 8, 1, 1, 1, 1, EW, null, null, 20, 1, 0, 1, 3, <<BLOB>>, 1, 1, 2021-12-15 18:17:51, 464, 2021-12-15 18:17:51, 464
<==      Total: 2

**Comment by miemieYaho** [comment]
给出git形式的demo
