### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by YueGuangShiXGY** [baomidou/mybatis-plus#4246]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

分页使用不同的出参和入参,官方文档要求必须使用同样的出参入参,这也太蠢了吧

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/49852614/149742649-cd15fca6-e15b-4b5e-9009-18a7c1f986bd.png)

### 报错信息

无

**Comment by cocobolor** [comment]
兄弟,他只是告诉你返回的page和传入的page是同一个,没要你一定要用之前的page接,用新的变量也可以接,只不过他俩其实是同一个对象
