### ISSUE TITLE
 自定义SQL,map-underscore-to-camel-case设置不生效

### ISSUE THREAD

**Issue by hhxyjsj** [baomidou/mybatis-plus#425]
**一、mybatis-plus配置：**
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.baomidou.springboot.entity
  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: IGNORED
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      #db-type: h2
    #刷新mapper 调试神器
    refresh: true
    # 原生配置
  configuration:
> map-underscore-to-camel-case: true
    cache-enabled: false

**二、自定义查询SQLXML**

> < select id="selectList01ByWrapper" resultType="java.util.Map">
>         SELECT * FROM user
>         < where>
>             ${ew.sqlSegment}
>         </ where>
>     </ select>

**三、自定义查询dao**
List<Map<String, Object>> selectList01ByWrapper(@Param("ew") Wrapper wrapper);

**问题：**
1、调用

> com.baomidou.mybatisplus.extension.service.getMap(Wrapper<T> queryWrapper)

时，当map-underscore-to-camel-case: true时，返回的结果集没有将属性中的下划线转换为驼峰格式，反而是在underscore-to-camel-case: false时，返回的结果集将属性中的下划线转换成驼峰格式了；所在这块是不是写反了？

2、自己在dao扩展的方法（自定义的sql），underscore-to-camel-case: true/false时，返回的结果集的属性中的下划线都没有进行转换？

**Comment by hhxyjsj** [comment]
![a](https://user-images.githubusercontent.com/31506377/43759712-a95c59b0-9a52-11e8-8b74-f07b06d5c266.png)

**Comment by hhxyjsj** [comment]
![Uploading b.png…]()

**Comment by xkenmon** [comment]
这个仓库不维护了吗？
文档不更新，issue也不管？

**Comment by qmdx** [comment]
@xkenmon  稍安勿燥，这么多问题 Bug 解决我们也需要工作，只能抽时间处理请耐心等待， 3X 文档还在编辑中会尽快释出，着急问题可以加群号:648281531 和别人交流， issue 肯定不会太及时

**Comment by xkenmon** [comment]
抱歉，有点急了。
开源事业不容易

**Comment by miemieYaho** [comment]
1.mybatis的属性map-underscore-to-camel-case对map无效
2.mp的属性underscore-to-camel-case只是自带的方法生成的select是否字段名进行as
3.如果你非要返回的map的key为驼峰,去参照"官方文档->常见问题"里有说明
