### ISSUE TITLE
添加 spring-native 支持

### ISSUE THREAD

**Issue by toohandsome** [baomidou/mybatis-plus#4253]
https://github.com/spring-projects-experimental/spring-native/issues/1402#issuecomment-1012963685

**Comment by koudaiDemon** [comment]
@miemieYaho 你好，我看到这个issue被关闭了，请问一下，mybatis-plus是如何实现这个功能的呢

**Comment by qmdx** [comment]
> @miemieYaho 你好，我看到这个issue被关闭了，请问一下，mybatis-plus是如何实现这个功能的呢

暂时没有这个计划，可以先打开

**Comment by nieqiurong** [comment]
#5527  统一至此处讨论.
