### ISSUE TITLE
mybati-plus同时使用TenantLineInnerInterceptor和PaginationInnerInterceptor， 分页插件未生效

### ISSUE THREAD

**Issue by kelpliu** [baomidou/mybatis-plus#4257]
### 当前使用版本(必填,否则不予处理)
mybatis-plus:3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus同时添加TenantLineInnerInterceptor和PaginationInnerInterceptor

### 重现步骤(如果有就写完整)
1.创建mybatisplus配置
![image](https://user-images.githubusercontent.com/17726590/150463298-2ac6f735-ba0b-40a6-ac6e-f1a93d6ea0bd.png)

2.分页方法
IPage<VehiclePO> selectVehiclesPage(Page<?> page, @Param("params") HashMap<String, Object> selectCondition);
3.查询报错
![image](https://user-images.githubusercontent.com/17726590/150463260-3db83589-62db-4b92-b8d3-70cd24d8079f.png)

### 报错信息

exception is java.lang.ClassCastException: com.hxzj.iccs.svrdm.dao.po.VehiclePO cannot be cast to com.baomidou.mybatisplus.core.metadata.IPage

**Comment by miemieYaho** [comment]
看文档
