### ISSUE TITLE
update方法的建议

### ISSUE THREAD

**Issue by hhxyjsj** [baomidou/mybatis-plus#426]
> 最新版只能通过统一的“field-strategy”或“@TableField(strategy = FieldStrategy.NOT_EMPTY)”来设置更新和插入时当属性为Null时，是否更新或插入该字段，且该策略只能固定其中一种，这么做导致开发过程中不够灵活了。

> `这么做后带来的问题是，****如果我要根据ID更新某几个字段的时候，就需要先查出历史数据对象**，然后将要更新的字段set到查出的对象中，再调更新方法**，没有之前版本的**updateAllColumnById**方便。

> 因此，**建议保留原来的updateAllColumnById方法，这样的话如果不更新属性值为Null的字段的话，就调update方法，如果要更新所有字段，不判断是否为Null则调用updateAllColumnById方法**，提供2种更新和插入方法就行，无需设置相关策略

**Comment by qmdx** [comment]
什么版本 mp  ??  如果是   3.x 提供了 updateWrapper 有解决办法 uw.set
