### ISSUE TITLE
数据库主键是自增时  po加入数据库已经存在的id时 会报主键重复

### ISSUE THREAD

**Issue by a523546273** [baomidou/mybatis-plus#4260]
### 当前使用版本(必填,否则不予处理)
3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库主键是自增时  po的主键id也加了   @TableId(value = "id", type = IdType.AUTO)注解
po加入数据库已经存在的id时会报主键重复  以前的版本不会  升级到最新版本出现了
请问这个优化 还是bug

### 重现步骤(如果有就写完整)
    TStoreProductInfoPo po = BeanUtil.copy(dto, TStoreProductInfoPo.class);
        po.setDeleted(CommonConstant.DELETED.DELETED_0.value());
        po.setCreateBy(ThreadLocalUtils.getUserId());
        po.setCreateTime(new Date());
//前端有的时候加入了id  加入数据库有id为1的数据会报错
po.setId(1);
        save(po);

### 报错信息
主键冲突

**Comment by qmdx** [comment]
新增版支持 自增设置自定义 ID  旧版本不支持所有报错

**Comment by HankGuo** [comment]
https://github.com/baomidou/mybatis-plus/pull/3592/files
3.4.1版本的时候增加了这个change，暂时看来只能显示的将id置为null
