### ISSUE TITLE
is:issue is:open 如何设置才能在调用selectMaps查询时返回值为null的字段呢？

### ISSUE THREAD

**Issue by lvgitt** [baomidou/mybatis-plus#4264]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
目前是只返回了有值的字段，无值的字段没返回 

### 重现步骤(如果有就写完整)
表中既有有值的字段，又有无值的字段，通过selectMaps方法查询的时候，只返回了有值的字段，无值的字段没返回，需要怎么设置才能返回呢？
因为数据库中的字段名为下划线方式命名，而java中的命名为驼峰命名，需求是要取下划线命名的字段。

### 报错信息
无

**Comment by miemieYaho** [comment]
找mybatis的配置里有
