### ISSUE TITLE
updateBatchById  执行后，数据库没有更新，但是返回结果仍然是true，不能用于乐观锁

### ISSUE THREAD

**Issue by 164250072** [baomidou/mybatis-plus#4265]
### 当前使用版本(必填,否则不予处理)

3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

updateBatchById  执行后，数据库没有更新，但是updateBatchById 的返回结果仍然是true，不能用于乐观锁。
期望updateBatchById能返回成功条数，由开发人员判断执行结果是否执行回滚等

**Comment by miemieYaho** [comment]
batchExecutor不支持返回影响行数

**Comment by bravelionet** [comment]
官方怎么解决这问题呢, 批量更新怎么返回影响行数
