### ISSUE TITLE
关于查询结果错误，字段被重复设值

### ISSUE THREAD

**Issue by CSpy163** [baomidou/mybatis-plus#4267]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我的 DO 有两层，父类包含通用属性，子类包含业务属性。
子类注解如下：
@Data
@AllArgsConstructor
@EqualsAndHashCode(callSuper=true)

### 重现步骤(如果有就写完整)
创建两层 DO，这应该很常见。1. 子类DO使用上述注解，简单查询数据库；2. 子类加入 @NoArgsConstructor 注解，再查询数据库；对比结果集会发现第二次查询正确，而第一次查询结果会出现某些字段被错误设置的情况。

### 报错信息
无报错信息

**Comment by CSpy163** [comment]
Data注解显示错误，就是 lombok 的那个 @Data

**Comment by miemieYaho** [comment]
必加  @NoArgsConstructor
