### ISSUE TITLE
新增后获取getId()为null

### ISSUE THREAD

**Issue by ddyddy** [baomidou/mybatis-plus#4271]
### 当前使用版本(必填,否则不予处理)
mp3.5.0
springboot2.4.2
mysql5.7

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用service的save和mapper的insert，对象id都是null

### 报错信息
无

**Comment by miemieYaho** [comment]
请给出复现demo

**Comment by qmdx** [comment]
看下 文档 id 策略 是否解决你的问题，目前的描述无法定位
