### ISSUE TITLE
mybatisPlus3.4.2能否修复ServiceImpl重新发一版

### ISSUE THREAD

**Issue by yanhuilin** [baomidou/mybatis-plus#4274]
我们的spring版本是2.3.2，对应mybatisPlus3.4.2，但是该版本ServiceImpl中，mapper的Class泛型指向了entity，并且搜索泛型是通过直接取父类的泛型，导致ServiceImpl的实现类的子类使用Service方法会报mapper的cache对象找不到，如果升级mybatisPlus，3.4.3以上要求spring2.4+，会因代码不兼容启动不了，基本是需要重构代码代价过高，想咨询一下能否发布一版专门修复一下ServiceImpl问题（备注3.3.1没有缓存mapper所以没有问题）

**Comment by Hccake** [comment]
自己复制源码修改，保证全类名一致，根据类加载优先级会达到覆盖替换的功能

**Comment by ahgaoyong** [comment]
升级spring boot很简单的 2.4+ ， 有一个坑需要修改下就行了
2.3.*中的代码：
`config.addAllowedOrigin("*");`
改为：
`config.addAllowedOriginPattern("*");`
就可以了，很简单的，我都升级到2.6了，紧跟步伐，否则一些依赖包的安全更新还需要自己手动去升级

**Comment by qmdx** [comment]
请升级到高版本，低版本不做维护
