### ISSUE TITLE
@Select 注解自定义SQL查询，如果包含子查询注解@Result时，子查询不能动态修改表名

### ISSUE THREAD

**Issue by summerc1** [baomidou/mybatis-plus#4275]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
加载动态表名插件DynamicTableNameInnerInterceptor，@Select 注解自定义SQL查询时，会执行插件中的修改表名，如果该查询包含子查询注解@Result时，子查询的SQL不能动态修改表名。

**Comment by miemieYaho** [comment]
子查询不会走插件,这是mybatis的问题
