### ISSUE TITLE
线程池中延时任务执行时，update 操作不执行？？

### ISSUE THREAD

**Issue by tokenwind** [baomidou/mybatis-plus#4278]
### 当前使用版本(必填,否则不予处理)

<groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus</artifactId>
      <version>3.3.0</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
MyserviceImpl 下
某个method内：
              ScheduledExecutorService executorService = new ScheduledThreadPoolExecutor(1,new ThreadFactory(){
                                  public Thread newThread(Runnable r) {
                                      Thread t = new Thread(r);
                                      t.setName("com.xx.xx.service.impl.xxTask");
                                      t.setDaemon(true);
                                      return t;
                                  }
                              });
                executorService.schedule(() -> {
                    try {
                       this.update(myEntity);    //-----------1
                        myMapper.updateEntity(stuPod1.getData().get(0).getPodip(),podRecord.getId()); //----------2
                    } catch (Exception exception) {
                        exception.getStackTrace();
                    }
                }, 30, TimeUnit.SECONDS);
                executorService.shutdown();

### 重现步骤(如果有就写完整)
如果执行1 的update 在延时任务中sqlsession 会直接close 不执行update 操作
如果执行2 则可以更新

**Comment by jojocodeX** [comment]
有没有考虑事务问题
