### ISSUE TITLE
QueryWrapper查询时如果条件value为空或空白不应该拼接sql

### ISSUE THREAD

**Issue by jackcooper2015** [baomidou/mybatis-plus#428]
### 当前使用版本(必须填写清楚，否则不予处理)
RC-1

### 该问题是怎么引起的？
例如：
new QueryWrapper<>().eq("name",name)
此时如果name为空，sql中依然包含name条件，应该根据用户配置的field-strategy来处理，修改逻辑在
AbstractWrapper#eq方法中通过判断field-strategy来处理是否addConditon.

**Comment by miemieYaho** [comment]
这个自己进行判断,使用 eq(boolean,column,value) 方法,第一个值为true才会进行拼接,不是每一个人的要求都是value不为空或者null才拼接的,field-strategy配置和这里无关
