### ISSUE TITLE
FORCE INDEX

### ISSUE THREAD

**Issue by shenhuan2021** [baomidou/mybatis-plus#4280]
什么时候支持FORCE INDEX？ 这个功能还是很常用的，不考虑下支持吗？

**Comment by huayanYu** [comment]
暂不考虑，可以自己参考文档扩展

**Comment by shenhuan2021** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by God-hrh** [comment]
请问有解决方案了嘛？能不能使用QueryWrapper强制走指定索引？

**Comment by 15775773164** [comment]
请问有解决方案吗

**Comment by qmdx** [comment]
开启 https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/inner/IllegalSQLInnerInterceptor.java 这个插件会做一些检查工作，但是对性能会影响，建议只用在开发环境
