### ISSUE TITLE
clickhouse使用了特殊函数后导致分页组件中的order by 不生效，还报错

### ISSUE THREAD

**Issue by dislazy** [baomidou/mybatis-plus#4281]
### 当前使用版本(必填,否则不予处理)
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.4.3.4</version>
		</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

1、设置排序参数page.setOrders(Lists.newArrayList(new OrderItem("gmvTotal", false)));

        // 分页和数据
 2、IPage<EcSpuDTO> queryaaa(PageDTO<aaa> page);

3、对应SQL如下：
```
select
        sum (gmv) as gmvTotal,
aid
        from gmv
        where
multiSearchAnyCaseInsensitiveUTF8(gmv_name,['面包','牛奶'])
group by aid
```
使用了clickhouse的`multiSearchAnyCaseInsensitiveUTF8`函数
### 报错信息
```
        group by aid", exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 51, column 57.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"
```

**Comment by miemieYaho** [comment]
jsqlparser 不支持它

**Comment by dislazy** [comment]
> 

是需要我手动写order by 对吧
