### ISSUE TITLE
实体类生成问题

### ISSUE THREAD

**Issue by shenxiuqiang** [baomidou/mybatis-plus#429]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0-gamma

### 该问题是怎么引起的？

id 不设置自增生成的实体类少了TableId.class/IdType.class引入

### 重现步骤

数据库id字段为主键，Extra为None，生成实体类

### 报错信息

实体类没有引入TableId.class/IdType.class

**Comment by qmdx** [comment]
请使用 `3.0-RC2` 以上版本，直接修改版本号即可https://search.maven.org/search?q=g:com.baomidou%20AND%20a:mybatis-plus&core=gav
