### ISSUE TITLE
java: 无法访问com.baomidou.mybatisplus.extension.service.impl.ServiceImpl

### ISSUE THREAD

**Issue by limitAp** [baomidou/mybatis-plus#4296]
### 当前使用版本(必填,否则不予处理)
3.4.3
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

service层类继承 ServiceImpl
controller层 @Autowired注入 xxxService

### 报错信息
java: 无法访问com.baomidou.mybatisplus.extension.service.impl.ServiceImpl
  找不到com.baomidou.mybatisplus.extension.service.impl.ServiceImpl的类文件

**Comment by limitAp** [comment]
已解决，引入多个版本

**Comment by kylin0627** [comment]
我现在用的是3.5.3版本，还是有这个问题，请问怎么解决的？
