### ISSUE TITLE
是否有考虑将IPage等实体类单独出一个实体模块

### ISSUE THREAD

**Issue by ruansheng8** [baomidou/mybatis-plus#4298]
### 当前使用版本(必填,否则不予处理)

v3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

给外部提供的接口模块通常都只包含最纯粹的实体类, 但是如果要使用 IPage , PageDTO 等实体类作为方法返回结果 , 就必须依赖 core 或者 extension 整个模块 , 这两个模块里面又包含了各种其他功能.
是否有考虑像annotation模块一样 , 单独抽离一个类似model的模块 , 只包含纯粹的简单实体

**Comment by qmdx** [comment]
IPage  当然应该无法抽取，你可以考虑自定义自己的 Page 来转换对外提供服务的对象
