### ISSUE TITLE
mybatis-plus-boot-starter    3.5.1 版本，removeById方法，类型强制和主键同一类型了

### ISSUE THREAD

**Issue by qeprwjcgya** [baomidou/mybatis-plus#4302]
mybatis-plus-boot-starter    3.5.1 版本，removeById方法，类型强制和主键同一类型了
当调用removeById方法，当实体主键的类型是Long类型，传值 int 类型的时，执行时会报 argument type mismatch，

**Comment by qeprwjcgya** [comment]
mybatis-plus-boot-starter 3.5.1 版本，removeById方法，类型强制和主键同一类型了 
如果主键是Long类型，传值的类型是int类型，执行 removeById方法 会报 argument type mismatch，

**Comment by a40885948** [comment]
同遇到问题，这个改动已经不兼容前面版本了，好多报错啊。。。

**Comment by ahgaoyong** [comment]
Long类型的主键传递int会有风险的啊

**Comment by VampireAchao** [comment]
同旧版本升上来的，只能每个地方都改一下

**Comment by Jasper-Ju** [comment]
removeByIds 第二个参数传入false就可以解决啦。
