### ISSUE TITLE
3.4.1 版本saveOrUpdateBatch方法会被Interceptor的拦截两次

### ISSUE THREAD

**Issue by ls65535** [baomidou/mybatis-plus#4303]

**Comment by miemieYaho** [comment]
执行了几次mapper的method就拦截几次

**Comment by ls65535** [comment]
当更新的时候
![image](https://user-images.githubusercontent.com/45529962/153536936-67e484ce-b8ab-473c-8ad6-14b5e00b3c06.png)
会执行的
