### ISSUE TITLE
IdType.AUTO时是否可以自动清空传入的ID

### ISSUE THREAD

**Issue by RainF** [baomidou/mybatis-plus#4307]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.0.7.1升级新版本导致

### 重现步骤(如果有就写完整)
insert的时候，实体有带ID,但ID策略使用的是auto,是否可以自动清空该ID,旧版本没有这个问题

### 报错信息
Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '11' for key 'PRIMARY'
; Duplicate entry '11' for key 'PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '11' for key 'PRIMARY'

**Comment by qmdx** [comment]
版本 3.4.3.1 开始支持，自增可以指定ID  使用指定ID 不指定则自增，更多查看升级日志 https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md  解决办法  set  id 为 null
