### ISSUE TITLE
实体类上面使用lombok的@Builder注解后，执行mapper.selectList()会出现异常

### ISSUE THREAD

**Issue by hitcp** [baomidou/mybatis-plus#4310]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类上面使用lombok的@Builder注解后，执行mapper.selectList()会出现异常：Error attempting to get column 'xxx' from result set.  Cause: java.sql.SQLException: Invalid value for getInt()

### 重现步骤(如果有就写完整)
1.实体类上面加lombok的@Builder注解
2.执行mapper.selectList()

### 报错信息
Error attempting to get column 'xxx' from result set.  Cause: java.sql.SQLException: Invalid value for getInt()

**Comment by miemieYaho** [comment]
没有无参构造
