### ISSUE TITLE
请问 mybatis plus 是否能够支持 父子表继承关系的增删改查操作

### ISSUE THREAD

**Issue by tysite** [baomidou/mybatis-plus#4313]
mybatis-plus  是否有支持 两张表为继承关系， 父表有唯一主键, 子表无主键或与附表主键相同的 增删改查操作功能

CREATE TABLE father (
   id  bigint                NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  name varchar(50)   NOT NULL COMMENT '名称'
  PRIMARY KEY (`id  `)
)  COMMENT = '父表'；

CREATE TABLE son1 (
     id  bigint                NOT NULL COMMENT '附表主键',
    age int                   DEFAULT NULL COMMENT '年龄'
) COMMENT = '子表1';

如果有，请指教下如何使用

**Comment by qmdx** [comment]
级联操作？暂不支持
