### ISSUE TITLE
DefaultIdentifierGenerator.<init>(Ljava/net/InetAddress;)

### ISSUE THREAD

**Issue by semonshi** [baomidou/mybatis-plus#4319]
3.4.3 

项目中引入 springcloud
 <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-bootstrap</artifactId>
    </dependency>

<img width="755" alt="image" src="https://user-images.githubusercontent.com/39510850/154881211-0a79cba4-b543-424c-becc-c05a943448e4.png">

java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.incrementer.DefaultIdentifierGenerator.<init>(Ljava/net/InetAddress;)V
	at com.baomidou.mybatisplus.autoconfigure.IdentifierGeneratorAutoConfiguration$InetUtilsAutoConfig.identifierGenerator(IdentifierGeneratorAutoConfiguration.java:57) ~[mybatis-plus-boot-starter-3.4.3.jar:3.4.3]

DefaultIdentifierGenerator 类没有图示的初始化方法，报错

**Comment by conifercone** [comment]
inetUtils.findFirstNonLoopbackAddress的返回值是java.net.InetAddress吗

**Comment by conifercone** [comment]
![image](https://user-images.githubusercontent.com/30498960/154907255-c986c33b-8979-44e9-a209-6c179a52c964.png)

**Comment by XR-LM** [comment]
![image](https://user-images.githubusercontent.com/40235159/162562704-065c385a-e664-4b44-b583-bbaf26598655.png)
是java.net.InetAddress类型

**Comment by miemieYaho** [comment]
升级
