### ISSUE TITLE
是否可以将TableName注解扩展一下，可以支持更多的特性

### ISSUE THREAD

**Issue by fanlei1988** [baomidou/mybatis-plus#432]
### 当前使用版本(必须填写清楚，否则不予处理)

目前版本:mybatis-plus 3.0-RC2

### 问题由来？

如果数据库里，数据表的设计既有驼峰命名的（UserName），也有带下划线的（user_name）,那么使用默认的设置就会出问题（虽然这些是因为规范不统一造成的），在使用@TableId也能解决，但是需要每个字段都去设置太麻烦了

### 想要达到的目的

能否动态的去针对不同的表做不同的设置，达到如上效果

### 想法

扩展一下@TableName注解（或者增加一个@Table注解或者其他一个注解），使其支持动态设置整张表的通用属性（比如说columnUnderline设置为flase ，默认是true，其他的可以抽离出来的亦可）

### 涉及需要改动的地方

TableInfoHelper 类第160行

`
        /* 可以在此处获取相关注解,并将相关的属性赋予globalConfig*/

       xxxx  x= clazz.getAnnotation(xxxx.class);

       globalConfig.getDbConfig().setColumnUnderline(......);//举例

        /* 初始化表名相关 */

        initTableName(clazz, globalConfig, tableInfo);
`

**Comment by huayanYu** [comment]
不会支持，请保持规范一致
