### ISSUE TITLE
多表查询自定义SQL出现--Invalid bound statement (not found)

### ISSUE THREAD

**Issue by tangmin996** [baomidou/mybatis-plus#4323]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter-3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

mybatis-plus自带方法正常，自定义多表LEFT JOIN查询出现问题

### 重现步骤(如果有就写完整)

1.引入依赖
![image](https://user-images.githubusercontent.com/97079052/155201235-63da650d-2b33-4be8-87a3-75d9f2945387.png)

2.数据源代理配置--DataSourceProxyConfig
![image](https://user-images.githubusercontent.com/97079052/155201671-6b4504ac-e6fe-4409-a8b8-690cb5a396e9.png)

3.spring配置--application.yml
![image](https://user-images.githubusercontent.com/97079052/155201890-ae700356-b603-41e5-ac18-701db357ecfe.png)

4.Application配置
![image](https://user-images.githubusercontent.com/97079052/155202001-ab678fcc-e2f8-4102-bb68-b14fbc1bb945.png)

5.业务代码（截取）--SkuInfoServiceImpl
![image](https://user-images.githubusercontent.com/97079052/155202318-9f939dc1-4825-4ffc-94a3-ce786a281023.png)

6.业务代码（截取）--SkuSaleAttrValueServiceImpl
![image](https://user-images.githubusercontent.com/97079052/155202534-61d97371-7a9d-4690-ba50-980bc26d5b64.png)

7.业务代码（截取）--SkuSaleAttrValueDao
![image](https://user-images.githubusercontent.com/97079052/155202677-7e6dfdcd-caf6-4177-9aaf-aa2ad1f16260.png)

8.业务代码（截取）--SkuSaleAttrValueDao.xml
![image](https://user-images.githubusercontent.com/97079052/155202806-d12cd497-98e1-4b34-8330-e9af248c2b45.png)

9.POJO--SkuItemSaleAttrVo,AttrValueWithSkuIdVo
![image](https://user-images.githubusercontent.com/97079052/155203006-11b1bfa0-6732-49ab-a48b-4d9807e42089.png)
![image](https://user-images.githubusercontent.com/97079052/155203069-a28a4f61-fef9-49e7-89b6-3f546be08624.png)

10.问题说明
数据库基本查询都正常，就是无法联表查询，项目中用了引入了seata（分布式事务），不晓得是不是seata原因？？
![image](https://user-images.githubusercontent.com/97079052/155203534-347725e0-df18-4bad-a31f-689c93167cc7.png)

### 报错信息
![image](https://user-images.githubusercontent.com/97079052/155203230-7d58cb04-dee1-4cac-87a2-7d04fb097916.png)

**Comment by miemieYaho** [comment]
你自己构造bean,那yml的配置就失效了
