### ISSUE TITLE
QueryWrapper select func dynamic args

### ISSUE THREAD

**Issue by jhx-zc** [baomidou/mybatis-plus#4326]
### 当前使用版本(必填,否则不予处理)
maven: 3.5.9 latest

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
需要增加的 select列为多列，只能以可变参数来设置，为何不增加一个array呢？
![image](https://user-images.githubusercontent.com/52167297/155449319-640f5369-95ab-4476-b0d3-2a16c4afcbc5.png)

我的select的cols是由用户动态上传的，我就不太方便使用了。多次调用select也只能存放最后一个col name。而且没有找到其他适当的方案来解决该问题

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by jhx-zc** [comment]
对不起，我找到了问题。我用的是以前的Configure方式：

**Comment by huayanYu** [comment]
可变参数是可以接收array的啊

**Comment by jhx-zc** [comment]
好的 谢谢，之前我没有给数组类型强转String。所以报错。看他的报错我以为是类型问题。
![image](https://user-images.githubusercontent.com/52167297/155907786-8af4b63e-305f-4706-a0eb-957bf19beb56.png)
