### ISSUE TITLE
Mybatis-plus无SQL多表联合查询方案

### ISSUE THREAD

**Issue by seabean1999** [baomidou/mybatis-plus#4332]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter - 3.5.1

### 做法(确定最新版也有问题再提!!!)
利用mybatis-plus现有的单表通用CRUD做无SQL多表联合查询——若干次单表查询，然后在Service层进行数据的整合，效果等同于多表联合查询，在高并发且数据量大的场景下还有不少优点，这种做法怎么样？  我看网上有人在实际项目中这样做了，参考链接：[MySQL多表关联查询效率高点还是多次单表查询效率高，为什么？ - 小知的回答 - 知乎](https://www.zhihu.com/question/68258877/answer/2071090987)

**Comment by seabean1999** [comment]
具体做法参考链接：[Mybatis Plus多表连接查询的问题及解决方案](http://www.codebaoku.com/it-java/it-java-235567.html)

**Comment by VampireAchao** [comment]
欢迎PR
