### ISSUE TITLE
不懂就问，有了Service CRUD 接口为什么还要 Mapper CRUD 接口？

### ISSUE THREAD

**Issue by VanLiuZhi** [baomidou/mybatis-plus#4340]
感觉这两个接口，用哪一个都能满足需求，为什么要弄两个呢？纯小白

**Comment by huayanYu** [comment]
Service 掉的Mapper 的， Mapper是必须的，Service可以不用

**Comment by zhengfc** [comment]
改进IService层能自动注入mapper层的自定义接口，并且建议IService改成IDao或者IRepository；IService也不需要引入Entity，专注数据层；
