### ISSUE TITLE
查询数据的时候，是否支持字段自动填充？

### ISSUE THREAD

**Issue by dhshenc** [baomidou/mybatis-plus#4346]
使用版本：3.4.3

问个问题：有没有大佬，查询数据的时候，统一自动给某个字段赋值数据，比如多租的那个功能。
多租的那个功能已经使用，现在想也给另外一个字段也实现这种赋值方式，不知道各位大佬是没有好的方案
或者其他方式实现的都可以。

我自己想过两种方案
      1.  改造多租的那个功能
      2. 自动填充的那个功能
              现在看只支持新增和修改的时候进行字段填充，没有查询的自定义填充

请各位大佬指点指点

**Comment by nancheung** [comment]
简单拦截器就可以实现，当然你也可以仿照多租户插件写一个

**Comment by dhshenc** [comment]
> 

我就是想问问有没有大佬写的有，可以让借鉴下😁

**Comment by miemieYaho** [comment]
简单的直接实体字段给个默认值

**Comment by VampireAchao** [comment]
查的时候直接给某个字段赋值，会导致只读事务不可用。。。如果是需要默认值，还是给数据库字段设置一个默认值即可
