### ISSUE TITLE
不支持特殊字符的模糊查询

### ISSUE THREAD

**Issue by HeiKeJi6** [baomidou/mybatis-plus#4347]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用wrapper,特殊字符* % \ 作为like的条件字段，发现分页查询的结果为空

**Comment by huayanYu** [comment]
查询的sql长什么样？ 你预期是什么样

**Comment by qmdx** [comment]
需要转义吧特殊字符，这和 mp 没关系 数据库出来问题
