### ISSUE TITLE
代码生成时跨平台机制优化

### ISSUE THREAD

**Issue by minliacom** [baomidou/mybatis-plus#435]
### 当前使用版本(必须填写清楚，否则不予处理)
v2.1.5

### 该问题是怎么引起的？
代码生成时跨平台机制优化

### 重现步骤
从头开始使用 AutoGenerator生成代码

### 报错信息
在不同OS平台下路径需要做跨平台优化

**Comment by qmdx** [comment]
输出路径自己解决例如：
`String projectPath = System.getProperty("user.dir");
gc.setOutputDir(projectPath + "/src/main/java");`
