### ISSUE TITLE
关键字作为查询条件bug

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4350]
### 当前使用版本(必填,否则不予处理)
3.4.3.4升到3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mysql使用key做关键字

### 重现步骤(如果有就写完整)
@TableField("`key`")
 private String key;
![Uploading image.png…]()

### 报错信息
关键字错误

**Comment by 274574162** [comment]
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = 'TEACHER_ACCOUNT_REGEX')' at line 3
### The error may exist in com/dy/datacenter/base/mapper/SettingMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,name,`key`,value  FROM t_base_setting     WHERE (key = ?)
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = 'TEACHER_ACCOUNT_REGEX')' at line 3
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = 'TEACHER_ACCOUNT_REGEX')' at line 3

**Comment by 274574162** [comment]
![image](https://user-images.githubusercontent.com/39609367/157019303-19e41679-0fec-4e73-88bd-5869034f7483.png)

**Comment by miemieYaho** [comment]
代码呢

**Comment by 274574162** [comment]
settingMapper.selectOne(new QueryWrapper<SettingEntity>().eq("`key`", SettingConstant.TEACHER_ACCOUNT_REGEX));
必须这样写才行

**Comment by miemieYaho** [comment]
只能那样
