### ISSUE TITLE
日志打印执行sql和参数，不打印查询结果集

### ISSUE THREAD

**Issue by wuxf-01** [baomidou/mybatis-plus#4351]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
由于批量数据处理时每次需要查询大量数据然后遍历,需要查看执行的sql和参数，但是打印结果集太多，干扰排查问题

**Comment by miemieYaho** [comment]
你说的打印不属于mp的问题
