### ISSUE TITLE
最新版 mybatis-plus 3.5.1 多租户插件 TenantLineInnerInterceptor 不进入 ignoreTable()

### ISSUE THREAD

**Issue by thousmile** [baomidou/mybatis-plus#4357]
### 最新版 3.5.1 TenantLineInnerInterceptor  不进入 ignoreTable() 方法
 
* 在 3.4.3.4 版本，会先进入 ignoreTable() 方法。然后再调用 getTenantId()
* 在 3.5.1  版本，直接调用 getTenantId() 。 并没有 进入 ignoreTable() 方法

场景复原  https://github.com/thousmile/mbp-demo

**Comment by Hccake** [comment]
和 #4344 重复

此PR #4353 已处理

**Comment by thousmile** [comment]
此PR https://github.com/baomidou/mybatis-plus/pull/4353 已处理
