### ISSUE TITLE
通过注解的方式使用分页查询插件

### ISSUE THREAD

**Issue by zhy-brian-online** [baomidou/mybatis-plus#4358]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
通过自定义分页查询出现异常org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 182

### 报错信息
org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 182

**Comment by miemieYaho** [comment]
代码呢?

**Comment by jojocodeX** [comment]
是不是查询List用到selectOne导致
