### ISSUE TITLE
分页插件的无论填写什么分页规则都会将全部数据查询出来

### ISSUE THREAD

**Issue by anyutianluo** [baomidou/mybatis-plus#4359]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页条件没有生效

### 重现步骤(如果有就写完整)
配置文件
@Bean
    public PaginationInnerInterceptor paginationInnerInterceptor() {
        PaginationInnerInterceptor paginationInnerInterceptor = new PaginationInnerInterceptor();
        return paginationInnerInterceptor;
    }
测试用例
@Test
    void selectPage() {
        Page<User> objectPage = new Page<>(0,5);
        QueryWrapper<User> userQueryWrapper = new QueryWrapper<>();
        userQueryWrapper
                .eq("name","insert");
        IPage<User> page = userMapper.selectPage(objectPage,userQueryWrapper);
        objectPage.getRecords().forEach(System.out::println);
        System.out.println(page.getTotal());
        System.out.println(page.getPages());
//        page.getRecords().forEach(System.out::println);
    }

### 报错信息
没有报错信息,就是分页条件不起作用

**Comment by miemieYaho** [comment]
看文档

**Comment by diego1109** [comment]
> 看文档

按照文档里的配置，也不 work。
- [https://baomidou.com/pages/2976a3/#spring](https://baomidou.com/pages/2976a3/#spring)
- [https://baomidou.com/pages/97710a/#paginationinnerinterceptor](https://baomidou.com/pages/97710a/#paginationinnerinterceptor)

**Comment by diego1109** [comment]
> 看文档

找到问题了 @MybatisPlusTest 在单测中没有使分页生效。
