### ISSUE TITLE
Mybatis Plus 的LamdbaUpdateWrapper的setSql调用java类方法

### ISSUE THREAD

**Issue by zacat** [baomidou/mybatis-plus#4362]
当前使用版本(必填,否则不予处理)

3.5.1

该问题是如何引起的？(确定最新版也有问题再提!!!)

Xml里可以的调用JAVA类方法方式，是否可以在LamdbaUpdateWrapper里的setSql中调用。

**Comment by VampireAchao** [comment]
目前不支持，欢迎pr
