### ISSUE TITLE
saveBatch的插件点不开，这是一个可以一条sql batch执行吗？

### ISSUE THREAD

**Issue by hachikozjq** [baomidou/mybatis-plus#4365]
### 当前使用版本(必填,否则不予处理)
3.5.1

https://github.com/baomidou/mybatis-plus/issues/3360

https://github.com/baomidou/mybatis-plus/issues/3360#issuecomment-789371126

https://github.com/baomidou/mybatis-plus/issues/2912#issuecomment-693347502

**Comment by huayanYu** [comment]
https://baomidou.com/pages/f84a74/#%E9%80%9A%E7%94%A8-insertbatch-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%BE%E5%9C%A8-service-%E5%B1%82%E5%A4%84%E7%90%86
