### ISSUE TITLE
H2数据库 offset失效

### ISSUE THREAD

**Issue by dfdfqwqw** [baomidou/mybatis-plus#4366]
### 当前使用版本(必填,否则不予处理)
3.0.7.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用H2数据库做单元测试，循环分页查询时发现offset没生效，大于1时还是会查出第一条数据
看了下master代码还是这样的
![image](https://user-images.githubusercontent.com/51687046/157821396-c8435870-1ea0-4577-beba-5f78d78c43f3.png)

### 重现步骤(如果有就写完整)
long offset=1;
while(true){
  Page<XX> page = new Page<>(offset, 500, false);
  List<XXX> list=page(page, wrapper).getRecords();
   if (CollectionUtils.isEmpty(smsMonUsages)) {
        break;
   }
   offset++;
}

### 报错信息
无限循环

**Comment by VampireAchao** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/b8938036d11f5b3c7462a97790f97c730f3ec98d

**Comment by dfdfqwqw** [comment]
> https://gitee.com/baomidou/mybatis-plus/commit/b8938036d11f5b3c7462a97790f97c730f3ec98d

回复你了

**Comment by miemieYaho** [comment]
版本太低,看文档使用最新版
