### ISSUE TITLE
请问什么时候能开发兼容scala的语言编程呢？

### ISSUE THREAD

**Issue by PingYufeng** [baomidou/mybatis-plus#4367]
mybatis 官网已经有兼容scala开发的包，mybatis-plus能实现兼容吗？
[mybatis scala](https://github.com/mybatis/scala)

**Comment by qmdx** [comment]
无支持计划，您可以考虑自行扩展，这边可以给予提供适配支持

**Comment by wjkanm** [comment]
我也希望啥时候能够支持scala。。。
