### ISSUE TITLE
KtQueryWrapper 的 allEq 怎么调用

### ISSUE THREAD

**Issue by gamergamer8888** [baomidou/mybatis-plus#4369]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

如果传入变量，显示类型不匹配
如果直接传入mapOf，正确

### 重现步骤(如果有就写完整)
`
val b = mapOf(User::name to "Jone")
val queryWrapper1 = KtQueryWrapper(User()).allEq(b) // 报错
val queryWrapper2 = KtQueryWrapper(User()).allEq(mapOf(User::name to "Jone")) //不报错
`
### 报错信息
Type mismatch.
Required:
(Mutable)Map<KProperty<*>!, TypeVariable(V)!>!
Found:
Map<KProperty1<User, String?>, String>

**Comment by VampireAchao** [comment]
能否尝试升级到最新版尝试
