### ISSUE TITLE
为什么这么就久了还不发布版本

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#437]
### 当前使用版本(必须填写清楚，否则不予处理)
v2.1.5

### 该问题是怎么引起的？
released this on 15 Nov 2017

**Comment by qmdx** [comment]
没毛病吧大兄弟！ 查看 https://search.maven.org/search?q=g:com.baomidou%20AND%20a:mybatis-plus&core=gav

**Comment by tianshishouhu** [comment]
在github怎么还是2.1.5


发送自 Windows 10 版邮件应用

发件人: qmdx
发送时间: 2018年8月20日 23:29
收件人: baomidou/mybatis-plus
抄送: wangjian; Author
主题: Re: [baomidou/mybatis-plus] 为什么这么就久了还不发布版本 (#437)

没毛病吧大兄弟！ 查看 https://search.maven.org/search?q=g:com.baomidou%20AND%20a:mybatis-plus&core=gav
