### ISSUE TITLE
文档没更新，配置分页插件没有setUseDeprecatedExecutor这个方法

### ISSUE THREAD

**Issue by hi-jungle** [baomidou/mybatis-plus#4370]
### 当前使用版本(必填,否则不予处理)
v-3.5.1
文档没更新吧，setUseDeprecatedExecutor已经没有了

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/44832463/158125553-1facc4be-ba0b-4840-8d2b-6b9c959ef61f.png)

### 重现步骤(如果有就写完整)
必现

### 报错信息

没报错

**Comment by hi-jungle** [comment]
![image](https://user-images.githubusercontent.com/44832463/158126061-19993428-b95f-488a-be47-987bd91d6dab.png)

**Comment by waveBoom** [comment]
看了下，应该是没更新，那个字段已经去除了 3.5.1版本

**Comment by CzyerChen** [comment]
目前看了官方文档还是显示旧版本的书写方式
引入3.5.1的版本还是不清楚如何书写
在网上查询到以下写法，正确吗？何时能更新官方文档？

@Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        //乐观锁
        interceptor.addInnerInterceptor(new OptimisticLockerInnerInterceptor());
        //分页锁
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }

**Comment by 1x1-lab** [comment]
#2955 这个是作者回答的高版本就没有这个配置了
