### ISSUE TITLE
in 一个empty list 能否直接返回空list

### ISSUE THREAD

**Issue by zhouwenjun0820** [baomidou/mybatis-plus#4372]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

mysql中in() 是错误语法，MP能否优化一下直接返回空List呢？

### 报错信息

![image](https://user-images.githubusercontent.com/35791384/158149795-d4677842-f7ba-4224-a499-455cd666334a.png)

**Comment by miemieYaho** [comment]
不能,自己判断
