### ISSUE TITLE
mysql写的触发器无法触发

### ISSUE THREAD

**Issue by wfh010624** [baomidou/mybatis-plus#4374]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在mysql中给数据表创建触发器，使用mybatisplus操作的时候没有触发，两边都没有报错信息

**Comment by idlesysman** [comment]
这跟mybatis-plus无关

**Comment by idlesysman** [comment]
建议手动insert/update看是否触发
