### ISSUE TITLE
配置逻辑删除后，无法再使用物理删除

### ISSUE THREAD

**Issue by Hunter-Lam** [baomidou/mybatis-plus#4378]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

需求背景：table既要逻辑删除，某些场景（如管理员清理数据）又要物理删除。
当前配置逻辑删除后，就无法通过MP使用物理删除

### 重现步骤(如果有就写完整)

无

### 报错信息

无

**Comment by miemieYaho** [comment]
写xml

**Comment by taotao365s** [comment]
mark

**Comment by Hunter-Lam** [comment]
写XML还需要提问吗？我就是希望MP能提供能力

**Comment by VampireAchao** [comment]
配置逻辑删除后，再使用物理删除会导致自增id不连续，会导致逻辑删除和物理删除混用难维护
