### ISSUE TITLE
关于逻辑删除的，提两点建义

### ISSUE THREAD

**Issue by male110** [baomidou/mybatis-plus#4381]
我搜索了一下以前别人提的issue，我提的问题别人也有遇到过。我想再提一下。
虽然这些可以用写SQL实现，但用一框架再去写SQL就让人觉得不太舒服。

1，加了罗辑删除的不能物理删除。
建义可以加一个forceDelete这样的方法，对有逻辑删除进行物理删，其它语言的一些框架都是这么做。

2，有时候需要查询已删除的数据，建义支持下。比如加一个includeDeleted方法之类的，来查询已删除的数据。

**Comment by miemieYaho** [comment]
逻辑删除就是删除,如果不想删除就自己用其他字段代表状态

**Comment by male110** [comment]
逻辑删除不是真的删除，在数据库中还有这条数据。
比如，有一个收藏表，userid,goodsid，用户收藏商品，我插入一条数1，1，用户删除收藏，我把这条数据标记为删除。如果用户再次点藏，我不想再插入一条1，1的数据，因为数据库里已经有一条删除的状态的，我只要把他改成未删除状态的就可以了。

其次，比如，我有一个商表，记录了最后修改人last_update_user_id，就算这个人是删除状态，这时我也想能查出来这个人的姓名，知道他是谁。

在其它语言的一些框架里都有提供相应的功能的。

**Comment by huayanYu** [comment]
你应该区分状态和删除。

**Comment by dujiecn** [comment]
> 逻辑删除就是删除,如果不想删除就自己用其他字段代表状态

这个诉求是很普遍的，希望大佬还是结合实际情况考虑一下。确实有时候需要查询出已删除的记录

**Comment by wblbird** [comment]
没错，我也支持楼主。我在做EXCEL批量导入的时候，由于表主键唯一，逻辑删除后又仍然存在，导致批量导入的时候主键冲突
