### ISSUE TITLE
typeHandler 泛型信息丢失

### ISSUE THREAD

**Issue by lovebing** [baomidou/mybatis-plus#4382]
https://github.com/baomidou/mybatis-plus/blob/0a286e1195f5a6c6d146ce4731ddd7cbd008573a/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/metadata/TableFieldInfo.java#L551

使用 propertyType 导致泛型信息丢失。如果这里传 field 进去，就可以实现一个公共的 typeHandler，支持 List<T> 的序列化和反序列化。

**Comment by ConnorLH** [comment]
发现同样的问题，为什么不进行修复呢？
