### ISSUE TITLE
请问 apply 方法是否会有 sql 注入风险

### ISSUE THREAD

**Issue by yunfeiSong** [baomidou/mybatis-plus#4384]
### 当前使用版本(必填,否则不予处理)

3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![微信截图_20220322172220](https://user-images.githubusercontent.com/33363778/159450774-9bb59f13-2eb1-4f37-a7c7-d3ed101bf5cd.png)

![微信截图_20220322171929](https://user-images.githubusercontent.com/33363778/159450870-c42f2f9f-7555-4b23-adae-be088d596ec9.png)

### 重现步骤(如果有就写完整)

无

### 报错信息
无

**Comment by VampireAchao** [comment]
按照官方文档，正确使用就不会

**Comment by qmdx** [comment]
任何允许输入字符串的 SQL 片段都是存在注入问题【需要使用者自己控制安全】，可以调用 MP SqlInjectionUtils 的 check 方法检查 SQL 合法性。
