### ISSUE TITLE
租户拦截器（TenantLineInnerInterceptor）代码优化建议

### ISSUE THREAD

**Issue by jeeagile** [baomidou/mybatis-plus#4386]
### 当前使用版本(必填,否则不予处理)
版本 3.5.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
租户拦截器（TenantLineInnerInterceptor）方法builderExpression如下代码段：
       // 租户
        Expression tenantId = tenantLineHandler.getTenantId();
        // 构造每张表的条件
        List<EqualsTo> equalsTos = tables.stream()
            .filter(x -> !tenantLineHandler.ignoreTable(x.getName()))
            .map(item -> new EqualsTo(getAliasColumn(item), tenantId))
            .collect(Collectors.toList());
此代码段执行先获取了租户表达式，然后进行过滤再构造每张表条件，由于应用在启动的时候需要优先执行SQL，但这时候没有办法获取到租户信息（需要进行异常处理），建议此处获取租户表达式放到过滤之后，代码调整优化如下（大佬有其他办法更好）:
        // 构造每张表的条件
        List<EqualsTo> equalsTos = tables.stream()
                .filter(x -> !tenantLineHandler.ignoreTable(x.getName()))
                .map(item -> {
                    Expression tenantId = tenantLineHandler.getTenantId();
                    return new EqualsTo(getAliasColumn(item), tenantId);
                })
                .collect(Collectors.toList());

**Comment by miemieYaho** [comment]
86ecda70f2d8acf0f80ba5236631f834cdef911a

**Comment by miemieYaho** [comment]
不过你这种一启动就执行sql的情况你怎么处理租户信息?

**Comment by jeeagile** [comment]
简单来说启动执行的sql跟租户没有关系（可以理解为定时任务），我这边打算获取租户信息从用户session里获取（使用的是apache shiro），但启动的时候还不存在用户session，导致apache shiro底层报错，只能进行异常处理了，我看代码已进行调整，感谢大佬支持。

**Comment by jeeagile** [comment]
启动执行SQL跟租户无关，租户信息处理还在考虑中，只所以提这个问题，目前是从用户session中获取（考虑还不完善），租户表达式里用了apache shiro获取session导致报错。感谢大佬支持！！！

**Comment by qmdx** [comment]
自行处理可以借助 ThreadLocal 传递用户信息
