### ISSUE TITLE
mybatis plus实体类同时存在有参构造和无参构造时，实体对象属性接收结果部分为null

### ISSUE THREAD

**Issue by misaki-zdx** [baomidou/mybatis-plus#4388]
### 当前使用版本(必填,否则不予处理)

3.4.3.1，3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

业务场景需要Map转实体对象。用fastJson转对象时需要无参构造，在实体对象加上无参构造并用@Tolerate修饰，之后此实体查询接收异常。

### 重现步骤(如果有就写完整)

mybatis plus实体类加上无参构造，selectById即可

### 报错信息

无报错信息。

**Comment by miemieYaho** [comment]
你不加注解就不为null了?

**Comment by misaki-zdx** [comment]
> 你不加注解就不为null了?

非常感谢！自己太迷糊了=_=!  mapunderscoretocamelcase设置为true，导致@TableField失效。
