### ISSUE TITLE
条件构造器allEq含有BiPredicate参数时没有按照预期执行

### ISSUE THREAD

**Issue by holsey** [baomidou/mybatis-plus#4390]
mybatisplus.version：3.5.1

代码部分
HashMap<SFunction<User, ?>, Object> map = new HashMap();
map.put(User::getName, "Jone");

Page<User> userPage = userMapper.selectPage(new Page<>(1, 10),
Wrappers.<User>lambdaQuery().allEq((k, v) -> k.equals("name"), map, true));
userPage.getRecords().forEach(user -> log.info("{}", user));

控制台sql执行
SELECT id,name,age,email,role_id FROM user
没有把name字段作为查询条件

**Comment by miemieYaho** [comment]
SFunction<User, ?>.equals("name")==false
