### ISSUE TITLE
Warn: Could not find @TableId in Class: com.**类没有主键，项目启动时会报出warn并卡住很长时间，此表本身不带主键

### ISSUE THREAD

**Issue by wanghongquana** [baomidou/mybatis-plus#4391]
### 当前使用版本(必填,否则不予处理)
2.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目启动就会有

### 报错信息

Warn: Could not find @TableId in Class: com.**

**Comment by miemieYaho** [comment]
不是卡
