### ISSUE TITLE
@ TableLogic 是否考虑支持多个值标识为删除，多个值标识为未删除

### ISSUE THREAD

**Issue by oymy** [baomidou/mybatis-plus#4392]
### 当前使用版本(必填,否则不予处理)
3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
例如， 如果我们有一个状态枚举， 其中 DELETED标识删除，其他多个状态 ACTIVE,EXPIRED 等表示 未删除。
目前的 @TableLogic 是无法支持的。

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
不支持
