### ISSUE TITLE
多数据源（多种数据库）分页插件若配置多个InnerInterceptor,会出现多个limit,程序报错，若不指定，则不返回总数等信息

### ISSUE THREAD

**Issue by yaMaRaj** [baomidou/mybatis-plus#4394]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://user-images.githubusercontent.com/50065878/160100609-a600b599-bef7-4bf0-8910-20ca3fa1f956.png)
![image](https://user-images.githubusercontent.com/50065878/160100768-ae97de42-0fc5-41ca-a6b1-9a919767b7f4.png)
多个InnerInterceptor时，不根据实际的mapper判断到底是哪个数据源，直接循环遍历所有的，然后就会在beforeQuery中多次执行，导致出现多个limit.

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/50065878/160101193-f9ed1313-d97f-43a3-83f3-8b68185ab391.png)
![image](https://user-images.githubusercontent.com/50065878/160101269-57ced4b1-b2cc-4865-be98-fdefe63a24a6.png)

### 报错信息
![image](https://user-images.githubusercontent.com/50065878/160101137-d14919bd-359b-430a-82c2-a2a4a5731ad5.png)

**Comment by huayanYu** [comment]
不要配DbType

**Comment by yaMaRaj** [comment]
> 不要配DbType

不配DbType返回的IPage对象中，total字段一直都是0
![image](https://user-images.githubusercontent.com/50065878/160227751-fe6b6436-98a6-4a49-9508-46d2c52391d3.png)

**Comment by yaMaRaj** [comment]
不解决问题就直接关了？
