### ISSUE TITLE
分页建议

### ISSUE THREAD

**Issue by zk230** [baomidou/mybatis-plus#440]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.9

### 该问题是怎么引起的？
前端使用datatables控件，控件上送的参数是起始记录条数（start）,而不是当前页数（current）,导致分页无法实现

### 重现步骤

前端使用datatables控件，控件上送的参数是起始记录条数（start）,而不是当前页数（current）,导致分页无法实现

### 报错信息

我看了下3.x的版本分页虽然已经接口化了，但是依然是以current来操作分页，建议 更灵活一点，比如添加起始记录条数 字段,操作limit和offset更加灵活

**Comment by miemieYaho** [comment]
个性化的设置你可以继承page或者实现ipage自己动手.
