### ISSUE TITLE
自定义mapper事务问题请教

### ISSUE THREAD

**Issue by jhx-zc** [baomidou/mybatis-plus#4400]
### 当前使用版本(必填,否则不予处理)
latest： 3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
拥有一个自定义mapper，没有继承BaseMapper。但是如果这个mapper的sql执行出问题，没有回滚数据。如果在这个sql执行前其他sql出错又会正常回滚。

### 重现步骤(如果有就写完整)
这个是自定义Mapper的定义，以及其service。正常运行的话是可以正确执行的。
![image](https://user-images.githubusercontent.com/52167297/160993788-ae76cf20-99c9-4647-808c-2c4f0131e924.png)

1. 异常回滚案例：
第30行代码是预期会出错的代码，但是前两个save的结果打进了数据库
![image](https://user-images.githubusercontent.com/52167297/160993295-02ed8eff-521d-4df6-966d-7c679ca17fd2.png)

2.正常回滚案例1：
多次插入同一id数据，引发事务回滚，验证可以正常回滚
![image](https://user-images.githubusercontent.com/52167297/160994731-f454c566-5d63-4251-9b1b-ab55917f299c.png)

3.正常回滚案例2： 
临时删除29行save对应的表，引起回滚。效果正常
![image](https://user-images.githubusercontent.com/52167297/160995220-d99f0ed5-9bb2-4454-9f53-ef4eb6ee7993.png)

请问是我的service写的有问题导致的事务无法正确回滚吗？还是i自定义的mapper需要有其他的配置？

**Comment by VampireAchao** [comment]
可以手动控制事务实现？

**Comment by qmdx** [comment]
未反馈
