### ISSUE TITLE
updateBatchById

### ISSUE THREAD

**Issue by miaotaizi** [baomidou/mybatis-plus#4401]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
批量更新

### 重现步骤(如果有就写完整)
实体字段为 枚举类型

### 报错信息
字段值变为 枚举 名

**Comment by VampireAchao** [comment]
[通用枚举文档](https://baomidou.com/pages/8390a4/#_1%E3%80%81%E5%A3%B0%E6%98%8E%E9%80%9A%E7%94%A8%E6%9E%9A%E4%B8%BE%E5%B1%9E%E6%80%A7)
请确认是否按照文档使用，最新版是否存在该问题，或提供能复现的代码
