### ISSUE TITLE
希望可以对MybatisPlusInterceptor添加扩展方法 可以对查询结果和查询参数进行后置处理 如将查询结果放入查询参数中的分页参数中

### ISSUE THREAD

**Issue by qinyunfei** [baomidou/mybatis-plus#4415]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![微信图片编辑_20220406122302](https://user-images.githubusercontent.com/23376450/161896916-a3599c23-6c8c-49f4-b1bc-1eb10219e04e.jpg)

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
不支持
