### ISSUE TITLE
希望对MybatisPlusInterceptor进行修改问题如图中所描述

### ISSUE THREAD

**Issue by qinyunfei** [baomidou/mybatis-plus#4416]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![微信截图_20220406124949](https://user-images.githubusercontent.com/23376450/161898101-46c6c7bc-808c-48f3-aeec-f56ac40f28e6.png)

### 重现步骤(如果有就写完整)
mapper方法为空参数 如  List<User> selectListRel();  我声明自定义mybatispuls  InnerInterceptor拦截器再query.beforeQuery中对parameter进行赋值时   该parameter并不会传入executor.query中执行 executor.query中执行的parameter任然是null  希望可以进行处理使用户使用InnerInterceptor 更灵活

### 报错信息
无

**Comment by miemieYaho** [comment]
不支持
