### ISSUE TITLE
sql server 2014 版本中 saveOrUpdate失效

### ISSUE THREAD

**Issue by zhangtz5** [baomidou/mybatis-plus#4419]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

saveOrUpdate 添加或更新数据时提示 Updates: 1 但数据库中数据未更改

### 重现步骤(如果有就写完整)
SQL to parse, SQL: UPDATE mob_xs_meet_sign_up_info  SET meet_id=?,
dist_id=?,
dist_name=?,
meet_join_count=?,
sign_up_type=?,

update_date=?  WHERE id=?  AND del_flag=0
parse the finished SQL: UPDATE mob_xs_meet_sign_up_info SET meet_id = ?, dist_id = ?, dist_name = ?, meet_join_count = ?, sign_up_type = ?, update_date = ? WHERE id = ? AND del_flag = 0
==>  Preparing: UPDATE mob_xs_meet_sign_up_info SET meet_id=?, dist_id=?, dist_name=?, meet_join_count=?, sign_up_type=?, update_date=? WHERE id=? AND del_flag=0
==> Parameters: 1500660960117477377(String), A07251725(String), 侍艳(String), 12(Integer), true(Boolean), 2022-04-08 14:29:25.42(Timestamp), 1501491822534971394(String)
<==    Updates: 1

结果：
![image](https://user-images.githubusercontent.com/33055220/162379918-45bb1f0d-2c18-4bdc-9f64-5d4263ea3451.png)

meet_join_count 由7更改为 12 失败

**Comment by qmdx** [comment]
无法定位，如果解决欢迎评论分享
