### ISSUE TITLE
从数据库选取 1万条以上数据的性能

### ISSUE THREAD

**Issue by chzhong** [baomidou/mybatis-plus#442]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3

### 该问题是怎么引起的？
由于业务原因，不得不从数据库中一次性取出上万条数据（无法分页）。

### 重现步骤
1. 于任意数据库表中，插入几万条数据。
2. 将其全部 SELECT 出来。

### 报错信息
用 数据库原始查询，HeidiSQL 等耗时不足1秒（约 70ms 不到的数据库时间 + 500~700ms 的网络传输时间）。
但是通过 MyBatis-Plus 返回的数据对象耗时 2500ms~4500ms 不等。

**Comment by huayanYu** [comment]
你可以先对比原生mybatis的耗时。 返回映射这一块是原生的东西。 差距应该不大。  如果差距很大再来开启问题。
