### ISSUE TITLE
[Feature] 支持分页自定义Count

### ISSUE THREAD

**Issue by Jackjun724** [baomidou/mybatis-plus#4423]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter@3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

当我的MySQL表中有一个`text`类型字段时，在一个十几万数据的表上使用`select count(*)` 耗时多达两秒，而`select count(otherIndex)` 仅几十毫秒（具体原因参考MySQL优化策略）。

### 重现步骤(如果有就写完整)
构建十几万数据的表，包含text类型的字段，切内容为较长的文本

### 报错信息
无

### 其他信息

查阅相关文档后没有找到这个功能，Mybatis Page Helper 支持自己写`id + '_COUNT'`来override生成的count语句，但是我尝试写`id + '_mpCount'`无效。

**Comment by miemieYaho** [comment]
page.setCountId
