### ISSUE TITLE
FastjsonTypeHandler查出来为空

### ISSUE THREAD

**Issue by l42111996** [baomidou/mybatis-plus#4424]
### 当前使用版本(必填,否则不予处理)

mybatis 3.5.1
mysql 8.0.28

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

字段名为 
@ApiModelProperty("部件信息")
@TableField(typeHandler = FastjsonTypeHandler.class)
private AvatarInfo avatar;

我查询的方式为
playerDisplay = getById(id);

对象信息为
@Getter
@Setter
public class AvatarInfo implements Serializable {
    private int[] avatars;
}

### 重现步骤(如果有就写完整)
如上

### 报错信息
无

**Comment by miemieYaho** [comment]
自己排查
