### ISSUE TITLE
每次查询条件参数个数以及具体参数不同该如何处理？

### ISSUE THREAD

**Issue by fytsLiuNing** [baomidou/mybatis-plus#443]
### 当前使用版本(必须填写清楚，否则不予处理)

2.3

### 该问题是怎么引起的？
注意: 很多问题已在大版本号下的最新版上修复,使用最新版还有该问题再提 issue!

是否每次查询都需要编辑实体包装类，因为每个查询条件的参数个数，和参数都不同，如何构建通用的dao层或者业务层呢？请指教

**Comment by miemieYaho** [comment]
dbutils适合你
