### ISSUE TITLE
graalvm native 什么时候支持呢

### ISSUE THREAD

**Issue by MikeGrateful** [baomidou/mybatis-plus#4439]
graalvm native 什么时候支持呢

**Comment by VampireAchao** [comment]
欢迎pr

**Comment by linghengqian** [comment]
This is an issue that should be closed because https://github.com/quarkiverse/quarkus-mybatis is in a production-ready state.

**Comment by mylxy** [comment]
> This is an issue that should be closed because https://github.com/quarkiverse/quarkus-mybatis is in a production-ready state.

什么意思？这是两个不同的框架呀！

**Comment by linghengqian** [comment]
@mylxy We don't discuss Spring, for MybatisPlus, it's at https://github.com/quarkiverse/quarkus-mybatis/tree/master/mybatis-plus .

**Comment by mylxy** [comment]
> @mylxy We don't discuss Spring, for MybatisPlus, it's at https://github.com/quarkiverse/quarkus-mybatis/tree/master/mybatis-plus .

谢谢！

**Comment by lanPeiYu** [comment]
mybatis 3.5.12 can fix this, i tried

**Comment by nieqiurong** [comment]
#5527  统一至此处讨论.
