### ISSUE TITLE
【建议】 构造器中 select能否也设计成链式

### ISSUE THREAD

**Issue by qiuhuanhen** [baomidou/mybatis-plus#4440]
### 当前使用版本 3.5.1 

当前最新版本

### 该问题是如何引起的？

使用构造器查询的时候 (new QueryWrapper<xx>.lambda.select(xx::getXxx).select(xx::getXzzz) ) 
第一个select 会被后面的select覆盖  。    虽然理解也知道  select支持动态参数 select(xx::getXxx,xx::getXzzz) ，
但是既然构造器设计成了链式 且 eq()是支持多个的，而select并不支持多个，可能会引起使用中的误操作

### 重现步骤(如果有就写完整)

后面的   .select会覆盖前面的 .select

### 报错信息
无报错

**Comment by VampireAchao** [comment]
链式`.select`虽然能风格一致，但也会导致代码量更多，也许却有场景存在复用`wrapper`中查询条件但`select`字段变动需求，贸然升级可能会带来老用户升级困难

**Comment by qmdx** [comment]
没有必要
