### ISSUE TITLE
lambda表达式，无法实现子查询

### ISSUE THREAD

**Issue by Lsatin** [baomidou/mybatis-plus#4441]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
LambdaQueryWrapper.select，无法实现 **子查询**

### 重现步骤(如果有就写完整)
SELECT (子查询) AS xxx FROM XXX

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not find lambda cache for this property [xxx] of entity [class]

**Comment by VampireAchao** [comment]
可以使用
```java
Wrappers.<Entity>query().select("子查询").lambda().eq(Entity::getId,1L);
```
这种方式实现

**Comment by Lsatin** [comment]
这个我知道。
但是，无法和已经使用lambda的wrapper做嵌套

**Comment by huayanYu** [comment]
无法
