### ISSUE TITLE
在条件构造器中如何使用正则表达式查询字段数据

### ISSUE THREAD

**Issue by netSharks** [baomidou/mybatis-plus#4445]
### 当前使用版本(必填,否则不予处理)

com.baomidou mybatis-plus-boot-starter 3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在条件构造器中如何使用正则表达式查询字段数据

### 重现步骤(如果有就写完整)

比如查询ip字段192.168。*或者10.*.17，以及文字内容的正则

**Comment by qmdx** [comment]
wrapper 不支持表达式函数，请自定义xml sql
