### ISSUE TITLE
MybatisMapperRefresh 老是出现问题，引起系统奔溃

### ISSUE THREAD

**Issue by xiangyichang** [baomidou/mybatis-plus#445]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatisplus.version>2.3</mybatisplus.version>
<mybatisplus.spring.boot.version>1.0.5</mybatisplus.spring.boot.version>

### 该问题是怎么引起的？
注意: 很多问题已在大版本号下的最新版上修复,使用最新版还有该问题再提 issue!
Linux上无法启动，tomcat下老是奔溃中
 怎么设置关闭MybatisMapperRefresh ？？？

### 重现步骤
运行一段时间就报错

### 报错信息
Current thread(0x00007f2ac9923999): JavaThread "mybatis-plus MapperRefresh" [_thread_in_native, id=23882, stack(0x00007f2a6f4b6000,....)]

**Comment by miemieYaho** [comment]
1.你用的bootstart版本太陈旧,新版不叫这个名字了
2.这个刷新mapper是默认不会有的,除非你自己配置了
