### ISSUE TITLE
自动拼接 and null = null

### ISSUE THREAD

**Issue by feng-dan** [baomidou/mybatis-plus#4453]
### 当前使用版本(必填,否则不予处理)
mybatis-plus.version  3.4.3.4

### 报错信息

<img width="843" alt="8b7fb9d9c1ae0becbf9d98eeef1f7c4" src="https://user-images.githubusercontent.com/29519215/164682372-febfc1b1-b31b-4ac7-b964-b08883902b80.png">

![image](https://user-images.githubusercontent.com/29519215/164683328-b2468a8b-9868-413e-8706-36c100933a9d.png)

**Comment by miemieYaho** [comment]
给出复现demo

**Comment by feng-dan** [comment]
问题解决了，不是 mybatis-plus 问题，谢谢回复

**Comment by shuolol** [comment]
请问是怎么解决的呢，我也遇到同样的问题

**Comment by Leevle** [comment]
我也遇到了相同问题，请问你的解决方案是什么能给我参考吗
