### ISSUE TITLE
乐观锁插件优化建议

### ISSUE THREAD

**Issue by Janzlan** [baomidou/mybatis-plus#4455]
### 当前使用版本(必填,否则不予处理)
3.5.1

建议OptimisticLockerInnerInterceptor增加配置项：是否抛出乐观锁异常OptimisticLockingFailureException
1、自行判断updates=0进行处理，代码变得臃肿
2、忘记判断，排查麻烦
3、抛出异常，交给controller统一拦截进行友好提示，多舒服

或者，有其他统一处理的方案？

**Comment by miemieYaho** [comment]
你说的是执行sql后的事,插件只作用于执行sql前

**Comment by Debenson** [comment]
是的， 以前的乐观锁插件可以实现类似的效果，现在不行了
