### ISSUE TITLE
selectPage可以正常查询 selectList却报错

### ISSUE THREAD

**Issue by zhengmingcan** [baomidou/mybatis-plus#4456]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

selectPage可以正常查询 selectList却报错

### 重现步骤(如果有就写完整)
 List<Long> semiFinishedIdList = semiFinishedPlanConfigDOPage.getRecords().stream().map(SemiFinishedPlanConfigDO::getId).collect(Collectors.toList());
        QueryWrapper<MakePercentConfigDO> makePercentConfigQueryWrapper = new QueryWrapper<>();
        makePercentConfigQueryWrapper.lambda().in(MakePercentConfigDO::getSemiFinishedId, semiFinishedIdList);
        List<MakePercentConfigDO> makePercentConfigDOList = makePercentConfigMapper.selectList(makePercentConfigQueryWrapper);

### 报错信息

org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'MPGENVAL1' in 'class com.baomidou.mybatisplus.core.conditions.query.QueryWrapper'

	at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:373)
	at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:163)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)

**Comment by VampireAchao** [comment]
指定一下泛型，在`lambda`方法中传入一下`entity`试试呢
```java
QueryWrapper<MakePercentConfigDO> makePercentConfigQueryWrapper = new QueryWrapper<>();
makePercentConfigQueryWrapper.lambda(new MakePercentConfigDO()).in(MakePercentConfigDO::getSemiFinishedId, semiFinishedIdList);
```
