### ISSUE TITLE
分页插件在多租户插件启用时，分页Count查询时，未带入 teanId,导致记录总数和分页实际总数不一致

### ISSUE THREAD

**Issue by liujian969** [baomidou/mybatis-plus#4458]
### 当前使用版本(必填,否则不予处理)
3.4.3.4 +

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版测试 仍存在问题

### 重现步骤(如果有就写完整)

` @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        //增加分页插件
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor());

        //增加租户插件
        interceptor.addInnerInterceptor(new TenantLineInnerInterceptor(new TenantLineHandler() {
            @Override
            public Expression getTenantId() {
                if (BaseContextHandler.getTenantID() != null) {
                    return new StringValue(BaseContextHandler.getTenantID());
                }
                return new NullValue();
            }

            @Override
            public String getTenantIdColumn() {
                return "TENANT_ID";
            }

            @Override
            public boolean ignoreTable(String tableName) {
                return false;
            }
        }));

        return interceptor;
    }`

### 报错信息

使用page 分页查询， 打印 两条sql语句：

查询总页数时， 未自动添加拦截 TENANT_ID= ？  

获取分页数据时 ，正常。

**Comment by miemieYaho** [comment]
看文档插件顺序

**Comment by LiZhouYan** [comment]
建议内部做一下插件的顺序，例如：分页在最后等
不仔细看文档，还真会踩到坑
