### ISSUE TITLE
批量保存不同类型

### ISSUE THREAD

**Issue by mengxzh** [baomidou/mybatis-plus#4460]
### 当前使用版本(必填,否则不予处理)

mybatis-plug-boot-starter : 3.4.2

### 我的问题
我现在有一个 List<T> , 想通过调用一个service的 saveOrUpdateBatch，实现通过调用一个 service 把这个 List<T> 中所有的类型都保存/更新 到 对应的表里, 目前 T 是确定的 使用了@TableFieldId, 并且 T 类上也有@TableName    

现在我不知道是否已经有现成的方法还是需要自己去扩展
如果自己扩展的话是怎么扩展

**Comment by VampireAchao** [comment]
先分组，后存库
```java
List<UserInfo> list = new ArrayList<>();
        list.stream().collect(Collectors.groupingBy(UserInfo::getClass)).values().forEach(userService::saveOrUpdateBatch);
```
