### ISSUE TITLE
分页插件sql解析错误

### ISSUE THREAD

**Issue by Yzz-Ymin** [baomidou/mybatis-plus#4463]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在做查询的时候如果使用find_in_set函数进行表连接，会存在分页插件sql解析错误问题，联表直接变成了单表

### 重现步骤(如果有就写完整)

select A left join B on find_in_set("B.id", A.parent_id)

### 报错信息
报错的sql结果，但是分页sql解析为 SELECT COUNT(*) AS total FROM A;

**Comment by totoro52** [comment]
on find_in_set("B.id", A.parent_id)  这个插件识别不了直接给你优化掉了，你可以关闭分页的优化选项，但这不算解决问题。

**Comment by qmdx** [comment]
> on find_in_set("B.id", A.parent_id) 这个插件识别不了直接给你优化掉了，你可以关闭分页的优化选项，但这不算解决问题。

这是一个解决办法，或者可以提 Bug  到 jSqlParser 让该组件支持该函数的解析 https://github.com/JSQLParser/JSqlParser
