### ISSUE TITLE
lambdaUpdateWrapper重复赋值同一个字段，postgresql报错

### ISSUE THREAD

**Issue by shiyinhongsama** [baomidou/mybatis-plus#4468]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
object.update(LambdaUpdateWrapper)时，如果对象已经有值，会生成重复 `set xxx=?` 的sql语句。
在华为gaussDB报错，Postgresql旧版本也是：
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/26181818/165847601-f5e36452-5dcf-404d-8ce3-1b04ed319a85.png">

### 重现步骤(如果有就写完整)
首先如果我的对象字段很多，我只想update一部分，很容易使用下面的方式：
```
object.setId(1);
object.setColumnX("any");
object.update(LambdaUpdateWrapper.set(object::getColumX, "any").eq(object::getId, object.getId()));
```
建议优化一下，谢谢~
### 报错信息
```
Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: multiple assignments to same column 'column_x'

**Comment by miemieYaho** [comment]
不会去重,你优化你的代码吧

**Comment by shiyinhongsama** [comment]
好的，代码肯定优化，我这边只是提个建议哈
