### ISSUE TITLE
大佬，能更新文档吗？

### ISSUE THREAD

**Issue by rffanlab** [baomidou/mybatis-plus#447]
我新手，使用MP的时候，看文档各种问题找不到。。。。。。。文档太老了？spring boot版本的MP。。。。

**Comment by huayanYu** [comment]
可以先把mybatis的官方文档看熟悉，熟练了再来使用mp。

**Comment by rffanlab** [comment]
大佬啊，关键是，我看着MP的官方文档啊，但是很多代码都不同啊，例如查询，官方文档写的是Wrapper 但是代码应用中Wrapper根本没有，却需要使用QueryWrapper 。。。。。这个，你让我怎么看？。。。。。。。

**Comment by rffanlab** [comment]
或者，你们讲文档写的细一点，例如加上这些版本变更中的改变？- -可否？

**Comment by yuxiaobin** [comment]
目前(官网)[http://mp.baomidou.com/]是2.x的文档
