### ISSUE TITLE
继承BaseMapper，selectById偶发在数据库存在值的情况下返回null，IService的getById存在同样问题

### ISSUE THREAD

**Issue by gaojoe19** [baomidou/mybatis-plus#4473]
### 当前使用版本(必填,否则不予处理)
当前版本3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
生产环境异常排查，发现低概率出现selectById返回null，检查数据库有值，改为mybatis原生方式查询可以查出数据。数据库：mysql5.7.17,应用框架：springboot2.6.3

### 报错信息

无报错信息

**Comment by huayanYu** [comment]
无法复现，底层还是mybatis。 可提供一个能复现的demo和步骤

**Comment by 806330706** [comment]
我也出现了相同的问题，偶现结果为null, mybatis-plus-boot-starter 3.2.0,请问这个怎么解

**Comment by zqb666** [comment]
3.5.2也有这个问题 导致saveOrUpdate和saveOrUpdateBatch的时候 实体类里有id值的情况下 也走了save 没有走update 希望官方尽快解决下这个严重bug
