### ISSUE TITLE
测试环境和产线环境的用户名不一样有什么比较好的解决办法吗

### ISSUE THREAD

**Issue by hzitao** [baomidou/mybatis-plus#4476]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我使用的是oracle数据库，测试环境的用户名是A，产线环境的用户名是B，我不想上线打包时还要把所有的A改为B，想直接通过配置文件来实现SQL动态读取配置文件的信息，然后渲染到SQL，执行sql有什么比较好的方法吗

### 重现步骤(如果有就写完整)

测试环境SQL：select * from A.test
产线环境SQL：select * from B.test

想直接A或者B替换为类似#{username}渲染为select * from #{username}.test
username在配置文件中读取

**Comment by huayanYu** [comment]
框架不解决这个问题
