### ISSUE TITLE
Clickhouse 驱动 需要更新为com.clickhouse.jdbc.ClickHouseDriver

### ISSUE THREAD

**Issue by liujian969** [baomidou/mybatis-plus#4477]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

Clickhouse修复了0.3.2之前的时区问题， 但老的版本上不再维护，需要更新新的 Driver。同时URL也做了更新，
更新后的驱动URL为 jdbc:ch://localhost/test?socket_timeout=120000

### 重现步骤(如果有就写完整)

需要替换原来的 jdbc:clickhouse://localhost/test?socket_timeout=120000

### 报错信息

插入未反应

**Comment by liujian969** [comment]
具体驱动 详见： https://github.com/ClickHouse/clickhouse-jdbc

**Comment by linghengqian** [comment]
Why is this issue marked `todo:spiral_notepad:` instead of `status:volunteer wanted`?  This means that breaking change PRs cannot be submitted? @huayanYu

**Comment by linghengqian** [comment]
I am working on this issue.

**Comment by linghengqian** [comment]
- Resolved at https://github.com/baomidou/mybatis-plus/pull/4799.
