### ISSUE TITLE
存储过程要怎么调用？是否有自定义接入方法

### ISSUE THREAD

**Issue by hyuans** [baomidou/mybatis-plus#448]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
看文档中没有存储过程调用的案例，有没相关案例可以提供下？
有没有办法在这个框架做些自定义的改造？比如通过元数据（metadata）分析存储过程入参出参结构，然后根据结构做自定义规则的参数赋值

**Comment by qmdx** [comment]
mybatis 原生该怎么玩还是怎么玩
