### ISSUE TITLE
代码没有传值，能不能按数据库定义的默认字段插入。

### ISSUE THREAD

**Issue by jisl1024** [baomidou/mybatis-plus#4481]
### 当前使用版本(必填,否则不予处理)

3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
生产环境跑了一段时间，因为业务需要。需要扩充字段，扩展字段数据库脚本已经更新了。
这边代码还没更新，希望插入能够数据库定义默认值插入。比如实体没传值就按，数据库定义的默认值插入而不是null
比如，增加一个字段
`group_code` varchar(16) NOT NULL DEFAULT '0' COMMENT '分组编号	'
最后能够插入不同值

之前接触其他的mybaits插入有两个选择，插入，和插入实体有的
更新也是，全部更新，和按照实体更新
不知道有没有，

**Comment by Saroth** [comment]
您有找到实现方法吗？
我也非常需要类似insertSelective的功能
