### ISSUE TITLE
是否支持除组件外的批量修改

### ISSUE THREAD

**Issue by qeprwjcgya** [baomidou/mybatis-plus#4483]
请问是否支持这种批量修改，如果循环去update会影响效率
<foreach collection="list" item="item" index="index" open="" close="" separator=";"> 
       update TB_ROLE_MENU  
          <set> 
          FID=#{item.fid}
          </set> 
          where ROLEID = #{item.roleid} 
      </foreach>

**Comment by huayanYu** [comment]
看不懂描述，请重新整理描述重提
