### ISSUE TITLE
是否支持除组件外的批量修改

### ISSUE THREAD

**Issue by qeprwjcgya** [baomidou/mybatis-plus#4484]
**现有两种实现方式
--------------------------------------------------------------------------------------------
第一种
可以通过mybatis-plus原生的
        updateRoleMenus.forEach(item->{
            Menu menuEdit = new Menu();
            menuEdit.setFid(item.getFid());
            UpdateWrapper<Menu> wrapper = new UpdateWrapper<>();
            wrapper.eq(Menu::getRoleId,item.getRoleId());
            this.update(menuEdit,wrapper);
        });
第二种
----------------------------------------------------------------------------------------------
通过修改mybatis中mapper.xml文件件，如下：
<update id="updateRoleMenus" parameterType="java.util.List"> 
      <foreach collection="list" item="item" index="index" open="" close="" separator=";"> 
       update TB_ROLE_MENU  
          <set> 
          FID=#{item.fid}
          </set> 
          where ROLEID = #{item.roleId} 
      </foreach>
</update>

如果修改的条数有多条时第一种的效率是低于第二种的，mybatis-plus有没有更好的方式替换第一种的。****

**Comment by huayanYu** [comment]
没有，你这始终需要循环动态拼接sql。  第二种是最高效的了。 再高效就只能JDBC了。 但是你逃不出循环处理的问题。
