### ISSUE TITLE
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("

### ISSUE THREAD

**Issue by zhoubin7** [baomidou/mybatis-plus#4485]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
加入多租户插件

### 重现步骤(如果有就写完整)

SELECT
	sum(
	CASE
			
			WHEN pcr.pcall_times MOD 60 = 0 THEN
			pcr.pcall_times ELSE ( FLOOR( pcr.pcall_times / 60 ) + 1 ) * 60 
		END 
		) AS 'call_times',
		sum( pcall_times ) AS 'actual_call_times' 
	FROM
		t_phone_call_record AS pcr 
WHERE
	pcall_times > 0

### 报错信息

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 1, column 11.

Was expecting one of:

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException
