### ISSUE TITLE
mybatis.type-aliases-package不生效，需添加mybatis-plus.type-aliases-package才生效

### ISSUE THREAD

**Issue by tantalate** [baomidou/mybatis-plus#4487]
### 3.5.1

Springboot老项目新使用mybatis-plus 
配置了mybatis.type-aliases-package，但是xxxmapper.xml中仍然无法直接使用类名
配置mybatis-plus.type-aliases-package之后，才能直接使用类名。

这两个选项有啥区别？这种情况是设计如此还是出问题了？

**Comment by miemieYaho** [comment]
这里不教spring的知识

**Comment by tantalate** [comment]
Mybatis-Plus不是号称**无侵入：只做增强不做改变，引入它不会对现有工程产生影响，如丝般顺滑**?
那现有项目引入之后导致无法运行，应该算是BUG了吧
