### ISSUE TITLE
2.3.1版本的insertOrUpdateBatch()方法第二参数不起作用

### ISSUE THREAD

**Issue by ynFatal** [baomidou/mybatis-plus#449]
### 当前使用版本
当前使用版本2.3.1

### 该问题是怎么引起的？
我在测试添加的方法，测试 inserBatch() 和 insertOrUpdateBatch() 的时候，我做了个比较，前者问题不是很大，在设置第二个参数 batchSize 的时候，结果在我理解范围之内；然后测试后者时，不管我把 batchSize 设置为多少，它的耗时都没变，控制台也只显示一条sql对应一条记录。我想问是我理解错了，还是 insertOrUpdateBatch() 方法有问题？

### 图片
**1. 测试inserBatch()的第二参数**
>batchSize 设置越大，耗时相对越小

![1](https://user-images.githubusercontent.com/40764140/44727016-9a81fc00-ab0b-11e8-8175-56f630a95213.jpg)

![2](https://user-images.githubusercontent.com/40764140/44727026-a1107380-ab0b-11e8-9816-5fa19d33c0a5.jpg)

**2. 测试insertOrUpdateBatch()的第二参数**
>batchSize 的大小好像与耗时没有关系

![3](https://user-images.githubusercontent.com/40764140/44727032-a5d52780-ab0b-11e8-9b11-5e02a8722ea1.jpg)

![4](https://user-images.githubusercontent.com/40764140/44727039-aa99db80-ab0b-11e8-827a-de7d6e75deb1.jpg)

**Comment by ynFatal** [comment]
2.3.1版本的insertOrUpdateBatch()方法的问题

**Comment by miemieYaho** [comment]
点进实现类里去看源码

**Comment by ynFatal** [comment]
我看了源码了，也测过了

**Comment by ynFatal** [comment]
@miemieYaho 我看了源码了，也测过了

**Comment by ynFatal** [comment]
>@miemieYaho 前辈，您好，能耽误你几分钟吗，你的QueryWrapper构造方法中的参数 T entity 的作用是不是为了获得实体类型的字节码对象。
```
    /**
     * 实体类型
     */
    protected T entity;
    protected MergeSegments expression;
    /**
     * 实体类型
     */
    protected Class<T> entityClass;

    @Override
    public T getEntity() {
        return entity;
    }

    public This setEntity(T entity) {
        Assert.notNull(entity, "entity is not null");
        this.entity = entity;
        this.entityClass = (Class<T>) entity.getClass();
        return typedThis;
    }
```
`this.entityClass = (Class<T>) entity.getClass();`
就这句。

还有个问题，是不是只要我们能通过泛型T拿到运行时期的实体类型的话。这个参数可以去掉？

**Comment by miemieYaho** [comment]
不是,entity用于生成where条件,后期获取的class用于排除搜索字段的功能

ynFatal <notifications@github.com> 于2018年9月2日周日 上午10:09写道：

**Comment by ynFatal** [comment]
@miemieYaho 前辈，我最近几天一直在看你的demo，3.0-RELEASE，我运行了你的demo，对你写的TestTypeHandler有个疑问？请前辈指点一下，谢谢。
添加的时候，有作用；
但是查询的时候不起作用。
我做错了什么吗？
```
==>  Preparing: SELECT id,name,age,email FROM user WHERE id=? AND deleted=0 
==> Parameters: 1(Long)
<==      Total: 1

test2@baomidou.com
```
指点迷津，谢谢前辈

**Comment by miemieYaho** [comment]
select 要生效是要使用 resultMap 的.去 xml 里个 resultmap 然后在`@TableName`注解里指定 resultmap

**Comment by ynFatal** [comment]
@miemieYaho 前辈，谢谢你。搞定了。谢谢

**Comment by ynFatal** [comment]
@miemieYaho 前辈，又要打扰你了，我刚刚看了你的Wrapper模块（3.0-RELEASE各种姿势的那个demo）
就试着测 lambda + excludeColumns 进行排除，发现这两个同时使用的时候QueryWrapper需要加一个参数（new User()）才能使用
```
User one3 = userService.getOne(new QueryWrapper<User>(new User())
                .lambda()
                .excludeColumns(User::getEmail));
```
否则报错
```
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Unable to find entity type, please use method `excludeColumns(Class<T> entityClass, String... excludeColumns)`
```
在前辈写的所有测试中，QueryWrapper都是没有参数的。我想这是需要优化一下还是我逻辑错了。
谢谢前辈指点~

**Comment by miemieYaho** [comment]
excludeColumns 方法目前不完善,请勿使用, 
因为QueryWrapper内部获取不到具体的泛型(参考 List<T>)

**Comment by ynFatal** [comment]
@miemieYaho 前辈，那lambda的其他方法就能正常使用吧？

**Comment by miemieYaho** [comment]
恩

**Comment by miemieYaho** [comment]
除了 lambdaQueryWrapper 的 select 和 excludeColumns会有问题,其他的没问题
