### ISSUE TITLE
QueryWrapper可以支持去重查询,LambdaQueryWrapper不支持

### ISSUE THREAD

**Issue by Kirno7** [baomidou/mybatis-plus#4490]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
    @Override
    public void test1() {
        QueryWrapper<WebUserEntity> wrapper = Wrappers.emptyWrapper();
        wrapper.select("distinct  *");
        for (WebUserEntity o : service.list(wrapper)) {
            LogUtil.json(o);
        }
    }

LambdaQueryWrapper怎么自己拼接select distinct

**Comment by zzzzzyw** [comment]
xml文件 或者 LambdaQueryWrapper#apply 拼接sql 或者直接用注解 @Select("xxx")

**Comment by uncarbon97** [comment]
```
new QueryWrapper<SysUserEntity>()
                .select("DISTINCT xx")
                .lambda()
                .eq()
```
