### ISSUE TITLE
executeBatch中NullPointerException淹没原来真实的报错

### ISSUE THREAD

**Issue by miracle-bean** [baomidou/mybatis-plus#4493]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-extension-3.4.2.jar

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
方法：com.baomidou.mybatisplus.extension.toolkit.SqlHelper#executeBatch(java.lang.Class<?>, org.apache.ibatis.logging.Log, java.util.function.Consumer<org.apache.ibatis.session.SqlSession>)
![image](https://user-images.githubusercontent.com/23690863/167760784-37a9ad15-e696-4e5a-900c-4905ed4d0b54.png)
Objects.requireNonNull抛出空指针，进而淹没了原来真实的报错，会开发调整调整困扰肉

**Comment by miracle-bean** [comment]
更正是：org.mybatis.spring.MyBatisExceptionTranslator#translateExceptionIfPossible
遇到匹配不到的Exception会就返回null，导致真实的报错被淹没
![Uploading image.png…]()

**Comment by miracle-bean** [comment]
![image](https://user-images.githubusercontent.com/23690863/167769319-c77d4ebe-3d1b-4240-bcf8-88a0ea4886d6.png)

**Comment by miemieYaho** [comment]
这是mybatis的类

**Comment by condyRen** [comment]
碰到同样的问题，不知道具体引起错误的原因。希望这个异常的处理再优化下

**Comment by condyRen** [comment]
碰到同样的问题，不知道具体引起错误的原因。希望这个异常的处理再优化下

**Comment by NeonCowboy** [comment]
在3.4.1 版本遇到同样的情况，不过看起来在3.4.3 版本以上解决了这个问题，这个 issue 可以 close 了。
@miemieYaho 
https://github.com/baomidou/mybatis-plus/commit/5382ca0b78bd3369aff634c41b3ca5c53765beaa
