### ISSUE TITLE
多租户情况下@InterceptorIgnore注解如何过滤baseMapper中的方法？

### ISSUE THREAD

**Issue by JackietLee** [baomidou/mybatis-plus#4506]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
代码中使用了baseMapper中的方法，但不知道多租户插件如何对此方法不进行过滤。
新版本多租户插件，能否像老版本的ISqlParserFilter

**Comment by totoro52** [comment]
带上日志描述清晰点，太模糊了，“但不知道多租户插件如何对此方法不进行过滤。” 哪个方法都不说一下嘛

**Comment by JackietLee** [comment]
> 带上日志描述清晰点，太模糊了，“但不知道多租户插件如何对此方法不进行过滤。” 哪个方法都不说一下嘛

比如说我使用了basemapper.insert 方法，但是@InterceptorIgnore没有办法放在basemapper.insert方法上
老版本可以用ISqlParserFilter通过比较statementid，新版本好像已经被移除了
paginationInterceptor.setSqlParserFilter(new ISqlParserFilter() {
            @Override
            public boolean doFilter(MetaObject metaObject) {
                MappedStatement ms = SqlParserHelper.getMappedStatement(metaObject);
                // 对应Mapper或者dao中的方法
                if("com.erbadagang.mybatis.plus.tenant.mapper.UserMapper.insert".equals(ms.getId())){
                    return true;
                }
                return false;
            }
        });

**Comment by totoro52** [comment]
你可以重写多租户插件的beforeQuery方法，也可以重写willIgnoreTenantLine方法，加上你自己的逻辑即可，这里可以拿到你要的方法信息

**Comment by JackietLee** [comment]
> 你可以重写多租户插件的beforeQuery方法，也可以重写willIgnoreTenantLine方法，加上你自己的逻辑即可，这里可以拿到你要的方法信息

谢谢，已经改完了
