### ISSUE TITLE
分页插件自定义sql模糊查询标签解析异常 “%”#{}“%“

### ISSUE THREAD

**Issue by caidingnu** [baomidou/mybatis-plus#4510]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页插件模糊查询

### 重现步骤(如果有就写完整)
Mapper：
    Page<User> list(@Param("page") IPage<User> page, @Param("name") String name);
Xml：
  select
           <include refid="Base_Column_List"/>
           from user where name like "%"#{name}"%"

### 报错信息
optimize this sql to a count sql has exception, sql:"select
            
        id, name, time, version, swit, create_time, update_time
     
           from user where name like "%"?"%"", exception:
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "?" "?"
    at line 5, column 41.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "ESCAPE"
    "GROUP"
    "HAVING"
    "START"
    "["
    "^"
    "|"
    <EOF>

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException

**Comment by caidingnu** [comment]
邮件已经收到，谢谢！
