### ISSUE TITLE
执行分析插件SqlExplainInterceptor能否单独使用呢？

### ISSUE THREAD

**Issue by li395092734** [baomidou/mybatis-plus#4511]
想问一下，执行分析插件SqlExplainInterceptor，能否单独拿出来使用呢？目前了解到的是，做一定的SQL过滤的功能。
我其实想使用这个插件，也就是预执行一些SQL。获取EXPLAIN中的执行结果的。

**Comment by qmdx** [comment]
复制出来用就行了
