### ISSUE TITLE
【咨询】自定义查询结果映射+对象嵌套

### ISSUE THREAD

**Issue by xinbimingjingtai** [baomidou/mybatis-plus#4512]
### 当前使用版本(必填,否则不予处理)
3.3.2

**在自定义关联查询时，能否满足以下条件:**

- 对于`Order`对象, 无需显示指定列与字段的关联，能够自动进行映射, 且`*`表示所有列
- 对`User`和`Product`对象, 可以使用下列任一方式

> 1. 使用XML等自定义列与字段的映射, 在`Mapper`方法上用注解使用此前定义的映射
> 2. 使用`.`等作为嵌套字段的分隔符, 如`user.id`, `products.id`

- 支持配置`mapUnderscoreToCamelCase`
- 当且仅当嵌套对象存在非空列，自动创建嵌套对象

**数据结构:**

```
public class Order {
    private Integer id;
    private String orderNo;
    private BigDecimal amount;
    private Integer status;
    private User user;
    private List<Product> products;
}

public class User {
    private Integer id;
    private String name;
    private String avatar;
    private Date birthday;
}

public class Product {
    private Integer id;
    private String title;
    private String image;
    private String desc;
}
```

**Comment by totoro52** [comment]
你这个需求可以参考下JPA

**Comment by xinbimingjingtai** [comment]
额, 后面测试了一下, 可以使用`.`作为嵌套字段的分隔符, `MyBatis`实现了.
