### ISSUE TITLE
Java父类和子类报 more than one TableId

### ISSUE THREAD

**Issue by endypark** [baomidou/mybatis-plus#4513]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
父类 
A{
  @TableId
  private Long aId; 
  //共10个字段
}
子类
B extends A{
  @TableId
  private Long bId;
  //包括A的10个字段
  //另外3个字段
}

C extends A{
   //类似B
}

D extends A{
  //类似B
}

Will throw : more than one

### 重现步骤(如果有就写完整)
启动时就会报错

### 报错信息
@TableId can't more than one in Class  B
@TableId can't more than one in Class  C
@TableId can't more than one in Class  D

**Comment by endypark** [comment]
我擦，直接就close了。。。

**Comment by endypark** [comment]
严重鄙视

**Comment by endypark** [comment]
一个字的解释没有

**Comment by miemieYaho** [comment]
解释什么?@TableId can't more than one in Class B告诉你这么清楚还需要解释什么?
