### ISSUE TITLE
mybatis-plus.type-enums-package 特殊场景下不生效

### ISSUE THREAD

**Issue by letian-tang** [baomidou/mybatis-plus#4514]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.2没问题，升级到3.5.1 有问题
MybatisSqlSessionFactoryBean
3.5.1版本因为修改这段代码的顺序
![image](https://user-images.githubusercontent.com/9101213/169459787-c8bd43fa-be82-40c4-8ddd-14cade773dd7.png)

### 系统启动的时候，因为配置了resultMap，提前解析这段，给ImState 默认EnumTypeHandler
![image](https://user-images.githubusercontent.com/9101213/169461605-e8b5752c-f160-4e02-9743-081070d29c28.png)

![image](https://user-images.githubusercontent.com/9101213/169460266-063597a2-f6ba-45df-9465-cd296368c8ba.png)

包扫描 mybatis-plus.type-enums-package ，之后执行，就无法给ImState正确的MybatisEnumTypeHandler类型

**Comment by Dlinw** [comment]
我刚刚才看到这个合并，我现在也有获取到错误枚举处理器的问题。

**Comment by Dlinw** [comment]
![image](https://user-images.githubusercontent.com/45334447/169464020-2e76818e-114b-43d4-8cb0-523189c2cab4.png)

**Comment by Dlinw** [comment]
这个提交会导致枚举处理器失效。回退到3.5.0就没有问题了。

另外：尝试了多个版本，在TableField中设置typeHandler = MybatisEnumTypeHandler 后也会导致找不到正确枚举处理器。

**Comment by miemieYaho** [comment]
近期会发版,发版后就无此问题了
