### ISSUE TITLE
Mybats-plus + Postgresql 提取公共字段出现的问题

### ISSUE THREAD

**Issue by esbug** [baomidou/mybatis-plus#4518]
### 1：下面是我的BaseEntity场景定义

<img src = 'https://s3.bmp.ovh/imgs/2022/05/24/f5b0bba7b8f0834c.png' />

### 2：下面是我的user类（userId是uuid，对外提供的，id是主键自增）
<img src = 'https://s3.bmp.ovh/imgs/2022/05/24/ecf4495ebe3215aa.png' />

### 问题1：我使用mybatis-plus的简单查询( 例如：selectById)，会抛出id字段不存在的一个异常。猜测是没有识别到BaseEntity
<img src = 'https://s3.bmp.ovh/imgs/2022/05/24/32a4c58716802367.png' />

<img src = 'https://s3.bmp.ovh/imgs/2022/05/24/f11728892bab04db.png' />

### 问题2：我改成使用自定义sql的方式，根据postgresql，需要带上双引号才能识别字段，myabtis-plus并没有帮忙处理这个，以及和mysql不同的是引用参数从 # 变成了 $
<img src = 'https://s3.bmp.ovh/imgs/2022/05/24/546fabdb67ac98c7.png' />

### 问题3：使用自定义SQl查询出来的结果如下
数据库如下：
<a href="https://imgtu.com/i/XCDfsI"><img src="https://s1.ax1x.com/2022/05/24/XCDfsI.png" alt="XCDfsI.png" border="0" /></a>
查询结果如下：
<a href="https://imgtu.com/i/XCDjLq"><img src="https://s1.ax1x.com/2022/05/24/XCDjLq.png" alt="XCDjLq.png" border="0" /></a>

**Comment by qmdx** [comment]
1，字段 id 不存在指的是你的数据库 id 吧
2，自定义 SQL 自己处理关键词转义等逻辑
3，查询部分代码请给出来

**Comment by esbug** [comment]
> 1，字段 id 不存在指的是你的数据库 id 吧 2，自定义 SQL 自己处理关键词转义等逻辑 3，查询部分代码请给出来

这是我的BaseEntity
```java
package com.txys.system.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import lombok.Data;

@Data
public abstract class BaseEntity<T> extends Model<BaseEntity<T>> {

    @TableField(value = "createdBy")
    private String createdBy;

    @TableField(value = "createdAt")
    private String createdAt;

    @TableField(value = "updatedAt")
    private String updatedAt;

    @TableField(value = "updatedBy")
    private String updatedBy;

    @TableField(value = "deletedAt")
    private String deletedAt;
}

```

这是我的SystemUser表
```java
package com.txys.system.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;

@TableName("\"SystemUser\"")
@Data
public class SystemUser extends BaseEntity<SystemUser> implements Serializable {

    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    @TableField(value = "username")
    private String username;

    @TableField(value = "password")
    private String password;
}
```

###1、我现在的问题是：调用selectById，
```
SELECT id,username,password,createdBy,createdAt,updatedAt,updatedBy,deletedAt FROM "SystemUser" WHERE id=?
```
查询时会自动加上父类继承的字段。之前不加上是因为exsit=false的原因。
但是查询结果映射的时候，会报错：

```Error querying database.  Cause: org.postgresql.util.PSQLException: 错误: 字段 "createdby" 不存在```

也就是说：映射找不到继承的父类公共字段

**Comment by miemieYaho** [comment]
这是驱动报错找不到字段,和mp无关
