### ISSUE TITLE
fastjson 1.2.80及以下存在新的风险需要更新

### ISSUE THREAD

**Issue by michealzh** [baomidou/mybatis-plus#4519]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

https://github.com/alibaba/fastjson/wiki/security_update_20220523?spm=5176.b45069876.sas.30.3f282b72UnBdfA

**Comment by miemieYaho** [comment]
没用它
