### ISSUE TITLE
雪花算法，并发测试下大量重复

### ISSUE THREAD

**Issue by yujunchengg** [baomidou/mybatis-plus#4520]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用idea将服务做集群，开了3个节点，使用jmeter测试出现大量重复，
IdWorker.initSequence(workId,dataCenterId);这段代码断点跟进去也是起效了的

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/36986915/169982709-88538a9e-671c-401f-8c34-c21e9665999b.png)

**Comment by miemieYaho** [comment]
你要是workId,dataCenterId都一样那id就会重复

**Comment by yujunchengg** [comment]
我设置为不一样的都不行，单机版本测试都有重复的

**Comment by miemieYaho** [comment]
你不妨好好检查一下你的测试流程和参数

**Comment by qmdx** [comment]
请给出你的测试 代码

**Comment by HEXDude** [comment]
猜测一下,MybatisPlus的雪花算法的生成主要依赖网卡的Mac地址和JVM PID.也许考虑可以将几个服务隔离试试.

**Comment by fwk1010** [comment]
一样的问题，但我这边不好找测试用例

**Comment by qmdx** [comment]
同一台机器多个实例，请控制下每个实例的机器人ID的分配问题，全局配置可以设置
