### ISSUE TITLE
自定义typeHandle 为泛型时，有一定几率执行到错误的typeHandle 

### ISSUE THREAD

**Issue by wweiaixingxing** [baomidou/mybatis-plus#4521]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

    @TableField(typeHandler = ImagesInfoHandler.class)
    private List<ImagesInfo> imagesInfo;

   
    @TableField(typeHandler = LongArrayTypeHandler.class)
    private List<Long> ids;

### 重现步骤(如果有就写完整)

1.代码实现逻辑
![image](https://user-images.githubusercontent.com/106131095/170174951-24805bf4-5046-4ad8-b950-4299b13629e0.png)
![image](https://user-images.githubusercontent.com/106131095/170174986-38ba22a0-c4ed-4211-9b00-cdfc758bd6a8.png)
![image](https://user-images.githubusercontent.com/106131095/170175031-7882e502-800f-403f-9a11-96c32da7a974.png)

### 报错信息
执行到错误typeHandle  导致反序列化失败

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/170176753-8da3bb64-48b6-4efa-86eb-74f4b37d7a58.png)

**Comment by weitangli** [comment]
试一下这样？
```
@TableField(typeHandler = JacksonTypeHandler.class)
private ImagesInfo[] imagesInfo;
```

**Comment by weitangli** [comment]
你的问题应该是`JsonUtil.jsonToObject`封装不好导致的。

**Comment by wweiaixingxing** [comment]
谢谢，这样是可以的，我自己找到问题了，是mybatis 的bug，mybatis  注册  TypeHandlerRegistry 是 应为类型和实例类 都是一样的，所以找错了TypeHandle ，
![image](https://user-images.githubusercontent.com/106131095/171077078-bdb899ee-29e7-4ba4-bcac-3117480e92d6.png)
指定一下这个就可以，但是@MappedTypes({ Long.class}) 就可以，但是又会引起自定义sql 执行是 不能找到对应的TypeHandle
这个bug 根本原因是mybatis 在支持 List<T> 泛型是，反序列化是 一个序列是T ，另一个是List ，所以出错，mybatis 官网修复只修复了一种 对应bug https://github.com/mybatis/mybatis-3/pull/1887  https://github.com/mybatis/mybatis-3/issues/1445

**Comment by weitangli** [comment]
不是很理解，或者你在自定义查询上使用`@ResultMap`试试？
例如：
```java
@Mapper
public interface UserMapper extends BaseMapper<User> {

    @ResultMap("mybatis-plus_User")
    @Select("select ........")
    User getByXXX(@Param(Constants.WRAPPER) Wrapper<User> queryWrapper);
}
```
