### ISSUE TITLE
有没有考虑过添加多表查询的功能

### ISSUE THREAD

**Issue by rainLeelzr** [baomidou/mybatis-plus#453]
请问有没有考虑过添加多表查询的功能？最简单的left join 也行
例如
select xxx 
from A
left join B using x1
where a.x2 = b.x2
and b.x3 in (1,2,3)
主要是不想写where那堆动态条件，特别是in条件，要用foreach标签写一大堆东西

**Comment by miemieYaho** [comment]
没有
