### ISSUE TITLE
逻辑删除不生效

### ISSUE THREAD

**Issue by duoaipan** [baomidou/mybatis-plus#454]
当前使用版本(必须填写清楚，否则不予处理)
3.0-RC3

该问题是怎么引起的？
重现步骤
一开始在.yml文件中配置参数如下：
mybatis-plus:
global-config:
#逻辑删除配置
logic-delete-value: 1
logic-not-delete-value: 0
sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
后根据提示将sql-injecto从配置中删除改为Bean注入：
@bean
public GlobalConfig globalConfiguration() {
GlobalConfig conf = new GlobalConfig();
conf.setSqlInjector(new LogicSqlInjector());
return conf;
}
且已在相应实体增加@TableLogic注解：
/**
* 状态：0生效，1冻结
*/
@TableLogic
private Integer status;

报错信息
调用removeById()方法后数据从数据库中物理删除，并没有逻辑删除，并且select方法也没有自动拼接未删除条件。

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples
使用最新版,参考官方demo
