### ISSUE TITLE
MybatisX 文档地址404

### ISSUE THREAD

**Issue by binaryjerry** [baomidou/mybatis-plus#4549]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

Mybatis-X官网文档找不到
https://mp.baomidou.com/guide/mybatisx-idea-plugin.html

**Comment by huayanYu** [comment]
https://baomidou.com/pages/ba5b24/#%E5%B8%B8%E8%A7%81%E9%97%AE%E7%AD%94
