### ISSUE TITLE
mybatisplus @TableField不起作用

### ISSUE THREAD

**Issue by kibear** [baomidou/mybatis-plus#455]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
在mapper中使用自定义的方法：
bean使用驼峰法命名，表字段使用下划线，查询的时候bean的属性不能设置，加上@TableField还是不能设置。但是当我把mapUnderscoreToCamelCase这个设置成true以后就可以了；使用basemapper继承下来的方法也可以；当然使用mybatis的resultmap来做映射也是可以的。
难道说@TableField只有插入的时候能映射，读取的时候就不能映射，但是用basemapper里面的方法也可以映射的。

### 重现步骤
表：admin
id | user_name | name
1      root           admin
//  config
@Bean
public SqlSessionFactory sqlSessionFactory(DataSource dataSource, GlobalConfiguration globalConfiguration)
			throws Exception {
		MybatisSqlSessionFactoryBean sessionFactoryBean = new MybatisSqlSessionFactoryBean();
		sessionFactoryBean.setDataSource(dataSource);
		sessionFactoryBean.setGlobalConfig(globalConfiguration);
		PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
		sessionFactoryBean.setMapperLocations(resolver.getResources("classpath:mapper/*Mapper.xml"));
		sessionFactoryBean.setTypeAliasesPackage("com.kibear.domain");
		return sessionFactoryBean.getObject();
	}

@Bean
public GlobalConfiguration globalConfiguration() {
		GlobalConfiguration globalConfiguration = new GlobalConfiguration();
		globalConfiguration.setDbColumnUnderline(true);
		globalConfiguration.setIdType(0);
		return globalConfiguration;
	}
// bean
@Data
public class Admin {
	
	private Integer id;
	@TableField("user_name")
	private String userName;
	private String name;

}
// mapper
public interface AdminMapper extends BaseMapper<Admin> {
	
	@Select("select id, user_name, name from admin where user_name = #{userName}")
	Admin selectByUserName(@Param("userName") String userName);

}
//
测试：
1. mapper自定义方法
Admin admin = adminMapper.selectByUserName("root");
System.out.println(admin);// Admin(id=1, userName=null, name=name)

2. basemapper继承的方法
Admin query = new Admin();
query.setUserName("root");
Admin admin = adminMapper.selectOne(query);//.selectByUserName("root");
System.out.println(admin);// Admin(id=1, userName=root, name=name)

当我把MybatisConfiguration中mapUnderscoreToCamelCase设置成true以后就可以了，但是如果bean命名和表字段不是驼峰和下划线对应的时候，不是就不行了。

### 报错信息
无

**Comment by miemieYaho** [comment]
2.x版本上是这样的,mybatis的驼峰配置要和mp的驼峰配置布尔值保持一致.
