### ISSUE TITLE
是否可以直接指定分页offset

### ISSUE THREAD

**Issue by zjline** [baomidou/mybatis-plus#4555]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
是否可以直接指定分页的起始位置？现在的分页都是传入page、size，然后自动计算offset。现在想直接指定offset。没有找到现成，想问一下是否有，有就可以直接用，省得改造

**Comment by miemieYaho** [comment]
page、size哪里不满足你了?

**Comment by zjline** [comment]
> 



> page、size哪里不满足你了?

有个场景，第1页5条，第2页10条

**Comment by miemieYaho** [comment]
page-size : 1-5 和 2-10 不行?

**Comment by zjline** [comment]
> page-size : 1-5 和 2-10 不行?

2-10数据是从第11条开始，6到10这5条数据就没了。场景就是类似于不均匀分页，第一页展示1~5条数据，第二页展示6~15条数据

**Comment by zjline** [comment]
> > page-size : 1-5 和 2-10 不行?
> 
> 2-10数据是从第11条开始，6到10这5条数据就没了。场景就是类似于不均匀分页，第一页展示1至5条数据，第二页展示6至15条数据

**Comment by alanland** [comment]
你可以试试  
```java
this.BaseMapper.selectList(new LambdaQueryWrapper<XXX>().last("limit 2 offset 4"))
```
毕竟不均匀分页不是一个常见的设计模式，Page 和 Size 的设计更加直观易用。

**Comment by zjline** [comment]
> 你可以试试
> 
> ```java
> this.BaseMapper.selectList(new LambdaQueryWrapper<XXX>().last("limit 2 offset 4"))
> ```
> 
> 毕竟不均匀分页不是一个常见的设计模式，Page 和 Size 的设计更加直观易用。

好吧
