### ISSUE TITLE
@TableName和全局表前缀配置之后生成的sql中还是使用类名作为表名

### ISSUE THREAD

**Issue by b1gdea1** [baomidou/mybatis-plus#4558]
### 当前使用版本(必填,否则不予处理)
3.5.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/59244373/171974405-8c860986-6a0d-4f3d-8135-29ea0e3f9410.png)

**Comment by miemieYaho** [comment]
有复现demo么

**Comment by b1gdea1** [comment]
下午的时候仔细检查了，是我自己写的sql里面指定了表名，难怪网上没有我这样的问题。my bad
