### ISSUE TITLE
LogicSqlInjector不起作用

### ISSUE THREAD

**Issue by fullstar** [baomidou/mybatis-plus#456]
### 使用环境
-  版本 3.0 RELEASE 
- SpringBoot 2.0.3
- 字段上有加@TableLogic注解

### 发现逻辑删除不起作用
经调试发现下面这行代码遍历每个字段时, 每次都会重新赋值, 导致最终结果tableInfo的LogicDelete标识变为true后又被重新覆盖为false
`
tableInfo.setLogicDelete(this.initLogicDelete(dbConfig, field));
`

**Comment by miemieYaho** [comment]
3.0.1版本上已修复
