### ISSUE TITLE
【orderby相关建议优化】调用orderby方法时，实际业务场景中condition=false时，isAsc参数可能为null

### ISSUE THREAD

**Issue by MadaraFsl** [baomidou/mybatis-plus#4561]
### 当前使用版本(必填,否则不予处理)

3.4.0，3.0分支源码没有相关优化代码

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

业务中前端可能不排序导致condition=false，所以个人代码中接受Boolean类型的isAsc可能为null，调用方法会报错
queryWrapper.orderBy(false, null, "name");

### 重现步骤(如果有就写完整)

自己想到的相关方案
![Uploading image.png…]()

### 报错信息

参数 boolean isAsc 不能为null，从使用者角度只是建议优化，个人也可以解决该问题

**Comment by MadaraFsl** [comment]
图片补充 
![image](https://user-images.githubusercontent.com/38450923/172281992-c5ebe144-221c-4149-8de8-c45413f12dea.png)

**Comment by zhushizhan** [comment]
我也遇到这个问题了，本来就会有这种需求，个人感觉方法应该直接不执行，而不是在这个地方改属于强制必须选择一种才行

**Comment by miemieYaho** [comment]
自行处理

**Comment by zhushizhan** [comment]
这应该是因为使用了 Arrays.list() 导致的空指针吧
