### ISSUE TITLE
传入的参数含有 英文逗号 时，自动拼接生成的 sql 错误

### ISSUE THREAD

**Issue by HeSasa** [baomidou/mybatis-plus#4566]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/32067974/172570246-a14b724c-c911-4b02-a0de-ee3143ea1c3f.png)

原本 'vul_desc'字段输入的参数是 
IBM WebSphere Application Server 7.0, 8.0, 8.5...
一遇到英文逗号就将 逗号后面的信息给下一个参数传进去了， 导致生成的sql错误

**Comment by miemieYaho** [comment]
mp不参与执行sql
