### ISSUE TITLE
LambdaQueryWrapper的orderBy方法是否支持直接写SQL，实现自定义排序

### ISSUE THREAD

**Issue by liunancun** [baomidou/mybatis-plus#4573]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用LambdaQueryWrapper之后，不支持复杂排序
比如 order by FIELD(status, 1, 0, 2, 3) ASC, start_time desc

### 报错信息
方法不支持

**Comment by uncarbon97** [comment]
```
new QueryWrapper<SysUserEntity>()
                .orderBy()
                .lambda()
                .eq()
```
