### ISSUE TITLE
v3.5.2逻辑删除后，查询无效，依然可以查询出来

### ISSUE THREAD

**Issue by xiesangzi** [baomidou/mybatis-plus#4575]
v3.5.2逻辑删除后，查询无效，依然可以查询出来

**Comment by xiesangzi** [comment]
查询逻辑删除条件没有自动加上

**Comment by miemieYaho** [comment]
比如?

**Comment by starriesWEB** [comment]
删除的时候是正常逻辑删除的，用mapp分页查询的时候没有拼接上逻辑删除字段,mapper.xml里面表名有个\`user\`
`baseMapper.getUserPage(page, userPageForm)`

**Comment by fengdh23** [comment]
> 删除的时候是正常逻辑删除的，用mapp分页查询的时候没有拼接上逻辑删除字段,mapper.xml里面表名有个`user` `baseMapper.getUserPage(page, userPageForm)`

现在有答复吗。我也遇到这个问题

**Comment by MurphyZX** [comment]
> 删除的时候是正常逻辑删除的，用mapp分页查询的时候没有拼接上逻辑删除字段,mapper.xml里面表名有个`user` `baseMapper.getUserPage(page, userPageForm)`

+1 遇到同样的问题
