### ISSUE TITLE
使用多租户功能分页查询变慢

### ISSUE THREAD

**Issue by 1602908128** [baomidou/mybatis-plus#4576]
### 当前使用版本(必填,否则不予处理)

3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

开启多租户插件后分页查询变慢

### 重现步骤(如果有就写完整)

分页插件用的pagehelper，开启多租户插件后分页查询变慢，不使用分页或者关闭多租户插件恢复正常

**Comment by qmdx** [comment]
你这个 范围太大了无具体指标无法处理， 租户需要 sql 解析会损耗一些性能的

**Comment by qmdx** [comment]
你这个 范围太大了无具体优化点指标参数无法处理， 租户需要 sql 解析会损耗一些性能的
