### ISSUE TITLE
多租户插件与pagehelper冲突

### ISSUE THREAD

**Issue by wangli-sss** [baomidou/mybatis-plus#4577]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
多租户插件在sql语句解析的时候会将sql语句格式化，刚开始是offset在前面，limit在后，格式化后limit在前面offset在后面
导致的结果是第三页以后的分页查询条数一直增加

### 重现步骤(如果有就写完整)
引入最新版本的pagehelper和最新版本的mp，设置多租户，分页查询用pagehelper就能重现，数据库pg

### 报错信息

original SQL: select dict_id, dict_name, dict_type, status, create_by, create_time, remark
		from sys_dict_type OFFSET ? LIMIT ?
SQL to parse, SQL: select dict_id, dict_name, dict_type, status, create_by, create_time, remark
		from sys_dict_type OFFSET ? LIMIT ?
parse the finished SQL: SELECT dict_id, dict_name, dict_type, status, create_by, create_time, remark FROM sys_dict_type LIMIT ? OFFSET ?
==>  Preparing: SELECT dict_id, dict_name, dict_type, status, create_by, create_time, remark FROM sys_dict_type LIMIT ? OFFSET ?
==> Parameters: 20(Long), 10(Integer)

**Comment by miemieYaho** [comment]
把分页插件放后面

**Comment by wangli-sss** [comment]
pom文件里分页插件放后面？

**Comment by wangli-sss** [comment]
还是一样

**Comment by miemieYaho** [comment]
mybatis插件执行顺序里放后面

**Comment by qmdx** [comment]
请用 mp 内置分页插件，减少不必要的麻烦
