### ISSUE TITLE
TableFieldInfo能扩展吗

### ISSUE THREAD

**Issue by chenfeiwu** [baomidou/mybatis-plus#4579]
我需要针对不同字段进行不同的格式化，目前只有全局格式化，真希望这部分能根据每个字段自定义格式化，或者TableFieldInfo的value属性支持EL表达式
![image](https://user-images.githubusercontent.com/14910761/173479373-a5fab1a2-4ae6-496e-b2b0-54111d5e90c5.png)

**Comment by qmdx** [comment]
单个字段你可以注解 TableField("字段名称")
