### ISSUE TITLE
selectBatchIds 报错 

### ISSUE THREAD

**Issue by zhigzyan** [baomidou/mybatis-plus#458]
### 当前使用版本(必须填写清楚，否则不予处理)

 <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatisplus-spring-boot-starter</artifactId>
                <version>1.0.5</version>
            </dependency>
<dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus</artifactId>
                <version>2.1.8</version>
            </dependency>

2.1.8切换过3.0-RELEASE，问题依然存在

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

该问题是加入逻辑删除以后存在的，去掉逻辑删除，正常。

### 重现步骤

1.加入逻辑删除
2.使用 selectBatchIds

### 报错信息

org.apache.ibatis.binding.BindingException: Parameter 'list' not found. Available parameters are [coll, param1]

**Comment by miemieYaho** [comment]
- 你使用的 mybatisplus-spring-boot-starter 早已不维护了,请使用 mybatis-plus-boot-starter
- mp的2.x 和3.x 版本差异很大,不知道你到底想用哪一个
- 3.x 的最新稳定版是3.0.1

**Comment by fujialong** [comment]
版本3.0
分页的这个类PaginationInterceptor,下载下来的源码打开的时候提示:library source does not match the bytecode ,想问下是不是我的问题

**Comment by miemieYaho** [comment]
@fujialong 不是
