### ISSUE TITLE
api not support ilke

### ISSUE THREAD

**Issue by guandatawangjialin** [baomidou/mybatis-plus#4580]
SELECT COUNT(1) FROM t_ds_process_definition pd LEFT JOIN t_ds_schedules s ON pd.id = s.process_definition_id JOIN t_ds_user u ON pd.user_id = u.id WHERE pd.project_id = ? AND pd.process_type = ? AND pd.is_del IS FALSE AND (u.user_name LIKE concat('%', ?, '%') OR u.name LIKE concat('%', ?, '%') OR pd.description LIKE concat('%', ?, '%') OR pd.name LIKE concat('%', ?, '%')) 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/102361568/173485341-f85491d0-4596-4799-b3f3-7464b5ce8955.png">

**Comment by guandatawangjialin** [comment]
![Uploading image.png…]()

**Comment by huayanYu** [comment]
请按照格式提交
