### ISSUE TITLE
兼容驼峰和下划线

### ISSUE THREAD

**Issue by lishaopeng221** [baomidou/mybatis-plus#4583]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
整合多人写的代码，有的是下划线的有的是驼峰的，弄到一个项目里面会报错，
希望有一个配置，可以设置那些表使用驼峰，那些表使用下划线

**Comment by GFTXWD** [comment]
你这算好的了，我这个项目，mysql为主导，SqlServer为辅助，SqlServer还是动态读取表里面数据源获取的sql session，mysql是我们java主用，所以是遵循驼峰，SqlServer是.net的老库，老库字段是大小写，下划线，驼峰混用的，恰好今天尝试在这个屎山引入mybatis plus遇到了你这种问题，我的解决方案是在数据库实体使用mybatis plus的@TableField 和 jackson的 @JsonProperty，希望对你有帮助

**Comment by qmdx** [comment]
注解解决 https://baomidou.com/pages/223848/

**Comment by qchenn** [comment]
> 注解解决 https://baomidou.com/pages/223848/

没注解表示是否开启驼峰啊

**Comment by qchenn** [comment]
> 注解解决 https://baomidou.com/pages/223848/

由于老代码有下划线，集成MB后为了兼容关闭驼峰了，但新代码用驼峰了，有什么方法兼容吗
