### ISSUE TITLE
自动填充功能对自定义的参数为集合类型的方法无效

### ISSUE THREAD

**Issue by 2YSP** [baomidou/mybatis-plus#4585]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我继承了AbstractMethod添加了一个批量插入的方法，然后自动填充字段的功能就失效了，debug发现是
com.baomidou.mybatisplus.core.MybatisParameterHandler#setParameters的方法有问题，parameterObject属性是有值的，但是条件判断进入了value = this.boundSql.getAdditionalParameter(propertyName);，结果返回了null。

### 重现步骤(如果有就写完整)
我的代码
`public interface BaseMapperPlus<T extends BusinessBaseEntity> extends BaseMapper<T> {

    /**
     * 批量插入
     *
     * @param list
     * @return
     */
    int insertBatch(@Param("list") List<T> list);
}`

**Comment by miemieYaho** [comment]
最新版也有问题?

**Comment by qmdx** [comment]
请使用最新版本测试，依然存在该问题请打开ISSUE

**Comment by 2YSP** [comment]
> 最新版也有问题?

还没试，因为mybatis-plus版本被封装到了公司基础框架里了，后面在入参前手动填充字段解决了这个问题。
