### ISSUE TITLE
需要添加@param使参数生效

### ISSUE THREAD

**Issue by wanghuaqun** [baomidou/mybatis-plus#4589]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis，mybatis-plus共存。原有项目引入mybatis 3.5版本，此时无需使用@param
引入mybatis-plus后旧的写法需要添加@param

### 报错信息
入参找不到get方法

**Comment by miemieYaho** [comment]
检查 mybatis 版本冲突

**Comment by wanghuaqun** [comment]
您好：
     mybatis  应该要什么版本。由于某些原因我可能无法修改mybatis版本，mybatis ***@***.***注解了，目前我使用的版本是3.5.6已经是比较新的版本了



***@***.***
 
发件人： miemieYaho
发送时间： 2022-06-15 14:52
收件人： baomidou/mybatis-plus
抄送： wanghuaqun; Author
主题： Re: [baomidou/mybatis-plus] ***@***.***使参数生效 (Issue #4589)
检查 mybatis 版本冲突

**Comment by miemieYaho** [comment]
mp 依赖的mybatis版本支持不使用`@param`,检查你的jar版本依赖冲突导致使用了低版本的mybatis

**Comment by qmdx** [comment]
未反馈
