### ISSUE TITLE
关于 MyBatis Plus 与数据库表

### ISSUE THREAD

**Issue by laiyy0728** [baomidou/mybatis-plus#459]
请问一下当前版本的 MyBatis Plus 是否支持根据 @TableName、@TableId、@TableField 自动创建数据库表？ 如果支持，请问改如何配置？

**Comment by qmdx** [comment]
不支持有这种中间件 https://flywaydb.org/

**Comment by GreatGarlic** [comment]
@qmdx 用flyway有启动顺序问题，请问如何优雅解决？

**Comment by GreatGarlic** [comment]
@tomoya92 一般情况下，如果你没有在使用@PostConstruct注解的函数中调用mybatis plus 的dao，就不会出现加载顺序的问题，flyway默认是最先加载的，你看下还有什么影响了启动顺序

**Comment by tomoya92** [comment]
@GreatGarlic 从昨天折腾到今天，找到了可能影响的地方

1. shiro的配置类
2. 实现CommandLineRunner接口的类在启动的时候优先级也是很高的

我项目里目前就发现了这两个地方有影响，不过它们有一个共同点，都调用了mybatisplus 的dao了

另外，
spring注解中的 `@AutoConfigureAfter` 貌似没有用，我在shiroConfig类上加上了 `@AutoConfigureAfter(MyBatisPlusConfig.class)` 启动还是报错，shiro调用了mybatis plus 的dao拿数据报错

求大佬指点

**Comment by GreatGarlic** [comment]
@tomoya92 shiro在程序启动的时候就会调用dao吗？

**Comment by tomoya92** [comment]
@GreatGarlic 是的，要读取数据库里的权限配置信息

**Comment by tomoya92** [comment]
@GreatGarlic 没有这个bean flywayInitializer ，不过这个问题我已经解决了，没用springboot自动配置的flyway，我自己写的一个flyway的配置，然后指定mybatisplusconfig依赖于flywayconfig就没问题了

谢谢大佬

**Comment by GreatGarlic** [comment]
@tomoya92 可以的
