### ISSUE TITLE
使用clickhouse时, 无法通过指定用户去访问

### ISSUE THREAD

**Issue by TheXs** [baomidou/mybatis-plus#4591]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用springboot继承mybatis与mybatis-plus, 底层dataSource为clickhouse. 调用查询发现sql执行错误, dataSource是使用'default'(clickhouse默认用户)进行查询的, 而非项目中设置的username和password

### 报错信息
DB::Exception: default: Authentication failed, 期待是DB::Exception: username: Authentication failed

谢谢回复！

**Comment by miemieYaho** [comment]
你应该找 dataSource 或者 dbdriver
