### ISSUE TITLE
为什么不在IService类上增加@Indexed注解service的加载效率？

### ISSUE THREAD

**Issue by ghost** [baomidou/mybatis-plus#4593]
![image](https://user-images.githubusercontent.com/50005644/173994659-f37d044a-dfc1-473f-8066-a298ac599615.png)

**Comment by ghost** [comment]
以及Mapper类上增加@indexed，因为很多项目中都继承、实现了Iservice以及Mapper，并且有很多类

**Comment by ghost** [comment]
发现问题的版本：3.5.1，然后去看最新的mp 4.0版本发现还是没有。有大佬给解释下吗

**Comment by miemieYaho** [comment]
你愿意加就自己加
