### ISSUE TITLE
INSERT_UPDATE失效

### ISSUE THREAD

**Issue by sky00000000** [baomidou/mybatis-plus#4594]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`this.strictUpdateFill(metaObject, "updUpdateTime", LocalDateTime::now, LocalDateTime.class);
@TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updUpdateTime;`
该方式只能初始化时自动填充数据，后面由于数据不为空无法更新时间
`if (metaObject.getValue(fieldName) == null) {
            Object obj = fieldVal.get();
            if (Objects.nonNull(obj)) {
                metaObject.setValue(fieldName, obj);
            }
        }`
自动填充如果为UPDATE或者INSERT_UPDATE应该是能够支持每次都刷新该属性值

**Comment by miemieYaho** [comment]
这是默认规则,你觉得不好你可以重写对应的method
