### ISSUE TITLE
Update操作加入用Map参数生成where语句

### ISSUE THREAD

**Issue by superniubi** [baomidou/mybatis-plus#4603]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如果可以用Map参数的话在某些场景下更加方便，不用进行wrapper和map之间的转化，比如要将where的字段参数传递给上下游服务。

**Comment by miemieYaho** [comment]
wrapper.allEq
