### ISSUE TITLE
JSON字段分页查询出错

### ISSUE THREAD

**Issue by btbox** [baomidou/mybatis-plus#4605]
版本：3.5.1

MySQL字段是 json字段，分页查询的时候出错

![image](https://user-images.githubusercontent.com/43517569/175191691-7b91e4d9-18e1-4fd9-8d5a-af1707ad453b.png)

![image](https://user-images.githubusercontent.com/43517569/175191766-952b635b-392d-4e20-81a9-8a9014f7d345.png)

![image](https://user-images.githubusercontent.com/43517569/175191939-5021d52d-2045-4b95-b17f-2683b4772a5e.png)

# 报错信息

Error instantiating class com.ht.mediacenter.work.chat.entity.MediaTaskImGroupMessage with invalid types (String,String,String,String,Integer,Integer,JSONObject,String,Date,String,Date) or values (1539061596989444097,e9ca23d68d884d4ebb19d07889727dae,1,null,4,0,{"fileName": "", "filePath": "", "fileSize": 96545798, "fileSuffix": "mp4"},admin,Tue Jun 21 09:44:14 CST 2022,null,null). Cause: java.lang.IllegalArgumentException: argument type mismatch

**Comment by miemieYaho** [comment]
代码呢?

**Comment by btbox** [comment]
@miemieYaho 
![image](https://user-images.githubusercontent.com/43517569/175231649-1376e378-0621-4426-a0cd-74b4c18e04f9.png)

**Comment by miemieYaho** [comment]
jsontypehandler是认的数据库字段类型为 varchar

**Comment by btbox** [comment]
@miemieYaho 那我数据库字段为json应该如何操作呢

**Comment by miemieYaho** [comment]
自己写typehandler

**Comment by qmdx** [comment]
up
