### ISSUE TITLE
3.4.3.4版本removeById有bug

### ISSUE THREAD

**Issue by john1337** [baomidou/mybatis-plus#4606]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
removeById有bug，该方法会更新FieldFill.UPDATE的字段，但是又没有这些字段的值

### 重现步骤(如果有就写完整)
100%必现

**Comment by john1337** [comment]
removeById是无法有效实现逻辑删除的，除非除了逻辑删除字段不需要更新其他字段

**Comment by miemieYaho** [comment]
代码呢?请以最新版给出复现demo

**Comment by john1337** [comment]
> 代码呢?请以最新版给出复现demo

productMapper.deleteById(UUID.randomUUID());
productMapper继承了BaseMapper

**Comment by qmdx** [comment]
请升级到最新版本测试，如果依然存在问题，给出详情的重现逻辑
