### ISSUE TITLE
批量保存时，自动填充带来的耗时问题

### ISSUE THREAD

**Issue by yanwencheng** [baomidou/mybatis-plus#4611]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

批保存1000条数据耗时约2000ms，经分析为自动填充实体对象创建人，修改人等自动填充数据导致。

**Comment by huayanYu** [comment]
缓存啊，
或自己填充好再批量插入
或完全调用原生mybatis
