### ISSUE TITLE
分页查询时只执行select count(*)语句

### ISSUE THREAD

**Issue by mrc321** [baomidou/mybatis-plus#4612]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
未知，且随机

### 报错信息
分页查询时，只执行 `SELECT COUNT(*)`，并没有执行后面查询记录的sql语句。导致查询结果只有记录数，并没有记录。
![image](https://user-images.githubusercontent.com/46882196/175764161-842d8d92-d4ac-4543-8524-49658d2d8f2a.png)
当再次执行一次时，才能两条语句查询成功
![image](https://user-images.githubusercontent.com/46882196/175764223-0ee76194-1999-4b08-8713-3d1f79a95fe4.png)

且这种现象具有偶然性，并不知道在什么条件下会触发这种问题。

**Comment by uncarbon97** [comment]
COUNT(*) 返回的total > 0 吗

**Comment by cwhm123** [comment]
您好  这个问题最后解决了吗
