### ISSUE TITLE
3.5.2 使用的 JSQLParser 4.4 有坑

### ISSUE THREAD

**Issue by WindProtect** [baomidou/mybatis-plus#4616]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用的 [JSQLParser 4.4 这个版本](https://github.com/JSQLParser/JSqlParser/issues/1572) 有坑，如果 SQL 中带有任何的 rr, rs 和 ur 的时候会报错

### 重现步骤(如果有就写完整)

```sql
SELECT * FROM a AS rr
```

### 报错信息

```
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "." "."
    at line 1, column 9.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ACTIVE"
```

**Comment by lucky-xin** [comment]
我也碰到这个问题

**Comment by miemieYaho** [comment]
你可以手动降级到上个版本,再给他提issue

**Comment by WindProtect** [comment]
> 你可以手动降级到上个版本,再给他提issue

写了一半 Issue 发现已经有人提过了我这里也引用了，作者回复了说可以先用 4.5 Snapshot 版本然后等正式发布。不过我先降级等下个版本吧。
