### ISSUE TITLE
使用Redis作为Mysql二级缓存，枚举属性无法正确解析

### ISSUE THREAD

**Issue by holajacky** [baomidou/mybatis-plus#4618]
### 当前使用版本(必填,否则不予处理)
`3.5.2`

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
>枚举属性  TRUE(1, "正常")

按照官网文档正确配置枚举后，首次查询时可以解析到对应的枚举属性，数据库为1时，返回前端的是“正常”，当第二次查询，Redis命中缓存时，返回前端的值就变成了TRUE

**Comment by miemieYaho** [comment]
检查你的缓存序列化方式
