### ISSUE TITLE
强烈建议官网增加版本更新说明的细节

### ISSUE THREAD

**Issue by IvesQing** [baomidou/mybatis-plus#4620]
### 当前使用版本(必填,否则不予处理)
version:3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
原先使用版本3.4的，升级3.5.1后，发现使用数据库主键自增的Auto后，原先主键id有值也会自动自增并替换id，3.51版本则是会报错 ，提示主键重复，也就会id有值不会再自增了

### 重现步骤(如果有就写完整)
强烈建议能说明清楚版本升级的细节，plus是dao层，影响范围太广了

**Comment by zhang673101454** [comment]
是哦，上次因为这个问题出过一次错了，好多人也反馈过吧，升级太随意了

**Comment by qmdx** [comment]
感谢建议，后续升级日志会重点描述可能存在影响的地方。出现你说的问题是对象的非正常引起的， java 对象值赋值未清理。
