### ISSUE TITLE
OptimisticLockerInnerInterceptor插件咨询咨询

### ISSUE THREAD

**Issue by zhizuntop** [baomidou/mybatis-plus#4623]
### 当前使用版本(必填,否则不予处理)
版本：3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自定义sql 批量更新，乐观锁出现：nested exception is org.apache.ibatis.binding.BindingException: Parameter 'MP_OPTLOCK_VERSION_ORIGINAL' not found. Available parameters are [list, param1]

使用系统封装好的updateById(id)方法没有问题，且乐观锁生效

**Comment by huayanYu** [comment]
自定义的要自己写
