### ISSUE TITLE
能否提供配置关闭字符画显示

### ISSUE THREAD

**Issue by jidaojiuyou** [baomidou/mybatis-plus#4626]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
没啥问题，就是看你们打印骚东西。想能提供个开关关闭或者通过log.debug打印。

### 重现步骤(如果有就写完整)
项目启动就会打印mp的字符画。这个能否通过配置关闭或者通过log.debug打印

### 报错信息
没有报错信息，就是觉得你们的全局配置不能自定义就很不合理。

### 诉求
能通过配置决定是否打印MyBatis-Plus的字符画。（最好实现这种方式）
或者使用log.debug打印(我们好自己拦截)

<img width="536" alt="image" src="https://user-images.githubusercontent.com/24694117/176839890-4a86b8d2-1126-4476-8dcc-b9eec0de103b.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/24694117/176840068-42762d71-f842-499d-b735-d3facb1ae61a.png">

<img width="928" alt="image" src="https://user-images.githubusercontent.com/24694117/176840175-58e3b60a-1191-4a3e-b109-26a7d9047c61.png">

**Comment by miemieYaho** [comment]
yml自己配
