### ISSUE TITLE
3.5.2 版本 count 不兼容的类型: 从long转换到int可能会有损失

### ISSUE THREAD

**Issue by SageJustus** [baomidou/mybatis-plus#4628]
### 当前使用版本(必填,否则不予处理)
3.5.2 jdk17

### 重现步骤(如果有就写完整)
正常使用CRUD接口count()
```java
int count = count(new QueryWrapper.eq(...))
```

### 报错信息
Maven Install报错：不兼容的类型: 从long转换到int可能会有损失

**Comment by miemieYaho** [comment]
count返回值从Integer变Long了
