### ISSUE TITLE
枚举跟文档说的不匹配，文档说数据库存的是code

### ISSUE THREAD

**Issue by 1183011789** [baomidou/mybatis-plus#4634]
### 当前使用版本(必填,否则不予处理)

        <mybatisplus.version>3.4.2</mybatisplus.version>

### 重现步骤(如果有就写完整)
![de6b69592f4293dd4ba2247789532a6](https://user-images.githubusercontent.com/30824602/177287107-5cb223af-ea14-4d63-a6ee-2ee5a6e78265.png)

![image](https://user-images.githubusercontent.com/30824602/177287047-ec1abace-752e-4e55-ac5c-9ecbbe1e722b.png)

### 报错信息
跟文档说的不匹配，文档说数据库存的是code'

**Comment by miemieYaho** [comment]
你哪里看出来存的不是code的值了?

**Comment by 1183011789** [comment]
![image](https://user-images.githubusercontent.com/30824602/177290325-d234374e-a1ad-44c6-a12f-cb14115a7710.png)
code是1、2、3

**Comment by 1183011789** [comment]
数据库存储的也不是1、2、3啊

**Comment by 1183011789** [comment]
抱歉我的问题，官方实例没问题

**Comment by 1183011789** [comment]
本地3.4.2版本   我升级下
