### ISSUE TITLE
PostgreSQL 无法正确处理bool类型

### ISSUE THREAD

**Issue by aboutZZ** [baomidou/mybatis-plus#4635]
### 当前使用版本
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
PostgreSQL 表中bool类型字段，在插入更新时，插值为`0`、`1`，而不是`true`、`false`

### 报错信息
执行SQL报错

**Comment by huayanYu** [comment]
具体点。 一直用PG从未有问题。

**Comment by aboutZZ** [comment]
自己代码失误，抱歉
