### ISSUE TITLE
调用框架save操作，数据库中UUID带横线，返回数据实体UUID没有横线

### ISSUE THREAD

**Issue by l1053727938** [baomidou/mybatis-plus#4637]
### 当前使用版本(必填,否则不予处理)

使用版本3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
pg数据库设置主键为uuid类型，保存数据后数据库中uuid带横线，但是返回实体数据中uuid不带横线
![图片](https://user-images.githubusercontent.com/29198257/177715220-33b97a4c-aa06-4092-af8e-a4667d8b602d.png)
![图片](https://user-images.githubusercontent.com/29198257/177715330-0354017f-1d27-4922-bf83-654fcd3f8c36.png)

**Comment by miemieYaho** [comment]
mp不参与数据封装
