### ISSUE TITLE
postgresql如何编写插件实现 eq时自动生成 COLLATE case_insensitive

### ISSUE THREAD

**Issue by libra1010** [baomidou/mybatis-plus#4642]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用  postgresql 但是 pgsql 区分大小写，希望能在 程序里面使用 eq 时生成的sql直接自动带入  COLLATE case_insensitive
以此达到不区分大小写的功能
目前我使用的方式是，加入 tableInfo, tableInfoFieldInfo 的proxy, 但是此种方式感觉入侵有点高，而且升级就可能不支持
请问有没有插件方式可以实现 字段上加一个 注解， 以此达到目的的插件？

**Comment by miemieYaho** [comment]
没有,你不如改数据库配置来支持

**Comment by libra1010** [comment]
> 没有,你不如改数据库配置来支持

数据库实现不了呀，要不然就得是 citext,并不是很想使用

**Comment by huayanYu** [comment]
没有，建议自己实现
