### ISSUE TITLE
南大通用gbase8a数据库，分页接口报错，如何配置？

### ISSUE THREAD

**Issue by pigMan15** [baomidou/mybatis-plus#4645]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
切换数据源为gbase8a数据库时

### 报错信息
You have an error in your SQL syntax; check the manual that corresponds to your GBase server version for the right syntax to use near 'OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY' at line 1

**Comment by miemieYaho** [comment]
1. 使用最新版
2. 给出你的代码
