### ISSUE TITLE
AbstractWrapper 重载apply方法添加 Supplier参数

### ISSUE THREAD

**Issue by iszhangsc** [baomidou/mybatis-plus#4649]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
希望 AbstractWrapper.class
添加一个将参数`applySql`更换为`Supplier`的方法，用以实现懒加载
public Children apply(boolean condition, String applySql, Object... values) {
        return maybeDo(condition, () -> appendSqlSegments(APPLY,
            () -> formatSqlMaybeWithParam(applySql, null, values)));
    }

**Comment by miemieYaho** [comment]
你这种是不是就不需要`Object... values`了?

**Comment by qmdx** [comment]
可以把条件提前如下

```
if(条件) {
 。。。业务执行。。。

   lqw.apply(。。。)
}
```
