### ISSUE TITLE
设置实体的 @TableName(value = "表名") 自定义实体名称后 SelectPage() 会失效找不到这个表

### ISSUE THREAD

**Issue by kshq1996** [baomidou/mybatis-plus#4650]
### 当前使用版本(必填,否则不予处理)

3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

3.5.2也存在

### 重现步骤(如果有就写完整)

设置实体的 @TableName(value = "表名") 自定义实体名称后 SelectPage() 会失效找不到这个表
public static TableInfo getTableInfo(Class<?> clazz)  出现在这个方法里 没有解析 @TableName 的参数
### 报错信息
XXXXX Not Found TableInfoCache.

**Comment by kshq1996** [comment]
急急急 这里要用到

**Comment by miemieYaho** [comment]
怎么用的说清楚

**Comment by miemieYaho** [comment]
Not Found TableInfoCache 说明没有对应的 basemapper<Class>

**Comment by kshq1996** [comment]
> Not Found TableInfoCache 说明没有对应的 basemapper

是嘛 我看看 同名了一些实体

**Comment by kshq1996** [comment]
> > Not Found TableInfoCache 说明没有对应的 basemapper
> 
> 是嘛 我看看 同名了一些实体

是的 是我的问题 谢谢了 我以为是没有读取@TableName的内容
