### ISSUE TITLE
Lambda的between条件构造失效

### ISSUE THREAD

**Issue by Klayt11** [baomidou/mybatis-plus#4657]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版不清楚

### 重现步骤(如果有就写完整)
LambdaQueryChainWrapper<ScmProduct> wrapper = lambdaQuery()
.eq(ScmProduct::getDelFlag, 0)
.between(queryBO.getCreateDateSection() != null, BaseEntity::getCreateTime, queryBO.getCreateDateSection().getStart(), queryBO.getCreateDateSection().getEnd())

### 报错信息
condition 无论是true还是false，都会拼接上这个sql段

**Comment by miemieYaho** [comment]
有复现demo么

**Comment by Klayt11** [comment]
没有再写demo了，我是在开发中遇到的。就只有between的condition无效，最后写死了false，发现sql拼接还是带上了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月15日(星期五) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/mybatis-plus] Lambda的between条件构造失效 (Issue #4657)





 
有复现demo么

**Comment by miemieYaho** [comment]
什么叫没有再写demo了?你的情况我们无法复现
