### ISSUE TITLE
saveOrUpdateBatch  报There is no getter for property named 'filter' 

### ISSUE THREAD

**Issue by zouk688** [baomidou/mybatis-plus#4658]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

List<GlzdQybz> qybzList = new ArrayList<>();
这里执行批量保存或更新就会 There is no getter for property named 'filter'  List就没有引用‘filter’
saveOrUpdateBatch(input.getQybzList());

但如果只用saveBatch 是可以保存，这里传参一样用的Collection<T> entityList
### 报错信息
nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'filter' in

**Comment by miemieYaho** [comment]
有复现demo吗

**Comment by qmdx** [comment]
未反馈
