### ISSUE TITLE
wrapper构造模糊查询时，参数为null时，生成的sql 中出现 %null%

### ISSUE THREAD

**Issue by HabenChan** [baomidou/mybatis-plus#466]
### 当前使用版本(必须填写清楚，否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.1</version>
        </dependency>

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

使用wrapper构造模糊查询时，参数为null时，生成的sql 中出现 %null%

补充：参数值并不时字符串null

### 重现步骤

![image](https://user-images.githubusercontent.com/15723833/45211973-44107c80-b2c6-11e8-8503-6e3e1196ef62.png)

### 报错信息

![image](https://user-images.githubusercontent.com/15723833/45211912-1deadc80-b2c6-11e8-92b8-fed16824c8b6.png)

**Comment by miemieYaho** [comment]
这种自行处理入参为null的情况,
`like(StringUtils.isNotBlack(value),column,value)`
