### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): *****.insertBatchSomeColumn

### ISSUE THREAD

**Issue by NoThingNoDust** [baomidou/mybatis-plus#4660]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
引入insertBatchSomeColumn后报错org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): *****.insertBatchSomeColumn
![image](https://user-images.githubusercontent.com/38269002/179548369-a3858ea2-5e86-4feb-a32c-3c958f9de4fd.png)

### 重现步骤(如果有就写完整)
1. 在DBMapper里新增了一条int insertBatchSomeColumn(List<Do> entityList);
2. 重写了属于自己的MyBatisPlusSqlInjector
3. 重写了MybatisPlusConfig的sqlInjector

**Comment by miemieYaho** [comment]
自行排查配置
