### ISSUE TITLE
【需求】是否可以支持数据对象的通用后缀

### ISSUE THREAD

**Issue by xggz** [baomidou/mybatis-plus#4662]
比如我的数据对象都以DO结尾，例：UserDO、RoleDO，在不加@TableName注解的情况下，能否增加一个全局配置，可以使表名解析成user、role，而不是user_do、role_do

**Comment by miemieYaho** [comment]
大概率不能

**Comment by xggz** [comment]
> 大概率不能

这是一个悲伤的故事😔 那只能自己重写关于表名生成策略的方法了

**Comment by qmdx** [comment]
你这个太独一无二了，你用前缀吧
