### ISSUE TITLE
在SQL Server中当表存在触发器且主键为自增时，MP无法正常使用插入接口

### ISSUE THREAD

**Issue by JosephC666** [baomidou/mybatis-plus#4665]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用Mybatis-plus的save() 往SQL Server中插入一行数据会报：nested exception is com.microsoft.sqlserver.jdbc.SQLServerException:必须执行该语句才能获得结果。经调查发现，如果该表存在触发器则会报错。

#### 2、创建一个User类：并为对应字段添加对应注解：
@TableIdName("User")
public class User implements Serializable ......

@TableId(value = "id",type = IdType.AUTO)
private Long id;

@TableField("name")
private String name;

省略 get、set......

#### 3、业务层调用添加接口
@Resource
private UserService userService;

public void test(){
    User user =new User();
    user.setName("Ada");
    userService.save(user);
}

#### 4、调用业务方法
调用步骤3的test()

### 报错信息
Error getting generated key or setting result to parameter object.Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。；nested exception is com.microsoft.sqlserver.jdbc.SQLServerException:必须执行该语句才能获得结果

**Comment by qmdx** [comment]
检查 ID 是否设置为自增，数据类型是否正确

**Comment by qmdx** [comment]
未反馈

**Comment by IvesQing** [comment]
这个问题有处理嘛，同样必现遇见

**Comment by 777sfdf** [comment]
你好 请问这个问题是怎末解决的呢  是在对应的service方法出加上try/catch 进行捕获异常 还是对其又手写xml文件了呢

**Comment by xzq512** [comment]
可在触发器中设置
SET NOCOUNT ON
阻止触发器返回额外结果集
即可顺利插入数据

**Comment by JosephC666** [comment]
> 可触发器中应设置 SET NOCOUNT ON 阻止触发器返回额外结果集 即可顺利插入数据

如果有数据库的权限进行设置这是可行的。但这么多年过去了，在更新的版本中是否应该考虑更多不同数据库的特性呢。感觉MP独宠MYSQL

**Comment by xzq512** [comment]
那只能说明MP的可移植性很差
