### ISSUE TITLE
IdType.AUTO 字段，显式赋值后不能插入问题

### ISSUE THREAD

**Issue by seasomnia** [baomidou/mybatis-plus#4669]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
显式得给IdType.AUTO 字段赋值后 save方法报错，同样的操作在3.1.1版本中不能复现。字段设置IdType.AUTO后在生成insert sql时是不是应该将该字段撇除，不管它是否有值。

### 重现步骤(如果有就写完整)
1、创建一个User类：并为对应字段添加对应注解：
@TableIdName("User")
public class User implements Serializable ......

@TableId(value = "id",type = IdType.AUTO)
private Integer id;

@TableField("name")
private String name;

3、业务层调用添加接口
private UserService userService;

public void test(){
User user =new User();
**user.setId(1);**
user.setName("Ada");
userService.save(user);
}

4、调用业务方法
调用步骤3的test()

### 报错信息
当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'User' 中的标识列插入显式值。

**Comment by qmdx** [comment]
类似 https://github.com/baomidou/mybatis-plus/issues/4668
