### ISSUE TITLE
TableField在用了@Select("select* from...)后不生效

### ISSUE THREAD

**Issue by Silentdoer** [baomidou/mybatis-plus#4676]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
@TableField("user_gender")
private GenderEnum gender;
用BaseMapper自带的selectById是可以将数据库表里的user_gender转换为gender属性查出来；
但是用自定义的selectByMmm（用了select*语句）则查不出来，但是又能自动下划线转小驼峰；
而且@TableName里写了 autoResultMap = true

### 重现步骤(如果有就写完整)
如上

### 报错信息

无，直接null

**Comment by miemieYaho** [comment]
不支持自己写的sql
