### ISSUE TITLE
多租户插件问题：当TenantLineHandler忽略某张表时， 等值子查询的时候却在该表sql语句拼接tenant_id

### ISSUE THREAD

**Issue by miaomiaocv** [baomidou/mybatis-plus#4677]
### 当前使用版本(必填,否则不予处理)
3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版3.5.1也存在

### 重现步骤(如果有就写完整)
第一步：在TenantLineHandler实现类里面，忽略sys_user_role表格不参与多租户模式。
第二步：在sql语句的where拼接该表sys_user_role的等值子查询。注（左右链接是正常的）。

### 报错信息
![image](https://user-images.githubusercontent.com/52368622/180907703-92343dd7-b299-4a73-8ae7-db5f375212a1.png)

**Comment by Hccake** [comment]
这种情况建议贴一个最简的可以复现的 sql，而不是扔张图

**Comment by alixiaodi** [comment]
我的也有类似的情况
A（主表）B（副表 - 忽略租户，单独查询没问题）
使用 a join b 的时候就会出问题，sql中默认会拼接上a租户字段和b租户字段
