### ISSUE TITLE
请问BaseMapper里面的方法怎么使用缓存

### ISSUE THREAD

**Issue by hundanLi** [baomidou/mybatis-plus#468]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
使用redis和注解缓存

### 重现步骤
BaseMapper里面的方法怎么缓存

### 报错信息
无

**Comment by miemieYaho** [comment]
https://baomidou.gitee.io/mybatis-plus-doc/#/question?id=mapper-%E5%B1%82%E4%BA%8C%E7%BA%A7%E7%BC%93%E5%AD%98%E9%97%AE%E9%A2%98
