### ISSUE TITLE
ServiceImpl.saveOrUpdate()方法增加类似SQL“INSERT IGNORE”的支持

### ISSUE THREAD

**Issue by a852203465** [baomidou/mybatis-plus#4683]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter： 3.4.3.4

由于会出现并发插入数据库，需要数据库本身在插入再次判断

**Comment by qmdx** [comment]
不支持，参考 https://baomidou.com/pages/42ea4a/ 自行实现注入
