### ISSUE TITLE
对于多租户插件获取租户id的疑问

### ISSUE THREAD

**Issue by lpn666** [baomidou/mybatis-plus#4684]
### 当前使用版本(必填,否则不予处理)
是

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请教一个问题
多租户插件获取用户id的时候，我看大多数是从springsecurity的loadUserByUsername 里面拿到的租户信息，或者从context里面拿到。
如果多个请求并发，但是到mapper的时间没有按照先后到达的顺序，那拿到的租户id不就是乱的么，这样mybatis-plus多租户插件查到的资产信息，不会有问题么？

### 重现步骤(如果有就写完整)

还没想到测试的方法，没有那么高并发的场景测试。

**Comment by phynos** [comment]
你知道你在说什么吗？牛头不对马嘴的
每个请求都是单线程处理，用户信息一般和线程绑定（准确来说和请求上下文绑定），不存在你说的这种情况，和高并发一毛钱关系都没有

**Comment by lpn666** [comment]
并不是所有的请求都是单线程的，比如spring-reactive。如果后面的请求不跟前面的在一个线程里面了，拦截器应该怎么使用呢

**Comment by lpn666** [comment]
> 你知道你在说什么吗？牛头不对马嘴的 每个请求都是单线程处理，用户信息一般和线程绑定（准确来说和请求上下文绑定），不存在你说的这种情况，和高并发一毛钱关系都没有

话说你算什么东西，不会说人话就别说，不懂得就别瞎j8回答，显得你很弱智。
