### ISSUE TITLE
多租户组件关联查询右表未加上租户id导致查询数据错误

### ISSUE THREAD

**Issue by 17818004048** [baomidou/mybatis-plus#4690]
实际执行sql--------------------------
SELECT
          i.*
        FROM
            t_rpc_invoker i
                LEFT JOIN t_app a ON i.f_app_id = a.f_id
                LEFT JOIN t_rpc_service s ON i.f_service_id = s.f_id
        WHERE
            i.f_code = #{invokerCode}
          AND a.f_code = #{appCode}
          AND s.f_code = #{serviceCode}
          AND i.f_company_id='default'    ------------------i.f_company_id='default'是多租户自动加上的条件
        limit 1

期待执行sql------------------------------------------------
SELECT
          i.*
        FROM
            t_rpc_invoker i
                LEFT JOIN t_app a ON i.f_app_id = a.f_id
                LEFT JOIN t_rpc_service s ON i.f_service_id = s.f_id
        WHERE
            i.f_code = #{invokerCode}
          AND a.f_code = #{appCode}
          AND s.f_code = #{serviceCode}
          AND i.f_company_id='default'   
          AND a.f_company_id='default'    --------期待关联的右表也加上多租户条件
          AND s.f_company_id='default'    --------期待关联的右表也加上多租户条件
          limit 1

**Comment by 17818004048** [comment]
关联查询右表不加租户id会导致关联数据有误

**Comment by miemieYaho** [comment]
以最新版为基础的复现demo有吗?

**Comment by 17818004048** [comment]
没有，我们项目这边发现了这样的问题




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上7:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 多租户组件关联查询右表未加上租户id导致查询数据错误 (Issue #4690)





 
以最新版为基础的复现demo有吗?

**Comment by miemieYaho** [comment]
不用最新版试?

**Comment by 17818004048** [comment]
我们项目现在用的版本是3.4.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 下午3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 多租户组件关联查询右表未加上租户id导致查询数据错误 (Issue #4690)





 
不用最新版试?
