### ISSUE TITLE
数据库定义的Clob字段，但是插件生成的语句是Blob，查询慢

### ISSUE THREAD

**Issue by youxiaxiaomage** [baomidou/mybatis-plus#4692]
### 当前使用版本(必填,否则不予处理)
v3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库中clob字段，插件生成的sql是blob,查询效率比pl/sql慢很多

### 重现步骤(如果有就写完整)
`2022-07-29 09:43:05.280 [http-nio-8110-exec-1] ERROR [] com.alibaba.druid.filter.stat.StatFilter -  - slow sql 54744 millis. select r.request,
               r.response
        from bes_record r
        where r.trace_no = ?[1002492860447264768]
<==    Columns: REQUEST, RESPONSE
<==        Row: <<BLOB>>, <<BLOB>>
<==      Total: 1
`
### 报错信息
pl/sql查询1s不到，但自动生成的sql为50s+

**Comment by miemieYaho** [comment]
typeHandler的事,自己想办法

**Comment by youxiaxiaomage** [comment]
这个也试了，没有达到提高查询速度的
