### ISSUE TITLE
我希望可以继承TenantLineInnerInterceptor并重写它，但是不支持

### ISSUE THREAD

**Issue by chenfeiwu** [baomidou/mybatis-plus#4697]
有个场景： A租户通过此方式进行字段逻辑隔离，B租户直接数据库隔离；那么B租户的表不需要再用这个字段了，也就没这个拦截器了

**Comment by huayanYu** [comment]
源码不都有么，整个copy下来重写

**Comment by chenfeiwu** [comment]
> 源码不都有么，整个copy下来重写

那等于我要自己维护一个分支了，主版本迭代了我如何更新呢

**Comment by huayanYu** [comment]
那你PR啊

**Comment by chenfeiwu** [comment]
> 那你PR啊

哎 我觉得这不是最佳方案，每次更新如果有变动那我这个版本都很被动，如果所有开源组织或社区都如此说有源码重写的态度的话 挺令人失望的

**Comment by chenfeiwu** [comment]
> 那你PR啊

如果大家遇到觉得某个问题可以完善一下的，当然觉得这个提议不是一个好的建议，那么也需要给出一定的理由，而不是遇到就拉分支改源码，那以后这个分支方向只会越来越偏，无论是对于这个开源项目或者社区都不是一个友好的方式

**Comment by chenfeiwu** [comment]
> 那你PR啊

我还是用代理的方式去解决吧，虽然也不是一个完美的方案，但比改源码的代价小多了，谢谢你的提议

**Comment by VampireAchao** [comment]
可以在租户表名过滤逻辑处理

**Comment by chenfeiwu** [comment]
> 可以在租户表名过滤逻辑处理

这个也不是完美，约束力太大了，比如大家都有个t_user的表

**Comment by VampireAchao** [comment]
可以在租户表名过滤逻辑处理的位置编写自定义逻辑，不仅仅是对表名过滤，因为表名过滤逻辑在每次DB操作都会触发，这是一个特性
