### ISSUE TITLE
通过QueryWrapper获取具体的泛型实体注册的表名

### ISSUE THREAD

**Issue by aimilin6688** [baomidou/mybatis-plus#4698]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

QueryWrapper<Person> queryWrapper = new QueryWrapper<>();
以上语句可以初始化一个QueryWrapper 现在想获取QueryWrapper具体泛型类型 Person 类，然后通过Person类获取该类上 的@TableName注解，有没有什么方法或者工具可以直接获取？

**Comment by VampireAchao** [comment]
TableInfoHelper.getTableInfo(UserInfo.class).getTableName()
