### ISSUE TITLE
数据库中查询SQL返回是没有结果，但是映射resultmap确显示total=1

### ISSUE THREAD

**Issue by denghp** [baomidou/mybatis-plus#47]
![a1](https://cloud.githubusercontent.com/assets/2291149/25987907/73a17884-3728-11e7-84c1-d730b8c188da.png)
![a2](https://cloud.githubusercontent.com/assets/2291149/25987927/858aa868-3728-11e7-9385-c895c327309e.png)
![a3](https://cloud.githubusercontent.com/assets/2291149/25987933/8e9f6498-3728-11e7-93d4-1c7ccf2caa7b.png)

**Comment by qmdx** [comment]
图片挂了

**Comment by denghp** [comment]
已经重新上传图片

**Comment by qmdx** [comment]
这是你自定义方法与 mp 没有什么关系，自己好好查查原因。更多问题加入我们讨论q群 576493122  和其他人沟通下。
