### ISSUE TITLE
插入或者更新数据后怎样自动填充原来实体类中的主键和其他字段如数据库自动生成的时间戳等等

### ISSUE THREAD

**Issue by hundanLi** [baomidou/mybatis-plus#470]
### 当前使用版本(必须填写清楚，否则不予处理)

2.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
插入数据，实体类还是无Id

### 重现步骤
无

### 报错信息

无

**Comment by miemieYaho** [comment]
除了主键其他字段不会回写.出现主键无法回写先好好检查你的配置
