### ISSUE TITLE
主键不兼容binary类型

### ISSUE THREAD

**Issue by patrickstarz** [baomidou/mybatis-plus#4705]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
主键无法设置binary类型

### 重现步骤(如果有就写完整)
/**
 * 查询出来乱码
 */
@TableId(type = IdType.INPUT)
@TableField(jdbcType = JdbcType.BINARY)
private String id;

/**
 * 查询出来正常
 */
@TableField(jdbcType = JdbcType.BINARY)
private String orgID;

### 报错信息
查询出来的binary的二进制乱码

**Comment by miemieYaho** [comment]
主键只支持`TableId`注解

**Comment by patrickstarz** [comment]
> 主键只支持`TableId`注解

但是问题是TableId注解无法设置字段类型为binary，这个怎么解
