### ISSUE TITLE
可否增加 涛思数据[TDengine]的支持呢？

### ISSUE THREAD

**Issue by mancong** [baomidou/mybatis-plus#4709]
### 当前使用版本(必填,否则不予处理)

mp : 3.5.2

可以正常 执行sql 但是分页无效。

**Comment by miemieYaho** [comment]
你可以pr

**Comment by qmdx** [comment]
参考 https://github.com/baomidou/mybatis-plus/pull/4433

**Comment by linghengqian** [comment]
- Duplicate of https://github.com/baomidou/mybatis-plus/pull/4910.  This issue should be marked as invalid and closed.
