### ISSUE TITLE
多租户如果原来的条件已经包含了租户表达式了，如何忽略后续处理

### ISSUE THREAD

**Issue by feiver** [baomidou/mybatis-plus#4711]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

例如SQL： select * from xxx where tenant_id=?;
处理后：select * from xxx where tenant_id=? and xxx.tenant_id=1;

如果已经存在了租户条件，就不再添加条件怎么处理，以前的版本可以重写processPlainSelect，判断where是否包含getTenantIdColumn，升级3.5.1后失效

**Comment by qmdx** [comment]
默认租户插件会添加条件的  1，自己写的sql不添加租户条件   2，注解忽略租户插件执行  https://baomidou.com/pages/223848/#interceptorignore

**Comment by feiver** [comment]
> 默认租户插件会添加条件的 1，自己写的sql不添加租户条件 2，注解忽略租户插件执行 https://baomidou.com/pages/223848/#interceptorignore

如果还要从mapper注解 就很无语
