### ISSUE TITLE
generator配置entityBooleanColumnRemoveIsPrefix=true导致is_XXX字段查询时丢失前缀

### ISSUE THREAD

**Issue by folochina** [baomidou/mybatis-plus#472]
### 当前使用版本(必须填写清楚，否则不予处理)
imybatis plus generator:1.2.5
mybatis plus boot start:3.0.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
1.表结构：任意包含类似is_delete is开头字段的表
2.配置entityBooleanColumnRemoveIsPrefix=true生成mapper与entity
3.使用selectOne查询任意条件出现错误，报错delete在sql中是关键字错误，
sql语句为select delete from table xxx,不是 select is_delete from table
4.使用@TableField("is_delete") 继续报错，sql变成:select is_delete as delete from table

### 重现步骤
配置的entityBooleanColumnRemoveIsPrefix=true
mapper.xml: is_delete=delete
entity.java: delete=false
xxxMapper.selectOne(entity)
执行sql: select delete from table xxx

### 报错信息
You have an error in your SQL syntax
select is_delete as delete from table

**Comment by miemieYaho** [comment]
遇到需要as的sql,请把java属性名规避掉数据库关键字
- 你可以把数据库字段改名为"delete",然后在`@TableField`注解里指定数据库字段名并用转义符包裹
- java属性名和数据库字段都改为"deleted"

**Comment by folochina** [comment]
@miemieYaho 明白你的意思,我不打开entityBooleanColumnRemoveIsPrefix=true就完美解决了
- 但是entityBooleanColumnRemoveIsPrefix=true这个属性是不是就是一个花架子，生成的bean符合规则，但是使用查询等的时候却不行
- 能否设置这个屏蔽is前缀的属性，在查询的时候也能够识别去加上is前缀查数据库

**Comment by miemieYaho** [comment]
哪来的花架子? is 开头的其他非关键字可是好好的哦

**Comment by heardfate** [comment]
> @miemieYaho 明白你的意思,我不打开entityBooleanColumnRemoveIsPrefix=true就完美解决了
> 
> * 但是entityBooleanColumnRemoveIsPrefix=true这个属性是不是就是一个花架子，生成的bean符合规则，但是使用查询等的时候却不行
> * 能否设置这个屏蔽is前缀的属性，在查询的时候也能够识别去加上is前缀查数据库

最后妥协不打开吗，我最近也碰到这问题，
系统不更新，看来只能用去除is后，也不是关键字的字段用作数据库字段来表示 如is_deletes

**Comment by DevilMafia** [comment]
我同样也遇到这个问题， 数据库字段名称如为 is_ 开头：is_delete 、is_attachment 等； Java 实体对象字段命名规则在阿里巴巴的Java开发规约中有提到过，实体字段属性不提倡 "is" 开头。 所以，在使用 mybatis-plus generator 时，配置了数据库表策略时 设置 setFieldPrefix("is_") ， 此时生成的实体类之中 字段名称既已去除 is 前缀。但是此时不论调用那个 select 方法，都会报错，SQL 日志打印 select id,name,,,, is_delete as delete, is_attachment as attachment ,, from t_* ; 此时就会报错。
