### ISSUE TITLE
IService中的save方法保存完自动返回主键id

### ISSUE THREAD

**Issue by qq12157138** [baomidou/mybatis-plus#4723]
3.4.0的时候没问题，这是3.5.2的新特性吗？需要怎么配置？

新版本的插入的时候id自增列会有问题。以前IdType=Auto得时候插入的时候即使指定了id也会准寻自增列id+1的原则去插入，新版本不会

**Comment by qq12157138** [comment]
因为我需要多次保存，下次保存的时候返回的对象上有id就会报错 @miemieYaho

**Comment by qq12157138** [comment]
没人知道吗？？？？？

**Comment by VampireAchao** [comment]
多次保存可以手动去掉

**Comment by qq12157138** [comment]
@VampireAchao 意思是3.5.2这样是正确的？不向下兼容了是吧？

**Comment by VampireAchao** [comment]
是的
