### ISSUE TITLE
主键如何兼容mysql和oracle生成策略

### ISSUE THREAD

**Issue by qq511340079** [baomidou/mybatis-plus#4725]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库代码需要兼容mysql和oracle，但是mysql是自增主键，oracle是序列，@TableId使用AUTO会在oracle数据库报错，而使用INPUT在mysql数据库好像又不行

**Comment by qmdx** [comment]
使用 默认 id 雪花生成算法，不适用数据库自带的即可

**Comment by kunhour** [comment]
我感觉有场景使用的
