### ISSUE TITLE
如果表字段id非自增，手动select最大id时会拼上tenant_id，用注解@InterceptorIgnore(tenantLine = "1")无效

### ISSUE THREAD

**Issue by luhd7** [baomidou/mybatis-plus#4728]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
sqlserver数据库中，在<selectKey keyProperty="id" resultType="long" order="BEFORE">的标签里获取最大id时，会拼上tenant_id导致获取的最大id不正确报错

**Comment by luhd7** [comment]
<selectKey order="BEFORE" resultType="Long" keyProperty="id">
      select isnull(max(id),0)+1 from '表名'
</selectKey>

**Comment by miemieYaho** [comment]
给出git形式的复现demo

**Comment by luhd7** [comment]
> 给出git形式的复现demo
![image](https://user-images.githubusercontent.com/88182055/183802159-80180685-772b-4700-ac3f-db146c2fd83e.png)
![1660031679321_0D762B50-EAE8-4cd4-9B2F-1D2EF82D53F4](https://user-images.githubusercontent.com/88182055/183801867-0b684d25-d3e4-4607-90ac-890e3a592e42.png)
就是像这样会有问题

**Comment by miemieYaho** [comment]
使用: `3.5.2.2-SNAPSHOT`
仓库地址: `https://oss.sonatype.org/content/repositories/snapshots/`

**Comment by luhd7** [comment]
> 收到
