### ISSUE TITLE
自定义sql 批量插入，tenantId没有填充

### ISSUE THREAD

**Issue by taotao365s** [baomidou/mybatis-plus#4729]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 报错信息
![image](https://user-images.githubusercontent.com/1212932/183871864-4ec0680f-2f01-4b32-99e5-55a85c30c3fb.png)

**Comment by miemieYaho** [comment]
你想怎么个填充法?

**Comment by taotao365s** [comment]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/1212932/184258691-d54314e1-a346-4db9-b76b-24b9dcadc678.png">

@miemieYaho 这里的规范，就是指自己手动赋值，对吧？

**Comment by miemieYaho** [comment]
是要求sql写标准
