### ISSUE TITLE
GlobalConfig.setEntityName(..)设置了之后，entity名字如果和数据库中的tablename不一致，会报table not exists

### ISSUE THREAD

**Issue by pjypjy** [baomidou/mybatis-plus#473]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.1

并没有自动生成@TableName注解

**Comment by pjypjy** [comment]
TableInfo.java：71行
            // 转换字段
            if (NamingStrategy.underline_to_camel == strategyConfig.getColumnNaming()) {
                // 包含大写处理
                if (StringUtils.containsUpperCase(name)) {
                    this.convert = true;
                }
            } else if (!entityName.equalsIgnoreCase(name)) {
                this.convert = true;
            }

71行的name应该改成entityName吧？

**Comment by qmdx** [comment]
测试 gc.setEntityName("%sEntity"); 没有重新你的异常。

请贴出表结构，具体配置 ，方便定位
