### ISSUE TITLE
字段flag上设置了@TableField(update = "%s+1")，但最后拼接进去的sql是flag= flag+1，没取到flag的值

### ISSUE THREAD

**Issue by Github-six** [baomidou/mybatis-plus#4730]
### 当前使用版本(必填,否则不予处理)
3.5.2

之前用的3.4.0也不行，升到3.5.2也不行

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/58926187/184054505-26dffd9c-9d5f-4342-87bb-33499106c0ce.png)

字段flag上设置了@TableField(update = "%s+1")，但最后拼接进去的sql是flag= flag+1，没取到flag的值，不知道是不是开了动态表名的原因

**Comment by miemieYaho** [comment]
就是这样的

**Comment by Github-six** [comment]
![image](https://user-images.githubusercontent.com/58926187/184058016-9b16340d-e8f5-4f2d-a4cd-13ea32dbe512.png)
比如这个，我本来想存入数据库的经过他自动加1之后的3，但现在他取不到我传入的那个2，所以他最后如果是插入数据库就会让flag为null，如果是更新就会让flag不变，其他的会变
最后日志打出来应该是下面这样的吧
![image](https://user-images.githubusercontent.com/58926187/184058500-f27e487b-7b54-48b5-b5d4-41da9e42e0ea.png)

**Comment by miemieYaho** [comment]
不用比如了,这功能就是这样的,数据库字段值自增长

**Comment by Github-six** [comment]
欧克欧克
