### ISSUE TITLE
在配合 springboot3 使用时,类NestedIOException无法找到

### ISSUE THREAD

**Issue by 20gg** [baomidou/mybatis-plus#4732]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

配合springboot3 框架使用

### 重现步骤(如果有就写完整)
发现版本spring-core-6.0.0已经把类org.springframework.core.NestedIOException删除了

### 报错信息
![image](https://user-images.githubusercontent.com/8279488/184109043-40b261fc-41a9-4f6b-bdf1-9f11cd433e74.png)

**Comment by 20gg** [comment]
已有相同问题

**Comment by eritpchy** [comment]
+1, 调试模式并不会有这个问题

**Comment by eritpchy** [comment]
![image](https://user-images.githubusercontent.com/8630635/184544273-7c706af3-b64f-4789-83ef-6ffc70af25ff.png)
感谢
