### ISSUE TITLE
我才发现，用了这么久，没有批量更新，不通用主键而用wrapper的方式

### ISSUE THREAD

**Issue by HoneyTorres** [baomidou/mybatis-plus#4734]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
需要批量更新where条件为非主键或复合主键

### 报错信息
没有这个功能

**Comment by miemieYaho** [comment]
没有

**Comment by HoneyTorres** [comment]
你直接关了算啥呀，不能增加一个wrapper的批量操作么，最起码增加一个tolist呀

**Comment by miemieYaho** [comment]
要不你提交pr?

**Comment by HoneyTorres** [comment]
我看看，能实现的话给你提交
