### ISSUE TITLE
关于sql注入器的一点建议 

### ISSUE THREAD

**Issue by taotao365s** [baomidou/mybatis-plus#4735]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 报错信息

![image](https://user-images.githubusercontent.com/1212932/184266598-660e0d23-d8e6-4fee-b1af-638ae06fa205.png)

这里用了继承，是否可以使用 service-loader的方式在方法体重预留某些扩展？毕竟继承具有强制性特点，而扩展是按需配置的

**Comment by miemieYaho** [comment]
不能
