### ISSUE TITLE
mybatis-plus-extension默认单条插入方法返回int类型不方便后续操作问题,非严重bug

### ISSUE THREAD

**Issue by fireworkor** [baomidou/mybatis-plus#4739]
### 当前使用版本(必填,否则不予处理)

mybatis-plus-extension-3.5.1 全系列

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我要插入一条数据,使用默认的savef方法,结果返回是否插入成功的数量,而不是插入的这条记录,如图一,这里很不合理

如果我要继续给这条数据更新状态,我不知道主键是什么, 找不到这条数据,

同样的情况下,jpa就返回插入的实体类如图2

![image](https://user-images.githubusercontent.com/28347713/184525012-2965a30b-711c-43e1-ae7e-a088f227c3da.png)

![image](https://user-images.githubusercontent.com/28347713/184525149-7d61efe6-2862-4c26-9bfa-f5c17fa1e769.png)

### 重现步骤(如果有就写完整)

无

### 报错信息

不报错,建议修改原生方法

### 解决方案 建议方案一

方案一: 增加重载同名方法

方案二: 调整接口返回类型

**Comment by huayanYu** [comment]
方法三： 看文档知道主键填充到 了原来实体。
方法四： 提PR给mybatis让他原生支持返回实体。
