### ISSUE TITLE
3.0 文档完善计划

### ISSUE THREAD

**Issue by virtuecai** [baomidou/mybatis-plus#474]
### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

在阅读 http://mp.baomidou.com 文档的时候发现很多模块的内容没有， 请问什么时候可以完善？

**Comment by folochina** [comment]
mark

**Comment by miemieYaho** [comment]
[3.x 例子](https://gitee.com/baomidou/mybatis-plus-samples)
先自己看例子,文档都是要人写的,没那么多精力写,文档人人均可 pr

**Comment by virtuecai** [comment]
不好意思，原来3.*还在开发阶段，抱歉。
