### ISSUE TITLE
升级3.5.2配合springboot报错

### ISSUE THREAD

**Issue by huanglingz** [baomidou/mybatis-plus#4742]
### 当前使用版本(必填,否则不予处理)
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.14</version>
        <relativePath />
    </parent>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2</version>
        </dependency>
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我在使用接口测试时报错。换3.5.1正常。

### 重现步骤(如果有就写完整)

接口代码

    @Test
    public void testSelect() {
        System.out.println(("----- selectAll method test ------"));
        List<SysStudent> userList = sysStudentMapper.selectList(null);
        userList.forEach(System.out::println);
    }

### 报错信息

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.core.MybatisXMLConfigBuilder.settingsElement(MybatisXMLConfigBuilder.java:272)

The following method did not exist:

    org.apache.ibatis.session.Configuration.setArgNameBasedConstructorAutoMapping(Z)V

The method's class, org.apache.ibatis.session.Configuration, is available from the following locations:

    jar:file:/C:/Users/Administrator.DESKTOP-DDJ51ET/.m2/repository/org/mybatis/mybatis/3.5.9/mybatis-3.5.9.jar!/org/apache/ibatis/session/Configuration.class

The class hierarchy was loaded from the following locations:

    org.apache.ibatis.session.Configuration: file:/C:/Users/Administrator.DESKTOP-DDJ51ET/.m2/repository/org/mybatis/mybatis/3.5.9/mybatis-3.5.9.jar

**Comment by meiMingle** [comment]
org.springframework.boot:spring-boot-starter-parent:2.5.14所管理的mybatis版本似乎是比较旧的版本。
你可以试试强制指定以下依赖版本：
mybatis-》3.5.10
mybatis-spring-》2.0.7
jsqlparser->4.4

**Comment by miemieYaho** [comment]
检查版本依赖冲突
