### ISSUE TITLE
版本3.5.2分页方法返回的total错误

### ISSUE THREAD

**Issue by seepine** [baomidou/mybatis-plus#4746]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库mysql，通用service的page分页查询方法
```
 LambdaQueryWrapper<SysRole> wrapper = Wrappers.lambdaQuery();
IPage<SysRole> res = service.page(page, wrapper);
```
生成的sql
```
SELECT
	id,
	NAME,
	description,
	tenant_id,
	is_delete 
FROM
	sys_role 
WHERE
	is_delete = 0 
	AND sys_role.tenant_id = '1555096862863155201' 
	LIMIT 10
```

数据库中共有15条数据
查到的records只有2条，但是返回的total为15，看了一下没有进行租户过滤
![image](https://user-images.githubusercontent.com/93666053/185033866-870509da-9042-49d2-82ac-8bf7868da0d9.png)

**Comment by miemieYaho** [comment]
把租户插件放分页前面
