### ISSUE TITLE
idtype无效

### ISSUE THREAD

**Issue by MrYZhou** [baomidou/mybatis-plus#4755]
### 当前使用版本(必填,否则不予处理)
jdk17
mybatis-plus 3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
  mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    global-config:
      db-config:
        logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
        tablePrefix: null #表名前缀
        idType: ASSIGN_UUID #全局默认主键类型,默认值：ASSIGN_ID,雪花long类型id

### 重现步骤(如果有就写完整)
 idType: ASSIGN_UUID 然后entity那边按理就不用设置了。但是数据库还是按雪花id的生成

### 报错信息
无

**Comment by MrYZhou** [comment]
![image](https://user-images.githubusercontent.com/44339602/185355368-922601a9-3a66-4285-aa76-c10e3ade4db8.png)

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by MrYZhou** [comment]
> 给出你的复现demo

https://gitee.com/lgpr/toolbox-serve.git

然后点到
![image](https://user-images.githubusercontent.com/44339602/185517832-5028448e-37de-49c9-ab69-bce52e59adf4.png)

**Comment by miemieYaho** [comment]
你的项目无法编译,你自己排查吧,肯定是你的配置问题

**Comment by MrYZhou** [comment]
> 你的项目无法编译,你自己排查吧,肯定是你的配置问题

是什么问题，应该可以启动啊，你数据库自己得配置下吧，这个明显是按文档说的配置在db-config下。这个不行我这边也不报错。怎么看。

**Comment by MrYZhou** [comment]
> > 你的项目无法编译,你自己排查吧,肯定是你的配置问题
> 
> 是什么问题，应该可以启动啊，你数据库自己得配置下吧，这个明显是按文档说的配置在db-config下。这个不行我这边也不报错。怎么看。

如果在字段上面注解这个策略是生效得，就只有在yml那边配置全局得不行

**Comment by melon-huang** [comment]
同学，你的配置文件mybatis-plus在spring下，所以不生效，建议检查一下。
https://gitee.com/lgpr/toolbox-serve/blob/master/main-module/src/main/resources/application-dev.yml#L108

**Comment by luofeng52** [comment]
哥们，你的mybatis-plus配置放在spring里面，要单独放在最外面
