### ISSUE TITLE
generator @Table 生成逻辑出错

### ISSUE THREAD

**Issue by geercode** [baomidou/mybatis-plus#476]
### 当前使用版本(必须填写清楚，否则不予处理)
最新版本3.0.1
generator
com.baomidou.mybatisplus.generator.config.po.TableInfo
![image](https://user-images.githubusercontent.com/18181713/45470434-570ccc00-b760-11e8-9f9b-146e846da2dc.png)
切换了EntityName生成的时候没有生成@Table标签

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
逻辑错误,用了驼峰命名以后默认表名没有发生变化,导致生成错误

**Comment by qmdx** [comment]
修复，请关注 `3.0.3` 发布 https://github.com/baomidou/mybatis-plus/commit/bf956bcb02d964574b51d0a874fc5b1db5f537ba

**Comment by geercode** [comment]
在基于mybatis-plus-generator进行二次开发~ @qmdx
