### ISSUE TITLE
能不能把remove方法也搞成update一样的写法

### ISSUE THREAD

**Issue by sy714573037** [baomidou/mybatis-plus#4761]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

remove方法要写一个wrapper,繁琐的很

### 重现步骤(如果有就写完整)

现在的写法

userService.remove(Wrappers.<User>lambdaQuery().eq(User::getId , 1L));

能不能提供下面这种写法

userService.remove().eq(User::getId , 1L);

**Comment by miemieYaho** [comment]
userService.lambdaUpdateQuery().eq(User::getId , 1L.remove());
