### ISSUE TITLE
Query和LambdaQuery都不能很好地支持distinct语句

### ISSUE THREAD

**Issue by KillerJmc** [baomidou/mybatis-plus#4764]
### 当前使用版本
3.5.2

### 该问题是如何引起的？
我原来使用的是LambdaQuery，发现不能distinct，后来普通Query也没有相关方法。

### 重现步骤
现在只能这么写:
Wrappers.<Role>query().select("distinct role_name");

希望作者大大加入Distinct去重方法，我希望以后能写成这样：
Wrappers.<Role>lambdaQuery().selectDistinct(Role::getRoleName);
和：
Wrappers.<Role>query().selectDistinct("role_name");

**Comment by niko-develop** [comment]
sum 什么的函数看上去也不支持， 将 sql 片段放在代码里面， 总感觉不是很优雅

**Comment by qmdx** [comment]
建议 xml 中写
