### ISSUE TITLE
实体类中使用同名不同驼峰命名的属性，在使用selectBatchIds查询时，返回的结果会出现一定概率绑定到错误的实体类属性中

### ISSUE THREAD

**Issue by uxawseny** [baomidou/mybatis-plus#4768]
### 当前使用版本(必填,否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在同一个实体类中使用了相同名称(驼峰不同)的属性时，出现该问题。
3.5.2也存在该问题

### 重现步骤(如果有就写完整)

如下，在实体类中定义了两个属性，一个名为replytoid，加了@TableField(exist = false)注解；另一个名为replyToId，绑定数据库@TableField("REPLY_TO_ID")，在使用selectBatchIds查询时，结果集中的属性赋值到了replytoid而不是replyToId。如果单独只有一个属性，则会正确赋值到replyToId。

    @TableField(exist = false)
    private String replytoid;

    @TableField("REPLY_TO_ID")
    private String replyToId;

而以下两个属性同时存在，则又会正确赋值到 sendTimes属性

@TableField(exist = false)
    private LocalDateTime sendtimes;
    @TableField("SEND_TIMES")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime sendTimes;

### 报错信息

无报错信息

**Comment by miemieYaho** [comment]
mybatis不区分大小写,除非你用resultmap
