### ISSUE TITLE
last拼接sql不生效

### ISSUE THREAD

**Issue by MonkeyCoder128** [baomidou/mybatis-plus#4771]
### 当前使用版本(必填,否则不予处理)

3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用last("limit 1")进行sql拼接.但是打印出来的sql并没有拼接上

### 重现步骤(如果有就写完整)

firstYuliangDataWrapper.lambda().eq(YuliangData::getPositionNum, deviceConfig.getPositionNum()).eq(YuliangData::getChannelNum, deviceConfig.getChannelNum()).between(ReservoirYuliangData::getCollectTime, offSetHour, now).last("limit 1");

### 打印的sql
SELECT id,position_num,channel_num,unit,total_count,receive_value,collect_time,creat_time FROM 
yuliang_data WHERE position_num = '595' AND channel_num = 'F1' AND collect_time BETWEEN 
'2022-08-24 12:54:00' AND '2022-08-24 13:54:00'

**Comment by miemieYaho** [comment]
升级版本再说
