### ISSUE TITLE
eq查询 字符串后面带空格  导致查出多条数据  like优化

### ISSUE THREAD

**Issue by lexang** [baomidou/mybatis-plus#4778]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

eq查询 字符串后面带空格  导致查出多条数据

改为like  只有：
like ‘%name’
like ‘name%’
like ‘%name%’

有什么其他办法吗 或者什么时候支持like ‘name’  吗

**Comment by lucheng** [comment]
无法复现，可以说明一下数据库，和重新步骤
