### ISSUE TITLE
使用@InterceptorIgnore注解忽略租户，主表忽略成功，副表不成功

### ISSUE THREAD

**Issue by xiaomizhou2** [baomidou/mybatis-plus#4780]
v3.5.1

使用@InterceptorIgnore注解，指定mapper方法忽略多租户插件，该方法的join表的租户字段未被忽略

例：SELECT * FROM a INNER JOIN b ON a.id = b.id AND b.tenant_id

**Comment by miemieYaho** [comment]
怎么个复现流程?

**Comment by xiaomizhou2** [comment]
> 怎么个复现流程?

pom中引入的是mybatis-plus这个依赖，没使用mybatis-plus-boot-stater依赖。

原因是非boot-starter依赖不扫描@InterceptorIgnore注解的mapper，所以不生效。请问使用非starter依赖怎么使@InterceptorIgnore注解生效呢？

**Comment by miemieYaho** [comment]
只要是mp正确初始化了就生效,和是不是stater无关,给出你的复现demo

**Comment by xiaomizhou2** [comment]
> 只要是mp正确初始化了就生效,和是不是stater无关,给出你的复现demo

已解决，问题原因是pagehelper与mp依赖冲突，十分感谢
