### ISSUE TITLE
功能建议：建议增加Hibernate类似的dynamic-update

### ISSUE THREAD

**Issue by veione** [baomidou/mybatis-plus#4783]
### 当前使用版本(必填,否则不予处理)
3.0 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
建议增加Hibernate类似的dynamic-update，以便于能够只需要更新变动的字段即可，这样就避免了全量更新。

**Comment by qmdx** [comment]
默认更新就是非空值
