### ISSUE TITLE
生成器缺少java8的时间戳类型Instant

### ISSUE THREAD

**Issue by imic07** [baomidou/mybatis-plus#479]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.0.2

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
DbColumnType 中缺少java8的时间戳类型Instant

### 重现步骤
数据库使用timestamp类型，代码生成器生成的bean对象会使用 LocalDateTime 类型。

### 报错信息
无

**Comment by qmdx** [comment]
实现接口 com.baomidou.mybatisplus.generator.config.rules.PropertyInfo

然后：DataSourceConfig 注入对应数据库的 typeConvert 重写 processTypeConvert 方法判断你需要的类型返回你自定义的字段类型类

**Comment by yuenke** [comment]
@qmdx v2.3.3版本如何处理，没看到有这个 com.baomidou.mybatisplus.generator.config.rules.PropertyInfo

**Comment by qmdx** [comment]
> @qmdx v2.3.3版本如何处理，没看到有这个 com.baomidou.mybatisplus.generator.config.rules.PropertyInfo

你可以用 3.0 的生成器模块
