### ISSUE TITLE
使用selectList方法查询单个字段，那个字段为null，返回列表里面那个对象为null

### ISSUE THREAD

**Issue by luyunjian000** [baomidou/mybatis-plus#4791]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用selectList方法查询单个字段name，数据库里面name为null，则返回列表里面那个对象为null
应该是返回的列表里面都是有对象的，只是对象的name字段是null

**Comment by miemieYaho** [comment]
数据封装是mybatis的逻辑
