### ISSUE TITLE
能否直接通过sFunction或者Fcuntion逆向生成QueryWrapper？

### ISSUE THREAD

**Issue by likewatchstar** [baomidou/mybatis-plus#4795]
3.1.0

    @Override
    public <T> List<T> listBy(SFunction<T,?> sFunction, Object val) {

        QueryWrapper queryWrapper=new QueryWrapper();
        queryWrapper.lambda().eq(sFunction,val);
        return baseMapper.selectList(queryWrapper);
    }
            allCommunity = estateMapper.listBy(x->x.getId(),communityId);
            
            allBuilding=buildingMapper.listBy(x->x.getEstateId(),communityId);
            
            List<String> buildingIds = allBuilding.stream().map(x->x.getId()).collect(Collectors.toList());
            
            allRoom=roomMapper.listBy(x->x.getBuildingId(),buildingIds);

就是类似这种代码，我们只需要考虑lambda的行为就行了，new QueryWrapper感觉是一个重复的行为，lambda已经可以表示出行为逻辑

**Comment by qmdx** [comment]
不支持
