### ISSUE TITLE
动态表名对通用分页获取方法 `selectPage` 无效

### ISSUE THREAD

**Issue by samho2008** [baomidou/mybatis-plus#4797]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
分页的时候，会执行两条 SQL，第一条是查询总条数，第二条是获取具体数据的 SQL，在第二条 SQL 中表名修改成功了，但是在第一条 SQL 中表名还是没有变（没有执行到动态表名拦截器？）。

**Comment by miemieYaho** [comment]
看文档调整插件顺序
