### ISSUE TITLE
saveBatch 插入太慢   https://mp.baomidou.com/guide/crud-interface.html#insertbatchsomecolumn 访问不了!

### ISSUE THREAD

**Issue by 15003476628** [baomidou/mybatis-plus#4798]
mysql 选装一下一下这个插件 https://mp.baomidou.com/guide/crud-interface.html#insertbatchsomecolumn

其他数据库 自己拼sql 

mybatis-plus 为了多数据源兼容性 是for loop  insert

_Originally posted by @lltx in https://github.com/baomidou/mybatis-plus/issues/3360#issuecomment-789371126_

**Comment by miemieYaho** [comment]
https://baomidou.com/pages/49cc81/#insertbatchsomecolumn
