### ISSUE TITLE
在开启LogicDelete的情况下用EntityWrapper做分页查询后添加时间判断 会有两个where

### ISSUE THREAD

**Issue by homolumo** [baomidou/mybatis-plus#48]
`        Page<GoodCategoryBean> list = mpGoodCategoryService.selectPage(new Page<>(page, limit),
            new EntityWrapper<>(new GoodCategoryBean()).lt(GoodCategoryBean.ADDDATE, LocalDateTime.now()));`

`SQL: SELECT  id,`name`,addDate,isDel  FROM t_good_category   WHERE  isDel=0  WHERE (addDate < ?)`

Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException

**Comment by willenfoo** [comment]
群里文件中，有逻辑删除的视频讲解， 或者在优酷上看视频 http://v.youku.com/v_show/id_XMjc4ODY0MDI5Ng==.html?spm=a2hzp.8244740.userfeed.5!2~5~5~5!3~5~A

**Comment by Caratacus** [comment]
#56
