### ISSUE TITLE
mybatis返回list对象是list<JsonObject>的

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4802]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
字段为json,
@TableField(typeHandler = FastjsonTypeHandler.class)
 private List<ApproverOpinionDto> approverOpinions;
虽然返回数据了,但是list里面是jsonobject,循环获取对象属性时报错

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/39609367/189058283-a55f19fd-bffd-4e2d-829a-31221e606c64.png)

**Comment by miemieYaho** [comment]
不支持泛型
