### ISSUE TITLE
自定义插件导致分页结果错误

### ISSUE THREAD

**Issue by XiaShus** [baomidou/mybatis-plus#4808]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自己实现了一个数据隔离的插件导致分页会返回数据错误。
插件逻辑：
1.实现 InnerInterceptor 接口
2.使用 mpBs.sql 修改查询 sql

### 重现步骤(如果有就写完整)
自己开发插件可以实现

### 报错信息
无报错

插件代码
[ProjectLeverInterceptor.txt](https://github.com/baomidou/mybatis-plus/files/9554880/ProjectLeverInterceptor.txt)

**Comment by miemieYaho** [comment]
是放在分页插件前面的吗?

**Comment by XiaShus** [comment]
> 是分页插件前面的吗？

不知道怎么调整插件顺序

**Comment by miemieYaho** [comment]
MybatisPlusInterceptor.addInnerInterceptor(1)
MybatisPlusInterceptor.addInnerInterceptor(2)
MybatisPlusInterceptor.addInnerInterceptor(3)
