### ISSUE TITLE
UnsupportedOperationException on MPJInterceptor

### ISSUE THREAD

**Issue by trungdoviet** [baomidou/mybatis-plus#4809]
### 当前使用版本(必填,否则不予处理) 
mybatis-plus-join:1.2:1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
When calling mapper with method
```java
List<Object> list(Map<?,?> criterias;
```
then it throw exception UnsupportedOperationException on MPJInterceptor, line 63
Reason:When mapper has param with type Map, mhybatis use ImmutableMap for that type. so in MPJInterceptor we try to put like this:
```java
if (!map.containsKey(Constant.PARAM_TYPE)) {
                    map.put(Constant.PARAM_TYPE, Objects.nonNull(ew) && (ew instanceof MPJBaseJoin));
                } 
```
then it does not allow for ImmutableMap

### 重现步骤(如果有就写完整)
We should have another solution for ImmutationMap

**Comment by miemieYaho** [comment]
该项目不是我们的
