### ISSUE TITLE
新增策略insert-strategy设置为ignored后，新增时不会填充逻辑删除的字段

### ISSUE THREAD

**Issue by visionki** [baomidou/mybatis-plus#4810]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

起初是想更新null字段进入数据库，于是把新增策略和更新策略都设置为了ignored，发现新增后查询不到数据。

看代码里的备注或文档，`FieldStrategy`相关的只提到校验null或空，检查了半天才发现是这个原因，如果是特性请在文档提一下，避免踩坑。

**Comment by miemieYaho** [comment]
https://baomidou.com/pages/223848/#fieldstrategy
