### ISSUE TITLE
SELECT  FROM user WHERE name = ? AND (name LIKE ?) 

### ISSUE THREAD

**Issue by Eminem58** [baomidou/mybatis-plus#4813]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
QueryWrapper<User> queryWrapper = new QueryWrapper<>(userVO);
queryWrapper .like("name", name);

### 重现步骤(如果有就写完整)
SELECT  FROM user WHERE name = ? AND (name LIKE ?) 

### 报错信息
name字段模糊查询，没有进行优化处理

**Comment by qmdx** [comment]
不支持优化，需要自己判断 ，或者 注解 实体 ，不写 wrapper.like 

```
@TableField(condition = SqlCondition.LIKE)
private String name;
```
