### ISSUE TITLE
UpdateById 方法，传的有id，其他属性都是null，生成的SQL数据库不能运行

### ISSUE THREAD

**Issue by xuMingHai1** [baomidou/mybatis-plus#4814]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
UpdateById 方法，传的有id，其他属性都是null，生成的SQL数据库不能运行。
`UPDATE tab WHERE id = ?` 
感觉这种情况不需要执行SQL

**Comment by miemieYaho** [comment]
自行规避
