### ISSUE TITLE
调用selectMaps()方法，为什么不管实体类日期是什么类型，返回的都是LocalDateTime类型

### ISSUE THREAD

**Issue by fangchenyong** [baomidou/mybatis-plus#4815]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用selectMaps()方法，为什么不管实体类日期是什么类型，返回的都是LocalDateTime类型

**Comment by miemieYaho** [comment]
这你得问mybatis
