### ISSUE TITLE
insert-strategy 配置对部分字段不生效

### ISSUE THREAD

**Issue by sophisticatedxie** [baomidou/mybatis-plus#4817]
### 当前使用版本(必填,否则不予处理)
v3.5.2 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 本地经过反复的单元测试，发现Long类型的  created_by 和updated_by字段无论有没有设置值， mp 都会在打印的sql中出现对应的插入语句。
org.springframework.dao.DataIntegrityViolationException: com.gaoding.gdesign.upgrade.mapper.UpgradeTaskMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Column 'created_by' cannot be null
; Column 'created_by' cannot be null; nested exception is java.sql.BatchUpdateException: Column 'created_by' cannot be null

	

### 重现步骤(如果有就写完整)
 我是springboot工程， 本地只有一张表.表中字段created_by 与updated_by 为非null。
 
 1.  配置： 
  mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 开启一级缓存
    local-cache-scope: session
    # 开启二级缓存
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      where-strategy: not_empty
 2. entity: 
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/41357203/190375178-ba4c54c7-d4e2-4d3e-9cbe-3308895a2fd0.png">
3. 单测代码@SpringBootTest(classes = UpgradeApplication.class)
public class BatchTest {

    @Autowired
    private UpgradeTaskService upgradeTaskService;

    @Test
    public void  test(){
        List<UpgradeTask> tasks=new ArrayList<>(10000);
        for (int i = 0; i < 10000; i++) {
            UpgradeTask upgradeTask=new UpgradeTask();
            upgradeTask.setUmsId(1L);
            upgradeTask.setRecordId((long) i);
            tasks.add(upgradeTask);
        }
        long l = System.currentTimeMillis();
        upgradeTaskService.saveBatch(tasks);
        System.out.println(System.currentTimeMillis()-l);
    }
}

### 报错信息
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/41357203/190375354-dcc063e5-8eb0-4d46-9be9-367cad1ed0db.png">

**Comment by miemieYaho** [comment]
注解 fill 优先级更高
