### ISSUE TITLE
希望在主包中将spring的依赖类去掉

### ISSUE THREAD

**Issue by xcocean** [baomidou/mybatis-plus#4820]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
非spring项目，集成此版本会找不到spring类。

### 重现步骤(如果有就写完整)
解决方案：降低版本3.4.3

### 报错信息
NoClassDefFoundError: org/springframework/core/GenericTypeResolver

**Comment by qmdx** [comment]
你指的是不是反射部分，新版预留了处理口子

**Comment by qmdx** [comment]
注入非 spring 框架的 GenericTypeUtils.setGenericTypeResolver 的泛型实现即可

**Comment by ghost** [comment]
我有同样的问题，
com.baomidou.mybatisplus.core.toolkit.reflect.SpringReflectionHelper.resolveTypeArguments 中 import了
org.springframework.core.GenericTypeResolver

我们项目中没有Spring的依赖，所以运行时报错
