### ISSUE TITLE
@TableField 对应列字段名有特殊字符 对应不上找不到字段列

### ISSUE THREAD

**Issue by Mrljt497** [baomidou/mybatis-plus#4827]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查询数据库，@TableField("order-id") 最终对应不上找不到字段列  会解析成 order  -后的会被切割掉

### 重现步骤(如果有就写完整)
pojo中是这样
    @TableField(“order-id”)
    private String orderId;

### 报错信息
com.microsoft.sqlserver.jdbc.SQLServerException: 列名 'order' 无效。
; bad SQL grammar []; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 列名 'order' 无效。

**Comment by rq0323** [comment]
遇到差不多的问题，但是我感觉你这个数据库字段命名规范一般是支持“_”不支持“-”吧！

**Comment by miemieYaho** [comment]
请勿使用非主流规范命名

**Comment by rq0323** [comment]
您好，邮件已接收，谢谢。
