### ISSUE TITLE
官方文档中“3.x数据库关键字如何处理？”的问答有冲突

### ISSUE THREAD

**Issue by rq0323** [baomidou/mybatis-plus#4828]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
官方问答中：在以前的版本是自动识别关键字进行处理的，但是3.x移除了这个功能。
按理说现在使用应该不会再自动加关键字转译了，但是我的版本还会自动加关键字引号处理。

### 重现步骤(如果有就写完整)
mysql改用postgres时出现不支持`符合

### 报错信息
![image](https://user-images.githubusercontent.com/45582885/190984999-d83c8914-54fb-419e-aed5-12313e87a752.png)

**Comment by miemieYaho** [comment]
来个demo

**Comment by rq0323** [comment]
您好，邮件已接收，谢谢。

**Comment by rq0323** [comment]
> 来个demo

非常抱歉，是“代码生成器（新）”的问题，字段上的注解“@TableField("`type`")”是自动生成的，请问如何兼容postgres，还是手动再去掉？  就是哪个属性是配置mysql自动转译关键字的。

**Comment by miemieYaho** [comment]
字段名规避关键字

**Comment by rq0323** [comment]
您好，邮件已接收，谢谢。
