### ISSUE TITLE
Mybatis Plus那个banner太夸张了，被霸屏了，建议小一点

### ISSUE THREAD

**Issue by ypm0313** [baomidou/mybatis-plus#483]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.0.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
banner.txt

### 重现步骤
启动应用

### 报错信息

___  ___       ______         _    _        ______  _             
|  \/  |       | ___ \       | |  (_)       | ___ \| |            
| .  . | _   _ | |_/ /  __ _ | |_  _  ___   | |_/ /| | _   _  ___ 
| |\/| || | | || ___ \ / _` || __|| |/ __|  |  __/ | || | | |/ __|
| |  | || |_| || |_/ /| (_| || |_ | |\__ \  | |    | || |_| |\__ \
\_|  |_/ \__, |\____/  \__,_| \__||_||___/  \_|    |_| \__,_||___/
          __/ |                                                   
         |___/                                              3.0.1

**Comment by qmdx** [comment]
这个已经修改 `3.0.3` 会变小
