### ISSUE TITLE
建议支持SQL HINTs

### ISSUE THREAD

**Issue by chenxi21039** [baomidou/mybatis-plus#4837]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
建议支持SQL HINT，支持给优化器建议。
https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html
https://docs.oracle.com/cd/B19306_01/server.102/b14211/hintsref.htm#i8327

**Comment by huayanYu** [comment]
只做基本的sql

**Comment by Rainsheep** [comment]
+1, 需要依赖 sql hints 强制从主库读取数据，发现 mp 没办法在 select 后面加 hint

**Comment by ColinChenX** [comment]
希望可以加这个功能，现在是需要使用Hint语法强制路由到主库，发现除了重新写个SQL语句或者在原有的SQL上判断并拼接外，没有更好的办法。
