### ISSUE TITLE
开启租户插件，框架提供的增删查改，想要在里面忽略租户拼接，怎么做

### ISSUE THREAD

**Issue by miaomiaocv** [baomidou/mybatis-plus#4841]

**Comment by VampireAchao** [comment]
文档见：https://baomidou.com/pages/aef2f2/#tenantlineinnerinterceptor

可以在`Mapper`上加`@InterceptorIgnore`去忽略

`ignoreTable`方法也是每次都会执行判断，可基于这一点实现更灵活的方案
