### ISSUE TITLE
关于自动装配问题

### ISSUE THREAD

**Issue by livk-cloud** [baomidou/mybatis-plus#4842]
mybatis-plus-boot-starter = "3.5.2"

SpringBoot3-M5删除了spring.factories的自动装配[spring boot wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes)
可以升级一下[自动装配](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes)的方式嘛

**Comment by huayanYu** [comment]
可以帮忙升级吗

**Comment by livk-cloud** [comment]
> 可以帮忙升级吗

> 需要我来提交PR嘛

**Comment by huayanYu** [comment]
> > 可以帮忙升级吗
> 
> > 需要我来提交PR嘛

恩

**Comment by livk-cloud** [comment]
> > > 可以帮忙升级吗
> > 
> > 
> > > 需要我来提交PR嘛
> 
> 恩

> 我需要提交PR的规则地址文档

**Comment by livk-cloud** [comment]
> 可以帮忙升级吗

> 已经提交PR了

**Comment by linghengqian** [comment]
- I am working on this issue.
