### ISSUE TITLE
什么时候支持spring boot 3.0？

### ISSUE THREAD

**Issue by euler-king** [baomidou/mybatis-plus#4846]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
spring boot 3.0.0版本，无法兼容，部分spring boot 中的类已经删除了。

**Comment by miemieYaho** [comment]
等mybatis发版兼容了再说

**Comment by linghengqian** [comment]
- I am working on this issue.
