### ISSUE TITLE
@InterceptorIgnore(tenantLine = "true")在select语句前自动生成的count(*)查询语句上不生效

### ISSUE THREAD

**Issue by HanYehong** [baomidou/mybatis-plus#4850]
### 当前使用版本(必填,否则不予处理)
V3.4.1

### 该问题是如何引起的？
在select SQL语句开启 @InterceptorIgnore(tenantLine = "true") 下，SQL语句本身可以成功过滤租户，但是在mp自动为select语句生成的count(*) sql未自动过滤租户，导致count(*)数=0，select SQL就不会执行了（但SQL执行实际有数）

### 重现步骤(如果有就写完整)
必现

### 报错信息
无

**Comment by miemieYaho** [comment]
调整插件顺序,放分页插件前面去
