### ISSUE TITLE
关于分页排序冲突的问题

### ISSUE THREAD

**Issue by leblog** [baomidou/mybatis-plus#4854]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

page 分页条件查询

### 重现步骤(如果有就写完整)
代码
QueryWrapper<HxPeifang> wrapper = new QueryWrapper<>();
  if(StringUtils.isNotEmpty(peifang.getFmingcheng())){
      wrapper.like("Fmingcheng", peifang.getFmingcheng());
  }
  //wrapper.orderByDesc("flastmodifytime"); //不能排序
  final Page page = peifangService.page(new Page(pageNum, pageSize),wrapper);
  return page;

### 报错信息

Error querying database.  Cause: com.microsoft.sqlserver.jdbc.SQLServerException: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

### 期望结果
`可以进行排序`

**Comment by miemieYaho** [comment]
Cause: com.microsoft.sqlserver.jdbc.SQLServerException:

**Comment by leblog** [comment]
有没有什么解决办法可以使用到排序

**Comment by qmdx** [comment]
应该是 sqlserver 的分页语法和拼接排序字段导致 SQL 异常，由于我们没有 sqlserver 的数据库环境无法重现你的问题，希望自行解决 PR 可以从 1，分页方言 2，SQL解析优化 方向入手
