### ISSUE TITLE
多租户的触发问题

### ISSUE THREAD

**Issue by KingsOfKungFu** [baomidou/mybatis-plus#4857]
### 当前使用版本(必填,否则不予处理)

<mybatis-plus.version>3.3.0</mybatis-plus.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mapper接口上 如果没有 @SqlParser(filter = true) 注解 且 xml中的SQL有 if()或者ifnull() 函数则会触发mybatis-plus的多租户模式。
	会在SQL上拼接 statementId字段。但Idea的控制台不会显示
MySQL数据库

### 报错信息

![5da9b41dd3dcb5fe15b3db235a0ff1f](https://user-images.githubusercontent.com/39298890/192474436-dc729415-4629-49a2-b331-d65677eac5b9.png)

**Comment by qmdx** [comment]
是不是分页导致 ？你关闭 SQL 优化功能

**Comment by KingsOfKungFu** [comment]
没有分页的情况也是一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月9日(星期三) 晚上6:48
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/mybatis-plus] 多租户的触发问题 (Issue #4857)





 
是不是分页导致 ？你关闭 SQL 优化功能

**Comment by miemieYaho** [comment]
用最新版给出demo

**Comment by KingsOfKungFu** [comment]
那到底是什么问题引起的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月9日(星期三) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/mybatis-plus] 多租户的触发问题 (Issue #4857)





 
用最新版给出demo

**Comment by qmdx** [comment]
给出重现 demo 后打开
