### ISSUE TITLE
关于getOne查询数据优化建议

### ISSUE THREAD

**Issue by ZShUn** [baomidou/mybatis-plus#486]
在版本3.0.1查看到getOne方法不太严谨，查询单条数据是从list当中获取第一条.这样可能客户端拿不到想要的结果，建议直接向上抛出异常.直接中断程序。
![image](https://user-images.githubusercontent.com/16457274/45581237-0ff01980-b8cd-11e8-90a6-f28782e06938.png)
![image](https://user-images.githubusercontent.com/16457274/45581247-25fdda00-b8cd-11e8-9acf-c3f3e7dbfa3f.png)

**Comment by huayanYu** [comment]
达成共识。

**Comment by huayanYu** [comment]
已修改，下个版本推出
