### ISSUE TITLE
分页插件返回结果集处理空格的问题

### ISSUE THREAD

**Issue by leblog** [baomidou/mybatis-plus#4863]
### 当前使用版本(必填,否则不予处理)

关于返回的分页结果中json对象有空格,这些空格有办法处理吗?

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/56074493/192933086-85fba28d-518e-4675-96d9-40ef19d9d66d.png)

### 报错信息
![image](https://user-images.githubusercontent.com/56074493/192933041-3b58d7ef-e4ec-4a46-b30e-24d704cc52b4.png)

**Comment by miemieYaho** [comment]
和mp无关
