### ISSUE TITLE
当字段名和数据库的关键字冲突时，会因为自动生成出来的 SQL 语句没有添加反引号 `` 导致 SQL 语法错误

### ISSUE THREAD

**Issue by samho2008** [baomidou/mybatis-plus#4868]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当字段名和数据库的关键字冲突时，会因为自动生成出来的 SQL 语句没有添加反引号 `` 导致 SQL 语法错误

### 重现步骤(如果有就写完整)
希望自动生成出来的 SQL 语句可以自动为字段名添加反引号

**Comment by lan-dian** [comment]
> 来自官方文档，自己换了一些表达

在以前的版本是自动识别关键字进行处理的，但是3.x移除了这个功能。

因为，不同的数据库对关键字的处理不同,很难维护。此外，在数据库设计时候本身不建议使用关键字。
所以，你可以自己处理关键字，方案如下

```java
@TableField(value = "`status`")
private Boolean status;
```

**Comment by samho2008** [comment]
> > 来自官方文档，自己换了一些表达
> 
> 在以前的版本是自动识别关键字进行处理的，但是3.x移除了这个功能。
> 
> 因为，不同的数据库对关键字的处理不同,很难维护。此外，在数据库设计时候本身不建议使用关键字。 所以，你可以自己处理关键字，方案如下
> 
> ```java
> @TableField(value = "`status`")
> private Boolean status;
> ```

感谢回复，其实也可以根据识别出来的数据库做相应处理，毕竟框架本身能够识别出使用的数据库类型。但是可能考虑到版本兼容性问题和性能问题就没处理了吧。目前也只能先这样解决了，感谢
