### ISSUE TITLE
3.0跟2.x关键注解不兼容, 这个是故意这样的吗

### ISSUE THREAD

**Issue by ltbyun** [baomidou/mybatis-plus#487]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3, 3.0.2

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
2.3注解名
com.baomidou.mybatisplus.annotation.TableId
com.baomidou.mybatisplus.enum.IdType

3.0.2注解名
com.baomidou.mybatisplus.annotation.TableId
com.baomidou.mybatisplus.annotation.IdType

而且有些类直接没有了, 比如下面的:
com.baomidou.mybatisplus.plugins.pagination.Pagination

**Comment by qmdx** [comment]
3.x  重构版本， 2.x 会继续维护  改动太大没法无缝
