### ISSUE TITLE
Optional支持

### ISSUE THREAD

**Issue by lamb007** [baomidou/mybatis-plus#4873]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
baseMapper中有没有计划支持Java8的Optional，可以大量简化判空代码，还是非常方便的，改起来也不麻烦吧

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
没计划
