### ISSUE TITLE
根据 whereEntity 条件，更新记录报错

### ISSUE THREAD

**Issue by yangdechang** [baomidou/mybatis-plus#4875]
### 当前使用版本(必填,否则不予处理)
版本3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
// 批量更新订单项支付时间
OmsOrderItemEntity omsOrderItemEntity = new OmsOrderItemEntity();
omsOrderItemEntity.setPayTime(payAt);
omsOrderItemDao.update(omsOrderItemEntity, Wrappers.lambdaUpdate(OmsOrderItemEntity.class).eq(OmsOrderItemEntity::getOrderId, orderId));

### 报错信息
Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'.
; Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'.; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'.

具体图片如下：
![image](https://user-images.githubusercontent.com/29271870/194700243-afa7f969-f59e-4698-8d05-1798c9359454.png)

**Comment by miemieYaho** [comment]
检查你的字段update验证策略

**Comment by yangdechang** [comment]
update验证策略没问题，其他非空字段都不会更新，只有这两个json字段更新了

**Comment by miemieYaho** [comment]
你的无法复现
