### ISSUE TITLE
Mybatis Method queryTotal execution error of sql

### ISSUE THREAD

**Issue by topherli** [baomidou/mybatis-plus#4880]
### 当前使用版本(必填,否则不予处理)
mybatis 3.5.6  mysql8.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
CICD中自动化API测试偶尔出现，是偶尔复现，并发测试中为复现

### 报错信息
![image](https://user-images.githubusercontent.com/106127912/195087784-fcce1f21-aef2-43ce-a972-617cafaf5f81.png)
代码如下：
![image](https://user-images.githubusercontent.com/106127912/195088017-5cbf2dba-3de3-4354-a904-05237c8da4bb.png)

**Comment by miemieYaho** [comment]
mp版本?

**Comment by topherli** [comment]
> mp版本?
感谢及时恢复 3.2.0

**Comment by topherli** [comment]
![image](https://user-images.githubusercontent.com/106127912/195226938-1a55429a-53b8-444b-993d-06269696b752.png)
![image](https://user-images.githubusercontent.com/106127912/195227450-00d328c3-b997-4b52-9a7c-aec554e2eb30.png)

**Comment by topherli** [comment]
> mp版本?
![image](https://user-images.githubusercontent.com/106127912/195227500-3469ead0-a326-47c0-8096-952ed96791b4.png)

![image](https://user-images.githubusercontent.com/106127912/195227450-00d328c3-b997-4b52-9a7c-aec554e2eb30.png)

**Comment by miemieYaho** [comment]
版本太老
