### ISSUE TITLE
全局配置逻辑删除后，在代码中查询的时候想忽略逻辑删除怎么处理

### ISSUE THREAD

**Issue by thinwonton** [baomidou/mybatis-plus#4884]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 问题描述
由于业务的需要，我们全局配置了逻辑删除，但是有个业务场景，需要查询包含删除和未删除的数据。查询的时候发现，不管怎么样都会带上逻辑未删除标识。
在代码中需要怎么处理才能实现呢

**Comment by qmdx** [comment]
那就不要设置为逻辑删除，用一个状态自己控制

**Comment by VampireAchao** [comment]
通过翻阅源码发现,`ignoreTable`在每次拼接条件时都会调用，可以在此处用变量控制
