### ISSUE TITLE
listByIds报错

### ISSUE THREAD

**Issue by aYongGit** [baomidou/mybatis-plus#4888]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用查询 listByIds()  报错
### 重现步骤(如果有就写完整)

使用查询 listByIds(ids)  报错，当参数ids的数组为空时报错

### 报错信息

sql异常

**Comment by miemieYaho** [comment]
自行处理
