### ISSUE TITLE
想通过反射的方式拼接lambdaQueryWrapper的查询条件,像eq这样入参的column参数如何填写呢?

### ISSUE THREAD

**Issue by Alimian** [baomidou/mybatis-plus#4889]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我想通过反射动态去拼接lambdaQueryWrapper,但是再尝试的时候eq方法里面的入参不太确定怎么填写,直接将属性名放进去运行时会报错通过反射拼条件的这种方法是否可行呢?如果可行,那么我应该如何填写 .eq(Ggkind::getRiskcode,riskcode)这样的条件的入参呢?具体代码如下:

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/40780392/196616029-0810c0b8-f3fd-4442-9907-7058e9bea177.png)

**Comment by totoro52** [comment]
我之前做过这个需求，我的做法是用普通的queryWrapper， 对反射取到的字段名做下划线处理或者取他的tableField注解的value即可
所以不需要去使用lamdba，实际上这个lamdbaQueryWrapper也是通过序列化的方式去hack字段名，然后再转换成数据库字段。

如果非要使用lamdba，实际上就是在脱裤子放屁

**Comment by Alimian** [comment]
好吧,目前是这样使用的
