### ISSUE TITLE
mybatis-plus-generator的jar包里的pom.xml有误

### ISSUE THREAD

**Issue by bthulu** [baomidou/mybatis-plus#489]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.2

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
mybatis-plus-generator-3.0.2.pom里的这段依赖有问题, maven里的scope是没有optional选项的. 
这导致所有<scope>optional</scope>的依赖都被maven识别成了<scope>compile</scope>

    <dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>2.3.9</version>
      <scope>optional</scope>
    </dependency>

正确的应该是

    <dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>2.3.9</version>
      <optional>true</optional>
    </dependency>

这里可能是mybatis-plus/mybatis-plus-generator/build.gradle里下面这段代码引起的

`optional rootProject.ext.dependencies["freemarker"]`

**Comment by miemieYaho** [comment]
升级 3.0.3版本
