### ISSUE TITLE
建议新增：first() 方法

### ISSUE THREAD

**Issue by Alexios-cd** [baomidou/mybatis-plus#4890]
### 当前使用版本(必填,否则不予处理)

    <dependency>
         <groupId>com.baomidou</groupId>
         <artifactId>mybatis-plus-boot-starter</artifactId>
         <version>3.5.2</version>
    </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我看到官网最新也就3.5.1但是用的确实是3.5.2

不是问题只是建议
### 重现步骤(如果有就写完整)
无
### 建议
![Snipaste_2022-10-19_17-50-37](https://user-images.githubusercontent.com/11305545/196658438-41c3d825-3803-4e02-b380-786a59a0da5d.png)

原意是返回一个实体对象，但是因为在线上操作时发现返回的是一个list（各种脏数据导致的）
建议新增：
baseMapper.selectFirst();
lambdaQuery().first()；
虽然这样返回的数据不一定是对的，但是会避免直接报错的现象。
虽然有方法进行limit操作，但是没有 first() 方便。

**Comment by qmdx** [comment]
不同数据库的 first One 是不一样的，你可以 List get 0
