### ISSUE TITLE
@EnumValue  read DB error!

### ISSUE THREAD

**Issue by SilenceCarrot** [baomidou/mybatis-plus#4892]
### 当前使用版本(必填,否则不予处理)
最新版本：3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
对于枚举的处理，使用注解 @EnumValue ，
``` java
@Getter
@AllArgsConstructor
public enum AppEnableEnum {
    /**
     * 可用
     */
    AVAILABLE("available"),
    /**
     * 禁用
     */
    UNAVAILABLE("unavailable"),
    ;

    @EnumValue
    private final String code;
}
```

写DB没有问题，能正常写入。
但是读DB则报错：Cause: java.lang.UnsupportedOperationException 

我看了之前的一些issues，也做了debug，但是仍不知问题原因，debug如下：
![image](https://user-images.githubusercontent.com/15966265/196911218-c87e5227-5c0a-4cd4-a930-76bb66b49ebf.png)

还请帮忙指点下，这个问题要如何排查。

补充：这个枚举类型的时候如下：
```java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName(value = "easyrun_apps")
@Accessors(chain = true)
public class Apps extends BaseAuditDO {
    /**
     * 应用名
     */
    private String appName;
    /**
     * 是否启用
     */
    @TableField(fill = FieldFill.INSERT)
    private AppEnableEnum available;
}

```

### 重现步骤(如果有就写完整)
抱歉，因为是内部项目，无法给出完成代码模块。
还请指点一二，我会给出debug信息给您。

### 报错信息
"nested exception is org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column &#39;available&#39; from result set.  Cause: java.lang.UnsupportedOperationException"

**Comment by miemieYaho** [comment]
要么jdbc驱动不支持,要么数据库连接池不支持,自己看着升级吧

**Comment by qmdx** [comment]
如上处理还是未解决，打开反馈问题
