### ISSUE TITLE
保存数据 报ID不存在  org.postgresql.util.PSQLException: ERROR: column "ID" does not exist

### ISSUE THREAD

**Issue by guozhengit** [baomidou/mybatis-plus#4895]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

原数据源为MYSQL；后迁移至postgreSql数据库；迁移至最新版依然复现

### 重现步骤(如果有就写完整)
1.数据库表主键为id；
2.dao类中字段
    @TableId(value = "ID", type = IdType.AUTO)
    private Long id;
3.保存数据调用默认方法
    this.save(contractVO);

### Cause: org.postgresql.util.PSQLException: ERROR: column "ID" does not exist
  位置：437
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "ID" does not exist
  位置：437

**Comment by miemieYaho** [comment]
pg不认大写,org.postgresql.util.PSQLException bad SQL
