### ISSUE TITLE
mp连接postgresql 类型不一致问题samllint与Boolean转换

### ISSUE THREAD

**Issue by guozhengit** [baomidou/mybatis-plus#4896]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

dao数据类型与表数据类型不一致导致解析失败
1.表数据字段为smallint
2.dao类数据类型为boolean

### 报错信息
org.postgresql.util.PSQLException: ERROR: column "is_img" is of type smallint but expression is of type boolean

**Comment by miemieYaho** [comment]
typehandler,自己处理
