### ISSUE TITLE
Sql server分页bug

### ISSUE THREAD

**Issue by lee8519** [baomidou/mybatis-plus#4899]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
由于业务复杂,sql联查最新的数据,所以自己写了sql如下
select fdp.* from tb_xx(NOLOCK) fdp	
JOIN (
	select autoid,ROW_NUMBER() over (PARTITION BY supplierId ORDER BY submitTime DESC) as r from tb_xx(nolock) 
	where dataFrom='aa' AND flag=0
) fdp1_tb on fdp1_tb.r=1 and fdp1_tb.autoid=fdp.autoid

### 重现步骤(如果有就写完整)
接口Page<XX> findList(Page<XX> page, @Param("sMap")Map<String, Object> fdps);
自定义sql
<select id="findList" resultType="FactoryDeliveryPlan">
select fdp.* from tb_xx(NOLOCK) fdp	
JOIN (
	select autoid,ROW_NUMBER() over (PARTITION BY supplierId ORDER BY submitTime DESC) as r from tb_xx(nolock) 
	where dataFrom='aa' AND flag=0
) fdp1_tb on fdp1_tb.r=1 and fdp1_tb.autoid=fdp.autoid
order by fdp.autoid desc 
</select>

### Cause: java.sql.SQLException: Incorrect syntax near 'fdp1_tb'.
; bad SQL grammar []; nested exception is java.sql.SQLException: Incorrect syntax near 'fdp1_tb'.

**Comment by qmdx** [comment]
可能是 jSqlParser 解析异常，参考 https://baomidou.com/pages/97710a/ 关闭 page 自动 sql 优化
