### ISSUE TITLE
注入逻辑缺乏灵活性，是否可以增加接口让用户定制？

### ISSUE THREAD

**Issue by baihe** [baomidou/mybatis-plus#49]
在动态注入的时候，会强制要求继承 BaseMapper，否则不会注入。
这样自己定制基础类的时候，就会受到极大的限制。
这个判断，建议放在 sqlInjector 里面，增加 shouldInject 这样的方法，让注入类自己决定是否要注入。

顺便 extractModelClass 也是强依赖 BaseMapper 的，不过至少可以自己 Override。

**Comment by qmdx** [comment]
继承 AutoSqlInjector 重新你要注入的逻辑即可，启动的时候全局配置注入你的重写子类。

**Comment by baihe** [comment]
现在是把三四个文件拷贝出来，全部自己重写。如果一开始重写，没有先仔细把相关的实现逻辑都看一遍，就会踩坑。
我的意思是，现在虽然可以重写，但是现在的设计对重写并不友好。

**Comment by qmdx** [comment]
@baihe   默认注入的是 AutoSqlInjector  其实不复杂你参考下、逻辑删除注入的是 LogicSqlInjector 类（你参考下这个）

http://mp.baomidou.com/#/logic-delete

**Comment by baihe** [comment]
嗯，我知道，我也是这么做的。
只是感觉定制的灵活性可以做的更好一点，因为现在对于 BaseMapper 的依赖太强了，我明白 BaseMapper 是比较核心的东西，但是一般公司级别或项目组定制的话，对于 BaseMapper 会有所裁剪的避免滥用，这种情况下就比较尴尬了，要把有相关依赖的实现全部拷贝出来全部改掉，因为目前对这个的改动并不「开放」。

**Comment by baihe** [comment]
现在用了一个讨巧的办法，直接把 jar 包里面的 basemapper 替换成我们自己定义的接口发布到内部仓库里，然后只需要定制 autosqlinjector 就可以了。

**Comment by qmdx** [comment]
@baihe  BaseMapper 是判断是否需要 MP  crud 的标准，后面考虑下载 BaseMapper 层在抽象一个顶级父类  Mapper 这样你的基础类基础 Mapper 然后进行裁剪

**Comment by yuxiaobin** [comment]
谁说一定要继承BaseMapper？

你自己的mapper如果不继承，就只有自定义的方法；继承了，你这个mapper就会有MP的基础CURD方法。

[表情包]

**Comment by baihe** [comment]
你试过了吗？
我一开始是用的自定的 basemapper，然后不起作用。看了一下代码，逻辑上是和 basemapper 绑定的，如果不是子类，就不触发 autoinject 类的方法。
所以只有两种办法：
1. 完全重写相关的 buidler，主要是替换到 basemapper 的判定
2. 把 jar 包的 basemapper 替换掉。

**Comment by baihe** [comment]
我采用第二种办法，主要是前两天升级了一下，然后发现改动不小，觉得维护太麻烦了，毕竟第一种办法有点 hack 的感觉。

**Comment by baihe** [comment]
如果你确实使用了自己的 basemapper，整个 mapper 和原来的 basemapper 一点关系也没有，并且只是简单的实现了自己的 injector，请不啬赐教。
谢谢。

**Comment by yuxiaobin** [comment]
进群说吧 QQ群：576493122
