### ISSUE TITLE
mybatisplus有没有相关util类，可以将前端查询的sort参数、filter参数转换为EntityWrapper的

### ISSUE THREAD

**Issue by rchlz** [baomidou/mybatis-plus#490]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
实际需求是这样的，比如前端查询的时候，需要按多个字段排序(或过滤)，前端是拼凑的一段字符，后端有没有相关的工具类直接将这些字段转换成Wrapper对象，省的自己去解析字符串一个个去写orderBy()

### 重现步骤
无

### 报错信息
无

**Comment by rchlz** [comment]
比如前端传过来的是sort=amount,desc|count,asc，后端直接解析为wrapper.orderBy("amount",false).orderBy("count",true)

**Comment by miemieYaho** [comment]
没有
