### ISSUE TITLE
如何封装返回值里面的mysql方法

### ISSUE THREAD

**Issue by yeohx** [baomidou/mybatis-plus#4901]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？
select group_concat(DISTINCT name) as names
from user
where name like （”%王%“）
group by name
不想使用xml写sql，是否可以通过java代码封装返回值里面的mysql方法。wrapper只能封装查询条件，可以封装返回值么？

**Comment by qmdx** [comment]
可以 使用 mybatis  @Select 注解写 SQL
