### ISSUE TITLE
写操作时，根据同时写入的某一字段值，动态更新另一字段值

### ISSUE THREAD

**Issue by cyhoo** [baomidou/mybatis-plus#4909]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

写操作时，根据同时写入的某一字段值，动态更新另一字段值

### 重现步骤(如果有就写完整)

字段A：值C的非对称加密值，写时自动加密，读时自动解密；（已用TypeHandler解决）
字段B：值C的SHA摘要值，写时，若值C为null，则不写入不更新，若值C为""，则写入更新均为""，若值C为其他值，则更新写入的值均为值C的SHA摘要值；（如何实现，MetaObjectHandler貌似实现不了）

### 报错信息

MetaObjectHandler设置值为null时，最终生成的sql会写入字段值为null。

**Comment by qmdx** [comment]
`MetaObjectHandler`   请确保设置值是存在的

**Comment by cyhoo** [comment]
是的，MetaObjectHandler不能设置值为null，所以有没有组件可以实现上面的需求呢？

**Comment by qmdx** [comment]
MetaObjectHandler  必须设置值，如果不设置请允许数据库字段为空，自行判断不填充
