### ISSUE TITLE
logicDelete逻辑删除值为char时，SQL拼接错误

### ISSUE THREAD

**Issue by zx472010602** [baomidou/mybatis-plus#491]
### 当前使用版本(必须填写清楚，否则不予处理)

2.0.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

使用逻辑删除值为char类型

### 重现步骤

在SpringBoot配置文件
logic-delete-value: 'Y'
logic-not-delete-value: 'N'
后，该全局String类型对象成功注入值，却在拼接时未拼入单引号导致SQL拼接后无法执行（去掉yml配置文件里的单引号同样出现该错误）

**Comment by miemieYaho** [comment]
逻辑删除java数据类型不支持char
