### ISSUE TITLE
wrapper条件如何实现两个字段比较，columnA > columnB 

### ISSUE THREAD

**Issue by Domineer-Long** [baomidou/mybatis-plus#4913]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Wrapper语法，where条件中两个字段相比较怎么写，
比如 where columnA > columnB

**Comment by miemieYaho** [comment]
apply("columnA > columnB")

**Comment by LouisLiu00** [comment]
怎么使用 lambda 语法呢? 这样在实体改变字段的时候，不需要在改所有的 column_a, column_b，而是改 :: 的方法引用就可以
