### ISSUE TITLE
实体类中有多个属性名是mysql关键字，查询报错，

### ISSUE THREAD

**Issue by mhtml** [baomidou/mybatis-plus#4914]
### 当前使用版本(必填,否则不予处理)
<mybatisplus.version>3.3.1</mybatisplus.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
@TableField 只能对 as 前面的数据库字段添加``,却不能对as 后面的类属性名加``
SELECT   selection_option AS option,selection_status AS status,selection_order AS order   FROM hy_tb_selection     WHERE (selection_classify = ?)

**Comment by totoro52** [comment]
“只能对 as 前面的数据库字段添加,却不能对as 后面的类属性名加”， 没理解这段话的含义，另外起名称要尽量避开关键词。

**Comment by mhtml** [comment]
毛海涛已收到你的邮件

**Comment by mhtml** [comment]
> “只能对 as 前面的数据库字段添加,却不能对as 后面的类属性名加”， 没理解这段话的含义，另外起名称要尽量避开关键词。

![image](https://user-images.githubusercontent.com/51606118/198955125-8c655a76-8c56-46c6-b4e0-1a32c686c171.png)
我当然懂你的意思，属性名尽量避开使用关键字，可现在没办法，接手别人的代码，不能轻易改，涉及到很多方，牵一发动全身，我上面问题的意思时，使用@TableField ，翻译过来的sql语句是这样SELECT selection_option AS option,selection_status AS status,selection_order AS order FROM hy_tb_selection WHERE (selection_classify = ?)，由于实体类属性名有多个mysql关键字而报错，@TableField只能解决数据库里面有表字段是关键字的场景，无法解决实体类中属性名有多个mysql关键字的场景

**Comment by Alimian** [comment]
tablefield注解中添加``符号包裹那个数据库字段试试呢

**Comment by mhtml** [comment]
>
