### ISSUE TITLE
MybatisPlusException:can not find cache for the property [] of entity []

### ISSUE THREAD

**Issue by Xiaobang97** [baomidou/mybatis-plus#4916]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
通过数据库generator生成的表  entity 存在自定义@TableField(exist=false)属性 xx,
使用LambdaQuery进行查询报错
LmabdaQueryWrapper<Entity> wrapper = new LambdaQueryWrapper<>();
wrapper.eq(Entity::getXx(),str);
，指定字段拿不到缓存的问题，使用QueryWrapper的wrapper.eq(“column ”,xx)可解决，除此之外还有其他方法可解决吗？
百度的其他方案试了未生效

### 报错信息

MybatisPlusException:can not find cache for the property [] of entity []

**Comment by miemieYaho** [comment]
`@TableField(exist=false)`表示这个属性不是数据库表字段,自然就不会有该属性的缓存
