### ISSUE TITLE
tablefield注解中添加``符号包裹那个数据库字段试试呢

### ISSUE THREAD

**Issue by mhtml** [baomidou/mybatis-plus#4917]
tablefield注解中添加``符号包裹那个数据库字段试试呢

_Originally posted by @Alimian in https://github.com/baomidou/mybatis-plus/issues/4914#issuecomment-1299406255_
      额 ， tablefield注解中添加``符号只能解决 数据库中表属性名是mysql的关键字情况，对于实体类中属性名是mysql关键字不起作用

**Comment by qmdx** [comment]
请避开关键词
