### ISSUE TITLE
like自动拼接%不鸡肋吗

### ISSUE THREAD

**Issue by topherli** [baomidou/mybatis-plus#4920]
### 当前使用版本(必填,否则不予处理)
跟版本没关系吧

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
首尾自动加%有点鸡肋，效率很低，中间如果加%又要写自己处理，这个%的位置明显业务控制一次最好最全面，受不了拉
比如我的业务：
like 'abc' 
like 'a%b%c'
like 'ab%'

**Comment by topherli** [comment]
还有就是很多接口提供bool condition，俺也觉得容易造成代码重复

**Comment by ztyzbb** [comment]
提供bool condition的接口，也提供不带bool condition的重载，bool condition省去写if else的麻烦岂不美哉
like首尾添加%是最常用的场景，我觉得挺好的

**Comment by totoro52** [comment]
> 还有就是很多接口提供bool condition，俺也觉得容易造成代码重复

使用这个方法就可以省略掉if，怎么会造成代码重复？
