### ISSUE TITLE
升级至3.5.2后引入了Kotlin相关的依赖，是否是预期行为？

### ISSUE THREAD

**Issue by ztyzbb** [baomidou/mybatis-plus#4921]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.1没有Kotlin相关依赖，升级到3.5.2后出现相关依赖，在ChangeLog中没有看到相关说明，请问引入Kotlin是否是预期行为？如果是预期行为，对于不使用Kotlin的项目是否可以将相关依赖排除？谢谢！

**Comment by zdxzqwz** [comment]
刚升级完打包发现多了2m，看了下jar包里面的lib文件发现多了kotlin包，我的处理方式是直接排除，暂时还没发现什么问题
![image](https://user-images.githubusercontent.com/49261002/199873921-c7ae36cd-23e1-40f1-8a8a-a2d927103384.png)

**Comment by nieqiurong** [comment]
可以删除掉,后面的版本不会携带了.
