### ISSUE TITLE
自定义sql 当有条件的时候无法执行

### ISSUE THREAD

**Issue by chengqian117** [baomidou/mybatis-plus#4923]
### 当前使用版本(必填,否则不予处理)
<dependency>
	<groupId>com.baomidou</groupId>
	<artifactId>mybatis-plus-boot-starter</artifactId>
	<version>3.5.2</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用 ${ew.customSqlSegment} 当没有查询条件时，执行正常。一旦有查询条件。不走自定义sql。

### 重现步骤(如果有就写完整)

IPage<TmsAppVo> pageAppFileVo(IPage page, @Param(Constants.EW) Wrapper<TmsAppVo> wrapper);

xml：
 <select id="pageAppFileVo" resultMap="TmsAppVoMap">
        select
                tms_app_file.file_id,
                tms_file.file_name,
                tms_file.etag,
                tms_file.md5_hash,
                tms_app_file.icon,
                tms_app_file.package_name,
                tms_app_file.version,
                tms_app_file.version_code,
                tms_app_file.app_name,
                tms_app_file.type,
                tms_app_file.model_id,
                tms_app_file.nick_name,
                tms_app_file.desctxt,
                tms_app_file.remarks,
                tms_app_file.latest,
                tms_app_file.`status`,
                tms_app_file.organ_id,
                tms_app_file.create_time,
                tms_app_file.update_time
        FROM
        tms_app_file
        left join
        tms_file on tms_app_file.file_id=tms_file.id
            ${ew.customSqlSegment}
    </select>
### 报错信息
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'md5_hash' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'md5_hash' in 'where clause'

**Comment by miemieYaho** [comment]
select a.a,b.b from tablea a left join tableb b on ...... where a.id = ? and b.id = ?

**Comment by chengqian117** [comment]
查询条件构造把表名加上就好了
