### ISSUE TITLE
3.x新特性

### ISSUE THREAD

**Issue by ChinaWim** [baomidou/mybatis-plus#4927]
### 当前使用版本(必填,否则不予处理)
2.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
2.x版本相比3.5.x版本最重要新特性有哪些？为什么要升级3.x版本

**Comment by qmdx** [comment]
2.0文档  https://baomidou.gitee.io/mybatis-plus-doc/#/
3.0文档  https://baomidou.com/

您自己对比下
