### ISSUE TITLE
TableField FieldStrategy yml全局配置无效

### ISSUE THREAD

**Issue by 251795891** [baomidou/mybatis-plus#493]
在3.0.2版本中，TableField FieldStrategy 注解全局配置无效

在TableFieldInfo中发现代码如下：
       /*
         * 优先使用单个字段注解，否则使用全局配置
         */
        if (dbConfig.getFieldStrategy() != tableField.strategy()) {
            this.fieldStrategy = tableField.strategy();
        } else {
            this.fieldStrategy = dbConfig.getFieldStrategy();
        }
 
bean中的TableField注解strategy值默认为Not_Null。

根据条件，不等时，取的是默认的not_null

当相等时，取哪个都一样。

所以yml中的配置基本没什么作用。

问题应该是由TableField的strategy default value引起的。

我的理解： 如果在bean中没指定strategy ，  则判断 yml是否全局配置过，如果没配置过再默认

**Comment by miemieYaho** [comment]
下个版本上修复

**Comment by miemieYaho** [comment]
尝试使用 3.0.4-SNAPSHOT 快照
