### ISSUE TITLE
saveBatch在@TableId type = IdType.AUTO 数据库设置ID自增，但是保存后集合里的对象ID没有注入回来

### ISSUE THREAD

**Issue by qunqunzq** [baomidou/mybatis-plus#4938]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

saveBatch在@TableId type = IdType.AUTO 数据库设置ID自增，但是保存后集合里的对象ID没有注入回来。

**Comment by miemieYaho** [comment]
那就是mybatis不支持

**Comment by qunqunzq** [comment]
> 那就是mybatis不支持

真假！单个保存就没问题 有id返回

**Comment by miemieYaho** [comment]
executorType不一样

**Comment by jsercom** [comment]
nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: java.lang.NullPointerException 
报错如上

**Comment by shuaizai88** [comment]
什么数据库？

**Comment by jsercom** [comment]
> 什么数据库？

DB2

**Comment by qmdx** [comment]
> > 什么数据库？
> 
> DB2

可能是 Jdbc3KeyGenerator 不能很好地支持 DB2 这边也没有测试数据，希望自行解决 PR 或者分享解决办法，或者使用默认雪花算法
