### ISSUE TITLE
表注释、字段注释问题，TableName，TableField注解修改

### ISSUE THREAD

**Issue by TannnnnnnnnnnnnnnnK** [baomidou/mybatis-plus#4941]
### 当前使用版本(必填,否则不予处理)
<mybatis-plus-boot-starter.version>3.4.2</mybatis-plus-boot-starter.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
没有问题，期望新增特性
总结：TableName注解增加 comment属性，表示数据库表的注释；TableField注解增加 comment属性，表示数据库表字段的注释

### 重现步骤(如果有就写完整)

需求场景：
1，每个数据库表对应的 service里面都有一个 checkAndGetById的方法，功能就是按ID查找数据库记录，返回实体类
`

    public T checkAndGetById(Long id) {
        T t = baseRepo.getById(id);
        BaseClientException.throwIf(t == null, "{} 数据不存在 {}",
                getTableComment(), id);
        return t;
    }

`
2，但是这个方法仅仅只是 抛异常时候的提示文字有变化，其他代码都一样
3，所以希望有个地方能获取到数据库表的注释
4，正好mybatis-plus有TableName，TableField注解，希望这两个注解增加comment属性，并且提供获取表注释、字段注释的方法

### 报错信息

-

**Comment by miemieYaho** [comment]
你想加的对mp来说没有一点用诶

**Comment by TannnnnnnnnnnnnnnnK** [comment]
> 你想加的对mp来说没有一点用诶

表注释、字段注释没有用到的地方么，类似的表字段长度这些属性，不考虑未来可能需要使用的场景？

**Comment by TannnnnnnnnnnnnnnnK** [comment]
> 注释



> 你想加的对mp来说没有一点用诶

呵呵
