### ISSUE TITLE
删除操作报错

### ISSUE THREAD

**Issue by ESHidden** [baomidou/mybatis-plus#495]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本
2.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
  EntityWrapper<WxTxDetail> ew = new EntityWrapper<WxTxDetail>();
            ew.where("check_date = {0}", info.get("checkDate"));
            Map<String,Object> params = new HashMap<>();
            params.put("check_date",info.get("checkDate"));
            wxMapper.delete(ew);
### 重现步骤

  EntityWrapper<WxTxDetail> ew = new EntityWrapper<WxTxDetail>();
            ew.where("check_date = {0}", info.get("checkDate"));
            Map<String,Object> params = new HashMap<>();
            params.put("check_date",info.get("checkDate"));
            wxMapper.delete(ew);

### 报错信息
2018-09-18 17:21:46.842  WARN 10352 --- [nio-8889-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

**Comment by ESHidden** [comment]
> ### 当前使用版本(必须填写清楚，否则不予处理)
> 当前版本
> 2.3
> 
> ### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
> 2018-09-18 17:21:46.842 WARN 10352 --- [nio-8889-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
> 
> ### Error updating database. Cause: com.baomidou.mybatisplus.exceptions.MybatisPlusException: org.postgresql.util.PSQLException: ResultSet 中找不到栏位名称 Extra。
> ### The error may involve defaultParameterMap
> ### The error occurred while setting parameters
> ### Cause: com.baomidou.mybatisplus.exceptions.MybatisPlusException: org.postgresql.util.PSQLException: ResultSet 中找不到栏位名称 Extra。
> ### 重现步骤
> ### 报错信息

**Comment by miemieYaho** [comment]
sql打印以及代码使用能截个图么?

**Comment by miemieYaho** [comment]
你不发出来哪知道怎么回事?那么多人用都正常,就你们有问题怎么看?

**Comment by ESHidden** [comment]
明天我把完整的报错信息也贴来

**Comment by ESHidden** [comment]
我换成3.0.3版本就好了
