### ISSUE TITLE
selectById 这个方法传了id值返回对象是null，表里有这条记录

### ISSUE THREAD

**Issue by zqb666** [baomidou/mybatis-plus#4953]
### 当前使用版本(必填,否则不予处理)

3.5.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.2也有这个问题 导致saveOrUpdate和saveOrUpdateBatch的时候 实体类里有id值的情况下 也走了save ，没有走update 希望官方尽快解决下这个严重bug

### 重现步骤(如果有就写完整)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/6092525/202092479-936554f4-5675-46b4-a93a-a8b7fb6161f0.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/6092525/202092514-7fc82a68-111d-4538-90f0-eb3f8cf79efb.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/6092525/202092573-b4e14c4f-000e-404a-8f7e-b46b3fd79c1d.png">

表里有1的这个主键

### 报错信息
selectById返回null
saveOrUpdate或者 saveOrUpdateBatch ，实体类里有id值，没走update走了save，报mybatis plus saveOrUpdateBatch BatchUpdateException: Duplicate entry '' for key '.PRIMARY'

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by zqb666** [comment]
没事了 是 项目中用了多租户功能 ，用了mybatis 多租户插件 intercepetor 引起的 我用swagger调试的时候没传租户编码
