### ISSUE TITLE
xxxMapper类中注解无法正常运行

### ISSUE THREAD

**Issue by Oroy188** [baomidou/mybatis-plus#4954]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

从mybaits升级到mybaits plus，在mapper类中
![image](https://user-images.githubusercontent.com/49527956/202119895-f26f7e9c-f468-4b1d-b913-97837ec7f694.png)
运行此方法直接卡住，断点查看在报错但最后没有抛出来，感觉并不完全兼容mybatis，或者哪里没配置好，官网上的配置都配置了

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by Oroy188** [comment]
抱歉  是是其他的问题 不好意思
