### ISSUE TITLE
采用了MybatisPlus提供的TenantLineInnerInterceptor插件复杂查询报Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","

### ISSUE THREAD

**Issue by zqb666** [baomidou/mybatis-plus#4955]
### 当前使用版本(必填,否则不予处理)
3.5.2 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

采用了MybatisPlus提供的TenantLineInnerInterceptor，使用mybatis  plus多租户插件的时候 使用复杂的业务sql查询 报错，如果换成简单的单表查询或者两表联合查询就不会报错，
加了 @InterceptorIgnore(tenantLine = "true") 过滤多租户逻辑后不报错了，请问这个是什么原因引起的？看报错好像是分页的但是我没用到分页

### 重现步骤(如果有就写完整)

  <select id="selectRiskPatientsAll" resultMap="PatVoMap">
        SELECT a.*,b.event_time as ry_time,c.id as rk_id,c.rk_time,c.zz_doctor_name ,t3.zd_name,t3.zd_ident,t3.zd_sign,t5.dev_code,
        t5.dev_type,a.hospital_number as d_hospital_number,rr.pgpf_point_type,rr.event_time,rr.pgpf_point_type,
        pg.id as rid,pg.pgpf_time as pg_pgpf_time,pg.type as pg_type,pg.hospital_number as pg_hospital_number,pg.point_id
        FROM (select * from  yx_patient
        <where>
            is_deleted = 0
            and hospital_number is not null
            <if test="patient != null and patient != ''">
                and (patient_ident = #{patient} or patient_name like concat('%',#{patient},'%') )
            </if>
            and is_leave = 0
            and dept_ident in
            <foreach collection="deptIdents" index="index" item="time" open="(" separator="," close=")">
                #{time}
            </foreach>
        </where>
        )a
        INNER JOIN
        (SELECT patient_ident,hospital_number,MAX(event_time) as event_time FROM yx_hl7_event
        WHERE event_type = 1
        GROUP BY patient_ident,hospital_number,event_type) b
        on a.patient_ident = b.patient_ident
        and b.hospital_number = b.hospital_number
        INNER JOIN
        (SELECT t2.id,t2.patient_ident,t2.bed_number,t2.hospital_number,t2.rk_time,t2.zz_doctor_name FROM yx_hl7_rk_detail t2,
        (SELECT MAX(rk_time) as rk_time,patient_ident,hospital_number FROM yx_hl7_rk_detail
        GROUP BY patient_ident,hospital_number) c2
        where  t2.patient_ident = c2.patient_ident and t2.hospital_number = c2.hospital_number and t2.rk_time = c2.rk_time
        ) c
        on c.patient_ident = a.patient_ident and c.hospital_number = a.hospital_number
        left join
        yx_hl7_rk_zd_detail t3
        on a.patient_ident = t3.patient_ident and c.rk_time = t3.rk_time
        left join
        (SELECT * FROM yx_dev_bind WHERE id in
        (SELECT max(id) FROM
        yx_dev_bind GROUP BY patient_ident
        ))t4
        on a.patient_ident=t4.patient_ident
        left JOIN yx_dev_detail t5
        on t4.dev_code = t5.dev_code
        INNER JOIN
        (
        SELECT r1.event_time as event_time,r1.hospital_number,r1.pgpf_point_type,r2.id,r2.pgpf_point_name FROM
        (SELECT max(event_time) as event_time,hospital_number, event_type as  pgpf_point_type FROM yx_hl7_event WHERE event_type = 1
        GROUP BY hospital_number,event_type
        UNION
        SELECT max(rk_time) as event_time, hospital_number,3 as  pgpf_point_type FROM yx_hl7_rk_detail WHERE is_cancle = 0
        GROUP BY hospital_number
        UNION
        SELECT max(event_time) as event_time, hospital_number,event_type as pgpf_point_type FROM yx_hl7_event WHERE event_type in (8,9,10)
        GROUP BY hospital_number,event_type
        UNION
        SELECT aa1.event_time as event_time,aa1.hospital_number as hospital_number ,if(aa2.event_type = 14,-1,13)as pgpf_point_type FROM
        (SELECT max(event_time) as event_time, hospital_number FROM yx_hl7_event WHERE event_type in (13,14)
        GROUP BY hospital_number) aa1,yx_hl7_event aa2
        WHERE aa2.event_time = aa1.event_time and aa2.hospital_number = aa1.hospital_number
        ) r1 ,yx_pgpf_point r2
        WHERE r1.pgpf_point_type in (1,3,8,9,10,13) and r2.pgpf_point_type = r1.pgpf_point_type
        and r2.type = 1 and r2.is_enable = 1 and r2.is_deleted = 0 and r2.is_remind = 1
        ORDER BY event_time DESC
        ) r1
        <where>
            r1.pgpf_point_type in (1,3,8,9,10,13)
            <if test="pointType != null ">
                and r1.pgpf_point_type = #{pointType}
            </if>
        </where>
        ORDER BY event_time DESC
        ) rr
        on a.hospital_number = rr.hospital_number
        and rr.hospital_number is not null
        and rr.event_time is not null
        and rr.event_time &gt;= b.event_time
        LEFT JOIN
        (
        select pg2.* from
        (
        select max(p1.pgpf_time) as pgpf_time ,p1.type,p1.hospital_number
        from yx_pgpf_cfg_reocrd p1,yx_pgpf_cfg_reocrd_detail p2
        where p1.id = p2.record_id
        and p2.doc_content is not null
        group by p1.hospital_number,p1.type
        ) pg1,yx_pgpf_cfg_reocrd pg2
        where pg2.hospital_number = pg1.hospital_number and pg2.type = pg1.type and pg2.pgpf_time = pg1.pgpf_time
        ) pg
        on pg.hospital_number = a.hospital_number and pg.pgpf_time &gt;= b.event_time
        order by a.bed_number asc ,a.hospital_number desc ,b.event_time desc
    </select>

调用的地方：
 List<VtePatientHomePageOutVO> patientInfoList;
  patientInfoList = vtePatientMapper.selectListPatientsAll(null,vtePatientPararm.getPatient(),
                    vtePatientPararm.getIsLeave(),vtePatientPararm.getType(), ContextUtil.getName());
### 报错信息

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 2, column 59.

Was expecting one of:

    ";"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "INTO"
    "START"
    "WINDOW"
    <EOF>

**Comment by huayanYu** [comment]
太复杂了， 处理不了，自己sql处理。
