### ISSUE TITLE
&rewriteBatchedStatements=true 设置对saveOrUpdateBatch不生效吗？

### ISSUE THREAD

**Issue by YS1127** [baomidou/mybatis-plus#4957]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
批量插入或者更新时候，使用service提供的saveOrUpdateBatch方法，插入慢，修改数据库连接的设置，开启rewriteBatchedStatements=true，saveBatch方法是生效了，但是saveOrUpdateBatch方法不生效

**Comment by rickstar666** [comment]
同问，楼主解决了吗

**Comment by YS1127** [comment]
时间有点久远了，好像是换了种方式，没用saveOrUpdateBatch方法了
