### ISSUE TITLE
mybtis plus批量删除问题

### ISSUE THREAD

**Issue by h13481717323** [baomidou/mybatis-plus#4958]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

更换了3.5.2还是存在这个问题，前端选择一条数据，将它的id传到后台，走的是批量删除（一条或者多条数据都走这个接口），然后我发现后台跟他id相似的都被删除掉了。我查看了前端请求的负载，确实只有一个我选择的id，后台debug也只接收到那个id，但是进行删除时，反应更新了多条数据，数据库里相似id的都被删掉了

### 重现步骤(如果有就写完整)
数据的id是1593985259969482752，1593985259969482753，1593985259969482754，1593985259969482755，选择删除其中一个，其他几个也一起被删掉

### 报错信息

无报错信息

**Comment by miemieYaho** [comment]
给出你的复现demo证明是mp的问题

**Comment by h13481717323** [comment]
这是我自己复现的demo，麻烦您那边试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 中午12:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] mybtis plus批量删除问题 (Issue #4958)





 
给出你的复现demo证明是mp的问题

**Comment by h13481717323** [comment]
排查到了应该是我这边的问题，不好意思了
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 中午12:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] mybtis plus批量删除问题 (Issue #4958)





 
给出你的复现demo证明是mp的问题

**Comment by h13481717323** [comment]
因为我直接用sql语句操作mysql也会全删

**Comment by h13481717323** [comment]
因为in里输入19位的long，不加引号的话mysql只会匹配前16位，也就是double的范围
