### ISSUE TITLE
新版有支持复合主键的计划吗

### ISSUE THREAD

**Issue by bthulu** [baomidou/mybatis-plus#496]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.2

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
有些时候还是很需要复合主键的, 能省很多事, 不知道mybatis plus有原生支持复合主键的计划没

**Comment by miemieYaho** [comment]
没有
