### ISSUE TITLE
实体只有id，并且标注了 @TableId(value = "id", type = IdType.INPUT)，但是并没有走 MetaObjectHandler

### ISSUE THREAD

**Issue by Fyuxuan** [baomidou/mybatis-plus#4964]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体只有id，并且标注了 @TableId(value = "id", type = IdType.INPUT)，但是并没有走 MetaObjectHandler，在id属性上加上了 @TableField(fill = FieldFill.INSERT) 也不走，
但是如果再随便加一个字段，标记 @TableField(value = "creator", fill = FieldFill.INSERT)，就会走 MetaObjectHandler 了

排除了配置有问题 或者姿势有问题，因为如果有问题，随便加一个字段 标记 @TableField(value = "creator", fill = FieldFill.INSERT)，为啥就走 MetaObjectHandler 了

**Comment by miemieYaho** [comment]
id是id,字段是字段,分开的

**Comment by miemieYaho** [comment]
IdType.INPUT = 你自己代码里set值

**Comment by qmdx** [comment]
ID 生成器 https://baomidou.com/pages/568eb2/
