### ISSUE TITLE
是否可以支持@PageableDefault的分页配置

### ISSUE THREAD

**Issue by youngledo** [baomidou/mybatis-plus#4965]
### 当前使用版本(必填,否则不予处理)

3.4.34

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据分页是很频繁的业务，当前mp的分页是自己实现的，而很多时候分页参数用的Spring Boot Data官方的@PageableDefault，这样就会造成mp的分页与@PageableDefault需要进行转换，希望mp能支持@PageableDefault，这样便于处理请求和响应的分页。

或许认为没有必要去适配，但@PageableDefault确实很好用，毕竟与@Controller无缝衔接。如果作者同意，我可以PR。

### 重现步骤(如果有就写完整)

无

### 报错信息

无

**Comment by miemieYaho** [comment]
你需要的是`Pageable`转成mp的`Ipage`,自己写个工具类转就行了.mp不会强依赖spring data

**Comment by youngledo** [comment]
行吧（可不可以轻量依赖下data包），就是需要显示的做下转换，不是特别优雅

**Comment by miemieYaho** [comment]
不会依赖
