### ISSUE TITLE
MP不能知道当前数据库表已存在数据的自增ID

### ISSUE THREAD

**Issue by esbug** [baomidou/mybatis-plus#4967]
### 重现步骤
数据库手动导入过几十条数据，通过代码进行数据插入操作时，mybatis-plus不能知道当前主键ID自增数。所以抛出了key 存在的错误。

**Comment by miemieYaho** [comment]
自增是吧,和mp无关

**Comment by qmdx** [comment]
不知道，请自行处理

**Comment by rhdai** [comment]
遇到同样的问题
使用select nextval('sys_permission_id_seq'::regclass) 结果是29   但是mp插入的时候提示id18已存在
