### ISSUE TITLE
一个获取数据的bug

### ISSUE THREAD

**Issue by TheLardoo** [baomidou/mybatis-plus#4972]
### 当前使用版本(必填,否则不予处理)
![image](https://user-images.githubusercontent.com/27659152/203909327-07e585c9-2cf6-43b6-990c-c1fdbe8691bd.png)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用同一个page实例作为参数，查询两个page

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/27659152/203909522-155da5e8-e8b4-4072-936e-dd2b715dcb9c.png)

![image](https://user-images.githubusercontent.com/27659152/203909530-8c27174a-f55d-4521-b8a0-c80a6b0b416a.png)

### 报错信息
无法获取数据

**Comment by miemieYaho** [comment]
就这样的
