### ISSUE TITLE
使用MybatisPlus提供的多租户插件, 根据条件查询数据库表 报Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="

### ISSUE THREAD

**Issue by lishuyanla** [baomidou/mybatis-plus#4974]
### 当前使用版本(必填,否则不予处理)
mybatis-plus.version -> 3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
按照官方文档使用 mybatis-plus 多租户插件，根据条件查询数据库所有表，都用到分页，情况如下：

1、第一种方式，使用xml纯sql方式，报Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
<select id="selectPageDbTableList" resultMap="GenTableResult">
        select table_name, table_comment, create_time, update_time from information_schema.tables
        where table_schema = (select database())
        AND table_name NOT LIKE '%xxl_job_%' AND table_name NOT LIKE '%gen_%'
        AND table_name NOT IN (select table_name from gen_table)
        <if test="genTable.tableName != null and genTable.tableName != ''">
            AND lower(table_name) like lower(concat('%', #{genTable.tableName}, '%'))
        </if>
        <if test="genTable.tableComment != null and genTable.tableComment != ''">
            AND lower(table_comment) like lower(concat('%', #{genTable.tableComment}, '%'))
        </if>
        <if test="genTable.params.beginTime != null and genTable.params.beginTime != ''">
            AND date_format(create_time,'%y%m%d') &gt;= date_format(#{genTable.params.beginTime},'%y%m%d')
        </if>
        <if test="genTable.params.endTime != null and genTable.params.endTime != ''">
            AND date_format(create_time,'%y%m%d') &lt;= date_format(#{genTable.params.endTime},'%y%m%d')
        </if>
        order by create_time desc
    </select>
实际输出 ：
select table_name, table_comment, create_time, update_time from information_schema.tables
where table_schema = (select database())
  AND table_name NOT LIKE '%xxl_job_%' AND table_name NOT LIKE '%gen_%'
  AND table_name NOT IN (select table_name from gen_table)
order by create_time desc

2、第二种方式，使用 QueryWrapper<Object> 拼接sql方式，报Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "=" "="
![image](https://user-images.githubusercontent.com/40929609/203947878-0707e613-9b8e-4292-a956-4daaee3a259a.png)
![image](https://user-images.githubusercontent.com/40929609/203947935-6c2b2ace-4916-4ae8-a610-97b76ad1516c.png)

### 重现步骤(如果有就写完整)
启用多租户插件，运行如下sql：

select table_name, table_comment, create_time, update_time from information_schema.tables
where table_schema = (select database())

### 报错信息
第一个方式的报错信息：
![image](https://user-images.githubusercontent.com/40929609/203949791-75824932-2bbf-407b-8fc3-e981c424ef70.png)

第二个方式的报错信息
![image](https://user-images.githubusercontent.com/40929609/203948205-4457a354-5d08-4537-a809-059c05a2ed5a.png)

**Comment by lishuyanla** [comment]
当取消多租户插件时，测试结果两种方式都是成功的，无报错。

**Comment by miemieYaho** [comment]
jsqlparser 不支持解析

**Comment by lishuyanla** [comment]
使用xml纯sql方式也不支持吗？

**Comment by lishuyanla** [comment]
或者是使用注解方式，过滤特定的方法，排除 SQL 解析

**Comment by miemieYaho** [comment]
可以加注解不走租户插件

**Comment by lishuyanla** [comment]
好的，加上 @InterceptorIgnore(tenantLine = "true") 已解决
