### ISSUE TITLE
MybatisPlus 分页插件无效，一直返回所有的数据

### ISSUE THREAD

**Issue by qiao-zhi** [baomidou/mybatis-plus#4975]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
引入分页插件之后，想进行分页。 确定Inteceptor注入进去了，就是没生效。

### 重现步骤(如果有就写完整)
1. 注入
<img width="879" alt="image" src="https://user-images.githubusercontent.com/30372677/204133069-3c66ca4c-4fb9-4b98-a46c-97ee0a015b5b.png">
2. 使用
<img width="697" alt="image" src="https://user-images.githubusercontent.com/30372677/204133083-f38a51eb-0d8c-463f-b456-ee19d9eb6818.png">
3. 结果
<img width="904" alt="image" src="https://user-images.githubusercontent.com/30372677/204133157-f2036700-d4c3-4c7c-97ba-ee3951006012.png">
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/30372677/204133169-e4e773d9-0b83-4f5b-b64c-1c5238da91b2.png">

### 报错信息
无报错

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples
