### ISSUE TITLE
建议com.baomidou.mybatisplus.core.metadata.IPage#convert支持并行

### ISSUE THREAD

**Issue by Dlinw** [baomidou/mybatis-plus#4976]
建议com.baomidou.mybatisplus.core.metadata.IPage#convert支持并行
可能需要在该方法中做一些属性的查询与填充，这些填充本身没有任何状态，所以可以支持并行计算。

**Comment by miemieYaho** [comment]
并行是无序的,你喜欢并行就自己写个utils搞
