### ISSUE TITLE
分页查询 COUNT () 括号里没有 *

### ISSUE THREAD

**Issue by crossyourheart** [baomidou/mybatis-plus#4979]
### 当前使用版本(必填,否则不予处理)

 <version>3.4.1</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

若依框架 将mybatis 替换成mybatis-plus ，用分页插件 sql语句中的 COUNT () 括号里没有 * ，导致sql执行报错。
但是直接使用Pagehelper.startPage() 可以。

### 报错信息

![image](https://user-images.githubusercontent.com/31943751/204429525-592c3121-10c1-4774-b10d-1f9d8c3dbbd7.png)

**Comment by miemieYaho** [comment]
最新版

**Comment by fun-huan** [comment]
我跟你遇到了同样的问题，最后发现是依赖冲突导致的，你可以看下你工程里面是否有高版本的jsqlparser包。
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>

**Comment by crossyourheart** [comment]
> 我跟你遇到了同样的问题，最后发现是依赖冲突导致的，你可以看下你工程里面是否有高版本的jsqlparser包。 com.github.jsqlparser jsqlparser
我是升级成最新的mybatis-plus 之后，发现启动报错。也是依赖冲突，排除了pagehelper 中的 mybatis  就可以了。

**Comment by boxzhang88** [comment]
若依整合Mybatis-plus报错select count()去掉这个依赖就行了

        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jsqlparser</artifactId>
                    <groupId>com.github.jsqlparser</groupId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by Qwenjin** [comment]
不是Jsqlparser的问题，参考：https://github.com/baomidou/mybatis-plus/issues/5020

**Comment by XuHaodong-github** [comment]
> 若依整合Mybatis-plus报错select count()去掉这个依赖就行了
> 
> ```
>     <dependency>
>         <groupId>com.github.pagehelper</groupId>
>         <artifactId>pagehelper-spring-boot-starter</artifactId>
>         <exclusions>
>             <exclusion>
>                 <artifactId>jsqlparser</artifactId>
>                 <groupId>com.github.jsqlparser</groupId>
>             </exclusion>
>         </exclusions>
>     </dependency>
> ```

这个有用
