### ISSUE TITLE
自定义page时，变更了原来的字段，但是实际返回并没有

### ISSUE THREAD

**Issue by telami** [baomidou/mybatis-plus#498]
### 当前使用版本(必须填写清楚，否则不予处理)
**com.baomidou:mybatis-plus-boot-starter:3.0.3**
### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
再返回分页数据时，leader规定返回参数不能使  current，size，total，

必须返回pageSize，pageCurrent，pageTotal

如图所示我实现了IPage
![image](https://user-images.githubusercontent.com/25978237/45727945-6f656680-bbf8-11e8-9d49-22f9321e0202.png)
并且debug时返回参数已经变为了
![image](https://user-images.githubusercontent.com/25978237/45727986-96bc3380-bbf8-11e8-9db1-78531c614e70.png)
但是！！！！
返回参数仍是
![image](https://user-images.githubusercontent.com/25978237/45728009-ae93b780-bbf8-11e8-9e8c-f7d8c594ecfc.png)

不知道在哪里拦截了，help me

**Comment by telami** [comment]
@akuma @yourchanges 求救。。。
我觉得leader这个决定纯粹闲的，但是没办法。。

**Comment by miemieYaho** [comment]
定义你这`pageSize，pageCurrent，pageTotal`仨的 get 方法, json 化是根据 get 方法来的
