### ISSUE TITLE
LambdaUpdateWrapper.set()期待加下val和column的类型一致性检查

### ISSUE THREAD

**Issue by cikai** [baomidou/mybatis-plus#4985]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
LambdaUpdateWrapper.set(DbEntity::String, ArrayList<String>);

**Comment by VampireAchao** [comment]
由于eq、ne、gt、set这些基本方法都在AbstractWrapper里，如果要这个泛型检查的话，需要在`AbstractLambdaWrapper`中`@Override`这些方法，目前而言数量有点多，暂时无计划考虑但欢迎`PR`
