### ISSUE TITLE
自定义分页查询，带map参数报错

### ISSUE THREAD

**Issue by cui19951005** [baomidou/mybatis-plus#499]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
2.x切换到3.x后public ipage list(page,map)方法报错
Parameter 'status' not found. Available parameters are [page, params, param1, param2]
### 重现步骤

public ipage list(page,map)

### 报错信息
Parameter 'status' not found. Available parameters are [page, params, param1, param2]

**Comment by miemieYaho** [comment]
自定义分页多个入参 用`@Param`注解取值

**Comment by lilong19970214** [comment]
这个问题我找个两个文档也没有解决，但是后来恍惚中用一种方式解决了。希望能帮到你。希望这不是网上的那种千篇一律的答案！
![微信图片_20191210093349](https://user-images.githubusercontent.com/40228927/70487400-32083400-1b30-11ea-85f2-2afe6d7e4a3b.png)
这是是Dao传递map的时候方式，
![image](https://user-images.githubusercontent.com/40228927/70487427-4ba97b80-1b30-11ea-9de9-734f30a295bf.png)
Xml中以这种方式取值
