### ISSUE TITLE
Native Build Tools构建本地可执行文件 报错

### ISSUE THREAD

**Issue by tiro8183** [baomidou/mybatis-plus#4994]
### 当前使用版本(必填,否则不予处理)
JDK Version(required): graalvm-ce-java17-22.3.0

SpringBoot Version(required): 3.0.0

mybatis-plus-boot-starter: 3.5.2.7-SNAPSHOT

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Native Build Tools构建本地可执行文件时出现

### 重现步骤(如果有就写完整)
mvn clean native:compile -Pnative
Native Build Tools构建本地可执行文件时出现

### 报错信息
![image](https://user-images.githubusercontent.com/28704881/205780282-7c05f5f1-a90a-4f85-afe2-d2bc971bd666.png)

**Comment by tiro8183** [comment]
这是我的项目:https://github.com/tiro8183/shape2database.git

**Comment by linghengqian** [comment]
- You can generate graalvm reachability metadata in conditional agent mode for your unit tests and submit them to https://github.com/oracle/graalvm-reachability-metadata.  mybatis-plus does not have CI to test.

**Comment by LeeMeo** [comment]
我们最近也同样在尝试springboot3.0的native image build，看到mybatis-plus很多地方目前都不支持，目前打算回退到mybatis框架。

**Comment by LeeMeo** [comment]
查了一下，目前基本确定是由于mybatis3目前并不支持AOT编译，已经有人提出了这个issue，见链接https://github.com/mybatis/mybatis-3/issues/2747

**Comment by the-tsing** [comment]
不是mybatis的问题，我将mybatisplus换成mybatis 3.5.10再编译，结果没问题能通过

**Comment by LeeMeo** [comment]
> 不是mybatis的问题，我将mybatisplus换成mybatis 3.5.10再编译，结果没问题能通过

确定执行的是springboot3.0的mvn -Pnative native:compile么？还是只是mvn compile？

**Comment by cuihj** [comment]
> > 不是mybatis的问题，我将mybatisplus换成mybatis 3.5.10再编译，结果没问题能通过
> 
> 确定执行的是springboot3.0的mvn -Pnative native:compile么？还是只是mvn compile？

mybatis 没问题

**Comment by gogolin001** [comment]
确定就是mybatis的问题，他不支持aot编译。

**Comment by lanPeiYu** [comment]
mybatis 3.5.12 may fix this problems

**Comment by developerworks** [comment]
There is no latest artifacts in maven central repo after `mybatis-plus-boot-starter/3.5.3.1`

**Comment by nieqiurong** [comment]
#5527  统一至此处讨论
