### ISSUE TITLE
为啥maven仓库里没有3.5.2.1~3.5.2.6的包呢

### ISSUE THREAD

**Issue by KerwinAusten** [baomidou/mybatis-plus#4995]
我看小版本都到3.5.2.7-SNAPSHOT了

**Comment by LeeMeo** [comment]
同样头疼中，目前项目用的都还是maven，得用gradle编译之后自己手工上传到maven仓库，才能支持原先的项目适配。

**Comment by qmdx** [comment]
查看文档如何使用快照  https://baomidou.com/pages/bab2db/
