### ISSUE TITLE
PostgreSQL JSONB 查询符号问题

### ISSUE THREAD

**Issue by O-Marshal** [baomidou/mybatis-plus#4996]
### 当前使用版本(必填,否则不予处理)

3.5.2

请问 PostgreSQL JSONB 查询中的`?`怎么书写？如何转义？直接使用以下写法 `?` 会被转义为 `Null`值

`QueryWrapper<ArchiveEntity>().apply("groups::jsonb ?| array['aaa1']")`

搜索了半天没有找到有效答案，有人说双问号，试了也没有任何作用，求教正确写法

**Comment by miemieYaho** [comment]
不知道,百度查吧
