### ISSUE TITLE
MyBatisPlus still not supporting SpringBoot3.0

### ISSUE THREAD

**Issue by Bahramudin** [baomidou/mybatis-plus#4997]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

Not supporting SpringBoot3.0

### 报错信息

org.apache.ibatis.binding.BindingException: Invalid bound statement (not found):

**When MyBatisPlus will be updated to support SpringBoot3.0? SpringBoot3.0 already officially released, but the problem with MP is still present.**
Thanks!

**Comment by daixixidai** [comment]
we are waitting for it for a long time。haha

**Comment by miemieYaho** [comment]
3.5.2.7-SNAPSHOT

**Comment by aispringli** [comment]
> 

do you have a release plan?

**Comment by aispringli** [comment]
> 3.5.2.7-SNAPSHOT

do you have a release plan?

**Comment by lixiaolong117** [comment]
支持SpringBoot3.0的正式版，什么时候能发布呢？大佬给个时间点呗～

**Comment by miemieYaho** [comment]
> > 3.5.2.7-SNAPSHOT
> 
> do you have a release plan?

你们试过这个版本能用就发

**Comment by miemieYaho** [comment]
> 支持SpringBoot3.0的正式版，什么时候能发布呢？大佬给个时间点呗～

你们试过这个版本能用就发

**Comment by Bahramudin** [comment]
@miemieYaho When I tried, I get this error:
```
Could not find artifact org.mybatis.spring.boot:mybatis-spring-boot-starter:jar:3.5.2.7-SNAPSHOT

Try to run Maven import with -U flag (force update snapshots)
```

Also, get the same error whit **mybatis-plus-boot-starter**

```
Could not find artifact com.baomidou:mybatis-plus-boot-starter:jar:3.5.2.7-SNAPSHOT

Try to run Maven import with -U flag (force update snapshots)
```

**I think this bug is very easy to solve, but I don't know why till now did not get solved. If you do not have the plan to release a stable version that can support SpringBoot3.0, and want to stack in SpringBoot version < 3.0, then you can tell us here to not wait for this framework and start to use other frameworks.
Thanks!**

**Comment by linghengqian** [comment]
> @miemieYaho When I tried, I get this error:
> 
> ```
> Could not find artifact org.mybatis.spring.boot:mybatis-spring-boot-starter:jar:3.5.2.7-SNAPSHOT
> 
> Try to run Maven import with -U flag (force update snapshots)
> ```
> 
> Also, get the same error whit **mybatis-plus-boot-starter**
> 
> ```
> Could not find artifact com.baomidou:mybatis-plus-boot-starter:jar:3.5.2.7-SNAPSHOT
> 
> Try to run Maven import with -U flag (force update snapshots)
> ```
> 
> **I think this bug is very easy to solve, but I don't know why till now did not get solved. If you do not have the plan to release a stable version that can support SpringBoot3.0, and want to stack in SpringBoot version < 3.0, then you can tell us here to not wait for this framework and start to use other frameworks. Thanks!**

- You are not using maven repositories from https://oss.sonatype.org/content/repositories/snapshots/ . 
- I have closed a large number of issues in batches at https://github.com/baomidou/mybatis-plus/pull/4870, but a steady stream of people open new issues without searching for historical issues. Almost no one opens an issue with a git with a minimal reproducible example, which is definitely not good for us to continue the topic, because I can't believe that I or you can read minds.

**Comment by lixiaolong117** [comment]
> 

3.5.2.7从哪能找到啊

**Comment by maiqigh** [comment]
> > 支持SpringBoot3.0的正式版，什么时候能发布呢？大佬给个时间点呗～
> 
> 你们试过这个版本能用就发

昨天把项目升级测试了一下， `3.5.2.7-SNAPSHOT` 可以丝滑集成，暂时没发现什么问题

**Comment by euler-king** [comment]
> > > 3.5.2.7-SNAPSHOT
> > 
> > 
> > do you have a release plan?
> 
> 你们试过这个版本能用就发

I upgrade from spring boot 3.0.0-M2 、mybatis-plus 3.5.1
to version
spring boot 3.0.0 mybatis-plus 3.5.2.7-SNAPSHOT

this no problem，publish release version

测试集成没有问题。

**Comment by Bahramudin** [comment]
@linghengqian Thanks! The problem is solved, but still, waiting for a stable release of MP. Wish to become available as soon as possible.

**Comment by jackxu2011** [comment]
使用queryWrapper生成的sql有点问题
```
### The error may involve com.linkcld.fw.test.user.UserMapper.selectList
### The error occurred while executing a query
### SQL: SELECT  id,first_name,last_name,age,birthday  FROM user     WHERE (last_name = ?)
### Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT  id,first_name,last_name,age,birthday  FROM [*]user \000a \000a WHERE (last_name = ?)"; expected "identifier"; SQL statement:
SELECT  id,first_name,last_name,age,birthday  FROM user 
 
 WHERE (last_name = ?) [42001-214]
; bad SQL grammar []
```

**Comment by qmdx** [comment]
使用最新  `3.5.3`  版本
