### ISSUE TITLE
由3.3.1.tmp 升级导 3.5.2 ，枚举类型不能正常映射

### ISSUE THREAD

**Issue by TomThread** [baomidou/mybatis-plus#4999]
### 当前使用版本(必填,否则不予处理)

3.3.1.tmp

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

由3.3.1.tmp 升级导 3.5.2 ，枚举类型不能正常映射，不能映射updateById方法

### 报错信息

不起作用

**Comment by miemieYaho** [comment]
给出复现demo

**Comment by szgRunner** [comment]
试试 8.1.2.147 版本的驱动
