### ISSUE TITLE
如何配置sql日志

### ISSUE THREAD

**Issue by biezhi** [baomidou/mybatis-plus#5]
我使用的是log4j，如何配置打印sql输出到控制台？

**Comment by qmdx** [comment]
与原生 Mybatis 日志一样配置，例如：
<logger name="org.apache.ibatis" additivity="false">
        <level value="DEBUG" />
        <appender-ref ref="Console" />
</logger>

**Comment by biezhi** [comment]
我这样配置就成功了

```bash
log4j.logger.SELECT=debug
```
不知道为什么日志输出的是如下的, `SELECT`是什么意思
```bash
SELECT.1915324600 | ==>  Preparing: select IFNULL(a.cont_click,0) as `cont_click`,a.*,b.class_name,c.user_truename,d.name `type_title`, b.class_folder,b.cont_templet as class_cont_templet,b.class_templet as class_templet from l_cont as a left join l_class as b on a.class_id=b.class_id left join l_admin as c on a.edit_userid=c.id left join tzzs_type as d on a.typeId=d.id where 1=1 AND a.class_id='4' AND a.sign='3' AND a.cont_commen='1' order by edit_date desc limit 0,8 
[bbs] 2016-10-08 13:38:33,948 DEBUG [RMI TCP Connection(3)-127.0.0.1] SELECT.1915324600 | ==> Parameters: 
```

**Comment by qmdx** [comment]
SELECT是什么意思！！ 

> 没遇到过！！

**Comment by RoJinnSennSei** [comment]
第一次配日志.... log4j2.xml 里 单独<logger name="com.张三.mapper" level="debug"></logger>      com.张三.mapper是你自己的mapper所在包,
如果是springboot 配置log4j2.xml 发现 如果root的level设置为debug 控制台信息出现太多, 但是设置为info又看不到请求后执行的sql.(root的level也会影响底下appender的level 能否打印或输出)

**Comment by RoJinnSennSei** [comment]
`<logger name="com.east.mapper" level="debug">
            
        </logger>`

**Comment by RoJinnSennSei** [comment]
`<logger name="com.张三.mapper" level="debug">
            
        </logger>`

**Comment by jounghu** [comment]
logback怎么配置啊
