### ISSUE TITLE
分页查询传入其他报错

### ISSUE THREAD

**Issue by cui19951005** [baomidou/mybatis-plus#500]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
2.x切换到3.x后 public IPage method(page,entity or  map ) 方法报错
Parameter 'status' not found. Available parameters are [page, params, param1, param2]
使用@param还会报错比如
public IPage method(page,@pram("p") entity ) 
xml配置
#{p.name}
Parameter 'status' not found. Available parameters are [page, p, param1, param2]
### 重现步骤
public IPage method(page,@pram("p") entity ) 
xml使用
#{p.name}
### 报错信息
Parameter 'status' not found. Available parameters are [page, p, param1, param2]

###疑问
为什么提的问题对方没有验证你们就关闭问题了。

**Comment by miemieYaho** [comment]
我们验证过是没有问题的,方便的话,你写一个能复现 bug 的项目上传到 git, 我们再看看.

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-pagination/src/test/java/com/baomidou/mybatisplus/samples/pagination/PaginationTest.java
