### ISSUE TITLE
手写分页查询，无法查询到第一页之后的数据

### ISSUE THREAD

**Issue by ZacharyBear** [baomidou/mybatis-plus#5000]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
看图：
![Snipaste_2022-12-07_15-02-59](https://user-images.githubusercontent.com/62818957/206111426-2b9cce54-b361-4f09-861c-3d495c70d2bd.png)
这个方法启使用默认的searchCount，但是统计count的部分没有包含原始SQL的关联语句和where语句，条件不一致导致统计出来的数据和实际查询结果不一致。似乎这里会影响后面的查询，我通过查询方法无法查询到数据，但直接在数据库客户端执行是有数据的.

### 重现步骤(如果有就写完整)
我在Mapper中写了一个分页方法，包含分页参数和查询参数两个条件。并且编写了相关查询SQL（有外关联和where）。这个方法执行后只能返回第一页的数据，即使我传入的分页参数page=2也不行。

### 报错信息
分页逻辑不正确

### 相关信息
这里主表只有两条数据，分页数量为15，但是关联后有70多条数据

**Comment by miemieYaho** [comment]
set`page.optimizeJoinOfCountSql=false`

**Comment by ZacharyBear** [comment]
> set`page.optimizeJoinOfCountSql=false`

it works, thank you😃
