### ISSUE TITLE
运行自带方法提示invild bound

### ISSUE THREAD

**Issue by xiguazhiPrince** [baomidou/mybatis-plus#5001]
### 当前使用版本(必填,否则不予处理)
mybatisplus3.5.2
其他我们自己带的jar中有引用mybatis和mybatis-spring，还有mybatis-stater等…具体版本号记不住了，手机码字…

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
这个问题我猜测可能是数据源的配置造成的
我们项目中自己封装了多数据源的jar，那么为  ！每个数据源！  构造了属于它datasoure，sqlsession，management等一系列的bean，每个bean指定名称。最后在@mapperscan中定义每个数据源对应的mapper.xml路径和sqlsession

例如: 
@MapperScan（value= /mysql，sqlsession=mysql-sqlsession）
@MapperScan（value= /doris，sqlsession=doris-sqlsession）

这么一来，通过默认的spring.datasouce和默认的启动配置类就没用了。
我想着也为mybatisplus也写datasoure，sqlsession，management等一系列的bean，
然后通过@MapperScan（value= /plus，sqlsession=plus-sqlsession）的方式来搞一下

但是折腾了一下又不生效，也不知道为什么

### 期望解答
我想知道如果mybatisplus指定自定义的datasource和sqlsession，正确方式该怎么做？

**Comment by miemieYaho** [comment]
`MapperScan`里面哪来的`sqlsession`?
你这种需要你自己照着mp的stater的代码抄再自己debug

**Comment by xiguazhiPrince** [comment]
> 

![image](https://user-images.githubusercontent.com/34903051/206232594-324cc276-b74a-4f55-8f12-d27abd12c719.png)
sqlSessionFactoryRef属性

**Comment by xiguazhiPrince** [comment]
> `MapperScan`里面哪来的`sqlsession`? 你这种需要你自己照着mp的stater的代码抄再自己debug

![image](https://user-images.githubusercontent.com/34903051/206233235-d02babfc-d7f7-4e88-9208-5940d638005f.png)
上面3个是mybatis原生的3个数据源配置，通过指定sqlSessionFactoryRef来指定了数据源，下面这个那个是我新加的，但是运行自带方法提示invild bound

我再模仿aotuConfig试一遍

**Comment by miemieYaho** [comment]
`MapperScan(value="com.*.xxx.xx.xx")`

**Comment by xiguazhiPrince** [comment]
> `MapperScan(value="com.*.xxx.xx.xx")`

模仿mybatisPlusAutoConfig之后，配合@MapperScan完美自实现了自定义数据源，谢谢
