### ISSUE TITLE
3.5.2.7-SNAPSHOT分页无效

### ISSUE THREAD

**Issue by ijry** [baomidou/mybatis-plus#5003]
### 当前使用版本(必填,否则不予处理)

3.5.2.7-SNAPSHOT

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用分页功能

### 重现步骤(如果有就写完整)
// 分页
Page<CollegeGoods> page = new Page<CollegeGoods>(1, 10));
// 查询列表
IPage<CollegeGoods> dataPage = collegeGoodsService.page(page,queryWrapper);

分页无效

### 报错信息

dataPage.getRecords()打印出来是所有数据
dataPage.getTotal()打印出来是0

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by ijry** [comment]
运行后访问127.0.0.1:8888然后看控制台打印

**Comment by miemieYaho** [comment]
git形式的

**Comment by ijry** [comment]
> git形式的

https://github.com/ijry/spring-boot3-demo

**Comment by miemieYaho** [comment]
你分页插件怎么不配?
