### ISSUE TITLE
怎么映射mysql的geometry类型？

### ISSUE THREAD

**Issue by wushuaiping** [baomidou/mybatis-plus#5004]
请问现在的版本支持这个嘛？网上没搜到的解决方案没法用

**Comment by miemieYaho** [comment]
写typehandler

**Comment by wushuaiping** [comment]
> 
有方案吗铁汁，对mybatis的这个不是很了解

**Comment by miemieYaho** [comment]
百度

**Comment by qmdx** [comment]
可以参考 https://baomidou.com/pages/fd41d8/ 代码类似 JacksonTypeHandler 的处理方式
