### ISSUE TITLE
逻辑删除的值问题

### ISSUE THREAD

**Issue by FayShen** [baomidou/mybatis-plus#5011]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
逻辑删除能否像id生成器一样运行时生成值，而不是固定值。例如使用当前时间戳作为删除值，这样建唯一索引时就不会有冲突

**Comment by miemieYaho** [comment]
支持数据库函数,文档里有

**Comment by FayShen** [comment]
好的，我明白了
