### ISSUE TITLE
关于update/remove 非幂等操作

### ISSUE THREAD

**Issue by weiro-9-w7** [baomidou/mybatis-plus#5013]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

历史版本， 是不管你有没有删除到数据或更新到数据， 统一返回true
最新的版本，如果删除的数据不存在， 则会返回false
感觉这样失去了幂等性
想知道是什么原因作出这个改变， 谢谢

**Comment by qmdx** [comment]
永远返回 true 和你忽略返回结果的判断效果是一样，当前版本只是统一为正常影响了操作记录返回true
