### ISSUE TITLE
字段使用JacksonTypeHandler，list查不到数据，字段为null

### ISSUE THREAD

**Issue by SSylow** [baomidou/mybatis-plus#5017]
### 当前使用版本(必填,否则不予处理)
3.5.2
MySQL5.7 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用的目前就是最新的

### 重现步骤(如果有就写完整)
字段数据是这样类型的
["",""]
字段：
    @TableField(typeHandler = JacksonTypeHandler.class)
    private List<String> goodsImgs;
类也写了autoResultMap
@TableName(value = "**", autoResultMap = true)

增删改，getById 都正常，但是list和page就不行。
都是自带的list，自定义sql或者不自定义结果都为null

### 报错信息
无报错

**Comment by miemieYaho** [comment]
你自己写的sql要自己写resultmap来用

**Comment by SSylow** [comment]
@miemieYaho 我知道呢，目前还没用自定义的sql，就是自带的ServiceImpl中的list
我看demo中没问题，不知道是不是数据库不同 我用的MySQL5.7

**Comment by SSylow** [comment]
我自己不知道咋搞的，正常了，接下来自己实现自定义sql。谢谢
@miemieYaho
