### ISSUE TITLE
建议MybatisPlusAutoConfiguration内部处理一下异常

### ISSUE THREAD

**Issue by quchuangh** [baomidou/mybatis-plus#5019]
建议在 MybatisPlusAutoConfiguration#sqlSessionFactory 中捕获并输出异常，避免出现一些诡异且难以调试的问题。

### 当前使用版本(必填,否则不予处理)
3.4.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis plus 创建 sqlSessionFactory 的源码如下：
```java
@Bean
@ConditionalOnMissionBean
MybatisPlusAutoConfiguration#sqlSessionFactory(DataSource dataSource) throws Exception {}
```
当 MybatisPlusAutoConfiguration  对象被成功创建，但 sqlSessionFactory() 方法调用失败后。spring 可能会多次执行  sqlSessionFactory() 方法直到执行成功，且执行出错时不抛出任何异常提示，系统正常启动。
引发的后果是 拦截器 被多次添加从而出现各种诡异的问题。
以上问题因为没有错误提示开发者很难调试。建议能在内部捕获异常，打出错误，提醒开发者。

### 重现步骤(如果有就写完整)
1. 撰写一个错误的Mapper组件，语法要正确，能正常编译通过，如下脚本错误的添加了<script>标签
  ```java
   @select("<script> select * from t_user where username=#{username}</script>")
   User findByUsername(String username);
 ```
2. 启动程序，spring会创建  MybatisPlusAutoConfiguration 对象
3. 调用 MybatisPlusAutoConfiguration#sqlSessionFactory() ，因为错误 Mapper的原因将抛出异常，但spring不对其进行处理。程序继续启动。
4. spring之后会再次执行第3步，并执行成功。

由于第4步执行成功了，整个程序是正常运行的。但 sqlSessionFactory() 方法被执行了两次，导致拦截器被添加了两次。所有的拦截器都会执行两次。如乐观锁拦截器执行两次，导致乐观锁的 version 总是被加两次，导致更新失败。

### 报错信息
没有报错信息。正是因为没有报错信息，问题很难查找。所以希望作者大大能在  sqlSessionFactory  中加上报错信息，避免其他开发人员踩坑。

**Comment by quchuangh** [comment]
这里补充一下，错误的脚本这样写
@Select("<script> select * from t_user  where username=#{username}</script>")
User findByUsername(String username);
sqlSessionFactory() 方法会因为 Select 中多了 <script> 标签而创建失败。

**Comment by ijaychang** [comment]
表示关注

**Comment by miemieYaho** [comment]
能提供一个git形式的复现demo?

**Comment by quchuangh** [comment]
感谢关注和作者的回复，我会尽快提交一个git形式的复现demo. 请作者大大先别关闭问题。万分感谢。

**Comment by quchuangh** [comment]
实在抱歉，这个问题只在一个月前的工程中出现过。我重新构建新的工程试图复现它，2天时间里我不断重试，但一直没有重现。当出现错误mapper时 spring 总之能捕获异常并退出启动。之前的问题是 spring 没有捕获异常。我想这个可能跟bean的创建方式有关，但我无法模拟出来。我会关闭这个问题，并在下次遇到这个问题时给出完整的堆栈信息。这次我太大意了，非常抱歉。
