### ISSUE TITLE
lambda查询方式，查部分字段没效果，会全部查出来

### ISSUE THREAD

**Issue by luosai001** [baomidou/mybatis-plus#502]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.3

    QueryWrapper<Person> personQueryWrapper = new QueryWrapper<>();
    personQueryWrapper.lambda().select(Person::getName).eq(Person::getId,2);
    personQueryWrapper.select("name");
第三行代码可以实现值只查出name字段的值.
第二行代码lambda方式会查询出所有字段的值，这个是bug呢，还是需要其他设置？

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/501

**Comment by dudiao** [comment]
版本：3.0.4

我也遇到这种情况了，lambda设置的select不生效
```java
QueryWrapper<Td14Workday> qw = new QueryWrapper();
qw.lambda().select(Td14Workday::getDateInfo, Td14Workday::getWorkdayStatus)
    .between(Td14Workday::getDateInfo, firstDay, lastDay);
List<Td14Workday> list = entityService.list(qw);
```
