### ISSUE TITLE
开启逻辑删除后，removeById 传入id为字符串，实体的id类型为Long会有异常。

### ISSUE THREAD

**Issue by XuJZ-Coder** [baomidou/mybatis-plus#5021]
https://github.com/baomidou/mybatis-plus/blob/7794cfcd79715a2fe89fdf5041594ca90db0891b/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/service/impl/ServiceImpl.java#L279

**Comment by qmdx** [comment]
请保证类型匹配
