### ISSUE TITLE
MP是否兼容PolarDB？

### ISSUE THREAD

**Issue by zjie0723** [baomidou/mybatis-plus#5025]
### 当前使用版本(必填,否则不予处理)
3.3.2

计划升级到3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
无

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by qmdx** [comment]
参考 https://github.com/baomidou/mybatis-plus/pull/4924 PR 支持

**Comment by zjie0723** [comment]
好的，谢谢
