### ISSUE TITLE
V3.5.3 LikeTable设置无效

### ISSUE THREAD

**Issue by Zweyer** [baomidou/mybatis-plus#5027]
如下图，版本 3.5.3 配置策略LikeTable无效，将查找到全部表，将databaseQueryClass设置为SQLQuery正常。

![image](https://user-images.githubusercontent.com/18591014/189589301-0a5d91e8-c52d-41ec-84e7-36540938eec2.png)

**Comment by GHQiuJun** [comment]
databaseQueryClass设置为SQLQuery正常
这个配置我在文档中没有查到，麻烦请问一下在哪里配置

**Comment by qmdx** [comment]
@Zweyer  请问你使用的什么数据库

**Comment by qmdx** [comment]
未反馈
