### ISSUE TITLE
spring boot 3.0 集成最新的 mp 快照版本后启动报错

### ISSUE THREAD

**Issue by SimonVonXCVII** [baomidou/mybatis-plus#5029]
### 当前使用版本(必填,否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus</artifactId>
            <version>3.5.2</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2.7-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-core</artifactId>
            <version>3.5.2</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-annotation</artifactId>
            <version>3.5.2</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>3.5.2</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.5.3</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
spring boot 3.0 集成最新的 mp 快照版本后启动报错

### 报错信息
![image](https://user-images.githubusercontent.com/36143469/208338891-ea67f81a-a142-4c52-b750-b8ee6a6e0a0b.png)
![image](https://user-images.githubusercontent.com/36143469/208338924-982f6ca4-e3e0-481c-9c5b-cfa4877009b0.png)

**Comment by miemieYaho** [comment]
统一快照版

**Comment by SimonVonXCVII** [comment]
> 统一快照版

统一快照版本后成功启动了，感谢！
注：mybatis-plus-generator 还是用 3.5.3 版本
