### ISSUE TITLE
Spring Boot 升级到 3.0 版本后无法进行自动配置

### ISSUE THREAD

**Issue by theodorehills** [baomidou/mybatis-plus#5032]
### 当前使用版本(必填,否则不予处理)
MyBatis Plus Boot Starter v3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
由于 Spring 团队在 Spring Boot 3.x 版本中移除了通过 `META-INF/spring.factories` 文件注册自动配置的方式，导致在 Spring Boot 3.0 环境下没有探测到 MyBatis Plus 内的 `AutoConfiguration`

> 可参考 [Spring 官方迁移文档](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files)

### 重现步骤(如果有就写完整)
创建 Spring Boot 3.0 项目并引入 MP，随意设置一些 Mapper 后，通过 `@Autowired` 引用 Mapper 时会提示没有这个 bean

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/4971
