### ISSUE TITLE
获取数据库设置的默认值

### ISSUE THREAD

**Issue by Jick-study** [baomidou/mybatis-plus#5035]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
比如表里的X字段我设置的默认值为 'tttuuu'

当我执行完baseMapper.insert方法后，我期望表对象的X字段会拿到数据库设置的默认值tttuuu，这个可以实现吗？

（我知道会有人说将这个处理用代码来实现，@TableField(fill = FieldFill.INSERT)，但是类似的场景其实挺多的，而且我要是没有理解错的话，设置过多的默认值处理肯定会对性能有影响的，毕竟底层会拦截某一个字段的特殊处理嘛。所以我们团队期望将这个默认值的逻辑就是放在数据库层面）

**Comment by miemieYaho** [comment]
不select是不能的
