### ISSUE TITLE
updateBatchById(List<entity>) saveOrUpdateBatch(List<entity>) 带@version字段条件更新，更新不到也返回true？

### ISSUE THREAD

**Issue by dongzhaoxiang** [baomidou/mybatis-plus#5036]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

单条更新更新到数据返回true。更新不到返回false。没有问题。
但是发现批量操作都返回true。浏览了一下网上，其他人也发现了这个问题。能不能像jdbcTemplate那样返回个0 1 或者 true false 的数组。

**Comment by dongzhaoxiang** [comment]
不能给出批量更新的返回结果，那就很鸡肋了。好多重要的业务哪敢用这个批量更新

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/4803#issuecomment-1360875508

**Comment by dongzhaoxiang** [comment]
来信已收到！
