### ISSUE TITLE
Oracle 查询别名 关键字

### ISSUE THREAD

**Issue by Lsatin** [baomidou/mybatis-plus#5039]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体属性与表字段不对应，使用@TableField注解。
建议注解增加别名属性，让用户可以自定义别名

### 重现步骤(如果有就写完整)
实体
`
@TableField("levels")
`
`
privete String level;
`
打印SQL
SELECT levels AS level FROM XXX

### 报错信息
SQL语法错误

**Comment by qmdx** [comment]
1，禁止使用关键词

2，转义

注解配置转义符 ` '` 

@TableField("'levels'")

全局配置
```
GlobalConfig.DbConfig dbConfig = new GlobalConfig.DbConfig();
 dbConfig.setColumnFormat("'%s'");
```

**Comment by LJieerone** [comment]
注解配置转义符  '
@TableField("'levels'")
sqlserver查询可以，保存的时候报错
