### ISSUE TITLE
已经配置分页插件，但是total pages都为0

### ISSUE THREAD

**Issue by ychange2012** [baomidou/mybatis-plus#504]
mybatis-plus-boot-starter 2.2.0版本
已经配置分页插件，但是total pages都为0
List<User> selectUserList(Pagination page, Integer state);

public Page<User> selectUserPage(Page<User> page, Integer state) {
    return page.setRecords(userMapper.selectUserList(page, state));
}

<select id="selectUserList" resultType="User">
    SELECT * FROM user WHERE state=#{state}
</select>

@Bean
    public PaginationInterceptor paginationInterceptor() {
       return new PaginationInterceptor();
    }

**Comment by qmdx** [comment]
请升级 `2.3` 试试

**Comment by ychange2012** [comment]
因为自定义数据源了，注入分页插件形式变了，现在对每个数据源单独注入，可以获取分页信息了。
