### ISSUE TITLE
PostInitTableInfoHandler 未能在新版本是找到相应的类？

### ISSUE THREAD

**Issue by amwgwiqpl** [baomidou/mybatis-plus#5040]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

看commit里有相关类的提交，之前类名为JoinTableInfoHandler，但新版本中无该类存在，能开放此功能吗？

**Comment by miemieYaho** [comment]
快照版里面,会在3.5.3上正式推出
