### ISSUE TITLE
自动维护表结构功能(不同于Flyway，类似SpringData JPA)

### ISSUE THREAD

**Issue by huchuansai** [baomidou/mybatis-plus#5047]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我自己长时间在生产环境使用Flyway+mp有两年了，维护的是一个saas项目，每个月都会有升级，其中最头疼的就是数据库字段的删减和表的维护了。用Flyway的好处就是可以自动帮你维护，坏处就是：

1.需要写大量的迁移脚本，其中迁移脚本中大多数都是字段的删减和表的新增，mp能否可以参考jpa去实现自己的一套规则，或者nodejs的typeorm框架也有类似的实现；

2.如果迁移脚本写错(sql语法比较严格)或者是同一个迁移文件中有很多sql代码，偏偏最后一行报错了，如果没加事务的话那就是毁灭性的打击，然后你需要重新修改迁移文件、打包构建、发布，来来回回需要个3至5分钟吧，GOD！

### 报错信息
Flyway的市场占有还是很低的，有大部分程序员都不知道有这个东西。附我的Flyway迁移脚本

<img width="373" alt="image" src="https://user-images.githubusercontent.com/50079978/209895113-2a473d2d-5fe4-4e73-a81b-c4dfd9081b25.png">

**Comment by huayanYu** [comment]
没有打算,你可以独立开源一个项目,和Flyway抢市场.

**Comment by qmdx** [comment]
新版本 3.5.3 支持，使用文档 https://baomidou.com/pages/1812u1/ 对于 flyway 的迁移你可以把当前已经支持的脚本维护到 MP 的 ddl_history 中就不会再次执行了

**Comment by huchuansai** [comment]
个人认为MP的ddl维护还不如Flyway的，但是Flyway的问题也有很多，所以问问MP能不能再优化一下这个ddl维护功能，少点脚本多点注解？

**Comment by qmdx** [comment]
> 个人认为MP的ddl维护还不如Flyway的，但是Flyway的问题也有很多，所以问问MP能不能再优化一下这个ddl维护功能，少点脚本多点注解？

注解工作量太大兼容性也是问题，执行脚本是最好的选择
