### ISSUE TITLE
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException

### ISSUE THREAD

**Issue by the-tsing** [baomidou/mybatis-plus#5048]
### 当前使用版本(必填,否则不予处理)

3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
native编译

### 重现步骤(如果有就写完整)
mvn -Pnative clean package

### 报错信息

![QQ截图20221229102953](https://user-images.githubusercontent.com/56435687/209895477-11444455-6be6-407f-94e3-056f51b366cd.png)

**Comment by nieqiurong** [comment]
#5527  统一至此处讨论.
