### ISSUE TITLE
查询集合返回stream，方便结果集二次加工

### ISSUE THREAD

**Issue by dreamshit** [baomidou/mybatis-plus#5050]
当前使用版本：3.5.2

非问题，第一次使用，查询集合结果时，没有找到返回stream方法(LambdaQueryChainWrapper)。
源码中也有stream，但是在返回前collect了。常用业务中可能会需要对list继续加工，比如转为map，或者BeanCopy等。
这时就要从list重新开stream做二次加工。

是否可以增加返回stream的方法。

**Comment by miemieYaho** [comment]
没有

**Comment by dreamshit** [comment]
看到了SimpleQuery类有封装了一些工具。
从写法上没办法从wrapper链式到底，但是也可以节省一些代码。

感谢作者回复。还是不太熟悉，我先看看源码，这个先关闭了。

再次感谢。
