### ISSUE TITLE
3.5.3 .one()方法 当返回结果为null时 直接报异常

### ISSUE THREAD

**Issue by chenhz4088** [baomidou/mybatis-plus#5053]
### 当前使用版本(必填,否则不予处理)
3.5.3版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
.one()方法，当返回结果为null时 直接报异常。

default R execute(SFunction<BaseMapper, R> function) {
return Optional.ofNullable(getBaseMapper()).map(function).orElseGet(() -> SqlHelper.execute(getEntityClass(), function));
}

Optional.ofNullable(getBaseMapper()).map(function)返回null， getEntityClass()方法也为null。

### 重现步骤(如果有就写完整)
.one()方法，当返回结果为null时可复现

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Class must no be null

**Comment by miemieYaho** [comment]
[3.5.3.1-SNAPSHOT与3.5.3.1版本一同发布](https://github.com/baomidou/mybatis-plus/commit/188370b6539ce3a09100e6b428722dcc0620c747)
两个版本都可用,正式版因为才发布可能需要几个小时后才能被拉取

**Comment by chenhz4088** [comment]
好
