### ISSUE TITLE
更新sql时，希望setSql增加个参数化的方法。

### ISSUE THREAD

**Issue by amwgwiqpl** [baomidou/mybatis-plus#5055]
### 当前使用版本(必填,否则不予处理)

3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
目前只有这一个方法。不能将Sql参数值参数化
<img width="647" alt="image" src="https://user-images.githubusercontent.com/12265435/210066456-dd70f65b-05d6-4ffd-9490-56a623dce7d8.png">

### 重现步骤(如果有就写完整)
希望可以增加一个参数化的setSql，以支持更灵活的sql处理
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/12265435/210066434-f025ed5d-c77f-4be5-92ba-f71e6787f2b3.png">

**Comment by miemieYaho** [comment]
你希望增加的函数,你准备怎么用,可有例子?

**Comment by huayanYu** [comment]
无回复close

**Comment by amwgwiqpl** [comment]
目前项目中，有应用json字段类型的操作， 会使用到数据库的json_set等方法， 基本上是 Column = JSON_SET(Column, "$.a", "{0}"), 增加参数化的setApply方法，可实现字段参数化的逻辑， 避免参数值直接拼接在sql内
