### ISSUE TITLE
postgres子查询使用string_agg报错，需要升级jsqlparser

### ISSUE THREAD

**Issue by Lvbuqing** [baomidou/mybatis-plus#5057]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

需要升级jsqlparser 到4.5版本
详情请见
[There are aggregate functions in the subquery：string_agg #1705
](https://github.com/JSQLParser/JSqlParser/issues/1705)

**Comment by miemieYaho** [comment]
4.5有其他bug

**Comment by Lvbuqing** [comment]
这咋弄？那我还能继续使用4.5的版本吗？
可是我4.4的版本报错啊

**Comment by Lvbuqing** [comment]
可以说一下具体的问题吗

**Comment by huayanYu** [comment]
你查下历史issue吧
