### ISSUE TITLE
分页异常，分页条数和响应的行数不一样

### ISSUE THREAD

**Issue by kuwuhai** [baomidou/mybatis-plus#5058]
### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/48682522/210134021-0b4c905f-4a88-4e6a-9701-27fc8f855f00.png)

![image](https://user-images.githubusercontent.com/48682522/210133993-c92c5366-652b-470e-82e7-42bf381462ec.png)

**Comment by miemieYaho** [comment]
sql执行是mybatis的事
