### ISSUE TITLE
乐观锁插件失效

### ISSUE THREAD

**Issue by 408043749** [baomidou/mybatis-plus#506]
使用版本 3.0.3

乐观锁插件失效

**Comment by miemieYaho** [comment]
怎么失效的你倒是说啊

**Comment by 408043749** [comment]
配置了拦截器
    @Bean
    public OptimisticLockerInterceptor optimisticLockerInterceptor() {
        return new OptimisticLockerInterceptor();
    }

保存方法：

    @RequestMapping(value="/save",method= RequestMethod.PUT)
    @ResponseBody
    public boolean save(@RequestBody DgUser dgUser){
        if(null!=dgUser.getId()){
            iDgUserService.updateById(dgUser);
        }else {
            dgUser.setPassword("123456");
            iDgUserService.save(dgUser);
        }

        return true;
    }

执行updateById方法并没有乐观锁参数
2018-09-21 14:02:52.706 DEBUG 16840 --- [nio-8080-exec-6] c.p.d.mapper.DgUserMapper.updateById     : ==>  Preparing: UPDATE dg_user SET LOGIN_NAME=?, NAME=?, NICKNAME=?, MOBILE=?, REMARKS=? WHERE ID=? AND DEL_FLAG='0'

**Comment by miemieYaho** [comment]
参数是要传的,你好好检查有没有传进来

**Comment by miemieYaho** [comment]
不行,乐观锁就是这么用的,建议你先恶补一下基础知识

**Comment by 408043749** [comment]
嗯 是我的错，是需要先查出来作为条件where参数的，一直注意到 set参数了。感谢大神
