### ISSUE TITLE
引用mybatis-plus后，graphql无法自动配置

### ISSUE THREAD

**Issue by zhangjunapk** [baomidou/mybatis-plus#5061]
### 当前使用版本(必填,否则不予处理)
当前版本:3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
pom文件引用最新版本mybatis-plus(3.5.1)，项目里面用到了graphql，并且在yml文件里面重新指定了graphql 的path，spring.graphql.path属性就失效了，因为mybatis-plus的spring-boot-autoconfiguretion依赖版本为2.5.3
![image](https://user-images.githubusercontent.com/28592113/210175309-0080503b-8eba-4864-af36-dbced535e65e.png)
![image](https://user-images.githubusercontent.com/28592113/210175366-184b1d00-5294-4912-b1e6-4adf4645cab0.png)
但是2.5.3版本的没有graphql的自动配置，就导致yml文件里面的graphql path配置不生效，请求会404
需要手动指定spring-boot-autoconfiguretion的版本为2.7.5才能使graphql的path配置生效
![image](https://user-images.githubusercontent.com/28592113/210175436-4c5a02c7-d35e-4102-9240-0700b13e1728.png)

### 报错信息
404

**Comment by huayanYu** [comment]
spring-boot的版本自己控制啊
