### ISSUE TITLE
怎么设置转换mysql的geometry字段类型

### ISSUE THREAD

**Issue by hw1992** [baomidou/mybatis-plus#5063]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
之前使用的是tk mybatis，直接这样设置转换的

![image](https://user-images.githubusercontent.com/29779220/210293073-b3e81e4e-085f-456d-b32a-049fe7c48c6b.png)

![image](https://user-images.githubusercontent.com/29779220/210293102-24dac7b3-2b4e-4006-a05d-b2325445def0.png)

### 重现步骤(如果有就写完整)

使用mybatis plus好像不支持
![image](https://user-images.githubusercontent.com/29779220/210293124-0a33f269-107b-4dc4-8d77-ef113052187c.png)

**Comment by hw1992** [comment]
![image](https://user-images.githubusercontent.com/29779220/210293170-cf872613-c4d0-4545-915e-2e27d898501f.png)

**Comment by miemieYaho** [comment]
```java
@Bean
public Typehandler xxTypehandler(){
return yourTypehandler
}
```
