### ISSUE TITLE
如何merge两个(或多个)泛型相同的Wrapper

### ISSUE THREAD

**Issue by zjarlin** [baomidou/mybatis-plus#5064]

**Comment by zjarlin** [comment]
QueryWrapper<T> wrapper1 = new QueryWrapper<T>()
                .eq("id", 1);
        QueryWrapper<T> wrapper2 = new QueryWrapper<T>()
                .eq("riskId", 2);
         QueryWrapper<T> wrapper=   xxUtil.apply(wrapper1,wrapper2);

        QueryWrapper<T> wrapper3 = new QueryWrapper<T>()
                .eq("id", 1)
                .eq("riskId", 2);

     使得   wrapper等效于wrapper3

**Comment by miemieYaho** [comment]
不支持
