### ISSUE TITLE
3.5.3版本LambdaQueryChainWrapper内部entityClass属性为空

### ISSUE THREAD

**Issue by jiangqiang1996** [baomidou/mybatis-plus#5068]
### 当前使用版本(必填,否则不予处理)
3.5.3+springboot3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/44720422/210920436-3257c19b-ea81-4230-8064-dd63fcef1382.png)
如上图，我写了几种查询的方式，唯独第60行在数据库查不到数据的时候会报错。使用basemapper查询是正常的，这两个唯一的区别就是类型来源不一样。

报错信息：
![image](https://user-images.githubusercontent.com/44720422/210920512-739fde9f-0170-46d7-a599-af44f8eedb67.png)

**Comment by jiangqiang1996** [comment]
![image](https://user-images.githubusercontent.com/44720422/210920669-4ddc0b0e-c88a-4618-8530-2cc3cf77ae86.png)

**Comment by miemieYaho** [comment]
3.5.3.1
