### ISSUE TITLE
关于弃用和删除AbstractBaseExecutor、MybatisSimpleExecutor、MybatisBatchExecutor、MybatisReuseExecutor的问题

### ISSUE THREAD

**Issue by darren-wang** [baomidou/mybatis-plus#5071]
### 当前使用版本(必填,否则不予处理)

3.5.2

近期我们在使用MP的时候，发现升级MP（3.1.2到3.5.2）后，有很多内容发生了较大改变，其中`AbstractBaseExecutor`、`MybatisSimpleExecutor`、`MybatisBatchExecutor`、`MybatisReuseExecutor` 实现了ibatis的 Executor接口，继承了BaseExecutor 抽象基类，这些类，从3.4.0开始弃用，3.4.3的时候就删除，查了一下发版记录，并没有找到为什么要弃用和删除这些类的说明。

搜了一下issue，也没找到相关弃用和删除相关功能的issue，

咨询一下这里是出于什么考量要弃用和删除相关的类呢？

**Comment by darren-wang** [comment]
@miemieYaho 您好，请教一下，废弃和删除上述这些类的目的是为了避免重复，让用户直接使用原生Mybatis提供的功能吗？

**Comment by darren-wang** [comment]
@nieqiurong 
您好，这个commit: 
https://github.com/baomidou/mybatis-plus/commit/701facf74238eac6af5ee8b5d9f92c5c2613a1e3
的message是`同步执行器代码.`，意思是为了保持MP的代码功能和原生Mybatis的能力一致吗，还是说遇到了实际的问题在解决相关问题进行的改进，没有找到相关的发版说明，只能看代码提交记录。

**Comment by miemieYaho** [comment]
这几个都是为了老的分页插件服务的,新的分页插件不需要这些当然就删了

**Comment by darren-wang** [comment]
> 这几个都是为了老的分页插件服务的,新的分页插件不需要这些当然就删了

好的，感谢您的答复。

3.3.0之前的版本，功能是有问题的，我们遇到了，原因就是MP中的类和Mybatis原生的实现不一致，commit: https://github.com/baomidou/mybatis-plus/commit/701facf74238eac6af5ee8b5d9f92c5c2613a1e3
修复了这些问题，后面MP升级相关的类都被删了，用户直接使用Mybatis原生的类，目前已经不会遇到相关问题了，但我们还是想了解一下我们演进的原因，所以提问题了。

另外现在删了相关的类之后，我通过搜索代码，当前的MP中已经找不到Executor的实现了。相关的功能是直接使用Mybatis原生的SimpleExecutor、ReuseExecutor、BatchExecutor加以替代，我们MP不再额外提供Executor的实现了是吗？

**Comment by miemieYaho** [comment]
嗯
