### ISSUE TITLE
使用分页插件时，支持仅在第一页进行一次count查询，后续分页不再查询总数量

### ISSUE THREAD

**Issue by kslex** [baomidou/mybatis-plus#5073]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

目前的分页插件在每一个分页查询前都会count一次总数量，当查询的记录数量非常巨大，并且查询条件范围内的总数量恒定不变（或者不插入新的数据）时，每次count计算显得有点浪费性能

**Comment by miemieYaho** [comment]
入参page可指定不查count

**Comment by kslex** [comment]
> 入参page可指定不查count

我清楚可以通过`searchCount`参数来指定是否count，我是想有没有必要添加一个类似`searchCountOnlyOnce`参数来更精细地控制，将类似一下的代码抽象到Mybatis-plus框架层面
``` Java
Page page = new Page();
if (page.hasPrevious()) {
    page.setSearchCount(false);
}
```

**Comment by miemieYaho** [comment]
内部只会保证基本功能,不会玩出各种花
