### ISSUE TITLE
${}传参识别成了全路径包名……

### ISSUE THREAD

**Issue by z402424668** [baomidou/mybatis-plus#5075]
### 当前使用版本(必填,否则不予处理)
3.5.2，最新的版本~

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
${}传参时，将参数识别为了项目的包名。

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/28495253/211487000-7106db92-6096-4b53-b99a-cf6732b57c12.png)

### 报错信息
${}传参，被识别为了项目的包名，加了单引号是ok的，换成#{}也ok，但是就是${}传参出这个问题
![image](https://user-images.githubusercontent.com/28495253/211487080-13ea41d6-da94-4ed4-a39d-33add471eecb.png)

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式

**Comment by z402424668** [comment]
解决了解决了，抱歉。  最后定位是在打包时，xml文件将${}解析成了Maven里的id标识，导致出现的这个问题。
最后换了个名字，避免和maven的属性出现冲突，解决啦~
