### ISSUE TITLE
代码生成器类型转换错误

### ISSUE THREAD

**Issue by HsinDumas** [baomidou/mybatis-plus#5077]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mysql定义的tinyint(4)生成的字段类型为Byte，老版本是Integer

**Comment by Nnaking** [comment]
tinyint(1) 之前是Boolean的现在也成Byte了

**Comment by wrl10123** [comment]
同问，新版本变成Byte，也没找到开关可以不启用这种转换

**Comment by lanjerry** [comment]
转成integer
.typeConvertHandler(new ITypeConvertHandler() {
            @Override
            public @NotNull IColumnType convert(GlobalConfig globalConfig, TypeRegistry typeRegistry, TableField.MetaInfo metaInfo) {
                // 兼容旧版本转换成Integer
                if (JdbcType.TINYINT == metaInfo.getJdbcType()) {
                    return DbColumnType.INTEGER;
                }
                return typeRegistry.getColumnType(metaInfo);
            }
        })

**Comment by lanjerry** [comment]
tinyint(1)有些MySQL版本和驱动有差异性,如果确定长度为1了,还是转换成Byte了,可以在数据库连接上增加&tinyInt1isBit=true
