### ISSUE TITLE
LambdaQueryChainWrapper 小缺陷

### ISSUE THREAD

**Issue by YorkWong** [baomidou/mybatis-plus#5078]
### 当前使用版本(必填,否则不予处理)

3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

当使用LambdaQueryChainWrapper 查询结果为0时，会引发Class Not be null。
使用LambdaQueryChainWrapper(Class<T> entityClass) 构造器构造则正常。
其他的构造方法都缺少对LambdaQueryChainWrapper中的entityClass赋值处理

### 重现步骤(如果有就写完整)

final LambdaQueryChainWrapper<Entity> condition = new LambdaQueryChainWrapper<>(this.mapper);

condition.eq(Entity::getId, id).one(); //搜索结果为0时触发

### 报错信息

<img width="921" alt="CleanShot 2023-01-11 at 11 37 46@2x" src="https://user-images.githubusercontent.com/4627702/211712182-1708d45b-81a4-4ac9-8642-332d3dda086a.png">

**Comment by miemieYaho** [comment]
3.5.3.1
