### ISSUE TITLE
运行时警告非法反射

### ISSUE THREAD

**Issue by Jick-study** [baomidou/mybatis-plus#5080]
### 当前使用版本 最新版本

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.baomidou.mybatisplus.core.toolkit.SetAccessibleAction (jar:file:) to field java.lang.invoke.SerializedLambda.capturingClass
WARNING: Please consider reporting this to the maintainers of com.baomidou.mybatisplus.core.toolkit.SetAccessibleAction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

麻烦问下这个有望解决嘛~

**Comment by qiandingqin** [comment]
我也存在这个问题。使用 3.5.3.1 最新版本  jdk 11

**Comment by ghost** [comment]
@fy287216637 @qiandingqin  请问下你们是否有在mybatis中增加mybatis-plus的分页和防全表更新拦截器？
并且PaginationInnerInterceptor先于BlockAttackInnerInterceptor初始化（或被add进mybatis）？
交换这两个Interceptor的初始化顺序是否还有问题？

**Comment by YukiYlf** [comment]
同样问题 
Unable to make field private final java.lang.Class java.lang.invoke.SerializedLambda.capturingClass accessible: module java.base does not "opens java.lang.invoke" to unnamed module @2d1ef81a
![image](https://user-images.githubusercontent.com/55609473/214279700-a0f1399d-113e-4ef7-bf89-d71eeab3d367.png)
没有分页，就是简单使用查询

**Comment by YukiYlf** [comment]
jdk17 ,springboot3, mybatisplus--使用 3.5.3.1

**Comment by fy287216637** [comment]
> 

没有，都是默认的东西

**Comment by Jick-study** [comment]
> @fy287216637 @qiandingqin 请问下你们是否有在mybatis中增加mybatis-plus的分页和防全表更新拦截器？ 并且PaginationInnerInterceptor先于BlockAttackInnerInterceptor初始化（或被add进mybatis）？ 交换这两个Interceptor的初始化顺序是否还有问题？

没有，都是默认的东西

**Comment by HarrisonC118** [comment]
> 同样问题 Unable to make field private final java.lang.Class java.lang.invoke.SerializedLambda.capturingClass accessible: module java.base does not "opens java.lang.invoke" to unnamed module @2d1ef81a ![image](https://user-images.githubusercontent.com/55609473/214279700-a0f1399d-113e-4ef7-bf89-d71eeab3d367.png) 没有分页，就是简单使用查询

运行加参数 `--add-opens java.base/java.lang=ALL-UNNAMED` 试一下呢
