### ISSUE TITLE
Idea MybatisX无法从Dao跳转到xml文件

### ISSUE THREAD

**Issue by KuoCHsiang** [baomidou/mybatis-plus#5085]
### 当前使用版本(必填,否则不予处理)
1.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

可以从Xml文件一键跳转至Dao结尾的类文件，但是无法从Dao结尾的类文件一键跳转至Xml文件

**Comment by qmdx** [comment]
1，可能是 XML 映射配置错误无法正确识别  2，其它插件冲突（卸载相关插件）
