### ISSUE TITLE
数据库字段更新为null

### ISSUE THREAD

**Issue by WindWZQ** [baomidou/mybatis-plus#509]
### 当前使用版本(必须填写清楚，否则不予处理)
``` java
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.0.3</version>
</dependency>
```

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
updateAllColumnById方法被去除后，现在将数据库字段更新为null，是不是只能用全局配置 field-strategy: ignored？这样项目的所有业务不是都变成了强制更新所有字段？还是有我没找到的其他姿势。

**Comment by miemieYaho** [comment]
- `update(@Param("et") T entity, @Param("ew") Wrapper<T> updateWrapper);` 方法
- `updateWrapper`的`set(String column, Object val)`方法
[test 例子](https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-crud/src/test/java/com/baomidou/mybatisplus/samples/crud/SampleTest.java)

**Comment by WindWZQ** [comment]
说实话我觉得这个方法不太好用，如果我是用一个实体来更新数据库，用这个方法会非常的繁琐。

**Comment by miemieYaho** [comment]
这只是你的一己之见,改方法是经过我们内部集体讨论后的结果

**Comment by qmdx** [comment]
update(实体，条件)  怎么会繁琐呢？？？  默认 实体是不处理 空字符串 null 的，支持 wrapper.set 处理

**Comment by WindWZQ** [comment]
我意思是实体更新并且需要null值的时候会有些繁琐。没错是我一己之见，我也没有代表别人啊：）

**Comment by miemieYaho** [comment]
当你数据库字段里有一些字段在 update 的时候不能进行变动的时候,你就会觉得原来的 updateAllColumn 并不好用了

**Comment by WindWZQ** [comment]
嗯，确实是不同业务不同需求

**Comment by 350478992** [comment]
> 说实话我觉得这个方法不太好用，如果我是用一个实体来更新数据库，用这个方法会非常的繁琐。

能不能搞一个update方法，然后可以修改部分字段的方法呀

**Comment by 350478992** [comment]
> 当你数据库字段里有一些字段在 update 的时候不能进行变动的时候,你就会觉得原来的 updateAllColumn 并不好用了

能不能搞一个update方法，然后可以修改部分字段的方法呀，其他字段就不用一直set、set了，为null的字段set一下就好了
