### ISSUE TITLE
数据权限拦截器功能增强

### ISSUE THREAD

**Issue by skywsp** [baomidou/mybatis-plus#5092]
### 当前使用版本(必填,否则不予处理)
```
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.5.3.1</version>
</dependency>
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
原有功能不足。

### 重现步骤(如果有就写完整)
无需重现

### 功能增强后例子
[示例Demo代码仓库及说明文档](https://gitee.com/ygyg1344_wangshaopeng/java-test/tree/master/mybatis-plus)

示例代码见代码仓库中的：
```
com.sky.wsp.mybatis.plus.plugins.inner.MyDataPermissionInterceptor
```

**Comment by Y-Meta** [comment]
项目一大把写在xml里的sql你只拓展mp的感觉没啥实际意义 ，至少得基于mybatis的Interceptor 才差不多能用

**Comment by miemieYaho** [comment]
你可以pr,并附加test代码

**Comment by qmdx** [comment]
up
