### ISSUE TITLE
实体类枚举insert正常，查询映射失败

### ISSUE THREAD

**Issue by MoraxMa** [baomidou/mybatis-plus#5094]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
插入数据后查询映射失败

### 重现步骤(如果有就写完整)
```java
@Getter
@AllArgsConstructor
public enum MsgStatus implements IEnum<String> {

    SEND,
    PUSHED,
    RECEIVED,
    READ,
    FAILED,
    RECALLED,
    ;

    @Override
    public String getValue() {
        return this.toString();
    }
}
```
```java
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("customer_chat_record")
public class CustomerChatRecord extends Model<CustomerChatRecord> implements Serializable {
    ......

    private String guid;

    private MsgStatus status;

    ......
}
```
```java
lambdaQuery().eq(CustomerChatRecord::getGuid, guid).oneOpt()
```

### 报错信息
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/44521439/215318639-bedc6b5f-7340-437a-85a8-8fa749309d79.png">

**Comment by miemieYaho** [comment]
数据库驱动不支持jdbc4

**Comment by MoraxMa** [comment]
> 数据库驱动不支持jdbc4

我使用8.0.32的mysql驱动还是一样的报错

```xml
<dependency>
    <groupId>com.mysql</groupId>
    <artifactId>mysql-connector-j</artifactId>
    <version>8.0.32</version>
</dependency>
```

**Comment by xsg22** [comment]
> > 数据库驱动不支持jdbc4
> 
> 我使用8.0.32的mysql驱动还是一样的报错
> 
> ```
> <dependency>
>     <groupId>com.mysql</groupId>
>     <artifactId>mysql-connector-j</artifactId>
>     <version>8.0.32</version>
> </dependency>
> ```

我也碰到这个问题，原因是我使用的druid版本过低（1.1.20），rs.getObject(columnName, this.propertyType)会调用druid的getObject(String columnLabel, Class<T> type)方法，druid直接抛异常。把druid升级到1.2.9就正常了。
```
public <T> T getObject(String columnLabel, Class<T> type) throws SQLException {
      throw new SQLFeatureNotSupportedException();
  }
```
