### ISSUE TITLE
请教一个mybatis-plus 2.3 在idea编译的问题

### ISSUE THREAD

**Issue by dtbdtb** [baomidou/mybatis-plus#5095]
idea 2020.3
我们想编译代码，mybatis-plus 2.3
冒昧地打搅下，想请请教几个问题
1
这个版本的代码，jdk应该用什么，什么版本？是jdk1.8吗？
2
我们在settings.gradle
将include 'buildSrc'注释了
对不对？
3
遇到错误：

A problem occurred configuring root project 'mybatis-plus'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.springframework.build.gradle:propdeps-plugin:0.0.7.
     Required by:
         project :
      > Could not resolve org.springframework.build.gradle:propdeps-plugin:0.0.7.
         > Could not get resource 'https://repo.spring.io/plugins-release/org/springframework/build/gradle/propdeps-plugin/0.0.7/propdeps-plugin-0.0.7.pom'.
            > Could not GET 'https://repo.spring.io/plugins-release/org/springframework/build/gradle/propdeps-plugin/0.0.7/propdeps-plugin-0.0.7.pom'.
               > Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

4
我们在build.gradle里面加了
maven { url "http://repo.springsource.org/plugins-release" }
但是还是报同样的错误

**Comment by aohanhongzhi** [comment]
我发现这个构建打包，确实有点不同寻常。我直接
```shell
./gradlew build -x test
```
执行Success，但是没找到可用jar包

**Comment by aohanhongzhi** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/37319319/6130d4c3-450d-43d3-b304-b97eb6b3193f)

**Comment by dtbdtb** [comment]
谢谢




***@***.***
 
发件人： aohanhongzhi
发送时间： 2023-06-07 11:05
收件人： baomidou/mybatis-plus
抄送： dtbdtb; Author
主题： Re: [baomidou/mybatis-plus] 请教一个mybatis-plus 2.3 在idea编译的问题 (Issue #5095)
我发现这个构建打包，确实有点不同寻常。我直接
./gradlew build -x test
执行Success，但是没找到可用jar包
―
