### ISSUE TITLE
mybatis-plus-generator[pg生成自增主键的问题]

### ISSUE THREAD

**Issue by 6Glory9** [baomidou/mybatis-plus#5097]
### 当前使用版本(必填,否则不予处理)
3.5.1,3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.3.1 也存在这个问题
3.4.2 貌似能解决这个问题，SQL查询能正确查询出来，主键逻辑也做优化。

### 重现步骤(如果有就写完整)
0. PG不同的表的ID主键不总是在在第一位的时候就会出现这样的问题
2. com.baomidou.mybatisplus.generator.config.querys.PostgreSqlQuery#tableFieldsSql 
![image](https://user-images.githubusercontent.com/6240229/215630667-1ef808e6-f1d4-48e7-83e9-74044baf4d4c.png)
![image](https://user-images.githubusercontent.com/6240229/215630540-2dc408b9-fb7c-4294-bb11-14b5f218817c.png)

### 报错信息

SELECT A
	.attname AS NAME,
	format_type ( A.atttypid, A.atttypmod ) AS TYPE,
	col_description ( A.attrelid, A.attnum ) AS COMMENT,
	D.column_default,
CASE
		
		WHEN LENGTH ( B.attname ) > 0 THEN
		'PRI' ELSE'' 
END AS KEY 
FROM
	pg_attribute
	A LEFT JOIN (
	SELECT
		pg_attribute.attname 
	FROM
		pg_index,
		pg_class,
		pg_attribute 
	WHERE
		pg_class.oid = 'o_code' :: regclass 
		AND pg_index.indrelid = pg_class.oid 
		AND pg_attribute.attrelid = pg_class.oid 
		AND pg_attribute.attnum = ANY ( pg_index.indkey ) 
	) B ON A.attname = b.attname
	INNER JOIN pg_class C ON A.attrelid = C.oid
	INNER JOIN information_schema.COLUMNS D ON A.attname = D.COLUMN_NAME 
WHERE
	A.attrelid = 'o_code' :: regclass 
	AND A.attnum > 0 
	AND NOT A.attisdropped 
	AND D.TABLE_NAME = 'o_code' 
ORDER BY
	A.attnum;;

**Comment by nieqiurong** [comment]
3.5.3.1试试使用元数据的方式查询看看
