### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.core.NestedIOException

### ISSUE THREAD

**Issue by fffguo** [baomidou/mybatis-plus#5099]
### 当前使用版本(必填,否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
不支持
spring-boot-starter-parent
3.0.2

### 报错信息
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/27751972/215672444-fb16fabb-c81a-458a-ae86-f1a468f092b5.png">

**Comment by qclucky7** [comment]
#4818

**Comment by qclucky7** [comment]
检查下POM文件, 应该有冲突 版本覆盖了。

**Comment by fffguo** [comment]
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/27751972/215714012-f9a1c113-2c1a-4d42-bee9-afcfbb5d2b8e.png">


<img width="1146" alt="image" src="https://user-images.githubusercontent.com/27751972/215714251-a7747058-011b-4319-8eb0-bd90fd5d7a43.png">

**Comment by fffguo** [comment]
3.5.3.1 包含以下依赖，且该包的类：SqlSessionFactoryBean
包含异常：NestedIOException    

<dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis-spring</artifactId>
      <version>2.0.7</version>
      <scope>compile</scope>
    </dependency>
