### ISSUE TITLE
mybatis-plus v3.5.3 是否支持SpringBoot 3.x ？

### ISSUE THREAD

**Issue by Exclusive-gfj** [baomidou/mybatis-plus#5101]
### 当前使用版本(必填,否则不予处理)

v3.5.3

**Comment by daenmax** [comment]
我也想问，springboot3.0.1，mp 3.5.3.1，启动报错**Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required**

**Comment by gogolin001** [comment]
旧版本的3.5.3就支持springboot3运行了，但是因为mybatis的原因不支持aot编译

**Comment by daenmax** [comment]
支持的
