### ISSUE TITLE
mybatis-plus-generator-3.5.0 enableTableFieldAnnotation()设置不生效

### ISSUE THREAD

**Issue by zxiaozhuo** [baomidou/mybatis-plus#5102]
### 当前使用版本(必填,否则不予处理)
3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
表字段为大写 列如：UserName 生成实体userName但是没有@TableField注解

### 重现步骤(如果有就写完整)
 StrategyConfig strategyConfig = new StrategyConfig
                .Builder()
                .addInclude(scanner("表名，多个英文逗号分割").split(","))
                .entityBuilder()
                .naming(NamingStrategy.underline_to_camel)
                .enableTableFieldAnnotation()
                .controllerBuilder()
                .enableRestStyle()
                .build();

**Comment by nieqiurong** [comment]
提供一个demo或者试试最新的版本看看

**Comment by qmdx** [comment]
请使用 `3.5.3.1`+ 版本 https://github.com/baomidou/mybatis-plus/commit/e36e90a669177b49a31c8308f5f3f7de3fd38621 测试正常
```
public void testEnableTableFieldAnnotation() {
    AutoGenerator generator = new AutoGenerator(DATA_SOURCE_CONFIG);
    generator.strategy(strategyConfig().entityBuilder().enableTableFieldAnnotation().build());
    generator.execute();
}
```
