### ISSUE TITLE
selectList(@Param("ew") Wrapper<T> queryWrapper)偶然情况下会携带LIMIT 1

### ISSUE THREAD

**Issue by oldRabbitForz** [baomidou/mybatis-plus#5104]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
baseMapper.selectList传入queryWrapper，偶然情况下查询语句会携带limit 1导致查询返回的list数量错误

**Comment by miemieYaho** [comment]
用最新版给出你的复现demo以git形式

**Comment by qmdx** [comment]
无法定位，反馈后打开 issue
