### ISSUE TITLE
Oracle 12c +mybatis-plus + spring boot 集成后 ，查询语法错误

### ISSUE THREAD

**Issue by kuainaiyang** [baomidou/mybatis-plus#5106]
### 当前使用版本
oracle数据库版本12c
jdk: 1.8
oracle:驱动版本ojdbc8
mybatis-plus-boot-starter(3.5.3.1)
spring-boot(2.6.7)
###  操作步骤
创建spring项目，创建一个简单表，通过iservice中的getById。语法错误。
### 报错信息
Sql = SELECT id,name FROM ZT_TEST WHERE id=:1  , OriginalSql = SELECT id,name FROM ZT_TEST WHERE id=? , Error Msg = ORA-00904: "ID": invalid identifier

**Comment by miemieYaho** [comment]
给出git形式的demo

**Comment by kuainaiyang** [comment]
> 给出git形式的demo

[demo git地址](https://github.com/kuainaiyang/oracledemo)

**Comment by kuainaiyang** [comment]
问题已经解决，oracle数据库字段没有大写导致。
