### ISSUE TITLE
3.5.1 版本 从3.3.2升到3.5.1  bean对象里原来重写主键pkval的方法 原来是protected 现在报错

### ISSUE THREAD

**Issue by asia2xi** [baomidou/mybatis-plus#5107]
### 当前使用版本(必填,否则不予处理)

3.5.1 版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

从3.3.2升到3.5.1  bean对象里原来重写主键pkval的方法 原来是protected 现在报错

### 重现步骤(如果有就写完整)
  bean对象里  
主键有标记 
 @TableId(value = "id", type = IdType.AUTO)
    private Integer id; 

 @Override
    protected Serializable pkVal() {
        return this.id;
    }

### 报错信息

中的pkVal()无法覆盖com.baomidou.mybatisplus.extension.activerecord.Model中的pkVal()
  正在尝试分配更低的访问权限; 以前为public

**Comment by asia2xi** [comment]
是不再需要重写了么 只在id列上有tableId 注解就可以了吗

**Comment by jimmyqin** [comment]
我也遇到这个问题,您的解决了么

**Comment by qmdx** [comment]
修改为父类对应类型即可
