### ISSUE TITLE
mybatis-plus-generator 开启springdoc时 生成实体类时注释未生成

### ISSUE THREAD

**Issue by fwjj** [baomidou/mybatis-plus#5109]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用 FreemarkerTemplateEngine 

### 报错信息

![image](https://user-images.githubusercontent.com/42243236/216935375-77ccb499-d3be-4e16-9223-0c5b8e1f9717.png)

**Comment by fwjj** [comment]
这个文件
mybatis-plus-generator/src/main/resources/templates/entity.java.ftl

**Comment by qmdx** [comment]
什么数据库，怎么写的生成器代码贴出来
