### ISSUE TITLE
关于多数据源 BaseMapper 自带方法不起作用 重写的方法却可以

### ISSUE THREAD

**Issue by leyisong** [baomidou/mybatis-plus#511]
### 当前使用版本(必须填写清楚，否则不予处理)

1.0.16

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
刚开始单数据源用BaseMapper中的增删改查等基础方法没有问题,后来配置多数据源,BaseMapper中的增删改查方法测试找不到,继承BaseMapper的自定义dao中自定义查询或者重写BaseMapper中的方法,测试正常

### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.cpic.part.core.authority.user.mapper.UserEOMapper.selectById

**Comment by leyisong** [comment]
求解答

**Comment by leyisong** [comment]
我们公司比较保守 354962246 邮箱：354962246@qq.com 签名由 网易邮箱大师 定制 在2018年09月25日 20:26，miemieYaho 写道： 1.0.16?远古版本? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by huayanYu** [comment]
@leyisong https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter 官方适配

**Comment by leyisong** [comment]
多谢！！！ 原因找到了，由于配置和注解两种方式混合使用，导致配置的sqlsessionfactory注入冗余了，排查了很长时间😊，（我也不知道明明注解就很简单明了了，非要也要支持配置方式的） 354962246 邮箱：354962246@qq.com 签名由 网易邮箱大师 定制 在2018年09月25日 22:17，小锅盖 写道： @leyisong https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter 官方适配 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
