### ISSUE TITLE
使用条件查询时sql不拼接@tablelogic字段

### ISSUE THREAD

**Issue by wenkesong-li** [baomidou/mybatis-plus#5113]
### 该问题是如何引起的？
使用条件查询时sql不拼接@tablelogic字段

### 重现步骤
1.entity层
<img width="697" alt="image" src="https://user-images.githubusercontent.com/30657112/217403019-27b0a0af-1739-4650-88df-e628514433aa.png">

2.mapper层
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/30657112/217402972-28d4b410-bc48-448f-9e6c-b0e3e4a18fa0.png">
3.xml
<img width="966" alt="image" src="https://user-images.githubusercontent.com/30657112/217403074-e76afea1-de69-4b05-826d-d8681c48d03a.png">
4.sql执行结果
`SELECT  permission.id AS id, permission.permission_name AS permissionName, permission.permission_path AS permissionPath, permission.type AS type, permission.show_type AS showType, permission.sort AS sort, permission.parent_id AS parentId, permission.seq AS seq, permission.link_url AS linkUrl, permission.state AS state, permission.deleted AS deleted, permission.created_by AS createdBy, permission.created_at AS createdAt, permission.updated_by AS updatedBy, permission.updated_at AS updatedAt FROM b_permission permission WHERE (parent_id = 0) LIMIT 10;

5.问题描述 
如sql执行结果可见 条件未自动拼接@tablelogic的deleted字段

### 期望
自动拼接@tablelogic的字段

**Comment by miemieYaho** [comment]
自己写的sql自己拼条件

**Comment by loveyourlife126** [comment]
为啥自定义的sql,tenant_id会帮忙拼接呢，这个地方设计有啥考量 @miemieYaho
