### ISSUE TITLE
saveBatch异常咨询

### ISSUE THREAD

**Issue by CasterWx** [baomidou/mybatis-plus#5118]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

> 前提: 使用到了dynamicTable动态表名插件

service.saveA(listA); // listA 2500条
service.saveB(listB); // listB 2500条

saveA、saveB实现均调用 com.baomidou.mybatisplus.extension.service.IService#saveBatch方法()，但saveA产生了3次statement，saveB缺产生了近千次，每次statement中一个Preparing里Parameters数量不一定(1~4个)，导致落库性能差

![image](https://user-images.githubusercontent.com/30624750/217547969-c9a2c9b5-dab3-4aa7-847a-f74b3ed8e240.png)

### 报错信息

无报错

**Comment by CasterWx** [comment]
初步排查到的原因，部分listB中部分项存在null值，拼出来的SQL模板不同，有字段缺失的时候就新起了一个statement，请问有什么办法可以把PO中为null的字段也拼在SQL中吗

**Comment by miemieYaho** [comment]
注解指定insert时字段验证规则
