### ISSUE TITLE
分页插件中的count语句多租户条件没生效

### ISSUE THREAD

**Issue by xbai2022** [baomidou/mybatis-plus#5119]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
同时引入TenantLineInnerInterceptor 和PaginationInnerInterceptor插件。在执行select 语句时，进入分页插件请求的count语句没有带上租户条件。导致相应的查询结果不一致

### 重现步骤(如果有就写完整)
1. 项目中引入分页插件
2. 项目中引入多租户插件
3. 编写分页查询
4. count语句没带上多租户条件。分页查询语句有带上。相应的page对象中的total和实际的数量对不上

### 报错信息
无

**Comment by miemieYaho** [comment]
看文档调整插件顺序
