### ISSUE TITLE
使用orderBy方法的时候，druid报错java.sql.SQLException: sql injection violation, part alway true condition not allow

### ISSUE THREAD

**Issue by code98** [baomidou/mybatis-plus#512]
Caused by: java.sql.SQLException: sql injection violation, part alway true condition not allow : SELECT  

经过验证去除orderBy就可以正常获取数据，加上则不行。

在2.3的时候是没问题的，3.0出现问题。

**Comment by qmdx** [comment]
推荐 `HikariCP` Spring Boot 官方默认内置，没有对比就没有伤害！！
<img width="502" alt="hikaricp" src="https://user-images.githubusercontent.com/1481125/46051614-e6f14380-c16c-11e8-9c35-98051ab5a4c3.png">
