### ISSUE TITLE
无法使用自带的insertBatchSomeColumn

### ISSUE THREAD

**Issue by kevqi7** [baomidou/mybatis-plus#5121]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

该项目使用的老版本mp，已经设置了sqlinjector 并在mybatis config里使用@bean注入

### 重现步骤(如果有就写完整)
是否可能为多个子项目的问题

### 报错信息
Statement with id="insertBatchSomeColumn" not defined in mapper xml

**Comment by miemieYaho** [comment]
自己排查

**Comment by Tezzxamo** [comment]
报错不影响正常使用
