### ISSUE TITLE
pgsql array查询

### ISSUE THREAD

**Issue by lin-code-world** [baomidou/mybatis-plus#5122]
### 当前使用版本(必填,否则不予处理)
mybatisplus：3.5.3.1
pgsql：14
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类
  @TableField(typeHandler = ArrayTypeHandler.class, jdbcType = JdbcType.ARRAY)
  private String[] recoveryType
对应表字段recovery_type数组类型

new LambdaQueryChainWrapper<>(baseMapper)
      .setEntity(entity)
      .page(pageVo);
翻页获取列表，生成的sql日志发现where条件里recovery_type=null，代码里打了断点，entitiy.recoveryType是有值的

**Comment by nieqiurong** [comment]
如果只是日志打印出null的话,那是正常的,这个值在mybatis的日志中是没法打印了, 具体可以看ArrayTypeHandler中的setNonNullParameter方法的else逻辑, 最后.free()就释放了.

如果是查询数据没有的话,需要开启@TableName中的autoResultMap为true,
