### ISSUE TITLE
升级3.5.1版本以后com.baomidou.mybatisplus.extension.api包下的R对象已过时，被什么对象所替代了？

### ISSUE THREAD

**Issue by Meta39** [baomidou/mybatis-plus#5123]
### 当前使用版本(必填,否则不予处理)

版本：3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

升级到3.5.1版本

### 报错信息
java: 程序包com.baomidou.mybatisplus.extension.api不存在

**Comment by miemieYaho** [comment]
自己写

**Comment by davidricardo1026** [comment]
升级真坑
