### ISSUE TITLE
3.5.3.1没有getWorkerId和getDatacenterId，代码如何改造？

### ISSUE THREAD

**Issue by xiaoyuwang1987** [baomidou/mybatis-plus#5125]
这代码要怎么改造？
private Sequence getSequence() {
        GlobalConfig globalConfig = mybatisPlusProperties.getGlobalConfig();
        Long workerId = globalConfig.getWorkerId();
        Long datacenterId = globalConfig.getDatacenterId();
        if (workerId != null && datacenterId != null) {
            return new Sequence(workerId, datacenterId);
        }
        return Optional.ofNullable(UniqueUtil.getIdWorker()).map(it -> {
            log.info("Init mybatis-plus sequence, workId=[{}], datacenterId=[{}]", it.getWorkerId(), it.getDatacenterId());
            return new Sequence(it.getWorkerId(), it.getDatacenterId());
        }).orElse(new Sequence());
    }

**Comment by miemieYaho** [comment]
自己写properties配置
