### ISSUE TITLE
saveOrUpdateBatch 使用这个方法批量更新报错

### ISSUE THREAD

**Issue by dengjiexiao** [baomidou/mybatis-plus#5130]
### 当前使用版本(必填,否则不予处理)
3.1.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
进行批量更新插入

### 报错信息
org.apache.ibatis.exceptions.PersistenceException:

**Comment by nieqiurong** [comment]
提供一个示例工程

**Comment by nieqiurong** [comment]
有问题再打开.
