### ISSUE TITLE
现在mybatis-plus支持springboot3.0版本吗

### ISSUE THREAD

**Issue by jisl1024** [baomidou/mybatis-plus#5131]
### 当前使用版本(必填,否则不予处理)

使用了mybatis-plus 3.5.2版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

不过在springboot3.0一直无法启动

### 报错信息
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:204) ~[spring-core-6.0.4.jar:6.0.4]

**Comment by timnick-snow** [comment]
最新版的支持
试试3.5.3+

**Comment by jisl1024** [comment]
> 最新版的支持 试试3.5.3+

试了不行还是报一样的错误

**Comment by miemieYaho** [comment]
检查你的jar包版本是否有依赖冲突

**Comment by jisl1024** [comment]
> 

把spring版本改成2.7.8正常了，用spring3.0不支持

**Comment by herbert95** [comment]
```
   <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>snapshots</id>
            <url>https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-boot-starter</url>
        </repository>
    </repositories>
```
换成3.5.3.1版本的mybatis-plus；springboot3.0可以正常工作。可以试试~

**Comment by hongbao-chen** [comment]
> > 
> 
> 把spring版本改成2.7.8正常了，用spring3.0不支持

```
   <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>snapshots</id>
            <url>https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-boot-starter</url>
        </repository>
    </repositories>
```
换成3.5.3.1版本的mybatis-plus；springboot3.0可以正常工作。可以试试~

**Comment by jisl1024** [comment]
> ```
>    <dependencies>
>         <dependency>
>             <groupId>com.baomidou</groupId>
>             <artifactId>mybatis-plus-boot-starter</artifactId>
>             <version>3.5.3.1</version>
>         </dependency>
>     </dependencies>
> 
>     <repositories>
>         <repository>
>             <id>snapshots</id>
>             <url>https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-boot-starter</url>
>         </repository>
>     </repositories>
> ```
> 
> 换成3.5.3.1版本的mybatis-plus；springboot3.0可以正常工作。可以试试~

好的
