### ISSUE TITLE
动态表名和分页插件冲突

### ISSUE THREAD

**Issue by t-aest** [baomidou/mybatis-plus#5132]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

动态表名和分页插件同时使用
### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/49835675/219254700-2c31d45d-f9f9-428d-8b0a-b719406e7404.png)

### 报错信息
动态表名触发的后台的分页失效

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式
