### ISSUE TITLE
`@InterceptorIgnore`注解使用`others`属性不生效

### ISSUE THREAD

**Issue by aboutZZ** [baomidou/mybatis-plus#5135]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 重现步骤(如果有就写完整)
想使用 @InterceptorIgnore 注解忽略某个拦截器，在`mapper`类的某个方法上进行注解：
```java
@InterceptorIgnore(others = {"com.example.MyInterceptor@true"})
```
但是没有生效，仍然走了该拦截器。

去掉该注解，改为使用InterceptorIgnoreHelper，同样不生效
```java
InterceptorIgnoreHelper.handle(IgnoreStrategy.builder().others(Map.of("com.example.MyInterceptor", true)).build());
```

另外，该注解源码文档写的不是很清楚。key是什么？是类名吗？
https://github.com/baomidou/mybatis-plus/blob/9656f4b2717c2f3f210b58881e7e0cf7cf6e6da1/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/InterceptorIgnore.java#L66-L75
### 报错信息
无

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/test/java/com/baomidou/mybatisplus/core/plugins/InterceptorIgnoreHelperTest.java
你需要在你自己的插件里调用`InterceptorIgnoreHelper.willIgnoreOthersByKey`进行判断走不走插件

**Comment by aboutZZ** [comment]
希望可以完善代码中的注释，key 和 id 不知道是啥，看源码搞了半天才弄懂
