### ISSUE TITLE
如果使用逻辑删除的时候，save一条数据的时候需要显式赋值吗？

### ISSUE THREAD

**Issue by code98** [baomidou/mybatis-plus#514]
![image](https://user-images.githubusercontent.com/10418235/46058724-c76b1280-c18e-11e8-90eb-77b8f1add539.png)

enable是我的逻辑删除字段，如图所示，save的时候是否需要给enable赋值？还是框架会自动赋值？

**Comment by miemieYaho** [comment]
mp 目前不会干这事,建议数据库给默认值
