### ISSUE TITLE
希望mybatis-plus能够在所处上下文（例如spring的应用上下文）销毁时清理掉一些全局的缓存

### ISSUE THREAD

**Issue by ForJ-W** [baomidou/mybatis-plus#5145]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

以下是我个人希望能够做出的优化，
希望mybatis-plus能够在所处上下文（例如spring的应用上下文）销毁时清理掉一些全局缓存：
com.baomidou.mybatisplus.core.config.GlobalConfig#mapperRegistryCache
com.baomidou.mybatisplus.core.metadata.TableInfoHelper#TABLE_INFO_CACHE

可能在自定义多个类加载器/多个上下文加载时会出现无效的数据

**Comment by qmdx** [comment]
描述清楚什么使用场景，遇到什么问题，期望怎么解决

**Comment by ForJ-W** [comment]
场景：
  使用多个SqlSessionFactory
问题：
  由于
  com.baomidou.mybatisplus.core.config.GlobalConfig#mapperRegistryCache
  com.baomidou.mybatisplus.core.metadata.TableInfoHelper#TABLE_INFO_CACHE
  com.baomidou.mybatisplus.core.metadata.TableInfoHelper#TABLE_NAME_INFO_CACHE
  为全局共享缓存
  没有清理机制，当我销毁\创建SqlSessionFactory，缓存会越来越多
期望：
  在SqlSessionFactory销毁时能够清理掉对应的上方缓存

**Comment by qJerry** [comment]
这里在执行spring test的时候，只要设置了autoResultMap=true，由于mp的上下文不同步，TABLE_INFO_CACHE未被清除也会受影响

**Comment by qJerry** [comment]
> 这里在执行spring test的时候，只要设置了autoResultMap=true，由于mp的上下文不同步，TABLE_INFO_CACHE未被清除也会受影响

从3.3.2升级到3.4.0就正常了，会重建result map
