### ISSUE TITLE
在`mapper.xml`文件中，逻辑删除剔除查询失效

### ISSUE THREAD

**Issue by yl-yue** [baomidou/mybatis-plus#5146]
### 当前使用版本
3.5.2

### 该问题是如何引起的？
在`mapper.xml`文件中定义的SQL不会自动追加逻辑删除条件，导致逻辑删除剔除查询失效。

> 目前暂时通过多租户拦截器解决此问题。

**Comment by miemieYaho** [comment]
自己写的sql自己加

**Comment by yl-yue** [comment]
这个逻辑删除特性，就不能做到像`tenant_id`一样，不需要业务开发人员管了。

一会会自动追加条件（内置`crud`），一会不会（`xml`），这样会让人觉得不完善，怪怪的。

逻辑删除特性已实现，如果没问题的话，我可以提交一个PR，将此特性合并进来。 @miemieYaho

**Comment by miemieYaho** [comment]
本来就是这样设计的

**Comment by miemieYaho** [comment]
租户插件那是mybatis插件,拦截全局sql的,这个是预注入sql,只生效与mp带的crud

**Comment by yl-yue** [comment]
所以逻辑删除这个特性怪怪的，不像租户特性那么直观，理解起来容易产生误解，我在自己的项目中实现了全局拦截添加，考虑可以的话，可以将这个特性提交给`mybatis-plus`，我推崇的业务框架封装理念是，**业务与技术分离**。所以这特性应该全由框架处理，而非业务开发人员，如果有特殊查询需求，那是配置忽略表或单独处理的事情。
