### ISSUE TITLE
junit5 单元测试无法使用数据加密保护功能

### ISSUE THREAD

**Issue by Githubbili** [baomidou/mybatis-plus#5147]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
对数据库的url、账号和密码都进行加密，但是在单元测试中显示无法访问数据库，一直出错。
已经尝试过在VM和运行环境添加过，但是都没有用。

### 重现步骤(如果有就写完整)
![2e172b344e93aa3dd7ac89c13444db5](https://user-images.githubusercontent.com/21958998/220234337-eef4f6e4-f16a-4221-a70d-5fab188f70cc.png)

![612580233b48ea51dacac15ea1f7780](https://user-images.githubusercontent.com/21958998/220234220-af0b265c-d431-4c51-8e00-bd075dc3c306.png)

![image](https://user-images.githubusercontent.com/21958998/220234316-6a8fb614-4073-49fe-bfbf-8419053a831f.png)

### 报错信息
![0163da43723564cf976c0e924cc5c53](https://user-images.githubusercontent.com/21958998/220234233-cef8bdf7-55f9-4c68-b822-01f9fa999f46.png)

**Comment by huayanYu** [comment]
这是druid防火墙报错
