### ISSUE TITLE
动态表名解析缺失

### ISSUE THREAD

**Issue by 125835373** [baomidou/mybatis-plus#5148]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
原始sql:select t1.* from t_user as t1,t_user_appoint as t2 where t1.user_id=t2.user_id
使用如上查询sql，表名替换解析器中只能识别到t1表，未能识别到t2表

### 重现步骤(如果有就写完整)
@Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        //表名替换拦截器
        DynamicTableNameInnerInterceptor dynamicTableNameInnerInterceptor = new DynamicTableNameInnerInterceptor();
        dynamicTableNameInnerInterceptor.setTableNameHandler((sql, tableName) -> {
            // 替换表名
            if (tableName.contains(GlobalConst.DELIMITER_UNDERSCORE)){
                return tableName ;
            }
            return qPaasTableContext.genTableName(tableName);
        });
        interceptor.addInnerInterceptor(dynamicTableNameInnerInterceptor);
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }
执行sql：select t1.* from t_user as t1,t_user_appoint as t2 where t1.user_id=t2.user_id
进入 替换表名方法中，实际只进入一次，应进入2次，使用inner join无问题

### 报错信息
无报错信息

**Comment by 125835373** [comment]
3.5.3同样存在问题

**Comment by miemieYaho** [comment]
只会去识别带join关键字的
