### ISSUE TITLE
saveBatch插入oracle，timestamp字段总是报错

### ISSUE THREAD

**Issue by keweiLv** [baomidou/mybatis-plus#5149]
### 当前使用版本(必填,否则不予处理)

3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用saveBatch插入oracle数据，数据库字段为timestamp类型，java实体类无论如何修改类型总是报错：无效的月份。请问是不支持还是方法不对，应当如何解决。

### 报错信息

java.sql.BatchUpdateException:ORA-01843:无效的月份。

**Comment by keweiLv** [comment]
close

**Comment by Transparenthw** [comment]
请问怎么解决的？
