### ISSUE TITLE
plus4.X是不是鸽了，好久过去了，啥时候上线呢

### ISSUE THREAD

**Issue by tuoluofusijiyang** [baomidou/mybatis-plus#5150]
plus4.X是不是鸽了，好久过去了，啥时候上线呢，支持jdk17吧，不想用mybatis-plus-join ！！！

### 当前使用版本(必填,否则不予处理)
未来版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
作者不更新，官网也没有明确消息

### 重现步骤(如果有就写完整)
每一秒都在难受~

### 报错信息
难受~

**Comment by javaofferss** [comment]
可以看看我写的mybatis-jql.

**Comment by qmdx** [comment]
等待吧
