### ISSUE TITLE
mybatis执行器设置不生效

### ISSUE THREAD

**Issue by wuzzzh** [baomidou/mybatis-plus#5155]
### 当前使用版本(必填,否则不予处理)
3.5.2

#### yml文件
> mybatis-plus:
        executor-type: reuse

#### 代码片段
`public void save(SysMenu entity) {
        for (int i = 0; i < 10; i++) {
            SysMenu sysMenu = new SysMenu();
            sysMenu.setName(i + "");
            this.insert(sysMenu);
        }
 }`
#### 问题
为什么设置了 executor为reuse，但实际并没有复用预处理器
![image](https://user-images.githubusercontent.com/72498755/220580332-252e437b-d425-4f73-9340-674eb08eca27.png)

#### 自己获取session就可以复用预处理器
`public void save(SysMenu entity) {
        SqlSession sqlSession = GlobalConfigUtils.currentSessionFactory(SysMenu.class).openSession(ExecutorType.REUSE);
        for (int i = 0; i < 10; i++) {
            SysMenu sysMenu = new SysMenu();
            sysMenu.setName(i + "");
            sqlSession.getMapper(SysMenuMapper.class).insert(sysMenu);
        }
    }`

![image](https://user-images.githubusercontent.com/72498755/220580930-84fe4d93-adce-4d9c-981c-3ed67f095472.png)

### 需求
请问是框架问题还是我自己的问题？

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/220662238-11f2d5d0-8b24-45d3-99d3-d1f9b7f94400.png)

**Comment by wuzzzh** [comment]
啥意思？DEBUG是使用的SqlSessionTemplate呀
![image](https://user-images.githubusercontent.com/72498755/220800715-eab997d7-7461-485d-86a1-8ce028c94490.png)

**Comment by miemieYaho** [comment]
那你debug出来的type是什么就是什么啊,执行sql都是mybatis的事了

**Comment by nieqiurong** [comment]
在你自己的save方法上加上事务,才能公用一个sqlsession,才能实现复用逻辑.
