### ISSUE TITLE
MybatisPlus3.5.3分页查询无效果

### ISSUE THREAD

**Issue by JasonXCZS** [baomidou/mybatis-plus#5157]
### 当前使用版本(必填,否则不予处理)
- JDK: Oracle OpenJDK 17.0.2
- SpringBoot: 3.0.2
- mybatis-plus: 3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
current和size分别设置1，10，直接controller层调用service层的page方法，发现无分页效果

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/29533122/220681702-ccf66dde-789c-4782-8ba0-1c737e73f2e6.png)
![image](https://user-images.githubusercontent.com/29533122/220684994-3dc57b0f-5869-47b2-9b4d-cd031472a6c8.png)
![image](https://user-images.githubusercontent.com/29533122/220682495-25ffc838-5046-471a-8902-42d54639a5e9.png)

### 报错信息
未执行分页SQL,返回数据超过10条，未执行分页效果
![image](https://user-images.githubusercontent.com/29533122/220685541-387821be-b764-43d3-a591-ea22db0b045e.png)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples
