### ISSUE TITLE
新版的代码生成器如何配置是否创建某类文件

### ISSUE THREAD

**Issue by Wsr-7** [baomidou/mybatis-plus#5158]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter 3.5.1
mybatis-plus-generator 3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在新版的代码生成器配置中.如何只生成entity和mapperxml?在实际使用上.controller/service基本不会改动.但当表结构有较多更改时,想要只生成一个entity和mapper的xml文件.
在旧版的代码生成器中是可以通过重写注入器InjectionConfig的isCreate()方法控制只生成某些文件.但在新版配置中似乎已经没有这一项配置.我应该如何达到同样效果?

**Comment by timnick-snow** [comment]
可以通过将对应模板路径配置为空来禁用。不确定有没有更好的办法
```java
    private TemplateConfig buildTemplateConfig() {
        TemplateConfig.Builder builder = new TemplateConfig.Builder();
        if (!config.isGenEntity()) {
            builder.entity("");
        }
        if (!config.isGenMapper()) {
            builder.mapper("");
        }
        if (!config.isGenService()) {
            builder.service("");
        }
        if (!config.isGenServiceImpl()) {
            builder.serviceImpl("");
        }
        if (!config.isGenXml()) {
            builder.xml("");
        }
        if (!config.isGenController()) {
            builder.controller("");
        }
        return builder.build();
    }
```

**Comment by nieqiurong** [comment]
generator.template(new TemplateConfig.Builder().disable(TemplateType.CONTROLLER, TemplateType.SERVICE, TemplateType.SERVICE_IMPL).build());

或 

.templateConfig(builder -> {
                builder.disable(TemplateType.CONTROLLER, TemplateType.SERVICE, TemplateType.SERVICE_IMPL);
 })

**Comment by qmdx** [comment]
up
