### ISSUE TITLE
为什么使用 .list ，.listByIds 进行查询，结果会自动排序？

### ISSUE THREAD

**Issue by pzzzzzzzzzzz** [baomidou/mybatis-plus#5160]
版本：3.5.1 && 3.5.3.1（最新）

[1,4,23,5,67]
查询后的结果，会自动将数据 按照 id 的大小顺序自动排序。这不是想要的。

[4, 129, 67, 100, 43, 134, 357, 358]

[{displayValueZh=爸爸, id=4}, {displayValueZh=弟弟, id=43}, {displayValueZh=哥哥, id=67}, {displayValueZh=姐姐, id=100}, {displayValueZh=妈妈, id=129}, {displayValueZh=妹妹, id=134}, {displayValueZh=我的, id=357}, {displayValueZh=你的, id=358}]
[{displayValueZh=爸爸, id=4}, {displayValueZh=弟弟, id=43}, {displayValueZh=哥哥, id=67}, {displayValueZh=姐姐, id=100}, {displayValueZh=妈妈, id=129}, {displayValueZh=妹妹, id=134}, {displayValueZh=我的, id=357}, {displayValueZh=你的, id=358}]

我需要按照我查询的id顺序排序。不需要自动排序？应该怎么操作？

**Comment by miemieYaho** [comment]
看你执行的sql,sql对的那你应该找数据库默认排序的麻烦

**Comment by pzzzzzzzzzzz** [comment]
> 看你执行的sql,sql对的那你应该找数据库默认排序的麻烦

我通过数据库管理软件，使用查询语句，返回的数据是正常的，如果使用 mybatis-plus 提供的 查询 就会 按照 id 自动排序。就很郁闷。
