### ISSUE TITLE
逻辑删除 查询 最左前缀匹配

### ISSUE THREAD

**Issue by cubes94** [baomidou/mybatis-plus#5161]
### 当前使用版本(必填,否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.2</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
背景：在类AbstractMethod中，方法sqlWhereEntityWrapper拼接出查询条件模板。使用逻辑删除时，顺序为：WRAPPER_ENTITY、LogicDeleteSql、WRAPPER_SQLSEGMENT。
问题：使用自定义sql时，逻辑删除判断在最前面，无法使用mysql最左前缀匹配。
改进：希望能把LogicDeleteSql条件放到最后，或者提供配置去改变查询顺序。

### 重现步骤(如果有就写完整)
-

### 报错信息
-

**Comment by miemieYaho** [comment]
没办法放最后面
