### ISSUE TITLE
使用了逻辑删除@TableLogic，但是有的接口查询需要查所有的

### ISSUE THREAD

**Issue by silence1011** [baomidou/mybatis-plus#5164]
### 当前使用版本(必填,否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
    您好，我使用了逻辑删除@TableLogic，但是现在有个接口，需要查询所有的数据，包括已经删除的，但是我们现在已经使用了逻辑删除，就不会查询包含删除的数据了，目前我们有没有什么注解或者方法可以实现，个别查询方法屏蔽掉逻辑删除的功能，就像如果我们加了拦截器，但是确实有的接口需要全表更新或者删除的时候，可以加那个注解@InterceptorIgnore就可以实现了，谢谢

**Comment by xy9860** [comment]
https://baomidou.com/pages/6b03c5/
![image](https://user-images.githubusercontent.com/25838633/221470593-1d8e3989-56a5-4fcb-8095-7413b2310d35.png)

**Comment by silence1011** [comment]
谢谢你，这个我也看到了，但是我就一个接口用到，如果用状态去表示确实可以解决，但是问题是逻辑删除的功能就要自己实现了，我觉得麻烦，所以才想咨询下我们有没有什么方法可以实现，谢谢你的回复

**Comment by Y-Meta** [comment]
> 

一个接口用到的话直接xml写sql就行了吧

**Comment by silence1011** [comment]
> https://baomidou.com/pages/6b03c5/ ![image](https://user-images.githubusercontent.com/25838633/221470593-1d8e3989-56a5-4fcb-8095-7413b2310d35.png)

谢谢你，这个我也看到了，但是我就一个接口用到，如果用状态去表示确实可以解决，但是问题是逻辑删除的功能就要自己实现了，我觉得麻烦，所以才想咨询下我们有没有什么方法可以实现，谢谢你的回复

**Comment by silence1011** [comment]
> > 
> 
> 一个接口用到的话直接xml写sql就行了吧

嗯嗯，就是想问问有没有自带的解决方法可以实现

**Comment by c332030** [comment]
也就是说，删了的数据，没法再通过 mybatis plus 查出来了，数据都不由自己掌控了，不写 xml 的情况下
