### ISSUE TITLE
强烈建议讲@Table等实体类相关注解单独放到一个包进行解耦！！！！！

### ISSUE THREAD

**Issue by wangtianruipopo** [baomidou/mybatis-plus#5166]
微服务之间的实体类可以共用，但是包不解耦就很难受，解耦后可以无所顾虑的创建公共包存放实体类了

**Comment by miemieYaho** [comment]
现在不是吗?

**Comment by wangtianruipopo** [comment]
> 现在不是吗?

不是啊，我要用这个注解必然要引入mybatis-plus这个包吧？然后引入了这个包之后，其他地方引入实体类的包，那是不是得把数据库这一套也搞进来？这样就耦合了呀！
有可能我的某个业务逻辑包就是单纯操作传过来的数据，并不需要去查数据库，但是因为这个耦合，就必须得把数据库引入，不引入的话，我就用不了那个实体类，这种办法就必须再新建一个类，传到这个业务逻辑包里面去

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/221525150-ffd57ecc-e99d-4fad-a5c1-893994861c2b.png)
???
