### ISSUE TITLE
mapper上使用InterceptorIgnore注解，但是pagehelper的count查询不能取消租户注入

### ISSUE THREAD

**Issue by xukaisjz** [baomidou/mybatis-plus#5167]
### 当前使用版本(必填,否则不予处理)
mybatis-plus版本：3.4.2
pagehelper版本：1.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在mapper方法上添加InterceptorIgnore取消租户注入行为
在mapper方法前使用了pagehelper的startPage方法，在执行count查询时会注入租户查询条件

### 重现步骤(如果有就写完整)
startPage()
baseMapper.selectPageListByCondition(params);

**Comment by miemieYaho** [comment]
把他的分页插件放到mp的插件后面

**Comment by xukaisjz** [comment]
> 
像这样？
  @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor()
    {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
      // 多租户
        interceptor.addInnerInterceptor(tenantLineInnerInterceptor());
      // 分页插件
        interceptor.addInnerInterceptor(paginationInnerInterceptor());
        // 乐观锁插件
        interceptor.addInnerInterceptor(optimisticLockerInnerInterceptor());
        // 阻断插件
        interceptor.addInnerInterceptor(blockAttackInnerInterceptor());
        return interceptor;
    }

**Comment by xukaisjz** [comment]
> 把他的分页插件放到mp的插件后面

像这样？
@bean
public MybatisPlusInterceptor mybatisPlusInterceptor()
{
MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
// 多租户
interceptor.addInnerInterceptor(tenantLineInnerInterceptor());
// 分页插件
interceptor.addInnerInterceptor(paginationInnerInterceptor());
// 乐观锁插件
interceptor.addInnerInterceptor(optimisticLockerInnerInterceptor());
// 阻断插件
interceptor.addInnerInterceptor(blockAttackInnerInterceptor());
return interceptor;
}

**Comment by miemieYaho** [comment]
你不是用pagehelper吗?`@Bean`他的插件到mp的插件的所在代码行数的后面

**Comment by zldaysleepy** [comment]
我也遇到了,请问有好的解决方案吗

**Comment by xukaisjz** [comment]
自定义一个注解，通过设置标记，在租户注入那里增加标记判断，可以用Threadlocal添加一个变量标记

**Comment by qichhhhh** [comment]
> 你不是用pagehelper吗?`@Bean`他的插件到mp的插件的所在代码行数的后面

@miemieYaho 你好，我也遇到了这个问题，@Bean 的声明顺序是这样的，但是在 PageHelper 的 COUNT 的语句还是把 tenant_id 拼接了
![image](https://github.com/baomidou/mybatis-plus/assets/24191302/bb9bdc88-ce9c-4ada-925a-f9a6445508af)
![image](https://github.com/baomidou/mybatis-plus/assets/24191302/1d26c794-6048-4c9c-8bbd-eeace5170a40)

![image](https://github.com/baomidou/mybatis-plus/assets/24191302/0cfa6906-dd5a-461d-b6dd-6a319e1001eb)

**Comment by zldaysleepy** [comment]
你放反了,PageInterceptor需要在前面,因为先注入的后执行

**Comment by qichhhhh** [comment]
> 你放反了,PageInterceptor需要在前面,因为先注入的后执行

谢谢大哥，可以了
