### ISSUE TITLE
update语句的执行和数据库的更新是同步还是异步? update语句会等数据库更新完后才往下走吗？

### ISSUE THREAD

**Issue by lingshao9537** [baomidou/mybatis-plus#5168]
### 当前使用版本(必填,否则不予处理)
2.0.8

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
springboot项目集群环境  mysql主主复制  先执行update语句 然后kafka通知另一台机器 执行select语句 select查到的更新前数据 

### 提问
update语句的执行 和 数据库的更新 是同步还是异步  update语句会等数据库更新完后才往下走吗？

**Comment by miemieYaho** [comment]
问jdbc
