### ISSUE TITLE
entity模板生成问题

### ISSUE THREAD

**Issue by dabaisk** [baomidou/mybatis-plus#517]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis.plus.version=3.0.2

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
MySQL blob类型，entity的xml应添加<result column="data" property="data" typeHandler="org.apache.ibatis.type.BlobTypeHandler" />！！！！
MySQL tinyint类型，entity生成为Boolean类型！！！！

### 重现步骤
MySQL blob类型，entity的xml应添加<result column="data" property="data" typeHandler="org.apache.ibatis.type.BlobTypeHandler" />！！！！
MySQL tinyint类型，entity生成为Boolean类型！！！！

### 报错信息
entity生成属性类型错误！！！！

**Comment by miemieYaho** [comment]
对于默认的不满意你可以写自己的 convert

**Comment by dabaisk** [comment]
找到了MySqlTypeConvert怎么用呢，生成的时候可以设置吗？

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-generator

**Comment by dabaisk** [comment]
解决了，DataSourceConfig.setTypeConvert
