### ISSUE TITLE
代码生成postgresql的表时报错，“关系不存在”

### ISSUE THREAD

**Issue by reixuemin** [baomidou/mybatis-plus#5171]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
生成代码时，我看查询表字段的语句是这个，pg_class.oid的传参也是表名，但是我这边的pg_class.oid字段都是数字，是不是查询表字段的语句写错了，还是说有数据库的版本兼容问题？
![image](https://user-images.githubusercontent.com/14087655/222641100-9e46753e-6ead-4ad3-a8b4-358664c72013.png)
![image](https://user-images.githubusercontent.com/14087655/222641347-8b513afc-58c5-4e8d-bcac-5a07d4b26401.png)
![image](https://user-images.githubusercontent.com/14087655/222641293-31b4f914-4381-474f-a756-4cff6e804fd1.png)

**Comment by qmdx** [comment]
无法重现该问题，能否提供数据库版本 、建表语句 、生成器配置
