### ISSUE TITLE
数据库字段驼峰命名，自动转换成了下划线

### ISSUE THREAD

**Issue by unclechenjw** [baomidou/mybatis-plus#5174]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我司数据库字段名是驼峰模式，设置了 mapUnderscoreToCamelCase 为false，希望不对数据库字段名进行驼峰映射

### 重现步骤(如果有就写完整)
Mapper 继承 extends BaseMapper<Po>
调用 selectById 方法，生成Sql 字段名变成了下划线分割模式

### 报错信息
导致了 java.sql.SQLSyntaxErrorException: Unknown column 异常

**Comment by unclechenjw** [comment]
烦请帮忙看下，谢谢了

**Comment by miemieYaho** [comment]
你的配置没生效

**Comment by unclechenjw** [comment]
![image](https://user-images.githubusercontent.com/13768596/223054145-6bc6506a-d19a-4d25-a983-4646b74d0608.png)

debug断点【sessionFactory.getObject().getConfiguration().setMapUnderscoreToCamelCase(false);】
这行代码运行到了，是配置错地方了吗

**Comment by miemieYaho** [comment]
debug看`TableInfoHelper#initTableInfo`,查看你那个值

**Comment by unclechenjw** [comment]
处理好了，谢谢，打扰了
