### ISSUE TITLE
想合入新类型数据库方言

### ISSUE THREAD

**Issue by yangmeng66** [baomidou/mybatis-plus#5175]
### 当前使用版本(必填,否则不予处理)
v3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
疑问一: 
       在国产数据库的大背景下, 我们也是其中之一, 类似达梦, tidb等等, 这是我们的官网(http://doc.yashandb.com/), 我们也想全面的兼容你们这么优秀且很受欢迎的框架, 这这个连接中看到不同数据库的差异仅仅分页方言和代码生成(https://github.com/baomidou/mybatis-plus/issues/new),那么请问下如果我们想把我们数据库的方言合入你们社区都需要经过哪些测试呢?  具体有文档吗? 非常感谢

疑问2: 
      看到com.baomidou.mybatisplus.annotation.DbType支持的很多我们国产数据库, 但是在IDialect子类中却没有看到一一对应的数据库分页方言, 想问下这个是混用的吗? 比如tidb直接选择mysql就好了?

**Comment by miemieYaho** [comment]
差异是只有分页方言和代码生成
分页方言不会写重复的东西可以查看`DialectFactory.getDialect`方法

**Comment by yangmeng66** [comment]
好的, 感谢回复

**Comment by yangmeng66** [comment]
哦哦, 好的原来是这样的, 那我们的数据库是支持mysql和oracle的分页方式的, 那也就不需要单独的分页方言了,直接用oracle即可, 对了, 还有我们国产数据库YashanDB后续也会提PR关于方言和代码自动生成, 请问都需要经过哪些测试才能合入到你们master上呢? 是通过各个模块下面的test吗?

**Comment by qmdx** [comment]
> 哦哦, 好的原来是这样的, 那我们的数据库是支持mysql和oracle的分页方式的, 那也就不需要单独的分页方言了,直接用oracle即可, 对了, 还有我们国产数据库YashanDB后续也会提PR关于方言和代码自动生成, 请问都需要经过哪些测试才能合入到你们master上呢? 是通过各个模块下面的test吗?

3.0 分支

**Comment by miemieYaho** [comment]
既然支持mysql为何不默认使用mysql方言

**Comment by yangmeng66** [comment]
@miemieYaho 
 1 你好, 是这样的, 虽然我们DB是支持mysql/oracle份分页的, 但是协议是不一样的, jdbc:yasdb://192....., 
 2 还有我看DbType类中也有许多国产数据库的身影, 所以我们也想在你们这么优秀的框架中体现一下, 像下面的这些代码我理解也需要适配一下

```
com.baomidou.mybatisplus.extension.toolkit.JdbcUtils#getDbType(java.lang.String)
com.baomidou.mybatisplus.extension.plugins.pagination.DialectFactory#getDialect
```

**Comment by yangmeng66** [comment]
@qmdx 
好的, 谢谢回复

**Comment by yangmeng66** [comment]
@miemieYaho
您好, 我汇总了一下, 就DbType.java, DialectFactory,java, 代码生成的相关特殊语法类, 
麻烦问下如果要合入到你们优秀社区3.0的话只需要都需要什么测试呢?  全量跑通单元测试可以吗? 期待您的回复..

**Comment by miemieYaho** [comment]
不需要那么复杂

**Comment by miemieYaho** [comment]
注意好格式化代码就行了

**Comment by yangmeng66** [comment]
好的，没问题，感谢你的回复，期待合入
这个issue，我会在合入后关闭哈
