### ISSUE TITLE
Mybatis-plus 如何通过kerberos+impala实现客户端身份认证？

### ISSUE THREAD

**Issue by xiaomaiyun** [baomidou/mybatis-plus#5178]
### 当前使用版本(必填,否则不予处理)
master

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Mybatis-plus 如何通过kerberos+impala实现客户端身份认证？

### 重现步骤(如果有就写完整)
Mybatis-plus 如何通过kerberos+impala实现客户端身份认证？

### 报错信息
[Mybatis-plus 如何通过kerberos+impala实现客户端身份认证？](https://blog.csdn.net/herendong/article/details/126323260)

**Comment by huayanYu** [comment]
自己处理
