### ISSUE TITLE
自定义IKeyGenerator通过@Bean方式配置不生效

### ISSUE THREAD

**Issue by duans0217** [baomidou/mybatis-plus#518]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatisplus-spring-boot-starter   1.0.5
mybatis-plus   2.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

自定义IKeyGenerator通过@Bean方式配置不生效，只能通过
mybatis-plus.global-config.key-generator=com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
这个版本没有从自动从bean工厂拿吗？

**Comment by miemieYaho** [comment]
你用的 bootstart 是上古版本,使用如下版本
http://mvnrepository.com/artifact/com.baomidou/mybatis-plus-boot-starter/2.3.2

**Comment by duans0217** [comment]
多谢，更新版本后可以了。
