### ISSUE TITLE
selectPage分页失效

### ISSUE THREAD

**Issue by yfgcq** [baomidou/mybatis-plus#5180]
### 当前使用版本(必填,否则不予处理)
mybati-plus 3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
selectPage分页失效

    @Bean
    public MybatisPlusInterceptor pageInnerInterceptor() {
        MybatisPlusInterceptor paginationInnerInterceptor = new MybatisPlusInterceptor();
        paginationInnerInterceptor.addInnerInterceptor(new PaginationInnerInterceptor());
        return paginationInnerInterceptor;
    }
![微信截图_20230308144215](https://user-images.githubusercontent.com/6744449/223643249-971be4ff-e0e4-446a-9a13-c08e35ba77b7.png)
![微信截图_20230308144331](https://user-images.githubusercontent.com/6744449/223643278-44e5e502-606e-4127-9d26-0c8869e7d794.png)

**Comment by qmdx** [comment]
看看是不是其它 mybatis 组件干扰，例如其它分页插件 pageHelper

**Comment by huayanYu** [comment]
无回复,关闭

**Comment by otaku-bowei** [comment]
碰到了同样的情况

**Comment by SeakyLuo** [comment]
+1

**Comment by drinkagain** [comment]
遇到同样的问题，是怎么解决的啊
