### ISSUE TITLE
雪花ID不生效

### ISSUE THREAD

**Issue by yss0729** [baomidou/mybatis-plus#5185]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用 IdType.ASSIGN_ID  主键策略，打印sql 生成的id是1 ， 数据库字段类型是bigint(20) ，实体类id是Long类型，用新版本也没用。
另 IdType.ASSIGN_UUID 是正常工作的。

**Comment by huayanYu** [comment]
无法复现,检查是否有自增.请描述详细复现步骤.,重新提交PR

**Comment by huayanYu** [comment]
重新提交issue
