### ISSUE TITLE
nested exception is org.apache.ibatis.exceptions.PersistenceException:  Cause: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by killSomebody** [baomidou/mybatis-plus#5197]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

代码运行一段时间就会这样 

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

**Comment by nieqiurong** [comment]
提供一个完整的堆栈日志或者示例工程吧

**Comment by qmdx** [comment]
无法定位，未及时反馈暂时关闭，反馈后打开
