### ISSUE TITLE
3.5.3.1typeConvert配置不生效，文档说明不全

### ISSUE THREAD

**Issue by qingpei88800** [baomidou/mybatis-plus#5199]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
        Builder dataSourceConfigBuilder =
                new DataSourceConfig.Builder("j",
                        "",
                        "")
                        .schema("gifshow")
                        .typeConvert(new MySqlTypeConvertCustom());

### 重现步骤(如果有就写完整)
必现

### 报错信息
设置的typeConvert没有作用，

解决：
默认的databaseQueryClass是的DefaultQuery，这个不会使用typeConvert，而是使用getTypeConvertHandler。
要想typeConvert生效，必须指定databaseQueryClass为SQLQuery。这个文档里没有说明

**Comment by wangran99** [comment]
`new DataSourceConfig.Builder("jdbc:mysql://127.0.0.1:3306/mybatis-plus","root","123456")
    .dbQuery(new MySqlQuery())
    .schema("mybatis-plus")
    .typeConvert(new MySqlTypeConvert())
    .keyWordsHandler(new MySqlKeyWordsHandler())
    .build();`

遇到同样问题。默认的FastAutoGenerator生成的tinyint(1)为Byte类型，希望为Boolen。自定义typeConvert无效，更改databaseQueryClass才生效，希望文档更新一下。

**Comment by lontten** [comment]
+1

**Comment by nieqiurong** [comment]
已更新
