### ISSUE TITLE
同时开启逻辑删除和乐观锁插件，执行逻辑删除报错

### ISSUE THREAD

**Issue by dinglin** [baomidou/mybatis-plus#52]
Dao执行 delete(Long)操作时，因为逻辑删除，delete转换未update语句处理没有问题。
update会触发乐观锁插件OptimisticLockerInterceptor处理，执行到如下代码时，parameterObject不再是实体对象，会报错
`final Object versionValue = versionField.get(parameterObject);`

**Comment by Caratacus** [comment]
2.0.9新版本解决
