### ISSUE TITLE
AutoGenerator是否可以支持自动跳过父类的字段？

### ISSUE THREAD

**Issue by acxlam** [baomidou/mybatis-plus#520]
### `当前使用版本`
3.0.3

### 该问题是怎么引起的？
系统不同的实体使用不同的父类，能否尝试通过Classs.forName自行跳过父类的字段？现在只能自己写代码获取，不是很方便。

```  
//  strategy.setSuperEntityColumns(fieldsToUnderScore(Class.forName("xxxx")));

private static List<String> fieldsToUnderScore(Class<?> clazz) {

		List<String> allFields =  Arrays.stream(clazz.getDeclaredFields())
				.map(field -> CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, field.getName())).collect(
						Collectors.toList());

		//父类属性一并加上
		Class<?> parentClass = clazz.getSuperclass();

		if (parentClass != null) {
			allFields.addAll(fieldsToUnderScore(parentClass));
		}

		return allFields;

	}
   
	



```

**Comment by qmdx** [comment]
不看源码至少看下文档吧， 
        strategy.setSuperEntityColumns("id", .....);

**Comment by acxlam** [comment]
> 
> 
> 不看源码至少看下文档吧，
> strategy.setSuperEntityColumns("id", .....);

但是这样要人工填入每个字段。

**Comment by qmdx** [comment]
反射需求会考虑

**Comment by qmdx** [comment]
请关注 3.0.8 发布，已支持 https://gitee.com/baomidou/mybatis-plus/commit/8e11a5a876d2e12e9f8a80a9378f4bb28ad54748  测试用例 https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/test/java/com/baomidou/mybatisplus/test/generator/StrategyConfigTest.java
