### ISSUE TITLE
增加一个新特性-类似JPA的批量查询迭代器的分页功能

### ISSUE THREAD

**Issue by zhuobinchan** [baomidou/mybatis-plus#5203]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-core-3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
其实是希望增加一个新特性，类似JPA中 Slice的实现（https://www.baeldung.com/spring-data-jpa-iterate-large-result-sets)
因为其实很多时候下载场景就是需要分页方式的一批批获取数据，每次自己手写迭代器其实是一个很通用的做法

请问作者有没有这方面的实现的打算，因为我翻了一下源码和文档都没有找到类似的功能；还有接受这个新特性的pr吗？

**Comment by qmdx** [comment]
分页插件？？ https://baomidou.com/pages/97710a/#paginationinnerinterceptor 
还是什么功能，具体说下？？

**Comment by zhuobinchan** [comment]
> 分页插件？？ https://baomidou.com/pages/97710a/#paginationinnerinterceptor 还是什么功能，具体说下？？

是的，就是分页插件增强，比较方便的 不断循环获取下一页数据，直到根据条件查询出所有数据，最好是能直接使用 Iterator 的接口特性来 获取所有数据

**Comment by qmdx** [comment]
> > 分页插件？？ https://baomidou.com/pages/97710a/#paginationinnerinterceptor 还是什么功能，具体说下？？
> 
> 是的，就是分页插件增强，比较方便的 不断循环获取下一页数据，直到根据条件查询出所有数据，最好是能直接使用 Iterator 的接口特性来 获取所有数据

自己添加一个循环处理即可
