### ISSUE TITLE
修改数据后该数据会被插入在数据库尾部

### ISSUE THREAD

**Issue by winegd** [baomidou/mybatis-plus#5204]
### 当前使用版本(必填,否则不予处理)
3.5.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用3.5.3.1版本也会有此问题

### 重现步骤(如果有就写完整)
`   

 @Test
    void update_class(){
        ClassInfo classInfo = new ClassInfo("70bc19db96be77616f4566075e35559c",String.valueOf(1),String.valueOf(1));
        classInfoMapper.updateById(classInfo);
    }

`

### 报错信息

无

**Comment by miemieYaho** [comment]
mp不负责sql执行
