### ISSUE TITLE
开启逻辑删除，又需要物理删除，如何实现最好

### ISSUE THREAD

**Issue by rainLeelzr** [baomidou/mybatis-plus#521]
1：如果开启逻辑删除插件，那么需要物理删除的业务，就不能实现。
2：mybatis-plus的select语句会自动过滤掉逻辑删除的记录。如何select出来，展示给前端？

请问用什么方式实现以上2点比较好

**Comment by miemieYaho** [comment]
写xml

**Comment by rainLeelzr** [comment]
我想是通用的，就像BaseMapper的方法一样，所有entity都可以直接用

**Comment by miemieYaho** [comment]
那就注入自定义全局方法,[参考](https://baomidou.gitee.io/mybatis-plus-doc/#/sql-injector)

**Comment by wangjia2016** [comment]
应该考虑扩充一个物理删除方法的
