### ISSUE TITLE
orace 修改数据类型问题

### ISSUE THREAD

**Issue by huh0ngtao** [baomidou/mybatis-plus#5211]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 重现步骤(如果有就写完整)
Oracle字段类型为varchar2，然后修改数据类型为nvarchar2，保存数据没有问题，查询数据有时候会返回乱码，但是重启服务就没有问题了。
oracle版本为11，字符集AMERICAN _ AMERICA. ZHS16GBK

xml文件没有映射jdbcType

### 报错信息
返回数据偶尔乱码

大佬，想问下这个问题是什么原因导致的，是解析结果集的时候的映射不对导致的吗？

**Comment by miemieYaho** [comment]
不知道,数据封装是mybatis的事

**Comment by qmdx** [comment]
jdbcType 问题默认注入 SQL 你可以通过 TableField 属性 jdbcType 指定，字符集问题自行解决
