### ISSUE TITLE
插入后返回的id和数据库中的id不一致

### ISSUE THREAD

**Issue by lgl97git** [baomidou/mybatis-plus#5212]
### 当前使用版本(必填,否则不予处理)
3.5.3.1
![image](https://user-images.githubusercontent.com/52186988/227133810-7b494fa4-be61-48a5-a98f-c89d68c9b234.png)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用的mp最新版本，mysql5.7
当我把注解：@TableId(value = "id", type = IdType.AUTO)    注释以后不会有该问题
![image](https://user-images.githubusercontent.com/52186988/227135006-165ee446-cef7-4e82-8fe8-688f97b4ed9d.png)
![image](https://user-images.githubusercontent.com/52186988/227136254-b92c92a5-a19f-40d0-92fd-685384aacbb3.png)

### 重现步骤(如果有就写完整)
准备一个list对象集合，集合里需要带上id，而不是让id自增
进行批量插入操作后
用该list中的id进行其他操作，发现list中的id和数据库中的id不一致，导致出错

### 报错信息
无

**Comment by wsliliang** [comment]
@lgl97git 我使用原始的jdbc和mysql驱动试过了，这个应该不是mybatisplus的问题，应该是mysql驱动和mysql数据库的问题（也许不能叫做问题，可以说不能这样用），你可以用jdbc和PreparedStatement试试，返回的id确实是不对的。

**Comment by wsliliang** [comment]
@lgl97git 我在这里#5209 回复了这个问题，你可以参考验证一下
