### ISSUE TITLE
type-aliases-package别名设置问题，A module依赖B module

### ISSUE THREAD

**Issue by wqbill** [baomidou/mybatis-plus#5216]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
原来使用是mybatis，有两个module都设置了别名：mybatis.type-aliases-package
A module依赖B module
切换成mybatis-plus后设置不生效，于是改成了：mybatis-plus.type-aliases-package
启动A module报错 提示找不到B module里的类（B中mapper.xml中别名对应的类）
启动B module正常
去掉mybatis-plus恢复mybatis正常

补充说明一下
mybatis-plus.type-aliases-package=Apackage,Bpackage
可以正常运行
但是mybatis不需要这样，能把B的配置直接读出来

### 报错信息
```
Failed to parse mapping resource: 'file [D:\B module\target\classes\mapper\production\BEntityMapper.xml]'
```

**Comment by cobight** [comment]
### 版本

**Comment by nieqiurong** [comment]
提供一个示例工程上来看看,typeAliasesPackage这块没做特别的处理,和mybatis原来一样的.

**Comment by qmdx** [comment]
未及时反馈暂时关闭，请反馈后打开
