### ISSUE TITLE
雪花主键冲突

### ISSUE THREAD

**Issue by deanjoson** [baomidou/mybatis-plus#5217]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
K8S集群下，5副本部署springboot应用，压测时接口中调用saveBatch偶发

### 报错信息
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/4687434/227690544-e54a540b-58cc-46da-a426-fccc60dfdea3.png">

**Comment by qmdx** [comment]
同一个物理主机多个节点可能存在冲突问题的，因为雪花算法基础因子一样。你可以通过 初始化设置不同节点雪花算法参数不一致来解决  https://baomidou.com/   自定义ID生成器  部分参考，注入 DefaultIdentifierGenerator 方法 long workerId, long dataCenterId 参数
