### ISSUE TITLE
DefaultSqlInjector进行多余的MappedStatement添加

### ISSUE THREAD

**Issue by Cw404** [baomidou/mybatis-plus#5218]
### 当前使用版本(必填,否则不予处理)
3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当Mapper接口父类为com.baomidou.mybatisplus.core.mapper.Mapper超级类时，DefaultSqlInjector（SQL 默认注入器）依然会注入单表的MappedStatement（Insert等），这显得是多余的

### 重现步骤(如果有就写完整)
项目事例代码：
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/43946403/227705627-dd2088fb-1cbc-4391-b21a-c6a4c6a965b8.png">

运行情况：
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/43946403/227705702-58f230cd-bbf0-4692-8e3e-fb99a7337fcc.png">

### 报错信息
无

**Comment by miemieYaho** [comment]
就是这样的

**Comment by Cw404** [comment]
这显然是基础Mapper的设计约定，非常感谢🙏
