### ISSUE TITLE
[FEATURE] 自动注入 sql 应避免逻辑删除字段条件重复

### ISSUE THREAD

**Issue by insight720** [baomidou/mybatis-plus#5220]
### 需求或者改进建议

在配置逻辑删除后使用自动注入 SQL（即不手写 SQL），无论是否手动设置逻辑删除字段条件，自动注入 SQL 都会添加逻辑删除字段条件。上述情况下，如果手动设置逻辑删除字段条件，则自动注入的 SQL 中逻辑删除条件会重复。

### 建议的实现方案

*在上述情况下，如果已经手动设置了逻辑删除字段条件，则不再重复添加逻辑删除字段条件。*

### 替代方案

*可以添加临时禁用自动添加 SQL 条件的 API，方便使用。*

**Comment by miemieYaho** [comment]
不支持
