### ISSUE TITLE
exists 性能优化

### ISSUE THREAD

**Issue by GOODBOY008** [baomidou/mybatis-plus#5223]
### 当前使用版本(必填,否则不予处理)
[v3.5.3.1](https://github.com/baomidou/mybatis-plus/releases/tag/v3.5.3.1)
### 性能问题
目前 exists  是通过 count 来实现的，大表情况性能会有问题。可以考虑 select * from table limit 1 （mysql下）通过判断返回list大小来实现。

@miemieYaho 是否可以采纳？我很乐意提交PR，谢谢~

**Comment by miemieYaho** [comment]
分页方式不存在通用性

**Comment by GOODBOY008** [comment]
> 分页方式不存在通用性
@miemieYaho 你好，
可以借助现有的`com.baomidou.mybatisplus.extension.plugins.pagination.dialects.IDialect`来解决数据库方言问题，因为这个接口已经做了各种数据库方言适配。

**Comment by miemieYaho** [comment]
不是所有人都是单一数据源

**Comment by GOODBOY008** [comment]
@miemieYaho 我实现了一版，你可以帮忙看看吗？

**Comment by miemieYaho** [comment]
这个又必须依赖分页插件

**Comment by GOODBOY008** [comment]
> 这个又必须依赖分页插件

是的，因为page插件做了多数据库限制返回的方言。
