### ISSUE TITLE
生成的sql语句中用户定义标识符（表名、属性名）没有加上`，导致某些敏感标识符出错

### ISSUE THREAD

**Issue by Crazyokd** [baomidou/mybatis-plus#5227]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
用户使用的表名、字段名比较敏感

### 重现步骤(如果有就写完整)
使用特殊标识符，如`group`

### 报错信息
```
org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax;
```

**Comment by Crazyokd** [comment]
由于我在我的项目中因为需求使用了group作为表名，但group在mysql中属于关键词（group by），故导致生成的sql报错。
个人感觉解决应该不难，只要为所有用户定义标识符自动加上`即可。现代自动生成sql的工具也确实是这样处理的。

**Comment by miemieYaho** [comment]
自己在注解上加

**Comment by Crazyokd** [comment]
好奇为什么不做成默认的？

**Comment by leimeng-ma** [comment]
> 不同数据库的转义方式是不一样的
