### ISSUE TITLE
您好，官方文档的代码生成器新 全局覆盖文件方法过期了

### ISSUE THREAD

**Issue by gaoyang123gy** [baomidou/mybatis-plus#5228]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用官方文档里的代码生成器(新) 快速生成 发现 文件覆盖方法过期了

### 重现步骤(如果有就写完整)

@Test
    void generator() {

        FastAutoGenerator.create("url",
                        "username",
                        "password")

                .globalConfig(builder -> {
                    builder.author("yang") // 设置作者
                            .enableSwagger() // 开启 swagger 模式
                            .fileOverride() // 覆盖已生成文件
                            .outputDir(System.getProperty("user.dir") + "/src/main/java"); // 指定输出目录
                })
                .packageConfig(builder -> {
                    builder.parent("com.xxxx") // 设置父包名
                            //.moduleName("springboot") // 设置父包模块名
                            .pathInfo(Collections.singletonMap(OutputFile.xml, "D://")); // 设置mapperXml生成路径
                })
                .strategyConfig(builder -> {
                    builder
                            .addInclude("t_user") // 设置需要生成的表名
                            .addTablePrefix("t_", "c_"); // 设置过滤表前缀
                })
                .templateEngine(new FreemarkerTemplateEngine()) // 使用Freemarker引擎模板，默认的是Velocity引擎模板
                .execute();
    }

### 报错信息

10:42:09.737 [main] WARN com.baomidou.mybatisplus.generator.config.GlobalConfig -- 全局覆盖已有文件的配置已失效，已迁移到策略配置中

**Comment by walkkong** [comment]
我遇到同样的问题，后来发现官方的这个文档，策略配置中有提到
![image](https://user-images.githubusercontent.com/55477781/230000210-a0900f58-29c6-4953-bc33-2cc285456198.png)



文档在：https://baomidou.com/pages/981406/#service-%E7%AD%96%E7%95%A5%E9%85%8D%E7%BD%AE

**Comment by gaoyang123gy** [comment]
是的，我发现entity、Controller、Service、Mapper策略配置分别可以开启对应的文件覆盖，但没有找到一个方法可以直接开启全部的文件覆盖

**Comment by walkkong** [comment]
> 是的，我发现entity、Controller、Service、Mapper策略配置分别可以开启对应的文件覆盖，但没有找到一个方法可以直接开启全部的文件覆盖

我也没找到，看官方的回复吧，可以暂时使用分别开启的方式

**Comment by qmdx** [comment]
```
    public void testFileOverride() {
        AutoGenerator generator = new AutoGenerator(DATA_SOURCE_CONFIG);
        generator.strategy(strategyConfig()
            // 实体文件覆盖
            .entityBuilder().enableFileOverride()
            // Mapper文件覆盖
            .mapperBuilder().enableFileOverride()
            // Service文件覆盖
            .serviceBuilder().enableFileOverride()
            // Controller文件覆盖
            .controllerBuilder().enableFileOverride()
            .build());
        generator.execute();
    }
```
