### ISSUE TITLE
分页插件setCountId，租户插件会失效

### ISSUE THREAD

**Issue by zhongjun96** [baomidou/mybatis-plus#5231]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

分页插件自定义Count语句，设置CountId，生成的语句未携带租户id

### 重现步骤(如果有就写完整)

```
// 自定义count 未携带租户id
Page<Dome> page = new Page<>(request.getPageNum(), request.getPageSize());
page.setCountId("dome_Count");
```

**Comment by miemieYaho** [comment]
租户插件放前面

**Comment by zhongjun96** [comment]
> 租户插件放前面

现在就是租户插件最前面。不指定countId，生成的count sql带租户id。
指定countId，生成的就不带租户id

**Comment by miemieYaho** [comment]
目前看来不行,指定的countId是直接用Executor.query查出的count,没法再走一遍插件

**Comment by qmdx** [comment]
自定义 count 你可以考虑自行传入 租户 ID 内容
