### ISSUE TITLE
no

### ISSUE THREAD

**Issue by KYV365** [baomidou/mybatis-plus#5232]
1

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/229682142-d7289ef5-61a3-4c32-ac2b-7bf5c6d909b6.png)
你最好给出你的复现demo以git形式

**Comment by raojun0504** [comment]
> ![image](https://user-images.githubusercontent.com/28334419/229682142-d7289ef5-61a3-4c32-ac2b-7bf5c6d909b6.png) 你最好给出你的复现demo以git形式

第一页10条已经更新成2了，但是第二页查询没有数据。如果第一页current=0就没有问题，但是Page对象里面，current默认等于1
![image](https://user-images.githubusercontent.com/49931739/229757053-d652d66f-0b34-4d94-afdb-84dde73c9545.png)
![image](https://user-images.githubusercontent.com/49931739/229757174-d06a0c73-ab1b-4f48-a5be-16746237828e.png)
![image](https://user-images.githubusercontent.com/49931739/229757238-05927d3c-caf3-4473-87b3-1bae70f554f8.png)
