### ISSUE TITLE
ASSIGN_ID在集群下出现了重复

### ISSUE THREAD

**Issue by oday-xiexin** [baomidou/mybatis-plus#5233]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在集群下 插入日志表偶然告警了一次 我一共就四台机器 经过查看一台成功插入 一台主键冲突报错

### 重现步骤(如果有就写完整)
无 不知道如何复现

### 报错信息

![image](https://user-images.githubusercontent.com/40761282/229722010-85a22a8a-7daf-4e0b-84cd-8e2b28726191.png)

**Comment by oday-xiexin** [comment]
我是老版本升级上来的 老版本的ID_WORKER_STR好像没出现这个问题过倒是新版的ASSIGN_ID出现过

**Comment by miemieYaho** [comment]
新老版本没有区别,你是docker容器内?java11及以上使用如下命令查看应用的`数据标识 ID`是否有重复
```shell
tee ~/H.java <<EOF
import java.net.InetAddress;
import java.net.NetworkInterface;
public class HelloWorld{
    public static void main(String args[]) throws Exception{
    	InetAddress inetAddress = InetAddress.getLocalHost();
        NetworkInterface network = NetworkInterface.getByInetAddress(inetAddress);
        long id = 0L;
        if (null == network) {
            id = 1L;
        } else {
            byte[] mac = network.getHardwareAddress();
            if (null != mac) {
                id = ((0x000000FF & (long) mac[mac.length - 2]) | (0x0000FF00 & (((long) mac[mac.length - 1]) << 8))) >> 6;
                id = id % (32);
            }
        }
        System.out.println(id);
    }
}
EOF
java ~/H.java
```

**Comment by oday-xiexin** [comment]
> 新老版本没有区别,你是docker容器内?java11及以上使用如下命令查看应用的`数据标识 ID`是否有重复
> 
> ```shell
> tee ~/H.java <<EOF
> import java.net.InetAddress;
> import java.net.NetworkInterface;
> public class HelloWorld{
>     public static void main(String args[]) throws Exception{
>     	InetAddress inetAddress = InetAddress.getLocalHost();
>         NetworkInterface network = NetworkInterface.getByInetAddress(inetAddress);
>         long id = 0L;
>         if (null == network) {
>             id = 1L;
>         } else {
>             byte[] mac = network.getHardwareAddress();
>             if (null != mac) {
>                 id = ((0x000000FF & (long) mac[mac.length - 2]) | (0x0000FF00 & (((long) mac[mac.length - 1]) << 8))) >> 6;
>                 id = id % (32);
>             }
>         }
>         System.out.println(id);
>     }
> }
> EOF
> java ~/H.java
> ```

不是docker环境 就是正常的liunx脚本部署

**Comment by oday-xiexin** [comment]
> 新老版本没有区别,你是docker容器内?java11及以上使用如下命令查看应用的`数据标识 ID`是否有重复
> 
> ```shell
> tee ~/H.java <<EOF
> import java.net.InetAddress;
> import java.net.NetworkInterface;
> public class HelloWorld{
>     public static void main(String args[]) throws Exception{
>     	InetAddress inetAddress = InetAddress.getLocalHost();
>         NetworkInterface network = NetworkInterface.getByInetAddress(inetAddress);
>         long id = 0L;
>         if (null == network) {
>             id = 1L;
>         } else {
>             byte[] mac = network.getHardwareAddress();
>             if (null != mac) {
>                 id = ((0x000000FF & (long) mac[mac.length - 2]) | (0x0000FF00 & (((long) mac[mac.length - 1]) << 8))) >> 6;
>                 id = id % (32);
>             }
>         }
>         System.out.println(id);
>     }
> }
> EOF
> java ~/H.java
> ```

大佬 可以手动设置数据id吗 类似这样么mybatis-plus.global-config.worker-id: 5？

**Comment by miemieYaho** [comment]
没有,`DefaultIdentifierGenerator`默认是读取ip来算出`dataCenterId`,如果这个值重复那就会生成的雪花id会有重复
你也可以自己注入`DefaultIdentifierGenerator`到spring里自己保证`workerId`和`dataCenterId`不重复

**Comment by oday-xiexin** [comment]
> 没有,`DefaultIdentifierGenerator`默认是读取ip来算出`dataCenterId`,如果这个值重复那就会生成的雪花id会有重复 你也可以自己注入`DefaultIdentifierGenerator`到spring里自己保证`workerId`和`dataCenterId`不重复

希望启动debug模式可以打点日志出来 供排查

**Comment by miemieYaho** [comment]
> > 没有,`DefaultIdentifierGenerator`默认是读取ip来算出`dataCenterId`,如果这个值重复那就会生成的雪花id会有重复 你也可以自己注入`DefaultIdentifierGenerator`到spring里自己保证`workerId`和`dataCenterId`不重复
> 
> 希望启动debug模式可以打点日志出来 供排查

tee ~/H.java <<EOF
import java.net.InetAddress;
import java.net.NetworkInterface;
public class HelloWorld{
    public static void main(String args[]) throws Exception{
    	InetAddress inetAddress = InetAddress.getLocalHost();
        NetworkInterface network = NetworkInterface.getByInetAddress(inetAddress);
        long id = 0L;
        if (null == network) {
            id = 1L;
        } else {
            byte[] mac = network.getHardwareAddress();
            if (null != mac) {
                id = ((0x000000FF & (long) mac[mac.length - 2]) | (0x0000FF00 & (((long) mac[mac.length - 1]) << 8))) >> 6;
                id = id % (32);
            }
        }
        System.out.println(id);
    }
}
EOF
java ~/H.java
自己看啊

**Comment by HenryGentry** [comment]
我也发现了，用k8s部署的服务，同一台机器多个实例的话，在高并发的场景就会出现雪花ID重复的问题。
通过代码验证，发现同一机器的实例获取到的dataCenterId都是一样的

**Comment by qmdx** [comment]
如下注入自定义唯一参数

```
@Bean
public DefaultIdentifierGenerator identifierGenerator()  {
   return new DefaultIdentifierGenerator(唯一参数 `workerId` ， 唯一参数 `dataCenterId`);
}
```
