### ISSUE TITLE
mybatis-plus 3.5 内部依赖设置有问题

### ISSUE THREAD

**Issue by ban-shi-yi-sheng** [baomidou/mybatis-plus#5234]
### 当前使用版本(必填,否则不予处理)

3.5.2+

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.3.1 同样如此 
整合spring 

### 重现步骤(如果有就写完整)

    <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="dataSource" />
        <property name="configLocation" value="classpath:mybatis-config.xml"/>
    </bean>

    
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="xx.xx.xx"/>
    </bean>

### 报错信息
WARN org.springframework.context.support.ClassPathXmlApplicationContext -- Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory': Lookup method resolution failed

### 就是依赖有问题 
mybatis-plus 3.5 内部的 mybatis-spring 版本才2.0.7

**Comment by ban-shi-yi-sheng** [comment]
<img width="1108" alt="iShot_2023-04-05_08 23 48" src="https://user-images.githubusercontent.com/28346321/229950864-a7bacac7-8c58-4977-a008-e0757063230f.png">

**Comment by miemieYaho** [comment]
有什么问题?
