### ISSUE TITLE
单体项目雪花算法生成ID重复

### ISSUE THREAD

**Issue by LECYWZA** [baomidou/mybatis-plus#5238]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 重现步骤(如果有就写完整)
Springboot单体项目,只配置了
![image](https://user-images.githubusercontent.com/22796879/230867074-cc778a23-a0ec-4136-b28b-c34df6f20a8e.png)

实体类主键贴了 @TableId(type = IdType.ASSIGN_ID)
server层使用  this.saveBatch(list, list.size())   插入13000 条数据, 报错如下图

### 报错信息
![image](https://user-images.githubusercontent.com/22796879/230866808-4f71b1ee-d529-4eb6-946d-fbc97f3f8bd1.png)

请问是我没正确配置吗

**Comment by oday-xiexin** [comment]
这个版本我也遇到过

**Comment by LECYWZA** [comment]
解决了,是我自己的问题

**Comment by oday-xiexin** [comment]
> 解决了,是我自己的问题

你是什么问题导致的呀

**Comment by LECYWZA** [comment]
集合中多个对象内存地址相同。导致改一个变多个。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月11日(周二) 晚上7:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [baomidou/mybatis-plus] 单体项目雪花算法生成ID重复 (Issue #5238)




  
解决了,是我自己的问题
  
你是什么问题导致的呀
