### ISSUE TITLE
能否提供类似pagehelper的全局分页功能

### ISSUE THREAD

**Issue by yixiaco** [baomidou/mybatis-plus#5239]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 描述
使用mp提供的分页插件，在使用查询同一条语句的分页与不分页的情况下不方便，需要写两个方法。
而使用ph插件只需要写一个方法，通过本地线程变量注入分页参数即可实现一个方法即可以分页也可以不分页。
使用场景：
在执行分页查询时，与导出数据时。

### 问题
租户插件与ph插件存在不兼容情况及以后可能出现的其他不兼容情况

**Comment by huayanYu** [comment]
没有,你可以贡献,

**Comment by JaneYork** [comment]
> 没有,你可以贡献,

怎么返回，是否有下一页hasNextPage。  @huayanYu
