### ISSUE TITLE
mp 主键注解类名是？

### ISSUE THREAD

**Issue by TonyYule** [baomidou/mybatis-plus#524]
mp 主键注解类名是？

对框架不了解 想加入群 还要回答问题 
不知道啊啊啊啊啊啊

**Comment by miemieYaho** [comment]
那就去看文档 https://baomidou.gitee.io/mybatis-plus-doc/#/

**Comment by TonyYule** [comment]
麻蛋  加个群这个麻烦 劳资 回答 是 @TableId  提示错误

**Comment by TonyYule** [comment]
不用  我用nutz
