### ISSUE TITLE
BINARY类型数据能存不能读

### ISSUE THREAD

**Issue by yaaynn** [baomidou/mybatis-plus#5241]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
问题是我将Sha3-256用binary存到了数据库,但是读出来的时候,值是Null,但是我用mapping.xml写代码就可以读取,我已经配置了, `jdbcType = JdbcType.BINARY, typeHandler = ByteArrayTypeHandler.class`.

这里需要注意的是,存入是正常的,作为查询条件也可以,日志也有数据`<<BLOB>>`, 查询之后没哟值.

**Comment by miemieYaho** [comment]
`@TableName(autoResultMap=true)`注解加了吗

**Comment by yaaynn** [comment]
> `@TableName(autoResultMap=true)`注解加了吗

好吧,问题解决了,我甚至都没有往这个方向去解决问题,在我遇到这个问题的第一反应就是给XML文件加上` jdbcType="BINARY" javaType="byte[]" typeHandler="org.apache.ibatis.type.ByteArrayTypeHandler"` 但是他只对我手写的方法有效,所以我怀疑是不是MP的查询时使用的Entity进行的,于是我就在注解上加上了`jdbcType = JdbcType.BINARY, typeHandler = ByteArrayTypeHandler.class`.后来我实在找不到资料,就到了这里尝试提出这个问题.

现在问题虽然解决了,但是我依然好奇,MP对于XML中的`resultMap`配置到底是怎么处理的.
