### ISSUE TITLE
使用mapper时没有问题，但是直接使用service的话就会报错

### ISSUE THREAD

**Issue by Mossbb** [baomidou/mybatis-plus#5243]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Invalid bound statement (not found): com.ryytn.newback.dao.service.TblRanchLiveH5BuryPointLogService.getBaseMapper

使用mapper时没有问题，但是直接使用service的话就会报这个错

### 报错信息

Invalid bound statement (not found): com.ryytn.newback.dao.service.TblRanchLiveH5BuryPointLogService.getBaseMapper

**Comment by miemieYaho** [comment]
mapperscan别扫描service包

**Comment by qmdx** [comment]
是的必须要 mapper

**Comment by Mossbb** [comment]
> 是的必须要 mapper

额，不对吧，service的默认方法不能用吗

**Comment by Mossbb** [comment]
> mapperscan别扫描service包



> mapperscan别扫描service包

感谢！！！！疏忽了，

**Comment by WarriorFromLongAgo** [comment]
当前使用版本(必填,否则不予处理)
3.3.1

该问题是如何引起的？(确定最新版也有问题再提!!!)
"Invalid bound statement (not found): cn.sffix.recovery.support.business.feedback.service.UserFeedbackSvc.getByIdService"
我无法升级我的版本，是企业项目
我在controller，调用service，我的service是没有继承mybatisplus的东西的。service下有一层manager这里继承了IService（mybatisplus的）
但是我发现，controller注入的service对象，以已经是mybatisproxy对象了。

重现步骤(如果有就写完整)
报错信息
"Invalid bound statement (not found): cn.sffix.recovery.support.business.feedback.service.UserFeedbackSvc.getByIdService"
