### ISSUE TITLE
想复写分页插件，实现在count之后，动态修改pageSize 大小

### ISSUE THREAD

**Issue by daniel031699** [baomidou/mybatis-plus#5246]
### 当前使用版本(必填,否则不予处理)
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.1.1</version>
		</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mysql数据库分页列表查询，查询到最后一页，如果超过最后一页的数量，查询巨慢。所以我想复写分页插件，在count之后，能动态修改pageSize的值。

**Comment by qmdx** [comment]
你是不是想说，例如你数据 99 条，现在每页显示 10 条查询第 10页的时候很慢？

**Comment by miemieYaho** [comment]
自己看源码搞
