### ISSUE TITLE
springboot3.0.5整合问题

### ISSUE THREAD

**Issue by wjlong1128** [baomidou/mybatis-plus#5248]
mapperscan注解会将所扫描的包下的所有接口代理为mapperproxy对象

**Comment by miemieYaho** [comment]
mybatis就是这样的

**Comment by wjlong1128** [comment]
> mybatis就是这样的

我指的是会将所扫包下面本该不属于mapper的接口代理为接口
比如service的接口

**Comment by miemieYaho** [comment]
我说的就是这个

**Comment by wjlong1128** [comment]
今天去建了个demo，果然，谢谢您的耐心
