### ISSUE TITLE
enum 在查询时会 get tableInfo导致 null point

### ISSUE THREAD

**Issue by aispringli** [baomidou/mybatis-plus#5250]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用带有枚举的查询时，在MybatisEnumTypeHandler#findEnumValueAnnotationField，会获取枚举对应的TableInfo，不明白为什么最近改动这个逻辑了，枚举不是Table，没有TableInfo导致null

### 重现步骤(如果有就写完整)
带有枚举的查询

![image](https://user-images.githubusercontent.com/25081167/232659665-e8f229b3-377b-4ac5-a3e4-f6112a4cd03e.png)

![image](https://user-images.githubusercontent.com/25081167/232660929-5231b4e7-1169-4b2d-affd-8576bd2b5bda.png)

**Comment by miemieYaho** [comment]
你用的是快照版吧

**Comment by aispringli** [comment]
> 你用的是快照版吧

master分支最新代码

**Comment by miemieYaho** [comment]
你自己打的包?

**Comment by aispringli** [comment]
> 你自己打的包?

嗯，本地打包测试，先加个功能

**Comment by miemieYaho** [comment]
那你重新pull再打个
