### ISSUE TITLE
TableField注解不起作用

### ISSUE THREAD

**Issue by zhaoshengkai-0107** [baomidou/mybatis-plus#5251]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`@ApiModelProperty(value = "更新人", hidden = true)
    @TableField(value = "update_by")
    private String ab_c;

    @TableField(exist = false)
    private String abC;
`
`SELECT dict_id,name,description,create_by,update_by AS ab_c,create_time,update_time FROM sys_dict 
limit 1 
 {executed in 0 msec}
<==    Columns: dict_id, name, description, create_by, ab_c, create_time, update_time
<==        Row: 1, user_status, 用户状态, admin, admin, 2019-10-27 20:31:36, 2023-04-18 13:44:10
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1a827222]
[{"abC":"admin","ab_c":null,"description":"用户状态","updateTime":1681796650000,"dictId":1,"createBy":"admin","createTime":1572179496000,"name":"user_status"}]
[{"abC":"admin","ab_c":null,"createBy":"admin","createTime":1572179496000,"description":"用户状态","dictId":1,"name":"user_status","updateTime":1681796650000}]
`

### 重现步骤(如果有就写完整)
TableField注解不起作用
1.使用默认配置
2.当表的字段名中带下划线时,java类的属性名与表的字段名一模一样.都是ab_C时查询完成后不会对java类的属性名赋值

**Comment by miemieYaho** [comment]
https://www.baidu.com/s?ie=UTF-8&wd=mybatis%20mapunderscoretocamelcase

**Comment by zhaoshengkai-0107** [comment]
刚才想明白了,就算和表字段一样都是下划线的,但是当这个注解为true时,自动会将下划线转成驼峰命名...
