### ISSUE TITLE
人大金仓数据库tinyint字段类型转换为Boolean类型失败

### ISSUE THREAD

**Issue by jerryStat** [baomidou/mybatis-plus#5252]
### 当前使用版本(必填,否则不予处理)
v3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
通过dao层调用selectList方法时，偶发存在tinyint转换为boolean类型报错

### 报错信息
tinyint不能转换为boolean类型报错

**Comment by jerryStat** [comment]
其他方法未出现该报错

**Comment by qmdx** [comment]
无法定位暂时关闭，入发现原因欢迎反馈修复
