### ISSUE TITLE
logicDeletePropertyName配置实体类字段跟生成后的实体类字段不一致

### ISSUE THREAD

**Issue by lnfire2013** [baomidou/mybatis-plus#5255]
> 版本：3.5.3.1

> 重现步骤：

 `FastAutoGenerator.create(url,username,password).strategyConfig(builder -> { 
              builder.entityBuilder()
                         .logicDeletePropertyName("delete")
                         .logicDeleteColumnName("is_del")
})
 .templateEngine(new VelocityTemplateEngine())
.execute();
`
> 生成后的代码：

    @ApiModelProperty("是否删除")
    @TableField("is_del")
    @TableLogic
    private Boolean isDel;

> 问题：

    生成的实体类字段跟配置的不一致

**Comment by the-tsing** [comment]
+1，
还有
.dataSourceConfig(builder -> builder.typeConvertHandler((globalConfig, typeRegistry, metaInfo) -> {
                    int typeCode = metaInfo.getJdbcType().TYPE_CODE;
                     if (typeCode == Types.TINYINT || typeCode == Types.SMALLINT) {
                        // 自定义类型转换
                        return DbColumnType.INTEGER;
                    }
                    return typeRegistry.getColumnType(metaInfo);
                }))
不生效，我数据库设置的tinyint，这里typeCode读出来是BIT
