### ISSUE TITLE
3.3.x release addMappedStatement load very slowly

### ISSUE THREAD

**Issue by ningmengwork** [baomidou/mybatis-plus#5256]
### 当前使用版本(必填,否则不予处理)

3.3.2 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 `addMappedStatement `  load very slowly

### 报错信息
![image](https://user-images.githubusercontent.com/37521861/233000009-83b08f37-7993-4e23-b158-ae329de4f352.png)

**Comment by miemieYaho** [comment]
你打开了debug当然慢了

**Comment by ningmengwork** [comment]
debug 和运行有什么关系吗？虽然是debug模式启动，但是启动巨慢，几分钟都起不来，debug不应影响启动速度的啊

**Comment by ningmengwork** [comment]
速度巨慢，项目都没办法debug调试启动了

**Comment by nieqiurong** [comment]
一般来说,如果你项目来说平时没这么慢,可能是idea打断点标记过多会导致偶发性项目运行缓慢,这种情况将idea打断点标记情况一下再打上自己需要的断点就行,尝试把项目打成jar包直接运行看耗时和idea运行耗时对比看看.

**Comment by nieqiurong** [comment]
后面版本这个debug日志已经去掉了,会影响点点部分启动速,但不至于说将30秒启动的项目拖垮到几分钟.

**Comment by huayanYu** [comment]
closed
