### ISSUE TITLE
根据MapperId 获取MappedStatement 对应的绑定参数

### ISSUE THREAD

**Issue by hzn6426** [baomidou/mybatis-plus#5257]
### 当前使用版本(必填,否则不予处理)

3.3.x

已经根据mapper获取到statement了
MappedStatement stmt =  config.getMappedStatement(mapper);
下一步要获取真实的SQL
stmt.getBoundSql(parameter).getSql();
此时需要parameter,因为是通用的处理方式,所以此时无法获取parameter参数, mybatis-plus能不能获取参数绑定,或者有没有方式能够获取mapper的真实SQL, 谢谢!

**Comment by miemieYaho** [comment]
stmt.getBoundSql(parameter) -> ognl -> 得到sql

**Comment by hzn6426** [comment]
能具体点吗? ognl怎么获取,谢谢

**Comment by hzn6426** [comment]
能具体点吗? 最好有一段代码, 谢谢 或者在mybatis plus初始化时可以获取每个mapper 的SQL吗?

**Comment by miemieYaho** [comment]
mybatis的xml的if标签知道吧,需要入参走完if判断才能得到能执行的sql

**Comment by hzn6426** [comment]
现在需要在项目启动的时候获取每个mapper的 对应的SQL,不需要执行相应的请求

**Comment by miemieYaho** [comment]
执不执行是你的事,你要想获取不带if标签的可以执行的sql就必须要入参
