### ISSUE TITLE
updateById 方法生成的sql语句，有空行问题，导致 JSQLParser  检查失败

### ISSUE THREAD

**Issue by 4color** [baomidou/mybatis-plus#5260]
### 当前使用版本(必填,否则不予处理)

3.4.2开始，以上所有的版本都尝试过

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

开始用3.4.2版本，然后sql 会有检查 的bug
具体问题跟这个人一样： 
https://github.com/JSQLParser/JSqlParser/issues/1741

我就把升级到 JSQLParser 4.6

现在只有有某个值为空时，那行的sql set 就是空行，有多个空行时，就会引发 JSQLParser   的检查失败。

### 报错信息

Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "\n\n\n" <ST_SEMICOLON>

**Comment by 4color** [comment]
CREATE_USER_GUID=?,
CREATE_USER_NAME=?,
CREATE_TIME=?,


ENABLED_STATUE=?,
VERSION_NUM=?,


JSQLParser 上也有人提这个问题
https://github.com/JSQLParser/JSqlParser/issues/1756

**Comment by chy996633** [comment]
如果DB允许字段非空，可以@TableField 设置 update\insertStrategy为IGNORE，这样MP会生成完整的SQL

**Comment by nieqiurong** [comment]
#5345  合并至此处讨论
