### ISSUE TITLE
Gbase8s 3.3.0，xml中如果select 后字段使用预编译占位符报错

### ISSUE THREAD

**Issue by PaceChow** [baomidou/mybatis-plus#5268]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在xml里面编写的sql，select后面的字段时候占位符的时候（预编译：#{}），语法执行会报错

**Comment by miemieYaho** [comment]
和mp有什么关系吗?
