### ISSUE TITLE
mybatis-plus-generator新版本DefaultQuery面对postgres的JSON字段时只能识别为Object

### ISSUE THREAD

**Issue by MomentDerek** [baomidou/mybatis-plus#5269]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
新版本从SQLquery换成了DefaultQuery

### 重现步骤(如果有就写完整)
使用新版本，不指定SQLquery进行代码生成，遇到json字段时，只能识别为object

现在是设置为SQLQuery，配置PostgreSqlTypeConvert进行生成，是否有配置使得使用DefaultQuery也可以做到？

**Comment by miemieYaho** [comment]
json类型没有对应的java类

**Comment by lanjerry** [comment]
这个不太好弄的,在pg驱动下,读取uuid,json,jsob这些数据类型元数据都是other,在mybatis官方的生成器下也是当obj处理.

**Comment by MomentDerek** [comment]
拿这个作为临时方案先用着吧
