### ISSUE TITLE
开启enableSpringdoc文档后@Schema(description = "$!{table.comment}")未生效

### ISSUE THREAD

**Issue by youtao531** [baomidou/mybatis-plus#5270]
### 当前使用版本(必填,否则不予处理)
<mybatis-plus.version>3.5.3.1</mybatis-plus.version>
<mybatis-plus-generator.version>3.5.3.1</mybatis-plus-generator.version>

**Comment by pwallk** [comment]
建议使用自定义模板，去掉$后面的!
![image](https://user-images.githubusercontent.com/69385076/234227362-8f50a823-fc21-467a-8306-1641408efcaa.png)
