### ISSUE TITLE
DataPermissionInterceptor 插件在官方文档中没有使用说明

### ISSUE THREAD

**Issue by liuyiyo** [baomidou/mybatis-plus#5273]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我看新版本源码多了一个数据权限处理的插件，但是官方文档中没有找到对应的使用说明。
![image](https://user-images.githubusercontent.com/52642305/233817498-54b01240-1735-4103-8426-db10ebaf1a15.png)
希望能够补上

**Comment by binfengyan** [comment]
数据权限插件是商业版本支持的！

**Comment by qmdx** [comment]
https://baomidou.com/pages/1a87dp/#datapermissioninterceptor
