### ISSUE TITLE
动态表名插件配置的是第一数据源，但是会对第二数据源生效

### ISSUE THREAD

**Issue by DCTANT** [baomidou/mybatis-plus#5274]
### 当前使用版本(必填,否则不予处理)
V3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我这边需要进行数据迁移，第一数据源是需要被迁移的数据库是一个空库，第二数据源是曾经的库，需要将第二数据源中的数据迁移到第一数据源中。

由于第一数据源采用了分表的方式缓解数据库查询压力，因此第一数据源的表名是动态的，分为1~9，而第二数据源的表名是固定的。我在第一数据源的配置中加上了动态表名插件DynamicTableNameInnerInterceptor，但是我在查询第二数据源的时候动态表名插件却生效了，导致因为表名不存在而报错了。

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/29122507/233824956-bde46a94-2ed7-444f-b928-df60d1293f7d.png)
![3304840bdc71c5099320d97996a1aa0](https://user-images.githubusercontent.com/29122507/233824963-f982c9de-73cc-45f3-937d-81205ff1aced.png)
![d50217d746fc0ac22387c9a15ff56eb](https://user-images.githubusercontent.com/29122507/233824970-c59f63c3-fe12-4544-8d72-c8a6a0bc7cec.png)

### 报错信息
就是第二数据源找不到表，然后报错了

**Comment by justToBeGood** [comment]
https://blog.csdn.net/a_tzluy/article/details/128042120
![image](https://user-images.githubusercontent.com/50023670/237018117-671b01f1-ab48-4dea-be2e-95f1ace4848c.png)
网上看到的解析，你试下？

**Comment by qmdx** [comment]
动态表名不会修改数据源的只是改名字，请自行检查你的数据源是否切换正确
