### ISSUE TITLE
jdk17 反射警告

### ISSUE THREAD

**Issue by a1043710306** [baomidou/mybatis-plus#5278]
### 当前使用版本(必填,否则不予处理)
com.baomidou:mybatis-plus-boot-starter:3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用最新快照版本也有此项警告信息

### 重现步骤(如果有就写完整)
启动初始化时报错

### 报错信息
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.baomidou.mybatisplus.core.toolkit.SetAccessibleAction (file:/home/sweet/bot/plugins/loliege-0.1.0.mirai.jar) to field java.lang.invoke.SerializedLambda.capturingClass
WARNING: Please consider reporting this to the maintainers of com.baomidou.mybatisplus.core.toolkit.SetAccessibleAction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by 1845062639** [comment]
我也遇到了一样的问题，错误在lambdaquerywrapper对象中用了orderbyasc（）方法

**Comment by nieqiurong** [comment]
#5172

**Comment by 1845062639** [comment]
我的问题已解决，把pom文件中的mp依赖版本调低到3.4.2就不会再报错
