### ISSUE TITLE
saveBatch方法在for循环里执行时报主键冲突

### ISSUE THREAD

**Issue by hlli86** [baomidou/mybatis-plus#5280]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.1、3.5.2、3.5.3.1 都出现该问题
3.4.0 版本正常

### 重现步骤(如果有就写完整)
伪代码如下：
@Transactional(rollbackFor = Exception.class)
public Integer saveInfo(String resourceIndexCode, List<T> relationList) {
 boolean result = saveBatch(relationList);
}
循环执行saveInfo方法后报主键冲突错误

### 报错信息

![image](https://user-images.githubusercontent.com/50994859/234149392-a10c9adc-8695-44af-90a0-9b139842b14b.png)

**Comment by qmdx** [comment]
你应该是同一个对象循环，请使用不同对象处理，新版本允许自增情况设置ID 所有会有你这种同一个对象循环使用重复问题
