### ISSUE TITLE
全局变量DateType.ONLY_DATE设置不生效

### ISSUE THREAD

**Issue by TophillZK** [baomidou/mybatis-plus#5281]
### 当前使用版本(必填,否则不予处理)
Springboot 版本：2.7.6
Mybatis 版本：2.3.0
MyBatisPlus 版本：3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在生成Entity时，设置日期类型为DateType.ONLY_DATE，但是结果仍然生成了java.sql.Timestamp

### 重现步骤(如果有就写完整)
生成语句部分：
    FastAutoGenerator
    .create(URL,USER_NAME,PASSWD)
    .globalConfig(builder ->{
      builder.outputDir(SYS_PATH)
          .author(AUTHOR)
          .disableOpenDir()
          .dateType(DateType.ONLY_DATE)
          .commentDate("yyyy-MM-dd");
    })

生成结果部分：
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.io.Serializable;
import java.sql.Timestamp;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
@TableName("ns_base_info")
public class NsBaseInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId("ns_code")
    private String nsCode;

    @TableField("ns_name")
    private String nsName;

    @TableField("create_time")
    private Timestamp createTime;
}

### 报错信息
我期望是：
import java.util.Date;
  private Date createTime;
但是目前生成的是：
import java.sql.Timestamp;
  private Timestamp createTime;

这个结果和使用DateType.SQL_PACK一样。

**Comment by ninecloud** [comment]
这个问题我也遇到了，MyBatisPlus 版本：3.5.1 这个参数是生效的，我降版本解决的。

**Comment by qmdx** [comment]
请使用 `3.5.3.1` + 版本，测试用例  https://github.com/baomidou/mybatis-plus/commit/d1fc2252e71119b20d4fd2f6a56dbfc20db321a7
