### ISSUE TITLE
mybatisplus实现动态数据源的一些问题

### ISSUE THREAD

**Issue by BukJiang** [baomidou/mybatis-plus#5283]
### 当前使用版本(必填,否则不予处理)
v3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

前提：使用DynamicDataSource做动态数据源，数据源中同时包含了mysql和oracle（数据源除了url跟dbtype不一样，其他都是一样的，包括库跟表，所以entity只有一份）

问题一：在使用过程中发现，引入分页插件PaginationInnerInterceptor，需要指定dbType，可是我的dbType是动态的
问题二：在对数据进行insert的时候，mysql仅能使用@tableId(value = "id", type = IdType.AUTO)，但是动态切换到oracle的时候insert就会有问题。需要对entity使用@keySequence注解，并且type需改成 Idtype
.input

结论：想问一下，如果是这种场景，有什么方式可以实现吗

**Comment by miemieYaho** [comment]
1. 并不需要指定dbtype
2. 用雪花id不用数据库自增
