### ISSUE TITLE
多租户插件TenantLineHandler中ignoreTable方法传入的参数tableName带了反引号

### ISSUE THREAD

**Issue by bert561** [baomidou/mybatis-plus#5285]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
由于SQL语句表名带了反引号，导致
多租户插件TenantLineHandler中ignoreTable方法传入的参数tableName带了反引号，从而导致判断不准确

### 重现步骤(如果有就写完整)
sql语句：select * from `A`
TenantLineHandler的ignoreTable的实现：
    
@Override
public boolean ignoreTable(String tableName) {
        log.info("传入的表名：{}",tableName);
        return "A".equals(tableName);
}

预期结果：ignoreTable方法返回true
实际结果：ignoreTable方法返回false

**Comment by qmdx** [comment]
转义符是吧？ 那需要你自己处理先移除转义符再判断
