### ISSUE TITLE
DM与MySQL在保留关键字上的兼容性问题

### ISSUE THREAD

**Issue by leimeng-ma** [baomidou/mybatis-plus#5286]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
不算是问题吧，就是想咨询一下，如果要同时适配DM数据库和MySQL数据库，但是表中字段存在interval这样的保留关键字，mysql支持`interval`  DM支持“INTERVAL”这种方式，是否有配置可以进行处理这种兼容性

### 重现步骤(如果有就写完整)

无

**Comment by TonyWang8904** [comment]
我也有这个问题，请问怎么解决的啊

**Comment by huayanYu** [comment]
没有

**Comment by lylyuanliang** [comment]
请问解决了吗, 我目前也有这个问题, 暂没有找到比较好的方案

**Comment by qmdx** [comment]
关键词可以全局配置转义符，或者 xml 通过数据源区分选择不同sql片段 https://baomidou.com/ 参考文档问答部分

**Comment by lylyuanliang** [comment]
因为要兼容多个数据库, 我找到个解决方案 https://baomidou.com/pages/56bac0/#columnformat, 全局格式化字段, 但是如果能找到一个类似tkmybatis的mapper.wrap-keyword配置的方式就更好了

**Comment by melin** [comment]
IDialect 缺少一个方法处理，对字段加转义的功能。
类似hibernate：https://github.com/hibernate/hibernate-orm/blob/6a1581cf4a085e6842768eb181ef674a198ae178/hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java#L1033C14-L1033C24

@nieqiurong
