### ISSUE TITLE
基础sql delete异常

### ISSUE THREAD

**Issue by nzb15555196162** [baomidou/mybatis-plus#5291]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
DELETE FROM table_name  WHERE (column_name IN (?))

### 重现步骤(如果有就写完整)
mybatis plus 删除

### 报错信息
![image](https://user-images.githubusercontent.com/18350673/234585857-c1bf89a8-233b-402e-b9ae-2bdd68f79fd4.png)

**Comment by miemieYaho** [comment]
给出git形式的复现demo

**Comment by nzb15555196162** [comment]
> 给出git形式的复现demo
ok

**Comment by nzb15555196162** [comment]
目前问题已经解决，升级中间件导致的，切换版本问题解决，我关闭这个issue
