### ISSUE TITLE
关于全局使用格式化转义符columnformat的使用

### ISSUE THREAD

**Issue by evelynn996** [baomidou/mybatis-plus#5293]
使用转义符注解例如 `@TableName("'table'")`  或者全局使用格式化转义符columnformat配置文档 https://baomidou.com/pages/56bac0/#columnformat

_Originally posted by @qmdx in https://github.com/baomidou/mybatis-plus/issues/5277#issuecomment-1521020465_
            
版本是3.5.3.1，配置如下：
```java
mybatis-plus:
  type-aliases-package: com.zsy.adminvue.domain
  global-config:
    db-config:
      column-format: "'%s'"
```
在测试中，where条件里id主键也生效了，如下，是我哪里做的不对吗？
```java
 @Test
    void contextLoads() {
        ArrayList<Long> roleIdList = new ArrayList<>();
        roleIdList.addAll(Arrays.asList(1L,2L));
        List<SysRole> sysRoles = sysRoleMapper.selectBatchIds(roleIdList);
        System.out.println(sysRoles);
```

```
selectBatchIds     : ==>  
Preparing: SELECT 'id','name','code','desc','create_time','update_time','status' FROM sys_role WHERE 'id' IN ( ? , ? `)`
```

**Comment by qmdx** [comment]
这不是已经加上转义符了么

**Comment by evelynn996** [comment]
> 这不是已经加上转义符了么

昨天糊涂了，弄成了单引号而不是反引号 ，我的锅。。

**Comment by 18191518054** [comment]
### SQL: SELECT  id,"user_id","name","note","type","connection_params","create_time","update_time"  FROM "t_ds_datasource"     WHERE ("type"= ?)
### Cause: dm.jdbc.driver.DMException: 第3 行附近出现错误:
无效的列名[ID]
为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2

**Comment by 18191518054** [comment]
我期望给主键也添加双引号

**Comment by 18191518054** [comment]
mybatis-plus版本:3.5.1还是不行

**Comment by evelynn996** [comment]
> ### SQL: SELECT id,"user_id","name","note","type","connection_params","create_time","update_time" FROM "t_ds_datasource" WHERE ("type"= ?)
> ### Cause: dm.jdbc.driver.DMException: 第3 行附近出现错误:
> 无效的列名[ID] 为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2

@18191518054 你配置了column-format吗？贴出来

**Comment by 18191518054** [comment]
> > ### SQL: SELECT id,"user_id","name","note","type","connection_params","create_time","update_time" FROM "t_ds_datasource" WHERE ("type"= ?)
> > ### Cause: dm.jdbc.driver.DMException: 第3 行附近出现错误:
> > 无效的列名[ID] 为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2
> 
> [@18191518054](https://github.com/18191518054) 你配置了column-format吗？贴出来

  global-config:
    db-config:
      id-type: auto
      column-format: '"%s"'

**Comment by evelynn996** [comment]
> global-config: db-config: id-type: auto column-format: '"%s"'

@18191518054  
改成这样试试
```
column-format:  "`%s`"
```

**Comment by Fire-Cream** [comment]
试了一下，只能这么写
column-format:  '"%s"'
如果是 column-format:  "`%s`"，生成的sql的字段会加上 ``

**Comment by Jinsist** [comment]
> ### SQL: SELECT id,"user_id","name","note","type","connection_params","create_time","update_time" FROM "t_ds_datasource" WHERE ("type"= ?)
> ### Cause: dm.jdbc.driver.DMException: 第3 行附近出现错误:
> 无效的列名[ID] 为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2

这个解决了吗，我也想给主键加上quote字符

**Comment by Fire-Cream** [comment]
> > ### SQL：SELECT id,"user_id","name","note","type","connection_params","create_time","update_time" FROM "t_ds_datasource" WHERE ("type"= ?)
> > ### 原因： dm.jdbc.driver.DMException: 第 3 行附近出现错误：
> > 无效的列名[ID]为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2
> 
> 这个解决了吗，我也想给主键加上quote Char

解决了， column-format: '"%s"'  这样写

**Comment by Jinsist** [comment]
> > > ### SQL：SELECT id,"user_id","name","note","type","connection_params","create_time","update_time" FROM "t_ds_datasource" WHERE ("type"= ?)
> > > ### 原因： dm.jdbc.driver.DMException: 第 3 行附近出现错误：
> > > 无效的列名[ID]为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2
> > 
> > 
> > 这个解决了吗，我也想给主键加上quote Char
> 
> 解决了， column-format: '"%s"' 这样写

没有啊，这个没法给主键字段加上：
### The error occurred while executing a query
### SQL: SELECT    id,"table_name","table_config_info","table_comment","table_type","create_time","update_time"    FROM  "etl_table_definition"
### Cause: dm.jdbc.driver.DMException: 第1 行附近出现错误:

**Comment by Fire-Cream** [comment]
> > > > ### SQL：SELECT id,"user_id","name","note","type","connection_params","create_time","update_time" FROM "t_ds_datasource" WHERE ("type"= ?)
> > > > ### 原因： dm.jdbc.driver.DMException: 第 3 行附近出现错误：
> > > > 无效的列名[ID]为什么我的给主键不能加引号，数据库达梦8，mybatis-plus版本:3.5.2
> > > 
> > > 
> > > 这个解决了吗，我也想给主键加上quote Char
> > 
> > 
> > 解决了， column-format: '"%s"' 这样写
> 
> 没有啊，这个没法给主键字段加上：
> 
> ### The error occurred while executing a query
> ### SQL: SELECT id,"table_name","table_config_info","table_comment","table_type","create_time","update_time" FROM "etl_table_definition"
> ### Cause: dm.jdbc.driver.DMException: 第1 行附近出现错误:

主键不加会报错吗，我这边没出现过这个问题
