### ISSUE TITLE
使用ImadcnIdentifierGenerator雪花算法生成id

### ISSUE THREAD

**Issue by lj919374296** [baomidou/mybatis-plus#5294]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
    <version>3.4.0</version>
</dependency>
<dependency>
    <groupId>com.imadcn.framework</groupId>
    <artifactId>idworker</artifactId>
    <version>1.5.0</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/63218295/234805626-b651e155-fd4a-4fbd-baaa-2c408580db39.png)

### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/63218295/234805746-f47ef4ca-a896-4fb2-a07b-de560efdddf9.png)

分布式项目中，启动不同的服务。通过zookeeper注册后得到的workerid 都是0，这样nextId（）是不是会重复
### 报错信息
![image](https://user-images.githubusercontent.com/63218295/234806701-dc0f0e73-ef8d-421b-9f68-264db5195a8b.png)
不同服务，workerid相同，请指点，感谢

**Comment by miemieYaho** [comment]
这你要问他了 https://github.com/imadcn/idworker

**Comment by lj919374296** [comment]
好的
