### ISSUE TITLE
mybatis-plus.global-config.db-config.logic-delete-field=deleted 不生效

### ISSUE THREAD

**Issue by wzgl998877** [baomidou/mybatis-plus#5296]
### 当前使用版本(必填,否则不予处理)
3.4.3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
设置
mybatis-plus.global-config.db-config.logic-delete-field=deleted
无效

### 重现步骤(如果有就写完整)
一、表结构
 /**
     * 修改人名称
     */
    @TableField("update_user_name")
    private String updateUserName;

    /**
     * 是否删除(0.未删除，1.已删除)
     */
    @TableField("deleted")
    private String deleted;

二、单元测试
@Autowired
    private IClueService clueService;

    @Test
    void test() {
        clueService.getById("2023042600000003");
    }
三、打印的sql为
SELECT clue_id,company_name,company_main_business,source,area,country,website,name,title,email,phone,clue_type,attach_path,other_social_media,people_introduction,clue_details,remark,salesman,goods_model,owner_name,owner_id,department_id,company_id,team_members,status,create_time,update_time,create_user,update_user,update_user_name,deleted FROM t_clue WHERE clue_id=?
并没有带上deleted
四、字段上加上，@TableLogic
  /**
     * 是否删除(0.未删除，1.已删除)
     */
    @TableField("deleted")
    @TableLogic
    private String deleted;
五、同样的单元测试，打印的sql为
SELECT clue_id,company_name,company_main_business,source,area,country,website,name,title,email,phone,clue_type,attach_path,other_social_media,people_introduction,clue_details,remark,salesman,goods_model,owner_name,owner_id,department_id,company_id,team_members,status,create_time,update_time,create_user,update_user,update_user_name,deleted FROM t_clue WHERE clue_id=? AND deleted='0'

### 报错信息
mybatis-plus.global-config.db-config.logic-delete-field=deleted 这个没生效，大佬们帮忙看下

**Comment by 986510453** [comment]
https://baomidou.com/pages/6b03c5/

**Comment by Bingzhenjuz1** [comment]
> https://baomidou.com/pages/6b03c5/

这个链接失效了，讲的是什么？
