### ISSUE TITLE
CachePaginationInterceptor 去掉后启用redis二级缓存分页异常

### ISSUE THREAD

**Issue by x55admin** [baomidou/mybatis-plus#530]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.4

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
之前用2.X版本配置
```
 @Bean
    public PaginationInterceptor paginationInterceptor() {
        return new CachePaginationInterceptor();
    }
```
一切正常升级后CachePaginationInterceptor不见了默认分页插件PaginationInterceptor无法对分页进行缓存

**Comment by miemieYaho** [comment]
CachePaginationInterceptor 已经移除了,不建议使用二级缓存缓存任何数据

**Comment by jckinda** [comment]
> CachePaginationInterceptor 已经移除了,不建议使用二级缓存缓存任何数据

那二级缓存是有什么功能代替吗？？？

**Comment by qmdx** [comment]
@jckinda service 层spring 注解缓存
