### ISSUE TITLE
Inner Join 分页优化支持

### ISSUE THREAD

**Issue by ChinaJeckXu** [baomidou/mybatis-plus#5302]
# 当前使用版本3.5.2
外层 limit 对大数据量分页数据查询不友好，建议增加 INNER JOIN 分页优化插件

**Comment by Jay-9527** [comment]
同意，另外在进行多表查询时，抛弃了旧的Join。就少了很多便捷。

**Comment by ChinaJeckXu** [comment]
> 同意，另外在进行多表查询时，抛弃了旧的Join。就少了很多便捷。

另外还有利用ID自增特性多次Count查询叠加计数，起码一千万内Count 效率不会太拉

**Comment by miemieYaho** [comment]
不会集成
