### ISSUE TITLE
枚举功能异常

### ISSUE THREAD

**Issue by wenwancheng0626** [baomidou/mybatis-plus#5304]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

mybatis-plus.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumOrdinalTypeHandler
在使用该配置执行修改操作时，枚举中设置的code值未生效，更改常量定义的顺序，保存到数据库的值也会发生变化，
如下定义，当性别为男时，存入数据库的值为0   
    MALE(1,"男"),
    FEMALE(2,"女")，
    ISNULL(0, "")；

### 重现步骤(如果有就写完整)
原代码如下：

**枚举类**
@Getter
public enum SexEnum{

    ISNULL(0, ""),
    MALE(1,"男"),
    
    FEMALE(2,"女");
    SexEnum(Integer code, String msg) {
        this.code = code;
        this.msg = msg;
    }
    @EnumValue
    private Integer code;
    private String msg;

}

**properties配置**
mybatis-plus.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumOrdinalTypeHandler

**相关依赖**
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.3.1.tmp</version>
        </dependency>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>1.7</version>
        </dependency>

**Comment by miemieYaho** [comment]
使用了mp的枚举注解之后,default-enum-type-handler就不会作用于这个枚举了
