### ISSUE TITLE
实体类中时间类型怎么设为java.util.date

### ISSUE THREAD

**Issue by 0556heqing** [baomidou/mybatis-plus#5305]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类代码不能设为 java.util.date？

### 重现步骤(如果有就写完整)
1. 全局配置设置为 ：.dateType(DateType.ONLY_DATE)
2. 数据库字段类型设置为：datetime
3. 生成代码
4. 实体类中的类型为： import java.sql.Timestamp;

**Comment by 0556heqing** [comment]
补充：如果数据库字段为：date，生成的代码没有问题

**Comment by Jw1058783348** [comment]
> 补充：如果数据库字段为：date，生成的代码没有问题

3.5.2可以。3.5.3不知道为啥会把数据库里的datetime识别成timestamp
![image](https://github.com/baomidou/mybatis-plus/assets/45027541/eaf2cefb-06b8-45e8-989a-e4497beb1f08)

**Comment by Bin1993** [comment]
3.5.3.1没这个问题

**Comment by qmdx** [comment]
请使用 `3.5.3.1` + 版本，测试用例  https://github.com/baomidou/mybatis-plus/commit/d1fc2252e71119b20d4fd2f6a56dbfc20db321a7
