### ISSUE TITLE
mybatis plus中如何获取数据库中实际的影响行数

### ISSUE THREAD

**Issue by mywnlb** [baomidou/mybatis-plus#5306]
### 当前使用版本(必填,否则不予处理)

3.5.3  3.1.2

### 重现步骤(如果有就写完整)
1 数据库连接添加参数 useAffectedRows=true
2 继承  mybatis的 Interceptor 监听 StatementHandler，Eexcute,利用 invocation.proceed()获取返回值
3 在update updateById方法下并不是数据库实际的影响行数，而是查询到的行数
4 在以上基础上 在Interceptor 继承方法中调用sqlserssion手动执行，又会造成sql重复执行

### 报错信息
无法获取到数据库实际的影响行数

**Comment by miemieYaho** [comment]
去问mybatis
