### ISSUE TITLE
mybatis-plus-generator代码生成器配置全局覆盖的问题.

### ISSUE THREAD

**Issue by yfxuwork** [baomidou/mybatis-plus#5307]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
生成代码的时候. 按官方示例
代码生成器（新）
builder.fileOverride()   // 覆盖已生成文件
配置无法生效, 
无法覆盖之前生成过的代码文件.

### 重现步骤(如果有就写完整)
全局配置
builder.fileOverride()   // 覆盖已生成文件
在代码生成器3.5.3.1 版本中, 通过ide跟进代码里, 可以看到该配置已标记为弃用, 后续在策略配置中进行.
但是直到最新的3.5.3.1版本, 策略配置里面没有看到覆盖相关的配置属性.  

### 报错信息
只能一直通过使用旧版的3.5.1来生成代码.  希望官方能在新版的代码生成器更新中修复...

**Comment by suavess** [comment]
策略配置中有相关配置，在controllerBuilder下，但是不生效....
我这边全局配置和策略配置都尝试了，结果都不生效
<img width="1425" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/35449657/f359e104-0c60-4a74-ac90-28eebe2c7751">

**Comment by 61go** [comment]
怎么没人解答啊

**Comment by Bin1993** [comment]
Entity.Builder、Controller.Builder、Mapper.Builder、Service.Builder中都有enableFileOverride，策略中配置override的时候，这几个都要配置，不然就是配哪个就生效哪个

**Comment by qmdx** [comment]
```
    @Test
    public void testFileOverride() {
        AutoGenerator generator = new AutoGenerator(DATA_SOURCE_CONFIG);
        generator.strategy(strategyConfig()
            // 实体文件覆盖
            .entityBuilder().enableFileOverride()
            // Mapper文件覆盖
            .mapperBuilder().enableFileOverride()
            // Service文件覆盖
            .serviceBuilder().enableFileOverride()
            // Controller文件覆盖
            .controllerBuilder().enableFileOverride()
            .build());
        generator.execute();
    }
```
