### ISSUE TITLE
最近是否有发版计划

### ISSUE THREAD

**Issue by xggz** [baomidou/mybatis-plus#5310]
### 当前使用版本(必填,否则不予处理)
rt，没有计划的话，能否先发一个版本解决高版本jdk的警告问题：
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$2 (file:/Users/xxx/.m2/repository/cglib/cglib/3.1/cglib-3.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by 203579397** [comment]
催更

**Comment by miemieYaho** [comment]
3.5.3.3-SNAPSHOT 可用
