### ISSUE TITLE
大概是一个自动填充的问题

### ISSUE THREAD

**Issue by Greenjiao** [baomidou/mybatis-plus#5313]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在使用updateById时发现，如果说我传递的实体对象除了Id外的所有字段都为null，那么会报sql语法错误
大概是自动填充把null的字段给全都忽略掉了导致这个语法错误吧
小小的建议，加一下判断如果除了id外的字段都为空那么就报个自己的异常（因为想做异常处理提示，这报的是sql语法的错，我更想直接提示出去是字段全为空的错）

### 重现步骤(如果有就写完整)

然后我又试了将其他字段不置空，只将id置空，使用updateById反倒不会报错了，修改也成功了，不过条件是 id = null 来执行的当然什么都没修改

小小的建议是可以添加一下这方面的逻辑判断

### 报错信息
除了id的其他字段全为空时
![2023-05-07_061416](https://user-images.githubusercontent.com/80018120/236648566-82276b2b-28b9-4934-bf18-5058df7c388d.png)
id置空时
![2023-05-07_062252](https://user-images.githubusercontent.com/80018120/236648740-e0c5f9f0-1461-40ff-aba9-c47cf4bdeb52.png)

**Comment by miemieYaho** [comment]
加不了判断,执行sql是mybatis的事
