### ISSUE TITLE
wrapper里,能不能condition判定为false就不执行val中的表达式,还有分页拦截器配置

### ISSUE THREAD

**Issue by Ouyang-Yu** [baomidou/mybatis-plus#5314]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
wrapper里,能不能condition判定为false就不执行val中的表达式
下面执行会报空指针
                    String s = null;
                    eq(s != null, Account::getAge, s.length());

还有每个项目都要加分页拦截器配置,为什么starter不自动加呢,数据库不同拦截器不一样?自动根据驱动和url自动判定?
这也符合boot的默认大于配置

**Comment by miemieYaho** [comment]
1. 必须执行那是java的规定
2. 分页插件不是单独存在的不会自动加

**Comment by haitaohua** [comment]
> 1. 必须执行那是java的规定
> 2. 分页插件不是单独存在的不会自动加

第三个参数是否可以更改为lambda表达式呢？ 这样一来condition为false时，不执行该表达式
不知道其他人使用condition的场景是什么，但我通常condition都是拿来判空，如果不为空的话，第三个val处再进一步获取值（可能），而condition == false目前并不能熔断val的取值，为了防止空指针，只能在这个地方再进行一次三目运算，实在是不够优雅。
