### ISSUE TITLE
我们的技术派开源项目也使用了 MyBatis-Plus，不知道能否入选Projects Using MyBatis-Plus

### ISSUE THREAD

**Issue by itwanger** [baomidou/mybatis-plus#5318]
项目地址：https://github.com/itwanger/paicoding

并且多次写文章进行推广，希望能够有幸入选，也算是一个小的成绩了，😝

<img width="875" alt="image" src="https://user-images.githubusercontent.com/6011374/236758994-df632d97-741c-4560-8b42-21fc7b40e631.png">

**Comment by qmdx** [comment]
可以的你直接提交 PR  到 https://github.com/baomidou/awesome-mybatis-plus 这儿即可
