### ISSUE TITLE
数据库SqlServer 2008,使用saveBatch，报错： com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。

### ISSUE THREAD

**Issue by scstc** [baomidou/mybatis-plus#5325]
数据库SqlServer 2008,使用saveBatch，报错： com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。

有什么解决方案，让saveBatch方法支持SQLServer吗

**Comment by ZeYuYang1024** [comment]
这个是数据量很大吗？我记得超过1000行就会报错了！如果可以的话，将你的数据分片处理，然后调用saveBatch试一试

**Comment by miemieYaho** [comment]
SqlServer是驱动不支持

**Comment by scstc** [comment]
> SqlServer是驱动不支持

怎样处理才能够支持

**Comment by ZeYuYang1024** [comment]
> > SqlServer是驱动不支持
> 
> 怎样处理才能够支持

要不for循环 单个save吧
