### ISSUE TITLE
关于分页插件的配置放在启动类才能生效的问题

### ISSUE THREAD

**Issue by pkaq** [baomidou/mybatis-plus#5333]
### 当前使用版本(必填,否则不予处理)
3.5.3.1
spring 3.0.6
jdk:17

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
```
    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor mybatisPlusInterceptor = new MybatisPlusInterceptor();

        mybatisPlusInterceptor.addInnerInterceptor(new PaginationInnerInterceptor());

        return mybatisPlusInterceptor;
    }
```

### 重现步骤(如果有就写完整)

分页插件放在 @Configuration 的配置类里 启动后断点查看MybatisPlusInterceptor对象发现Interceptors为 0 
而同样的配置放在启动类上则不会有问题

### 报错信息
无

**Comment by Jay-9527** [comment]
PaginationInnerInterceptor 这里指定版本再试试。

**Comment by huayanYu** [comment]
无回复,关闭
