### ISSUE TITLE
希望添加对lealone数据库的支持

### ISSUE THREAD

**Issue by zhoujin7** [baomidou/mybatis-plus#5334]
### 当前使用版本(必填,否则不予处理)
3.5.3.2-SNAPSHOT

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
希望添加对lealone数据库的支持. lealone是基于h2发展而来的数据库.
https://github.com/lealone/Lealone

### 报错信息
无

**Comment by qmdx** [comment]
已合并
