### ISSUE TITLE
“代码生成器增加是否生成service接口的开关”是否具有该功能

### ISSUE THREAD

**Issue by guluuwater** [baomidou/mybatis-plus#5338]
### 当前使用版本(必填,否则不予处理)
v3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
更新日志中提到了“代码生成器增加是否生成service接口的开关”，但是好像没有这个配置项，请问该在哪里配置？

**Comment by qmdx** [comment]
基本用法参考最新生成器 https://www.baomidou.com/pages/779a6e/#%E4%BD%BF%E7%94%A8

`globalConfig(builder -> builder.disableServiceInterface() ...`

又如禁用 xml 生成

```
// 模板配置
.templateConfig(builder -> builder.disable(TemplateType.XML))

public enum TemplateType {

    ENTITY, SERVICE, SERVICE_IMPL, CONTROLLER, MAPPER, XML

}
```
