### ISSUE TITLE
Clob filed data don't in the Result-Set

### ISSUE THREAD

**Issue by myheavyhead** [baomidou/mybatis-plus#5340]
### 当前使用版本(必填,否则不予处理)
version 3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
normal use.

### 重现步骤(如果有就写完整)
I design a filed type is CLOB in gaussDB, when i want search from the db to get the filed data, used like this "IService<I>.page(param1, param2)", i can't find the filed in the Result-Set, the file it's like not in the database! 
look at the mybatis-plus console sql logs, my CLOB file converted to BLOB, i don't konw why.

### 报错信息
None errror, but data isn't in the Result-Set.

**Comment by miemieYaho** [comment]
mybatis typehandler
