### ISSUE TITLE
my CLOB filed convert to <<BLOB>> auto

### ISSUE THREAD

**Issue by myheavyhead** [baomidou/mybatis-plus#5344]
### 当前使用版本(必填,否则不予处理)
mybatisplus：3.4.2
springboot：2.6.7

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
normal used.

### 重现步骤(如果有就写完整)
In gaussDB i hava a fied type is CLOB, the sql script like this 'filedA CLOB NULL', when i use mybatisplus's ServiceImpl.page() to search the data from DB, my CLOB filed convert to BLOB auto, how can i use my CLOB filed, the mybatisplus log like this:

==>  Preparing: SELECT * ....
==>  Parameters: ....
<==  Columns: ....
<==  Row: ..., ..., BLOB, ....
<==      Total: 1

**Comment by miemieYaho** [comment]
mybatis typehandler
