### ISSUE TITLE
LambdaWrapper.like() 通配符转义问题优化建议

### ISSUE THREAD

**Issue by WineAndPoetry** [baomidou/mybatis-plus#5349]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
模糊查询 使用构造器like方法时，通配符 [%,-] 等转义问题，在orcal 数据库中没有默认的转义符 需要使用 escape 指定
建议添加一个类似：
 like(boolean condition, R column, Object val, String escape)
的方法用以指定like语句中的转义符

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by qmdx** [comment]
请描述清楚你的问题，当前错误是什么，希望什么结果。

**Comment by qmdx** [comment]
无反馈，请反馈后打开

**Comment by WineAndPoetry** [comment]
是这样的，like语句中 如果要查找类似 %,^&*<>等符号的内容时，因为oracle没有默认的类似 / 的转义符，导致like没有按预期实现功能，需要使用 escape 关键字指定，所以只能使用原生的sql语句来实现，所以建议有一个类似like(boolean condition, R column, Object val, String escape)的方法，在lambda查询构造器中

**Comment by qmdx** [comment]
关键 escape 指定这种写法非通用 SQL 语句（暂不考虑加入公共方法内）， 你可以这样去写 `Wrappers.<Table>lambdaQuery().eq(Table::getId, 1).apply("name like {0} escape '\\'", "test\\%")`
