### ISSUE TITLE
请问如何设置不生成service、controller

### ISSUE THREAD

**Issue by light0x000** [baomidou/mybatis-plus#535]
虽然可以删掉,但是未免不优雅,想必mp应该有此功能

**Comment by miemieYaho** [comment]
`setController(null)` 类推

**Comment by light0x000** [comment]
😂感谢

**Comment by dennymou** [comment]
> `setController(null)` 类推

哪个东西setController?求告知

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html

例如         templateConfig.setXml(null);
