### ISSUE TITLE
为什么你们的分页中的 setRecords方法不设计成<? extends T>

### ISSUE THREAD

**Issue by JinheJamesLi** [baomidou/mybatis-plus#5354]
### 该问题是如何引起的？(确定最新版也有问题再提!!!) 
写入当前类的子类类型检查不一致
Page<Admin> page = super.page(pageObject, adminWrapper);
            List<AdminVO> adminVOS = new ArrayList<>();
            page.setRecords(adminVOS)
            AdminVO 是 Admin 的子类

### 报错信息
类型检查不一致

**Comment by luyanfeng** [comment]
确实是很不方便，希望对泛型的支持好好优化下

**Comment by JinheJamesLi** [comment]
> 确实是很不方便，希望对泛型的支持好好优化下

管理员没有搭理我

**Comment by qmdx** [comment]
如果是  <? extends T> 那么获取具体类型的时候存在转型问题如 `List<H2Student> records = (List<H2Student>)page.getRecords();`  或者 `List<? extends H2Student> records = page.getRecords()` 个人觉得这是没有必要的设置。
