### ISSUE TITLE
查询函数 Query  between 的操作

### ISSUE THREAD

**Issue by lixiaofan413** [baomidou/mybatis-plus#5356]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
常规的写法是 between key,value1,value2   也就是 where  create_time between 'v1' and 'v2'
今天突然执行一种写法发现也可行  也就是    between key1,key2 value  也就是  where 'value' between createTime and endTime
能否添加一个API？

**Comment by miemieYaho** [comment]
可
