### ISSUE TITLE
SpringBoot3 AOT  编译报错

### ISSUE THREAD

**Issue by zhaobo-98** [baomidou/mybatis-plus#5358]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

<img width="1759" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/49614720/62f0303a-d028-4fab-a7e2-d2429f649e22">

### 重现步骤(如果有就写完整)

 mvn clean package -Pnative

### 报错信息
[](https://github.com/mybatis/mybatis-3/issues/2858)

**Comment by zhaobo-98** [comment]
https://github.com/mybatis/mybatis-3/issues/2858

**Comment by BOFA1ex** [comment]
https://github.com/mybatis/parent/blob/mybatis-parent-37/pom.xml
mybatis-parent#37 has already set compile-args with `-parameters`.
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>${compiler.plugin}</version>
  <configuration>
    <parameters>true</parameters>
    <!-- Slightly faster builds, see https://issues.apache.org/jira/browse/MCOMPILER-209 -->
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>
</plugin>
```
u could declare mybatis#3.5.13 both with the latest `mybatis-plus` version.
```xml
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis</artifactId>
    <version>3.5.13</version>
</dependency>
```

**Comment by yy306525121** [comment]
这个报错可以参考这个链接解决https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start-for-building-native-image，

但是只要一引入mybatis-plus还是会报错，只能先不用Mybatis-plus了

**Comment by zieglar** [comment]
关注后续

**Comment by weichenhk** [comment]
> 报这个错可以参考这个链接解决[https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start-for-building-native-image，](https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start-for-building-native-image%EF%BC%8C)
> 
> 但是只要一引入mybatis-plus还是会报错，只能先不用Mybatis-plus了

我尝试后，通过mybatis提供的这个方案，在使用mybatis-spring-boot-starter时可以实现使用native image的编译和运行。
替换为mybatis-plus-boot-starter后可以编译，运行报错。感觉跟使用了反射有关。运行查询方法错误部分内容如下：
![image](https://github.com/baomidou/mybatis-plus/assets/42668192/ba3ed1d3-0c06-45a0-863f-1adf71028a68)


之后使用[跟踪代理收集元数据](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/)。其中提供的说明和代码示例。生成元数据之后再通过mvnw -Pnative native:compile编译为native image，可以正常运行。我只实现了一个查询方法，没有进行更多测试。
元数据中的文件reflect-config.json中应该是以下内容起到了作用：
![image](https://github.com/baomidou/mybatis-plus/assets/42668192/710cf238-d213-495f-be3d-1de4f0b6bf5c)

这个是我目前找到的可以在使用mybatis-plus时实现native image的方法。希望有帮助。

**Comment by yy306525121** [comment]
> 

嗯嗯， 万分感谢，我抽空试一试

**Comment by yy306525121** [comment]
> > 报这个错可以参考这个链接解决[https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start-for-building-native-image，](https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start-for-building-native-image%EF%BC%8C)
> > 但是只要一引入mybatis-plus还是会报错，只能先不用Mybatis-plus了
> 
> 我尝试后，通过mybatis提供的这个方案，在使用mybatis-spring-boot-starter时可以实现使用native image的编译和运行。 替换为mybatis-plus-boot-starter后可以编译，运行报错。感觉跟使用了反射有关。运行查询方法错误部分内容如下： ![image](https://user-images.githubusercontent.com/42668192/251094571-ba3ed1d3-0c06-45a0-863f-1adf71028a68.png)
> 
> 之后使用[跟踪代理收集元数据](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/)。其中提供的说明和代码示例。生成元数据之后再通过mvnw -Pnative native:compile编译为native image，可以正常运行。我只实现了一个查询方法，没有进行更多测试。 元数据中的文件reflect-config.json中应该是以下内容起到了作用： ![image](https://user-images.githubusercontent.com/42668192/251090068-710cf238-d213-495f-be3d-1de4f0b6bf5c.png)
> 
> 这个是我目前找到的可以在使用mybatis-plus时实现native image的方法。希望有帮助。

好的好的， 万分感谢， 我抽空试一下

**Comment by wssy001** [comment]
升级`mybatis-plus-boot-starter`中`mybatis`相关的版本，项目中引入<code>[MyBatisNativeConfiguration](https://github.com/mybatis/spring-boot-starter/wiki/MyBatisNativeConfiguration.java)</code>
，至此就能顺利编译项目。
如需使用`BaseMapper`或者`IService`提供的`CRUD`方法，还需要手动配置一下`mybatis plus`中一些接口的`jdk`代理与相关类的反射，这些操作用<code>[Tracing Agent](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/#tracing-agent)</code>暂时不能收集。
参考的`pom.xml`：
```xml
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.5.3.1</version>
    <exclusions>
        <exclusion>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-spring</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>3.0.2</version>
</dependency>
```

**Comment by shihaoH** [comment]
@wssy001 请问有哪些接口和类需要配置呢。。谢谢大佬

**Comment by wssy001** [comment]
> @wssy001 请问有哪些接口和类需要配置呢。。谢谢大佬

我稍晚会发到<code>[Discussion](https://github.com/baomidou/mybatis-plus/discussions)</code>
我个人能力有限，目前只搞定了一部分接口，确保能进行简单的CRUD操作

**Comment by wssy001** [comment]
> @wssy001 请问有哪些接口和类需要配置呢。。谢谢大佬

@shihaoH  可以参考这个<code>[discussion](https://github.com/baomidou/mybatis-plus/discussions/5453)</code>

**Comment by nieqiurong** [comment]
#5527  统一至此处讨论
