### ISSUE TITLE
50个并发间隔30s跑，一定时间后sql请求时间极度拉长

### ISSUE THREAD

**Issue by topherli** [baomidou/mybatis-plus#5359]
### 当前使用版本(必填,否则不予处理)
mybatis:3.5.2
dynamic-datasource:3.50
springboot:2.5.8
jdk:1.8.0_202-b08
从监控上看，由于并发数并不高，数据库的cpu(%0.7) 内存(%5.6) ，io基本上没有任何占用

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
运行1到2个小时就出现，每次50个并发，100个并发，150个并发去循环去请求，每次并发请求间隔是30s，且并发的访问的数据一般不会是同一条数据，sql都是超级简单的sql，单条select，找不到则insert

### 重现步骤(如果有就写完整)
不同的环境结果不一样，有的环境需要更长的时间才能再现，一开始访问都正常，每次重现，不会清库，sql访问都有走索引

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/106127912/d98e0b08-ae34-4352-811b-b0967bd83371)

**Comment by huayanYu** [comment]
初步判断和MP无关, 个人更倾向连接池配置问题. 如果有详细证明是MP问题请重提ISSUE
