### ISSUE TITLE
条件构造器用不了notLikeRight()和notLikeLeft()

### ISSUE THREAD

**Issue by GitBySzl** [baomidou/mybatis-plus#5360]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
用QueryWrapper.lambda()点不出来notLikeRight()和notLikeLeft()，只有notLike()

**Comment by miemieYaho** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/28334419/eb799ed6-44d5-443b-aadc-aa6f4a82c83b)
?

**Comment by miemieYaho** [comment]
更新你的版本
