### ISSUE TITLE
已配置 select-strategy: not_empty  但是id 还是查询了

### ISSUE THREAD

**Issue by csx-bill** [baomidou/mybatis-plus#5361]
### 当前使用版本(必填,否则不予处理)
mybatis-plus.version   3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查询参数：
![image](https://github.com/baomidou/mybatis-plus/assets/31872268/f6140b65-ab8b-4b89-bb93-a5e75b1e1744)

已配置 select-strategy: not_empty  但是id 还是查询了
![image](https://github.com/baomidou/mybatis-plus/assets/31872268/1590321e-541e-48a0-9cb6-b4192ada2c14)

![image](https://github.com/baomidou/mybatis-plus/assets/31872268/aaf8f852-49c6-4715-8de9-16e734319237)

**Comment by miemieYaho** [comment]
对id无效

**Comment by csx-bill** [comment]
为何对 id 是无效的？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: miemieYaho ***@***.***&gt;
发送时间: 2023年5月29日 00:10
收件人: baomidou/mybatis-plus ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [baomidou/mybatis-plus] 已配置 select-strategy: not_empty  但是id 还是查询了 (Issue #5361)





 
对id无效

**Comment by miemieYaho** [comment]
只对普通字段生效,id属于主键
