### ISSUE TITLE
大佬们能不能加个instr的条件构造器方法，因为like会索引失效

### ISSUE THREAD

**Issue by elianacc** [baomidou/mybatis-plus#5362]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

不是问题，就是说能不能优化下，加个条件构造器方法

**Comment by miemieYaho** [comment]
instr是标准sql还是某个数据库独有的?你可以用wrapper.apply方法

**Comment by elianacc** [comment]
> instr是标准sql还是某个数据库独有的?你可以用wrapper.apply方法

mysql postgresql Oracle都有的这个函数

**Comment by elianacc** [comment]
> instr是标准sql还是某个数据库独有的?你可以用wrapper.apply方法

wrapper.apply确实可以，感谢感谢，就是说下个小版本加一个 .instr 方法就更完美了

**Comment by elianacc** [comment]
> instr是标准sql还是某个数据库独有的?你可以用wrapper.apply方法

确实不是通用的，用apply就好了， postgresql是strpos

**Comment by miemieYaho** [comment]
不通用就加不了
