### ISSUE TITLE
乐观锁为什么不能抛异常呢

### ISSUE THREAD

**Issue by weiro-9-w7** [baomidou/mybatis-plus#5364]
当前使用版本(必须填写清楚，否则不予处理)
com.baomidou mybatis-plus-boot-starter 3.1.0
该问题是怎么引起的？([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接close掉)
乐观锁更新失败，没有任何提示信息，打印sql才发现是因为版本号不对。
==> Preparing: UPDATE user SET name=?, version=? WHERE id=? AND version=?
==> Parameters: kitty123(String), 3(Integer), 6(Long), 2(Integer)
<== Updates: 0

###建议
建议拦截器里面加个异常信息吧，这样更通用，不然每次更新还需要自己去校验是否更新成功。望采纳

**Comment by miemieYaho** [comment]
加不了
