### ISSUE TITLE
如果entity字段名不不希望跟 table的列名一样(即映射逻辑不是驼峰下划线) 

### ISSUE THREAD

**Issue by light0x000** [baomidou/mybatis-plus#537]
使用版本: 3.0.1

可否在entity字段上注解标明对应的table列名. 目前支持这样吗

**Comment by miemieYaho** [comment]
一直都支持

**Comment by light0x000** [comment]
> 一直都支持

谢谢 去 com.baomidou.mybatisplus.annotation 这个包找了 

顺便再问下~

拼接条件目前好像是与数据库列名一样对吧  可以有什么设置改成以entity字段名为准吗
比如 数据库 字段是 “user_id”,  实体字段是 “userId”
下面这样拼接条件的时候, 我想用userId而不是“user_id”
```
userMapper.selectOne(new QueryWrapper<User>().eq("user_id",1));  //这里使用的是 数据库 字段名
```
会不会有点贪婪😄

**Comment by miemieYaho** [comment]
不支持哈
