### ISSUE TITLE
ServiceImpl 实现类，初始化bean非常慢

### ISSUE THREAD

**Issue by melin** [baomidou/mybatis-plus#5370]
下面是打印出初始化超过100ms 的bean，基本都是ServiceImpl实现类。下面是mac m1机器上结果，如果是intel 就更慢了。
非常不利于在k8s中快速部署。

同时考虑一下，增加日志 打印出 MybatisSqlSessionFactoryBean#buildSqlSessionFactory 方法执行时间

@miemieYaho @qmdx 
![image](https://github.com/baomidou/mybatis-plus/assets/1145830/f3afab79-96ce-4a57-bed0-df21af683202)

下面是1核pod 里面，mybatis-plus 相关类初始化耗时非常慢；

![image](https://github.com/baomidou/mybatis-plus/assets/1145830/260ad694-84ad-4353-8688-9fe1f164b445)

**Comment by lngg057** [comment]
我感觉这是个不太好解决的问题，提出来很久了，没被解决。官方也认为这个没有必要解决~

**Comment by nieqiurong** [comment]
提供一下使用版本以及BaseMapper子类和 ServiceImpl 子类数量.

重点检查检查一下项目切面情况.

**Comment by sk142857** [comment]
有解决吗？

**Comment by nieqiurong** [comment]
有问题再打开

**Comment by netyjq** [comment]
问题依然存在

**Comment by cooker** [comment]
> 我感觉这是个不太好解决的问题，提出来很久了，没被解决。官方也认为这个没有必要解决~

确实很慢，几个表就10几秒了

**Comment by melin** [comment]
> > 我感觉这是个不太好解决的问题，提出来很久了，没被解决。官方也认为这个没有必要解决~
> 
> 确实很慢，几个表就10几秒了

hibernate 复杂度要比 mybatis 大很多， 启动加载时没有那么耗时的。

**Comment by cooker** [comment]
> > > 我感觉这是个不太好解决的问题，提出来很久了，没被解决。官方也认为这个没有必要解决~
> > 
> > 
> > 确实很慢，几个表就10几秒了
> 
> hibernate 复杂度要比 mybatis 大很多， 启动加载时没有那么耗时的。

有解决方案吗？滚动发布等了几分钟，太慢了

**Comment by Ai-010** [comment]
@cooker 后面怎么解决的 ？
