### ISSUE TITLE
未来是否会支持针对深分页的改造需求？

### ISSUE THREAD

**Issue by libin-tech** [baomidou/mybatis-plus#5373]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用分页插件PaginationInnerInterceptor，对于offset很大的情况下SQL执行是有性能问题的。
只能进行业务改造，如id连续的情况，会携带最后一个id当下一页的参数这种方式进行性能弥补。
未来会开发插件在很少改动代码的情况下完成上述需求吗？
比如在分页参数增加offset对应的字段名以及字段值，由插件进行处理。
这样可以跟使用PaginationInnerInterceptor一样的方式很少成本改动？

**Comment by miemieYaho** [comment]
不会
