### ISSUE TITLE
能否通过 Wrapper 修改当前操作 FieldStrategy

### ISSUE THREAD

**Issue by WangJincheng4869** [baomidou/mybatis-plus#5374]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

目前 FieldStrategy 只能在 实体类中配置，这样灵活性很低，因为会出现不同逻辑时对 null 值的处理不同。

我看目前支持 `.set` 的方式讲某个字段设置为null，这满足一定情况，当表字段较少或者只是要求这个字段为 null 时比较适用

但是，当表字段较多时这种方法会非常麻烦。

### 使用场景介绍

1. 当提交工单（工单表字段很多，几十个字段）时，我需要将全部字段进行修改，因为用户可能会将部分表单置空
2. 当进行工单分配、获取等操作时，只会修改部分字段。这时就要忽略 null 值执行，否则工单数据会丢失

### 诉求

如果 `Wrapper` 支持配置 `FieldStrategy` ，那么当我执行 update 方法时，就可以灵活的实现上述情况

**Comment by miemieYaho** [comment]
不能
