### ISSUE TITLE
版本升级-3.4.0升级到3.5.2，是否必须主动重写Entity中的pkVal()方法，有无向下兼容的方案？

### ISSUE THREAD

**Issue by IsZxm** [baomidou/mybatis-plus#5376]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
旧版本pkVal()为protected,新版本pkVal()为public。从3.4.0升级为3.5.2后打包报错，原因是两个版本pkVal()的方法修饰符不一致导致的。
如果要解决该问题，是否必须改写程序中所有涉及到的protected pkVal()为public pkVal()，有无更为简便的方式？

### 报错信息

https://github.com/baomidou/mybatis-plus/issues/4048

**Comment by qmdx** [comment]
你批量修改下相关实体这样不就一劳永逸了

**Comment by IsZxm** [comment]
> 你批量修改下相关实体这样不就一劳永逸了

你这么说的确又无法反驳
