### ISSUE TITLE
单表CRUD为BaseMapper提供时如何做到类似association的功能

### ISSUE THREAD

**Issue by liudaomanbu** [baomidou/mybatis-plus#538]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.4

单表CRUD是mp的BaseMapper提供的时,能做到类似association的效果吗?
一个A表中,有2.3个字段实际上是一个对象.
比如说A表中有三个字段为地区code,地区全称,地区简称.
然后因为实际上这三个字段是一个地区对象,有对应的地区类,里面封装了方法.
所以我希望A表对应的Bean中没有这三个字段的属性,而是直接有一个地区对象的属性.
这个地区对象才是有这三个属性.
这种在原生mybatis中可以使用xml中resultMap的association来实现.
使用mp的BaseMapper能实现吗?

**Comment by miemieYaho** [comment]
xml 里写 resultMap ,然后 entity 上注解指定该 resultMap

**Comment by liudaomanbu** [comment]
> xml 里写 resultMap ,然后 entity 上注解指定该 resultMap

@TableName注解中使用resultMap填写xml中resultMap的id是吗?我明白了,我去试试,谢谢

**Comment by qmdx** [comment]
如上，不行你及 xml 返回一个实体 VO

**Comment by tankxxl** [comment]
> > xml 里写 resultMap ,然后 entity 上注解指定该 resultMap
> 
> @TableName注解中使用resultMap填写xml中resultMap的id是吗?我明白了,我去试试,谢谢

你好，试出来什么结论没？
实体类中都是简单属性，体现不出来实体间的关系，如：Student类有一个属性为School类型，如果做CRUD，是否这些基本操作都需要自己写sql？？
