### ISSUE TITLE
注释错误

### ISSUE THREAD

**Issue by Lvbuqing** [baomidou/mybatis-plus#5384]
### 当前使用版本(必填,否则不予处理)
3.0+
### 重现步骤(如果有就写完整)

/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/ddl/DdlHelper.java

这是注释写错了还是没错啊？

![image](https://github.com/baomidou/mybatis-plus/assets/32841009/cc8bad1b-f986-4942-beac-9124a034b720)

![image](https://github.com/baomidou/mybatis-plus/assets/32841009/59b7bec5-b942-4364-962d-d2689716d1a4)

**Comment by Montaro2017** [comment]
![Image](https://github.com/user-attachments/assets/869c2607-b547-4885-a043-2f7e866d97f8)
这里是不是运行SQL脚本文件 @nieqiurong
