### ISSUE TITLE
表里有很大数据量要查出来循环处理，mybatis-plus有方便的流式查询方法吗

### ISSUE THREAD

**Issue by e001432124** [baomidou/mybatis-plus#5393]
### 当前使用版本(必填,否则不予处理)

使用版本：
jdk8
springboot 2.3.2
dynamic-datasource-spring-boot-starter:3.6.1
mybatis-plus-boot-starter:3.5.1
 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

业务上有一个表要批处理，上百万，一次性查出来不可能的了，也不想分页查询，我记得jdbc是支持流式查询的，想问下，mybatis-plus是怎么实现的？

**Comment by miemieYaho** [comment]
https://cloud.tencent.com/developer/article/1865727
