### ISSUE TITLE
查询指定字段能不能增加调用的方式实现？

### ISSUE THREAD

**Issue by simonkingws** [baomidou/mybatis-plus#5395]
### 当前使用版本(必填,否则不予处理)
version：3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
查询指定字段的方法：
select(String... sqlSelect)
 例：select("id", "name", "age")

问题：需要查询的字段都需要手动填写，且要和数据库字段保持一致，如果数据库字段更改，SQL就会报错。这里的查询的字段有点硬编码。

建议：能不能增加通过实体调用的方式来实现，比如：T.getId或T.id等。来保证数据库字段即便更改，也能保证调用的字段能和数据库字段映射上。

**Comment by miemieYaho** [comment]
LambdaQueryWrapper
