### ISSUE TITLE
lambdaQuery.orderBy报错：该方法仅能传入 lambda 表达式产生的合成类

### ISSUE THREAD

**Issue by wugs24** [baomidou/mybatis-plus#5397]
### 当前使用版本(必填,否则不予处理)

![image](https://github.com/baomidou/mybatis-plus/assets/86362605/6197fe41-d23f-4be3-bbaf-899c7f65d133)

### 重现步骤(如果有就写完整)
![image](https://github.com/baomidou/mybatis-plus/assets/86362605/152a8177-e8cd-45ac-af53-7fc501b6c382)

去掉orderByDesc就不会报错
![image](https://github.com/baomidou/mybatis-plus/assets/86362605/07def4d5-4dbe-4c0c-8f2b-9edc0f47e9a6)

### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/86362605/18501f54-5ce6-4859-a952-ecdd584e8a9d)

**Comment by miemieYaho** [comment]
无法复现
