### ISSUE TITLE
更新 timestamp类型字段报错

### ISSUE THREAD

**Issue by javanan** [baomidou/mybatis-plus#54]
mysql timestamp类型的字段 selectByid查询出来后，不修改timestamp字段类型的内容，，直接用updateByid 更新改实体，报错。无提示报错信息

**Comment by yuxiaobin** [comment]
进qq（576493122）群说详细点，骚年，你这样的问题是没法回答的

**Comment by qmdx** [comment]
应该解决了是吧！这里关掉
