### ISSUE TITLE
能否给BaseMapper增加updateFull系列的方法?

### ISSUE THREAD

**Issue by liudaomanbu** [baomidou/mybatis-plus#540]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.4

目前BaseMapper的update方法是根据属性是否有值来选择性更新字段的.
但是当某些情况下,必须将某个字段更新为Null时,没有办法使用BaseMapper完成.
能否增加updateFullById和updateFull方法?

**Comment by miemieYaho** [comment]
字段验证策略默认是 not_null, 你也可以使用 update 而不是 updatebyId 方法更新字段为 nul

**Comment by liudaomanbu** [comment]
> 字段验证策略默认是 not_null, 你也可以使用 update 而不是 updatebyId 方法更新字段为 nul

使用update方法能把字段值更新为null吗?我看update和updatebyId方法的区别只有where条件啊.

**Comment by miemieYaho** [comment]
updateWrapper.set 方法
