### ISSUE TITLE
 存在 SQL 注入风险, 如想避免 SQL 注入校验，可以调用 Page.setUnsafeOrderBy

### ISSUE THREAD

**Issue by hanweidong** [baomidou/mybatis-plus#5401]
### 当前使用版本(必填,否则不予处理)

v3.5.3.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
排序中我需要把字段转换成正则的形式（“ cast(regexp_replace(number, '[^0-9]', '', 'g') as int)”）

### 重现步骤(如果有就写完整)
存在一列number字段（1#或#1）的形式，我需要使用正则的方式取出数字对列表进行排序

### 报错信息
存在 SQL 注入风险, 如想避免 SQL 注入校验，可以调用 Page.setUnsafeOrderBy

**Comment by 1304175015** [comment]
最后怎么处理的，我也遇到同样问题了
