### ISSUE TITLE
DataChangeRecorderInnerInterceptor 根据条件更新 修改的新值为null 旧值正确

### ISSUE THREAD

**Issue by farmer-youngest** [baomidou/mybatis-plus#5403]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
`
update(
                Wrappers.lambdaUpdate(TestTabEntity.class)
                        .ge(TestTabEntity::getId,83)
                        .le(TestTabEntity::getId,90)
                        .set(TestTabEntity::getUuid,"555")
        );
`
 根据条件更新 修改的新值为null 旧值正确

### 报错信息
`{
	"tableName": "test_tab",
	"operation": "update",
	"recordStatus": "true",
	"changedData": [
		{
			"ID": "83",
			"UUID": "555->null"
		},
		{
			"ID": "84",
			"UUID": "555->null"
		},
		{
			"ID": "85",
			"UUID": "555->null"
		},
		{
			"ID": "86",
			"UUID": "555->null"
		},
		{
			"ID": "87",
			"UUID": "555->null"
		},
		{
			"ID": "88",
			"UUID": "555->null"
		},
		{
			"ID": "89",
			"UUID": "555->null"
		},
		{
			"ID": "90",
			"UUID": "555->null"
		}
	],
	"cost(ms)": 3071
}`

**Comment by 986510453** [comment]
字段类型对得上吗？uuid是字符串类型？

**Comment by farmer-youngest** [comment]
> 字段类型对得上吗？uuid是字符串类型？

字段类型对得上，uuid是varchar

**Comment by lunxian8** [comment]
lambda有关吗？我也是测试 新值输出null https://gitee.com/baomidou/mybatis-plus/issues/I7VTVV

**Comment by nieqiurong** [comment]
#6430
