### ISSUE TITLE
未添加@TableId 注解，控制台发出警告

### ISSUE THREAD

**Issue by heyXiaoT** [baomidou/mybatis-plus#5405]
### 当前使用版本(必填,否则不予处理)
v3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实体类未配置@TableId

### 建议
是否可以添加配置，用于关闭 **Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.** 这个警告信息

**Comment by miemieYaho** [comment]
不能

**Comment by Farb** [comment]
有些实体确实只想查询，但不查询Id相关信息啊 @miemieYaho
