### ISSUE TITLE
自定义MybatisSqlSessionFactoryBean之后 ，properties配置的 mybatis-plus.mapper-locations 配置失效

### ISSUE THREAD

**Issue by gyjx** [baomidou/mybatis-plus#5407]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 重现步骤(如果有就写完整)
自定义MybatisSqlSessionFactory 

 @Bean
    @Primary
    public SqlSessionFactory sqlSessionFactory(MybatisPlusInterceptor mybatisPlusInterceptor) throws Exception {
        MybatisSqlSessionFactoryBean sqlSessionFactory=new MybatisSqlSessionFactoryBean();
        sqlSessionFactory.setDataSource(dataSource());
        sqlSessionFactory.setPlugins(mybatisPlusInterceptor);
        return sqlSessionFactory.getObject();
    }

properties配置

mybatis-plus.mapper-locations=classpath:mapper/*.xml,classpath:mybatis/*.xml

### 报错信息

org.apache.ibatis.binding.BindingException: Invalid bound statement (not found):

请问该问题如何解决？

**Comment by miemieYaho** [comment]
抄mp的starter
