### ISSUE TITLE
Bug/建议

### ISSUE THREAD

**Issue by tme1946** [baomidou/mybatis-plus#541]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.4

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
生成的代码无法查询

### 重现步骤
表名以T_USER方式命名，在配置文件中配置
strategy.setTablePrefix("T_");
生成的实体类为正常的User

### 报错信息
Table 'ssm.user' doesn't exist

查询是按照实体类名来反向生成的
建议如果生成类中配置了setTablePrefix方法的话，
可以在生成的实体类上生成类似@TableName("t_user")注解
这样修改了前缀（或后缀）不会影响查询

**Comment by miemieYaho** [comment]
你可以配置 mp 的 DbConfig.tablePrefix 来设置表名前缀

**Comment by miemieYaho** [comment]
你可以配置 mp 的 DbConfig.tablePrefix 来设置表名前缀

**Comment by tme1946** [comment]
mybatis-plus:
  global-config:
    db-config:
      #查询时加入表前缀
      table-prefix: "t_"

设置了之后可以使用了，谢谢大佬。

我拓展一下，要是我库中有两类表，一类是t_开头的，用于管理用户的
一类是qrtz_开头的，用于计划任务的，如果按这个配置的话，qrtz类的表怎么办呢

**Comment by qmdx** [comment]
无法满足你这么多前缀的自动识别这个时候你需要注解
