### ISSUE TITLE
分页查询大批量数据时，count(1) 操作是否可以支持异步？

### ISSUE THREAD

**Issue by shanyao-bryant** [baomidou/mybatis-plus#5417]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
您好，在项目中，使用分页查询大批量数据时，**count(1)** 操作和实际查询sql是同步执行的。
在这种场景下，count(1) 其实都是都数据的，不需要等待 count(1) 完了之后，在判断是否要执行查询sql。
通过测试，**异步执行 count(1)** 会提高查询速度。
我看了最新版本，好像没有这个功能的支持。
目前自己的项目中通过修改源码已经实现了通过参数控制是否要异步执行分页查询。
在未来的版本会添加此功能吗？

**Comment by miemieYaho** [comment]
大概率不会

**Comment by shanyao-bryant** [comment]
> 大概率不会

好的

**Comment by xbox1994** [comment]
@shanyao-bryant 这是一个非常实用的功能，我们也需要，可以将你们【修改源码已经实现了通过参数控制是否要异步执行分页查询】的详细代码分享出来吗？

**Comment by shanyao-bryant** [comment]
不好意思，今天才看到消息。。。 我把代码提交到我仓库里的mybatis-plus代码里了，你可以拉下来参考一下，我写的不是很好。。。

**Comment by xbox1994** [comment]
> 不好意思，今天才看到消息。。。 我把代码提交到我仓库里的mybatis-plus代码里了，你可以拉下来参考一下，我写的不是很好。。。

谢谢
