### ISSUE TITLE
为什么 service层提供了批量插入的方法，mapper层没有提供

### ISSUE THREAD

**Issue by bigtree1992** [baomidou/mybatis-plus#5418]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
正常使用

### 报错信息
无

**Comment by tltwuyu** [comment]
mapper是有批量插入的选装插件的。但是两者的底层实现不同。

**Comment by VampireAchao** [comment]
mapper层的批量插入选装插件部分数据库不兼容，因此作为选装插件，但是service是兼容全数据库的，且支持事务，但性能不一定有mapper层的批量插入选装插件好
也可以使用最新版的Db类
```java
Db.saveBatch(userList);
```
