### ISSUE TITLE
代码生成问题：连接SQLServer数据库生成代码时无法获取表和字段的注释comment

### ISSUE THREAD

**Issue by wqkeep** [baomidou/mybatis-plus#5419]
### 当前使用版本(必填,否则不予处理)
版本：3.5.3.1
![image](https://github.com/baomidou/mybatis-plus/assets/48304878/a757e379-47c4-42ea-b0f0-b0f0592b0f75)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
MySQL生成代码没任何问题，仅仅是切换到SQLServer生成代码后字段没有获取到注释comment
![image](https://github.com/baomidou/mybatis-plus/assets/48304878/b1906d9b-2d5c-4926-b176-17e46bd7236b)

### 重现步骤(如果有就写完整)
![image](https://github.com/baomidou/mybatis-plus/assets/48304878/41951f8b-f1de-469e-8f69-a01ed7823fec)

MySQL生成：
![image](https://github.com/baomidou/mybatis-plus/assets/48304878/4209105a-09eb-48ac-89a5-90c896fd1bc0)

SQLServer生成：
![image](https://github.com/baomidou/mybatis-plus/assets/48304878/8f6a4017-8a88-4573-b6e2-be1a61b07daa)

### 报错信息
无报错信息，仅仅是获取不到表和字段的注释comment，其它一切正常
![image](https://github.com/baomidou/mybatis-plus/assets/48304878/b567b791-ab4b-4929-aa71-91c21c54c07a)

**Comment by qmdx** [comment]
如下指定 databaseQueryClass 类 SQL 查询方式

```
    /**
     * 数据源配置
     */
    private static final DataSourceConfig DATA_SOURCE_CONFIG = new DataSourceConfig
        .Builder("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=MYSQL", "sa", "")
        .databaseQueryClass(SQLQuery.class) // 设置SQL查询方式，默认的是元数据查询方式
        .build();
```
