### ISSUE TITLE
一对多关联对象分页查询，total字段不准确

### ISSUE THREAD

**Issue by lyingfromyou** [baomidou/mybatis-plus#542]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
一个用户对应多个角色，导致分页查询出来的total字段是错的，例如：
SELECT  COUNT(1)  from sys_user 
LEFT JOIN user_role on user_role.user_id = user_role.user_id 
LEFT JOIN sys_role ON sys_role.role_id = user_role.role_id 
这样会查出两条数据

**Comment by miemieYaho** [comment]
就算你丢数据库里查也是两条
