### ISSUE TITLE
自动填充主键字段值特定情况下失败

### ISSUE THREAD

**Issue by LTCErick** [baomidou/mybatis-plus#5420]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实现MetaObjectHandler做自动填充数据库主键字段值（添加的@TableId注解），debug无法进入自定义实现了MetaObjectHandler的类，在对应的实体类上添加创建时间字段并添加@TableField(value = "CREATE_DATE", fill = FieldFill.INSERT)，此时可以进入该类并正常填充主键字段值和创建时间字段值。

### 报错信息
无法进入自定义实现了MetaObjectHandler的类，导致数据自动填充失败

**Comment by miemieYaho** [comment]
主键不在判断需要去填充的范围内

**Comment by LTCErick** [comment]
3.0.1版本好像没有这个严格填充的限制，升级需要额外注意这个问题吗？
另外实现方式为覆盖insertFill() 方法，而不是strictInsertFill，为何会触发呢？
@Override
    public void insertFill(MetaObject metaObject) {
        log.info("已进入数据自动填充表主键信息");
        setTableId(metaObject);
    }
