### ISSUE TITLE
service.saveBatch() 如何批量返回id至对象中

### ISSUE THREAD

**Issue by stacktime** [baomidou/mybatis-plus#5422]
mybatis-plus 3.5.2
![image](https://github.com/baomidou/mybatis-plus/assets/54928835/c135f84b-f778-423a-872c-85acbc41e74e)

使用批量新增,无法返回实体中的主键id
`// 插入（批量） 
boolean saveBatch(Collection<T> entityList);`
![image](https://github.com/baomidou/mybatis-plus/assets/54928835/66b10627-db57-41f3-b1d6-525a63f70913)

**Comment by wting1123** [comment]
请问如何解决这个问题

**Comment by 85668869** [comment]
我也遇到了，有解决方案么？

**Comment by nieqiurong** [comment]
什么数据库,主键策略是什么样的?

**Comment by qmdx** [comment]
无反馈，请反馈后打开

**Comment by zhuzhenguang** [comment]
我也碰到这个问题，数据库是mysql 8，主键是auto，应该使用mysql的自增主键。mapper insert后实体会有id，但是saveBatch后，list里的实体没有id。
但是如果用H2在单元测试中是好的。

**Comment by xiaobull** [comment]
使用 IService 的saveBatch()方法，可以将id批量返回到实体对象中
<img width="705" alt="微信截图_20240819155934" src="https://github.com/user-attachments/assets/06ba753e-755f-40ae-ad0d-ad03214253a9">
