### ISSUE TITLE
Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by RuiqianZhang** [baomidou/mybatis-plus#5423]
### 当前使用版本(必填,否则不予处理)
4.0.0-B1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目从springboot2 升级到springboot3后出现

### 重现步骤(如果有就写完整)
使用单数据源就没问题，使用动态多数据源就一直报错数据源未配置。

### 报错信息
Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles dev are currently active).

**Comment by RuiqianZhang** [comment]
提错地方了

**Comment by singelone** [comment]
这个问题怎么解决的
