### ISSUE TITLE
自动填充功能，空值也更新期望如果空值不填充

### ISSUE THREAD

**Issue by gaspire** [baomidou/mybatis-plus#5433]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 重现步骤(如果有就写完整)
使用了自动填充功能，
`@TableField(fill = FieldFill.INSERT_UPDATE)
    private Long updateBy;`
也实现了MetaObjectHandler， 在方法中updateFill，如果当前用户ID为空，就没有调用
`this.strictFillStrategy(metaObject, "updateBy", this::getUserId);`
### 报错信息

实际结果的sql 语句里 还是有 set update_by = null, 有没有办法不更新，如果为空的时候

**Comment by miemieYaho** [comment]
填充是在ognl之后的

**Comment by TOP-LH** [comment]
> 

请问可以处理吗, 我这里也希望为空不更新, 不为空在更新比较好

**Comment by TOP-LH** [comment]
> 填充是在ognl之后的


请问可以处理吗, 我这里也希望为空不更新, 不为空在更新比较好

**Comment by qmdx** [comment]
可以申明策略  `@TableField( .. updateStrategy=FieldStrategy.IGNORED)`  这样 `OGNL`  不会判空，你可以传入任何值
