### ISSUE TITLE
请问一下mybatis-plus3.5.3.1版本，默认的雪花算法生成的主键id，是否解决了时钟回拨的问题

### ISSUE THREAD

**Issue by huanti** [baomidou/mybatis-plus#5434]
### 当前使用版本(必填,否则不予处理)
3.5.3.1版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如题

### 报错信息
暂无

**Comment by qmdx** [comment]
雪花算法是不允许时间回拨的
