### ISSUE TITLE
主键是 IdType.AUTO 时    saveBatch 保存时,  报主键重复, 希望可以修复

### ISSUE THREAD

**Issue by hanrunaini** [baomidou/mybatis-plus#5435]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

saveBatch  保存时 发生的

### 报错信息
org.springframework.dao.DuplicateKeyException: com.atguigu.ssyx.product.mapper.SkuImageMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Duplicate entry '118' for key 'sku_image.PRIMARY'
; Duplicate entry '118' for key 'sku_image.PRIMARY'; nested exception is java.sql.BatchUpdateException: Duplicate entry '118' for key 'sku_image.PRIMARY'

**Comment by miemieYaho** [comment]
对象是同一个吧?

**Comment by qmdx** [comment]
代码贴出来

**Comment by yanity233** [comment]
请问解决了吗?怎么解决的

**Comment by zengyl201610224125** [comment]
解决了吗 什么原因
