### ISSUE TITLE
Postgres数据库中中文排序异常

### ISSUE THREAD

**Issue by tapestryonly** [baomidou/mybatis-plus#5443]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用Postgres数据库，查询时按中文排序，代码如下：
query.orderByAsc( String.format( " convert_to(%s, 'GB18030') ", item ) );

### 重现步骤(如果有就写完整)
在3.5.2（以及更早的版本）中执行正常，但是在3.5.3.1中会报错找不到column GB18030
打印出的SQL中GB18030上的单引号被去除了。
恢复到3.5.2后恢复正常

**Comment by qmdx** [comment]
新版 `3.5.3.2` 移除了强制过滤逻辑，开发者自己决定是否开启注入 SQL 过滤，另外过滤 SQL 的工具类也升级优化更加合理，请关注最新版本的发布
