### ISSUE TITLE
达梦多个schema生成代码时xml中sql执行失败

### ISSUE THREAD

**Issue by syanming** [baomidou/mybatis-plus#5450]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-generator</artifactId>
    <version>3.5.3.1</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用达梦数据库时有多个schema, 生成代码时开启了enableSchema, 然后在xml中编写sql时执行报错
我是想同一套代码可以直接切换驱动就可以直接运行

### 重现步骤(如果有就写完整)
1: 使用generator生成代码, 开启enableSchema
生成的entity
![image](https://github.com/baomidou/mybatis-plus/assets/34526129/8274597a-00b7-4fb3-80a7-f378207127ad)

2: 在xml中编写sql
![image](https://github.com/baomidou/mybatis-plus/assets/34526129/3fdb0c74-0424-4a49-a559-16a9c8a9aeb3)

3: sql执行失败, 报错

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/34526129/6da80190-18f2-42da-b5ed-f10b4c2df7fa)

**Comment by miemieYaho** [comment]
你自己写的sql与代码生成无关
