### ISSUE TITLE
能否在类上面增加忽略数据访问字段，因为有些字段是继承过来的

### ISSUE THREAD

**Issue by changyoutianxia** [baomidou/mybatis-plus#5452]
### 当前使用版本(必填,否则不予处理)

v3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
能否增加一个注解，访问数据库的时候忽略某些字段，因为我在构建一个公共的实体的时候，有些表没有createUser，
能否在类上面加注解，忽略其中的某些属性。
而@TableField 这个注解只能用在属性上面

**Comment by miemieYaho** [comment]
tableName里
