### ISSUE TITLE
KtQueryWrapper和KtUpdateWrapper泛型限制问题

### ISSUE THREAD

**Issue by initchen** [baomidou/mybatis-plus#5454]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

源码中KtQueryWrapper继承的Query接口传的泛型是KProperty<*>，代码如下：
```
open class KtQueryWrapper<T : Any> : AbstractKtWrapper<T, KtQueryWrapper<T>>, Query<KtQueryWrapper<T>, T, KProperty<*>> {
  ...
}
```
会导致在使用的时候，没有泛型进行约束，比如下面这段代码也可以编译通过
```
KtUpdateWrapper(User()).eq(OtherUser::otherName, "sss") 
```

我目前尝试改动泛型为KMutableProperty1<T, *>是可以做到约束的，比如：
```
open class KtQueryWrapper<T : Any> : AbstractKtWrapper<T, KtQueryWrapper<T>>, Query<KtQueryWrapper<T>, T, KMutableProperty1<T, *>> {
  ...
}
```
### 重现步骤(如果有就写完整)
```

import com.baomidou.mybatisplus.annotation.TableField
import com.baomidou.mybatisplus.annotation.TableName
import com.baomidou.mybatisplus.core.MybatisConfiguration
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper
import com.baomidou.mybatisplus.extension.kotlin.KtQueryWrapper
import org.apache.ibatis.builder.MapperBuilderAssistant

fun main() {
    TableInfoHelper.initTableInfo(MapperBuilderAssistant(MybatisConfiguration(), ""), User::class.java)
    TableInfoHelper.initTableInfo(MapperBuilderAssistant(MybatisConfiguration(), ""), OtherUser::class.java)
    println(KtQueryWrapper(User()).select(User::name).eq(User::name, "sss").sqlSegment)
    println(KtQueryWrapper(User()).select(OtherUser::otherName).eq(OtherUser::otherName, "sss").sqlSegment)
}

@TableName("sys_user")
class User {

    var id: Int? = null

    @TableField("username")
    var name: String? = null

    var roleId: Int? = null
}

@TableName("other_user")
class OtherUser {

    var id: Int? = null

    var otherName: String? = null

    var roleId: Int? = null
}
```

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/commit/276ea9895dc56d6d50ce81c7e3af769a9252f0d3

**Comment by c332030** [comment]
这样我没法使用基类了

**Comment by c332030** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15310784/d58203f9-d818-47e8-8b05-5b8e2c048c31)

**Comment by c332030** [comment]
这种怎么处理，列名对上不就行了吗

**Comment by c332030** [comment]
变量也不能用 val 修饰了，有些字段直接用 sql 修改，查回来后不需要改，用 val 很正常吧

**Comment by c332030** [comment]
@miemieYaho 辛苦帮忙看看

**Comment by c332030** [comment]
```kotlin
interface ICService<T : Any> : IService<T> {

    fun update(whereChain: (KtUpdateChainWrapper<T>) -> KtUpdateChainWrapper<T>): Boolean {

        val wrapper = whereChain.invoke(ktUpdate())

        val now = Instant.now()

        if (IUpdater::class.java.isAssignableFrom(entityClass)) {
            wrapper.set(IUpdater::updater, getUserId())
            wrapper.set(IUpdateTime::updateTime, now)
        } else if (IUpdateTime::class.java.isAssignableFrom(entityClass)) {
            wrapper.set(IUpdateTime::updateTime, now)
        }

        return wrapper.update()
    }

}
```

**Comment by c332030** [comment]
```kotlin
interface IUpdateTime {

    @get:ApiModelProperty("更新时间")
    var updateTime: Instant?

}

interface IUpdater : IUpdateTime {

    @get:ApiModelProperty("更新人")
    @get:JsonSerialize(using = ToStringSerializer::class)
    var updater: Long?

}

data class User(

    var id: Long? = null,

    override var updater: Long? = null,
    override var updateTime: Instant? = null,

): IUpdater
```

**Comment by c332030** [comment]
这样也会报错
```kotlin
interface ICUpdaterService<T: IUpdater> : ICService<T> {

    override fun update(whereChain: (KtUpdateChainWrapper<T>) -> KtUpdateChainWrapper<T>): Boolean {
        return super.update{
            it.set(IUpdater::updater, getUserId())
        }
    }

}
```
![image](https://github.com/baomidou/mybatis-plus/assets/15310784/f591a0d3-f649-4e32-ae37-93aa36d93514)

**Comment by c332030** [comment]
这样用不了的
![image](https://github.com/baomidou/mybatis-plus/assets/15310784/4edcd127-155f-4b2f-98a2-a28c76f2c6af)

**Comment by c332030** [comment]
这种重复性的更新操作，难道每次都写一遍吗

**Comment by initchen** [comment]
> 这样也会报错
> 
> ```kotlin
> interface ICUpdaterService<T: IUpdater> : ICService<T> {
> 
>     override fun update(whereChain: (KtUpdateChainWrapper<T>) -> KtUpdateChainWrapper<T>): Boolean {
>         return super.update{
>             it.set(IUpdater::updater, getUserId())
>         }
>     }
> 
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/15310784/286317462-f591a0d3-f649-4e32-ae37-93aa36d93514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjA0NTksIm5iZiI6MTcwMTIyMDE1OSwicGF0aCI6Ii8xNTMxMDc4NC8yODYzMTc0NjItZjU5MWEwZDMtZjY0OS00ZTMyLWFlMzctOTNhYTM2ZDkzNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5N2YzNzNmMzEyNDIyMDI1ZTNiMzZkNGUwMjFlYzFkNjc5ZTEwYjQyNDU1MDRhOGZkZTg2ZGNkYTE5ODUzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfQG0SPc4NFvl-vi4kfBfzXj0ThE2fSMTuq1jb_vhtc)

试试强转呢it.set(IUpdater::updater as KMutableProperty1<T, *>, getUserId())

**Comment by initchen** [comment]
> 变量也不能用 val 修饰了，有些字段直接用 sql 修改，查回来后不需要改，用 val 很正常吧

数据库实体类用final修复的字段，查询后也能赋值吗，有这个场景的话，源码的泛型由KMutableProperty1<T, *>改为KProperty1<T, *>是同时支持var和val

**Comment by c332030** [comment]
> > 这样也会报错
> > ```kotlin
> > interface ICUpdaterService<T: IUpdater> : ICService<T> {
> > 
> >     override fun update(whereChain: (KtUpdateChainWrapper<T>) -> KtUpdateChainWrapper<T>): Boolean {
> >         return super.update{
> >             it.set(IUpdater::updater, getUserId())
> >         }
> >     }
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/15310784/286317462-f591a0d3-f649-4e32-ae37-93aa36d93514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjA0NTksIm5iZiI6MTcwMTIyMDE1OSwicGF0aCI6Ii8xNTMxMDc4NC8yODYzMTc0NjItZjU5MWEwZDMtZjY0OS00ZTMyLWFlMzctOTNhYTM2ZDkzNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5N2YzNzNmMzEyNDIyMDI1ZTNiMzZkNGUwMjFlYzFkNjc5ZTEwYjQyNDU1MDRhOGZkZTg2ZGNkYTE5ODUzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfQG0SPc4NFvl-vi4kfBfzXj0ThE2fSMTuq1jb_vhtc)
> 
> 试试强转呢it.set(IUpdater::updater as KMutableProperty1<T, *>, getUserId())

你好，这样不报错但是有警告，关掉警告会导致其他有意义的警告显示不了吧，虽然这里没有喽
有的警告虽然不影响编译，但是可能导致线上报错
![image](https://github.com/baomidou/mybatis-plus/assets/15310784/2be99d9f-90f7-4e6c-b591-47e1a4046714)

**Comment by initchen** [comment]
> > > 这样也会报错
> > > ```kotlin
> > > interface ICUpdaterService<T: IUpdater> : ICService<T> {
> > > 
> > >     override fun update(whereChain: (KtUpdateChainWrapper<T>) -> KtUpdateChainWrapper<T>): Boolean {
> > >         return super.update{
> > >             it.set(IUpdater::updater, getUserId())
> > >         }
> > >     }
> > > 
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://private-user-images.githubusercontent.com/15310784/286317462-f591a0d3-f649-4e32-ae37-93aa36d93514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjA0NTksIm5iZiI6MTcwMTIyMDE1OSwicGF0aCI6Ii8xNTMxMDc4NC8yODYzMTc0NjItZjU5MWEwZDMtZjY0OS00ZTMyLWFlMzctOTNhYTM2ZDkzNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5N2YzNzNmMzEyNDIyMDI1ZTNiMzZkNGUwMjFlYzFkNjc5ZTEwYjQyNDU1MDRhOGZkZTg2ZGNkYTE5ODUzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfQG0SPc4NFvl-vi4kfBfzXj0ThE2fSMTuq1jb_vhtc)
> > 
> > 
> > 试试强转呢it.set(IUpdater::updater as KMutableProperty1<T, *>, getUserId())
> 
> 你好，这样不报错但是有警告，关掉警告会导致其他有意义的警告显示不了吧，虽然这里没有喽 有的警告虽然不影响编译，但是可能导致线上报错 ![image](https://private-user-images.githubusercontent.com/15310784/286454706-2be99d9f-90f7-4e6c-b591-47e1a4046714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjUyNjMsIm5iZiI6MTcwMTIyNDk2MywicGF0aCI6Ii8xNTMxMDc4NC8yODY0NTQ3MDYtMmJlOTlkOWYtOTBmNy00ZTZjLWI1OTEtNDdlMWE0MDQ2NzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1M2IwMzJlMmI1OTBkYTlkMzIzNTQyODg2ZmE0YWZjZjI1MzRkZTZlNWRjMzRkMjUxY2ZlMTEwZGIwNDAyNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LkjiqDuquKQmiToXkKSjFnkwg1fYRaJwkSkgHOMtpk4)

关闭警告的范围有代码行、方法、类、整个文件，你压制代码行或者方法应该就可以了，比如下面是关闭单行的
```
@Suppress("UNCHECKED_CAST")
wrapper.set(IUpdater::updater as KMutableProperty1<T, *>, 1)
@Suppress("UNCHECKED_CAST")
wrapper.set(IUpdater::updateTime as KMutableProperty1<T, *>, now)
```

**Comment by c332030** [comment]
> > > > 这样也会报错
> > > > ```kotlin
> > > > interface ICUpdaterService<T: IUpdater> : ICService<T> {
> > > > 
> > > >     override fun update(whereChain: (KtUpdateChainWrapper<T>) -> KtUpdateChainWrapper<T>): Boolean {
> > > >         return super.update{
> > > >             it.set(IUpdater::updater, getUserId())
> > > >         }
> > > >     }
> > > > 
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ![image](https://private-user-images.githubusercontent.com/15310784/286317462-f591a0d3-f649-4e32-ae37-93aa36d93514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjA0NTksIm5iZiI6MTcwMTIyMDE1OSwicGF0aCI6Ii8xNTMxMDc4NC8yODYzMTc0NjItZjU5MWEwZDMtZjY0OS00ZTMyLWFlMzctOTNhYTM2ZDkzNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5N2YzNzNmMzEyNDIyMDI1ZTNiMzZkNGUwMjFlYzFkNjc5ZTEwYjQyNDU1MDRhOGZkZTg2ZGNkYTE5ODUzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfQG0SPc4NFvl-vi4kfBfzXj0ThE2fSMTuq1jb_vhtc)
> > > 
> > > 
> > > 试试强转呢it.set(IUpdater::updater as KMutableProperty1<T, *>, getUserId())
> > 
> > 
> > 你好，这样不报错但是有警告，关掉警告会导致其他有意义的警告显示不了吧，虽然这里没有喽 有的警告虽然不影响编译，但是可能导致线上报错 ![image](https://private-user-images.githubusercontent.com/15310784/286454706-2be99d9f-90f7-4e6c-b591-47e1a4046714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjUyNjMsIm5iZiI6MTcwMTIyNDk2MywicGF0aCI6Ii8xNTMxMDc4NC8yODY0NTQ3MDYtMmJlOTlkOWYtOTBmNy00ZTZjLWI1OTEtNDdlMWE0MDQ2NzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1M2IwMzJlMmI1OTBkYTlkMzIzNTQyODg2ZmE0YWZjZjI1MzRkZTZlNWRjMzRkMjUxY2ZlMTEwZGIwNDAyNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LkjiqDuquKQmiToXkKSjFnkwg1fYRaJwkSkgHOMtpk4)
> 
> 关闭警告的范围有代码行、方法、类、整个文件，你压制代码行或者方法应该就可以了，比如下面是关闭单行的
> 
> ```
> @Suppress("UNCHECKED_CAST")
> wrapper.set(IUpdater::updater as KMutableProperty1<T, *>, 1)
> @Suppress("UNCHECKED_CAST")
> wrapper.set(IUpdater::updateTime as KMutableProperty1<T, *>, now)
> ```

这样是可以，但是我是想能不关闭警告还是不要关闭警告，我先降级吧

KMutableProperty1<T, *>改为KProperty1<T, *> 我觉得还是有必要的，更新一两个字段用 set 更新，就不用考虑赋值了，直接传实体过去更新还会忽略 null

**Comment by c332030** [comment]
KProperty1<in T, *> 这样限定可以传父类可以吗，我第一次 fork 各种问题编译不了

**Comment by initchen** [comment]
> KProperty1<in T, *> 这样限定可以传父类可以吗，我第一次 fork 各种问题编译不了

确实可以传父类了

**Comment by c332030** [comment]
> > KProperty1<in T, *> 这样限定可以传父类可以吗，我第一次 fork 各种问题编译不了
> 
> 确实可以传父类了

好的，谢谢
