### ISSUE TITLE
查询列全为空值时，结果对象为null

### ISSUE THREAD

**Issue by jellyleo** [baomidou/mybatis-plus#5460]
### 当前使用版本(必填,否则不予处理)
3.5.3.1
![图片](https://github.com/baomidou/mybatis-plus/assets/34032791/ae89016b-109d-4153-8b97-ca00b46b0cb7)

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![图片](https://github.com/baomidou/mybatis-plus/assets/34032791/342702f5-5ea4-4ca3-b422-7984ac2f6758)
只查询表中的ip字段，符合条件的数据只有一条，且ip为null

### 重现步骤(如果有就写完整)
期待svcList返回值应该为[{"ip":null}]，实际返回的为[null]
对svcList做了判空，但是遍历时未对子元素svc判空，导致svc.getIp()出现空指针异常

### 报错信息
MyBatis-Plus未报错，但是在业务上selectList要始终对集合中的对象判空，影响代码美观。
考虑是否可以保证selectList的结果集合中元素为非null。

**Comment by miemieYaho** [comment]
数据封装是mybatis的事
