### ISSUE TITLE
Model是否可以改成interface

### ISSUE THREAD

**Issue by 203579397** [baomidou/mybatis-plus#5461]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

优化建议
在与lombok builder superBuild 结合使用时，会因为 abstract class Model 无法构建 Builder；
我看了一下  Model 中没有需要序列化的属性，如果可能建议考虑一下，确实框架改动较大；

### 重现步骤(如果有就写完整)

优化建议

### 报错信息

暂无

**Comment by qmdx** [comment]
不能哦 interface  局限性太大很多逻辑无法处理
