### ISSUE TITLE
Db.saveBatch批量插入不会回填id

### ISSUE THREAD

**Issue by wting1123** [baomidou/mybatis-plus#5468]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![1689411017927](https://github.com/baomidou/mybatis-plus/assets/54521069/a34efb7a-665e-4107-bbf4-e571c3bf93fb)
![1689411050539](https://github.com/baomidou/mybatis-plus/assets/54521069/cb8659e3-f90c-4e98-95eb-259425926933)

### 报错信息
新增成功后，没有回填id到实体类中，请问一下怎么解决

**Comment by VampireAchao** [comment]
Hello,

Could you provide a small repro project?
We may also need instruction about JVM configuration to reproduce the issue.

Regards,
VampireAchao

**Comment by qmdx** [comment]
目前反馈内容无法定位，你可以看看是不是设置的注解 ID 自增，如果是这样需要数据库设置自增
