### ISSUE TITLE
3.5.3.1版本AbstractSqlParserHandler类被删除

### ISSUE THREAD

**Issue by cptbaker233** [baomidou/mybatis-plus#5471]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

由3.4.1版本升级到3.5.3.1版本后出现

### 重现步骤(如果有就写完整)

由3.4.1版本升级到3.5.3.1版本后出现

### 报错信息
@SqlParser注解类被删除
AbstractSqlParserHandler类被删除
this.sqlParser(metaObject)方法被删除(该方法在AbstractSqlParserHandler类中)

**Comment by miemieYaho** [comment]
中间版本就已经标注过过时了
