### ISSUE TITLE
JDK17 警告

### ISSUE THREAD

**Issue by Jick-study** [baomidou/mybatis-plus#5472]
### 当前使用版本(必填,否则不予处理)
3.5.3

jdk17

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
首次执行数据库操作会有警告

### 报错信息
[c.b.m.c.t.s.ReflectLambdaMeta:41] Unable to make field private final java.lang.Class java.lang.invoke.SerializedLambda.capturingClass accessible: module java.base does not "opens java.lang.invoke" to unnamed module @78e89bfe

**Comment by nieqiurong** [comment]
用3.5.3.3-SNAPSHOT试试
