### ISSUE TITLE
updateBatchById触发Parameter 'MP_OPTLOCK_VERSION_ORIGINAL' not found

### ISSUE THREAD

**Issue by zxhchime** [baomidou/mybatis-plus#5478]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
updateBatchById

### 重现步骤(如果有就写完整)
1. list = listById
2. updateBatchById(list)

com.baomidou.mybatisplus.extension.plugins.inner.OptimisticLockerInnerInterceptor#doOptimisticLocker
我看官方文档以及代码注释里说批量修改无法支持乐观锁，但是我debug的确走进乐观锁方法了

请问什么原因或者是已经有人提过的issue我没看见的吗

### 报错信息
BindingException: Parameter 'MP_OPTLOCK_VERSION_ORIGINAL' not found. Available parameters are [et]

**Comment by zxhchime** [comment]
而且这个问题本地复现不了，线上服务有多个结点，有一个结点触发这个报错后，反复请求就一直报错，其他结点正常

**Comment by qmdx** [comment]
遇到重现逻辑和步骤请打开该 issue
