### ISSUE TITLE
2 版本升到3.0.3 遇到的问题

### ISSUE THREAD

**Issue by jueyue** [baomidou/mybatis-plus#548]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
第一个问题
  QueryWrapper wrapper = new QueryWrapper<>(params.getModel());
        if (params.getMap() != null) {
            handlerWrapper(wrapper, params.getMap(), params);
        }
        baseService.page(page, wrapper);

分页查询 TableInfoHelper 直接获取的字段列表不是用的注解导致查询的数据全部为空
List<String> columns = tableInfo.getFieldList().stream().map(TableFieldInfo::getColumn).collect(toList());
        if (null != tableInfo.getKeyColumn()) {
            columns.add(tableInfo.getKeyColumn());
        }

第二个问题
批量保存,改了模式,导致嵌套事务 失败
 SqlSession batchSqlSession = this.sqlSessionBatch();
        int i = 0;
        String sqlStatement = this.sqlStatement(SqlMethod.INSERT_ONE);
查询带有对象
@Override
    @Transactional(rollbackFor = RuntimeException.class)
    @CacheEvict(key = "#root.targetClass + ':key_'+#key")
    public boolean updateById(DictModel entity) {
        boolean updateSuccess = retBool(dictRepository.updateById(entity));
        if (updateSuccess) {
            dictRepository.delete(Condition.create(new DictModel()).eq("P_ID", entity.getId()));
            for (int i = 0; i < entity.getSubDict().size(); i++) {
                entity.getSubDict().get(i).setPid(entity.getId());
                entity.getSubDict().get(i).setPkey(entity.getKey());
            }
            updateSuccess = saveBatch(entity.getSubDict());
        }
        return updateSuccess;
    }

包这个错误
Cannot change the ExecutorType when there is an existing transaction
### 重现步骤
上面描述

### 报错信息
Cannot change the ExecutorType when there is an existing transaction

**Comment by qmdx** [comment]
请使用 `3.0.4` 版本
