### ISSUE TITLE
字段填充和if标签的问题

### ISSUE THREAD

**Issue by wzkris** [baomidou/mybatis-plus#5480]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

自定义sql搭配字段填充功能，最后生成的sql没有填充的字段

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/90759163/4f86d0a5-7e39-49ff-8a5a-c05f379f19f1)(可以看到填充器把数据填充进去了)
![image](https://github.com/baomidou/mybatis-plus/assets/90759163/d245101d-e359-4fb0-81c3-aa08d1cdc0f8)(但是生成的sql不存在这两个字段)
![image](https://github.com/baomidou/mybatis-plus/assets/90759163/01592b20-1786-4b5f-9635-d53581c83178)(自定义sql中是写了if判断的)

**Comment by miemieYaho** [comment]
ognl之后才是填充

**Comment by wzkris** [comment]
> 

可以把填充的时机提前吗

**Comment by wzkris** [comment]
> ognl之后才是填充
是不是意味着我自定义sql就没办法自动填充字段了

**Comment by qmdx** [comment]
> > 
> 
> 可以把填充的时机提前吗

暂时做不到 MP 的机制是启动注入的，判断条件事先初始化了，除非你注解移除判断条件
填充逻辑实在执行 XML sql 编译后，这个受低层 mybatis 限制无法提前。
