### ISSUE TITLE
 java.sql.SQLSyntaxErrorException: Column 'del_flag' specified twice

### ISSUE THREAD

**Issue by zhangqin2016** [baomidou/mybatis-plus#5483]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
insert
### 报错信息 
就是普通插入数据的时候会拼接两个一样的del_flag
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Column 'del_flag' specified twice
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Column 'del_flag' specified twice

**Comment by zhangqin2016** [comment]
有人吗

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by zhangqin2016** [comment]
我的问题，注解复制的时候与字段不匹配
