### ISSUE TITLE
多租户插件，没有添加表别名

### ISSUE THREAD

**Issue by SonKi-Aurora** [baomidou/mybatis-plus#5488]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用多租户插件，多表联查，tenant_id字段前没有加表别名，导致分不清字段所属表

**Comment by miemieYaho** [comment]
sql呢?

**Comment by wichell** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/3366894/70adcb33-9bc8-4597-bf14-114b4fa516f0)

重写租户插件里的获取表名方法可暂时解决
