### ISSUE TITLE
sql server 使用临时表时,分页出现关键字错误

### ISSUE THREAD

**Issue by onedayren** [baomidou/mybatis-plus#5489]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
拼装的语句逻辑没问题，不过sqlserver不支持SELECT COUNT(*) FROM (xxx) TOTAL 嵌套内出现IF 或者WITH 关键字,是否有方案可以解决？

![image](https://github.com/baomidou/mybatis-plus/assets/28996803/eb12e34d-d007-4f46-8377-21f06191616a)

### 重现步骤(如果有就写完整)

this.baseMapper.xxxx(page, params)

### 报错信息

Incorrect syntax near the keyword 'IF'.

**Comment by miemieYaho** [comment]
没有,自己写分页

**Comment by qmdx** [comment]
自定义count部分 SQL更多参考文档 baomidou.com
