### ISSUE TITLE
建议：改用 maven-publish 发布 Maven

### ISSUE THREAD

**Issue by Cat7373** [baomidou/mybatis-plus#549]
### 当前使用版本
[commit@9b4c373](https://github.com/baomidou/mybatis-plus/tree/9b4c373a32ace3f4fdbaf8dd7f0a38b7608f8a38)

### 建议
目前发布到`maven`库使用的是`uploadArchives`，建议更换为`maven-publish`插件的`publishing`

最近我自己的库用`Kotlin-DSL`重写后顺便换成了`publishing`，发现这个插件发布的包略干净一丢丢(至少`pom.xml`里的`test`依赖全部被清掉了，毕竟这些只用于测试，对引用库的人毫无卵用)

### Links
就如官方文档中说的，`uploadArchives`是`遗留`的，`原始`的，不应在新项目中使用的：

* https://docs.gradle.org/current/userguide/artifact_management.html
* https://docs.gradle.org/current/userguide/maven_plugin.html

应该用新的`Publishing`代替它：

* https://docs.gradle.org/current/userguide/publishing_overview.html

**Comment by qmdx** [comment]
等你 PR

**Comment by miemieYaho** [comment]
已使用
