### ISSUE TITLE
动态表名问题

### ISSUE THREAD

**Issue by wj17629081583** [baomidou/mybatis-plus#5490]
### 当前使用版本(必填,否则不予处理)

3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

  public void pushPowerInfo() {
        Map<String,Object> map= new HashMap<>();
        map.put("inboundTraffic",getFloodList());
        map.put("Rainfall",getStationRainList());
        log.error("推送的数据如下",map);
    }
    public List<Map<String, Object>> getFloodList() {
        QueryWrapper<Floodt> queryWrapper = new QueryWrapper<>();
        queryWrapper.select("value", "code", "time");
        queryWrapper.like("time", TimeUtils.stringTime().substring(0, 13));
        return FloodtMapper.selectMaps(queryWrapper);
    }
   

    public List<Map<String, Object>> getStationRainList(){
        QueryWrapper<ionrain> queryWrapper = new QueryWrapper<>();
        queryWrapper.like("f_time", TimeUtils.stringTime().substring(0, 13));
        RequestDataHelper.setRequestData(new HashMap<String, Object>() {{
            put("table_name", TimeUtils.month());
        }});
        return bionrainMapper.selectMaps(queryWrapper);
    }

### 重现步骤(如果有就写完整)
表一Floodt 是不需要动态表名的
表二bionrainMapper 需要动态表名的

### 报错信息

 SELECT     value,,code,time     FROM   Floodt_202307        WHERE (time LIKE ?)
### Cause: java.sql.SQLSyntaxErrorException: Table 'Floodt_202307        ' doesn't exist

会把第二张表动态条件查询到第一张表上去，  然后 分开2controller 又是好的

**Comment by wj17629081583** [comment]
public List<Map<String, Object>> getFloodList() {
QueryWrapper queryWrapper = new QueryWrapper<>();
queryWrapper.select("value", "code", "time");
queryWrapper.like("time", TimeUtils.stringTime().substring(0, 13));
 RequestDataHelper.setRequestData(new HashMap<String, Object>() {{
           
        }});
return FloodtMapper.selectMaps(queryWrapper);
}

以上 解决了，但是不太优雅哈 ，望提供更好的解决方式

**Comment by qmdx** [comment]
根据你提供的信息暂时无法定位问题所在，请提供重现 demo

**Comment by wj17629081583** [comment]
> 根据你提供的信息暂时无法定位问题所在，请提供重现 demo

我发的就是完整的demo哦 ，测试样例您这边可以生成2个表的查询 测试

**Comment by qmdx** [comment]
> ueryWrapper queryWrapper = new QueryWrapper<>();
> queryWrapper.select("value", "code", "time");
> queryWrapper.like("time", TimeUtils.stringTime().substring(0, 13));
> return FloodtMapper.selectMaps(queryWrapper);
> }

请把动态表名部分配置也贴出来

**Comment by qmdx** [comment]
无反馈暂时关闭，请反馈后打开
