### ISSUE TITLE
nonEmptyOfEntity报错是什么引起的

### ISSUE THREAD

**Issue by usermrchen** [baomidou/mybatis-plus#5491]
### 当前使用版本(必填,否则不予处理)

 <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 查询这个sql的时候SpiderTaskAmSearch6 search6 = spiderTaskAmSearch6Service.getOne(new QueryWrapper<SpiderTaskAmSearch6>()
                            .ne("state", "0")
                            .select("keyword,date_hour")
                            .ge("date_hour", formatSearch)
                            .eq("keyword", keyword.getKeyword())
                            .orderByDesc("date_hour")
                            .last("limit 1"));

### 重现步骤(如果有就写完整)
定时器1分钟调用这个sql的时候就报错

### 报错信息

 Error evaluating expression 'ew.nonEmptyOfEntity and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: nonEmptyOfEntity
![QQ截图20230721105656](https://github.com/baomidou/mybatis-plus/assets/109937873/650e5600-adb6-4bfc-8664-5744c51541a9)

**Comment by qmdx** [comment]
你编译下当前源码试试，应该解决了这个问题

**Comment by usermrchen** [comment]
好的
