### ISSUE TITLE
mp 缺失两个功能

### ISSUE THREAD

**Issue by yuhou615** [baomidou/mybatis-plus#5492]
### 当前使用版本(必填,否则不予处理)
<version>3.5.3.1</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

缺失功能 1:

@TableField(typeHandler = FastjsonTypeHandler.class) 
不支持fastjson2

缺失功能 2:

PostgreSQL  字段类型jsonb格式，表操作的时候，sql语句不对。

### 重现步骤(如果有就写完整)

因为是功能缺失，只需要做这样的操作就会报错。

### 报错信息

因为是功能缺失，只需要做这样的操作就会报错。

希望早点加上这两个功能

**Comment by miemieYaho** [comment]
没有
