### ISSUE TITLE
LambdaQueryWrapper的eq方法可以对比任意两个Object，导致查询数据错误

### ISSUE THREAD

**Issue by Minghan1992** [baomidou/mybatis-plus#5493]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
看v3.5.3.1的eq方法也是同样的逻辑
LambdaQueryWrapper 的eq方法未对对比值校验类型，直接传入Object。
在版本3.4.2的具体方法：val值传入的类是Object，未与R column做类的类型校验，导致Enum可等于Integer的方式传入。
    /**
     * ignore
     */
    default Children eq(R column, Object val) {
        return eq(true, column, val);
    }

### 重现步骤(如果有就写完整)
任意值可传入，未校验。
如Enum可等于Integer

### 报错信息
数据库查询未找到想要的数据

**Comment by miemieYaho** [comment]
那是你的事
