### ISSUE TITLE
代码生成器中所有 InjectConfig.TableInfo.TableField.type 为 null

### ISSUE THREAD

**Issue by 1104340845** [baomidou/mybatis-plus#5496]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator 3.5.3

### 重现步骤(如果有就写完整)
1

### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/74954382/4635f1f1-532d-4ce6-bb42-20257e8f6cf9)

**Comment by nieqiurong** [comment]
用columnType

**Comment by qmdx** [comment]
up

**Comment by 1104340845** [comment]
不行，我想要判断是否是json

**Comment by 1104340845** [comment]
旧版是可以使用的，新版这个字段全为 null 了

**Comment by qmdx** [comment]
> 不行，我想要判断是否是json

具体需求还是不太明白， MetaInfo 是可以读取到 jdbc 真是类型，你可以做任何事情

**Comment by 1104340845** [comment]
> 
我想要在 entity 对应的字段上加上对应的 json 类型解析器, MetaInfo 里面没有 json 格式

**Comment by qmdx** [comment]
新版本默认使用 jdbc 获取类型方式，你可以databaseConfig 配置设置 dbQuery 为对应数据库类型处理查询类试下
