### ISSUE TITLE
请问一下mybatis-plus支不支持联合主键？

### ISSUE THREAD

**Issue by duanguangchen** [baomidou/mybatis-plus#5497]
### 当前使用版本(必填,否则不予处理)
v3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请问一下mybatis-plus支不支持联合主键？

**Comment by miemieYaho** [comment]
不支持

**Comment by qmdx** [comment]
MP 推崇的是每张表都必须有物理主键 ID ，如果存在这种情况的表你可以主键复合主键任意 ID 注解，但是 byId 方法无法使用
