### ISSUE TITLE
请问pgsql的json数组作为条件改如何查询？

### ISSUE THREAD

**Issue by cat0i** [baomidou/mybatis-plus#5498]
实体的字段
![image](https://github.com/baomidou/mybatis-plus/assets/41892758/314debca-38d2-452a-8594-87d176b81992)
数据库对应的字段，和字段值
![image](https://github.com/baomidou/mybatis-plus/assets/41892758/4d4319e1-d497-4d97-9761-f77d7fb10ecb)
![image](https://github.com/baomidou/mybatis-plus/assets/41892758/595fda33-3140-44e4-af32-959dc838e421)
请问怎么根据提供值（admin,common）来去查询数据库包含我提供值的结果呢？
搜了很多，好像都无法实现。
目前采用了一种很呆呆的写法，请问mybatis-plus有集成pgsql的json条件查询什么的吗？
![image](https://github.com/baomidou/mybatis-plus/assets/41892758/6282562b-691a-4975-91a9-8c5deb4300be)

**Comment by miemieYaho** [comment]
没有,你现在的用法是对的
