### ISSUE TITLE
请问租户偶发性失效为什么？

### ISSUE THREAD

**Issue by q2444113093** [baomidou/mybatis-plus#5499]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
是这样的，当系统使用一段时间后，固定的线程就会出现租户失效。失效后所有的sql都没有加上租户导致看见全部数据。
其中配置如下：
![image](https://github.com/baomidou/mybatis-plus/assets/39699354/ccbf73f9-960e-47aa-977d-3e8727a310c1)
SecurityUtils.getTenantId() 是获取 springsecurity 中上下文信息，是通过token在redis中获取
![image](https://github.com/baomidou/mybatis-plus/assets/39699354/cf9980c9-745a-4e5d-b162-f3d00ad8ee5d)
现在问题是什么情况造成的失效，并且什么样的租户id会导致查询所有数据呢？

**Comment by dengliming** [comment]
之前碰到是因为有些地方手动设置忽略租户，忘了清理导致线程复用有问题。

**Comment by qmdx** [comment]
当前提供代码无法定位您的具体问题，如果错误或者发现并找到原因，欢迎重新打开分享

**Comment by TOP-LH** [comment]
我也会这样，你的问题好了吗？
