### ISSUE TITLE
Mybatis-Plus空字符串不查询怎么设置

### ISSUE THREAD

**Issue by sdjkjkjjk** [baomidou/mybatis-plus#55]
Mybatis-Plus空字符串不查询怎么设置

**Comment by qmdx** [comment]
1、结果集无法预知为空字符串，如果你想指定查询字段可以自定义 sql 或者 wrapper.setSqlSelect("字段1 ， 字段2， .... ")

2、查询字段判断 空 可以设置全局查询策略为非空。
