### ISSUE TITLE
springboot 3x AOT 支持问题

### ISSUE THREAD

**Issue by z744489075** [baomidou/mybatis-plus#5506]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
开发者好,spring boot3X 引入的AOT原生编译目前mybatis已经支持. 请问mybatis-plus是否有支持的计划呢. 感谢

**Comment by nieqiurong** [comment]
#5527  统一至此处讨论.
