### ISSUE TITLE
无法删除mysql分区

### ISSUE THREAD

**Issue by IT-yao** [baomidou/mybatis-plus#5508]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
这是xml方法
<delete id="deleteTableByTime">
        alter table ${table} drop partition
        <foreach collection="list" item="partName" separator="," >
            ${partName}
        </foreach>
    </delete>
### 报错信息

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: alter table f_et_anti_cheat_alarm_region_hour drop partition
          
            P_2023070108
         , 
            P_2023070109

**Comment by miemieYaho** [comment]
partition是jsqlparser的关键字,你用了什么插件就注解不走插件

**Comment by IT-yao** [comment]
能具体说下怎么做吗

**Comment by IT-yao** [comment]
添加了@InterceptorIgnore(blockAttack="true")，还是这样

**Comment by miemieYaho** [comment]
你自己看报错是在哪个插件
