### ISSUE TITLE
网页文档白屏

### ISSUE THREAD

**Issue by wangqingyii** [baomidou/mybatis-plus#5509]
### 当前使用版本(必填,否则不予处理)
https://mybatis.plus/guide/generator.html 打开白屏

### 重现步骤(如果有就写完整)
核心文档相关文档点击白屏

### 报错信息
OMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

**Comment by qmdx** [comment]
baomidou.com  之前的那个域名无效了
