### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred 这个warning有计划解决么

### ISSUE THREAD

**Issue by john1337** [baomidou/mybatis-plus#5510]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mybatis-plus加载时会打印WARNING: An illegal reflective access operation has occurred，不知是否有计划去掉，毕竟这是warning信息

**Comment by qmdx** [comment]
jdk 什么版本

**Comment by john1337** [comment]
> jdk 什么版本

jdk11
