### ISSUE TITLE
能麻烦在编译源码jar时进行delombok吗

### ISSUE THREAD

**Issue by Moonzzz** [baomidou/mybatis-plus#5513]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
现在部分使用lombok注解的类，在idea中查看源码时报source code does not match bytecode

### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/46017308/c1be8f6c-7eff-4ce5-9ffa-f82876eaa81f)

**Comment by miemieYaho** [comment]
不能,其他人都是正常的
