### ISSUE TITLE
count超级表，执行过慢

### ISSUE THREAD

**Issue by ETLGRN** [baomidou/mybatis-plus#5520]
### 当前使用版本(必填,否则不予处理)

V3.0.7.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
目前超级表30W数据，子表60个，count超级表，执行时间在7-10S，赶紧很不合理。
表结构如下：
create table ndm_net_info
(
    ts    TIMESTAMP(23) not null
        constraint ts
            primary key,
    speed FLOAT(12, 5
) ,
	in_speed FLOAT(12,5),
	out_speed FLOAT(12,5),
	in_packet_loss FLOAT(12,5),
	out_packet_loss FLOAT(12,5),
	status TINYINT UNSIGNED(4),
	agent_uid VARCHAR(32),
	product_id INT UNSIGNED(11),
	device_id INT UNSIGNED(11),
	idx TINYINT UNSIGNED(4)
);

comment
on table ndm_net_info is 'STABLE';

comment
on column ndm_net_info.agent_uid is 'TAG';

comment
on column ndm_net_info.product_id is 'TAG';

comment
on column ndm_net_info.device_id is 'TAG';

comment
on column ndm_net_info.idx is 'TAG';

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/48743710/605a2102-17ff-4d0c-b300-94334ffbe845)

**Comment by huayanYu** [comment]
解决不了
