### ISSUE TITLE
分页查询传入Page的size参数为-1，报错

### ISSUE THREAD

**Issue by BubblingXuYijie** [baomidou/mybatis-plus#5528]
### 当前使用版本
3.5.3.1

### 该问题是如何引起的？
临时想查询全部数据，按照官方文档的指导，向Page的size字段传入参数-1，但是报错

### 报错信息
mybatisPlus没有处理size为-1的情况，而把-1直接拼接在了sql的limit=后面，导致sql报错

**Comment by miemieYaho** [comment]
无法复现.给出你的demo以git形式

**Comment by lidy669** [comment]
就是mybatisPlus在3.5版本后不能处理不进行分页全部查询处理，之前的Page的size字段传入参数-1即可，现在不行了，会报错

**Comment by lidy669** [comment]
> 无法复现.给出你的demo以git形式
Page的size字段传入参数-1

**Comment by lidy669** [comment]
> 无法复现.给出你的demo以git形式

就是mybatisPlus在3.5版本后不能处理当Page的size字段传入参数-1时进行全部查询，这个我们也遇到了。

**Comment by miemieYaho** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/28334419/11f877f3-bc14-41bb-91b2-0d468345c104)
你们是配置了`page.maxLimit()`还是`插件.maxLimit`?

**Comment by BubblingXuYijie** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/45624106/3f340dd4-d1db-4979-9c0a-fbebf841886f)
![image](https://github.com/baomidou/mybatis-plus/assets/45624106/ba1980f7-d404-4877-ac79-bce6897c5842)

关于mybatisPlus的配置只有这么一点，然后配置了多数据源，这是sessionFactory的配置

**Comment by BubblingXuYijie** [comment]
插件里面设置了maxLimit

**Comment by BubblingXuYijie** [comment]
插件里面设置了maxLimit，去掉就可以了

**Comment by lidy669** [comment]
好的，我看一下，谢谢
