### ISSUE TITLE
设置QueryWrapper排序字段时会在sql排序前多一个and

### ISSUE THREAD

**Issue by zhujujun** [baomidou/mybatis-plus#553]
### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

创建QueryWrapper对象并设置排序规则就会出现，sql语句打印发现order by前面多一个and 原来在and后面有1=1 现在最新版本去掉 就出现问题了

**Comment by qmdx** [comment]
给出重现代码

**Comment by zhujujun** [comment]
BaseDomain baseDomain=new BaseDomain();
QueryWrapper<BaseDomain> queryWrapper=new QueryWrapper<BaseDomain>(baseDomain).
    			orderByAsc("字段1","字段2");
List<BaseDomain > list=list(queryWrapper);

**Comment by Caratacus** [comment]
可以了 感谢反馈

**Comment by miemieYaho** [comment]
使用 3.0.6-SNAPSHOT 快照版本
