### ISSUE TITLE
3.5.1  sqlserver savebatch 插入时 SQLServerException: 必须执行该语句才能获得结果

### ISSUE THREAD

**Issue by zhuweimin1994** [baomidou/mybatis-plus#5533]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

sqlserver savebatch 插入时 SQLServerException: 必须执行该语句才能获得结果

自动回填id的时候，是否可以自定义是否要回填id

**Comment by qmdx** [comment]
sqlserver 驱动的问题，它是不支持批量返回 id 的

**Comment by Dragns** [comment]
目前可以设置不回填id吗?不然sqlserver主键自增批量操作就报错

**Comment by qmdx** [comment]
> 目前可以设置不回填id吗?不然sqlserver主键自增批量操作就报错

你可以考虑 for 循环 insert 不要直接调用默认的 saveBatch
