### ISSUE TITLE
建议LambdaUpdateChainWrapper增加字段自增自减功能

### ISSUE THREAD

**Issue by hailin84** [baomidou/mybatis-plus#5536]
### 当前使用版本(必填,否则不予处理)
3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
缺少功能

### 重现步骤(如果有就写完整)
想实现类似的效果
update wallet set money = money + 1000 where id = 1
update wallet set money = money - 1000 where id = 1
找到一个类似的PR，但是并没有合并进来：
https://github.com/baomidou/mybatis-plus/pull/4379

### 报错信息
无

**Comment by miemieYaho** [comment]
wrapper.setSql("money = money + 1000")

**Comment by hailin84** [comment]
> wrapper.setSql("money = money + 1000")

后面那1000是参数传进来的呢，就是觉得拼Sql语句不太优雅。大佬考虑下哈。
