### ISSUE TITLE
升级mybatis-plus到3.5.3.1和JSQLParser 从4.3升级到4.6版本引起的插入问题

### ISSUE THREAD

**Issue by nbacheng** [baomidou/mybatis-plus#5537]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用JSQLParser 4.6版本

### 重现步骤(如果有就写完整)
使用标准的保存数据
com.baomidou.mybatisplus.extension.service.IService<T>
   default boolean save(T entity) {
        return SqlHelper.retBool(getBaseMapper().insert(entity));
    }
出现下面错误
JSQLParser Version 4.6:mysql5.7 ParseException: Encountered unexpected token: "\n\n\n" <ST_SEMICOLON> (Issue #1842)
提给JSQLParser，他们的回答如下：
We know that MyBatis inserts 2 empty lines into the statements and we suggest to fix it upstream in their software.
Its a MyBatis problem, not a problem of JSQLParser.
### 报错信息

JSQLParser Version 4.6:mysql5.7 ParseException: Encountered unexpected token: "\n\n\n" <ST_SEMICOLON> (Issue #1842)

**Comment by nieqiurong** [comment]
#5345
