### ISSUE TITLE
新特性意见：`Compare` 接口添加比如 `eqIfNonNull` 系列的默认方法

### ISSUE THREAD

**Issue by Deycoesr** [baomidou/mybatis-plus#5538]
比如在这里：
https://github.com/baomidou/mybatis-plus/blob/7f3a9e47605cd78ea5b68ae5a88c9919adfdc6f8/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/conditions/interfaces/Compare.java#L79-L96
追加一个 `eqIfNonNull` 方法：
```java
default Children eqIfNonNull(R column, Object val) {
    return eq(Objects.nonNull(val), column, val);
}
```
这样就可以像这样去使用：
<img width="938" alt="Screenshot" src="https://github.com/baomidou/mybatis-plus/assets/33995808/9aed2ad8-b19f-4813-b940-d425fa62ca41">
一个常规的分页查询就可以非常方便的实现

**Comment by qmdx** [comment]
底层已经提供条件判断了，如果支持 notNull 还有 notEmpty 支持不过来，而且会很乱，建议用户自行需要拓展
