### ISSUE TITLE
insertBatch 在sqlserver2016上报异常

### ISSUE THREAD

**Issue by cqliuys** [baomidou/mybatis-plus#554]
使用的mybatis-plus-boot-starter 2.3版本 进行批量插入(insertBatch), 主键为自增时报错 ，如果是自定义的则可以。异常信息：Cause: org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: com.microsoft.sqlserver.jdbc.SQLServerException: The statement must be executed before any results can be obtained. at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:255) at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:135)

**Comment by qmdx** [comment]
建议使用 idwork  uui 策略， sql-server 太特每一个版本都不一样没法支持
