### ISSUE TITLE
3.5.3版本分页插件不生效

### ISSUE THREAD

**Issue by SeakyLuo** [baomidou/mybatis-plus#5544]
### 当前使用版本(必填,否则不予处理)
mybatisplus 3.5.3
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3</version>
        </dependency>

已经配置了分页插件，但实际上还是获取到了全量数据

@Configuration
public class DaoConfiguration {

    @Bean
    @Primary
    public SqlSessionFactory sqlSessionFactory(@Qualifier("dataSource") DataSource dataSource) throws Exception {
        MybatisSqlSessionFactoryBean bean = new MybatisSqlSessionFactoryBean();
        bean.setDataSource(dataSource);
        return bean.getObject();
    }

    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new OptimisticLockerInnerInterceptor());
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }

    @Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseGeneratedKeys(false);
    }
}

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java

**Comment by SeakyLuo** [comment]
@miemieYaho 你好，能详细解释下吗，没懂啥意思…

**Comment by miemieYaho** [comment]
照着抄

**Comment by SeakyLuo** [comment]
> 照着抄

这个我注入了试了下不行，而且mybatisplus包里自带的MybatisPlusAutoConfiguration也已经注入了，但还是获取到的全量数据 @miemieYaho

**Comment by SeakyLuo** [comment]
@akuma @asdfgh @clevertension 请问能解答下吗

**Comment by SeakyLuo** [comment]
找到原因了，加入了不该加入的bean，精简一下即可

`
@Configuration
public class DaoConfiguration {

    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new OptimisticLockerInnerInterceptor());
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }

}
`
