### ISSUE TITLE
瀚高数据库分页报错

### ISSUE THREAD

**Issue by wanting0210** [baomidou/mybatis-plus#5550]
### 当前使用版本(必填,否则不予处理)

3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

springboot集成了mybatis-plus 3.5.3版本，分页时报错Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.metadata.IPage.countId()Ljava/lang/String;

### 重现步骤(如果有就写完整)

集成后将springboot打包成war包，部署到tomcat等web容器中就会报错，打包成jar或直接运行springboot程序时都不报错

### 报错信息

Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.metadata.IPage.countId()Ljava/lang/String;

**Comment by qmdx** [comment]
你看看 tomcat 什么情况导致 `com.baomidou.mybatisplus.core.metadata.IPage.countId()Ljava/lang/String` 异常，打印执行 SQL 如果是正确的，那么与 MybatisPlus 无关请自行解决

**Comment by wanting0210** [comment]
> 你看看 tomcat 什么情况导致 `com.baomidou.mybatisplus.core.metadata.IPage.countId()Ljava/lang/String` 异常，打印执行 SQL 如果是正确的，那么与 MybatisPlus 无关请自行解决

SQL并未打印，就直接报出该错误

**Comment by wanting0210** [comment]
另外就是不只tomcat会报错，使用中间件东方通进行部署，也会报错

**Comment by miemieYaho** [comment]
检查你的mp依赖版本冲突

**Comment by wanting0210** [comment]
> 检查你的mp依赖版本冲突

好的，已检查，并找到了问题所在，麻烦了，谢谢
