### ISSUE TITLE
分页不设置数据源类型,无法区分sqlserver2012还是sqlserver2005

### ISSUE THREAD

**Issue by whiteppure** [baomidou/mybatis-plus#5556]
### 当前使用版本(必填,否则不予处理)
V3.5.3  sqlserver2012 不设置分页插件(MybatisPlusInterceptor#PaginationInnerInterceptor)的数据源类型的时候区分存在问题, 不知道是项目设置的sqlserver jdbc-url的问题还是框架的bug

项目数据库配置:
```
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://ip:port;DatabaseName=xxx
          username: xxx
          password: xxx
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最新版3.5.3.1存在该问题

区分sqlserver版本存在问题,无法区分sqlserver2012还是sqlserver2005

### 重现步骤(如果有就写完整)
调用链:PaginationInnerInterceptor.beforeQuery -> PaginationInnerInterceptor.findIDialect -> JdbcUtils.getDbType(Executor) -> JdbcUtils.getDbType(String)

**Comment by miemieYaho** [comment]
你有好的区分方法吗?

**Comment by whiteppure** [comment]
在获取数据库连接(Connection) 对象的时候可以拿到版本属性,可以通过版本属性来判断

- SQL Server 2000: 版本号为8.x
- SQL Server 2005: 版本号为9.0.x
- SQL Server 2008: 版本号为10.0.x
- SQL Server 2008 R2: 版本号为10.5.x
- SQL Server 2012: 版本号为11.x
- SQL Server 2014: 版本号为12.x
- SQL Server 2016: 版本号为13.
- SQL Server 2017: 版本号为14.x
- SQL Server 2019: 版本号为15.x

> 你有好的区分方法吗?

**Comment by miemieYaho** [comment]
代码是如何?可有debug截图?

**Comment by whiteppure** [comment]
![B94ACE77-A245-4465-97E9-DC221EACD38D](https://github.com/baomidou/mybatis-plus/assets/51473016/3583066a-976b-4a7a-b407-a318055c7399)

![CCC27D0F-2BC8-48c2-9DD5-F1068A908C0D](https://github.com/baomidou/mybatis-plus/assets/51473016/4e8870d1-4017-4a6b-9751-911b8300b1d1)

**Comment by whiteppure** [comment]
亲 @miemieYaho 啥时候能修改啊  还是你们觉得没必要修改

**Comment by qmdx** [comment]
> 亲 @miemieYaho 啥时候能修改啊 还是你们觉得没必要修改

你可以自定义下方言参考文档 https://baomidou.com/pages/97710a/#%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E5%BA%93

SQLServer 目前已经有 2 个方言版本内置了，每个版本的分页竟然都不一样我们也很无语，没法全部版本都支持到 。

建议自己实现方法注入即可，感谢支持！！

**Comment by rayliang123** [comment]
自己写一个拦截器来对DbType进行赋值就可以了


程序如下

public class QueryChangeDbTypeInterceptor implements QueryInterceptor {

	DynamicDataSourceDbTypeProperties dynamicDataSourceDbTypeProperties;
	DynamicDataSourceProperties dynamicDataSourceProperties;

	public QueryChangeDbTypeInterceptor(DynamicDataSourceDbTypeProperties dynamicDataSourceDbTypeProperties,DynamicDataSourceProperties dynamicDataSourceProperties) {
		this.dynamicDataSourceDbTypeProperties = dynamicDataSourceDbTypeProperties;
		this.dynamicDataSourceProperties = dynamicDataSourceProperties;

	}


	@Override
	public void intercept(Executor executor, MappedStatement ms, Object parameter, RowBounds rowBounds, ResultHandler resultHandler, BoundSql boundSql) {
		if (dynamicDataSourceProperties == null || dynamicDataSourceDbTypeProperties == null || dynamicDataSourceDbTypeProperties.getDatasource().size() == 0)
			return;
		String ds = DynamicDataSourceContextHolder.peek();
		BladePaginationInterceptor bladePaginationInterceptor = SpringUtil.getBean(BladePaginationInterceptor.class);
		if (Objects.nonNull(bladePaginationInterceptor)) {
			bladePaginationInterceptor.setDbType(null);
			if (StringUtil.isBlank(ds)) {
				ds = dynamicDataSourceProperties.getPrimary();
			}
			DbTypeValue dialetValue = dynamicDataSourceDbTypeProperties.getDatasource().get(ds);
			if (dialetValue != null) {
				String dbTypeStr = dialetValue.getDbType();
				DbType dbType = DbType.getDbType(dbTypeStr);
				if (dbType != null) {
					bladePaginationInterceptor.setDbType(dbType);
				}
			}
		}
	}
	@Override
	public int getOrder() {
		return Integer.MIN_VALUE;
	}
}


这样就可以通过配置来设置dbtyp，从而分页插件通过不同dbtype来选择不同的分页sql

![Image](https://github.com/user-attachments/assets/1e713277-b557-4fa3-a700-c7e94f54afdc)
