### ISSUE TITLE
升级mybatisplus版本3.5.3.1报错 java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.injector.AbstractMethod: method 'void <init>()' not found

### ISSUE THREAD

**Issue by 15281753095** [baomidou/mybatis-plus#5563]
### 当前使用版本(必填,否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.2</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
因为公司的snyk扫描出了，说3.5.2版本有sql注入问题。所以必须强制升级版本。然后我
将mybatisplus版本从<version>3.5.2</version>升级到<version>3.5.3.1</version> 项目能编译。但是不能启动成功。
Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.injector.AbstractMethod: method 'void <init>()' not found
### 重现步骤(如果有就写完整)
经过测试
 <version>3.5.2</version>正常使用
<version>3.5.1</version>正常使用
<version>3.5.0</version>正常使用
  <version>3.5.3.1</version> 报错。不能启动项目
<version>3.5.3.2</version> 报错。不能启动项目

### 报错信息
Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.injector.AbstractMethod: method 'void <init>()' not found

**Comment by qmdx** [comment]
能否给出重新问题 demo 使用最新版本

**Comment by 15281753095** [comment]
已经找到问题，发现是依赖的 mybatisplus-plus版本没有升级。什么时候mybatisplus能支持联合主键呀<dependency>
            <groupId>com.github.jeffreyning</groupId>
            <artifactId>mybatisplus-plus</artifactId>
            <version>1.7.4-RELEASE</version>
        </dependency>

**Comment by miemieYaho** [comment]
没有支持联合主键的计划

**Comment by 15281753095** [comment]
> 没有支持联合主键的计划

emmm,为什么呢。
