### ISSUE TITLE
page分页查询，size<0，分页查询可以查询到全部数据，但是total没有赋值，我需要优化这个功能。

### ISSUE THREAD

**Issue by Yasin4040** [baomidou/mybatis-plus#5566]
### 当前使用版本(必填,否则不予处理)
mybatis最新版。

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我想直接使用page分页的查询方法。
当输入，pageSize<0时，能查询到总数。但是total为0.能不能将total赋值？

### 报错信息
total为0，需要手动赋值。可以优化这个问题啊？或者新增优化

**Comment by huayanYu** [comment]
设计如此.
