### ISSUE TITLE
MetaSpace持续增长

### ISSUE THREAD

**Issue by jhsrcmh** [baomidou/mybatis-plus#557]
### 版本3.0.5
Spring Boot 2.0.3.RELEASE
Spring Cloud Finchley.BUILD-SNAPSHOT

### MetaSpace持续增长
设置元空间大小为128M，线上应用运行一段时间，产生dump, dump详见附件：
[java_pid17759_Leak_Hunter.zip](https://github.com/baomidou/mybatis-plus/files/2475009/java_pid17759_Leak_Hunter.zip)

### 重现步骤
设置元空间大小为128M，持续执行Sql即可。

## 报错信息
java.lang.OutOfMemoryError: Metaspace
Dumping heap to java_pid17759.hprof ...
Heap dump file created [95644501 bytes in 0.803 secs]

**Comment by jhsrcmh** [comment]
使用MAT检查泄漏点时，截图如下：
<img width="640" alt="screen shot 2018-10-13 at 10 52 39" src="https://user-images.githubusercontent.com/1079658/46900527-1f678000-ced6-11e8-9516-03dcaa2a35e0.png">

**Comment by qmdx** [comment]
给否给出具体优化方案？

**Comment by coolskyman** [comment]
本人遇到同样的问题。MAT发现是com.baomidou.mybatisplus.toolkit.SystemClock无法回收导致

**Comment by coolskyman** [comment]
询问过QQ群里的人。说是，有空才能看是什么原因。如果可以，还是切回原生的mybatis吧

**Comment by yuxiaobin** [comment]
这个SystemClock就是无法被回收，设置了Daemon=true
因为需要一直更新当前时间，具体请查看注解
