### ISSUE TITLE
lambdaQuery() Unchecked generics array creation for varargs parameter 

### ISSUE THREAD

**Issue by refeccd** [baomidou/mybatis-plus#5571]
### 当前使用版本(必填,否则不予处理)

3.5.3.2

### 报错信息

<img width="646" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/26990889/a23a508d-2d13-4771-a05d-2074a3cd5509">

**Comment by refeccd** [comment]
补充：如果想让idea不提示，需要使用 `com.baomidou.mybatisplus.core.conditions.query.Query#select(java.util.List<R>)`
<img width="516" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/26990889/cf41be44-e70a-46e3-a5f0-626612a021f8">

**Comment by nieqiurong** [comment]
#5572  统一至此处讨论.
