### ISSUE TITLE
Unchecked generics array creation for varargs parameter 

### ISSUE THREAD

**Issue by nieqiurong** [baomidou/mybatis-plus#5572]
处理LambdaQueryWrapper与LambdaQueryChainWrapper警告.
涉及如下API:
1. select(R...)
2. select(boolean, R...)
3. orderBy(boolean, boolean, R, R...)
4. orderBy(boolean, boolean, R, R...)
5. orderByAsc(R, R...)
6. orderByAsc(boolean, R, R...)
7. orderByDesc(R, R...)
8. orderByDesc(boolean, R, R...)
9. groupBy(R, R...)
10. groupBy(boolean, R, R...)

统计是否有重写此方法的开发者,后期大版本可能在两个类中将上述方法置为final.

#3720 #3230  #2870 #720  #467

**Comment by refeccd** [comment]
正常情况下，应该不会重写这类方法。反正我司没重写

**Comment by nieqiurong** [comment]
> 正常情况下，应该不会重写这类方法。反正我司没重写

先用这个版本试试看看  3.5.4-SNAPSHOT ,下载解压至本地仓库,后面再跟进此问题.

链接：https://pan.baidu.com/s/1ewwvQlLDCO0d8UVJeE6k7w 
提取码：rzwo

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/2f3466d2-a62a-4d40-ab43-6d0eb52d8919)

**Comment by refeccd** [comment]
什么时候会release？

**Comment by nieqiurong** [comment]
> 什么时候会release？

已经发了3.5.4-SNAPSHOT
