### ISSUE TITLE
高版本JDK下lambda无法执行IDEA调试

### ISSUE THREAD

**Issue by zongyanglaobiao** [baomidou/mybatis-plus#5573]
### 当前使用版本(必填,否则不予处理)

mybatis-plus-boot-starter 版本 3.5.3.1
springboot 3.0.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

查询(select)时

### 重现步骤(如果有就写完整)

简单查询

### 报错信息

org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.reflect.InaccessibleObjectException: Unable to make field final java.lang.invoke.MethodHandle java.lang.invoke.MethodHandleProxies$1.val$target accessible: module java.base does not "opens java.lang.invoke" to unnamed module @3cef309d]

**Comment by nieqiurong** [comment]
提供完整点的错误日志,顺便切换到3.5.3.2试试看看.

**Comment by nieqiurong** [comment]
看着可能是IDEA调试支持的问题

**Comment by zongyanglaobiao** [comment]
好的谢谢，那我的IDEA需要设置什么嘛






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月12日(星期六) 晚上10:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/mybatis-plus] MyBatis建造查询时评估OGNL表达式时出错,具体的原因是反射访问了java.lang.invoke.MethodHandle这个类的一个字段,但是由于模块访问限制导致了IllegalAccessException。 (Issue #5573)





 
看着可能是IDEA调试支持的问题

**Comment by nieqiurong** [comment]
> 好的谢谢，那我的IDEA需要设置什么嘛
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月12日(星期六) 晚上10:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [baomidou/mybatis-plus] MyBatis建造查询时评估OGNL表达式时出错,具体的原因是反射访问了java.lang.invoke.MethodHandle这个类的一个字段,但是由于模块访问限制导致了IllegalAccessException。 (Issue #5573) 看着可能是IDEA调试支持的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

先开发时增加VM参数. --add-opens=java.base/java.lang.invoke=ALL-UNNAMED

![image](https://github.com/baomidou/mybatis-plus/assets/15142701/2a6a4ac8-f92d-44db-90fd-95c37df49ac7)

**Comment by nieqiurong** [comment]
下载切换到这个版本试试看看 3.5.4-SNAPSHOT.

链接：https://pan.baidu.com/s/1KN9EXtzdoKBvl6vSRKKicA 
提取码：lvc3
