### ISSUE TITLE
希望Wrapper 全部增加忽略逻辑删除的功能

### ISSUE THREAD

**Issue by shangzp** [baomidou/mybatis-plus#5574]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

逻辑删除问题

### 重现步骤(如果有就写完整)

能不能在所有的Wrapper加上可以控制忽略逻辑删除字段的功能？好多issues 提啊。
目前遇到一个场景，需要根据某个字段查询出所有的数据（包括逻辑删除的），然后做某些处理后，做updateBatchById 操作，将已经逻辑删除的is_deleted设置为false, 但是这时候updateBatchById 里面会加is_deleted = true 导致更新失败。这个场景是客户刚提的，如果直接去掉is_deleted 不再使用，需要整个项目都要更改代码，很不方便。

**Comment by shangzp** [comment]
另外主要是还是想用mybatis-plus的Entity，自己写更新sql的时候以后表如果增减字段还需要来维护这个更新sql

**Comment by huayanYu** [comment]
这个是规范问题.
如果你要查出来的,建议用状态字段,而不是逻辑删除. 
个性化需求写几个xml也很简单.
