### ISSUE TITLE
添加多租户插件后saveOrUpdateBatch无法自动添加tenant_id的值

### ISSUE THREAD

**Issue by zhangzhi0111** [baomidou/mybatis-plus#5579]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

添加 多租户插件后      interceptor.addInnerInterceptor(tenantLineInnerInterceptor);

批量添加无法补全对象中的tenant_id值，单个添加可以
### 重现步骤(如果有就写完整)

1.mybatis配置文件中添加        interceptor.addInnerInterceptor(tenantLineInnerInterceptor);
2.调用saveOrUpdateBatch（List<Entity>）批量添加数据到mysql
3.查看数据库表Entity的tenant_id为空
4.如果调用save（）方法则可以自动补全tenant_id的值

### 报错信息
无报错信息

**Comment by nieqiurong** [comment]
提供一下执行SQL语句debug日志.

**Comment by nieqiurong** [comment]
提供日志再打开
