### ISSUE TITLE
关于 @TableField(fill = FieldFill.INSERT_UPDATE, update = "now()") 插入时无效，更新时正常

### ISSUE THREAD

**Issue by whoooami** [baomidou/mybatis-plus#558]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.4

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
实体配置
@TableField(fill = FieldFill.INSERT, update = "now()")
	private Date createTime;
	private String status;
	//todo
	@TableField(fill = FieldFill.INSERT_UPDATE, update = "now()")
	private Date updateTime;

=====

[2018-10-13 17:55:05][http-nio-8080-exec-1]:[DEBUG] [insert][159] - ==>  Preparing: INSERT INTO little_note ( create_time, status, update_time, ed_id, er_id, message, type ) VALUES ( ?, ?, ?, ?, ?, ?, ? ) 
[2018-10-13 17:55:05][http-nio-8080-exec-1]:[DEBUG] [insert][159] - ==> Parameters: null, AC(String), null, 1(Integer), 2(Integer), msgC(String), 1(Integer)
[2018-10-13 17:55:05][http-nio-8080-exec-1]:[DEBUG] [insert][159] - <==    Updates: 1

=======
mysql> select * from little_note order by id desc limit 1;
+----+---------------------+--------+-------------+-------+-------+---------+------+
| id | create_time         | status | update_time | ed_id | er_id | message | type |
+----+---------------------+--------+-------------+-------+-------+---------+------+
|  6 | 2018-10-13 17:55:05 | AC     | NULL        |     1 |     2 | msgC    |    1 |
+----+---------------------+--------+-------------+-------+-------+---------+------+
### 重现步骤

直接保存

### 报错信息

无

**Comment by miemieYaho** [comment]
去看文档,不是你这么玩的

**Comment by whoooami** [comment]
不好意思，没太理解 。
我知道这个另一种方式是要实现 MetaObjectHandler ，然后设置值。
但是注解
public @interface TableField
中的update字段
 * <p>
     * 例如：@TableField(.. , update="now()") 使用数据库时间
     * 输出 SQL 为：update 表 set 字段=now() where ...
     * </p>
     */
    String update() default "";

请问下这个我的理解有误吗？

**Comment by miemieYaho** [comment]
属性名叫 `update`,只生效于update方法

**Comment by whoooami** [comment]
嗯，谢谢
