### ISSUE TITLE
基于Annotation或者QueryWrapper查询boolean类型的值全部为null

### ISSUE THREAD

**Issue by 1017neroliu** [baomidou/mybatis-plus#5586]
### 当前使用版本(必填,否则不予处理)
3.0.5

### 重现步骤(如果有就写完整)
基于annotation或QueryWrapper的查询：select A.id, A.status from A;或者select * from A;
如果A中存在boolean类型字段，如status，实际库里的值为1或者0，不存在有null值的存在。通过annotation或者QueryWrapper查询
返回的该类型的字段全部为null，使用IService接口中的listByIds返回的值为正常值：true 或 flase

**Comment by miemieYaho** [comment]
用最新版给出你的复现demo
