### ISSUE TITLE
pgsql下，驼峰命名会被转成小写，然后mybatis-plus查询报错

### ISSUE THREAD

**Issue by diy4869** [baomidou/mybatis-plus#5588]
### 当前使用版本(必填,否则不予处理)

mybatis-plus 3.5.3.1
pgsql: 42.6.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/29079700/054bf95f-2e51-4575-bf60-b487e65f4302)

驼峰命名的数据库字段在pgsql下会被转成小写，导致查询的时候会报错，加个双引号就没问题

### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/29079700/054bf95f-2e51-4575-bf60-b487e65f4302)

**Comment by diy4869** [comment]
调用baseMapper下的方法去操作数据库导致的

**Comment by miemieYaho** [comment]
https://baomidou.com/pages/56bac0/#mapunderscoretocamelcase
