### ISSUE TITLE
Transaction not enabled  这个日志输出问题

### ISSUE THREAD

**Issue by caztg** [baomidou/mybatis-plus#5592]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.extension.toolkit.SqlHelper#executeBatch(java.lang.Class<?>, org.apache.ibatis.logging.Log, java.util.function.Consumer<org.apache.ibatis.session.SqlSession>)
这个方法必定会打印这个日志
![image](https://github.com/baomidou/mybatis-plus/assets/26920442/0bf9990b-33bd-41f2-b827-a2d519eda7a3)

### 重现步骤(如果有就写完整)

执行批量操作

### 报错信息
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@22077df5] Transaction not enabled

想要不打印该行sql 有什么好的处理方法，因为我看执行批量操作就一定会打印

**Comment by nieqiurong** [comment]
调用方法上标记事务注解.

**Comment by caztg** [comment]
@nieqiurong 
如果涉及多数据源 好像会有问题。

**Comment by weirhp** [comment]
我也遇到了多数据源下，会有这个信息。但是事务好像还是正常的 ？

**Comment by nieqiurong** [comment]
> @nieqiurong 如果涉及多数据源 好像会有问题。

下版本提供单独方法调用.
