### ISSUE TITLE
3.5.3.2遇到Factory method 'sqlSessionFactory' threw exception with message: ALWAYS

### ISSUE THREAD

**Issue by zhangYHBox** [baomidou/mybatis-plus#5598]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
将版本3.5.3.1 升级到3.5.3.2
启动运行报错，参数配置都没变，3.5.3.1 正常，3.5.3.2报错

### 重现步骤(如果有就写完整)
在parse mapper file 阶段报错

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/32611410/13bf3de6-40a5-44c6-8524-2697890d1502)

![image](https://github.com/baomidou/mybatis-plus/assets/32611410/08ab0226-2ca3-4d1b-b8dc-5b7c2cb5b933)

**Comment by miemieYaho** [comment]
检查你版本依赖是否冲突

**Comment by lansyy** [comment]
请问这个是哪个包冲突引起的

**Comment by VampireAchao** [comment]
安装Maven Helper插件：
<img width="997" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/52746628/80df14a5-5bc3-4876-a87a-9698ae803249">

在你的pom.xml下面找到这个，点击`Dependency Analyzer`
<img width="495" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/52746628/6a3483f1-e2a4-4aa0-8bf1-d7a72475e763">

选择冲突

<img width="628" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/52746628/c70ad5d7-5c16-4daf-b3d4-9643741e53fd">

这里就是你冲突的包

<img width="516" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/52746628/a3ff7322-1537-48a2-93fd-ff655441f8a2">
