### ISSUE TITLE
使用逻辑删除时，SQL拼出两个WHERE，导致查询报错

### ISSUE THREAD

**Issue by suye1234** [baomidou/mybatis-plus#56]
WHERE  is_deleted=0  WHERE (merchant_no = ? AND is_enabled = ?)

使用下面这种情况时，会出现这个问题：

 Wrapper<Merchant> wrapper = new EntityWrapper<Merchant>();

wrapper.eq("merchant_no", merchantNo);
wrapper.eq("is_enabled", EnableStatus.ENABLED.getIntValue());

selectOne(wrapper);

**Comment by willenfoo** [comment]
群里文件中，有逻辑删除的视频讲解， 或者在优酷上看视频 http://v.youku.com/v_show/id_XMjc4ODY0MDI5Ng==.html?spm=a2hzp.8244740.userfeed.5!2~5~5~5!3~5~A

**Comment by Caratacus** [comment]
感谢反馈,下个版本会处理.

**Comment by Caratacus** [comment]
已处理
