### ISSUE TITLE
type-enums-package在spring-boot-devtools下出现失效

### ISSUE THREAD

**Issue by zx472010602** [baomidou/mybatis-plus#561]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
type-enums-package属性设置的枚举包后，如果项目使用了spring-boot-devtools依赖，会生成一个restart classloader，在mybatis的org.apache.ibatis.type.TypeHandlerRegistry的
TYPE_HANDLER_MAP.get(type)行,type为restart classloader加载的枚举,typeHandlerRegistry内存储的为App classloader加载的枚举,所以获取值为null,会使用mybatis默认的typehandler,所以MP的注解及IENUM自动枚举转换都会失效，只会使用mybatis的默认的，该场景在使用type-handlers-package自定义枚举转换时，不会失效，可以正常运行

### 重现步骤
引用spring-boot-devtools依赖，并使用type-enums-package扫描继承自IENUM下的枚举或注解属性，无效报错，无法枚举转换

**Comment by miemieYaho** [comment]
那就不要用 spring-boot-devtools

**Comment by VanHelxing** [comment]
> 那就不要用 spring-boot-devtools

3.1.2 还是存在该问题，是不打算列为issue处理吗

**Comment by qmdx** [comment]
没有打算支持 devtools
