### ISSUE TITLE
DataChangeRecorderInnerInterceptor拦截器sql执行失败也会执行dealOperationResult方法打印日志

### ISSUE THREAD

**Issue by liufengvling** [baomidou/mybatis-plus#5610]
怎么做到真正数据库变更了再获取变更记录，或者获取operationResult的同时获得数据库变更执行成功结果？

### 当前使用版本(必填,否则不予处理)

3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

dealOperationResult方法在执行之前已经执行
数据库为db2，当执行insert字符串超长报错SQLSTATE=22001.

**Comment by huayanYu** [comment]
没啥办法,你可以按照自己思路改插件..
