### ISSUE TITLE
自动填充功能 MetaObjectHandler,先查询（getById）后更新（updateById）导致更新的时候把创建时间也更新

### ISSUE THREAD

**Issue by simplehpt** [baomidou/mybatis-plus#5611]
### 当前使用版本(必填,否则不予处理)

[3.5.1] ~ [3.5.3.2]

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1 先查询调用getById方法 ，然后更新调用updateById方法 导致 更新的时候把创建时间也更新了。
2 如果只调用updateById方法没有此问题

先查询后更新的代码如下：
![image](https://github.com/baomidou/mybatis-plus/assets/5326857/078d63b6-6d4e-448d-a066-2131997ad761)
实体类的配置如下：
![image](https://github.com/baomidou/mybatis-plus/assets/5326857/1bd5259f-eb89-4212-826c-774dea43dcaf)
实现MetaObjectHandler如下：
![image](https://github.com/baomidou/mybatis-plus/assets/5326857/db3553fa-6b26-43be-ac3c-668c795d3778)

### 重现步骤(如果有就写完整)
 1 先查询 2 在修改 

### 报错信息
没有报错，预期结果应该是只更新更新时间，创建时间不需要更新 ； 现状是创建时间和更新时间都更新了

**Comment by simplehpt** [comment]
控制台打印的日志：
![image](https://github.com/baomidou/mybatis-plus/assets/5326857/dd8f2d41-7fb6-4069-9841-6760c539fe04)

**Comment by miemieYaho** [comment]
给出你的复现demo,以git形式

**Comment by miemieYaho** [comment]
你那个字段有值当然要更新了,不想更新就提前setnull
