### ISSUE TITLE
LambdaQueryWrapper 能否支持 判断为NULL 不加入条件查询

### ISSUE THREAD

**Issue by von2017** [baomidou/mybatis-plus#5618]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
  LambdaQueryWrapper<QuoteSupplierDetailPageQueryDto> queryWrapper = Wrappers.lambdaQuery();
        if(ObjectUtil.isNotEmpty(quoteSupplierDetailPageQueryDto.getSupplyName())){
            queryWrapper.like(QuoteSupplierDetailPageQueryDto::getSupplyName, quoteSupplierDetailPageQueryDto.getSupplyName());
        }
        if(ObjectUtil.isNotEmpty(quoteSupplierDetailPageQueryDto.getDetailNo())){
            queryWrapper.like(QuoteSupplierDetailPageQueryDto::getDetailNo, quoteSupplierDetailPageQueryDto.getDetailNo());
        }
        if(ObjectUtil.isNotEmpty(quoteSupplierDetailPageQueryDto.getCreateUser())){
            queryWrapper.like(QuoteSupplierDetailPageQueryDto::getCreateUser, quoteSupplierDetailPageQueryDto.getCreateUser());
        }
        if(ObjectUtil.isNotEmpty(quoteSupplierDetailPageQueryDto.getQuoteStatus())){
            queryWrapper.like(QuoteSupplierDetailPageQueryDto::getQuoteStatus, quoteSupplierDetailPageQueryDto.getQuoteStatus());
        }

### 重现步骤(如果有就写完整)

如上不想对每一个字段进行 ObjectUtil.isNotEmpty操作 
是否能重写LambdaQueryWrapper 进行判null再组装参数的操作

### 报错信息

无报错

**Comment by miemieYaho** [comment]
`queryWrapper.like(ObjectUtil.isNotEmpty(quoteSupplierDetailPageQueryDto.getSupplyName()),QuoteSupplierDetailPageQueryDto::getSupplyName,quoteSupplierDetailPageQueryDto.getSupplyName())`
