### ISSUE TITLE
分模块后无法调用BaseMapper中的方法

### ISSUE THREAD

**Issue by BzCoder** [baomidou/mybatis-plus#562]
MP 3.0.5
在同一个模块下正常使用
但是把Service，Mapper，Entity放到另外一模块（通用模块），就引用不到BaseMapper的方法了
是否是我的使用方法有问题？

**Comment by qmdx** [comment]
可能是配置问题参考 http://mp.baomidou.com/guide/faq.html#%E5%87%BA%E7%8E%B0-invalid-bound-statement-not-found-%E5%BC%82%E5%B8%B8
