### ISSUE TITLE
启用多租户拦截器的情况下，使用insert into ……  select ……

### ISSUE THREAD

**Issue by lshaci** [baomidou/mybatis-plus#5628]
### 重现步骤(如果有就写完整)
insert into table_name (id, name, tenant_id)
select uuid_short(), name, tenant_id
from table_name

### 报错信息
当启用多租户拦截时，拦截器TenantLineInnerInterceptor中执行processInsert，随后调用processInsertSelect；
在执行processInsertSelect中的appendSelectItem时，会拼上租户列，导致sql变成：
insert into table_name (id, name, tenant_id)
select uuid_short(), name, tenant_id, tenant_id
from table_name

### 期望
在执行processInsertSelect中拼接租户列时，先判断selectItems中是否已经存在了租户列

**Comment by huayanYu** [comment]
期望你能直接提PR

**Comment by lshaci** [comment]
ignore
