### ISSUE TITLE
saveOrUpdateBatch方法执行报错

### ISSUE THREAD

**Issue by SwaggyLin** [baomidou/mybatis-plus#5629]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

调用saveOrUpdateBatch方法报错

### 重现步骤(如果有就写完整)

服务运行一段时间会报这个错,如果重启服务器再调用就正常了.
是否跟环境或数据库版本或druid的配置有关?

### 报错信息

<img width="717" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/25942168/3a939c24-f827-43f9-87d8-adabd2c30503">

**Comment by SwaggyLin** [comment]
从3.3.2版本升级到3.4.0版本 也没有解决这个问题 平时也不好复现 到生产了就报错

**Comment by nieqiurong** [comment]
看着应该是获取到SqlSessionFactory为空了,这个要排查一下可能性了,先升级到3.5.3.2,这块有做一部分优化.

**Comment by SwaggyLin** [comment]
> 看着应该是获取到SqlSessionFactory为空了,这个要排查一下可能性了,先升级到3.5.3.2,这块有做一部分优化.

能说下是在具体哪个版本优化的吗,在v3.4.3.3版本由于对count方法做了修改,导致返回类型从int->LONG,代码需要做大面积的修改

**Comment by nieqiurong** [comment]
> Reference in new is

3.5.3.2上面优化的,主要是把SerivceImpl里面的SqlSessionFactory获取改成注入bean的方式了,或者我修改一个你需要的版本编译给你观察看看.

**Comment by nieqiurong** [comment]
> > 看着应该是获取到SqlSessionFactory为空了,这个要排查一下可能性了,先升级到3.5.3.2,这块有做一部分优化.
> 
> 能说下是在具体哪个版本优化的吗,在v3.4.3.3版本由于对count方法做了修改,导致返回类型从int->LONG,代码需要做大面积的修改

3.5.3.2上面优化的,主要是把SerivceImpl里面的SqlSessionFactory获取改成注入bean的方式了,或者我修改一个你需要的版本编译给你观察看看.

**Comment by SwaggyLin** [comment]
> > > 看着应该是获取到SqlSessionFactory为空了,这个要排查一下可能性了,先升级到3.5.3.2,这块有做一部分优化.
> > 
> > 
> > 能说下是在具体哪个版本优化的吗,在v3.4.3.3版本由于对count方法做了修改,导致返回类型从int->LONG,代码需要做大面积的修改
> 
> 3.5.3.2上面优化的,主要是把SerivceImpl里面的SqlSessionFactory获取改成注入bean的方式了,或者我修改一个你需要的版本编译给你观察看看.

可以基于3.4.0版本修改吗 跨这么多版本升级风险有点大

**Comment by nieqiurong** [comment]
> > > > 看着应该是获取到SqlSessionFactory为空了,这个要排查一下可能性了,先升级到3.5.3.2,这块有做一部分优化.
> > > 
> > > 
> > > 能说下是在具体哪个版本优化的吗,在v3.4.3.3版本由于对count方法做了修改,导致返回类型从int->LONG,代码需要做大面积的修改
> > 
> > 
> > 3.5.3.2上面优化的,主要是把SerivceImpl里面的SqlSessionFactory获取改成注入bean的方式了,或者我修改一个你需要的版本编译给你观察看看.
> 
> 可以基于3.4.0版本修改吗 跨这么多版本升级风险有点大

下载这个版本试试看看. 
链接：https://pan.baidu.com/s/1MstGqRnHE2RA34AlNP5dtA 
提取码：ryt0

**Comment by nieqiurong** [comment]
有问题再打开.

**Comment by SwaggyLin** [comment]
确实解决了~谢谢~
