### ISSUE TITLE
3.5.3.2 重写 selectPage 方法导致 Invalid bound statement (not found)

### ISSUE THREAD

**Issue by Charles7c** [baomidou/mybatis-plus#5630]
### 当前使用版本(必填,否则不予处理)

3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

3.5.3.1 不存在此问题，升级后出现此问题。
初步排查是因为 3.5.3.2 selectPage 增加了 default 默认实现。

### 重现步骤(如果有就写完整)

重写 selectPage 接口方法，以添加 @DataPermission 数据权限注解。

```java
public interface UserMapper extends BaseMapper<User> {

    @Override
    @DataPermission
    List<User> selectList(@Param(Constants.WRAPPER) Wrapper<User> queryWrapper);

    @Override
    @DataPermission
    <P extends IPage<User>> P selectPage(P page, @Param(Constants.WRAPPER) Wrapper<User> queryWrapper);
}
```

### 报错信息

Invalid bound statement (not found): xx.xx.xx.mapper.UserMapper.selectPage

**Comment by miemieYaho** [comment]
就这么设计的,你把selectPage删掉就行了

**Comment by miemieYaho** [comment]
把注解加到selectPage和selectList最终调用的method上
