### ISSUE TITLE
Mapper自定义方法

### ISSUE THREAD

**Issue by reixuemin** [baomidou/mybatis-plus#5634]
3.5.3.2的，最新版

咨询个事情，以前公司这边自己实现了一下方法，做法是动态新增mapper的方法，用完就删掉，现在这里的configuration设置为过期了，是有什么风险吗？不能这么操作？为啥会设置过时
![image](https://github.com/baomidou/mybatis-plus/assets/14087655/05ee7108-3a78-4a9b-b0fb-4cd01fb3470b)

**Comment by nieqiurong** [comment]
为了防止后面这方法大量调用,这块地方先标记过时后面会改掉.
如果是spring项目的话,尽量去获取容器中注入的SqlSessionFactory,通过SqlSessionFactory获取getConfiguration
