### ISSUE TITLE
关于mybatis-plus对一对多关系的支持情况求助

### ISSUE THREAD

**Issue by vincentwc** [baomidou/mybatis-plus#5635]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

求助贴：请问mybatis-plus是否支持一对多关系结构的数据保存

### 重现步骤(如果有就写完整)
Dept {
    String id;
    String name;
}
Person {
    String id;
    String deptId;
    String name;
}
如上所述，现在想要同时保存一个部门和n个人员信息，是否支持在同一条sql里面完成该操作，而不是先保存部门，拿到部门id，在把部门id放到人员对象集合，再次入库

**Comment by miemieYaho** [comment]
不能
