### ISSUE TITLE
postgresql使用jsonb字段排序时字段被识别为sql注入

### ISSUE THREAD

**Issue by kevinh458** [baomidou/mybatis-plus#5637]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
  .orderByDesc("jsonb->>'sort'") 
 走了这个方法被识别为sql注入 columnSqlInjectFilter

### 报错信息

是否有其他解决办法，我现在用last解决了
.last( "ORDER BY jsonb->>'sort'")

**Comment by miemieYaho** [comment]
升级
