### ISSUE TITLE
请问贵项目 对springboot 3.X版本的全面支持，大概多久能推出？有没有时间计划节点？

### ISSUE THREAD

**Issue by dujun0909** [baomidou/mybatis-plus#5639]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
# 请问贵项目 对springboot 3.X版本的全面支持，大概多久能推出？有没有时间计划节点？

### 重现步骤(如果有就写完整)
启动springboot 3 时 报错，应该是对springboot 3.X版本的没有全面支持。

### 报错信息
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean  Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
![mybatis plus](https://github.com/baomidou/mybatis-plus/assets/14818244/c38436ab-23b2-4aee-80ce-dd26a8e3250c)

**Comment by miemieYaho** [comment]
你试过最新版吗?

**Comment by dujun0909** [comment]
我试过[3.5.3.2] 依然有这个问题， 这是 mvnrepository.com 所能查到的最新的版本了。原因应该是现在mybatis-plus 依赖的mybatis-spring版本较低，所以比较关心能在何时推出全面支持 springboot 3.X 的版本。毕竟对 JDK17 / Spring6 /springboot 3的支持是大势所趋。

**Comment by miemieYaho** [comment]
mybatis-spring最新版不支持java8,目前mp并没有不支持java8的计划

**Comment by ImmortalLiu** [comment]
目前我司也在升级公司脚手架，也想问问mybatis-plus啥时候全面支持SpringBoot 3，目前SpringBoot 3脚手架使用的mybatis

**Comment by SimonVonXCVII** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/36143469/25e62d49-95de-4a7b-82da-8af6a7915922)
Spring Boot 3.1.3 + Mybatis Plus 3.5.3.2，一般的 CRUD 都没有问题，你们的项目为什么用不了呢

**Comment by Oli51467** [comment]
> ![image](https://user-images.githubusercontent.com/36143469/266310042-25e62d49-95de-4a7b-82da-8af6a7915922.png) Spring Boot 3.1.3 + Mybatis Plus 3.5.3.2，一般的 CRUD 都没有问题，你们的项目为什么用不了呢
我试过了，确实可以。别的版本都不行
