### ISSUE TITLE
Update方法模板生成非空忽略的一点问题

### ISSUE THREAD

**Issue by Hccake** [baomidou/mybatis-plus#564]
### 当前使用版本(必须填写清楚，否则不予处理)
V3.0.5

### 问题描述

查看了下源码，在此类中
`com.baomidou.mybatisplus.core.metadata.TableFieldInfo` 

生成update的模板方法，并拼接sqlSet时
如果该属性上拥有IGNORED注解，将直接return sqlScript,
导致拥有该属性不会被非空忽略。

```
 private String convertIf(String sqlScript, String property) {
        if (this.fieldStrategy == FieldStrategy.IGNORED) {
            return sqlScript;
        } else {
            return this.fieldStrategy == FieldStrategy.NOT_EMPTY && this.isCharSequence ? SqlScriptUtils.convertIf(sqlScript, String.format("%s != null and %s != ''", property, property), false) : SqlScriptUtils.convertIf(sqlScript, String.format("%s != null", property), false);
        }
    }
```

**Comment by miemieYaho** [comment]
没什么原因,从一开始就是这么设计的

**Comment by Hccake** [comment]
> 没什么原因,从一开始就是这么设计的

可以简单说下这么设计的原因吗？比如适用场景之类的
谢谢～

**Comment by Hccake** [comment]
这个问题之前想通了，现在自己来这备注下吧。



### 问题背景

- 2.x 版本的时候，mp官方是提供了`updateAllColumnById`方法来进行全部字段更新的，可以将null值更新入数据库。  
- 如果想在更新时忽略某些字段，比如创建人，创建时间等，可以通过
 `@TableField(strategy=FieldStrategy.IGNORED)`注解来忽略此字段
- 3.0 版本剔除了`updateAllColumnById`方法， 但是项目中又多处使用了此方法，所以简单的查看了2.x版本的源码，将此方法的稍作修改作为全局方法注入了
- 结果发现在使用普通update方法时，会将增加了`@TableField(strategy=FieldStrategy.IGNORED)`注解的字段，更新入库


### 源码对比 

发现问题只能去调试啊，最后发现两个版本中的 `convertIfTag` 方法操作有点不同  
- 2.x 版本中 若字段上有 `IGNORED` 注解，则直接`return ""`,所以在update时，拼接更新sql会忽略掉这些字段  
- 3.x 版本中  若字段上有 `IGNORED` 注解，则直接返回sql片段，所以update时，不论此字段有没有值，都将被更新入库


> 2.x 源码 com.baomidou.mybatisplus.mapper.AutoSqlInjector

```    
	
     * @param ignored   允许忽略
     * @param fieldInfo 字段信息
     * @param prefix    条件前缀
     * @param close     是否闭合标签
     * @return
     * 
    protected String convertIfTag(boolean ignored, TableFieldInfo fieldInfo, String prefix, boolean close) {
		/* 忽略策略 */
        FieldStrategy fieldStrategy = fieldInfo.getFieldStrategy();
        if (fieldStrategy == FieldStrategy.IGNORED) {
            if (ignored) {
                return "";
            }
            // 查询策略，使用全局策略
            fieldStrategy = this.getGlobalConfig().getFieldStrategy();
        }
		// ........省略若干代码
	}

```


> 3.x 源码
> package com.baomidou.mybatisplus.core.metadata.TableFieldInfo;

```

     * 转换成 if 标签的脚本片段
     *
     * @param sqlScript sql 脚本片段
     * @param property  字段名
     * @return if 脚本片段

    private String convertIf(final String sqlScript, final String property) {
        //此处判断 若注解未IGNORED 直接返回了
        if (fieldStrategy == FieldStrategy.IGNORED) {
            return sqlScript;
        }
        if (fieldStrategy == FieldStrategy.NOT_EMPTY && isCharSequence) {
            return SqlScriptUtils.convertIf(sqlScript, String.format("%s != null and %s != ''", property, property),
                false);
        }
        return SqlScriptUtils.convertIf(sqlScript, String.format("%s != null", property), false);
    }
```


### 结论
当时没想明白为什么，明明2.x版本 IGNORED 可以用来忽略字段的更新，3.x版本就不行了。
提了issues，也没有解惑。
> 小声bb，管理员真冷漠  

后来想通了，3.x 版本中提供了updateWrapper，可以通过setSql来控制更新字段，即可强制更新为null。    

FieldStrategy 的作用变得更纯粹了，和2.x版本中，可以用来忽略更新不同，3.x版本中 FieldStrategy 只是用来判断该字段是否需要添加条件控制。  

- NOT_EMPTY   
 非空非null 才更新

- NULL   
 非NULL 才更新

- IGNORED   
 此处忽略，代表忽略此字段控制，因为项目中一般都是全局配置了FieldStrategy非空非null才更新，所以某些特殊字段可以用此注解来忽略，在更新时每次都更新


### 最后

大版本升级真要命，奉劝大家也奉劝自己，如果项目中依赖某个第三方的包比较重，没事千万别更新。  
心痛。
