### ISSUE TITLE
官方不支持的特性，关了吧。

### ISSUE THREAD

**Issue by fuuhoo** [baomidou/mybatis-plus#5643]

**Comment by miemieYaho** [comment]
文档里也没说过可以这么玩吧?你哪看的?

**Comment by fuuhoo** [comment]
> 文档里也没说过可以这么玩吧?你哪看的?

之前在csdn看到的相关文章。
在id为Integer类型的时候确实是可以的。
我查了一下主要是这块影响的
![image](https://github.com/baomidou/mybatis-plus/assets/33688588/a1886866-834b-4d66-99b6-d0fded8dccc6)
在Integer的时候会不带单引号，String的时候带单引号。
也就是这个不是一个特性，而是一个bug？

**Comment by miemieYaho** [comment]
哪来的bug,官方文档都没说支持过的东西

**Comment by fuuhoo** [comment]
> 哪来的bug,官方文档都没说支持过的东西
就是在deleted的类型为Interger的时候，如果delval设置为id的话，自动填充为真实的id值。这个不就是意外的情况吗？

**Comment by miemieYaho** [comment]
狗洞人钻不过去是意外情况吗?

**Comment by fuuhoo** [comment]
> 狗洞人钻不过去是意外情况吗?

抬杠一把好手
