### ISSUE TITLE
逻辑删除表内的数据后重新插入的id为删除数据的id 导致主键id重复插入失败

### ISSUE THREAD

**Issue by yanity233** [baomidou/mybatis-plus#5645]
### 当前使用版本(必填,否则不予处理)
3.5.3.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
逻辑删除表内的数据后重新插入的id为删除数据的id
### 重现步骤(如果有就写完整)
 //删除skuPoster表原有数据
        skuPosterMapper.delete(new LambdaQueryWrapper<SkuPoster>().eq(SkuPoster::getSkuId, skuInfoId));

        //重新批量插入
        if (!CollectionUtils.isEmpty(skuPosterList)) {
            for (SkuPoster skuPoster : skuPosterList) {
                skuPoster.setSkuId(skuInfoId);
            }
            skuPosterService.saveBatch(skuPosterList);
        }

### 报错信息
org.springframework.dao.DuplicateKeyException: com.cyan.mapper.SkuPosterMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Duplicate entry '139' for key 'PRIMARY'
; Duplicate entry '139' for key 'PRIMARY'

**Comment by miemieYaho** [comment]
自行规避
