### ISSUE TITLE
SpringBoot 2.3.12 想使用mybatis-plus 2.1.9，BaseMapper方法无法使用

### ISSUE THREAD

**Issue by SevenBlue2018** [baomidou/mybatis-plus#5648]
### 当前使用版本(必填,否则不予处理)
2.1.9

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
升级springboot版本从1.5.16到2.3.12后，不升级mybatis-plus版本，访问mapper方法时，BaseMapper方法找不到。
升级mybatis-plus到3.x版本，涉及到大量API变动，改造成本太高，因此想升级springboot版本，但是不升级mybatis-plus版本。

### 重现步骤(如果有就写完整)
SpringBoot 2.3.12+mybatis-plus 2.1.9

### 报错信息
BindingException: Invalid bound statement (not found): com.ewt360.xinliprod.service.biz.domain.repo.mapper.MindDetailMapper.selectList

**Comment by huayanYu** [comment]
不行哦.
