### ISSUE TITLE
insert 后主键会自动 set 到实体的 ID 字段？

### ISSUE THREAD

**Issue by zyu** [baomidou/mybatis-plus#565]
### 当前使用版本(必须填写清楚，否则不予处理)

3.05
### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

 long cartid =  cartService.insert(cart);
return R.ok().put("id",cart.getId());

### 报错信息
无论怎么插入 id都是0 根本就没有返回插入id值

**Comment by miemieYaho** [comment]
https://baomidou.gitee.io/mybatis-plus-doc/#/question?id=insert%E5%90%8E%E5%A6%82%E4%BD%95%E8%BF%94%E5%9B%9E%E4%B8%BB%E9%94%AE
