### ISSUE TITLE
当前的版本是否支持graalvm的编译，比如micronaut框架集成这个，graal打包需要注意什么

### ISSUE THREAD

**Issue by zundaren** [baomidou/mybatis-plus#5650]

**Comment by nieqiurong** [comment]
不清楚这个框架,只能按照spring的方式你去改造了. 
https://github.com/baomidou/mybatis-plus/issues/5527

**Comment by zundaren** [comment]
> 不清楚这个框架,只能按照spring的方式你去改造了. #5527

主要还是反射和资源文件的注册，我先尝试集成试下看看

**Comment by zundaren** [comment]
框架里面依赖了spring不怎么好改，还是找找其他替代方案了
