### ISSUE TITLE
SqlRunner.db().selectPage()分页查询无效

### ISSUE THREAD

**Issue by conservators** [baomidou/mybatis-plus#5655]
### 当前使用版本(必填,否则不予处理)

3.4.3.4
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

我在使用SqlRunner.db().selectPage()分页查询时分页参数无效，请问，是我的写法有问题吗
### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/34743247/f7b1d1a0-2180-4199-b4d9-5cf8fedbb046)

**Comment by miemieYaho** [comment]
分页插件加了吗?

**Comment by conservators** [comment]
> 分页插件加了吗?

使用旧版本的PaginationInterceptor方式可以分页，新版本的插件MybatisPlusInterceptor启动出现错误 ，我使用的是mysql8.0
![image](https://github.com/baomidou/mybatis-plus/assets/34743247/42a401f7-38db-49a1-a04b-e53d2123ffc7)

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor.defaultCountSelectItem(PaginationInnerInterceptor.java:79)

The following method did not exist:

    net.sf.jsqlparser.statement.select.SelectExpressionItem.withAlias(Lnet/sf/jsqlparser/expression/Alias;)Lnet/sf/jsqlparser/statement/select/SelectExpressionItem;

The method's class, net.sf.jsqlparser.statement.select.SelectExpressionItem, is available from the following locations:

    jar:file:/D:/mavenlocal/com/github/jsqlparser/jsqlparser/3.1/jsqlparser-3.1.jar!/net/sf/jsqlparser/statement/select/SelectExpressionItem.class

It was loaded from the following location:

    file:/D:/mavenlocal/com/github/jsqlparser/jsqlparser/3.1/jsqlparser-3.1.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of net.sf.jsqlparser.statement.select.SelectExpressionItem

**Comment by miemieYaho** [comment]
jsqlparser版本冲突了

**Comment by conservators** [comment]
> jsqlparser版本冲突了

好滴，我换个版本，谢谢
