### ISSUE TITLE
entity与QueryWrapper结合查询bug

### ISSUE THREAD

**Issue by Laggar** [baomidou/mybatis-plus#566]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatisplus 3.0.5

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

entity 与QueryWrapper结合查询时 ，where条件中多了一个AND

### 重现步骤

        Category c = new Category();
        c.setCategoryName("aaa");
        QueryWrapper<Category> wrapper = new QueryWrapper<>(c);
        wrapper.orderByDesc("create_at");
        categoryService.list(wrapper);

### 报错信息

SELECT  id,category_id,parent_id,category_code,category_name,category_desc,category_grade,bool_leaf_node,prop_create_type,seq,create_time,update_time,create_at,create_by,update_at,update_by  FROM category    WHERE  category_name=?               AND  ORDER BY create_at DESC

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/553

**Comment by miemieYaho** [comment]
使用 3.0.6-SNAPSHOT 快照版本
