### ISSUE TITLE
update操作时 想修改字段为null 使用了UpdateWrapper没生效报无效的列 使用的oracle数据库

### ISSUE THREAD

**Issue by 18211927120** [baomidou/mybatis-plus#5664]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
update操作时 想修改字段为null 使用了UpdateWrapper没生效报无效的列 使用的oracle数据库

### 重现步骤(如果有就写完整)
![image](https://github.com/baomidou/mybatis-plus/assets/57982877/eb767947-4b16-4a34-ae97-6daf4244d91f)

用了几种操作都不行
![image](https://github.com/baomidou/mybatis-plus/assets/57982877/f163ebd8-9cf1-463a-b864-398523281a6a)

字段加了注解类型注解也不行
![image](https://github.com/baomidou/mybatis-plus/assets/57982877/2083c5a1-396f-4f49-b9f8-85173cb2b7d3)

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL1', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111

**Comment by miemieYaho** [comment]
https://mybatis.org/mybatis-3/zh/configuration.html#settings
![image](https://github.com/baomidou/mybatis-plus/assets/28334419/6b883f18-d606-4bbc-942f-2ae7dea321b2)

**Comment by 18211927120** [comment]
刚试了一种方法 字段加注解 加上类型 使用updateById方法可以了 但是后面的LambdaUpdateWrapper还不行
![image](https://github.com/baomidou/mybatis-plus/assets/57982877/28bf0551-239a-4c13-8702-916d12141dc4)
![image](https://github.com/baomidou/mybatis-plus/assets/57982877/c4246ec9-45fe-4d31-abb0-55af3f7720dc)
