### ISSUE TITLE
3.5.3.2 使用 selectpage无法分页

### ISSUE THREAD

**Issue by longjianghu** [baomidou/mybatis-plus#5665]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
整合 springboot3

### 重现步骤(如果有就写完整)
```
selectPage(new Page<>(1, 20),queryWrapper)
```

### 报错信息

分页参数没有加上，另外打印日志也没有见到有查询记录数的信息

**Comment by miemieYaho** [comment]
分页插件加上,看文档

**Comment by longjianghu** [comment]
> 分页插件加上,看文档

谢谢
