### ISSUE TITLE
指定字段查询，IDE警告

### ISSUE THREAD

**Issue by Jick-study** [baomidou/mybatis-plus#5669]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
指定字段查询

### 重现步骤(如果有就写完整)
如何能让IDE不警告这个，大神们指导下
![image](https://github.com/baomidou/mybatis-plus/assets/29773167/8e505a3c-7481-46cf-b033-1927d9e826ef)

**Comment by nieqiurong** [comment]
下个版本解决,现在可以升级[3.5.4-SNAPSHOT.

**Comment by nieqiurong** [comment]
#5572

**Comment by Jick-study** [comment]
> 下个版本解决,现在可以升级[3.5.4-SNAPSHOT.

麻烦问下预计什么时候会正式发布3.5.4版本哇~

**Comment by nieqiurong** [comment]
> > 下个版本解决,现在可以升级[3.5.4-SNAPSHOT.
> 
> 麻烦问下预计什么时候会正式发布3.5.4版本哇~

还有个sql解析器问题, 看下这个月底能不能发把
