### ISSUE TITLE
使用@TableId注解后，再使用@OrderBy 排序字段错误

### ISSUE THREAD

**Issue by czj2037** [baomidou/mybatis-plus#5676]
### 当前使用版本(必填,否则不予处理)

3.5.3.2

### 重现步骤(如果有就写完整)
使用@TableId注解后，再使用@OrderBy，排序的字段是自动推测生成的Column，而不是取TableId中的value
请查看这个方法 com.baomidou.mybatisplus.core.metadata.TableInfoHelper#initTableFields
            if (isPK) {
                if (isOrderBy) {
                    tableInfo.getOrderByFields().add(new TableFieldInfo(globalConfig, tableInfo, field, reflector, existTableLogic, true));
                }
                continue;
            }

**Comment by nieqiurong** [comment]
使用3.5.4-SNAPSHOT试试.
