### ISSUE TITLE
分页查询统计数据总数异常

### ISSUE THREAD

**Issue by TonyYule** [baomidou/mybatis-plus#568]
查询xml 文件
`<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.albedo.java.modules.app.repository.InitiatinActivitiesRepository">

    <select id="findList" resultMap="ActivitiesResultMap">
        SELECT a.*, p.*, u.*, i.*
        FROM d_initiatin_activities AS a
        LEFT JOIN d_images AS i ON  a.id_ = i.deal_id
        LEFT JOIN d_participants_activities AS p ON a.id_ = p.activity_id
        LEFT JOIN sys_user_t AS u ON p.user_id = u.id_

        <where>
            a.status_ = 0
            <if test="userId != null and userId !='' ">
                AND a.organizer_user =#{userId}
            </if>
            <if test="visible != null and visible !='' ">
                AND a.visible =#{visible}
            </if>
        </where>
        order by a.set_time DESC

    </select>

    <resultMap id="participantMap" type="com.albedo.java.modules.app.domain.ParticipantsActivities" >
        <result property="id" column="id_" />
        <result property="userId" column="user_id"/>
        <association property="user" javaType="com.albedo.java.modules.sys.domain.User">
            <result property="id" column="id_"/>
            <result property="name" column="name_"/>
            <result property="userImage" column="user_image"/>
        </association>
    </resultMap>

    <resultMap id="ImagesMap" type="com.albedo.java.modules.app.domain.Images" >
        <result property="id" column="id_" />
        <result property="dealId"  column="deal_id" />
        <result property="url"  column="url"/>
    </resultMap>

    <resultMap type="com.albedo.java.modules.app.domain.InitiatinActivities" id="ActivitiesResultMap">
        <id  column="id_" property="id"/>
        <result property="dealType" column="deal_type"/>
        <result property="activityType" column="activity_type"/>
        <result property="userImage" column="userImage"/>
        <result property="nickname" column="nickname"/>
        <result property="honestyScore" column="honesty_score"/>
        <result property="title" column="title"/>
        <result property="describe" column="describe"/>
        <result property="organizerUser" column="organizer_user"/>
        <result property="nickname" column="nickname"/>
        <result property="dealMoney" column="deal_money"/>
        <result property="appointNumber" column="appoint_number"/>
        <result property="setTime" column="set_time"/>
        <result property="cycleStart" column="cycle_start"/>
        <result property="cycleEnd" column="cycle_end"/>
        <result property="address" column="address"/>
        <result property="location" column="location"/>
        <result property="longitude" column="longitude"/>
        <result property="latitude" column="latitude"/>
        <result property="allowLate" column="allow_late"/>
        <result property="activeState" column="active_state"/>
        <result property="createdDate" column="created_date"/>
        <result property="honestyScore" column="honesty_score"/>

        <collection property="participantsActivities" column="id_" notNullColumn="id_"
                    ofType="com.albedo.java.modules.app.domain.ParticipantsActivities"
                    resultMap="participantMap">
        </collection>
        <collection property="images" column="id_" notNullColumn="id_"
                    ofType="com.albedo.java.modules.app.domain.Images"
                    resultMap="ImagesMap">
        </collection>
    </resultMap>

</mapper>
`

### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-core/2.1.9/

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
/com/baomidou/mybatis-plus-core/2.1.9/mybatis-plus-core-2.1.9-sources.jar!/com/baomidou/mybatisplus/plugins/PaginationInterceptor.java
DEBUG查看到
`    protected void queryTotal(boolean overflowCurrent, String sql, MappedStatement mappedStatement, BoundSql boundSql, Pagination page, Connection connection) {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            DefaultParameterHandler parameterHandler = new MybatisDefaultParameterHandler(mappedStatement, boundSql.getParameterObject(), boundSql);
            parameterHandler.setParameters(statement);
            int total = 0;
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    total = resultSet.getInt(1);
                }
            }
            page.setTotal(total);
            /*
             * 溢出总页数，设置第一页
             */
            int pages = page.getPages();
            if (overflowCurrent && (page.getCurrent() > pages)) {
                // 设置为第一条
                page.setCurrent(1);
            }
        } catch (Exception e) {
            logger.error("Error: Method queryTotal execution error !", e);
        }
    }`
sql为

SELECT COUNT(1) 
FROM d_initiatin_activities AS a 
LEFT JOIN d_images AS i ON a.id_ = i.deal_id 
LEFT JOIN d_participants_activities AS p ON a.id_ = p.activity_id 
LEFT JOIN sys_user_t AS u ON p.user_id = u.id_ WHERE a.status_ = 0 
### 重现步骤
统计成了 用户表的总数

**Comment by miemieYaho** [comment]
这种情况自己写 count sql, 这种 sql 你丢数据库里一样不是正确的 count, 无解

**Comment by TonyYule** [comment]
> 这种情况自己写 count sql, 这种 sql 你丢数据库里一样不是正确的 count, 无解

代码去掉 left join 到where直间的值就可以了嘛

**Comment by miemieYaho** [comment]
你要知道 where 里是可以添加连接的表的限制条件的.

**Comment by TonyYule** [comment]
我项目里面 怎么重写这个类
com/baomidou/mybatis-plus-support/2.1.9/mybatis-plus-support-2.1.9-sources.jar!/com/baomidou/mybatisplus/toolkit/SqlUtils.java

**Comment by TonyYule** [comment]
com/baomidou/mybatisplus/plugins/pagination/optimize/JsqlParserCountOptimize.java
修改如下 
`    private static List<SelectItem> countSelectItem() {
        Function function = new Function();
        function.setName("COUNT");
        function.setDistinct(true);
        List<Expression> expressions = new ArrayList<>();
        LongValue longValue = new LongValue(1);
        ExpressionList expressionList = new ExpressionList();
        expressions.add(longValue);
        expressionList.setExpressions(expressions);
        function.setParameters(expressionList);
        List<SelectItem> selectItems = new ArrayList<>();
        SelectExpressionItem selectExpressionItem = new SelectExpressionItem(function);
        selectItems.add(selectExpressionItem);
        return selectItems;
    }`

增加 function.setDistinct(true);
即可解决

**Comment by qmdx** [comment]
请自定义 count sql 然后 page.searchCount(false)
