### ISSUE TITLE
网卡多时根据雪花算法生产id时速度太慢问题

### ISSUE THREAD

**Issue by kimojar** [baomidou/mybatis-plus#5681]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
本机虚拟网卡较多，共计11各网卡，在启动时，发现启动很慢。
dump线程发现com.baomidou.mybatisplus.core.toolkit.Sequence.getDatacenterId()方法执行很慢，具体是在调用NetworkInterface.getByInetAddress(this.inetAddress)时慢。

### 重现步骤(如果有就写完整)
多虚拟几个虚拟网卡，简单的话就虚拟环回网卡可测试。

### 报错信息
差不多多一个虚拟网卡，会慢一倍的启动时间。

**Comment by huayanYu** [comment]
都会dump线程了， 提交个PR吧。。。

**Comment by qmdx** [comment]
无法重现该问题，如果可以优化欢迎 PR
