### ISSUE TITLE
脚本中存在大量空格和换行导致脚本解析错误，是否可以在解析前去除空格和换行

### ISSUE THREAD

**Issue by greenhand520** [baomidou/mybatis-plus#5686]
### 当前使用版本(必填,否则不予处理)
版本：3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
脚本中存在大量空格和换行导致脚本解析错误，是否可以在解析前去除空格和换行
![image](https://github.com/baomidou/mybatis-plus/assets/32732204/099f4be4-5894-4341-b9e5-3b49f219e25c)

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/32732204/7b6b93cb-8ab9-4f2c-a32b-35aff5ec3e35)

**Comment by nieqiurong** [comment]
是自己编写的sql吗?

**Comment by qmdx** [comment]
无法定位你的问题，给出详细的重现代码

**Comment by tanqiyuan** [comment]
我也遇到了，退回3.5.3.1就没有问题了， 而且3.5.3.2很多SQL查询速度都比3.5.3.1慢非常多

**Comment by QuillVot** [comment]
能否给个能重现问题的dome

**Comment by nieqiurong** [comment]
如果是自己业务代码里面有空格可以尝试开启.
```yaml
mybatis-plus:
  configuration:
    shrink-whitespaces-in-sql: true
```

**Comment by nieqiurong** [comment]
#5345

**Comment by Jick-study** [comment]
> #5345

麻烦问下，下个版本会修复这个问题嘛？

**Comment by pansong291** [comment]
类似这样？
https://github.com/JSQLParser/JSqlParser/issues/1988

**Comment by pansong291** [comment]
> 如果是自己业务代码里面有空格可以尝试开启.
> 
> ```yaml
> mybatis-plus:
>   configuration:
>     shrink-whitespaces-in-sql: true
> ```

@nieqiurong 请教一下这个会不会把数据里的空行给替换了？比如：
```sql
update shop_info set title=?,



content='abc



def'
where id=?
```

**Comment by gantrylau** [comment]
> > 如果是自己业务代码里面有空格可以尝试开启.
> > ```yaml
> > mybatis-plus:
> >   configuration:
> >     shrink-whitespaces-in-sql: true
> > ```
> 
> @nieqiurong 请教一下这个会不会把数据里的空行给替换了？比如：
> 
> ```sql
> update shop_info set title=?,
> 
> 
> 
> content='abc
> 
> 
> 
> def'
> where id=?
> ```

实测会替换

**Comment by nieqiurong** [comment]
自3.5.3.2开始,内置注入已经处理多余的换行.

#6187
