### ISSUE TITLE
Id字段填充无意义值

### ISSUE THREAD

**Issue by ZMMWMY** [baomidou/mybatis-plus#5687]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用insert方式保存对象，这个对象的实体类只用@TableName标识，其他字段均没有注解，id字段是数据库对应主键，数据库中设定了id自增。
发现insert时，id字段已经被分配了值，并没有使用数据库自增。这是有什么生成策略吗
![image](https://github.com/baomidou/mybatis-plus/assets/19320021/45c52164-f200-4e1e-b003-c8c4a491e3bb)

![image](https://github.com/baomidou/mybatis-plus/assets/19320021/8d66d926-d141-480f-ad44-3707edf78680)

### 重现步骤(如果有就写完整)
无

### 报错信息
无

**Comment by miemieYaho** [comment]
字段名为id默认是主键,默认主键策略是雪花id

**Comment by ZMMWMY** [comment]
> 字段名为id默认是主键,默认主键策略是雪花id

但如果是雪花id，那么用Integer类型是不是承接不住，从而报错？

**Comment by ZMMWMY** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/19320021/c8d7aa3f-8ed2-42a0-af28-e3625fb93296)
而且生成的数值位数不一定就到了Integer最长的位数，数字长度不固定

**Comment by qmdx** [comment]
你需要调整下策略 https://baomidou.com/pages/e131bd/  可以配置全局或者注解某个具体的表实体
