### ISSUE TITLE
QueryWrapper.first() 方法问题

### ISSUE THREAD

**Issue by G3792274** [baomidou/mybatis-plus#5689]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
QueryWrapper wrapper = new QueryWrapper ();

当有一段sql需要插入，  MP, 的两个方法完全不同，

wrapper = wrapper.apply("select * from a where a='123'");     -- 不会转义单引号

wrapper = wrapper.first("select * from a where a='123'");     --- 会转义单引号

### 重现步骤(如果有就写完整)

String sql = "with  helloList AS(  SELECT id,role,`status`, concat_ws(',',a,b)  From table  )

### 报错信息

Sql 被转义了 ， concat_ws(',',a,b)    --->concat_ws(\',\',a,b)

**Comment by miemieYaho** [comment]
用最新版

**Comment by G3792274** [comment]
最新版 ，问题仍旧存在。
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
    <version>3.5.3.2</version>
</dependency>
![image](https://github.com/baomidou/mybatis-plus/assets/19231863/bcbe39eb-ad44-4dfc-99ce-a51cdb0ead32)

**Comment by nieqiurong** [comment]
> 最新版 ，问题仍旧存在。 com.baomidou mybatis-plus 3.5.3.2 ![image](https://user-images.githubusercontent.com/19231863/272468136-bcbe39eb-ad44-4dfc-99ce-a51cdb0ead32.png)

提供一个示例工程上来.
