### ISSUE TITLE
LambdaQueryWrapper的构造方法无法跨package访问

### ISSUE THREAD

**Issue by ypm0313** [baomidou/mybatis-plus#569]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)

使用条件构造器会造成大量对字段名称的硬编码（详细说明见：[使用Mybatis-plus条件构造器的正确姿势](http://www.peimin.cn/2018/09/29/Best-practices-using-Wrapper-in-Mybaits-plus/)），所以想通过实现自己的QueryWrapper类解决此问题，但是发现LambdaQueryWrapper的一个构造方法没有使用public修饰，故在我自己的package下无法访问。

构造方法如下：
`LambdaQueryWrapper(T entity, Class<T> entityClass, String sqlSelect, AtomicInteger paramNameSeq, Map<String, Object> paramNameValuePairs, MergeSegments mergeSegments) {
        this.entity = entity;
        this.paramNameSeq = paramNameSeq;
        this.paramNameValuePairs = paramNameValuePairs;
        this.expression = mergeSegments;
        this.sqlSelect = sqlSelect;
        this.entityClass = entityClass;
    }`

希望：
1. 给LambdaQueryWrapper的构造方法加上public修饰
2. 官方能在后续版本里友好地处理字段名称硬编码问题

### 重现步骤
尝试继承AbstractWrapper实现自己的QueryWraper类：
`package cn.peimin.mybatisplus.conditions.query;

import com.baomidou.mybatisplus.core.conditions.AbstractWrapper;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.segments.MergeSegments;
import com.baomidou.mybatisplus.core.metadata.TableFieldInfo;
import com.baomidou.mybatisplus.core.toolkit.ArrayUtils;
import com.baomidou.mybatisplus.core.toolkit.StringUtils;
import com.baomidou.mybatisplus.core.toolkit.TableInfoHelper;

import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Predicate;

/**
 * @Author: Murphy
 * @Date: 2018/10/7 上午10:20
 */
public class QWrapper<T> extends AbstractWrapper<T, String, QWrapper<T>> {

    private String sqlSelect;

    public QWrapper() {
        this(null);
    }

    public QWrapper(T entity) {
        this.entity = entity;
        this.initEntityClass();
        this.initNeed();
    }

    public QWrapper(T entity, String... columns) {
        this.entity = entity;
        this.select(columns);
        this.initEntityClass();
        this.initNeed();
    }

    private QWrapper(T entity, Class<T> entityClass, AtomicInteger paramNameSeq, Map<String, Object> paramNameValuePairs, MergeSegments mergeSegments) {
        this.entity = entity;
        this.entityClass = entityClass;
        this.paramNameSeq = paramNameSeq;
        this.paramNameValuePairs = paramNameValuePairs;
        this.expression = mergeSegments;
    }

    /**
     * 修改后以支持驼峰命名
     * @param sqlSelect
     * @return
     */
    public QWrapper<T> select(String... sqlSelect) {
        if (ArrayUtils.isNotEmpty(sqlSelect)) {
            String[] columnArr = sqlSelect.clone();
            for(int i=0; i<columnArr.length; ++i) {
                columnArr[i] = StringUtils.camelToUnderline(columnArr[i]);
            }
            if (ArrayUtils.isNotEmpty(columnArr)) {
                this.sqlSelect = String.join(",", columnArr);
            }
        }
        return typedThis;
    }

    public QWrapper<T> select(Predicate<TableFieldInfo> predicate) {
        return this.select(this.entityClass, predicate);
    }

    public QWrapper<T> select(Class<T> entityClass, Predicate<TableFieldInfo> predicate) {
        this.entityClass = entityClass;
        this.sqlSelect = TableInfoHelper.getTableInfo(this.getCheckEntityClass()).chooseSelect(predicate);
        return (QWrapper)this.typedThis;
    }

    public LambdaQueryWrapper<T> lambda() {
        return new LambdaQueryWrapper(this.entity, this.entityClass, this.sqlSelect, this.paramNameSeq, this.paramNameValuePairs, this.expression);
    }

    public String getSqlSelect() {
        return this.sqlSelect;
    }

    /**
     * 驼峰命名转换为下划线命名
     * @param column
     * @return
     */
    @Override
    protected String columnToString(String column) {
        // 驼峰命名转换为下划线命名
        return StringUtils.camelToUnderline(column);
    }

    protected QWrapper<T> instance(AtomicInteger paramNameSeq, Map<String, Object> paramNameValuePairs) {
        return new QWrapper(this.entity, this.entityClass, paramNameSeq, paramNameValuePairs, new MergeSegments());
    }
}
`

### 报错信息

Error:(77, 16) java: LambdaQueryWrapper(T,java.lang.Class<T>,java.lang.String,java.util.concurrent.atomic.AtomicInteger,java.util.Map<java.lang.String,java.lang.Object>,com.baomidou.mybatisplus.core.conditions.segments.MergeSegments)在com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper中不是公共的; 无法从外部程序包中对其进行访问

**Comment by miemieYaho** [comment]
1. 该构造方法不是给你们用的
2. 不是每个人都是驼峰转下划线的
