### ISSUE TITLE
MP升级到3.4.3后无法自动引入相关依赖

### ISSUE THREAD

**Issue by OPbjO** [baomidou/mybatis-plus#5690]
### 当前使用版本(必填,否则不予处理)
spring-boot 2.7.16
mybatis-plus-boot-starter 3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
升级前MP版本为3.4.2，maven依赖如图：
![image](https://github.com/baomidou/mybatis-plus/assets/40695047/592114b6-a7b8-4dde-8255-1303e1d1ce36)
升级后MP版本为3.4.3，maven依赖如图：
![image](https://github.com/baomidou/mybatis-plus/assets/40695047/6fe36beb-c50f-4366-8af9-ebb43663da25)
相关的依赖，比如mybatis-plus、spring-boot-starter-jdbc都无法自动引入

### 重现步骤(如果有就写完整)
MP升级到最新版本3.5.3.2，还是没有相关依赖
![image](https://github.com/baomidou/mybatis-plus/assets/40695047/6590ef1f-4326-4c48-8a00-12190e266040)

### 报错信息
升级后，由于缺少的mybatis-plus包，事务注解@Transactional找不到

**Comment by miemieYaho** [comment]
https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-boot-starter/3.5.3.2
