### ISSUE TITLE
分页插件问题无法正确处理使用ResultHandler参数的查询接口

### ISSUE THREAD

**Issue by chaosirPan** [baomidou/mybatis-plus#5691]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
新版本也存在问题。
存在问题的函数：com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor#willDoQuery()
如果resultHandler参数非null，则无法返回total的值，导致continuePage()函数返回false

**Comment by nieqiurong** [comment]
使用3.5.4-SNAPSHOT试试
