### ISSUE TITLE
Bug：addTablePrefix无效

### ISSUE THREAD

**Issue by tianzhihen121** [baomidou/mybatis-plus#5692]
### 当前使用版本(必填,否则不予处理)
3.5.3.1版本
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.5.3.1</version>
            <scope>test</scope>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
不明

### 重现步骤(如果有就写完整)
按照官网【代码生成器(新)-快速生成】的例子：https://baomidou.com/pages/779a6e/#%E4%BD%BF%E7%94%A8
数据库(mysql8.0)，自定义一张表auth_user，在配置项中设置过滤表前缀auth_，就可复现
```
                .strategyConfig(builder -> {
                    builder.addInclude("auth_user") // 设置需要生成的表名
                            .addTablePrefix("auth_"); // 设置过滤表前缀
                })
```

### 报错信息
会发现生成出来的实体类是AuthUser，而不是User，也就是还是有前缀Auth，原因不明。这个addTablePrefix方法的作用似乎没体现出来，感觉是个Bug

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/80a0c557-6c47-4496-b1d1-229256ca9367)

**Comment by insist-learning** [comment]
同上，复现不了
![image](https://github.com/baomidou/mybatis-plus/assets/40890438/b2230eec-3d38-4dc3-8633-7a209793c43d)
![image](https://github.com/baomidou/mybatis-plus/assets/40890438/de7eb6d6-dfd4-4f72-a371-913748bccbe1)
![image](https://github.com/baomidou/mybatis-plus/assets/40890438/2e903f06-d001-4222-8681-0ac0fcc9a44d)

**Comment by tianzhihen121** [comment]
抱歉，已排查，与Mybatis-plus-generator源码无关，系自己公司开发改造了NamingStrategy和INameConvert内的代码，自定义了一个新类型导致了失效。此issue关闭
