### ISSUE TITLE
添加PolarDB数据库支持

### ISSUE THREAD

**Issue by qq752230872** [baomidou/mybatis-plus#5693]
添加PolarDB数据库支持

**Comment by nieqiurong** [comment]
是那个100%兼容 MySQL 和 PostgreSQL的?

**Comment by qq752230872** [comment]
是的，请问目前mp是支持的嘛



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nieqiurong ***@***.***&gt;
发送时间: 2023年10月8日 14:13
收件人: baomidou/mybatis-plus ***@***.***&gt;
抄送: 包启益 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [baomidou/mybatis-plus] 添加PolarDB数据库支持 (Issue #5693)





 
是那个100%兼容 MySQL 和 PostgreSQL的?

**Comment by nieqiurong** [comment]
> 是的，请问目前mp是支持的嘛 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: nieqiurong ***@***.***&gt; 发送时间: 2023年10月8日 14:13 收件人: baomidou/mybatis-plus ***@***.***&gt; 抄送: 包启益 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [baomidou/mybatis-plus] 添加PolarDB数据库支持 (Issue #5693) 是那个100%兼容 MySQL 和 PostgreSQL的? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

理论上没什么问题,用的都是mysql或者postgresql的驱动包,具体你可以试试.
