### ISSUE TITLE
多数据库类型，多数据源怎么配置databaseIdProvider

### ISSUE THREAD

**Issue by adaivskenan** [baomidou/mybatis-plus#5696]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
master配置的mysql，其它库是oracle等类型，sql语法不一样，xml中加了databaseId。但是这个值在构建SqlSessionFactory时已经被databaseIdProvider提供了，覆盖databaseIdProvider也只能返回一个特定值，不能运行时动态变化。怎么能实现动态的替换这个值。

**Comment by nieqiurong** [comment]
mybatis只支持这样,只能通过构建多个sqlSessionFactory.
