### ISSUE TITLE
达梦数据库 saveBatch方法无法执行

### ISSUE THREAD

**Issue by catgptjourney** [baomidou/mybatis-plus#5698]
### 当前使用版本(必填,否则不予处理)
  <groupId>com.baomidou</groupId>
  <artifactId>mybatis-plus-boot-starter</artifactId>
  <version>3.5.3.1</version>

### 该问题是如何引起的?
达梦数据库 IService.saveBatch() 无法执行

### 重现步骤(如果有就写完整)
国产数据库 达梦数据库执行saveBatch方法异常

**Comment by nieqiurong** [comment]
异常堆栈是什么?没有这种数据库环境,这种问题不好定位.

**Comment by aikeep** [comment]
@catgptjourney @nieqiurong 可能和我遇到的是同一个问题 #5709
