### ISSUE TITLE
save 方法保存到数据库，时间类型问题

### ISSUE THREAD

**Issue by tengme** [baomidou/mybatis-plus#5703]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在代码中手动set时间字段（java.util.Date）为yyyy-mm-dd 23:59:59，则保存到数据中是yyyy-mm-dd 00:00:00

### 报错信息
无报错

**Comment by shlijun** [comment]
遇到过类似的问题，可以试试更新jdbc驱动

**Comment by tengme** [comment]
与工具框架不兼容
