### ISSUE TITLE
in(StringUtils.isNotBlank(dm),Grall::getDm,dm.split(","))，前面判断不起作用，依旧会出现空指针异常

### ISSUE THREAD

**Issue by csj96** [baomidou/mybatis-plus#5706]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

in(StringUtils.isNotBlank(dm),Grall::getDm,dm.split(","))，前面判断不起作用，依旧会出现空指针异常

### 重现步骤(如果有就写完整)

in(StringUtils.isNotBlank(dm),Grall::getDm,dm.split(","))，

### 报错信息

空指针异常

**Comment by nieqiurong** [comment]
后面不是惰性求值的,进方法栈就必须求值出来了,这个看下后面加不加个函数式写法,但又不是太美观.

**Comment by nieqiurong** [comment]
#5712
