### ISSUE TITLE
有计划支持响应式数据类型吗，r2dbc目前是spring 官方支持的，

### ISSUE THREAD

**Issue by pigping88** [baomidou/mybatis-plus#5710]
有计划支持响应式数据类型吗，r2dbc目前是spring 官方支持的，但是感觉不够方便，如果支持的话，就更加完美了

**Comment by miemieYaho** [comment]
mybatis支持吗?

**Comment by BruceAn1978** [comment]
同问。
如果能够支持Reactive响应式Driver，那数据库的连接性能将会极大提升，不用动不动配置几十，上百个连接了。
