### ISSUE TITLE
并发情况下执行selectList方法，MybatisMapperMethod::executeForMany抛空指针异常

### ISSUE THREAD

**Issue by zshunxiang** [baomidou/mybatis-plus#5720]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
并发情况下执行selectList方法，大概率出现空指针异常

### 重现步骤(如果有就写完整)
并发下·正常执行sql查询语句，语句和参数正常，数据库里也存在数据，但执行selectList时，通过调试发现在MybatisMapperMethod::executeForMany方法里出现空指针情况。

### 报错信息
<img width="840" alt="1697623359248_71185451-0F95-4272-A6B2-DA4CF43AA709" src="https://github.com/baomidou/mybatis-plus/assets/30036367/91fc4704-2045-43ec-b206-c3448f9ae0da">
<img width="1024" alt="1697623316529_BCE25922-5EEA-492c-9E77-4956D9F754C8" src="https://github.com/baomidou/mybatis-plus/assets/30036367/b98ce6b7-49c2-4b38-858b-0a14f7a54f82">
<img width="362" alt="1697623295280_C0BE11A8-F480-4eb7-91AC-BF92EB39704C" src="https://github.com/baomidou/mybatis-plus/assets/30036367/654825ac-d536-4a31-8cc7-d70391818766">

<img width="845" alt="1697623580338_5733E6DF-7001-4bae-8364-F8A5978FD471" src="https://github.com/baomidou/mybatis-plus/assets/30036367/4cbb242c-d5c5-43d0-8cc9-d5311e46fcd1">

**Comment by miemieYaho** [comment]
可有复现demo?

**Comment by zshunxiang** [comment]
> 可有复现demo?

使用LambdaQueryWrapper和IService的list方法查任何表，每次查百条数据，并发50多就会大概率复现这个问题
