### ISSUE TITLE
文档中的这句话“全局里约等于 INPUT”是什么意思？约等于INPUT？？

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5721]
/**
     * 该类型为未设置主键类型(注解里等于跟随全局,全局里约等于 INPUT)
     */
    NONE(1),

不太理解。

**Comment by miemieYaho** [comment]
另一个枚举值INPUT的效果

**Comment by startjava** [comment]
全局默认值是ASSIGN_ID，所以NONE默认的效果是ASSIGN_ID，，，那么约等于INPUT是什么意思？是指值都需要外部类似于“手动”或"指定"来给ID值吗？

**Comment by miemieYaho** [comment]
全局默认值虽然是ASSIGN_ID,万一有人乱配配成NONE呢?那就当成是INPUT一样效果就行了

**Comment by startjava** [comment]
“万一有人乱配配成NONE呢?”，如果有人乱配置全局成了NONE，那不也是无主键的效果嘛，ID默认值是0，是这样的吗。

**Comment by startjava** [comment]
一直不太懂是什么行为

**Comment by miemieYaho** [comment]
为什么默认0?0就是有值,包装类是没有默认值的

**Comment by startjava** [comment]
“全局默认值虽然是ASSIGN_ID,万一有人乱配配成NONE呢?那就当成是INPUT一样效果就行了”

是不是，虽然我使用NONE策略，全局默认是ASSIGN_ID，所以NONE就变成ASSIGN_ID了，但如果有人乱配置全局为NONE，那就相当于手动set id值，也就是INPUT的效果。

我的理解对吗

**Comment by VampireAchao** [comment]
> “全局默认值虽然是ASSIGN_ID,万一有人乱配配成NONE呢?那就当成是INPUT一样效果就行了”
> 
> 是不是，虽然我使用NONE策略，全局默认是ASSIGN_ID，所以NONE就变成ASSIGN_ID了，但如果有人乱配置全局为NONE，那就相当于手动set id值，也就是INPUT的效果。
> 
> 我的理解对吗

字段注解上的优先级大于全局策略，mybatis-plus框架默认不会给id赋值为"0"
