### ISSUE TITLE
mybatis-plus是同步的还是异步的

### ISSUE THREAD

**Issue by male110** [baomidou/mybatis-plus#5723]
我这边提供了两个接口给Python来用，一个是做某个处理把处理结果给我，处理完成后，调一个接口，告诉我处理完成了。
现在遇到一个奇怪的问题，就是在处理完成里，应该能拿到上一步提交过来的数据，结果是没有拿到的。查数据库数据又是存在的。
有一种可能，就是先调的完成，再调的上传处理结果，所以在处里完成里我拿不到数据。但Python方说他那里都是同步调的，没有问题。
所以，mybatis-plus是异步的还是同步的？
数据库配置如下：
`
  datasource:
    # MySQL8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    # 达梦
    #    driver-class-name: dm.jdbc.driver.DmDriver
    #    url: jdbc:dm://192.168.3.19:5236/paper_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    #    username: paper_boot
    #    password: 12345678
    # PostgreSQL
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://192.168.3.19:5432/postgres
    #    username: postgres
    #    password: 123456
    hikari:
      connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
      minimum-idle: 2               # 最小空闲连接数
      maximum-pool-size: 10         # 最大连接数
      auto-commit: true             # 自动提交
      idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
      connection-test-query: SELECT 1
      pool-name: PaperHikariCP

`

**Comment by miemieYaho** [comment]
同步的
