### ISSUE TITLE
QueryWrapper传入和返回的数据类型一样，我想不一样，如何写这个代码？

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5724]
QueryWrapper<QueryUserinfoDTO> queryWrapper = new QueryWrapper<QueryUserinfoDTO>(queryUserinfoDTO);
传入和返回的数据类型一样，我想不一样，如何写这个代码？

**Comment by miemieYaho** [comment]
不支持

**Comment by startjava** [comment]
如果这样我有一个疑问，就是：
    @TableField(value = "age", exist = false, condition = "%s&gt;=#{%s}")
    private Long beginAge;
    @TableField(value = "age", condition = "%s&lt;=#{%s}")
    private Long endAge;

数据表中有age列，但我想实现区间查询，而beginAge属性不是数据表中的列，所以exist = false了，但查询时却不添加此条件。
如果exist = true，查询时添加了此条件，但我在insert插入新的记录时，却没有这个beginAge列

不知道这种情况如何处理。

**Comment by startjava** [comment]
@miemieYaho
