### ISSUE TITLE
mp saveBatch 主键重复冲突问题

### ISSUE THREAD

**Issue by Orakky** [baomidou/mybatis-plus#5725]
### 当前使用版本(必填,否则不予处理)
`mybatis-plus 3.5.3.2`
`mysql:8.0.33`
`springboot:2.7.13`

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

 jdbc连接串已添加`allowMultiQueries=true`

接口

` public interface IDiskService extends IService<Disk>{}`

第一种实现测试

```
@Transactional
public void process(List<Disk> diskList>{
   diskService.saveBatch(diskList);
}
```

第二种实现测试
```
@Transactional
public void process(List<Disk> diskList){
  List<List<Disk>> partitions=  Lists.partition(diskList,50);
  for(List<Disk> part:partitions){
    List<Disk> tempDisk = Lists.newArrayList();
    tempDisk.addAll(part);
    diskService.saveBatch(tempDisk);
    tempDisk.clear();
 }
}
```

### 重现步骤(如果有就写完整)

`Disk` 类中的主键为`IdType=Auto`,Mysql中为自增主键

### 报错信息

`Duplicate entry '50' for  key 'disk.PRIMARY'`

**Comment by chendk** [comment]
问题解决了吗？
