### ISSUE TITLE
升级mybatis plus 版本到最新版3.5.3.2 batch方法底层bug

### ISSUE THREAD

**Issue by Smilehzy** [baomidou/mybatis-plus#5726]
### 当前使用版本(必填,否则不予处理)

3.5.3.2 

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

升级mybatis plus 版本到最新版3.5.3.2 batch方法底层bug

在调用批量等方法时，新版通过@ Autowired 注入sqlSessionFactory，多数据源会出现问题。（获取注入@Primary的）

老版本中没有问题，获取sqlSessionFactory是通过静态方法SqlHelper.sqlSessionFactory(Entity.class)获取的，这个方法在最新版被丢弃了。

**Comment by nieqiurong** [comment]
#5702
