### ISSUE TITLE
@TableName中的excludeProperty和@TableField中的exist=false有什么区别，感谢都一样呢，都是忽略的作用

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5727]
不太清楚具体的区别。感谢。

**Comment by nieqiurong** [comment]
excludeProperty用于排除你继承过来的

**Comment by startjava** [comment]
我发现excludeProperty属性即可以排除继承的属性，也可以排除当前实体类的，有2个功能，是不是优先使用此属性呢？
也就是@TableField中的exist=false只能排除当前类的属性？这个我没有测试。

**Comment by nieqiurong** [comment]
> 我发现excludeProperty属性即可以排除继承的属性，也可以排除当前实体类的，有2个功能，是不是优先使用此属性呢？ 也就是@TableField中的exist=false只能排除当前类的属性？这个我没有测试。

excludeProperty增加的是用来处理继承第三方包的情况,TableField是用于标记本实体,至于你说的TableField中的exist=false只能排除当前类的属性不清楚你想表达的意思,本身这个注解是作用于属性字段上面,如果你要把父类的属性复制到子类的来说还是怎么.

**Comment by startjava** [comment]
“excludeProperty增加的是用来处理继承第三方包的情况,T”，我测试出来的结果是继承的和本类的都可以排除，有可能歪打正着。
其它的您说的我都懂了，感谢。
