### ISSUE TITLE
debug的时候 有断点情况下mybatis plus restartedMain线程走的非常慢 

### ISSUE THREAD

**Issue by xuxianyu** [baomidou/mybatis-plus#573]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.1

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
debug模式  加了断点 启动会非常缓慢 而且后续的使用也是非常缓慢 

### 重现步骤
加上断点 用debug模式启动   我使用的是 idea2018 +manjaro系统 spring boot 2.0 +mybatis plus 3.0.1

### 报错信息
无报错信息 就是非常缓存  经过观察 是 mybatis plus 初始化的时候restartedMain线程缓慢

**Comment by miemieYaho** [comment]
建议你可以升级一下你的电脑了

**Comment by xuxianyu** [comment]
并不是电脑问题    电脑公司标配  i5 7代  内存16g    只有加了断点 才会变得异常缓慢 






在 2018-10-22 19:00:52，"miemieYaho" <notifications@github.com> 写道：


建议你可以升级一下你的电脑了

**Comment by miemieYaho** [comment]
你当真我们会在代码里下毒?你是第一个说慢的, debug 日志太多是会降低程序运行速度的
