### ISSUE TITLE
autoResultMap 针对在xml写的查询sql无效，是不支持还是？

### ISSUE THREAD

**Issue by hchlw** [baomidou/mybatis-plus#5731]
### 当前使用版本(必填,否则不予处理)
mybatis plus 3.5.2
mysql 5.7
springboot 2.7.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mysql 表中一个字段是 json 格式，对象A中的某个字段类型是 List<子对象> 接收， 我调用自带的方法  list、getById 都是可以正常映射，但是在 xml 自己写的sql 就是映射不了，xml 中用的是 resultType ，指向的是对象A

### 报错信息
没有报错，只是数据没有映射，输出为 null

**Comment by miemieYaho** [comment]
不支持
