### ISSUE TITLE
什么情况下用jdbcType呢？

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5735]
![image](https://github.com/baomidou/mybatis-plus/assets/49554320/d6fa5874-4fc7-4dcc-ae30-e65231e118e3)

![image](https://github.com/baomidou/mybatis-plus/assets/49554320/eb79db53-455f-4201-a1a2-b401cd6c3312)

mysql数据库

我没有用如下2个注解：
![image](https://github.com/baomidou/mybatis-plus/assets/49554320/8d0d3710-6cca-4379-a923-708659e6a94d)
也能实现insert操作，
请问什么情况下必须要使用jdbcType呢？

**Comment by miemieYaho** [comment]
不配置有错的情况下
