### ISSUE TITLE
numericScale如何生效呢？

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5736]
![image](https://github.com/baomidou/mybatis-plus/assets/49554320/1c844e22-940c-4ad4-9cea-81b57995af5d)

![image](https://github.com/baomidou/mybatis-plus/assets/49554320/6066a404-b6cf-493e-8a54-bd5eb8c848a3)

实体类和数据表结构在上图，但执行insert语句时：
    @RequestMapping("insert")
    public void insert(HttpServletRequest request, HttpServletResponse response) {
        Numericscale numericscale = new Numericscale();
        numericscale.setPrice(123.12345);
        numericscaleService.insert(numericscale);
    }

日志输出：
: ==> Parameters: 123.12345(Double)

并没有保留2位，正确用法是什么？在仓库中没有看到这个属性的example code，感谢。

**Comment by miemieYaho** [comment]
这是mybatis的属性

**Comment by startjava** [comment]
那我这种写法为什么没有生效，是不是mybatis-plus没有传参给mybatis？还是我的写法有问题。

**Comment by startjava** [comment]
https://github.com/mybatis/mybatis-3/pull/2904
和这个有关系吗。

**Comment by miemieYaho** [comment]
debug`Insert`类看注入的sql

**Comment by startjava** [comment]
但从上面的URL来看，好像是mybatis3.5.13不支持的事。

**Comment by startjava** [comment]
deubg了，调试一一下，生成如下内容：
```
<script>
INSERT INTO numericscale <trim prefix="(" suffix=")" suffixOverrides=",">
<if test="id != null">
id,
</if>price,
</trim> VALUES <trim prefix="(" suffix=")" suffixOverrides=",">
<if test="id != null">
#{id},
</if>#{price,jdbcType=NUMERIC,numericScale=2},
</trim>
</script>
```

属性是有了，值还是2.
