### ISSUE TITLE
项目很大时，启动十分缓慢，是否有workaround？

### ISSUE THREAD

**Issue by benhouse1987** [baomidou/mybatis-plus#574]
### 当前使用版本(必须填写清楚，否则不予处理)
2.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
最新版本试了一下似乎很多类都不一样了，整个项目跑不起来。
当项目包含大量表映射时，启动项目会自动生成很多代理方法，仔细看了下这部分耗时非常长，在大规模团队开发时，十分影响开发效率，经常需要本地重启项目，每次重启耗时8到10分钟，请问是否有此类问题的解决方案？

**Comment by miemieYaho** [comment]
你用原生 mybatis 也是这么启动的,你说的8-10分钟也太夸张了!

**Comment by lngg057** [comment]
> 你用原生 mybatis 也是这么启动的,你说的8-10分钟也太夸张了!

@miemieYaho 你试过项目几百上千个mapper文件，特别是这些文件不在同一个module里面，启动跑一下就知道了！
这就是个很严重的问题，你没遇到不代表这个问题不存在。初始化的时候慢是很多人都反馈过的，难道所有人机器都是lowb？

**Comment by qmdx** [comment]
> > 你用原生 mybatis 也是这么启动的,你说的8-10分钟也太夸张了!
> 
> @miemieYaho 你试过项目几百上千个mapper文件，特别是这些文件不在同一个module里面，启动跑一下就知道了！ 这就是个很严重的问题，你没遇到不代表这个问题不存在。初始化的时候慢是很多人都反馈过的，难道所有人机器都是lowb？

最新版本针对这个问题做了很多启动优化，请关注 `3.5.3.2` 版本的发布

**Comment by lngg057** [comment]
> > > 你用原生 mybatis 也是这么启动的,你说的8-10分钟也太夸张了!
> > 
> > 
> > @miemieYaho 你试过项目几百上千个mapper文件，特别是这些文件不在同一个module里面，启动跑一下就知道了！ 这就是个很严重的问题，你没遇到不代表这个问题不存在。初始化的时候慢是很多人都反馈过的，难道所有人机器都是lowb？
> 
> 最新版本针对这个问题做了很多启动优化，请关注 `3.5.3.2` 版本的发布

@qmdx 感谢❤
