### ISSUE TITLE
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not use this method for "getEntity"?

### ISSUE THREAD

**Issue by HappyAxin** [baomidou/mybatis-plus#5743]
### 当前使用版本

版本：3.5.4

### 该问题是如何引起的？

LambdaQueryWrapper 的包装类查询获取对象

### 重现步骤(如果有就写完整)
![image](https://github.com/baomidou/mybatis-plus/assets/46963688/8c16e2be-2b65-4f6d-acca-cb8d58183a81)

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/46963688/985b6ed8-bbd4-4ce2-84f6-b93675ae736b)

啥时候能修复啊？

**Comment by miemieYaho** [comment]
不修复,因为就不是这么用的
