### ISSUE TITLE
【优化建议】 countsql优化建议

### ISSUE THREAD

**Issue by zhourui999** [baomidou/mybatis-plus#5745]
### 当前使用版本 3.5.4

<img width="1510" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/40812600/b04e01c7-45a0-4e8b-abe0-ca522c05d9fd">

建议将图中框中的代码迁移，减少存在distinct和group by情况下不必要的前置判断判断

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/bcf49832a329ccdea8272a0a020826db188d860c

**Comment by JavaLionLi** [comment]
这个优化直接导致 sqlserver distinct和orderby一起用报错
 sqlserver里不允许count里存在orderby
这个是不是得修复一下啊

**Comment by JavaLionLi** [comment]
distinct是常用语法 orderby对他也没有影响啊 为啥非要把distinct排除呢

**Comment by binfengyan** [comment]
> 这个优化直接导致 sqlserver distinct和orderby一起用报错 sqlserver里不允许count里存在orderby 这个是不是得修复一下啊

麻烦提个Issue，描述再具体一些
