### ISSUE TITLE
databaseId无法正常获取

### ISSUE THREAD

**Issue by jinyulei0710** [baomidou/mybatis-plus#5746]
### 当前使用版本(必填,否则不予处理)
3.5.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
从3.5.3.2 升级到 3.5.4
```
    <sql id="notDeleted">
        <choose>
            <when test="_databaseId == 'dm'">
                '0000-01-01 00:00:00'
            </when>
            <otherwise>
                0
            </otherwise>
        </choose>
    </sql>

```
databaseId无法正常获取

**Comment by nieqiurong** [comment]
1. 写清楚是升级还是降级
2. 提供复现工程

**Comment by jinyulei0710** [comment]
> 从3.5.3.2 升级到 3.5.4

**Comment by nieqiurong** [comment]
提供你的复现工程.

**Comment by jinyulei0710** [comment]
[mybatis-plus-demo.zip](https://github.com/baomidou/mybatis-plus/files/13304746/mybatis-plus-demo.zip)

**Comment by jinyulei0710** [comment]
@nieqiurong 复现工程已经上传,运行test下的 testSelect 在 3.5.3.2版本下打印：select id from sys_account where id=1 and is_deleted= '0000-01-01 00:00:00'，而在3.5.4.1 打印 select id from sys_account where id=1 and is_deleted= 0 databaseID配置不生效

**Comment by jinyulei0710** [comment]
配置为：
mybatis-plus:
  configuration:
    database-id: dm

**Comment by nieqiurong** [comment]
https://github.com/mybatis/spring-boot-starter/issues/911

**Comment by nieqiurong** [comment]
已发布3.5.5-SNAPSHOT
