### ISSUE TITLE
[bug] left join counsql 优化结果不正确

### ISSUE THREAD

**Issue by zhourui999** [baomidou/mybatis-plus#5748]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
sql语句为：select FROM  a LEFT JOIN  b ON a.id = b.a_id
优化后的count sql为：SELECT COUNT(*) AS total FROM  a
优化后的sql没有on条件，导致count总数异。

这里需要添加判断
<img width="924" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/40812600/3c8d6c3e-117b-468a-bc89-03193d91ff0b">

修改后代码
<img width="1194" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/40812600/349993a5-80aa-4001-9de7-d57b493c15e4">

**Comment by miemieYaho** [comment]
page.setOptimizeJoinOfCountSql(false)
