### ISSUE TITLE
MybatisPlusInterceptor使用匿名内部类无法获取注解Intercepts

### ISSUE THREAD

**Issue by lixx174** [baomidou/mybatis-plus#5752]
依赖：`com.baomidou:mybatis-plus-boot-starter:3.5.4`

配置分页时使用的匿名内部类形式，在触发分页功能
时`org.apache.ibatis.plugin.Plugin#getSignatureMap`方法报错
`org.apache.ibatis.plugin.PluginException: No @Intercepts annotation was found in interceptor com.boot.admin.infra.config.MybatisPlusConfig$1`。
配置代码如下：
```
@Configuration
public class MybatisPlusConfig {

    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        return new MybatisPlusInterceptor(){{
            // 分页插件
            addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
            // 防止全表更新
            addInnerInterceptor(new BlockAttackInnerInterceptor());
        }};
    }
}
```

**Comment by miemieYaho** [comment]
这是mybatis的逻辑,mybatis不支持

**Comment by lixx174** [comment]
thanks a lot
