### ISSUE TITLE
updateBatchById更新永远位true

### ISSUE THREAD

**Issue by Wilson-Lai-Zzz** [baomidou/mybatis-plus#5753]
### 当前使用版本：3.4.1
![image](https://github.com/baomidou/mybatis-plus/assets/32032164/3bedcd62-f1a2-4303-a906-602bd10da45e)

**Comment by miemieYaho** [comment]
https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/executor/BatchExecutor.java#79
