### ISSUE TITLE
numericScale属性无效的原因找到了，广播一下，大家不要发力了，mybatis底层不支持。

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5754]
`github.com/mybatis/mybatis-3/issues/2987`

但是，是否能在mybatis-plus这个层面进行实现呢？

**Comment by startjava** [comment]
@miemieYaho

**Comment by startjava** [comment]
@miemieYaho 请问，mp的针对这个属性的test测试用例可以跑出效果吗？

**Comment by nieqiurong** [comment]
不考虑实现
