### ISSUE TITLE
请问@TableField中的update属性的表达式是什么规则？

### ISSUE THREAD

**Issue by startjava** [baomidou/mybatis-plus#5759]
请问@TableField中的update属性的表达式是什么规则？
文档中只给了如下2种示例：
@TableField(update = "now()")     
private String password;

@TableField(update = "%s+1")     
private Long age;

这种写法是SQL语法，还是JAVA的，，不过看到now()函数，感觉是mysql的语法。

**Comment by nieqiurong** [comment]
数据库,%s你可以理解为就是当前字段,你不写%s写成age+1一样的.
