### ISSUE TITLE
updateAllColumnById方法找不到？v3.0.5

### ISSUE THREAD

**Issue by wangruyu1** [baomidou/mybatis-plus#576]
updateAllColumnById为什么找不到呢？还有能不能在条件更新中添加field的null的操作？这样就能控制是否更新null的字段了。不然自己写sql来解决的话mybatis-plus有何意义呢。

**Comment by miemieYaho** [comment]
update(entity,updateWrapper) 更新. updateWrapper.set(column,columnValue),  
你没有去仔细研究用法就在这说这些有何意义?

**Comment by qmdx** [comment]
不被怼就好好看看文档 http://mp.baomidou.com/guide/wrapper.html#updatewrapper
