### ISSUE TITLE
ServiceImpl  baseMapper 空指针异常

### ISSUE THREAD

**Issue by whycoder** [baomidou/mybatis-plus#5761]
### 当前使用版本(必填,否则不予处理)
3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

偶然打包回会出现，ServiceImpl 里的 baseMapper为空 ，会报空指针异常.想知道什么情况会导致baseMapper注入不进去，是空

### 报错信息
javava.lang.NullPointerException
	at com.baomidou.mybatisplus.extension.service.additional.query.ChainQuery.list(ChainQuery.java:37)

**Comment by VampireAchao** [comment]
请给出最小复现demo用于排查
