### ISSUE TITLE
saveOrUpdate已经弃用

### ISSUE THREAD

**Issue by qiuyueovo** [baomidou/mybatis-plus#5763]
### 当前使用版本(必填,否则不予处理)
v 3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用的最新版本。目前是观察到 saveOrUpdate 似乎以及弃用了

**Comment by qmdx** [comment]
根据反馈某些特殊场景会存在问题，推荐使用其它方法尽快替代，未来会抛弃该方法
