### ISSUE TITLE
MySqlTypeConvert对于point字段类型转化成Integer类型

### ISSUE THREAD

**Issue by jintonghuoya** [baomidou/mybatis-plus#5766]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
MySqlTypeConvert对于point字段类型转化成Integer类型
contains("int")导致的

### 重现步骤(如果有就写完整)
不用重现

**Comment by miemieYaho** [comment]
java里有'point'对应的数据类型吗?

**Comment by jintonghuoya** [comment]
> java里有'point'对应的数据类型吗?

java 没有，我说的是mysql

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/a4e5b3a4-63b8-45ec-b366-b1f59965baa1)

这种类型支持起来也麻烦,看驱动对应的类型为byte[].
