### ISSUE TITLE
【工件选择问题】我应该使用 mybatis-plus-spring-boot3-starter 吗？

### ISSUE THREAD

**Issue by Demonese** [baomidou/mybatis-plus#5767]
### 当前使用版本(必填,否则不予处理)

3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

**首先说明：这不是BUG反馈**

3.5.4 版本发布后，带来了新的 starter 工件 `mybatis-plus-spring-boot3-starter`。现在我使用的是 Spring Boot 3，那么是否意味着使用 `mybatis-plus-spring-boot3-starter` 是更好的选择？

**Comment by qmdx** [comment]
是的未来长期 spring boot 3.0 starter 的维护在 `mybatis-plus-spring-boot3-starter` 模块
