### ISSUE TITLE
saveOrUpdateBatch 以联合索引为主键怎么搞

### ISSUE THREAD

**Issue by ABetterCat** [baomidou/mybatis-plus#5771]
### 当前使用版本(必填,否则不予处理)
`		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.4.2</version>
		</dependency>`

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

以联合主键判断是否存在，存在则更新，不存在则插入，有没有方案？

**Comment by huayanYu** [comment]
没有

**Comment by ABetterCat** [comment]
差评
