### ISSUE TITLE
XML执行的SQL警告：optimize this sql to a count sql has exception

### ISSUE THREAD

**Issue by Jick-study** [baomidou/mybatis-plus#5775]
### 当前使用版本(必填,否则不予处理)
3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用分页Mapper

### 重现步骤(如果有就写完整)
① 定义mapper
![image](https://github.com/baomidou/mybatis-plus/assets/29773167/792b0fd4-e7f0-4f8a-853e-cdfdc770d4d2)

② 其中排序的SQL不能用#符号，只可以使用$
![image](https://github.com/baomidou/mybatis-plus/assets/29773167/8dc0e0e1-10ac-4cf1-ba51-23ea2e48a366)

③ **老版本没有问题，使用当前最新版会出现WARN级别错误**
![image](https://github.com/baomidou/mybatis-plus/assets/29773167/30e742b3-5e39-4045-90ad-6467f2124320)

### 报错信息

上面的③

**Comment by Jick-study** [comment]
实际执行的SQL为：
SELECT COUNT(*)
FROM (
	SELECT *
	FROM platform.user_info
	WHERE user_state = 'ACTIVE'
	ORDER BY update_at DESC
) TOTAL

SELECT *
FROM platform.user_info
WHERE user_state = 'ACTIVE'
ORDER BY update_at DESC
LIMIT 10

**Comment by nieqiurong** [comment]
#5686
