### ISSUE TITLE
请教有分表的情况下代码生成如何配置entity中TableName属性去掉分表后缀

### ISSUE THREAD

**Issue by jacentsao** [baomidou/mybatis-plus#5784]
### 当前使用版本(必填,否则不予处理)
3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
举例`product_0 -> product`

### 重现步骤(如果有就写完整)
表配置，过滤后缀`_0`
```JAVA
.addTableSuffix("_0")
.addInclude("product_0") // 表匹配
```
生成的文件名都是product，但是Entity中生成的`@TableName("product_0")`依然包含后缀

### 报错信息
无报错

**Comment by nieqiurong** [comment]
看是否增加一个分表处理功能,感觉建立个product主表用来生成代码可能会更好点.

**Comment by jacentsao** [comment]
> 看是否增加一个分表处理功能,感觉建立个product主表用来生成代码可能会更好点.

https://mybatis.org/generator/configreference/table.html，能否按照mybatis generator中的domainObjectName一样，指定升成的表名和对象名。单据再建立一个主表不太合适，本身业务上不会使用，反而会造成一定的干扰。
