### ISSUE TITLE
添加支持DDD设计的类似JPA的@Embedded与@Embeddable注解提议

### ISSUE THREAD

**Issue by wanghongbin73** [baomidou/mybatis-plus#5786]
### 当前使用版本(必填,否则不予处理)
3.5.3

添加支持DDD设计的类似JPA的@Embedded与@Embeddable注解提议
![image](https://github.com/baomidou/mybatis-plus/assets/22722572/4583f442-8bb4-4078-99a0-24408ba70b98)

**Comment by nieqiurong** [comment]
不考虑
