### ISSUE TITLE
Trino/Presto 暂无数据库支持和分页方言支持

### ISSUE THREAD

**Issue by bgggithub** [baomidou/mybatis-plus#5788]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
缺少数据库支持

### 重现步骤(如果有就写完整)
添加trino链接，使用mp支持的分页，提示 database not supported.

### 报错信息
 database not supported.

**Comment by miemieYaho** [comment]
分页方言你有试过使用PostgreDialect能用吗?

**Comment by bgggithub** [comment]
> 分页方言你有试过使用PostgreDialect能用吗?

您好，暂未尝试，看代码顺序使用sql测试会报错如下图:
![1700465346796](https://github.com/baomidou/mybatis-plus/assets/47015940/9d3a825d-ad6c-4af5-809d-c87326c2076a)
