### ISSUE TITLE
selectById查不到数据 

### ISSUE THREAD

**Issue by xmmxhxxl** [baomidou/mybatis-plus#5791]
### 当前使用版本(必填,否则不予处理)
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatisplus-spring-boot-starter</artifactId>
                <version>2.1.9</version>
            </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

1、使用selectById查不到数据，total是0，但是复制打印的SQL到数据库查询可以查询到结果，id类型是Long；
2、通过String.valueOf(id)在查询，就可以查询到结果，但这不是我想要的类型。

### 重现步骤(如果有就写完整)

**偶现现象**
1、DO对象
@TableName(value ="app")
@Data
public class AppDO implements Serializable {

    /**
     * id
     */
    @TableId(value = "id")
    private Long id;
......
}
2、dao对象
@Repository
public class AppDao extends ServiceImpl<AppMapper, AppDO> {

    public AppDO getAppDOById(Long id) {
        AppDO appDO = selectById(id);
        return appDO;
    }
....
}
3、Mapper对象
public interface AppMapper extends BaseMapper<AppDO> {
}
4、通过selectById查询
        AppDO appDO = selectById(id);
idea中的查询SQL，查询到的total为0
![image](https://github.com/baomidou/mybatis-plus/assets/83877653/98a43519-2c1d-4664-8380-c3db40e83e80)
数据库中执行该SQL，可以查询到数据
![image](https://github.com/baomidou/mybatis-plus/assets/83877653/e27417dc-1075-4181-9ff1-e77d79a297c7)

### 报错信息
1、查询结果的total为0，但是复制控制台打印的SQL到数据库可以查询到结果；
2、已确认数据库、数据表、字段类型均无误，数据库为mysql5.7;
3、今天（2023.11.19）出现，之前从未出现，出现之后为偶现现象，有时候会出现，有时候不会出现。

**Comment by miemieYaho** [comment]
建议找个跳大神的来驱魔

**Comment by xmmxhxxl** [comment]
> 建议找个跳大神的来驱魔

不是bug吗

**Comment by qmdx** [comment]
执行 sql 是正常的那就是其它问题

**Comment by xiangjiayong** [comment]
我也遇到这个 bug 了同问

**Comment by hongweihao** [comment]
我也遇到这个问题，最后排查发现是接口返回long类型Id，但是浏览器解析的时候精度丢失😢

![Image](https://github.com/user-attachments/assets/5a14127d-ec1e-4afc-83e3-072e118e6028)
