### ISSUE TITLE
insert方法id生成策略

### ISSUE THREAD

**Issue by Chao-Liu233** [baomidou/mybatis-plus#5793]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

之前spring项目，mybatis-plus版本3.4.0，调用insert方法时，如果实体类设置了值也会根据数据库自增生成。项目升级springboot后使用mybatis-plus-boot-starter insert方法却不会重新生成，使用设置的值出现Duplicate entry '41266' for key 'PRIMARY';

**Comment by nieqiurong** [comment]
升级到3.5.5-SNAPSHOT,自定义sql方法注入把insert方法注入一下.
Insert(boolean ignoreAutoIncrementColumn)
