### ISSUE TITLE
批量更新失败

### ISSUE THREAD

**Issue by LXC-9349** [baomidou/mybatis-plus#5796]
### 当前使用版本(必填,否则不予处理)
3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
字段使用@TableField(value = "`grant`")
批量更新不行，单条更新可以

### 重现步骤(如果有就写完整)
多数据源，seata环境下

### 报错信息
sql语法有错误

**Comment by nancheung** [comment]
请提供更多详细可复现的信息
