### ISSUE TITLE
hi，代码生成器支持一下按like生成呗

### ISSUE THREAD

**Issue by wispei** [baomidou/mybatis-plus#58]
项目二次开发，创建了几十个app_这样开头的表，希望批量生成一下~但好像目前不支持

**Comment by qmdx** [comment]
// strategy.setInclude(new String[] { "user" }); // 需要生成的表

        // strategy.setExclude(new String[]{"test"}); // 排除生成的表

默认数据库全部表，你可以考虑生成后 copy 进去。 支持 like 改动较大，这希望你自己灵活使用。
