### ISSUE TITLE
lambdaQuery 多条件groupby生成 sql有多余逗号

### ISSUE THREAD

**Issue by Leon406** [baomidou/mybatis-plus#5801]
### 当前使用版本(必填,否则不予处理)
3.5.4.1
SpringBoot v2.7.17

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

升级mybatis-plus-boot-starter版本 3.5.1 到3.5.4后出现

降级版本到3.5.4以下后正常
3.5.3.2版本测试正常,是3.5.4.x引入的问题

### 重现步骤(如果有就写完整)
相关代码
![image](https://github.com/baomidou/mybatis-plus/assets/26186607/44439663-ce8d-4c8d-acdc-4181a64fbbdb)

### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/26186607/1ae70cbf-537c-4524-8735-d631036f8c79)

**Comment by nieqiurong** [comment]
提供复现工程上来看看.

**Comment by Leon406** [comment]
> 提供复现工程上来看看.

公司代码,无法提供

稍微debug了以下, 确认问题原因,拼接的问题, doGroupBy判断column就好了

![image](https://github.com/baomidou/mybatis-plus/assets/26186607/acb87941-2045-469f-981b-9937dcce447f)

**Comment by nieqiurong** [comment]
更新至3.5.5-SNAPSHOT试试

**Comment by Leon406** [comment]
可以正常使用了
