### ISSUE TITLE
v3.5.3.2是用kotlin1.9编译的？

### ISSUE THREAD

**Issue by MingNiu** [baomidou/mybatis-plus#5807]
### 当前使用版本(必填,否则不予处理)
mybatis plus v3.5.3.2及后续版本

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
spring boot 2.7.18
kotlin 1.7.21
gradle 7.6.3
jdk 17
mybatis plus v3.5.3.2及后续版本

### 重现步骤(如果有就写完整)
gradle build

### 报错信息
编译时报：
xxxx/.gradle/caches/modules-2/files-2.1/com.baomidou/mybatis-plus-extension/3.5.4.1/91309200b3fad930d0ecdcb031ec914277546ed6/mybatis-plus-extension-3.5.4.1.jar!/META-INF/mybatis-plus-extension.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/commit/9a800a907b25c88a200126642999e53ff79d47b8

**Comment by MingNiu** [comment]
所以这是个错误？还是说我得把kotlin升级到1.9？

**Comment by nieqiurong** [comment]
> 所以这是个错误？还是说我得把kotlin升级到1.9？

升级1.9

**Comment by VampireAchao** [comment]
麻烦您升一下子

**Comment by MingNiu** [comment]
spring boot 3.2才支持kotlin 1.9。为啥v3.5.3.2要升到1.9啊？这让我怎么配合spring boot 2.7一起用。。。

**Comment by private-static** [comment]
> spring boot 3.2才支持kotlin 1.9。为啥v3.5.3.2要升到1.9啊？这让我怎么配合spring boot 2.7一起用。。。

spring boot版本跟kotlin版本没有挂钩吧？我2.7.15配合kotlin 1.9.21正常使用。
