### ISSUE TITLE
分页时 autoCountSql 的  select * from a left join b on a.id=b.a_id表时 b表直接被优化掉了 导致分页总数不对 如何解决的

### ISSUE THREAD

**Issue by zongbo110** [baomidou/mybatis-plus#5812]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/57896091/9fe3fc40-9b4b-48bd-8e1f-1dcfa4fecb4c)

**Comment by zongbo110** [comment]
发现是autoCountSql 自动把分页sql的左连接优化掉了，但是左连接应该是一对多的，导致只查询出主表数据

**Comment by miemieYaho** [comment]
page.setOptimizeJoinOfCountSql(false)
