### ISSUE TITLE
  [research]: 技术调研 。注解@TableField 中typeHandler 是否无法在 lambdaUpdate ,lambdaQuery中不能使用

### ISSUE THREAD

**Issue by wxiao1002** [baomidou/mybatis-plus#5816]
### 版本
mybatis-plus 3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
1. 创建Temp 对象，对象中包含一个基本类型字段
2. 在Test 对象中添加Temp 类型字段，并且增加注解     @TableField(typeHandler = JacksonTypeHandler.class)
3. 使用lambdaUpdate 进行set 设置值
4. 程序提示错误，使用updateById 则没有错误 ，错误信息是 Use setObject() with an explicit Types value to specify the type to use.

### 重现步骤(如果有就写完整)
1. 创建 对象
```
class Temp{
  public String address; 
}

@TableName(value = "test",autoResultMap = true)
class Test{

   @TableId
   Long id;  

   @TableField(typeHandler = JacksonTypeHandler.class)
 public Temp temp
}

```

2. 进行update测试
```
 var update = Wrappers.<Test>lambdaUpdate();
update.set(Test::getTemp,new Temp()).eq(Test::getId,1);
 
```

**Comment by miemieYaho** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/28334419/1e70b3c1-c1ab-4bcb-bb0f-581ecc3c98d7)

**Comment by wxiao1002** [comment]
> ![image](https://private-user-images.githubusercontent.com/28334419/286862070-1e70b3c1-c1ab-4bcb-bb0f-581ecc3c98d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzQ4NTgsIm5iZiI6MTcwMTMzNDU1OCwicGF0aCI6Ii8yODMzNDQxOS8yODY4NjIwNzAtMWU3MGIzYzEtYzFhYi00YmNiLWJiMGYtNTgxZWNjM2M5OGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4NTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZGE2YTM0OTc5MGZlOTIwOTJhZTFlMTcyYTU5YjJlMTdmN2M5NWRkZDBkOTFhMmUzYThiYmNkNTdlMDc1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Et9hH9JYOlJGODoVJelo8FcJUdvJpC3W051hEmNjMmQ)

thx
