### ISSUE TITLE
逻辑删除建议

### ISSUE THREAD

**Issue by siminx** [baomidou/mybatis-plus#582]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

逻辑删除建议只使用logicDeleteValue，删除时值赋为logicDeleteValue，查询时查值不等于logicDeleteValue。

比如状态有删除、启用、禁用，即非删除状态有多个的情况这样比较适用。

**Comment by miemieYaho** [comment]
这是你的业务上的事,和逻辑删除无关,自行 xml 写 sql 查逻辑删除了的数据
