### ISSUE TITLE
JDK21 plus使用的mybatis版本过低，导致报错，请更新mybatis-spring版本

### ISSUE THREAD

**Issue by JogJo** [baomidou/mybatis-plus#5820]
### 当前使用版本(必填,否则不予处理)
3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
JDK21 plus使用的mybatis版本过低，未支持jdk21，导致报错

### 报错信息
java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

请更新mybatis版本

<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-spring</artifactId>
    <version>3.0.3</version>
</dependency>

**Comment by nieqiurong** [comment]
#5747
