### ISSUE TITLE
配置了逻辑删除，某些功能需要物理删除，我使用了自定义的sql物理删除，就报错

### ISSUE THREAD

**Issue by kingsusi163it** [baomidou/mybatis-plus#5823]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
配置了逻辑删除，某些功能需要物理删除，我使用了自定义的sql物理删除，就报错

### 报错信息
Cause: java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.14, delete not allow  :XXX

**Comment by miemieYaho** [comment]
报错都告诉你了还在这提啥
