### ISSUE TITLE
如何替换默认的MybatisEnumTypeHandler

### ISSUE THREAD

**Issue by sszzss** [baomidou/mybatis-plus#5830]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

想使用自己的typehandler替换自带的MybatisEnumTypeHandler

**Comment by miemieYaho** [comment]
你是想自己实现mp的枚举规则还是不用mp的枚举规则?

**Comment by sszzss** [comment]
> 你是想自己实现mp的枚举规则还是不用mp的枚举规则?

比如带有@EnumValue注解的我想使用自己的typehandler去处理，现在是不是做不到

**Comment by miemieYaho** [comment]
对
