### ISSUE TITLE
自动填充时if标签动态生成sql异常

### ISSUE THREAD

**Issue by ckb201511** [baomidou/mybatis-plus#5832]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
生成的BoundSql 对象是在自动填充前生成的，导致if test 的时候字段一直为空

### 重现步骤(如果有就写完整)

字段标记为自动填充，在 <if test="xxx != null"></if> 是生成的sql 是有问题

**Comment by ckb201511** [comment]
自动填充时if标签动态生成sql异常

**Comment by huayanYu** [comment]
请正确提问. 示例,步骤

**Comment by ckb201511** [comment]
你好，你的邮件我已经收到，我会尽快回复！谢谢
