### ISSUE TITLE
这个会回归到之前不用加实体类的情况吗？

### ISSUE THREAD

**Issue by scafel** [baomidou/mybatis-plus#5835]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-spring-boot3-starter 3.5.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用自定义基类泛型，LambdaQueryWrapper 创建时必须传入实体类，不加实体类就报错

### 重现步骤(如果有就写完整)

![image](https://github.com/baomidou/mybatis-plus/assets/25117857/54453c96-4878-4669-87d2-d64092f3dfa9)

![image](https://github.com/baomidou/mybatis-plus/assets/25117857/5bcc2428-e8c4-4251-8e95-c660d987bb09)

### 报错信息

can not find lambda cache for this entity [top.scafel.education.interaction.entities.edubaseentities]

**Comment by miemieYaho** [comment]
一直都这样
