### ISSUE TITLE
增加反引号

### ISSUE THREAD

**Issue by ZX828** [baomidou/mybatis-plus#5836]
### 当前使用版本(必填,否则不予处理)

            <version>3.5.4.1</version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
正在学，试了一下，生成的SQL语句是这样的
INSERT INTO table_book  ( type, name, describe )  VALUES (  ?, ?, ?  )
describe好像被当成关键词了，报错。
怎么在 列名表名上加反引号``？
INSERT INTO `table_book`  ( `type`, `name`, `describe` )  VALUES (  ?, ?, ?  )

找了会儿配置，没发现能在列名前后加``的。

### 重现步骤(如果有就写完整)
创建了一个类，4个属性 ，id,type,name,describe。
把describe改成describe_就不报错，改回来就报错。

### 报错信息
Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'describe )  VALUES (  'a', 'a', 'aaa'  )' at line 1

**Comment by c332030** [comment]
@TableField("\`nickname\`")
private String name;

https://baomidou.com/pages/223848/#tablefield

**Comment by ZX828** [comment]
> @TableField("`nickname`") private String name;
> 
> https://baomidou.com/pages/223848/#tablefield

谢谢。
成功跑起来了！

**Comment by ZX828** [comment]
https://baomidou.com/pages/223848/#tablefield

**Comment by simonkingws** [comment]
mybatis-plus-generator 工具通过什么方法可以设置生成的实体全部字段增加反引号，个人觉得默认都有反引号，这样针对历史项目的改造可能会友好些，要不然还需要检查字段是否包含关键字并单独处理。
