### ISSUE TITLE
先one后list，list返回结果错误

### ISSUE THREAD

**Issue by fanyy** [baomidou/mybatis-plus#5838]
### 当前使用版本(必填,否则不予处理)
3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当先调用同样查询条件（比如lambdaquery）的one方法后，再调用同样查询条件的list方法，list方法会返回空集合，调查发现是one方法后会像localcache放入一个空集合，实际是有返回记录的，和basemapper的selectOne有关，我发现selectOne实现变了，新的使用了ResultHandler，好像和这个有关

### 重现步骤(如果有就写完整)
1 调用同样查询条件（比如lambdaquery）的one方法后 ，假设有返回记录
2 调用同样查询条件的list方法，list方法会返回空集合

**Comment by nieqiurong** [comment]
用3.5.5-SNAPSHOT试试.

**Comment by fanyy** [comment]
有发布到仓库吗，没拉到

**Comment by fanyy** [comment]
拉到可以了，后面等正式版发布了
