### ISSUE TITLE
3.5.3.2版本新增了Wrapper 查询 ,但是具体写法不明确

### ISSUE THREAD

**Issue by damonflycloud** [baomidou/mybatis-plus#5839]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.3.2版本新增了Wrapper 查询 TypeHandler 写法,但是官方文档的样例写得不明确
需求: 按照旧方式的话,可以在resultmap里面指定对应的typehandler进行某个字段结果集处理,
`<resultMap id="rewardDetailtMap" type="java.util.Map">
    <result column="userPhone" typeHandler="com.csair.taskCenter.common.mybatis.handle.SensitiveTypeHandler" property="userPhone" />
    <result column="taskName" jdbcType="VARCHAR" property="taskName" />
  </resultMap>`

新方式:查看文档说3.5.3.2版本新增了Wrapper 查询 TypeHandler 写法,如果我要实现以上的功能,我的wrapper应该怎么写呢,按照官方的写法会有问题

**Comment by miemieYaho** [comment]
Wrapper不能定义resultmap
