### ISSUE TITLE
在使用多租户插件TenantLineInnerInterceptor时，from表添加的租户条件为什么没有添到where条件中，而是添加到第一个join的on条件中

### ISSUE THREAD

**Issue by qqseeku** [baomidou/mybatis-plus#5841]
### 当前使用版本(必填,否则不予处理)
截止到[3.5.4.1]

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目中需要使用租户隔离数据，但是实际执行的SQL不符合预期
![17023739418606](https://github.com/baomidou/mybatis-plus/assets/58835016/18a1813d-1c79-4964-be25-7e86a3c175d8)

**Comment by chess3cake** [comment]
执行结果不符合预期，可能是数据库的实现不一样？
胡诌一下，Mysql(5.7?)里面左边图的第一个执行计划里，应该join的两张表u和up已经经过了tenant_id筛选，所以不需要在where里增加筛选。

**Comment by qqseeku** [comment]
我使用的也是mysql。之前我曾经执行左图相似的过滤，发现过滤不生效，之后一直没有这样用过。现在我又试了一下没有模拟出当时的效果，不知道当时怎么搞的，或许用的left join
