### ISSUE TITLE
[BUG] JSQLParser Version : StarRocks : can not recognize refresh materialized view keyword

### ISSUE THREAD

**Issue by aaawuanjun** [baomidou/mybatis-plus#5843]
### 当前使用版本(必填,否则不予处理)
4.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
sqlparser 4.6的问题，不能识别refresh关键字。sqlparser的4.8-snapshot已经支持了
详情见：
https://github.com/JSQLParser/JSqlParser/issues/1914

### 重现步骤(如果有就写完整)
JSQLParser里面提的issue里面有复现步骤
```SQL
refresh materilized view mv1
refresh materilized view mv1 force
```

### 报错信息
JSQLParser里面提的issue里面有报错信息

**Comment by nieqiurong** [comment]
#5872
