### ISSUE TITLE
Spring Boot 3.2.x与mybatis-plus不兼容

### ISSUE THREAD

**Issue by tianxiadys** [baomidou/mybatis-plus#5844]
### 当前使用版本(必填,否则不予处理)
3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
与spring boot 3.2.x版本不兼容

### 重现步骤(如果有就写完整)
同时使用spring boot3.2.x与mybatis plus任意版本，项目均无法启动

### 报错信息

Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

### 解决方案
将mybatis-spring依赖版本更新为3.0.3+即可

**Comment by tangrufeii** [comment]
我遇到了同样的问题,在我的博客中有说明可以参考 [https://duck.vin/article/85](url)

**Comment by nieqiurong** [comment]
#5747
