### ISSUE TITLE
mybatis-plus-generator  3.5.4.1 PackageConfig 中没有other配置

### ISSUE THREAD

**Issue by daxiangme** [baomidou/mybatis-plus#5848]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator  3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
PackageConfig 中没有other配置

### 重现步骤(如果有就写完整)
官网文档：
![image](https://github.com/baomidou/mybatis-plus/assets/26734130/dfa3484a-ec37-4996-9fc9-05d805a82864)
代码：
![image](https://github.com/baomidou/mybatis-plus/assets/26734130/456a9e2c-7969-4800-9454-ce493c6b33ae)

### 报错信息
PackageConfig 中没有other配置

**Comment by aozeyu** [comment]
@EnigmaGuest 可以@仓库的维护人员帮忙看看
