### ISSUE TITLE
TenantLineHandler  多组户插件问题，@InterceptorIgnore是不是只能忽略一个自定义的mapper

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [baomidou/mybatis-plus#5850]
我想忽略一个使用QueryMapper的selectList的查询，目前是通过自己写一个mapper替代QueryMapper方式，再加上注解，是否有更好的方式呢

**Comment by qmdx** [comment]
可以这样，会忽略当前操作线程的所有逻辑

InterceptorIgnoreHelper.handle(IgnoreStrategy.builder().tenantLine(true).build());

**Comment by Zhaobudaoyuema** [comment]
这种方式需要的版本高了 我现在是3.4.1一切换3.5.3就报错。等后续有时间了再试试这种

**Comment by TOP-LH** [comment]
> 可以这样，会忽略当前操作线程的所有逻辑
> 
> InterceptorIgnoreHelper.handle(IgnoreStrategy.builder().tenantLine(true).build());
> 
> 

这个调用是不是需要try finally一下？我现在偶尔会有租户查询条件失效的问题，不知道问题在哪里？
