### ISSUE TITLE
请问是否存在不耦合 spring 的使用方案？

### ISSUE THREAD

**Issue by light0x00** [baomidou/mybatis-plus#5851]
官网里介绍的是和 spring boot 或 spring 的用法。

官网贴的依赖也包含了 spring-core 和 spring-context ，这对用户的使用场景作出了假设。

请问是否存在一个 ”核心模块“ 只依赖 mybatis 而不反向依赖 spring？

```xml
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
    <version>最新版本</version>
</dependency>
```

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-no-spring
