### ISSUE TITLE
Invalid value type for attribute 'factoryBeanObjectType': java.lang.String，

### ISSUE THREAD

**Issue by Basil1991** [baomidou/mybatis-plus#5853]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-spring-boot3-starter 3.5.4.1
spring-boot 3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
存在

### 报错信息
存在@mapper注解无法启动服务。

Invalid value type for attribute 'factoryBeanObjectType': java.lang.String，

### 参考这个解决方案

https://github.com/spring-projects/spring-framework/issues/31247 需要更新spring-mybatis版本

**Comment by nieqiurong** [comment]
#5747

**Comment by sharkfly666** [comment]
升级mp 3.5.5  spring-mybatis 3.0.3  mybatis 3.5.15
