### ISSUE TITLE
MybatisSqlSessionFactoryBean文件里面说的打印sao东西，是什么sao东西？

### ISSUE THREAD

**Issue by HelenAndLi** [baomidou/mybatis-plus#5861]
### Discussed in https://github.com/baomidou/mybatis-plus/discussions/5860

<div type='discussions-op-text'>

<sup>Originally posted by **HelenAndLi** December 20, 2023</sup>
`        // TODO 初始化 id-work 以及 打印骚东西
        targetConfiguration.setGlobalConfig(this.globalConfig);

        // TODO 打印骚东西 Banner
        if (globalConfig.isBanner()) {
            System.out.println(" _ _   |_  _ _|_. ___ _ |    _ ");
            System.out.println("| | |\\/|_)(_| | |_\\  |_)||_|_\\ ");
            System.out.println("     /               |         ");
            System.out.println("                        " + MybatisPlusVersion.getVersion() + " ");
        }`</div>

**Comment by HelenAndLi** [comment]
说的打印sao东西，是什么东西呢

**Comment by miemieYaho** [comment]
就上面那一坨

**Comment by HelenAndLi** [comment]
> 就上面那一坨

那一坨为什么是sao东西

**Comment by cllershen** [comment]
你好骚啊

**Comment by HelenAndLi** [comment]
> 你好骚啊

你挺恶臭啊

**Comment by cllershen** [comment]
> > 你好骚啊
> 
> 你挺恶臭啊

只是开玩笑，sorry
