### ISSUE TITLE
使用shardJDBC分表后，是不是updateById会有问题

### ISSUE THREAD

**Issue by moLineee** [baomidou/mybatis-plus#5863]
### 当前使用版本(必填,否则不予处理)
2.1.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用shardJDBC分表后，updateById会报错，只能用wrapper条件把分表策略的key带上，才找得到对应的表。是否有配置可让updateById继续使用

### 报错信息
Can not update sharding value for table

**Comment by chess3cake** [comment]
第一种方案，可以考虑从底层进行处理，核心逻辑是替换mybatisplus自己生成的sql[ #5871 
第二种方案，shardJDBC从某个版本开始提供手动分表的能力，具体哪个版本我不记得了，可以查看一下文档

**Comment by good-134** [comment]
> ### 当前使用版本(必填,否则不予处理)
> 2.1.4
> 
> ### 该问题是如何引起的？(确定最新版也有问题再提!!!)
> 使用shardJDBC分表后，updateById会报错，只能用wrapper条件把分表策略的key带上，才找得到对应的表。是否有配置可让updateById继续使用
> 
> ### 重现步骤(如果有就写完整)
> ### 报错信息
> Can not update sharding value for table

报这个错误是updateById id不是分片键吗?
