### ISSUE TITLE
SpringBoot 3.2.1 启动报错

### ISSUE THREAD

**Issue by refeccd** [baomidou/mybatis-plus#5867]
### 当前使用版本(必填,否则不予处理)

3.5.4.1

### 重现步骤(如果有就写完整)

hello world 应用即可

### 报错信息

```java
org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'ddlApplicationRunner' is expected to be of type 'org.springframework.boot.Runner' but was actually of type 'org.springframework.beans.factory.support.NullBean'
	at org.springframework.beans.factory.support.AbstractBeanFactory.adaptBeanInstance(AbstractBeanFactory.java:410)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:391)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:778)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
```

**Comment by refeccd** [comment]
3.2.0版本 callRunnber 方法是使用的`context.getBeanProvider(Runner.class).orderedStream().forEach`遍历`Runner`
`orderedStream` 时会过滤`NullBean`. `DdlApplicationRunner`未配置任何`IDdl`是返回的是`null`，所以是个`NullBean`
被过滤掉了，不会报错
<img width="747" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/26990889/7b005113-6f2f-473f-bfc4-6b158f2e9897">

**Comment by refeccd** [comment]
3.2.1版本 callRunnber 方法是使用`context.getBean`获取`Runner`实例对象的
同样情况，`DdlApplicationRunner `返回的`null`被封装成`NullBean `,和最终需要的类型`Runner`不匹配，会报错
<img width="934" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/26990889/07726799-eb73-46c1-a7db-5ec79c0caaf1">

**Comment by pigeon2049** [comment]
+1 复现

**Comment by Yanghaorui** [comment]
+1 spring-boot 3.1.7时已经开始出现了

**Comment by falcon-jin** [comment]
@Bean
    public DdlApplicationRunner ddlApplicationRunner(@Autowired(required = false) List<IDdl> ddlList) {
        return new DdlApplicationRunner(ddlList);
    }
可以在自己项目里面注入bean临时解决 等3.5版本发布

**Comment by 1527430** [comment]
3.5的开发太慢了，快点吧，都等着用呢。

**Comment by Wangab** [comment]
复现 +1

**Comment by zhiyuan-zhang** [comment]
复现 +1

**Comment by MrYZhou** [comment]
已经解决了，依赖改成
<dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>3.5.5</version>
            </dependency>

**Comment by HongboTong** [comment]
> 已经解决了，依赖改成 com.baomidou mybatis-plus-spring-boot3-starter 3.5.5

666呀，哥们，你在哪找到这版本的

**Comment by riki77777** [comment]
> 已经解决了，依赖改成 com.baomidou mybatis-plus-spring-boot3-starter 3.5.5

感谢

**Comment by chesongsong** [comment]
> 已经解决了，依赖改成 com.baomidou mybatis-plus-spring-boot3-starter 3.5.5

牛批

**Comment by nieqiurong** [comment]
#5747

**Comment by Yu-YiDu** [comment]
good

**Comment by Krisjiang211** [comment]
> 已经解决了，依赖改成 com.baomidou mybatis-plus-spring-boot3-starter 3.5.5

牛逼哥们我靠牛逼

**Comment by pengfit** [comment]
nb了

**Comment by wenyushu** [comment]
牛逼！🥹

**Comment by JIaDLu** [comment]
> 已经解决了，依赖改成 com.baomidou mybatis-plus-spring-boot3-starter 3.5.5

nb

**Comment by WenWuZhiDao** [comment]
> 已经解决了，依赖改成 com.baomidou mybatis-plus-spring-boot3-starter 3.5.5

厉害👍
