### ISSUE TITLE
从3.5.3升级到3.5.4.1后遇到的问题

### ISSUE THREAD

**Issue by Min997** [baomidou/mybatis-plus#5873]
在项目中自定义了字段的加解密的注解和拦截器，当使用selectOne进行查询到数据后，执行解密拦截器，对带有加密注解的字段进行解密，但是拿不到查询到的数据，invocation.proceed() 是空的
![image](https://github.com/baomidou/mybatis-plus/assets/63356325/44ef96cd-2b86-4d1d-9eb0-0c9322bd7234)

**Comment by Min997** [comment]
但是selectById、selectList没有这个问题

**Comment by nieqiurong** [comment]
用3.5.5-SNAPSHOT试试
