### ISSUE TITLE
3.5.1升级到3.5.3.2启动异常

### ISSUE THREAD

**Issue by nzb15555196162** [baomidou/mybatis-plus#5875]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
升级到3.5.3.2启动异常

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/18350673/300196ff-82bb-4f02-afce-b41fbe13d127)
![image](https://github.com/baomidou/mybatis-plus/assets/18350673/d05b6f5b-bbd1-41ed-8f73-1ab4baeef90b)

**Comment by ChetWang** [comment]
spring-boot版本暂时先降到3.1.6，目前plus 3.5.4.x还不支持spring boot 3.1.7和3.2.x；
或者使用plus 3.5.5-SNAPSHOT版本

**Comment by nieqiurong** [comment]
#5867

**Comment by nzb15555196162** [comment]
请问下下一次版本是否修复这个问题?如果是的话,下一次什么时候筏板
