### ISSUE TITLE
v3.5.5正式版的mybatisSpringVersion仍然是2.1.2，应更新为3.0.3

### ISSUE THREAD

**Issue by Macrow** [baomidou/mybatis-plus#5879]
### 当前使用版本(必填,否则不予处理)

v3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

v3.5.5正式版的mybatisSpringVersion仍然是2.1.2，导致无法启动

### 重现步骤(如果有就写完整)

查看 https://github.com/baomidou/mybatis-plus/blob/v3.5.5/build.gradle

可发现mybatisSpringVersion仍然是2.1.2

**Comment by Macrow** [comment]
另外发现v3.5.5引用的spring-boot-starter-jdbc也是老版本，是2.7.15，是因为使用了springBootVersion，而未使用springBoot3Version


```yaml
 libraries = [
        mybatisVersion = '3.5.15',
        mybatisSpringVersion = '2.1.2',
        mybatisSpringBootStarterVersion = '2.3.1',
        springVersion = '5.3.27',
        springBootVersion = '2.7.15',
        springBoot3Version = '3.2.0',
        springCloudVersion = '3.1.1',
        jsqlparserVersion = '4.6',
        junitVersion = '5.9.0',
    ]
```

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/blob/v3.5.5/spring-boot-starter/mybatis-plus-spring-boot3-starter/build.gradle
