### ISSUE TITLE
MyBatisPlusConfig放到公共包中不生效

### ISSUE THREAD

**Issue by zxl78585** [baomidou/mybatis-plus#588]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本：3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
我使用的是最新版，在配置分页的时候，我是把公共类都提取出去了，MyBatisPlusConfig放到公共包中，当前项目再引入，发现分页有问题；将MyBatisPlusConfig文件拷贝到本工程中，分页就正常了。

### 重现步骤
创建一个jar工程，在里面写MyBatisPlusCOnfig，然后当前工程引入该配置，然后，执行分页，分页不生效

### 报错信息
无

**Comment by miemieYaho** [comment]
这和本项目无关,自行百度解决

**Comment by xiaoyangzhang** [comment]
解决了，需要手动给`MybatisSqlSessionFactoryBean`设置拦截器`sqlSessionFactoryBean.setPlugins(plugins);`
