### ISSUE TITLE
V3.5.5版本的mybatis-spring还是2.1.2

### ISSUE THREAD

**Issue by dai794251336** [baomidou/mybatis-plus#5880]
### 当前使用版本(必填,否则不予处理)
V3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://github.com/baomidou/mybatis-plus/assets/26127871/d985223a-4e84-456d-8155-740827ceed53)

### 重现步骤(如果有就写完整)

![image](https://github.com/baomidou/mybatis-plus/assets/26127871/20e3dd08-9049-478e-808d-25e96aa7436e)

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/26127871/64f5e253-76f1-4454-be32-0c349a35d9b3)

**Comment by nieqiurong** [comment]
```xml
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
    <version>3.5.5</version>
</dependency>
```
