### ISSUE TITLE
求助！！！使用IService.selectPage方法偶现Unknown column '1' in 'where clause'

### ISSUE THREAD

**Issue by mayuxiang2** [baomidou/mybatis-plus#5882]
### 当前使用版本(必填,否则不予处理)
2.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
调用selectPage() 条件wrapper.eq('status',前端参数)
偶发性100次请求会有1-2次报错

### 重现步骤(如果有就写完整)
测试环境无法重现，生产偶尔出现
PaginationInterceptor.queryTotal只有这个方法报，查列表反而正常，最后查出的结果Total=0但是Record却有列表数据。

### 报错信息
Execute error Select count(1) from table where （status =？）
Unknown column '1'in 'where clause'

PaginationInterceptor.queryTotal(PaginationInterceptor.java：176)

**Comment by mayuxiang2** [comment]
数据库Tidb

**Comment by mayuxiang2** [comment]
![9E5B3D90-2566-4468-BF77-155A1D3987B7](https://github.com/baomidou/mybatis-plus/assets/90622367/e5e7d6db-86a3-4c79-aacb-0066e42e7254)

**Comment by miemieYaho** [comment]
2.x已经不维护了,你这个估计是哪里造成sql的where里出现 '1=1' 了

**Comment by mayuxiang2** [comment]
好吧   确定wrapper只eq了一个条件 入参是顺着报错的线程编号和时间线捋过来的😭😭  并且 selectPage的queryTotal报这个错后请求并没有中断 正常执行查出了一条数据，最后数据集有一条记录但是total是0。。
