### ISSUE TITLE
关于mybatis plus中的BaseMapper<T>以及IService<T> 以及ServiceImpl<M extends <Basemapper>，T>   这几个类

### ISSUE THREAD

**Issue by StickT** [baomidou/mybatis-plus#59]
请问有哪位可以帮忙解释下框架里面的这几个类吗，为什么有了Basemapper这个类之后还要再写通用的Service呢，这不是重复了吗？求助各位大神，尤其是本框架的作者

**Comment by qmdx** [comment]
BaseMapper   就是你说的通用的 mapper 层

ServiceImpl  通用的 service 层实现、通用是为了让 service 层只有自定义方法（当然你可以不用）。

以上的通用处于 【 代码更加简洁 】 的考虑，只关心自定义复杂方法
