### ISSUE TITLE
功能请求：带条件的 getById

### ISSUE THREAD

**Issue by pexcn** [baomidou/mybatis-plus#590]
### 当前使用版本

3.0

### 功能请求

建议在 [ServiceImpl.java](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/service/impl/ServiceImpl.java) 添加一个带条件的 getById.

```java
@Override
public T getById(Serializable id, Wrapper<T> queryWrapper) {

}
```

**Comment by miemieYaho** [comment]
使用 getOne,不会支持重复没必要的方法
