### ISSUE TITLE
支持增删改的日志切面

### ISSUE THREAD

**Issue by jerryPlayer0** [baomidou/mybatis-plus#5905]
我们想记录用户在系统里的增删改操作，这些部分都会设计数据库数据的变更，所以想问一下是否有切面支持本次更新（新增/删除）前后的数据输出，方便用户获取对应的数据内容。或者在哪一层扩展实现下比较合理

**Comment by rowstop** [comment]
用 类似 Mysql 的 binlog 是否更合适

**Comment by GeorgeAnson** [comment]
最新版本具有数据审计功能插件，不知道是不是满足你的需求
DataChangeRecorderInnerInterceptor
