### ISSUE TITLE
逻辑删除覆盖  formatLogicDeleteSql

### ISSUE THREAD

**Issue by langlichong** [baomidou/mybatis-plus#5908]
### 当前使用版本(必填,否则不予处理)
3.5.3

### 重现步骤(如果有就写完整)
源码里提示可以覆盖formatLogicDeleteSql方法
![image](https://github.com/baomidou/mybatis-plus/assets/11713419/e03cde51-e30e-4c45-928e-974deda02d05)

在springboot 2.5.12 web环境下 写了个TableInfo的子类（类上添加了 @Component注解）覆盖了formatLogicDeleteSql，程序启动后做业务查询压根不会执行到子类覆盖的代码，要做额外的配置吗

**Comment by miemieYaho** [comment]
注入 PostInitTableInfoHandler

**Comment by langlichong** [comment]
> 注入 PostInitTableInfoHandler
![image](https://github.com/baomidou/mybatis-plus/assets/11713419/2d6ce17d-248c-4f59-8ceb-ec4f772a62fc)
不太明白啊，怎么写啊，求教

**Comment by miemieYaho** [comment]
升级到最新版,实现这个类,再注入到spring里
