### ISSUE TITLE
[v3.5.5/3.5.4.1]不支持com.github.jsqlparser.jsqlparser-4.7版本报错：NotFoundException:net.sf.jsqlparser.statement.select.SelectExpressionItem

### ISSUE THREAD

**Issue by 805728578** [baomidou/mybatis-plus#5911]
### 当前使用版本(必填,否则不予处理)
v3.5.4.1/3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
pagehelper升级2.1.0后依赖的jsqlparser为4.7版本
mybatis-plus依赖jsqlparser为4.6版本

在使用mybatis-plus分页插件时依赖兼容性问题导致
### 报错信息

NotFoundException:net.sf.jsqlparser.statement.select.SelectExpressionItem

**Comment by nieqiurong** [comment]
#5872
