### ISSUE TITLE
Update 时 debug 日志中 PGObject 参数打印不正确

### ISSUE THREAD

**Issue by ilwyiworld** [baomidou/mybatis-plus#5915]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Update 时 debug 日志参数打印不正确（PGObject 参数，应该是所有非基本数据类型打印都会出现这个问题）

### 重现步骤(如果有就写完整)
在 update 数据的时候，statement 的 sql 语句是正常的，但是 debug 日志中 JSONB 参数不对，后面的参数覆盖了前面的参数，应该是在 setColumn 时使用的是对象的引用，导致所有的对象参数都是同一个了，所以基本数据类型不受影响。

<img width="1582" alt="1" src="https://github.com/baomidou/mybatis-plus/assets/7789175/2459be9b-d02b-4510-9388-e023100c1f8e">

**debug 日志：**

{"lastDayProfit":0.0,"lastDayTime":1704783957201,"libIds":[],"lockFlag":0,"onSaleFlag":0,"pieceFlag":0,"totalProfit":0.0}(PGobject), {"lastDayProfit":0.0,"lastDayTime":1704783957201,"libIds":[],"lockFlag":0,"onSaleFlag":0,"pieceFlag":0,"totalProfit":0.0}(PGobject), 1704783957201(Long), 4(Long)

<img width="1614" alt="2" src="https://github.com/baomidou/mybatis-plus/assets/7789175/0e7defce-5dae-4d13-8462-6ff7130efccb">

**statement：**

HikariProxyPreparedStatement@1286109059 wrapping UPDATE t_json  SET labels_weight='{"文学":1.0,"文学体裁":0.97,"历史":1.0,"唐朝":1.0,"朝代":1.0}', bus_params='{"lastDayProfit":0.0,"lastDayTime":1704784685415,"libIds":[],"lockFlag":0,"onSaleFlag":0,"pieceFlag":0,"totalProfit":0.0}', update_time=1704784685415  WHERE id=?

<img width="447" alt="3" src="https://github.com/baomidou/mybatis-plus/assets/7789175/8f3197a0-17b0-481e-a01c-90d05e513254">

<img width="477" alt="4" src="https://github.com/baomidou/mybatis-plus/assets/7789175/602a909c-4965-4411-94d5-f56e8b4401b0">

<img width="578" alt="5" src="https://github.com/baomidou/mybatis-plus/assets/7789175/1b674989-e86f-47e1-bb10-ec3c74ddc085">

### 报错信息
debug 日志不正确

**Comment by miemieYaho** [comment]
又不是mp的打印sql,你这...

**Comment by ilwyiworld** [comment]
> 又不是mp的打印sql,你这...

所以你们以前就知道这个 bug 么哈哈哈

**Comment by miemieYaho** [comment]
不知道

**Comment by ilwyiworld** [comment]
> 不知道
那先关了 去mybatis那边提了
