### ISSUE TITLE
自定义Entity字段名称后，当对应的列为null时，字段值出现意外的默认值

### ISSUE THREAD

**Issue by acexy** [baomidou/mybatis-plus#5917]
### 当前使用版本(必填,否则不予处理)

3.5.5
MySQL

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

假设一个Entity
```java
class Entity {
    private String field;
}
```
当Entity中的filed与数据库中的表字段名一致时且field这个列为null时，经过mp处理后得到的结果是field = null。

现在将Entity调整为自定义字段名，但是指向同样的列时
```java
class Entity {
    @TableField(value = "field")
    private String field1;
}
```
此时经过mp处理后field1的值将变成默认空字符串 ""，得到了一个意料外的结果，它应该同上面保持一致。

### 重现步骤(如果有就写完整)

同上

**Comment by miemieYaho** [comment]
给出你的复现demo,以git形式
