### ISSUE TITLE
在原有mybatis中集成mybatisplus，同个sql在mp中查询不到数据，在mybatis中能查询到数据

### ISSUE THREAD

**Issue by cedric-hxc** [baomidou/mybatis-plus#5921]
### 当前使用版本(必填,否则不予处理)
3.4.0与3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在原有mybatis基础上，引入mybatisplus，升级mybatis版本信息使其与mp版本匹配。
原有mapper中的sql保持不变，在mp框架上执行原有sql查询出来的数据为空，但移除mp后查询能正常查询数据（工具中也能正常查询）
![image](https://github.com/baomidou/mybatis-plus/assets/35954613/65814d9c-0643-49bb-bbb3-404322849d2d)
![image](https://github.com/baomidou/mybatis-plus/assets/35954613/ecab3fe0-4a52-42e4-80a5-f4960d7d1e56)

目前排查到可能为sql映射时间导致数据查询问题？，jdbcType=TIMESTAMP，数据库中类型为datetime。

### 重现步骤(如果有就写完整)
从mybatis版本3.4.6升级到3.5.7版本，在引入mp包
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.0</version>
        </dependency>
执行原mybatis框架sql语句

### 报错信息
无，查询不到结果

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式

**Comment by cedric-hxc** [comment]
你好！我已收到你的邮件，谢谢~

**Comment by cedric-hxc** [comment]
该问题已经解决，引起该问题的原因是引入mp的同时也将mysql的驱动升级了。
升级版本为mysql-connector-java（5.1.42）  --》 mysql-connector-java（8.0.27）
由此引入兼容性的问题，高版本驱动不返回时间戳毫秒，导致匹配失败，因此匹配不到数据导致。
