### ISSUE TITLE
saveOrUpdate方法多线程高并发会出现重复数据，导致查询报错Duplicate key

### ISSUE THREAD

**Issue by YohanLiu** [baomidou/mybatis-plus#5922]
### 当前使用版本(必填,否则不予处理)
3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 使用 saveOrUpdate(T entity, Wrapper<T> updateWrapper)和saveOrUpdateBatch(Collection<T> entityList)这两个方法，在多线程高并发的场景下，会出现数据重复
![image](https://github.com/baomidou/mybatis-plus/assets/48281017/10c2baa9-4b5c-4814-a5b3-40ad0933e634)

### 重现步骤(如果有就写完整)
多线程一样的数据条件。

### 报错信息
插入或更新并不会报错，但查询就会报错，Duplicate key

**Comment by miemieYaho** [comment]
什么叫`一样的数据条件`?

**Comment by hieastz** [comment]
感觉这个问题不是框架的原因
