### ISSUE TITLE
一对多分页查询时，total大于record的问题

### ISSUE THREAD

**Issue by Raxcl** [baomidou/mybatis-plus#5923]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/70327089/b248c0d7-5c8d-4661-bc1c-9cd8b25c5f40)
![image](https://github.com/baomidou/mybatis-plus/assets/70327089/5fc7a9c9-b75d-4673-a612-82bdfdb8b629)
使用一对多collection对查询后的数据进行封装，导致本来的三条数据变成两条，
但是mybatis plus会提前拼接 count查询总条数，
这也导致了total大于record的问题

解决方案：
改成子查询的形式进行拼接，但我想知道是否打算对以上的情况进行优化呢
```
<collection property="potentialCustomerMediaVOList" ofType="com.djbx.cxb.manager.vo.business.PotentialCustomerMediaVO" select="getCustomerMediaVOList"
            column="id">
    <id column="id" property="id"/>
    <result column="create_time" property="createTime"/>
    <result column="url" property="url"/>
</collection>
```

**Comment by miemieYaho** [comment]
基本无法优化
