### ISSUE TITLE
配置了自定义的IdentifierGenerator后，获取的还是 DefaultIdentifierGenerator

### ISSUE THREAD

**Issue by chaobingliu** [baomidou/mybatis-plus#5924]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我使用了mybatis-plus 3.5.5 版本替换了项目中的mybatis

### 重现步骤(如果有就写完整)
1、使用@Bean注解，配置了自定义的IdentifierGenerator
    @Bean
    public GlobalConfig globalConfiguration(IdGenService idGenService) {
        GlobalConfig conf = new GlobalConfig();
        //自定义Id生成器
        conf.setIdentifierGenerator(entity -> idGenService.geNextid());
        return conf;
    }
2、在主键字段中配置了@TableId(type = IdType.ASSIGN_ID)

3、没有配置 global-config 任何信息
### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/11538240/d6444bba-0916-4d43-9f04-66b7081190c3)

**Comment by miemieYaho** [comment]
把你的IdentifierGenerator注入spring

**Comment by chaobingliu** [comment]
非常感谢您的回复。
把IdentifierGenerator 注入到spring 的方式我试过，都没有成功。
我看官网有三种方式来实现自定义ID生成器的功能。
第一种方式是：将自定义生成器通过使用@component注解将其作为一个组件；
第二种方式是：通过@Bean方法将自定义生成器注入到spring
第三种方式是我上面使用的方式， 通过GlobalConfig 的setIdentifierGenerator方法将自定义Id生成器注册。
在您的指导下，我用以下方法测试了一下，依然没有成功。
![image](https://github.com/baomidou/mybatis-plus/assets/11538240/b3f033bd-d48b-4594-a548-e8eeb2ee2856)
老师，能帮忙再看一下，可能是什么问题吗？

**Comment by miemieYaho** [comment]
你不要自己`@bean sqlsessionfactorybean`

**Comment by chaobingliu** [comment]
再次感谢老师的答复，我再研究一下，非常感谢！

**Comment by LiuRuiXiang** [comment]
我也遇到了 解决了吗

**Comment by mindsynt** [comment]
版本3.5.8 我也遇到了 解决了吗
