### ISSUE TITLE
数据库方言添加

### ISSUE THREAD

**Issue by wmbylyitian** [baomidou/mybatis-plus#593]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.9

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
没有什么问题，现在数据库缺少gbase（也就是informix）的支持，能否添加一下呢？informix在返回mybatis的时候 大数据会认为是字节。可能还需要改mybatis底层（猜测）

**Comment by miemieYaho** [comment]
没听过的数据库呢,如果分页方言和我们支持的数据库类似可以指定相应的数据库方言,没有的话你可以自己实现一下方言,效果好欢迎pr,mybatis的底层我们是不会去轻易动的哦
