### ISSUE TITLE
 DataPermissionInterceptor如何过滤两个以上的in的条件？

### ISSUE THREAD

**Issue by xiaoyuwang1987** [baomidou/mybatis-plus#5933]
### 当前使用版本(必填,否则不予处理)
InExpression inExpression = new InExpression();
            AndExpression andExpression = new AndExpression(where, inExpression);
            for (DataFilterColEnum dataFilterColEnum : dataFilterColEnums) {
                if (DataFilterColEnum.WHSEID == dataFilterColEnum) {
                    inExpression = new InExpression(buildColumn("", dataFilterColEnum.getVal()), whseids);
                } else if (DataFilterColEnum.STORER_KEY == dataFilterColEnum) {
                    inExpression = new InExpression(buildColumn("", dataFilterColEnum.getVal()), storerKeys);
                }
                andExpression = andExpression.withLeftExpression(inExpression);
            }
            return andExpression;

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
这样写好像不行？

**Comment by xiaoyuwang1987** [comment]
要实现的是 select * from table where 条件1 in () and 条件2 in() 可能还有条件3 这样

**Comment by wzkris** [comment]
重写DataPermissionHandler#getSqlSegment方法，自己拼返回的sql片段
