### ISSUE TITLE
mybatis将数据库查询内容映射到entity时，没有正确映射到正确的值，新建的实例属性一直是默认值

### ISSUE THREAD

**Issue by jerryyummy** [baomidou/mybatis-plus#5935]
### 当前使用版本(必填,否则不予处理)
mybatis 3.5.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mapper在映射成blog对象时无法正确映射blog_id,导致新建的blog该值一直为0

### 重现步骤(如果有就写完整)
<img width="672" alt="Screenshot 2024-01-22 at 12 34 43 PM" src="https://github.com/baomidou/mybatis-plus/assets/62087610/0e9910a1-a376-4c62-a246-8d89615f47e3">
这是我的entity，其中blog_id是自增主键，与数据库对应列名称一致

@Select("select * from blog")
  List<Blog> getAllBlogs();//这是我在mapper层中调用的方法返回一堆blog

@Override
    public List<Blog> getBlogs(){
        return blogMapper.getAllBlogs();
    }//这是我在服务层中调用对应方法，但此时所有blog对象的blog_id都为0

<img width="655" alt="Screenshot 2024-01-22 at 12 38 40 PM" src="https://github.com/baomidou/mybatis-plus/assets/62087610/5811f12e-1049-4900-a26e-383682b04ef9">
这是测试结果，显示数据库返回的数据没错但是当映射成blog对象是blog_id并不会改变成数据库列对应的值

### 报错信息
没有报错，但是从mapper映射的数据不对

**Comment by miemieYaho** [comment]
https://baomidou.com/pages/56bac0/#mapunderscoretocamelcase
