### ISSUE TITLE
可不可以添加对elasticsearch的分页支持

### ISSUE THREAD

**Issue by clhui** [baomidou/mybatis-plus#5936]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
集成elasticsearch sql模式时

### 重现步骤(如果有就写完整)

使用jdbc:es://https:xxxx/格式url链接ElasticSearch时

### 报错信息

Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: other database not supported.

**Comment by huayanYu** [comment]
欢迎pR

**Comment by clhui** [comment]
不太会呀，好像没权限
