### ISSUE TITLE
MybatisPlus 将来会不会有 MybatisPlusTest ?

### ISSUE THREAD

**Issue by algakzru** [baomidou/mybatis-plus#594]
### 当前使用版本(必须填写清楚，否则不予处理)

`<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.0.5</version>
</dependency>`

### 该问题是怎么引起的？

Mybatis 有 [MybatisTest](http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-test-autoconfigure)
MybatisPlus 将来也会不会有 MybatisPlusTest ?
会的话，大概什么时候？

**Comment by miemieYaho** [comment]
没有这种 test,代码的 test 源码里倒是有不少,[使用示例](https://gitee.com/baomidou/mybatis-plus-samples)
