### ISSUE TITLE
3.5.5传排序参数无效

### ISSUE THREAD

**Issue by yhl452493373** [baomidou/mybatis-plus#5941]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.4.1升级到3.5.5后出现

### 重现步骤(如果有就写完整)

前端传排序参数:

orders[0].column=name&orders[0].asc=1

在3.5.4.1中，Controller方法上Page作为参数，其中的 orders 是有值的

在3.5.5中，orders是空列表了

### 报错信息

未报错

**Comment by nieqiurong** [comment]
待定是继续保留属性至Page还是修改代码使用PageDto

**Comment by QuintinZhangQQ** [comment]
@qmdx 
page中 getOrders(）为啥要改成orders(），pageDto 中也不存在这个getOrders(）

**Comment by nieqiurong** [comment]
用3.5.6-SNAPSHOT版本的PageDto试试看看

**Comment by Allenkearn** [comment]
我也遇到这个问题了，请问下后面是怎么解决的？
