### ISSUE TITLE
MybatisSqlSessionFactoryBean找不到org/mybatis/logging/LoggerFactory

### ISSUE THREAD

**Issue by cunzhiwang** [baomidou/mybatis-plus#5943]
### 当前使用版本(必填,否则不予处理)
   mybatis-plus-boot-starter   3.5.3.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
看了一下最新版也存在，我在自定义MybatisSqlSessionFactoryBean时出现的

### 报错信息

Caused by: java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory
![image](https://github.com/baomidou/mybatis-plus/assets/57314096/8986be2d-b6ca-4c5d-af59-d3cc84b91aef)

**Comment by miemieYaho** [comment]
依赖冲突
