### ISSUE TITLE
为什么会删我sql中间的空格

### ISSUE THREAD

**Issue by TSYMQMYST** [baomidou/mybatis-plus#5945]
### 当前使用版本(必填,否则不予处理)
<spring-boot.mybatis>3.0.3</spring-boot.mybatis>
<mybatis-plus.version>3.5.4</mybatis-plus.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
最近因为单位内部问题, 所以要将后台框架从ruoyi升级成ruoyi-vue-plus[狮子的]
所以我先默认所有sql都是没问题的
因为定时任务已经运行半年+了
但是迁移过来之后运行这个建表语句就报错
看了日志发现它把我的STORAGE的子句里面所有空格都删了

### 重现步骤(如果有就写完整)
![image](https://github.com/baomidou/mybatis-plus/assets/129494079/8b1c5a28-04c1-4a08-8f4f-82c926cbb565)

### 报错信息

org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: ORA-00972: 标识符过长

; bad SQL grammar []

**Comment by nieqiurong** [comment]
提供复现工程
