### ISSUE TITLE
建议：做一个注解，忽略逻辑删除拼接

### ISSUE THREAD

**Issue by xiaoVinCode** [baomidou/mybatis-plus#5946]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我想要查询逻辑删除后的数据，又不想写SQL，直接是条件构造器就还带逻辑删的条件

**Comment by miemieYaho** [comment]
不支持

**Comment by limng06** [comment]
> 不支持

昨天 我们领导 提了一个场景，逻辑删除的数据，重新录入的时候，直接用 逻辑删除的记录 做更新 。 我实现的时候发现，QueryWrapper传入 逻辑删除字段=删除值 ，还是会自动拼接一个  逻辑删除字段=未删除，条件互斥了，我觉得可以加一个检测，如果 wrapper 已经传入了 逻辑删除字段 的条件 就不要自动拼接了

**Comment by lc980999197** [comment]
> > 不支持
> 
> 昨天 我们领导 提了一个场景，逻辑删除的数据，重新录入的时候，直接用 逻辑删除的记录 做更新 。 我实现的时候发现，QueryWrapper传入 逻辑删除字段=删除值 ，还是会自动拼接一个 逻辑删除字段=未删除，条件互斥了，我觉得可以加一个检测，如果 wrapper 已经传入了 逻辑删除字段 的条件 就不要自动拼接了

强烈支持，既然是逻辑删除，那么就有要去查询逻辑删除数据的需求
