### ISSUE TITLE
建议：select count()做一些默认处理

### ISSUE THREAD

**Issue by scf18857887860** [baomidou/mybatis-plus#5947]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
xxxMapper.selectCount(Wrappers.<PlPrintTemplateDO>lambdaQuery().eq(PlPrintTemplateDO::getDelFlag, Boolean.FALSE)
                ..select(PlPrintTemplateDO.class, x -> !x.getColumn().equals("xxxx")))

### 报错信息
bad sql

该sql最终组装出的sql是 
```
SELECT COUNT(column1,column2........) 
AS total FROM table_name   WHERE  (del_flag = 0)

```

mybatis plus底层是否可以针对count类方法做一些默认处理，
例如：
1.传入字段只能是单个
2.多个字段传入时，默认用*替代 or取第一个字段 等等

**Comment by huayanYu** [comment]
自己处理
