### ISSUE TITLE
Db新特性Bug，Db.lambdaQuery中的orderByAsc()排序不生效

### ISSUE THREAD

**Issue by catdun** [baomidou/mybatis-plus#5948]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用最新版本的MybatisPlus，本想使用Db.新特性解决循环依赖问题，但是发现lambdaQuery中的oderByAsc排序不生效问题

### 重现步骤(如果有就写完整)
代码：
```java
List<Quote> quoteList = Db.lambdaQuery(Quote.class)
        .eq(Quote::getBuyNeedId, buyNeed.getId())
        .orderByAsc(Quote::getQuote)
        .list();
```
没有按预期中quoteList 中根据Quote::getQuote字段进行排序

### 报错信息
未报错，排序不生效

**Comment by VampireAchao** [comment]
收到，解决中

**Comment by VampireAchao** [comment]
暂未复现...检查你的字符编码集是否支持排序

**Comment by VampireAchao** [comment]
请给出复现Demo，若无问题，我将在一段时间(也许几天)后关闭本issue
