### ISSUE TITLE
逻辑删除 TableLogic delval='id' 对 String 类型主键 id 无效

### ISSUE THREAD

**Issue by Wuaner** [baomidou/mybatis-plus#5951]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
若主键为String类型，则删除标志位（类型当然也是String）上的 TableLogic delval='id' 注解无效。（删除操作后会把该标志位置为字符串“id”，而不是期望的该行数据主键id列的值）。

### 重现步骤(如果有就写完整)
如上

### 报错信息
无

**Comment by Wuaner** [comment]
导致出问题的[代码](https://github.com/baomidou/mybatis-plus/blob/b9d219f3e96ab229767f474be45032abde9686fe/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/metadata/TableInfo.java#L468C85-L468C91)；

此处的处理导致如果删除标志位的类型为String，拼接出来的SET sql会变成 `删除标志位 = 'id'`，而非期望的 `删除标志位 = id`

**Comment by miemieYaho** [comment]
不支持

**Comment by Wuaner** [comment]
> 不支持

稍微变通了一下：
将删除标志位的类型设置为`Object`(或者自定义的枚举)，而非 id 列的`String` （同时TableLogic val 值前后需加 `'` 以避免出现数据库类型转换异常）
目前看实现了想要的效果
