### ISSUE TITLE
什么时候能支持多表查询啊？

### ISSUE THREAD

**Issue by honestAnt** [baomidou/mybatis-plus#5953]

**Comment by loverasd** [comment]
特意登录账号，来支持一下。
诸位开发者加油⛽️

**Comment by yhl452493373** [comment]
https://mybatisplusjoin.com/
用1.4.8,1.4.9和1.4.10有问题。
如果涉及分页，先分主表，再联合查从表，否则join分页都有问题

**Comment by yulichang** [comment]
> https://mybatisplusjoin.com/ 用1.4.8,1.4.9和1.4.10有问题。 如果涉及分页，先分主表，再联合查从表，否则join分页都有问题

这些版本没问题，你是非springboot工程，适配问题    
https://github.com/yulichang/mybatis-plus-join/issues/110

**Comment by honestAnt** [comment]
谢谢楼上大佬的解答
