### ISSUE TITLE
使用OrderItem排序的空格问题

### ISSUE THREAD

**Issue by ghost** [baomidou/mybatis-plus#5954]
### 当前使用版本(必填,否则不予处理)

spring-boot:2.7.17
com.baomidou:mybatis-plus-boot-starter:3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用OrderItem进行数据的排序，执行的sql自动去掉了我的空格，导致sql报错

### 重现步骤(如果有就写完整)
![企业微信截图_17068523572185](https://github.com/baomidou/mybatis-plus/assets/28785991/695c45c7-48d9-439a-8e4c-94d62c018550)
![企业微信截图_17068524452583](https://github.com/baomidou/mybatis-plus/assets/28785991/80be3d82-1ddc-4cf3-bd41-1c6ed336f453)

### 报错信息
如上图所示

**Comment by qmdx** [comment]
使用： `Wrappers.query().orderByDesc(" 排序内容")` 方式查询 ，默认 setColumn 方式做了内容处理。如果是前端任意传递字符串注意 SQL 注入 https://baomidou.com/pages/110sec/
