### ISSUE TITLE
字段中exists关键字导致排序失效

### ISSUE THREAD

**Issue by hezhi3f** [baomidou/mybatis-plus#5956]
### 当前使用版本(必填,否则不予处理)
3.5.3.2 3.5.4 3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
有个exists字段导致PaginationInnerInterceptor::concatOrderBy解析sql时，报错
SELECT tb_name,...,exists,...   
FROM bddp_db.entity_tb      
WHERE  (exists = ? AND legal = ? AND db_id IN (?,?,?,?,?,?,?,?,?,?,?,?))

### 报错信息
java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "exists" "EXISTS"
    at line 1, column 86.

Was expecting one of:

    "!"
    "("
    "*"
    "NOT"

**Comment by miemieYaho** [comment]
无解

**Comment by VampireAchao** [comment]
无解

**Comment by hezhi3f** [comment]
😟

**Comment by VampireAchao** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/52746628/6d15a112-8ee3-4dcb-b65e-57f421aa2ea3)

**Comment by yuge1805** [comment]
无解嘛？

**Comment by softboy99** [comment]
为什么close?解决了吗？3.5.12遇到了

**Comment by hezhi3f** [comment]
> 为什么close?解决了吗？3.5.12遇到了

开发者说了无解，改字段名吧，别用关键字

**Comment by softboy99** [comment]
可我们是mapper.xml中有exists,都执行不了了，select * from ( SELECT
                            q.*,
                            bo.contract_no as contractno,
                            CASE
                                WHEN EXISTS (
                                    SELECT 1
                                    FROM sample s
                                    WHERE s.quotation_id = q.id
                                ) AND NOT EXISTS (
                                    SELECT 1
                                    FROM sample s
                                    WHERE s.quotation_id = q.id
                                      AND s.sample_flow_status != '已入库'
                                ) THEN '已入库'
                                ELSE NULL
                                END as quotationsamplestatus
                        FROM quotation q LEFT JOIN biz_order bo ON q.id = bo.quotation_id) t
            WHERE (status_id = ?) ORDER BY create_time DESC
