### ISSUE TITLE
spring的aop拦截失败

### ISSUE THREAD

**Issue by Agility6** [baomidou/mybatis-plus#5957]
### 当前使用版本
MyBatisPlus3.5.5
spring-boot-starter-parent 2.7.14

### 该问题是如何引起的

1. 对`remove`方法进行拦截
<img width="923" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/75616395/10c1fbb3-4982-4275-b8d3-efb3af8d90bf">

2. controller层
<img width="1049" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/75616395/36c50b6b-aef6-467e-b6a7-53055220c2c5">

3. 进行debug的时候发现成功添加到`chain`中 
<img width="1117" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/75616395/43679b9e-48ee-434b-b425-47086c0e3947">

### 其他版本尝试

MyBatisPlus3.4.1
spring-boot-starter-parent 2.7.14

1. 同样操作

2. 进行debug，可以正常被拦截
<img width="1267" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/75616395/8ecbbcbb-d212-44b8-a464-9bdb4c3cdb9a">

如果这不是我操作引发的问题，我愿意尝试解决这个bug

**Comment by binfengyan** [comment]
实际验证过与版本无关

**Comment by Agility6** [comment]
你好，请问实际验证，切换MyBatisPlus3.5.5可以正常拦截到吗？

**Comment by binfengyan** [comment]
我这边使用3.5.5正常拦截,建议排查其它方面问题
