### ISSUE TITLE
MyBatis Plus 分页插件 bad SQL grammar []

### ISSUE THREAD

**Issue by lyfGeek** [baomidou/mybatis-plus#5958]
### 当前使用版本(必填,否则不予处理)

        
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.4</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用 MyBatis Plus 进行查询时 sql 自动在查询语句（SELECT ...）后加了 ; 分号，导致 LIMIT 语句报错。

### 重现步骤(如果有就写完整)

![image](https://github.com/baomidou/mybatis-plus/assets/35895457/ab2b804e-b017-4ac4-9aef-ddc9b347f59b)

![image](https://github.com/baomidou/mybatis-plus/assets/35895457/80d088c6-091c-441c-bb16-a94012541926)

![image](https://github.com/baomidou/mybatis-plus/assets/35895457/4c0577c8-6113-48a2-8b49-0a04cd962523)

![image](https://github.com/baomidou/mybatis-plus/assets/35895457/6daa5872-f332-47f1-ad94-79bc352f0555)

### 报错信息

org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 2,2' at line 17
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 2,2' at line 17

**Comment by miemieYaho** [comment]
排查你的配置在哪里多个`;`,那么多人用不可能就你遇到这种bug的

**Comment by lyfGeek** [comment]
这个 default <E extends IPage<T>> E page(E page) 方式是 IService 里的，这边没有做任何实现。请教下出现这个问题的可能是什么？
