### ISSUE TITLE
UpdateWrapper的lambda表达式字段无法更新为null

### ISSUE THREAD

**Issue by guiqulaici** [baomidou/mybatis-plus#596]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
更新字段为null

### 重现步骤
1、UpdateWrapper的lambda表达式更新
UpdateWrapper<CategoryTag> updateWrapper = new UpdateWrapper<>();
updateWrapper.lambda().set(CategoryTag::getTagName, null).eq(CategoryTag::getId, 3142);
categoryTagService.update(new CategoryTag(), updateWrapper);
无法更新

2、UpdateWrapper字段更新
UpdateWrapper<CategoryTag> updateWrapper = new UpdateWrapper<>();
updateWrapper.set("tag_name", null).eq("id", 3142);
categoryTagService.update(new CategoryTag(), updateWrapper);
可以更新

### 报错信息
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'WHERE' 附近有语法错误。
; bad SQL grammar []; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'WHERE' 附近有语法错误。

**Comment by miemieYaho** [comment]
使用 3.0.6.2-SNAPSHOT 版本试试

**Comment by JsonSong89** [comment]
我的3.0.5版本,也有这个问题,一模一样.

**Comment by miemieYaho** [comment]
最新版 3.0.6
