### ISSUE TITLE
in查询condition无效，当in查询参数为空时，报空指针错误

### ISSUE THREAD

**Issue by cike978** [baomidou/mybatis-plus#5960]
### 当前使用版本(必填,否则不予处理)

3.5.5

### 重现步骤(如果有就写完整)
pageVO.getCgqlx()是空的，虽然加了判断，但是还是会报错
![image](https://github.com/baomidou/mybatis-plus/assets/17735948/af1aeb83-9aa6-4df8-aedb-db64ca7195e0)

### 报错信息

![image](https://github.com/baomidou/mybatis-plus/assets/17735948/8e191098-e680-4c9d-a96e-ca3557f1d612)

**Comment by miemieYaho** [comment]
入参是object而不是函数那是不存在滞后执行的
