### ISSUE TITLE
FileOutConfig 缺失

### ISSUE THREAD

**Issue by venusDo** [baomidou/mybatis-plus#5961]
### 当前使用版本(必填,否则不予处理)
3.5.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
需要用到 ClickHouseQuery和FileOutConfig 
3.5.0开始才有ClickHouseQuery
但是就没有了FileOutConfig

**Comment by nieqiurong** [comment]
3.5.0开始有大的改动，按照新的代码生成器文档进行调整.
