### ISSUE TITLE
Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

### ISSUE THREAD

**Issue by JasonNerd** [baomidou/mybatis-plus#5962]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
SpringBoot从2.6.0改为3.2.2

### 重现步骤(如果有就写完整)
也即将SpringBoot升级到3.2.2版本后

### 报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/71767491/3c9b1665-49d2-4acb-b8bb-34d0820dd3cf)

了解到该问题似乎已经有之前的issue，然而似乎该问题再次出现，并且查询到maven依赖
![image](https://github.com/baomidou/mybatis-plus/assets/71767491/ec343c19-600f-4574-827a-5086eee3cecd)

发现mybatis版本仍停留在2.xx
------
父工程 pom部分 如下:
```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.2</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>

<groupId>com.cloud</groupId>
<artifactId>micserv</artifactId>
<version>1.0</version>
<packaging>pom</packaging>

<properties>
    <java.version>17</java.version>
    <spring-cloud.version>2023.0.0</spring-cloud.version>
    <mysql.version>8.1.0</mysql.version>
    <mybatis-plus.version>3.5.5</mybatis-plus.version>
</properties>
```

**Comment by MoonEsther** [comment]
> ### 当前使用版本(必填,否则不予处理)
> 3.5.5
> 
> ### 该问题是如何引起的？(确定最新版也有问题再提!!!)
> SpringBoot从2.6.0改为3.2.2
> 
> ### 重现步骤(如果有就写完整)
> 也即将SpringBoot升级到3.2.2版本后
> 
> ### 报错信息
> ![image](https://private-user-images.githubusercontent.com/71767491/304019913-3c9b1665-49d2-4acb-b8bb-34d0820dd3cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDE3NjMsIm5iZiI6MTcwODUwMTQ2MywicGF0aCI6Ii83MTc2NzQ5MS8zMDQwMTk5MTMtM2M5YjE2NjUtNDlkMi00YWNiLWI4YmItMzRkMDgyMGRkM2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA3NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDdmM2U4NzAxMjBlMmU3NDJjYWM0OGU3Yzk5ZmFhZGE3YTRlZDBjODkxYzRhMTVhMWUyMDRhNWYyZjFmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZN10xwNos9QghIjT9JGaYuvSe53_bnYuVhc30kPEQCE)
> 
> 了解到该问题似乎已经有之前的issue，然而似乎该问题再次出现，并且查询到maven依赖 ![image](https://private-user-images.githubusercontent.com/71767491/304020348-ec343c19-600f-4574-827a-5086eee3cecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDE3NjMsIm5iZiI6MTcwODUwMTQ2MywicGF0aCI6Ii83MTc2NzQ5MS8zMDQwMjAzNDgtZWMzNDNjMTktNjAwZi00NTc0LTgyN2EtNTA4NmVlZTNjZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA3NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyY2RmM2RhZGU3MjFmMGE0ZjdiMGJmYmE2MDg5ZGNkZWQ4ZWJjNTNhMjAxMDg2MzI3MmJiYWRkNmFkOWYzZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gexn6gmGtso43bEAGnXWTcN8qDzdNaR6cSyqr2U4bAs)
> 
> ## 发现mybatis版本仍停留在2.xx
> 父工程 pom部分 如下:
> 
> ```
> <parent>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-parent</artifactId>
>     <version>3.2.2</version>
>     <relativePath/> 
> </parent>
> 
> <groupId>com.cloud</groupId>
> <artifactId>micserv</artifactId>
> <version>1.0</version>
> <packaging>pom</packaging>
> 
> <properties>
>     <java.version>17</java.version>
>     <spring-cloud.version>2023.0.0</spring-cloud.version>
>     <mysql.version>8.1.0</mysql.version>
>     <mybatis-plus.version>3.5.5</mybatis-plus.version>
> </properties>
> ```
兄弟我也遇到了,但是你可以这样修改
![image](https://github.com/baomidou/mybatis-plus/assets/56014350/58fb4f48-ac44-4213-aba5-0574987c18e7)
因为springboot3.2.x之后
![image](https://github.com/baomidou/mybatis-plus/assets/56014350/46acb40b-dd87-4fb3-86ba-55b85dfe5e6e)

**Comment by kse-music** [comment]
在pom里添加mybatis-spring依赖管理就行了

```
 <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis-spring</artifactId>
                <version>3.0.3</version>
            </dependency>
</dependencyManagement>
```

**Comment by JasonNerd** [comment]
@itzpm 太细了，这是怎么debug出来的？我感觉springboot项目很难debug到具体源，毕竟依赖太多了

**Comment by MoonEsther** [comment]
> 在pom里添加mybatis-spring依赖管理就行了
> 
> ```
>  <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>org.mybatis</groupId>
>                 <artifactId>mybatis-spring</artifactId>
>                 <version>3.0.3</version>
>             </dependency>
> </dependencyManagement>
> ```

对的,新版的mybatis-spring已经改过来了

**Comment by MoonEsther** [comment]
> @itzpm 太细了，这是怎么debug出来的？我感觉springboot项目很难debug到具体源，毕竟依赖太多了

就是报错了,然后看一下就知道哪里有问题了,新版的mybatis-spring也是这样改的

**Comment by Umenezumi** [comment]
> @itzpm 太细了，这是怎么debug出来的？我感觉springboot项目很难debug到具体源，毕竟依赖太多了

https://blog.csdn.net/u011410254/article/details/134611035

**Comment by Umenezumi** [comment]
```xml
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis.plus.version}</version>
            <!-- 临时解决 factoryBeanObjectType 错误，等待 MyBatis-Plus 修复-->
            <exclusions>
                <exclusion>
                    <groupId>org.mybatis</groupId>
                    <artifactId>mybatis-spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--临时解决 factoryBeanObjectType 错误，等待 MyBatis-Plus 修复-->
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-spring</artifactId>
            <version>${mybatis.version}</version>
        </dependency>
```

**Comment by nieqiurong** [comment]
#5747

**Comment by wangjiancheng180** [comment]
额滴神3.5.7还没修复

**Comment by nieqiurong** [comment]
额滴神村里还没通网

**Comment by Umenezumi** [comment]
> 额滴神 3.5.7 还没修复

你再仔细调整下呢？我这边已经解决了

**Comment by ArtistSu** [comment]
还没有修复, spring-boot 3.2.5 然后 mybatis-plus 3.5.5 然后 用的gradle
如图 还是2.1.2 , 只能手动加个新的依赖了
![image](https://github.com/user-attachments/assets/ddd072d0-b1f2-4184-bb13-fbe791c58fe5)

**Comment by nieqiurong** [comment]
> 还没有修复, spring-boot 3.2.5 然后 mybatis-plus 3.5.5 然后 用的gradle 如图 还是2.1.2 , 只能手动加个新的依赖了 ![image](https://private-user-images.githubusercontent.com/50010130/354891780-ddd072d0-b1f2-4184-bb13-fbe791c58fe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MzU4OTYsIm5iZiI6MTcyMjgzNTU5NiwicGF0aCI6Ii81MDAxMDEzMC8zNTQ4OTE3ODAtZGRkMDcyZDAtYjFmMi00MTg0LWJiMTMtZmJlNzkxYzU4ZmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA1MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNTZlODYyNzg0Zjk1NzBiNTdlNDY1Y2MxZDM1NGRlZGM5MmI0NzNmODM3OGIyNmYzN2NjZWM4MTI4MTEyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2_omzPxndS32QIBvWpMx9UnRTLRJi7FcVrdqcsI-0M)

不会用 mybatis-plus-spring-boot3-starter ?

**Comment by Umenezumi** [comment]
> 还没有修复，spring-boot 3.2.5 然后 mybatis-plus 3.5.5 然后 用的 gradle 如图 还是 2.1.2 , 只能手动加个新的依赖了 ![image](https://private-user-images.githubusercontent.com/50010130/354891780-ddd072d0-b1f2-4184-bb13-fbe791c58fe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDA0OTAsIm5iZiI6MTcyMjg0MDE5MCwicGF0aCI6Ii81MDAxMDEzMC8zNTQ4OTE3ODAtZGRkMDcyZDAtYjFmMi00MTg0LWJiMTMtZmJlNzkxYzU4ZmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA2NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YmFjMGQyYTFmZjY5YmE0ODMwNmMyMWZiMzk0NjU2ZDg1NDhhYWRlOGJiN2NlYWMzYTFhZmI5ZTg5ODk3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._eYg7YqYzxb7c1qPGhWcWKq8B629Kb9j6e5PeoRFfNo)

你的 starter 用错了，仔细阅读下文档

**Comment by ArtistSu** [comment]
我都不知道有这个starter，我一直以为他自动根据版本变，gav都改了
