### ISSUE TITLE
建议有1到两个长期支持版本

### ISSUE THREAD

**Issue by Speily** [baomidou/mybatis-plus#5966]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
版本选择忧虑！有看版本升级记录修修补补加东西，可不可以有个长期支持版本

**Comment by VampireAchao** [comment]
嗯，长期支持版本的想法挺好，但现状来看，我们暂时没有太多精力处理。主要是资源和维护上的考虑。我们会尽量保证每个版本都尽可能稳定，同时保持更新。希望这样能帮到你，有啥问题我们随时在这
