### ISSUE TITLE
saveBatch报错，org.springframework.aop.framework.JdkDynamicAopProxy cannot be cast to com.baomidou.mybatisplus.core.override.MybatisMapperProxy

### ISSUE THREAD

**Issue by qingla666** [baomidou/mybatis-plus#5969]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
从3.4.3升级到3.5.5之后，批量保存数据saveBatch报错，升级到3.5.3版本不会报错
![图片](https://github.com/baomidou/mybatis-plus/assets/63495472/6206eec5-5418-45c9-99a5-c1c1d9b773d1)
![图片](https://github.com/baomidou/mybatis-plus/assets/63495472/2b05a1a6-677c-4da7-8d1d-051e55713d24)

### 报错信息
服务器异常，原因:org.springframework.aop.framework.JdkDynamicAopProxy cannot be cast to com.baomidou.mybatisplus.core.override.MybatisMapperProxy

**Comment by nieqiurong** [comment]
提供一下复现工程,或者提供一下basemapper变量断点信息截图.

**Comment by qingla666** [comment]
@nieqiurong 按照你的方法已修复报错，希望3.5.6版本尽快发布

**Comment by nieqiurong** [comment]
已发布3.5.6-SNAPSHOT.
