### ISSUE TITLE
请问MP还支持MySQL5吗？

### ISSUE THREAD

**Issue by thinkcodee** [baomidou/mybatis-plus#5972]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
请问MyBatis-Plus是否支持MySQL5的版本？现在因为一些问题，服务器上的MySQL版本是5.X

**Comment by nieqiurong** [comment]
支持

**Comment by thinkcodee** [comment]
> 支持

好的，多谢
