### ISSUE TITLE
apply 动态sql拼接每次拼接到where 后面？

### ISSUE THREAD

**Issue by piaohailin** [baomidou/mybatis-plus#5974]
### 当前使用版本(必填,否则不予处理)

3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

LambdaQueryWrapper queryWrapper.select
queryWrapper.select(Book.class,item -> true).apply("CASE WHEN XXXX")；

//查询条件
queryWrapper.eq

//分页信息
Page

//执行查询
selectPage
### 报错信息
1、apply 动态sql拼接每次拼接到where 后面？
2、用LambdaQueryWrapper 机制如何动态拼接实现 select * ，"CASE WHEN XXXX" as newXXXX；

参考案例：https://blog.csdn.net/weixin_44060488/article/details/131001948

**Comment by miemieYaho** [comment]
1. apply本来就是where部分的
2. 不支持
