### ISSUE TITLE
page排序机制在高版本下自动被过滤 等于号= 问题

### ISSUE THREAD

**Issue by piaohailin** [baomidou/mybatis-plus#5976]
### 当前使用版本(必填,否则不予处理)

3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

早期代码如下：
       page.addOrder(OrderItem.asc("dept_name"))
                .addOrder(OrderItem.asc("CASE " +
                        "WHEN comXX = 'XX' THEN 1 " +
                        "WHEN comXX = 'XX' THEN 2 " +
                        "ELSE 3 " +
                        "END"));

### 报错信息

升级后，拼接的sql 被去掉“=”导致无法执行。

目前是用last拼接的方式应付过去，总觉得用标准的addOrder处理更好一点，自动被过滤“=”如何解决？

**Comment by binfengyan** [comment]
order by  后面使用 = 有什么特殊业务场景吗？ 一般正常不会在order by 里面添加逻辑判断，麻烦描述具体一些

**Comment by piaohailin** [comment]
CASE WHEN sensor = 'A' THEN 1 " +
                "WHEN sensor = 'B' THEN 2 " +
                "ELSE 3 END
类似的这样语句

**Comment by piaohailin** [comment]
> order by 后面使用 = 有什么特殊业务场景吗？ 一般正常不会在order by 里面添加逻辑判断，麻烦描述具体一些

CASE WHEN sensor = 'A' THEN 1 " +
"WHEN sensor = 'B' THEN 2 " +
"ELSE 3 END
类似的这样语句

**Comment by qmdx** [comment]
请使用  wrapper.last (...)   处理，不建议 传入 SQL 片段
