### ISSUE TITLE
JDK升级21，springboot升级3.2.3，mybatis-plus使用最新版3.5.5，报异常！

### ISSUE THREAD

**Issue by ANGLIOK** [baomidou/mybatis-plus#5981]
### 当前使用版本(必填,否则不予处理)
springboot.version : 3.2.3
JDK.version : 21
mybatis-plus.version: 2.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动springboot程序报错

![image](https://github.com/baomidou/mybatis-plus/assets/62325709/2bdc0538-39d9-4e53-8c49-8e393f50a7b7)

# 猜想
翻阅资料感觉应该是 mybatis-plus包下的 mybatis-spring 2+版本引起的
![image](https://github.com/baomidou/mybatis-plus/assets/62325709/a528be1f-3f73-4f0b-b4c0-fe9de09c537d)

手动引入：
![image](https://github.com/baomidou/mybatis-plus/assets/62325709/66d7f48e-5ac1-49b9-9f29-d6dcb9341370)

问题解决，这个官方包是否可以修复一下；

**Comment by nieqiurong** [comment]
#5747
