### ISSUE TITLE
sql拼接错误

### ISSUE THREAD

**Issue by sscfaith** [baomidou/mybatis-plus#599]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
sql拼接错误，order by前面有and

### 重现步骤
Category category = new Category();
category.setStatus("valid");

QueryWrapper<Category> categoryQueryWrapper = new QueryWrapper<>(category);

if (StringUtils.isNotBlank(name))
     categoryQueryWrapper.like("NAME_", name);

categoryQueryWrapper.orderByAsc("SORT_");

List<Category> categoryList = category.selectList(categoryQueryWrapper);

### 报错信息
![image](https://user-images.githubusercontent.com/23066241/47840998-1beb5880-ddf3-11e8-8991-dbb677e9fd46.png)

**Comment by miemieYaho** [comment]
能发一下你的全局配置以及 entity 信息吗?我们好复现

**Comment by sscfaith** [comment]
@miemieYaho 

- entity

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("ACT_RE_CATEGORY")
public class Category extends Model<Category> implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId(value = "ID_", type = IdType.AUTO)
    private Integer id;

    @TableField("NAME_")
    private String name;

    @TableField("SORT_")
    private Integer sort;

    @TableField("STATUS_")
    private String status;

    @TableField("ICON_")
    private String icon;

    /**
     * 当前第几页
     */
    @TableField(exist = false)
    @JsonIgnore
    private Integer current = 1;

    /**
     * 每页显示几条
     */
    @TableField(exist = false)
    @JsonIgnore
    private Integer limit = 10;

}

- config

![image](https://user-images.githubusercontent.com/23066241/47887265-66171d00-de79-11e8-813b-b7e3104b3b66.png)

**Comment by miemieYaho** [comment]
使用 `3.0.6.2-SNAPSHOT` 版本试试

**Comment by miemieYaho** [comment]
3.0.6.3-SNAPSHOT

**Comment by miemieYaho** [comment]
```xml
<repository>
    <id>snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```

**Comment by sscfaith** [comment]
3.0.6已无此问题
