### ISSUE TITLE
springboot3.1.9 mybatis-plus3.5.5分页失败

### ISSUE THREAD

**Issue by Ewannai** [baomidou/mybatis-plus#5992]
### 当前使用版本(必填,否则不予处理)
springboot3.1.9 mybatis-plus3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用page进行分页查询

### 重现步骤(如果有就写完整)
使用page分页查询，返回不正确，且total=0

**Comment by nieqiurong** [comment]
提供复现工程.
