### ISSUE TITLE
T getOne(Wrapper<T> queryWrapper)方法，不同环境返回的结果不一样

### ISSUE THREAD

**Issue by 731931316** [baomidou/mybatis-plus#5996]
### 当前使用版本(必填,否则不予处理)

3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用getOne（queryWrapper）方法时，生产环境和测试环境都会查出来两条，但是只有生产环境报错，报错信息为：Expected one result (or null) to be returned by selectOne(), but found: 2
测试环境并没有报错，定位不到问题

### 重现步骤(如果有就写完整)
生产环境调用getOne（queryWrapper）时报错，都没有传throwEx = false。不同环境结果不一样，很奇怪

### 报错信息
Expected one result (or null) to be returned by selectOne(), but found: 2

**Comment by miemieYaho** [comment]
以git形式给出你的复现demo

**Comment by wangbiao5901** [comment]
queryWrapper 条件查询出了2条数据，throwEx 默认值是true，默认会抛异常

**Comment by VampireAchao** [comment]
传一下throwEx = false，感谢
