### ISSUE TITLE
ORDER BY FIELD(status, 2, 1, 3)，可否有方法实现，而不用使用写sql

### ISSUE THREAD

**Issue by walkdy2019** [baomidou/mybatis-plus#5999]
### 当前使用版本(必填,否则不予处理)
版本号：3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
现有的方法里，都只是关于 order by asc/desc，编译成脚本就是 order by status asc/desc这样的简单排序，
能否把脚本 order by field(字段, 值1，值2，值3......)也提成方法呢？

**Comment by miemieYaho** [comment]
非标准sql不考虑
