### ISSUE TITLE
打印两次logo日志, 是否存在重复加载问题

### ISSUE THREAD

**Issue by hecunsheng** [baomidou/mybatis-plus#6002]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
为什么会打印两次logo日志, 是否存在重复加载问题, 原因是什么?
尝试排除重复依赖不能解决此问题

### 重现步骤(如果有就写完整)
引入依赖启动出现

### 报错信息

Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2024-03-18 21:19:53.676  WARN 10503 --- [           main] c.b.m.core.injector.AbstractMethod       : [com.logtech.agent.common.mapper.agent.MessageMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.4.2 
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.4.2

**Comment by hecunsheng** [comment]
<img width="1270" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/15025081/b0ea4fcb-3012-476b-9114-7880c8743921">

**Comment by nieqiurong** [comment]
检查项目是否初始化多个sqlsessionfactorybean

**Comment by hecunsheng** [comment]
是加载了2个, 不影响是吧
