### ISSUE TITLE
DataChangeRecorderInnerInterceptor数据变动记录插件记录枚举字段有问题

### ISSUE THREAD

**Issue by IceSugarLemon** [baomidou/mybatis-plus#6004]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
枚举字段

### 重现步骤(如果有就写完整)
类字段
<img width="268" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/28007467/9783b8f3-97a8-4ea3-94f1-cf84e91d5924">

枚举类
<img width="276" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/28007467/429ebff6-1093-4023-94cc-c757a781b358">

打印的变动日志
<img width="457" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/28007467/9038a9a3-20bd-4de0-8be2-aaa7c2260f7d">

**Comment by nieqiurong** [comment]
试试3.5.6

**Comment by nieqiurong** [comment]
#6430
