### ISSUE TITLE
实体增量属性更新，公共填充属性无法更新

### ISSUE THREAD

**Issue by 654894017** [baomidou/mybatis-plus#6005]
### 当前使用版本(必填,否则不予处理)

3.4.34

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

UpdateWrapper<A> wrapper = new UpdateWrapper<>();
wrapper.set("a1", "a1")
wrapper.eq("id", 1L);
mapper.update(null, wrapper);   

部分属性字段更新，MetaObjectHandler 的 updateFill方法不会被调用，无法更新公共字段，比如updateTime， 实体类属性的“FieldFill.INSERT_UPDATE”都已配置。

我希望的执行语句应该是这样的

update a set a1 = 'a1' , updateTime= 123123123 where id = 1L;    updateTime值是MetaObjectHandler设置进去的

**Comment by VampireAchao** [comment]
UpdateWrapper目前不会触发自动填充，需要自动填充请使用updateById
