### ISSUE TITLE
多租户插件在多线程下无法获取到session

### ISSUE THREAD

**Issue by xxp520** [baomidou/mybatis-plus#6007]
### 当前使用版本(必填,否则不予处理)
mybatis-plus：3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用applicationEventPublisher发布一个异步事件
<img width="1052" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/42729495/0e139068-d529-45fb-b0f1-2bf046cba7e5">
mybatis-plus插件配置：
<img width="1061" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/42729495/5bbaa2e7-e19a-4f0f-a650-7f05d27907e5">
使用spring提供的线程池ThreadPoolTaskExecutor，传递session的配置：
<img width="840" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/42729495/2080c44a-d123-4a5e-92de-ffd13fa72d13">

**Comment by HillCheuang** [comment]
你可以将session塞入到线程上下文中解决这个问题，ThreadLocal
