### ISSUE TITLE
阿里的oceanbase,分页语法问题

### ISSUE THREAD

**Issue by luygege** [baomidou/mybatis-plus#6009]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-extension 3.4.*

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
数据库是阿里的oceanbase，oracle租户，分页的时候会使用limit，也就是mysql的分页方式，但实际上应该是oracle的分页语法
![dba19e62879d7fb1f3495b6dfbb3b428](https://github.com/baomidou/mybatis-plus/assets/57478167/701b49e1-fd3a-4d52-8487-83317b624adf)
![be297b7ffc740cb50a939fcbb2330004](https://github.com/baomidou/mybatis-plus/assets/57478167/04d05d5b-0de8-4d3d-bda2-52e476171a34)

**Comment by nieqiurong** [comment]
此数据库兼容两种语法,手动指定
