### ISSUE TITLE
建议*Wrapper类，提供一个清除参数的方法。

### ISSUE THREAD

**Issue by soulmz** [baomidou/mybatis-plus#601]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
LambdaQueryWrapper 这个包装类，可否提供一个清除参数方法？

需要在同一个方法里，使用多次查询。否则就要重新new一个对象了..

### 重现步骤

    @Test
    public void test() {
        LambdaQueryWrapper<User> queryWrapper = new LambdaQueryWrapper<>();
        queryWrapper.eq(User::getRoleId, 124);
        this.userMapper.selectList(queryWrapper);
        // SQL: select * from user where role_id = 124
        // 我希望这里能清除掉上面的参数，重新进行包装。例如 queryWrapper.clean();
        queryWrapper.eq(User::getId, 1234);
        this.userMapper.selectOne(queryWrapper);
        // SQL: select * from user where role_id = 124 and id = 1234
        // 期望的SQL: select * from user where id = 1234
    }

**Comment by qmdx** [comment]
重新 new 一个不就好了

**Comment by veaxcw** [comment]
赞同，建议提供一个flush sql封装器的方法，避免new很多不必要的对象  flush 后可以直接复用同一个sqlwrapper
