### ISSUE TITLE
`new ServiceImpl()`会抛出null异常

### ISSUE THREAD

**Issue by yl-yue** [baomidou/mybatis-plus#6010]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
如果采用`new ServiceImpl()`类初始化时`GenericTypeUtils.resolveTypeArguments(getClass(), ServiceImpl.class);`为null。

为什么我是`new ServiceImpl()`而不是继承，为了剔除一些默认方法，给团队做定制规范使用。

```java
public abstract class BaseService<M extends BaseMapper<T>, T> {

    @Autowired
    protected M baseMapper;
    private ServiceImpl<M, T> serviceImpl = new ServiceImpl<>();
    @SuppressWarnings("unchecked")
    protected Class<T> entityClass = (Class<T>) ClassUtil.getTypeArgument(getClass(), 1);

    @PostConstruct
    private void init() {
        ReflectUtil.setFieldValue(serviceImpl, "baseMapper", baseMapper);
        ReflectUtil.setFieldValue(serviceImpl, "entityClass", entityClass);
        ReflectUtil.setFieldValue(serviceImpl, "mapperClass", (Class<T>) ClassUtil.getTypeArgument(getClass(), 0));
    }
}
```

### 报错信息
```java
Caused by: java.lang.NullPointerException: null
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.currentModelClass(ServiceImpl.java:129) ~[mybatis-plus-extension-3.5.5.jar:3.5.5]
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.<init>(ServiceImpl.java:76) ~[mybatis-plus-extension-3.5.5.jar:3.5.5]
	at ai.yue.library.data.mybatis.service.BaseService.<init>(BaseService.java:45) ~[classes/:na]
```

**Comment by Jasonyou-boy** [comment]
### 泛型的类型是从class文件分析出来的，问题出在GenericTypeUtils.resolveTypeArguments(getClass(), ServiceImpl.class)中的getClass()

在继承的时候获得的是继承者的class信息，直接new ServiceImpl时getClass()获得的是它本身 ，它本身class中泛型参数是M，T。
![image](https://github.com/baomidou/mybatis-plus/assets/96352227/9b75ba9c-7a85-49e0-b39d-9be4361b6d72)
直接new的情况
![image](https://github.com/baomidou/mybatis-plus/assets/96352227/568a7c33-1090-424a-83a6-c55ba172998e)
继承后的情况
![image](https://github.com/baomidou/mybatis-plus/assets/96352227/5437d821-86af-4524-8ab2-59b3375a2d91)
![image](https://github.com/baomidou/mybatis-plus/assets/96352227/aadc4e73-2e55-455f-99b9-5f9df5ff3278)
返回为空后currentModelClass（）访问了该数组

**Comment by nieqiurong** [comment]
本身ServiceImpl是要设计成abstract的,并不支持你这种写法.

**Comment by yl-yue** [comment]
感谢回复，我已去除了套娃封装，改用直接继承`ServiceImpl`方式，在文档中写明了规范方式
