### ISSUE TITLE
填充List时的问题

### ISSUE THREAD

**Issue by arenick001** [baomidou/mybatis-plus#6012]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用in语句时出现

### 重现步骤(如果有就写完整)
这是一个很诡异的bug
![图片](https://github.com/baomidou/mybatis-plus/assets/80769355/dce19ba6-1fc4-43f4-820b-2cc887c0bc02)
这个图片中可以看到，当我直接使用字符串时查询到14条数据，但是。。。
![图片](https://github.com/baomidou/mybatis-plus/assets/80769355/583af8d0-e9ea-48ff-9543-5f7f70e070c2)
当我使用List存放时，查到的数据条数为0，尽管语句一模一样。。。
但最大的问题就是在另一个子模块我也传入了一个List使用了in关键字，没有出现问题。。。
lombok日志级别是DEBUG，没有出现任何报错

### 报错信息
none

**Comment by nieqiurong** [comment]
你认为List类型toString的格式是什么样的呢

**Comment by VampireAchao** [comment]
こんにちは、

おっしゃる問題について確認しました。おそらく、Listの要素が文字列化（toString）された結果を誤って使用している可能性があります。IN 文を使用する際には、Listの要素が正しく文字列化されていないことが原因で、期待外れのSQLが生成されることがあります。

以下の点を確認していただければと思います：

Listを直接IN文に渡す際は、要素が文字列化されていないことを確認してください。例えば、Listの要素が数値型の場合、"[1, 0]"という文字列ではなく、1, 0という形式で渡される必要があります。
もしまだ問題が解決しない場合は、最小限の再現可能なデモをGitHubにアップロードしていただければと思います。このデモは、H2データベースを使用している場合、または統合テストで再現できるようにしてください。
私たちはこの問題を解決するためのお手伝いをし、より具体的な情報をいただければ幸いです。

よろしくお願いいたします。
