### ISSUE TITLE
【BUG】mybatis-plus.configuration-properties配置项无法加载指定的外部参数配置文件

### ISSUE THREAD

**Issue by darren-wang** [baomidou/mybatis-plus#602]
### 当前使用版本(必须填写清楚，否则不予处理)
使用mybatis-plus-boot-starter-3.0.1

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
我们使用.properties文件而不是yaml配置springboot应用，希望在另一个.properties文件中外部化一些mybatis的参数。

在MP的文档中看到了`mybatis-plus.configuration-properties`这个配置项，给出的示例是：
```yaml
mybatis-plus:
    configuration-properties: classpath:mybatis/config.properties
```
从文档上看容易给人一种能够直接将`mybatis/config.properties`文件里面的内容加载进去的感觉，但是我们在application.properties文件里这么配了的时候不生效。SB并没有把后面指定的properties文件内容加载成一个`Properties`，而是生成了一个key为`classpath`, value是`mybatis/config.properties`的`Properties`对象.

我们目前的做法是将外部参数的.properties文件用代码的方式读入到一个`Properties`文件中，再将它设置到`MybatisConfiguration`的`variables`域中。

`mybatis-plus.configuration-properties`配置项能不能够支持在值中允许配置一或多个外部参数配置文件的位置，能够直接将外部参数配置文件读进来的功能，这样我们就不用自己写代码去读取这些配置文件了。

**Comment by miemieYaho** [comment]
注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!
