### ISSUE TITLE
使用自定义Mapper进行分页查询时，如果Page中的model字段名与数据库的不一致，也加上了@TableField进行映射，但结果集中该字段仍然为空

### ISSUE THREAD

**Issue by SeniorArchitect** [baomidou/mybatis-plus#6025]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用自定义Mapper进行分页查询时，如果Page中的model字段名与数据库的不一致，也加上了@TableField进行映射，但结果集中该字段仍然为空，使用wrapper方式查询就没问题！

### 重现步骤(如果有就写完整)
MyPage<UserDO> queryUserList(@Param("page") MyPage<?> page, @Param("userSex") Integer userSex);

@TableName("t_user")
@Getter
@Setter
@ToString(callSuper = true)
public class UserDO extends AbstractModel {

	private static final long serialVersionUID = -975454591881697576L;

	@TableField(value = "user_name")
	private String userName;

	@TableField(value = "phone_num")
	private String phoneNum;

	@TableField(value = "passwd")
	private String password;

	@TableField(value = "user_avatar")
	private String userAvatar;

	@TableField(value = "user_sex")
	private Integer userSex;
}

  	<select id="queryUserList" resultType="com.dh.dhuser.dal.model.UserDO">
		SELECT
			* 
		FROM
			t_user t 
		WHERE
			t.user_sex = #{userSex} 
			AND t.state = 1
	</select>

### 报错信息
 查询的结果集password字段为空

**Comment by miemieYaho** [comment]
注解只对entity生效,你要自己写'as xxx'

**Comment by SeniorArchitect** [comment]
3Q!
