### ISSUE TITLE
作者您好，ktUpdateChainWrapper 的 sqlSet 方法，params 少个*号，可否尽快修复一版进入 maven 库？

### ISSUE THREAD

**Issue by liuenzuo666** [baomidou/mybatis-plus#6027]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
kt 的 lambda 方式 ktUpdate().eq(表名：：id，1).setSql(" 列名= 列名 +1").update()
最新版本和 git 代码库中都存在此问题

### 重现步骤(如果有就写完整)
上方引起原因可百分百复现
少写一个*号导致 params 调用 kyUpdateWrapper的 setSql 的时候params 没有展开

### 报错信息
报错信息没有参考意义，在传递不同形式的参数的时候，报错信息不同。

**Comment by VampireAchao** [comment]
在做了在做了

**Comment by VampireAchao** [comment]
https://github.com/baomidou/mybatis-plus/commit/81bcb9742ed83220f9bb7a12a579f6aca5bda8fd

**Comment by liuenzuo666** [comment]
感谢，是否可以告知何时可以推送 maven 库中以便我们调整项目代码

**Comment by VampireAchao** [comment]
> 感谢，是否可以告知何时可以推送 maven 库中以便我们调整项目代码

+vx： apacheachao

推了我叫你
