### ISSUE TITLE
能否考虑加入一个 eqSql 方法？

### ISSUE THREAD

**Issue by Muyangmin** [baomidou/mybatis-plus#6028]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
现有的 Wrapper 可以通过 `inSql`/`leSql`/`geSql` 来完成嵌套子查询，但是没有 `eqSql` 方法。虽然使用场景比较小众，但加上应该没有别的副作用。

#### 场景示例
现有一张表，定期或不定期会写入数据，每组数据有统一的时间戳。时间戳是有序的索引列。
```SQL
CREATE TABLE t_example(
  //...
  DataTimestamp DATETIME(3) NOT NULL COMMENT '数据时间戳',
)
```
假设现在仅希望查询最新的数据，我们可以这样写：
```SQL
SELECT * FROM t_example WHERE DataTimestamp = (SELECT MAX(DataTimestamp) FROM t_example);
```
但是，现在的 mp 版本没有 eqSql 方法。希望能加上。

**Comment by miemieYaho** [comment]
你要怎么用?apply不能满足?

**Comment by Muyangmin** [comment]
apply 可以完成，大概是 `apply("$columnName = $SQL")` 这样子。不过我当时的第一反应是 eqSql，也许从语义上会更直观一些，且减少一些模板字符串：`eqSql(columnName, SQL)`。

#6029  是我参考 `inSql`方法加入的对称的定义。
