### ISSUE TITLE
Postgresql优化建议

### ISSUE THREAD

**Issue by lehoso** [baomidou/mybatis-plus#6030]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-core-3.0.7.1~mybatis-plus-core-3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
IN关键字 在Postgresql中有更好的替代，使用any （values|array） 会比in效果更好 ，因为in关键字数据库默认长度限制在1000个以内。且性能更加，不会走subplan，因此不涉及hash table的问题。和work_mem设置大小无关。

**Comment by miemieYaho** [comment]
与mp无关
