### ISSUE TITLE
sqlite 保存的时候获取数据库增ID报错

### ISSUE THREAD

**Issue by cktk** [baomidou/mybatis-plus#6032]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
引入 sqlite 最新版本的依赖 保存数据的时候报错  报错原因是获取生成的主键错误
这个版本可以正常的sav数据 并获取到自增主键ID
可用版本
```xml
       <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.42.0.1</version>
        </dependency>
```

最新版本
```xml
<dependency>
    <groupId>org.xerial</groupId>
    <artifactId>sqlite-jdbc</artifactId>
    <version>3.45.2.0</version>
</dependency>
```

 在最新版本的sqlite-jdbc中无法获取数据库自增ID

### 重现步骤(如果有就写完整)
  3.43.0.0 的发布日志
🚨 删除了对 Statement#getGeneratedKeys 的支持：不再支持 getGeneratedKeys

### 参考地址 
https://github.com/xerial/sqlite-jdbc/issues/963

**Comment by miemieYaho** [comment]
你是觉得我们能修改jdbc吗?

**Comment by nieqiurong** [comment]
3.45.0.0驱动又恢复支持了.

https://github.com/xerial/sqlite-jdbc/commit/f7d49f63172462c810219a7b53f5c0e667e11ce8
