### ISSUE TITLE
SQL Server saveBatch批量插入报错

### ISSUE THREAD

**Issue by jintonghuoya** [baomidou/mybatis-plus#6033]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
SQL Server不支持批量返回Id导致报错

**Comment by zxtswcx** [comment]
你好，这个是怎么解决的？

**Comment by jintonghuoya** [comment]
> ### 重现步骤(如果有就写完整)

自己写一个批量不返回id的基类
