### ISSUE TITLE
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("     at line 5, column 12.

### ISSUE THREAD

**Issue by sly-APalmCat** [baomidou/mybatis-plus#6040]
### 当前使用版本(必填,否则不予处理)

com.baomidou:mybatis-plus-boot-starter:3.5.4.1
com.baomidou:mybatis-plus:3.5.4.1
com.github.jsqlparser:jsqlparser:4.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

IF(ie.province IS NULL || ie.`province` = "", "", "-") AS country_area

### 重现步骤(如果有就写完整)

 对 ||  |  这种符号报错。
sql中执行就是了。

### 报错信息

net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 5, column 12.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "INTO"
    "START"
    "WINDOW"
    "["
    "^"
    "|"

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException

**Comment by nieqiurong** [comment]
|| 换成 or
