### ISSUE TITLE
原始sql  SELECT * FROM *WHERE (apply_code NOT LIKE '%001%' ）  转换后的  SELECT * FROM *WHERE (NOT apply_code NOT LIKE '%001%' ） 为啥 where not ** not like 不是 直接 not like

### ISSUE THREAD

**Issue by zhangyufengg** [baomidou/mybatis-plus#6047]
### 当前使用版本(必填,否则不予处理)
3.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
是

### 重现步骤(如果有就写完整)

applyQueryWrapper.notlike("");
applyMapper.selectPage(page, applyQueryWrapper);
经过
Statements statements = CCJSqlParserUtil.parseStatements(sql);   拦截后
sql  多加了一个not 

### 报错信息
原始sql  SELECT * FROM *WHERE (apply_code NOT LIKE '%001%' ） 
转换后的  SELECT * FROM *WHERE (NOT apply_code NOT LIKE '%001%' ） 为啥 where not ** not like 不是 直接 not like

**Comment by miemieYaho** [comment]
升级版本
