### ISSUE TITLE
jdk21下使用分页total=0 pages=0

### ISSUE THREAD

**Issue by wm475390847** [baomidou/mybatis-plus#6048]
### 当前使用版本(必填,否则不予处理)
jdk21
mybatis-plus版本：
```
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
 </dependency>
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用jdk8可以获取total，使用jdk21无法获取

### 重现步骤(如果有就写完整)
分页拦截器代码
```
@Configuration
public class MybatisPlusConfig {

    /**
     * 分页插件 3.5.X
     */
    @Bean
    public PaginationInnerInterceptor paginationInnerInterceptor() {
        PaginationInnerInterceptor paginationInterceptor = new PaginationInnerInterceptor();
        // 设置最大单页限制数量，默认 500 条，-1 不受限制
        paginationInterceptor.setMaxLimit(-1L);
        paginationInterceptor.setDbType(DbType.MYSQL);
        // 开启 count 的 join 优化,只针对部分 left join
        paginationInterceptor.setOptimizeJoin(true);
        return paginationInterceptor;
    }

    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor mybatisPlusInterceptor = new MybatisPlusInterceptor();
        mybatisPlusInterceptor.setInterceptors(Collections.singletonList(paginationInnerInterceptor()));
        return mybatisPlusInterceptor;
    }
}
```

结果：
分页
jdk21：total为0
<img width="505" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/68719907/ea006cb7-2856-44a2-ab54-9bdd70058ad2">

jdk8：total不为0
<img width="679" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/68719907/2f5801fd-b267-4963-bec9-60f8c95db4ae">

### 报错信息

无报错信息
![image](https://github.com/baomidou/mybatis-plus/assets/68719907/179c09aa-8e76-484a-84b3-ec10b8dc09c2)
打印为0
![image](https://github.com/baomidou/mybatis-plus/assets/68719907/6c3ff6be-82fc-4ef2-a8d8-2359c0b0b001)

**Comment by nieqiurong** [comment]
看更新日志,后面的版本才对新的jdk才有适配,还不行就提供复现工程

**Comment by wm475390847** [comment]
好像不是版本的问题，我看jdk8也没有total了 我在看看

**Comment by liguochuan00** [comment]
如何解决的？我的也发现这个问题了，我是JDK17
