### ISSUE TITLE
batch操作，数据没有入库

### ISSUE THREAD

**Issue by myxland** [baomidou/mybatis-plus#605]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
数据库为Oracle 12c，使用【saveBatch】或者【saveOrUpdateBatch】的时候，数据没有提交到数据库。
是否需要独立配置什么东西？

### 重现步骤
调用IService的【saveBatch】或者【saveOrUpdateBatch】接口

### 报错信息
无
数据没有插入数据库

**Comment by miemieYaho** [comment]
junit 测试的?

**Comment by myxland** [comment]
不是，直接spring rest测试的，画面提交的数据没有入库。

**Comment by qmdx** [comment]
错误呢？异常信息呢

**Comment by keepcoolwu** [comment]
估计没有配置事务
