### ISSUE TITLE
自动生成代码配置禁用模板不生效

### ISSUE THREAD

**Issue by ghost** [baomidou/mybatis-plus#6060]
### 当前使用版本(必填,否则不予处理)

3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
.strategyConfig()
 .mapperBuilder()
.disableMapperXml()//禁用mapperxml文件生成不生效

**Comment by nieqiurong** [comment]
使用3.5.7-SNAPSHOT试试

**Comment by iqolome** [comment]
> 使用3.5.7-SNAPSHOT试试

貌似没地方可以找到这个版本呢,  可以发个版本吗 @nieqiurong
