### ISSUE TITLE
void org.apache.ibatis.session.Configuration.parsePendingMethods(boolean)

### ISSUE THREAD

**Issue by bchengwang** [baomidou/mybatis-plus#6063]
### 当前使用版本(必填,否则不予处理)
3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:122)

The following method did not exist:

    'void org.apache.ibatis.session.Configuration.parsePendingMethods(boolean)'

The calling method's class, com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder, was loaded from the following location:

    jar:file:/D:/DevInstall/Maven/LocalRepository/com/baomidou/mybatis-plus-core/3.5.6/mybatis-plus-core-3.5.6.jar!/com/baomidou/mybatisplus/core/MybatisMapperAnnotationBuilder.class

The called method's class, org.apache.ibatis.session.Configuration, is available from the following locations:

    jar:file:/D:/DevInstall/Maven/LocalRepository/org/mybatis/mybatis/3.5.14/mybatis-3.5.14.jar!/org/apache/ibatis/session/Configuration.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.ibatis.session.Configuration: file:/D:/DevInstall/Maven/LocalRepository/org/mybatis/mybatis/3.5.14/mybatis-3.5.14.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder and org.apache.ibatis.session.Configuration

### 重现步骤(如果有就写完整)
使用下面版本
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-dependencies</artifactId>
    <version>3.2.4</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
    <version>3.5.6</version>
</dependency>
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>3.0.3</version>
</dependency>
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter-test</artifactId>
    <version>3.0.3</version>
    <scope>test</scope>
</dependency>

### 报错信息

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:122)

The following method did not exist:

    'void org.apache.ibatis.session.Configuration.parsePendingMethods(boolean)'

The calling method's class, com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder, was loaded from the following location:

    jar:file:/D:/DevInstall/Maven/LocalRepository/com/baomidou/mybatis-plus-core/3.5.6/mybatis-plus-core-3.5.6.jar!/com/baomidou/mybatisplus/core/MybatisMapperAnnotationBuilder.class

The called method's class, org.apache.ibatis.session.Configuration, is available from the following locations:

    jar:file:/D:/DevInstall/Maven/LocalRepository/org/mybatis/mybatis/3.5.14/mybatis-3.5.14.jar!/org/apache/ibatis/session/Configuration.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.ibatis.session.Configuration: file:/D:/DevInstall/Maven/LocalRepository/org/mybatis/mybatis/3.5.14/mybatis-3.5.14.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder and org.apache.ibatis.session.Configuration

**Comment by bchengwang** [comment]
根据排查是因为和mybatis-spring-boot-starter中的mybatis版本冲突

**Comment by panovr** [comment]
So how to solve this error?

**Comment by bchengwang** [comment]
@panovr  Currently, mybatis-spring-boot-starter is not compatible with the latest version of MyBatis. My current solution is to use version 3.5.5 of MyBatis Plus.
