### ISSUE TITLE
多租户插件的TenantLineHandler接口可以扩展一个方法ignoreTable，入参增加 当前库名

### ISSUE THREAD

**Issue by nicky1** [baomidou/mybatis-plus#6069]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
一个项目中引入了多个数据库，需要针对特定的数据库进行排除逻辑。

**Comment by nieqiurong** [comment]
提供完整需求描述，以及期望需要的结果

**Comment by sirius19** [comment]
com.baomidou.mybatisplus.annotation.InterceptorIgnore
