### ISSUE TITLE
DataChangeRecorderInnerInterceptor出现格式转换错误org.postgresql.util.PSQLException: conversion to class

### ISSUE THREAD

**Issue by Basil1991** [baomidou/mybatis-plus#6073]
### 当前使用版本(必填,否则不予处理)

3.5.6

使用Postgres

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
DataChangeRecorderInnerInterceptor 类中将值会手动转为String类型
<img width="793" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/5119689/12e214ec-8984-470e-a7c2-2c464685cc00">

而在读取时会报错
<img width="901" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/5119689/989e3d6e-5c69-4dbe-a6c7-50e47c98c86f">

### 报错信息
<img width="1614" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/5119689/9533a5d0-8932-4353-bed6-2538867dcc1b">

**Comment by MrXiaoMo** [comment]
我也遇到了相同的错误

**Comment by sirius19** [comment]
有没有详细点的描述，什么样的更新语句等等

**Comment by bruce-pang** [comment]
Postgres版本是多少?

**Comment by q821863269** [comment]
我的解决方案：
1、将官方的DataChangeRecorderInnerInterceptor复制出来，创建MyDataChangeRecorderInnerInterceptor
2、修改如下两处代码
![image](https://github.com/baomidou/mybatis-plus/assets/37721392/b74f422e-42a3-4925-b343-6f61243952fb)
![image](https://github.com/baomidou/mybatis-plus/assets/37721392/37c9fa39-5c90-458b-937c-676ef6dc0885)
3、添加拦截器的时候，将DataChangeRecorderInnerInterceptor更换为自定义的MyDataChangeRecorderInnerInterceptor

**Comment by nieqiurong** [comment]
#6430
