### ISSUE TITLE
V3.5.6新增接口存在问题

### ISSUE THREAD

**Issue by richwxd** [baomidou/mybatis-plus#6078]
### 当前使用版本(必填,否则不予处理)

3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/22185826/44b7f9e5-db4f-4fe9-8736-4ee2c262bdf2)

### 重现步骤(如果有就写完整)
用了泛型，但是方法未使用，导致任何继承的方法无法使用泛型类

### 报错信息

无法编译

**Comment by yangyang0507** [comment]
麻烦您好好看看注释和上面的那个 parse 方法

**Comment by richwxd** [comment]
要的是继承类复写 toJson 方法，无法使用泛型，并不是parse方法。 toJson方法内传入的应该是T

**Comment by richwxd** [comment]
要的是继承类复写 toJson 方法，无法使用泛型，并不是parse方法。 toJson方法内传入的应该是T

> 麻烦您好好看看注释和上面的那个 parse 方法
