### ISSUE TITLE
@EnumValue枚举使用出错

### ISSUE THREAD

**Issue by LanXueRuo** [baomidou/mybatis-plus#6080]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-spring-boot3-starter 3.8.6
mysql

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/167635523/cb2b1a5d-786e-47d7-8ac1-0bfdfaa1653b)
当使用 @EnumValue 注解枚举的属性为Character字符类型的时候，p6spy打印sql是没问题的，但是到了执行的时候会进行序列化，导致插入数据库的时候出错。
改成String类型就不会有这个问题了

### 报错信息
 ![image](https://github.com/baomidou/mybatis-plus/assets/167635523/dfd4c2e4-b7ad-4724-858c-28e9aad5fe27)

**Comment by miemieYaho** [comment]
不支持character
