### ISSUE TITLE
BaseMapper#updateById会将字段更新为null

### ISSUE THREAD

**Issue by wzkris** [baomidou/mybatis-plus#6083]
### 当前使用版本(必填,否则不予处理)
3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/90759163/b91086ff-fcec-48f7-a925-868313cf3fa9)
根据id去更新两个字段，其他全部都是null，但是执行结果会将update_at和update_id更新成null
![image](https://github.com/baomidou/mybatis-plus/assets/90759163/e93bc459-3a3d-49cd-8c00-5afe14dd4876)

### 重现步骤(如果有就写完整)

经过测试发现是@TableField(fill = FieldFill.INSERT_UPDATE)注解问题，移除则不会出现

### 报错信息
没有报错

**Comment by wzkris** [comment]
经过测试，FieldFill为UPDATE和INSERT_UPDATE时，使用updateById方法会直接将标记的字段更新成null，请问是什么原因？

**Comment by miemieYaho** [comment]
没什么原因,就这样

**Comment by wzkris** [comment]
> 没什么原因,就这样

null也默认填充吗？null不应该过滤才对吗？

**Comment by VampireAchao** [comment]
检查下`com.baomidou.mybatisplus.core.handlers.MetaObjectHandler`配置
