### ISSUE TITLE
mybatis-plus-boot-starter:3.1.1升级到mybatis-plus-spring-boot3-starter:3.5.4 save 不自动清空主键内容

### ISSUE THREAD

**Issue by BlackJia** [baomidou/mybatis-plus#6092]
### 当前使用版本(必填,否则不予处理)
老版本：com.baomidou:mybatis-plus-boot-starter:3.1.1
mybatis:3.5.1
spring-boot-starter-parent:2.3.12.RELEASE

新版本：com.baomidou:mybatis-plus-spring-boot3-starter:3.5.4
mybatis:3.5.13
springtboot:3.0.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

升级前：save、saveBatch方法 主键即使传入值，也会被清空，执行成功。
升级后：save、saveBatch方法 主键传入值，不会被清空 -> 修改什么配置可以兼容

新老版本打断点，到org.apache.ibatis.scripting.xmltags.MixedSqlNode这里。
这个类的私有属性 contents 新版本把主键ID放出来了，老版本过滤掉了。没找到这个contents赋值的地方。

比如：实体类 User:id、name、gender，新增的时候id设置了值
新版本中 contents 会返回3个属性（id、name、gender），老版本只会返回2个（name、gender）

**Comment by nieqiurong** [comment]
#6006
