### ISSUE TITLE
支持一个Mapper绑定多个XML的功能

### ISSUE THREAD

**Issue by guoyangqiao** [baomidou/mybatis-plus#6094]
### 当前使用版本(必填,否则不予处理)
`3.4.3.4`

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
尝试把多个Mapper xml文件绑定到一个Mapper

### 重现步骤(如果有就写完整)
多个XML文件，只能关联到同名的XML
比如下面这个例子：
![image](https://github.com/baomidou/mybatis-plus/assets/8182636/bf60ce30-c138-4068-8b89-32756d1395e9)
Mapper定义了方法selectVoid
![image](https://github.com/baomidou/mybatis-plus/assets/8182636/3f963409-6212-403d-9467-63dcaece64a2)
方法被定义在了Ext的Mapper内
![image](https://github.com/baomidou/mybatis-plus/assets/8182636/6a475ecd-acdb-4f56-8444-16f2a6382e37)
当方法定义在Ext的Mapper中，调用报错

### 报错信息
Invalid bound statement (not found): xxx.RawEventSchemaMapper.selectVoid

**Comment by nieqiurong** [comment]
指定 mapper-locations 属性

**Comment by guoyangqiao** [comment]
xml文件和Mapper在同一个目录下，应该能直接识别

另外：
![image](https://github.com/baomidou/mybatis-plus/assets/8182636/2341b40f-df36-4cb6-a88b-30ccb822268a)
启动后仍然报找不到

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/edf60877-7071-472c-9708-af32c5d08cda)

**Comment by guoyangqiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/15142701/325494063-edf60877-7071-472c-9708-af32c5d08cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzA3MTMsIm5iZiI6MTcxNDAzMDQxMywicGF0aCI6Ii8xNTE0MjcwMS8zMjU0OTQwNjMtZWRmNjA4NzctNzA3MS00NzJjLTk3MDgtYWYzMmM1ZDA4Y2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MjFlZWE4YzcxYWE2ZmVjN2ExMTkxYjY0MDVlZGVhODRjYzU2YjFiMGU2YjZmNzBkOTYxYTI1ZDZjZjA4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XnovOGUISeqxC3InnM12MzDMT13qKEqeWnMT8xxL1FU)

感谢回复。debug看了下，Mapper scan没有扫描指定目录，导致两个mapper都没有加载。
