### ISSUE TITLE
3.3.1版本针对数据表字段做映射时，如果字段第一个前缀只有一个字母，无法转成正常的驼峰命名格式

### ISSUE THREAD

**Issue by frank250** [baomidou/mybatis-plus#6095]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Mapper文件：
![image](https://github.com/baomidou/mybatis-plus/assets/23476659/4c824e44-e182-404b-845b-95a1a55d7084)
需要返回字段：J_SALES_CHANNEL

对应的DTO文件有一个属性：
![image](https://github.com/baomidou/mybatis-plus/assets/23476659/3a8a7c2b-2532-4d15-8072-8eba9afee8b6)

对应数据表字段：J_SALES_CHANNEL
![image](https://github.com/baomidou/mybatis-plus/assets/23476659/2c5f7ef8-53b4-4e8e-b10b-852f9099b52d)

返回的数据格式：
![image](https://github.com/baomidou/mybatis-plus/assets/23476659/50c944e3-f418-4ff9-b585-fd15d964d722)

预期是正常返回 按下划线转换得到的驼峰格式 jSalesChannel，但实际返回的是：jsalesChannel

bug：验证是字段按下划线分割后，第一个前缀只有一个字母时，无法转成正常的驼峰命名格式。

### 报错信息

字段第一个前缀只有一个字母，无法转成正常的驼峰命名格式

**Comment by nieqiurong** [comment]
提的很好，下次不要再提了,要提就给json和javabean规范去提.

**Comment by VampireAchao** [comment]
这个和orm没关系，属于springmvc和json层面
