### ISSUE TITLE
继承 BaseMapper 类能否在xml层重写其中方法，后续调用方法能够执行重写方法，

### ISSUE THREAD

**Issue by coderLrf** [baomidou/mybatis-plus#6098]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://github.com/baomidou/mybatis-plus/assets/74143740/87bd2682-11bc-4d46-b74e-4eb111d61091)

### 重现步骤(如果有就写完整)
![image](https://github.com/baomidou/mybatis-plus/assets/74143740/5bddcc96-830d-4245-8081-7449b5061aa7)

**Comment by coderLrf** [comment]
不重写则执行mybatisplus自带的方法，因为传入的不是实体类对象，会报字段不存在错误

**Comment by zfh521** [comment]
在3.4.3.4版本中可以在xml的文件里覆盖BaseMapper中的默认方法，目前使用3.5.6版本，发现在xml定义selectPage无法覆盖。
我这边目前的解决办法是在BaseMapper的子类中定义同名的方法来解决这个问题。

**Comment by miemieYaho** [comment]
可以重写

**Comment by coderLrf** [comment]
但我试了一下是失效的，走的还是默认方法，会报一些dto字段不存在问题

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式
