### ISSUE TITLE
mysql 字段 加转义

### ISSUE THREAD

**Issue by tlinsion** [baomidou/mybatis-plus#610]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-boot-starter-3.0.1.jar

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
mysql 建表的时候有些字段和mysql关键字冲突了,在用QueryWrapper的时候,执行会报错.有没有什么办法可以让它自动给字段加 `  转义  `type`  类似这样的效果

### 重现步骤
dictMapper.selectList(new QueryWrapper<Dictionary>().eq("`type`", LocalConstants.BIGTYPE_MATERIAL).orderByAsc("`type`,`parent_code`,`code`"));
SELECT id,code,desc,parent_code,type,active FROM edu_dictionary WHERE `type` = ? ORDER BY `type`,`parent_code`,`code` ASC

### 报错信息
Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc,parent_code,type,active  FROM edu_dictionary  WHERE  `type` = 4 ORDER BY `t' at line 1

**Comment by miemieYaho** [comment]
没有办法,自己手动加
