### ISSUE TITLE
在继承ServiceImpl的实现类中自动注入失效

### ISSUE THREAD

**Issue by Bobo1553** [baomidou/mybatis-plus#6101]
### 当前使用版本(必填,否则不予处理)

3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

Service类的使用情况，在TmpAuthorityServiceImpl中注入Cache对象为NULL
<img width="1005" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/18628852/8d79efd7-38aa-4ab5-858b-748b905ca3d2">

去掉对ServiceImpl的继承，注入正常
<img width="571" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/18628852/1b97cc43-ec92-4e1d-beba-cd161510b0d9">

**Comment by nieqiurong** [comment]
提供复现工程

**Comment by Bobo1553** [comment]
抱歉，前几天太忙没来得及整最小复现工程，今天整了一下，如下是一个复现工程

github链接：https://github.com/Bobo1553/mybatis-service-test

分支：mybatis-service
请求http://127.0.0.1:8080/api/user/cache接口，会报NPE，报错如下：
<img width="1376" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/18628852/a17f3b5e-f754-4d96-abee-c74bf771329f">
<img width="1098" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/18628852/ecbbdb24-bf52-4b12-b503-0a7f059926f3">
<img width="480" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/18628852/374c2e63-170c-40bd-b584-7f065c7837c6">

分支：no-mybatis-service
请求http://127.0.0.1:8080/api/user/cache接口，正常返回cache
<img width="1359" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/18628852/c7415eb0-b6fd-4a0e-b7fb-64eef2c71242">

**Comment by Bobo1553** [comment]
ISSUES反馈补充：

**确定当前使用版本**：3.5.6

**提供环境信息**：Java版本 8.0，数据库版本 H2，驱动版本8.0.32

**详细描述问题**：在继承了ServiceImpl<XXXMapper, XXX>的类中使用@Resource注入失效，对应的变量为NULL

**提供完整堆栈日志**：无

**提供复现步骤**：启动，请求接口http://127.0.0.1:8080/api/user/cache

**补充提供复现工程**：https://github.com/Bobo1553/mybatis-service-test

**Comment by nieqiurong** [comment]
有个东西叫动态代理，删掉final就行
