### ISSUE TITLE
翻页插件问题

### ISSUE THREAD

**Issue by lilanlong** [baomidou/mybatis-plus#6103]
### 当前使用版本(必填,否则不予处理)

3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

使用mybatis @SelectProvider 注解进行翻页查询，使用了SQLServer2005Dialect翻页实现，select前面有一个空格，导致SQL截取的时候出现了问题。
![image](https://github.com/baomidou/mybatis-plus/assets/18063071/a759344c-2973-4ea4-bef8-a51a82eef3f6)

### 报错信息

SQL 错误 [156] [S0001]: 关键字 'FROM' 附近有语法错误。

**Comment by nieqiurong** [comment]
用 3.5.7-SNAPSHOT 试试

**Comment by lilanlong** [comment]
3.5.7-SNAPSHOT   从哪下载，自己下载源码编译吗
