### ISSUE TITLE
count错误

### ISSUE THREAD

**Issue by heshujing** [baomidou/mybatis-plus#6106]
### 当前使用版本(必填,否则不予处理)
3.5.6
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
count 统计:
![mybatis-plus356_2024042701231231](https://github.com/baomidou/mybatis-plus/assets/14806212/49a38694-200e-4cfd-bad9-16136087b5ef)
### 报错信息
![mybatis-plus356_20240427010017](https://github.com/baomidou/mybatis-plus/assets/14806212/2cfcfa93-5fab-483d-8452-2cca8b8636c3)

**Comment by heshujing** [comment]
JDK17+SpringBoot3

**Comment by shan-liangguang** [comment]
能否给个详细的复现步骤？我按照简单的复现了一下图中的查询（mybatis-plus3.5.6+jdk17+springboot3.0.2），暂未发现问题
![image](https://github.com/baomidou/mybatis-plus/assets/111164125/98284619-ceb6-4b07-a53f-2c82061fc9b5)

**Comment by nieqiurong** [comment]
提供完整堆栈日志。
