### ISSUE TITLE
mybatis plus generator 禁止生成serviceImpl、mapper、xml、controller失效

### ISSUE THREAD

**Issue by 404742630** [baomidou/mybatis-plus#6108]
### 当前使用版本(必填,否则不予处理)
3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
原本可以通过TemplateConfig.disable来禁止生成某些类的（通过赋null值的形式），但3.5.6版本不建议使用TemplateConfig后，在PathInfoHandler的构造方法中会给pathInfo设置TemplateConfig中的默认值，导致后续在AbstractTemplateEngine中批量输出serviceImpl、mapper、xml、controller时因存在默认的pathInfo使相应策略中的generate标识失效

### 重现步骤(如果有就写完整)
FastAutoGenerator.create(this.dbUrl, this.dbUserName, this.dbPassword)
                .globalConfig(builder -> {
                    builder.disableOpenDir()
                            .author(this.author);
                })
                .strategyConfig(builder -> {
                    builder.addInclude(this.tableList)
                            .entityBuilder()
                            .enableFileOverride()
                            .naming(NamingStrategy.underline_to_camel)
                            .columnNaming(NamingStrategy.underline_to_camel)
                            .enableTableFieldAnnotation()
                            .addTableFills(this.tableFillList)
                            .serviceBuilder()
                            .enableFileOverride()
                            .disable()
                            .mapperBuilder()
                            .enableFileOverride()
                            .disable()
                            .controllerBuilder()
                            .disable();
                })

**Comment by nieqiurong** [comment]
#6060
