### ISSUE TITLE
批量操作在高并发容易导致死锁

### ISSUE THREAD

**Issue by siriuscc** [baomidou/mybatis-plus#611]
### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

com.baomidou.mybatisplus.service.impl.ServiceImpl#insertOrUpdateBatch(java.util.List<T>, int)
com.baomidou.mybatisplus.service.impl.ServiceImpl#updateBatchById(java.util.List<T>, int)
批量操作容易导致死锁。
对同一张表 操作，且顺序相反，因为都在各自的事务中，锁住部分资源，互相等待，直接死锁。

假如有数据 a,b, 事务A，B
事务A执行操作顺序：a,b;
事务B执行操作顺序：b,a;
当A锁住a，B锁住b，互相等待.

### 重现步骤

模拟高并发，对同一张表同一段数据高并发update。

### 报错信息
无

**Comment by qmdx** [comment]
少年批量和锁不划等号！！ 请看看什么是乐观锁
