### ISSUE TITLE
在win11+jdk21环境下，自动生成代码只会输出表名，一直卡住，不知道为什么

### ISSUE THREAD

**Issue by AnAloneJaver** [baomidou/mybatis-plus#6117]
**当前使用版本**
<mybatis-plus-generator.version>3.5.6</mybatis-plus-generator.version>
        <velocity.version>2.3</velocity.version>
**描述bug现象**
![image](https://github.com/baomidou/mybatis-plus/assets/28829323/eb05002b-0ea9-418a-8ed9-ac77edbcce47)
在win11+jdk21环境下，自动生成代码只会输出表名，一直卡住，不知道为什么
希望有遇到跟我相同的大佬能提供一些有用的信息。我这里没有任何的错误信息，不知道为什么会有这样的情况发生
**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by nieqiurong** [comment]
补充描述数据库信息,复现步骤,最好提供复现工程.

**Comment by AnAloneJaver** [comment]
数据库版本
![image](https://github.com/baomidou/mybatis-plus/assets/28829323/abedac94-d0fe-4e16-9950-9b9ff7196c59)
工程地址
https://gitee.com/youlaiorg/youlai-boot
测试类
https://gitee.com/youlaiorg/youlai-boot/blob/master/src/test/java/com/youlai/system/generator/FastAutoGeneratorTest.java
测试表
![image](https://github.com/baomidou/mybatis-plus/assets/28829323/64a6c7fb-8392-46a1-97e8-a565ad20d42b)
表ddl
```
CREATE TABLE `waste_test` (
   `id` bigint(20) NOT NULL AUTO_INCREMENT,
   `username` varchar(50) DEFAULT NULL,
   `scope` decimal(5,2) DEFAULT NULL,
   `sex` tinyint(4) DEFAULT NULL,
   `address` varchar(50) DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB
```
jdk版本
openjdk21
操作系统
win11
测试结果依然是输出表名之后，没有任何的输出

**Comment by nieqiurong** [comment]
用debug日志调一下

**Comment by AnAloneJaver** [comment]
等输入呢，要在控制台输入表名，歪日，debug看到了Scanner！！！！我的问题
