### ISSUE TITLE
【MP3.0.5】mybatis-plus.configuration-properties配置项无法加载指定的外部参数配置文件

### ISSUE THREAD

**Issue by darren-wang** [baomidou/mybatis-plus#612]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus-boot-starter-3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

问题描述详见issue #602 

来吧，先看依赖的版本号：

![1](https://user-images.githubusercontent.com/7202883/48039049-32f0c880-e1ae-11e8-8c09-86a38199fb10.jpg)

确认jar包版本：

![2](https://user-images.githubusercontent.com/7202883/48039116-73e8dd00-e1ae-11e8-8a37-00afb1981424.jpg)

看一下外部配置文件，确实存在

![3](https://user-images.githubusercontent.com/7202883/48039153-84995300-e1ae-11e8-8d90-5e216425782f.jpg)

文件里面有测试内容：

![5](https://user-images.githubusercontent.com/7202883/48039213-bf9b8680-e1ae-11e8-94ef-b70fb96c39e3.jpg)

[来吧，看看MP的官方文档](http://mp.baomidou.com/guide/config.html#configurationproperties)

里面对应配置项如下：

<img width="786" alt="7" src="https://user-images.githubusercontent.com/7202883/48039442-bc54ca80-e1af-11e8-8db9-bf4ea89e9dfb.png">

看一下我们的`application.properties`文件是怎么配置的，根据官方文档配置：

![4](https://user-images.githubusercontent.com/7202883/48039186-aabef300-e1ae-11e8-9a70-df4bceb3a3b4.jpg)

最后看看代码运行起来的加载结果，
测试代码:
```java
@Autowired
MybatisPlusProperties mpconfig;

...

mpconfig.getConfigurationProperties();
```

调试截图：

![6](https://user-images.githubusercontent.com/7202883/48039497-f45c0d80-e1af-11e8-8dbc-5ccf823d2a7a.png)

看看这里最后加载的是啥，是配置有问题吗，还是代码有问题？

**Comment by miemieYaho** [comment]
文档尚未完工,你就开抄错误配置,这是我们的失误  
但是如果你真是一个合格的程序员应该早就通过 debug 或者看源码或者其他的方式知道配置 Properties 属性是以 key/value 的形式配置而不是什么指定 properties 文件吧 
但你显然没有

**Comment by darren-wang** [comment]
显然是你们的文档误导了用户，一个严谨的文档应该表明哪些功能已经具备，哪些功能还没完成，计划在什么版本提供。

你没有完成的功能就贴出文档，除非有明确说明该功能尚未完工，否则对于用户而言，直观的感受就相当于告诉用户可以使用该功能。

我发帖的意思是出于严谨，想跟开发人员确认一下这里是否存在配置使用上的错误，我贴出的就是调试的截图，更不用说看到那个`Properties`类型的域，所以我一开始的issue#602报的是bug，意思就是说这里文档不应该告诉用户去配置一个外部文件。

如果没有完成对应功能，就在文档上面说明开发中，预计什么版本提供。什么叫我就开抄错误配置，用户按照官方文档的操作结果成了用户犯错了。

傲慢是阻碍人类进步的最大壁垒，请不要上来就像吃了火药一样喷，说什么合格不合格，讨论技术问题就是讨论技术问题，不要随便乱扣帽子。

**Comment by miemieYaho** [comment]
1. 你的issue 并不是直指文档有误  
2. 文档人人都可 pr

**Comment by darren-wang** [comment]
我已经确认过这个点的情况了，期待后续版本
