### ISSUE TITLE
今天使用 parent 和 moduleName，结果 VelocityTemplateEngine模板的package.Parent是parent.moduleName

### ISSUE THREAD

**Issue by byMoWen** [baomidou/mybatis-plus#6121]
**当前使用版本**
3.5.5
**当前环境信息**
例如: Java8 + Mysql5.7
jdk17  mysql8
**描述bug现象**
今天使用 parent 和 moduleName，结果 VelocityTemplateEngine模板的package.Parent是parent.moduleName
**提供问题复现步骤**
// 包配置
                .packageConfig(builder -> {
                    builder
                            .parent("org.email") // 父包模块名 默认值:com.baomidou
                            .moduleName("send") // 设置父包模块名 默认值:无
                            .controller("controller")//Controller 包名 默认值:controller
                            .entity("domain")//Entity 包名 默认值:entity
                            .service("service")//Service 包名 默认值:service
                            .mapper("mapper")//Mapper 包名 默认值:mapper
                            .pathInfo(Collections.singletonMap(OutputFile.xml, userPath + "src/main/resources/mapper")); // 设置mapperXml生成路径
                    //默认存放在mapper的xml下
                })

    ${package.Parent}    ${package.ModuleName}

结果却是org.email.send       send
如果moduleName设置为空    结果却是org.email        空
**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by byMoWen** [comment]
public @NotNull String getParent() {
        return StringUtils.isNotBlank(this.moduleName) ? this.parent + "." + this.moduleName : this.parent;
    }
？？？？源码是加上的。那我怎么添加只再parent目录的其他如common的工具类

**Comment by nieqiurong** [comment]
你到底想问什么?????

**Comment by VampireAchao** [comment]
自定义模板啊
