### ISSUE TITLE
TableInfo懒加载

### ISSUE THREAD

**Issue by lilanlong** [baomidou/mybatis-plus#6122]
**请详细描述需要增加的功能**
用MapperScan注解扫描mapper，当mapper很多的时候，启动速度就会很慢，MapperScan注解中有lazyInitialization属性可以设置懒加载mapper，由于mapper没有加载相应的tableinfo也没有，能否在获取tableinfo的时候，同时初始化相应的mapper。

**Comment by miemieYaho** [comment]
不能
