### ISSUE TITLE
json相关函数会有错误

### ISSUE THREAD

**Issue by sirius0612** [baomidou/mybatis-plus#6126]
**当前使用版本**
3.5.3
**当前环境信息**
 Java8 + Mysql8.0.31

**描述bug现象**
在sql里使用了json_table 会报解析错误

**提供问题复现步骤**
<select id="getAnswersLike" resultType="java.lang.Long">
        select
            ind.id
        from
            inspection_detail ind,
            json_table (ind.answers,
                        '$[*]' columns(
                         itemName varchar(255) path '$.itemName',
                         `value` varchar(255) path '$.value',
                         isSelect int path '$.isSelect',
                         content varchar(255) path '$.content')) as jt
        where
            ind.del_flag_ = 0 and
            (jt.itemName like concat('%',#{param},'%')
                or
             jt.content like concat('%',#{param},'%')
                or
             jt.value like concat('%',#{param},'%'))
          and
            (jt.isSelect is null or jt.isSelect =1)
    </select>
但是会报错误 Encountered unexpected token: "(" "("
    at line 5, column 24.
传入param 则会报 Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 5, column 24.
**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException 只能找 jsqlparser
