### ISSUE TITLE
如何获取QueryWrapper中的参数名称

### ISSUE THREAD

**Issue by lvjingang-git** [baomidou/mybatis-plus#6129]
**请详细描述需要增加的功能**
比如我想通过条件中部分字段进行统一加解密处理，如何获取QueryWrapper中的条件参数名称呢？我看了下源码发现实际过程中AbstraceWrapper 构件条件时替换了参数名统一ew.xxx代替了，我不明白为何这样，不保留原始name或者给开个扩展也行 扩展AbstractWrapper  但是我目前发现无法扩展它

**Comment by miemieYaho** [comment]
你有想过`wrapper.eq("name","老王").or().eq("name","老李")`的情况吗?

**Comment by lvjingang-git** [comment]
你没理解我需求，我是想通过扩展AbstractWrapper时获取原始的 参数名称，这样可以处理是否对它做加密处理，现在原始拦截器拦截后发现 mybtais-plus丢失了where条件的原始 参数名称

**Comment by miemieYaho** [comment]
所以`wrapper.eq("name","老王").or().eq("name","老李")`呢?

**Comment by VampireAchao** [comment]
例如重写
`com.baomidou.mybatisplus.core.conditions.AbstractWrapper#addCondition`，这里能获取到第二个参数`R column`，这个就是参数名称
