### ISSUE TITLE
UNSIGNED BIGINT(20)映射问题

### ISSUE THREAD

**Issue by heardfate** [baomidou/mybatis-plus#613]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.5</version>
</dependency>

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
数据库ID字段使用UNSIGNED BIGINT(20)类型，手动在数据库存储ID值为`18446744073709551615`
JAVABEAN 下ID映射成 private `Long` id;
获取数据：报错java.sql.SQLDataException: Value '18,446,744,073,709,551,615' is outside of valid range for type java.lang.Long 越界类
插入数据：正常

JAVABEAN 下ID映射成 private `BigInteger` id;
获取数据：正常
插入数据：报错Could not set property 'id' of 'class XXX.entity.User' with value '1060015479998566402' Cause: java.lang.IllegalArgumentException: argument type mismatch

### 重现步骤
直接用默认生成器生成DAO，service，修改ID字段类型
数据库表用的就是demo的表

### 报错信息
数据库ID字段使用UNSIGNED BIGINT(20)类型，手动在数据库存储ID值为`18446744073709551615`
JAVABEAN 下ID映射成 private `Long` id;
获取数据：报错java.sql.SQLDataException: Value '18,446,744,073,709,551,615' is outside of valid range for type java.lang.Long 越界类
插入数据：正常

JAVABEAN 下ID映射成 private `BigInteger` id;
获取数据：正常
插入数据：报错Could not set property 'id' of 'class XXX.entity.User' with value '1060015479998566402' Cause: java.lang.IllegalArgumentException: argument type mismatch

**Comment by miemieYaho** [comment]
你手动设置的超出了 long 的最大值, mp 的 idwork 是 long 型,强转失败
