### ISSUE TITLE
Mybatis拦截器怎么拿到QueryWrapper中的参数和值

### ISSUE THREAD

**Issue by lvjingang-git** [baomidou/mybatis-plus#6132]
我想通过原生mybatis拦截器 获取QueryWrapper中的参数名。目前发现只有参数值，但是名称被替换了。请问如何扩展呢？是否可以考虑下个版本给AbstractWrapper中搞个拦截器扩展这个功能呢

**Comment by totoro52** [comment]
你的需求是写一个拦截器去拦截全局的QueryWrapper的某个参数并对其值进行加密操作的行为？

**Comment by miemieYaho** [comment]
不考虑
