### ISSUE TITLE
Factory method 'sqlSessionFactory' threw exception with message: 'void org.apache.ibatis.session.Configuration.parsePendingResultMaps(boolean)'

### ISSUE THREAD

**Issue by iuin8** [baomidou/mybatis-plus#6133]
**当前使用版本**

**当前环境信息**
Java17 + pgsql
gradle的依赖版本都放截图上了

**描述bug现象**
应用启动报错
**提供问题复现步骤**
每次启动都会报错
**提供完整堆栈日志(可选)**
Error creating bean with name 'testController' defined in file [/Users/fa/dev/projects/IdeaProjects/me/iuin-main/iuin-mall/commodity-service/build/classes/java/main/com/iuin/commodity/controller/TestController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'comUserServiceImpl' defined in file [/Users/fa/dev/projects/IdeaProjects/me/iuin-main/iuin-mall/commodity-service/build/classes/java/main/com/iuin/commodity/service/impl/ComUserServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'comUserDao': Unsatisfied dependency expressed through field 'baseMapper': Error creating bean with name 'comUserMapper' defined in file [/Users/fa/dev/projects/IdeaProjects/me/iuin-main/iuin-mall/commodity-service/build/classes/java/main/com/iuin/commodity/repostory/mapper/ComUserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory': Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception with message: 'void org.apache.ibatis.session.Configuration.parsePendingResultMaps(boolean)'
**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

<img width="1331" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/38066133/36e8b496-3faa-4fee-bdda-ede7e127d94b">

从报错和截图上看, 貌似是需要个Configuration.parsePendingResultMaps(boolean), 有参的方法, 但[mybatis-3.5.16](https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.5.16)才有这个方法, 在下面有提供对应的截图和链接
<img width="1800" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/38066133/6fd761f6-5448-4830-8b87-bd1ab999c0cb">
https://github.com/mybatis/mybatis-3/commit/fba61d2b752a84cb439eb03ae56776da4a1d4af7?diff=split&w=0

我试着手动添加了这个依赖到[mybatis-3.5.16]就正常了
<img width="1342" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/38066133/02cc4fd0-b1ff-4417-ba76-5a3d07525902">

**Comment by miemieYaho** [comment]
[mybatis-plus-spring-boot3-starter](https://github.com/baomidou/mybatis-plus/tree/3.0/spring-boot-starter/mybatis-plus-spring-boot3-starter)
