### ISSUE TITLE
异步任务中方法中存在updateById方法sql打印条目为1，数据库未修改

### ISSUE THREAD

**Issue by Tojay12** [baomidou/mybatis-plus#6141]
**当前使用版本**
v3.5.5
**当前环境信息**
例如: Java8 + Mysql8

**描述bug现象**
使用spring 提供的@Async注解实现异步
 多个异步任务中A方法sql打印更新条数为1，B也如此。
**提供问题复现步骤**
A、B方法都存在updateById方法，A方法中调用B方法，A方法控制台打印更新成功，数据库未修改成功，B方法修改成功。
**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by miemieYaho** [comment]
回炉重学`事务`
