### ISSUE TITLE
分页插件求总数量时对left join优化的bug 

### ISSUE THREAD

**Issue by cuibobo** [baomidou/mybatis-plus#6147]
**当前使用版本**
所有版本
**当前环境信息**
任意环境

**描述bug现象**
如sql为 select a.* from a left join b on a.id = b.a_id and a.is_deleted = 'n'; 此时利用分页插件分页时，count的sql会优化去掉 left join导致数量不对。
是不是应该在mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/inner/PaginationInnerInterceptor.java:337 这部分对on的表达式里面也要加上on的表达式是否包含左右表。如果包含是不是也不能去除left join

**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**

**Comment by miemieYaho** [comment]
PaginationInnerInterceptor.optimizeJoin
IPage.optimizeJoinOfCountSql
