### ISSUE TITLE
多租户插件在表不带别名的情况下出错 SELECT t1.* FROM t1,t2 where t1.a = t2.a 

### ISSUE THREAD

**Issue by Basil1991** [baomidou/mybatis-plus#6155]
**当前使用版本**

最新版本
---------------------------------------------------------------

原SQL：SELECT t1.* FROM t1,t2 where t1.a = t2.a 

改写后SQL： SELECT t1.* FROM t1, t2 WHERE t1.a = t2.a AND apply_province_code = 'fj' AND apply_province_code = 'fj'

当表没有别名时，租户条件不会带上表名,导致语句执行错误

----------------------------------------------------------------

**Comment by miemieYaho** [comment]
加上别名

**Comment by Basil1991** [comment]
> 加上别名

我知道加上别名可以解决。但是这边我们在技术框架级别集成了相关能力，业务开发做的过程不一定都会注意到。
针对这种情况可以在识别没有别名时加上表名.租户条件吗 @miemieYaho

**Comment by miemieYaho** [comment]
sql标准就是要加别名,请认真开发
