### ISSUE TITLE
使用 Wrappers.lambdaQuery 查询耗时很长，改用new LambdaQueryWrapper<>()就很快

### ISSUE THREAD

**Issue by MrBlackChen** [baomidou/mybatis-plus#6156]
版本：3.4.3和3.5.2
数据库：PostgreSQL 13.12
示例代码：
方式1：infoMapper.selectOne(Wrappers.lambdaQuery(RiskInfo.class));启动服务后，多次调用，每次都很慢。
方式2：infoMapper.selectOne(new LambdaQueryWrapper<>());每次都很快。
我遇到的场景中，方式1要慢了10倍左右。
请帮我分析一下可能得原因，谢谢。

**Comment by miemieYaho** [comment]
看源码

**Comment by MrBlackChen** [comment]
源码中并没有发现什么特别之处，如果你发现了，麻烦告知一下，谢谢。
