### ISSUE TITLE
BlockAttackInnerInterceptor 自定义Sql出现换行符，优化

### ISSUE THREAD

**Issue by ryanSir** [baomidou/mybatis-plus#6168]
**请详细描述需要增加的功能**
   @Override
    public void beforePrepare(StatementHandler sh, Connection connection, Integer transactionTimeout) {
        PluginUtils.MPStatementHandler handler = PluginUtils.mpStatementHandler(sh);
        MappedStatement ms = handler.mappedStatement();
        SqlCommandType sct = ms.getSqlCommandType();
        if (sct == SqlCommandType.UPDATE || sct == SqlCommandType.DELETE) {
            if (InterceptorIgnoreHelper.willIgnoreBlockAttack(ms.getId())) {
                return;
            }
            BoundSql boundSql = handler.boundSql();
            String sql = boundSql.getSql();
            parserMulti(sql.replace("\n", ""), null);
        }
    }

**Comment by nieqiurong** [comment]
#6187
