### ISSUE TITLE
主键生成算法问题

### ISSUE THREAD

**Issue by zengzhihong** [baomidou/mybatis-plus#617]
### 当前使用版本(必须填写清楚，否则不予处理)

版本2.3.2的starter

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

配置文件配置了 workerId和centerId  但是实际并不生效

### 重现步骤

MybatisPlusAutoConfiguration 126行的if判断条件不成立 无法执行 init方法IdWorker.initSequence(workerId, datacenterId);

### 报错信息

无

**Comment by zengzhihong** [comment]
以上issue指的是Idworker

**Comment by qmdx** [comment]
测试有效，升级到最新版本，不可用请提供 demo 重现地址
