### ISSUE TITLE
数据权限拦截器设置后，分页时自带的count无法拦截，需要多写一行代码count才可以

### ISSUE THREAD

**Issue by muchao512** [baomidou/mybatis-plus#6172]
**当前使用版本**
3.5.5
**当前环境信息**
例如: Java8 + Mysql5.7
Java11 + MySQL8
**描述bug现象**
配置好CustomDataPermissionHandler实现MultiDataPermissionHandler后，将插件加入拦截器之后，分页查询时，自带的count无法拦截（SQL中不带有数据权限拦的SQL片段）
**提供问题复现步骤**
配置好CustomDataPermissionHandler实现MultiDataPermissionHandler后，将插件加入拦截器之后，分页查询时，自带的count无法拦截（SQL中不带有数据权限拦的SQL片段）
**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by miemieYaho** [comment]
放分页前面去
