### ISSUE TITLE
Page 类中的 current属性  是否 可以变成成其他名字呢？

### ISSUE THREAD

**Issue by mrxlh** [baomidou/mybatis-plus#6173]
在get 请求查询的时候，?size=20&current=1  

HTML character  会变成 \"20¤t=1\" 传参异常

参考：
https://toolstud.io/web/charmap.php?encoded=curren&sort=name

**Comment by totoro52** [comment]
自己封装一个类，然后set回去不就可以了

**Comment by mrxlh** [comment]
> 自己封装一个类，然后set回去不就可以了

这并不能从根上解决这个问题，其他小伙伴在使用的时候，依然有可能踩坑。

**Comment by totoro52** [comment]
> > 自己封装一个类，然后set回去不就可以了
> 
> 这并不能从根上解决这个问题，其他小伙伴在使用的时候，依然有可能踩坑。

你直接在controller那里接受plus的page对象吗？ 那肯定会遇到问题。。而且那个类里面一堆属性， 最好是封装一个自己的分页，写个getPage方法自己return个page就行了。

**Comment by mrxlh** [comment]
> > > 自己封装一个类，然后set回去不就可以了
> > 
> > 
> > 这并不能从根上解决这个问题，其他小伙伴在使用的时候，依然有可能踩坑。
> 
> 你直接在controller那里接受plus的page对象吗？ 那肯定会遇到问题。。而且那个类里面一堆属性， 最好是封装一个自己的分页，写个getPage方法自己return个page就行了。

嗯嗯，大佬您说的方式确实可以解决我的问题，但保证不了其他小伙伴 不会踩这个坑。
1. 您建议重新封装一个Page类，那原有的Page类是做啥用的呢？
2. 采用easycode 插件，生成的基本的CRUD，其中的分页就是采用MP 中的Page类实现的，据了解该插件有一定的受众基础，所以其他使用该插件的小伙伴也有可能遇到同样的问题。  
    https://plugins.jetbrains.com/plugin/10954-easycode
以上是鄙人拙见哈，大佬。

**Comment by totoro52** [comment]
> > > > 自己封装一个类，然后set回去不就可以了
> > > 
> > > 
> > > 这并不能从根上解决这个问题，其他小伙伴在使用的时候，依然有可能踩坑。
> > 
> > 
> > 你直接在controller那里接受plus的page对象吗？ 那肯定会遇到问题。。而且那个类里面一堆属性， 最好是封装一个自己的分页，写个getPage方法自己return个page就行了。
> 
> 嗯嗯，大佬您说的方式确实可以解决我的问题，但保证不了其他小伙伴 不会踩这个坑。
> 
> 1. 您建议重新封装一个Page类，那原有的Page类是做啥用的呢？
> 2. 采用easycode 插件，生成的基本的CRUD，其中的分页就是采用MP 中的Page类实现的，据了解该插件有一定的受众基础，所以其他使用该插件的小伙伴也有可能遇到同样的问题。
>    https://plugins.jetbrains.com/plugin/10954-easycode
>    以上是鄙人拙见哈，大佬。

1.这个easycode没用过，但我刚才去看了眼，它确实自带的默认模板就是import了com.baomidou.mybatisplus.extension.plugins.pagination.Page这个类，但它是模板，支持更改。

2.其实我不理解为什么拿框架的类去作为参数类去接受，框架的类本身自己就无法受控，哪天如果plus更新了一个版本改了这个类的字段，然后后端一更新plus版本，你们前后端的对接不就全炸了吗，你想改这个类还改不了。

3. 封装自己的page不是为了替代plus的page，是为了更好的把控， 你可以自己写自己的page和size属性，然后在写个方法getPage去new一个plus的page给到查询方法，虽然有点脱裤子放屁，但这样就不会和plus的page深度绑定。

**Comment by mrxlh** [comment]
> > > > > 自己封装一个类，然后set回去不就可以了
> > > > 
> > > > 
> > > > 这并不能从根上解决这个问题，其他小伙伴在使用的时候，依然有可能踩坑。
> > > 
> > > 
> > > 你直接在controller那里接受plus的page对象吗？ 那肯定会遇到问题。。而且那个类里面一堆属性， 最好是封装一个自己的分页，写个getPage方法自己return个page就行了。
> > 
> > 
> > 嗯嗯，大佬您说的方式确实可以解决我的问题，但保证不了其他小伙伴 不会踩这个坑。
> > 
> > 1. 您建议重新封装一个Page类，那原有的Page类是做啥用的呢？
> > 2. 采用easycode 插件，生成的基本的CRUD，其中的分页就是采用MP 中的Page类实现的，据了解该插件有一定的受众基础，所以其他使用该插件的小伙伴也有可能遇到同样的问题。
> >    https://plugins.jetbrains.com/plugin/10954-easycode
> >    以上是鄙人拙见哈，大佬。
> 
> 1.这个easycode没用过，但我刚才去看了眼，它确实自带的默认模板就是import了com.baomidou.mybatisplus.extension.plugins.pagination.Page这个类，但它是模板，支持更改。
> 
> 2.其实我不理解为什么拿框架的类去作为参数类去接受，框架的类本身自己就无法受控，哪天如果plus更新了一个版本改了这个类的字段，然后后端一更新plus版本，你们前后端的对接不就全炸了吗，你想改这个类还改不了。
> 
> 3. 封装自己的page不是为了替代plus的page，是为了更好的把控， 你可以自己写自己的page和size属性，然后在写个方法getPage去new一个plus的page给到查询方法，虽然有点脱裤子放屁，但这样就不会和plus的page深度绑定。

理解，框架修改影响面还是比较大的，确实积重难返了。
