### ISSUE TITLE
3.5.1 oracle数据库，使用LambdaUpdateWrapper更新数据时，报无效列类型，如何解决

### ISSUE THREAD

**Issue by 1012827105** [baomidou/mybatis-plus#6175]
mapper.update(null,new LambdaUpdateWrapper().set(PO::getUpdateUser,null))

org.apache.ibatis.type.BaseTypeHandler#setParameter 调用ps.setNull(i, jdbcType.TYPE_CODE);方法报错，报错详情如下：
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL1', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111

**Comment by zhaoyunxing92** [comment]
PO::getUpdateUser这个类上面是不是有`typeHandler`

**Comment by zhaoyunxing92** [comment]
PO::getUpdateUser这个类上面是不是有`typeHandler`

**Comment by HK-hub** [comment]
oracle遇到同样的错误，是不是要把字段设置为空

**Comment by HK-hub** [comment]
int update = this.baseMapper.update(null, wrapper
                                .set(PileSendOutPlan::getSendType, pileSendOutPlan.getSendType())
                                .set(PileSendOutPlan::getSendNow, pileSendOutPlan.getSendNow())
                                .set(PileSendOutPlan::getNextDaySend, null)
                                .set(PileSendOutPlan::getPlanSendTime, pileSendOutPlan.getPlanSendTime())
                                .eq(PileSendOutPlan::getId, pileSendOutPlan.getId()));

**Comment by HK-hub** [comment]
同款错误
```java
int update = this.baseMapper.update(null, wrapper
                                .set(PileSendOutPlan::getSendType, pileSendOutPlan.getSendType())
                                .set(PileSendOutPlan::getSendNow, pileSendOutPlan.getSendNow())
                                .set(PileSendOutPlan::getNextDaySend, null)
                                .set(PileSendOutPlan::getPlanSendTime, pileSendOutPlan.getPlanSendTime())
                                .eq(PileSendOutPlan::getId, pileSendOutPlan.getId()));
```
