### ISSUE TITLE
一次批量导入逐渐变慢的问题

### ISSUE THREAD

**Issue by luoxiaofeng1029** [baomidou/mybatis-plus#6178]
**当前使用版本**
3.5.4
**当前环境信息**
例如: Java17 + Mysql5.7

**描述bug现象**
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/a0463e08-050f-4830-89ad-0d14f824755a)
![I}KPXP1LIA3X}5 R0HJ68R6](https://github.com/baomidou/mybatis-plus/assets/50006313/beb170a9-ac17-47bc-ba7a-2b19359a1cfb)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/8509e363-9c53-495c-b3f0-1f320ee6786f)
![8A 0{KP)HMKLMOLW7I57TJM](https://github.com/baomidou/mybatis-plus/assets/50006313/24aa7e01-ae74-4b50-a50a-cb6cacbbda72)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/c185c1a7-3efa-4517-9b0e-9d6b04fcb782)
![~`E@FVZ9AQK0 R KC95D($O](https://github.com/baomidou/mybatis-plus/assets/50006313/b31aceb2-9ad1-468c-8991-d261928dc825)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/faa29412-410b-4bb7-a713-290bbc77f624)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/71b92223-e05a-4bb4-9939-80175cfde65e)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/499f9fc4-43b1-4a37-b5f0-e958c528d96c)
![DM1NN(9WS%}%(9@0BXPMF$L](https://github.com/baomidou/mybatis-plus/assets/50006313/f0d417e0-27e6-4d2e-9ab5-1b7f33f19d56)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/145dc112-a69f-4676-b694-f08b888dc820)
![SIY$F F3PMVEXYSX$TTU _R](https://github.com/baomidou/mybatis-plus/assets/50006313/e146f9f3-5286-488b-9408-2d1bf06b939b)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/2f3e6893-b768-439d-9f58-0c0753559cf0)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/e40a987a-10ae-4a24-91ae-b3180ab095c0)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/253cb6de-26c9-4146-a0af-68bc0639bc08)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/181d7ac0-22a1-4a4a-b0c8-4210d7e39a2d)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/9944ea26-df10-4f3c-8cce-4dc8b557c7f3)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/a936e01d-86b6-4aa6-be77-51209f01516e)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/35dcf217-bd3b-4f80-9474-a27851923e35)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/47febc1b-f332-45de-be64-05aa1f49bec4)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/15173d17-d5da-40cc-98e3-f7c5b0bb7012)
![JOXVN2($%WTTQB6~ _ @TV4](https://github.com/baomidou/mybatis-plus/assets/50006313/972a8a26-554f-4133-9414-980722d21e6c)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/0636e731-faf9-417a-9d4a-5082ca6e6e27)
![image](https://github.com/baomidou/mybatis-plus/assets/50006313/bec3bf61-8ef9-479c-a708-56edcf081c96)

如上这次问题的全过程,然后现在就想知道底层的原因是什么?
目前自己临时解决方法就是多线程批量导入了.

**Comment by nieqiurong** [comment]
生成的语句，提高性能的方式你可以自定插入语句，而不是动态insert语句

**Comment by luoxiaofeng1029** [comment]
> 生成的语句，提高性能的方式你可以自定插入语句，而不是动态insert语句

我的主要问题是为什么速度后面会在每K条增加.字段规格里有符号的换成普通中文后速度就正常了.你看我所有的内容了吗

**Comment by nieqiurong** [comment]
没做任何处理，检查驱动底层.

**Comment by yexiule** [comment]
找到原因了吗，我也想知道

**Comment by luoxiaofeng1029** [comment]
> 找到原因了吗，我也想知道

没找到,我自己写了原生sql解决了.但是你楼上说了没处理,检查驱动底层....我还能说啥
