### ISSUE TITLE
wrapper.in没有生效问题

### ISSUE THREAD

**Issue by zjgrcb** [baomidou/mybatis-plus#6181]
**当前使用版本**
3.5.2

**当前环境信息**
例如: Java11 + Mysql5.7

**描述bug现象**
queryWrapper.and(wrapper -> wrapper.in("goodSortation", sortation));
sortation参数传入的 1,2,3 数据库存在3的数据，但是程序没有查询出来

**Comment by miemieYaho** [comment]
sortation是list吗?

**Comment by huayanYu** [comment]
没有回复，关闭
