### ISSUE TITLE
Mockito xxxLambdaQueryChainWrapper.page() 未能Mock出结果，而是实际调用时，返回的null值

### ISSUE THREAD

**Issue by wangyx6** [baomidou/mybatis-plus#6184]
**当前使用版本**
mybatis-plus： 3.4.3.4
spring-boot: 2.4.11
mockito-core: 3.6.28
**当前环境信息**
Java8 + Mysql 5.1.44

**描述bug现象**
使用Mockito编写单测时，mock service对应的lambdaQuery.page(xxx)方法时，page 返回的结果为null
**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.
工厂地址：https://github.com/wangyx6/mybatis-plus-junit.git

功能反馈
请详细描述好需求，以及期望得到的处理方式.
mockito 模拟Page方法时，可以有预期的返回，返回预先定义好的数据

BUG问题反馈
优先处理有复现工程的ISSUES反馈。

**Comment by miemieYaho** [comment]
与mp无关
