### ISSUE TITLE
结合mycat使用问题

### ISSUE THREAD

**Issue by keepcoolwu** [baomidou/mybatis-plus#619]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

我们需要实现 update t_user set name='',password='' where id='1' and dataOwner=2
这样的sql，其中dataOwner是分库分表字段， 通过下面代码实现，程序报错

User obj = new User();
obj.setId("1");
obj.setName("admin");
obj.setDataOwner(2);

UpdateWrapper<User> updateWrapper = new UpdateWrapper<User>();
updateWrapper.eq("DATA_OWNER", 2);
updateWrapper.eq("ID", "1");

userMapper().update(obj, updateWrapper);

执行报错，见报错信息

### 重现步骤
另外有没有类似 hibernate中  updatable =false,insertable=true
这样的注解，达到insert的时候 包含分区字段，update的时候不包含分区字段的效果
目前分库分表中间件都要求，update语句不能包含分区字段。我们现在通过修改你们的源码（TableInfo）实现：

  public String getAllSqlSet(boolean ignoreLogicDelFiled, final String prefix) {
        String newPrefix = prefix == null ? StringPool.EMPTY : prefix;
        String result= fieldList.stream()
            .filter(i -> {
                if (ignoreLogicDelFiled) {
                    return !(isLogicDelete() && i.isLogicDelete());
                }
               //增加判断分区字段逻辑
                if(i.getColumn().equalsIgnoreCase("DATA_OWNER")){
                	return false;
                }
                return true;
            })
            .map(i -> i.getSqlSet(newPrefix)).collect(joining(StringPool.NEWLINE));
        System.out.println(result);
        return result;
    }

### 报错信息

Caused by: 
org.apache.ibatis.binding.BindingException: Parameter 'name' not found. Available parameters are [ew, param1, et, param2]
	at org.apache.ibatis.binding.MapperMethod$ParamMap.get(MapperMethod.java:202)
	at org.apache.ibatis.reflection.wrapper.MapWrapper.get(MapWrapper.java:45)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.setParameters(MybatisDefaultParameterHandler.java:256)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.parameterize(PreparedStatementHandler.java:93)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.parameterize(RoutingStatementHandler.java:64)

**Comment by miemieYaho** [comment]
```java
User obj = new User();
obj.setName("admin");

UpdateWrapper updateWrapper = new UpdateWrapper();
updateWrapper .set("password","");
updateWrapper.eq("DATA_OWNER", 2);
updateWrapper.eq("ID", "1");

userMapper().update(obj, updateWrapper);
```
