### ISSUE TITLE
可否放开TableInfo.withInsertFill/withUpdateFill 配置属性，比如通过@TableName注解能够配置此项，使其更加灵活？

### ISSUE THREAD

**Issue by iQiFengLe** [baomidou/mybatis-plus#6197]
比如一个实体，包含删除、添加、加入回收站时间、最后更新时间，如果我想将加入回收站时间与更新时间、删除时间使用自动填充功能为其填充，那么必须使用@TalbeField(fill=XXX)进行定义。
一旦为其定义，那么使用实体更新或插入时就会触发，而生成sql会包含这些字段。
比如：将其加入回收站时，不应该更新最后更新时间字段。而实际的sql却有该字段导致报错（因为填充器内部逻辑不会给实体的最后更新时间设置值）

**Comment by miemieYaho** [comment]
你的标题和你的内容存在冲突
填充是在ognl之后进行的那就只能是提前指定该字段会在对应阶段必出现在sql里

**Comment by iQiFengLe** [comment]
> 你的标题和你的内容存在冲突 填充是在ognl之后进行的那就只能是提前指定该字段会在对应阶段必出现在sql里
嗯，这是对的
