### ISSUE TITLE
is_delete字段值为0的数据,通过list批量查询总被过滤掉无法查出来

### ISSUE THREAD

**Issue by yz-jaker** [baomidou/mybatis-plus#6198]
LambdaQueryWrapper<UserBase> userWrapper = new QueryWrapper<UserBase>().lambda()
                    .in(UserBase::getIsDelete, Arrays.asList(0,1));
            Map<Long, UserBase> userBaseMap = userBaseService.list(userWrapper).stream().collect(Collectors.toMap(UserBase::getUserId, Function.identity()));

**Comment by miemieYaho** [comment]
就这样的
