### ISSUE TITLE
是否提供LambdaQueryWrapper已有条件自定义删除功能

### ISSUE THREAD

**Issue by MuAnswer** [baomidou/mybatis-plus#6199]
**业务场景**
一个公共业务一般会有很多共性的查询条件，此时习惯性封装成公共方法，但是如果有定制业务对某个条件互斥，就无法使用该公共LambdaQueryWrapper，这样就会产生很多冗余代码，后续不好维护
**现状**
仅支持对整个lambda进行clear操作
**预期**
公共方法对日期进行设置         queryWrapper.between(SdkLog::getTime, req.getPastStartTime(), req.getEndTime());
我需要对这个time进行移除，例如：queryWrapper.between(SdkLog::getTime, clear);（ps：目前没有这种重载方法，仅yy示例）

是否有，而且可行？提供类似重载呢？

**Comment by miemieYaho** [comment]
没有

**Comment by MuAnswer** [comment]
> 没有

好奇问下，未来是否会提供类似功能呢？

**Comment by miemieYaho** [comment]
也没有
