### ISSUE TITLE
mybatis 依赖的版本问题

### ISSUE THREAD

**Issue by tangxusc** [baomidou/mybatis-plus#62]
我们当前项目使用的mybatis版本为3.3.1 我们想使用mybatis-plus,但是又不想更改我们现在使用的mybatis(因为我们做了一定的定制开发),导致版本冲突,所以能否在POM中不直接依赖mybatis,而是加入scope为provided 由用户来决定mybatis版本等问题

**Comment by yuxiaobin** [comment]
可以排除依赖
`<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
</exclusions>`

**Comment by tangxusc** [comment]
谢谢解答
