### ISSUE TITLE
更新TableLogic 字段不生效

### ISSUE THREAD

**Issue by 654894017** [baomidou/mybatis-plus#6203]
**请详细描述需要增加的功能**
我有一个更新的逻辑是要更新 （ is_deleted  =   主键  ， ）   ， 这样只要is_delete != 0  的都是删除的，  实际在使用的时候我手动设置is_deleted = 主键 ， 同时字段标注了TableLogic， 在执行update 的时候，    is_deleted 是无法生效的执行的sql里面压根没把这个字段带上去更新。 是否可以放开这个限制，当这个字段已经设置了值就用设置的值更新。

**Comment by miemieYaho** [comment]
你用basemapper的update可以,basemapper的delete不可以
