### ISSUE TITLE
mybatis 组装出来的sql应该将多余的换行符去除

### ISSUE THREAD

**Issue by lujiamingzZ** [baomidou/mybatis-plus#6207]
在开启数据鉴权插件时，会走JSqlParser的parse进行sql检验。在存在多/n时会导致检验不通过；
以下为[JSqlParser](https://github.com/JSQLParser/JSqlParser)官方issue回答链接：
[问题一](https://github.com/JSQLParser/JSqlParser/issues/1988)
[问题二](https://github.com/JSQLParser/JSqlParser/issues/2012)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/6187
