### ISSUE TITLE
配置自定义 LanguageDriver 被 com.baomidou.mybatisplus.MybatisXMLLanguageDriver覆盖导致无效

### ISSUE THREAD

**Issue by atomiCat** [baomidou/mybatis-plus#621]
### 当前使用版本  2.3.3
springBoot环境中
自定义 **PerfectLanguageDriver** extends com.baomidou.mybatisplus.MybatisXMLLanguageDriver
application.yml 配置 :
mybatis-plus:
&nbsp;&nbsp;configuration:
&nbsp;&nbsp;&nbsp;&nbsp;defaultScriptingLanguage: com.test.**PerfectLanguageDriver**

在Configuration.setDefaultScriptingLanguage(class) 设置断点会看到三次执行，
class 依次为
com.baomidou.mybatisplus.MybatisXMLLanguageDriver
com.test.PerfectLanguageDriver
com.baomidou.mybatisplus.MybatisXMLLanguageDriver
这样自己的PerfectLanguageDriver始终不生效
求解

**Comment by yuxiaobin** [comment]
这里有一个bug，没判断是否有LanguageDriver,直接hardcode塞了MybatisXMLLanguageDriver

**Comment by miemieYaho** [comment]
使用 3.0.6 ,可能已修复该问题

**Comment by atomiCat** [comment]
没有勇气换3.0，项目代码量比较多，项目成立时用的2.0，切到3.0api都变了，太麻烦了

**Comment by miemieYaho** [comment]
试试使用 `2.3.4-SNAPSHOT` 快照版本
