### ISSUE TITLE
update(entity, updateWrapper)，entity=null时MetaObjectHandler没触发，这个是基于什么考虑的

### ISSUE THREAD

**Issue by lancankun** [baomidou/mybatis-plus#6211]
**当前使用版本**
3.5.6
**当前环境信息**
Java8 + Mysql8

**描述bug现象**
xxxMapper.update(entity, updateWrapper)方法更新时，因为我的实体类里有些字段设置有默认值，所以不能直接传入new xxxEntity()作为entity的入参。但是当entity=null时MetaObjectHandler就不能触发了。这个不是bug的话，是基于什么考虑的。 
我的应用场景是，不想被Entity里的默认值覆盖更新到数据库，只想通过updateWrapper.set来设置值，且要触发MetaObjectHandler的话，有没有能直接使用的方法呢。谢谢了

**提供问题复现步骤**
userMapper.update(null, updateWrapper); // 不传entity时，没法触发MetaObjectHandler自动填充

**提供完整堆栈日志(可选)**
无
**提供问题复现工程(可选)**
无

**Comment by miemieYaho** [comment]
没有

**Comment by lancankun** [comment]
MetaObjectHandler没触发，这个是bug吗

**Comment by miemieYaho** [comment]
有entity才触发
