### ISSUE TITLE
多租户如何实现tenant_id in (1, 2)

### ISSUE THREAD

**Issue by zijun-hiwintech** [baomidou/mybatis-plus#6214]
现有的多租户是单个用户单个值  ,现在我们想实现单个用户多个值的情况,具体应该怎么处理?

**Comment by miemieYaho** [comment]
不支持

**Comment by 1198735966** [comment]
![image](https://github.com/user-attachments/assets/2cfa8b85-1f28-40be-b556-a8e6903c4054)
是否可以重写，自已判断构建表达式 ，加入到 interceptors 中

**Comment by semmywong** [comment]
想请教下，最终是怎么实现的

**Comment by 1198735966** [comment]
![Image](https://github.com/user-attachments/assets/34b66590-b5a7-4ffc-b83c-32716338708d)

**Comment by zijun-hiwintech** [comment]
厉害啊
