### ISSUE TITLE
因为MP加快了开发进度 导致我被裁员失去工作 MP 作者需要赔偿

### ISSUE THREAD

**Issue by landashu** [baomidou/mybatis-plus#6217]
因为MP加快了开发进度 导致我被裁员失去工作 MP 作者需要赔偿

**Comment by zk020106** [comment]
你无敌了

**Comment by qmdx** [comment]
赔，我看看有多少需要赔的

**Comment by wangqiqi95** [comment]
必须得赔 不赔申请仲裁

**Comment by ifdelete** [comment]
啊？

**Comment by Hi-Mr-Wind** [comment]
我也要求赔偿，要求赔偿额度 1BTC

**Comment by bwcx-jzy** [comment]
那 hutool 作者是不是要赔得倾家荡产都不够奥？

**Comment by chen934298133** [comment]
6

**Comment by Mr-LiXiantong** [comment]
6

**Comment by damonxue** [comment]
非官方的我：请需要赔偿在此下边回复统计下， 然后一起找baomidou要赔偿。 否则抱团仲裁。

**Comment by JavaLionLi** [comment]
赔哈哈 持续观望

**Comment by RebelTinker** [comment]
赔，说吧 怎么陪

**Comment by bwcx-jzy** [comment]
satoken 作者站在角落瑟瑟发抖

**Comment by lazgg** [comment]
应该让甲骨文赔,让你写什么java,大厂手写汇编

**Comment by open-snail** [comment]
翘首以待

**Comment by damonxue** [comment]
> 非官方的我：请需要赔偿在此下边回复统计下， 然后一起找baomidou要赔偿。 否则抱团仲裁。

希望索要赔偿的都能人人1.5个BTC。

**Comment by qh-king** [comment]
活久见啊

**Comment by Mr-Blue-a** [comment]
该赔

**Comment by LAIguapi** [comment]
特来围观，笑死了

**Comment by chengliang4810** [comment]
特来围观，笑死了

**Comment by qmdx** [comment]
> 我也要求赔偿，要求赔偿额度 1BTC

 必须找 美国人 制裁我们， 导致我们还能用 apache 和 spring boot 加速了开发

**Comment by cheakin** [comment]
一时搞不清是真的，还是来反串的

**Comment by FangPengbo** [comment]
James Gosling 是不是也要赔你？

**Comment by landashu** [comment]
![ce49b8b14392483ed2c734209548244](https://github.com/baomidou/mybatis-plus/assets/17019818/e1e8c155-d6eb-4b47-8c57-8890ce071891)

**Comment by RebelTinker** [comment]
哈哈哈 楼上你要笑死我

**Comment by huangbh1024** [comment]
> ![ce49b8b14392483ed2c734209548244](https://private-user-images.githubusercontent.com/17019818/334688956-e1e8c155-d6eb-4b47-8c57-8890ce071891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjYwNTcsIm5iZiI6MTcxNjk2NTc1NywicGF0aCI6Ii8xNzAxOTgxOC8zMzQ2ODg5NTYtZTFlOGMxNTUtZDZlYi00YjQ3LThjNTctODg5MGNlMDcxODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZWNlYzhlNzg4YWU4OGFjMDgyNzEwNzQ5MmU4ODhmNjZlYjA3YmQyM2QyMDljZjM2Y2I3OGE0ZDNiZDU2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sLnmrQ8ioFA63hqCi0kKm0zwlLGwwrywjz5jVZBP9Bs)

6

**Comment by xiaomizhou2** [comment]
见证历史，如果成功我就去索赔 satoken、pig 和 ruoyi

**Comment by starsky-web** [comment]
逆天

**Comment by zk020106** [comment]
> ![ce49b8b14392483ed2c734209548244](https://private-user-images.githubusercontent.com/17019818/334688956-e1e8c155-d6eb-4b47-8c57-8890ce071891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjYwODEsIm5iZiI6MTcxNjk2NTc4MSwicGF0aCI6Ii8xNzAxOTgxOC8zMzQ2ODg5NTYtZTFlOGMxNTUtZDZlYi00YjQ3LThjNTctODg5MGNlMDcxODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2NTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OGU0MDBjZjZhYmI5NmVjZjJmOTM5Yzg4YzllYTg1NjcwNDNkYjc3YzIwYmZmYWUyN2EzN2IwZjhkOTUxMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHTBkFRmaWYbzfK9-Wdb2dCTN7VhH-qs8DiDZDUDoJU)

这是gpt告诉你的 你让gpt来找MP

**Comment by lucius-lee** [comment]
黑红也是红是吧？

**Comment by bwcx-jzy** [comment]
> 见证历史，如果成功我就去索赔 satoken、pig 和 ruoyi

不要忘记叫上我去索赔 hutool

**Comment by xiaomizhou2** [comment]
使用 Google 工具包的记得去向 Google 索赔  这公司有钱

**Comment by BestQwerty** [comment]
幽默

**Comment by bkywksj** [comment]
整活?

**Comment by JerryFan626** [comment]
先去找冯诺依曼赔偿了再来

**Comment by XHHzZz** [comment]
直接找公司赔偿，没有公司直接不工作

**Comment by wj9337** [comment]
支持。我要去起诉jetbrains。他让我不会用文本文档写代码，技能退化严重！在这个市场环境下，一点竞争力都没有，不好找工作

**Comment by meifannao05** [comment]
太抽象了

**Comment by meifannao05** [comment]
文心一言不赔偿

**Comment by fujc2dev** [comment]
特来围观

**Comment by guxiyang** [comment]
都不要逮着一个软柿子捏，多去薅那些大厂去

**Comment by ESCATS** [comment]
> 因为MP加快了开发进度 导致我被裁员失去工作 MP 作者需要赔偿
![1716966927855](https://github.com/baomidou/mybatis-plus/assets/67588862/7a8daf43-977b-4954-9add-d4b1cef61210)

**Comment by Max-Qiu** [comment]
> 都不要逮着一个软柿子捏，多去薅那些大厂去

我要去找阿里，因为nacos

**Comment by link-yuml** [comment]
因为nacos和xxl-job导致研发工作变得更简单了，是不是大家都要去找他们赔偿

**Comment by openwave11** [comment]
高级黑？

**Comment by zhenruyan** [comment]
热门留影

**Comment by ESCATS** [comment]
> 因为MP加快了开发进度 导致我被裁员失去工作 MP 作者需要赔偿

![dec7f88e582688fa8376bc39642370c](https://github.com/baomidou/mybatis-plus/assets/67588862/877fb1e1-a982-4df6-95c5-b2d22e6fce7b)
我翠翠草原实名支持，赔偿

**Comment by Hi-Mr-Wind** [comment]
大家去找hutool，磊子是个大户

**Comment by akito4** [comment]
支持索赔，还我们一个公道

**Comment by link-yuml** [comment]
回到最原始的全部代码手写实现，提高程序员就业率

**Comment by RT-2020** [comment]
太抽象了

**Comment by mpj1234** [comment]
有意思

**Comment by qmdx** [comment]
![0867c95d24f9de7c867ee629732b915](https://github.com/baomidou/mybatis-plus/assets/1481125/84d25591-ee7a-42a1-b2a8-6242557bf0b3)

不行我要举报你们薅社会主义羊毛

**Comment by sssjack** [comment]
评论惊现草原大帝！

**Comment by maomao94** [comment]
我来围观一下

**Comment by RadianceL** [comment]
围观大佬，期待大佬维权成功

**Comment by maomao94** [comment]
制裁spring，禁止使用spring

**Comment by cxlogin** [comment]
大胆 开门查水表

**Comment by herodotus-ecosystem** [comment]
应该制裁开源，就是因为开源，让软件开发越来越没有难度。

**Comment by zaixiakongyiji** [comment]
支持索赔,期待大佬维权成功  : P

**Comment by RebelTinker** [comment]
还得是人太多了

**Comment by maomao94** [comment]
gorm 慌的一笔

**Comment by lovecodeyou** [comment]
翠翠6

**Comment by RebelTinker** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/58228765/e295ed88-17cb-4564-b31a-076cb528652f)

**Comment by FTLIKON** [comment]
一时分不清是反串还是高级黑

**Comment by Ruling95** [comment]
https://www.openharmony.cn/mainPlay
那这个不得更害怕。

**Comment by KuangJieRepository** [comment]
单走一个 6

**Comment by frsimple** [comment]
666

**Comment by herodotus-ecosystem** [comment]
> 回到最原始的全部代码手写实现，提高程序员就业率

先让红薯把开源中国关了

**Comment by bug-mlb** [comment]
em...6

**Comment by luoxiaofeng1029** [comment]
> ![ce49b8b14392483ed2c734209548244](https://private-user-images.githubusercontent.com/17019818/334688956-e1e8c155-d6eb-4b47-8c57-8890ce071891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjkxNzIsIm5iZiI6MTcxNjk2ODg3MiwicGF0aCI6Ii8xNzAxOTgxOC8zMzQ2ODg5NTYtZTFlOGMxNTUtZDZlYi00YjQ3LThjNTctODg5MGNlMDcxODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA3NDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NzRhMDc1YzRmNzUxNGY0ZTc3NTI4YzRkZTVjMThhZDEwYmRiMWFjMmYyZjdjMzhhN2I5NjFiZjZlYWY0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.18IhEbOxdtlkFEff1KOpe-HT-DS-ZFEDrFGYepnmrhA)

![image](https://github.com/baomidou/mybatis-plus/assets/50006313/505645c6-f9c3-4025-9b1a-d707ae537217)

**Comment by StageGuard** [comment]
你无敌了

**Comment by chrelyonly** [comment]
观摩大佬

**Comment by herodotus-ecosystem** [comment]
自动化和效率的提升不是靠加班么？

![image](https://github.com/baomidou/mybatis-plus/assets/11025512/d6d594d0-2eab-4b4d-aaf1-be3e671a5a1e)

**Comment by 1470397673** [comment]
必须要赔偿，不赔偿天理难容的，我先单走一个6

**Comment by dagongzai731** [comment]
6

**Comment by XDRSZYHRL** [comment]
6

**Comment by jidushan200** [comment]
前排
