### ISSUE TITLE
Join Primary key

### ISSUE THREAD

**Issue by MacleZhou** [baomidou/mybatis-plus#622]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
  如何处理联合主键的单表CRUD? 有没有例子？

**Comment by miemieYaho** [comment]
不支持联合主键

**Comment by MacleZhou** [comment]
可以考虑扩展支持吗？比如在TableId中增加Order用于描述主键的顺序。在mapper的selectById中通过变参(Object...obj)来调用

**Comment by miemieYaho** [comment]
不会支持
