### ISSUE TITLE
java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/extension/plugins/inner/InnerInterceptor

### ISSUE THREAD

**Issue by Han-duoduo** [baomidou/mybatis-plus#6221]
在打包后，运行jar包报错：java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/extension/plugins/inner/InnerInterceptor

**Comment by huayanYu** [comment]
检查依赖冲突

**Comment by Han-duoduo** [comment]
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

在build中加入以上plugin 已解决！！
