### ISSUE TITLE
建议：处理typeAliasesPackage时，没必要通过Class.forName获取包名

### ISSUE THREAD

**Issue by JiaRG** [baomidou/mybatis-plus#623]
https://github.com/baomidou/mybatis-plus/blob/38b59908f983764694218a2cfa067366c8ed47b4/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/toolkit/PackageHelper.java#L69
可以使用以下的方式获取：
`ClassUtils.getPackageName(metadataReader.getClassMetadata().getClassName())`

https://github.com/baomidou/mybatis-plus/blob/38b59908f983764694218a2cfa067366c8ed47b4/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/spring/MybatisSqlSessionFactoryBean.java#L475
registerAliases方法后续会处理相关异常情况的

**Comment by JiaRG** [comment]
并且之后将项目的结构打包成下图这种结构时，Class.forName直接抛ClassNotFoundException，但是项目jar中是存在class文件的。
![image](https://user-images.githubusercontent.com/31472350/48254738-ce4f9b00-e445-11e8-8c28-09582574eff7.png)

并且将jar包抽离出去后，通过ClassLoader方式构造的PathMatchingResourcePatternResolver的getResources也返回空数组
https://github.com/baomidou/mybatis-plus/blob/38b59908f983764694218a2cfa067366c8ed47b4/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/SpringBootVFS.java#L27
但是在PackageHelper类中通过无参构造的PathMatchingResourcePatternResolver却可以找到。

最后这里改成无参构造的方式，项目就可以启动了，并且不会影响在IDEA中通过main方法启动

**Comment by hcl04** [comment]
ClassLoader 的锅

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/ae8048e66b135a973a870e7248ecaf94079e3592
