### ISSUE TITLE
mybatis-plus4 凉了吗～

### ISSUE THREAD

**Issue by 721806280** [baomidou/mybatis-plus#6230]
**请详细描述需要增加的功能**

**Comment by whcrow** [comment]
我建议mp团队放弃维护，因为有些issue提的太操蛋、太傻逼了！

**Comment by ESCATS** [comment]
![微信图片_20240603143955](https://github.com/baomidou/mybatis-plus/assets/67588862/ec35597c-096c-4479-9baf-3043bd23d235)
你小子！这个Mybatis-Plus4你来帮我写！

**Comment by nieqiurong** [comment]
去对应仓库提.
