### ISSUE TITLE
代码生成器，entity格式不准确

### ISSUE THREAD

**Issue by tb-bear** [baomidou/mybatis-plus#6232]
![image](https://github.com/baomidou/mybatis-plus/assets/18545839/90b5e8fd-aa13-4c2e-a8e5-ae636633d1d5)
mybatis-plus 版本为：3.5.6
生成的entity，格式化不对有点别扭。希望可以修改模板； 
目前我通过复制修改entity.java.ftl 已经解决自己的问题；希望作者有时间的时候可以修改下模板；
![image](https://github.com/baomidou/mybatis-plus/assets/18545839/070f3812-24c5-4ab5-8284-94c1f9aabfa1)

**Comment by tb-bear** [comment]
解决办法为：
1.依赖中添加 
<dependency>
    <groupId>org.freemarker</groupId>
    <artifactId>freemarker</artifactId>
</dependency>
2. 代码生成器中添加
.templateConfig(builder -> {
    builder.entity("templates/entity.java.ftl");
}).templateEngine(new FreemarkerTemplateEngine())
![image](https://github.com/baomidou/mybatis-plus/assets/18545839/af230dee-b2f4-4efb-91f9-899e7cdd0e22)
指定自己的模板
其中entity.java.ftl是从
![image](https://github.com/baomidou/mybatis-plus/assets/18545839/171f2172-3ec4-4069-9add-b835a19542b7)
复制过来的； 

我把自己的模板发一下， 下载后请修改下名称后缀( 这里不支持传这个后缀的文件)
[entity.java.txt](https://github.com/user-attachments/files/15541592/entity.java.txt)

**Comment by nieqiurong** [comment]
提供复现工程.

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/7026c7f2-449d-4fc4-ade5-a6b987ac0b34)
