### ISSUE TITLE
mybatisplus-generator 没有实现 notLike table 

### ISSUE THREAD

**Issue by Fate02010** [baomidou/mybatis-plus#6234]
**当前使用版本**
mybatis-plus-generator 3.5.6
**当前环境信息**
例如: Java21 + Mysql5.7

**描述bug现象**
    protected List<DatabaseMetaDataWrapper.Table> getTables() {
        // 是否跳过视图
        boolean skipView = strategyConfig.isSkipView();
        // 获取表过滤
        String tableNamePattern = null;
        if (strategyConfig.getLikeTable() != null) {
            tableNamePattern = strategyConfig.getLikeTable().getValue();
        }
        return databaseMetaDataWrapper.getTables(tableNamePattern, skipView ? new String[]{"TABLE"} : new String[]{"TABLE", "VIEW"});
    }

没有实现 notLike
**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by xxx-tea** [comment]
com.baomidou.mybatisplus.generator.config.StrategyConfig#validate
方法中已写了<likeTable> 与 <notLikeTable> 只能配置一项

**Comment by nieqiurong** [comment]
只有在使用SQLQuery的时候才有效，元数据查询方式不支持.
