### ISSUE TITLE
3.4.3.4 怎么没有源码了或者式标签呢

### ISSUE THREAD

**Issue by zp994188707** [baomidou/mybatis-plus#6235]
**当前使用版本**

**当前环境信息**
例如: Java8 + Mysql5.7

**描述bug现象**

**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by huayanYu** [comment]
太久远了，大概忘了。
