### ISSUE TITLE
代码生成器期望能多加点功能

### ISSUE THREAD

**Issue by Shuijiao926** [baomidou/mybatis-plus#6239]
比如我想要生成的Service不要继承父类，或者生成的ServiceImpl自定义实现接口，或者自定义想加哪些注解。
并且Cola架构的话我得写好几遍生成代码，因为mapper、service、DO这些都在不同的包，有没有办法优化呢，一个菜鸟的使用感受

**Comment by huayanYu** [comment]
改模板~

**Comment by Shuijiao926** [comment]
> 改模板~

我知道可以写个模板文件，主要是我想在Java代码里搞定，链式调用就ok了，这样很爽0 - 0

**Comment by nieqiurong** [comment]
不能满足的自行处理.
