### ISSUE TITLE
单元测试，测试逻辑删除与自动填充功能配合使用

### ISSUE THREAD

**Issue by alangong114** [baomidou/mybatis-plus#624]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis plus 3.0.3

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
单元测试，测试逻辑删除与自动填充功能配合使用

### 重现步骤
![image](https://user-images.githubusercontent.com/4981060/48257439-816fc280-e44d-11e8-8e6f-4a6f1494e516.png)

### 报错信息
更新用户信息，逻辑删除时，实际走update 策略，生成sql并没有更新update_time

**Comment by miemieYaho** [comment]
使用 `3.0.6.3-SNAPSHOT` 试试,如果不行,把你详细的代码贴上,你只给出这点信息无法定位错误呀

**Comment by miemieYaho** [comment]
使用 `3.0.6.3-SNAPSHOT` 试试,如果不行,把你详细的代码贴上,你只给出这点信息无法定位错误呀

**Comment by alangong114** [comment]
MetaObjectHandler:
![image](https://user-images.githubusercontent.com/4981060/48300891-00353000-e520-11e8-8570-15e4b4a79e76.png)
Entity：
![image](https://user-images.githubusercontent.com/4981060/48300914-57d39b80-e520-11e8-9a9c-d7b81d27b6b6.png)

参考下，3.0.6.3 还没试，只是我觉得，如果是逻辑删除，实际走的是update method的话，那么在Fill Update的时候应该记录一下 ，我没有仔细跟源码，实际是走勒Fill Update的MetaObjectHandler，但是在实际生成sql时，并没有set入库，逻辑删除，个人感觉还是可以和MetaObjectHandler 搭配的，起码可以知道什么时候被删的

**Comment by miemieYaho** [comment]
你说的逻辑删除啊,那个不行,自动填充是填充到entity里的.删除的入参并不是entity,无法填充.  
最新版本上提供了 `LogicDeleteByIdWithFill` ,你可以用这个,配合自定义basemapper

**Comment by alangong114** [comment]
> 你说的逻辑删除啊,那个不行,自动填充是填充到entity里的.删除的入参并不是entity,无法填充.
> 最新版本上提供了 `LogicDeleteByIdWithFill` ,你可以用这个,配合自定义basemapper

好的，也就是说使用 LogicDeleteByIdWithFill 这个可以完美解决这个需求是吧，那我就先把问题关了
