### ISSUE TITLE
主键生成策略的一个问题

### ISSUE THREAD

**Issue by left0ver** [baomidou/mybatis-plus#6243]
### 当前使用版本(必填,否则不予处理)
3.5.5
主键生成策略设置为NONE，这里注释里说的是跟随全局，全局约等于input
<img width="773" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/89240290/84d7e4fc-9d56-48cc-8b76-16c8edd786a7">
但是全局的默认配置是ASSIGN_ID （使用雪花算法生成）

<img width="662" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/89240290/96a5c3cf-b78a-43c3-b0c1-7a97e612256f">

这里是注解有问题嘛？ 有没有大佬可以解答一下

**Comment by left0ver** [comment]
我自己测试过，主键生成策略配置为NONE，插入数据时，不传id，确实是用雪花算法生成ID

**Comment by miemieYaho** [comment]
全局里

**Comment by left0ver** [comment]
> 全局里

没理解您什么意思

**Comment by miemieYaho** [comment]
NONE在全局里约等于input

**Comment by left0ver** [comment]
> NONE在全局里约等于input

我懂了，感谢🙏
