### ISSUE TITLE
代码生成器 - strategyConfig 配置不生效

### ISSUE THREAD

**Issue by mlrl-github** [baomidou/mybatis-plus#6245]
**当前使用版本**
mybatis-plus-generator-3.5.6

**描述bug现象**
调用了 `disable` 方法, 相应的文件也会生成

**提供问题复现步骤**
FastAutoGenerator generator = FastAutoGenerator.create(url, username, password)
                .globalConfig(builder -> builder
                        .author(author)
                        .outputDir(outputDir)
                )
                .strategyConfig(table -> table
                        .addInclude(tables)
                        .addTablePrefix(tablePrefix)
                )
                .packageConfig(builder -> builder
                        .parent("")
                        .entity("")//entity
                        .mapper("")//mapper
                        .service("")//service
                        .serviceImpl("")//impl
                        .xml("")//xml
                        .controller("")//controller
                )
                .strategyConfig(entity -> entity
                        .mapperBuilder().disable()
                        .controllerBuilder().disable()
                        .serviceBuilder().disable()
                        .entityBuilder().disable()
                )
                .templateEngine(new FreemarkerTemplateEngine());
        generator.execute();

**运行结果**
![image](https://github.com/baomidou/mybatis-plus/assets/52648611/74a22d1b-ad71-4cb5-a8b9-6380c9775a82)

**Comment by liangjihua** [comment]
1

**Comment by liangjihua** [comment]
+1

**Comment by nieqiurong** [comment]
#6060
