### ISSUE TITLE
声明自定义继承的Entity类后，不会去实现序列化接口

### ISSUE THREAD

**Issue by Shuijiao926** [baomidou/mybatis-plus#6252]
加上继承类：
![微信截图_20240612100859](https://github.com/baomidou/mybatis-plus/assets/93018767/6c0352d3-5673-4b87-8aee-33ace2082a69)
![微信截图_20240612100922](https://github.com/baomidou/mybatis-plus/assets/93018767/6acced7a-80cc-4bff-b1ec-9d6c4e31ff65)
不加上：
![微信截图_20240612100938](https://github.com/baomidou/mybatis-plus/assets/93018767/2259b13e-59a5-4dc3-b458-cb6bb8e04766)
![微信截图_20240612101034](https://github.com/baomidou/mybatis-plus/assets/93018767/19e1cd84-12c2-4e8d-bd70-3c15871b6dd7)

**Comment by Shuijiao926** [comment]
代码生成器版本：3.5.2

**Comment by nieqiurong** [comment]
默认统一在父类上实现，在子类上实现设计反序列问题，如果你有单独自行调整模板即可。
