### ISSUE TITLE
分页能否自定义拓展，期望支持hologres

### ISSUE THREAD

**Issue by superzhang2013** [baomidou/mybatis-plus#6253]
**当前使用版本**
3.5.2

**当前环境信息**
例如: Java21 + Mysql5.7

**描述bug现象**
**旧有连接clickhouse代码迁移到hologres，分页相关方法异常**
![hologres](https://github.com/baomidou/mybatis-plus/assets/3965146/9afa9dfc-b25c-4012-8c54-771d3e237bf1)

**Comment by nieqiurong** [comment]
https://help.aliyun.com/zh/hologres/user-guide/use-jdbc-to-connect-to-hologres?spm=a2c4g.11186623.0.0.219a55c5wxOCr4
