### ISSUE TITLE
3.5.7版本，批量操作添加事务

### ISSUE THREAD

**Issue by gofunn** [baomidou/mybatis-plus#6254]
**请详细描述需要增加的功能**
如题。
批量操作是否应该像之前的方法`com.baomidou.mybatisplus.extension.service.impl.ServiceImpl#saveBatch`一样，添加事务

**Comment by gofunn** [comment]
其他方法都是ByIds的命名，不知道这个是不是漏掉了。
`com.baomidou.mybatisplus.core.mapper.BaseMapper#selectBatchIds(java.util.Collection<? extends java.io.Serializable>)`

**Comment by gofunn** [comment]
BaseMapper里没有这个方法，是否会加上？
`com.baomidou.mybatisplus.extension.service.IService#page(E)`

**Comment by nieqiurong** [comment]
1.selectBatchIds下个版本改了。
2.事务建议自行管理,BaseMapper不是为了替代Service层。
