### ISSUE TITLE
3.5.7关于service层removeBatchByIds的建议

### ISSUE THREAD

**Issue by DonkeyWang** [baomidou/mybatis-plus#6257]
3.5.7版本service里的removeBatchByIds,没有了参数list是否为空集合的校验,老版本传入一个new ArrayList()是没有问题的,现在新版本会报错,致使项目没法平滑升级.想问一下,后续版本会不会再次加入这个校验,让项目可以平滑升级

**Comment by nieqiurong** [comment]
已发布 3.5.8-SNAPSHOT
