### ISSUE TITLE
Mapper重写了selectPage方法，第二个参数使用实体，但是报错

### ISSUE THREAD

**Issue by a5613150** [baomidou/mybatis-plus#6259]
**当前使用版本**
3.5.0

**描述bug现象**
我有一个项目，Mapper重写了selectPage(@Param("page")Page pageContext, @Param("entity")Entity entity)方法，是可以正常调用xml里面的方法。
但是我使用另一个项目使用同样的写法，却报错了。以下是报错信息
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'ew' not found. Available parameters are [entity, page, param1, param2]

**Comment by miemieYaho** [comment]
Mapper不要使用相同的名称命名method,mybatis不认,没报错只能说你运气好你自己写的覆盖掉了另一个

**Comment by a5613150** [comment]
我找到原因了，原来我的xml，namespace没写正确，导致映射不到mapper类，可能就调用mybatisplus的方法了，所以就报错了。是可以覆盖掉mybatisplus的selectPage方法的。
