### ISSUE TITLE
分页报错，按照https://mp.baomidou.com/guide/page.html配置

### ISSUE THREAD

**Issue by flb0704** [baomidou/mybatis-plus#626]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus：3.0.5
mybatis:3.4.6
mybatis-spring:1.3.2
mybatis-plus-boot-starter：3.0.5
都是最新版本

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
直接按照官方文档配置的分页，报错

### 重现步骤
Mapper接口：
`Page<Map> getRecentMatchsByTeamId(Integer teamId, Page page);`

XML:
`<select id="getRecentMatchsByTeamId" resultType="map">
        ......
    </select>`

Service接口：
`Page<Map> getRecentMatchsByTeamId(Integer teamId,Page page);`

Service实现类：
```
public Page<Map> getRecentMatchsByTeamId(Integer teamId, Page page) throws BusinessException {
        return teamsDotaTMapper.getRecentMatchsByTeamId(teamId, page);
    }
```

在返回的时候项目中定义的全局异常捕获到信息

### 报错信息
o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Resolved exception caused by Handler execution: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 10

**Comment by flb0704** [comment]
问题已解决，该了Mapper接口的返回方式为：
`List<Map> getRecentMatchsByTeamId(Integer teamId, Page page);`
返回正常，后面在Service层自己重新做了下处理：
`Page pageResult=new Page();
        pageResult.setRecords(mapper接口返回的数据);
        pageResult.setPages(page.getPages());
        pageResult.setCurrent(page.getCurrent());
        pageResult.setSize(page.getSize());
        pageResult.setTotal(page.getTotal());`

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-pagination
