### ISSUE TITLE
关于Page.records默认值的问题

### ISSUE THREAD

**Issue by Alleninggx** [baomidou/mybatis-plus#6263]
![image](https://github.com/baomidou/mybatis-plus/assets/40049392/22cbc0d5-c714-4a42-afa3-14d75b277df1)

这里的EmptyList对象虽然是可序列化的，但是是一个immutable列表。

![image](https://github.com/baomidou/mybatis-plus/assets/40049392/f7da9fb0-c273-49f1-ad47-d20f77d1670d)

所以在Dubbo夸服务传输时，使用fastjson2对Page对象反序列化，会用List.add方法来添加records元素，导致会抛出UnsupportedOperationException异常。

所以这里的records是否可以用一个非immutable列表作为默认值？

对于PageDTO，描述是作为夸服务使用的，但我不了解怎么解决这个问题，请指教。

**Comment by nieqiurong** [comment]
虽然可以修改成普通的ArrayList，但这大概率也可以通过升级fastjson解决.

**Comment by Alleninggx** [comment]
fastjson已经是最新版本了

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/c0ba6023-cf23-43fb-9a39-738cab1e327f)
测试看着没什么问题,你断点看下readJSONBObject方法里面的参数把.

**Comment by nieqiurong** [comment]
不确定是不是些这样的问题.
https://github.com/alibaba/fastjson2/issues/1835

**Comment by Alleninggx** [comment]
看issue里描述是同一个问题，我看看fastjson2那边能不能解决吧

**Comment by nieqiurong** [comment]
拿fastjson的代码验证了一下,只有存在属性为public的情况才能复现这个情况,不确定是否为同个情况,需要补充复现工程来看看.

**Comment by nieqiurong** [comment]
你的响应模型是自定义的还是直接PageDto?
```java
public class App {

    public static void main(String[] args) {
        Page<Person> page = new Page<>();
        List<Person> data = new ArrayList<>();
        data.add(null);
        data.add(new Person("abc"));
        data.add(null);
        // page.data = Collections.unmodifiableList(data);
        page.setData(data);
        byte[] bytes = JSONB.toBytes(page);
        Page page1 = JSONB.parseObject(bytes, Page.class);
        System.out.println(page1);

    }

    public static class Person {
        private String name;

        public Person() {
        }

        public Person(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

    }

    public static class Page<T> {

        // 属性为public下才会出问题.
        public List<T> data = Collections.emptyList();

        public void setData(List<T> items) {
            this.data = items;
        }

        public List<T> getData() {
            return data;
        }

    }

}
```

**Comment by Alleninggx** [comment]
Mapper定义了这个，然后一路原样返返回（mapper->service->dubbo->另一个server）。

Mapper：
![image](https://github.com/baomidou/mybatis-plus/assets/40049392/8bbacfa4-7d12-40bd-96fa-eb940cd3775c)
Dubbo：
![image](https://github.com/baomidou/mybatis-plus/assets/40049392/cbd6e94d-c60a-433f-af21-c6b43ec6bbd9)

在Dubbo序列化前，具体类型是Page。

**Comment by Alleninggx** [comment]
@nieqiurong https://github.com/Alleninggx/MybatisPlus-test
这是复现工程
![image](https://github.com/baomidou/mybatis-plus/assets/40049392/e197b840-969d-4633-acc7-e4715cc00c26)


改一下redis地址，先启动provider，再启动customer

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/0f7f09a3-aa94-4b09-9245-2b3e28686975)
发现是开启了这个就有影响,具体还得看下fastjson源码了.

**Comment by nieqiurong** [comment]
https://github.com/alibaba/fastjson2/issues/2734
