### ISSUE TITLE
mybatis plus分页插件不生效

### ISSUE THREAD

**Issue by viviqy** [baomidou/mybatis-plus#627]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.5</version>
</dependency>

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
查询分页数据时 , 发现IPage里records返回的是所有条件查询数据 , 并没有只返回分页数据

### 重现步骤

启动类:
@SpringBootApplication(exclude = {DruidDataSourceAutoConfigure.class})
@EnableTransactionManagement
@MapperScan(value = {"com.dao.*"})
@EnableScheduling
@EnableElasticsearchRepositories
public class TemplateApplication {
    public static void main(String[] args) {
        SpringApplication.run(TemplateApplication.class, args);
    }
}

配置类:
@Configuration
public class MybatisPlusConfig {
    @Bean
    public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
        paginationInterceptor.setDialectType("mysql");
        return paginationInterceptor;
    }
}

测试方法:
 public void run7() {
        Page<Total> totalPage = new Page<>(1,10);
        IPage<Total> totalIPage = totalMapper.selectPage(totalPage, new QueryWrapper<Total>()
                .between(Total.VALUE, 1, 1000)
                .eq(Total.TOTAL_TYPE_ID, 5));
        System.out.println(totalIPage.getRecords().size());
        System.out.println(paginationInterceptor);
    }

mybatis.xml:
 <bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
        <property name="dataSource" ref="dynamicDatasource"></property>
        <property name="configLocation" value="classpath:mybatis/config/mybatis-config.xml"></property>
        <property name="mapperLocations" value="classpath:mybatis/mapper/**/*.xml"></property>
        <property name="typeAliasesPackage" value="com.pojo.entity"></property>
    </bean>

显示结果:
570
AbstractSqlParserHandler(sqlParserList=null, sqlParserFilter=null)

logger下sql信息:
2018-11-12 18:04:29.342 [main] DEBUG-c.m.t.d.v.T.selectPage - ==>  Preparing: SELECT id,name,value,total_type_id,created_time,extend1,extend2 FROM total WHERE value BETWEEN ? AND ? AND total_type_id = ? 
2018-11-12 18:04:29.369 [main] DEBUG-c.m.t.d.v.T.selectPage - ==> Parameters: 1(Integer), 1000(Integer), 5(Integer)
2018-11-12 18:04:29.455 [main] DEBUG-c.m.t.d.v.T.selectPage - <==      Total: 570

发现末尾sql并未拼接limit

### 报错信息
无报错 , 当取消sql分析插件, 发现执行时sql语句也会打印

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/tree/master/mybatis-plus-sample-pagination
