### ISSUE TITLE
3.5.7版本BaseMapper#insert返回值

### ISSUE THREAD

**Issue by wzkris** [baomidou/mybatis-plus#6275]
**当前使用版本**
3.5.7
**当前环境信息**
jdk17

**描述bug现象**
BaseMapper#insert批量方法的返回值个数和插入条目个数不一致

![1718952905505](https://github.com/baomidou/mybatis-plus/assets/90759163/e142f2ae-fbf2-4a1b-9da7-1fbe98cf4f74)

updateById批量方法也有这样的问题

**Comment by nieqiurong** [comment]
BatchResult里面有个updateCounts数组
