### ISSUE TITLE
增加 海量数据库 的支持

### ISSUE THREAD

**Issue by lilanlong** [baomidou/mybatis-plus#6276]
增加 海量数据库 的支持

**Comment by huayanYu** [comment]
https://github.com/baomidou/mybatis-plus/pull/5355/files  参考提交即可

**Comment by lilanlong** [comment]
如何提交代码呢




害羞的男孩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 增加 海量数据库 的支持 (Issue #6276)





 
https://github.com/baomidou/mybatis-plus/pull/5355/files  参考提交即可
