### ISSUE TITLE
oracle sequence 获取失败

### ISSUE THREAD

**Issue by awswt** [baomidou/mybatis-plus#628]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
插入数据时,未能获取到@KeySequence上的序列的值

### 重现步骤
person类

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@Data
@TableName("SR_PERSON")
@KeySequence("SEQ_SR_PERSON")
public class SRPerson extends BaseColumns {
    @TableId(value = "PK", type = IdType.INPUT)
    private Long pk;

    private String custom1;

    private String custom2;
...
}

为何xml配置展示不出......
xml配置如下:
`
<bean id="sqlSessionFactoryHieData" primary="true" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
        <property name="dataSource" ref="dataSourceHieData"/>
        <property name="mapperLocations" value="classpath*:mybatis/hie/*/*Mapper.xml"/>
        <property name="globalConfig" ref="globalConfig"/>
    </bean>
`
  

    <bean id="globalConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig">
        <property name="dbConfig" ref="dbConfig"/>
     </bean>

    <bean id="dbConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig.DbConfig">
        <property name="idType" value="INPUT"/>
        <property name="keyGenerator"  ref="OracleKeyGenerator"/>
    </bean>

    <bean id="OracleKeyGenerator" class="com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator"/>

 
` 
<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="com.ats.sr.dao.mapper.hie"/>
        <property name="sqlSessionFactoryBeanName" value="sqlSessionFactoryHieData"/>
    </bean>
`

**Comment by yuxiaobin** [comment]
配置typeAliasesPackage

**Comment by awswt** [comment]
> 配置typeAliasesPackage

还是不行,一样的报错,

**Comment by miemieYaho** [comment]
idType设置为AUTO试试

**Comment by yuxiaobin** [comment]
加qq群说吧 648281531

**Comment by yuxiaobin** [comment]
MVC配置如下，经测，没发现问题，
提交:https://gitee.com/baomidou/mybatis-plus-samples/commit/2b68419c1e9807462a0542ad6273f880930387bd

`
<bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
        <property name="dataSource" ref="dataSource"/>
        <property name="globalConfig" ref="globalConfig"/>
        <property name="plugins">
            <array>
                <bean class="com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor"></bean>
            </array>
        </property>

    </bean>

    <bean id="globalConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig">
        <property name="dbConfig" ref="dbConfig"/>
    </bean>

    <bean id="dbConfig" class="com.baomidou.mybatisplus.core.config.GlobalConfig.DbConfig">
        <property name="keyGenerator" ref="keyGenerator"/>
    </bean>

    <bean id="keyGenerator" class="com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator"/>
`
