### ISSUE TITLE
两个不同实体类的Wrapper可以直接复制where条件吗？

### ISSUE THREAD

**Issue by yinseyeying** [baomidou/mybatis-plus#6282]
假如我有Wrapper<User>和Wrapper<Person>。Wrapper<User>.eq().in().likeleft()...已经设置了一批where条件，是否有什么方法可以直接将所有条件复制到Wrapper<Person>？假如两个表的字段完全一致。
如果可以的话，希望也教一下group是否能直接复制，谢谢！

**Comment by nieqiurong** [comment]
没得

**Comment by yinseyeying** [comment]
> 没得

那后续有考虑实现这个功能吗？

**Comment by huayanYu** [comment]
没计划
