### ISSUE TITLE
Java Flight Recorder finds many exceptions thrown by Mybatis-Plus, e.g. "java.lang.NoSuchMethodError"

### ISSUE THREAD

**Issue by YangyangLi-dev** [baomidou/mybatis-plus#6285]
**当前使用版本**
<groupId>com.baomidou</groupId>
<artifactId>mybatis-plus-boot-starter</artifactId>
<version>3.5.7</version>
**当前环境信息**

Java8 + PostgreSQL
**描述bug现象**
146 errors were thrown in total. The most common error was ''java.lang.NoSuchMethodError'', which was thrown 81 times. Investigate the thrown errors to see if they can be avoided. Errors indicate that something went wrong with the code execution and should never be used for flow control.
<img width="1440" alt="MP-errors found by flight recorder" src="https://github.com/baomidou/mybatis-plus/assets/21339369/e9fab5b4-1cab-4229-a5b5-75d4ec1ea760">

**提供问题复现步骤**
Run application and start java flight recorder, generate .jfr file then use java mission control to analyse .jfr file
**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by nieqiurong** [comment]
错误堆栈呢?

**Comment by YangyangLi-dev** [comment]
> 错误堆栈呢?

Message	Count
java.lang.Object.insertOrUpdate(Ljava/lang/Object;)

java.lang.Object.selectPage(Lcom/baomidou/mybatisplus/core/metadata/IPage;Lcom/baomidou/mybatisplus/core/conditions/Wrapper;)Lcom/baomidou/mybatisplus/core/metadata/IPage;

**Comment by VampireAchao** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by VampireAchao** [comment]
可以尝试检查依赖是否冲突

另外请给出复现Demo，若无问题，我将在一段时间(也许几天)后关闭本issue
