### ISSUE TITLE
BaseMapper 增加基础接口

### ISSUE THREAD

**Issue by fashionbrot** [baomidou/mybatis-plus#6289]
**请详细描述需要增加的功能**
1、BaseMapper是否可以增加 existsId 接口  传入主键Id 即可查询
2、BaseMapper是否可以增加 saveBatch、updateBatch 接口，不使用IService、ServiceImpl 也可以使用 saveBatch 
3、BaseMapper是否可以增加 updateEntityById 接口如下：
    int updateEntityById (@Param(Constants.ENTITY) T entity, Serializable id);

**Comment by wzkris** [comment]
1不是已经存在exist方法了
2在最新版已经实现
3和updateById有什么区别？
