### ISSUE TITLE
日志打印有输出空字符串，实际没有插入字符串，插入了null

### ISSUE THREAD

**Issue by AlfieLao** [baomidou/mybatis-plus#6290]
**当前使用版本**
3.4.3.2
**当前环境信息**
例如: Java8 + Oracle

**描述bug现象**
使用getBaseMapper().insert()插入数据，日志打印有输出空字符串，实际没有插入字符串，插入了null
该字段配置如下：
两种配置都试过
@TableField(insertStrategy=FieldStrategy.NOT_NULL, value = "field7")
@TableField(insertStrategy=FieldStrategy.IGNORED, value = "field7")
private String field7;

插入的时候，日志如下：
024-06-27 11:21:13.674 DEBUG 13568 ---[nio-8199-exec-6]
c.i.f.m.BoFieldsValueMapp er.insert:==>
Preparing: INSERT INTO BO_FILEDSVALUE149( projectld, field1, field2, field3, field4, field5, field6, field7, createBy, branch, dateTime, currDept, status, lastDate) VALUES
( ?, ?, ?, ?, ?,?, ?, ?,?, ?,?,? ?, ? )
2024-06-27 11:21:13.679 DEBUG 13568 ---[nio-8199-exec-6]
c.i.f.m.BoFieldsValueMapp
er.insert ==> 
Parameters:149(String),
2024-06-14(String), e(String), test(String), test(String), test(String),(String),(String),
test(String), test(String),2024-06-2711:21:13(String),
test(String), 1(String),2024-06-2711:21:13(String)
2024-06-27 11:21:13.685 DEBUG 13568 ---[nio-8199-exec-6]
c.i.f.m.BoFieldsValueMapp er.insert :<== Updates:1

但是结果是插入了null，而不是空字符串
![Uploading image.png…]()

**提供问题复现步骤**
同上
**提供完整堆栈日志(可选)**
见上面
**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.
内网开发，工程带不出来

**Comment by nieqiurong** [comment]
用示例工程提供一个复现的小用例.
