### ISSUE TITLE
velocity模板(entity.java.vm)中的变量${springdoc}未正确获取，导致生成代码的注解没有正确生成

### ISSUE THREAD

**Issue by qgao233** [baomidou/mybatis-plus#6305]
**当前使用版本**
springdoc-openapi-starter-webmvc-api: 2.0.2，
mybatis-plus-generator: 3.5.5

**当前环境信息**
例如: Java21 + Mysql8

**描述bug现象**
velocity模板(entity.java.vm)中的变量${springdoc}未正确获取，导致生成代码的注解没有正确生成。

根据模板内容可知，要在springdoc=true时，才会生成，如下代码所示：
```
#if(${springdoc})
import io.swagger.v3.oas.annotations.media.Schema;
#elseif(${swagger})
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
#end
```
但实际上还是诊断成swagger下的注解了，如下实际生成代码：
```
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel(value = "AppUserActivity对象", description = "test")
public class AppUserActivity {
```

**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by nieqiurong** [comment]
复现代码.
