### ISSUE TITLE
自动生成主键id在微软云上不生效

### ISSUE THREAD

**Issue by wkk89** [baomidou/mybatis-plus#6307]
**当前使用版本**
3.3.1
**当前环境信息**
Java8 + Mysql5.7

**描述bug现象**
    @Bean
    public MybatisPlusPropertiesCustomizer plusPropertiesCustomizer() {
        return plusProperties -> plusProperties.getGlobalConfig()
                .setBanner(false)
                .setMetaObjectHandler(new DateMetaObjectHandler())
                .setIdentifierGenerator(entity -> UniqueIdUtil.nextId());
    }
同样的代码在阿里云上面可以正常给id赋值，但是在微软云无法给id赋值

**提供问题复现步骤**

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by nieqiurong** [comment]
那给微软云提工单,说不适配你的代码.
