### ISSUE TITLE
实体类id是int类型, 调用insert方法后, id没有写入值

### ISSUE THREAD

**Issue by scheshan** [baomidou/mybatis-plus#631]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

```
        User user = new User();
        userMapper.insert(user);

        System.out.println(user.getId());
```

### 报错信息

User的ID列是long类型才能自动写入值,如果是int则不会写入.

**Comment by miemieYaho** [comment]
本来就这样

**Comment by scheshan** [comment]
这是出于什么考虑呢? int做主键也很多啊

**Comment by scheshan** [comment]
翻了一圈代码,并不是这个原因..................

有个TableId 注解,加到字段就可以用数据库自增列生成的值,不加注解的话是自动生成的值,看上去和时间戳相关
