### ISSUE TITLE
Occasionally occurs java.lang.NullPointerException，but retrying fixes it

### ISSUE THREAD

**Issue by Huankongwu** [baomidou/mybatis-plus#6313]

**Comment by Huankongwu** [comment]
我无法确认这个是 mabatis-plus还是 mybatis 的问题

**Comment by sangewuxie** [comment]
不，这个也是我提交的，但是他们怀疑是 mybatis-plus的问题

**Comment by nieqiurong** [comment]
如果是本地完整的复现的,请提供示例工程,如果是线上运行时间发生的,得找到最初的日志堆栈,可能是Fast Throw后面得堆栈没打印了.

**Comment by Huankongwu** [comment]
> 如果是本地完整的复现，请提供示例工程，如果是线开发商时间到来，得找到最初的日志堆栈，可能是Fast Throw后面得堆栈没打印了。

这是最底层的栈信息了

**Comment by Huankongwu** [comment]
> 如果是本地完整的复现，请提供示例工程，如果是线开发商时间到来，得找到最初的日志堆栈，可能是Fast Throw后面得堆栈没打印了。

这个很难复现，偶发，需要大量数据下，偶现一次

**Comment by nieqiurong** [comment]
这种堆栈参考信息太少了,不足以看出什么问题.只能说在mybatis下这种问题一样的会有.
例如这就是线上日志,由于jvm优化后后面得堆栈就没了.
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/6ab74110-2a13-4cb5-b089-deb32fb080af)

**Comment by Huankongwu** [comment]
辛苦删除这个问题，栈未看全，底层其他的出现问题
