### ISSUE TITLE
严重问题：3.5.7重写了deleteByIds，如果项目使用了乐观锁，做了空异常校验，会抛出异常

### ISSUE THREAD

**Issue by AEnchanter** [baomidou/mybatis-plus#6315]
版本： 3.5.7

环境：无所谓

现象：使用removeBatchByIds方法，调用了mapper的deleteByIds方法，入参会封装成Map，实体类et放入的是空对象，而乐观锁校验时，会对参数为空的进行异常校验，导致抛出异常
![image](https://github.com/baomidou/mybatis-plus/assets/52193793/b25b98a0-2c1a-4f97-ac83-48591cc6c919)
![image](https://github.com/baomidou/mybatis-plus/assets/52193793/93e8b94c-0ff7-4a5b-bc11-09ee25f8bd7c)

复现步骤：开启乐观锁，自定义异常。采用逻辑删除，调用deleteByIds方法

**Comment by nieqiurong** [comment]
已发布 3.5.8-SNAPSHOT
