### ISSUE TITLE
2.x版本内Wrapper.formatSqlIfNeed方法性能问题

### ISSUE THREAD

**Issue by JasonCL2015** [baomidou/mybatis-plus#632]
### 我们在使用Wrapper构造查询条件时，使用了Wrapper<T> in(String column, Object... value)，我们发现当查询条件集合例如userIdList很大时，性能下降显著，后来发现是Wrapper.formatSqlIfNeed方法内部的这段字符串替换的原因导致，请问这块是否考虑优化？
`sqlStr = sqlStr.replace(String.format("{%s}", i), String.format("#{%s.paramNameValuePairs.%s}", this.getParamAlias(), genParamName));`

**Comment by JasonCL2015** [comment]
完整代码如下，for循环params，内部sqlStr.replace又是一个遍历循环，建议这里拆成多个${%s}，用StringBuffer拼接后返回
`protected String formatSqlIfNeed(boolean need, String sqlStr, Object... params) {
        if (need && !StringUtils.isEmpty(sqlStr)) {
            if (ArrayUtils.isNotEmpty(params)) {
                for(int i = 0; i < params.length; ++i) {
                    String genParamName = "MPGENVAL" + this.paramNameSeq.incrementAndGet();
                    sqlStr = sqlStr.replace(String.format("{%s}", i), String.format("#{%s.paramNameValuePairs.%s}", this.getParamAlias(), genParamName));
                    this.paramNameValuePairs.put(genParamName, params[i]);
                }
            }

            return sqlStr;
        } else {
            return null;
        }
    }`

**Comment by yuxiaobin** [comment]
这个建议自己手动拼sql，不然内部的map要扩展很多次
StringBuilder sb = new xxx;
sb.append(); //sb-> 1,2,3,4,5
ew.and(" xx_column in ("+sb+")")

**Comment by JasonCL2015** [comment]
隐藏的坑难道不修复吗，官方文档也没有友情提示的。
