### ISSUE TITLE
有支持Wrapper多表jion的计划吗

### ISSUE THREAD

**Issue by catgptjourney** [baomidou/mybatis-plus#6323]
**请详细描述需要增加的功能**

**Comment by jaimyjie** [comment]
把这个库的功能移植过来就可以了：https://github.com/yulichang/mybatis-plus-join

**Comment by catgptjourney** [comment]
> 把这个库的功能移植过来就可以了：https://github.com/yulichang/mybatis-plus-join

这个库支持非Mysql数据库吗？

**Comment by miemieYaho** [comment]
未知

**Comment by jaimyjie** [comment]
> > 把这个库的功能移植过来就可以了：https://github.com/yulichang/mybatis-plus-join
> 
> 这个库支持非Mysql数据库吗？

他也是基于MyBatis-Plus的增强工具，我实际只用mysql，具体其他数据库是否支持需要分析下源代码
