### ISSUE TITLE
映射的表实体类上使用多行注释使用注解@TableName调用mybatis-plus自动装配的SQL都会造成读取到多行注释的内容

### ISSUE THREAD

**Issue by EntiWe** [baomidou/mybatis-plus#6325]
**当前使用版本**
3.5.7
**当前环境信息**
SpringBoot3.3+java22+mysql

**描述bug现象**
在映射的表实体类上使用多行注释并且使用注解@TableName后，调用insert或者其它的mybatis-plus自动装配的SQL都会造成读取到多行注释的内容
具体情况如下：
![image](https://github.com/baomidou/mybatis-plus/assets/49016942/9a79caf9-ad4c-413a-84ff-d929d31c95c4)
![image](https://github.com/baomidou/mybatis-plus/assets/49016942/14e93ddd-2a03-4cc0-a4a2-37972f23df8c)

**提供问题复现步骤**
![image](https://github.com/baomidou/mybatis-plus/assets/49016942/3e24233a-4196-4786-9198-82228af8761e)

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by miemieYaho** [comment]
去找java
