### ISSUE TITLE
SqlServerQuery tablesSql 表描述乱码

### ISSUE THREAD

**Issue by jackychan123** [baomidou/mybatis-plus#6334]
**当前使用版本**

**当前环境信息**
例如: Java17 +  SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 

**SqlServerQuery 中tablesSql 使用cast(sep.value as varchar(500)) as COMMENTS 会出现乱码，应该改为cast(sep.value as nvarchar(500)) as COMMENTS**

**Comment by nieqiurong** [comment]
你测试通过了的话可以考虑提交上来，我没得数据库环境
