### ISSUE TITLE
在使用left join编写做多表联查时当我将从表中的字段作为查询条件的时候报错

### ISSUE THREAD

**Issue by EntiWe** [baomidou/mybatis-plus#6336]
**当前使用版本**
Mybatis-plus 3.5.7

**当前环境信息**
不重要

**描述bug现象**
在使用left join编写做多表联查时当我将从表中的字段作为查询条件的时候报错

**提供问题复现步骤**
![image](https://github.com/user-attachments/assets/74367925-f4ad-4c38-8c6f-ff8879d8199f)
![image](https://github.com/user-attachments/assets/faa385fd-2d54-4c13-8769-cb14d9c022c5)

**提供完整堆栈日志(可选)**
java.lang.ClassCastException: class net.sf.jsqlparser.statement.select.ParenthesedSelect cannot be cast to class net.sf.jsqlparser.schema.Table (net.sf.jsqlparser.statement.select.ParenthesedSelect and net.sf.jsqlparser.schema.Table are in unnamed module of loader 'app')

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by nieqiurong** [comment]
提供详细堆栈
