### ISSUE TITLE
[Bug]: mybatis-plus-boot-starter 3.5.5 使用逻辑删除功能后，saveOrUpdateBatch报主键已存在错误

### ISSUE THREAD

**Issue by krislinzhao** [baomidou/mybatis-plus#6342]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

mybatis-plus-boot-starter 3.5.5

### 问题描述

使用逻辑删除功能后，saveOrUpdateBatch报主键已存在错误

**Comment by rowstop** [comment]
逻辑删除了你还查出来了？还是说主键的值是你自己塞进去的
第一种情况 查得时候过滤掉
第二种情况 看看能不能用别的值呢？否则这张表就别用逻辑删除
