### ISSUE TITLE
aa_bb_2），查询的时候sql会把 '_' 线去掉换成 'aa_bb2'

### ISSUE THREAD

**Issue by 46133** [baomidou/mybatis-plus#635]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.4  ; 3.0-RC3

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

自动生成mapper, 
数据库中 字段以下划线和数字结尾（aa_bb_2），查询的时候sql会把 数字前'_' 线去掉换成 'aa_bb2'，导致找不到该字段
通过@TableField指定可以解决

### 重现步骤
生成一下看看

### 报错信息
找不到该列

**Comment by miemieYaho** [comment]
你的entity字段名叫 `aaBb2` ?

**Comment by zhfish** [comment]
会这样，不排除有数字表名。

**Comment by miemieYaho** [comment]
你这种只有注解指定,你最后有个数字,我们又如何知道该不该在前面加`_`呢?
