### ISSUE TITLE
[功能改进]: IService接口里的getById方法

### ISSUE THREAD

**Issue by dujiecn** [baomidou/mybatis-plus#6352]
### 当前程序版本

最新版

### 功能改进

比如现在数据库的表的主键ID字段是递增的，为了性能考虑不能使用uuid的字符串
而具有业务含义的ID是bizId字段，是uuid字符串格式。
需求：查询的时候不用递增的ID查询，而改用bizId查询。是否可以作为配置项来改变getById查询的字段名？

### 参考资料

无

**Comment by miemieYaho** [comment]
不支持
