### ISSUE TITLE
[BUG]: xml 有 sample 报net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","

### ISSUE THREAD

**Issue by kx-hdh** [baomidou/mybatis-plus#6357]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

MP 版本 3.5.7
数据库是MySQL 8.0
### 问题描述

使用了大家解决空格的最简易的方式
  **configuration:
    shrink-whitespaces-in-sql: true**
也使用了 **mpBs.sql().replaceAll("(\\r?\\n){2,}", "$1")**
最后发现是sample导致的
SQL是 Parsing SQL: SELECT a.id AS "id",sample.name AS "sample.name" FROM l_sample_out_details a LEFT JOIN l_sample_out_manage sample ON sample.id = a.out_library_id
this.parserSingle 会报错

### 详细堆栈日志

```bash
Was expecting one of:

    <EOF>
    <ST_SEMICOLON>

net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
```

**Comment by miemieYaho** [comment]
jsqlparser的事你在这里报没用

**Comment by kx-hdh** [comment]
@miemieYaho 主要之前版本都是好的，是不是考虑换用版本

**Comment by miemieYaho** [comment]
没那么容易，你可以自己试试看他有没有新版本发布你用报不报错

**Comment by wzkris** [comment]
降级呗，还能咋

**Comment by nieqiurong** [comment]
换个别名规避一下.

**Comment by nieqiurong** [comment]
按照规避  net.sf.jsqlparser.parser.CCJSqlParserConstants#tokenImage
