### ISSUE TITLE
[功能改进]: 插入数据主键重复冲突问题 DuplicateKeyException

### ISSUE THREAD

**Issue by misakim1ngzzz** [baomidou/mybatis-plus#6358]
### 当前程序版本

3.4.0

### 功能改进

单机单实例使用不当也会导致主键冲突, 原因是一张表生成Id的规则混用,一部分使用IdWoker静态方法生成,另一部分使用globalConfig的DefaultIdentifierGenerator生成，这是两个Instance, 高并发大概率会导致主键生成冲突

1. 框架 默认是 IdType.ASSIGN_ID的生成器实例 `com.baomidou.mybatisplus.core.MybatisSqlSessionFactoryBuilder#build(org.apache.ibatis.session.Configuration)`

![image](https://github.com/user-attachments/assets/f0ca2e17-cc7e-4ab6-8b09-35dad3435c39)

3. IdWoker静态方法注入的生成器

![image](https://github.com/user-attachments/assets/4aeafb2e-569e-4758-bba4-3e6c1716e962)

4. 希望global不要单独new Generator实例直接使用IdWoker静态方法

**Comment by miemieYaho** [comment]
用最新版再说话
