### ISSUE TITLE
[求大佬指点]:  mybatis plus + dynamic datasource 集成多数据源，如何配置不同的数据库前缀

### ISSUE THREAD

**Issue by kai23333** [baomidou/mybatis-plus#6359]
### 当前程序版本

3.5.4

### 功能改进

mybatis配置如下：
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: is_deleted 
      logic-delete-value: 1 
      logic-not-delete-value: 0 
      table-prefix: prefix1_
    enable-sql-runner: false
  mapper-locations: classpath:mapper/*.xml

求大佬指点， table-prefix如何配置多个，对应到dynamic datasource多个数据源

**Comment by miemieYaho** [comment]
不支持

**Comment by huayanYu** [comment]
不支持哦，只能自己构建静态多数据源多MP
