### ISSUE TITLE
生成环境配置什么才能不打印sql语句

### ISSUE THREAD

**Issue by lettgers** [baomidou/mybatis-plus#636]
当前版本是3.0.5

生成环境配置什么才能不打印sql语句?

**Comment by miemieYaho** [comment]
没使用 mp提供的插件情况下, 出门右转 www.baidu.com

**Comment by lettgers** [comment]
您好,我用的是mp,按照文档配置的spring-boot配置的,启动后默认就打印了日志,我想线上环境不打印sql的日志,需要怎么配置

在 2018-11-17 20:16:48，"miemieYaho" <notifications@github.com> 写道：


没使用 mp提供的插件情况下, 出门右转 www.baidu.com

**Comment by miemieYaho** [comment]
没有特殊配置下是不会打印 sql 日志的,你去了解一下 boot 的日志配置吧

**Comment by lettgers** [comment]
ok 谢谢 可能是我配置的logback的原因

在 2018-11-19 14:16:42，"miemieYaho" <notifications@github.com> 写道：


没有特殊配置下是不会打印 sql 日志的,你去了解一下 boot 的日志配置吧

**Comment by thlws** [comment]
遇到一样的问题，虽然issue closed，还是贴下把，总有人会搜索进来
注释掉下面的部分，就不会打印。
mybatis-plus:
  mapper-locations: mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

**Comment by liuhaojava** [comment]
> 遇到一样的问题，虽然问题已关闭，还是贴下吧，总有人会搜索进来
> 注释掉下面的部分，就不会打印。
> 
> ```
> mybatis-plus:
>   mapper-locations: mapper/*.xml
> #  configuration:
> #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
> ```

本地环境是好的，生产环境docker部署 docker logs任然会打印出来sql log
