### ISSUE TITLE
[错误报告]: 执行saveOrUpdate方法是报错：Handler dispatch failed: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by xietianbao80** [baomidou/mybatis-plus#6361]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

执行saveOrUpdate方法是报错：Handler dispatch failed: java.lang.StackOverflowError

![QQ图片20240726180152](https://github.com/user-attachments/assets/3176c848-4a45-4fed-9be0-68489310f6af)

在3.5.5及以下没有此问题

**Comment by miemieYaho** [comment]
开局一张图，内容全靠编？
