### ISSUE TITLE
[功能改进]: FieldStrategy.IGNORED 在插入或更新时忽略该字段

### ISSUE THREAD

**Issue by vritser** [baomidou/mybatis-plus#6363]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

FieldStrategy.IGNORED 被标记为了废弃，但其实际语义没有得到应用；
```java

public class BaseEntity {
    private Boolean isDeleted;
    private LocalDateTime createdAt = LocalDateTime.now();
    private LocalDateTime updatedAt = LocalDateTime.now();
}
```
在更新操作时，createdAt 字段因为有默认值，会被意外更新掉，现需 IGNORED 策略能实现其`忽略`的语义

### 参考资料

#5129

**Comment by miemieYaho** [comment]
never
