### ISSUE TITLE
[错误报告]: application.properties配置mybatis-plus.global-config.db-config.logic-delete-value=1等配置项，后面含有特殊字符如#时，生成的preparedStatement语句也含有#，有sql注入风险

### ISSUE THREAD

**Issue by ys2017rhein** [baomidou/mybatis-plus#6365]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

v3.5.7

### 问题描述

application.properties配置mybatis-plus.global-config.db-config.logic-delete-value=1等配置项含有特殊字符如#时，preparedStatement语句也含有#，有sql注入风险。建议配置项都校验一下特殊字符。springboot版本：3.3.1

**Comment by miemieYaho** [comment]
?,你自己系统启动配置也乱来?

**Comment by ys2017rhein** [comment]
> ?,你自己系统启动配置也乱来?

极限操作，正常正常

**Comment by miemieYaho** [comment]
不会检查
