### ISSUE TITLE
使用达梦数据库频繁出现查询的实体类结果与实际返回的结果不匹配

### ISSUE THREAD

**Issue by wangwei618** [baomidou/mybatis-plus#6369]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.3.0

### 问题描述

之前用Oracle数据库，从来没出现过这种问题
把数据库换成达梦数据库之后，查询就会频繁出现实体类结果和实际的结果不匹配（就是我明明是查询的A表，但是实际执行的sql是查询的B表，间隙性的出现这种情况）
而且不是一个接口出现这样的情况，只要使用了查询的地方都会出现这种情况
![1](https://github.com/user-attachments/assets/0d06ed04-b6a2-4262-9bea-2f417348e6b9)
![3](https://github.com/user-attachments/assets/e8d97263-7c6e-444d-89d5-c4fa50035d9e)
![2](https://github.com/user-attachments/assets/d4327f31-fc88-484b-993f-28110216ba84)

**Comment by miemieYaho** [comment]
以最新版给出复现demo
