### ISSUE TITLE
[功能改进]: TenantLineInnerInterceptor类里有一处代码需优化

### ISSUE THREAD

**Issue by re-resolve** [baomidou/mybatis-plus#6370]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

多租户插件TenantLineInnerInterceptor的源码有个很明显的问题：
代码分支：release v3.5.7
所处类：/src/main/java/com/baomidou/mybatisplus/extension/plugins/inner/TenantLineInnerInterceptor.java
```java
// fixed gitee pulls/141 duplicate update
List<UpdateSet> duplicateUpdateColumns = insert.getDuplicateUpdateSets();
  if (CollectionUtils.isNotEmpty(duplicateUpdateColumns)) {
      EqualsTo equalsTo = new EqualsTo();
      equalsTo.setLeftExpression(new StringValue(tenantIdColumn));
      equalsTo.setRightExpression(tenantId);
      // 上面的equalsTo没被使用到
      duplicateUpdateColumns.add(new UpdateSet(new Column(tenantIdColumn), tenantId));
}
```
上面这里是否需要优化代码并测试？

**Comment by nieqiurong** [comment]
https://github.com/baomidou/mybatis-plus/blob/67f7ab7760a07f429e1c7d0c22282deb9fad9b19/mybatis-plus-extension/src/test/java/com/baomidou/mybatisplus/test/extension/plugins/inner/TenantLineInnerInterceptorTest.java#L462
