### ISSUE TITLE
[错误报告]: 查询条件使用in(R column, Object... values) 时传入基础数据类型出现逻辑错误

### ISSUE THREAD

**Issue by shu-cloud** [baomidou/mybatis-plus#6372]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

![image](https://github.com/user-attachments/assets/ae99afdf-09ff-4072-9e20-1f4419829c9b)
查询条件使用in(R column, Object... values) 时传入基础数据类型时,没有报错提示，paramTypes传入1，实际查出来的记录paramType为0，出现逻辑错误，values没有类型限制，比较容易出现此类问题
![image](https://github.com/user-attachments/assets/192943d6-e133-4e96-bc10-1261cc50c64b)

**Comment by miemieYaho** [comment]
打开你对应mapper的debug日志看mybatis打印的sql执行日志你就知道了
