### ISSUE TITLE
[多租户]: 定时任务执行表查询无租户id情况下

### ISSUE THREAD

**Issue by 501956430** [baomidou/mybatis-plus#6373]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.6

### 问题描述

在spring 定时器执行查询的场景中，由于不存在租户的上下文，会导致出现获取租户id null 情况。
1、可以对Threadlocal设置租户上下文，但是并不符合实际需要。
2、定时任务执行的本身，是不明确租户的上下文的，除了将定时任务脱离当前租户架构，独立一个模块 可以规避这个问题
3、在mybatisplus的架构体系中是否有可以存在这种场景的解决方案， 如 在定时器场景中时 不执行租户id拦截。

**Comment by huayanYu** [comment]
自己业务自己处理判断租户是否存在
