### ISSUE TITLE
3.5.6版本以上InExpression为什么摒弃了itemsList，导致 IN 的时候没括号，可以怎么解决

### ISSUE THREAD

**Issue by yexingzi** [baomidou/mybatis-plus#6376]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

InExpression我希望带有括号

### 参考资料

3.5.6之前版本
![微信图片_20240807084843](https://github.com/user-attachments/assets/4b642700-efe3-498b-a097-3e7b4c577cd5)
3.5.6版本及以上
![微信图片_20240807084850](https://github.com/user-attachments/assets/27bd4e7f-c613-480b-8972-1a09f5553358)

**Comment by miemieYaho** [comment]
怎么用的，什么地方说清楚

**Comment by yexingzi** [comment]
依照多租户插件，动态处理sql。我们有个数据权限动态处理sql，按照多租户的源码copy下来，但是会存在In的情况，这样就导致了问题

**Comment by miemieYaho** [comment]
你自己写的代码你自己负责啊,而且这是jsqlparser的东西

**Comment by JavaerLQ** [comment]
今天刚好遇到了这个问题，加上new Parenthesis()包一层就有括号了

**Comment by yexingzi** [comment]
> 今天刚好遇到了这个问题，加上new Parenthesis()包一层就有括号了

好的，我试试
