### ISSUE TITLE
[错误报告]: 数据变更记录插件BUG

### ISSUE THREAD

**Issue by xcore-fun** [baomidou/mybatis-plus#6377]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

DataChangeRecorderInnerInterceptor的getUpdatedColumnDatas方法的第352行有问题，这里没有判断propertyNameTrim跟columnName是否一致就直接修改了columnName的值导致数据错位造成异常

**Comment by xcore-fun** [comment]
例如：
<update id="updateLoginResult">
        update sys_users
        <set>
            <if test="isSuccess">
                error_number = 0, locked_end_at = null, last_login_at = now()
            </if>
            <if test="!isSuccess">
                error_number = error_number + case when locked_end_at is null then 1 else 0 end,
                locked_end_at =
                case when locked_end_at is null then
                case when error_number = 4 then now() + interval '10' minute else null end
                else locked_end_at end
            </if>
        </set>
        where username = #{username}
    </update>
error_number读取到的是字符串的0导致转换错误
conversion to class java.lang.String from int4 not supported

**Comment by nieqiurong** [comment]
#6430
