### ISSUE TITLE
[功能改进]: 是否可以增加逻辑删除开关

### ISSUE THREAD

**Issue by minliuhua** [baomidou/mybatis-plus#6383]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

有时候想全局切换逻辑删除是否删除

**Comment by miemieYaho** [comment]
没有
