### ISSUE TITLE
使用分页插件时，用$来做动态查询后台提示warn

### ISSUE THREAD

**Issue by guolei123321** [baomidou/mybatis-plus#6384]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.4.0

### 问题描述

使用分页插件时，用$来做动态排序后台提示warn
![WechatIMG798](https://github.com/user-attachments/assets/1894ac90-9455-43d8-9d27-51b3328e08ad)

**Comment by guolei123321** [comment]
有什么办法可以避免嘛
![Uploading WechatIMG801.jpg…]()

**Comment by miemieYaho** [comment]
和$无关，jsqlparser无法解析，日志都告诉你了
