### ISSUE TITLE
生成实体类的时id无法生成

### ISSUE THREAD

**Issue by 757957414** [baomidou/mybatis-plus#639]
### 当前使用版本(必须填写清楚，否则不予处理)
版本： 3.0.6
mysql版本：8.0.13

### 该问题是怎么引起的？**
使用官网给的事例进行生成发现实体类没有 id 主键( mapper 文件有 id)
主键是自增的 名称就叫 id 
主键生成策略是使用 IdType.AUTO
数据库链接地址：jdbc:mysql://localhost:3306/lm?characterEncoding=utf-8
表：
![image](https://user-images.githubusercontent.com/23210825/48697649-0c0bab00-ec20-11e8-9169-6afea74ba01b.png)
使用的是freemarker 模板
### 重现步骤
正常导包生成就是这样

### 报错信息
无

我发现如果不使用 id 这个名称就不会出现这个情况比如使用 uuid 这个名称就可以生成

**Comment by miemieYaho** [comment]
mp 默认字段名为 `id` 的字段视为 主键,不需要额外注解

**Comment by 757957414** [comment]
这样我怎么拿id呢

> mp默认字段名为`id`的字段视为主键，不需要额外注解

那这样我如何使用id呢

**Comment by 757957414** [comment]
问题是实体类没有帮我生成 id 这个字段，那我查询的时候怎么得到id？自己写一个id字段么？

**Comment by 757957414** [comment]
是的这个是我没注意到，因为没有那两个父类，而设置里面将id设置为父类的字段所以没生成

**Comment by jw-star** [comment]
好坑啊，注释掉就可以了 
// 写于父类中的公共字段
        //strategy.setSuperEntityColumns("id");
