### ISSUE TITLE
[功能改进]: savebatch是否可以改成      INSERT INTO xxx(aa, bb, cc)  VALUES(..)

### ISSUE THREAD

**Issue by objectboy2016** [baomidou/mybatis-plus#6390]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

rewriteBatchedStatements=true已配置
目前savebatch生成的是单条insert , 是否可以修改为INSERT INTO xxx(aa, bb, cc)  VALUES(..)方式

**Comment by miemieYaho** [comment]
你说的有单独的注入件，看文档
