### ISSUE TITLE
 配合dynamic-datasource 并且使用从数据库加载数据源方式，map-underscore-to-camel-case失效

### ISSUE THREAD

**Issue by Melodykuang** [baomidou/mybatis-plus#6393]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

 配合dynamic-datasource 并且使用从数据库加载数据源方式，map-underscore-to-camel-case失效

### 详细堆栈日志

```bash
//mybatis-plus返回map自动转驼峰配置
    @Bean
    public ConfigurationCustomizer mybatisConfigurationCustomizer() {
        return configuration -> configuration.setObjectWrapperFactory(new MybatisMapWrapperFactory());
    }  
这个代码没有走到

返回动态数据集合 List<Map<String, Object>>   字段转驼峰失败
```

**Comment by miemieYaho** [comment]
map转驼峰那是另外的,看文档

**Comment by Melodykuang** [comment]
> map转驼峰那是另外的,看文档

动态数据源加上的话不会走那个转驼峰的逻辑

**Comment by miemieYaho** [comment]
和动态数据源啥关系
```java
@Bean
    public ConfigurationCustomizer mybatisConfigurationCustomizer() {
        return configuration -> configuration.setObjectWrapperFactory(new MybatisMapWrapperFactory());
    }  
```
你配置的没生效=没加载到你这配置,你把自动注入的搞成你自己配了那不肯定不生效嘛
