### ISSUE TITLE
[功能改进]: 描述 LambdaQueryWrapper 条件构造方法的condition和val计算问题 3.5.6 版本

### ISSUE THREAD

**Issue by dsanjun** [baomidou/mybatis-plus#6395]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

LambdaQueryWrapper 条件构造方法，最好是condition =false 时不要再执行val 的计算

### 参考资料

比如下面这个条件构造，当filter.getExportDate()=“”时会报错
query.eq(StringUtils.hasText(filter.getExportDate()), XixueExportDO::getCreateTime,
					LocalDateUtil.dbParse(filter.getExportDate()));
我不得不将代码调整成
	if (StringUtils.hasText(filter.getExportDate())) {
				query.eq(XixueExportDO::getCreateTime, LocalDateUtil.dbParse(filter.getExportDate()));
			}

**Comment by miemieYaho** [comment]
用.func(),计不计算那是java的事
