### ISSUE TITLE
[错误报告]: IService.updateById(bean)时，where子句生成错误

### ISSUE THREAD

**Issue by xieliangza** [baomidou/mybatis-plus#6399]
### 确认

- [ ] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.3.2

### 问题描述

如【详细堆栈日志】所示，该对象主键字段为【syskey】，长json字符串字段为【pageStyle】
**入参信息为：**
{
  "syskey": "YGYSXT",
  "pageStyle": "{\"position\":{\"elementType\":\"position\",\"label\":\"定位\",\"position\":\"\",\"options\":[{\"value\":\"relative\",\"label\":\"相对定位\"},{\"value\":\"absolute\",\"label\":\"绝对定位\"}]},\"width\":{\"elementType\":\"inputAndUnit\",\"label\":\"W\",\"width\":\"100\",\"unit\":\"%\",\"options\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]},\"height\":{\"elementType\":\"inputAndUnit\",\"label\":\"H\",\"height\":\"100\",\"unit\":\"%\",\"options\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]},\"left\":{\"elementType\":\"inputAndUnit\",\"label\":\"X\",\"left\":\"\",\"unit\":\"px\",\"options\":[{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"}]},\"top\":{\"elementType\":\"inputAndUnit\",\"label\":\"Y\",\"top\":\"\",\"unit\":\"px\",\"options\":[{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"}]},\"overflow\":{\"elementType\":\"select\",\"label\":\"溢出方式\",\"overflow\":\"auto\",\"options\":[{\"value\":\"\",\"label\":\"请选择\"},{\"value\":\"hidden\",\"label\":\"隐藏\"},{\"value\":\"scroll\",\"label\":\"滚动条\"},{\"value\":\"auto\",\"label\":\"自适应\"},{\"value\":\"visible\",\"label\":\"不处理\"},{\"value\":\"inherit\",\"label\":\"继承父元素值\"}],\"showPadding\":true},\"collapseList\":{\"elementType\":\"collapseList\",\"active\":[\"facade\",\"else\"],\"collapseItem\":[{\"id\":\"minMax\",\"collapseListTitle\":\"宽高最大最小值\",\"min-width\":{\"elementType\":\"inputAndUnit\",\"label\":\"最小宽度\",\"min-width\":\"\",\"unit\":\"%\",\"options\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]},\"min-height\":{\"elementType\":\"inputAndUnit\",\"label\":\"最小高度\",\"min-height\":\"\",\"unit\":\"px\",\"options\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]},\"max-width\":{\"elementType\":\"inputAndUnit\",\"label\":\"最大宽度\",\"max-width\":\"\",\"unit\":\"%\",\"options\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]},\"max-height\":{\"elementType\":\"inputAndUnit\",\"label\":\"最大高度\",\"max-height\":\"\",\"unit\":\"px\",\"options\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]}},{\"id\":\"facade\",\"collapseListTitle\":\"外观\",\"opacity\":{\"elementType\":\"inputAndUnit\",\"type\":\"slider\",\"label\":\"透明度\",\"opacity\":100,\"unit\":\"%\",\"min\":0,\"max\":100,\"showLine\":true},\"backgroundColorHidden\":{\"onlyNotShow\":true,\"backgroundColorHidden\":false},\"backgroundImageHidden\":{\"onlyNotShow\":true,\"backgroundImageHidden\":false},\"background-color\":{\"elementType\":\"backgroundColor\",\"label\":\"填充颜色\",\"background-color\":\"#ccc\"},\"background-image\":{\"elementType\":\"backgroundImage\",\"label\":\"填充图片\",\"background-image\":\"/statics/DESIGNER/2022/11/22/J3030082473263366144.jpg?t=1723511439639\",\"buttonText\":\"选择背景图片\",\"imgName\":\"\",\"background-repeat\":\"no-repeat\",\"options\":[{\"label\":\"不重复\",\"value\":\"no-repeat\"},{\"label\":\"重复照片\",\"value\":\"repeat\"},{\"label\":\"水平重复\",\"value\":\"repeat-x\"},{\"label\":\"垂直重复\",\"value\":\"repeat-y\"},{\"label\":\"填充\",\"value\":\"fill\"},{\"label\":\"适应\",\"value\":\"adapt\"}]},\"border\":{\"elementType\":\"border\",\"label\":\"边框\",\"border-color\":\"#fff\",\"border-style\":\"solid\",\"leftValue\":\"3\",\"topValue\":\"3\",\"rightValue\":\"3\",\"bottomValue\":\"3\",\"leftUnit\":\"px\",\"topUnit\":\"px\",\"rightUnit\":\"px\",\"bottomUnit\":\"px\",\"labelList\":[\"左侧\",\"顶侧\",\"右侧\",\"底侧\"],\"unitList\":[{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"%\",\"label\":\"%\"}],\"options\":[{\"value\":\"solid\",\"label\":\"实线\"},{\"value\":\"dashed\",\"label\":\"虚线\"},{\"value\":\"dotted\",\"label\":\"点状边框\"},{\"value\":\"double\",\"label\":\"双线\"}],\"showLine\":true},\"border-radius\":{\"elementType\":\"quadruplet\",\"type\":\"borderRadius\",\"label\":\"圆角\",\"leftValue\":\"8\",\"topValue\":\"8\",\"rightValue\":\"8\",\"bottomValue\":\"8\",\"leftUnit\":\"px\",\"topUnit\":\"px\",\"rightUnit\":\"px\",\"bottomUnit\":\"px\",\"labelList\":[\"左下\",\"左上\",\"右上\",\"右下\"],\"unitList\":[{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"%\",\"label\":\"%\"}]}},{\"id\":\"else\",\"collapseListTitle\":\"其他\",\"padding\":{\"elementType\":\"quadruplet\",\"type\":\"padding\",\"label\":\"内边距\",\"leftValue\":\"5\",\"topValue\":\"5\",\"rightValue\":\"5\",\"bottomValue\":\"5\",\"leftUnit\":\"px\",\"topUnit\":\"px\",\"rightUnit\":\"px\",\"bottomUnit\":\"px\",\"labelList\":[\"左侧\",\"顶侧\",\"右侧\",\"底侧\"],\"unitList\":[{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"%\",\"label\":\"%\"}]},\"margin\":{\"elementType\":\"quadruplet\",\"type\":\"margin\",\"label\":\"外边距\",\"leftValue\":\"10\",\"topValue\":\"10\",\"rightValue\":\"10\",\"bottomValue\":\"10\",\"leftUnit\":\"px\",\"topUnit\":\"px\",\"rightUnit\":\"px\",\"bottomUnit\":\"px\",\"labelList\":[\"左侧\",\"顶侧\",\"右侧\",\"底侧\"],\"unitList\":[{\"value\":\"\",\"label\":\"无\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"%\",\"label\":\"%\"}]},\"labelWidth\":{\"elementType\":\"inputAndUnit\",\"label\":\"标签宽度\",\"type\":\"default\",\"labelWidth\":\"150\",\"className\":\"css-big-label\",\"unit\":\"px\",\"options\":[{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"},{\"value\":\"vw\",\"label\":\"vw\"},{\"value\":\"vh\",\"label\":\"vh\"}]},\"labelBackgroundColor\":{\"elementType\":\"color\",\"label\":\"标签背景颜色\",\"labelBackgroundColor\":\"rgba(240, 15, 15, 1)\"},\"labelColor\":{\"elementType\":\"color\",\"label\":\"标签字体颜色\",\"labelColor\":\"#fff\"},\"labelBorderColor\":{\"elementType\":\"color\",\"label\":\"表格边框颜色\",\"labelBorderColor\":\"rgba(7, 220, 131, 1)\"}}]},\"right\":{\"elementType\":\"inputAndUnit\",\"label\":\"右侧\",\"right\":\"\",\"unit\":\"px\",\"hidden\":true,\"options\":[{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"}]},\"bottom\":{\"elementType\":\"inputAndUnit\",\"label\":\"底侧\",\"bottom\":\"\",\"unit\":\"px\",\"hidden\":true,\"options\":[{\"value\":\"%\",\"label\":\"%\"},{\"value\":\"px\",\"label\":\"px\"},{\"value\":\"rem\",\"label\":\"rem\"}]},\"z-index\":{\"elementType\":\"input\",\"label\":\"页面层级高\",\"onlyNotShow\":true,\"z-index\":0,\"showLine\":true}}"
}

### 详细堆栈日志

```bash
生成的sql语句为：

UPDATE T_SYSTEM_DEFINE SET PAGE_STYLE={"position":{"elementType":"position","label":"定位","position":"","options":[{"value":"relative","label":"相对定位"},{"value":"absolute","label":"绝对定位"}]},"width":{"elementType":"inputAndUnit","label":"W","width":"100","unit":"%","options":[{"value":"","label":"无"},{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]},"height":{"elementType":"inputAndUnit","label":"H","height":"100","unit":"%","options":[{"value":"","label":"无"},{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]},"left":{"elementType":"inputAndUnit","label":"X","left":"","unit":"px","options":[{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"}]},"top":{"elementType":"inputAndUnit","label":"Y","top":"","unit":"px","options":[{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"}]},"overflow":{"elementType":"select","label":"溢出方式","overflow":"auto","options":[{"value":"","label":"请选择"},{"value":"hidden","label":"隐藏"},{"value":"scroll","label":"滚动条"},{"value":"auto","label":"自适应"},{"value":"visible","label":"不处理"},{"value":"inherit","label":"继承父元素值"}],"showPadding":true},"collapseList":{"elementType":"collapseList","active":["facade","else"],"collapseItem":[{"id":"minMax","collapseListTitle":"宽高最大最小值","min-width":{"elementType":"inputAndUnit","label":"最小宽度","min-width":"","unit":"%","options":[{"value":"","label":"无"},{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]},"min-height":{"elementType":"inputAndUnit","label":"最小高度","min-height":"","unit":"px","options":[{"value":"","label":"无"},{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]},"max-width":{"elementType":"inputAndUnit","label":"最大宽度","max-width":"","unit":"%","options":[{"value":"","label":"无"},{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]},"max-height":{"elementType":"inputAndUnit","label":"最大高度","max-height":"","unit":"px","options":[{"value":"","label":"无"},{"value":"%","label":"%"},{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]}},{"id":"facade","collapseListTitle":"外观","opacity":{"elementType":"inputAndUnit","type":"slider","label":"透明度","opacity":100,"unit":"%","min":0,"max":100,"showLine":true},"backgroundColorHidden":{"onlyNotShow":true,"backgroundColorHidden":false},"backgroundImageHidden":{"onlyNotShow":true,"backgroundImageHidden":false},"background-color":{"elementType":"backgroundColor","label":"填充颜色","background-color":"#ccc"},"background-image":{"elementType":"backgroundImage","label":"填充图片","background-image":"/statics/DESIGNER/2022/11/22/J3030082473263366144.jpg15t=1723511439639","buttonText":"选择背景图片","imgName":"","background-repeat":"no-repeat","options":[{"label":"不重复","value":"no-repeat"},{"label":"重复照片","value":"repeat"},{"label":"水平重复","value":"repeat-x"},{"label":"垂直重复","value":"repeat-y"},{"label":"填充","value":"fill"},{"label":"适应","value":"adapt"}]},"border":{"elementType":"border","label":"边框","border-color":"#fff","border-style":"solid","leftValue":"3","topValue":"3","rightValue":"3","bottomValue":"3","leftUnit":"px","topUnit":"px","rightUnit":"px","bottomUnit":"px","labelList":["左侧","顶侧","右侧","底侧"],"unitList":[{"value":"px","label":"px"},{"value":"%","label":"%"}],"options":[{"value":"solid","label":"实线"},{"value":"dashed","label":"虚线"},{"value":"dotted","label":"点状边框"},{"value":"double","label":"双线"}],"showLine":true},"border-radius":{"elementType":"quadruplet","type":"borderRadius","label":"圆角","leftValue":"8","topValue":"8","rightValue":"8","bottomValue":"8","leftUnit":"px","topUnit":"px","rightUnit":"px","bottomUnit":"px","labelList":["左下","左上","右上","右下"],"unitList":[{"value":"px","label":"px"},{"value":"%","label":"%"}]}},{"id":"else","collapseListTitle":"其他","padding":{"elementType":"quadruplet","type":"padding","label":"内边距","leftValue":"5","topValue":"5","rightValue":"5","bottomValue":"5","leftUnit":"px","topUnit":"px","rightUnit":"px","bottomUnit":"px","labelList":["左侧","顶侧","右侧","底侧"],"unitList":[{"value":"px","label":"px"},{"value":"%","label":"%"}]},"margin":{"elementType":"quadruplet","type":"margin","label":"外边距","leftValue":"10","topValue":"10","rightValue":"10","bottomValue":"10","leftUnit":"px","topUnit":"px","rightUnit":"px","bottomUnit":"px","labelList":["左侧","顶侧","右侧","底侧"],"unitList":[{"value":"","label":"无"},{"value":"px","label":"px"},{"value":"%","label":"%"}]},"labelWidth":{"elementType":"inputAndUnit","label":"标签宽度","type":"default","labelWidth":"150","className":"css-big-label","unit":"px","options":[{"value":"px","label":"px"},{"value":"rem","label":"rem"},{"value":"vw","label":"vw"},{"value":"vh","label":"vh"}]},"labelBackgroundColor":{"elementType":"color","label":"标签背景颜色","labelBackgroundColor":"rgba WHERE SYSKEY=15
```

**Comment by xieliangza** [comment]
/**
     * 系统关键值
     */
    @TableId(value = "SYSKEY", type = IdType.NONE)
    private String syskey;

    /**
     * 页面样式
     */
    @TableField(value = "PAGE_STYLE")
    private String pageStyle;

**Comment by miemieYaho** [comment]
自行解决

**Comment by xieliangza** [comment]
我知道可以将字符串编码为其他可以解决，但这种json格式的怎么会影响到where子句的生成，这难道不值得去处理么

**Comment by miemieYaho** [comment]
什么叫影响,你哪cv出来的执行sql?生成出来的sql只可能是`update xxx set ee=?,bb=? where id=?`并使用jdbc的PreparedStatement去执行,干活的都是mybatis和jdbc,我们处理什么?

**Comment by xieliangza** [comment]
醒悟过来了，应该是那个sql日志有问题，而不是框架保存有问题
