### ISSUE TITLE
[功能改进]: mapper.xml 或 @Select注解中怎么支持  db-config.shcema

### ISSUE THREAD

**Issue by Kumilo** [baomidou/mybatis-plus#6402]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

期望或者请求解答，怎么才能在mapper.xml 或@Select 注解中的手写原生sql 中支持  
mybatis-plus.global-config.db-config.schema

**Comment by miemieYaho** [comment]
你自己写个全局常量+表名

**Comment by Kumilo** [comment]
通过全局变量实现
mybatis-plus.configuration.variables
