### ISSUE TITLE
[错误报告]: 使用mybatisbatch对象报错，springboot3.0.6，mybatisplus3.5.7

### ISSUE THREAD

**Issue by Xintiao1** [baomidou/mybatis-plus#6403]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

Servlet.service() for servlet [dispatcherServlet] in context with path [/mwapi/flowableService/v1] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/core/batch/MybatisBatch] with root cause

无法找到路径

**Comment by miemieYaho** [comment]
检查依赖冲突
