### ISSUE TITLE
多数据源，HikariCP连接池，如何自定义控制SQL执行时间

### ISSUE THREAD

**Issue by Caesar2816** [baomidou/mybatis-plus#6404]
### 确认

- [x] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [x] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

mybatis-plus 3.2.0   HikariCP 2.7.9

### 问题描述

springboot 2.1.3  mybatis-plus 3.2.0  HikariCP 2.7.9 多数据源，无法自定义SQL执行时间
现象：大SQL执行时间过长，未主动断开，导致连接不够用
配置项：
spring.datasource.dynamic.datasource.master.hikari.is-auto-commit=true
spring.datasource.dynamic.datasource.master.hikari.connection-timeout=10000
spring.datasource.dynamic.datasource.master.hikari.validation-timeout=10000
已配置hikariCP连接超时时长，但是不生效；自定义时间为10s，但是执行超过10s后还是会接着执行
期望：可以全局控制服务中所有SQL执行时间，并可以自定义个别SQL的执行时间

**Comment by miemieYaho** [comment]
百度去

**Comment by Caesar2816** [comment]
mybatis-plus.configuration.default-statement-timeout=30
spring.datasource.dynamic.datasource.master.hikari.connection-timeout=30000
spring.datasource.dynamic.datasource.master.hikari.validation-timeout=30000
这几个关于超时的配置 加上后都不生效 无法控制SQL的熔断时间
想让他在执行30s的时候 就主动断开连接
