### ISSUE TITLE
[错误报告]: 字段类型为JSONObject无法映射

### ISSUE THREAD

**Issue by ChiMuYuan** [baomidou/mybatis-plus#6405]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

<mybatis-plus-spring-boot3-starter.version>3.5.7</mybatis-plus-spring-boot3-starter.version>

### 问题描述

字段类型为JSONObject时，结果为null

@TableField(value = "data", typeHandler = FastjsonTypeHandler.class)
private JSONObject data;

<fastjson.version>1.2.83</fastjson.version>

**Comment by miemieYaho** [comment]
看文档表名注解里配置项

**Comment by ChiMuYuan** [comment]
OK，没注意，不好意思

@TableName(autoResultMap = true)
