### ISSUE TITLE
[功能改进]: 希望增加日志打印SQL的功能

### ISSUE THREAD

**Issue by zhdgzs** [baomidou/mybatis-plus#6408]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

希望增加日志打印SQL的功能，只打印SQL，而不打印返回的数据。
并且现在日志里的SQL，并不能直接运行，希望可以打印成可以执行的SQL

**Comment by miemieYaho** [comment]
看文档

**Comment by zhdgzs** [comment]
文档里只找到了p6spy的方案，使用这个还需要额外引入，并且要修改driver和url。
类似 mybatis-flex 原生支持的并没有找到

**Comment by miemieYaho** [comment]
那没有

**Comment by zhdgzs** [comment]
有没有考虑在之后的版本中增加这个功能呢？可以把此 issues 开启

**Comment by miemieYaho** [comment]
没有
