### ISSUE TITLE
MybatisSqlSessionTemplate移除问题

### ISSUE THREAD

**Issue by yangye0626** [baomidou/mybatis-plus#641]
### 当前使用版本(必须填写清楚，否则不予处理)
版本为V3.0.6

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
更新V3.0.6之后启动加载bean文件，发现没有MybatisSqlSessionTemplate，
之前使用mybatis配置习惯一直沿用，由于MP完全兼容mybatis，所以配置习惯没有变动引入MP的jra包使用即可，当加载sqlsession使用有些报错。

### 重现步骤

目前按着mybatis配置方式习惯会有报错 配置如下：

	<bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
		<property name="dataSource" ref="dataSource" />
		<property name="configLocation" value="classpath:context/mybatis-config.xml" />
		<property name="mapperLocations">
			<array>
				<value>classpath*:sql/**/**/*.xml</value>
			</array>
		</property>
		<property name="plugins">
            <array>
                <bean id="paginationInterceptor" class="com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor">
                    <property name="dialectType" value="MariaDB" />
                </bean>
                <bean id="performanceInterceptor" class="com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor" >
                    <property name="maxTime" value="100" />
                    <property name="format"  value="true" /> 
                </bean>
            </array>
        </property>
		
	</bean>

	这里应该开始报错了
	<bean id="sqlSessionTemplate" class="com.baomidou.mybatisplus.extension.MybatisSqlSessionTemplate" destroy-method="clearCache">
		<constructor-arg index="0" ref="sqlSessionFactory" />
	</bean>

### 报错信息
Cannot find class [com.baomidou.mybatisplus.extension.MybatisSqlSessionTemplate] for bean with name 'sqlSessionTemplate'

**Comment by miemieYaho** [comment]
使用原来的SqlSessionTemplate试试

**Comment by Caratacus** [comment]
com.baomidou.mybatisplus.extension.MybatisSqlSessionTemplate已经没有被使用了，现在直接使用SqlSessionTemplate即可
