### ISSUE TITLE
[错误报告]: Wrappers.<>lambdaUpdate()更新字段为null的值不成功，还是只更新了不为null 的字段

### ISSUE THREAD

**Issue by RyanCheng08** [baomidou/mybatis-plus#6427]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.4.1

### 问题描述

![image](https://github.com/user-attachments/assets/36fe7728-d04c-4169-88ad-447f73b71e86)

这是我的代码，在对象里面存在了值为null的字段，但是用Wrappers.<>lambdaUpdate()和update更新还是只更新了不为null 的字段

**Comment by miemieYaho** [comment]
.set（xx，null）

**Comment by RyanCheng08** [comment]
> .set（xx，null）

一定要显式的把null字段set出来是吧
