### ISSUE TITLE
请问3.0.6版本热加载如何使用，MybatisMapperRefresh这个类已经被删掉了

### ISSUE THREAD

**Issue by Janrin** [baomidou/mybatis-plus#643]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

**Comment by miemieYaho** [comment]
已经移除了该鸡肋功能

**Comment by isghost** [comment]
关键会导致 Jrebel 的热加载失效

**Comment by isghost** [comment]
有什么替代方案吗？
我们这项目启动一次需要十分钟

**Comment by miemieYaho** [comment]
从3.0.5上cv下来,手动new出来保持应用开启时不会被回收就行了

**Comment by qmdx** [comment]
使用 Jrebel 啊

**Comment by isghost** [comment]
> 使用 Jrebel 啊

有办法使Jrebel的热加载重新生效吗

**Comment by miemieYaho** [comment]
使用 `3.0.7.2-SNAPSHOT` 快照版本,该类移回来了

**Comment by geekscloud** [comment]
> 使用`3.0.7.2-SNAPSHOT`快照版本，该类移回来了

JRebel 也失效了,怎么办

**Comment by StarzoneCN** [comment]
为何会草率地移除功能呐？不做兼容吗？这样以后都不敢升级版本啊

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`

**Comment by SweetInk** [comment]
> > 使用`3.0.7.2-SNAPSHOT`快照版本，该类移回来了
> 
> JRebel 也失效了,怎么办

搞了个插件Jrebel的插件，了解下[Jrebel-mybatisplus](https://github.com/SweetInk/jrebel-mybatisplus)

**Comment by qmdx** [comment]
@SweetInk  厉害了，有兴趣加入 baomidou 把你的 qq 发邮箱至 jobob@qq.com
