### ISSUE TITLE
@InterceptorIgnore生效范围

### ISSUE THREAD

**Issue by wzkris** [baomidou/mybatis-plus#6431]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

`@InterceptorIgnore(tenantLine = "true")`
<h4>这个注解放在Mapper层有效，放在Controller层就无效，我想忽略某个Controller下的所有接口该如何操作？</h4>

**Comment by miemieYaho** [comment]
没有

**Comment by wzkris** [comment]
> 没有

牛
