### ISSUE TITLE
[功能改进]: 描述 代码自动生成工具 创建的entity对象里面 是否可以增加字段名称的静态变量

### ISSUE THREAD

**Issue by yeohx** [baomidou/mybatis-plus#6434]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

目前生产的entity如下:
public class Role implements Serializable {
    private static final long serialVersionUID = 1L;
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
}
是否可以在这个里面增加一个静态变量说明表字段名称例如:
public static String ID = "id";
因为在使用 wepper 构造查询条件的时候需要指定表的字段名称.如果有一个静态变量就可以在封装wepper的时候直接使用了.
例如:
QueryWrapper<Role> queryWrapper = new QueryWrapper<>();
        queryWrapper.eq("id","123"); 这个改成 queryWrapper.eq(Role.ID,"123"); 
        List<Role> roles = roleMapper.selectList(queryWrapper);

**Comment by nieqiurong** [comment]
https://baomidou.com/reference/new-code-generator-configuration/#entity-%E7%AD%96%E7%95%A5%E9%85%8D%E7%BD%AE  enableColumnConstant
