### ISSUE TITLE
[错误报告]: 描述 json list字段反序列化泛型型问题

### ISSUE THREAD

**Issue by pengliang0601** [baomidou/mybatis-plus#6445]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

最新版本

### 问题描述

![image](https://github.com/user-attachments/assets/27ebe989-41de-41dc-8673-29e2e784e388)
![image](https://github.com/user-attachments/assets/169c2be4-1a8b-495e-8a31-e7a979b9f0e8)
字段定义的是long，序列化结果为int，我是用的是Fastjson2TypeHandler  看了代码，genericType字段可能要特殊处理下

**Comment by pengliang0601** [comment]
可能是通过resultMap 来的，resultMap生成的TypeHandler没有字段，无法获取到泛型

**Comment by miemieYaho** [comment]
不支持范型

**Comment by huayanYu** [comment]
你也可以根据需要自己重写Fastjson2TypeHandler

**Comment by pengliang0601** [comment]
> 你也可以根据需要自己重写Fastjson2TypeHandler

这个块mybatilsPush是否能够完善
