### ISSUE TITLE
[功能改进]: 描述pgsql jsonb字段 集合对象返回LinkedHashMap

### ISSUE THREAD

**Issue by newbirdking** [baomidou/mybatis-plus#6447]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

使用3.5.1版本.参照官网写的([https://baomidou.com/guides/type-handler/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B%E5%A4%84%E7%90%86%E5%99%A8])pgsql jsonb,单独的对象没有问题,但是用集合,则会变成LinkedHashMap
![Uploading image.png…]()

### 参考资料

https://baomidou.com/guides/type-handler/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B%E5%A4%84%E7%90%86%E5%99%A8

**Comment by newbirdking** [comment]
![1725252940104](https://github.com/user-attachments/assets/b9952341-807c-464b-a55b-fd2c4c2e3d6b)

**Comment by miemieYaho** [comment]
不支持泛型

**Comment by nieqiurong** [comment]
升级版本至3.5.6+支持泛型.

https://github.com/baomidou/mybatis-plus-samples/commit/402411842becceac4c5ad0532223c6b9fcb006f6

**Comment by jiangjihui** [comment]
我也遇到了这个问题，发现 3.4.3.1版本的mybatis-plus拿到的都是LinkedHashMap，使用 3.5.9 版本没有问题。感谢3.5.6+支持了泛型。
