### ISSUE TITLE
[功能改进]: 查询返回的实体是不是可以通过类注解直接忽略数据库不存在的字段

### ISSUE THREAD

**Issue by simonkingws** [baomidou/mybatis-plus#6449]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

开发中很多时候查询的实体中，不少字段是需要通过转化才在页面中展示。如图：
![image](https://github.com/user-attachments/assets/a68ef0f9-1ad9-450e-982a-a6bd044a0302)
![image](https://github.com/user-attachments/assets/a623943c-ce23-43e1-9a12-4013b09d8d03)
目前查询的实体只要不包含数据库字段就会报错，解决也只能通过字段注解@TableField(exist=false)来解决。

能不能通过一个类注解，全局忽略不存在的字段，来保证查询的结果直接使用扩展类接受。例如：
![image](https://github.com/user-attachments/assets/9faf033e-d974-463d-8431-a31d9033d370)

**Comment by nieqiurong** [comment]
@TableName#excludeProperty

**Comment by simonkingws** [comment]
这个方式也必须通过枚举每一个属性才可以【@TableName(value = "auction_plan",excludeProperty = {"test", "test02"})】，和@TableField(exist=false)使用起来的差不多，都需要修改数据库映射实体。

如果我的扩展类里面自定义了很多字段，又继承数据库映射字段，那么使用@TableName#excludeProperty就需要把我的扩展类的字段都要列举出来，这样处理有点硬编码。

能不能在不修改数据库映射实体情况下，通过一个单独的类注解，直接加在扩展类上。这样以来整个扩展类就可以随意自定义参数，而不影响返回结果。

**Comment by miemieYaho** [comment]
不能,本身就是用于entity与表对应的
