### ISSUE TITLE
QueryWrapper orderby 产生多余的and

### ISSUE THREAD

**Issue by suensun** [baomidou/mybatis-plus#645]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
QueryWrapper<X> qw = new QueryWrapper<X>();
qw.eq("name","1222").orderByDesc("name");
mapper.selectPage(page,qw);
以上方式会导致生成SQL语句：where name =? AND order by name desc 
多余的AND不法去除
### 报错信息

 ORA-00936: 缺失表达式

**Comment by miemieYaho** [comment]
没发现你说的问题,你最好确定一下你的mp 的版本号

**Comment by suensun** [comment]
> 没发现你说的问题,你最好确定一下你的mp 的版本号

经查，确实有一个工程引用的是3.0.5，换成3.0.6后确实异常问题消失。感谢解答！
