### ISSUE TITLE
[错误报告]: 3.5.2版本如何实现某个mybatis 方法忽略sql语法检查？

### ISSUE THREAD

**Issue by tiger822** [baomidou/mybatis-plus#6456]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.2

### 问题描述

由于有些数据库（如sqlserver)的语法奇特，mybatis plus的语法检查组件完全适应不了，所以希望某些mapper方法能通过注解的方式让其规避sql的语法检查，是否能实现？ 百度没找到答案。

比如在sql里面有 set @var1=#{var1}这种语法，语法检查就出异常。

### 详细堆栈日志

```bash
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: declare @mo varchar(20),@itemno varchar(20),@planReq integer
        set @mo=?
        set @itemno=?
        Set @planReq=(select isnull(sum(PlanReq),0) from ds_mo_mate where mo=@mo and  itemno=@itemno)
....
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "set" "SET"
    at line 2, column 9.

Was expecting one of:

    ","
    "."
    ";"
    "="
    "["
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31234)
```

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException 不能

**Comment by tiger822** [comment]
> net.sf.jsqlparser.parser.ParseException 不能

我知道，就是想问如何跳过这个检测

**Comment by miemieYaho** [comment]
只有插件里在用,去掉插件

**Comment by tiger822** [comment]
> 只有插件里在用,去掉插件

请问如何配置可以去掉？

**Comment by miemieYaho** [comment]
https://baomidou.com/plugins/#%E6%8B%A6%E6%88%AA%E5%BF%BD%E7%95%A5%E6%B3%A8%E8%A7%A3-interceptorignore
