### ISSUE TITLE
[功能改进]:  添加kotlin语言代码生成器

### ISSUE THREAD

**Issue by Baldur404** [baomidou/mybatis-plus#6457]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

建议添加koltin语言版本代码生成器，实体数据类使用kotlin的dataclass，以及java对于高版本jdk也可以生成dataclass

**Comment by qmdx** [comment]
你可以自定义模板啊，更多可以[查看视频](https://www.bilibili.com/video/BV1hq4y1d7tv/)
