### ISSUE TITLE
[错误报告]: entity如何加载接口属性字段？

### ISSUE THREAD

**Issue by diypyh** [baomidou/mybatis-plus#6459]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

由于业务设计原因，需要抽离公共字段为接口类型，但是无法加载接口属性字段，实现如下：

![image](https://github.com/user-attachments/assets/832beda4-8409-4a8b-9e45-3009bdd83d95)

但实际上并不有加载接口里的属性字段

**Comment by miemieYaho** [comment]
那玩意叫常量
