### ISSUE TITLE
[功能改进]: 解决分页插件必须指定单个参数@Param的思路

### ISSUE THREAD

**Issue by fujinjun** [baomidou/mybatis-plus#6461]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

方案：
1. 在PaginationInnerInterceptor.willDoQuery中第1行后添加：
```java
if (page == null && rowBounds instanceof IPage){
    page = (IPage<?>) rowBounds;
    rowBounds = new RowBounds();
}
```
2. 让Page继承自 RowBounds.
机制：
1. 由于Mybatis自身会忽略掉RowBounds,所以继承自RowBounds后，就不需要对另外1个参数写@Param了
2. 在执行前，将RowBounds转为page,相当于还原参数，符合Mybatis Plus的分页实现。

**Comment by miemieYaho** [comment]
page不只能分页也可携带xml需要的其他参数,你这样就不行了

**Comment by fujinjun** [comment]
@miemieYaho  其他参数也不影响吧，在使用前已经解包出来了啊 ，我主要是从以前版本升级遇到的问题
