### ISSUE TITLE
[错误报告]: 使用自定义PostInitTableInfoHandler报错

### ISSUE THREAD

**Issue by diypyh** [baomidou/mybatis-plus#6462]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

使用自定义的PostInitTableInfoHandler配置时，系统报错：

配置：
mybatis-plus.global-config.post-init-table-info-handler=cc.kuaida.common.config.KuaidaPostInitTableInfoHandler

报错：
Failed to bind properties under 'mybatis-plus.global-config.post-init-table-info-handler' to com.baomidou.mybatisplus.core.handlers.PostInitTableInfoHandler:

    Property: mybatis-plus.global-config.post-init-table-info-handler
    Value: "cc.kuaida.common.config.KuaidaPostInitTableInfoHandler.java"
    Origin: class path resource [application.properties] - 51:57
    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [com.baomidou.mybatisplus.core.handlers.PostInitTableInfoHandler]

没找到有这个配置的说明，请请如何实现？主要目的是想在扫描实体时，动态增加自定义属性

**Comment by miemieYaho** [comment]
bean注入不是yml配置
