### ISSUE TITLE
[错误报告]: 指定scanBasePackages对于@Mapper注解扫描不生效

### ISSUE THREAD

**Issue by luooyii** [baomidou/mybatis-plus#6463]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

指定包扫描基类，对于@Mapper注解扫描失效，扫描package依然基于启动类所在包。在debug模式下强行修改packages值，依然无法获取到mapper

提供最小复现实现
https://github.com/luooyii/package-scan-error

![image](https://github.com/user-attachments/assets/fb0b9d64-b71e-4736-8c60-70f8fe61bb01)

![image](https://github.com/user-attachments/assets/91f0ecd7-2cdf-44eb-9cc2-c67ad6de0c1b)

**Comment by luooyii** [comment]
关联问题 #5350 #5930

**Comment by miemieYaho** [comment]
![image](https://github.com/user-attachments/assets/335d00af-79aa-48ff-8a95-d46ae532b65d)
