### ISSUE TITLE
[错误报告]: 调用批量插入方法插入已成功返回false

### ISSUE THREAD

**Issue by fengshuwangheqiao** [baomidou/mybatis-plus#6464]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

调用
![1](https://github.com/user-attachments/assets/79107119-8a2b-4cbe-a40b-eb26a886fb24)
返回信息为false，3.5.6返回true,无任何报错信息，数据库已插入成功

**Comment by totoro52** [comment]
复现不出来，功能正常
![image](https://github.com/user-attachments/assets/b483cd09-bdeb-4c59-8435-1d937bc32bd5)



还有plus哪来的insertBatch方法
![image](https://github.com/user-attachments/assets/0c6b4aaf-ffbd-4d91-82af-60e9ab5e224c)

**Comment by fengshuwangheqiao** [comment]
看一下截图，调用的是 Db.saveBatch(entityList),  调用IService中的saveBatch返回是正常的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] [错误报告]: 调用批量插入方法插入已成功返回false (Issue #6464)





 
复现不出来，功能正常
 image.png (view on web)
 
还有plus哪来的insertBatch方法
 image.png (view on web)

**Comment by fengshuwangheqiao** [comment]
正常的调用ser





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] [错误报告]: 调用批量插入方法插入已成功返回false (Issue #6464)





 
复现不出来，功能正常
 image.png (view on web)
 
还有plus哪来的insertBatch方法
 image.png (view on web)

**Comment by totoro52** [comment]
复现不了，可以提供demo

**Comment by fengshuwangheqiao** [comment]
[demo.zip](https://github.com/user-attachments/files/16903261/demo.zip)

**Comment by totoro52** [comment]
确实是plus的bug，这里判断出了问题，JDBC给了SUCCESS_NO_INFO状态码，最新代码我看到了已经修了，先用旧版吧等更新吧
![image](https://github.com/user-attachments/assets/1cfb63ff-17d1-4066-a56e-dc397a9a6497)

**Comment by nieqiurong** [comment]
#6267
