### ISSUE TITLE
[功能改进]: wrapper.select(Class<T> entityClass, Predicate<TableFieldInfo> predicate) 无法排除主键

### ISSUE THREAD

**Issue by LouShangxiaolong** [baomidou/mybatis-plus#6465]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

写法如下：
`wrapper.select(OrderLog.class, a -> !a.getColumn().equals("id"))`
`v3.4.0` 版本下可以` select` 除了 主键 `id` 之外的所有字段，升级为 `v3.5.6` 后就无法排除主键失效了，会` select` 包含主键 `id` 以及所有字段。
查看官方文档中出现如下说明：
![image](https://github.com/user-attachments/assets/17bae95a-b71c-4738-9956-f26dea9393fc)
我想说的是出于什么考虑才把主键过滤排除在外的？以及从什么版本开始改为这种情况的？以及能否恢复过滤主键
因为我在 releases 页面查看了 `v3.4.0` -> `v3.5.6` 所有升级事项，没有找到相关改动的记录。

**Comment by miemieYaho** [comment]
一直都这样，主键不是TableFieldInfo

**Comment by LouShangxiaolong** [comment]
不是的，我可以很确定说的在 v3.4.0 版本是生效的







  	
 李小龙 
楼上(深圳)科技有限公司   	     
 ***@***.*** 
	   		 楼上(深圳)科技有限公司  	 企业主页  	      
 「GOOD GOOD STUDY! DAY DAY UP!」    
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
***@***.***>
日　期：2024年09月06日 18:58:52
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [baomidou/mybatis-plus] [功能改进]: wrapper.select(Class<T> entityClass, Predicate<TableFieldInfo> predicate) 无法排除主键 (Issue #6465)

一直都这样，主键不是TableFieldInfo

**Comment by miemieYaho** [comment]
![image](https://github.com/user-attachments/assets/aaf997cb-789a-413a-8fe4-2df07235eea8)
![image](https://github.com/user-attachments/assets/49bceb13-d425-48d5-afaa-f4b24fbead03)

**Comment by LouShangxiaolong** [comment]
🤔 下周我单独跑个3.4.0的demo重新试试







  	
 李小龙 
楼上(深圳)科技有限公司   	     
 ***@***.*** 
	   		 楼上(深圳)科技有限公司  	 企业主页  	      
 「GOOD GOOD STUDY! DAY DAY UP!」    
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
***@***.***>
日　期：2024年09月06日 19:07:55
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [baomidou/mybatis-plus] [功能改进]: wrapper.select(Class<T> entityClass, Predicate<TableFieldInfo> predicate) 无法排除主键 (Issue #6465)

image.png (view on web)

**Comment by LouShangxiaolong** [comment]
> ![image](https://private-user-images.githubusercontent.com/28334419/365141918-aaf997cb-789a-413a-8fe4-2df07235eea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDcyNzgsIm5iZiI6MTcyNTg0Njk3OCwicGF0aCI6Ii8yODMzNDQxOS8zNjUxNDE5MTgtYWFmOTk3Y2ItNzg5YS00MTNhLThmZTQtMmRmMDcyMzVlZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAxNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZmNjNzIxZjlkYzJjMDJiNTkzYzAwYmI2ZTU1MTdiOWUwYzA5M2YyYmY1ZjE4Yzc4NGEwZjc0YWU0Y2FkMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wvLkhKoDXTpBpUFE_DhKFVsCx-WfnuyPV3Cp_Ss0Kq0) ![image](https://private-user-images.githubusercontent.com/28334419/365142907-49bceb13-d425-48d5-afaa-f4b24fbead03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDcyNzgsIm5iZiI6MTcyNTg0Njk3OCwicGF0aCI6Ii8yODMzNDQxOS8zNjUxNDI5MDctNDliY2ViMTMtZDQyNS00OGQ1LWFmYWEtZjRiMjRmYmVhZDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAxNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MTk1ZTY5MTc2MmJiOGU5MDQzZWJkMGQ4YWYwNjQ1NTQ4OGViNzRjN2VjNDg4MmQ4NGMxYzU1ZDEyY2NmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxhWc8NFDtV9iLh-C8F5Wb8FvsB6X6B3R3DS-8ZEGLk)

哦，发现问了，不是`select`的问题。是`3.4.0` 以及之前的版本 在执行`saveBatch` 时会自动 忽略掉 自增主键，使用新的自增id。
![image](https://github.com/user-attachments/assets/28ebe449-64f7-41a2-aea3-8497839719ec)

切换到`3.5.6` 会把原来的 `id` 带上，导致了 id 重复。
![image](https://github.com/user-attachments/assets/e4ef1a1d-4d6e-4747-b95c-b0f635a26683)
但是具体时哪个版本开始改变的就没试了；

``` java
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("s_order_log")
public class OrderLog implements Serializable {
    private static final long serialVersionUID = 1L;
    /**
     * id
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;
    /**
     * 订单id
     */
    private String orderId;
    /**
     * 操作类型
     */
    private String operationType;
    /**
     * 操作备注
     */
    private String remark;
    /**
     * 主状态
     */
    private Integer hostStatus;
    /**
     * 子状态
     */
    private Integer childStatus;
    /**
     * 创建时间
     */
    private LocalDateTime createTime;
}
```

**Comment by miemieYaho** [comment]
![image](https://github.com/user-attachments/assets/7431d242-8800-4beb-89be-36ab182b10db)

**Comment by LouShangxiaolong** [comment]
> ![image](https://private-user-images.githubusercontent.com/28334419/365503416-7431d242-8800-4beb-89be-36ab182b10db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTI5NzcsIm5iZiI6MTcyNTg1MjY3NywicGF0aCI6Ii8yODMzNDQxOS8zNjU1MDM0MTYtNzQzMWQyNDItODgwMC00YmViLTg5YmUtMzZhYjE4MmIxMGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzMzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNzdkNmRiZGFjMGVmZTBmZWRlOWQ0MDQ1ODNiMzFhNmU5ZjE0YzU3ZDQ0Njg0OGEyZjM3NmEwZTFlZDE4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mp6MT8JAEpaetIBKqBe_VxCT3ThPeWmu37ihOfod9-4)

好的。感谢
