### ISSUE TITLE
[错误报告]: 描述升级mybatis-plus-boot-starter的版本3.3.2到3.5.7之后，报错com.baomidou.mybatisplus.extension.parsers不存在

### ISSUE THREAD

**Issue by Gulliver9527** [baomidou/mybatis-plus#6469]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

![1725692145712](https://github.com/user-attachments/assets/486a902e-9d67-441c-8a72-4bd4e45f85eb)

**Comment by miemieYaho** [comment]
没了
