### ISSUE TITLE
[功能改进]: 代码生成器支持TypeHandler

### ISSUE THREAD

**Issue by superxiao** [baomidou/mybatis-plus#6471]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

目前代码生成器(code generator)生成的[entity](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/resources/templates/entity.java.ftl)里无法设置field TypeHandler。支持的`@TableField`自定义仅包括`value`和`fill`。

**Comment by qmdx** [comment]
这个不太好支持 typeHandler 是未知的处理类型，出现频率也是很小的，你可以生成实体后自己加上
