### ISSUE TITLE
[错误报告]: 描述 乐观锁更新失败不会主动抛出异常

### ISSUE THREAD

**Issue by ErQi** [baomidou/mybatis-plus#6474]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

在 **ServiceImpl** 中使用 **updateById** 来进行更新数据.
在并发情况下会更新失败,返回值未 false,但是并未抛出异常.
详细日志如下图.

![image](https://github.com/user-attachments/assets/6ff21c6e-c31a-4256-a6f4-d36dd8e4aa9a)

**Comment by ErQi** [comment]
前面使用的3.5.4.1版本有这个问题,切换到3.5.7版本,问题依旧存在.
怀疑该问题连续存在多个版本.

**Comment by miemieYaho** [comment]
自行判断返回自己抛异常
