### ISSUE TITLE
版本号建议和boot保持同步

### ISSUE THREAD

**Issue by mpv945** [baomidou/mybatis-plus#648]
3.0.6

之前学习用的是spring boot 2.0，现在准备用spring boot 1.5，然后mp依赖的还是3.0.6,启动好多报错

希望把版本号和spring boot 改成一致，这样更新spring boot就不需要手动改mp的版本号了

**Comment by miemieYaho** [comment]
不可能一样的,如果 mybatis-plus-boot-start 依赖的 boot 版本不和你的要求,那就排除掉依赖再添加自己的依赖试试
