### ISSUE TITLE
[错误报告]: 人大金仓数据库，xml关联表查询时，不会拼接schema

### ISSUE THREAD

**Issue by LeeSmallNorth** [baomidou/mybatis-plus#6489]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.5

### 问题描述

SpringBoot : v2.3.7.RELEASE
Mybatis-Plus: v3.5.5
1; 配置文件已配置schema
![image](https://github.com/user-attachments/assets/79af33f2-3e9c-4b40-9c6e-0435cfbfa736)

2: 自定义的查询语句
![image](https://github.com/user-attachments/assets/df73d1e6-feb7-45cd-9afd-22285fff3af6)

3：错误原因：没有拼接schema

4：正确写法
![image](https://github.com/user-attachments/assets/5560538c-e2be-470a-80ba-21ec75ff21a9)

此issue可能会被定义成正常设计，个人觉得全局已经设置了schema，自定义的sql有没有办法拼接上，否则如何迁移至其它schema，所有的xml都将要被修改。

**Comment by miemieYaho** [comment]
自己写的sql不在规则之内
