### ISSUE TITLE
环境spring boot 使用PerformanceInterceptor 性能分析插件 获取不到statement

### ISSUE THREAD

**Issue by yipengjj** [baomidou/mybatis-plus#65]
springboot集成PerformanceInterceptor插件的时候 提示没有statement的getter方法

org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'statement' in 'class org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy'

**Comment by yipengjj** [comment]
springboot版本 1.5.3.RELEASE 
mybatisplus-springboot版本 1.0.1

**Comment by Caratacus** [comment]
连接池应该是tomcatjdbc,提供下数据库类型

**Comment by yipengjj** [comment]
mysql  5.7

**Comment by Caratacus** [comment]
尝试下新版本2.0.9这几天会发

**Comment by yipengjj** [comment]
使用最新版本还是有问题 springboot 2.1-gamma  mybatisplus-springboot 1.0.4

**Comment by yuxiaobin** [comment]
请把错误信息贴全

**Comment by qmdx** [comment]
@yipengjj  这里关掉，你有问题群里来说。

**Comment by hookszhang** [comment]
我也有同样的问题，现在如何解决了？

**Comment by hegphegp** [comment]
好像在yml配置文件添加spring.datasource.type=com.zaxxer.hikari.HikariDataSource就可以了
