### ISSUE TITLE
injectionConfig这个类自定义了map之后需要自己重写vm模板吗

### ISSUE THREAD

**Issue by zyb284629791** [baomidou/mybatis-plus#650]
### 当前使用版本 3.0.1
injectionConfig这个类自定义了map之后需要自己重写vm模板吗？
// 自定义配置
        InjectionConfig cfg = new InjectionConfig() {
            @Override
            public void initMap() {
                HashMap<String,Object> map = new HashMap<>();
                PackageConfig packageConfig = new PackageConfig();
                packageConfig.setModuleName(moduleName);
                map.put("package", packageConfig);
                this.setMap(map);
            }
        };
按照上面代码覆盖了这段配置，但是并没有起作用，在vm中也没有看到任何关于cfg.map的预留位置

**Comment by qmdx** [comment]
`cfg.xxx`  xxx 为 map  key

**Comment by zyb284629791** [comment]
@qmdx 不好意思，没太懂，是说要重写模版文件吗？

**Comment by qmdx** [comment]
是的自己修改

**Comment by zyb284629791** [comment]
好的，谢谢了！

**Comment by zyb284629791** [comment]
![image](https://user-images.githubusercontent.com/11675735/49079115-c3d13600-f27a-11e8-84b2-c758a7de56e8.png)
@qmdx 还有一个问题想咨询下，在processTable的时候，如果globalconfig定义了entityname，那么在处理的时候只能作用在entity上，其他的mapper、service等都没办法和entity保持一致。这个是就这样设计的？还是这里的逻辑待考虑？麻烦了！

**Comment by qmdx** [comment]
把你遇到问题，和期望的场景，描述清楚

**Comment by zyb284629791** [comment]
![image](https://user-images.githubusercontent.com/11675735/49137936-d144f980-f328-11e8-86ba-e4efcc7ed423.png)
@qmdx 是这样的，我在GlobalConfig中设置了entityName，但是生成的文件中只有entity生效了，其他文件的名称还是根据表名生成的，而我期望的结果是其他文件也是跟entity命名保持一致，即图中MidMissionMapper、MidMissionController等。通过跟代码发现是上图那里的逻辑处理的结果，就想问下这个地方除了在GlobalConfig中将MapperName，ServiceName等属性全部写死了还有没有什么别的方法能做到这一点？
