### ISSUE TITLE
[错误报告]: 实体类主键留空，会自动生成一个值，被插入到数据库的自增字段里

### ISSUE THREAD

**Issue by ECAMT35** [baomidou/mybatis-plus#6503]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.8

### 问题描述

数据库：MariaDB
问题：一张表的id字段配设置为主键自增，在springboot使用Mapper的insert或者Service的save插入一条数据时，创建一个实体类没给id属性设置一个值，经过save方法插入时会自动生成一个值
![屏幕截图_20240921_015805](https://github.com/user-attachments/assets/16018017-5a10-4423-8c7f-217a06eb81fb)

![屏幕截图_20240921_015551](https://github.com/user-attachments/assets/af6a6719-284e-4236-8333-9856b8cdc610)

` User user = new User();
  user.setUserName(signupDto.getUserName());
  user.setPassword(PasswordUtil.encrypt(signupDto.getPassword()));
  user.setEmail(signupDto.getEmail());
  userMapper.insert(user);`

**Comment by miemieYaho** [comment]
去看文档
