### ISSUE TITLE
[功能改进]: 描述 分页+合并数据的场景下，怎么让最后返回的分页数据和实际条数一致呢？

### ISSUE THREAD

**Issue by AugustTuan** [baomidou/mybatis-plus#6507]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

请教一个场景，
如果在分页查询数据以后，需要对查询的结果进行数据合并处理，再返回给前端。 
请这种分页以后过滤的场景，有办法让返回分页相关数据准确吗？
比如前端传递单页10条，分页查询合并以后只剩5条了。这样原来分页查询的总条数和当前页条数都不准了
可以通过mybaits-plus解决这个问题吗？

**Comment by miemieYaho** [comment]
没有

**Comment by qmdx** [comment]
物理分页以执行 SQL  为准，业务合并需要自己计算数量
