### ISSUE TITLE
[功能改进]: 支持通过querywrapper构造窗口函数吗？在官网教程里面没有找到示例

### ISSUE THREAD

**Issue by AugustTuan** [baomidou/mybatis-plus#6508]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

可以在querywarapper链式调用里面构造窗口函数吗？

**Comment by AugustTuan** [comment]
所以目前是不支持是吗

**Comment by huayanYu** [comment]
复杂的都建议自己写原始sql
