### ISSUE TITLE
使用EmptyWrapper 错误

### ISSUE THREAD

**Issue by li1191863273** [baomidou/mybatis-plus#651]
### 当前使用版本(必须填写清楚，否则不予处理)
	
	spring-boot-starter-parent	2.1.0.RELEASE
	mybatis-plus-boot-starter	3.0.6

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
      
	使用QueryWrapper的子类EmptyWrapper 错误

### 重现步骤
       
        User paramUser = new User();
        paramUser.setPassword("123456");

        QueryWrapper<User> wrapper = new EmptyWrapper<>();
        wrapper.setEntity(paramUser);

        List<User> userList = userService.list(wrapper);
        System.out.println(JSON.toJSONString(userList));

打印SQL

    SELECT
        id,
        username,
        password,
        deleted,
        feature,
        status,
        gmt_create,
        gmt_modified 
    FROM
        staging_user 
    WHERE
        deleted=0

查询结果错误

改为QueryWrapper正常

        User paramUser = new User();
        paramUser.setPassword("123456");

        QueryWrapper<User> wrapper = new QueryWrapper<>();
        wrapper.setEntity(paramUser);

        List<User> userList = userService.list(wrapper);
        System.out.println(JSON.toJSONString(userList));

打印SQL

    SELECT
        id,
        username,
        password,
        deleted,
        feature,
        status,
        gmt_create,
        gmt_modified 
    FROM
        staging_user 
    WHERE
        password='123456' 
        AND deleted=0

查询结果正常

**Comment by qmdx** [comment]
EmptyWrapper 是设计上的一个问题，后面版本对外屏蔽，不允许直接使用请使用 QueryWrapper

**Comment by li1191863273** [comment]
不使用QueryWrapper请问使用哪个？使用EmptyWrapper吗

**Comment by qmdx** [comment]
EmptyWrapper 是设计上的一个问题，后面版本对外屏蔽，不允许直接使用EmptyWrapper  。

请使用 QueryWrapper

@li1191863273 i 你可愁坏我了

**Comment by li1191863273** [comment]
哈哈哈
