### ISSUE TITLE
[功能改进]: 描述 @TableField中的update能否在insert中生效

### ISSUE THREAD

**Issue by 5433zzz** [baomidou/mybatis-plus#6510]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

现在 @TableField中的update只能在更新时生效，能否改成根据fill = FieldFill.INSERT 在新增数据时也有效果。 
现在的需求中，新增时需要有创建时间，修改数据时需要有自动更新时间。
    @TableField(value = "CREATED_TIME",fill = FieldFill.INSERT,update = "sysdate")
    @TableField(value = "UPDATED_TIME",fill = FieldFill.INSERT_UPDATE,update = "sysdate")

**Comment by chess3cake** [comment]
向你推荐我的做法，注册自定义的AnnotationHandler，这样就可以使用自定义的TableField注解了。
