### ISSUE TITLE
[功能改进]: 索引覆盖场景的分页查询

### ISSUE THREAD

**Issue by jhx1024** [baomidou/mybatis-plus#6522]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

当出现深度分页的情况，使用索引覆盖进行优化时，查询分页的limit参数是在子查询中，但是分页插件的limit是在最外层的SQL,这个时候如何管理分页，希望分页按照子查询中的

**Comment by wzkris** [comment]
子查询走分页，查出来之后用id去in一下

**Comment by qmdx** [comment]
分页插件的逻辑是固定的，你有优化需求可以 xml 自定义 limit 控制逻辑，不要走分页插件默认规则
