### ISSUE TITLE
[功能改进]:代码生成器，create中url参数未去除可能出现的空字符，例如{}jdbc:mysql:xxx 会报连接失败错误，{}表示为显示的空格

### ISSUE THREAD

**Issue by sansWl** [baomidou/mybatis-plus#6528]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

    1. 去除FastAutoGenerator.create("jdbc:postgresql://localhost:5432/postgres", "xxx", "xxx")空格字符影响
    2.     mybatis-plus-spring-boot3-starter:3.5.7

**Comment by qmdx** [comment]
不太明白，那么你为什么要加上空字符？？？

**Comment by sansWl** [comment]
> 不太明白，那你为什么要加上空字符？？？

直接复制粘贴或者拼接的时候十分容易忽视前面空格字符啊
