### ISSUE TITLE
[错误报告]: 描述 如果排序字段是带引号的字段，如"userId"，在设置排序时会去除引号(变成userId)，导致sql报错

### ISSUE THREAD

**Issue by qingzheng66** [baomidou/mybatis-plus#6530]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.4

### 问题描述

如果排序字段是带引号的字段，在设置排序时会去除引号，导致sql报错。
错误原因在：设置排序字段时，使用正则，去除掉了引号。
 public OrderItem setColumn(String column) {
        this.column = StringUtils.replaceAllBlank(column);
        return this;
    }

**Comment by qingzheng66** [comment]
大于3.5.4.1的版本会出现这个问题

**Comment by qmdx** [comment]
出于安全考虑不再允许传入`非字段字符`，如果你依然想这么使用可以重写 `OrderItem` 这个类，参考 https://github.com/baomidou/mybatis-plus/issues/6448
