### ISSUE TITLE
[功能改进]: LambdaQueryWrapper select方法为什么不能像eq、ne方法一样拼接

### ISSUE THREAD

**Issue by MuSan-Li** [baomidou/mybatis-plus#6538]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [ ] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

在写查询语句时候 select方法 不能像eq、ne方法一样拼接呢
如图所示
图片1
![1](https://github.com/user-attachments/assets/bd8bacda-1666-4b88-80ac-e8ea357fcdb4) 
图片2
![2](https://github.com/user-attachments/assets/32627212-4641-4083-9bc5-f320a47a40e4)
如果写多个select方法只会查询最后的select内容
望改进，或答复 谢谢

**Comment by miemieYaho** [comment]
就这样
