### ISSUE TITLE
[错误报告]: 执行查询mapper时，系统有时候会在渲染后的sql中添加validity字段排序，但是检查了系统并未加入该字段。

### ISSUE THREAD

**Issue by hanweidong** [baomidou/mybatis-plus#6540]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.8

### 问题描述

执行查询mapper时，系统有时候会在渲染后的sql中添加validity字段排序，但是检查了系统并未加入该字段。
![image](https://github.com/user-attachments/assets/31a673bd-f5ab-4df6-b84c-216b2a3db4fc)

**Comment by miemieYaho** [comment]
前端传的吧

**Comment by hanweidong** [comment]
没有的，我检查了下这个是get请求，没有让前端传过来排序信息。很多个接口都会偶现这个问题

**Comment by hanweidong** [comment]
看日志感觉是sql渲染的时候加了validity排序，但是在mybatisplus库没有搜索到validity

**Comment by miemieYaho** [comment]
那你提供复现demo吧
