### ISSUE TITLE
[功能改进]: 提示信息是否可以全英文或者全中文

### ISSUE THREAD

**Issue by mitu2** [baomidou/mybatis-plus#6542]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

感觉一半中文一半英文很奇怪。

### 参考资料

![image](https://github.com/user-attachments/assets/5cb46a74-8695-443e-8183-7c3de86a7100)

**Comment by miemieYaho** [comment]
为了照顾个别不看英文人士
