### ISSUE TITLE
mysql-connector-j 9.0.0 创建连接启动慢

### ISSUE THREAD

**Issue by lucky-lbc** [baomidou/mybatis-plus#6543]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.6

### 问题描述

目前就是druid 启动后，创建连接。驱动版本使用的9.0.0 .  启动很慢
使用的mysql-connector-j  版本为9.0.0.
![图片](https://github.com/user-attachments/assets/de308b6f-1dc9-411d-aa1a-d73f48eebf4d)
这个地方会hang住，非常慢。有啥解决办法吗。找了半天是mybatis-plus里面设置的版本为9.0.0  . ==！
有啥处理方法吗，我看说getHostName()引发了反向dns，spring boot 版本3.2.x

**Comment by lucky-lbc** [comment]
我在另一个项目为8.0.33 . 没有getHostName()方法。启动就很快

**Comment by miemieYaho** [comment]
用maven helper插件自己看依赖

**Comment by lucky-lbc** [comment]
> 用maven helper插件自己看依赖

看依赖排除9.0.0吗。我看了依赖冲突啊。getHostName() 慢有碰到过吗

**Comment by jinceon** [comment]
在 /etc/hosts 文件给数据库的ip加个映射就好
