### ISSUE TITLE
[功能改进]: 能否在feign接口中也能使用Wrapper进行传参。

### ISSUE THREAD

**Issue by live-in-a-dream** [baomidou/mybatis-plus#6547]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

在开发过程中，feign接口我觉得可以只需要简单得增删改查就可以，feign中不允许重新赋值，也就是说feign就如同IService简单，不知道Wrapper如何通过feign进行传递，也就是序列化。小小得建议。

**Comment by miemieYaho** [comment]
不支持传输

**Comment by live-in-a-dream** [comment]
> 不支持传输

有什么原因吗？
