### ISSUE TITLE
3.0版本后移除了MySQL等关键词的自动转义，怎么开启或者扩展支持特殊字符转义

### ISSUE THREAD

**Issue by xie-summer** [baomidou/mybatis-plus#655]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6版本

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
建表有特殊字符类似 status order ，直接使用select查询报错。关键字没有加`` 转义。有没有方法扩展支持转义，请大神求助

**Comment by miemieYaho** [comment]
字段注解里用转义符包裹 例:   
```java
@TableField("`group`")
private Integer group;
```
