### ISSUE TITLE
[功能改进]: 是否能把CrudRepository换成CrudMapper，把数据库相关操作都写在Mapper层，这样就不会出现双DAO层了

### ISSUE THREAD

**Issue by vipbooks** [baomidou/mybatis-plus#6556]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

按分层责任的划分数据库相关的操作应该放到DAO层，而在MyBatis里Mapper就是DAO层，在v3.5.9版本中新加了CrudRepository，这又是一个DAO层，就有Mapper和Repository两个DAO层了，而MVC模式中是不存在两个DAO层的，CrudRepository是JPA的说法不是MyBatis的说法，所以在MyBatisPlus中应该把原来IService的数据库操作放到CrudMapper中去，把Mapper当作真正的DAO层使用，现在的Mapper就是个XML的过度类，根本没有起到DAO层的作用，数据库操作都是在Service层完成的。

**Comment by miemieYaho** [comment]
这不算新加，以后会干掉，你不用就行了

**Comment by yozurukt** [comment]
> 这不算新加，以后会干掉，你不用就行了

你好，意思是`CrudRepository`这一层会在未来的版本中被废弃吗？

**Comment by icboluo** [comment]
这个 CRUD 和 IService 是真的垃圾

**Comment by qichhhhh** [comment]
> > 这不算新加，以后会干掉，你不用就行了
> 
> 你好，意思是`CrudRepository`这一层会在未来的版本中被废弃吗？

同问，那现在IService还要改吗？

**Comment by devbian** [comment]
<img width="871" alt="Image" src="https://github.com/user-attachments/assets/eea87e5f-9423-4163-9f83-b69825d8065d" /> 这里说【后续不再维护Service与Repository，建议不要在继续使用】，CrudRepository 不是3.5.9刚加上的吗？ 怎么又要废弃了？ 

[feat: 重构 service 模块抽象为 CrudRepository 不再建议使用 IService 避免业务层数据混乱]
