### ISSUE TITLE
[错误报告]: 最新版依赖没有PaginationInnerInterceptor插件了？

### ISSUE THREAD

**Issue by italycalibur2019** [baomidou/mybatis-plus#6557]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

![image](https://github.com/user-attachments/assets/1f48d344-8778-4fd5-b93d-8b5c44a28edd)
![image](https://github.com/user-attachments/assets/0fff857f-4bee-4cee-a1e9-2495f26331a3)
如图所示，我已按照README要求导入了最新依赖包，但是没有获取分页插件，查看源码这个类好像并没有移除掉

**Comment by italycalibur2019** [comment]
> ### 确认
> * [x]  我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
> * [x]  我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
> * [x]  我已经修改标题, 将标题中的 描述 替换为遇到的问题
> 
> ### 当前程序版本
> 3.5.9
> 
> ### 问题描述
> ![image](https://private-user-images.githubusercontent.com/53480306/380375582-1f48d344-8778-4fd5-b93d-8b5c44a28edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzE1NzQsIm5iZiI6MTcyOTkzMTI3NCwicGF0aCI6Ii81MzQ4MDMwNi8zODAzNzU1ODItMWY0OGQzNDQtODc3OC00ZmQ1LWI5M2QtOGI1YzQ0YTI4ZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4Mjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YWZkM2RlNTkyYmIzYTAzNGQ2ZDgyMGY3NzYxOTZkNTgxM2UwNzJiN2MzZTRiOWY5YjFiZGRkYzAzMzgxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SR5r00UD-xG8JgXTpcdVGTWL6IkwKotc0kq463Rgink) ![image](https://private-user-images.githubusercontent.com/53480306/380375804-0fff857f-4bee-4cee-a1e9-2495f26331a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzE1NzQsIm5iZiI6MTcyOTkzMTI3NCwicGF0aCI6Ii81MzQ4MDMwNi8zODAzNzU4MDQtMGZmZjg1N2YtNGJlZS00Y2VlLWExZTktMjQ5NWYyNjMzMWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4Mjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDhjMWFmMWUxY2VkZDIzOWViMDcwMTNkZGEzYTY4N2YyYmU3Y2ZhZGY1ZDAxNDUyZDc2NzY2Mzk3MzQ0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q2kRG2i3TrK4afpDrgVHGO4GNBNV2mJWA8k-y6KR6nY) 如图所示，我已按照README要求导入了最新依赖包，但是没有获取分页插件，查看源码这个类好像并没有移除掉
> 
> ### 详细堆栈日志
> _No response_

p.s. 将版本降至3.5.8后可以获取到分页插件

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md

**Comment by italycalibur2019** [comment]
> https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md

thx :)

**Comment by iqolome** [comment]
@miemieYaho  插件包位置拆分后文档官网没有更新,导致找不到插件对应位置,  并不知道 mybatis-plus-jsqlparser 里 PaginationInnerInterceptor 在这里,希望后面可以说明一下各个插件包被拆分到了哪里

**Comment by Bucengfeijianqurentou** [comment]
我遇到了同样的问题，降低版本才解决。

**Comment by selfdialog** [comment]
<img width="1355" height="511" alt="Image" src="https://github.com/user-attachments/assets/40cbde7b-0b65-4d62-9961-9ce5b32172cf" />

我引入了mybatis-plus-jsqlparser-4.9还是无法使用PaginationInnerInterceptor，怎么大家怎么解决的

**Comment by AllenDEricDAlexander** [comment]
> <img alt="Image" width="1355" height="511" src="https://private-user-images.githubusercontent.com/30248712/472011212-40cbde7b-0b65-4d62-9961-9ce5b32172cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQyMjU2NzAsIm5iZiI6MTc1NDIyNTM3MCwicGF0aCI6Ii8zMDI0ODcxMi80NzIwMTEyMTItNDBjYmRlN2ItMGI2NS00ZDYyLTk5NjEtOWNlNWIzMjE3MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAzVDEyNDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOWFkNTRiNWVkNjJmZjk0Y2MwZTFkZGIwN2YxOWFlOTJiZGM2YWEzNDlmOTkzOGJmNzBhYmQwYTI2MWQxYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kN0gYXr2-Q6IRvSHYYXCvZAq6wnqRd7a5qEAr3vOd7U">
> 我引入了mybatis-plus-jsqlparser-4.9还是无法使用PaginationInnerInterceptor，怎么大家怎么解决的

引入这个，版本和mp版本保持一致。 已实测，可以解决。
  <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>3.5.12</version>
</dependency>

**Comment by tatwww** [comment]
我選擇降版版本來解決 , 原來用 3.5.14 -> 3.5.12

        
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
            <version>3.5.12</version>
        </dependency>
        
        
      <dependency>
          <groupId>com.baomidou</groupId>
          <artifactId>mybatis-plus-jsqlparser</artifactId>
          <version>3.5.12</version>
      </dependency>
