### ISSUE TITLE
[错误报告]: 升级mybatis-plus3.5.9后找不到PaginationInnerInterceptor

### ISSUE THREAD

**Issue by pineapple-guo** [baomidou/mybatis-plus#6559]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

![image](https://github.com/user-attachments/assets/c4edcc3a-1253-4df5-aee5-46b1782d8177)
![image](https://github.com/user-attachments/assets/eb3423ac-d858-4407-8f8c-0e06c1cbfb02)
使用com.baomidou:mybatis-plus-spring-boot3-starter:3.5.9后，无法找到分页插件

**Comment by HoldEvan** [comment]
+1

**Comment by jongyu** [comment]
+1

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/6557

**Comment by musicguoke** [comment]
使用bom的情况下,导入下面依赖即可  [新版本的变化](https://baomidou.com/getting-started/install/#maven-bom)
```
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-jsqlparser</artifactId>
</dependency>
```

**Comment by WangHaoPro** [comment]
+1，3.5.8找得到，3.5.9找不到了
