### ISSUE TITLE
自动生成的entity ，对于表字段带下划线没有生成@TableField 注解来明确表实际字段名

### ISSUE THREAD

**Issue by mpv945** [baomidou/mybatis-plus#656]
### 根据官网的教程http://mp.baomidou.com/guide/generator.html#%E6%B7%BB%E5%8A%A0%E4%BE%9D%E8%B5%96
配置了自动生成代码操作，策列配置如下
                // 策略配置
		StrategyConfig strategy = new StrategyConfig();
		strategy.setTablePrefix(new String[] { "" });// 此处可以修改为您的表前缀
		strategy.setNaming(NamingStrategy.underline_to_camel);// 表名生成策略
		strategy.setInclude(new String[] { "test_case","test_case_info" }); // 需要生成的表
		strategy.setEntityLombokModel(true);

数据表 有个字段为open_id字段，然后生成的entity 为private Long openId;

### 重现步骤，就是如果数据有带下划线的字段，我在旧版本（2.1.8）可以生成；例如
数据表 有个字段为open_id字段
生成的entity如下
@TableField(“open_id”)
private Long openId;

**Comment by yuxiaobin** [comment]
StrategyConfig.entityTableFieldAnnotationEnable(true); --强制生成字段注解

**Comment by shengyisg** [comment]
StrategyConfig.entityTableFieldAnnotationEnable（真）; - 强制生成字段注解
因为你这个样会把不需要的（不带下划线的name字段）的这种也会生成@TableField

**Comment by fanlushuai** [comment]
> StrategyConfig.entityTableFieldAnnotationEnable(true); --强制生成字段注解

无语
