### ISSUE TITLE
[错误报告]: 分页插件PaginationInnerInterceptor没有了

### ISSUE THREAD

**Issue by li-fcb1899** [baomidou/mybatis-plus#6561]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

![image](https://github.com/user-attachments/assets/200b21ee-6483-434c-b32a-5a79378350c1)
![image](https://github.com/user-attachments/assets/3a9bae42-14b8-4fca-a37d-7798e2087c9c)

**Comment by noroadzh** [comment]
我和你一样的问题，我还以为是我写错了，然后去看了mybatis-plus的包，里面的确没有PaginationInnerInterceptor这个了

**Comment by Comven** [comment]
需要自己手动引入jsqlparser，3.5.9之后做了组件拆分
```
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-jsqlparser</artifactId>
</dependency>
```

**Comment by Qwenjin** [comment]
3.5.9 最低版本Java11？ mybatis-plus-jsqlparser 无法用Java8

Failed to instantiate [com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor]: Factory method 'mybatisPlusInterceptor' threw exception; nested exception is java.lang.UnsupportedClassVersionError: net/sf/jsqlparser/statement/select/SelectItem has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Qwenjin** [comment]
3.5.7是最后一个支持Java8的？

**Comment by li-fcb1899** [comment]
> 需要自己手动引入jsqlparser，3.5.9之后做了组件拆分
> 
> ```
> <dependency>
>     <groupId>com.baomidou</groupId>
>     <artifactId>mybatis-plus-jsqlparser</artifactId>
> </dependency>
> ```

好的，希望官网文档里提示一下

**Comment by Comven** [comment]
> mybatis-plus-jsqlparser

试试引入mybatis-plus-jsqlparser-4.9 试试，不知道行不行，没测试过

**Comment by AiJiangnan** [comment]
SpringBoot2引用：
```xml
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-jsqlparser-4.9</artifactId>
</dependency>
```

SpringBoot3引用：
```xml
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-jsqlparser</artifactId>
</dependency>
```

**Comment by gonownow** [comment]
请问jsqlparser没有用怎么解决
![image](https://github.com/user-attachments/assets/ec217499-d7aa-4f85-a0a2-9d5bf5143879)
![image](https://github.com/user-attachments/assets/051b3a42-298b-4c18-bd44-c09446814441)


> SpringBoot2引用：
> 
> ```
> <dependency>
>     <groupId>com.baomidou</groupId>
>     <artifactId>mybatis-plus-jsqlparser-4.9</artifactId>
> </dependency>
> ```
> 
> SpringBoot3引用：
> 
> ```
> <dependency>
>     <groupId>com.baomidou</groupId>
>     <artifactId>mybatis-plus-jsqlparser</artifactId>
> </dependency>
> ```



> 需要自己手动引入jsqlparser，3.5.9之后做了组件拆分
> 
> ```
> <dependency>
>     <groupId>com.baomidou</groupId>
>     <artifactId>mybatis-plus-jsqlparser</artifactId>
> </dependency>
> ```

**Comment by AiJiangnan** [comment]
@gonownow 新版本的建议使用pom导入依赖版本。

```
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-bom</artifactId>
    <version>${mybatis-plus.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

**Comment by chenmobuys** [comment]
这种大改动，版本号这样变更
