### ISSUE TITLE
[功能改进]: 无法为主键设置typeHandler

### ISSUE THREAD

**Issue by ZhaoGuoXin** [baomidou/mybatis-plus#6565]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

因为主键使用的是uuid, 需要自己实现typeHandler. 但是tableId和tableField不能同时生效, 无法为主键设置typeHandler.

**Comment by miemieYaho** [comment]
不支持，你可以选择注入到全局typehandler

**Comment by yyinghan** [comment]
mysql8 支持uuid v7通过uuid_to_bin转成binary来达到uuid的有序排列，这样uuid v7很适合做为主键，但需要代码做一定转换，typehandler就很合适。如果使用String类型的uuid做主键，使用全局typehandler则会对所有使用String的主键产生影响，无法控制到表。比较好的解决办法是用java.util.UUID类型做TableId再结合全局typehandler，但mp的IdentifierGenerator仅支持Number和String类型，如果使用java.util.UUID，则IdentifierGenerator会失效，无法自动生成id。所以建议@TableId支持typeHandler，或者增加@TypeHandler注解来指定typeHandler，或者让IdentifierGenerator支持自定义类型。
