### ISSUE TITLE
[错误报告]: 使用generator生成代码的时候，文件路径空字符串时，导包错误。

### ISSUE THREAD

**Issue by xuemingqi** [baomidou/mybatis-plus#6566]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

v3.5.9

### 问题描述

使用generator生成代码的时候，文件路径空字符串时，导包错误。
比如
FastAutoGenerator.create(DB_URL, DB_USERNAME, DB_PASSWORD)
                .packageConfig(builder -> builder
                        .parent("com.test.db")
                        .controller("")
生成的controller,package com.test.db.;后面多了一个点“.”

**Comment by ppx-build-code** [comment]
.controller("") 
不需要重定义包名就不要设置

**Comment by xuemingqi** [comment]
> .controller("") 不需要重新定义包名就不要设置

容错上我觉得应该要修改一下。
