### ISSUE TITLE
[错误报告]: 遇到的问题 mybatisplus执行count()方法时,需要对查询字段加密,但是在拦截器中获取不到实体对象

### ISSUE THREAD

**Issue by runnerFeng** [baomidou/mybatis-plus#6576]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

// 支持 LambdaQueryWrapper
        if (paramMap.containsKey(Constants.WRAPPER) && paramMap.get(Constants.WRAPPER) instanceof AbstractWrapper) {
            AbstractWrapper queryWrapper = (AbstractWrapper) paramMap.get(Constants.WRAPPER);
//            Class<?> entityClass = queryWrapper.getEntityClass();
            Class<?> entityClass = getEntityClass(queryWrapper);
            // TODO count方法获取不到class
            if (entityClass!=null && annotateWithEncrypt(entityClass)) {
                encryptWrapperForQuery(entityClass, queryWrapper, boundSql);
            }
        }

**Comment by runnerFeng** [comment]
`private Class<?> getEntityClass(AbstractWrapper queryWrapper) {
        // 使用反射从 LambdaQueryWrapper 中获取实体类的类型
            Class entityClass = queryWrapper.getEntityClass();
            if (entityClass == null){
//                queryWrapper.
            }
            return entityClass;
    }`

**Comment by miemieYaho** [comment]
你set实体了吗？

**Comment by runnerFeng** [comment]
`count(new LambdaQueryWrapper<HedgeExchange>().eq(xxx))>0`
改成这种
`count(new LambdaQueryWrapper<>(HedgeExchange.class).eq(xxx))>0`
可以了
第一种写法可以支持获取entityClass吗，这种写法我看设置为null了
感谢回复！

**Comment by miemieYaho** [comment]
你翻翻Java看看他能获取不
