### ISSUE TITLE
自动生成代码，关于表字段生成问题指正

### ISSUE THREAD

**Issue by mpv945** [baomidou/mybatis-plus#658]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
我的表字段包含下划线的字段名称user_group_id，但是自动生成的实体对象没有生成数据@TableField("user_group_id")注解

### 重现步骤
数据库表字段带下划线，字段名全小写字母，生成实体映射不加@TableField

### 报错信息
最后发现是这个方法
com.baomidou.mybatisplus.generator.config.po.TableField#setConvert(com.baomidou.mybatisplus.generator.config.StrategyConfig)中，else if (NamingStrategy.underline_to_camel == strategyConfig.getColumnNaming()) 判断之后应该直接判断!this.name.equals(this.propertyName)而不是判断this.name是否存在大写才设置转换属性，或者应该判断this.propertyName是否包含大写。望下个版本能修正。感谢

**Comment by qmdx** [comment]
这不是错误 mp 使用有一个命名策略，你这个符合下划线命名策略，只要全局配置即可，默认是推荐不注解方案

**Comment by fanlushuai** [comment]
> 也许你使用的某个版本不是这个，有升级日志可以看看什么时候调整的。

Bug: 数据库字段全下划线命名，策略选择下划线转驼峰，永远不会生成@TableField。
如果采用全局强制策略。对于那些没有发生下划线转化的也会加上注解。违背了你所谓的不建议加。同样让对此有要求的使用者无语。

**Comment by qmdx** [comment]
@fanlushuai 代码和生成器是分别配置的，生成器只是辅助加速开发的怎么选择策略还需要开发者去判别，如有 Bug 欢迎 pr
