### ISSUE TITLE
[功能改进]: TypeHandler针对List<T>反序列化时, 无法获取到List.class的泛型, 建议@TableField注解增加一个字段以描述泛型

### ISSUE THREAD

**Issue by Tuhuaqing** [baomidou/mybatis-plus#6586]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

[功能改进]: TypeHandler针对List<T>反序列化时, 无法获取到List.class的泛型

![1](https://github.com/user-attachments/assets/74d8c4b0-552a-4d17-8bb6-2b0996a5d1af)

这导致使用FastjsonTypeHandler反序列化出来的List<T>实际上是个 List<JSONObject>, 在读取其元素数据时报错了.

![2](https://github.com/user-attachments/assets/2e947cb2-c52c-4415-bf24-84d99a958dcb)

建议@TableField注解增加一个字段以描述List泛型类, 这样我就可以在FastjsonTypeHandler中更好的反序列化

**Comment by mayu3952678** [comment]
为啥关了

**Comment by incubus-ohy** [comment]
> 为啥关了

+1

**Comment by llongtao** [comment]
为啥关了
+1

**Comment by jzbjbcxy** [comment]
为啥关了
