### ISSUE TITLE
现在的3.x.x版本感觉让2.x 的选择升级很难

### ISSUE THREAD

**Issue by mappstore** [baomidou/mybatis-plus#659]
SqlMethod中为什么把UPDATE_ALL_COLUMN_BY_ID、INSERT_ONE_ALL_COLUMN、UPDATE_FOR_SET这几个对应的方法删除？
另外selectPage里的参数为什么不保留org.apache.ibatis.session.RowBounds？即使你要添加自己的实现对象也应该继承这个对象进行扩展
上面情况其实可以通过新增接口来解决，保留原有的接口尽可能向下兼容。
另外EntityWrapper已经去掉且父类修改，现在加的几个我不觉得比原来这个EntityWrapper会好很多。

**Comment by miemieYaho** [comment]
精简接口,提供更加通用的,那只是你觉得
