### ISSUE TITLE
[功能改进]: 遇到的问题 mapper自带的方法能不能动态自定义返回类型？

### ISSUE THREAD

**Issue by AiHaoChen** [baomidou/mybatis-plus#6596]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

       假设有一个PersonMapper，那么对应的查询数据列表的结果是Person， Person类就对应的是表的原字段。
       但是在实际业务开发过程中，返回的Person类不一定满足需求，需要增加一些字段变成PersonDTO，PersonVO之类的，还需要手动用工具把Person类转换为对应的类。倘若是查询一条数据还好，但是若是查询列表也不是分页，也需要手动转换，需要通过工具再转一道就浪费性能和时间。
       因从，能否在使用自带的personMapper.selectList等方法的时候，就能传入需要的结果类型，返回也返回需要的结果类型，从而简化这一步，减少时间和性能消耗。

**Comment by miemieYaho** [comment]
不能
