### ISSUE TITLE
[错误报告]: 描述 select 语句自动添加了Limit 10000000000001 怎么调整自动添加的limit 后面的 值的大小

### ISSUE THREAD

**Issue by biuifuture** [baomidou/mybatis-plus#6598]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.4.0

### 问题描述

select id, xxx,xxx from xxx where  yn = 1 limit 10000000000001;

请问怎么调整自动添加的limit 后面的 值的大小

**Comment by miemieYaho** [comment]
就没有自动limit的功能

**Comment by biuifuture** [comment]
那这个limit 怎么加上的，代码肯定没有显性的拼装
