### ISSUE TITLE
@TableId和@TableField不能组合使用

### ISSUE THREAD

**Issue by yangpengfei369** [baomidou/mybatis-plus#66]
使用版本号为`1.0`的`mybatisplus-maven-plugin`生成代码,vo类中的主键属性字段上有两条注解`@TableId(type = IdType.UUID)@TableField(value="B_ID")private String bId;`实际使用时并没有将SQL中的`bId`映射成`B_ID`,需要手动修改为'@TableId(value="B_ID", type = IdType.UUID)'.
不知道是不是偶发,请知悉

**Comment by qmdx** [comment]
1.0 已经不维护了，你可以尝试自己修改下生成器。或者升级为 2.x 最新版
