### ISSUE TITLE
[错误报告]: type-handlers-package全局配置未生效

### ISSUE THREAD

**Issue by 17857333693** [baomidou/mybatis-plus#6602]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

我使用@TableField(typeHandler = UserPasswordTypeHandler.class)单独指定 typehandler可以正常工作
当我注释掉 @TableField(typeHandler = UserPasswordTypeHandler.class)
改用全局type-handlers-package: com.pjb.demo.mapper.handler时 typehandler无法生效

备注：@TableName(autoResultMap = true) 已加

**Comment by miemieYaho** [comment]
git形式给出你的复现demo

**Comment by 17857333693** [comment]
https://gitee.com/pan-jiabin/demo.git
![image](https://github.com/user-attachments/assets/2a60e59b-5392-4ce0-b8dd-b1d56712ab74)
![image](https://github.com/user-attachments/assets/e919d90c-1612-4a9b-bf7b-b65f7e93262f)
![image](https://github.com/user-attachments/assets/32c7bd14-8c18-465d-a007-9ad273dc891b)

**Comment by miemieYaho** [comment]
初步看如果你这个能全局生效那会影响所有string类型的字段

**Comment by 17857333693** [comment]
是的 但实际上typehandler并没有产生作用

**Comment by miemieYaho** [comment]
因为排在了默认string的typehandler后面

**Comment by 17857333693** [comment]
奥 懂了 感谢感谢

**Comment by 17857333693** [comment]
我还想问一个问题 ：目前可以替代全局
