### ISSUE TITLE
[功能改进]: 阅读官方文档，我已关闭广告过滤，还不能访问，真想逼出来一个fuck baomidou吗

### ISSUE THREAD

**Issue by xiaomizhou2** [baomidou/mybatis-plus#6605]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

阅读官方文档，我已关闭广告过滤，还不能访问，真想逼出来一个fuck baomidou吗

### 参考资料

阅读官方文档，我已关闭广告过滤，还不能访问，真想逼出来一个fuck baomidou吗

**Comment by flik1337** [comment]
+1

**Comment by xiaomizhou2** [comment]
欲盖弥彰了开始

**Comment by xiaomizhou2** [comment]
@miemieYaho 不解决问题 解决提出问题的人是吧

**Comment by xiaomizhou2** [comment]
![image](https://github.com/user-attachments/assets/57ead056-51a5-402d-86bb-dfdc483f3ead)

**Comment by ZHAO-CURRY** [comment]
![image](https://github.com/user-attachments/assets/3606db45-95f3-40f7-b678-6eb153877822)

**Comment by qiuyueovo** [comment]
![image](https://github.com/user-attachments/assets/0dc83e0c-3d19-42c1-9f0b-43fe3be4f647)
我也是 但是我并没有任何关于跳过ad之类的插件

**Comment by chairc** [comment]
fuck baomidou

**Comment by libin-tech** [comment]
免费让你用看点广告怎么了？
