### ISSUE TITLE
[错误报告]: 描述 Cannot invoke "Object.hashCode()" because "key" is null

### ISSUE THREAD

**Issue by liufenix** [baomidou/mybatis-plus#6606]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

执行联表查询时报错

### 详细堆栈日志

```

**Comment by miemieYaho** [comment]
git形式给出复现demo

**Comment by liufenix** [comment]
定位到原因了
