### ISSUE TITLE
[功能改进]: 希望在使用字段自动填充时，做更新填充操作支持覆盖原来的属性值

### ISSUE THREAD

**Issue by wu-sv** [baomidou/mybatis-plus#6610]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

自动填充时写了
`    @Override
    public void updateFill(MetaObject metaObject) {

        log.info("开始更新填充...");

        this.strictUpdateFill(metaObject, "updateTime", LocalDateTime.class, LocalDateTime.now());

    }`
但是由于在insert操作时也已经对updateTime进行了写入操作，所以使得updateTime该属性已经有值了，而现阶段MetaObjectHandler 提供的默认方法策略是：如果属性有值则不覆盖：
` default MetaObjectHandler strictFillStrategy(MetaObject metaObject, String fieldName, Supplier<?> fieldVal) {

        if (metaObject.getValue(fieldName) == null) {

            Object obj = fieldVal.get();

            if (Objects.nonNull(obj)) {

                metaObject.setValue(fieldName, obj);

            }

        }

        return this;

    }`
所以也就导致updateTime没有随着每次update时进行时间的更新，希望能够支持在做update时能覆盖原来的值

**Comment by miemieYaho** [comment]
你自己cv一下改改用不就行了

**Comment by wu-sv** [comment]
> 你自己cv一下改改用不就行了
好吧

**Comment by corleonePeng** [comment]
一语惊醒梦中人，我研究一上午了，原来更新字段没有每次都刷新啊，感觉是个使用习惯的问题吧
