### ISSUE TITLE
[功能改进]: 能否修改 TableInfo里面的 fieldList，我想动态增加一些字段进去

### ISSUE THREAD

**Issue by huixiang-2024** [baomidou/mybatis-plus#6616]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

我想在PostInitTableInfoHandler 的扩展里面，对 TableInfo 进行修改，增加一些未定义的公共字段，但是我发现TableInfo获取的fieldList 是不可修改的，我该如何实现我的需求呢
```
public List<TableFieldInfo> getFieldList() {
    return Collections.unmodifiableList(this.fieldList);
  }
```

**Comment by huayanYu** [comment]
反射
