### ISSUE TITLE
Mybatis-plus支持sql函数吗？比如最大值函数max()

### ISSUE THREAD

**Issue by HowardHub** [baomidou/mybatis-plus#662]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
提供的查询条件只有where的拼接？

### 重现步骤
我想找数据库中某个表id（为bigint类型）的最大值，请问在mybatis-plus中怎样实现哦？

**Comment by miemieYaho** [comment]
http://mp.baomidou.com/guide/wrapper.html#select  
http://mp.baomidou.com/guide/wrapper.html#apply  
熟读文档,自由发挥

**Comment by HowardHub** [comment]
文档上又没有这种使用方式，这会儿Mybatis-plus使不上劲。只能用mybatis，把max()函数写到mapper.xml文件中去。


| |
pp361127
|
|
pp361127@163.com
|
签名由网易邮箱大师定制
在2018年11月29日 15:35，miemieYaho<notifications@github.com> 写道：

Closed #662.

**Comment by qmdx** [comment]
@HowardHub  复杂的 sql 建议 xml 解决

**Comment by wujunshen** [comment]
SELECT MAX(id)    FROM table
这么简单的sql还要我用xml或者手写sql在代码，那么这个plus有啥用？

**Comment by yuxiaobin** [comment]
回楼上，方法在那里，看你会不会用：

QueryWrapper<User> wrapper = new QueryWrapper<>();
wrapper.select("max(id) as id");
User user = mapper.selectOne(wrapper);
System.out.println("maxId=" + user.getId());
List<User> users = mapper.selectList(Wrappers.<User>lambdaQuery().orderByDesc(User::getId));
Assert.assertEquals(user.getId().longValue(), users.get(0).getId().longValue());

**Comment by wujunshen** [comment]
> 回楼上，方法在那里，看你会不会用：
> 
> QueryWrapper wrapper = new QueryWrapper<>();
> wrapper.select("max(id) as id");
> User user = mapper.selectOne(wrapper);
> System.out.println("maxId=" + user.getId());
> List users = mapper.selectList(Wrappers.lambdaQuery().orderByDesc(User::getId));
> Assert.assertEquals(user.getId().longValue(), users.get(0).getId().longValue());

多谢，后来解决了。之前没有找到好的方法，有点急了，言语上有些不敬，抱歉了
