### ISSUE TITLE
[功能改进]: 是否可以提供集成guice框架的功能

### ISSUE THREAD

**Issue by czlovewyw** [baomidou/mybatis-plus#6620]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

我们团队目前没有使用spring作为我们的框架选型，而是基于vertx+guice封装了一套轻量化框架，并使用了mybatis作为我们的持久化框架技术选型。现在考虑切换到mybatis-plus，但是发现作者并未像mybatis那样提供集成guice的封装，不知道是否可以考虑提供该项集成封装能力。

### 参考资料

mybatis基于guice的封装可见如下地址：https://mybatis.org/guice/index.html

**Comment by huayanYu** [comment]
团队没人熟悉guice， 您可以直接提交PR

**Comment by Ai-010** [comment]
mybatis-plus 改动的多 感觉不太好支持 guice
