### ISSUE TITLE
[错误报告]: 数据库表名是database,使用了反括号，生成的查询sql报错，使用的mysql

### ISSUE THREAD

**Issue by arrayest** [baomidou/mybatis-plus#6621]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

我新建的数据库表名是database,使用了反括号。@Table(name = "`database`")
但是是生成的sql没有给database表名加上反括号，导致sql是错误的。需要框架能够保留我的数据库中database表名的外面的反括号。

### 详细堆栈日志

```bash
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,name,owner,character_set,collation,comment,created_at,updated_at  FROM database           ORDER BY updated_at DESC
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database           ORDER BY updated_at DESC' at line 1
; bad SQL grammar []] with root cause
```

**Comment by miemieYaho** [comment]
我们没有叫`table`的注解

**Comment by arrayest** [comment]
> 我们没有叫`table`的注解

这个注解是jpa提供的。可以生成mysql关键字的表名。但是使用mybatis plus 默认的QueryMapper查询，生成的sql不正确。

**Comment by miemieYaho** [comment]
我们什么时候说过会认jpa的注解了?

**Comment by arrayest** [comment]
关闭issue吧。我用了@TableName("`database`")
注解后，已经好了。

**Comment by arrayest** [comment]
关闭issue吧。我用了@TableName("`database`")
注解后，已经好了。
