### ISSUE TITLE
[功能改进]: 是否考虑在Wrapper类中增加一个布尔值或者Map值，让后续的插件使用到自定义值

### ISSUE THREAD

**Issue by jxgahxs** [baomidou/mybatis-plus#6624]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

使用场景：假设使用Wrapper条件查询，条件构造器为带有参数，此时会查全表。如果表数据过大，会造成内存溢出。我写了一个大查询拦截插件（针对Wrapper条件没有参数），如果Wrapper条件没有SQL参数片段直接拒绝。但是有些场景是的的确确要查询全表的。我的想法是否能在Wrapper类中添加一个设置布尔值或者Map值（设置安全因子），由使用者根据安全因子条件去决定是否拦截大查询SQL。

**Comment by miemieYaho** [comment]
你的需求你自己用treadlocal存取不就够了
