### ISSUE TITLE
[错误报告]: 描述多个List泛型的对象无法通过字段类型处理器TypeHandler处理的问题

### ISSUE THREAD

**Issue by likyin** [baomidou/mybatis-plus#6627]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

使用背景：Springboot3.2.5, jdk17, mysql8, mybatis-plus3.5.9

问题描述：当应用内存在多个List<>类型的TypeHandler时，只有最先使用的那个TypeHandler会生效。

由于业务需要，数据库的多个表中存有多个List类型的序列化后json内容，这些字段对应不同的Java实体类，需要在查询的时候将json类型的内容反序列化为List<?>对象。

以下为我的实现方式：

1. TypeHandler实现：

`@MappedJdbcTypes(JdbcType.VARCHAR)
@MappedTypes(List.class)
public abstract class ListTypeHandler<T> implements TypeHandler<List<T>> {

    @Override
    public void setParameter(PreparedStatement ps, int i, List<T> parameter, JdbcType jdbcType) throws SQLException {
        ps.setString(i, JsonUtils.toJson(parameter));
    }

    @Override
    public List<T> getResult(ResultSet rs, String columnName) throws SQLException {
        return toListObject(rs.getString(columnName));
    }

    @Override
    public List<T> getResult(ResultSet rs, int columnIndex) throws SQLException {
        return toListObject(rs.getString(columnIndex));
    }

    @Override
    public List<T> getResult(CallableStatement cs, int columnIndex) throws SQLException {
        return toListObject(cs.getString(columnIndex));
    }

    protected abstract List<T> toListObject(String json);

}`

`@MappedJdbcTypes(JdbcType.VARCHAR)
@MappedTypes(List.class)
public class CheckoutOriginalListHandler extends ListTypeHandler<WarehouseCheckout.OriginalInfo> {

    @Override
    protected List<WarehouseCheckout.OriginalInfo> toListObject(String json) {
        if(StringUtils.isBlank(json)){
            return null;
        }
        return JsonUtils.toObject(json, List.class, WarehouseCheckout.OriginalInfo.class);
    }

}`

`@MappedJdbcTypes(JdbcType.VARCHAR)
@MappedTypes(List.class)
public class ItemLeftAmountListHandler extends ListTypeHandler<ItemInfo.LeftAmountInfo> {

    @Override
    protected List<ItemInfo.LeftAmountInfo> toListObject(String json) {
        if(StringUtils.isBlank(json)){
            return null;
        }
         return JsonUtils.toObject(json, List.class, ItemInfo.LeftAmountInfo.class);

    }
}
`

2. 然后再对应的实体类中用TableField的typeHandler进行关联：
  @TableField(typeHandler = CheckoutOriginalListHandler.class)
  private List<WarehouseCheckout.OriginalInfo> originalInfoList;
  @TableField(  typeHandler = ItemLeftAmountListHandler.class)
  private List<LeftAmountInfo> leftInfoList;

3. 当我实现以上内容时，仅有应用启动后最先初始化的TypeHandler生效。
 如果我先使用CheckoutOriginalListHandler相关的查询，则我在后续查询ItemLeftAmountListHandler的时候，字段会被反序列化为List<WarehouseCheckout.OriginalInfo>类型，反之亦然。

**Comment by miemieYaho** [comment]
给出你的复现demo以git形式

**Comment by xutengx** [comment]
同样的问题.

**Comment by flypiggy-stack** [comment]
同样的问题，怎么解决呢？

**Comment by xutengx** [comment]
自定类型继承 List, 或者 使用其他的数据库框架 https://github.com/gaarason/database-all

**Comment by minggg98** [comment]
save issue, how to solve it?

**Comment by HanHan666666** [comment]
这个问题好像是在TypeHandler上使用了@MappedTypes(List.class)导致的，这个注解会把这个TypeHandler注册到全局，让mybatis plus自动选择，而不是走你字段上注解指定的那个
要走指定的，实体类要加@TableName(value="xxx", autoResultMap = true) 开启这个autoResultMap
加了这个，MP 才会按字段上的 typeHandler 构建 resultMap 好像是，而不是走全局 List.class 的 handler 选择。
开启 autoResultMap 并在字段上显式指定 handler 应该就行了。

**Comment by xutengx** [comment]
> 这个问题好像是在TypeHandler上使用了@MappedTypes(List.class)导致的，这个注解会把这个TypeHandler注册到全局，让mybatis plus自动选择，而不是走你字段上注解指定的那个 要走指定的，实体类要加@TableName(value="xxx", autoResultMap = true) 开启这个autoResultMap 加了这个，MP 才会按字段上的 typeHandler 构建 resultMap 好像是，而不是走全局 List.class 的 handler 选择。 开启 autoResultMap 并在字段上显式指定 handler 应该就行了。

你是对的, 不过我还想知道的是, 你是如何知道这个答案的, 是有这种问题或者使用方式的文档吗 ?

**Comment by HanHan666666** [comment]
> > 这个问题好像是在TypeHandler上使用了@MappedTypes(List.class)导致的，这个注解会把这个TypeHandler注册到全局，让mybatis plus自动选择，而不是走你字段上注解指定的那个 要走指定的，实体类要加@TableName(value="xxx", autoResultMap = true) 开启这个autoResultMap 加了这个，MP 才会按字段上的 typeHandler 构建 resultMap 好像是，而不是走全局 List.class 的 handler 选择。 开启 autoResultMap 并在字段上显式指定 handler 应该就行了。
> 
> 你是对的, 不过我还想知道的是, 你是如何知道这个答案的, 是有这种问题或者使用方式的文档吗 ?

这很简单，AI辅助分析一下mybatis plus的源码。或者直接让AI分析，然后自己再去确认一下代码逻辑，防止AI犯错。
