### ISSUE TITLE
[功能改进]: 描述 接入tdengine时，如何使用mybatis-plus做字段映射，做简单的增删改查？

### ISSUE THREAD

**Issue by qq61966100** [baomidou/mybatis-plus#6635]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

接入tdengine时，如何使用mybatis-plus做字段映射，做简单的增删改查？没找到对应的文档，目前我用xml每个表都要写sql

**Comment by miemieYaho** [comment]
其他db怎么做就怎么做
