### ISSUE TITLE
实体类中关系问题

### ISSUE THREAD

**Issue by tankxxl** [baomidou/mybatis-plus#664]

**Comment by miemieYaho** [comment]
不想写 sql 去用 hibernate,mybatis 的特点就是在 xml 维护 sql

**Comment by tankxxl** [comment]
> 不想写 sql 去用 hibernate,mybatis 的特点就是在 xml 维护 sql

不是不想写sql哈，只是想知道这种实体关联关系下，mp是如何处理的？是不是我的实体只要嵌套实体如：Student对象中有一个School对象，那么mp提供的BaseMapper、ActiveRecord等都不能用了，所有sql只能自己写，来处理Student和School属性的对应关系？？

**Comment by miemieYaho** [comment]
mp 只维护单表 sql, 不支持 join
