### ISSUE TITLE
[错误报告]: mybatis-plus-solon-plugin 无对应Mapper.xml的java类 没有进行注入

### ISSUE THREAD

**Issue by Winminn** [baomidou/mybatis-plus#6643]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

在sonlon中，正常启动项目，但是调用IcoDAO ，
会报错`Type interface com.cn.dao.ico.IcoDAO is not known to the MybatisPlusMapperRegistry`
该类无对应的mapper.xml，加上一个mapper.xml后可以解决该问题
``` java
package com.cn.dao.ico;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.cn.pojo.po.IcoPO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface IcoDAO extends BaseMapper<IcoPO> {
}

```

### 详细堆栈日志

```bash
org.apache.ibatis.binding.BindingException: Type interface com.cn.dao.ico.IcoDAO is not known to the MybatisPlusMapperRegistry.
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.lambda$getMapper$1(MybatisMapperRegistry.java:54)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.getMapper(MybatisMapperRegistry.java:54)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMapper(MybatisConfiguration.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:291)
	at com.baomidou.mybatisplus.core.override.SolonMybatisMapperProxy.invoke(SolonMybatisMapperProxy.java:29)
	at com.sun.proxy.$Proxy34.selectList(Unknown Source)
        at com.cn.service.ico.IcoServiceImpl.updateIco(IcoServiceImpl.java:75)
```

## 对比两个3.5.9版本
`mybatis-plus-boot-starter`
`mybatis-plus-solon-plugin`

是调用com.baomidou.mybatisplus.core.MybatisConfiguration#addMapper 方法进行Mapper注入
- 以下为spring的调用链路
![image](https://github.com/user-attachments/assets/f07ad777-a905-4f12-a2fe-0a9f588ae319)

- 以下是solon的调用链路
![image](https://github.com/user-attachments/assets/91637826-15e1-4799-b976-a88df1f007f2)

spring会触发org.mybatis.spring.mapper.MapperFactoryBean#checkDaoConfig 方法 进行注入

solon要怎么实现请帮忙解决一下

**Comment by LemonCute** [comment]
为什么关闭了该 issue ，问题依然存在啊。
mybatisplus的一个核心功能就是不需要写xml文件，现在的代码设计导致我不写xml完全不行

**Comment by noear** [comment]
一直都是可以没有 xml 的。参考示例：

https://gitee.com/opensolon/solon-examples/blob/main/4.Solon-Data/demo4031-mybatisplus/src/main/java/demo4031/dso/mapper/AppxMapper2.java

---

你的错，是别的问题引起的。。。具体可以参考示例项目

**Comment by Winminn** [comment]
> 为什么关闭了该 issue ，问题依然存在啊。 mybatisplus的一个核心功能就是不需要写xml文件，现在的代码设计导致我不写xml完全不行

当时没有解决我的问题，就给我关了。
我最近发现是配置问题，yml要加类的扫描路径 `com.cn.dao.*`

详细配置如下
```
mybatis.db1:
  mappers:        #支持包名 或 类名 或 xml（.xml结尾）//支持 ** 和 *
    - "classpath:mappers/*.xml"
    - "com.cn.dao.*"   #  ！！！！  加这一段才会扫描 @Mapper注解的类
```

**Comment by LemonCute** [comment]
@Winminn 啊好吧，我想起来了。这个Mapping 是可以配置XML，也可以配置接口类的。只是这里没有MappingScan了。
