### ISSUE TITLE
逻辑删除 与 unique key的问题

### ISSUE THREAD

**Issue by pozhenzi9010** [baomidou/mybatis-plus#666]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 遇到的问题
在设计unique key的时候将is_deleted字段与应用要求unique的字段一起放入unique key中，这样is_deleted=0的记录就不会与is_deleted=1的字段冲突了,这是符合逻辑的，is_deleted=0的记录之间会发生冲突，但这正是unique key的本意，所以也是符合逻辑的，但是问题在于is_deleted=1的记录之间也会发生冲突,简单来说就是 unique key存在的情况下不允许unique key字段相同的记录被删除两次以上

### 个人建议 仅供参考
增加delete_time字段，软删除时把该字段更新为当前时间，查询时where条件后加 delete_time is null

**Comment by miemieYaho** [comment]
这属于你们业务上的事,不支持,自行处理

**Comment by PedroGao** [comment]
经过我半天的探索和研究，增加delete_time的方式如下：

1. 添加逻辑删除注解

```java
@Getter
@Setter
@ToString
public class User {

    private Long id;

    private String name;

    private Integer age;

    private String email;

    @TableLogic
    private Date deleteTime;
}
```


2. 修改appplication.properties配置

```properties
# mybatis.mapper-locations=classpath:mapper/*.xml
# mybatis.type-aliases-package=com.pedro.shirodemo.mapper
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 逻辑删除
mybatis-plus.global-config.db-config.logic-delete-value=NOW()
mybatis-plus.global-config.db-config.logic-not-delete-value=NULL
```

此处比较取巧，因为delete-value和not-delete-value均为字符串值，sql在拼接的时候也会拼字符串，因此完全可以借助sql自身的 NOW() 函数来实现delete_time的赋值。

希望可以重开此issue，帮助更多的开发者，拜谢了，确实又很多人在这个问题上绕了很久。

**Comment by qmdx** [comment]
> 经过我半天的探索和研究，增加delete_time的方式如下：
> 
> 1. 添加逻辑删除注解
> 
> ```java
> @Getter
> @Setter
> @ToString
> public class User {
> 
>     private Long id;
> 
>     private String name;
> 
>     private Integer age;
> 
>     private String email;
> 
>     @TableLogic
>     private Date deleteTime;
> }
> ```
> 
> 1. 修改appplication.properties配置
> 
> ```ini
> # mybatis.mapper-locations=classpath:mapper/*.xml
> # mybatis.type-aliases-package=com.pedro.shirodemo.mapper
> mybatis-plus.configuration.map-underscore-to-camel-case=true
> # 逻辑删除
> mybatis-plus.global-config.db-config.logic-delete-value=NOW()
> mybatis-plus.global-config.db-config.logic-not-delete-value=NULL
> ```
> 
> 此处比较取巧，因为delete-value和not-delete-value均为字符串值，sql在拼接的时候也会拼字符串，因此完全可以借助sql自身的 NOW() 函数来实现delete_time的赋值。
> 
> 希望可以重开此issue，帮助更多的开发者，拜谢了，确实又很多人在这个问题上绕了很久。

值得鼓励
