### ISSUE TITLE
wp.apply() 参数问题

### ISSUE THREAD

**Issue by qhl100** [baomidou/mybatis-plus#668]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

wp.apply("") ro wp.apply(null);

### 重现步骤
WHERE null

### 报错信息

WHERE null

这块是否能优化一下,如果参数为null or "" 那么不进行拼装或者抛出异常

**Comment by miemieYaho** [comment]
自己进行判断, wp.apply(StringUtils.isNotBlack(value),value)
