### ISSUE TITLE
2.1.9升级3.0.6报错需要sqlSessionFactory

### ISSUE THREAD

**Issue by yybray** [baomidou/mybatis-plus#672]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
2.1.9同样的代码 升级3.0.6

### 重现步骤
单元测试service的list方法

### 报错信息
需要sqlSessionFactory

**Comment by miemieYaho** [comment]
不推荐从 2.x 直接升级到 3.x.  
去看3.x 的例子  https://gitee.com/baomidou/mybatis-plus-samples
