### ISSUE TITLE
建议Wrapper的方法都写一个重载，不带Wrapper的，而不是传null

### ISSUE THREAD

**Issue by jasmine4y** [baomidou/mybatis-plus#673]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 重现步骤

![default](https://user-images.githubusercontent.com/29448988/49488384-642de880-f881-11e8-9ad4-1e8e62ec8b88.png)

### 报错信息

建议这些带Wrapper的方法都写一个重载，不带Wrapper的，而不是传null

**Comment by miemieYaho** [comment]
???

**Comment by jasmine4y** [comment]
![default](https://user-images.githubusercontent.com/29448988/49488579-2bdada00-f882-11e8-93ab-001006b2945f.png)

**Comment by miemieYaho** [comment]
我们只提供最基本的需求,这种特殊要求自行处理
