### ISSUE TITLE
逻辑删除字段加入@TableLogic注解后，更新对象报错

### ISSUE THREAD

**Issue by jasmine4y** [baomidou/mybatis-plus#674]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

逻辑删除字段加入@TableLogic后
![default](https://user-images.githubusercontent.com/29448988/49497310-0ca07480-f8a3-11e8-82dc-bbd9f500d9b8.png)

### 重现步骤
没加入@TableLogic前
![default](https://user-images.githubusercontent.com/29448988/49497381-43768a80-f8a3-11e8-94b0-d1a7476019cb.png)

![default](https://user-images.githubusercontent.com/29448988/49497358-30fc5100-f8a3-11e8-8ca0-35abf477f475.png)

加入后

![default](https://user-images.githubusercontent.com/29448988/49497393-4cfff280-f8a3-11e8-8998-822b4083d8c2.png)

### 报错信息

MySQL server version for the right syntax to use near 'WHERE id=1   AND delete_status=0' at line 1

**Comment by miemieYaho** [comment]
???,有什么问题吗?你想要什么效果?

**Comment by miemieYaho** [comment]
出门右转百度 --> `逻辑删除`

**Comment by jasmine4y** [comment]
> 
> 
> ???,有什么问题吗?你想要什么效果?

我加了这个注解之后更新就报错了，这个是特殊效果吗？

**Comment by jasmine4y** [comment]
> 
> 
> 出门右转百度 --> `逻辑删除`
我知道了，加了这个注解后，更新的时候这个字段被过滤掉了，

**Comment by jasmine4y** [comment]
原来加了这个注解后，deleteById就变成了 逻辑删除
