### ISSUE TITLE
mybatis如何兼容原来的代码升级到mybatis-plus

### ISSUE THREAD

**Issue by xuweiming** [baomidou/mybatis-plus#676]
### 当前使用版本(必须填写清楚，否则不予处理)

springboot + mbatis

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
想改成springboot + mybatis-plus 按照官方给的文档把springboo-mybatis包去掉换成mybatis-plus的，项目跑不起来

### 重现步骤

原来的代码没有继承baseMapper

### 报错信息

要怎么不改原来代码跑起来

**Comment by miemieYaho** [comment]
重现步骤?报错信息?当前使用版本?整理清楚了再提

**Comment by xuweiming** [comment]
mp文档没说清楚怎么兼容升级，把mybatis升级为mp

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples 各种案例

**Comment by xuweiming** [comment]
案例里没有怎么兼容把mybatis原来代码不改升级到mp的

**Comment by qmdx** [comment]
@xuweiming 去掉 mybatis 依赖，直接使用 mp 的然后参考 sample 启动，自动支持以前的逻辑
