### ISSUE TITLE
数据库类型SQL_SERVER缺失，代码逻辑错误

### ISSUE THREAD

**Issue by sirzc** [baomidou/mybatis-plus#677]
### 当前使用版本(必须填写清楚，否则不予处理)
所有版本
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
com.baomidou.mybatisplus.generator.config.DataSourceConfig
switch中不存在SQL_SERVER，逻辑中却有
### 重现步骤
`    public IDbQuery getDbQuery() {
        if (null == dbQuery) {
            switch (getDbType()) {
                case ORACLE:
                    dbQuery = new OracleQuery();
                    break;
                case SQL_SERVER:
                    dbQuery = new SqlServerQuery();
                    break;
                case POSTGRE_SQL:
                    dbQuery = new PostgreSqlQuery();
                    break;
                case DB2:
                    dbQuery = new DB2Query();
                    break;
                case MARIADB:
                    dbQuery = new MariadbQuery();
                    break;
                default:
                    // 默认 MYSQL
                    dbQuery = new MySqlQuery();
                    break;
            }
        }
        return dbQuery;
    }

    /**
     * 判断数据库类型
     *
     * @return 类型枚举值
     */
    public DbType getDbType() {
        if (null == dbType) {
            if (driverName.contains("mysql")) {
                dbType = DbType.MYSQL;
            } else if (driverName.contains("oracle")) {
                dbType = DbType.ORACLE;
            } else if (driverName.contains("postgresql")) {
                dbType = DbType.POSTGRE_SQL;
            } else if (driverName.contains("db2")) {
                dbType = DbType.DB2;
            } else if (driverName.contains("mariadb")) {
                dbType = DbType.MARIADB;
            } else {
                throw ExceptionUtils.mpe("Unknown type of database!");
            }
        }
        return dbType;
    }`

**Comment by mrzero404** [comment]
我也遇到这问题

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`
