### ISSUE TITLE
 Wrapper 自定义SQL的问题

### ISSUE THREAD

**Issue by GitBiao** [baomidou/mybatis-plus#679]
### 当前使用版本(必须填写清楚，否则不予处理)

2.1.8

### 该问题是怎么引起的？

使用 Wrapper 自定义SQL，我看到文档中说3.0.7版本可以使用，3.0.7版本什么时候发布可以使用呢

**Comment by miemieYaho** [comment]
大概1月份,快照版不影响使用的

**Comment by GitBiao** [comment]
好的 期待。。。
