### ISSUE TITLE
selectObjs 提议

### ISSUE THREAD

**Issue by tuxin95** [baomidou/mybatis-plus#680]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

![image](https://user-images.githubusercontent.com/29939855/49635693-8b301a00-fa3b-11e8-9c12-19a21655fdd9.png)

### 重现步骤
注释上面写着只会返回第一个字段的值 结果确实返回所有字段了
![image](https://user-images.githubusercontent.com/29939855/49635756-b9155e80-fa3b-11e8-949a-8cfd7a921244.png)
是我理解错了吗  这个问题也导致 
![image](https://user-images.githubusercontent.com/29939855/49635778-c7637a80-fa3b-11e8-8c86-501ff4c2fc6c.png)
返回NULL

**Comment by Caratacus** [comment]
这个问题会在3.0.7版本得到解决

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`
