### ISSUE TITLE
条件构造器getSqlSelect()一直返回null字符串

### ISSUE THREAD

**Issue by jiangyunjun** [baomidou/mybatis-plus#681]
### 当前使用版本(必须填写清楚，否则不予处理)
SpringBoot:<version>2.1.1.RELEASE</version>
MyBatis-Plus:<version>3.0.6</version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
条件构造器一直返回null字符串，导致查询无结果

### 重现步骤
    @Test
    public void List(){
        QueryWrapper<Account> wrapper = new QueryWrapper<>();
        wrapper.likeLeft("biz","test");
        System.err.println(wrapper.getSqlSelect());
        List<Account> accounts = accountMapper.selectList(wrapper);
    }

    public static void main(String[] args) {
        QueryWrapper<Account> wrapper = new QueryWrapper<>();
        wrapper.likeLeft("biz","test");
        System.err.println(wrapper.getSqlSelect());
    }

### 报错信息
无报错，System.err.println(wrapper.getSqlSelect())打印出来null，将该wrapper添加进selectList中查询结果为null

**Comment by miemieYaho** [comment]
`getSqlSelect ` 不获取查询 sql 的 where 条件的

**Comment by jiangyunjun** [comment]
@miemieYaho 谢谢啦，找到了
