### ISSUE TITLE
想请教下对java8时间格式的支持

### ISSUE THREAD

**Issue by 313715295** [baomidou/mybatis-plus#682]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
看到之前有个issuse答复是支持的，麻烦帮忙看下这个问题，谢谢。
原先项目数据库用的datetime类型，实体是Date类型。
自定义sql，.lt("expire_time", Date.from(today.atStartOfDay(ZoneId.systemDefault()).toInstant()))，这样是没问题的，如果改成LocalDate类型或LocalDateTime，不会抛异常，但是这条时间判断没有生效。

**Comment by miemieYaho** [comment]
数据库是什么类型,就用相应匹配的类型去当入参

**Comment by 313715295** [comment]
数据库类型是datetime只能用Date类型参数是吧，LocalDate/LocalDateTime不支持是mysql的原因吗？~刚转行不太久，基础不太好，谢谢了

**Comment by 313715295** [comment]
> 数据库是什么类型,就用相应匹配的类型去当入参

数据库类型是datetime只能用Date类型参数是吧，LocalDate/LocalDateTime不支持是mysql的原因吗？~刚转行不太久，基础不太好，谢谢了

**Comment by miemieYaho** [comment]
datetime 是 年月日-时分秒的格式的, date 和LocalDateTime都是这种格式,但是LocalDate是年月日的格式

**Comment by 313715295** [comment]
> datetime 是 年月日-时分秒的格式的, date 和LocalDateTime都是这种格式,但是LocalDate是年月日的格式

嗯，但是我试了LocalDateTime格式也无效，只有util.Date类型有效

**Comment by miemieYaho** [comment]
2.x 的不清楚,可能 mybatis 版本有点低? 3.x 上的没问题的

**Comment by 313715295** [comment]
> 2.x 的不清楚,可能 mybatis 版本有点低? 3.x 上的没问题的

好的，十分感谢，可能应该是版本问题，只要新版本没问题就OK，最近应该要弄成新的了
