### ISSUE TITLE
枚举类型字段代码生成问题

### ISSUE THREAD

**Issue by dwjhope** [baomidou/mybatis-plus#683]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
代码生成的entity中的字段可以将typeEnumsPackage的某个枚举类自动生成吗
？

**Comment by miemieYaho** [comment]
不能
