### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by pengtdy** [baomidou/mybatis-plus#688]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
复杂sql执行会出现内存溢出 java.lang.OutOfMemoryError: Java heap space

### 重现步骤
在mapper文件中使用自己在xml中定义的查询时，并且是极其复杂的查询时会出现内存溢出问题，先是卡顿一会，之后报出java.lang.OutOfMemoryError: Java heap space

### 报错信息
java.lang.OutOfMemoryError: Java heap space

**Comment by miemieYaho** [comment]
mp 只负责注入通用 basemapper 的 sql, 其他的不参与,如果使用原始 mybatis 不会溢出的话,你可以写个 demo 分别展示 使用 mp 会溢出而使用原始 mybatis 不会溢出的复现

**Comment by pengtdy** [comment]
我确实遇到了这个问题，在使用mybatis的时候可以正常查询，但是导入了mp后继承了basemapper后，会出现运行缓慢，之后就抛出内存溢出错误，我测试是在一个全新的项目上，没有任何业务代码，只是测试这个问题。

**Comment by miemieYaho** [comment]
内存分配的小了吧, mp 本身也是有不少地方用了缓存的
