### ISSUE TITLE
建议可以支持数据库反向方式操作

### ISSUE THREAD

**Issue by xuyuany2010** [baomidou/mybatis-plus#689]
### 当前使用版本(必须填写清楚，否则不予处理)

最新版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

使用无法满足

### 重现步骤

实体类集成了基础类（比如：创建时间、修改等），被继承的这些类对应的数据库表有些有这些字段，有些没这些字段，不能在基础类中标示忽略吧。

### 建议处理
数据库启动时加载表或视图结构，查询的时候直接select * ，然后根据返回来映射，修改或添加的时候根据加载的数据表结构来构建语句，这样既不用处理忽略字段，也不会没这个字段报错，可以配置一个类型这种支持，不是说要废弃原来的方式，谢谢

**Comment by miemieYaho** [comment]
不支持,你只考虑了 select, 那 insert 呢? 本应该是你的业务设计问题,那就自己解决

**Comment by xuyuany2010** [comment]
insert的我说了啊，项目启动时加载数据库所有的表结构，根据数据库的表结构来构建insert和update语句

**Comment by xuyuany2010** [comment]
不能都去手动注解标记撒，这种方式用起来更简单啊

**Comment by miemieYaho** [comment]
不支持
