### ISSUE TITLE
这里设置了所有的Table Field 都成为了 IdField

### ISSUE THREAD

**Issue by wuma** [baomidou/mybatis-plus#69]
![image](https://user-images.githubusercontent.com/8328911/27017860-4277b248-4f5e-11e7-8daa-5934d1f57bc6.png)

个人感觉，这个地方，会让Model的所有 Field 都成为 TableId，并且无法获取到类型，导致设置TableInfo的idType = GlobalConfig

**Comment by qmdx** [comment]
已经优化
