### ISSUE TITLE
AbstractMethod.extractModelClass是否考虑增加缓存

### ISSUE THREAD

**Issue by ly641921791** [baomidou/mybatis-plus#692]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.5

### 该问题是怎么引起的？

我发现BaseMapper中的每个方法都会通过AbstractMethod.extractModelClass获取一次泛型，例如：`UserMapper extends BaseMapper<User>`中的每个方法，都会重复通过该方法使用反射获取泛型`User.class`。

在看Spring源码时，发现Spring中会通过Map缓存一些反射的解析结果，来提高初始化效率，不知本项目是否有该打算？

**Comment by miemieYaho** [comment]
感谢,这个不需要进行缓存,因为只有启动时注入 sql 用得到,不过还是可以优化一下提高启动速度,现已在 gitee 上修改.

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`
