### ISSUE TITLE
参数同时使用page和Map，会报错

### ISSUE THREAD

**Issue by ychange2012** [baomidou/mybatis-plus#695]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter3.0.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
interface 里面，参数同时使用page和Map,会报ibatis.binding.BindingException。如果单独参数@Param是没问题的。
以前旧版本是没问题的。

**Comment by miemieYaho** [comment]
就这样的

**Comment by ychange2012** [comment]
以前旧版本不会的。

**Comment by miemieYaho** [comment]
不一样了

**Comment by ychange2012** [comment]
有其他解决方法吗？有时需要map做参数。

**Comment by miemieYaho** [comment]
没有
