### ISSUE TITLE
多次对同一QueryWrapper对象使用JSON.toJSONString，所得字符串不一样

### ISSUE THREAD

**Issue by yoanliang** [baomidou/mybatis-plus#696]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
多次对同一个QueryWrapper进行json字符串化，得到的字符串数据不一样

### 重现步骤
QueryWrapper<String> query = new QueryWrapper<String>().eq("id", 1)
String json1 = JSON.toJSONString(query);
String json2 = JSON.toJSONString(query);
json1.equals(json2)  // false

初步了解到是json字符串化过程中调用了getSqlSegment方法，这个方法使同一个对象的paramNameSeq发生了递增

**Comment by miemieYaho** [comment]
wrapper不应该用来json化
