### ISSUE TITLE
Oracle是否支持批量增删改？

### ISSUE THREAD

**Issue by myxland** [baomidou/mybatis-plus#698]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
Oracle数据库，执行批量插入

### 重现步骤
打印语句，发现不是批量插入的，而是逐条插入的

### 报错信息
无

**Comment by miemieYaho** [comment]
建议你去看源码

**Comment by myxland** [comment]
源码上写的不支持oracle…哎哎，就是想确认下呢~
