### ISSUE TITLE
能不能连表查询，或者自定义sql

### ISSUE THREAD

**Issue by qq12352100** [baomidou/mybatis-plus#7]

**Comment by yangyang0507** [comment]
非常遗憾的告诉你，目前MP还不能支持连表查询，不过我们正在进行讨论，连表查询功能将会在以后进行提供。届时，还有更加牛逼的功能，具体可以参考我们的dev-2.0分支。

如果需要进行多表操作，建议你现在先像传统Mybatis用法一样写。
