### ISSUE TITLE
代码生成自定义实体名称强制修改了xml名称

### ISSUE THREAD

**Issue by geekscloud** [baomidou/mybatis-plus#701]
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
3.0.6

### 重现步骤
代码生功能设置自定义entityName 后回强制给 xml的名字也加上自定义后缀(手动设置setXmlName(null) 也无效)
如:
全局策略 globalConfig 配置
globalConfig.setEntityName("%sEntity");
执行之后
 生成 UserEntity.java
 生成 UserEntityMapper.xml
 生成 UserMapper.java

**Comment by geekscloud** [comment]
setXmlName（'%sMapper'） 也不行

**Comment by qmdx** [comment]
经过排查不存在该问题，你应该是抄了  https://mp.baomidou.com/guide/generator.html 的 xml 自定义路径，然后设置了后缀当然 getEntityName 发生了变化你需要替换回来。

如下
```java
focList.add(new FileOutConfig("/templates/mapper.xml.ftl") {
            @Override
            public String outputFile(TableInfo tableInfo) {
                // 自定义输入文件名称
                return projectPath + "/service-system/src/main/resources/mapper/" + pc.getModuleName()
                        + "/" + tableInfo.getEntityName().replace("后缀", "") + "Mapper" + StringPool.DOT_XML;
            }
        });
```
