### ISSUE TITLE
使用updateById 更新实体类中某一个字段

### ISSUE THREAD

**Issue by yang3350380** [baomidou/mybatis-plus#702]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
使用updateById 更新实体类中某一个字段

### 报错信息
会把除了要更新的字段以外其他字段全部更为null

设置了 field-strategy: 2

**Comment by miemieYaho** [comment]
3.x 版本上没有 2,自己检查自己的配置

**Comment by yang3350380** [comment]
> 3.x 版本上没有 2,自己检查自己的配置

那我用3.x这问题怎么解决?

**Comment by jiangbin-github** [comment]
使用update和updateById方式，不能将字段更新为null。但实际业务场景中有时候会用将某个字段更新为null。

**Comment by miemieYaho** [comment]
> 使用update和updateById方式，不能将字段更新为null。但实际业务场景中有时候会用将某个字段更新为null。

文档看了吗?张口就来说不能?

**Comment by miemieYaho** [comment]
> > > 使用update和updateById方式，不能将字段更新为null。但实际业务场景中有时候会用将某个字段更新为null。
> > 
> > 
> > 文档看了吗?张口就来说不能?
> 
> 我是的意思是不能使用updateById 来更新字段为null，太不方便。得使用UpdateWrapper方式。

注解 `TableField`的`strategy` 属性了解一下

**Comment by jiangbin-github** [comment]
> > > > 使用update和updateById方式，不能将字段更新为null。但实际业务场景中有时候会用将某个字段更新为null。
> > > 
> > > 
> > > 文档看了吗?张口就来说不能?
> > 
> > 
> > 我是的意思是不能使用updateById 来更新字段为null，太不方便。得使用UpdateWrapper方式。
> 
> 注解 `TableField`的`strategy` 属性了解一下
多谢！
