### ISSUE TITLE
如果不配置mybatis-config.xml文件，就无法使用IdType的功能，这是bug吗？

### ISSUE THREAD

**Issue by shenbinglife** [baomidou/mybatis-plus#71]
使用mybatis plus2.0.8， spring 4.3.8， mysql。
使用过程中发现IdType=3不起作用，不论是在spring xml中使用globalConfig还是用@TableId注解，都不能自动生成UUID。

网络上找不到任何解释，后来发现在spring的MybatisSqlSessionFactoryBean中配置了configLocation指向一个不存在任何配置的mybatis-config.xml后，IdType才起作用了。这是bug吗？

**Comment by Caratacus** [comment]
无图无真相

**Comment by shenbinglife** [comment]
配置configLocation前：
异常：
![image](https://user-images.githubusercontent.com/16119667/27210729-0cbea086-5287-11e7-80ba-2e97ad1d9690.png)
配置：
![image](https://user-images.githubusercontent.com/16119667/27210752-41b9ad62-5287-11e7-9b0f-cb0f3fb496ac.png)

配置后，将spring中的cofigLocation的注释取消后，加载内容为空的mybaits-config.xml如下图。然后插入数据成功了：
![image](https://user-images.githubusercontent.com/16119667/27210807-8e4a2904-5287-11e7-88a4-bb532412f571.png)

Controller：

![image](https://user-images.githubusercontent.com/16119667/27210901-4c1e46a4-5288-11e7-90a7-765581dba2cc.png)

**Comment by shenbinglife** [comment]
图片来了，答案在哪？

**Comment by qmdx** [comment]
@shenbinglife   com.baomidou.mybatisplus.MybatisDefaultParameterHandler 方法 populateKeys 是否支持。 图来看没啥问题。如果未解决加入我们群。

**Comment by Caratacus** [comment]
2.0.9新版本解决
