### ISSUE TITLE
逻辑删除疑问请教

### ISSUE THREAD

**Issue by sz-sunset** [baomidou/mybatis-plus#713]
### 当前使用版本(必须填写清楚，否则不予处理)
3.06

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
逻辑删除 logic-not-delete-value 参数能否支持多个

或则

带有逻辑删除对象 生成查询语句是支持 
isDel != logic-delete-value
而不是固定的  isDel =  logic-not-delete-value

**Comment by miemieYaho** [comment]
不支持
