### ISSUE TITLE
批量插入方法：saveOrUpdateBatch有些问题，两个主键以上，只根据一个主键进行处理

### ISSUE THREAD

**Issue by surersen** [baomidou/mybatis-plus#714]
### 当前使用版本(必须填写清楚，否则不予处理)

当前版本 v3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

利用 saveOrUpdateBatch方法保存或更新时，只根据了一个主键orderid作为条件，更新了。把原来数据冲掉了。

### 报错信息

Model 3个主键，利用 saveOrUpdateBatch方法保存或更新时，只根据了一个主键orderid作为条件，更新了

![image](https://user-images.githubusercontent.com/12604070/50208520-5497bf00-03ac-11e9-89be-41d624d39d61.png)

mybatis执行日志如下：

![image](https://user-images.githubusercontent.com/12604070/50208720-eacbe500-03ac-11e9-8ef1-acf1cae32457.png)

**Comment by miemieYaho** [comment]
不支持多主键

**Comment by surersen** [comment]
@miemieYaho 
目前有支持多主键的预定吗

**Comment by miemieYaho** [comment]
没有

**Comment by surersen** [comment]
@miemieYaho 
设计的表有一部分是两个以上的主键，请指教下除了自增id当主键，还有其他方案不？

**Comment by miemieYaho** [comment]
mp 自带的 idwork

**Comment by surersen** [comment]
谢谢了
