### ISSUE TITLE
MetaObjectHandler 接口自定义实现后， 调用插入时不会将填充字段数据插入数据库表。

### ISSUE THREAD

**Issue by newheart** [baomidou/mybatis-plus#717]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.0.6</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
自定义MyMetaObjectHandler implements MetaObjectHandler，插入时实体对象字段确实调用insertFill自动填充了，但是数据库对应字段没有落入填充的数据。复现步骤如下图：

### 重现步骤
![image](https://user-images.githubusercontent.com/10294610/50261243-a9881380-0446-11e9-9335-b761d930d453.png)

![image](https://user-images.githubusercontent.com/10294610/50261324-0a175080-0447-11e9-84cb-ad8970019f01.png)

![image](https://user-images.githubusercontent.com/10294610/50261296-ef44dc00-0446-11e9-80ae-77ec284b0acd.png)

**Comment by miemieYaho** [comment]
字段注解,看文档

**Comment by newheart** [comment]
https://mp.baomidou.com/guide/ 官方指南没有找到 关于这个注释的说明文档，能给个文档链接么？

**Comment by newheart** [comment]
> 字段注解,看文档
官方指南没看到 关于这个注释的说明文档，能给个文档链接么？

**Comment by miemieYaho** [comment]
怎么就没有了.你发的连接上没有?你再好好看看
