### ISSUE TITLE
关于后端循环打印分页数据问题一直只出现第一页的数据

### ISSUE THREAD

**Issue by cqyhm** [baomidou/mybatis-plus#718]
### 当前使用版本(必须填写清楚，否则不予处理)
目前使用<version>3.0.6</version>，mysql5.7.23
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
分页查询在循环分页的时候
### 重现步骤
              Long pageSize=50L;
		for(Long current=1L; current <=2;current++) {
			IPage<User> pager=userService.page(new Page<User>(current, pageSize));
			log.info("current={},size={}",current,pager.getSize());
			List<User> users=pager.getRecords();
			for (User user : users) {
				log.info("{}",user.getId());
				break;
			}
		}
我确保表中有2行以上的数据。通过程序循环执行，每次获得一页的数据。照理来讲日志应该打印出
不同的Id的。但是我发现一直显示的都是第一个页的数据。特奇怪。
开始还以为我自己搞错了，但是通过同样的写法，用浏览器传递当前页号，就可以查询得到当前
的某一页。通过后端循环就是得不到结果，我还尝试关闭缓存，依然如故。奇怪了。

**Comment by miemieYaho** [comment]
为什么这种问题还要来提 issue?难道我们还能在代码里下毒?你的 pageSize 写个 50 算几个意思?

**Comment by cqyhm** [comment]
不过通过网页前端,每次传递当前页作为参数就能正常分页,这样看起来又不像是缓存的问题.

**Comment by cqyhm** [comment]
实验了下关闭缓存什么的,这个问题还是存在的.
mybatis-plus.configuration.cache-enabled=false
等晚上在看看看这个的工作原理.

**Comment by cqyhm** [comment]
有点需要注意的就是,我在单元测试类上增加了事务的注解标志@Transactional.
后来在朋友的提示下,把这个去掉了.然后在执行单元测试尽然发现查询结果正常了.
只是原因还有待分析,应该是和事务有关.
