### ISSUE TITLE
map 转驼峰无效

### ISSUE THREAD

**Issue by slyang520** [baomidou/mybatis-plus#719]
### 当前使用版本(必须填写清楚，否则不予处理)
compile("com.baomidou:mybatis-plus-boot-starter:3.0.6")
数据库mysql 5.6
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
map 下划线转驼峰无效
mybatis-plus.configuration.map-underscore-to-camel-case=true
### 重现步骤
case 1.0
<select id="seletMapTest" resultType="java.util.Map">
        select 1 as test_type
 </select>
  Map<String, Object> test2 = mapper.seletMapTest();
{
"test_type":1
}
case 2.0
 List<Map<String, Object>> object = SqlRunner.DEFAULT.selectList("select 1 as test_type");
[
{
"test_type":1
}
]

**Comment by miemieYaho** [comment]
mybais 没学好吧

**Comment by miemieYaho** [comment]
这是mybatis原生属性
