### ISSUE TITLE
通用查询我可以返回跟表实体不一样的对象吗？

### ISSUE THREAD

**Issue by bufoon** [baomidou/mybatis-plus#721]
### 当前使用版本(必须填写清楚，否则不予处理)

2.0版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

无

### 重现步骤

无

### 报错信息
无

就是比如我很多查询出来的对象是实体对象，但是我提供出去往往会转换成VO对象给接口返回，所以又没查询方法，类似自己写mybatis的时候，自己可以指定resultType，可以返回指定的对象而不是统一返回表实体对象，虽然通用方法里面有Map类型的，但是还是想问下能不能自己指定对象

**Comment by qmdx** [comment]
vo 你需要 xml 里面返回操作
