### ISSUE TITLE
建议增加使用wrapper求某一列的和

### ISSUE THREAD

**Issue by detectiveHLH** [baomidou/mybatis-plus#723]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-boot-starter</artifactId>
        <version>3.0.6</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
无法使用wrapper对某一列进行求和

### 重现步骤
无

### 报错信息
无

**Comment by miemieYaho** [comment]
熟读文档,灵活使用
