### ISSUE TITLE
连续分页不生效

### ISSUE THREAD

**Issue by Andyfan322** [baomidou/mybatis-plus#725]
### 当前使用版本(必须填写清楚，否则不予处理)
         <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
        </dependency>
### 重现步骤

            IPage<UserInitShip> first=   new Page<>(i + 1, pageSize);
             first = userInitShipMapper.selectPage(first, queryWrapper);
            IPage<UserInitShip> second=   new Page<>(i + 2, pageSize);
            second = userInitShipMapper.selectPage(second, queryWrapper);

### 报错信息
  second = userInitShipMapper.selectPage(second, queryWrapper); 语句的sql没执行，也没打印出sql，total=0，项目里没PageHelper。

**Comment by miemieYaho** [comment]
1.  mybatis 一级缓存的问题  
2. 你这种测试毫无意义

**Comment by Andyfan322** [comment]
错了，是@Transactional 问题，加了事务，只会执行一条。

**Comment by keepsilenc** [comment]
原因就是分页参数即便不一致,还是触发了缓存 .  在执行语句后面加 1=1 ,2=2 的便可以解决
