### ISSUE TITLE
分页排序使用一个字段接收排序值

### ISSUE THREAD

**Issue by Hanson1330** [baomidou/mybatis-plus#729]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 问题

1. 为什么使用两个字段来接收排序参数

2.为什么不支持先降序后升序这种很常见的使用场景

**Comment by qmdx** [comment]
Page 分页部分排序源码如下，如果需要更灵活在 Wrapper 中排序
`/**
     * <p>
     * 升序
     * </p>
     *
     * @param ascs 多个升序字段
     */
    public Page<T> setAsc(String... ascs) {
        this.ascs = ascs;
        return this;
    }

    @Override
    public String[] descs() {
        return descs;
    }

    public Page<T> setDescs(List<String> descs) {
        if (CollectionUtils.isNotEmpty(descs)) {
            this.descs = descs.toArray(new String[0]);
        }
        return this;
    }

    /**
     * <p>
     * 降序
     * </p>
     *
     * @param descs 多个降序字段
     */
    public Page<T> setDesc(String... descs) {
        this.descs = descs;
        return this;
    }`
