### ISSUE TITLE
sharding-sphere+postgresql分页查询总记录数报错

### ISSUE THREAD

**Issue by zhiduochang** [baomidou/mybatis-plus#731]
### 当前使用版本(必须填写清楚，否则不予处理)

经测试，版本：3.0.0.M1、3.0.0.M2、3.0.0.M3、3.0.0.M4、3.0.0、3.1.0.M1都存在该问题

### 报错信息
Can't find index: AggregationSelectItem(type=COUNT, innerExpression=(1), alias=Optional.absent(), derivedAggregationSelectItems=[], index=-1), please add alias for aggregate selections

**Comment by miemieYaho** [comment]
那是他的问题,你找错地了
