### ISSUE TITLE
执行单元测试事务不回滚

### ISSUE THREAD

**Issue by zhenyuT** [baomidou/mybatis-plus#732]
### 当前使用版本(必须填写清楚，否则不予处理)
版本:3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

继承IService接口，调用saveBatch方法。

单元测试，加了@transactional @Rollback注解，直接在当前xxxTest类中执行，事务可以回滚；通过mvn test命令执行(一共90个单元测试)，某些测试方法的事务不回滚，数据直接插入到数据库了。

将com.baomidou.mybatisplus.extension.service.impl.ServiceImpl类的sqlSessionBatch方法 :
```
    /**
     * <p>
     * 批量操作 SqlSession
     * </p>
     */
    protected SqlSession sqlSessionBatch() {
        return SqlHelper.sqlSessionBatch(currentModelClass());
    }
```
修改为：

```
    @Autowired
    @Qualifier("customSqlSessionFactory")
    SqlSessionFactory sqlSessionFactory;

    /**
     * <p>
     * 批量操作 SqlSession
     * </p>
     */
    protected SqlSession sqlSessionBatch() {
        return sqlSessionFactory.openSession(ExecutorType.BATCH);
    }
```

直接通过注解注入SqlSessionFactory后，这个问题得到解决。

但是我们的项目中是用到了多数据源的，这种方式虽然能解决问题，但是个人并不是很喜欢。
还有通过SqlHelper.sqlSessionBatch(currentModelClass())的方式获取SqlSession的做法，是什么原因导致出的问题呢？？？

### 重现步骤

继承IService接口调用saveBatch方法，通过mvn test命令执行单元测试。

### 报错信息

事务不回滚

**Comment by zhenyuT** [comment]
测试发现，是由于SqlSessionFactory被重新创建了导致的，而SqlHelper.sqlSessionBatch(currentModelClass())方法获取的SqlSessionFactory对象还是之前的旧对象(如上图)。

产生这种情况的原因可能是单测中使用了Mockito进行对象的mock。前面执行正常的测试类都是有使用@MockBean注解进行对象mock的，而第一个出问题的测试类是没有使用mock的。在这个有问题的测试类里面也加上mock后，这个类也变得正常了。

有没有对这块比较了解的，给讲解一下原理，感激不尽！

![Uploading code.png…]()

**Comment by zhenyuT** [comment]
<img width="523" alt="code" src="https://user-images.githubusercontent.com/9477681/50418958-38db5f80-0869-11e9-9b63-0aacc0ba1d8f.png">

能否对这里的代码进行优化呢，感觉这里获取SqlSessionFactory的方式存在这风险啊

**Comment by zhenyuT** [comment]
> 没什么风险,本身就不推荐以及不支持创建多个sqlsessionfactory公用相同的mapper.

我这边没有SqlSessionFactory公用相同的mapper的情况哦，虽然有多个SqlSessionFactory，但是每个mapper对应的SqlSessionFactory都是固定的。

之所以出现事务不回滚的原因，是因为SqlSessionFactory对象被重新创建了(原因未知)，而model缓存的SqlSessionFactory还是旧的。

对于Spring+Junit+Mockito的实现原理不是很清楚，但是看日志发现Spring boot和mybatis-plus的启动logo有被重复打印的，这是否说明整个Spring容器都被重新创建了？

**Comment by miemieYaho** [comment]
你觉得上线正常使用还会被重新创建吗?

**Comment by zhenyuT** [comment]
> 你觉得上线正常使用还会被重新创建吗?

应该不会！

不过影响我跑单测，事务不回滚，每次数据都会插入到数据库。。。

**Comment by miemieYaho** [comment]
那就不关我们的事了

**Comment by zhenyuT** [comment]
> 那就不关我们的事了

单测也是项目中很重要的一环啊 😢 😢
我们每次部署都会自动跑一遍单测，对于事务不回滚的情况基本是不能忍受的 

虽然这个问题目前看起来不会影响线上的使用，但是说实话，我心里还是觉得有点没底。就算有问题，也只有在程序执行异常且事务没回滚才能发现，很难被测试出来。

我觉得作为一款优秀的框架，应该是让人可以很放心的去使用，不应该存在这种问题隐患的。

**Comment by miemieYaho** [comment]
这种你们自己使用不当造成的问题,就不要找我们背锅了.

**Comment by zhenyuT** [comment]
按您的意思，一个项目里面访问多个数据库的情况，就是不正常需求了么？

如果是我们使用不当，也劳烦您指出是哪里不当，我们应该如何改正！

**Comment by miemieYaho** [comment]
你的理解太片面,那你告诉我如果注入多个 sqlsessionfactory 并且扫描的 mapper 不重复那这个 sqlsessionfactory 应该放哪?你跑个 junit 程序被打乱了不是正常流程还怪别人?

**Comment by zhenyuT** [comment]
> 你的理解太片面,那你告诉我如果注入多个 sqlsessionfactory 并且扫描的 mapper 不重复那这个 sqlsessionfactory 应该放哪?你跑个 junit 程序被打乱了不是正常流程还怪别人?

我觉得如果不直接缓存SqlSessionFactory对象实例，而是缓存SqlSessionFactory的Bean名称，应该是可以解决我的问题的。因为即时容器重新创建了，但是Bean名称是不会变的。

对于junit的使用，我这两天也有在看官方的使用教程，也未发现是哪里使用不规范。如果您觉得是我使用的问题，麻烦能否指出可能是哪里的使用方式不对？

我这里更多的是把您当前辈请教，并没有责怪的意思。
希望您能解答我的疑惑，谢谢！

**Comment by miemieYaho** [comment]
没必要,tableinfohelper 里现在已经改成新的顶掉旧的缓存的 Configuration
