### ISSUE TITLE
查询语句小建议

### ISSUE THREAD

**Issue by yang3350380** [baomidou/mybatis-plus#733]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

所有使用queryWrapper查询方法

### 重现步骤

能否添加一个配置开关，让查询时的字段全部自动加反引号？目前使用ali的数据库自定义关键字非常多，原有项目一旦ali数据库引擎升级就会报错  例如：select `state`，`level` from xxxx

**Comment by miemieYaho** [comment]
这属于你们业务上的问题 wrapper 全是 new 出来的不存在开关
