### ISSUE TITLE
插入时自增主键没有使用MapperXXX.xml配置的策略

### ISSUE THREAD

**Issue by mashuangwei** [baomidou/mybatis-plus#735]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6版本，使用的是mysql数据库

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
自己额外定义了两个方法，然后新增了一个UserMapper.xml配置文件
public interface UserMapper extends BaseMapper<User> {
    User findByUserName(String userName);
    int addUser(User user);
}

xml配置文件内容：
 <insert id="addUser" parameterType="com.msw.devops.entity.User" useGeneratedKeys="true" keyProperty="id">
    insert into tb_user (id, username, `password`,
      create_time, `status`)
    values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR},
      #{createTime,jdbcType=DATE}, #{status,jdbcType=VARCHAR})
  </insert>

### 重现步骤
调用addUser方法时报错，本来我主键id设置类型为int类型，导致mybatisplus生成的主键值过大，类型不匹配了。我很好奇的是为什么不会按照我xml的配置文件进行主键自增呢。备注：即使我使用mybatisplus自己的insert方法也会有这个问题。

### 报错信息
{
    "code": 500,
    "message": "nested exception is org.apache.ibatis.reflection.ReflectionException: Could not set property 'id' of 'class com.msw.devops.entity.User' with value '1077492768484741121' Cause: java.lang.IllegalArgumentException: argument type mismatch",
    "date": "2018-12-25 17:14:29",
    "data": null
}

**Comment by miemieYaho** [comment]
这种情况自己用注解指定主键类型,再自己 set 值

**Comment by miemieYaho** [comment]
没意义,框架提供了你还再来一个没必要吧  
而且你说你要自增,但xml里还取id值?自增的sql是不包含id的
