### ISSUE TITLE
文档注释多行时，行应以 <br> 结尾

### ISSUE THREAD

**Issue by Cat7373** [baomidou/mybatis-plus#741]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
Javadoc 实际上是 html 代码，也就是说多行的内容其实在 html 渲染出来后会变成一行。。

而 html 多行的方法 emmm

我比较习惯在结尾加`<br>`，当然也可以用`<p>`包裹内容

### 重现步骤
随便找一个有多行注释的接口，在 IDEA 中按下查看文档的热键，或生成 javadoc 后查看，下面是在 IDEA 中查看的效果：

![](https://user-images.githubusercontent.com/9296576/50440160-dc8f4300-092f-11e9-8638-ff56c064dd83.png)

增加`<br>`后的效果

![](https://user-images.githubusercontent.com/9296576/50440179-f466c700-092f-11e9-936f-2313ad6182a4.png)

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/commit/0851c2f90fce6195035d32794da75ae951665c73
