### ISSUE TITLE
AbstractLambdaWrapper报错cannot find column's cache for %s, so you cannot used %s 版本：3.0.6

### ISSUE THREAD

**Issue by pengdezhi** [baomidou/mybatis-plus#745]
### 当前使用版本(必须填写清楚，否则不予处理)
版本为V3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
项目启动后，在项目用有使用Wrappers.query().lambda()进行条件查询，同一份代码，在某些机器上运行正常，某些机器上就会在 AbstractLambdaWrapper 类里面的59行， if (!initColumnMap || !columnMap.containsKey(fieldName)) {
            String entityClassName = lambda.getImplClassName();
            columnMap = LambdaUtils.getColumnMap(entityClassName);
            Assert.notEmpty(columnMap, "cannot find column's cache for %s, so you cannot used %s!",
                entityClassName, typedThis.getClass());
            initColumnMap = true;
        }
抛出这里的异常，代码跟踪后发现，此处的entityClassName 不是entity,而是一部分变成了service实现类，或者controller。所以就一定为空。

### 重现步骤
项目使用Wrappers.query().lambda()方法进行条件查询

### 报错信息
cannot find column's cache for SysUserServiceImpl, so you cannot used baomidou  AbstractWrapper lambda

**Comment by miemieYaho** [comment]
请勿使用 eclipse 的 compiler

**Comment by yzli840324** [comment]
这个问题在V3.0.7.1版本还是有问题，请问要怎么避免？
