### ISSUE TITLE
spring boot打包成jar，通用枚举类无法注入到实体类中

### ISSUE THREAD

**Issue by zeemood** [baomidou/mybatis-plus#747]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

在spring boot+mysql 5.5的架构下，idea启动没有问题，使用maven打包jar后，运行jar，查询的结果无法无法注入到实体类的枚举类字段中

### 重现步骤

实现IEnum<Integer>接口的枚举类，定义成实体类中的状态字段，jar包启动报错，IDE中不报错

### 报错信息
无报错信息，数据无法注入到实体类中

**Comment by miemieYaho** [comment]
有使用 spring-dev-tools?

**Comment by zeemood** [comment]
> 有使用 spring-dev-tools?

是的，会有冲突吗？而且枚举类字段存到数据库里的时候必须是字符串，也就是枚举类的name()，而不是IEnum的getValue()，所以我使用了varchar作为状态或着类型字段的数据类型，也是因为dev tools吗？用jrebel会不会？热启动太重要了

**Comment by miemieYaho** [comment]
配置dev-tools不要扫描枚举包,通用枚举参考文档
