### ISSUE TITLE
生成代码，关于字段首字母大写

### ISSUE THREAD

**Issue by christding** [baomidou/mybatis-plus#751]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
数据库表字段首字母是大写 类似 AccountName ，生成代码中字段 为 AccountName；期望为  accountName

**Comment by qmdx** [comment]
你这个命名不符合大众啊，你可能需要自己适配下生成器了。默认不会支持这种需求的
