### ISSUE TITLE
当field-strategy: ignored时 UpdateWrapper 根据条件更新 把所有满足条件的数据更新成一样的

### ISSUE THREAD

**Issue by li86569917** [baomidou/mybatis-plus#752]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.1

### 重现步骤

配置：field-strategy: ignored

UpdateWrapper<T> tQueryWrapper = new UpdateWrapper<>();
tQueryWrapper .eq("name","1");
tQueryWrapper .set("sex","1");
tService.update(new T(),tQueryWrapper );
//tService.update(null,tQueryWrapper );  这样会直接报错 org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'et.createUserId != null'. Cause: org.apache.ibatis.ognl.OgnlException: source is null for getProperty(null, "createUserId")
### 报错信息
执行后，生成语句为 表T的全字段  = null ,sex = '1' where name = '1'; 

希望可以增加  update(UpdateWrapper<T> UpdateWrapper);
可以只根据UpdateWrapper更新数据

**Comment by miemieYaho** [comment]
下个版本update 的第一个入参 entity 可以不传了,大概1.1发布

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`
