### ISSUE TITLE
queryWrapper 查询的字段值为 curdate( ) 不支持吗？在Navicat查询是能查的

### ISSUE THREAD

**Issue by Nonull7** [baomidou/mybatis-plus#753]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
mysql 函数curdate( )返回当前日期

### 重现步骤
map.put("user_id",userId);
map.put("today_date","curdate()");
 queryWrapper.allEq(map,true);
signinMapper.selectOne(queryWrapper);
### 报错信息
==>  Preparing: SELECT signin_id,user_id,today_date,start_work,off_work,date_type,over_time,late_time,leave_time,start_address,end_address,work_time FROM signin WHERE user_id = ? AND today_date = ? 
==> Parameters: 2(Integer), curdate()(String)
<==      Total: 0

**Comment by miemieYaho** [comment]
apply("today_date = curdate()")
