### ISSUE TITLE
create procedure以及create function等ddl操作失败

### ISSUE THREAD

**Issue by xieex** [baomidou/mybatis-plus#754]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

通过mybaits-plus来执行create function的ddl操作失败，之前使用2.3版本一切正常，升级到3.0.6版本出现问题。

### 重现步骤
在对应的mapper.xml中增加：
<update id="ExecuteDDL">
       ${ddlsql}
</update>
调用ExecuteDDL出错。
能够保证create function的ddl语句语法正确：
CREATE FUNCTION func_stuff(
 f_old VARCHAR(1000),f_start INT,f_length INT,f_replace VARCHAR(1000)
)
RETURNS VARCHAR(2000)
BEGIN
  RETURN CONCAT(SUBSTRING(f_old,0,f_start) , f_replace,SUBSTRING(f_old,f_start+f_length));
END

### 报错信息
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
 ### Error updating database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId. Error SQL: CREATE FUNCTION func_stuff( f_old VARCHAR(1000),f_start INT,f_length INT,f_replace VARCHAR(1000) ) RETURNS VARCHAR(2000) BEGIN RETURN CONCAT(SUBSTRING(f_old,0,f_start) , f_replace,SUBSTRING(f_old,f_start+f_length)); END
 ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId. Error SQL: CREATE FUNCTION func_stuff( f_old VARCHAR(1000),f_start INT,f_length INT,f_replace VARCHAR(1000) ) RETURNS VARCHAR(2000) BEGIN RETURN CONCAT(SUBSTRING(f_old,0,f_start) , f_replace,SUBSTRING(f_old,f_start+f_length)); END

**Comment by yuxiaobin** [comment]
java调用方法怎么写的？

**Comment by xieex** [comment]
问题解决了，是由于加上了TenantSqlParser导致的，结论是版本没问题，谢谢！
