### ISSUE TITLE
Oracle中，如何写查询时间范围语句

### ISSUE THREAD

**Issue by abcbuzhiming** [baomidou/mybatis-plus#755]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
Oracle 11G中，字段设置为timestamp，此时，传入的字符串时间必须使用Oracle的to_date函数进行格式化才能进行查询，查询语句如下
`SELECT * FROM PROJ_TEACH_RESEARCH_SETUP WHERE PROJ_CREATE_TIME  >= TO_DATE('2018-12-26 15:03:33','yyyy-MM-dd HH24:MI:SS')`

### 重现步骤
尝试使用Mybatis-plus的QueryWrapper进行条件查询
`projTeachResearchSetupMapper
				.selectList(new QueryWrapper<ProjTeachResearchSetup>().apply("PROJ_CREATE_TIME = TO_DATE('{0}','yyyy-MM-dd HH24:MI:SS')", "2018-12-26 15:03:33"));`

### 报错信息
Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL3', 
mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}.
 Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType null . 
 Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: 
 Error setting non null for parameter #1 with JdbcType null .
 Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: 无效的列索引

### 补充
这里的关键是我用的参数绑定的写法，如果我放弃参数绑定的写法，直接传入sql，查询能通过。如果想用参数绑定的方式，这里就会这样

**Comment by yuxiaobin** [comment]
建议使用Date对象当参数，不要使用特定的函数
```
projTeachResearchSetupMapper .selectList(new QueryWrapper<ProjTeachResearchSetup>().eq("PROJ_CREATE_TIME", DateUtils.parseDate("2018-12-26 15:03:33","yyyy-MM-dd HH:mm:ss"));
```

**Comment by abcbuzhiming** [comment]
> 建议使用Date对象当参数，不要使用特定的函数
> 
> ```
> projTeachResearchSetupMapper .selectList(new QueryWrapper<ProjTeachResearchSetup>().eq("PROJ_CREATE_TIME", DateUtils.parseDate("2018-12-26 15:03:33","yyyy-MM-dd HH:mm:ss"));
> ```

确认有效，谢谢，请关闭问题
