### ISSUE TITLE
代码生成工具tableInfo里面包引入写错

### ISSUE THREAD

**Issue by mrvon2015** [baomidou/mybatis-plus#757]
版本为：3.0.6
![image](https://user-images.githubusercontent.com/11691591/50532496-f3fb4580-0b54-11e9-9a07-cf7cc861a7c7.png)
应该是annotation 不应该是 annotations

**Comment by mrvon2015** [comment]
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-generate</artifactId>
    <version>2.3.3</version>
</dependency>
是这个版本的工具

**Comment by miemieYaho** [comment]
3.x 和 2.x 包名不一样
