### ISSUE TITLE
select() 无法查出 使用了@TableField注解的字段值

### ISSUE THREAD

**Issue by LuckyTerry** [baomidou/mybatis-plus#758]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

QueryWrapper#select(), LamdaQueryWrapper#select() 无法查出 使用了@TableField注解的字段值

### 重现步骤

查询语句
getOne(new LambdaQueryWrapper<PrintRecordDO>().select(PrintRecordDO::getInvoiceType))

PrintRecordDO定义
@TableField("type_code")
private String invoiceType;

**Comment by miemieYaho** [comment]
注解和获取返回值无关,数据封装走的原生 mybatis

**Comment by LuckyTerry** [comment]
ReslutMap映射不根据TableField注解定义吗？
columnSql里面都是正确的column，映射成结果就少了TableField注解的字段值。

**Comment by LuckyTerry** [comment]
> 注解和获取返回值无关,数据封装走的原生 mybatis

ReslutMap映射不根据TableField注解定义吗？
columnSql里面都是正确的column，映射成结果就少了TableField注解的字段值。

**Comment by miemieYaho** [comment]
不根据

**Comment by LuckyTerry** [comment]
那么这个tableField在insert时生效，resultMap时不生效，那么理论上就是查不出来罗？

**Comment by LuckyTerry** [comment]
> 不根据

那么这个tableField在insert时生效，resultMap时不生效，那么理论上就是查不出来罗？

**Comment by miemieYaho** [comment]
resultMap 是你自己写的,那叫 resultType,要查出来就自己 as 一下

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`
