### ISSUE TITLE
导入此包就报错

### ISSUE THREAD

**Issue by songjunyan** [baomidou/mybatis-plus#759]
### 当前使用版本(必须填写清楚，否则不予处理)
compile group: 'com.baomidou', name: 'mybatis-plus-boot-starter', version: '3.0.6'

### 重现步骤

 倒入此包 编译就报错

### 报错信息
![image](https://user-images.githubusercontent.com/7437521/50535413-a72f6300-0b84-11e9-9993-c388e25d59d9.png)

org.springframework.boot.autoconfigure.jdbc.DataSourceBuilder

**Comment by miemieYaho** [comment]
??? 把东西说清楚,说不清楚给复现 demo

**Comment by songjunyan** [comment]
公司项目 应该jar冲突了 我把自己的mybatis 和mbyats_spring jar去掉用compile group: 'com.baomidou', name: 'mybatis-plus-boot-starter', version: '3.0.6'这个引入了mybatis plus就会出现有一些jar类找不到如：
![image](https://user-images.githubusercontent.com/7437521/50543907-b9121400-0c1f-11e9-9cb8-7d8da9a8a641.png)

**Comment by miemieYaho** [comment]
缺包自己解决
