### ISSUE TITLE
哪个版本可以提供对国产数据库的支持

### ISSUE THREAD

**Issue by bjw211** [baomidou/mybatis-plus#760]
### 当前使用版本(必须填写清楚，否则不予处理)
当前使用版本( 2.1.9

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
项目有国产需求，需要兼容国产数据库：金仓、达梦、神州通用等，添加方言需要对源码进行修改，官方下个版本可否提供对国产数据库的支持?

**Comment by miemieYaho** [comment]
太偏门的不支持,自己改源码吧

**Comment by qmdx** [comment]
达梦可以直接用 oracle 的方言驱动，其他支持你自己扩展
