### ISSUE TITLE
逻辑删除@TableLogic无法使用通用枚举类，值不一样

### ISSUE THREAD

**Issue by zeemood** [baomidou/mybatis-plus#761]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

spring boot 2.1.1.RELEASE + MySQL 5.5下 使用逻辑删除和通用枚举类进行数据插入，无法获得正确的值

### 重现步骤
表中设计字段removed为逻辑删除字段，数据类型为tinyint(2)，使用通用枚举类作为实体类removed的数据格式，插入新数据，与预期的值不一致，期望是YES，结果为1等……

**Comment by miemieYaho** [comment]
代码呢?

**Comment by zeemood** [comment]
找到原因了。是因为devtools的问题。去掉之后就不会保存通用枚举类的name()返回值了。建议在官网上加上这个提示。
