### ISSUE TITLE
枚举类型，tinyint 无法映射到

### ISSUE THREAD

**Issue by northernsong** [baomidou/mybatis-plus#762]
### 当前使用版本(必须填写清楚，否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
数据库类型设置的是`tinyint(1)`的时候，发现该字段是null。当改为int(3)就好了。

### 重现步骤

设置数据库字段`tinyint(1)` 就会出现，枚举类：
```java
public enum ChargeStatusEnum implements IEnum<Integer> {
    /**
     * 启动中
     */
    starting(1),
    charging(2),
    stopping(3),
    over(4),
    unknown(5);

    private Integer value;

    ChargeStatusEnum(Integer value) {
        this.value = value;
    }

    @Override
    @JsonValue
    public Integer getValue() {
        return value;
    }
}
```

实体类字段：
```java
    @JsonIgnore
    @EnumValue
    private ChargeStatusEnum status;
```

### 报错信息

没有报错,只是`null`

**Comment by miemieYaho** [comment]
文档常见问题里面有

**Comment by citygs** [comment]
常见问题里没找到啊，能否复制粘贴一下呢，谢谢

**Comment by citygs** [comment]
> 文档常见问题里面有

文档里没找到啊，能否复制粘贴一下，或者告诉一下在哪个段落里
