### ISSUE TITLE
3.0.6版本分页结果缓存后total值为0

### ISSUE THREAD

**Issue by liwei3232004** [baomidou/mybatis-plus#763]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
在mapper接口开启缓存，分页结果缓存后再次查询total的值为0

### 重现步骤

在mapper接口开启缓存，分页结果缓存后再次查询total的值为0

### 报错信息
无报错信息

**Comment by HuTuXu** [comment]
同求解决方案

**Comment by miemieYaho** [comment]
不建议使用二级缓存

**Comment by qmdx** [comment]
分页暂不支持二级缓存，建议使用 service 层缓存

**Comment by Cat7373** [comment]
`Spring-MVC`项目的话，加一个拦截器搞定：

```java
/**
 * 负责清理 Mybatis 查询缓存的拦截器
 */
public class MybatisCacheClearInterceptor implements HandlerInterceptor {
    private SqlSession sqlSession = Springs.getBean(SqlSession.class);

    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        this.sqlSession.clearCache();
        return true;
    }
}
```

**Comment by Cat7373** [comment]
哦刚刚发现这里面有个我们私有的工具类`Springs `，所以你自己想办法拿一下这个`SqlSession`的实例吧。。
