### ISSUE TITLE
官方社区是否有计划支持自动建表，而不是逆向工程

### ISSUE THREAD

**Issue by newShiJ** [baomidou/mybatis-plus#764]
现在我的开发项目使用的是JPA体系，目前正在考虑切换使用mybatis，但是因为mybatis官方是推荐使用逆向工程，根据数据库表结构构建java代码。这样有一个不太友好的地方就是如果存在多个代码部署环境，一个字段的修改需要手动修复多个数据库环境，若使用JPA就不太需要考虑这个问题。不知道现在mybatis plus 是有计划支持这个需求

**Comment by miemieYaho** [comment]
没有,以后也不会有
