### ISSUE TITLE
postgres中nulls值排序放在列表最后

### ISSUE THREAD

**Issue by xuguangwu** [baomidou/mybatis-plus#766]
ORDER BY score asc nulls last，请问mp中该如何去写，现在我直接使用queryWrapper.orderByDesc(score)

**Comment by miemieYaho** [comment]
不知道你这语句是个啥,看文档自己研究

**Comment by fanlide** [comment]
@miemieYaho 文档中没提到null值排序的问题。在postgresql中倒序时，null会在最前面，要放在最后面就需要加 `nulls last`，这跟mysql中`order by *** is null`差不多。

@xuguangwu 楼主找到方法了吗？

**Comment by xuguangwu** [comment]
> @miemieYaho 文档中没提到null值排序的问题。在postgresql中倒序时，null会在最前面，要放在最后面就需要加 `nulls last`，这跟mysql中`order by *** is null`差不多。
> 
> @xuguangwu 楼主找到方法了吗？

queryWrapper.last("nulls last");
