### ISSUE TITLE
com.baomidou.mybatisplus.service.impl.insertBatch方法的疑问

### ISSUE THREAD

**Issue by stone1234** [baomidou/mybatis-plus#768]
### support 组件 2.3版本

调用com.baomidou.mybatisplus.service.impl.insertBatch方法的时候，会新建一个sqlsession，执行完成后直接关闭，在这种情况下，控制事务的@Transactional注解似乎没有作用。

**Comment by chchfee** [comment]
同问，批量插入是有问题的啊，执行时会报异常；到这一句  String sqlStatement = this.sqlStatement(SqlMethod.INSERT_ONE); 就直接抛异常了

**Comment by miemieYaho** [comment]
事务是控制到 connection 的
