### ISSUE TITLE
3.0-RELEASE版本，按照官方文档中的分页查询示例无法成功查询

### ISSUE THREAD

**Issue by LiuWillow** [baomidou/mybatis-plus#769]
### mybatis-plus 3.0.RELEASE分页查询问题，SpringCloud  Finchley.RELEASE 版本
备注：没有用到分页的查询能够成功执行
### 重现步骤
* datasource和sqlSessionFactory配置：
![image](https://user-images.githubusercontent.com/25578789/50625366-ab7fc580-0f62-11e9-8f28-b941239cc427.png)
* mybatis-plus分页配置：
![image](https://user-images.githubusercontent.com/25578789/50625393-e124ae80-0f62-11e9-9d88-ffdea288af43.png)
* properties中配置xml路径和entity路径
![image](https://user-images.githubusercontent.com/25578789/50625758-10d4b600-0f65-11e9-8183-8e201b421103.png)

* pom中指定resource：
![image](https://user-images.githubusercontent.com/25578789/50625766-1e8a3b80-0f65-11e9-82b7-03cd999234fe.png)

* mapper接口对应的分页查询方法：
![image](https://user-images.githubusercontent.com/25578789/50625428-1cbf7880-0f63-11e9-91b0-08015770adb3.png)

* xml中对应的sql：
![image](https://user-images.githubusercontent.com/25578789/50625447-395bb080-0f63-11e9-997a-a8e51c1b552e.png)

* service中调用：
![image](https://user-images.githubusercontent.com/25578789/50625420-0fa28980-0f63-11e9-8f69-da0b669f11a7.png)

### 报错信息
* 传入的page为1  size为1，实际表中一共三条数据
![image](https://user-images.githubusercontent.com/25578789/50625483-79bb2e80-0f63-11e9-9eaf-7c9346b84d59.png)

好像分页注入没有生效

**Comment by miemieYaho** [comment]
用最新版,参考 https://gitee.com/baomidou/mybatis-plus-samples
