### ISSUE TITLE
添加逻辑删除功能后，有些功能异常。

### ISSUE THREAD

**Issue by tangdelong** [baomidou/mybatis-plus#77]
我添加了逻辑删除功能后，根据ID删除没有问题，但根据条件删除就报异常，
删除伪代码如下：
studentMapper.delete(new EntityWrapper<Student>().eq("name", "XXX196"));
，修改、查询根据同样的条件过滤也报异常。

异常代码（部分）：
### Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :''0'

WHERE (name = ?)',expect WHERE, actual WHERE WHERE : UPDATE tlp_student SET isdelete='9' 
 WHERE  isdelete='0'

**Comment by jiy1012** [comment]
当用Wrapper拼接了eq等条件之后，所有的select和update 都会多一个where，where is_delete=0 where （Wrapper条件）

**Comment by Caratacus** [comment]
2.0.9新版本解决
