### ISSUE TITLE
升级3.0.7.1后generator包哪去了

### ISSUE THREAD

**Issue by eidolonse** [baomidou/mybatis-plus#770]
版本3.0.7.1
升级后项目报错，缺少generator包，以前maven会自动导入mybatis-plus-generator-3.0.6.jar

**Comment by miemieYaho** [comment]
自己导入

**Comment by qmdx** [comment]
https://search.maven.org/search?q=mybatis-plus

**Comment by yecpster** [comment]
小版本的更新我们理解只是bug修复或者增加小的特性，应该是可以放心升级的。但这个3.0.7.1升级后却把generator包移除出去造成项目无法编译，而且文档没有提到，感觉太不谨慎了。

**Comment by miemieYaho** [comment]
升级日志里面有,文档里不会有升级日志

**Comment by qmdx** [comment]
@yecpster  放心使用全部托管在git 上源码，有问题可以随时 PR  生成器考虑到生产环境不需要打包，因此解耦出去你需要自己引入，建议生成器部分可以放置到 test 部分
