### ISSUE TITLE
自动生成代码，实体类继承自定义baseEntity问题

### ISSUE THREAD

**Issue by williamHappy** [baomidou/mybatis-plus#772]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

生成的实体类，没有导入java.io.Serializable包

### 重现步骤
1. 配置开启gc.setActiveRecord(true);
2. 配置继承父类strategy.setSuperEntityClass("base.domain.BaseDO");
```java
public class BaseDO<T extends Model> extends Model<T>{}
```
这样的话，生成的实体类是没有Serializable包的
是不是这个问题：查看源码
![image](https://user-images.githubusercontent.com/19304825/50682453-d729ab00-1049-11e9-821e-e47289d2a76d.png)

### 报错信息
![image](https://user-images.githubusercontent.com/19304825/50682020-764da300-1048-11e9-9b07-ff3424c61654.png)

**Comment by qmdx** [comment]
待解决，你可以先 复制  entity 模板放在项目 resource 下然后修改导入包【临时方案】

**Comment by williamHappy** [comment]
嗯，是的，目前是这样解决的

**Comment by qmdx** [comment]
https://github.com/baomidou/mybatis-plus/commit/ffbbbe5839cccdbcd7346ca0aaf4e7e908be835c
