### ISSUE TITLE
3.0.7热加载不提供了么

### ISSUE THREAD

**Issue by duwei54** [baomidou/mybatis-plus#773]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

spring boot 2.0.0 全局配置refresh 不生效
查看源码是说refresh已经过时了

已经看到 https://github.com/baomidou/mybatis-plus/issues/398 说是有问题
以后不会提供热加载了么?

**Comment by miemieYaho** [comment]
有效,后面某个版本会移除
