### ISSUE TITLE
MybatisPlus的SqlInject与Interceptor有什么区别

### ISSUE THREAD

**Issue by jervainy** [baomidou/mybatis-plus#781]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
业务中需要根据用户筛选出属于自己的数据，打算写一个统一的处理，看了下SqlInject，分为了多个AbstarctMethod去处理，请问下这样处理的初衷是啥？

**Comment by miemieYaho** [comment]
解耦
