### ISSUE TITLE
主键重复异常

### ISSUE THREAD

**Issue by xufanevel** [baomidou/mybatis-plus#784]
### 当前使用版本(必须填写清楚，否则不予处理)
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.10.RELEASE</version>
	</parent>
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus</artifactId>
			<version>2.1.9</version>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatisplus-spring-boot-starter</artifactId>
			<version>1.0.5</version>
		</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
在集群环境下，对同一张表进行insert操作时，出现主键冲突的情况

### 报错信息

Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1083032402190766082' for key 'PRIMARY'
; SQL []; Duplicate entry '1083032402190766082' for key 'PRIMARY'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1083032402190766082' for key 'PRIMARY'

**Comment by miemieYaho** [comment]
你的集群环境时间同步吗?

**Comment by xufanevel** [comment]
是同步的，docker部署的

**Comment by miemieYaho** [comment]
怎样的集群?同一个机器上多个 docker?

**Comment by xufanevel** [comment]
docker都在不同的机器上

**Comment by xufanevel** [comment]
跟引入的mybatis-plus版本有没有影响呢

**Comment by miemieYaho** [comment]
你 docker 启动,那不是环境都一样嘛,机器 id 啥的很可能全都一样,生成出重复 id 也就不奇怪了

**Comment by xufanevel** [comment]
那么针对这种集群方式，注解id的生成策略需要怎么调整呢

**Comment by qmdx** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md

**Comment by xufanevel** [comment]
@qmdx 你项目中也有遇到这种情况吗？

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/2.x/CHANGELOG.md

**Comment by xufanevel** [comment]
要避免这个不同容器内主键ID不重复的话，我这边是需要怎么处理呢 @miemieYaho

**Comment by miemieYaho** [comment]
看一下源码,了解一下 idwork 类的初始化信息

**Comment by xufanevel** [comment]
![image](https://user-images.githubusercontent.com/20982461/50955982-7b519d00-14f5-11e9-9539-f8cf80b975a5.png)
如果是在同一台宿主机上的docker容器里面取到的值都是一样的

> 你 docker 启动,那不是环境都一样嘛,机器 id 啥的很可能全都一样,生成出重复 id 也就不奇怪了

**Comment by Cat7373** [comment]
你可以通过手动对`IdWorker`进行配置来防止出现重复的情况，比如我们在`SpringBoot`应用里是这么配置的：

application.yml

```yaml
# Id 生成器用，多个实例之间不得重复，范围为 0 ~ 1023，最多可支持 1024 个实例
node-id: 1
```

DatabaseConfigure.java

```java
/**
 * 数据库配置
 */
@Configuration
@MapperScan("xx.yy.zz.**.mapper")
public class DatabaseConfigure {
    /**
     * 为 IdWorker 初始化数据中心 ID 和机器 ID
     */
    @PostConstruct
    public void initIdWorker() {
        long dataCenterId = ((Integer.valueOf(Springs.getProperty("node-id")) >> 5) & 0b00011111);
        long workerId = (Integer.valueOf(Springs.getProperty("node-id")) & 0b00011111);
        IdWorker.initSequence(workerId, dataCenterId);
    }
}
```

这样在每个节点部署之前只需要修改配置文件中的`node-id`，保证它们不重复就行了

关于`Springs.getProperty`，你可以通过`@Value`来代替它
