### ISSUE TITLE
逻辑删除与Wrapper冲突

### ISSUE THREAD

**Issue by githubzz** [baomidou/mybatis-plus#785]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

当我开启了逻辑删除功能后，使用Mybatis自动生成的Mapper来查询分页时，发生SQL语句不正确的问题

### 重现步骤
查询方式：主要是使用自动生成的Mapper.selectPage(QueryWrapper)
`
IPage<M> pagConditon = new Page<>(pageUtils.getIndex(), pageUtils.getSize());
IPage<M> pageResult;
if (pageUtils.getCondition()!=null) {
    QueryWrapper<M> queryWrapper = new QueryWrapper<>();
    queryWrapper = pageUtils.getCondition().parseCondition(queryWrapper);
     pageResult=baseMapper.selectPage(pagConditon,queryWrapper);
}
`

### 报错信息
Error querying database.  Cause: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,2' at line 2
The error may exist in com/**/base/mapper/DatadictMapper.java (best guess)
The error may involve defaultParameterMap
The error occurred while setting parameters
SQL: SELECT  id,dname,dvalue,description,typeId,parentId,viewType,deleted,createTime,updateTime,creator,modifier  FROM base_datadict   WHERE deleted=0; LIMIT ?,?
Cause: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,2' at line 2
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,2' at line 2] with root cause

如上所示，错误的SQL语句是：
SELECT  id,dname,dvalue,description,typeId,parentId,viewType,deleted,createTime,updateTime,creator,modifier  FROM base_datadict   WHERE deleted=0; LIMIT ?,?
其中：deleted=0,是逻辑删除部分的，主要是deleted后面添加了一个分号，导致报错，我试了一下其他的条件查询，也是如此

**Comment by miemieYaho** [comment]
无法复现

**Comment by miemieYaho** [comment]
你那个分号是你自己配上去的,好好检查你的配置!

**Comment by githubzz** [comment]
分号可以怎么配置呢

**Comment by miemieYaho** [comment]
好好检查你的配置!

**Comment by githubzz** [comment]
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=false
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0;

这是我的所有配置

**Comment by miemieYaho** [comment]
你都发出来了还看不见吗? 你0后面是个啥你告诉我!

**Comment by githubzz** [comment]
嗯，看到了，谢谢
