### ISSUE TITLE
主键重复异常的问题

### ISSUE THREAD

**Issue by Wadeqin** [baomidou/mybatis-plus#786]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter 3.0.5

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

mybatis的modle insert时主键重复会抛出Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1083032402190766082' for key 'PRIMARY'
但是无法用try-catch捕捉，只能通过全局异常捕捉处理

**Comment by miemieYaho** [comment]
没毛病

**Comment by Wadeqin** [comment]
1.不应该可以让使用者去决定try-catch吗？
2.有没有比较好的处理方式，难道都是针对不同的业务去写全局异常的多条件处理？

**Comment by Wadeqin** [comment]
类似于spring dao的DuplicateKeyException这种，用户可以去决定怎么处理。

**Comment by miemieYaho** [comment]
这是 mybatis ,你要 try 就自己 try
