### ISSUE TITLE
关于Condition in Collection条件逻辑设计上的问题

### ISSUE THREAD

**Issue by jipeigong** [baomidou/mybatis-plus#788]
### 当前使用版本(必须填写清楚，否则不予处理)
版本2.2.0

### 问题描述
Condition condition = new Condition();
condition.in("xxx",new ArrayList<>());
xxxservice.selectList(condition);

此时会查询出表内所有结果，在通常的逻辑中此条查询理解为查询该字段的值匹配在集合内的所有结果，而此时集合为空，是否应该不查询出任何结果？

**Comment by miemieYaho** [comment]
这种情况自行做 if 处理
