### ISSUE TITLE
动态数据源service中切换加注解DS 切换数据源出错

### ISSUE THREAD

**Issue by xie-summer** [baomidou/mybatis-plus#791]
### 当前使用版本(必须填写清楚，否则不予处理)

v3.0.7
dynamic-datasource-spring-boot-starter.version>2.4.2</dynamic-datasource-spring-boot-starter.version>
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
两个service中分别加注解DS两个数据源，在一个service中调用另外一个service查询另外数据源
会导致被调用方数据源未切换，

**Comment by xie-summer** [comment]
@ @qmdx  大佬有时间查看吗

**Comment by miemieYaho** [comment]
去那边提 issue,这边不处理
