### ISSUE TITLE
逻辑删除字段配置不支持大小写忽略

### ISSUE THREAD

**Issue by umi-soft** [baomidou/mybatis-plus#793]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

LogicDeleteFieldName字段配置时，发现并不支持大小写忽略

### 重现步骤

LogicDeleteFieldName变更大小写后，@TableLogic注解丢失，说明目前并不支持大写小忽略特性

### 报错信息

无报错信息

**Comment by miemieYaho** [comment]
什么意思?请表达清楚

**Comment by umi-soft** [comment]
比如，设置逻辑删除字段时，对应生成Entity字段会添加@TableLogic注解，实际的数据库，如MySQL中表大写字段"DELETED"。那么Generator配置逻辑删除字段名称必须为大写"DELETED"，并不支持大小写忽略，如配置成小写"deleted"。

**Comment by qmdx** [comment]
生成器设置字段为大写
