### ISSUE TITLE
代码生成器默认配置生成的xml没有指定jdbctype，如何配置它？

### ISSUE THREAD

**Issue by aug7** [baomidou/mybatis-plus#796]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis plus boot starter 3.0.4

**Comment by Cat7373** [comment]
请参考[代码生成器文档](https://mybatis.plus/guide/generator.html)，可通过其中的`DataSourceConfig `来进行设置：

```java
// 数据源配置
DataSourceConfig dsc = new DataSourceConfig();
dsc.setDbType(DbType.MYSQL); // 手动指定数据库类型
dsc.setDriverName("com.mysql.jdbc.Driver");
```

**Comment by zzzzzmh** [comment]
![image](https://user-images.githubusercontent.com/3642590/59917625-021b8600-9455-11e9-82c9-bac42b9b73d1.png)
这个类里，没有jdbcType字段，setDbType 也无效吧
