### ISSUE TITLE
分页查询条件构造器不起作用

### ISSUE THREAD

**Issue by c79383270** [baomidou/mybatis-plus#799]
### 该问题是怎么引起的？
使用Iservice中的page方法做分页查询的时候条件构造器不起作用

### 重现步骤
查询代码:QueryWrapper<BdAirlines> wrapper = new QueryWrapper<BdAirlines>()
.eq("id","5ffb0115a6a44dadaa7dbf630ceb5e66");
IPage<BdAirlines> pages = airlinesService.page(page,wrapper);

打印出的sql语句:Execute SQL：select id, ser, iata_code, icao, airlines_name, billing_code, remark, agency, is_del, create_time, create_user, update_time, update_user from bd_airlines limit ? offset ?

没有跟上条件构造添加的条件

### 报错信息
没有报错,分页查询正常 但是条件构造中的条件没有被执行

**Comment by miemieYaho** [comment]
无法复现,请给出复现demo

**Comment by chenxiao90312** [comment]
是不是忘记在spring配置中，启用分页插件？
方法参考：https://mp.baomidou.com/guide/page.html
