### ISSUE TITLE
mybatis-plus 怎么增量生成代码

### ISSUE THREAD

**Issue by yelynn** [baomidou/mybatis-plus#800]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
比如业务上需要频繁改动某个表的字段
每次重新生成会覆盖之前自己写的非通用sql 如何增量只更新字段不覆盖之前的sql

**Comment by abcbuzhiming** [comment]
你使用思路是错的，不要在生成的的代码里改啊，你自己重新建个新的mapper和xml文件不就行了，无论怎么生成都不会覆盖到新的上的

**Comment by yelynn** [comment]
之前用mybatis generator的时候是生成了继承的mapper和xml。那mybatis-plus有没有类似的现成功能可以用？

**Comment by gf76866908** [comment]
mybatis-plus-boot-starter 最新的3.0.7.1  怎么找不到AutoGenerator这个类了 你们官网的 给的demo还是这个？？？

**Comment by SoyMeng** [comment]
设置代码不覆盖，只生成实体类就行了

**Comment by qmdx** [comment]
如上解决， 增量也没有意义难度极大
