### ISSUE TITLE
能说下PageHelper在3.0移除的原因吗?

### ISSUE THREAD

**Issue by zl7261** [baomidou/mybatis-plus#801]
只找到了这么一句话,也没有找到相应的替代模式.
https://github.com/baomidou/mybatis-plus/blob/3.0/CHANGELOG.md
咩咩说了 MP 3.0 分页已经飘飘欲仙了，不在需要迁就使用 PageHelper 模式

如果使用Page传参的话,对dao层的侵入是不是太深了?

**Comment by miemieYaho** [comment]
有什么深不深的,你喜欢PageHelper可以自己引PageHelper,我们不再提供和它相似的模式而已

**Comment by Cat7373** [comment]
已更换`com.github.pagehelper':pagehelper`，因为我们有一个非侵入的注解式分页，所以必须有这种`PageHelper `的模式

**Comment by zl7261** [comment]
其实这个pagehelper也是相当坑的.
说明文档不是很详细,绝对没有mybatis-plus详细,
也没有一个好点的示例代码,包括一些选项的
而且threadLocal存在内存泄漏的隐患,虽然他有个清除的方法,但是没在文档里写出来
默认操作每次分页都要去count一次,一个20W的表,QPS居然才100左右,ygc比起jdbc超了2倍不止
关闭了count之后,QPS跟mybatis的差距还是有10%以上
分页这种操作最好还是手写吧,起码count的缓存目前没找到好的轮子

**Comment by Cat7373** [comment]
> 其实这个pagehelper也是相当坑的.
> 说明文档不是很详细,绝对没有mybatis-plus详细,
> 也没有一个好点的示例代码,包括一些选项的
> 而且threadLocal存在内存泄漏的隐患,虽然他有个清除的方法,但是没在文档里写出来
> 默认操作每次分页都要去count一次,一个20W的表,QPS居然才100左右,
> count 50ms,select 10ms,
> 而且ygc比起jdbc超了2倍不止
> 
> 关闭了默认的count操作后,QPS跟mybatis的差距还是有10%以上
> 分页这种操作最好还是手写吧,起码count的缓存目前没找到好的轮子

通常来说性能问题我的态度是遇到瓶颈再解决，没有瓶颈的地方为了开发效率我可以接受一定的性能下降，比如我们现在的分页接口只需要加一个 @Pager 就能搞定，稍加配置还可以再支持导出成 excel，在项目中有一堆分页查询的时候极大的提升了开发效率

如果真的遇到了瓶颈，那可以单独针对这个瓶颈去进行优化，而不是一开始就付出提高数倍代码量的代价去对所有地方都做优化

**Comment by qmdx** [comment]
> > 其实这个pagehelper也是相当坑的.
> > 说明文档不是很详细,绝对没有mybatis-plus详细,
> > 也没有一个好点的示例代码,包括一些选项的
> > 而且threadLocal存在内存泄漏的隐患,虽然他有个清除的方法,但是没在文档里写出来
> > 默认操作每次分页都要去count一次,一个20W的表,QPS居然才100左右,
> > count 50ms,select 10ms,
> > 而且ygc比起jdbc超了2倍不止
> > 关闭了默认的count操作后,QPS跟mybatis的差距还是有10%以上
> > 分页这种操作最好还是手写吧,起码count的缓存目前没找到好的轮子
> 
> 通常来说性能问题我的态度是遇到瓶颈再解决，没有瓶颈的地方为了开发效率我可以接受一定的性能下降，比如我们现在的分页接口只需要加一个`@Pager`就能搞定，稍加配置还可以再支持导出成 excel，在项目中有一堆分页查询的时候极大的提升了开发效率
> 
> 如果真的遇到了瓶颈，那可以单独针对这个瓶颈去进行优化，而不是一开始就付出提高数倍代码量的代价去对所有地方都做优化

非常正确， MP  分页有 count 开关，如果 count 是瓶颈建议自己查询设置 total 值

**Comment by 5468sun** [comment]
> 其实这个pagehelper也是相当坑的.
> 说明文档不是很详细,绝对没有mybatis-plus详细,
> 也没有一个好点的示例代码,包括一些选项的
> 而且threadLocal存在内存泄漏的隐患,虽然他有个清除的方法,但是没在文档里写出来
> 默认操作每次分页都要去count一次,一个20W的表,QPS居然才100左右,
> count 50ms,select 10ms,
> 而且ygc比起jdbc超了2倍不止
> 
> 关闭了默认的count操作后,QPS跟mybatis的差距还是有10%以上
> 分页这种操作最好还是手写吧,起码count的缓存目前没找到好的轮子

请问MP分页有详细的文档？在哪里呢？我只找到这个。
https://mybatis.plus/guide/page.html
