### ISSUE TITLE
使用代码生成器生成实体类，tinyint(1) 映射为 boolean 类型

### ISSUE THREAD

**Issue by abcbuzhiming** [baomidou/mybatis-plus#802]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
使用代码生成器生成实体类，tinyint(1) 映射为 boolean 类型。官网常见问题上说，只要在jdbcurl上添加
tinyInt1isBit=false就可以解决这个问题，但是实测无效

### 重现步骤
无论再jdbcurl上加不加tinyInt1isBit=false，tinyint(1) 都会映射成boolean 类型

### 报错信息
无报错，就是生成类型不正确

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/converts/MySqlTypeConvert.java

**Comment by abcbuzhiming** [comment]
> https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-generator/src/main/java/com/baomidou/mybatisplus/generator/config/converts/MySqlTypeConvert.java

您的意思是说我必须用自定义lTypeConvert实现的方式来解决这个问题？

**Comment by miemieYaho** [comment]
恩
