### ISSUE TITLE
自定义主键获取方式怎么弄。如:ID从redis获取。。。

### ISSUE THREAD

**Issue by wojasonx** [baomidou/mybatis-plus#803]

**Comment by miemieYaho** [comment]
1.自己 set 2.用自动填充

**Comment by wojasonx** [comment]
@TitanId
    @TableId(value = "id", type=IdType.AUTO)
    private Long id;
id我手动set进去了。。但是没效果
INSERT INTO sys_user ( user_name ) VALUES ( ? )

**Comment by miemieYaho** [comment]
IdType.INPUT,有问题看文档
