### ISSUE TITLE
请问全局配置的 tablePrefix 的正确使用姿势？没有效果

### ISSUE THREAD

**Issue by yang3350380** [baomidou/mybatis-plus#804]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

tablePrefix
类型：String
默认值：null
表名前缀

Spring Boot：

mybatis-plus:
  global-config:
    db-config:
      table-prefix: xx_

### 报错信息

请问这个配置能起到什么作用？正确使用方法是怎样的，配置后没有效果

**Comment by miemieYaho** [comment]
非使用注解表名下才会生效
