### ISSUE TITLE
Sequence类getDatacenterId方法在容器内永远为0

### ISSUE THREAD

**Issue by punge** [baomidou/mybatis-plus#807]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

Docker内获取MAC地址失败

### 重现步骤

将sequence类的getDatacenterId方法在docker容器内执行，返回0

**Comment by miemieYaho** [comment]
https://stackoverflow.com/

**Comment by gerogeforli** [comment]
提个问题而已，不能解决关掉就行了，别发https://stackoverflow.com/

**Comment by gerogeforli** [comment]
> https://stackoverflow.com/

提个问题而已，不能解决关掉就行了，别发https://stackoverflow.com/
