### ISSUE TITLE
setSqlSelect("sum(clickCount)") 不起作用

### ISSUE THREAD

**Issue by bertonlee** [baomidou/mybatis-plus#808]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.0.7.1</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
打印sql语句还是走count(1)
`SELECT COUNT(1) FROM blog_article_featured `

### 重现步骤
` Wrapper<ArticleFeatured> a = new EntityWrapper<ArticleFeatured>().setSqlSelect("sum(clickCount)");
Integer count = articleFeaturedMapper.selectCount(a);`

### 报错信息
并不是我想要的
select sum(clickCount)  这是为什么呢，谢谢

**Comment by qq592302116** [comment]
解决，谢谢
