### ISSUE TITLE
当EntityWrapper的对象里，无设置值的时候，输出SQL还有where，看以下代码，加上order by 就出错

### ISSUE THREAD

**Issue by sdhery** [baomidou/mybatis-plus#81]
new EntityWrapper<SysAdmin>(sysAdmin).orderBy("CREATE_DATE",false)

**Comment by yuxiaobin** [comment]
谢谢反馈，该问题已经在修复，
可以参考[码云的dev分支](http://git.oschina.net/baomidou/mybatis-plus)
