### ISSUE TITLE
使用log4jdbc的jdbc驱动器代码生成器不可用

### ISSUE THREAD

**Issue by BYLBJ** [baomidou/mybatis-plus#810]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
driverName设置为net.sf.log4jdbc.DriverSpy,按照目前的代码逻辑会找不到对应的数据库类型

### 重现步骤
public DbType getDbType() {
        if(null == this.dbType) {
            if(this.driverName.contains("mysql")) {
                this.dbType = DbType.MYSQL;
            } else if(this.driverName.contains("oracle")) {
                this.dbType = DbType.ORACLE;
            } else if(this.driverName.contains("postgresql")) {
                this.dbType = DbType.POSTGRE_SQL;
            } else if(this.driverName.contains("sqlserver")) {
                this.dbType = DbType.SQL_SERVER;
            } else if(this.driverName.contains("db2")) {
                this.dbType = DbType.DB2;
            } else {
                if(!this.driverName.contains("mariadb")) {
                    throw ExceptionUtils.mpe("Unknown type of database!", new Object[0]);
                }

                this.dbType = DbType.MARIADB;
            }
        }

        return this.dbType;
    }

### 报错信息
Unknown type of database!

**Comment by miemieYaho** [comment]
你这是什么数据库?没有那只能等人 pr

**Comment by BYLBJ** [comment]
我用的是oracle，使用log4jdbc的驱动连接，driverName是net.sf.log4jdbc.DriverSpy，但目前代码生成器中getDbType方法是根据driverName判断的，所以就无法判断出对应的数据类型，我觉得这里是不是用驱动连接的URL判断更好

**Comment by BYLBJ** [comment]
> 你这是什么数据库?没有那只能等人 pr
我用的是oracle，使用log4jdbc的驱动连接，driverName是net.sf.log4jdbc.DriverSpy，但目前代码生成器中getDbType方法是根据driverName判断的，所以就无法判断出对应的数据类型，我觉得这里是不是用驱动连接的URL判断更好

**Comment by qmdx** [comment]
请使用官方标准驱动，否则你自行研究下 PR
