### ISSUE TITLE
关于代码生成器两个小问题求教

### ISSUE THREAD

**Issue by YellowDoing** [baomidou/mybatis-plus#812]
当前使用版本(3.0.7.1)
1. 我要再增加生成一个exception包，请问要怎么操作设置
2. 生成的Controller头部注解为什么会重复两次模块名，怎么设置成一个
![image](https://user-images.githubusercontent.com/20732953/51421914-360e2900-1be1-11e9-8b8a-5556c58c48a0.png)
谢谢

**Comment by huayanYu** [comment]
自定义模板
