### ISSUE TITLE
有没有 mybatisplus+log4j2 ? 

### ISSUE THREAD

**Issue by luffy-wxdcxs** [baomidou/mybatis-plus#814]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatisplus.version 2.1.9

想请教一下，既然mybatisplus可以基于mybatis封装，那请问支持log4j/log4j2打印sql到日志吗？
我该怎么去探索这个问题呢？

**Comment by miemieYaho** [comment]
baidu
