### ISSUE TITLE
@TableName 中的 resultMap 字段怎么使用？

### ISSUE THREAD

**Issue by mingfer** [baomidou/mybatis-plus#815]
### 当前使用版本(必须填写清楚，否则不予处理)
版本 2.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

不知道 @TableName 中的 resultMap 字段怎么使用。

主要是为了将 lvarchar 类型数据的 type-handle 配置为 StringTypeHandler。因为国产数据库 gbase 对于超过 256 的字符串数据必须使用 lvarchar 类型。但是默认情况下 gbase 的驱动里面 getClob() 方法会报二进制数据无法装换。

**Comment by miemieYaho** [comment]
xml里面写resultMap,把resultMap的 id 放到注解里去

**Comment by mingfer** [comment]
目前的项目里面没有使用 XML 是通过 @Results 注解来映射结果的，我尝试了将 @Results 注解的 ID 给到 resultMap ，但是测试的结果是不可行的。目前是只能用 XML 里面的 id 吗？

**Comment by miemieYaho** [comment]
注解形式就用快照版 `3.0.8.3-SNAPSHOT`
