### ISSUE TITLE
当该Field为类对象时, 可使用#{对象.属性}来映射到数据表.

### ISSUE THREAD

**Issue by dampce32** [baomidou/mybatis-plus#82]
@TableField(el="#{creator.id}",value="creator_id")
	protected User creator;
配置了但是没效果

**Comment by qmdx** [comment]
不是有注解么！！
``
    /**
     * <p>
     * 当该Field为类对象时, 可使用#{对象.属性}来映射到数据表.
     * </p>
     * <p>
     * 支持：@TableField(el = "role, jdbcType=BIGINT)<br>
     * 支持：@TableField(el = "role, typeHandler=com.baomidou.xx.typehandler.PhoneTypeHandler")
     * </p>
     */
    String el() default "";
``
