### ISSUE TITLE
执行insert语句出现空指针异常

### ISSUE THREAD

**Issue by ajavaer** [baomidou/mybatis-plus#822]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

###controller
![qq 20190123123420](https://user-images.githubusercontent.com/31003161/51583375-3bce7c00-1f0b-11e9-8f1e-7141c35cd130.jpg)

###debug的
![qq 20190123123328](https://user-images.githubusercontent.com/31003161/51583363-25282500-1f0b-11e9-985f-5c2f9c586bb7.png)

### 报错信息
![buginfo](https://s2.ax1x.com/2019/01/23/kARygP.png)

我实在实在是debug不出来问题，麻烦了，在线等解决方法

**Comment by miemieYaho** [comment]
你这是你业务上的 bug,我们如何帮你看?

**Comment by ajavaer** [comment]
> 你这是你业务上的 bug,我们如何帮你看?

这怎么是业务的bug？entity debug出来明明白白的，我调用的是mp的service封装的save方法报的空指针

**Comment by miemieYaho** [comment]
你 controller 50 行报的错ok?

**Comment by miemieYaho** [comment]
日志看不出来什么,要么尝试升级版本要么自己 debug 找

**Comment by ajavaer** [comment]
50行就是save方法，
我找了很久了，实在debug不出来，怎么会这样呢？entity信息没问题，service也没问题，怎么就不能insert

**Comment by ajavaer** [comment]
我截图前删除了一行，50行就是save

**Comment by qmdx** [comment]
feedbackService 未正确注入，导致空指针

**Comment by ajavaer** [comment]
> feedbackService 未正确注入，导致空指针

注入了的，debug获取到了
