### ISSUE TITLE
在insert时候报错，空指针异常

### ISSUE THREAD

**Issue by ajavaer** [baomidou/mybatis-plus#823]
### 当前使用版本
3.0.6

###controller
![qq 20190123123420](https://user-images.githubusercontent.com/31003161/51583375-3bce7c00-1f0b-11e9-8f1e-7141c35cd130.jpg)

###debug的
![qq 20190123123328](https://user-images.githubusercontent.com/31003161/51583363-25282500-1f0b-11e9-985f-5c2f9c586bb7.png)

### 报错信息
![buginfo](https://s2.ax1x.com/2019/01/23/kARygP.png)

我实在实在是debug不出来问题，麻烦了，在线等解决方法

**Comment by miemieYaho** [comment]
要么你就写个复现 demo

**Comment by ajavaer** [comment]
> 要么你就写个复现 demo

哎，我自己写了个方法不走save调service，也不管用，是空指针，但是哪个参数空指针debug不到啊

**Comment by ajavaer** [comment]
> 要么你就写个复现 demo

我好崩溃啊，重新写了个demo一模一样发现可以，但是之前的就不行，是不是有缓存什么的需要删除什么啊，我代码生成器运行后有修改过entity，是不是走的还是之前的还是怎么回事

**Comment by qmdx** [comment]
未提供 demo 无法重现
