### ISSUE TITLE
找不到@TableName等一些基础功能的说明文档

### ISSUE THREAD

**Issue by yuriwxc** [baomidou/mybatis-plus#825]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
我通过网上资料查询到了@TableName ，@TableId, @TableField的一些说明， 为什么在官方文档里面找不到任何相关资料？ 是我找错了地方吗？  官方的指南和配置页面都找不到。

**Comment by miemieYaho** [comment]
[参考](https://baomidou.gitee.io/mybatis-plus-doc/#/generic-crud?id=%E6%B3%A8%E8%A7%A3%E8%AF%B4%E6%98%8E)或者看源码
