### ISSUE TITLE
mybatis-Plus2.3不支持分布式事务LCN4.0

### ISSUE THREAD

**Issue by chen497147884** [baomidou/mybatis-plus#826]
### LCN4.0分布式事务整合Mybatis-Plus分布式事务失效
在Service  impl实现层
使用int rs = this.baseMapper.insert(new TestEntity("mybatis-plus-hello-2"));
分布式事务失效
改成原生的Mybatis
this.baseMapper.save("mybatis-plus-hello-2");
在xml中  编写SQL
<insert id="save" parameterType="string">
        INSERT INTO T_TEST(NAME) VALUES(#{name})
    </insert>
分布式事务有效

### 重现步骤
无

### 报错信息

无

PS:Demo 连接    https://gitee.com/chen497147884/springcloud-lcn-demo

**Comment by qmdx** [comment]
对 LCN 不了解，普通事务是支持的应该不会不支持 LCN 吧？ 希望你自己排除解决，如果是 MP 问题欢迎告知 或 PR

**Comment by zlmisme** [comment]
好像是lcn无法获取数据库代理
