### ISSUE TITLE
mybatis-plus 全局模式配置kotlin模式下swagger模式无效

### ISSUE THREAD

**Issue by windyrjc** [baomidou/mybatis-plus#827]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator 3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
在generator 全局配置中同时将配置swagger和kotlin设置为true swagger不生效

**Comment by Cat7373** [comment]
虽然我很讨厌 Swagger😂

**Comment by nieqiurong** [comment]
> 虽然我很讨厌 Swagger

但你内心还是很开心的.

**Comment by qmdx** [comment]
女装老大 && 秋秋 已经解决了
