### ISSUE TITLE
关于 IService.getOne 默认值是否抛异常的建议

### ISSUE THREAD

**Issue by iisimpler** [baomidou/mybatis-plus#828]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

在 com.baomidou.mybatisplus.extension.service.IService 中有一个查询一条记录的方法，这方法默认行为是当查询到多条记录是不是直接抛异常，而是查询到list，然后get(0)。个人建议将此默认值设为true。如果用户真有这样的需求，那他可先拼一个带有order的wrapper， 然后手动设置第二个参数为false，xxxServiceImpl.getOne(wrapper)，因为只有排过序的wrapper再取第一条才是有意义的，不然很容易引起误解，强烈建议查询到多条就抛异常处理。

```
/**
     * <p>
     * 根据 Wrapper，查询一条记录
     * </p>
     *
     * @param queryWrapper 实体对象封装操作类 {@link com.baomidou.mybatisplus.core.conditions.query.QueryWrapper}
     */
    default T getOne(Wrapper<T> queryWrapper) {
        return getOne(queryWrapper, false);
    }
```

### 重现步骤

无需重现。

### 报错信息

不会报错，但是没注意到这个坑，会污染数据库数据。

**Comment by qmdx** [comment]
调整为直接抛出异常  `3.0.7.1` 以后版本的支持，请关注下一个版本的发布

**Comment by chenise** [comment]
请问这种情况下抛出的是扫码异常呢？接口上没有写
