### ISSUE TITLE
关于 UpdateWrapper, LambdaUpdateWrapper set方法优化建议

### ISSUE THREAD

**Issue by iisimpler** [baomidou/mybatis-plus#829]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

在 `UpdateWrapper`,  `LambdaUpdateWrapper` 两个类中，不但有 eq 这类的方法组装where条件，还有set方法拼接 set 字段，建议set方法行为和eq方法行为一致老老实实拼接where条件就好， 或者干脆废弃掉set方法。因为目前在update方法中既然有第一个参数entity用来拼接set条件，那么就没必要让wrapper再兼具这样的角色了。还有，在目前流式写法中，本来就很长了，将set和eq等条件混在一起很难维护，分开写更优，望斟酌考虑。

```
    /**
     * <p>
     * 根据 whereEntity 条件，更新记录
     * </p>
     *
     * @param entity        实体对象
     * @param updateWrapper 实体对象封装操作类 {@link com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper}
     */
    boolean update(T entity, Wrapper<T> updateWrapper);
```

### 重现步骤

上面已描述清楚

### 报错信息

无，但是使用不当，容易污染数据库数据。

**Comment by miemieYaho** [comment]
UpdateWrapper 有更多用途
