### ISSUE TITLE
Entity 继承 2.0.8 正常，2.0.9 报不能绑定的错误。

### ISSUE THREAD

**Issue by eastxiang** [baomidou/mybatis-plus#83]
如果Entity有继承关系，例如代码如果放在父类，则在2.0.8 正常，2.0.9 报不能绑定的错误。
    @TableId
    protected Long id;

    @Override
    protected Serializable pkVal() {
        return id;
    }

**Comment by broadliyn** [comment]
owner肯定是直接关闭你的问题，然后甩你一个question页面。。。

其实我也有同样的问题，2.0.8以前一切正常，升级到2.0.9各种找不到绑定的问题。。。

心累，打算弃坑了。

**Comment by qmdx** [comment]
@eastxiang   @broadliyn   抱歉  2 位  2.0.9 有一个主键优化处理点问题，由于测试用例没有 实体父类的覆盖遗漏了， 对于你们反馈的问题都会及时解决，如果文档有的一般都会发地址。 建议加入我们 Q 群号:576493122 能及时得到一手问题信息。多谢支持！ @broadliyn  也别玻璃心 mp 的成长靠大家一起来也维护。
