### ISSUE TITLE
复杂条件构造问题

### ISSUE THREAD

**Issue by xiaoyuer2019** [baomidou/mybatis-plus#831]
querywapper里能否在条件构造器里增加一个左括号和右括号的方法，这样可以自己自定义复杂的sql语句查询，比如a and (b or c)，b和c都是要先判断是否存在，这样就无法用or(i -> i.eq("name", "李白").ne("status", "活着")) 这样的方法，如果能增加左右括号的方法，就可以自己在想添加括号的地方添加括号了。

**Comment by miemieYaho** [comment]
看文档,灵活用
