### ISSUE TITLE
条件构造器没找到 like 占位符的语句

### ISSUE THREAD

**Issue by wangjiahao123456** [baomidou/mybatis-plus#833]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
就是没找到like __1__ 语句的构造器，会直接在两边加上多余的%，这不是我想要的。
感觉只需要一个like 就够了，% _ 这些字符交个代码拼接就好了啊。

**Comment by miemieYaho** [comment]
too young too simple

**Comment by yuxiaobin** [comment]
likeLeft/likeRight了解一下
