### ISSUE TITLE
未来是否会加入表后缀功能

### ISSUE THREAD

**Issue by blank1993** [baomidou/mybatis-plus#836]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator 3.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
未来是否会加入表后缀功能，目前只有表前缀

**Comment by miemieYaho** [comment]
不会
