### ISSUE TITLE
generator不生成id

### ISSUE THREAD

**Issue by md51111** [baomidou/mybatis-plus#839]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

       // 全局配置
        GlobalConfig gc = new GlobalConfig();
        String projectPath = System.getProperty("user.dir");
        gc.setOutputDir(projectPath + "/src/main/java");
        gc.setAuthor("");
        gc.setOpen(false);
        gc.setIdType(ID_WORKER);
        mpg.setGlobalConfig(gc);

加了IdType，写了ID_WORKER，IdType.ID_WORKER，AUTO，IdType.AUTO，IdType.INPUT
都不生成id

### 重现步骤
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class ContentCn implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer tableId;

    private String field1;

    private String field2;

    private String field3;

}

       @Resource
	private ContentCnMapper mapper;

	@Test
	public void Insert(){
		ContentCn contentCn = new ContentCn();
		contentCn.setTableId(2);
		contentCn.setField1("张老师");
		contentCn.setField2("男");
		contentCn.setField3("在职教师");
		mapper.insert(contentCn);
	}

### 报错信息
org.springframework.dao.DataIntegrityViolationException: 
### Cause: java.sql.SQLException: Field 'id' doesn't have a default value
; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value

**Comment by miemieYaho** [comment]
https://mp.baomidou.com/config/generator-config.html

**Comment by md51111** [comment]
能详细点吗，配置都看了，也试了，谢谢了
