### ISSUE TITLE
对数据库sqlserver2005的分页支持

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#84]
2.0.9的版本 对sqlserver2005的分页支持有问题 不能识别sqlserver2005的方言
#数据库驱动
driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#测试地址
url=jdbc:sqlserver://192.168.1

**Comment by qmdx** [comment]
你可以自定义下 方言类，我们没有那么多环境多谢支持，可以的话可以 PR 给我们

**Comment by tianshishouhu** [comment]
2.0.9的版本已经提供sqlserver2005的方言，globalConfig已经注入dbType为sqlserver2005 <property name="dbType" value="sqlserver2005" /> 但是判断用哪个数据库的时候是用JdbcUtils的getDbType 是通过jdbcUrl来判断的 注入字段无效 
 else if (jdbcUrl.startsWith("jdbc:microsoft:") || jdbcUrl.startsWith("jdbc:log4jdbc:microsoft:")) {
            return DBType.SQLSERVER;
        } else if (jdbcUrl.startsWith("jdbc:sqlserver:") || jdbcUrl.startsWith("jdbc:log4jdbc:sqlserver:")) {
            return DBType.SQLSERVER2005;
        }
我通过源代码修改解决了这个问题 希望解决注入dbType属性，但是无效的注入，而是通过url来判断数据库的问题

**Comment by qmdx** [comment]
@tianshishouhu  确实 2.0.9 自动识别忽略了这个问题，已经修复 2.1-gamma 你试试

**Comment by tianshishouhu** [comment]
我测试了 2.1-gamma 确实解决了 但是还有个问题哈 插入数据 UUID获取不到 2.0.1的版本是可以的





在 2017-06-29 11:20:40，"qmdx" <notifications@github.com> 写道：


@tianshishouhu 确实 2.0.9 自动识别忽略了这个问题，已经修复 2.1-gamma 你试试

**Comment by qmdx** [comment]
@tianshishouhu   经过测 2.1-gamma  UUID 主键没有问题， 查看测试 

https://github.com/baomidou/mybatis-plus/blob/dev/src/test/java/com/baomidou/mybatisplus/test/h2/H2uuidTest.java
