### ISSUE TITLE
实体类字段是关键字问题

### ISSUE THREAD

**Issue by qqqqqqq1995** [baomidou/mybatis-plus#840]
### 当前使用版本(必须填写清楚，否则不予处理)
3.06

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

实体类无法处理属性值是关键字得情况

### 重现步骤
    @TableField(value = "is_read")
    private Boolean read;

**Comment by qmdx** [comment]
`@TableField(value = "`is_read`")`  注解转义，转义符 ```

**Comment by qqqqqqq1995** [comment]
is_read不是关键字，read才是，自动加得AS read 导致报错！

**Comment by miemieYaho** [comment]
规范你的字段名.不 as 无法映射
