### ISSUE TITLE
id问题

### ISSUE THREAD

**Issue by md51111** [baomidou/mybatis-plus#841]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
以前用的是mybatis，java开发我干了4年了，不是不会看文档调试，mybatis plus 刚接触，真的不会生成id，您能耐心点吗，谢谢了，生成的entity没有id时，mysql配置自增可以插入1,2的自增id，但不能使用deletebyid，自己添加了private Long id;时，是可以插入1089904636430700546这种id的，所以我想了解一下详细的解决办法，谢谢了

id，table_id是表中的字段，tableId有，但没有id,我之前没说清楚

**Comment by qqqqqqq1995** [comment]
有一个@TableId

**Comment by md51111** [comment]
这是生成的文件
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class ContentCn implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer tableId;

    private String field1;

    private String field2;

    private String field3;


}

**Comment by md51111** [comment]
数据表
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for content_cn
-- ----------------------------
DROP TABLE IF EXISTS `content_cn`;
CREATE TABLE `content_cn`  (
  `id` bigint(11) UNSIGNED NOT NULL,
  `table_id` int(11) NULL DEFAULT NULL,
  `field1` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `field2` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `field3` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

生成的entity
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class ContentCn implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer tableId;

    private String field1;

    private String field2;

    private String field3;


}

generator配置
public static void main(String[] args) {
        // 代码生成器
        AutoGenerator mpg = new AutoGenerator();

        // 全局配置
        GlobalConfig gc = new GlobalConfig();
        String projectPath = System.getProperty("user.dir");
        gc.setOutputDir(projectPath + "/src/main/java");
        gc.setAuthor("");
        gc.setOpen(false);
        gc.setIdType(ID_WORKER);
        mpg.setGlobalConfig(gc);

        // 数据源配置
        DataSourceConfig dsc = new DataSourceConfig();
        dsc.setUrl("jdbc:mysql://127.0.0.1:3306/aa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false");
        // dsc.setSchemaName("public");
        dsc.setDriverName("com.mysql.cj.jdbc.Driver");
        dsc.setUsername("root");
        dsc.setPassword("");
        mpg.setDataSource(dsc);

        // 包配置
        PackageConfig pc = new PackageConfig();
        pc.setModuleName(scanner("模块名"));
        pc.setParent("com.example.myjxb");
        mpg.setPackageInfo(pc);

        // 自定义配置
        InjectionConfig cfg = new InjectionConfig() {
            @Override
            public void initMap() {
                // to do nothing
            }
        };
        List<FileOutConfig> focList = new ArrayList<>();
        focList.add(new FileOutConfig("/templates/mapper.xml.ftl") {
            @Override
            public String outputFile(TableInfo tableInfo) {
                // 自定义输入文件名称
                return projectPath + "/src/main/resources/mapper/" + pc.getModuleName()
                        + "/" + tableInfo.getEntityName() + "Mapper" + StringPool.DOT_XML;
            }
        });
        cfg.setFileOutConfigList(focList);
        mpg.setCfg(cfg);
        mpg.setTemplate(new TemplateConfig().setXml(null));

        // 策略配置
        StrategyConfig strategy = new StrategyConfig();
        strategy.setNaming(NamingStrategy.underline_to_camel);
        strategy.setColumnNaming(NamingStrategy.underline_to_camel);
        //strategy.setSuperEntityClass("com.my.common.BaseEntity");
        strategy.setEntityLombokModel(true);
        //strategy.setSuperControllerClass("com.my.common.BaseController");
        strategy.setInclude(scanner("表名"));
        strategy.setSuperEntityColumns("id");
        strategy.setControllerMappingHyphenStyle(true);
        strategy.setTablePrefix(pc.getModuleName() + "_");
        mpg.setStrategy(strategy);
        // 选择 freemarker 引擎需要指定如下加，注意 pom 依赖必须有！
        mpg.setTemplateEngine(new FreemarkerTemplateEngine());
        mpg.execute();
    }

后来
   // 全局配置
    GlobalConfig gc = new GlobalConfig();
    String projectPath = System.getProperty("user.dir");
    gc.setOutputDir(projectPath + "/src/main/java");
    gc.setAuthor("");
    gc.setOpen(false);
    gc.setIdType(ID_WORKER);
    mpg.setGlobalConfig(gc);
加了IdType，写了ID_WORKER，IdType.ID_WORKER，AUTO，IdType.AUTO，IdType.INPUT
都不生成id

**Comment by qqqqqqq1995** [comment]
strategy.setSuperEntityColumns("id"); 
你配置了这个，表明你把id放到了baseEntity里。

**Comment by md51111** [comment]
注释掉可以生成id,真的非常感谢

官方文档感人
superEntityColumns
自定义基础的Entity类，公共字段

**Comment by BARERM** [comment]
遇到同样的问题，官方的生成Demo简直了。
id现在插入还是一串数字，并没有使用数据库里的自增id，全局id-type也设置了，@TableId也设置了。
依然没有用，版本3.0.7.1和3.1.0
