### ISSUE TITLE
使用AR模式查询时selectById()为什么不是返回对象本身?

### ISSUE THREAD

**Issue by iamya** [baomidou/mybatis-plus#845]
### 当前使用版本(必须填写清楚，否则不予处理)
 <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.0.7.1</version>
</dependency>

### 重现步骤
    @Test
    public void testAR() {
        User user = new User();
        user.setId(1L);
        User user1 = user.selectById();
        System.out.println(user1);
        System.out.println(user == user1);
    }

**Comment by miemieYaho** [comment]
不是
