### ISSUE TITLE
mybatis plus 这么强大，为什么不支持一对多 多对多这样的关联查询呢？

### ISSUE THREAD

**Issue by BigBigBIgMan** [baomidou/mybatis-plus#848]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

表关系，一对多，很常用呀，为什么不支持呢？

### 重现步骤

表关系，一对多，很常用呀，为什么不支持呢？

### 报错信息

表关系，一对多，很常用呀，为什么不支持呢？

**Comment by qmdx** [comment]
mp 定位是辅助 m 简化 crud 而不是成为 hibernate
