### ISSUE TITLE
插入记录 UUID获取不到

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#85]
<property name="idType" value="3" />
已经配置为UUID->`3`("全局唯一ID")了
2.1-gamma

**Comment by qmdx** [comment]
没有问题的，查看下测试用例 https://github.com/baomidou/mybatis-plus/blob/master/src/test/java/com/baomidou/mybatisplus/test/h2/H2uuidTest.java

**Comment by tianshishouhu** [comment]
我看了一下测试用例 是因为    /**
     * 主键
     */
    @TableId(type = IdType.UUID)
    private String id;


我的id字段上没有注解的 
extends Model<User>
	private String id;
	@Override
	protected Serializable pkVal() {
		return this.id;
	}
也就是全局注入无效 bi

**Comment by tianshishouhu** [comment]
你好 今天我把源码git下来了 发现有两个问题向你请教
1 com.oracle:ojdbc14:ja， com.microsoft.sqlserver:sqljdbc4:jar这两个数据库的jar包我这边是报错的 你那是怎么处理的 是本地导入？
2 发现com.baomidou.mybatisplus.test.h2.entity.persistent.H2uuid没有getId()方法，但是你提供的junit测试中调用了 还有
try (Connection conn = ds.getConnection()) { 这个我这里有语法问题 你那没有？ 期待你的回信






在 2017-06-30 15:42:28，"qmdx" <notifications@github.com> 写道：


Reopened #85.

**Comment by svatiYu** [comment]
1本地导入，
2，java7语法

**Comment by svatiYu** [comment]
@tianshishouhu
1本地导入，
2，java7语法
