### ISSUE TITLE
mybatis-plus 3.0 如何手动调用分页代码

### ISSUE THREAD

**Issue by 39301568aqq** [baomidou/mybatis-plus#850]
SqlHelper.fillWrapper(page, entityWrapper);
TableInfo tableInfo = (TableInfo) fromEntity.mEntityMap.get("tableInfo");
String mapper = tableInfo.getCurrentNamespace();
List list = sqlSessionTemplate.selectList(mapper + ".selectPage", parmas, page);
page.setRecords(list);

mybatis-plus 2.0中通过代码可以调用分页，3.0怎么实现以上功能

**Comment by Cat7373** [comment]
带高亮的代码：

```java
SqlHelper.fillWrapper(page, entityWrapper);
TableInfo tableInfo = (TableInfo) fromEntity.mEntityMap.get("tableInfo");
String mapper = tableInfo.getCurrentNamespace();
List list = sqlSessionTemplate.selectList(mapper + ".selectPage", parmas, page);
page.setRecords(list);
```

**Comment by qmdx** [comment]
参考文档 https://mp.baomidou.com/guide/page.html
原理不变，无非就是 IPage 接口化自动注入 list 部分
