### ISSUE TITLE
模糊查询的时候特殊符号没有处理，如参数为%时，生成的sql是 like '%%%'

### ISSUE THREAD

**Issue by After1991620** [baomidou/mybatis-plus#855]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
模糊查询的时候，参数为%，生成的sql是 like '%%%'，查询结果不正确

### 重现步骤
模糊查询的时候，参数为%

### 报错信息
没有报错，查询结果不正确

**Comment by Tianner** [comment]
没转义吧。like '%\%%'

**Comment by qmdx** [comment]
你觉得应该如何转义？

**Comment by cwt9562** [comment]
我觉得，可以尝试增加一个配置项
当配置开启时，将%转义为\%
本来是 like concat('%', '%', '%')
变成  like concat('%', '\%', '%')

可能 不同数据库的语法不同，转义的方式也会不一样
