### ISSUE TITLE
@TableField(exist=false)  不起作用

### ISSUE THREAD

**Issue by weir2010** [baomidou/mybatis-plus#856]
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'permission_ids' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'permission_ids' in 'field list']

 @TableField(exist=false)
    private String permissionIds;

**Comment by miemieYaho** [comment]
请给出复现 demo

**Comment by weir2010** [comment]
问题我已经截图到讨论群里面了

**Comment by Yuck1125** [comment]
你好 你这个问题解决了吗

**Comment by weir2010** [comment]
解决了

**Comment by zhanglindeng** [comment]
@weir2010 您好，出现同样的问题，请问是如何解决的呢？用的版本是 3.1.0

**Comment by weir2010** [comment]
升级下 当时是注解在不同的包里面引起的，mp改动造成的  用最新的版本试试
