### ISSUE TITLE
引入pageHelper后分页无法正常使用

### ISSUE THREAD

**Issue by TianPu8153** [baomidou/mybatis-plus#857]
### 当前使用版本(必须填写清楚，否则不予处理)
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <mybatis-plus-boot-starter.version>2.3</mybatis-plus-boot-starter.version>
        <mybatisplus.version>2.3</mybatisplus.version>
    </properties>
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
之前项目没有引入pageHelper，能够正常运行分页功能，引入之后发现

selectPage(page,new EntityWrapper<TbTask>().like("task_name",key)); //page.setSize(10);

会查找整个数据库，之前设置的pageSize完全不起作用。怀疑是与pageHelper有冲突，请问这个该怎么解决呢？

### 重现步骤

selectPage(page,new EntityWrapper<TbTask>().like("task_name",key)); //page.setSize(10);
查询的范围和返回结果与预期不符。我只想返回10条，但是实际上会返回符合条件的所有数据。

### 报错信息

没有报错信息...

我是个菜鸟，希望大神能详细点解答，谢谢！

**Comment by miemieYaho** [comment]
分页插件只能留下一个

**Comment by qmdx** [comment]
请使用 mp 内置分页模式 pageHelper 不支持

**Comment by 5468sun** [comment]
奇怪了，我mp内置分页插件和pageHelper 可以共存使用得。
我得配置是这样滴。

`<property name="plugins">
            <array>
                
                
                      
                    
                

                
                <bean class="com.github.pagehelper.PageInterceptor">
                    <property name="properties">
                        <value>
                            helperDialect=mysql
                            reasonable=true
                            rowBoundsWithCount=true
                            pageSizeZero=true
                            offsetAsPageNum=true
                        </value>
                    </property>
                </bean>
            </array>
        </property>`
