### ISSUE TITLE
怎样支持postgresql 的序列自增

### ISSUE THREAD

**Issue by hongliangpan** [baomidou/mybatis-plus#859]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

怎样支持postgresql 的序列自增
Postgresql中的 nextval('序列名')
类似如下：
	<insert id="saveGoods" parameterType="cn.zhsz.model.admin.Goods">
		insert into t_crud 
			values (nextval('seq_crud'),#{name},#{type},#{price})
	</insert>
参考
https://blog.csdn.net/wlwlwlwl015/article/details/48652009

**Comment by miemieYaho** [comment]
不支持
