### ISSUE TITLE
Page的属性condition不起查询作用

### ISSUE THREAD

**Issue by dhzxzzh** [baomidou/mybatis-plus#86]
代码如下
    @Test
    public void testQueryCondition(){
    	Page<SysUser> page = new Page<SysUser>(1,1);
    	Map<String,Object> condition = new HashMap<String,Object>();
    	condition.put("account", "admin");
    	page.setCondition(condition);
    	Page<SysUser> result =  sysUserService.selectPage(page);
    	Assert.assertTrue(result.getTotal()==1);
    }

执行的语句，没有“account=admin”这个语句

**Comment by jifuwei** [comment]
我感觉这个是告知当前查询的condition是哪一些，只是告知，实现的话还是需要交给wrapper来的

**Comment by yuxiaobin** [comment]
这里确实是一个bug。

已修复。

参考：
http://git.oschina.net/baomidou/mybatis-plus/commit/c7483c12a0cf97ab2228510086ab4c258e4935dc
