### ISSUE TITLE
这个还是太重了，能不能提个轻的包

### ISSUE THREAD

**Issue by ZJZZuse** [baomidou/mybatis-plus#861]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
不用替换工厂bean，提供功能。另外建议用bom的形式引入依赖，可以抽个小包去掉mybatis和mybatis spring的依赖，使插件更纯粹化，侵入性更小

**Comment by hcl04** [comment]
spring依赖的问题我们目前正在关注，稍后将准备着手解决该问题，感谢您的建议！

**Comment by qmdx** [comment]
已经很轻了各模块可以分开使用，如果有更好的完善欢迎 PR

**Comment by yuxiaobin** [comment]
core模块就已经可以注入CRUD，参考：MybatisMapperAnnotationBuilder

**Comment by ZJZZuse** [comment]
希望可以提供文档方便接入单独模块：）
