### ISSUE TITLE
希望查询返回值能支持optional

### ISSUE THREAD

**Issue by shengxiluo20** [baomidou/mybatis-plus#863]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

希望查询返回值能支持optional

**Comment by miemieYaho** [comment]
下个版本

**Comment by shengxiluo20** [comment]
多谢
