### ISSUE TITLE
3.0.7 GlobalConfigUtils中的方法getGlobalConfig可否获取全局配置

### ISSUE THREAD

**Issue by xuyuany2010** [baomidou/mybatis-plus#865]
### 当前使用版本(必须填写清楚，否则不予处理)

最新版本，使用springmvc，mybatis-plus/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/toolkit/GlobalConfigUtils.java
方法getGlobalConfig无法获取全局配置，可否调整获取全局配置，当全局配置没有时再获取默认配置

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

sqlSessionFactoryBean配置globalConfig无效

### 重现步骤

sqlSessionFactoryBean配置globalConfig无效

### 报错信息
信息不对称

**Comment by miemieYaho** [comment]
demo呢?

**Comment by xuyuany2010** [comment]
![image](https://user-images.githubusercontent.com/24486812/53136013-5eaa8980-35b8-11e9-820c-1d95e4105707.png)
![image](https://user-images.githubusercontent.com/24486812/53136070-86015680-35b8-11e9-9097-1a04b512ade7.png)
我的意思这里能否取springxml中的配置初始化

**Comment by qmdx** [comment]
> ![image](https://user-images.githubusercontent.com/24486812/53136013-5eaa8980-35b8-11e9-820c-1d95e4105707.png)
> ![image](https://user-images.githubusercontent.com/24486812/53136070-86015680-35b8-11e9-9097-1a04b512ade7.png)
> 我的意思这里能否取springxml中的配置初始化

不可以的

**Comment by xuyuany2010** [comment]
![image](https://user-images.githubusercontent.com/24486812/53136355-a4b41d00-35b9-11e9-926b-3732022eb2ce.png)
那这个配置就是用不了了

**Comment by xuyuany2010** [comment]
是没法获取，还是贵项目不想这么实现呢
