### ISSUE TITLE
自定义主键问题

### ISSUE THREAD

**Issue by blackscarf** [baomidou/mybatis-plus#868]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
自定义主键问题，plus提供三种主键【ID_WORKER、ID_WORKER_STR 、UUID ；】
/* 自定义元对象填充控制器 */
        MetaObject metaObject = ms.getConfiguration().newMetaObject(parameterObject);
        if (ms.getSqlCommandType() == SqlCommandType.INSERT) {
            if (tableInfo.getIdType().getKey() >= 2) {
                Object idValue = metaObject.getValue(tableInfo.getKeyProperty());
                /* 自定义 ID */
                if (StringUtils.checkValNull(idValue)) {
                    if (tableInfo.getIdType() == IdType.ID_WORKER) {
                        metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.getId());
                    } else if (tableInfo.getIdType() == IdType.ID_WORKER_STR) {
                        metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.getIdStr());
                    } else if (tableInfo.getIdType() == IdType.UUID) {
                        metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.get32UUID());
                    }
                }
            }

我们需要根据业务场景自定义主键；
不想在自己调用entity时手动set进去；
请问大神还有其他办法没有？谢谢
ps：自己尝试过重写来覆盖 plus 提供的save、saveBatch等方法，但是想请教下有没有更好的办法

### 重现步骤

如题

### 报错信息
如题

**Comment by miemieYaho** [comment]
可以使用自动填充功能,除此之外没有

**Comment by blackscarf** [comment]
请问下自动填充怎么玩的，有没有文档链接，谢谢
