### ISSUE TITLE
openjdk:8-jdk-alpine 不支持lambda

### ISSUE THREAD

**Issue by jinweida** [baomidou/mybatis-plus#869]
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
        </dependency>

用的这个版本，dockerfile->FROM openjdk:8-jdk-alpine ,使用lambda表达式报错了，不支持吗？

**Comment by miemieYaho** [comment]
请使用标准 jdk

**Comment by jinweida** [comment]
您说的使用oracle jdk吗

**Comment by miemieYaho** [comment]
正宗的 oraclejdk 或者 openjdk
