### ISSUE TITLE
insertBatch()在某些情况下执行不生效

### ISSUE THREAD

**Issue by jpr1990** [baomidou/mybatis-plus#87]
2.0.7遇到一个问题：
06-23 13:52:25-464 ERROR [ dou.mybatisplus.service.impl.ServiceImpl:135 ] Error: Cannot execute insertBatch Method. Cause:org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.common.dao.OperationLogMapper.insert

我在执行一个单元测试发现过不了！

 List<OperationLog> logs = Lists.<OperationLog>newArrayList();
        OperationLog log = OperationLog.builder().operatorId(2L).operatorName("2").createTime(new Date()).resource("/reason").build();
        logs.add(log);
        operationLogService.insertBatch(logs);

使用的是mybatis-plus批量插入的方法，你知道是什么原因吗？

使用insert（）方法是正常的。

**Comment by jpr1990** [comment]
问题已经解决。


### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.common.dao.OperationLogMapper.insert
mybatis-plus被加载了2次，第一次生成了实体类的对应insert sql;
但第二次加载却覆盖了第一次的生成，并且没有对应的insert sql 了所以报错。
发生的原因，定义了2个datasource,都配置了<property name="globalConfig" ref="globalConfig"/>

<bean id="ucSqlSessionFactory" class="com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean">
        <property name="dataSource" ref="ucDataSource" />
        
        <property name="configLocation" value="classpath:mybatis-config.xml"/>
        <property name="mapperLocations" value="classpath*:mapper/demo/*.xml" />
        <property name="plugins">
            <array>
                
                <bean id="paginationInterceptor" class="com.baomidou.mybatisplus.plugins.PaginationInterceptor">
                    <property name="dialectType" value="mysql" />
                </bean>
                <bean class="com.wlqq.ucs.common.page.PageInterceptor" />
            </array>
        </property>
        <property name="globalConfig" ref="globalConfig"/>
    </bean>

	
    <bean id="sqlSessionFactory" class="com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean">
        <property name="dataSource" ref="multipleDataSource"/>
        
        <property name="configLocation" value="classpath:mybatis-config.xml"/>
        <property name="mapperLocations" value="classpath*:mapper/main/*.xml"/>
        <property name="plugins">
            <array>
                
                <bean id="paginationInterceptor" class="com.baomidou.mybatisplus.plugins.PaginationInterceptor">
                   <property name="dialectType" value="mysql" />
                </bean>
                <bean class="com.wlqq.ucs.common.page.PageInterceptor"/>
            </array>
        </property>
        <property name="globalConfig" ref="globalConfig"/>
    </bean>
	
	
	
    <bean id="globalConfig" class="com.baomidou.mybatisplus.entity.GlobalConfiguration">
        
        
        <property name="idType" value="0"/>

        
        
        <property name="dbType" value="mysql"/>

        
        <property name="dbColumnUnderline" value="true"/>
    </bean>


	
通过检查debug日志发现的。	
log4j.logger.com.baomidou=debug



删除掉任意一个datasource中的<property name="globalConfig" ref="globalConfig"/>配置即可

**Comment by qmdx** [comment]
解决了就好！多谢支持。
