### ISSUE TITLE
增强 mybatis对JSON的支持

### ISSUE THREAD

**Issue by biexuxiaoyao** [baomidou/mybatis-plus#870]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
1.查询问题 ，数据表定义的JSON字段，使用内置的查询方法，取出为空，需要手写sql
2.希望增加 全局 typeHandler 配置处理，自动识别需要转换的类型（非字段上指定）
   如JSON，Enum类型等

**Comment by miemieYaho** [comment]
mybatis 有
