### ISSUE TITLE
当Mapper.xml中使用级联查询时，分页功能出现问题

### ISSUE THREAD

**Issue by Hunter0125** [baomidou/mybatis-plus#871]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
在Mapper.xml文件的resultMap标签中使用级联标签，对应下方查询语句是多表联合查询，此时返回结果中针对resultMap标签的最外层属性是冗余出现的，所以Ipage统计的是冗余后的行数。
但是，业务需要的却是resultMap标签最外层属性冗余前的行数。希望能进行优化。

**Comment by miemieYaho** [comment]
自行进行count查询

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/568
