### ISSUE TITLE
FieldStrategy.IGNORED注解属性作为查询条件

### ISSUE THREAD

**Issue by suspring** [baomidou/mybatis-plus#872]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
一般在修改某个字段的值为null时，需要在对应实体上添加strategy = FieldStrategy.IGNORED注解处理，但是当加上该注解后，我们通过service.list(QueryWrapper)构建查询条件是，有该注解的字段不管是否为null都会作为条件

### 重现步骤
比如实体：User
有属性：
    @TableField(value = "USERNAME",strategy = FieldStrategy.IGNORED)
    private String username;

    QueryWrapper<User> wrapper = new QueryWrapper<User>(new User());
    userService.list(wrapper);

生成对应sql：.....where USERNAME = ?
既然该字段可以为空，为何一定为作为查询条件，即使作为查询 条件，为何没有对null处理

**Comment by miemieYaho** [comment]
不会处理,就是这样的

**Comment by suspring** [comment]
> 不会处理,就是这样的

那通过实体构建查询条件就永远查不到到东西了？这设计上不就有问题了

**Comment by yuxiaobin** [comment]
FieldStrategy.IGNORED ： ignore表示不处理，不做null非null判断，所以不管是更新/还是查询都会拼接该字段，逻辑没毛病

**Comment by yuxiaobin** [comment]
除非还需要指定 IGNORE的时机：比如 UPDATE_ONLY, 但是目前没有

**Comment by suspring** [comment]
> FieldStrategy.IGNORED ： ignore表示不处理，不做null非null判断，所以不管是更新/还是查询都会拼接该字段，逻辑没毛病

就是因为该字段没有判断 所以在拼接sql的时候才可能出现null，才需要做处理

**Comment by iteaj** [comment]
我觉得是否可以再加入一个字段判断， 很多时候表的某些字段是不需要加入查询条件的， 比如：remark,icon等这些字段， 现在的做法需要将每个不需要加入的字段置为null很麻烦

**Comment by yuxiaobin** [comment]
> 我觉得是否可以再加入一个字段判断， 很多时候表的某些字段是不需要加入查询条件的， 比如：remark,icon等这些字段， 现在的做法需要将每个不需要加入的字段置为null很麻烦

不想select出来，可以这样：

1. 使用wrapper.select()--指定你想select出来的字段
2. TableField(select=false) 参考[TableField注解说明](https://mybatis.plus/guide/annotation.html#tablefield)
