### ISSUE TITLE
使用 new QueryWrapper(entity), 在xml中的${ew.customSqlSegment}  不能自动生成不为空的字段查询

### ISSUE THREAD

**Issue by xy0601** [baomidou/mybatis-plus#876]
### 当前使用版本(必须填写清楚，否则不予处理)

v3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

QueryWrapper<CarOwnerInfo> diseaseQueryWrapperw = new QueryWrapper<CarOwnerInfo>(carOwnerInfo);

public interface CarOwnerInfoMapper extends BaseMapper<CarOwnerInfo> {
    IPage<CarOwnerInfo> selectPageVo(Page page, @Param(Constants.WRAPPER) Wrapper<CarOwnerInfo> wrapper);
}

<select id="selectPageVo" resultMap="getClassMap">
        select * from tb_car_owner_info coi  left join sys_user u on coi.user_no = u.user_no ${ew.customSqlSegment}
    </select>

### 报错信息

获取不到QueryWrapper entity 自动不为空的字段查询语句

**Comment by miemieYaho** [comment]
本来就没有 entity 的信息
