### ISSUE TITLE
mysql表的id为bigint自增主键，插入时并没有自增而是一串数字

### ISSUE THREAD

**Issue by BARERM** [baomidou/mybatis-plus#877]
### 当前使用版本(必须填写清楚，否则不予处理)
Mybatis Plus 3.1.0
SpringBoot 2.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
Mysql表id为bigint类型自增主键，使用mybatis plus的save方法插入实体成功后，发面id为一串数字。
并没有按数据库自增。

### 重现步骤
如下是springboot的application.yml配置：
`mybatis-plus:`
`global-config:`
  `  db-config:`
    `  id-type: auto`
已经设置了全局的id-type为auto。

如下是生成的实体：
`private static final long serialVersionUID = 1L;`
    `@TableId(value = "id", type = IdType.AUTO)`
    `private Long id;`

### 报错信息
数据插入结果：
`id`
`1100827025365626881`
`1100827025365626882`
`1100827025365626883`
`1100827025365626884`
`1100827025365626885`
`1100827025365626886`

**Comment by qmdx** [comment]
你仔细看看你的 id 在增长，应该是你第一次使用了非自增插入了一个大的 id ，删除表新建自增从0 开始

**Comment by BARERM** [comment]
> 你仔细看看你的 id 在增长，应该是你第一次使用了非自增插入了一个大的 id ，删除表新建自增从0 开始

万分感谢 ！！
