### ISSUE TITLE
设置field-strategy: 2 无效

### ISSUE THREAD

**Issue by mr-ape** [baomidou/mybatis-plus#878]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.0.7.1</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
field-strategy: 2 和field-strategy: 1的效果是一样的

### 重现步骤
1.配置 field-strategy: 2 ，仍然可以更新空字符串，和配置 field-strategy: 1的作用是一样的
2.使用字段注解：@TableField(value = "name",strategy = FieldStrategy.NOT_EMPTY) 时，则name字段为null或这为空字符串都不可更新
3.难道非空判断只有使用注解时才可以吗？

### 报错信息
没有报错信息，通过打印sql信息判断name是否为set中的字段

**Comment by qmdx** [comment]
UpdateWrapper 方法 https://mybatis.plus/guide/wrapper.html#set

**Comment by ThinWonton** [comment]
从2.3.0开始
在 TableFieldInfo 类中获取field-strategy的方式就一直存在BUG
`
public TableFieldInfo(GlobalConfiguration globalConfig, TableInfo tableInfo, String column,
                          String el, Field field, TableField tableField) {
    
        /*
         * 优先使用单个字段注解，否则使用全局配置
		 */
        if (globalConfig.getFieldStrategy() != tableField.strategy()) {
           // 只要是全局配置和tableField注解的strategy默认值不一致，这一句永远执行，也就是全局配置无效！！！！！！！
            this.fieldStrategy = tableField.strategy();
        } else {
            this.fieldStrategy = globalConfig.getFieldStrategy();
        }
     
    }
`

**Comment by miemieYaho** [comment]
> 从2.3.0开始
> 在 TableFieldInfo 类中获取field-strategy的方式就一直存在BUG
> `
> public TableFieldInfo(GlobalConfiguration globalConfig, TableInfo tableInfo, String column,
> String el, Field field, TableField tableField) {
> 
> ```
>     /*
>      * 优先使用单个字段注解，否则使用全局配置
> 	 */
>     if (globalConfig.getFieldStrategy() != tableField.strategy()) {
>        // 只要是全局配置和tableField注解的strategy默认值不一致，这一句永远执行，也就是全局配置无效！！！！！！！
>         this.fieldStrategy = tableField.strategy();
>     } else {
>         this.fieldStrategy = globalConfig.getFieldStrategy();
>     }
>  
> }
> ```
> `

你有看过最新代码吗?
