### ISSUE TITLE
Wrapper 自定义SQL 到底怎么用？

### ISSUE THREAD

**Issue by ESHidden** [baomidou/mybatis-plus#879]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
官方文档：
![image](https://user-images.githubusercontent.com/28656389/53538728-da24b180-3b49-11e9-82e6-d4a9e555668b.png)
实践测试：
![image](https://user-images.githubusercontent.com/28656389/53541347-65a34000-3b54-11e9-9a20-96ada3199d56.png)
报错：
![image](https://user-images.githubusercontent.com/28656389/53538756-ee68ae80-3b49-11e9-8fba-52d53ef1ae73.png)

这到底怎么用，我有哪些细节没注意到吗？
### 重现步骤
使用 Wrapper 自定义SQL
按照指导文档使用报错
### 报错信息

org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'ew' in 'class com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper'

**Comment by ESHidden** [comment]
求大神指导！！！

**Comment by miemieYaho** [comment]
无法复现,给你你的复现 demo

**Comment by ESHidden** [comment]
> 无法复现，给出你的复现演示

service:
![image](https://user-images.githubusercontent.com/28656389/53552890-5bdf0400-3b77-11e9-81fb-11d1040a9e8c.png)
mapper:
![image](https://user-images.githubusercontent.com/28656389/53552933-73b68800-3b77-11e9-8ec6-81fd567f3826.png)
就这些，我这里一直报错

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/base/mapper/commons/CommonLogicDataMapper.java
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/MysqlTestDataMapperTest.java
无法复现

**Comment by ESHidden** [comment]
> https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/base/mapper/commons/CommonLogicDataMapper.java
> https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/mysql/MysqlTestDataMapperTest.java
> 无法复现
我全部的配置就这些：
![image](https://user-images.githubusercontent.com/28656389/53555514-0c9bd200-3b7d-11e9-997d-ce0e77e7bb64.png)
![image](https://user-images.githubusercontent.com/28656389/53555652-4cfb5000-3b7d-11e9-9781-ffadd2e0fb5f.png)

**Comment by miemieYaho** [comment]
我不看你的配置,我要你的复现demo

**Comment by miemieYaho** [comment]
先好好检查你的 `@Param` 是不是对的吧

**Comment by ESHidden** [comment]
我用错了，用的是spring的

**Comment by mushroomlb** [comment]
import org.apache.ibatis.annotations.Param;
