### ISSUE TITLE
selectCount(wrapper) 查询记录数的时候如果有排序字段报错

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#88]
wrapper.orderBy("insp_time", false);
selectCount(wrapper) 查询记录数的时候如果有排序字段报错

我用的是sqlserver2005

**Comment by Caratacus** [comment]
并无该问题,请继续反馈

**Comment by tianshishouhu** [comment]
我用最新的版本测试（2.1.0）还是有这个问题
		Wrapper<User> wrapper = new EntityWrapper<User>();
		wrapper.between("create_time", "2017-08-08 00:00:00", "2017-08-08 23:59:59");
		wrapper.orderBy("create_time", false);
		int total = userDao.selectCount(wrapper);

如果wrapper.orderBy("create_time", false);注释掉正常 
报错是com.microsoft.sqlserver.jdbc.SQLServerException:ORDER BY 子句中的列 "user.create_time" 无效，因为该列没有包含在聚合函数或 GROUP BY 子句中。
我觉得如果是求count 应该过滤掉排序字段

**Comment by liuboBobo** [comment]
我也有同样的问题，sqlserver2008r2

**Comment by Caratacus** [comment]
这是sqlserver语法的问题,selectCount Wrapper为什么要给orderby在里面赋值(本身查询出来的就是一个count数，就一个数为什么还要排序呢)?

**Comment by tianshishouhu** [comment]
语法确实有问题，我的意思说让程序做一些容错处理，如果是根据直接查Page对象，你觉得我有排序字段，能查出Page出来么

**Comment by qmdx** [comment]
这应该不算 bug count 排序也无意义
