### ISSUE TITLE
skipView sqlserver2017 设置无效

### ISSUE THREAD

**Issue by jiushizyj** [baomidou/mybatis-plus#880]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-generator 
3.0.7.1

### 重现步骤
skipView 设置无效视图会被生成

### 报错信息
无报错信息

**Comment by qmdx** [comment]
暂无该数据库无法测试，欢迎修复 pr

**Comment by jiushizyj** [comment]
sqlserver2012 也有该问题

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/886
