### ISSUE TITLE
关于批量提交

### ISSUE THREAD

**Issue by blackscarf** [baomidou/mybatis-plus#883]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

发现plus的批量保存是假批量保存，导致性能底下，如图，实际测试插入1000条记录需要30秒
请问会考虑实现真批量插入不，1000条的sql一次性执行，而不是循环执行1000条sql
 @Transactional(rollbackFor = Exception.class)
    @Override
    public boolean saveBatch(Collection<T> entityList, int batchSize) {
        SqlSession batchSqlSession = sqlSessionBatch();
        int i = 0;
        String sqlStatement = sqlStatement(SqlMethod.INSERT_ONE);
        try {
            for (T anEntityList : entityList) {
                batchSqlSession.insert(sqlStatement, anEntityList);
                if (i >= 1 && i % batchSize == 0) {
                    batchSqlSession.flushStatements();
                }
                i++;
            }
            batchSqlSession.flushStatements();
        } finally {
            closeSqlSession(batchSqlSession);
        }
        return true;
    }

**Comment by qmdx** [comment]
https://mybatis.plus/guide/faq.html#%E9%80%9A%E7%94%A8-insertbatch-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%BE%E5%9C%A8-service-%E5%B1%82%E5%A4%84%E7%90%86
