### ISSUE TITLE
设置多租户后，在自动填充租户ID字段，会导致插入数据库多次租户ID异常

### ISSUE THREAD

**Issue by kakablueair** [baomidou/mybatis-plus#884]
### 当前使用版本(必须填写清楚，否则不予处理)

使用版本为3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
设置多租户处理后，在实体类中租户字段增加【fill = FieldFill.INSERT】，在自动填充中对租户字段进行填充，会在编辑后的sql中出现多个租户字段信息

**Comment by miemieYaho** [comment]
使用多租户不要 entity 里出现租户字段

**Comment by youapple** [comment]
这样确实可以解决插入问题，但是这样查询时就无法返回租户字段了，实际有这种需求
