### ISSUE TITLE
mybatis-plus必须使用spring吗？不使用spring是否可以使用？

### ISSUE THREAD

**Issue by yangdc521** [baomidou/mybatis-plus#887]
mybatis-plus 必须使用spring吗？不使用spring是否可以使用？

**Comment by miemieYaho** [comment]
可以,用 `MybatisSqlSessionFactoryBuilder` 和 `MybatisConfiguration` 替换 `mybatis` 自己的 `SqlSessionFactoryBuilder` 和 `Configuration` 进行构造

**Comment by yangdc521** [comment]
好的。感谢，我研究下

**Comment by yangdc521** [comment]
你好，不用spring,,,源码中 依赖注入的类的属性如何处理？

**Comment by miemieYaho** [comment]
不用 spring 就不要用 我们提供的 service 选装件

**Comment by yangdc521** [comment]
好的谢谢
