### ISSUE TITLE
请问MyBatis Plus的启动Banner如何设置？

### ISSUE THREAD

**Issue by BARERM** [baomidou/mybatis-plus#888]
### 当前使用版本(必须填写清楚，否则不予处理)
MyBatis Plus 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
启动时显示如下Banner信息：
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.1.0 

### 重现步骤
启动项目时在控制台打印

### 报错信息
无报错，只是想去掉。因为打印出来日志工具无法识别。

**Comment by miemieYaho** [comment]
看文档

**Comment by BARERM** [comment]
> 看文档

文档找了半天确实没找到，麻烦您给个链接！ 谢谢了

**Comment by qmdx** [comment]
全局配置 banner = false

**Comment by BARERM** [comment]
非常感谢 ，文档中确实没找到～～

**Comment by nrxsh** [comment]
`
mybatis-plus:
  global-config:
    banner: false
`
