### ISSUE TITLE
mybatis plus的saveBatch方法建议

### ISSUE THREAD

**Issue by mackyuqimack** [baomidou/mybatis-plus#889]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
      <version>3.0.7.1</version>
    </dependency>
用的此版本的

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
我想做一个批量插入的功能希望是基于数据库的，不是基于ORM的，我测试了下mybatis plus的saveBatch方法日志为
==>  Preparing: INSERT INTO test ( name, dd_dd ) VALUES ( ?, ? ) 
==> Parameters: 测试1111(String), 批量插入11111(String)
==> Parameters: 测试22222(String), 批量插入22222(String)
能否支持INSERT INTO test ( name, dd_dd ) VALUES ( ?, ? ) ,( ?, ? ) ,( ?, ? ) ,( ?, ? ) 
这种拼接呢，这种批量插入的效率会高一些

**Comment by miemieYaho** [comment]
看文档

**Comment by qmdx** [comment]
https://mybatis.plus/guide/faq.html#%E9%80%9A%E7%94%A8-insertbatch-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%BE%E5%9C%A8-service-%E5%B1%82%E5%A4%84%E7%90%86

**Comment by boy9527** [comment]
saveBatch确实效率不高，麻烦还请优化下
