### ISSUE TITLE
当or跟where或者and一起使用时sql拼接问题

### ISSUE THREAD

**Issue by SmythAsen** [baomidou/mybatis-plus#890]
### 当前使用版本
mybatis-plus-boot-starter，2.2.0版本

当我使用EntityWrapper拼接多个or条件后，再使用eq或者where拼接条件时都会被默认加只or的括号中，在逻辑删除条件判断后的and括号中，导致这个条件的优先级降低从而不起作用，如果能有一个方法把他放到外面来跟逻辑删除一起判断就好了。
SELECT id ...fromg *** WHERE is_delete=0 AND (order_no LIKE ? OR......OR *** LIKE ? AND where条件字段=?)
上面这是大致的执行sql，逻辑删除会优先判断，优先级最高，但是我后来加的where条件字段却被降低了优先级。
举个例子：我从一张员工表中的表查询年龄在等于25岁的，但是名字like张三的 或者 昵称like张三的，代码大致如下：
new EntityWrapper<>().like("name","张三").or().like("nike_name","张三“).where("age={0}",25);
但是执行出来的sql却是：
select name,nike_name from workers where is_delete=0 and (name like ? or nike_name like? and age=25)
这样查询的话，其实年龄在30岁的叫张三的也给查出来了

**Comment by Cat7373** [comment]
emmm 看起来用的是 2.x？

**Comment by SmythAsen** [comment]
> emmm 看起来用的是 2.x？

是的，2.2.0。3.x已经修复了？

**Comment by miemieYaho** [comment]
> emmm 看起来用的是 2.x？

在不进来删你代码了啊

**Comment by Cat7373** [comment]
> > emmm 看起来用的是 2.x？
> 
> 在不进来删你代码了啊

如果能够让项目变的更好，那当然应该删，不过尽量注意不要影响到已经对外公开的东西，因此对外公开的东西相当于对用户的一种承诺，承诺说我会在这个大版本之内一直保证提供这个服务，你可以放心的升级。

移除公开的东西时尽量先标记过时和在文档中引导用户使用新的代替品，并一直保留到下个大版本再删除。

如果是针对我个人，那 emmm 你开心就好。。。

**Comment by SmythAsen** [comment]
> > > emmm 看起来用的是 2.x？
> > 
> > 
> > 在不进来删你代码了啊
> 
> 如果能够让项目变的更好，那当然应该删，不过尽量注意不要影响到已经对外公开的东西，因此对外公开的东西相当于对用户的一种承诺，承诺说我会在这个大版本之内一直保证提供这个服务，你可以放心的升级。
> 
> 移除公开的东西时尽量先标记过时和在文档中引导用户使用新的代替品，并一直保留到下个大版本再删除。
> 
> 如果是针对我个人，那 emmm 你开心就好。。。

啥情况，新版本修复了吗，我看了下如果升级到新版本的话改动很大，很多包的路径都变了，甚至方法名都变了……

**Comment by Cat7373** [comment]
@SmythAsen 较复杂的 SQL 建议直接在 Mapper 里写，如：

```java
/**
 * 基于名称或昵称，以及年龄查询用户
 * @param name 名称或昵称
 * @param age 年龄
 * @return 查询到的用户
 */
@Select({
        "SELECT",
        "  `id`,",
        "  `username`,",
        "  `password`,",
        "  `nickname`,",
        "  `age`",
        "FROM `user`",
        "WHERE (",
        "  `username` LIKE CONCAT('%', #{name}, '%') OR",
        "  `nickname` LIKE CONCAT('%', #{name}, '%')",
        ")",
        "AND `age` = #{age}"
})
List<User> listUserByNameAndAge(@Param("name") String name, @Param("age") int age);
```

这样看起来比较直观，也比较容易维护(当然也可以写进 xml 里)

**Comment by Cat7373** [comment]
@SmythAsen 没事没事，忽略中间那两句

**Comment by shengxiluo20** [comment]
加嵌套

**Comment by miemieYaho** [comment]
2.x 版本就是这样,尝试使用 orNew 和 andNew 方法
