### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by YAGAMIL** [baomidou/mybatis-plus#891]
### 请问deleteByMap listByMap等方法中需要传递的参数
例如List<T> selectByMap(@Param(Constants.COLUMN_MAP) Map<String, Object> columnMap)是用来做什么的，传入的Map<String, Object>中的String，Object分别指代什么东西或者应该如何赋值请提供案例;

**Comment by miemieYaho** [comment]
column : 值

**Comment by YAGAMIL** [comment]
那应该如何传参，这里的map应该怎样初始化？，有案例给看一下吗
