### ISSUE TITLE
表中存在联合主键时，@TableId注解声明问题

### ISSUE THREAD

**Issue by xingguang2013** [baomidou/mybatis-plus#893]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus 2.3.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

表存在联合主键，生成的model中将联合主键中的一个成员属性打上了@TableId注解，造成对表主键的误解

### 建议信息
 是否在遇到表是联合主键时，联合主键设置成@TableUnionId或复用@TableField注解。
@TableUnionId注解与@TableField注解功能类似，只是从名字上区分这是否是联合主键

**Comment by miemieYaho** [comment]
不能

**Comment by xingguang2013** [comment]
能否具体说明下原因，或者给个提示？

**Comment by miemieYaho** [comment]
mp 只且只会支持一个主键

**Comment by qmdx** [comment]
联合主键 mp 默认的 byId 方法将无法使用，你可以多个主键但是必须要一个逻辑主键

**Comment by xingguang2013** [comment]
感谢回复

**Comment by aohanhongzhi** [comment]
联合主键一般需要怎么解决比较好？xml文件？
