### ISSUE TITLE
带有分页查询的mapper，再传入Map参数，读取不到map里的参数

### ISSUE THREAD

**Issue by lipengjun92** [baomidou/mybatis-plus#894]
### 重现步骤
Mapper.java
List<User> selectUserPage(IPage page, Map<String, Object> params);

MybatisMapperMethod 里的executeForCursor方法
Object param = method.convertArgsToSqlCommandParam(args);
这一步把参数key都改变了，导致无法正确读取参数

### 报错信息
nested exception is org.apache.ibatis.binding.BindingException: Parameter 'userName' not found. Available parameters are [page, params, param1, param2]

**Comment by miemieYaho** [comment]
加注解,看文档和samples

**Comment by lipengjun92** [comment]
使用@Param("params") 可以解决，但是要在每个Mapper.java和Mapper.xml修改，能不能加个配置参数支持原生的写法

**Comment by miemieYaho** [comment]
不能
