### ISSUE TITLE
QueryWrapper有提供sum方法吗？

### ISSUE THREAD

**Issue by xl2790631** [baomidou/mybatis-plus#895]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
找不到sum方法

**Comment by xl2790631** [comment]
queryWrapper.select("sum(face_distinct_count)");
      
        return count(queryWrapper);

**Comment by xl2790631** [comment]
over

**Comment by user20161119** [comment]
> ```
>     return count(queryWrapper);
> ```

lambdaQuery就没办法这样用了吧？

**Comment by user20161119** [comment]
> queryWrapper.select("sum(face_distinct_count)");
> 
> ```
>     return count(queryWrapper);
> ```

`SELECT COUNT( sum(total) ) FROM ws_model_stat WHERE (tenantID = ? AND statYear = ? AND modelType = ?) `
按这个配置生成上面的sql,语法错误
