### ISSUE TITLE
升级3.0.7.1后问题

### ISSUE THREAD

**Issue by qiang6532** [baomidou/mybatis-plus#896]
继承BaseMapper 
1、@Select("select *")，结果找不到实体映射属性，必须@Select("select t.id....")，将每个字段写全。
2、单实体作为参数，必须增加@Param("")，不然会有绑定参数异常，SQL执行无法找到参数。
以上问题，不知道是否需要特殊配置？

**Comment by miemieYaho** [comment]
给出你的复现 demo

**Comment by lipengjun92** [comment]
https://github.com/baomidou/mybatis-plus/issues/894
和我的问题一样，必须添加@param
