### ISSUE TITLE
请问MybatisSqlSessionFactoryBean中引用的org.mybatis.logging.LoggerFactory来自哪个包

### ISSUE THREAD

**Issue by zyubupt** [baomidou/mybatis-plus#899]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
请问MybatisSqlSessionFactoryBean中引用的org.mybatis.logging.LoggerFactory来自哪个包

### 报错信息
![image](https://user-images.githubusercontent.com/5506056/53928759-3cd7f900-40c6-11e9-923e-726dfc2a00ee.png)

**Comment by huayanYu** [comment]
mybatis的包啊。
