### ISSUE TITLE
希望mybatis可以不用xml配置文件来操作数据库也可以自动生成表

### ISSUE THREAD

**Issue by TonyYule** [baomidou/mybatis-plus#9]
希望mybatis可以不用xml配置文件来操作数据库也可以自动生成表
可以参考nutz框架
nutz框架比mybatis方便很多

**Comment by yangyang0507** [comment]
从1.4.7起，已经支持了无xml也可以操作。  自动生成表，我们需要讨论一下~

**Comment by TonyYule** [comment]
我看了mybatisplus-spring-mvc的demo 用户表的操作 还是需要UserMapper.xml这个配置文件  我觉得 可以省略这个配置文件 在user类里面添加注解 可以参考 nutz http://www.nutzam.com/core/dao/pojo.html

**Comment by Caratacus** [comment]
不喜欢编写xml的话删除即可,需要注意的是在sqlsessionbean配置中去除指定的xml路径

**Comment by TonyYule** [comment]
可以不用xml自定义SQL吗  多对多关系呢 一对多关系呢？
