### ISSUE TITLE
性能分析插件无法显示执行的SQL

### ISSUE THREAD

**Issue by pythonzhu** [baomidou/mybatis-plus#90]
/**
	 * 性能分析插件，输出执行sql和时间
	 * 上线时关闭
	 * @return
	 */
	@Bean
	public PerformanceInterceptor performanceInterceptor(){
		PerformanceInterceptor performanceInterceptor = new PerformanceInterceptor();
		performanceInterceptor.setMaxTime(100);
		performanceInterceptor.setFormat(false);
		return performanceInterceptor;
	}

console打印结果：
 Time：58 ms - ID：com.****.mapper.MenuMapper.selectList
 Execute SQL：oracle.jdbc.driver.T4CPreparedStatement@538eed1e

**Comment by yuxiaobin** [comment]
This issue has already been resolved.
Pls upgrade mp version to 2.1-gamma

**Comment by pythonzhu** [comment]
已经更新到2.1-gamma
数据库为oracle11g,驱动为druid
