### ISSUE TITLE
2.x版本升级3.x版本，有没有官方教程？改动很大，不好处理呀

### ISSUE THREAD

**Issue by liupeng328** [baomidou/mybatis-plus#901]
### 当前使用版本 最新版

<version>2.1.9</version> 升级到最新版 3.1.0
 包名，分页，查询等等 改动了很多 

兼容性非常不好，有没有升级指南？读一下

**Comment by miemieYaho** [comment]
https://mybatis.plus/
https://github.com/baomidou/mybatis-plus-samples
