### ISSUE TITLE
请问如何配置多个SqlSessionTemplate

### ISSUE THREAD

**Issue by 250846434** [baomidou/mybatis-plus#902]
### 当前使用版本(必须填写清楚，否则不予处理)
2.1.9
新版中没有 updateAllColumn 不会用了~

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
mybatis多数据源中,开启分布式事务可以根据文件夹区分..
@MapperScan(basePackages="com.*",sqlSessionTemplateRef = "sqlSessionTemplate1")
### 重现步骤
能否提供类似于该注解的mybatis plus 版本?
直接使用mybatis 的注解,就会报错,若使用动态数据源,单个template无法支持分布式事务.
重写template注入多个Factory则会取错数据源.
以下为直接使用注解的报错,生成的sql正常应是:SELECT  test_id as  testId   FROM test
### 报错信息
SELECT  testId  FROM test
Unknown column 'testId' in 'field list'

**Comment by miemieYaho** [comment]
mp 不会提供
