### ISSUE TITLE
联合主键问题

### ISSUE THREAD

**Issue by showyouself** [baomidou/mybatis-plus#904]
### 当前使用版本(必须填写清楚，否则不予处理)
版本： 3.0.6
### 该问题是怎么引起的？
表存在联合主键
### 报错信息

使用insertOrUpdate发现model的下面这个方法会报错，除了重写所有byId方法，还有别的方法能优雅的支持吗
 /**
     * 主键值
     */
    protected Serializable pkVal() {
        return (Serializable) ReflectionKit.getMethodValue(this, TableInfoHelper.getTableInfo(getClass()).getKeyProperty());
    }

**Comment by miemieYaho** [comment]
没有
