### ISSUE TITLE
公共字段填充建议

### ISSUE THREAD

**Issue by fzsimlu** [baomidou/mybatis-plus#905]
需求背景
  很多情况下需要的查询时固定类似添加部门，或者个人的唯一标识去过滤。希望可以实现. 谢谢

**Comment by miemieYaho** [comment]
自行处理

**Comment by qmdx** [comment]
这个查询需要你自己去实现啊骚年

**Comment by fzsimlu** [comment]
😅本身就有这个功能，只是现在是有inser和update，少了insert查询
