### ISSUE TITLE
是否支持水平拆分的分表查询？

### ISSUE THREAD

**Issue by zeemood** [baomidou/mybatis-plus#906]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

数据量太大，需要根据地区做分表处理。或者有没有其他可行的方案？

**Comment by miemieYaho** [comment]
sharding-jdbc
