### ISSUE TITLE
使用update进行逻辑删除的时候自动将delete设置成2

### ISSUE THREAD

**Issue by Pace2Car** [baomidou/mybatis-plus#908]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
使用service的update操作进行逻辑删除时

### 重现步骤
entity.setDeleted(3); //3为删除

在update时这个deleted的值会自动变为2

### 报错信息
执行成功，但结果未达预期

**Comment by miemieYaho** [comment]
给出你的复现 demo

**Comment by Pace2Car** [comment]
String id = "test";
TestClazz entity= new TestClazz ();
entity.setStatus(3); // 3 为删除
entity.setUpdateTime(LocalDateTime.now()); // debug到这一步时参数正常
// step into update执行中发现在SqlSessionInterceptor.invoke这一步时时间参数正常，但是status莫名被更改为2
testClazzService.update(entity, new UpdateWrapper<TestClazz>().eq("id", id));

**Comment by huayanYu** [comment]
> String id = "test";
> TestClazz entity= new TestClazz ();
> entity.setStatus(3); // 3 为删除
> entity.setUpdateTime(LocalDateTime.now()); // debug到这一步时参数正常
> // step into update执行中发现在SqlSessionInterceptor.invoke这一步时时间参数正常，但是status莫名被更改为2
> testClazzService.update(entity, new UpdateWrapper().eq("id", id));

你至少应该给出你的数据库版本，相关mp配置， 执行出来的sql日志，数据库相关表的配置。

**Comment by Pace2Car** [comment]
抱歉抱歉，找到问题了，是一个同事为了方便，在所有update的地方加了切面将status改为了2，跟mp本身无关，给你们添麻烦了，抱歉
