### ISSUE TITLE
2.1.8直升3.1.0会出现问题吗

### ISSUE THREAD

**Issue by GitBiao** [baomidou/mybatis-plus#909]
### 当前使用版本(必须填写清楚，否则不予处理)

2.1.8

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

没有问题，我想升到3.1.0使用自定义sql的wapper，但是想先来问一下出现一些不可控问题码

**Comment by miemieYaho** [comment]
会不会出看情况

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples
