### ISSUE TITLE
再提性能分析插件无法使用

### ISSUE THREAD

**Issue by pythonzhu** [baomidou/mybatis-plus#91]
mybatis-plus更新到2.1-gamma,springboot-starter为1.0.4
oracle11g，连接池为druid1.1.0

在config中引入	/**
	 * 性能分析插件，输出执行sql和时间
	 * 上线时关闭
	 * @return
	 */
	@Bean
	public PerformanceInterceptor performanceInterceptor(){
		PerformanceInterceptor performanceInterceptor = new PerformanceInterceptor();
		performanceInterceptor.setMaxTime(10000);
		performanceInterceptor.setFormat(false);
		return performanceInterceptor;
	}

console打印为 
Time：54 ms - ID：com.****.mapper.MenuMapper.selectList
 Execute SQL：oracle.jdbc.driver.T4CPreparedStatement@52ebed39

**Comment by yuxiaobin** [comment]
经测，这个是因为Druid包装了statmemt，
已修复。
具体可以看oschina dev分支：
http://git.oschina.net/baomidou/mybatis-plus/tree/dev

**Comment by yuxiaobin** [comment]
还有，我对你create issue的热情表示。。。无法理解，之前那个issue你完全可以reopen，没使用过issue tracking类似系统来跟踪bug吗？
