### ISSUE TITLE
AbstractWrapper的formatSqlIfNeed 如果format 是 false 返回null

### ISSUE THREAD

**Issue by nullbull** [baomidou/mybatis-plus#910]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
`protected final String formatSql(String sqlStr, Object... params) {
        return this.formatSqlIfNeed(true, sqlStr, params);
    }

    protected final String formatSqlIfNeed(boolean need, String sqlStr, Object... params) {
        if (need && !StringUtils.isEmpty(sqlStr)) {
            if (ArrayUtils.isNotEmpty(params)) {
                for(int i = 0; i < params.length; ++i) {
                    String genParamName = "MPGENVAL" + this.paramNameSeq.incrementAndGet();
                    sqlStr = sqlStr.replace(String.format("{%s}", i), String.format("#{%s.paramNameValuePairs.%s}", this.getParamAlias(), genParamName));
                    this.paramNameValuePairs.put(genParamName, params[i]);
                }
            }

            return sqlStr;
        } else {
            return null;
        }
    }
`

### 重现步骤
AbstractWrapper 封装参数时，会将所有的参数名格式化成为统一的名称，但是这样不方便我们自定义拦截器来获取参数。mybaits原生直接可以get 参数。你们这个方法判断要不要format，但是不format不能直接返回null把，我建议应该提供一个配置，默认format，但是也能不format。 我这个需求是为了获取QueryWrapper参数的值，现在我只能根据约定和类型猜测来确定哪个值是我需要的

**Comment by miemieYaho** [comment]
这是内部使用,你不应该对此有疑问
