### ISSUE TITLE
MybatisSqlSessionFactoryBean logger 类找到

### ISSUE THREAD

**Issue by ashangpeng** [baomidou/mybatis-plus#911]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
    <version>3.1.0</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

public class MybatisSqlSessionFactoryBean implements FactoryBean<SqlSessionFactory>, InitializingBean, ApplicationListener<ApplicationEvent> {

    private static final Logger LOGGER = LoggerFactory
            .getLogger(SqlSessionFactoryBean.class);

### 重现步骤

请替换成新版本的方法

### 报错信息
类找不到

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples
