### ISSUE TITLE
如何配置可以把统一的表前缀去掉

### ISSUE THREAD

**Issue by youwoa** [baomidou/mybatis-plus#912]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
数据库的表都是tbl_前缀开头的，我想在生成代码的时候（包括entity、service、controller）都把tbl_前缀去掉，请问现在有这个实现吗，该怎么配置呢？谢谢

**Comment by youwoa** [comment]
已知晓

**Comment by sainyuwjz** [comment]
同问，怎么去除前缀？？？？
