### ISSUE TITLE
Maven多模块后org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): 

### ISSUE THREAD

**Issue by xiaour** [baomidou/mybatis-plus#913]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.0</version>
</dependency>

### 重现步骤
1.按照官网去掉mybatis-spring-starter,配置了mybatis-plus
2.MapperScan()路径正确，因为原生mybatis是可以映射到的。
3.extends BaseMapper<T>
### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.xxxx.StyleMapper.selectList

**Comment by yuxiaobin** [comment]
SqlSessionFactroy是否手动配置？如果是，替换MybatisSqlSessionFactory

**Comment by xyabc120** [comment]
同样的问题，按照示例配置的，所有路径配置和映射都检查过了，没解决。自写的XML方法能执行，mp 自带方法全部 `Invalid bound statement (not found).` 错误。手动配置 `MybatisSqlSessionFactory` 两种都能执行了，但没了逻辑删除的功能了。

**Comment by xyabc120** [comment]
差不多的问题，我是从 2.x 打算升 3.1 的，在执行 mp 自带方法时都报这个错，整了好几个小时，发现是引入包的问题。先前是 `mybatisplus-boot-starter` 改为 `mybatis-plus-boot-starter` 就好了
```diff
<dependency>
    <groupId>com.baomidou</groupId>
-    <artifactId>mybatisplus-boot-starter</artifactId>
+    <artifactId>mybatis-plus-boot-starter</artifactId>
</dependency>
```
