### ISSUE TITLE
OptimisticLockerInterceptor 乐观锁插件，和LogicSqlInjector 逻辑删除插件如何设置更新失败时抛异常

### ISSUE THREAD

**Issue by atomiCat** [baomidou/mybatis-plus#914]
这两个插件在updateById和deleteById方法执行时如果更新或删除失败会返回0，有没有地方能配置失败的时候抛异常？或者有没有什么优雅的实现方法？现在代码中只能判断 if( deleteById(id) == 0 )throw new Exceotion()

**Comment by miemieYaho** [comment]
没有

**Comment by yuxiaobin** [comment]
如果是个例，自己判断下再抛异常
如果是通用，建议自定义baseMapper方法
参考[mybatis-plus-samples](https://github.com/baomidou/mybatis-plus-samples)
