### ISSUE TITLE
oracle关键字配置TableField后SQL执行异常

### ISSUE THREAD

**Issue by mozhuwanjieDEV** [baomidou/mybatis-plus#915]
### 当前使用版本 2.3

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>2.3</version>
        </dependency>

### 该问题是怎么引起的？
1. 例如Task对象得mode字段，加上TableField字段进行配置；
 @TableField(value = "\\"mode\\"")
    private String mode;

 2. 构造EntityWrapper进行查询，生成得SQL中AS后得字段没加引号，依然是关键字，

taskRepository.selectList(
                new EntityWrapper<Task>()
                        .eq("task_type", "10")
                        .eq("task_state", "11"));

SELECT
       task_id          AS taskId,
       "mode"           AS mode,
       task_type        AS taskType,
       task_state       AS taskState
  FROM QN_CONTACT_TASK
 WHERE (task_type = ? AND task_state = ?)

### 报错信息

SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字

**Comment by vilin520** [comment]
@TableField(value = "'all'")
 异常：Cannot determine value type from string 'all'
我项目里all字段是double类型的。
在mysql里面使用3.X,会出现无法识别字段类型！
不知道要怎么解决！

**Comment by miemieYaho** [comment]
2.3版本不加 `@TableField(value = "\"mod\"")` 试试

**Comment by mozhuwanjieDEV** [comment]
> 2.3版本不加 @TableField(value = "\"mode\"") 试试

不加的话出来的sql中字段直接是mode,这个是关键字，查询失败呢

**Comment by miemieYaho** [comment]
那你用2.x 版本的话只能改数据库字段名了

**Comment by mozhuwanjieDEV** [comment]
> 那你用2.x 版本的话只能改数据库字段名了

额。。。
我看2.x的特性介绍是有关键字转义的啊

**支持关键词自动转义：支持数据库关键词（order、key......）自动转义，还可自定义关键词**

**Comment by miemieYaho** [comment]
未识别出你的 `mode` 是关键字. 3.x 不会自动转义,只能注解里像你现在这么用,但不会有2.x 的问题

**Comment by vilin520** [comment]
@TableField(value = "\"mode\"")改为@TableField(value = "`mode`")试试，用反单引号！MySQL下mybatis-plus3.X里面暂时不会报错！

**Comment by qmdx** [comment]
如上
