### ISSUE TITLE
鄙视，强烈鄙视！

### ISSUE THREAD

**Issue by lurenj** [baomidou/mybatis-plus#916]
过分啊，一下从2点几升到3点几，这两天改方法改的我想吐！

**Comment by yuxiaobin** [comment]
你为何这么Diao？
强烈不推荐2.x升级到3.x，除非你项目刚开始

**Comment by lurenj** [comment]
我也想那个时候是哪根筋短路了，好像打死我自己！

**Comment by qmdx** [comment]
2 3 跨度太大了，恭喜你体验了一把想死的感觉

**Comment by Cat7373** [comment]
我大概升级过四五个项目，似乎也没多难处理。。
