### ISSUE TITLE
3.1.0版本org.mybatis.logging.LoggerFactory问题

### ISSUE THREAD

**Issue by mooofir** [baomidou/mybatis-plus#918]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

- 启动时提示未找到org/mybatis/logging/LoggerFactory

- 查看已经Close的Issues有另外3个相同问题，但未解决。

- pom未引用spring-boot-mybatis-starter

- 观察Libraries引用的mybatis 3.4.4，其中日志工厂类为org.apache.ibatis.logging.LogFactory

### 重现步骤

		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-generator</artifactId>
			<version>3.1.0</version>
		</dependency>

### 报错信息

[com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory

**Comment by miemieYaho** [comment]
依赖冲突,3.1.0用的mybatis为最新版
