### ISSUE TITLE
Oracle Sequence 使用 

### ISSUE THREAD

**Issue by MrLiu007** [baomidou/mybatis-plus#92]
参考1：http://mp.baomidou.com/#/sequence?id=sequence%e4%b8%bb%e9%94%ae
参考2：<property name="dbType" value="oracle" />
当from 表单提交时候，id会提示空，报错，然后我去掉参考2中的配置，把参数1中动态new对象配置进去如下：<property name="keyGenerator" value="com.baomidou.mybatisplus.entity.OracleKeyGenerator" />
出现Failed to convert property value of type 'java.lang.String' to required type 'com.baomidou.mybatisplus.mapper.IKeyGenerator' for property 'keyGenerator'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.baomidou.mybatisplus.mapper.IKeyGenerator' for property 'keyGenerator': no matching editors or conversion strategy found

所以请问下，你具体实现步骤是什么？怎么做

**Comment by yuxiaobin** [comment]
你确定配置正确了？xml配置？贴出来给你找错

**Comment by MrLiu007** [comment]
我改好了，我把配置贴出来，方便大家使用：
![1499138507 1](https://user-images.githubusercontent.com/18440015/27813822-1dd7adcc-60ab-11e7-8e79-040f0beac25b.png)

**Comment by yuxiaobin** [comment]
你这是人人为我 我为人人啊！

为你这种精神点赞！

记得入群：唯一官方真宗技术兼吹B群：576493122
