### ISSUE TITLE
spring boot 2.1.0启动问题 NoClassDefFoundError

### ISSUE THREAD

**Issue by codegrady** [baomidou/mybatis-plus#920]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0
spring boot 2.1.0
### 重现步骤
项目启动

### 报错信息
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceJmxConfiguration$Hikari': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/jdbc/DataSourceUnwrapper

**Comment by miemieYaho** [comment]
自行排查
