### ISSUE TITLE
mp 自带方法没有sqlsession没有被spring管理

### ISSUE THREAD

**Issue by lcb1208** [baomidou/mybatis-plus#921]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis 2.0.0
mp:3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
service:
@Service
public class OrderServiceImpl extends ServiceImpl<OrderMapper, Order> implements IOrderService {

}
controller:
    @Autowired
    private IOrderService orderService;
public void get(){
orderService.getOne(new QueryWrapper<Order>()
                .lambda().******)
}
### 报错信息
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@69b95511] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@26ede54e] will not be managed by Spring

**Comment by miemieYaho** [comment]
自行检查

**Comment by miemieYaho** [comment]
要用事务自己加事务注解,或者切
