### ISSUE TITLE
Page在添加notLike后，count查询问题

### ISSUE THREAD

**Issue by Linyuzai** [baomidou/mybatis-plus#922]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

wrapper接notLike，page的时候，在子查询count的时候，sql拼接有问题。

### 重现步骤

```
Wrapper<Program> wrapper = Wrappers.lambdaQuery(program).eq(Program::getUserId, getUser().getId()).notLike(Program::getProgramName, Program.DEFAULT_PREFIX);
return programService.page(page, wrapper);
```

### 报错信息
```
==>  Preparing: SELECT COUNT(1) FROM t_program WHERE deleted = 0 AND user_id = ? AND NOT program_name NOT LIKE ? 
==> Parameters: aad3538a0f804856a693a58c4f14f637(String), %Default-%(String)
<==    Columns: COUNT(1)
<==        Row: 1
```
SQL在AND之后多了一个NOT，导致条数查询有问题

**Comment by miemieYaho** [comment]
无法复现.给出你的复现 demo

**Comment by Linyuzai** [comment]
> 无法复现.给出你的复现 demo

我这边直接新建一个wrapper，接上notLike，然后用page查询，都有这个问题。注入了分页插件和逻辑删除插件

**Comment by miemieYaho** [comment]
已确认,是 jsqlparser 的问题,你把它降级到1.2就正常了

**Comment by Linyuzai** [comment]
> 已确认,是 jsqlparser 的问题,你把它降级到1.2就正常了

OK，已解决
