### ISSUE TITLE
'java.lang.invoke.SerializedLambda' could not be instantiated

### ISSUE THREAD

**Issue by AnLiBoBo** [baomidou/mybatis-plus#924]
### 当前使用版本(必须填写清楚，否则不予处理)
<mybatis-plus-start.version>3.1.0</mybatis-plus-start.version>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
在mybatis-plus + dubbo环境下，我的客户端调用dubbo服务的时候抛出异常
'java.lang.invoke.SerializedLambda' could not be instantiated
后来我试着用lamb表达式，也是这个异常

`
QueryWrapper<User> qw= new QueryWrapper<>();

qw.eq("`user_name`","1");

userService.list(qw);
`

但是如果不传qw参数的话 是可以正常执行
这个问题我在3.0.2版本就遇到过，后来我把版本更新到3.1.0还想如此

### 重现步骤
mybatis-plus + dubbo环境
一个provider，一个web
controller调用provider的时候会抛出这个异常

### 报错信息
com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.normal: 'java.lang.invoke.SerializedLambda' could not be instantiated

**Comment by miemieYaho** [comment]
wrapper 不支持传递
