### ISSUE TITLE
在3.0-beta版本中，逻辑删除sql拼接没有加“AND” 导致selectById 报错

### ISSUE THREAD

**Issue by liwanlinGit** [baomidou/mybatis-plus#925]
public String getLogicDeleteSql(TableInfo table) {
        StringBuilder sql = new StringBuilder();
        List<TableFieldInfo> fieldList = table.getFieldList();
        int i = 0;
        for (TableFieldInfo fieldInfo : fieldList) {
            if (fieldInfo.isLogicDelete()) {
                if (++i > 1) {
                    sql.append(" AND ");
                }
                sql.append(fieldInfo.getColumn());
                if (StringUtils.isCharSequence(fieldInfo.getPropertyType())) {
                    sql.append("='").append(fieldInfo.getLogicNotDeleteValue()).append("'");
                } else {
                    sql.append("=").append(fieldInfo.getLogicNotDeleteValue());
                }
            }
        }
        return sql.toString();
    }

### 报错信息
并不会 走这行sql.append(" AND ");
导致selectById 报错

**Comment by miemieYaho** [comment]
都 9102年了!
