### ISSUE TITLE
请问，源码的编码是UTF-8吗？ 我这边看源码中中文都是乱码

### ISSUE THREAD

**Issue by yuelaotou** [baomidou/mybatis-plus#93]
请问，源码的编码是UTF-8吗？ 我这边看源码中中文都是乱码

话说，我的工程是UTF-8的，谢谢。

**Comment by svatiYu** [comment]
@yuelaotou 是的,请自行百度设置源码为utf-8

**Comment by wzl1219** [comment]
https://www.cnblogs.com/yfding/p/5955591.html
按照这个页面操作我终于看到中文了..
