### ISSUE TITLE
mapper的selectAllRole返回的实体类Date类型是null

### ISSUE THREAD

**Issue by ReStartLin** [baomidou/mybatis-plus#930]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus  v:3.1.0
mysql 8.0
### 重现步骤

```java
@TableName(value = "t_role")
public class RoleDO {
    @TableId(value = "role_id", type = IdType.AUTO)
    private Integer roleId;
    @TableField(value = "role_name")
    private String roleName;
    @TableField(value = "create_time")
    private Date createTime;
    @TableField(value = "update_time")
    private Date updateTime;

   setter and getter
}
````
这是实体类, 
创建一个例子插入
```java
        RoleDO roleDO = new RoleDO();
        roleDO.setRoleName("测试一");
        roleDO.setCreateTime(new Date());
        roleDO.setUpdateTime(new Date());
        roleMapper.insertRole(roleDO);
```
问题:
用mapper的selectOneById查询出来 createTime 和 updateTime 有值 
 但是用selectAllRole  查询出来的所有的实体类   createTime 和 updateTime都是null

**Comment by miemieYaho** [comment]
https://mybatis.plus/config/#mapunderscoretocamelcase

**Comment by ReStartLin** [comment]
> https://mybatis.plus/config/#mapunderscoretocamelcase

谢谢你的回复,但, 关于驼峰转换的规则 我已经在配置文件中开启为true  而且我的问题是:
使用selectOneById 获得的单个对象是有值回传的,  但是使用selectAllRole却会丢失Date相关的字段

**Comment by miemieYaho** [comment]
`selectAllRole` 是你自己写的,mp只是封装常用crud的mapper,实际运行走的是mybatis的流程,自己检查
