### ISSUE TITLE
selectOne对超过一条的记录抛异常

### ISSUE THREAD

**Issue by xem1987** [baomidou/mybatis-plus#935]

**Comment by chihche** [comment]
这个问题也是困扰我。。旧有项目都是直接使用selectOne
因为注解里面很明确说就是获取一条，现在改版后却不自动加上limit 1
这种不兼容的升级，真要命。直接报错。。。

**Comment by tunghsingw** [comment]
selectOne有一个版本，第二个参数指定是否引发异常。
不过还是比较模糊，容易出错，加入selectFirst是个不错的接口。
