### ISSUE TITLE
EncryptUtils.java 备注错误

### ISSUE THREAD

**Issue by zuster** [baomidou/mybatis-plus#937]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

EncryptUtils为加密处理工具类，但是注释中写的是“枚举处理工具类”

**Comment by miemieYaho** [comment]
ok
https://github.com/baomidou/mybatis-plus/commit/9899efa38d3d333577520b43f167d82e208be52d
