### ISSUE TITLE
@TableField(exist = false) 报错数组越界

### ISSUE THREAD

**Issue by sunnyjoo** [baomidou/mybatis-plus#938]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.0</version>
</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
我在实体类添加了这个@TableField(exist = false)属性,查询的时候为什么会出现数组越界异常

### 重现步骤
使用的是MySQL数据库,进行查询操作

**Comment by sunnyjoo** [comment]
找到原因了,是因为lombok插件Builder注解造成的

**Comment by sunnyjoo** [comment]
问题找到解决方法

**Comment by Duanzh** [comment]
com.baomidou mybatis-plus-boot-starter 3.1.0 上此问题尚未解决吧，还是无法使用Builder注解
