### ISSUE TITLE
3.x版本的和spring的整合 官方文档没有一个比较完整的示例说明

### ISSUE THREAD

**Issue by neil88** [baomidou/mybatis-plus#939]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
spring xml配置如下:
<bean id="sqlSessionFactory"
		  class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
		<property name="dataSource" ref="dataSource" />

		<property name="configuration">
			<bean class="com.baomidou.mybatisplus.core.MybatisConfiguration">
				<property name="mapUnderscoreToCamelCase" value="true"/>
			</bean>
		</property>

		<property name="configLocation" value="classpath:mybatis-config.xml" />
		<property name="mapperLocations" value="classpath:mapper/dqc/*Mapper.xml" />
		
		<property name="configLocation" value="classpath:mybatis-config.xml" />
		<property name="mapperLocations" value="classpath:mapper/dqc/*Mapper.xml" />

		<property name="globalConfig">
			<bean class="com.baomidou.mybatisplus.core.config.GlobalConfig">
				<property name="dbConfig">
					<bean class="com.baomidou.mybatisplus.core.config.GlobalConfig.DbConfig">
						<property name="idType" value="AUTO"/>
						<property name="fieldStrategy" value="NOT_NULL"/>
					</bean>
				</property>
			</bean>
		</property>
	</bean>

	<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		<property name="basePackage" value="com.webull.wlas.monitor.dqc.mapper" />
	</bean>

### 重现步骤
如上步配置所示

### 报错信息
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'indicatorConstantId' in 'field list'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'indicatorConstantId' in 'field list'

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-quickstart-springmvc/src/main/resources/spring.xml

**Comment by neil88** [comment]
> https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-quickstart-springmvc/src/main/resources/spring.xml

ok，thanks
