### ISSUE TITLE
通过mybatis查询映射为实体类BigDecimal出现科学计数法

### ISSUE THREAD

**Issue by philos3** [baomidou/mybatis-plus#940]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-generator</artifactId>
			<version>3.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus</artifactId>
			<version>3.0.7.1</version>
		</dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

mysql数据库存储格式为decimal 并且小数点位数为10，当数字为0的时候，通过mybatis查询映射为实体类BigDecimal出现科学计数法。

![Uploading image.png…]()

### 重现步骤

1、mysql数据库存储格式为decimal 并且小数点位数为10
2、利用mybatis映射为实体类Decimal，打断点可以看到被转换为科学计数的格式

### 报错信息
无（科学计数导致类型转换错误)

**Comment by miemieYaho** [comment]
这是 mybatis 的问题
