### ISSUE TITLE
MapperFactory可以自己扩展吗

### ISSUE THREAD

**Issue by 942bc** [baomidou/mybatis-plus#941]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
由于项目中需要对每个Mapper指定SqlSessionFactory，查看了一下源码没有找到对应的支持，故想自己扩展一个，但是没有找到实现方式

**Comment by qmdx** [comment]
https://mybatis.plus/guide/sql-injector.html
