### ISSUE TITLE
连续使用两条XML 自定义分页，页码不一样时，第二个不执行，直接取了第一个的结果

### ISSUE THREAD

**Issue by ychange2012** [baomidou/mybatis-plus#942]
### 当前使用版本(必须填写清楚，否则不予处理)
版本号3.0.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
连续调用IPage<User> selectPageVo(Page page)，获取list,第二直接用了第一次结果。已经试过page和list两个变量名字不一样，还是不行。

**Comment by ychange2012** [comment]
是业务功能需要用到，看到别的issue也提到了，不是测试。

**Comment by miemieYaho** [comment]
一级缓存问题,建议使用 selectList, ew.last("limit 10") 这种自己分页
