### ISSUE TITLE
StringBuilder VS format

### ISSUE THREAD

**Issue by anweicloud** [baomidou/mybatis-plus#943]
### 当前使用版本(必须填写清楚，否则不予处理)
Mybatis-plus v2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
强大的MyBatis-plus， 我有两个疑问：
1，SqlFormatter中
format的性能很一般，为啥么不用stringbuilder或者stringbuffer代替？
2，使用?占位提示参数不对，sql占位符为什么不能直接用?号，而是{index}，最终还是转为?处理。

**Comment by miemieYaho** [comment]
没有那么多为什么
