### ISSUE TITLE
关于LambdaQueryWrapper

### ISSUE THREAD

**Issue by 276234199** [baomidou/mybatis-plus#949]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
关于LambdaQueryWrapper
我的查询结果的对象是
//用户
class User{
Integer uId;
String name;
Department department;
....
}

//部门
class Department {
Integer deptId;
String deptName;
....
}

我想使用LambdaQueryWrapper 查询deptId=1的用户,应该怎么书写这个？
lambdaQuery.eq(User::getDepartment::getDeptId ,1);这样写不行····

**Comment by miemieYaho** [comment]
不支持你这样写
