### ISSUE TITLE
使用2.1-gamma分页问题

### ISSUE THREAD

**Issue by tuxin95** [baomidou/mybatis-plus#95]
在是使用2.1gamma分页中 sql  中select ...from 范围中出现的#{} 会出现错误

1. sql 

SELECT
        t.dm_id AS dmId,
        t.businessName,
        t.businessDesc,
        t.address,
        t.areaId,
        t.imagePath,
        t.phone,
        t.createUser,
        t.createTime,
        t.state,
        t.sort,
        t.infromNum,
        t.oneCategoryId,
        t.twoCategoryId,
        t.endTime,
        t.provinceId,
        t.cityId,
        t.townId,
        t.type,
        t.qrcode,
        t.license,
        t.shopPhoto,
        t.IDfront,
        t.IDback,
        t.remark,
        t.authStatus,
        t.longitude,
        t.latitude,
        t.isFirstRecharge,
        c1. NAME oneCategoryName,
        c2. NAME twoCategoryName,
        province.`name` provinceName,
        city.`name` cityName,
        town.`name` townName,
        tu.username,
        ROUND(
        6378.138 * 2 * ASIN(
        SQRT(
        POW(
        SIN(
        (
        #{userLatitude} * PI() / 180 - t.latitude * PI() / 180
        ) / 2
        ),
        2
        ) + COS(
        #{userLatitude} * PI() / 180) * COS(t.latitude * PI() / 180) * POW(
        SIN(
        (
        #{userLongitude} * PI() / 180 - t.longitude * PI() / 180
        ) / 2
        ),
        2
        )
        )
        ) * 1000
        ) AS distance
        FROM
        business t

最终2.1版本分页日志显示sql为:

SELECT COUNT(1) FROM business t LEFT JOIN t_user tu ON tu.typeId = t.dm_id LEFT JOIN category c1 ON c1.dm_id = t.oneCategoryId LEFT JOIN category c2 ON c2.dm_id = t.twoCategoryId LEFT JOIN region province ON province.dmId = t.provinceId LEFT JOIN region city ON city.dmId = t.cityId LEFT JOIN region town ON town.dmId = t.townId
因为把前面#{userLongitude}去掉了 所以最终报错
Caused by: java.sql.SQLException: Parameter index out of range (5 > number of parameters, which is 4).
我现在改为2.0.8版本了 日志打印sql是正确
SELECT COUNT(1) FROM ( SELECT t.dm_id AS dmId, t.businessName, t.businessDesc, t.address, t.areaId, t.imagePath, t.phone, t.createUser, t.createTime, t.state, t.sort, t.infromNum, t.oneCategoryId, t.twoCategoryId, t.endTime, t.provinceId, t.cityId, t.townId, t.type, t.qrcode, t.license, t.shopPhoto, t.IDfront, t.IDback, t.remark, t.authStatus, t.longitude, t.latitude, t.isFirstRecharge, c1. NAME oneCategoryName, c2. NAME twoCategoryName, province.`name` provinceName, city.`name` cityName, town.`name` townName, tu.username, ROUND( 6378.138 * 2 * ASIN( SQRT( POW( SIN( ( ? * PI() / 180 - t.latitude * PI() / 180 ) / 2 ), 2 ) + COS( ? * PI() / 180) * COS(t.latitude * PI() / 180) * POW( SIN( ( ? * PI() / 180 - t.longitude * PI() / 180 ) / 2 ), 2 ) ) ) * 1000 ) AS distance FROM business t

请问这种情况2.1需要怎么办.....急啊

**Comment by qmdx** [comment]
多谢反馈，我们会继续跟踪解决，如果是 bug  2.1 正式版会修复。

**Comment by yuxiaobin** [comment]
确实是mybatis分页插件-优化count的一个bug

因为优化count直接select count(1) from xxx, 把 from 之前的参数给去掉了，导致参数个数匹配。

厉害了word哥，你是第一个这么玩的。

**Comment by yuxiaobin** [comment]
你这种情况，建议关闭查询count，可以在Page.setSearchCount=false

**Comment by qmdx** [comment]
@tuxin95  如上 page.SetSearchCount(false) 自定义 count sql 设置到 page 中

**Comment by yuxiaobin** [comment]
优化count SQL导致selectItems里面的#{}丢失，在调用PaginationInterceptor.queryTotal()方法，使用了DefaultParameterHandler.setParameters,导致的问题。

可以考虑自定义一个parameterHandler替换原生的，应该是可以解决这个问题。

@qmdx

**Comment by yuxiaobin** [comment]
@qmdx 现在dev上提交了一个临时解决方案，保证count不出错

**Comment by qmdx** [comment]
@yuxiaobin  屌 da
