### ISSUE TITLE
关于LambdaQueryWrapper的又一个问题~

### ISSUE THREAD

**Issue by 276234199** [baomidou/mybatis-plus#950]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

TestEntity是一个复杂的实体类，因而没有@TableName的注解，数据库中没有TestEntity这张表，只有对应的SQL查询结果和代码中的ResultMap，是否这种情况下就不可以使用LambdaQueryWrapper

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.customSqlSegment'. Cause: org.apache.ibatis.ognl.OgnlException: customSqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: cannot find column's cache for "com.sot.entity.TestEntity", so you cannot used "class com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper"!]

**Comment by miemieYaho** [comment]
你的 TestEntity 没有对应的 mapper 继承 basemapper 并且该 mapper 能正常使用才能用 LambdaQueryWrapper

**Comment by 276234199** [comment]
明白了 多谢 ~
