### ISSUE TITLE
增加一个注解，控制是否启用逻辑删除

### ISSUE THREAD

**Issue by lzweb** [baomidou/mybatis-plus#951]
### 当前使用版本(必须填写清楚，否则不予处理)
3.x

### 报错信息

在使用逻辑删除的时候，所有的增删改查都自动加入了删除标记。
如果能通过增加注解，或者参数控制，关闭这个功能，用起来就更方便了。
既能实现逻辑删除，又能查询所有数据包含被删除的。

**Comment by xiexiezhenff** [comment]
刚才还在跟同事说这个问题 结果就有人提出来了。。
"除非它在select 这样的语句加个标签 默认就是不查处删除的，， 然后我们可以设置它查出来删除的  这就完美了。。"

**Comment by miemieYaho** [comment]
不支持,已经注入到结果性的 sql 语句中,不可逆没有选择性,自己写 sql 查删除的数据
