### ISSUE TITLE
自定义Page Count报错

### ISSUE THREAD

**Issue by SangerTears** [baomidou/mybatis-plus#952]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
分页查询

### 重现步骤
自定义分页查询，报错
Mapper
 IPage<Label> pageLabel(Page page, @Param("name") String name, @Param("catalogId") int catalogId);

### 报错信息
The error may involve defaultParameterMap
 The error occurred while setting parameters
 Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM lom_label t1 JOIN lom_label_catalog t2 ON t1.catalog_id = t2.sid WHERE 1 = 1

**Comment by miemieYaho** [comment]
`SELECT COUNT(1) FROM lom_label t1 JOIN lom_label_catalog t2 ON t1.catalog_id = t2.sid WHERE 1 = 1` 这个 sql 你拿去数据执行报错吗?

**Comment by SangerTears** [comment]
> `SELECT COUNT(1) FROM lom_label t1 JOIN lom_label_catalog t2 ON t1.catalog_id = t2.sid WHERE 1 = 1` 这个 sql 你拿去数据执行报错吗?

数据库直接查询，不报错，查询正常。

**Comment by SangerTears** [comment]
问题已经解决，是我连错数据库连。但是这个异常信息也不明确。如果是找不到表，应该抛出对应的异常才对

**Comment by miemieYaho** [comment]
后面有异常信息
