### ISSUE TITLE
PageInterceptor的count查询未使用Executor导致无法和其他Interceptor兼容

### ISSUE THREAD

**Issue by fredshawf** [baomidou/mybatis-plus#953]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-core-2.1.9

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
引用其他Interceptor插件

### 重现步骤
引用其他Interceptor后，若在SQL首部添加注释/\*!mycat:datanode=abc\*/
count查询的SQL 不能被拦截，即不能注入/\*!mycat:datanode=abc\*/到countSQL的首部
导致query与count的查询不能匹配

**Comment by miemieYaho** [comment]
自己重写 PageInterceptor

**Comment by fredshawf** [comment]
我要会写干嘛要提Issue。而且其他分页插件都是用Executor写的呀。支持一下呗？

**Comment by miemieYaho** [comment]
那没办法,也许4.0的时候可能会变成Executor,你可以用 pagehelper 进行分页
