### ISSUE TITLE
为什么不用JPA的注解来实现

### ISSUE THREAD

**Issue by fanhua1994** [baomidou/mybatis-plus#954]
导致我们写实体的时候有些臃肿。
```
@Entity
@Table(name = "sys_test")
@TableName(value = "sys_test")
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Test {
    @Id
    @Column(name = "id",length = 20)
    @TableId(value = "id",type = IdType.ID_WORKER_STR)
    private String id;

    private String name;

    private int age;

    @Column(name = "username",unique = true)
    private String username;
}
```

**Comment by qmdx** [comment]
不想引入太多的学习成本，一两个注解就搞定了不需要分的那么多

**Comment by fredshawf** [comment]
这个其实可以自己写一个注解 然后把需要的封装进去就可以了。其实我觉得，不应该在Entity上进行table的注解。这样违反了POJO规范。应该注解到Mapper上

**Comment by fredshawf** [comment]
对于企业级应用，如果我想换个数据库，或者将数据分离到不同层次(库/表中)，但是业务逻辑不变。这种情况，我就要修改POJO类。而POJO类是业务的核心，一旦修改，全项目要跑一遍测试。所以我建议应该把table和field注解 放到mapper中。

**Comment by fanhua1994** [comment]
> 对于企业级应用，如果我想换个数据库，或者将数据分离到不同层次(库/表中)，但是业务逻辑不变。这种情况，我就要修改POJO类。而POJO类是业务的核心，一旦修改，全项目要跑一遍测试。所以我建议应该把table和field注解 放到mapper中。

大佬说实话我不是很懂，把table field注解放到mapper中怎么自动更新表。

**Comment by fredshawf** [comment]
> > 对于企业级应用，如果我想换个数据库，或者将数据分离到不同层次(库/表中)，但是业务逻辑不变。这种情况，我就要修改POJO类。而POJO类是业务的核心，一旦修改，全项目要跑一遍测试。所以我建议应该把table和field注解 放到mapper中。
> 
> 大佬说实话我不是很懂，把table field注解放到mapper中怎么自动更新表。

我这里说的是这个M-P插件只能在模型类上注解(实现ORM)，不能在mapper上注解。模型层被注解后，就失去分离业务逻辑的意义了。当然我们只能吐槽，实际上我们的水平和作者差距很大，作者肯定有作者的考虑。但就企业级应用来说，能够分离业务逻辑是上上策。随着数据量的不断增长，企业级应用会面临换库，甚至整个持久层采用大数据也说不定。这样就不能实现解耦

**Comment by tunghsingw** [comment]
万万不要增加必须的学习成本，工具是给人用的，不是折腾人的，多谢多谢。

**Comment by tunghsingw** [comment]
万万不要增加非必须的学习成本，工具是给人用的，不是折腾人的，多谢多谢。
