### ISSUE TITLE
使用Page作为返回类型 @select自定义sql 时 查询结果为 null 

### ISSUE THREAD

**Issue by 550932785** [baomidou/mybatis-plus#956]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用Page作为返回类型 @select自定义sql 时 查询结果为 null 
将返回值改为 List 结果正确

### 重现步骤

![image](https://user-images.githubusercontent.com/20946141/54814632-17084200-4ccb-11e9-8ca5-40e371d3b4cc.png)

### 报错信息
![image](https://user-images.githubusercontent.com/20946141/54814697-37d09780-4ccb-11e9-95ee-8e35d4a865bd.png)

**Comment by 550932785** [comment]
![image](https://user-images.githubusercontent.com/20946141/54814864-8da53f80-4ccb-11e9-92a0-d613b41bfd23.png)

**Comment by miemieYaho** [comment]
用 IPage 接

**Comment by 550932785** [comment]
我试过，写到xml里面没问题，就是指使用注解不好用

**Comment by miemieYaho** [comment]
注解的话返回值只能用Ipage,下个版本才会支持Ipage的子类

**Comment by qmdx** [comment]
关注 3.1.1+ 发布
