### ISSUE TITLE
使用MockMvc测试Dynamic DataSource+Druid时的Bug

### ISSUE THREAD

**Issue by zhengzhaojian** [baomidou/mybatis-plus#957]
### 当前使用版本(必须填写清楚，否则不予处理)
druid-spring-boot-starter:1.1.10
dynamic-datasource-spring-boot-starter:2.5.3
mybatis-plus-boot-starter:3.0.7
### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用MockMvc测试多数据源整合Druid时，Druid的WebStatFilter报空指针异常。
在百度找到了如下解决办法：https://gitee.com/jinglun404/DLXD/issues/IGCM9 
发现Dynamic DataSource未找到关闭web-stat-filter的属性

**Comment by miemieYaho** [comment]
去 dynamic-datasource-spring-boot-starter 那边提
