### ISSUE TITLE
BaseMapper的updateById，不能对json字段自动转换

### ISSUE THREAD

**Issue by swxu2005** [baomidou/mybatis-plus#958]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
MySQL表中的json字段，Java实体类中用Map<String, Object>，并定义了自定义typeHandler。调用BaseMapper的insert方法，能自动调用自定义typeHandler成功转成字符串。但调用updateById方法无法调用自定义typeHandler。

### 重现步骤
实体类：
`public class TemplateEntity {
	
	private Long id;
	
	private String name;
	
	private Map<String,Object> value;

    private Long updater;
	
	private Date updateDate;
}`

自定义typeHandler：
`@MappedTypes({Object.class, Map.class})
@MappedJdbcTypes(JdbcType.VARCHAR)
public class JsonTypeHandler<T> extends BaseTypeHandler<Map<String, T>> {
  private static final ObjectMapper mapper = new ObjectMapper();
  private Class<T> clazz;

  public JsonTypeHandler(Class<T> clazz) {
    if (clazz == null) {
      throw new IllegalArgumentException("Type argument cannot be null");
    }
    this.clazz = clazz;
  }

  @Override
  public void setNonNullParameter(PreparedStatement ps, int i, Map<String, T> parameter, JdbcType jdbcType) throws SQLException {
    ps.setString(i, this.toJson(parameter));
  }

  @Override
  public Map<String, T> getNullableResult(ResultSet rs, String columnName) throws SQLException {
    return this.toObject(rs.getString(columnName), clazz);
  }

  @Override
  public Map<String, T> getNullableResult(ResultSet rs, int columnIndex) throws SQLException {
    return this.toObject(rs.getString(columnIndex), clazz);
  }

  @Override
  public Map<String, T> getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {
    return this.toObject(cs.getString(columnIndex), clazz);
  }

  private String toJson(Map<String, T> object) {
    try {
      return mapper.writeValueAsString(object);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  private Map<String, T> toObject(String content, Class<?> clazz) {
    if (content != null && !content.isEmpty()) {
      try {
        return (Map<String, T>) mapper.readValue(content, clazz);
      } catch (Exception e) {
        throw new RuntimeException(e);
      }
    } else {
      return null;
    }
  }

  static {
    mapper.configure(JsonParser.Feature.ALLOW_MISSING_VALUES, false);
    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
  }
}
`
### 报错信息
调用BaseMapper的updateById方法时，调试到MybatisDefaultParameterHandler类的setParameters方法时，情况是这样的：
![bug1](https://user-images.githubusercontent.com/18298380/54867388-a5a7bc80-4dba-11e9-870c-d6bf34613606.png)
估计因为updateById方法的参数带有@Param注解，所有输入参数被处理成"et."打头的，而且javaType都丢失了，导致获得的typeHandler是UnknownTypeHandler。最终更新失败，报错：
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'.

而调用BaseMapper的insert方法时，情况是这样的：
![bug2](https://user-images.githubusercontent.com/18298380/54867457-5f9f2880-4dbb-11e9-9846-5354b5e53c6f.png)
可以看到所有参数的类型都是正确的，而且获得的是正确的typeHandler

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/794
