### ISSUE TITLE
service层使用默认update更新问题

### ISSUE THREAD

**Issue by daai** [baomidou/mybatis-plus#961]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
update操作

### 重现步骤

updateTime数据库字段为 `update_time` varchar(17)，service层使用默认updateById更新，出错。why 字符串自动转日期类型？

### 报错信息

updateTime' of **** with value 'Mon Mar 25 15:07:43 CST 2019

**Comment by miemieYaho** [comment]
数据库操作都是 mybatis 的事,自己检查
