### ISSUE TITLE
使用left join关联查询集合时出现size=1，元素为null

### ISSUE THREAD

**Issue by Burt-L** [baomidou/mybatis-plus#962]
### 当前使用版本

mybatis-plus-boot-starter:3.0.6

### 该问题是怎么引起的？

使用left join关联表查询

### 重现步骤

`
List<SysServiceDAO> serviceDAOs = sysClientServiceMapper.findServicesByClientNames(clientNames);

<select id="findServicesByClientNames" resultType="com.test.oauth.dataobject.SysServiceDAO">
	SELECT
            s.id,
            s.parentId,
            s.`name`,
            s.url,
            s.path,
            s.isMenu
        FROM
            oauth_client_details AS ocd
        LEFT JOIN sys_client_service AS cs ON ocd.id = cs.clientId
	LEFT JOIN sys_service AS s ON cs.serviceId = s.id
        WHERE
            ocd.client_id
        IN
            <foreach collection="clientNames" index="index" item="clientName"
                     open="(" separator="," close=")">
                #{clientName}
            </foreach>
	</select>
`

### 报错信息

当查询无符合条件的数据时 serviceDAOs的size为1，且对象中所有字段为null，将left join改为inner join时serviceDAOs为null。业务上使用left join。期望使用left join时serviceDAOs为null，而非size=1，集合元素为null。

**Comment by Burt-L** [comment]
copy过来的foreach标签被吃掉了。。。

**Comment by miemieYaho** [comment]
数据封装是mybatis的事,我们没有作改动,自行检查
