### ISSUE TITLE
Howto Add custom resultmap to default mapper

### ISSUE THREAD

**Issue by nmwael** [baomidou/mybatis-plus#964]
Hi, thanks for this cool addon to mybatis:)

How can I add a custom resultmap to my mybatis plus mappers like this example:

https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/base/mapper/commons/ResultMapEntityMapper.java

I cannot get Mybatis plus to pickup the ResultMapEntityMapper.xml file.. I can see that MybatisConfiguration has an addResultMap but that takes an Result map class

**Comment by miemieYaho** [comment]
like this [ResultMapEntity](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/base/entity/ResultMapEntity.java)
```java
@TableName(resultMap = "resultChildren1")
public class ResultMapEntity {
    ......
}
```
and [xml](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/resources/mapper/ResultMapEntityMapper.xml)
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="com.baomidou.mybatisplus.test.base.mapper.commons.ResultMapEntityMapper">
    <resultMap id="baseResult" type="com.baomidou.mybatisplus.test.base.entity.ResultMapEntity">
        ......
    </resultMap>
    <resultMap id="resultChildren1" type="com.baomidou.mybatisplus.test.base.entity.ResultMapEntity"
               extends="baseResult">
        ......
    </resultMap>
</mapper>
```

Is this what you want?

**Comment by nmwael** [comment]
That was exactly what I wanted! Thanks.. 

Are there a forum/mailing list for mybatis plus? And are there a reason why there is no english translation of the guide?

**Comment by nmwael** [comment]
Somehow mybatisplus translates my java field FK_parentCalendar to this in SQL f_k_parent_calendar AS FK_parentCalendar.. How can I configure it not to do so?

**Comment by miemieYaho** [comment]
document for English is not ready.
we change the mybatis default property of `mapUnderscoreToCamelCase` to be `true`
if you don't want it,you can change it
if you use spring-boot , you can do this:
```yml
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
```

[this is our document for China](https://mybatis.plus/config/#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE)
maybe you can use google translation try to read it

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus-samples
it's samples for this project

**Comment by nmwael** [comment]
Yes, I've been both reading chinese documentation and looking at samples:) I would be happy to help translating to english document if you want it. MybatisPlus are an very cool addon for Mybatis and should have a much larger western user base..

**Comment by yuxiaobin** [comment]
> Somehow mybatisplus translates my java field FK_parentCalendar to this in SQL f_k_parent_calendar AS FK_parentCalendar.. How can I configure it not to do so?

Recommend to add annotation: @TableField("FK_PARENT_CALENDAR") for your java field, as Camelcase is suggested and mybatisplus will translate Camelcase to underscore SQL field by default.

**Comment by wangzhkai** [comment]
@nmwael you can read chinese documention?????

**Comment by nmwael** [comment]
@yuxiaobin did something like it, but in this case we have 100% control over the database and it's easier with
`mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false`
as @miemieYaho suggested :)

@wangzhkai google translate does an okay job, and since I already know mybatis, I can piece together what are lost in translation..

BTW at our company MybatisPlus are doing 95% of boilerplate for us, and are letting us concentrate on the business logic. While remaining able to control every knob in the cockpit.. Combining MybatisPlus with Apache Wicket  & Spring stack (spring boot+spring boot admin etc) looks like are really solid stack! 💯

**Comment by yangyang0507** [comment]
This is our doc repo: https://github.com/baomidou/mybatis-plus-doc

This document use VuePress(https://vuepress.vuejs.org/) to generate site.  

We have already started to write English documents. If you can help us improve English documents, we will be very grateful for you help!

We are very excited and honored that international friends can like our project(just like you). thank you again for your attention.

**Comment by nmwael** [comment]
@yangyang0507 I will give it a look later today..

**Comment by yangyang0507** [comment]
@nmwael We already added the outline of English documents.
- Site: https://mybatis.plus/en/
- Source: https://github.com/baomidou/mybatis-plus-doc/tree/master/en
We will write English documents as soon as possible😊

**Comment by qmdx** [comment]
closed, if there are other problems, create a new issue
