### ISSUE TITLE
有脱离spring单独使用的案例吗

### ISSUE THREAD

**Issue by Croyson** [baomidou/mybatis-plus#965]
有脱离spring单独使用的案例吗

**Comment by miemieYaho** [comment]
srping 无非就是帮你托管了bean,照着https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java这个类抄一份自己创建SqlSessionFactory

**Comment by Croyson** [comment]
那怎么从使用mybatisplus  获取的那些mapper

**Comment by miemieYaho** [comment]
https://github.com/mybatis/mybatis-3/blob/master/src/test/java/org/apache/ibatis/binding/BindingTest.java
注意把 `SqlSessionFactoryBuilder` 替换成 `MybatisSqlSessionFactoryBuilder` 和 `Configuration` 替换成 `MybatisConfiguration` ,其他的该怎么用怎么用

**Comment by Croyson** [comment]
单独使用的话，事物怎么管理
 (T) Proxy.newProxyInstance(mapperInterface.getClassLoader(), new Class[]{mapperInterface}, mapperProxy)  我跟到这个代码，发现当前 Connection 中的事物换了一个，这个需要怎么配置一下，才能使用Connection自带的事物呢

**Comment by miemieYaho** [comment]
百度去

**Comment by Croyson** [comment]
求指教啊， 我们项目中部分代码用jdbc 直接连的数据库，打算慢慢迁移成mybatisplus,现在遇到一个问题，事务没提交前 jdbc中插入的数据，jdbc能读取出来，但是用mybatis 读取不到，创建mapper的时候用的是同一个链接。

  inputStream = Resources.getResourceAsStream("mybatis/mappers/mappings.xml");
               TransactionFactory transactionFactory = new ManagedTransactionFactory();
               Environment environment = new Environment("default", transactionFactory, dataSource);
                Reader reader = new InputStreamReader(inputStream);
                Properties properties = new Properties();

                MybatisXMLConfigBuilder parser = new MybatisXMLConfigBuilder(reader, "default", properties);
                MybatisConfiguration configuration = (MybatisConfiguration) parser.getConfiguration();
                configuration.setEnvironment(environment);
                 configuration = (MybatisConfiguration) parser.parse();

                //分页插件
                PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
                configuration.addInterceptor(paginationInterceptor);

                //乐观锁插件
                OptimisticLockerInterceptor optimisticLockerInterceptor = new OptimisticLockerInterceptor();
                configuration.addInterceptor(optimisticLockerInterceptor);

                // 部分数据库不识别默认的NULL类型（比如oracle，需要配置该属性
                configuration.setJdbcTypeForNull(JdbcType.NULL);

                this.dataSource = dataSource;
                sqlSessionFactory = new MybatisSessionFactoryBuilder().build(configuration);





    public SqlSession getSqlSession() {
        SqlSession sqlSession;
        if (sqlSessionFactory == null) {
            throw new FixFlowDalException("mybatis sqlsession工厂创建失败");
        }
        Connection connection = DataSourceUtils.getConnection(dataSource);
        try{
            if(!connection.isClosed()){
           
                sqlSession = sqlSessionFactory.openSession(ExecutorType.REUSE,connection);
            }else{
                sqlSession = sqlSessionFactory.openSession();
            }

            if (sqlSession == null) {
                throw new FixFlowDalException("mybatis sqlSession创建失败");
            }
        }catch (Exception e){
            throw new FixFlowDalException("mybatis sqlSession创建失败");
        }

        return sqlSession;
    }
 BaseMapper mapper = sqlSessionFactory.getSqlSession().getMapper(this.mapper);
            Constructor<? extends Session> c1 = managerImplementation.getDeclaredConstructor(new Class[]{this.mapper});
            c1.setAccessible(true);
            return c1.newInstance(mapper);

**Comment by anuxs** [comment]
https://www.jianshu.com/p/042567d0b5a2

我也在找单独使用的方法，找到了这片文章：https://www.jianshu.com/p/042567d0b5a2。试过了可以。

`    public static void main(String[] args) throws Exception {
        //获取配置文件的输入流
        InputStream inputStream = Resources.getResourceAsStream("mybatis.cfg.xml");
        
        MybatisSessionFactoryBuilder mybatisSessionFactoryBuilder = new MybatisSessionFactoryBuilder();
        
        //通过配置文件获取session工厂
        SqlSessionFactory sessionFactory = mybatisSessionFactoryBuilder.build(inputStream);
        
        //获取一个session会话
        SqlSession session = sessionFactory.openSession();
        
        UserMapper mapper = session.getMapper(UserMapper.class);
        
        User user = mapper.selectById(1);
        
        System.out.println(user);
    }`

**Comment by joeaniu** [comment]
所谓的无侵入。。 连一个无spring的教程都没有。  依赖中还写死了依赖spring。不加spring的jar估计都跑不起来吧！
https://lubojian.cn/post/165.html 这篇说"此时运行可能会包没有类发现的错误springframework的错误，只需要再pom文件中添加上springframework的引用就好了"

**Comment by joeaniu** [comment]
作者能否给一个对spring依赖之处的清单吗？ 除了GenericTypeResolver，还有什么别的？这样写清楚比较好，让使用者判断是否值得采用。
