### ISSUE TITLE
getById返回null

### ISSUE THREAD

**Issue by lzdbh** [baomidou/mybatis-plus#967]
### 当前使用版本
3.1.0
springboot2.1.3

### 该问题是怎么引起的？
getById 返回null

#### 表sql语句
``` sql
CREATE TABLE `wx_mp_user` (
	`openid` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`openid`)
)
```
#### 代码器生成的实体、mapper、service
``` java
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class WxMpUser extends Model<WxMpUser> {

    private static final long serialVersionUID = 1L;

    private String openid;

    @Override
    protected Serializable pkVal() {
        return this.openid;
    }
}

public interface WxMpUserMapper extends BaseMapper<WxMpUser> {

}

public interface IWxMpUserService extends IService<WxMpUser> {

}

@Service
public class WxMpUserServiceImpl extends ServiceImpl<WxMpUserMapper, WxMpUser> implements IWxMpUserService {

}
```
#### 生成的xml
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.mybatis.mapper.WxMpUserMapper">

    <!-- 通用查询映射结果 -->
    <resultMap id="BaseResultMap" type="com.mybatis.entity.WxMpUser">
        <id column="openid" property="openid" />
    </resultMap>

</mapper>
```

#### 调用代码
``` java
 WxMpUser wxMpUser=wxMpUserService.getById(wxMessage.getFromUser());
```

### 报错信息
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@27738799] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@1524794256 wrapping com.mysql.cj.jdbc.ConnectionImpl@bd9cb9d] will not be managed by Spring
==> **Preparing: SELECT openid FROM wx_mp_user WHERE null=?** 
==> Parameters: okZBN1DyCtGOWHPOcH3nZhg6gpaU(String)
<==      Total: 0
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@27738799]

**Comment by miemieYaho** [comment]
注解`@TableId` ,去看文档

**Comment by lzdbh** [comment]
这个注释能不能在生成代码的时候自动给生成了？

**Comment by lzdbh** [comment]
> 
> 
> 注解`@TableId` ,去看文档

这个注解能否在生成代码实体代码的时候给自动加上？
