### ISSUE TITLE
逻辑删除遇上通用枚举String泛型

### ISSUE THREAD

**Issue by jsyzthz** [baomidou/mybatis-plus#972]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

同时使用通用枚举和逻辑删除，且通用枚举继承的泛型是String类型

### 重现步骤
1.在application.yml配置如下（只是截取关键，顾忽略缩进）：
```
      logic-not-delete-value: N
      logic-delete-value: Y
      type-enums-package: com.xxxx.*.enums
```
2.定义枚举
```
public enum YesNo implements IEnum<String> {
	YES("Y"), NO("N");
	YesNo(String value) {
		this.value = value;
	}
	private String value;
	@Override
	public String getValue() {
		return this.value;
	}
}
```
3.注册逻辑删除和应用
```
@Configuration
public class MyBatisPlusConfiguration {
	@Bean
    public ISqlInjector sqlInjector() {
        return new LogicSqlInjector();
    }
}

```
```
	/**
	 * 逻辑删除
	 */
	@TableLogic
	private YesNo deleted;
```

这时候后面执行查询所有list()方法，就会发现SQL语句貌似把YesNo当做整形来处理没有加引号，同样如果把逻辑删除改成String 也没有任何错误，一切正常。

### 报错信息
Execute SQL：SELECT id,username,age,phone,deleted,create_time,update_time FROM t_user WHERE deleted=Y
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'Y' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'Y' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)

**Comment by miemieYaho** [comment]
不要一起使用,不支持

**Comment by qmdx** [comment]
逻辑删除字段简单 0 1 表示就好了别搞得这么复杂
