### ISSUE TITLE
在XML中覆盖BaseMapper中的方法，启动时得到错误提示

### ISSUE THREAD

**Issue by FisherYu-CN** [baomidou/mybatis-plus#973]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在Mapper的XML中尝试覆盖像insert这类在BaseMapper里有的方法，提供了自定义SQL，在启动程序时会得到类似如下的提示：

{com.test.dao.UserMapper.insert} Has been loaded by XML or SqlProvider, ignoring the injection of the SQL.

虽然并不影响启动，且程序也会以XML中的行为为准，但是启动时看着这个错误信息很难受啊。这个信息为何是以System.err的形式输出？是不鼓励覆盖框架自带CRUD方法这样的行为吗？能否改为以其他方式进行输出，比如日志?

顺便提一下，我覆盖insert方法的原因是，我的程序需要在mysql和oracle两种数据库上运行，因为历史原因，在mysql上插入数据时，主键是自增的，相应地，在oracle上插入数据时，主键需要使用sequence生成来保证行为一致。目前，我无法使用一种@TableId的type来同时满足上面两种情况，使得程序在不同数据库运行时只需要修改配置不需要动entity的代码。因此我自定义了insert的SQL来实现不同的行为（是否有更好的方式）。

### 重现步骤

在Mapper.xml中为BaseMapper中的方法重新定义SQL后，在启动时报出以上信息

### 报错信息

{com.test.dao.UserMapper.insert} Has been loaded by XML or SqlProvider, ignoring the injection of the SQL.

**Comment by qmdx** [comment]
这不是错误这是警告提示，你忽略即可故意打印的
