### ISSUE TITLE
分页生成两个LIMIT，导致sql异常

### ISSUE THREAD

**Issue by GreatGarlic** [baomidou/mybatis-plus#974]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
常规单表查询：
  Page<ComponentInfo> page;
        if (pageNum == null || pageSize == null) {
            page = new Page<>(1, 20);
        } else {
            page = new Page<>(pageNum, pageSize);
        }
        return new ResponseModel<>(HttpStatus.Series.SUCCESSFUL,componentDao.selectPage(page, null));

### 报错信息
SELECT  id,name,tag,description,create_time,update_time  FROM component_info LIMIT ?,? LIMIT ?,?；
check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0,2' at line 1

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by qmdx** [comment]
1、分页插件是否配置 2次，或者使用第三方页面插件一起使用
2、sql 中使用了 limit

**Comment by GreatGarlic** [comment]
@qmdx 没有写sql，就是最普通的jpa模式

**Comment by GreatGarlic** [comment]
@qmdx OK，发现问题，xml里配置了，代码里也配置了，删掉一个即可，感谢
