### ISSUE TITLE
自定义SQL无法使用自动填充功能

### ISSUE THREAD

**Issue by Bryce-huang** [baomidou/mybatis-plus#975]
### 当前使用版本(必须填写清楚，否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <version>3.1.0</version>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

想问下现在的自定义sql，无法使用MP的自动填充功能吗？

### 重现步骤
 
 自己写的xml sql 没有自动填充的功能

### 报错信息
 自定义sql 没有自动注入的数据

**Comment by miemieYaho** [comment]
1. 只支持单个入参,而且入参必须是entity

**Comment by changyu3590** [comment]
只支持单个入参,而且入参必须是entity或者List集合,如果是集合必须内部元素是entity
-------------------------------------------------------------------------------------------------------
我就是这样试的，也是有问题，
