### ISSUE TITLE
count返回0，实际list有数据，数据库直接count也有数据

### ISSUE THREAD

**Issue by lydon18** [baomidou/mybatis-plus#976]
### 当前使用版本(必须填写清楚，否则不予处理)
版本号 2.1.9

这个问题说起来有点怪异，直接拷贝控制台中拼接好的count语句放在MySQL中是不为0，但是代码中返回的是0；
![TIM截图20190401112138](https://user-images.githubusercontent.com/13651761/55301910-86232a80-5471-11e9-85f7-a90b15816652.png)

### 重现步骤
比较尴尬的是这个我也不知道怎么重现

### 报错信息
无报错信息

**Comment by qmdx** [comment]
已查询 sql 为准
