### ISSUE TITLE
order表，执行orderService.save(entity)时报错

### ISSUE THREAD

**Issue by pompeii666** [baomidou/mybatis-plus#978]
### 报错信息是，sql语法错误
       INSERT INTO order ( id,user_id) VALUES ("111",2)
       因为order关键词，应该是INSERT INTO `order` ( id,user_id) VALUES ("111",2)

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/655

**Comment by pompeii666** [comment]
> #655

thx
