### ISSUE TITLE
增加注解@Repository解决idea的ServiceImpl 注入显示错误问题

### ISSUE THREAD

**Issue by imic07** [baomidou/mybatis-plus#982]
### 当前使用版本(必须填写清楚，否则不予处理)
最新版生成器。

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
dao层没有添加@Repository注解，导致service实现类上使用@Autowired时报错

### 报错信息
![image](https://user-images.githubusercontent.com/16321067/55381559-0622c080-5556-11e9-9e9a-1c069617768e.png)

### 解决办法
mapper.java.ftl模板中添加注解
![image](https://user-images.githubusercontent.com/16321067/55381650-366a5f00-5556-11e9-9f82-a4dd4680906b.png)
效果如下：
![image](https://user-images.githubusercontent.com/16321067/55381679-441fe480-5556-11e9-8d4a-f332e3e458ce.png)

**Comment by miemieYaho** [comment]
不需要,你觉得爆红不好看就用 `@Resource`

**Comment by qmdx** [comment]
或者自定义模板，参考文档
