### ISSUE TITLE
字段添加@TableField(strategy = FieldStrategy.IGNORE)在updateWrapper更新其他字段时会将当前字段设置为null

### ISSUE THREAD

**Issue by qingzhou413** [baomidou/mybatis-plus#985]
### 当前使用版本  
3.0.7.1

### 该问题是怎么引起的？
实体类设置：
@TableField(strategy = FieldStrategy.IGNORED)
private Long boundAlarmSettingId;

update执行：
 Goods.INSTANCE.update(Wrappers.<Goods>update().set("high_freq_position_id", area.getId()).set("high_freq_position", area.getName())
                            .eq("id", good.getId()));

日志中sql打印：
UPDATE goods SET bound_alarm_setting_id = ? , high_freq_position_id=?, high_freq_position=? where id=?
参数： null , 76, test, 12

**Comment by miemieYaho** [comment]
就是这样的
