### ISSUE TITLE
service.remove()  方法永遠返回true

### ISSUE THREAD

**Issue by jackpanz** [baomidou/mybatis-plus#986]
### 当前使用版本
v3.1.0

### 该问题是怎么引起的？
service.remove()
方法永遠返回true
刪除的邏輯跟更新的邏輯不是一樣的嗎
為什麼
service.update 可以返回true false
service.remove 只能返回true

**Comment by miemieYaho** [comment]
都是调用 mapper 方法,该返回什么就是什么,不存在只有 true
