### ISSUE TITLE
v3.1.0 建議加上全更新字段方法

### ISSUE THREAD

**Issue by jackpanz** [baomidou/mybatis-plus#987]
### 当前使用版本
v3.1.0

### 该问题是怎么引起的？
建議加上全更新字段方法

**Comment by miemieYaho** [comment]
会考虑一下

**Comment by qmdx** [comment]
打开下次发布版本关掉

**Comment by jorrycai** [comment]
感觉目前的机制不够灵活, 虽然有FieldFill.  个人还是习惯Mybatis Generator的insertSelective /insert ,update/updateSelective 这种

**Comment by qmdx** [comment]
请关注下一个版本的发布 https://github.com/baomidou/mybatis-plus/commit/674886dce8b2fca0b638bba608d1d49e8b851201
