### ISSUE TITLE
SqlMethod中DELETE相关操作，会判断为Update的MappedStatement

### ISSUE THREAD

**Issue by gsh-go** [baomidou/mybatis-plus#989]
### 当前使用版本(必须填写清楚，否则不予处理)
V 3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

项目中添加拦截器，返回SqlCommandType时，发现DELETE的相关操作会判断为UPDATE操作。
查看源码发现如下问题：

相关的类 com.baomidou.mybatisplus.extension.injector.methods.LogicDelete 中的injectMappedStatement方法， 会判断是否为逻辑删除，但是无论是否逻辑删除，最终返回的都是addUpdateMappedStatement；正确的应该是物理删除返回addDeleteMappedStatement，逻辑删除返回addUpdateMappedStatement吧？

public class LogicDelete extends AbstractLogicMethod {

    @Override
    public MappedStatement injectMappedStatement(Class<?> mapperClass, Class<?> modelClass, TableInfo tableInfo) {
        String sql;
        SqlMethod sqlMethod = SqlMethod.LOGIC_DELETE;
        if (tableInfo.isLogicDelete()) {
            sql = String.format(sqlMethod.getSql(), tableInfo.getTableName(), sqlLogicSet(tableInfo),
                sqlWhereEntityWrapper(true, tableInfo));
        } else {
            sqlMethod = SqlMethod.DELETE;
            sql = String.format(sqlMethod.getSql(), tableInfo.getTableName(),
                sqlWhereEntityWrapper(true, tableInfo));
        }
        SqlSource sqlSource = languageDriver.createSqlSource(configuration, sql, modelClass);
        return addUpdateMappedStatement(mapperClass, modelClass, sqlMethod.getMethod(), sqlSource);
    }
}

LogicDeleteBatchByIds、LogicDeleteById、LogicDeleteByMap同样存在相同的问题

### 报错信息

The error occurred while executing an update
Cause: java.lang.ClassCastException: net.sf.jsqlparser.statement.delete.Delete cannot be cast to net.sf.jsqlparser.statement.update.Update

**Comment by miemieYaho** [comment]
ok, 下个版本修复

**Comment by qmdx** [comment]
关注 3.1.1 + 发布

**Comment by hile1011** [comment]
升级了这个版本 好像对oracle11g不兼容了，现在有点陷入死循环了，有没有办法
