### ISSUE TITLE
使用spring异步功能@Async导致无法获取租户id

### ISSUE THREAD

**Issue by Bryce-huang** [baomidou/mybatis-plus#991]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

配置好租户功能，使用aop切面注入租户id，正常使用该功能，在某一块service方法，使用Spring@Async 异步处理，在异步方法内执行的sql无法获取租户id

### 重现步骤
1.配置租户功能并正常使用使用了aop注入租户id
2.在主类开启异步功能
3.调用异步方法
4.异步方法sql没有获取到租户ID

### 报错信息
sql无法获取当时的租户id

**Comment by miemieYaho** [comment]
这不归我们处理

**Comment by Bryce-huang** [comment]
可以考虑提供多线程功能增强

**Comment by miemieYaho** [comment]
租户ID是靠你自己获取的
