### ISSUE TITLE
ServiceImpl中分页方法，参数queryWrapper不生效

### ISSUE THREAD

**Issue by happydevelopers** [baomidou/mybatis-plus#992]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 重现步骤

/**
     * 翻页查询
     *
     * @param page         翻页对象
     * @param queryWrapper 实体对象封装操作类 {@link com.baomidou.mybatisplus.core.conditions.query.QueryWrapper}
     */
     @Override
    public IPage<T> page(IPage<T> page, Wrapper<T> queryWrapper) {
        return baseMapper.selectPage(page, queryWrapper);
    }

调用该方法后只分页，并不按照queryWrapper参数查询

**Comment by wangchaun** [comment]
怎么使用的？

**Comment by happydevelopers** [comment]
> 怎么使用的？

![image](https://user-images.githubusercontent.com/22808725/55536062-6c8d1780-56eb-11e9-80de-94777d02d85d.png)
@GetMapping("/page2")
	@ResponseBody
	public Object page2(Integer id) {
		QueryWrapper<User> queryWrapper = new QueryWrapper<User>();
		queryWrapper.gt(id!=null?true:false, "id", id);
		IPage<User> page = userService.page(new Page<User>(), queryWrapper);
		return page;
	}

**Comment by miemieYaho** [comment]
无法复现

**Comment by miemieYaho** [comment]
自行检查你的 id 是不是为 null
