### ISSUE TITLE
逻辑删除问题

### ISSUE THREAD

**Issue by wangchaun** [baomidou/mybatis-plus#993]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
开启逻辑删除、乐观锁插件。

逻辑删除生成的update语句并不会加上乐观锁。

### 报错信息
![image](https://user-images.githubusercontent.com/29708510/55534782-d277a000-56e7-11e9-9f67-a171b140606e.png)

**Comment by wangchaun** [comment]
另外，开启乐观锁之后，更新的时候不传递version字段也不会报错。

建议开启乐观锁之后，更新操作不传递version应该有报错提示。

**Comment by miemieYaho** [comment]
逻辑删除不需要 version,version 自己控制
