### ISSUE TITLE
怎么让自定义的插件在分页插件之前执行

### ISSUE THREAD

**Issue by zhidongluo** [baomidou/mybatis-plus#994]

**Comment by qmdx** [comment]
配置顺序在分页插件之前，如果是解析 sql 可以看下分页插件提供了 sql 解析器你可以切入

**Comment by zhidongluo** [comment]
> 配置顺序在分页插件之前，如果是解析 sql 可以看下分页插件提供了 sql 解析器你可以切入

![](https://s2.ax1x.com/2019/04/04/A2RC11.png)
我按照这个，但是打断点，却先进入了分页插件。
