### ISSUE TITLE
insert后无法获取主键

### ISSUE THREAD

**Issue by Stonewqw** [baomidou/mybatis-plus#998]
### 当前使用版本(必须填写清楚，否则不予处理)
2.3.3

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用mybatis-plus提供的service进行insert操作
![image](https://user-images.githubusercontent.com/13247724/55706900-ed625100-5a14-11e9-8cab-fd8a25b5c671.png)

### 重现步骤
![image](https://user-images.githubusercontent.com/13247724/55706942-04a13e80-5a15-11e9-8ab4-1c762cc2e4ed.png)
实体IdType已经是AUTO了
使用的是mp自带的insert方法
![image](https://user-images.githubusercontent.com/13247724/55706900-ed625100-5a14-11e9-8cab-fd8a25b5c671.png)
返回的结果如下：
![image](https://user-images.githubusercontent.com/13247724/55707080-55189c00-5a15-11e9-9420-a3d96319d221.png)

**Comment by qmdx** [comment]
auto 数据库要设置自增序列 百度解决

**Comment by Stonewqw** [comment]
数据库字段已经是自增序列了

**Comment by Stonewqw** [comment]
> auto 数据库要设置自增序列 百度解决

数据库字段已经是自增序列了

**Comment by qmdx** [comment]
> > auto 数据库要设置自增序列 百度解决
> 
> 数据库字段已经是自增序列了

https://search.maven.org/search?q=g:com.baomidou%20AND%20a:mybatis-plus&core=gav

2X 最高版本 2.3.1 请确定你的版本是否正确，如果是新项目建议使用 3X
